import json,pathlib,hashlib
R=pathlib.Path('/home/enpasos/projects/skillpilot');D=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-twelve-company-strategy-ethics-one-contract-local-root-author-v1';O=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-twelve-company-whole-science-independent-merge-audit-v1'
m=json.loads((D/'whole-twelve-company-strategy-ethics-one-contract-two-case-DEEN24-15.DRAFT-author-candidates-v1.json').read_text())[5];r=json.loads((D/'actual-root-whole-twelve-current577-contracts-originalP24-and-retained-whole-closure-intake.json').read_text())[5]
a=[
'Viele kleine Sonderaufträge ersetzen die stabile Großserie. Deshalb werden häufige Wechsel und umstellbare Rollen wichtig. Ein ausgebildetes Team kann flexibel wechseln, benötigt dafür die gegebenen Trainingstage. Für spätere große Standardaufträge kann die starre Linie weiterhin passen. Ich erörtere hier keine Qualität.',
'Zehn Wechsel dauern an der Linie 20 und im Team 5 Stunden; das spart 15 reine Umrüststunden. Vier Trainingstage sind Zusatzaufwand und mangels Tagesstunden/Wiederholung nicht von 15 abzuziehen. Verarbeitung, Personalkosten und Auslastung bleiben unbekannt, deshalb ist kein Gesamtstückkostenvorteil bewiesen. Zu Maßhaltigkeit oder Fehlern wird nichts untersucht.',
'Bei fortgesetzten kleinen Varianten und verfügbarer Schulung erprobe ich die Gruppenarbeit: Auftrag erfassen, Rollen abstimmen, Wechsel durchführen und Termin messen. Die Umrüstzeit und Termintreue werden vor und nach dem Versuch verglichen. Große Standardaufträge oder nicht verfügbare Schulung könnten die Wahl ändern. Qualität wird ausdrücklich nicht untersucht.',
'Die Automatisierung spart 5 variable Kosten je Stück, benötigt aber 5.000 zusätzliche fixe Jahreskosten. Bei 500 kosten manuell 5.500 und automatisch 8.000, also ist automatisch 2.500 teurer. Bei 1.200 stehen 11.800 und 10.800, automatisch spart 1.000. Derselbe technische Vorteil ist bei anderer Auslastung wirtschaftlich anders zu beurteilen.',
'1.000+9q=6.000+4q liefert q=1.000. Darüber ist automatisch billiger, darunter manuell. Verlässliche Nachfrage und Wartungs-/Qualifikationsfähigkeit sind Bedingungen. Bei weiteren kleinen Sondervarianten könnte die Umstellbarkeit begrenzen, ob die Automation einsetzbar ist. Eine Qualitätsanforderung, deren Folgen oder eine Qualitätsgrenze wird nicht beurteilt.',
'Bei verlässlichen 1.200 und vorhandener Wartungsfähigkeit würde ich die Automation, bei 500 die manuelle Fertigung wählen. Nach Einführung prüfe ich tatsächliche Mengen und Wartungsaufwand. Nachfragerückgang oder Wartungsprobleme können das Kostenurteil ändern. Qualitätsanspruch, Fehler und Maßhaltigkeit bleiben über die ganze Arbeit unbesprochen.'
]
marks=[[1,1,1,1],[1,1,0,1],[1,0,0,1],[1,1,1,1],[1,1,1,1],[1,0,0,1]]
# Conservative binary marks: no partial credit for A3 mixed quality/term criterion or B6 mixed quantity/quality criterion.
raw=sum(map(sum,marks));assert raw==19
p=O/'actual-whole-process19point-completely-absent-quality-dimension-counterwork-and-individual-REVISE.independent.json';assert not p.exists()
o={'reviewer':'/root/economics_merge_audit','wholeOriginalMaterial':m,'wholeCurrentContractAndP':r,'completeSixAnswerWork':a,'actualManual24CriterionMarks':marks,'actualRawScore':raw,'originalCapApplied':False,'actualOriginalResult':'PASS under reading that meaningful flexibility and its limits satisfy the combined quality/flexibility core in part','independentFinding':'REVISE: quality effects/requirements are completely absent throughout, while flexibility and its limit are meaningfully shown. Whole current P specifically requires quality alongside production, costs and flexibility. The combined field permits flexibility to mask wholly absent quality unless the individual essential dimension is protected.','boundedRemedy':'Separately protect wholly absent or throughout false quality assessment, preserving true partial quality performance anywhere, other text and the 24/15 rubric. No perfection or per-task quota.','gradingNotes':{'s1':'All four demand/flexibility/training/conditional ranking criteria evidenced.','s2':'Time, training and unknown total costs evidenced; quality measurement absent.','s3':'Trial and reversible standard-order/training change evidenced; mixed quality path and measurement criteria conservatively zero.','s4':'All four cost/quantity criteria evidenced.','s5':'Threshold, cost direction, operating conditions and case-specific flexibility limit evidenced, but no quality.','s6':'Conditional demand-based choice and its reversal evidenced; quality link and mixed follow-up criterion conservatively zero.'},'positiveUnderstandingNotRejected':'The flexibility response is meaningful partial performance, so it must not be mislabeled as wholly absent whole quality/flexibility field.'}
p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n');print(str(p.relative_to(R)),hashlib.sha256(p.read_bytes()).hexdigest(),raw)
