#!/usr/bin/env python3
"""Retain actual outputs and native dry-run routing for independent review, without install."""
from pathlib import Path
from PIL import Image
import datetime,hashlib,json,subprocess
OUT=Path(__file__).resolve().parent
ROOT=OUT.parents[5]
plan_path=OUT/'eleven-whole-current-goals-materials-source-prompt-native-preparation.author.raw.json'
plan=json.loads(plan_path.read_text())
def bind(p):
    data=p.read_bytes();return {'path':str(p.relative_to(ROOT)),'sha256':hashlib.sha256(data).hexdigest(),'bytes':len(data)}
def write(p,obj):
    p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
NOTES={
 '7874':('Primäre Sinneszelle mit eigenem Axon und sekundäre Sinneszelle mit Transmitterkontakt zu einer getrennten afferenten Nervenzelle. RP zeigt ein abgestuftes Rezeptorpotenzial, AP einen Aktionspotenzialpuls.','Gegebenes depolarisierendes Beispiel; negative Rezeptorpotenziale im zweiten ganzen Fall bleiben möglich. Die sekundäre Zelle hat kein eigenes gezeichnetes AP-Axon.'),
 '1975':('Modell einer neuronalen Aktivierung einer endokrinen Drüse. Hormon gelangt über das Blut zu Zielzellen; es bindet am passenden Rezeptor, am anders geformten Rezeptor passt es nicht.','Passender violetter Kontakt oben, deutlicher unterbrochener Bindungsweg mit X unten. Keine vollständige Hormonregelung oder universelle Organantwort.'),
 '3471':('Strukturelles Plastizitätsmodell: Zwei vorhandene Axon-Dendriten-Kontakte bleiben erhalten; nachher ist eine dritte Kontaktstelle hinzugekommen. Verschiedene Zellmembranen bleiben durch synaptische Spalte getrennt.','Ein neuer Kontakt; keine Behauptung einer größeren Einzelantwort, einer Hebb-Induktion oder einer ganzen Erinnerung. Die funktionelle Plastizität bleibt Bestandteil der ganzen Materialien.'),
 '485e':('Gegebenes Nervenzellnetz im intakten und gestörten Zustand. Eine unterbrochene Verbindung stoppt die gezeichnete Signalroute; der weiterhin vorhandene Kontakt hinter der Unterbrechung zeigt keine aktive Weitergabe.','Getrennte Zellen und sichtbare Kontaktspalte. Drei aktive Übergänge links, nur der erste rechts; downstream Kontakt strukturell erhalten, ohne Signalpfeil oder freigesetzte Partikel. Keine Diagnose.'),
 'afde':('Schematische fMRT-Illustration: Scanner, indirektes Blutsignal und eine qualitative Gehirnkarte zum Vergleich von Bedingungen. Die Farbkarte ist eine Modellzeichnung, kein gemessener Scan.','Blutoxygenierungsbezogene indirekte Darstellung; keine direkte Einzelneuronmessung, Gedankenlesung oder klinische Aussage.'),
 '2381':('Qualitative Potenzialmessung am Axon: Die innere Elektrode führt zum Plus-Eingang, die äußere Bezugselektrode zum Minus-Eingang. Das Messgerät bildet innen minus außen ab; die Modellkurve zeigt negative Ausgangslage und einen AP-Ausschlag.','Elektrodenspitzen tatsächlich innen/außen, getrennte Kabel. Qualitative Achsen ohne Zahlen, Einheiten oder Behauptung eines durchgeführten Versuchs.'),
 '97b2':('Gegebenes konvergentes Schaltbild: Die erregenden Eingänge E1 und E2 sowie der hemmende Eingang H treffen an getrennten Synapsen auf Z. Plus und Minus kennzeichnen ihre Potenzialwirkungen.','Erregend/hemmend funktionell identifiziert; keine Aussage, dass hemmende Axone negative APs leiten oder alle Netze so aufgebaut sind. Zahlen-/Transferleistung liegt in den ganzen Fällen.'),
 '9b96':('Gegebenes Serotonin-Synapsenmodell ohne und mit Rückaufnahmehemmer. Der Hemmer blockiert den Transport zurück in die sendende Endigung; im Modell bleibt mehr Serotonin im Spalt verfügbar, die empfangenden Rezeptoren bleiben zugänglich.','Sender/Empfänger/zurück große kurze Hinweise. Keine Serotoninerzeugung, Rezeptorblockade, universelle Depressionsursache, Diagnose oder Therapieempfehlung.'),
 '8b23':('Gegebenes Druckrezeptormodell: Kanalöffnung führt zu einem Netto-Einstrom positiver Ionen, einem abgestuften Rezeptorpotenzial RP und einer AP-Folge. Stärkerer Druck zeigt ein größeres RP und sechs statt drei gleich hohe AP-Pulse in derselben Modellzeitspanne.','Generische Kationen, keine erfundene spezifische Na-/K-Flussregel. Drei versus sechs qualitative Pulse mit gleicher Einzelhöhe; keine Messdaten oder vollständige Reizdauer-/Blockadeleistung.'),
 'c05e':('Vereinfachter Cortisol-Regelkreis: Stress wirkt auf den Hypothalamus, die Vorwärtsroute führt über Hypophyse und Nebennierenrinde zur Cortisolfreisetzung. Cortisol hemmt die zwei vorgelagerten Stationen in der gezeichneten Rückkopplung.','Hemmende T-Enden an beiden Stationen. Ein HPA-Beispiel, kein vollständiger gekoppelter Insulinkreis und kein klinischer Verlauf chronischen Stresses.'),
 '080b':('Zwei ausdrücklich zugeordnete synthetische Leitungsmodelle: A eines Wirbellosen ohne Myelin und B eines Wirbeltieres mit Myelin. Lokale Ströme verlaufen im Axon; AP-Regeneration liegt im Modell B an den Knoten.','Die Tiergruppen gelten nur für die gegebenen Modelle. Der zuvor zu dünne B-Innenraum ist korrigiert und schematisch vergleichbar zu A; keine pixelgenaue Morphometriemessung. Keine allgemeine Tiergruppen-, Myelin-, Geschwindigkeits- oder Intelligenzregel; alle berechneten und frischen Durchmesserfälle bleiben vollständig im gebundenen v4-Material.')
}
canonical=ROOT/plan['stage02Canonical']['path'];before=hashlib.sha256(canonical.read_bytes()).hexdigest();records=[]
for item in plan['plans']:
    gid=item['goalId'];prefix=next(k for k in NOTES if gid.startswith(k))
    attempt='03' if prefix in ['485e','8b23'] else '02' if prefix in ['1975','9b96','080b'] else '01'
    asset=OUT/'generated-originals'/gid/('original-generated-attempt-'+attempt+'.png')
    meta=asset.parent/('builtin-generator-attempt-'+attempt+'.actual.metadata.json')
    prompt=OUT/'prompts'/(gid+('.attempt-'+attempt if attempt!='01' else '')+'.prompt.txt')
    alt,note=NOTES[prefix];folder=OUT/'native-import-dry-run'/gid;folder.mkdir(parents=True,exist_ok=True)
    args=['npm','--prefix','app','run','visualization:import','--',gid,str(asset),'--landscape='+plan['stage02Canonical']['path'],'--subject=biologie','--lang=de','--provider=OpenAI / ChatGPT-Codex image generation','--review-status=pilot','--license=CC-BY-4.0','--prompt='+str(prompt),'--alt-text='+alt,'--description=Modellhafte Illustration: '+item['wholeStage02CandidateGoal']['title']+'.','--dry-run']
    start=datetime.datetime.now(datetime.timezone.utc).isoformat();result=subprocess.run(args,cwd=ROOT,capture_output=True,text=True);finish=datetime.datetime.now(datetime.timezone.utc).isoformat()
    stdout=folder/'native-import-dry-run.actual.stdout.txt';stderr=folder/'native-import-dry-run.actual.stderr.txt';stdout.write_text(result.stdout);stderr.write_text(result.stderr)
    assert result.returncode==0 and 'No files were written.' in result.stdout
    routing={}
    for line in result.stdout.splitlines():
        if ': ' in line and line.split(': ',1)[0] in ['Canonical image','Public image','Backend image','Canonical prompt','Canonical reconstruction prompt','JSON link URL']:
            key,value=line.split(': ',1);routing[key]=value
    assert len(routing)==6
    records.append({'goalId':gid,'role':'image author candidate, no independent V','wholeStage02CandidateGoal':item['wholeStage02CandidateGoal'],'completeCurrentDEENReferenceCases':item['completeCurrentDEENReferenceCases'],'actualFrozenSourceWitnessEffectiveBindings':item['actualFrozenSourceWitnessEffectiveBindings'],'updated080bWholeMaterials':item['updated080bWholeMaterials'],'selectedUnchangedOriginalAsset':bind(asset),'actualPixelDimensions':list(Image.open(asset).size),'actualFinalGeneratorMetadata':bind(meta),'actualFinalGenerationPrompt':bind(prompt),'actualAllGenerationHistory':[bind(p) for p in sorted(asset.parent.glob('builtin-generator*.metadata.json'))],'allOriginalAttempts':[bind(p) for p in sorted(asset.parent.glob('original-generated*.png'))],'selectedAttempt':attempt,'actualProvider':'OpenAI / ChatGPT-Codex image generation','actualTool':'ChatGPT/Codex builtin image generation','actualModelVersion':None,'modelVersionDisclosure':'not exposed; unknown','license':'CC-BY-4.0','boundedImageAltTextDe':alt,'ownAuthorSightNoteDe':note,'ownAuthorSightFullSizeAndBothActualWidths':True,'actualDisplayWidths':[360,680],'actualDisplays':[bind(OUT/'author-displays/final'/(gid+'.'+str(w)+'.png')) for w in [360,680]],'boundedModelNotWholeGoalPerformance':True,'nativePrepareBeforeAllAttempts':True,'nativePrepareMetadata':bind(OUT/'native-prepare-before-generation'/gid/'metadata.json'),'nativeImportDryRun':{'argv':args,'cwd':str(ROOT),'startedAt':start,'finishedAt':finish,'exitCode':result.returncode,'stdout':bind(stdout),'stderr':bind(stderr),'routingProducedByUnmodifiedNativeImport':routing},'authorDisposition':'candidate_ready_for_two_independent_visual_reviews','independentVisualApproval':False,'humanApproval':False,'newStrictCompletion':0})
after=hashlib.sha256(canonical.read_bytes()).hexdigest();assert before==after==plan['stage02Canonical']['sha256']
count=sum(len(r['actualAllGenerationHistory']) for r in records);assert count==18
write(OUT/'eleven-whole-goal-current-material-source-original-raster-native-routing.author.raw.json',{'role':'eleven image author candidates; no independent V, scientific approval or operative installation','nativePreparedWholePlan':bind(plan_path),'frozenStage02WholeNativeRaw':plan['stage02WholeNativeRaw'],'frozenStage02Canonical':plan['stage02Canonical'],'current080bWholeTwoCaseRaw':plan['current080bWholeTwoCaseRaw'],'actualDisplayReceipt':bind(OUT/'author-displays/final/actual-360-680-display.receipt.json'),'productionImportHelper':bind(ROOT/'scripts/import_goal_visualization.mjs'),'productionCommonHelper':bind(ROOT/'scripts/goal_visualization_common.mjs'),'actualBuiltinCalls':count,'nativePrepareBeforeEveryGeneration':True,'sixGoodFirstOutputsPreserved':True,'fiveTargetedCorrectedImages':True,'allOriginalAttemptsPreserved':True,'nativeImportDryRunExit0':11,'candidateCanonicalBeforeSha256':before,'candidateCanonicalAfterSha256':after,'wholeGoalTextAndMaterialsUnmodified':True,'threeRootModelImagesExcluded':plan['threeRootModelImagesExcluded'],'records':records,'activeWrites':False,'runtimeWrites':False,'operativeInstallCopiesWritten':0,'nativeResourceLinksWereNotHandBuilt':True,'independentVisualApproval':False,'humanApproval':False,'newStrictCompletion':0,'allOriginalSourceAndNationalScopeHoldsPreserved':True})
print(json.dumps({'authorCandidates':len(records),'actualBuiltinCalls':count,'nativeImportDryRunExit0':11,'canonicalUnchanged':before==after,'independentV':False,'strictCompletion':0}))
