from pathlib import Path
import json,hashlib,datetime,os,subprocess,time
R=Path('/home/enpasos/projects/skillpilot');B=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-current336-D124-thirteen-concrete-native-configs-inert-a-v1/native/current336-D124-batch-01';A=B/'round-a';W=A/'actual-own-page-and-visual-reading'
def digest(raw):return 'sha256:'+hashlib.sha256(raw).hexdigest()
def bound(p):return {'path':str(p.relative_to(R)),'sha256':digest(p.read_bytes()),'bytes':p.stat().st_size}
def write(p,j):
 assert not p.exists();p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n');return bound(p)
campaign=json.loads((A/'description-review-campaign.json').read_text());batch=campaign['batches'][0];bundle=json.loads((A/'review-bundle-manifest.json').read_text());batchfile=A/'batches'/(batch['batchId']+'.input.jsonl');lines=[json.loads(x) for x in batchfile.read_text().splitlines()]
notes=json.loads((W/'actual-thirteen-manually-formulated-independent-scientific-notes-a.json').read_text())['notes'];assert len(notes)==len(lines)==13
runid='wirtschaft-current336-D124-v19-b01-independently-executed-a-v1'
records=[]
for n,(line,note) in enumerate(zip(lines,notes),1):
 g=line['goal'];assert g['goalId'].startswith(note['idPrefix'])
 rec={'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json','schemaVersion':1,'recordId':f'current336-D124-b01-a-{n:02d}-{g["goalId"]}','runId':runid,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'bundleFingerprint':line['bundleFingerprint'],'bookDigest':line['bookDigest']}
 for key in ['goalId','goalFingerprint','pageFingerprint','currentTitleDe','currentTitleEn','currentDescriptionDe','currentDescriptionEn']:rec[key]=g[key]
 rec.update({'decision':note['decision'],'understandingEvidence':note['understandingEvidence'],'rationale':note['rationale'].replace('vorgegebenener','vorgegebener'),'evidenceProfileContract':'positive-understanding-evidence-v2','evidenceProfileRecommendation':note['evidenceProfileRecommendation'],'recordStatus':'candidate','reviewAuthority':'ai_candidate'})
 records.append(rec)
output=A/'results'/(batch['batchId']+'.records.jsonl');assert not output.exists();raw=('\n'.join(json.dumps(r,ensure_ascii=False,separators=(',',':')) for r in records)+'\n').encode();output.write_bytes(raw)
method={'actualReviewerAgent':'/root/economics_m2_source_independent_a','currentRound':'a','inputRestriction':'Only own bound native A packet, criteria/prompt, whole current bilingual goal and canonical/page context, all complete supplied P cases and actual current images/native PDF pages; no B records or historical D verdicts inspected.','manualWholeScientificJudgments':13,'wholePositiveApplicationCasesRead':28,'existingImageContextsActuallyViewed':13,'nativeOwnerPDFPagesTextActuallyRead':13,'modelIdentity':'GPT-6 / Codex as declared by the system; exact deployment/version and decoding settings not exposed, not invented','wordingGeneration':'Six individually formulated bilingual understanding/performance/transfer fields per goal, no profile expectation copied as a generic approval','nativeMetadataCopyOnly':'Binding program copies literal supplied IDs/fingerprints/titles/descriptions, never invents a binding or scientific conclusion.','smallOwnNotebookTypoBeforeFormalRecordBinding':{'before':'vorgegebenener','after':'vorgegebener','literalCorrections':1},'scientificAuthority':'ai_candidate only; human release remains separate','specialAuthored2Excluded':True}
method_binding=write(W/'actual-current-A01-review-method-and-visible-generation-parameters.json',method)
start=datetime.datetime.fromtimestamp((W/'actual-all13-image-and-owner-page-reading-bindings.json').stat().st_mtime,datetime.timezone.utc).isoformat();finish=datetime.datetime.now(datetime.timezone.utc).isoformat()
roles=['book_model','book_pdf','review_input_json','review_prompt','review_criteria']
run={'$schema':'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json','schemaVersion':1,'runId':runid,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'batchId':batch['batchId'],'batchInputFingerprint':batch['batchInputFingerprint'],'bundleFingerprint':campaign['bundleFingerprint'],'bookDigest':campaign['bookDigest'],'provider':'OpenAI','model':'GPT-6 / Codex (precise deployment version not exposed)','role':'subject_reviewer','promptFamilyId':'goal-description-understanding-evidence-review-v2','promptFingerprint':campaign['promptFingerprint'],'criteriaFingerprint':campaign['criteriaFingerprint'],'generationParametersFingerprint':method_binding['sha256'],'independenceGroupId':campaign['independenceGroupId'],'blindToOtherRuns':True,'goalIds':batch['goalIds'],'inputArtifacts':[{'role':x['role'],'digest':x['digest']} for x in bundle['artifacts'] if x['role'] in roles]+[{'role':'description_review_batch_input_jsonl','digest':batch['batchInputFingerprint']}],'startedAt':start,'completedAt':finish,'status':'completed','outputDigest':digest(raw),'toolchainVersion':'skillpilot-native-description-review-v2'}
runp=A/'results'/(batch['batchId']+'.run.json');write(runp,run)
node=Path('/tmp/skillpilot-checkpoint-native-node-path.txt').read_text().strip();args=[node,str(R/'app/node_modules/tsx/dist/cli.mjs'),'scripts/validateGoalDescriptionReviewCampaignResults.ts','--bundle',str(A/'review-bundle-manifest.json'),'--input',str(A/'description-review-input.json'),'--campaign',str(A/'description-review-campaign.json'),'--batches-dir',str(A/'batches'),'--results-dir',str(A/'results')];t=time.monotonic()
with (W/'actual-native-own-A01-candidate-validation.stdout.txt').open('x') as out,(W/'actual-native-own-A01-candidate-validation.stderr.txt').open('x') as err:result=subprocess.run(args,cwd=R/'app',stdout=out,stderr=err)
command=write(W/'actual-native-own-A01-candidate-validation.actual-command-exit.json',{'argv':args,'cwd':str(R/'app'),'actualExitCode':result.returncode,'seconds':round(time.monotonic()-t,3),'stdout':bound(W/'actual-native-own-A01-candidate-validation.stdout.txt'),'stderr':bound(W/'actual-native-own-A01-candidate-validation.stderr.txt'),'onlyOwnCurrentARoundRead':True,'noSummaryOrFinalizationExecuted':True})
assert result.returncode==0
assert digest(batchfile.read_bytes())==batch['batchInputFingerprint']
readings=write(W/'actual-A01-whole-input-reading-and-candidate-science-completion.receipt.json',{'status':'ACTUAL_INDEPENDENT_A_FIRST_PASS_CANDIDATES_NATIVE_VALID','run':bound(runp),'records':bound(output),'decisions':{'keep':13,'revise':0,'split_review':0,'block':0},'currentIDs':batch['goalIds'],'wholeCurrentPApplicationCasesRead':28,'wholeGoalDEENPageAndCanonicalContextsRead':13,'actualCurrentImageContextReading':bound(W/'actual-all13-image-and-owner-page-reading-bindings.json'),'actualNativeOwnerPDFReading':bound(W/'actual-own-pdftext-reading-command.json'),'scientificManualNotes':bound(W/'actual-thirteen-manually-formulated-independent-scientific-notes-a.json'),'actualExecutionMethod':method_binding,'nativeOwnCandidateValidation':command,'allNativeBindingsCopiedExactly':True,'reviewedSourceRefAsSuppliedCurricularContextOnly':True,'wholeCountryOrExternalPrimarySourceApprovalClaimed':False,'imageGenerationOrNewVisualApproval':False,'special2Reviewed':False,'BReviewRead':False,'dualRoundResolvedOrDCompleteClaimed':False,'humanReleaseClaimed':False})
(W/'actual-executed-binding-and-own-validator-helper.py').write_bytes(Path(__file__).read_bytes());(W/'actual-manually-authored-own13-scientific-notes-source.py').write_bytes(Path('/tmp/economics-D124-A01-manual-whole-review-notes.py').read_bytes())
print(json.dumps({'ownRound':'a','package':1,'actualGoalJudgments':13,'candidateDecisions':{'keep':13},'nativeValidationExit':result.returncode,'receipt':readings}))
