from pathlib import Path
import json,hashlib,shutil
R=Path('/home/enpasos/projects/skillpilot');O=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-nine-international-trade-finance-whole-science-independent-a-v1';A=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-nine-international-trade-finance-one-contract-local-author-v1/distinct-four-actor-and-fair-partial-author-successor-v3'
def bind(p):return {'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}
def out(n,a):
 p=O/n;assert not p.exists();p.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');return bind(p)
M=json.loads((A/'whole-nine-one-contract-two-case-DEEN24-15.DRAFT-author-candidates.json').read_text())['materials'];I=json.loads((A/'whole-nine-current-contracts-P18-existing-KEEP-and-actual-case-binding.author-index.json').read_text());W=json.loads((O/'actual-original-rubric-precision-32-own-whole-works384-individual-manual-grades.independent-successor.json').read_text())['works']
subjects=[
 {'contract':'Drei Mechanismen müssen an beobachtbaren Formen/Bedeutungen unterschieden werden; Gleichzeitigkeit und Deutungs-/Reichweitengrenzen sind Teil des Vertrags.','A':'Gemeinsame App/Becher/Jingle sind Formangleichung; örtliche Öffnungszeit/Sorte ist Anpassung; Trommel-Jingle-Stück und Konzertbecher sind eine neue Verbindung und Bedeutung.','B':'Turnierformat bleibt gemeinsam, Termin/Sprache passen es an; Geschichten/Figuren und veränderte Entscheidungen schaffen eine neue Praxis. Späteres Ende verändert diese bei stabilem Turnier.','reason':'Die beiden Fälle variieren tatsächliche Form, Verwendung und Weiterentwicklung. Reine Übersetzung und Downloads genügen nicht für Kreolisierung/Bedeutung. Daten aus Stammkundschaft/Teilnehmenden begründen ausdrücklich keine Gesamtbevölkerungs- oder Langzeitbehauptung.','boundary':'Eigene ganze Konvergenz-Verneinung bleibt trotz guter Anpassungs-/Hybridbeiträge14FAIL. Die neue echte Teilantwort18PASS lässt konkrete Becherbedeutung und Untersuchungsdetails offen.'},
 {'contract':'Preis-/Prämien-/Standardwirkungen fairer Verträge müssen von regelgebundenem Marktzugang unterschieden und mit Reichweite, ausgeschlossenen Gruppen und Grenzen beurteilt werden.','A':'30 von80t sind höher gekauft. Zertifizierung mindert Verkaufserlös,750 bleiben Wasserprojektmittel. Importeurabgabensenkung wird ohne vereinbarte Weitergabe kein Kooperativeneinkommen.','B':'20 von60 Betrieben erhalten den vertraglichen Absatz und350 Nettoverkaufserlös pro Betrieb;300 finanzieren Training. Vierzig bleiben beim Normalpreis; fünf Beratene erfüllen Zugangsdokumente nicht.','reason':'Zwei unterschiedliche Mengen-/Teilnahmeverteilungen erlauben Mechanismenvergleich ohne erfundene tatsächliche Fairtrade-Norm. Restriktive Projektprämien werden nicht dem privaten Einkommen zugerechnet; breiter Zugang schafft noch keine Nachfrage- oder Armutswirkung.','boundary':'Eigene ganze Prämienzweck-Verfehlung ist14FAIL trotz richtiger Preise und Zugangsanalyse; echte Teilantwort17PASS fehlt Standard-/Gruppenrechnung und ausgearbeitete Standards.'},
 {'contract':'NGO-Beiträge, Repräsentation, Finanzierung/Rechenschaft und deren Grenzen müssen von privater und öffentlicher Entscheidungsmacht unterschieden werden.','A':'Baufinanzierung90000 und jährliche Wartungslücke2000 unterscheiden Hilfe und dauerhaften Betrieb. Verein/Behörde bleiben eigene Akteure; Übersetzungs-/Entfernungshürden begrenzen offene Sitzungen.','B':'NGO-Dokumentation, Gewerkschaftsvertretung, Firmeneinkauf und öffentliche Sanktion sind getrennt. Freiwillige Interviews, positive Geberwünsche und Offline-Ausschluss erzeugen verschiedene Evidenz-/Zugangsgrenzen.','reason':'Finanzierung oder öffentlicher Einfluss schafft keine eigene Genehmigungs-/Gesetzgebungsmacht. Beide Fälle verlangen konkrete Beteiligung und überprüfbare Wirkung, keinen pauschalen NGO-Nutzen oder eine vollständige Ersatzregierung.','boundary':'Ganze öffentlich-private Machtgleichsetzung scheitert11FAIL; eine separate neue unvollständige20PASS-Arbeit lässt Bau-Stückrechnung, feste Dauerfinanzierung und ausgearbeitete Interviewmethode offen.'},
 {'contract':'IWF, Weltbank-Einrichtung, private Finanzakteure und Staat sind vier getrennte notwendige Rollen mit Mandat/Bedingungen, Finanzierungs-/Vertragslogik und Entscheidungsgrenzen.','A':'Bedingte Stabilisierung30 und private15 können das45-Zahlungsproblem adressieren; gebundene50 Entwicklungsfinanzierung lassen20 Projektbedarf. Parlament/Budget wird nicht durch Hilfe ersetzt.','B':'Ohne vereinbarte Verlängerung bleiben55 fällig;35 Entwicklungsfinanzierung lassen getrennt5 Projektbedarf. Private Vertragszustimmung, Stabilitätsbedingungen, Projektkontrolle und öffentliche Lastenentscheidung bleiben eigenständig.','reason':'Allgemeine strukturelle Finanzierungsinformationen sind primär belegt; Modellbeträge sind fiktiv. IBRD/IDA werden nicht mit identischen Instrumenten gleichgesetzt. Projektmittel sind keine freie private Tilgungskasse, IWF keine Weltregierung.','boundary':'Vier eigene ganze Arbeiten lassen jeweils genau einen der vier Akteure ohne eigene Rolle aus und enden14FAIL. Die tatsächliche18PASS-Teilantwort braucht keine Detailquote/IBRD-IDA-Vollständigkeit, zeigt aber alle vier Rollen und wesentlichen Entscheidungsgrenzen.'},
 {'contract':'Verlust-/Eigenkapital-, Zahlungs-/Fälligkeits- und systemische Übertragungsmechanismen müssen getrennt mit Kapital, Liquidität, Aufsicht/Offenlegung und Grenzen diskutiert werden.','A':'12 Verlust führen zu−3 Eigenkapital;15 schuldfinanzierte Liquidität reparieren dieses nicht. Der20-Anspruch ist ein tatsächlicher Verflechtungskanal, kein bekannter quantifizierter B-Verlust.','B':'Verkauf mit4 Verlust und25 Mittelabzug lassen91 Aktiva,89 Schulden,2 Kapital und1 Cash. Gleichzeitige Notverkäufe können Preis-/Abschreibungsrückkopplung auslösen.','reason':'Laufzeit-/Liquiditätsschutz und Verlustkapital sind ergänzend, Transparenz ein anderer Mechanismus. Das Material behauptet keine konkreten geltenden Basel-Quoten, sichere Steuerwirkung oder garantierte Krisenfreiheit; Kreditkosten und fehlende Reaktionsdaten sind bewertet.','boundary':'Ganze Offenlegungsfunktions-Verneinung14FAIL ist gesondert geschützt.17PASS-Teilantwort lässt B-Forderungskanal und restliche C-Bilanzdetails aus, zeigt aber systemische Rückkopplung, Kapital/Liquidität und eigene Aufsichtsfunktion.'},
 {'contract':'Digital gelieferte/physische Leistung, Datenfunktion und Plattformvermittlung müssen bei grenzüberschreitenden Beziehungen funktional getrennt und Alternativen mit Abhängigkeitsgrenzen beurteilt werden.','A':'Layoutdienst, Cloudspeicherung, Auftrags-/Zahlungsvermittlung und unbezahlte Abrufsignale sind verschiedene Funktionen. Vier Backupkosten verändern Marge, weder Preis noch automatisch Kundenzugang.','B':'Reparatur bleibt physisch lokal, Buchung/Datenverarbeitung werden international erbracht.81 Auszahlung, Rankingabhängigkeit und mögliche6 direkte Gebührenersparnis erklären tatsächliche Funktionen und Grenzen der eigenen Seite.','reason':'Datenflüsse sind nicht automatisch ein bezahlter zusätzlicher Service oder Warenexport. Technische Übertragung beweist weder zulässige Datenrechte noch Wiederherstellbarkeit oder gleiche Kunden. Es werden keine privaten Lernendendaten benutzt und kein Runtime-/Datenschutzprojekt verändert.','boundary':'Ganze Datenfunktions-Verneinung14FAIL trotz richtig beschriebener Services/Plattformen;19PASS-Teilantwort lässt zusätzliche Dateidaten, Wiederherstellungsprüfung und einzelne Zahlen-/Außenbeziehungsdetails offen.'},
 {'contract':'Alle drei räumlichen Standortformen benötigen expliziten Heimatbezug; vollständige laufende/Übergangskosten, Qualitäts-/Kapazitätseignung und konkrete Lieferabhängigkeiten tragen ein bedingtes Urteil.','A':'R/H erfüllen Qualitäts-/Kapazitätsbedarf100; N90 bleibt nur hypothetischer Kostenvergleich. Erste Gesamtkosten10000/10100/10700 unterscheiden Umstellung von späteren Aufträgen.','B':'Bei200 passt nur N nachgewiesen. R92% verfehlt95%, H140 verfehlt200. Unabhängige R-Energie und gemeinsamer N/H-Vorprodukt-/Netzbezug variieren funktionale gegen räumliche Nähe.','reason':'Dies sind ausdrücklich Standortoptionen, kein Beleg tatsächlicher historischer Produktions-/Arbeitsplatzverlagerung. Qualität, Kapazität und funktionale Ersatzversorgung bleiben harte Eignungsbedingungen; eine nahe oder billige Option wird nicht automatisch sicher.','boundary':'Ganze geografische Preisgruppengleichsetzung14FAIL;18PASS-Teilantwort zeigt alle drei Formen, Eignung und Risiken, obwohl laufende Kosten/Übergangskomponenten und Gegenabwägung nicht vollständig ausgeführt sind.'},
 {'contract':'Tarifärer Preis-/Staatsaufkommenseffekt ist von nichttarifärer Mengen-/Zugangslogik, Quotenrenten und legitimer Schutzfunktion zu unterscheiden; Betroffenengruppen und Grenzen tragen das Urteil.','A':'Unter eigens gegebenen15-Import-/62-Preisbedingungen unterscheiden sich180 Staatsaufkommen und180 private Gratislizenzrente. Diese besondere Modellgleichheit ist kein allgemeiner Satz über Zoll/Quote.','B':'Zoll90/80 kann den Importvorteil umkehren. R85/93 ist gleicher belegter Schutz, S92/93 eine importexklusive Wiederholung ohne neuen Risikobefund. Quote begrenzt höchstens5, liefert ohne Nachfrage keine neuen Marktpreise.','reason':'Eine bloße Testbelastung ist nicht per se illegitim, aber Duplikat/Gleichbehandlung/Risikonachweis sind eigenständig zu prüfen. Offizielle WTO-Aussagen wurden nur im tatsächlichen Zugriffsumfang benutzt; die fiktive Prüfung ist kein abschließendes Rechtsurteil.','boundary':'Ganze legitime Schutzfunktions-Verneinung14FAIL trotz korrekter Handelsrechnungen.17PASS-Teilantwort erlaubt einen begründeten transparenten Aufkommens-/Schutzentscheid, lässt genaue Anbietermarge und Teile der Gruppenfolge offen.'},
 {'contract':'Reale Handelsschaffung und reale Umlenkung müssen trotz privater Preisvorteile unterschieden werden; bilateraler/multilateraler Umfang, Außenseiter/Regeln und kriterienbezogene Gruppen-/Wohlfahrtsgrenzen sind nötig.','A':'H130→P85 spart45 Käuferpreis und reale Produktion; multilateral könnte D75 weitere10 sparen. Bilaterale Regeln schließen billigeren Outsider trotz weiterer Zustimmung aus.','B':'D110→P98 spart12 Käuferpreis, aber reale Produktion steigt15 plus3 Prüfung=18. Verlorene30 sind öffentlicher Transfer. Allgemeines Zollnull erlaubte D80; heimischer Arbeitsplatzschutz ist beim D→P-Wechsel nicht belegt.','reason':'Die Fälle trennen eigene Modellkosten konsequent von tatsächlichen aktuellen Abkommen/Zöllen. Käuferersparnis ist kein Netto-Wohlfahrtssatz; öffentliche Transfers werden nicht als zusätzliche Ressourcenvernichtung gezählt. Auswahl von Prioritäten bleibt offen, breitere Regeln sind nicht kostenlos garantiert.','boundary':'Ganze reale Umlenkungsverneinung14FAIL trotz guter A-Handelsschaffung.18PASS-Teilantwort bleibt in Gruppen-/Institutionenkostenbetrachtung unvollständig, zeigt aber beide unabhängigen Kernmechanismen und konkrete Regeln/Grenzen.'}
]
dec=[]
for k,(m,row,s) in enumerate(zip(M,I['rows'],subjects)):
 assert m['requires']==[row['goalId']] and m['examData']['coveredGoalIds']==[row['goalId']]
 assert m['contains']==[] and m['examData']['reviewStatus']=='draft'
 sc=m['examData']['scoring'];assert sc['maxPoints']==24 and sc['passingPoints']==15 and [st['points'] for st in sc['steps']]==[6]*4
 works=[w for w in W if w['materialId']==m['id']]
 validpartial=[w for w in works if 'fair-incomplete' in w['workId'] and w['result']=='PASS'];assert validpartial
 dec.append({'materialId':m['id'],'currentOrdinaryGoalId':row['goalId'],'decision':'KEEP','decisionScope':'Entire new bilingual scientific task/material/solution/rubric contract only; no status/nav/scope approval','wholeCurrentGoalAndOriginalP':{'goal':row['wholeGoal'],'positiveProfileRecord':row['wholePositiveProfileRecord'],'originalReviewFile':row['originalWholeReviewBinding']},'requiredWholePerformance':s['contract'],'actualWholeTwoCaseCoverage':{'caseA':s['A'],'caseB':s['B']},'ownScientificReasoning':s['reason'],'actualOwnCountercaseAndFairPartialResult':s['boundary'],'actualIndependentWholeWorkIds':[w['workId'] for w in works],'actualIndependentWholeWorkFinalResults':[{'workId':w['workId'],'rawPoints':w['rawPoints'],'finalPoints':w['finalPoints'],'result':w['result'],'wholeCoreCapApplied':w['actualPublishedCapAppliedOnlyToGenuineWholeAbsence']} for w in works],'bilingualReview':'All DE/EN case dossiers, four tasks, four solutions and all eight scoring-language strings actually read against the same whole contract. Equivalent demands, numeric assumptions, group/actor roles, conditional limits and partial-credit boundary agree. This is semantic reading, not character/hash comparison as science.','semanticKindDecision':{'requiredKind':'practiceAssessment','why':'The terminal assesses an already existing curricularAtomic contract with fictional multi-step work and own rubric. It creates no new ordinary competence and no memorization/card requirement.'},'courseTagsActual':m['tags'],'profileClaimsUnchanged':{'status':'needs_human_review','reviewAuthority':'ai_candidate','cases':2,'evidenceLevel':'E1/G1 retained, no human-release upgrade'},'scientificOpenFindings':[]})
d=out('actual-nine-entire-DEEN-whole-contract-and-two-case-science.independent-KEEP-decisions.json',{'reviewerRole':'Independent scientific reviewer A, not material author','actualWholeMaterialsReviewed':9,'actualWholeCurrentOrdinaryGoalsReviewed':9,'actualOriginalPositiveCasesReviewed':18,'actualWholeDEENTasksSolutionsRubricsReviewed':True,'actualIndependentExecutedFractionChecks':82,'actualOwnUniqueWholeAnswerworks':32,'actualFinalIndividualManualCriterionGrades':384,'wholeOriginalProvisionalOwnGradeHistoryPreserved':True,'ownGradeCorrectionResolved':'The provisional30-work file is historical. Final original-rubric precision corrects all own marks; two initially too-generous short responses now FAIL13/14, and two distinct materially incomplete new responses PASS18/20. No material or author rubric was changed.','decisions':dec,'verdict':'KEEP_all9_scientific_material_only','unchangedHistoricalSevenMaterialReviewsRestarted':False,'notIndependentScopeApproval':True,'notNewCurricularAtomicOrMemoryApproval':True,'notHumanReviewedReleasedOrTested':True,'activeWrites':0})
runner=O/'reproducible-independent-runners';runner.mkdir(exist_ok=True)
for f in ['/tmp/economics-international-nine-independent-a-own-works.py','/tmp/economics-international-independent-a-grade-followup.py','/tmp/economics-international-independent-a-numeric-primary-endguard.py','/tmp/economics-international-independent-a-finalize.py']:
 p=runner/Path(f).name;assert not p.exists();shutil.copyfile(f,p)
frozen=json.loads((O/'actual-nine-body-and-current-contracts-P18-independent-input-freeze.json').read_text())
for name in ['wholeAuthorHandoff','wholeNineBody','wholeNineContractsP18AndHistoricalKEEPIndex','wholeAuthorPrimarySourceReceiptReadAsProvenanceOnly']:assert bind(R/frozen[name]['path'])==frozen[name]
canpath=R/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_WIRTSCHAFT.de.json';can=json.loads(canpath.read_text());g={x['id']:x for x in can['goals']}
assert all(g[r['goalId']]==r['wholeGoal'] for r in I['rows'])
manifest=out('actual-final-independent-nine-whole-science-whole-file-manifest.json',{'allIndependentEvidenceAndRunners':[bind(p) for p in sorted(O.rglob('*')) if p.is_file()],'authorWholeInputs':frozen,'targetedCurrentCanonical555WholeGoalEndGuard':bind(canpath),'scope':'Independent entire material science; actual input guards are reproducibility only, not scientific substitute','activeWrites':0})
h=out('actual-final-nine-international-whole-DEEN-science-independent-a-KEEP.handoff.receipt.json',{'independentReviewer':'economics_m2_source_independent_a','reviewDate':'2026-10-10','verdict':'KEEP_all9_scientific_material_only','exactForeignAuthorHandoff':frozen['wholeAuthorHandoff'],'exactWholeReviewedDRAFTBodies':frozen['wholeNineBody'],'exactWhole9GoalP18Index':frozen['wholeNineContractsP18AndHistoricalKEEPIndex'],'scientificDecisions':d,'finalOriginalRubric32OwnWorks384Grades':bind(O/'actual-original-rubric-precision-32-own-whole-works384-individual-manual-grades.independent-successor.json'),'own82FractionChecks':bind(O/'actual-own-independent-rational-case-calculations-and-economic-boundaries.json'),'ownSevenPrimaryReadingFamiliesWithHonestAccessLimits':bind(O/'actual-seven-independent-primary-web-reading-bounded-paraphrases-and-access-limits.receipt.json'),'current555NineWholeGoalsP18Endguards':bind(O/'actual-current555-nine-whole-contracts-P18-original-statuses-and-frozen-input-endguards.independent.json'),'wholeManifest':manifest,'actualOwnResults':{'entireMaterials':9,'currentContracts':9,'originalPCases':18,'uniqueWholeOwnAnswers':32,'finalIndividualManualGrades':384,'completeAlternativePASS':9,'fairIncompletePASS':9,'ownShortIncompleteFAILWithoutCap':2,'genuineCoreOrDistinctActorAbsenceFAIL':12,'executedIndependentRationalChecks':82,'numericFailures':0},'scientificFindingsAgainstAuthorBodies':[],'ownProvisionalGradePrecisionErrorAndResolutionPreserved':True,'existingSevenHistoricalGoodMaterialsUntouchedNoReviewRestart':True,'requiredNextStep':'Separate foreign country/course/whole prerequisite closure/access/nav/status/SEM binding review, then guarded fieldwise integration on actual current canonical. This receipt itself does not release any material or pass wholeM4.','scopeApproval':False,'humanApprovalClaim':False,'PStatusUpgraded':False,'newAtomicMemoryOrImageWork':False,'activeWrites':0})
print(json.dumps(h,indent=2))
