import{readFileSync,writeFileSync,copyFileSync}from'node:fs';import{join}from'node:path';import assert from'node:assert/strict';import Ajv2020 from'ajv/dist/2020.js';import{run,ids,canPath,CAP,OUT,ROOT}from'./actualNativeCurrent555Macro13Common.mts';
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));const save=(n:string,d:any)=>writeFileSync(join(OUT,n),JSON.stringify(d,null,2)+'\n');const ix=read(join(OUT,'actual-276-country23-national-practice-only-target-reference-appends.author-index.json'));const before=read(join(OUT,'intake-before-current555.actual-native.json'));const positive=()=>{copyFileSync(join(OUT,'whole-current568-thirteen-foreign-KEEP-two-Nav-fields.INERT-final-author.json'),canPath);for(const v of ix.views)copyFileSync(v.afterPath,join(CAP,v.activePath));};
const val=new Ajv2020({strict:true,allErrors:true}).addKeyword({keyword:'x-skillpilot-listSemantics',schemaType:'string',valid:true,metaSchema:{enum:['ordered']}}).compile(read(join(ROOT,'contracts/curriculum-package/v1/composition-view.schema.json')));const schemas=ix.views.filter((v:any)=>v.actualNewReferenceCount).map((v:any)=>{assert.equal(val(read(v.afterPath)),true,JSON.stringify({view:v.activePath,errors:val.errors}));return{view:v.activePath,errors:0};});save('actual34-changed-crossstage-closed-schema-errors0.author.json',{changedWholeViews:schemas,unchangedLegacySekINotClaimedSchemaPASS:true});positive();const after=run('final-after-current568-macro13-299-accesses');
const metrics=(r:any)=>r.wholeRoute.rules.find((x:any)=>x.id==='CQR-104').metrics;const clean=(x:any)=>JSON.parse(JSON.stringify(x));const normal=(rows:any[])=>clean(rows).map(s=>Object.fromEntries(Object.entries(s).map(([k,v])=>[k,Array.isArray(v)?(v as string[]).filter(z=>!ids.includes(z)):v])));assert.deepEqual(normal(before.all64NativeScopeSets),normal(after.all64NativeScopeSets));
const wholeP=read(join(OUT,'whole-current555-thirteen-original-contracts-P29-and336P685-exact-author-endguards.json'));const ordinaryIds=wholeP.allCurrentOriginalWholeP.map((p:any)=>p.goalId);assert.equal(ordinaryIds.length,336);for(const id of ordinaryIds)assert.deepEqual(after.wholeCompiler.goals.find((g:any)=>g.goalId===id),before.wholeCompiler.goals.find((g:any)=>g.goalId===id));
const sourceContract=(d:any)=>{const c=structuredClone(d);delete c.rawAtomicGoals;for(const j of c.jurisdictions){delete j.visibleGoals;delete j.visibleClusterGoals;}return c;};assert.deepEqual(sourceContract(before.wholeSource),sourceContract(after.wholeSource));assert.equal(after.wholeSource.rawAtomicGoals-before.wholeSource.rawAtomicGoals,13);assert.equal(after.wholeCompiler.summary.goals,568);assert.equal(after.wholeCompiler.summary.errors,0);assert.equal(after.wholeCompiler.summary.warnings,0);
const bindings=after.actualMaterials.flatMap((m:any)=>m.actual64Scopes.map((s:any)=>{const eligible=s.countryCompatible&&s.courseCompatible&&s.missingPrerequisites.length===0;assert.equal(s.materialCurrentlyVisible,eligible,JSON.stringify({id:m.id,...s,eligible}));return{materialId:m.id,wholeClosure:m.wholeClosure,...s,eligible};}));assert.equal(bindings.filter((s:any)=>s.eligible).length,552);assert.equal(bindings.filter((s:any)=>s.eligible&&!s.wholeCoveredTargetsPresent).length,62);
for(const r of [before,after]){const q=metrics(r);assert.equal(q.visibleProjectedRouteTargetGoalOccurrences,6974);assert.equal(q.visibleProjectedRouteTargetGoalOccurrencesExcludedByProfileSelector,0);assert.equal(q.projectionScopesWithInvalidStageStructure,0);assert.equal(q.wholeMaterialCoveredGoalOccurrencesWithoutVisiblePrerequisitePath,0);assert.equal(q.wholeMaterialPrerequisiteOccurrencesMissingFromProjection,0);}
const drop=(v:any,id:string,role:string)=>{let n=0;const walk=(o:any)=>{if(!o||typeof o!=='object')return;for(const k of Object.keys(o)){if(Array.isArray(o[k])){o[k]=o[k].filter((q:any)=>{if(q?.kind==='goalEntry'&&q.goalId===id&&q.projectionRole===role){n++;return false;}return true;});for(const z of o[k])walk(z);}else walk(o[k]);}};walk(v);assert.equal(n,1);return v;};let negRef:any,negSupport:any;
try{const ni=ix.views.find((v:any)=>v.activePath.endsWith('de-ni-gym-economics-gk.view.json')),nip=join(CAP,ni.activePath);writeFileSync(nip,JSON.stringify(drop(read(nip),'2b1122b9-30c6-5160-b439-fe03cb04e583','target'),null,2)+'\n');negRef=run('negative-one-real-NI-GK-indicators-practice-reference-drop');assert.ok(metrics(negRef).visibleSelectedGoalOccurrencesMissingDirectTerminalRoute>metrics(after).visibleSelectedGoalOccurrencesMissingDirectTerminalRoute);assert.deepEqual(after.wholeSource,negRef.wholeSource);copyFileSync(ni.afterPath,nip);
const bb=ix.views.find((v:any)=>v.activePath.endsWith('de-bb-gym-economics-gk.view.json')),bbp=join(CAP,bb.activePath);writeFileSync(bbp,JSON.stringify(drop(read(bbp),'d36664f5-1dc2-5e4b-bda0-0a288407d2af','prerequisiteOnly'),null,2)+'\n');negSupport=run('negative-one-real-BB-GK-existing-growth-POnly-support-drop-whole-practice-remains-visible');assert.ok(metrics(negSupport).wholeMaterialCoveredGoalOccurrencesWithoutVisiblePrerequisitePath>0);assert.ok(metrics(negSupport).wholeMaterialPrerequisiteOccurrencesMissingFromProjection>0);assert.deepEqual(after.wholeSource,negSupport.wholeSource);
}finally{positive();}
const compiledChanges=after.wholeCompiler.goals.filter((g:any)=>!ids.includes(g.goalId)&&JSON.stringify(g)!==JSON.stringify(before.wholeCompiler.goals.find((b:any)=>b.goalId===g.goalId))).map((g:any)=>({goalId:g.goalId,wholeBefore:before.wholeCompiler.goals.find((b:any)=>b.goalId===g.goalId),wholeAfter:g}));assert.equal(compiledChanges.filter((g:any)=>ordinaryIds.includes(g.goalId)).length,0);
save('actual-final-macro13-299-accesses552-whole-bindings62-existing-POnly-source64-role-and-genuine-negatives.author-guards.json',{role:'AUTHOR_NATIVE_CANDIDATE_CHECKS_NOT_INDEPENDENT_SCOPE_KEEP',beforeCompiler:before.wholeCompiler.summary,afterCompiler:after.wholeCompiler.summary,whole64OldTargetSupportPOnlyMemoryOrientationRowsExactRemovingOnly13NewPractices:true,current336CompiledOrdinaryWholeExact:true,source16_2134WholeAtomicContractIncludingDiagnosticPartialWarningsExact:true,newSourceClaims:0,only13PracticeRawCountDelta:13,actualOldDerivedClusterCompilerChanges:compiledChanges,actual552CompatibleBindings:bindings.filter((s:any)=>s.eligible),actual62NewWholeAssessmentBindingsOverExistingPOnly:bindings.filter((s:any)=>s.eligible&&!s.wholeCoveredTargetsPresent),actual70CountryCourseClosureIncompatibleBindingsHeld:bindings.filter((s:any)=>s.countryCompatible&&s.courseCompatible&&s.missingPrerequisites.length),actual299Refs:ix.actualReferences,actual34ChangedCrossStageSchemasErrors0:true,unchangedLegacyNotClaimedSchemaPASS:true,metrics:[before,after,negRef,negSupport].map(metrics),strictNewClosures:0,strictRestoredBindings:0,strictNet:0,humanReleaseClaimed:false,activeWrites:0,privatePositiveCandidateRestored:true});console.log(JSON.stringify({role:'AUTHOR_ONLY',compiler:after.wholeCompiler.summary,refs:ix.actualReferences,wholeBindings:552,purePOnly:62,held:70,local:[before,after,negRef,negSupport].map(r=>metrics(r).visibleSelectedGoalOccurrencesMissingDirectTerminalRoute),unique:[before,after,negRef,negSupport].map(r=>metrics(r).uniqueVisibleSelectedGoalsMissingDirectTerminalRoute),supportNegative:metrics(negSupport).wholeMaterialPrerequisiteOccurrencesMissingFromProjection,scopeDebt:[before,after,negRef].map(r=>metrics(r).projectionScopesMissingTerminalAutonomyGoals)}));
