import json,pathlib,hashlib,datetime
N=pathlib.Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/biologie-biotechnologie-evolution-eight-current353-source-raster-native-technical-preparation-20261010-v1')
B=pathlib.Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/biologie-bio8-current353-native11-genuine-independent-b-20261010-v1')
def h(p):return 'sha256:'+hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def bind(p):return {'path':str(p),'sha256':h(p),'bytes':pathlib.Path(p).stat().st_size}
def write(p,x):
 with open(p,'x') as f:json.dump(x,f,ensure_ascii=False,indent=2);f.write('\n')
first=json.load(open(B/'FIRST.current353-Bio8-native11.B.substantive.json'))
ff=json.load(open(B/'FIRST.current353-Bio8-native11.B.freeze.json'))
assert all(h(x['path'])==x['sha256'] for x in ff['files'])
# Clarify locally authored source ids and namespace without changing the sealed first verdict.
extra={
'4a8':{'rp-bio-seki-rp-bio-seki-2014-tf11-biowissenschaften-und-gesellschaft-004-6f24a318':'RP TF11 printed44/physical46 competency4 includes knowledge-based technology explanation OR judgement. Food-use cases cover the explanatory choice only. Whole research/presentation/risk argument and judgement duties remain separate. The direct neutral row has jurisdiction null; RP identity comes from the actual document and source id.'},
'523':{'b12fe158-e505-4896-8189-28c3209756c3':'HE Q1.2 printed39 lists PCR and gel electrophoresis at basic level. Restriction enzymes are not named in this literal and are an authored methods elaboration; do not claim exact literal restriction-enzyme coverage. The corrected explain description does not claim performed laboratory method execution.'},
'528':{'0668587d-ef5f-4a14-b1bc-01f51cba16f1':'HE Q1.2 printed39 LK content explicitly names DNA change, foreign-DNA introduction into host cells using plasmids/viruses and cloning. The current model explanation is a bounded operationalisation of this content, not a laboratory manipulation or full course. GK applicability would not be supported.'},
'a3f':{'51983683-14c8-4624-b5be-5a895d6780f1':'HE Q1.2 printed39 PCR and gel are jointly listed for GK/LK. PCR principle/application is the bounded PCR part. Literal topic naming does not itself supply experimental implementation or all neighbouring DNA/epigenome content.'},
'd11':{'46f4ea54-367f-4f40-b3f2-0d7fd4dff90e':'HE Q1.2 printed39 LK includes plasmid/virus foreign-DNA carriers and cloning. Vectors/cloning are a bounded content share; general expression-system specification is authored explanatory elaboration. No blanket official plasmid/expression exact-clause or performed transformation claim.'}}
supp=[]
for g in first['sourceReviews']:
 note=extra.get(g['canonicalGoalId'][:3],{}).get(g['sourceGoalId'])
 if note:supp.append({'canonicalGoalId':g['canonicalGoalId'],'sourceGoalId':g['sourceGoalId'],'additionalExactBoundary':note,'changesFirstDecision':False})
write(B/'source-boundary-detail.B.original-first.addendum.json',{'role':'original neutral source detail; no peer material read','independenceMaintained':True,'firstFrozenUnchanged':True,'details':supp})
R=B/'normal-D11';c=json.load(open(R/'description-review-campaign.json'));batch=c['batches'][0]['batchId']
records=R/'results'/f'{batch}.records.jsonl'
write(B/'normal-D11.validation.actual.json',{'scope':'only affected normal D11 campaign schema and exact current bundle/book/goal/page/text/batch/run/output bindings','tool':'app/scripts/validateGoalDescriptionReviewCampaignResults.ts','exitCode':0,'stdout':'Goal-description review campaign results valid: 11','campaign':bind(R/'description-review-campaign.json'),'input':bind(R/'description-review-input.json'),'records':bind(records),'run':bind(R/'results'/f'{batch}.run.json'),'firstSealFilesReverified':len(ff['files']),'allFirstFilesMatch':True,'notScienceApproval':True})
E=json.load(open(N/'neutral-current353-Bio8-native11.entry.json'))
# Entry closes through the original byte-exact neutral closure plus own fresh findings/results.
entry={'schemaVersion':1,'role':'Portable final genuinely independent B original-neutral review entry','scope':{'whole8D_P_A_M_V':True,'targeted3NativeDOnly':True,'current32SourceWitnesses':True,'actual24Rasters':True,'actual22WholePages':True},'firstSubstantive':bind(B/'FIRST.current353-Bio8-native11.B.substantive.json'),'firstMarkdown':bind(B/'FIRST.current353-Bio8-native11.B.substantive.md'),'firstFreeze':bind(B/'FIRST.current353-Bio8-native11.B.freeze.json'),'sourceBoundaryDetail':bind(B/'source-boundary-detail.B.original-first.addendum.json'),'normalD11':{'campaign':bind(R/'description-review-campaign.json'),'input':bind(R/'description-review-input.json'),'batch':bind(R/'batches'/f'{batch}.input.jsonl'),'records':bind(records),'run':bind(R/'results'/f'{batch}.run.json'),'actualValidation':bind(B/'normal-D11.validation.actual.json'),'precreatedNeutralBNormalCampaignPreserved':True},'portableInputClosure':{'neutralEntry':bind(N/'neutral-current353-Bio8-native11.entry.json'),'neutralFreeze':bind(N/'FINAL.current353-Bio8-native11-neutral.technical.freeze.json'),'currentWholeInput':E['coreInputs']['whole479Bio8Candidate'],'wholeP8':E['coreInputs']['P8WholeCurrent'],'wholeSource32':E['coreInputs']['current32SourceWitnesses'],'actualPrimaries':E['coreInputs']['allActualPrimaries'],'externalClosure':E['coreInputs']['portableExternalClosure'],'nativeBundle':E['coreInputs']['native11Bundle'],'nativeHTML':E['coreInputs']['native11HTML'],'nativePDF':E['coreInputs']['native11PDF'],'current11NativeCaptures':E['current11NativeCaptures']},'authority':first['approvalBoundary'],'decisionSummary':{'normalD11Keep':8,'normalD11SplitReview':3,'normalD11Valid':11,'all8M7Ready':False,'peerFindingsRead':False,'rootFindingsRead':False,'authorSuccessorRead':False},'firstRemainsUnchanged':True,'reviewInstructions':'Do not read substantive FIRST until root has sealed its own source/native FIRST. Subsequent disagreements must be recorded append-only against these original fingerprints.'}
write(B/'FINAL.current353-Bio8-native11.B.portable.entry.json',entry)
files=[p for p in sorted(B.rglob('*')) if p.is_file()]
freeze={'schemaVersion':1,'role':'Final independent B portable artifact freeze; original FIRST intact','createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':[bind(p) for p in files],'entry':bind(B/'FINAL.current353-Bio8-native11.B.portable.entry.json'),'neutralEntry':entry['portableInputClosure']['neutralEntry'],'neutralFreeze':entry['portableInputClosure']['neutralFreeze'],'approved':0,'humanRelease':False,'peerFindingsRead':False}
write(B/'FINAL.current353-Bio8-native11.B.portable.freeze.json',freeze)
print(json.dumps({'entry':bind(B/'FINAL.current353-Bio8-native11.B.portable.entry.json'),'freeze':bind(B/'FINAL.current353-Bio8-native11.B.portable.freeze.json'),'ownFiles':len(files)},indent=2))
