import { readFileSync, writeFileSync } from 'node:fs'
import { fingerprintGoal, fingerprintMemoryCard } from './memory-production-readonly-export'
const R='/home/enpasos/projects/skillpilot';const N=R+'/curricula/DE/Gymnasium/quality/goal-evidence/2026-10-09/wirtschaft-current125-native-mapping-and-explicit-BE-course-author-20261009-v1';const O=R+'/curricula/DE/Gymnasium/quality/goal-evidence/2026-10-09/wirtschaft-four-SourceMemory-current-origin-AM-card-and-BE-visibility-technical-binding-v1';
const a=JSON.parse(readFileSync(O+'/whole-CAN485-only-one-new-BB2-memory-node-and-one-source-navigation-child.inert-author-candidate.json','utf8'));
const config=JSON.parse(readFileSync(R+'/curricula/DE/Gymnasium/quality/goal-evidence/2026-10-08/wirtschaft-final-nineteen-current311-after-methods20-native-preparation-20261008-v1/memory.config.json','utf8'));
const rows=readFileSync(R+'/'+config.reviewPath,'utf8').trim().split('\n').map(x=>JSON.parse(x));
const goals=Object.fromEntries(a.goals.map((g:any)=>[g.id,fingerprintGoal(g,config.ruleVersion)]));
const cards:any={}; for (const g of a.goals.filter((g:any)=>g.extendedData?.authorCandidate?.deckDraftBinding)) {const d=JSON.parse(readFileSync(R+'/'+g.extendedData.authorCandidate.deckDraftBinding.path,'utf8'));for(const c of d.cards)cards[d.deckId+'::'+c.id]=fingerprintMemoryCard({deckId:d.deckId,cardId:c.id,front:c.front.replace(/\s+/g,' ').trim(),back:c.back.replace(/\s+/g,' ').trim(),category:(c.category??'').replace(/\s+/g,' ').trim(),tags:(c.tags??[]).map((x:string)=>x.replace(/\s+/g,' ').trim())},config.ruleVersion)}
const stale=rows.filter((x:any)=>x.fingerprint!==goals[x.goalId]).map((x:any)=>({goalId:x.goalId,old:x.fingerprint,current:goals[x.goalId]}));
writeFileSync(O+'/actual-native-current485-goal-card-fingerprints.json',JSON.stringify({goals,cards,staleExisting311:stale},null,2)+'\n');console.log(JSON.stringify({currentGoals:a.goals.length,existingRows:rows.length,staleExisting311:stale.map((x:any)=>x.goalId)}));
const altPath='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-09/wirtschaft-by-ten-current311-specific-native-preparation-technical-v1/current300-source35-scope2-contract479-selective-technical-v1/memory.review.jsonl';const altRows=readFileSync(R+'/'+altPath,'utf8').trim().split('\n').map(x=>JSON.parse(x));const alt=new Map(altRows.map((x:any)=>[x.goalId,x]));const check=stale.map((x:any)=>({goalId:x.goalId,altActualFingerprint:(alt.get(x.goalId) as any)?.fingerprint,currentFingerprint:goals[x.goalId],matches:(alt.get(x.goalId) as any)?.fingerprint===goals[x.goalId],wholeRecord:alt.get(x.goalId)}));writeFileSync(O+'/actual-eleven-existing-foreign-KEEP-current485-AM-record-reuse.check.json',JSON.stringify({sourcePath:altPath,rows:check},null,2)+'\n');console.log(JSON.stringify({actual11Matches:check.filter((x:any)=>x.matches).length}));
