// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict'
import {readFileSync,writeFileSync,mkdirSync,lstatSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {dirname,relative,resolve} from 'node:path'
import {fileURLToPath} from 'node:url'
import {buildGoalBookSourceAtlasInputs} from '../../../../../../../app/scripts/goalBookSourceAtlasInputs.ts'
import {buildGoalBookModel,parseAndValidateGoalBookModel,stableGoalBookJson} from '../../../../../../../app/scripts/goalBookModel.ts'
import {fingerprintGoalForPositiveEvidence,fingerprintPositiveGoalEvidenceReviewInput,fingerprintPositiveGoalEvidenceProfile,validatePositiveGoalEvidenceRecordSemantics} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel.ts'
const root=resolve('.'),own=dirname(fileURLToPath(import.meta.url)),native=resolve(own,'../biologie-evolution-current17-and-protected-contexts-native-preparation-author-v1')
const sha=(b:Buffer|string)=>'sha256:'+createHash('sha256').update(b).digest('hex'),rel=(p:string)=>relative(root,p)
const bind=(p:string)=>{assert.ok(!lstatSync(p).isSymbolicLink());const b=readFileSync(p);return {path:rel(p),sha256:sha(b),bytes:b.length}}
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),write=(p:string,x:any)=>{assert.ok(p.startsWith(own+'/'));mkdirSync(dirname(p),{recursive:true});writeFileSync(p,Buffer.isBuffer(x)?x:typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');return bind(p)}
const entry=read(resolve(native,'neutral-current17-and-protected-contexts.native-independent-review.final.entry.json')),oldConfig=read(resolve(native,'source-atlas/atlas.inputs.book-local.inactive.json')),newConfig=read(resolve(own,'candidate/source-atlas.current479-394-three-HE-partial-edges.inputs.json'))
const before=buildGoalBookSourceAtlasInputs(oldConfig,root),after=buildGoalBookSourceAtlasInputs(newConfig,root)
for(const built of [before,after]){assert.equal(built.receipt.counts.canonicalCurricularAtomicGoals,394);assert.equal(built.receipt.counts.publishedCurricularAtomicGoals,394);assert.equal(built.receipt.counts.unresolvedSourceScopeDecisions,0)}
assert.deepEqual(Object.keys(after.outputs).sort(),Object.keys(before.outputs).sort())
const transports=[],outputDiffs=[];for(const [p,b] of Object.entries(after.outputs)){const next=write(resolve(own,'normal-source-atlas/book-local-output-byte-transports',p),b);transports.push({operativeBookLocalPath:p,portableArchive:next});if(before.outputs[p]!==b)outputDiffs.push({path:p,originalSha256:sha(before.outputs[p]),successorSha256:sha(b)})}
const jsonOutput=(p:string)=>JSON.parse(after.outputs[p]),manifest=jsonOutput(newConfig.manifestPath),canonical=read(resolve(root,entry.candidateCanonicalPath)),kinds=read(resolve(root,entry.candidateKindsPath)),qa=read(resolve(root,entry.candidateVisualizationQAPath)),portableQA=read(resolve(root,entry.portableVisualizationQAPath)),book=read(resolve(root,entry.candidateBookConfigPath)),digests:Record<string,string>={}
for(const record of portableQA.records)if(record.visualizationState==='available'){const actual=bind(resolve(root,record.publicAssetPath));assert.equal(actual.sha256,record.assetSha256);digests[record.imageUrl]=actual.sha256}
const model=buildGoalBookModel({landscape:canonical,semanticKindLedger:kinds,goalVisualizationQa:qa,goalVisualizationAssetDigests:digests,compositionViewManifest:manifest,compositionViewSources:manifest.sourcePaths.map((p:string)=>({path:p,view:jsonOutput(p)})),navigationView:jsonOutput(manifest.navigationViewPath),durationModelPolicy:read(resolve(root,manifest.durationModelPolicyPath)),evidenceReviewSources:[],config:book})
parseAndValidateGoalBookModel(model)
const previous=read(resolve(root,entry.actualFullCandidateModelPath));assert.equal(stableGoalBookJson(previous),stableGoalBookJson(model));assert.equal(model.pages.length,394)
write(resolve(own,'normal-source-atlas/book-local-output-transports.actual.json'),{schemaVersion:1,outputs:transports,actualSourceAtlasCounts:after.receipt.counts,wholeSourceAtlasOutputChangedBindings:outputDiffs,actualBookManifestAndAllSourceViewsExactlyUnchanged:true,activeWrites:0})
write(resolve(own,'candidate/full394-three-HE-role-corrected.actual-normal-model.json'),model)
const goals=new Map<string,any>(canonical.goals.map((g:any)=>[g.id,g])),pConfig=read(resolve(root,entry.positiveConfigPath)),pRecords=readFileSync(resolve(root,entry.positiveRecordPath),'utf8').trim().split('\n').map(s=>JSON.parse(s)),criteria=sha(readFileSync(resolve(root,pConfig.reviewCriteriaPath)))
assert.equal(pRecords.length,17)
const profileChecks=pRecords.map((record:any)=>{const g=goals.get(record.goalId),im=entry.rasterBindings.find((b:any)=>b.goalId===g.id),resources={[im.resourceLinkCandidate.url]:im.portableAlias.sha256};assert.equal(record.goalFingerprint,fingerprintGoalForPositiveEvidence(g,'curricularAtomic'));assert.equal(record.reviewInputFingerprint,fingerprintPositiveGoalEvidenceReviewInput(g,criteria,resources,'curricularAtomic'));assert.equal(record.profileFingerprint,fingerprintPositiveGoalEvidenceProfile(record.profile));assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(record,g,resources,'curricularAtomic'),[]);assert.equal(record.status,'needs_human_review');assert.equal(record.reviewAuthority,'ai_candidate');return {goalId:record.goalId,goalFingerprint:record.goalFingerprint,reviewInputFingerprint:record.reviewInputFingerprint,profileFingerprint:record.profileFingerprint,actualFingerprintChanges:0,semanticErrors:[]}})
const originalBaseline=read(resolve(root,entry.actualFullBeforeModelPath)),baselineChanged=originalBaseline.pages.filter((p:any)=>stableGoalBookJson(p)!==stableGoalBookJson(model.pages.find((q:any)=>q.goalId===p.goalId))).map((p:any)=>p.goalId);assert.equal(baselineChanged.length,19);assert.deepEqual(baselineChanged,entry.actualChangedPageIds)
const protected15=entry.actualProtectedSourceOrPageReviewIds;assert.equal(protected15.length,15);assert.ok(protected15.includes('0f1549f6-8341-53b0-8161-5eaeb2b37809'))
const originalMap=read(resolve(root,oldConfig.mappingPaths.find((p:string)=>p.endsWith('HE144-four-source-and-course.whole-successor.review.json'))!)),correctedMap=read(resolve(own,'candidate/HE144-three-partial-operator-and-course-edges.whole-successor.review.json'))
const edgeChecks=[71,75,81].map(i=>{const d=correctedMap.decisions[i],e=correctedMap.mappings.filter((r:any)=>r.legacyGoalId===d.sourceGoalId&&d.canonicalGoalIds.includes(r.canonicalGoalId));assert.equal(e.length,1);assert.equal(d.matchType,'partial');assert.equal(e[0].matchType,'partial');assert.deepEqual(d,originalMap.decisions[i]);return {decisionIndex:i,wholeDecision:d,wholeExecutableEdges:e,exactOriginalDecisionRetained:true,wholeIndependentSourceApproval:false}})
write(resolve(own,'checks/normal-source-projection-whole394-and-current-P17.actual.json'),{schemaVersion:1,normalSourceAtlasCounts:after.receipt.counts,actualFull394ModelExactlyExistingNativeCandidate:true,actual19NativePageDiffFromActiveBaselineExact:true,actualProtected15ContextUnionExact:true,actualProtectedLeafMethodOwnerAlreadyIncluded:true,actualAdditionalNativePageChanges:[],actualNewGoalOrKindOrRelationChanges:[],actualP17RecordChanges:[],actualWholeP17FingerprintAndSemanticChecks:profileChecks,actualThreePartialDecisionEdgeAgreementChecks:edgeChecks,normalOutputBindingsChanged:outputDiffs,ordinaryP17PriorGreenCheckRetained:entry.ordinaryCurrentP17Terminal,existingNativeFinalSeal:entry.technicalFinalSealPath,sourceMappingRoleAndProtocolPayloadsNeedIndependentFollowups:true,currentNativeSemanticApproval:false,wholeSourceApproval:false,activeWrites:0,strictGain:0})
console.log(JSON.stringify({normalSource394:394,unresolvedScope:0,full394ModelExactlyExistingNative:true,actualNativeAdditionalPageChanges:0,original19PageChangesExact:true,protected15UnionExact:true,wholeP17FingerprintsExact:17,decisionEdgePartialAgreement:3,sourceProjectionOutputChangedBindings:outputDiffs.map(d=>d.path),activeWrites:0,strictGain:0}))
