// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync,readdirSync} from 'node:fs'
import {resolve,dirname,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import Ajv2020 from '/home/enpasos/projects/skillpilot/app/node_modules/ajv/dist/2020.js'
import {stableGoalBookJson} from '/home/enpasos/projects/skillpilot/app/scripts/goalBookModel.ts'
import {validatePreparedGoalDescriptionRolloutBatch,materializeGoalDescriptionRolloutBatchDualSummary} from '/home/enpasos/projects/skillpilot/app/scripts/materializeGoalDescriptionRolloutBatch.ts'
import {extractGoalDescriptionDualRoundResolutionSource,buildGoalDescriptionDualRoundResolution,validateGoalDescriptionDualRoundResolution,fingerprintGoalDescriptionReviewContext,fingerprintGoalDescriptionReviewCampaign} from '/home/enpasos/projects/skillpilot/app/scripts/validateGoalDescriptionDualRoundResolution.ts'
import {buildGoalDescriptionRolloutSynthesisRoundBinding,fingerprintGoalDescriptionRolloutSynthesisDecisionManifest,validateGoalDescriptionRolloutSynthesisDecisionManifest} from '/home/enpasos/projects/skillpilot/app/scripts/validateGoalDescriptionRolloutSynthesisDecisionManifest.ts'
import {buildGoalDescriptionRolloutResolutionSynthesis} from '/home/enpasos/projects/skillpilot/app/scripts/goalDescriptionRolloutResolutionSynthesis.ts'
const root='/home/enpasos/projects/skillpilot',own=dirname(fileURLToPath(import.meta.url)),sha=(v:Buffer|string)=>'sha256:'+createHash('sha256').update(v).digest('hex'),read=(p:string)=>JSON.parse(readFileSync(p).toString());const landscape=read(resolve(root,'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_CHEMIE.de.json'));const output:any[]=[]
for(const scope of ['seventeen','c441']){const dir=resolve(own,'native-d-'+scope),config=resolve(own,'native-d-'+scope+'.batch.config.json'),dual=await materializeGoalDescriptionRolloutBatchDualSummary(relative(root,config),false),input=dual.first.input,manifest=read(resolve(dir,'synthesis-decisions.json')),manifestBytes=readFileSync(resolve(dir,'synthesis-decisions.json')),index=read(resolve(dir,'resolution-index.json'));const ajv=new Ajv2020({allErrors:true,strict:true}),validate=ajv.compile(read(resolve(root,'contracts/goal-description-review/v1/goal-description-standalone-batch-resolution-index.schema.json')));assert.ok(validate(index),JSON.stringify(validate.errors));
for(const entry of index.resolutions){const path=resolve(dir,entry.resolutionPath),bytes=readFileSync(path),resolution=JSON.parse(bytes.toString()),result=await validateGoalDescriptionDualRoundResolution({resolution,dualSummary:dual.summary,dualSummaryBytes:dual.bytes,currentInput:input,landscape,first:dual.first,second:dual.second,synthesisDecisionManifestArtifact:{manifest,manifestBytes,manifestPath:'synthesis-decisions.json'}});assert.deepEqual(result.errors,[]);assert.equal(result.strictDescriptionComplete,true);assert.equal(entry.resolutionDigest,sha(bytes));assert.equal(entry.resolutionFingerprint,resolution.resolutionFingerprint);assert.equal(resolution.resolutionId,read(resolve(dir,'batch-manifest.json')).batchId+'-resolution-'+entry.goalId)}output.push({scope,currentProductionCanonicalNativeResolutionChecks:'PASS',resolutions:index.resolutions.length,indexSchema:'PASS',unchangedStandardIndexDigest:sha(readFileSync(resolve(dir,'resolution-index.json')))})}
console.log(JSON.stringify({role:'Targeted native current-production-canonical check of already materialized standard paired indices; exact inert book-model routing is retained',results:output,activeWrites:false,humanApproval:false,humanTrial:false,strictGain:0}))
