// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync,readdirSync,existsSync} from 'node:fs'
import {resolve,dirname,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import Ajv2020 from '/home/enpasos/projects/skillpilot/app/node_modules/ajv/dist/2020.js'
import {stableGoalBookJson} from '/home/enpasos/projects/skillpilot/app/scripts/goalBookModel.ts'
import {validatePreparedGoalDescriptionRolloutBatch,materializeGoalDescriptionRolloutBatchDualSummary} from '/home/enpasos/projects/skillpilot/app/scripts/materializeGoalDescriptionRolloutBatch.ts'
import {extractGoalDescriptionDualRoundResolutionSource,buildGoalDescriptionDualRoundResolution,validateGoalDescriptionDualRoundResolution,fingerprintGoalDescriptionReviewContext,fingerprintGoalDescriptionReviewCampaign} from '/home/enpasos/projects/skillpilot/app/scripts/validateGoalDescriptionDualRoundResolution.ts'
import {buildGoalDescriptionRolloutSynthesisRoundBinding,fingerprintGoalDescriptionRolloutSynthesisDecisionManifest,validateGoalDescriptionRolloutSynthesisDecisionManifest} from '/home/enpasos/projects/skillpilot/app/scripts/validateGoalDescriptionRolloutSynthesisDecisionManifest.ts'
import {buildGoalDescriptionRolloutResolutionSynthesis} from '/home/enpasos/projects/skillpilot/app/scripts/goalDescriptionRolloutResolutionSynthesis.ts'
import addFormats from '/home/enpasos/projects/skillpilot/app/node_modules/ajv-formats/dist/index.js'
import {validatePositiveGoalEvidenceRecordSemantics} from '/home/enpasos/projects/skillpilot/app/scripts/positiveGoalEvidenceProfileModel.ts'
const root='/home/enpasos/projects/skillpilot',own=dirname(fileURLToPath(import.meta.url)),base=resolve(own,'..')
const author=resolve(base,'chemie-four-final-images-native-d17-plus-c441-p18-technical-author-20261007-v1'),native=resolve(author,'native-root'),srcA=resolve(base,'chemie-four-final-current-native-d-independent-root-a-20261007-v1'),srcB=resolve(base,'chemie-four-final-native-targeted-d-independent-b-20261007-v1'),prior=resolve(base,'chemie-next17-native-paired-current-preparation-technical-20261007-v1')
const declared=new Map<string,any>(),sha=(v:Buffer|string)=>'sha256:'+createHash('sha256').update(v).digest('hex')
const bind=(p:string)=>{const b=readFileSync(p);return {path:relative(root,p),sha256:sha(b),bytes:b.length}}
const use=(p:string)=>{const b=bind(p);declared.set(p,b);return b}
const bytes=(p:string)=>{use(p);return readFileSync(p)}
const read=(p:string)=>JSON.parse(bytes(p).toString('utf8'))
const write=(p:string,v:any)=>{mkdirSync(dirname(p),{recursive:true});writeFileSync(p,Buffer.isBuffer(v)||typeof v==='string'?v:JSON.stringify(v,null,2)+'\n',{flag:'wx'})}
const copy=(a:string,b:string)=>write(b,bytes(a))
const verify=(dir:string,name:string,expected:string)=>{const p=resolve(dir,name);assert.equal(use(p).sha256,'sha256:'+expected);const s=read(p);for(const e of s.files??s.ownFiles){const target=e.path.startsWith('curricula/')||e.path.startsWith('app/')?resolve(root,e.path):resolve(dir,e.path);const b=use(target);assert.equal(b.sha256.replace('sha256:',''),e.sha256.replace('sha256:',''));assert.equal(b.bytes,e.bytes)};return {seal:bind(p),payloadsVerified:(s.files??s.ownFiles).length}}
const seals={A:verify(srcA,'own-final-reviewed-four-and-reused-fourteen.freeze.json','47846e044f2bb45176f41ced0f5b450b30fc54ed1fd4e3ad2b3953951b96f0d2'),B:verify(srcB,'final-dossier.seal.json','b140a60fd54619860ad68f6e6cc4bf243fd7f1d97bd190806d923d49c3fd9d39'),prior:verify(prior,'technical-preparation.final.freeze.json','3bb98cd10d0dfc05daeca13206782005178d1c440d041e91d2b39ce89cb9df33'),author:verify(author,'final-own-files-and-reused-inputs.freeze.json','828cd1893368ee6106be20335f022d88e3d6ad7d75fcfdabf8d94c682e4791d9')}
const sourceCanon=resolve(native,'candidate/canonical.final-image-candidate.json'),landscape=read(sourceCanon)
const allLower:any[]=[]
for(const scope of ['seventeen','c441']){
const existingOut=resolve(own,'native-d-'+scope),existingIndex=resolve(existingOut,'resolution-index.json')
if(existsSync(existingIndex)){
 const config=resolve(own,'native-d-'+scope+'.batch.config.json'),index=read(existingIndex)
 await validatePreparedGoalDescriptionRolloutBatch(relative(root,config));await materializeGoalDescriptionRolloutBatchDualSummary(relative(root,config),false)
 assert.equal(index.resolutions.length,scope==='seventeen'?17:1);for(const r of index.resolutions)assert.equal(r.strictDescriptionComplete,true)
 allLower.push({scope,config:bind(config),index:bind(existingIndex),nativePreparedBatchPASS:true,nativeDualSummaryPASS:true,nativeSynthesisPASS:true,resolutions:index.resolutions.map((r:any)=>({goalId:r.goalId,nativeLowerDescriptionComplete:r.strictDescriptionComplete,errors:[],standardResolutionId:read(resolve(existingOut,r.resolutionPath)).resolutionId,humanApproval:false,centralStrictGain:0})),sourceCanon:bind(sourceCanon),modelSourceLandscapePath:read(resolve(existingOut,'bundle/book-model.json')).source.landscapePath,upperCurrentCanonicalRouteRemaining:true});continue
}

const out=resolve(own,'native-d-'+scope),sourceBundle=resolve(native,'native-d-'+scope+'/bundle')
for(const n of readdirSync(sourceBundle,{recursive:true}) as string[]){const p=resolve(sourceBundle,n);try{readFileSync(p)}catch{continue};copy(p,resolve(out,'bundle',n))}
const bundle=read(resolve(out,'bundle/manifest.json')),model=read(resolve(out,'bundle/book-model.json'))
const roundA={base:resolve(native,'native-d-'+scope+'/round-a'),input:'description-review-input.json',campaign:'description-review-campaign.json',bundle:'review-bundle-manifest.json',batches:resolve(native,'native-d-'+scope+'/round-a/batches'),results:resolve(srcA,'native-d-'+scope+'/results')}
const roundB={base:resolve(native,'native-d-'+scope+'/round-b'),input:'description-review-input.json',campaign:'description-review-campaign.json',bundle:'review-bundle-manifest.json',batches:resolve(native,'native-d-'+scope+'/round-b/batches'),results:resolve(srcB,'native-d-'+scope+'/results')}
const input=read(resolve(roundA.base,roundA.input)),secondInput=read(resolve(roundB.base,roundB.input));assert.equal(stableGoalBookJson(input),stableGoalBookJson(secondInput))
const firstCampaign=read(resolve(roundA.base,roundA.campaign)),secondCampaign=read(resolve(roundB.base,roundB.campaign));assert.notEqual(firstCampaign.independenceGroupId,secondCampaign.independenceGroupId)
assert.equal(firstCampaign.blindToOtherReviews,true);assert.equal(secondCampaign.blindToOtherReviews,true)
const batchId='chemie-final18-current-native-paired-20261007-v1-'+scope,configPath=resolve(own,'native-d-'+scope+'.batch.config.json')
const previousManifest=read(resolve(native,'native-d-'+scope+'/batch-manifest.json'))
const cfg={...read(resolve(native,'configs/native-d-'+scope+'.batch.config.json')),batchId,outputDirectory:relative(root,out),baseGoalBookConfigPath:relative(root,resolve(native,'configs/full378.'+scope+'.book.config.json')),publicRoot:relative(root,resolve(native,'app/public'))};write(configPath,cfg)
const roundBinding=(directory:string,c:any)=>({directory,campaignId:c.campaignId,campaignDigest:fingerprintGoalDescriptionReviewCampaign(c),roundId:c.roundId,independenceGroupId:c.independenceGroupId,batchId:c.batches[0].batchId,batchInputFingerprint:c.batches[0].batchInputFingerprint})
const manifest={$schema:'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-rollout-batch-manifest.schema.json',schemaVersion:1,validationContract:'goal-description-rollout-batch-v1',batchId,subject:'chemie',subjectLabel:'Chemie',configPath:relative(root,configPath),configDigest:sha(readFileSync(configPath)),goalIds:cfg.goalIds,curriculumAtomicDenominatorAtPreparation:378,source:{...previousManifest.source,baseGoalBookConfigPath:cfg.baseGoalBookConfigPath},artifacts:{bundleDirectory:'bundle',bookModelPath:'bundle/book-model.json',bookModelDigest:model.digest,bundleManifestPath:'bundle/manifest.json',bundleFingerprint:bundle.bundleFingerprint,reviewInputFingerprint:input.reviewInputFingerprint,rounds:{first:roundBinding('round-a',firstCampaign),second:roundBinding('round-b',secondCampaign)}},reviewPolicy:{oneBatchPerRound:true,blindIndependentFirstPass:true,aiRecordsAreCandidatesOnly:true,automaticAcceptance:false}};write(resolve(out,'batch-manifest.json'),manifest)
for(const [name,r,c] of [['a',roundA,firstCampaign],['b',roundB,secondCampaign]] as any[]){const target=resolve(out,'round-'+name);copy(resolve(r.base,r.input),resolve(target,'description-review-input.json'));copy(resolve(r.base,r.campaign),resolve(target,'description-review-campaign.json'));copy(resolve(r.base,r.bundle),resolve(target,'review-bundle-manifest.json'));for(const n of ['prompt.md','criteria.md','contracts/goal-description-review-record.schema.json'])copy(resolve(name==='a'?r.base:roundB.base,n),resolve(target,n));const bid=c.batches[0].batchId;copy(resolve(r.batches,bid+'.input.jsonl'),resolve(target,'batches',bid+'.input.jsonl'));for(const suffix of ['records.jsonl','run.json'])copy(resolve(r.results,bid+'.'+suffix),resolve(target,'results',bid+'.'+suffix));const run=read(resolve(target,'results',bid+'.run.json'));assert.equal(run.blindToOtherRuns,true);assert.equal(run.independenceGroupId,c.independenceGroupId)}
await validatePreparedGoalDescriptionRolloutBatch(relative(root,configPath));const dual=await materializeGoalDescriptionRolloutBatchDualSummary(relative(root,configPath),true)
const sources=input.goals.map((g:any)=>{const a=extractGoalDescriptionDualRoundResolutionSource({artifacts:dual.first,goalId:g.goalId,label:'sealed A'}),b=extractGoalDescriptionDualRoundResolutionSource({artifacts:dual.second,goalId:g.goalId,label:'sealed B'});assert.deepEqual(a.errors,[]);assert.deepEqual(b.errors,[]);assert.equal(a.source!.decision,'keep');assert.equal(b.source!.decision,'keep');return {goal:g,first:a.source!,second:b.source!}})
const synthesizedAt=new Date(Math.max(...[...dual.first.resultPairs,...dual.second.resultPairs].map(({run}:any)=>Date.parse(run.completedAt)))+1000).toISOString()
const batchBinding={batchId,batchManifestDigest:sha(readFileSync(resolve(out,'batch-manifest.json'))),configDigest:manifest.configDigest,bundleFingerprint:bundle.bundleFingerprint,bookDigest:input.bookDigest,reviewInputFingerprint:input.reviewInputFingerprint,dualSummaryDigest:sha(dual.bytes),canonicalLandscapeDigest:sha(bytes(sourceCanon))}
const rounds={first:buildGoalDescriptionRolloutSynthesisRoundBinding(sources[0].first.binding,firstCampaign.batches[0].batchInputFingerprint),second:buildGoalDescriptionRolloutSynthesisRoundBinding(sources[0].second.binding,secondCampaign.batches[0].batchInputFingerprint)}
const expectedGoals=sources.map(({goal:g,first,second}:any)=>({goalId:g.goalId,effectiveSemanticKind:'curricularAtomic',goalFingerprint:g.goalFingerprint,pageFingerprint:g.pageFingerprint,goalReviewContextFingerprint:fingerprintGoalDescriptionReviewContext(g),finalText:{titleDe:g.currentTitleDe,titleEn:g.currentTitleEn,descriptionDe:g.currentDescriptionDe,descriptionEn:g.currentDescriptionEn},firstSource:first,secondSource:second}))
const decisions=sources.map(({goal:g,first,second}:any)=>({decisionId:batchId+'-decision-'+g.goalId,goalId:g.goalId,effectiveSemanticKind:'curricularAtomic',goalFingerprint:g.goalFingerprint,pageFingerprint:g.pageFingerprint,goalReviewContextFingerprint:fingerprintGoalDescriptionReviewContext(g),finalText:{titleDe:g.currentTitleDe,titleEn:g.currentTitleEn,descriptionDe:g.currentDescriptionDe,descriptionEn:g.currentDescriptionEn},resolutionDecision:'keep_current',evidenceRound:'first',records:{first:{recordId:first.binding.recordId,recordDigest:first.binding.recordDigest},second:{recordId:second.binding.recordId,recordDigest:second.binding.recordDigest}},rationaleDe:'Von Root delegierte technische Zusammenführung der tatsächlichen versiegelten A-/B-KEEP-Records über exakt denselben ganzen bilingualen Ziel-/Seiten-/Kontexteingang. Keine neue fachliche Bewertung, keine Quellen-Gesamtabdeckung, menschliche Freigabe oder strenger Nettozuwachs. A: '+first.record.rationale.slice(0,1400)+' B: '+second.record.rationale.slice(0,1400),rationaleEn:'Root-delegated factual synthesis of actual sealed independent A/B KEEP records over the exact whole bilingual goal, native page and unchanged D context. No new scientific judgment, whole-source closure, human approval or strict gain. Four changed images have fresh sealed A/B whole D judgments; fourteen identical D routes retain their prior sealed decisions without fresh review. P bodies remain independently reviewed and separate. A: '+first.record.understandingEvidence.essentialUnderstandingEn.slice(0,1400)+' B: '+second.record.understandingEvidence.essentialUnderstandingEn.slice(0,1400)}))
const payload={$schema:'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-rollout-synthesis-decision-manifest.schema.json',schemaVersion:1,synthesisContract:'goal-description-rollout-synthesis-decision-v1',manifestId:batchId+'-synthesis',authority:'ai_synthesis',synthesizedBy:'Codex technical integrator; Root-delegated factual sealed A/B KEEP synthesis, no new scientific reviewer',synthesizedAt,batch:batchBinding,rounds,decisions}
const synthesis={...payload,manifestFingerprint:fingerprintGoalDescriptionRolloutSynthesisDecisionManifest(payload as any)};const sv=await validateGoalDescriptionRolloutSynthesisDecisionManifest({manifest:synthesis as any,expected:{batch:batchBinding as any,rounds,synthesizedAt,goals:expectedGoals as any}});assert.deepEqual(sv.errors,[])
const synthesisPath=resolve(out,'synthesis-decisions.json');write(synthesisPath,synthesis);const synthesisBytes=readFileSync(synthesisPath),entries:any[]=[],results:any[]=[]
for(const s of sources){const decision=decisions.find(d=>d.goalId===s.goal.goalId)!,summaryGoal=dual.summary.goals.find((g:any)=>g.goalId===s.goal.goalId)!,fact=buildGoalDescriptionRolloutResolutionSynthesis({batchId,manifest:synthesis as any,decision:decision as any,summaryGoal,firstSource:s.first,secondSource:s.second});const resolution=buildGoalDescriptionDualRoundResolution({resolutionId:batchId+'-resolution-'+s.goal.goalId,goalId:s.goal.goalId,effectiveSemanticKind:'curricularAtomic',decision:'keep_current',synthesis:fact,dualSummaryBytes:dual.bytes,currentInput:input,firstSource:s.first,secondSource:s.second,synthesisDecisionManifest:{contract:'goal-description-rollout-synthesis-decision-v1',manifestId:synthesis.manifestId,manifestPath:'synthesis-decisions.json',manifestDigest:sha(synthesisBytes),manifestFingerprint:synthesis.manifestFingerprint,decisionId:decision.decisionId}});const v=await validateGoalDescriptionDualRoundResolution({resolution,dualSummary:dual.summary,dualSummaryBytes:dual.bytes,currentInput:input,landscape,first:dual.first,second:dual.second,synthesisDecisionManifestArtifact:{manifest:synthesis as any,manifestBytes:synthesisBytes,manifestPath:'synthesis-decisions.json'}});assert.deepEqual(v.errors,[]);assert.equal(v.strictDescriptionComplete,true);const path=resolve(out,'resolutions',s.goal.goalId+'.resolution.json');write(path,resolution);entries.push({goalId:s.goal.goalId,titleDe:s.goal.currentTitleDe,groupId:batchId,decision:'keep_current',resolutionPath:'resolutions/'+s.goal.goalId+'.resolution.json',resolutionDigest:sha(readFileSync(path)),resolutionFingerprint:resolution.resolutionFingerprint,strictDescriptionComplete:true});results.push({goalId:s.goal.goalId,errors:v.errors,nativeLowerDescriptionComplete:true,standardResolutionId:resolution.resolutionId,humanApproval:false,centralStrictGain:0})}
const index={$schema:'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-standalone-batch-resolution-index.schema.json',schemaVersion:2,indexContract:'goal-description-standalone-batch-resolution-index-v1',artifactSetId:batchId+'-strict-resolutions',subject:'Chemie',semanticKind:'curricularAtomic',batchGoalIds:cfg.goalIds,groups:[{groupId:batchId,artifactDirectory:'.',dualSummaryPath:'dual-summary.json',dualSummaryDigest:sha(dual.bytes),campaignGoalCount:dual.summary.goalCount,resolvedGoalCount:entries.length}],resolutions:entries};const ajv=new Ajv2020({allErrors:true,strict:true}),check=ajv.compile(read(resolve(root,'contracts/goal-description-review/v1/goal-description-standalone-batch-resolution-index.schema.json')));assert.ok(check(index),JSON.stringify(check.errors));write(resolve(out,'resolution-index.json'),index)
allLower.push({scope,config:bind(configPath),index:bind(resolve(out,'resolution-index.json')),nativePreparedBatchPASS:true,nativeDualSummaryPASS:true,nativeSynthesisPASS:true,resolutions:results,sourceCanon:bind(sourceCanon),modelSourceLandscapePath:model.source.landscapePath,upperCurrentCanonicalRouteRemaining:true})
}
const authorRecords=bytes(resolve(native,'candidate/positive18.author-candidates.review.jsonl')).toString().trim().split('\n').map(s=>JSON.parse(s))
const priorP=new Map(bytes(resolve(prior,'positive/current17.records.jsonl')).toString().trim().split('\n').map(s=>{const r=JSON.parse(s);return [r.goalId,r]}))
const ledger=read(resolve(native,'candidate/semantic-kinds.final-image-candidate.json')),kindById=new Map(ledger.decisions.map((d:any)=>[d.goalId,d.semanticKind])),goalById=new Map(landscape.goals.map((g:any)=>[g.id,g]))
const c441='c441d9e8-d9d9-5e55-a189-a37345541321',ownPc=JSON.parse(bytes(resolve(srcB,'native-p-root/review/c441.current-image.v2.review.jsonl')).toString())
const rootPc=read(resolve(srcA,'own-four-actual-pages-and-whole-inputs.first-pass.json')).c441PositiveProfile
const reviewId='chemie-final18-current-paired-reviewed-body-binding-technical-20261007-v1',records:any[]=[],Plineage:any[]=[]
const ajvP=new Ajv2020({allErrors:true,strict:true});addFormats(ajvP)
const validateP=ajvP.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json'))),validateCfg=ajvP.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-review-config.schema.json')))
for(const original of authorRecords){const goal:any=goalById.get(original.goalId),isC=original.goalId===c441
if(isC)assert.deepEqual(original.profile,ownPc.profile);else assert.deepEqual(original.profile,(priorP.get(original.goalId)as any).profile)
const record={...original,reviewId,reviewedAt:new Date().toISOString(),reviewer:'Codex technical integrator; factual materialization of sealed independent scientific profiles, no new review or human approval',reason:'Exact supplied whole profile body retained from paired sealed scientific reviews, with exact current native image-inclusive review input. '+(isC?'c441: fresh current Root A and independent B full two DE/EN cases.':'Prior17: blind A17/B16, and corrected P580b v3 independent B route; no new seventeen-profile science review.')+' Human false, E1/G1 AI candidate; no generation approval or strict gain.',reviewRunIds:[],dissent:[]}
const resourceDigests:any={};for(const link of goal.resourceLinks??[])if(link.type==='goal-visualization')resourceDigests[link.url]=sha(bytes(resolve(native,'app/public',link.url.slice(1))))
assert.ok(validateP(record),JSON.stringify(validateP.errors));assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(record,goal,resourceDigests,kindById.get(record.goalId)as string),[]);assert.equal(record.status,'needs_human_review');assert.equal(record.reviewAuthority,'ai_candidate');assert.equal(record.evidenceLevel,'E1');assert.equal(record.maximumClaimScope,'G1')
records.push(record);Plineage.push({goalId:record.goalId,profileFingerprint:record.profileFingerprint,reviewInputFingerprint:record.reviewInputFingerprint,bodyExactAuthor18:true,bodyExactPriorPaired17:!isC,currentActualResourceDigests:resourceDigests,scientificSeals:isC?[seals.A.seal,seals.B.seal]:[seals.prior.seal],priorRecordPath:isC?relative(root,resolve(srcB,'native-p-root/review/c441.current-image.v2.review.jsonl')):relative(root,resolve(prior,'positive/current17.records.jsonl')),noNewScientificJudgment:true})}
assert.equal(records.length,18);assert.equal((rootPc.decision??rootPc.verdict??rootPc.profileDecision).toLowerCase(),'keep')
const outP=resolve(own,'positive/current18.records.jsonl');write(outP,records.map(r=>JSON.stringify(r)).join('\n')+'\n')
const pcfg={...read(resolve(native,'configs/positive18.author-candidates.config.json')),reviewId,landscapePath:relative(root,sourceCanon),semanticKindLedgerPath:relative(root,resolve(native,'candidate/semantic-kinds.final-image-candidate.json')),reviewPath:relative(root,outP),reviewRunManifestPaths:[],scope:{label:'Exact current P18 paired-reviewed science bodies and current image-inclusive bindings; technical materialization only, E1/G1 AI candidates, Human false, strictgain0',goalIds:records.map(r=>r.goalId)}};assert.ok(validateCfg(pcfg),JSON.stringify(validateCfg.errors));write(resolve(own,'positive/current18.inert-candidate.config.json'),pcfg)
write(resolve(own,'positive/current18.future-active.config.json'),{...pcfg,landscapePath:'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_CHEMIE.de.json',semanticKindLedgerPath:'curricula/DE/Gymnasium/quality/goal-book-publication/chemie.semantic-kinds.json'})
write(resolve(own,'positive/exact-current18-profile-science-and-image-binding-lineage.technical.json'),{rootC441Judgment:rootPc,seals,profiles:Plineage,newScientificJudgments:false,other17BodiesReviewedAgain:false,humanApproval:false,humanTrial:false,strictGain:0})
write(resolve(own,'ready-incremental-native-D17-plus-c441-P18.technical.json'),{role:'Root-delegated mechanical sealed-review materialization only',D:allLower,P18:{records:bind(outP),futureActiveConfig:bind(resolve(own,'positive/current18.future-active.config.json')),currentCandidateConfig:bind(resolve(own,'positive/current18.inert-candidate.config.json')),nativePerRecordSemanticChecksPASS:true,currentActualImageBytesBound:true,needsHumanReview:18,approved:0,scientificBodiesExactPrior17PlusCurrentPairedC441:true,scienceRunIdsNotInvented:true,scientificLineage:bind(resolve(own,'positive/exact-current18-profile-science-and-image-binding-lineage.technical.json'))},nativeUpperFullMaterializerRemaining:true,currentRootProductionWritesRequired:true,activeWrites:false,humanApproval:false,humanTrial:false,strictGain:0})
write(resolve(own,'incremental-declared-inputs.technical.json'),{files:[...declared.values()]})
console.log(JSON.stringify({D17Lower:'PASS',Dc441Lower:'PASS',standardResolutionIds:true,D17Resolved:17,Dc441Resolved:1,P18NativePerRecordSemantics:'PASS',P18NeedsHumanReview:18,activeWrites:false,strictGain:0}))
