from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,copy
ROOT=Path(__file__).resolve().parents[7];B=Path(__file__).resolve().parent;BASE=B.parent;N=BASE/'chemie-four-final-images-native-d17-plus-c441-p18-technical-author-20261007-v1/native-root';OLD=BASE/'chemie-next17-native-paired-current-preparation-technical-20261007-v1';AM=BASE/'chemie-three-current-semantic-memory-independent-root-20261007-v1';V=ROOT/'curricula/DE/Gymnasium/quality/goal-visualization-review';VA=V/'chemie-four-evidenced-current-independent-root-v-a-20261007-v1'
j=lambda p:json.loads(p.read_text());sha=lambda p:'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest();rel=lambda p:str(p.relative_to(ROOT));logical=lambda x:'sha256:'+hashlib.sha256(json.dumps(x,sort_keys=True,ensure_ascii=False,separators=(',',':')).encode()).hexdigest()
def put(p,x):
 p.parent.mkdir(parents=True,exist_ok=True);assert not p.exists(),str(p);p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
canon=ROOT/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_CHEMIE.de.json';newcanon=N/'candidate/canonical.final-image-candidate.json';sem=ROOT/'curricula/DE/Gymnasium/quality/goal-book-publication/chemie.semantic-kinds.json';newsem=N/'candidate/semantic-kinds.final-image-candidate.json';qaPath=ROOT/'curricula/DE/Gymnasium/quality/goal-visualization-qa/chemie.qa.json';registryPath=ROOT/'curricula/DE/Gymnasium/quality/deep-understanding-rollout/de-gymnasium-math-physics.config.json';live=j(canon);candidate=j(newcanon);lb={g['id']:g for g in live['goals']};cb={g['id']:g for g in candidate['goals']};assert list(lb)==list(cb)
science=['fd309753-4d48-5570-a4ec-09dfeb20ff9c','22133f29-ef02-4408-8f8d-2bbea3275d91','9751b6d8-cde3-527b-b37c-babb6cee79d2'];images=['0bf26276-2780-506c-ac34-35dd44a29409','a44af1fa-5988-5b7d-b206-691c6bbf7dd4','9751b6d8-cde3-527b-b37c-babb6cee79d2','c441d9e8-d9d9-5e55-a189-a37345541321'];changed=[g for g in lb if lb[g]!=cb[g]];assert set(changed)==set(science+images)
fieldDiffs=[{'goalId':g,'changedFields':[k for k in set(lb[g])|set(cb[g])if lb[g].get(k)!=cb[g].get(k)]}for g in changed]
for g in lb:
 for field in ['id','requires','contains','applicability','dimensionTags','tags','weight','type']:
  assert lb[g].get(field)==cb[g].get(field),(g,field)
protected=j(OLD/'protected/current151-whole-goal-page-context-source-and-gate-bindings.actual.json');ids=protected['strictCompleteGoalIds'];assert len(ids)==151 and not set(ids)&set(changed)
for r in protected['rows']:assert lb[r['goalId']]==cb[r['goalId']]==r['wholeCurrentGoal']
currentQA=j(qaPath);pairedQA=copy.deepcopy(currentQA);authorQA={r['goalId']:r for r in j(N/'candidate/chemie.qa.final-image-candidate.json')['records']};currentRows={r['goalId']:r for r in currentQA['records']};pairedRows={r['goalId']:r for r in pairedQA['records']};pairs=[]
a_specs={images[0]:('', '711b'),images[1]:('.attempt-02','13c8'),images[2]:('.attempt-03','0b5c'),images[3]:('.attempt-04','950a')}
b_specs={images[0]:('1','selected-two.independent-v-b.first-pass.json','f8e'),images[1]:('1','selected-two.independent-v-b.first-pass.json','f8e'),images[2]:('2','selected975.independent-v-b.first-pass.json','8d96'),images[3]:('3','selectedc441.independent-v-b.first-pass.json','b44')}
for gid in images:
 suffix,prefix=a_specs[gid];sealA=VA/(gid+suffix+'.first-pass.freeze.json');assert sha(sealA).split(':')[1].startswith(prefix);sa=j(sealA);ap=ROOT/sa['verdict']['path'];assert sha(ap)==sa['verdict']['sha256'];a=j(ap);assert a['decision']=='KEEP'
 inc,bname,bprefix=b_specs[gid];bd=V/('chemie-four-held-friendly-comic-independent-v-b-20261007-increment-'+inc);sealB=bd/'first-pass.final.freeze.json';assert sha(sealB).split(':')[1].startswith(bprefix);sb=j(sealB);brecs=j(bd/bname)['records'];br=next(r for r in brecs if r['goalId']==gid);assert br['verdict']==br['scientificVerdict']==br['readability360Verdict']==br['readability680Verdict']=='KEEP'
 assetPath=N/'app/public/assets/goal-visualizations/chemie'/gid/(gid+'.png');assetSha=sha(assetPath);assert assetSha==a['candidateOriginal']['sha256'];assert assetSha.removeprefix('sha256:')==br['assetSha256'].removeprefix('sha256:')
 for row in sb['files']:
  p=bd/row['path'];assert sha(p).removeprefix('sha256:')==row['sha256'].removeprefix('sha256:')
 pair={'goalId':gid,'assetSha256':assetSha,'A':{'verdict':rel(ap),'verdictDigest':sha(ap),'seal':rel(sealA),'sealDigest':sha(sealA),'decision':a['decision']},'B':{'verdict':rel(bd/bname),'verdictDigest':sha(bd/bname),'seal':rel(sealB),'sealDigest':sha(sealB),'decision':br['verdict']},'technicalOnly':True,'humanApproval':False,'strictGain':0};pairs.append(pair)
 row=copy.deepcopy(authorQA[gid]);row['landscapePath']=rel(canon)
 for k,v in currentRows[gid].items():
  if k.startswith('human'):row[k]=v
 timestamp=max(a['completedAtUTC'],sb.get('sealedAtUtc',sb.get('sealedAtUTC','')))
 row.update({'umlautsCorrectChatGpt':'yes','contentApprovedChatGpt':'yes','aiApproved':'yes','aiApprovedAssetSha256':assetSha,'aiReviewedAt':timestamp,'chatGptReviewedAt':timestamp,'chatGptReviewer':'Actual independent visual review A and B; factual technical pair binding','chatGptNotes':'Paired exact-current PNG KEEP from sealed actual A/B native-width reviews. A seal '+pair['A']['sealDigest']+'; B seal '+pair['B']['sealDigest']+'. No image-author approval, new scientific judgment, Human Approval, Human Trial or strict gain. Exact receipts: '+rel(B/'visualization/four-exact-current-paired-V.technical.json')})
 pairedRows[gid].clear();pairedRows[gid].update(row)
for gid in ids:assert pairedRows[gid]==currentRows[gid]
qaNew=B/'integration-candidates/chemie.four-current-paired.qa.json';put(qaNew,pairedQA);put(B/'visualization/four-exact-current-paired-V.technical.json',{'schemaVersion':1,'role':'Technical binding of completed independent actual current PNG A/B judgments','pairs':pairs,'allFourCurrentKEEP':True,'allHumanFieldsRetainedExactly':True,'allOtherQARecordsExact':True,'newScientificJudgments':False,'humanApproval':False,'humanTrial':False,'strictGain':0})
reg=j(registryPath);oldChem=next(s for s in reg['subjects']if s['subject']=='chemie');newChem=copy.deepcopy(oldChem);newIndices=[rel(B/'native-d-seventeen/resolution-index.json'),rel(B/'native-d-c441/resolution-index.json')];newChem['resolutionIndexPaths']+=newIndices
c441=images[3];owners=[]
for ip in oldChem['resolutionIndexPaths']:
 if any(r['goalId']==c441 for r in j(ROOT/ip)['resolutions']):owners.append(ip)
supers=oldChem.get('resolutionSupersessions',[]);terminals=[p for p in owners if not any(s['goalId']==c441 and s['supersededIndexPath']==p for s in supers)];assert len(terminals)==1
newChem.setdefault('resolutionSupersessions',[]).append({'goalId':c441,'supersededIndexPath':terminals[0],'replacementIndexPath':newIndices[1]})
newChem['positiveEvidenceConfigPaths'].append(rel(B/'positive/current18.future-active.config.json'))
futureAM=[]
for name,oldSuffix in [('canonical-chemistry-sek1-foundations','semantic-atomicity/canonical-chemistry-sek1-foundations.config.json'),('canonical-chemistry-sek1-symbols-stoichiometry','semantic-atomicity/chemie-stoffmenge-nine-current-20261005-v1/canonical-chemistry-sek1-symbols-stoichiometry.config.json')]:
 cfg=j(AM/(name+'.inert-candidate.config.json'));cfg['landscapePath']=rel(canon);cfg['reportPath']=rel(B/'post-integration-reports'/(name+'.report.md'));dest=B/'atomicity'/(name+'.future-active.config.json');put(dest,cfg);oldPath='curricula/DE/Gymnasium/quality/'+oldSuffix;assert oldPath in newChem['semanticAtomicityConfigPaths'];newChem['semanticAtomicityConfigPaths']=[rel(dest)if p==oldPath else p for p in newChem['semanticAtomicityConfigPaths']];futureAM.append(rel(dest))
mcfg=j(AM/'current378.inert-candidate.config.json');mcfg['landscapePath']=rel(canon);mcfg['reportPath']=rel(B/'post-integration-reports/chemistry-current378-memory.report.md');mpath=B/'memory/current378.future-active.config.json';put(mpath,mcfg);newChem['memoryReviewConfigPath']=rel(mpath)
# P scope uniqueness after the one new P18 addition.
pclaimed=[]
for cp in newChem['positiveEvidenceConfigPaths']:pclaimed+=j(ROOT/cp)['scope']['goalIds']
assert len(pclaimed)==len(set(pclaimed))
# Existing protected current A/M scientific records remain exact per goal.
oldMemoryCfg=j(ROOT/oldChem['memoryReviewConfigPath']);oldMemory={r['goalId']:r for r in map(json.loads,(ROOT/oldMemoryCfg['reviewPath']).read_text().splitlines())};newMemory={r['goalId']:r for r in map(json.loads,(ROOT/mcfg['reviewPath']).read_text().splitlines())}
for gid in ids:assert oldMemory[gid]==newMemory[gid]
fileOps=[]
def fileop(source,target,label):
 fileOps.append({'kind':'replace-file-or-create','label':label,'source':rel(source),'sourceDigest':sha(source),'target':rel(target),'expectedOldDigest':sha(target)if target.exists()else None,'newDigest':sha(source),'preserveOriginalBytesInApplyHistory':target.exists()})
fileop(newcanon,canon,'Only three reviewed science corrections and four current PNG resource bindings; existing fd309 alt wording reviewed with v2')
fileop(newsem,sem,'Only existing semantic-kind bindings affected by three reviewed science changes')
fileop(qaNew,qaPath,'Four exact-current paired A/B PNG QA bindings; every human field retained')
mapTarget=ROOT/'curricula/DE/Gymnasium/mapping/DE-BY/gymnasium/bavaria_chemistry_source_extraction_to_canonical_chemistry.review.json';mapSource=OLD/'source/planned-BY-two-bounded-child-routes.current-review.json';fileop(mapSource,mapTarget,'Exactly two bounded direct-source child routes; historical global summaries unchanged')
navTarget=ROOT/'app/scripts/config/goal-books/navigation/de-gym-chemistry-national-atlas.view.json';navSource=OLD/'context/planned-active-national-atlas-navigation.view.json';fileop(navSource,navTarget,'One existing neutral chapter label; no topology, learner view or source membership changes')
for gid in images:
 for folder in ['app/public/assets/goal-visualizations/chemie','curricula/DE/Gymnasium/visualizations/chemie','backend/src/main/resources/static/assets/goal-visualizations/chemie']:
  p=Path(folder)/gid/(gid+'.png');fileop(N/p,ROOT/p,'Exact selected current PNG; old JPGs retained')
 p=Path('curricula/DE/Gymnasium/visualizations/chemie')/gid/'prompt.de.md';fileop(N/p,ROOT/p,'Exact prompt bound to selected current generation; archive former prompt')
fieldOp={'kind':'replace-subject-value','target':rel(registryPath),'subject':'chemie','expectedOldValueDigest':logical(oldChem),'oldValue':oldChem,'newValue':newChem,'newValueDigest':logical(newChem),'unrelatedSubjectsRetainedAtApply':True}
protectedReceipt={'schemaVersion':1,'currentStrictGoalIds':ids,'count':151,'all151CurrentAndCandidateWholeGoalsExact':True,'all151QARecordsExact':True,'all151MemoryRecordsExact':True,'currentCanonDigest':sha(canon),'candidateCanonDigest':sha(newcanon),'canonicalWholeGoalCount':479,'changedWholeGoalCount':6,'unaffectedWholeGoalCount':473,'changedWholeGoalFields':fieldDiffs,'allIdsRequiresContainsApplicabilityExact':True,'protectedWholeGoals':[{ 'goalId':g,'logicalDigest':logical(lb[g])}for g in ids],'protectedExistingGateAndSourceBindings':rel(OLD/'protected/current151-whole-goal-page-context-source-and-gate-bindings.actual.json'),'protectedExistingNativeGateRecords':rel(OLD/'protected/current151-exact-native-D-page-context-and-whole-PAMV.records.json'),'privateOperativeViewUnchanged':{'path':'curricula/DE/Gymnasium/quality/goal-description-review/chemie/review-views/chemie-m7-full-canonical.view.json','digest':sha(ROOT/'curricula/DE/Gymnasium/quality/goal-description-review/chemie/review-views/chemie-m7-full-canonical.view.json')},'allEightInflightRetained':{'path':'curricula/DE/Gymnasium/quality/goal-description-review/in-flight-work-ledger.json','value':j(ROOT/'curricula/DE/Gymnasium/quality/goal-description-review/in-flight-work-ledger.json'),'count':len(j(ROOT/'curricula/DE/Gymnasium/quality/goal-description-review/in-flight-work-ledger.json')['activeBatchConfigPaths'])},'MathPhysicsSubjectValues':[{ 'subject':s['subject'],'valueDigest':logical(s)}for s in reg['subjects']if s['subject']in ['mathematik','physik']],'neutralAtlasLabelOnlyImpactEvidence':rel(OLD/'context/actual-current-to-planned-active-national-atlas-page-diff.json'),'neutralLabelDoesNotReplacePrivateReviewTopology':True,'noNewScienceOrReview':True,'humanApproval':False,'humanTrial':False,'strictGain':0}
assert protectedReceipt['allEightInflightRetained']['count']==8
put(B/'protected/guarded-current151-and-all-unrelated-fields.actual.json',protectedReceipt)
commands=[['app/node_modules/.bin/tsx','app/scripts/positiveGoalEvidenceReview.ts','--config='+rel(B/'positive/current18.future-active.config.json'),'--mode=check']]
for c in futureAM:commands.append(['app/node_modules/.bin/tsx','app/scripts/semanticAtomicityReview.ts','--config='+c,'--mode=check'])
commands.append(['app/node_modules/.bin/tsx','app/scripts/memoryCardReview.ts','--config='+rel(mpath),'--mode=check'])
commands.append(['node','scripts/check_goal_visualization_assets.mjs'])
plan={'schemaVersion':1,'role':'Root-only guarded Chem integration; no active writes by preparer','preparedAt':datetime.now(timezone.utc).isoformat(),'incrementalPacketSeal':{'path':rel(B/'incremental-native-D17-c441-P18.freeze.json'),'digest':sha(B/'incremental-native-D17-c441-P18.freeze.json')},'fileOperations':fileOps,'sharedRegistryOperation':fieldOp,'protected151':rel(B/'protected/guarded-current151-and-all-unrelated-fields.actual.json'),'postIntegrationNativeTargetedCommands':commands,'postIntegrationNativeDCurrentCanonicalFinalizer':'post-integration-native-current-D-validation.technical.mts','sourceRouteBoundaries':'Use already reviewed exact two-route candidate; no whole-source closure, historical global summaries and remaining mappings untouched','neutralChapterLabel':'Use previously sealed exact one-label plan. 17 atlas page contexts affected; protected 151 page contexts exact. Operative private review view and seven actual learner composition views retained.','noHistoricalFilesRemoved':True,'noInflightRemovedBeforeActualCentralGain':True,'remainingGate':'Root must run actual central M7 once all intended integrations are current, compare exact protected151 strict IDs and Math807/Physics478, and truthfully report terminal strict gains; this preparer performs no global QS.','nativeUpperRoutingLimitation':'Exact reviewed native BookModel source path is inert-relative candidate/canonical.final-image-candidate.json. Do not rewrite reviewed bundle/model/campaign fingerprints. Use targeted native current-canonical finalizer on standard index outputs after production copies; original upper materializer expects that exact inert path.','activeWrites':False,'humanApproval':False,'humanTrial':False,'strictGain':0}
put(B/'guarded-root-current-Chem18-integration-plan.technical.json',plan)
print(json.dumps({'plannedFileOperations':len(fileOps),'sharedRegistryOnlyChemFields':True,'all151Protected':True,'wholeGoalsUnchanged':473,'newIndices':2,'P18ScopeUnique':True,'inflightRetained':8,'activeWrites':False}))
