import json,pathlib
OUT=pathlib.Path(__file__).resolve().parent
ids=json.loads((OUT/'actual-deterministic-new-IDs-and-authoring-contracts.AUTHOR-INERT.json').read_text())['ids']
CLASS='273809d9-bc31-5c1b-8a58-149dd61d2ba0';PERF='50e07b86-428c-5f9c-8c7e-0d0669343af5';MONO='1826fe19-4d06-5183-9b41-9121ae1cc219';PRICE='3bcb976d-3e45-5c62-81ac-5ed909df202b'
task='''**Lokaler LK-Praxisabschluss: Markt und Preis mit bewusst gewählter Marktsteuerung –48 BE.** Alle Märkte, Zahlen, Regeln und öffentlichen Budgets sind fiktive Unterrichtsmodelle. Die Marktsteuerung ist die ausdrücklich gewählte Wahlalternative; sie wird nicht als Pflicht aller LK-Kurse behauptet. Tabellen, Achsenbeschriftungen und genaue Koordinatenfolgen gelten als vollständige textuelle Diagrammdarstellung. Kein Bild, keine privaten Daten und kein Rechtswissen sind vorausgesetzt.

**Material A – Marktbedingungen.**40 unabhängige Schraubenanbieter verkaufen identische Ware. Alle Preise sind bekannt, Wechsel ist kostenlos, Eintritt offen. Ein kleiner Anbieter verliert oberhalb des Marktpreises2 EUR sämtliche Kunden.40 Cafés sind dagegen durch Lage und Atmosphäre differenziert; Wechsel kostet Zeit. Ein Café verkauft bei p=2/3/4/5 EUR q=60/45/30/15Becher/Tag. Gesonderte gemeinsame Preisänderungen aller Cafés ergeben Q=1000/900/800/700. Diese Gesamtwerte sind keine Aggregation der eigenen Preisänderung eines einzelnen Cafés. Bei austauschbaren Caféleistungen und kostenloser Ausweichmöglichkeit würde im vorgegebenen Benchmark die Einzelanbieter-Preislinie bei3 horizontal verlaufen.

**Material B – Polypol und Monopol.**Auf einem gesonderten homogenen Markt geben die Tabellen p=8/11/14 und gesamte Nachfrage QD=80/60/40 sowie gesamtes Angebot QS=80/100/120 an; stückweise gerade Verbindung ist zulässig. Unter wirksamer Konkurrenz gilt p=8,Q=80. Derselbe Bedarf kann auch von einem einzigen vor Eintritt geschützten Anbieter versorgt werden. Für ihn sind nur drei zulässige Unterrichtsoptionen gegeben: p=8,q=80/Gewinn0; p=11,q=60/Gewinn180; p=14,q=40/Gewinn240. Stückkosten8, keine Kapazitätsgrenze unter80. Zusätzliche Geschäfte zwischen40 und80 hätten für Käufer eine Zahlungsbereitschaft mindestens8, für einige strikt darüber; externe Effekte fehlen. Es wird nur zwischen den angebotenen Optionen gewählt, kein kontinuierliches Optimum behauptet.

**Material C – Preisdifferenzierung.**Kurszugänge kosten variabel2 EUR je Zugang, Fixkosten50. A kauft5Zugänge bei12 oder25bei6;B kauft30bei12 oder35bei6. Nur6/12sind zulässig, Kapazität reicht. Zunächst personengebundene Gruppenprüfung ohne Zusatzkosten, kein Weiterverkauf. Alternative: A6/B12. Eine Variation erlaubt Weiterverkauf; dafür wird die Gesamtnachfrage des effektiven Einheitspreises6 unterstellt. Eine zweite Variation erhöht nur die Zusatzkosten der Gruppentrennung auf60.

**Material D – gewählte Marktsteuerung.**Ein weiterer Modellmarkt hat QD=100−2p und QS=2p. Für p=20/25/30 gilt QD=60/50/40 und QS=40/50/60. Ein vollständig durchgesetzter Höchstpreis20 lässt ohne Zusatzregeln höchstens QS verkaufen. Ziele: niedriger Preis und breite Versorgung. Als alternative Maßnahme gilt ein Mindestpreis30 mit glaubwürdigem Regierungsankauf des gesamten Überschusses. Ziele: höheren Produzentenerlös, private Versorgung mindestens45 und öffentliche Ausgaben höchstens500 EUR. Lager- und Verwaltungskosten sind unbekannt; Erlös ist kein Gewinn.

1. Leiten Sie aus A Anbieterform und Preis-/Absatzspielraum der Schraubenanbieter und Cafés ab. Begründen Sie mit mehreren Bedingungen und passen Sie den Schluss an den austauschbaren Café-Benchmark an.40Firmen allein ist kein Wettbewerbsnachweis. **8 BE**
2. Stellen Sie die individuelle Cafébeziehung, die gesonderte Gesamtnachfrage und die individuelle Preisnehmer-Benchmark aus A fachlich beschriftet dar. Zeichnen/beschreiben Sie für den vollkommenen Gesamtmarkt aus B beide Kurven und den Gleichgewichtspunkt. Unterscheiden Sie Einzelmenge und Gesamtmenge; behaupten Sie keine universelle Knickkurve. **8 BE**
3. Vergleichen und bewerten Sie die Marktversorgung aus B unter Polypol und geschütztem Monopol. Erklären Sie die private Optionswahl und die mögliche Ineffizienz; grenzen Sie sie von einem unbewiesenen allgemeinen Optimum oder exakten Wohlfahrtsverlust ab. **8 BE**
4. Diskutieren Sie anhand C die Gewinnsteigerung durch getrennte Preise gegenüber beiden Einheitspreisen. Bewerten Sie die Weiterverkaufsvariation und die60-EUR-Zusatzkostenvariation. **8 BE**
5. Erläutern Sie an den gegebenen Marktbedingungen zwei Preisfunktionen als Bedingungen dezentraler Marktkoordination. Verwenden Sie konkrete Informationen/Anreize, ohne aus einem höheren Preis automatisch einen gesellschaftlichen Vorteil abzuleiten. **8 BE**
6. Analysieren und veranschaulichen Sie beide Maßnahmen aus D im Preis-Mengen-Diagramm. Leiten Sie Mengen und gegebenenfalls öffentliche Ausgaben ab und bewerten Sie die jeweils angegebenen Ziele und eine Zuteilungs-/Kostenbegrenzung. **8 BE**

**Bewertung:** Teilpunkte für tragfähige unvollständige Antworten, äquivalente korrekt begründete Urteile und präzise textuelle Diagramme.48BE, bestanden ab29. Fehlt eine der vier neuen Kernleistungen vollständig oder wird sie durchgehend fachlich falsch ausgeführt, höchstens28BE: Bedingungen→Verhalten; Einzel-/Gesamtdiagramm; materialgebundener Gewinnvergleich; Eingriffsdiagramm→Zielbewertung. Einzelne Rechen-/Zeichenfehler begründen diese Grenze nicht. Keine zusätzliche Aufgabenquote.'''
tasken='''**Local advanced-course practice: markets/prices with deliberately selected market steering –48 marks.** All markets, figures, rules and public budgets are fictional teaching models. Steering is the expressly chosen elective alternative, not a requirement of every LK course. Labelled tables and exact coordinate sequences are complete textual diagram representations. No image, private data or actual-law recall is needed.

**A – Conditions.**40 independent bolt suppliers sell identical products, with all prices known, free switching and open entry. A small supplier loses all buyers above market price2.40 cafés differ in location/atmosphere and switching takes time. One café has prices2/3/4/5 and individual cups/day60/45/30/15. Separate common price changes across cafés yield aggregate1000/900/800/700, not aggregation of one firm’s unilateral price change. An interchangeable/free-switching benchmark gives one small café a horizontal price-taking line at3.

**B – Many-supplier and monopoly supply.**In a separate homogeneous market prices8/11/14 give aggregate demand80/60/40 and supply80/100/120; straight segments may connect them. Effective competition gives price8,quantity80. A single entry-protected supplier faces the same needs but chooses only among supplied options8/80/profit0,11/60/profit180,14/40/profit240. Unit cost8 and capacity at least80. Extra trades40–80 have willingness to pay at least8, some strictly above8; no externalities. No continuous optimum is asserted.

**C – Differentiation.**Course access has unit cost2,fixed cost50. A buys5 at12 or25 at6;B buys30 at12 or35 at6. Only6/12 are allowed, capacity sufficient. Initially groups are person-verified without extra cost and resale is impossible. Alternative A6/B12. One variation permits resale and stipulates common effective-price6 demand; another changes only segmentation cost to60.

**D – Selected steering.**Another model has QD=100−2p,QS=2p. Prices20/25/30 give demand60/50/40 and supply40/50/60. Fully enforced ceiling20 permits at most supplied quantity to sell without extra rules; goals are low price and broad service. Alternative floor30 includes credible public purchases of all excess supply; goals are producer revenue, private service at least45 and public spending at most500. Storage/administration costs are unknown; revenue is not profit.

1. Derive bolt/café supplier structure and pricing/sales scope from several A conditions and revise it for the interchangeable café benchmark. Forty firms alone does not establish competition. **8**
2. Represent individual café demand, separate aggregate demand and the individual price-taking benchmark with correct labels. Represent B’s perfectly competitive aggregate supply/demand and equilibrium. Distinguish individual/aggregate quantities; assert no universal kink. **8**
3. Compare and evaluate B’s supply under competition/monopoly. Explain the private option choice and possible inefficiency, limiting claims about a general optimum or exact welfare loss. **8**
4. Discuss C’s profit gain against both uniform prices and evaluate resale and60extra-cost variations. **8**
5. Explain two price functions as conditions for decentralised coordination with material-based information/incentives, without automatically equating a higher price with social benefit. **8**
6. Analyse and represent both D interventions in diagrams; derive quantities and where relevant public spending, assess each supplied goal and one allocation/cost limitation. **8**

**Assessment:** Partial credit for coherent incomplete answers, equivalent reasoned conclusions and precise textual diagrams.48marks, pass29. If one new core performance is wholly absent or consistently incorrect, maximum28: conditions→behaviour; individual/aggregate representation; material profit comparison; intervention diagram→goal evaluation. Isolated mistakes do not trigger that cap. No extra-task quota.'''
solution='''**Vollständiger Erwartungshorizont; gleichwertige fachlich begründete Lösungen erhalten Punkte.**

1. Beide Anbieterzahlen40 ergeben ein Polypol, aber kein identisches Verhalten. Schrauben: Gleichartigkeit+Preiskenntnis+kostenfreier Wechsel/Eintritt lassen oberhalb2den eigenen Absatz verschwinden; individuelle Preisnehmerrolle. Cafés: Differenzierung/Wechselzeit begründen begrenzten Preis-/Absatzspielraum, z.B.q45bei3→q30bei4. Austauschbare Leistungen und kostenloses Wechseln beseitigen diese Grundlage unter den gegebenen Informationsbedingungen; Benchmarkpreis3ist vorgegeben, kein neu berechnetes Optimum.8: Anbieterform2, konkrete Mehrbedingungen2, Verhaltensfolge2, begründete Variation2.

2. Individuell(q,p): (60,2),(45,3),(30,4),(15,5), horizontale Menge dieses Cafés/Tag,vertikaler EUR-Preis. Gesamt(Q,p): (1000,2),(900,3),(800,4),(700,5), andere Mengenskala;900ist nicht45, die Änderungssituationen sind verschieden. Einzelpreisnehmerlinie horizontal p3; nicht Gesamtmarktnachfrage. B-Gesamtdiagramm: Nachfrage(80,8),(60,11),(40,14), Angebot(80,8),(100,11),(120,14), Schnitt(80,8). Fallende individuelle Cafékurve ist materialbedingt; universelle Knickform nicht verlangt.8: individuelle Punkte/Achsen2, getrennte Gesamtgrößen2, Benchmark+vollkommener Gesamtmarkt2, Form-/Skalenbegründung2.

3.240ist unter den drei Optionen maximal: Monopol p14,q40 statt Konkurrenz p8,Q80. Eintrittssperre/fehlende Alternative ermöglichen den profitablen Mengenrückgang. Bei identischer Technik und Stückkosten8bleiben zwischen40und80nach Material zumindest einige wechselseitig vorteilhafte Geschäfte aus: möglicher Allokationsverlust. Der höhere Gewinn allein misst nicht Wohlfahrt. Keine Aussage über unbezeichnete Preise oder exakten Verlust; Polypolversorgung im Material günstiger in Menge/Zugang, nicht eine universelle Bewertung jedes Monopols.8: Optionsrechnung2, Versorgungvergleich2, bedingter Ineffizienzmechanismus2, Bewertungsgrenze2.

4. Einheit12:(12−2)×35−50=300;Einheit6:(6−2)×60−50=190. Trennung A6/B12:100+300−50=350, Vorteil50zum besten einheitlichen Preis. Mit übertragbarem Zugang und vorgegebener effektiver6-Nachfrage wird nur190erreicht; alte Abschottung fehlt.60Zusatzkosten ergeben290,unter300. Unterschiede der Nachfrage und wirksame Trennung ermöglichen Vorteile, zusätzliche Trennungskosten/Arbitrage können sie beseitigen.8: beide Einheitspreise2, Trennung/Mehrgewinn2, Varianten3, begründete Reichweitenbegrenzung1.

5. Informationsfunktion: sichtbare Preise bündeln Knappheits-/Nachfrageinformationen; Schraubenkunden können Anbieter vergleichen, Cafépreisunterschiede müssen wegen Qualitätsunterschieden interpretiert werden. Anreiz-/Lenkungsfunktion: erreichbare Erlöse können Anbieter zu Kapazität/Eintritt lenken, höhere Preise Käufer zu Alternativen; gilt nur bei tatsächlicher Wechsel-/Eintrittsmöglichkeit. Rationierungsfunktion als gleichwertiges zweites Beispiel: höhere Preise begrenzen Nachfrage über Zahlungsbereitschaft, sichern aber nicht gleiche Zugangschancen. Polypol/Monopolvergleich zeigt, dass Preis auch geschützte Macht widerspiegeln kann; Funktionsbehauptung ist an wirksame Bedingungen gebunden.8: zwei passende Funktionen mit konkretem Materialbezug je3, Bedingungen/keine automatische Wohlfahrtsfolgerung2.

6. D-Kurven schneiden sich bei(Q50,p25). Höchstpreis20: Nachfrage60,Angebot40,Überhang20,maximal40Verkäufe; niedriger Preis für tatsächlich Versorgte, weniger Gesamtversorgung als50; Zuteilung einzelner Käufer unbestimmt. Mindestpreis30: Nachfrage40,Angebot60,Überschuss20,öffentlicher Kauf20×30=600. Produzentenerlös1800statt1250,kein bewiesener Gewinn. Private45-Mindestversorgung verfehlt,500-Budget überschritten schon vor weiteren Kosten. Diagramm horizontale Regeln20/30mit markierten Angebots-/Nachfragemengen; glaubwürdiger Ankauf und Vollzug nötig.8: Kurven/Gleichgewicht+Regeln2, Höchstpreisgrößen/Ziele2, Mindestpreisgrößen/Budget2, differenzierte Ziele/Begrenzung2.'''
solutionen='''**Complete marking guide; equivalent justified answers earn credit.**

1. Both forty-seller markets are many-supplier by count, but not behaviour. Homogeneous bolts plus price knowledge/free switching/entry eliminate sales above2; individual price-taking. Café differentiation/switching costs permit limited pricing scope, e.g.45at3→30at4. Interchangeability/free switching remove that basis; benchmark3is supplied, not a newly computed optimum.8: classification2, multiple concrete conditions2, behavioural consequence2, revised reasoning2.
2. Individual(q,p):(60,2),(45,3),(30,4),(15,5), labelled café cups/day and euros. Aggregate(Q,p):(1000,2),(900,3),(800,4),(700,5) on a different quantity scale;900is not45 and the change scenarios differ. Individual price-taking is horizontal at3, not aggregate demand. B aggregate demand(80,8),(60,11),(40,14), supply(80,8),(100,11),(120,14), equilibrium(80,8). Café slope is material-specific, with no universal kink.8: individual points/axes2, aggregate distinction2, benchmark/perfect-market diagram2, shape/scale reasoning2.
3.240is the highest listed profit: monopoly14/40 versus competition8/80. Entry protection and absent alternatives sustain a profitable restriction. With identical unit cost8, material states that some mutually beneficial trades40–80are missed, implying possible allocative loss. Profit is not welfare. No unlisted price optimum/exact loss follows; competition improves stated quantity/access here, not in every imaginable monopoly.8: options2, supply comparison2, conditional inefficiency2, limits2.
4. Uniform12profit300;uniform6profit190. Separate prices yield350,a50gain against the best uniform option. Transferable access and stipulated effective-price6demand yield190; cost60alone gives290below300. Demand differences and enforceable separation permit gains; arbitrage/extra costs can remove them.8: uniform calculations2,differentiation/gain2,variants3,bounded discussion1.
5. Information: visible prices communicate scarcity/demand and enable bolt comparison; café quality differences must be considered. Incentive/allocation: expected receipts may motivate entry/capacity; prices may move buyers towards alternatives, conditional on switching/entry. Rationing by willingness to pay is an equivalent second function but does not ensure equal access. Protected-monopoly prices can reflect power, so higher price is not automatically welfare improvement.8: two concrete material-based functions3each,conditions/limit2.
6. Equilibrium50/25. Ceiling20: demand60,supply40,shortage20,at most40sales; lower price for recipients but less overall service; actual allocation unknown. Floor30: demand40,supply60,public purchases20cost600. Revenue1800versus1250,not proven profit; private45target and budget500fail before extra costs. Diagram marks horizontal20/30and corresponding quantities; implementation/full purchases must be credible.8: equilibrium/lines2,ceiling quantities/goals2,floor/budget2,conditional evaluation2.'''
new=[ids[k] for k in ['supplier-behaviour','imperfect-polypol-diagram','price-differentiation-profit','optional-intervention-diagram']]
practice={'id':ids['local-market-practice'],'title':'Markt und Preis mit gewählter Marktsteuerung selbstständig bearbeiten','titleEn':'Independently handle markets/prices with selected market steering','description':'Die lernende Person kann die vorgegebenen LK-Marktfälle selbstständig auswerten, Anbieterreaktionen aus Bedingungen ableiten, Einzel- und Gesamtmarktdiagramme darstellen, Marktversorgung und Preisdifferenzierungsgewinn begründet beurteilen sowie die bewusst gewählte Marktsteuerung im Modell analysieren.','descriptionEn':'The learner can independently analyse the supplied advanced-course market cases, derive supplier reactions, represent individual/aggregate diagrams, judge supply and differentiated-pricing profit, and analyse the deliberately selected steering alternative.','weight':1,'tags':['LK','Practice','Assessment'],'type':'atomic','contains':[],'requires':new+[MONO,PRICE],
 'dimensionTags':{'framework':'canonical-gymnasium-economics','phase':'Katalog','courseLevels':['LK'],'demandLevel':'AB3'},'applicability':{'jurisdiction':['DE-BB']},
 'extendedData':{'applicabilityMappingInheritance':'boundary','applicabilityFromRequires':True,'authorSourceRole':'local-endpoint-mandatory-market-plus-explicitly-selected-optional-steering','authorEvidenceStatus':'unreviewed INERT author candidate'},
 'examData':{'reviewStatus':'needs_review','coveredGoalIds':new+[MONO],'coveredStrands':['WW_WIRTSCHAFT','WW_GESELLSCHAFT','WW_POLITIK'],'demandLevels':['AB1','AB2','AB3'],'taskContent':task,'taskContentEn':tasken,'solutionContent':solution,'solutionContentEn':solutionen,'scoring':{'maxPoints':48,'passingPoints':29,'steps':[{'id':'s'+str(i+1),'points':8,'description':de,'descriptionEn':en} for i,(de,en) in enumerate([('Mehrbedingungen und neue Anbieterreaktion','Multiple conditions and revised supplier reaction'),('Individuelle/aggregierte Polypoldiagramme','Individual and aggregate many-supplier diagrams'),('Marktversorgung und begrenzter Monopolmechanismus','Supply and bounded monopoly mechanism'),('Gewinnvergleich und Trennungsvarianten','Profit comparison and separation variations'),('Preisfunktionen unter Marktbedingungen','Price functions under market conditions'),('Eingriffsdiagramme und Zielbewertung','Intervention diagrams and goal evaluation')])]},'reviewNote':'INERT author candidate only. No independent science, release, learner performance, M4/M6/M7 or human approval; selected steering is optional at original-course level.'},'resourceLinks':[]}
(OUT/'whole-local-BB-LK-practice-DEEN-material-answer-rubric.AUTHOR-INERT.json').write_text(json.dumps(practice,ensure_ascii=False,indent=2)+'\n')
(OUT/'actual-local-practice-whole-coverage-and-prerequisite-limits.AUTHOR-INERT.json').write_text(json.dumps({'wholePractice':practice,'coveredWholeNewGoalContracts':new,'wholeRetainedMonopolyContractCovered':True,'sourceOriginalAllFiveMarketAndPricePerformancesAddressed':['Task1 criteria/forms/behaviour','Task2 perfect AND imperfect diagrams','Task3 polypol/monopoly supply comparison/evaluation','Task4 profit differentiation discussion','Task5 price functions'],'optionalOriginalPerformance':'Task6 selected steering analysis/diagram/evaluation; no blanket LK compulsory claim','old273NotBroadenedOrCertifiedAgain':True,'old50e07FullElasticitySurplusContractNotClaimedCovered':True,'price3bBeyondSourceDecentralVsCentralContractIsPrerequisiteNotClaimedCovered':True,'noTaskQuota':True,'status':'needs_independent_whole_science_review'},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'practiceId':practice['id'],'tasks':6,'marks':48,'pass':29,'status':'needs_review'}))
