import copy,hashlib,json,pathlib,uuid,datetime
OUT=pathlib.Path(__file__).resolve().parent;ROOT=OUT.parents[6]
assert ROOT.name=='skillpilot'
LAND='605bdaf6-32d5-56fd-8d92-5a80c2fd2901'
NS=uuid.UUID(LAND)
def uid(name):return str(uuid.uuid5(NS,'BB-LK-market-p23:'+name))
IDS={k:uid(k) for k in ['supplier-behaviour','imperfect-polypol-diagram','price-differentiation-profit','optional-intervention-diagram','mandatory-market-branch','optional-market-steering-branch','local-market-practice']}
CLASS='273809d9-bc31-5c1b-8a58-149dd61d2ba0';PERF='50e07b86-428c-5f9c-8c7e-0d0669343af5';MONO='1826fe19-4d06-5183-9b41-9121ae1cc219';PRICE='3bcb976d-3e45-5c62-81ac-5ed909df202b'
def write(name,obj):
 p=OUT/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def goal(key,title,en,de,descen,requires,optional=False):
 return {'id':IDS[key],'title':title,'titleEn':en,'description':de,'descriptionEn':descen,'weight':1,'tags':['subject:Wirtschaft','canonical:gymnasium-de','jurisdiction:DE-BB','LK'],'contains':[],'requires':requires,'examples':[],
 'type':'atomic','dimensionTags':{'framework':'canonical-gymnasium-economics','phase':'Katalog','courseLevels':['LK'],'demandLevel':'AB2'},'applicability':{'jurisdiction':['DE-BB']},
 'sourceRef':'Amtlicher RLP GOST Wirtschaftswissenschaft Berlin-Brandenburg 2022, LK 2. Kurshalbjahr Mikroökonomie, S.22–23; '+('Wahlalternative Marktsteuerung, keine allgemeine Pflicht aller LK-Lernenden.' if optional else 'Pflichtfeld Markt und Preis.'),
 'extendedData':{'authorSourceRole':'optional-selected-market-steering' if optional else 'mandatory-market-and-price','authorEvidenceStatus':'INERT E1/G1 author candidate, independent review pending'},'resourceLinks':[]}
goals=[
 goal('supplier-behaviour','Anbieterverhalten aus Marktbedingungen ableiten','Derive supplier behaviour from market conditions',
 'Die lernende Person kann aus der Anbieterstruktur und gegebenen Bedingungen zu Produktgleichheit, Information, Ausweichmöglichkeiten und Marktzutritt ableiten, welchen Preis- und Absatzspielraum Anbieter in einem vorgegebenen Markt haben, und die Ableitung beim Wechsel einer maßgeblichen Bedingung begründet anpassen.',
 'The learner can derive suppliers’ pricing and sales scope from supplier structure and supplied conditions concerning product similarity, information, alternatives and market entry, and revise the reasoning when a decisive condition changes.',[CLASS]),
 goal('imperfect-polypol-diagram','Unvollkommenes Polypol im Preis-Mengen-Diagramm darstellen','Represent an imperfect many-supplier market in price–quantity diagrams',
 'Die lernende Person kann für ein vorgegebenes Modell eines unvollkommenen Polypols die Preis-Absatz-Beziehung eines einzelnen Anbieters aus Material in einem beschrifteten Preis-Mengen-Diagramm darstellen, von der Gesamtnachfrage unterscheiden und die gezeigte Form mit den gegebenen Marktbedingungen erklären, ohne daraus eine universell gültige Kurvenform abzuleiten.',
 'The learner can use supplied material to plot and label an individual supplier’s price–sales relationship in a model of an imperfect many-supplier market, distinguish it from aggregate demand and explain the represented shape through the given market conditions without asserting a universal curve shape.',[IDS['supplier-behaviour']]),
 goal('price-differentiation-profit','Gewinnwirkungen von Preisdifferenzierung diskutieren','Discuss profit effects of price differentiation',
 'Die lernende Person kann anhand gegebener gruppenspezifischer Nachfrage, Kosten und Bedingungen für getrennte Preise diskutieren, ob und wie Preisdifferenzierung gegenüber einem einheitlichen Preis den Gewinn verändert, und den Schluss bei veränderten Trennungs-, Weiterverkaufs- oder Zusatzkostenbedingungen begrenzen.',
 'The learner can use supplied group-specific demand, costs and conditions for separate prices to discuss whether and how price differentiation changes profit relative to a uniform price, and qualify the conclusion when separation, resale or additional-cost conditions change.',[IDS['supplier-behaviour']]),
 goal('optional-intervention-diagram','Staatseingriffe im Marktmodell analysieren und bewerten','Analyse and evaluate intervention using a market diagram',
 'Die lernende Person kann einen vorgegebenen staatlichen Preiseingriff im Preis-Mengen-Modell darstellen, daraus Mengen-, Verteilungs- und gegebenenfalls Budgetwirkungen unter den Materialannahmen ableiten und den Eingriff anhand gegebener Ziele und Vollzugsbedingungen begründet bewerten.',
 'The learner can represent a supplied public price intervention in a price–quantity model, derive quantity, distribution and where relevant budget effects under the material assumptions, and evaluate it using supplied objectives and implementation conditions.',[PERF],True)
]

def case(id,de,en,ans,ansen,focus,focusen):
 return {'id':id,'taskDemandDe':de,'taskDemandEn':en,'expectedPerformanceDe':ans,'expectedPerformanceEn':ansen,'understandingFocusDe':focus,'understandingFocusEn':focusen}
CASES={}
CASES['supplier-behaviour']=[
case('homogeneous-bolts-versus-differentiated-repair',
 'Alle Angaben sind fiktive Modellannahmen. Markt A:40 unabhängige kleine Schraubenanbieter verkaufen identische Schrauben; Kundschaft kennt alle Preise, kann ohne Zusatzkosten wechseln, neue Anbieter können eintreten. Ein Anbieter verkauft bei Marktpreis2 EUR bis zur eigenen Kapazität; bei einem Preis über2 wechseln seine Käufer vollständig. Markt B:40 unabhängige Reparaturdienste unterscheiden sich durch Lage, Öffnungszeiten und überprüfbare Leistung. Käufer kennen veröffentlichte Preise, Wechsel kostet Zeit. Für einen Dienst sind20 EUR/30Aufträge,22 EUR/24Aufträge und24 EUR/17Aufträge gegeben. Leite für A und B möglichen Preis- und Absatzspielraum aus mehreren Bedingungen ab. Darf man aus40Anbietern gleiche Preisnehmerrolle ableiten? Erkläre anschließend die Wirkung, wenn in B alle Leistungen austauschbar werden und Wechselkosten entfallen; kein Preis oder Gewinn außerhalb der Angaben ist zu erfinden.',
 'All facts are fictional model assumptions. Market A has40 independent small bolt suppliers selling identical products; buyers know all prices and switch at no extra cost; entry is open. A seller can sell up to capacity at the market price of2 euros but loses all buyers above2. Market B has40 independent repair services differentiated by location, opening hours and verifiable service. Buyers know published prices but switching takes time. One firm has supplied price/order options20/30,22/24 and24/17. Derive pricing and sales scope in A/B from several conditions. Does40 sellers imply identical price-taking? Then explain the change if B’s services become interchangeable and switching costs disappear; invent no unsupplied price or profit.',
 'Beide Märkte sind nach Anbieterzahl Polypole. In A machen Produktgleichheit, vollständige Preiskenntnis und kostenloses Wechseln einen eigenen Aufschlag nicht tragfähig; Eintritt begrenzt zusätzlich dauerhafte Sonderstellungen. Der einzelne Anbieter nimmt2 EUR hin, seine Mengenentscheidung bleibt kapazitätsgebunden. In B besteht trotz vieler Anbieter begrenzter eigener Preisspielraum: bei22 bleiben24Aufträge, bei24 noch17. Differenzierung und Wechselaufwand verhindern vollständiges Ausweichen, ohne unbegrenzte Marktmacht zu schaffen.40 allein erklärt die unterschiedlichen Reaktionen nicht. Werden Produkte austauschbar und Wechselkosten beseitigt, schwindet unter den gegebenen Informationsannahmen dieser Spielraum; ein höherer eigener Preis verliert Kundschaft an Alternativen. Ein konkreter neuer Marktpreis oder optimaler Gewinn ist nicht gegeben.',
 'Both are many-supplier markets by seller count. In A homogeneous products, complete price knowledge and costless switching make an individual markup unsustainable; entry additionally limits durable special positions. The seller takes2 euros as given and chooses sales within capacity. In B differentiation and switching effort provide limited pricing scope despite many firms:24 orders remain at22 and17 at24. Alternatives still constrain the firm, so scope is not unlimited. Forty sellers alone does not explain the contrast. Making services interchangeable and removing switching costs eliminates this source of pricing scope under the given information assumptions; buyers can leave a higher-priced seller. No new equilibrium price or profit optimum is supplied.',
 'Anbieterzahl mit mehreren konkreten Wettbewerbsbedingungen zu einer Verhaltensableitung verbinden.','Link seller count and multiple competitive conditions to a behavioural inference.'),
case('three-suppliers-entry-and-switching-change',
 'Fiktiver Baustoffmarkt: Drei voneinander unabhängige Firmen verkaufen denselben Baustoff. Preise aller Firmen sind sichtbar. Anfangs haben Kunden lange bindende Lieferverträge; neue Anbieter benötigen eine knappe Zulassung. Eine Firma kann deshalb einige bestehende Kunden bei einem begrenzten Aufschlag halten; die Reaktionen der anderen beiden Firmen sind nicht gegeben. Die neue Modellregel beendet die Vertragsbindung und erlaubt kurzfristigen Markteintritt zusätzlicher Lieferanten. Bestimme die Anbieterform im alten Zustand und leite einen bedingten Preis-/Absatzspielraum ab. Begründe, was sich mit Wechsel und Eintritt verändert. Prüfe die Behauptungen: Drei Firmen beweisen eine Absprache; nach der Reform folgt zwingend ein bestimmter gemeinsamer Preis. Es ist keine konkrete Spieltheorie- oder Kartellrechtskenntnis vorausgesetzt.',
 'Fictional building-material market: three independent firms sell the same material and all prices are visible. Initially buyers have long binding supply contracts and entrants need a scarce licence. A firm can retain some customers after a limited markup; rivals’ reactions are unspecified. A new model rule ends contractual lock-in and permits quick entry of extra suppliers. Classify the initial supplier structure and derive conditional pricing/sales scope. Explain what changes with switching and entry. Assess: three firms prove coordination; the reform necessarily produces a particular common price. No game-theory or actual cartel-law recall is needed.',
 'Anfangs liegt nach Anbieterzahl ein Oligopol vor. Vertragsbindung und Zulassungsengpass stützen einen begrenzten Aufschlag trotz Produktgleichheit und sichtbarer Preise; die anderen Firmen und mögliche Reaktionen begrenzen ihn, sind aber nicht quantifiziert. Das Ende der Bindung erleichtert Ausweichen; zusätzlicher Eintritt erweitert Alternativen und schwächt den alten Preisspielraum. Ob daraus ein Polypol wird, hängt von der tatsächlichen späteren Anbieterzahl ab. Drei unabhängige Anbieter sind kein Beleg für eine Absprache. Ohne Nachfrage-, Kosten- und Reaktionsdaten folgt kein bestimmter neuer gemeinsamer Preis. Eine schlüssige bedingte Ableitung genügt, keine erfundene Gleichgewichtsrechnung.',
 'Initially the market is an oligopoly by seller count. Lock-in and scarce entry permission support a limited markup despite homogeneous products and transparent prices; rivals constrain it but their responses are not quantified. Removing lock-in enables switching, and entry expands alternatives, weakening the previous pricing scope. Whether the later market is many-supplier depends on the realised seller count. Three independent sellers do not prove coordination. Without demand, cost and response data no particular common price follows. A coherent conditional inference suffices; no invented equilibrium calculation is warranted.',
 'Verhalten beim Wechsel realer Eintritts-/Ausweichbedingungen anpassen, ohne Absprache oder Zahlen zu erfinden.','Revise behaviour when actual entry/switching constraints change without inventing coordination or numbers.')]

CASES['imperfect-polypol-diagram']=[
case('differentiated-cafes-linear-material',
 'Fiktive20Cafés bieten unterschiedliche Lage und Atmosphäre; Preise und Qualität sind bekannt. Das Material beschreibt drei getrennte Modellbeziehungen, keine simultane Aggregation der Einzelkurve: Ein Café verkauft bei Preis p=2,3,4,5 EUR die Mengen q=60,45,30,15Becher/Tag. Bei einer gemeinsamen Preisänderung aller Cafés beträgt die Gesamtnachfrage Q=1000,900,800,700Becher/Tag. Als Benchmark eines vollkommenen Polypols wird für einen kleinen Anbieter bei Marktpreis3 eine horizontale Absatzlinie bis q=60 angegeben; oberhalb3 kann er nichts verkaufen. Zeichne die individuelle Café-Preis-Absatz-Beziehung und die gesonderte Gesamtnachfrage mit Menge horizontal und Preis vertikal, passenden Einheiten und unterscheidbaren Skalen. Vergleiche mit der gegebenen Preisnehmer-Benchmark. Erkläre die begrenzte Preisreaktion aus Differenzierung. Darf Q=900 als Einzelabsatz oder eine Knickform als universell verlangt behandelt werden? Tabellen oder genau beschriftete Koordinaten sind als textuelle Diagrammspezifikation zulässig; kein Bild ist Voraussetzung.',
 'Twenty fictional cafés differ in location and atmosphere, with prices and quality known. The material gives three separate model relationships, not simultaneous aggregation of the individual curve: one café sells q=60,45,30,15 cups/day at p=2,3,4,5 euros. If all cafés’ prices change together, aggregate demand is Q=1000,900,800,700 cups/day. A perfectly competitive benchmark for one small seller is horizontal at market price3 up to q=60; above3 it sells nothing. Plot individual café demand and separate aggregate demand with quantity horizontal, price vertical, units and distinct scales. Compare with the supplied price-taking benchmark. Explain limited price sensitivity through differentiation. Can aggregate900 be individual sales or a kink universally required? Labelled coordinates/tables are accepted as textual diagram specifications; an image is not required.',
 'Individuelle Kurve: Achsen q(Becher dieses Cafés/Tag) und p(EUR/Becher); Punkte(60,2),(45,3),(30,4),(15,5), im Modell fallend geradlinig verbunden. Gesamtnachfrage separat: Q(Becher aller Cafés/Tag),p; Punkte(1000,2),(900,3),(800,4),(700,5). Q=900 ist nicht q=45 und die Materialtabellen werden nicht durch20×q künstlich gleichgesetzt, weil sie unterschiedliche Änderungssituationen beschreiben. Die individuelle Preisnehmer-Benchmark verläuft bei p=3 horizontal bis60; sie ist nicht die fallende Gesamtmarktnachfrage eines vollkommenen Marktes. Differenzierung lässt manche Käufer beim höheren Einzelpreis bleiben, sodass eigene Preiswahl mit Absatzverlust verbunden ist. Die konkrete fallende Linie folgt den gelieferten Daten, nicht einer zwingenden universellen Knickkurve. Gewinnoptimum oder Angebotskurve des Cafés sind ohne weitere Daten nicht ableitbar.',
 'Individual diagram: horizontal q(cups sold by this café/day), vertical p(euros/cup); points(60,2),(45,3),(30,4),(15,5), connected by the model’s falling straight line. Separate aggregate diagram: Q(all cafés’ cups/day),p; points(1000,2),(900,3),(800,4),(700,5). Aggregate900 is not individual45; multiplying the individual curve by20 would incorrectly equate different change scenarios. The given individual price-taking benchmark is horizontal at3 up to60, not the falling aggregate demand of a perfectly competitive market. Differentiation retains some buyers at a higher individual price, linking own price choice to lower sales. This shape follows supplied observations; no universal kink is required. No profit optimum or café supply curve follows without additional data.',
 'Einzelanbieter-/Gesamtmarktdiagramm und Preisnehmer-Benchmark fachlich trennen.','Distinguish individual/aggregate diagrams and the price-taking benchmark.'),
case('differentiated-services-piecewise-provided-data',
 'Fiktive12Dienste bieten unterschiedliche Abholzeiten. Für einen Dienst ergibt eine Befragung p=8/10/12/14 EUR und q=50/48/25/10Aufträge pro Woche. Für gemeinsame Preisänderungen aller Dienste werden gesondert p=8/10/12/14 und Q=480/420/300/180 angegeben. Im Unterrichtsmodell sind zwischen den Messpunkten gerade Verbindungsstücke erlaubt; außerhalb gibt es keine Daten. Bei10 ist die individuelle Nachfrage links deutlich weniger preissensitiv als rechts. Stelle beide Beziehungen getrennt dar und erkläre, was die geänderte Neigung im Material zeigt. Unterscheide individuelle Menge48 von Gesamtmenge420. Ein alternatives Modell mit gleichartigen Leistungen und kostenfreiem Wechsel gibt dem einzelnen kleinen Dienst eine horizontale Preisnehmerlinie bei10. Ist eine geknickte oder eine gerade Einzelkurve für jedes unvollkommene Polypol zwingend? Kein strategisches Rivalenreaktionsgesetz ist angegeben.',
 'Twelve fictional services offer different collection times. One firm’s survey gives p=8/10/12/14 euros and q=50/48/25/10 weekly orders. Separate common price changes across all services give Q=480/420/300/180 at those prices. Straight segments may connect measured points; nothing is supplied outside them. At10 the individual relationship is less price-sensitive on the left than on the right. Represent the two relationships separately and explain the change in slope in this material. Distinguish individual48 from aggregate420. A homogeneous, costless-switching benchmark gives a small firm a horizontal price-taking line at10. Must every imperfect many-supplier market have a kinked or straight individual curve? No strategic rival-response rule is supplied.',
 'Individuell(q,p): (50,8),(48,10),(25,12),(10,14), korrekt beschriftet stückweise verbunden; aggregiert(Q,p): (480,8),(420,10),(300,12),(180,14) auf gesonderter Mengenskala. Von8 auf10 sinkt q nur2, von10 auf12 um23: die Angaben zeigen unterschiedliche lokale Preisempfindlichkeit, im Diagramm eine Änderung der Neigung.48 ist die Wochenmenge eines Dienstes,420 die Gesamtnachfrage bei gemeinsamer Änderung. Die horizontale individuelle Benchmark bei10 beruht auf Austauschbarkeit und kostenfreiem Ausweichen. Das vorliegende Muster ist datenbedingt; weder ein Knick noch eine Gerade ist eine universelle Pflichtform des unvollkommenen Polypols. Aus den Befragungswerten folgt kein unbezeichnetes Rivalenreaktionsmodell und keine Fortsetzung außerhalb der Tabelle.',
 'Individual(q,p) points(50,8),(48,10),(25,12),(10,14) are correctly labelled and joined piecewise; aggregate(Q,p) points(480,8),(420,10),(300,12),(180,14) use a separate quantity scale. Raising price8→10 loses2 orders, while10→12 loses23, showing different local price sensitivity and a slope change.48 is one firm’s weekly sales;420 is aggregate demand under a common price change. The horizontal individual benchmark at10 follows interchangeability and costless switching. This pattern is data-specific; neither a kink nor a straight line is universal for imperfect many-supplier markets. The survey does not establish an unspecified rival-response model or extrapolation beyond the table.',
 'Datenbedingte Kurvenneigung erklären und Grenzen der Formbehauptung einhalten.','Explain data-specific slopes and limit shape claims.')]

CASES['price-differentiation-profit']=[
case('separable-ticket-groups-profit-and-costs',
 'Fiktive Veranstaltung, ohne Kapazitätsengpass: variable Kosten4 EUR je Besuch, gleiche Fixkosten100 EUR. Gruppe A kauft bei p=10 genau10Tickets, bei p=6 genau30; Gruppe B kauft bei10 genau40, bei6 genau50. Nur diese beiden Preise sind zulässig. Einheitlicher Preis gilt für beide Gruppen. Bei getrennten Preisen kann die Zugehörigkeit kostenlos überprüft werden; Weiterverkauf ist im Modell unmöglich. Berechne Gewinn=(Preis−4)×Menge−100 für beide Einheitspreise und für A6/B10. Diskutiere den Gewinnunterschied und seine Bedingungen. Ändere dann nur die Zusatzkosten der Gruppenprüfung auf100 EUR: Ist getrennter Preis noch gewinnsteigernd gegenüber dem besten einheitlichen? Eine allgemeine gesellschaftliche Vorteilhaftigkeit ist aus Gewinn nicht zu behaupten.',
 'Fictional event with no capacity constraint: variable cost4 euros per visit and the same fixed cost100. Group A buys10 tickets at10 or30 at6; B buys40 at10 or50 at6. Only these two prices are allowed. A uniform price applies to both groups. Group membership can initially be verified at no extra cost and resale is impossible. Compute profit=(price−4)×quantity−100 for each uniform price and A6/B10. Discuss the gain and its conditions. Then change verification cost alone to100: does differentiation still raise profit against the best uniform option? Profit does not establish a general social benefit.',
 'Einheitspreis10:50Besuche, Erlös500, variable Kosten200, Gewinn200. Einheitspreis6:80Besuche, Erlös480, variable Kosten320, Gewinn60. Getrennt A6/B10: A liefert(6−4)×30=60, B(10−4)×40=240; abzüglich100Fixkosten ergibt200. Hier gibt es gegenüber dem besten Einheitspreis10 KEINE Gewinnsteigerung:200=200. Mehr Absatz allein reicht nicht. Mit100zusätzlichen Prüfkosten sinkt der Differenzierungsgewinn auf100 und liegt darunter. Gruppentrennung und fehlender Weiterverkauf ermöglichen verschiedene Preise, beweisen aber keinen zusätzlichen Gewinn; Nachfrage/Kosten müssen tatsächlich passen. Gewinn ist keine Gesamtwohlfahrtsrechnung.',
 'Uniform10:50 visits, revenue500, variable cost200, profit200. Uniform6:80 visits, revenue480, variable cost320, profit60. Separate A6/B10: A contributes(6−4)×30=60 and B(10−4)×40=240; subtracting100 fixed cost yields200. Differentiation gives NO gain over the best uniform10:200=200; extra sales alone do not suffice. Adding100 verification cost lowers differentiated profit to100. Segmentation and no resale permit separate prices but do not establish a gain; actual demand/costs must support it. Firm profit is not a total-welfare calculation.',
 'Mehr Menge oder verschiedene Preise nicht automatisch mit Mehrgewinn gleichsetzen.','Do not equate extra sales or separate prices automatically with higher profit.'),
case('course-access-positive-gain-and-resale-limit',
 'Fiktiver Kurszugang: variable Kosten2 EUR je Zugang, Fixkosten50 EUR. Zwei überprüfbare Gruppen, kein Kapazitätsengpass: A kauft bei Preis12 genau5, bei6 genau25; B kauft bei12 genau30, bei6 genau35. Nur6 und12 sind zulässig. Bei getrennten Preisen A6/B12 fallen zunächst keine weiteren Kosten an und Zugänge sind personengebunden. Berechne die Gewinne der zwei Einheitspreise und der Trennung. Diskutiere den Vorteil relativ zum besten Einheitspreis. Nun sind Zugänge übertragbar: B kann sämtliche gewünschten30Zugänge von A zu6 erhalten; für den Vergleich gilt insgesamt dieselbe Nachfrage bei einem gemeinsamen effektiven Preis6. Kann man den alten Mehrgewinn halten? Benenne außerdem die höchste zusätzliche Trennungskostenbelastung, bei der die ursprüngliche Trennung noch mindestens so viel Gewinn wie der beste Einheitspreis bringt.',
 'Fictional course access: variable cost2 per access and fixed cost50. Two verifiable groups with no capacity constraint: A buys5 at12 or25 at6; B buys30 at12 or35 at6. Only6 and12 are allowed. A6/B12 initially has no extra cost and access is tied to the person. Compute both uniform profits and differentiated profit; discuss the gain against the best uniform price. Access then becomes transferable: B can obtain all30 desired accesses from A at6; for this comparison total demand is stipulated to equal demand at a common effective price6. Can the old gain persist? Also identify the largest extra segmentation cost for which initial differentiation still yields at least the best uniform profit.',
 'Einheitspreis12:35Zugänge, Gewinn(12−2)×35−50=300. Einheitspreis6:60Zugänge, Gewinn(6−2)×60−50=190. Getrennt: A(6−2)×25=100, B(12−2)×30=300, abzüglich50 ergibt350. Gegenüber dem besten einheitlichen Preis beträgt der Mehrgewinn50. Mit maximal50Zusatzkosten bleibt Gleichstand zu300; darunter ist der Vorteil positiv, darüber nicht. Übertragbarkeit verhindert hier die wirksame Abschottung: B zahlt effektiv6, unter der vorgegebenen neuen Gesamtnachfrage bleibt190 statt350. Der alte Vorteil verlangt durchsetzbare Zuordnung und fehlende Arbitrage; die Aussage gilt für die gegebenen zulässigen Preise, nicht für ein allgemeines kontinuierliches Optimum oder eine Wohlfahrtsrangliste.',
 'Uniform12:35 accesses, profit(12−2)×35−50=300. Uniform6:60 accesses, profit(6−2)×60−50=190. Differentiation contributes100 from A and300 from B; subtract50 to get350, a gain of50 over the best uniform price. Extra segmentation cost up to50 preserves at least a tie at300; below50 the advantage is positive. Transferability breaks effective separation: B pays effectively6 and the stipulated common-price demand yields190 instead of350. The gain depends on enforceable group assignment and no arbitrage, and is bounded to the permitted prices, not a continuous optimum or welfare ranking.',
 'Echten Gewinnvergleich mit Kosten- und Weiterverkaufsgrenzen begründet diskutieren.','Discuss an actual profit comparison with cost and resale limits.')]

CASES['optional-intervention-diagram']=[
case('binding-price-ceiling-shortage',
 'Fiktiver Markt, keine aktuellen Rechtsregeln: Nachfrage QD=100−2p, Angebot QS=2p für p=0…50. Tabellen p=10/20/25/30 ergeben QD=80/60/50/40 und QS=20/40/50/60. Ein Höchstpreis20 wird vollständig durchgesetzt; ohne Nebenregeln wird höchstens die angebotene Menge verkauft. Ziele sind niedriger Preis und möglichst viele versorgte Käufer. Stelle Angebot/Nachfrage, Gleichgewicht und Höchstpreis dar; leite Nachfrage, Angebot und Knappheit ab. Bewerte die beiden Ziele getrennt und begrenze Aussagen über tatsächliche Zuteilung an einzelne Personen. Diagramm als Koordinaten-/Tabellenspezifikation ist erlaubt.',
 'Fictional market with no actual legal rules: QD=100−2p and QS=2p for p=0…50. Prices10/20/25/30 give demand80/60/50/40 and supply20/40/50/60. A ceiling20 is fully enforced; absent further rules at most supplied quantity is sold. Objectives are a low price and serving as many buyers as possible. Represent demand/supply, equilibrium and the ceiling; derive demand, supply and shortage. Evaluate the objectives separately and limit claims about who receives goods. Labelled coordinates/tables are accepted.',
 'Im(Q,p)-Diagramm liegt Nachfrage fallend durch(80,10),(60,20),(50,25),(40,30), Angebot steigend durch(20,10),(40,20),(50,25),(60,30); Schnittpunkt(50,25). Horizontale Preisgrenzep=20 liegt darunter: Nachfrage60,Angebot40,Nachfrageüberhang20, maximal40Verkäufe statt50. Für tatsächliche Käufer ist der Preis niedriger; das Ziel hoher Versorgung wird im gegebenen Angebotsmodell verfehlt. Welche Personen beliefert werden, ist ohne Zuteilungsregel unbekannt. Vollzug ist vorausgesetzt, mögliche Qualitäts-/Langfristfolgen nicht beziffert; kein allgemeines Verbot jeder Preisgrenze folgt.',
 'Demand in(Q,p) falls through(80,10),(60,20),(50,25),(40,30); supply rises through(20,10),(40,20),(50,25),(60,30), meeting at(50,25). Horizontal ceiling20 is below equilibrium: demand60, supply40, shortage20, at most40 sales instead of50. Successful buyers pay less, but broad service deteriorates in this supply model. Allocation to particular people is unknown without a rule. Enforcement is stipulated and quality/long-run effects unquantified; no universal rejection of ceilings follows.',
 'Bindende Preisregel aus Diagramm analysieren und an konkreten Zielen bewerten.','Analyse a binding price rule through the diagram and evaluate specific objectives.'),
case('price-floor-government-purchase-budget',
 'Fiktiver Markt: dieselben linearen Regeln QD=100−2p,QS=2p, mit Tabellen p=20/25/30/35: QD=60/50/40/30;QS=40/50/60/70. Statt einer Preisgrenze gilt jetzt ein durchgesetzter Mindestpreis30. Die Modellregierung kauft den gesamten Angebotsüberschuss zum Preis30; Verwaltungs-/Lagerkosten sind unbekannt. Ziele: Produzentenerlös stützen, öffentliche Ausgaben höchstens500 EUR, private Versorgung mindestens45Einheiten. Stelle den Eingriff im Diagramm dar, bestimme private Menge, öffentliche Käufe und Ausgaben und bewerte die Ziele. Erlös ist nicht Gewinn; ohne Regierungsankauf wäre die vermarktete Menge nicht60. Texte und Tabellen genügen als Diagrammspezifikation.',
 'Fictional market with the same linear rules QD=100−2p,QS=2p. At prices20/25/30/35, demand is60/50/40/30 and supply40/50/60/70. An enforced floor30 replaces the ceiling. The model government buys all excess supply at30; administration/storage costs are unknown. Goals are producer-revenue support, public spending at most500 euros and private service at least45 units. Represent the intervention, calculate private sales, government purchases and spending, and evaluate the goals. Revenue is not profit; without government buying, sold quantity would not be60. Text/tables suffice.',
 'Gleichgewicht bleibt(50,25); Preisuntergrenzep=30 darüber. Nachfrage40,Angebot60,Überschuss20. Private Käufer erwerben40,Regierung20; Ausgaben20×30=600 EUR schon vor Lager-/Verwaltungskosten. Produzentenerlös aus60×30=1800 steigt gegenüber50×25=1250, aber Kosten/Nettoertrag sind nicht gegeben. Budgetziel500 wird verfehlt, private Mindestversorgung45 ebenfalls. Das Erlösziel wird unter glaubwürdigem Vollankauf erreicht; ohne Ankauf würden nur40private Einheiten verkauft. Der Eingriff ist anhand dieser Ziele begründet zu beurteilen, nicht als universell immer gut oder schlecht.',
 'Equilibrium remains(50,25); floor30 is above it. Private demand40, supply60, excess20: private buyers buy40 and government20, costing20×30=600 before storage/administration. Producer revenue60×30=1800 exceeds50×25=1250, but costs/profit are unspecified. Spending cap500 and private-service minimum45 fail. Revenue support holds if full purchases are credible; without buying only40 private units sell. Evaluate these goals without a universal good/bad claim.',
 'Unterschiedliche Mengen, Transferbudget und Erlös/Gewinn sauber aus Eingriffsmodell trennen.','Distinguish quantities, transfer budget and revenue/profit in an intervention model.')]

UNDERSTANDING={
 'supplier-behaviour':('Anbieterverhalten hängt von Struktur und konkret wirksamen Wettbewerbsbedingungen ab; Firmenzahl allein trägt keine Preis-/Absatzprognose.','Supplier behaviour depends on structure and effective competition conditions; count alone cannot predict pricing or sales.'),
 'imperfect-polypol-diagram':('Individuelle Preis-Absatz-Beziehung und Gesamtmarktnachfrage sind verschiedene Modellgrößen; die Kurvenform folgt Materialbedingungen, nicht dem Wort Polypol.','Individual price–sales and aggregate demand are different model quantities; shape follows the material, not the label many-supplier.'),
 'price-differentiation-profit':('Preisgruppen wirken über tatsächlich verschiedene Mengen und Deckungsbeiträge; Mehrgewinn hängt an durchsetzbarer Trennung, Nachfrage und Zusatzkosten.','Group pricing acts through actual quantities and contribution margins; profit gains depend on enforceable separation, demand and extra costs.'),
 'optional-intervention-diagram':('Ein bindender Preiseingriff verändert Nachfrage-/Angebotsmengen und Verteilung; Zielerreichung und gegebenes Budget sind getrennt zu prüfen.','Binding price intervention changes supply/demand and distribution; goals and the stated budget must be assessed separately.')}
spec=[]
for key in CASES:
 g=next(g for g in goals if g['id']==IDS[key]);de,en=UNDERSTANDING[key]
 profile={'archetype':'representation' if key.endswith('diagram') else 'modeling',
 'expectations':[{'id':key,'essentialUnderstandingDe':de,'essentialUnderstandingEn':en,'observablePerformanceDe':g['description'], 'observablePerformanceEn':g['descriptionEn']}],
 'coverageExpectations':{'requiredExpectationIds':[key],'alternativeExpectationGroups':[],'minimumIndependentDemonstrations':2,'freshVariationRequired':True,'independentTransferRequired':True},
 'variationAxes':[{'id':'material-model-change','textDe':'Die zwei ausgeformten Materialien ändern maßgebliche Bedingungen: '+('Ausweichbarkeit/Eintritt statt bloß andere Produktnamen.' if key=='supplier-behaviour' else 'Datenneigung und Änderungsszenario bei identischer Achsenkonvention.' if key=='imperfect-polypol-diagram' else 'kein Mehrgewinn versus echter Vorteil mit veränderter Trennung/Weiterverkauf.' if key=='price-differentiation-profit' else 'Knappheit unter Höchstpreis versus Überschuss/Budget unter Mindestpreis.'),'textEn':'The written materials change decisive conditions: '+('switching/entry rather than only product names.' if key=='supplier-behaviour' else 'data slopes and change scenarios with the same axis conventions.' if key=='imperfect-polypol-diagram' else 'no gain versus a real advantage under changed separation/resale.' if key=='price-differentiation-profit' else 'ceiling shortage versus floor surplus and budget.')},
 {'id':'bounded-inference','textDe':'Neue begründete Materialvariation innerhalb einer umfassenden Leistung kann eigenständige Evidenz tragen; keine Pflicht, beide Beispielaufgaben abzuarbeiten.','textEn':'A reasoned fresh material variation within one substantial performance can provide independent evidence; no obligation to complete both examples.'}],
 'applicationCaseBriefs':CASES[key]}
 spec.append({'goalId':g['id'],'reason':'Eigener INERT E1/G1 Profilkandidat, vollständige erwartete Autorenantworten, keine beobachtete Lernendenleistung oder fachliche Selbstfreigabe. Own inert author expectations, not observed learner performance or independent approval.','evidenceLevel':'E1','maximumClaimScope':'G1','dissent':[],'profile':profile})
write('actual-deterministic-new-IDs-and-authoring-contracts.AUTHOR-INERT.json',{'namespace':LAND,'uuid5Prefix':'BB-LK-market-p23:','ids':IDS,'mandatoryOrdinaryIds':[IDS[k] for k in list(CASES)[:3]],'optionalOrdinaryId':IDS['optional-intervention-diagram'],'newIdsAreNotDuplicateExistingContracts':True,'sourceAndScopeApproval':False})
write('four-whole-ordinary-goals-three-mandatory-one-optional.AUTHOR-INERT.json',{'role':'unreviewed_author_candidate','goals':goals})
write('eight-whole-DEEN-casebriefs-and-complete-model-answers.AUTHOR-INERT.json',CASES)
write('positive-v2-four-goal-authoring-spec.AUTHOR-INERT.json',{'schemaVersion':1,'authoringContract':'positive-understanding-evidence-candidates-v1','reviewId':'bb-lk-three-mandatory-one-optional-author-inert-20261010-v1','reviewedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'reviewer':'codex-explicit-bb-author-candidate-not-independent-review','goals':spec})
print(json.dumps({'newIDs':IDS,'ordinary':len(goals),'bilingualCases':sum(map(len,CASES.values()))}))
