# Apache-2.0 helper; own didactic candidates CC-BY-4.0. Exact independently requested bounded author successor.
from pathlib import Path
import json,hashlib,copy,shutil,datetime
root=Path('/home/enpasos/projects/skillpilot');B=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-08');own=B/'wirtschaft-e2-three-eleven-source-atomicity-author-v4';old=B/'wirtschaft-e2-three-eleven-source-atomicity-author-v3';review=B/'wirtschaft-e2-three-eleven-independent-source-AM-review-v3/independent-whole-fourteen-source-atomicity-memory.actual.receipt.json';CAN=Path('curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_WIRTSCHAFT.de.json');money='83779981-2279-5f96-8ea3-2293e801973f';d3='d3c11bfa-103c-5b58-8183-561e0b076251';unit='9b5d298e-3476-5e52-ae87-6370140bb6d8';read=lambda p:json.loads(p.read_text());sha=lambda p:'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):
 p.parent.mkdir(parents=True,exist_ok=True)
 with p.open('x')as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
receipt=read(root/review);assert sha(root/review)=='sha256:6de310d0e00d9550cb3d8260a80bc77422f24b40fe911117fec4a15cada90cfa';findings={r['id']:r for r in receipt['findings']};assert set(findings)=={'BY-V3-SOURCE-HISTORY-01','BY-V3-SOURCE-D3-02'}and receipt['authorIsReviewer']is False
whole=read(root/old/'whole-goals.candidate.json');nextwhole=copy.deepcopy(whole);g=next(g for g in nextwhole if g['id']==money);g['description']=findings['BY-V3-SOURCE-HISTORY-01']['proposedDescriptionDe'];g['descriptionEn']=findings['BY-V3-SOURCE-HISTORY-01']['proposedDescriptionEn']
assert all(a==b for a,b in zip(whole,nextwhole)if a['id']!=money);oldg=next(x for x in whole if x['id']==money);assert dict(g,description=oldg['description'],descriptionEn=oldg['descriptionEn'])==oldg
write(root/own/'whole-goals.original-v3-candidate.json',whole);write(root/own/'whole-goals.candidate.json',nextwhole)
for name in ['atomic-goal-ids.candidate.json','stable-parent-goal-ids.json','placement.source-bound.candidate.json','reverse-requires.exact-foundations.reviewed-inert-ops.json','narrow-market-form-card.content-reviewed-visibility-pending.candidate.json']:
 (root/own/name).parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(root/old/name,root/own/name)
boundaries=read(root/old/'source-unit-boundaries-and-prerequisites.candidate.json')
for r in boundaries:
 if r['canonicalGoalId']==money:
  r['atomicityRationale']='Compare two supplied historical money forms in an explicitly given temporal context, explain four enabling/limiting properties, and help explain the bounded depicted change; no universal chronology or inevitable progress.'
  r['prerequisiteRationale']='Known money functions support a two-form contextual comparison and property explanation; no whole monetary history or unrelated monetary theory is required.'
 if r['canonicalGoalId']==d3:r['atomicityRationale']='Actual independent whole current d3 and both P cases support direct reuse for the specific review-information source unit; this is partial source coverage of a broader online-shopping competence, with no duplicate atom or second visible parent.'
write(root/own/'source-unit-boundaries-and-prerequisites.candidate.json',boundaries)
tax=read(root/old/'atomic-demand-levels.individual-author.candidate.json');next(r for r in tax if r['goalId']==money)['individualWholeOperatorReason']='Explain a supplied contextual historical change by comparing two actual money forms and the enabling/limiting causal roles of all four properties; structured material explanation, not a free value judgment.';write(root/own/'atomic-demand-levels.individual-author.candidate.json',tax)
mapping=read(root/old/'mapping/twelve-units-to-eleven-new-and-existing-d3.review.candidate.json');mapping['reviewId']='BY-WWG-twelve-source-units-eleven-new-existing-d3-author-v4';edge=next(e for e in mapping['mappings']if e['legacyGoalId']==unit);assert edge['canonicalGoalId']==d3 and edge['matchType']=='exact';edge['matchType']='partial';decision=next(d for d in mapping['decisions']if d['sourceGoalId']==unit);assert decision['matchType']=='exact';decision['matchType']='partial';decision['rationale']='Direct partial source-unit binding to the unchanged broader online-shopping goal. The specific customer-review information-quality competence is covered by genuine existing whole-goal/P evidence, while the broader goal additionally includes needs, costs, contracts/vendor checks and data consequences. Actual root234 reuse and independent BY-v3 finding require partial rather than exact; no duplicate atom or second visible parent.';mapping['summary']['exactMappings']=11;mapping['summary']['partialMappings']=1;assert mapping['status']=='incomplete'and mapping['summary']['reviewedSourceGoals']==0
write(root/own/'mapping/twelve-units-to-eleven-new-and-existing-d3.review.candidate.json',mapping)
# Reuse unchanged raw extraction bytes by their existing preserved exact path; no source-word rewriting.
extraction=Path(mapping['sourceExtractionPath']);src=read(root/extraction);assert len(src['sourceGoals'])==12 and len(src['sourceDocuments'])==2 and len(src['passages'])==3
reuse=read(root/old/'existing-d3-direct-source-unit-binding.inert.json');reuse['matchType']='partial';reuse['sourceCompetenceCoverageBoundary']='Customer-review information quality directly covers a specific part of the unchanged broader online-shopping goal; not an exact whole-goal match.';reuse['currentSuccessorFindingPath']=str(review);write(root/own/'existing-d3-direct-source-unit-binding.inert.json',reuse)
currentbytes=(root/CAN).read_bytes();current=json.loads(currentbytes);assert len(current['goals'])==370;index={g['id']:g for g in current['goals']};assert index[d3]==reuse['wholeExistingGoal']
newby={g['id']:g for g in nextwhole};parents=set(read(root/own/'stable-parent-goal-ids.json'));atoms=set(read(root/own/'atomic-goal-ids.candidate.json'));assert len(parents)==3 and len(atoms)==11 and not(atoms&set(index))
nextcanonical=dict(current,goals=[newby.get(g['id'],g)for g in current['goals']]+[g for g in nextwhole if g['id']in atoms]);ops=read(root/own/'reverse-requires.exact-foundations.reviewed-inert-ops.json')
for operation in ops['ops']:
 pos=next(i for i,g in enumerate(nextcanonical['goals'])if g['id']==operation['goalId']);assert nextcanonical['goals'][pos]==operation['wholeOriginal'];nextcanonical['goals'][pos]=operation['wholeCandidate']
write(root/own/'canonical-three-clusters-eleven-atoms.current113.inert.json',nextcanonical)
(root/own/'current113-original-canonical.snapshot.json').write_bytes(currentbytes)
write(root/own/'actual-primary-money-context-reading.author.json',{'role':'author_bounded_actual_primary_reading','readAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actualReadSources':[{'url':'https://www.bundesbank.de/de/aufgaben/themen/vertrauen-kern-des-geldes-663226','publicationDate':'2012-10-15','actualMainContentRead':'Complete main content (tool lines7-19); money forms/functions and trust. No claimed universal chronology.'},{'url':'https://www.bundesbank.de/de/aufgaben/themen/waehrungsreform-1948-614040','publicationDate':'2008-06-20','actualMainContentRead':'Complete main explanatory sections (tool lines15-41) and quotations/discussion (42-59); bounded1948 western-zones context, cigarette black-market money and newDM, broader supply/policy/institution conditions.'},{'url':'https://www.bundesbank.de/de/presse/reden/-taler-taler-du-musst-wandern-geschichte-des-bargeldes-vom-taler-in-die-heutige-zeit--824616','publicationDate':'2020-01-31','actualMainContentRead':'Complete displayed speech17-104. Used only historical Taler/context and continuity/property explanation paragraphs36-64, not current digital-policy or forecast claims.'}],'failedSourceAccessNotClaimed':[{'url':'https://publikationen.bundesbank.de/publikationen-de/schule-bildung/geld-und-geldpolitik-921580?article=1-funktionen-und-formen-des-geldes-921582','actualFailure':'Web fetch content-size limit; no complete reading.'},{'url':'https://www.bundesbank.de/resource/blob/606038/8b1a79820e15af9a4a5387fc5c8e60cf/472B63F073F071307366337C94F8C870/geld-und-geldpolitik-data.pdf','actualFailure':'urllib redirected400 and web404; no PDF retrieval/read claimed.'}],'didacticPropertiesSuppliedInCaseMaterials':True,'sourceTimelineNotUniversal':True,'independentReviewClaim':False})
write(root/own/'author-source-atomicity-bounded-two-findings-successor.actual.json',{'schemaVersion':1,'role':'author_inert_two_findings_successor','createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actualIndependentFindingsPath':str(review),'actualIndependentFindingsSha256':sha(root/review),'previousV3WholeSha256Preserved':sha(root/old/'whole-goals.candidate.json'),'previousV3MappingSha256Preserved':sha(root/old/'mapping/twelve-units-to-eleven-new-and-existing-d3.review.candidate.json'),'wholeCandidateGoalCount':14,'changedWholeGoalIds':[money],'changedWholeGoalFields':['description','descriptionEn'],'otherWholeCandidateGoalsExactlyUnchanged':13,'exactSourceExtractionPathRetained':str(extraction),'exactRawSourceExtractionSha256Retained':sha(root/extraction),'rawSourceUnitsExactlyRetained':12,'changedMappingSourceGoalId':unit,'changedMappingMatchTypeBefore':'exact','changedMappingMatchTypeAfter':'partial','matchCounts':{'exact':11,'partial':1},'d3WholeGoalAndVisiblePlacementExactlyUnchanged':True,'currentRootCanonicalSnapshotPath':str(own/'current113-original-canonical.snapshot.json'),'currentRootCanonicalSha256':sha(root/CAN),'currentStrictBaseline':113,'currentDenominatorUnchanged':303,'hypotheticalAfterAllElevenGatesDenominator':311,'previousThreeClustersAndTwoReadinessOperationsCarriedUnchanged':True,'newMoneyPAuthorCandidateSeparate':True,'previousV3HasNoPositiveProfiles':True,'pending':['Actual independent targeted whole money DE/EN/P2 and partial d3-source correction closure','Full eleven P-v2/current image/two independent D gates','A/M11 source classification and52-card/native visibility closure','Actual foreign-source coverage/applicability/LayerA/adoption checks; no automatic scope inheritance'],'independentApprovalClaimed':False,'humanApprovalClaimed':False,'activeWrites':0,'newStrictClosures':0})
print('BY-v4: whole14, exactly2 money description fields,13whole unchanged; d3 partial11exact+1partial; raw12unchanged; current113 overlay, denominator303 still.')
