# SPDX-License-Identifier: Apache-2.0
from pathlib import Path
import datetime,hashlib,json,sys
sys.dont_write_bytecode=True
import jsonschema
R=Path(__file__).resolve().parents[8];P=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/chemie-b008-C11-current-G1-competence-source-context-author-20261010-v1');M=P.parent/'chemie-b008-current517-machine-content-native-readiness-author-20261010-v1';O=P.parent/'chemie-b008-current-whole-P26-native-continuation-author-20261010-v1';C=R/'tmp/m7-resumption-20261010/chemistry-b008-P26-native-author/isolated-normal-capsule'
assert not (R/P/'author-current-C11-G1.final.freeze.json').exists()
def read(p):return json.loads((R/p).read_text())
def ref(p):
 b=(R/p).read_bytes();return {'path':str(p),'sha256':'sha256:'+hashlib.sha256(b).hexdigest(),'bytes':len(b)}
def put(p,x):(R/P/p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
for rr in read(P/'inputs/actual-current-input-bindings.json')['bindings']:assert ref(Path(rr['path']))==rr,rr['path']
mf=read(M/'author-current517.final.freeze.json')
for rr in mf['files']:assert ref(Path(rr['path']))==rr,rr['path']
old=read(P/'inputs/prior-whole-normal-G1-record.exact.json');rec=json.loads((R/P/'positive/current-e5-G1.original-author.records.jsonl').read_text());cfg=read(P/'positive/current-e5-G1.original-author.normal.config.json');assert rec['profile']==old['profile'];assert rec['evidenceLevel']==old['evidenceLevel']=='E1';assert rec['maximumClaimScope']==old['maximumClaimScope']=='G1'
for field in ['goalFingerprint','reviewInputFingerprint','profileFingerprint','status','reviewAuthority','reviewCriteriaFingerprint']:assert rec[field]==old[field]
schemas=[Path('contracts/goal-evidence/v2/goal-evidence-profile.schema.json'),Path('contracts/goal-evidence/v2/goal-evidence-review-config.schema.json')];jsonschema.validate(rec,read(schemas[0]));jsonschema.validate(cfg,read(schemas[1]))
wholep=M/'candidate/whole517.inactive.machine-content-final-learner-copy-author.json';whole=read(wholep);by={g['id']:g for g in whole['goals']};gid=rec['goalId'];eid='eed5eda3-2daf-5d48-b935-23dadd622d9b';assert by[gid]==read(P/'inputs/current-whole-e5-curricular-goal.exact-extract.json');assert by[eid]==read(P/'inputs/current-whole-held-eed5-assessment.exact-extract.json')
ctx=read(M/'checks/final-learner-copy-normal398-and-D38-context-exact-retention.json');pageby={p['goalId']:p for p in read(M/'native/final-current398-whole-P205-normal-model.actual.json')['pages']};aliases=[]
for row in ctx['whole38ContextBindings']:
 i=row['goalId'];url=pageby[i]['visualization']['url'];raw=(C/'app/public'/url.lstrip('/')).read_bytes();candidates=[Path('app/public')/url.lstrip('/')]+[f.relative_to(R)for f in (R/O/'assets/chemie'/i).glob('*')if f.is_file()];matches=[f for f in candidates if (R/f).is_file()and (R/f).read_bytes()==raw];assert matches,i;physical=matches[0]
 aliases.append({'goalId':i,'logicalPublicURL':url,'portableExistingExactResource':ref(physical),'normalOwnCapsulePublicCopyExact':True,'normalGroup':row['group'],'assetEdited':False})
put('checks/current38-normal-resource-portable-exact-aliases.actual.json',{'schemaVersion':1,'role':'Additional neutral portable raw input proof for retained current38 normal renderings; no fresh review','currentWhole':ref(wholep),'mainNeutralEntry':ref(M/'author-current517.final.entry.json'),'resourceAliases':aliases,'resourceCount':38,'main321FrozenFilesVerifiedExact':True,'activeWrites':[],'independentApproval':False})
helpers=[]
for p in [Path('app/scripts/positiveGoalEvidenceReview.ts'),Path('app/scripts/positiveGoalEvidenceProfileModel.ts'),*schemas]:
 assert (R/p).read_bytes()==(C/p).read_bytes();helpers.append(ref(p))
terminal=read(P/'terminal/normal-current-e5-G1-full-contract-check-attempt2.terminal.actual.json');assert terminal['actualExitCode']==0 and 'Approved: 0' in terminal['stdout']and 'Needs human review: 1'in terminal['stdout']and 'Blocking issues: 0'in terminal['stdout']
put('checks/current-e5-whole-science-schema-context-portability-and-boundary-proof.actual.json',{'schemaVersion':1,'role':'Original AUTHOR mechanical verification, no independent science approval','schemaInputs':[ref(s)for s in schemas],'profileAndConfigSchemasValid':True,'wholeGoalAndHeldExamExact':True,'wholeProfileAndTwoCompleteMaterialsExact':True,'wholeRequiredExpectationCount':7,'wholeCaseCount':2,'normalFingerprintsAllExactAgainstPriorG1':True,'normalRulesAndSchemaByteExact':helpers,'genuineCurrentNormalContractExit':0,'currentPApproved':0,'currentPNeedsReview':1,'currentPBlockers':0,'evidenceLevel':'E1','maximumClaimScope':'G1','NTG11SourceWitnessExact':True,'coursePlacementHoldPreserved':True,'PSelected':False,'mainFrozenEntryAndAll321FilesExact':True,'runtimeChanges':[],'activeWrites':[],'independentApproval':False})
(R/P/'README.md').write_text('''# Aktueller C11 G1-Kompetenzkandidat\n\nDieser additive Autorenstand legt das unveränderte ganze E1/G1-Profil des Ziels `e5a5dcd8-053c-55fd-b5c7-bba93779da53` mit beiden vollständigen Ozon-/Ammoniakfällen und frischem Transfer zur getrennten aktuellen unabhängigen Prüfung vor. Die sieben Pflichtdimensionen, alle wissenschaftlichen Materialien und die drei normalen Fingerprints sind exakt erhalten. Der aktuelle ganze517-, Native-Seiten- und Quellenkontext ist ausdrücklich gebunden.\n\nDer wörtliche Primärbeleg C11.1.11 gehört zu Chemie11 (NTG), offizielles Kursniveau unspecified. Historische Einflüsse sind eine zusätzliche erhaltene Pflicht des ganzen Ziels und werden ausschließlich durch datierte Fallquellen gestützt. Unterrichtsimpulse und eigene Folgerungen bleiben getrennt von Quellenfakten. Keine GK-/LK-Gleichsetzung oder SourceAtlas-Ersatzquelle wird behauptet.\n\nDer normale positive-v2-Prüfer endet mit EXIT0: approved0, needs_review1, blockers0. Das ist technische Gültigkeit des Kandidaten, keine unabhängige fachliche Freigabe. Zwei echte aktuelle unabhängige P-Entscheidungen über Kompetenz, Quellen und Native-Kontext bleiben erforderlich. Kursplatzierung HOLD und PSelected=false bleiben erhalten; der konservative Hauptstand P205 wird nicht geändert. Eine offene Platzierungsfrage ist keine erfundene G1-Schemaverbotsregel.\n\n`checks/current38-normal-resource-portable-exact-aliases.actual.json` ergänzt die neutrale Bindung von 38 normalen Rendering-Inputs an unveränderte tatsächlich vorhandene portable Bilddateien. Alle 321 Dateien des Hauptseals wurden unverändert gelesen und erneut bytegenau geprüft.\n\nKeine menschliche Prüfung/Trial, reale Lernendenleistung oder Host-Akzeptanz; aktiver Gewinn0. Keine operative Integration, keine Git-/GitHub-Schreibvorgänge. Alle wirklichen Fehlversuche sind erhalten.\n''')
selected=['inputs/actual-current-input-bindings.json','inputs/current-e5-logical-resource-to-portable-exact-file-bindings.json','inputs/current-whole-e5-curricular-goal.exact-extract.json','inputs/current-whole-held-eed5-assessment.exact-extract.json','inputs/prior-whole-normal-G1-record.exact.json','source/C11.1.11-NTG11.current-primary-witness.exact-copy.json','materials/whole-e5-current-operative-materials-and-profile.exact-extract.json','native/current-e5-normal-full-page.exact-extract.json','native/current-e5-normal-canonical-context.exact-extract.json','positive/current-e5-G1.original-author.normal.config.json','positive/current-e5-G1.original-author.records.jsonl','positive/chemistry-positive-criteria.exact.md','author/bounded-current-C11-G1-rationale-and-gates.json','checks/current-e5-normal-positive-fingerprint-and-whole-profile-exactness.json','checks/current-e5-whole-science-schema-context-portability-and-boundary-proof.actual.json','checks/current38-normal-resource-portable-exact-aliases.actual.json','terminal/normal-current-e5-G1-full-contract-check-attempt2.terminal.actual.json']
put('author-current-C11-G1.final.entry.json',{'schemaVersion':1,'role':'Original AUTHOR neutral current C11 G1 competence/source/context candidate, not approval','sealedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'goalId':gid,'heldAssessmentId':eid,'mainCurrentWhole':ref(wholep),'mainNeutralEntry':ref(M/'author-current517.final.entry.json'),'mainNeutralFreeze':ref(M/'author-current517.final.freeze.json'),'candidateInputs':[ref(P/s)for s in selected],'evidenceLevel':'E1','maximumClaimScope':'G1','status':'needs_human_review','reviewAuthority':'ai_candidate','wholeExistingProfileAndMaterialsExact':True,'officialSourceProgramme':'Chemie11 (NTG)','officialSourceCourse':'unspecified','coursePlacementStatus':'HOLD','PSelected':False,'operativeMainPConservativeCountUnchanged':205,'normalContractActualExit':0,'normalApprovedCount':0,'normalNeedsReviewCount':1,'normalBlockingCount':0,'remainingRequiredPCountGate':'Two genuine independent current competence/source/native-context reviews and current normal P binding/ROOT selection; unresolved programme placement is reported separately.','independentCurrentReview':'pending','activeGain':0,'activeWrites':[],'gitOrGithubWrites':[],'independentApproval':False,'allFilesSealedBy':'author-current-C11-G1.final.freeze.json'})
files=[ref(f.relative_to(R))for f in sorted((R/P).rglob('*'))if f.is_file()];assert not any(f.is_symlink()for f in (R/P).rglob('*'));put('author-current-C11-G1.final.freeze.json',{'schemaVersion':1,'role':'Additive original AUTHOR freeze, no P selection or activation','entry':ref(P/'author-current-C11-G1.final.entry.json'),'files':files,'fileCount':len(files),'bytes':sum(f['bytes']for f in files),'activeWrites':[],'independentApproval':False})
print(json.dumps({'entry':ref(P/'author-current-C11-G1.final.entry.json'),'freeze':ref(P/'author-current-C11-G1.final.freeze.json'),'files':len(files),'currentNormalContractExit':0,'PSelected':False}),flush=True)
