"""Bound actual selected primary reads and two unnecessary author-process clauses."""
import json,hashlib,copy
from pathlib import Path
O=Path(__file__).resolve().parent;ROOT=Path('/home/enpasos/projects/skillpilot');P=Path('/tmp/skillpilot-ops14-B-primary-20261010')
def save(n,x):
 p=O/n;assert not p.exists();p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');return p
def bind(p):return dict(path=str(p.relative_to(ROOT)),sha256=hashlib.sha256(p.read_bytes()).hexdigest(),bytes=p.stat().st_size)
fetch=json.loads((P/'actual-six-primary-fetch-index.json').read_text())+[json.loads((P/'actual-seventh-taler-primary-fetch.json').read_text())]
reads={
'hgb242':('HGB §242: Bilanz und GuV','Entire current paragraph text, subsections 1–4, own GET and web selected read.','Die Vorschrift unterscheidet stichtagsbezogene Bilanz und periodische GuV; die Ausnahmen bleiben erhalten. Unsere Fälle sind ausdrücklich vereinfachte Modelle ohne behauptete Bilanzpflicht jeder Person.','The provision distinguishes dated balance sheets and period income statements, retaining its exceptions. Own simplified cases do not claim every person has the statutory duty.'),
'hgb275':('HGB §275: GuV-Gliederung','Entire current subsection text 1–5 from own GET; web request timed out and supplied no read.','Das gesetzliche Gliederungsschema ist nicht mit unserer knappen Modell-GuV gleichgesetzt. Die Aufgabe behauptet kein vollständiges gesetzliches Format.','The statutory format is not equated with the short teaching statement; no complete statutory format is claimed.'),
'destatis-enterprises':('Destatis: Unternehmensregister, 2024','Actually selected main table C/G and entire displayed methodological footnotes; own GET200, web403 not a webpage read.','Berichtsjahr2024, Stand3.8.2026; C198362/7801230 und G538248/6017332. Statistische Unternehmen und jährliche Beschäftigungsverhältnisse haben verschiedene Definitionen; die Quotienten sind keine Medianbetriebe oder eindeutige Personen.','2024 table updated3August2026: C198362/7801230 and G538248/6017332. Statistical enterprises and annual employment relationships have distinct definitions; ratios are not median firms or unique people.'),
'destatis-craft':('Destatis: Handwerksstruktur, 2024','Actually selected C/F rows, units and methodological footnotes; own GET200, web403 not a read.','Stand23.4.2026; rechtliche Einheiten, gerundete Tausenderzahlen C210/86 und F388/253. Veröffentlichte40,9/65,2Prozent beruhen auf feineren Ausgangsdaten. Keine Gleichsetzung mit A-statistischen Unternehmen.','Updated23April2026; legal units and rounded thousands C210/86 and F388/253. Published40.9/65.2percent use less rounded underlying data. No automatic equality with A’s statistical enterprises.'),
'bundesbank-1948':('Bundesbank: Währungsreform 1948','Actual selected historical body paragraphs on cigarette money,20June1948 western reform and changes; no whole-site reading claim.','Zigaretten erfüllten in Teilen des Schwarzmarkts Geldfunktionen. Die westliche Reform begann am20.6.1948; institutionelle Regeln und wirtschaftliche Änderungen sind von bloßen Materialeigenschaften getrennt.','Cigarettes served monetary roles in parts of the black market. Western reform began20June1948; institutional rules and economic changes are distinguished from material properties.'),
'ecb-money':('EZB: Was ist Geld?','Actually selected historical forms, commodity/representative/fiat money paragraphs; not a reading of current digital-euro status.','Geldformen und ihre Akzeptanz hängen an Nutzung, institutioneller Ausgabe und Vertrauen. Ein geringer Papierwert allein widerlegt nicht die Zahlungsfunktion; keine unvermeidliche Fortschrittsgeschichte.','Forms and acceptance depend on use, issuance and trust; low paper value does not itself refute the payment function. No inevitable progress account.'),
'bundesbank-taler':('Bundesbank: Geschichte des Talers','Actual selected Joachimsthal1520, silver supply, trade and agreed cross-border circulation paragraphs, own web and GET parsed reads.','Joachimsthaler Silberprägung ab1520 verbreitete sich mit Rohstoffvorkommen, Handel und vereinbartem Umlauf. Der lange Vergleich mit späteren Scheinen ist keine direkte Ablösung durch die D-Mark.','Joachimsthal silver coins from1520 spread with silver deposits, trade and agreed circulation. The long comparison to later notes does not imply immediate replacement by the Deutsche Mark.')}
rows=[]
for f in fetch:
 raw=Path(f['rawPath']);parsed=Path(f['parsedPath']);assert hashlib.sha256(raw.read_bytes()).hexdigest()==f['sha256'];assert hashlib.sha256(parsed.read_bytes()).hexdigest()==f['parsedSHA256'];title,method,de,en=reads[f['id']]
 rows.append(dict(key=f['id'],title=title,url=f['url'],actualFinalURL=f['finalURL'],actualGETStatus=f['status'],actualRawBytes=f['bytes'],actualRawSHA256=f['sha256'],actualParsedSHA256=f['parsedSHA256'],rawPrivateCache=str(raw),parsedPrivateCache=str(parsed),actualSelectedReadMethod=method,ownBoundedAidDe=de,ownBoundedAidEn=en,thirdPartyFullTextCommitted=False))
save('actual-seven-own-current-primary-selected-reads-and-bounded-DEEN-aid.AUTHOR.json',dict(role='AUTHOR actual own selected primary reads, no foreign approval',actualGET200=7,actualSelectedReads=rows,failedWebClaims=dict(destatisBoth='403, not read through web; own GET read instead',hgb275='web timeout, own GET paragraph text read',initialBS4Parser='ModuleNotFoundError before fetch/output; HTMLParser used'),licensing='Own teaching cases/content CC-BY-4.0; third-party text not relicensed or committed.',humanApprovalClaim=False))
before=json.loads((O/'whole-fourteen-finance-business-representation-DEEN-two-case-one-contract.DRAFT-author-v1.json').read_text());after=copy.deepcopy(before);changes=[]
de=' Autor-eigene XML-/Formelprüfung ist keine behauptete Office- oder Lernendenakzeptanz.'
en=' Author XML/formula checking is not claimed office-host or learner acceptance.'
for g in after:
 if g['examData']['coveredGoalIds'][0].startswith('685624a0'):
  for field,clause in [('solutionContent',de),('solutionContentEn',en)]:
   assert clause in g['examData'][field];g['examData'][field]=g['examData'][field].replace(clause,'');changes.append(dict(id=g['id'],field=field,reason='Remove author-process detail from learner solution; actual execution and data-reference requirements retained.',removedClause=clause))
 for field in ['taskContent','taskContentEn']:
  for key,(title,*_) in reads.items():
   old='['+key+'](';new='['+title+']('
   if old in g['examData'][field]:g['examData'][field]=g['examData'][field].replace(old,new);changes.append(dict(id=g['id'],field=field,sourceKey=key,reason='Use human-readable source title; exact URL and actual source claim retained.'))
body=save('whole-fourteen-finance-business-representation-human-source-labels-and-learner-solutions.DRAFT-author-v2.json',after)
save('actual-two-learner-solution-clauses-and-readable-source-labels-only-author-delta.json',dict(role='AUTHOR own not-yet-handed-off draft readability delta, no foreign review',before=bind(O/'whole-fourteen-finance-business-representation-DEEN-two-case-one-contract.DRAFT-author-v1.json'),after=bind(body),actualChanges=changes,allNumericTaskSolutionAndRubricClaimsUnchanged=True,allRequiresCoveredTagsStatusAndOriginalPExact=True))
print(json.dumps({'actualPrimarySelectedReads':7,'wholeBodies':14,'finalBody':bind(body)}))
