"""Own inert E1 social-change authoring. Code Apache-2.0; text CC-BY-4.0."""
from pathlib import Path
import importlib.util

HERE = Path(__file__).resolve().parent
helper = HERE.parent / 'wirtschaft-e2-twenty-bilingual-positive-author-v1/author_candidate.py'
spec = importlib.util.spec_from_file_location('economics_bounded_author_helper', helper)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
module.OUT = HERE
module.REVIEW_ID = 'canonical-economics-e1-seventeen-positive-author-20261008-v1'
module.REVIEWER = 'codex-economics-e1-author-candidate-20261008-v1'
module.ENTRIES = []
add = module.add

add('Analyse living and working',
    'The learner can describe changes in work, family, and education.', 'data',
    ('Sozialer Wandel zeigt sich in veränderten Lebens- und Arbeitsbedingungen, Familienarrangements und Bildungswegen. Eine Beschreibung braucht vergleichbare Zeitpunkte und Indikatoren; Unterschiede zwischen Gruppen sowie Zusammenhänge sind von einer automatisch bewiesenen Ursache zu trennen.',
     'Social change appears in changing living and working conditions, family arrangements, and education pathways. Descriptions require comparable time points and indicators; group differences and associations must be distinguished from automatically proven causation.',
     'Die Person beschreibt Veränderungen aus gegebenen Zeitvergleichen für Arbeit, Familie und Bildung und erklärt Reichweite und Grenzen der Daten, ohne einen Wandel als zwangsläufigen Fortschritt oder Verfall auszugeben.',
     'Using supplied comparisons over time, the learner describes changes in work, family, and education and explains the data\'s scope and limits without presenting change as inevitable progress or decline.'),
    [('working-patterns', 'Eine fiktive Zeitreihe zeigt sinkende Industrie- und steigende Dienstleistungsbeschäftigung sowie mehr digitale Tätigkeiten. Beschreibe den Wandel und die Grenze der Aussage über Einzelpersonen.',
      'A fictional time series shows declining industrial and rising service employment alongside more digital tasks. Describe the change and the limit of claims about individuals.',
      'Die Person beschreibt die angegebenen Anteils-/Tätigkeitsänderungen und trennt eine veränderte Gesamtstruktur von der Behauptung, jede Person habe den Beruf gewechselt.',
      'The learner describes the stated changes in shares and tasks and distinguishes a changed overall structure from the claim that every person changed occupation.',
      'Strukturveränderung anhand vergleichbarer Daten.', 'Structural change using comparable data.'),
     ('family-and-education', 'Zwei gleich erhobene Zeitschnitte zeigen mehr unterschiedliche Haushaltsformen und einen größeren Anteil höherer Bildungsabschlüsse. Beschreibe die Veränderungen und zwei offene Deutungsfragen.',
      'Two comparably collected time points show more varied household forms and a higher proportion of advanced qualifications. Describe the changes and two unresolved interpretation questions.',
      'Die Person benennt beide Entwicklungen, fragt nach Verteilung und veränderten Lebensbedingungen und leitet weder individuelles Wohlbefinden noch eine bestimmte Ursache allein aus den Anteilen ab.',
      'The learner identifies both developments, asks about distribution and changed living conditions, and derives neither individual well-being nor a specific cause from the shares alone.',
      'Familien- und Bildungswandel ohne unbelegte Kausalbehauptung.', 'Family and educational change without unsupported causal claims.')],
    [('domain', 'Arbeit, Familie oder Bildungswege.', 'Work, family, or education pathways.'),
     ('time-comparison', 'Vergleichbare Zeitpunkte sowie Gesamtanteile oder Gruppenangaben.', 'Comparable time points and overall shares or group-specific data.')])

add('Explain social change and political responses',
    'The learner can explain political responses to social change.', 'concept',
    ('Politische Reaktionen verbinden ein gesellschaftliches Problem mit Zielen, Instrumenten und betroffenen Interessen. Ihr Wirkungsweg muss erklärt werden; eine Maßnahme folgt weder zwangsläufig aus dem Wandel noch erreicht sie allein durch Ankündigung ihr Ziel.',
     'Political responses connect a social problem to objectives, instruments, and affected interests. Their mechanism must be explained; a measure neither follows inevitably from change nor meets its objective merely by being announced.',
     'Die Person erläutert im gegebenen Wandel-Fall Problem, politisches Ziel und Instrument, beschreibt den erwarteten Wirkungsweg und berücksichtigt eine relevante Bedingung oder Interessenkollision.',
     'For a supplied social-change case, the learner explains the problem, policy objective, and instrument, describes the expected mechanism, and considers a relevant condition or conflict of interests.'),
    [('childcare-response', 'Mehr Haushalte möchten Erwerbsarbeit und Betreuung vereinbaren. Eine Gemeinde plant längere Betreuungszeiten. Erläutere politischen Bezug und Wirkungsbedingungen.',
      'More households want to combine paid work and caregiving. A municipality plans longer childcare hours. Explain the policy connection and conditions for effects.',
      'Die Person verbindet den genannten Vereinbarkeitsbedarf mit der geplanten Leistung und erläutert Zugänglichkeit, Personal und passende Öffnungszeiten als Bedingungen; individuelle Familienentscheidungen bleiben verschieden.',
      'The learner connects the stated reconciliation need to the planned service and explains access, staff, and suitable hours as conditions, recognising differing family decisions.',
      'Problem-Ziel-Instrument-Wirkung werden verbunden.', 'Problem, objective, instrument, and effect are connected.'),
     ('training-response', 'Digitale Arbeitsaufgaben verändern Qualifikationsanforderungen. Im Planspiel fördert der Staat Weiterbildung. Erläutere den Mechanismus und einen möglichen Konflikt.',
      'Digital work tasks change skill requirements. In a simulation, the state supports continuing training. Explain the mechanism and a possible conflict.',
      'Die Person erklärt Zugang zu angepassten Kompetenzen und berücksichtigt etwa Zeit-/Kostenbelastungen oder ungleichen Zugang; eine Förderung garantiert nicht jeden Arbeitsplatz.',
      'The learner explains access to updated skills and considers time or cost burdens or unequal access; support does not guarantee every job.',
      'Politischer Ansatz und begrenzte Reichweite.', 'Policy approach and its limited reach.')],
    [('policy-field', 'Familien-, Bildungs- oder arbeitsbezogene Politik bei angegebenem Wandel.', 'Family, education, or work-related policy under stated change.'),
     ('conditions-interests', 'Zugang, Ressourcen und unterschiedlich betroffene Interessen.', 'Access, resources, and differently affected interests.')])

add('Analyse political socialisation',
    'The learner can analyse processes of growing into society.', 'concept',
    ('Sozialisation verbindet gesellschaftliche Einflüsse, erlernte Orientierungen und eigenes Handeln. Familie, Schule, Gleichaltrige, Medien und politische Rahmenbedingungen können unterschiedlich wirken; Herkunft prägt Möglichkeiten, bestimmt aber nicht jede Entscheidung einer Person.',
     'Socialisation connects social influences, learned orientations, and individual action. Family, school, peers, media, and policy conditions can operate differently; background shapes opportunities but does not determine every individual decision.',
     'Die Person analysiert anhand eines gegebenen Lebenslaufs mehrere Sozialisationsinstanzen und ihre Wirkungswege, unterscheidet Rahmenbedingungen von eigenen Entscheidungen und erklärt eine mögliche alternative Entwicklung.',
     'Using a supplied biography, the learner analyses several agents of socialisation and their mechanisms, distinguishes conditions from personal decisions, and explains a possible alternative development.'),
    [('participation-biography', 'Ein fiktiver Jugendlicher begegnet unterschiedlichen politischen Ansichten in Familie, Schule und einem Verein und beginnt, selbst Positionen zu vergleichen. Analysiere die Sozialisation.',
      'A fictional young person encounters differing political views at home, at school, and in an association and begins comparing positions independently. Analyse the socialisation process.',
      'Die Person beschreibt konkrete Einflüsse und Lern-/Interaktionswege und zeigt aktive Auseinandersetzung statt bloßer Übernahme; sie unterstellt der ganzen Familie oder Gruppe keine einheitliche Meinung.',
      'The learner describes specific influences and learning or interaction mechanisms and identifies active engagement rather than mere adoption, without assigning one uniform opinion to an entire family or group.',
      'Mehrere Instanzen und eigene Verarbeitung.', 'Several agents and individual interpretation.'),
     ('opportunity-change', 'Eine Schule schafft ein zugängliches Beteiligungsforum. Zwei Jugendliche mit unterschiedlichen Vorerfahrungen nutzen es verschieden. Analysiere Rahmenbedingung und Handlungsspielraum.',
      'A school creates an accessible participation forum. Two young people with different prior experiences use it differently. Analyse the conditions and scope for agency.',
      'Die Person erklärt den erweiterten Beteiligungszugang, verbindet Vorerfahrungen mit möglichen Orientierungen und berücksichtigt eigene Entscheidungen; sie macht aus dem Material keine unveränderliche Herkunftsregel.',
      'The learner explains expanded participation access, connects prior experience to possible orientations, and considers individual decisions without turning the material into an immutable rule about background.',
      'Wahlfreiheit und soziale Prägung zusammen analysieren.', 'Analyse agency and social influence together.')],
    [('socialisation-agents', 'Familie, Schule, Gleichaltrige, Verein oder Medien in vorgelegten Fällen.', 'Family, school, peers, associations, or media in supplied cases.'),
     ('agency-structure', 'Erlernte Orientierung, institutioneller Zugang und eigene Verarbeitung.', 'Learned orientations, institutional access, and individual interpretation.')])

add('Explain businesses adapting to change',
    'The learner can explain how businesses adapt to new operating conditions.', 'concept',
    ('Veränderte Kosten, Technik, Nachfrage oder Standortbedingungen können betriebliche Anpassungen auslösen. Eine passende Anpassung verbindet Leistungsprozess, Kosten, Qualität und Flexibilität; keine Fertigungsform ist unter allen Bedingungen effizient.',
     'Changes in costs, technology, demand, or location can prompt business adaptation. An appropriate response connects production processes, costs, quality, and flexibility; no production system is efficient under all conditions.',
     'Die Person erläutert eine betriebliche Anpassung vom veränderten Rahmen über die Prozessentscheidung bis zu erwarteten Kosten-/Qualitäts-/Flexibilitätsfolgen und nennt eine fallbezogene Grenze.',
     'The learner explains business adaptation from the changed conditions through a process decision to expected effects on costs, quality, and flexibility, identifying a case-specific limit.'),
    [('customisation', 'Ein Hersteller erhält statt gleichartiger Großaufträge viele kleine Sonderaufträge. Er erwägt Gruppenarbeit statt einer starren Linie. Erläutere die Anpassung.',
      'A manufacturer receives many small customised orders instead of large standardised orders. It considers team-based production instead of a rigid line. Explain the adaptation.',
      'Die Person verbindet die veränderte Varianten-/Losstruktur mit Flexibilität und möglichen Umstellungs-/Qualifikationskosten und erklärt, weshalb geringe Stückkosten der Großserie nicht unverändert übertragbar sind.',
      'The learner connects changed variety and batch sizes to flexibility and possible conversion or training costs and explains why low unit costs of mass production cannot be transferred unchanged.',
      'Fertigungssystem folgt konkreten Leistungsanforderungen.', 'Production systems respond to specific output requirements.'),
     ('automation-costs', 'Ein Betrieb kann durch Technik Arbeitszeit pro Stück sparen, muss aber höhere feste Kosten tragen. Nachfrage ist unsicher. Erläutere eine begründete Anpassungsentscheidung.',
      'A firm can save labour time per unit through technology but must incur higher fixed costs. Demand is uncertain. Explain a justified adaptation decision.',
      'Die Person trennt variable Einsparung und fixe Investitionsbelastung und erläutert, wie Auslastung, Qualitätsanforderungen und Nachfragerisiko die Eignung der Anpassung beeinflussen.',
      'The learner separates variable savings from fixed investment burdens and explains how capacity use, quality requirements, and demand risk influence suitability.',
      'Technischer Vorteil ist kein unbedingter Wirtschaftlichkeitsnachweis.', 'A technical benefit is not unconditional evidence of economic efficiency.')],
    [('external-condition', 'Nachfragevarianten, Kosten, Technik oder Standortanforderungen.', 'Demand variety, costs, technology, or location requirements.'),
     ('process-tradeoff', 'Stückkosten, fixe Belastung, Qualität oder Flexibilität.', 'Unit costs, fixed burdens, quality, or flexibility.')])

add('Compare diagnoses of modern society',
    'The learner can compare social-science models used to describe modern society.', 'modeling',
    ('Gesellschaftsmodelle wählen unterschiedliche Leitmerkmale und Erklärungsperspektiven. Sie ordnen Beobachtungen, bilden aber nicht die gesamte Gesellschaft identisch ab; ein Vergleich muss gemeinsame Fälle, Schwerpunkt und Reichweite der Aussagen berücksichtigen.',
     'Models of society select different central features and explanatory perspectives. They organise observations but do not identically represent all of society; comparison must consider common cases, emphasis, and scope.',
     'Die Person vergleicht mindestens zwei im Material erläuterte Modelle am selben Fall, beschreibt ihren jeweiligen Fokus und begründet, welche Beobachtung das Modell erklärt oder offenlässt.',
     'The learner compares at least two models explained in the materials using the same case, describes their respective focus, and justifies which observation each explains or leaves open.'),
    [('network-and-risk', 'Material A fokussiert vernetzte Informationsbeziehungen, B gesellschaftlich erzeugte und grenzüberschreitende Risiken. Vergleiche die Perspektiven auf digitale Lieferketten mit Ausfallrisiko.',
      'Material A focuses on networked information relations; B on socially produced cross-border risks. Compare their perspectives on digital supply chains with failure risks.',
      'Die Person wendet beide ausdrücklich beschriebenen Perspektiven auf denselben Fall an und erklärt Vernetzung bzw. Risikoverteilung als unterschiedliche Foki statt A und B als bloß richtige/falsche Etiketten zu behandeln.',
      'The learner applies both explicitly described perspectives to the same case and explains networking and risk distribution as distinct emphases instead of treating A and B as simply right or wrong labels.',
      'Gleicher Fall macht Perspektivunterschiede sichtbar.', 'The same case makes differences in perspective visible.'),
     ('rationalisation-limit', 'Ein Material beschreibt Rationalisierung über standardisierte Regeln und Berechenbarkeit, ein anderes Netzwerke über Beziehungen und Zugänge. Vergleiche beide an digitaler Schulorganisation.',
      'One material describes rationalisation through standardised rules and calculability; another describes networks through relations and access. Compare them for digital school organisation.',
      'Die Person erklärt Regelstandardisierung und Beziehungs-/Zugangsstruktur am Fall und benennt etwa individuelle Erfahrungen als durch diese Kurzdarstellungen nicht vollständig erfasst.',
      'The learner explains standardisation and relational or access structures in the case and identifies aspects such as individual experiences not fully captured by these brief accounts.',
      'Modellschwerpunkt und Modellgrenze.', 'Model emphasis and model limits.')],
    [('model-focus', 'Im Material erläuterte Rationalisierung, Netzwerke oder gesellschaftlich erzeugte Risiken.', 'Rationalisation, networks, or socially produced risks explained in the materials.'),
     ('common-case', 'Lieferketten, Institutionen oder digitale Alltagsorganisation als gemeinsamer Vergleichsfall.', 'Supply chains, institutions, or digital everyday organisation as a common comparison case.')])

add('Assess migration as a factor of social change',
    'The learner can assess the effects of migration on society and politics.', 'concept',
    ('Migrationsfolgen hängen von Ausgangslage, Institutionen, Zeit und betroffenen Gruppen ab. Chancen und Herausforderungen sind mit konkreten Wirkungswegen sowie transparenten Kriterien zu beurteilen; die Kategorie Migration allein begründet weder eine einheitliche Wirkung noch Eigenschaften einzelner Menschen.',
     'Effects of migration depend on initial conditions, institutions, time, and affected groups. Opportunities and challenges require specific mechanisms and transparent criteria; migration alone establishes neither a uniform effect nor individual characteristics.',
     'Die Person bewertet vorgelegte gesellschaftliche und politische Folgen eines konkreten Migrationsfalls, unterscheidet kurzfristige Anforderungen von längerfristigen Möglichkeiten und begründet das Urteil mit Kriterien und Material.',
     'The learner assesses supplied social and policy effects in a specific migration case, distinguishes short-term requirements from longer-term opportunities, and justifies the judgement with criteria and evidence.'),
    [('municipal-arrival', 'Eine fiktive Gemeinde nimmt neue Einwohner auf; Material nennt Wohnraumbedarf, Sprachlernangebote, berufliche Qualifikationen und freie Stellen. Bewerte Chancen und Herausforderungen.',
      'A fictional municipality welcomes new residents; materials specify housing needs, language-learning provision, occupational qualifications, and vacancies. Assess opportunities and challenges.',
      'Die Person verbindet Wohnraum-/Zugangsanforderungen und mögliche Arbeitsmarktteilhabe mit konkreten Angaben, berücksichtigt Anerkennung und Lernzugang und vermeidet die pauschale Gleichsetzung aller Zugewanderten.',
      'The learner connects housing and access needs and possible labour-market participation to specific facts, considers recognition and learning access, and avoids treating all migrants as identical.',
      'Bedingte Wirkungen und institutionelle Vermittlung.', 'Conditional effects mediated by institutions.'),
     ('policy-options', 'Zwei fiktive Programme unterscheiden sich im Zugang zu Bildung und Beteiligung. Angaben zeigen unterschiedliche Teilhabemöglichkeiten, ohne alle späteren Ergebnisse zu messen. Bewerte gesellschaftliche/politische Folgen.',
      'Two fictional programmes differ in access to education and participation. The data show differing opportunities without measuring all later outcomes. Assess social and policy effects.',
      'Die Person beurteilt die im Material gezeigten Chancen nach offen gelegten Kriterien, trennt Möglichkeiten von bewiesenen Langfristwirkungen und nennt erforderliche weitere Daten.',
      'The learner assesses the opportunities shown using explicit criteria, distinguishes possibilities from established long-term effects, and identifies further data needed.',
      'Urteil bleibt an beobachtete Reichweite gebunden.', 'Judgement stays within the observed scope.')],
    [('context', 'Arbeitsmarkt, Bildung, Wohnen oder politische Teilhabe mit konkreten Fallangaben.', 'Labour markets, education, housing, or political participation with specific facts.'),
     ('time-institutions', 'Kurzfristige Anforderungen oder längerfristige Möglichkeiten bei unterschiedlichem Zugang.', 'Short-term requirements or longer-term opportunities under different access conditions.')])

add('Analyse businesses in dynamic markets',
    'The learner can analyse how businesses respond to market changes.', 'modeling',
    ('Nachfrage, relative Preise, Konkurrenz und Bedürfnisse verändern Absatzmöglichkeiten und betriebliche Anreize. Unternehmen reagieren auf Marktbedingungen und können sie durch Innovation oder Angebot mitgestalten; ein plausibler Reaktionsweg braucht fallbezogene Nachfrage- und Kostenannahmen.',
     'Demand, relative prices, competition, and needs change sales opportunities and business incentives. Firms respond to market conditions and can influence them through innovation or supply; a plausible response requires case-specific demand and cost assumptions.',
     'Die Person analysiert vom gegebenen Marktimpuls über Preis-, Produkt- oder Vermarktungsentscheidung bis zu erwarteten Absatz- und Kostenfolgen und prüft eine alternative Reaktion.',
     'The learner analyses a supplied market change through pricing, product, or marketing decisions to expected sales and cost effects and examines an alternative response.'),
    [('new-preferences', 'Nachfrager bevorzugen nun reparierbare Produkte; ein Hersteller kann Design ändern oder lediglich Werbung ändern. Analysiere die Reaktionen anhand gegebener Kosten und Bedürfnisse.',
      'Buyers now prefer repairable products; a producer can change the design or only the advertising. Analyse responses using supplied costs and needs.',
      'Die Person verbindet tatsächliche Reparierbarkeit mit Bedarf und Produktionskosten, unterscheidet Leistungsänderung von Kommunikation und beurteilt die Reaktion unter den Fallannahmen.',
      'The learner connects actual repairability to needs and production costs, distinguishes a service change from communication, and assesses responses under the case assumptions.',
      'Marktbedarf und tatsächliches Angebot.', 'Market needs and actual supply.'),
     ('relative-cost-change', 'Ein wichtiger Rohstoff wird teurer. Angaben erlauben ein sparsameres Produkt, einen Preisaufschlag oder geringere Marge. Analysiere Reaktionswege bei unterschiedlicher Preissensibilität.',
      'An important raw material becomes more expensive. The facts allow a more material-efficient product, a price increase, or a smaller margin. Analyse responses under differing price sensitivity.',
      'Die Person erklärt Kosten- und Nachfragewirkungen, beachtet mögliche Absatzverluste bei Preisaufschlag und verknüpft Produktinnovation mit Ressourcenbedarf; keine Reaktion wird ohne Fallannahmen für sicher erfolgreich erklärt.',
      'The learner explains cost and demand effects, considers possible sales losses from higher prices, and connects product innovation to resource requirements, without declaring any response certainly successful absent case assumptions.',
      'Kostensignal und Nachfragebedingungen gemeinsam analysieren.', 'Analyse cost signals and demand conditions together.')],
    [('market-impulse', 'Neue Bedürfnisse, Konkurrenz oder veränderte relative Kosten.', 'New needs, competition, or changed relative costs.'),
     ('response', 'Preis, Produktgestaltung oder Vermarktung bei ausgewiesenen Nachfrageannahmen.', 'Pricing, product design, or marketing under stated demand assumptions.')])

add('Analyse family and education structures',
    'The learner can describe changes in family and education structures and derive social consequences.', 'data',
    ('Veränderte Haushaltsformen und Bildungswege können Anforderungen an Betreuung, Institutionen und Teilhabe verändern. Folgen müssen aus angegebenen Strukturmerkmalen begründet werden; Durchschnittsdaten oder Familienbezeichnungen bestimmen nicht den Lebenslauf jeder Person.',
     'Changed household arrangements and education pathways can alter demands on caregiving, institutions, and participation. Consequences must be justified from supplied structural features; averages or family labels do not determine every individual biography.',
     'Die Person beschreibt eine gegebene Familien-/Bildungsstrukturänderung und leitet einen plausiblen gesellschaftlichen Folgeweg mit Bedingungen ab, ohne Korrelation als sicheren Einzelursachennachweis auszugeben.',
     'The learner describes a supplied change in family or education structures and derives a plausible social consequence with conditions, without presenting correlation as proof of a single cause.'),
    [('household-time', 'In einer fiktiven Region verändern sich Haushaltsgrößen und Erwerbszeiten, während Betreuungszeiten gleich bleiben. Beschreibe den Wandel und leite eine institutionelle Folge ab.',
      'In a fictional region, household sizes and working hours change while care opening hours remain the same. Describe the change and derive an institutional implication.',
      'Die Person nutzt die tatsächlichen Größen-/Zeitangaben und erläutert möglichen Anpassungsbedarf bei Betreuung oder Koordination; sie leitet daraus keine pauschale Qualität der Familien ab.',
      'The learner uses the stated household and time data and explains possible needs to adapt caregiving or coordination, without inferring a blanket judgement about family quality.',
      'Struktur und institutioneller Bedarf werden verbunden.', 'Structures and institutional needs are connected.'),
     ('education-paths', 'Eine fiktive Zeitreihe zeigt mehr höhere Abschlüsse, aber unterschiedlich große Zuwächse nach Gruppen. Beschreibe die Entwicklung und Folgen für Teilhabe.',
      'A fictional time series shows more advanced qualifications but unequal increases across groups. Describe the development and implications for participation.',
      'Die Person beschreibt Gesamt- und Gruppenentwicklung und erläutert mögliche veränderte Zugangschancen, ohne höhere Abschlüsse mit garantiertem beruflichem Erfolg jeder Person gleichzusetzen.',
      'The learner describes aggregate and group trends and explains possible changes in access opportunities, without equating qualifications with guaranteed career success for every person.',
      'Bildungsstruktur und differenzierte Folgen.', 'Education structures and differentiated consequences.')],
    [('structure', 'Haushaltsform/Größe, Erwerbszeit oder Bildungsweg.', 'Household arrangement or size, working hours, or education pathways.'),
     ('consequence-level', 'Individueller Bedarf, institutionelles Angebot oder gesellschaftliche Teilhabe.', 'Individual needs, institutional provision, or social participation.')])

add('Assess social-policy responses',
    'The learner can compare policy measures responding to social change.', 'concept',
    ('Ein Vergleich sozialpolitischer Maßnahmen braucht das gleiche Problem, transparente Ziele und unterschiedliche Wirkungswege. Zugang, Verteilung und Ressourcen können verschiedene Vorteile und Grenzen erzeugen; bloße Ausgabenhöhe ist kein ausreichender Erfolgsmaßstab.',
     'Comparing social-policy measures requires a common problem, transparent objectives, and distinct mechanisms. Access, distribution, and resources can produce different benefits and limits; spending alone is not a sufficient measure of success.',
     'Die Person vergleicht zwei vorgegebene Maßnahmen nach Zielbezug, Zugang und Verteilungs-/Ressourcenfolgen und begründet ein bedingtes Urteil aus den Fallangaben.',
     'The learner compares two supplied measures by objective, access, and distributional or resource effects and justifies a conditional judgement using the case facts.'),
    [('cash-and-service', 'Ein Planspiel vergleicht einen Geldzuschuss zur Betreuung mit zusätzlichen bezahlbaren Betreuungsplätzen. Bedarf, vorhandene Plätze und Budgets sind gegeben. Vergleiche.',
      'A simulation compares a cash subsidy for care with additional affordable care places. Needs, existing provision, and budgets are given. Compare.',
      'Die Person unterscheidet Finanzierung vorhandener Nutzung von erweitertem Angebot, prüft tatsächliche Plätze und Zugang und erklärt, welche Haushalte unter den Fallbedingungen profitieren können.',
      'The learner distinguishes funding existing use from expanding provision, checks actual places and access, and explains which households may benefit under the case conditions.',
      'Instrumentunterschied beeinflusst tatsächlichen Zugang.', 'Differences between instruments affect actual access.'),
     ('training-alternatives', 'Bei veränderten Arbeitsaufgaben stehen pauschale Kursgutscheine oder zielgerichtete Kurse mit Freistellung zur Wahl. Angaben nennen Zeit- und Zugangsprobleme. Vergleiche.',
      'Under changing work tasks, the options are general training vouchers or targeted courses with release from work. The facts describe time and access constraints. Compare.',
      'Die Person erklärt, welches Instrument Kosten bzw. Zeitrestriktionen erreicht, berücksichtigt Verwaltung und Zielgenauigkeit und gibt ein kriterienspezifisches Urteil statt einer pauschalen Rangfolge.',
      'The learner explains which instrument addresses cost or time constraints, considers administration and targeting, and gives a criterion-specific judgement rather than a blanket ranking.',
      'Gleicher Bedarf, verschiedene Wirkungswege und Grenzen.', 'The same need with different mechanisms and limits.')],
    [('instrument-pair', 'Geldleistung und Infrastruktur oder allgemeine und gezielte Unterstützung.', 'Cash and infrastructure, or general and targeted support.'),
     ('access-cost', 'Verfügbare Angebote, Zeitrestriktionen und Ressourcen.', 'Available provision, time constraints, and resources.')])

add('Explain cultural dimensions of social change',
    'The learner can explain relationships among cultural change, migration, and integration.', 'concept',
    ('Kultureller Wandel kann durch Austausch, neue Praktiken und institutionelle Zugänge mitgeprägt werden. Migration und Integration verbinden unterschiedliche Erfahrungen und Teilhabe; Kultur ist keine unveränderliche Eigenschaft einer homogenen Gruppe, und Integration ist nicht bloß Einseitigkeit.',
     'Cultural change can be influenced by exchange, new practices, and institutional access. Migration and integration connect differing experiences and participation; culture is not an immutable property of a homogeneous group, and integration is not merely one-way adaptation.',
     'Die Person erläutert im konkreten Material den Zusammenhang von Austausch, veränderten Praktiken und Teilhabe, unterscheidet Zugangsbedingungen von individueller Identität und vermeidet pauschale Kulturzuordnungen.',
     'Using specific materials, the learner explains links among exchange, changed practices, and participation, distinguishes access conditions from personal identity, and avoids blanket cultural attributions.'),
    [('community-exchange', 'Ein fiktives Stadtteilprojekt bringt alte und neue Bewohner zusammen; gemeinsam ändern sie Veranstaltungsformen und Zugangsmöglichkeiten. Erläutere kulturellen Wandel und Integration.',
      'A fictional neighbourhood project brings long-standing and new residents together; together they change event formats and access opportunities. Explain cultural change and integration.',
      'Die Person erläutert wechselseitigen Austausch und neu entstehende Praktiken sowie Bedeutung des Zugangs und erklärt weder alle Zugewanderten noch alle bisherigen Bewohner als gleich.',
      'The learner explains reciprocal exchange and emerging practices as well as access, without treating all migrants or all existing residents as identical.',
      'Wechselwirkung statt fester Gruppenkultur.', 'Interaction rather than fixed group cultures.'),
     ('access-and-exclusion', 'Eine Vereinsgeschichte nennt neue Angebote, aber auch sprachliche Zugangshürden und unterschiedliche Teilnahme. Erkläre, warum kultureller Austausch und soziale Teilhabe auseinanderfallen können.',
      'An association\'s account describes new offerings alongside language barriers and differing participation. Explain why cultural exchange and social participation may diverge.',
      'Die Person verbindet Teilnahme mit konkreten Hürden und Angeboten, trennt Zugang von vermuteter kultureller Bereitschaft und erklärt mögliche Inklusion/Exklusion anhand des Materials.',
      'The learner connects participation to specific barriers and opportunities, separates access from assumed cultural willingness, and explains possible inclusion or exclusion using the materials.',
      'Institutionelle Zugangsvoraussetzungen vermitteln Teilhabe.', 'Institutional access conditions mediate participation.')],
    [('cultural-practice', 'Gemeinsam entwickelte Aktivitäten oder veränderte Alltagspraktiken.', 'Jointly developed activities or changed everyday practices.'),
     ('participation-barrier', 'Sprache, Zeit, Zugang oder institutionelle Unterstützung.', 'Language, time, access, or institutional support.')])

add('Analyse inequality and social differentiation',
    'The learner can describe social inequality and income and education distributions and discuss causes.', 'data',
    ('Soziale Ungleichheit betrifft ungleiche Ressourcen und Chancen; Einkommen und Bildung sind verschiedene messbare Dimensionen. Zusammenhänge können mehrere individuelle und institutionelle Ursachen haben; eine Verteilungstabelle allein belegt keine eindeutige Kausalrichtung.',
     'Social inequality concerns unequal resources and opportunities; income and education are distinct measurable dimensions. Associations can have several individual and institutional causes; a distribution table alone does not establish one causal direction.',
     'Die Person beschreibt Einkommens-/Bildungsverteilungen aus Daten, unterscheidet Durchschnitt von Gruppenstreuung und diskutiert plausible Ursachen samt benötigten weiteren Belegen.',
     'The learner describes income and education distributions from data, distinguishes averages from group variation, and discusses plausible causes together with further evidence needed.'),
    [('income-distribution', 'Zwei fiktive Gruppen haben gleiches Durchschnittseinkommen, aber unterschiedliche Streuung und niedrige Einkommensanteile. Beschreibe Ungleichheit und offene Ursachenfragen.',
      'Two fictional groups have the same average income but different dispersion and proportions of low incomes. Describe inequality and unresolved causal questions.',
      'Die Person benennt die unterschiedlichen Verteilungen trotz gleichem Mittelwert und diskutiert etwa Arbeitszeit-/Qualifikations-/Institutionenunterschiede als zu prüfende Erklärungen statt aus dem Mittelwert Gleichheit abzuleiten.',
      'The learner identifies differing distributions despite the equal mean and discusses working-time, qualification, or institutional differences as hypotheses rather than deriving equality from the average.',
      'Verteilung und vorsichtige Ursachenanalyse.', 'Distribution and cautious causal analysis.'),
     ('education-access', 'Material zeigt unterschiedliche Abschlussquoten und verschieden guten Zugang zu Beratung und Lernangeboten. Beschreibe und diskutiere den Zusammenhang.',
      'Materials show different qualification rates and unequal access to guidance and learning provision. Describe and discuss the association.',
      'Die Person beschreibt die Unterschiede, erläutert einen plausiblen Zugangsmechanismus und nennt zusätzliche Vergleichsdaten für Kausalprüfung; sie behauptet keine angeborene Gruppenfähigkeit.',
      'The learner describes the differences, explains a plausible access mechanism, and identifies additional comparative data for causal assessment, without claiming innate group ability.',
      'Institutioneller Mechanismus statt Gruppenstereotyp.', 'Institutional mechanisms rather than group stereotypes.')],
    [('dimension', 'Einkommen, Bildung oder institutioneller Zugang.', 'Income, education, or institutional access.'),
     ('distribution-causality', 'Mittelwert, Streuung, Gruppenanteile und alternative Erklärungen.', 'Mean, dispersion, group shares, and alternative explanations.')])

add('Analyse labour-market changes',
    'The learner can analyse sectoral change, non-standard employment, and digitalisation.', 'data',
    ('Branchenanteile, Beschäftigungsformen und Arbeitsaufgaben erfassen verschiedene Ebenen des Arbeitsmarktwandels. Digitalisierung kann einzelne Aufgaben ersetzen oder ergänzen, Sektorenwandel beschreibt Beschäftigungsverschiebung und atypische Formen Abweichungen vom verwendeten Standard; keines bestimmt automatisch Beschäftigungsqualität.',
     'Sectoral shares, employment arrangements, and work tasks capture different levels of labour-market change. Digitalisation can replace or complement tasks; sectoral change describes shifts in employment and non-standard forms deviations from the specified standard; none automatically determines job quality.',
     'Die Person analysiert vorgelegte Veränderungen der Sektoren, Vertrags-/Zeitformen und Tätigkeiten, verbindet plausible Ursachen/Folgen und trennt die drei Ebenen in einem gemeinsamen Fall.',
     'The learner analyses supplied changes in sectors, contract or working-time arrangements, and tasks, connects plausible causes and effects, and distinguishes the three levels within one case.'),
    [('sector-and-task', 'Eine fiktive Statistik zeigt mehr Dienstleistungen; Fallberichte zeigen automatisierte Routinen und zusätzliche digitale Kundenbetreuung. Analysiere die unterschiedlichen Veränderungen.',
      'Fictional statistics show more services; reports describe automated routines and added digital customer support. Analyse the different changes.',
      'Die Person trennt Sektoranteil und Aufgabenwandel und erläutert mögliche Ergänzung/Ersetzung von Tätigkeiten; sie leitet daraus weder für jeden Betrieb noch jede Person dieselbe Jobwirkung ab.',
      'The learner distinguishes sectoral shares from changing tasks and explains possible complementarity or replacement without deriving identical job effects for every firm or person.',
      'Makrostruktur und Aufgabenebene werden getrennt.', 'Aggregate structure and task-level change are distinguished.'),
     ('contract-and-quality', 'Das Material definiert einen Standardvertrag und zeigt mehr Teilzeit/befristete Verträge bei digital organisierter Arbeit; Arbeitszeitwünsche, Sicherheit und Einkommen unterscheiden sich. Analysiere.',
      'Materials define a standard contract and show more part-time or fixed-term contracts in digitally organised work; preferences, security, and income differ. Analyse.',
      'Die Person ordnet Formen relativ zum vorgegebenen Standard ein, erläutert mögliche Flexibilität und Unsicherheit anhand der Fälle und bewertet Qualität aus konkreten Bedingungen statt allein dem Vertragslabel.',
      'The learner identifies arrangements relative to the supplied standard, explains possible flexibility and insecurity using the cases, and assesses quality through actual conditions rather than the contract label alone.',
      'Beschäftigungsform und Beschäftigungsqualität sind verschieden.', 'Employment arrangement and job quality are different.')],
    [('analysis-level', 'Branche, Vertrags-/Zeitform oder konkrete Aufgabe.', 'Sector, contractual or working-time arrangement, or specific task.'),
     ('worker-conditions', 'Zeitwünsche, Einkommen, Sicherheit und Qualifikationszugang.', 'Working-time preferences, income, security, and access to skills.')])

add('Compare social lifeworlds',
    'The learner can describe different social groups\' perspectives (for example young people, migration, or gender roles).', 'concept',
    ('Gruppenperspektiven entstehen aus konkreten Erfahrungen, Interessen und Zugangsmöglichkeiten und variieren innerhalb jeder Gruppe. Ein Perspektivvergleich muss die vorgelegten Stimmen verständlich rekonstruieren und darf Zugehörigkeit nicht als feste Meinung jeder Person behandeln.',
     'Group perspectives arise from specific experiences, interests, and access and vary within every group. Comparing perspectives requires understandable reconstruction of the supplied voices without treating membership as a fixed opinion shared by every individual.',
     'Die Person stellt mehrere im Material genannte Perspektiven fair dar, verbindet sie mit Erfahrungen und Interessen und beschreibt Gemeinsamkeiten sowie Unterschiede ohne stereotype Verallgemeinerung.',
     'The learner fairly describes several perspectives in the materials, connects them to experiences and interests, and identifies similarities and differences without stereotyping.'),
    [('youth-and-arrival', 'Drei fiktive Jugendliche, darunter eine neu zugezogene Person, äußern unterschiedliche Wünsche zu Schule und Freizeit. Stelle die Perspektiven dar und vergleiche Gemeinsamkeiten.',
      'Three fictional young people, including a recent newcomer, express different wishes about school and leisure. Describe their perspectives and compare shared concerns.',
      'Die Person ordnet jede Sicht der tatsächlichen Äußerung zu, erläutert Zugang und Bedürfnisse und erkennt Unterschiede innerhalb der Jugendgruppe sowie gemeinsame Anliegen jenseits der Zugehörigkeit.',
      'The learner assigns each perspective to the actual statement, explains access and needs, and recognises differences within the youth group as well as common concerns beyond membership.',
      'Fallstimmen statt unterstellter Gruppenmeinung.', 'Case-specific voices rather than presumed group opinion.'),
     ('care-and-role-perspectives', 'Zwei fiktive Personen beschreiben verschiedene Erwerbs-/Betreuungsarrangements und Rollenerwartungen. Stelle die Sichtweisen dar, ohne sie aus ihrem Geschlecht abzuleiten.',
      'Two fictional people describe different work and care arrangements and role expectations. Present their perspectives without deriving them from gender.',
      'Die Person rekonstruiert genannte Erfahrungen, Zeitrestriktionen und normative Erwartungen und trennt individuelle Positionen von einer pauschalen Zuschreibung an ein Geschlecht.',
      'The learner reconstructs the stated experiences, time constraints, and normative expectations and separates individual positions from blanket gender attribution.',
      'Erfahrung und Rollenanforderung begründen die Perspektive.', 'Experiences and role demands explain the perspective.')],
    [('perspective-source', 'Direkte Falläußerung, Erfahrung oder dokumentierte Zugangsbedingung.', 'Direct case statement, experience, or documented access condition.'),
     ('within-group-variation', 'Gemeinsamkeiten über Gruppen hinweg und Unterschiede innerhalb einer Gruppe.', 'Similarities across groups and differences within one group.')])

add('Assess digitalisation in the world of work',
    'The learner can discuss opportunities and risks of digitalisation for work and society.', 'concept',
    ('Digitale Technik kann Produktivität, Flexibilität und Zugang verbessern sowie Aufgaben, Kontrolle und Qualifikationsanforderungen verändern. Chancen und Risiken hängen von Gestaltung und Verteilung ab; Technik allein garantiert weder Wohlstand noch Arbeitsplatzverlust.',
     'Digital technology can improve productivity, flexibility, and access while changing tasks, monitoring, and skill requirements. Opportunities and risks depend on design and distribution; technology alone guarantees neither prosperity nor job loss.',
     'Die Person diskutiert im konkreten Arbeitsfall nachvollziehbare Chancen und Risiken, erklärt ihren Wirkungsweg und benennt Gestaltungsbedingungen sowie unterschiedlich Betroffene.',
     'For a specific work case, the learner discusses justified opportunities and risks, explains their mechanisms, and identifies design conditions and differently affected parties.'),
    [('remote-work-design', 'Eine Firma ermöglicht mobiles Arbeiten, setzt aber ständige Erreichbarkeit voraus. Material nennt eingesparte Wege und Belastungen. Diskutiere Chancen, Risiken und Gestaltungsoption.',
      'A firm permits remote work but expects constant availability. Materials describe saved commuting and burdens. Discuss opportunities, risks, and a design option.',
      'Die Person verbindet Wegersparnis und Flexibilität mit konkretem Nutzen, erklärt Entgrenzungsrisiko und begründet beispielsweise klare Erreichbarkeitszeiten; unterschiedliche Tätigkeiten bleiben berücksichtigt.',
      'The learner connects reduced commuting and flexibility to specific benefits, explains blurred-boundary risks, and justifies options such as clear availability hours while considering different tasks.',
      'Wirkung folgt Arbeitsgestaltung, nicht nur Technik.', 'Effects depend on work design, not technology alone.'),
     ('task-automation', 'Ein System automatisiert Routineprüfungen; Beschäftigte übernehmen komplexere Fälle, brauchen aber Schulung. Diskutiere Produktivität, Teilhabe und Risiken.',
      'A system automates routine checks; staff take on more complex cases but require training. Discuss productivity, participation, and risks.',
      'Die Person erläutert mögliche Zeit-/Qualitätsvorteile und veränderte Anforderungen, berücksichtigt Schulungszugang und mögliche Verdrängung einzelner Aufgaben und gibt ein bedingtes Urteil.',
      'The learner explains possible time and quality gains and changed demands, considers access to training and possible displacement of tasks, and gives a conditional judgement.',
      'Aufgabeneffekt und Verteilung der Chancen.', 'Task effects and distribution of opportunities.')],
    [('digital-use', 'Mobiles Arbeiten, Routineautomatisierung oder digitale Zusammenarbeit.', 'Remote work, routine automation, or digital collaboration.'),
     ('design-distribution', 'Erreichbarkeitsregeln, Schulungszugang und unterschiedliche betroffene Aufgaben.', 'Availability rules, access to training, and differently affected tasks.')])

add('Compare family and education policy',
    'The learner can explain family- and education-policy measures responding to change.', 'concept',
    ('Familien- und Bildungspolitik können veränderte Betreuungs-, Zugangs- und Lernbedarfe bearbeiten. Maßnahmen verändern unterschiedliche Bedingungen; eine Erläuterung verbindet Problem, Instrument und Wirkung und trennt angestrebte von nachgewiesenen Ergebnissen.',
     'Family and education policies can address changed care, access, and learning needs. Measures alter different conditions; explanation connects problem, instrument, and mechanism and separates intended from established results.',
     'Die Person erläutert eine familien- und eine bildungspolitische Maßnahme aus dem vorgelegten Wandel, erklärt jeweils den Wirkungsweg und nennt unterschiedliche Zugangs- oder Ressourcenbedingungen.',
     'The learner explains one family-policy and one education-policy measure in response to the supplied change, describes each mechanism, and identifies differing access or resource conditions.'),
    [('care-measure', 'Veränderte Erwerbszeiten treffen auf starre Betreuung. Im Planspiel werden Betreuungszeiten erweitert. Erläutere die familienpolitische Reaktion.',
      'Changed working hours conflict with fixed care hours. A simulation expands care opening hours. Explain the family-policy response.',
      'Die Person verbindet Maßnahme und Vereinbarkeitsproblem, berücksichtigt Personal sowie tatsächliche Verfügbarkeit und behauptet nicht, alle Familien müssten die gleiche Lebensform wählen.',
      'The learner connects the measure to the reconciliation problem, considers staff and actual availability, and does not assume every family must choose the same arrangement.',
      'Wandel und passende Unterstützungsbedingung.', 'Change and an appropriate support condition.'),
     ('learning-access-measure', 'Eine digitale Unterrichtsform erfordert Geräte, Lernzugang und Unterstützung. Das Programm stellt Geräte und Beratung bereit. Erläutere die bildungspolitische Reaktion.',
      'A digital teaching format requires devices, learning access, and support. A programme supplies devices and guidance. Explain the education-policy response.',
      'Die Person trennt materiellen Zugang und pädagogische Unterstützung, erklärt ihre Verbindung mit den genannten Bedarfen und benennt, dass Ausgabe von Geräten allein keinen Lernerfolg beweist.',
      'The learner distinguishes material access from pedagogical support, connects both to the stated needs, and identifies that providing devices alone does not prove learning success.',
      'Instrumente schaffen verschiedene Zugangsvoraussetzungen.', 'Instruments create different conditions for access.')],
    [('policy-focus', 'Vereinbarkeit/Betreuung oder Bildungs-/Lernzugang.', 'Reconciliation and care, or access to education and learning.'),
     ('implementation', 'Personal, Infrastruktur und tatsächlich nutzbare Unterstützung.', 'Staff, infrastructure, and support that can actually be used.')])

add('Analyse gender roles and equality policies',
    'The learner can analyse changes in gender roles and equality policies.', 'concept',
    ('Geschlechterrollen sind gesellschaftliche Erwartungen und können sich ändern; sie sind von individuellen Fähigkeiten und Entscheidungen zu unterscheiden. Gleichstellungspolitik setzt an konkreten Zugangshürden oder Erwartungen an, deren Veränderung anhand von Fallbedingungen und Kriterien geprüft wird.',
     'Gender roles are social expectations that can change and must be distinguished from individual capabilities and choices. Equality policies address specific access barriers or expectations; changes are assessed using case conditions and criteria.',
     'Die Person analysiert im gegebenen historischen oder aktuellen Fall veränderte Rollenerwartungen und eine Gleichstellungsmaßnahme, erläutert ihren Wirkungsweg und trennt Gruppenmuster von individuellen Zuschreibungen.',
     'In a supplied historical or contemporary case, the learner analyses changed role expectations and an equality measure, explains its mechanism, and distinguishes group patterns from individual attributions.'),
    [('historical-role-change', 'Zwei fiktive Zeitschnitte dokumentieren unterschiedliche Erwartungen an Erwerbs- und Sorgearbeit und einen erweiterten Bildungszugang. Analysiere Veränderung und Reichweite.',
      'Two fictional time points document different expectations about paid and care work and expanded access to education. Analyse the change and scope.',
      'Die Person benennt die veränderten Erwartungen und Zugangsbedingungen anhand der Dokumente und erklärt Handlungsmöglichkeiten, ohne eine feste angeborene Aufgabenverteilung abzuleiten.',
      'The learner identifies changed expectations and access conditions in the documents and explains opportunities for action without deriving a fixed innate division of tasks.',
      'Soziale Erwartung und Zugang statt natürlicher Zuschreibung.', 'Social expectations and access rather than naturalised attribution.'),
     ('access-policy', 'Ein Fall beschreibt eine konkrete Zugangshürde im Betrieb; eine transparentere Auswahl und vereinbare Arbeitszeiten sollen sie mindern. Analysiere die Maßnahme.',
      'A case describes a specific access barrier in a workplace; more transparent selection and compatible working hours aim to reduce it. Analyse the measure.',
      'Die Person verbindet die Instrumente mit Auswahl-/Zeitbedingungen, erläutert mögliche Teilhabewirkung und benötigte Ergebnisdaten und behandelt keine Personengruppe als einheitlich interessiert oder befähigt.',
      'The learner connects the instruments to selection and time conditions, explains possible participation effects and required outcome data, and does not treat any group as having uniform interests or abilities.',
      'Belegte Hürde, Wirkungsweg und offene Ergebnisprüfung.', 'Evidenced barrier, mechanism, and unresolved outcome assessment.')],
    [('role-access', 'Rollenerwartung, Bildungszugang oder betriebliche Auswahlbedingung.', 'Role expectations, education access, or workplace selection conditions.'),
     ('time-level', 'Dokumentierter Zeitvergleich oder Fall einer institutionellen Veränderung.', 'A documented time comparison or a case of institutional change.')])

add('Describe networks and social capital',
    'The learner can describe the role of social networks and social capital in social change.', 'concept',
    ('Soziale Beziehungen können Informationen, Vertrauen und Unterstützung zugänglich machen und damit Handlungsmöglichkeiten verändern. Derselbe Netzwerkzugang kann Chancen eröffnen und Außenstehende ausschließen; Sozialkapital ist nicht identisch mit Geld oder der bloßen Zahl digitaler Kontakte.',
     'Social relationships can provide access to information, trust, and support and thereby change opportunities for action. The same network access can open opportunities and exclude outsiders; social capital is not identical to money or a mere count of digital contacts.',
     'Die Person beschreibt im gegebenen Fall die konkreten Beziehungen und darüber vermittelten Ressourcen sowie ihre Bedeutung für Handlung und Wandel und erläutert eine mögliche Zugangsgrenze.',
     'The learner describes specific relationships and resources mediated through them in a supplied case, explains their role in action and change, and identifies a possible access limit.'),
    [('job-information', 'Ein fiktives Netzwerk vermittelt Hinweise auf Ausbildungsplätze und Unterstützung bei Bewerbungen; Personen außerhalb erhalten die Hinweise nicht. Beschreibe die Rolle.',
      'A fictional network shares apprenticeship information and application support; outsiders do not receive the information. Describe its role.',
      'Die Person verbindet Beziehungen mit Informations-/Unterstützungszugang und erklärt Chancen sowie Ausschlussmöglichkeiten; sie verwechselt Kontakte nicht mit einem garantierten Ausbildungsplatz.',
      'The learner connects relationships to information and support access and explains opportunities and possible exclusion, without equating contacts with a guaranteed apprenticeship.',
      'Beziehungen vermitteln Ressourcen und ungleichen Zugang.', 'Relationships mediate resources and unequal access.'),
     ('collective-action', 'Eine Nachbarschaft organisiert über vertrauensvolle Beziehungen gemeinsame Hilfe, während eine große digitale Kontaktliste kaum aktive Unterstützung bietet. Beschreibe den Unterschied.',
      'A neighbourhood organises mutual support through trusted relationships, while a large digital contact list offers little active help. Describe the difference.',
      'Die Person benennt tatsächlich mobilisierbare Unterstützung, Vertrauen und Koordination und erklärt, warum Zahl der Kontakte allein kein Maß für verfügbare soziale Ressourcen ist.',
      'The learner identifies support that can actually be mobilised, trust, and coordination and explains why the number of contacts alone does not measure available social resources.',
      'Qualität und Mobilisierbarkeit statt bloßer Kontaktzahl.', 'Quality and mobilisability rather than contact count alone.')],
    [('network-resource', 'Information, Vertrauen, Unterstützung oder gemeinsame Handlungsfähigkeit.', 'Information, trust, support, or capacity for joint action.'),
     ('access-strength', 'Tatsächlich nutzbare Beziehung, bloßer Kontakt oder Ausschluss vom Netzwerk.', 'An actually useful relationship, mere contact, or exclusion from a network.')])

if __name__ == '__main__':
    module.main()
