import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
ROOT=Path('/home/enpasos/projects/skillpilot')
O=Path(__file__).parent
A=ROOT/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-09/chemie-b008-current-twenty-six-native-preparation-author-v1/seven-operative-native-preparation-v2/native-seven'
def load(p):return json.loads(p.read_text())
def bind(p):
 b=p.read_bytes();return dict(path=str(p.relative_to(ROOT)),sha256='sha256:'+hashlib.sha256(b).hexdigest(),bytes=len(b))
def write(n,x):
 p=O/n
 with p.open('x') as f:f.write(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
 return bind(p)
now=datetime.now(timezone.utc).isoformat()
inp=load(A/'round-a/description-review-input.json');campaign=load(A/'round-a/description-review-campaign.json');batch=campaign['batches'][0]
runId='chemie-b008-native-seven-D-only-independent-A-20261009-first'
fields=['essentialUnderstandingDe','essentialUnderstandingEn','observablePerformanceDe','observablePerformanceEn','transferExpectationDe','transferExpectationEn']
notes=[
[
'Ein chemisches Datenprotokoll macht Größen, Einheiten, Herkunft und relevante Bedingungen überprüfbar. Beobachtete Werte oder Erscheinungen sind von ihrer chemischen Erklärung zu unterscheiden; recherchierte Daten dürfen nicht als eigene Messungen ausgegeben werden.',
'A chemistry data record makes quantities, units, provenance and relevant conditions verifiable. Observed values or appearances differ from their chemical explanation; researched data must not be represented as own measurements.',
'Die lernende Person erstellt aus tatsächlichen erhobenen oder bereitgestellten recherchierten Daten ein strukturiertes Protokoll mit Herkunft und Bedingungen und kennzeichnet beobachtende Beschreibung und deutende Erklärung getrennt. Fehlende Angaben werden sichtbar belassen.',
'The learner constructs a structured record from actual acquired or supplied researched data, identifies provenance and conditions, and distinguishes descriptive observation from explanatory interpretation. Missing information remains visible.',
'Bei einem neuen Datensatz mit Gerätewechsel und fehlender Temperatur- oder Herkunftsangabe überarbeitet die lernende Person die Dokumentation, erhält originale Werte und erklärt, welche ergänzenden Angaben nachbeschafft werden müssen, ohne sie zu erfinden.',
'For a fresh dataset with an instrument change and missing temperature or provenance information, the learner revises the documentation, preserves original values and explains which additional details must be obtained without inventing them.',
'Der unveränderte DE/EN-Text grenzt transparente Dokumentation von Hypothesenauswertung ab. Er fordert überprüfbare Einheiten/Herkunft/Bedingungen sowie Beobachtung versus Erklärung, ohne eigenständige Durchführung zu behaupten. Der direkte Nachfolger7d9 ist die Datenauswertung; diese wird nicht in das Dokumentationsziel importiert. Native Seite1 zeigt den ganzen Text lesbar und ist in HTML/PDF kontexttreu; ihre Abbildung ist Unterstützung, kein Performanznachweis. SourceRef/projection fehlen im Batch; nationale/source/stage-course-Gesamtfreigaben werden nicht behauptet.'
],
[
'Ein Trend oder Zusammenhang in chemischen Tabellen/Diagrammen ist ein datenbezogener Befund. Seine Beziehung zur Eingangshypothese muss begründet werden; Stützung unter konkreten Bedingungen ist kein unbegrenzter Beweis oder automatisch eine Teilchenerklärung.',
'A trend or relationship in chemical tables/graphs is a data-based finding. Its relation to the initial hypothesis requires justification; support under specific conditions is not unlimited proof or automatically a particle-level explanation.',
'Die lernende Person wertet die tatsächlichen Daten einer vorgegebenen chemischen Frage selbst aus, erklärt Trend und relevante Beziehung und begründet mit konkreten Datenstellen, ob und in welchem Umfang sie die Ausgangshypothese stützen oder ihr widersprechen.',
'The learner independently evaluates actual data for a supplied chemical question, explains the trend and relevant relationship, and uses specific data points to justify whether and to what extent they support or contradict the initial hypothesis.',
'In einem frischen Vergleich variiert die Konzentration statt der Temperatur und eine Datenreihe widerspricht dem erwarteten Trend. Die lernende Person interpretiert den neuen Zusammenhang und formuliert einen entsprechend begrenzten Hypothesenbezug statt den alten Ergebnissatz zu kopieren.',
'In a fresh comparison concentration varies instead of temperature and one series contradicts the predicted trend. The learner interprets the new relationship and gives a correspondingly limited hypothesis assessment instead of copying the former result statement.',
'DE und EN verlangen dieselbe geeignete Tabellen-/Diagrammauswertung, Trenddeutung und begründete Hypothesenbeziehung. Der Satz ist knapp und chemisch korrekt; er verwechselt Daten nicht mit mechanistischer Erklärung oder absoluter Bestätigung. Das Voraussetzungziel9fc dokumentiert Daten, der obere quantitative Nachfolger verlangt anspruchsvollere Mathematik/Digitalwerkzeuge; beides bleibt getrennt. Der ganze Text und die echten Vor-/Nachfolger sind auf nativer Seite2 sichtbar. Keine eigene Versuchsdurchführung, aktuelle P-Freigabe oder wirksame Länder-/Kursprojektion wird daraus abgeleitet.'
],
[
'Ein vorgegebener chemischer Erkenntnisweg verbindet Fragestellung, Methode, Beobachtung und Interpretation. Die verwendete Methode begrenzt beantwortbare Fragen; verbleibende Unsicherheit ist nicht bloß eine fehlende positive Bestätigung.',
'A supplied chemical inquiry connects its question, method, observations and interpretation. The method limits which questions it can answer; remaining uncertainty is more than a missing positive confirmation.',
'Die lernende Person rekonstruiert diesen gegebenen Erkenntnisweg, erläutert anhand seiner konkreten Beobachtungen die Methodenwahl und Interpretation und trennt chemisch beantwortbare Fragen von Schlussfolgerungen, die die vorhandene Untersuchung nicht trägt.',
'The learner reconstructs the supplied inquiry, explains the chosen method and interpretation using its actual observations, and distinguishes chemically answerable questions from conclusions unsupported by the available investigation.',
'Ein neuer Erkenntnisweg nutzt eine instrumentelle Anzeige statt einer bloßen Farb-Beobachtung. Die lernende Person vergleicht die veränderte Aussagekraft, identifiziert die weiterhin offene Frage und begründet, weshalb die Methode allein noch keine eindeutige Stoffidentifikation gewährleistet.',
'A fresh inquiry uses an instrument reading rather than visual colour observation alone. The learner compares the changed evidential reach, identifies the remaining open question and explains why the method alone still does not establish unique substance identity.',
'Das Ziel ist ausdrücklich die Erklärung eines vorgegebenen Erkenntniswegs. DE/EN halten Frage/Methode/Beobachtung/Interpretation und Beantwortbarkeit/Grenzen gleichwertig zusammen; weder Eigenplanung noch eigene Reflexion oder komplette wissenschaftliche Gültigkeitskriterien werden neu behauptet. Voraussetzung7d9 und Nachfolger e5a/a008 sind im nativen Kontext getrennt. Seite3 trägt den vollständigen lesbaren Text; das gemeinsame Bild mit einem Nachbarziel ersetzt nicht die hier verlangte Reichweitenanalyse. Applicability ist keine ganze Source-/Kursfreigabe.'
],
[
'Pro- und Kontra-Argumente erhalten ihr Gewicht aus fachlichen Belegen und expliziten Bewertungskriterien. Ein chemischer Befund liefert eine Grundlage; seine Gewichtung ist eine begründete Bewertung, nicht dieselbe Art Aussage wie ein Messwert.',
'Arguments for and against obtain their weight from scientific support and explicit assessment criteria. A chemical finding supplies a basis; weighting it is a justified evaluation, not the same type of statement as a measurement.',
'Die lernende Person findet zu demselben chemischen Sachverhalt eigene fachlich belegte Argumente beider Seiten, vergleicht sie mit bereitgestellten Argumenten und begründet ihre Relevanz und relative Gewichtung anhand recherchierter oder erkannter Kriterien.',
'The learner independently finds scientifically supported arguments on both sides of the same chemical issue, compares them with supplied arguments and justifies their relevance and relative weighting using researched or recognised criteria.',
'In einer frischen Bewertung ändern sich die Nutzungssituation und eine belegte Sicherheitsbedingung. Die lernende Person prüft, welche vorherigen Argumente weiter tragen und wie deren Gewicht gegenüber Kosten oder Umweltkriterien angepasst werden muss.',
'In a fresh evaluation the use situation and an evidenced safety condition change. The learner checks which earlier arguments remain relevant and how their weighting relative to cost or environmental criteria must change.',
'Der ganze Text fordert eigene belegte Pro-/Kontra-Argumente zusätzlich zum Vergleich gegebener Argumente; damit ist sichtbare Eigenleistung explizit. Das kriteriengeleitete Gewicht gehört zur einen Abwägung, während die abschließende Handlungsentscheidung beim externen Nachfolger1df liegt. DE/EN sind gleichwertig und importieren keine pauschale Umwelt-/Gesundheitsbehauptung. Native Seite4 zeigt diese Abgrenzung und den externen Quellen-Vorgänger. Die Abbildung veranschaulicht Kriterien, legt aber weder richtige Gewichtung noch Lernendenleistung fest.'
],
[
'Chemische Berufsfelder unterscheiden sich in Tätigkeiten, Anwendungsbereichen und Anforderungen. Ihre Beziehung zu chemischen Anwendungen und gesellschaftlichen Entwicklungen liefert Informationen für eine begründete Wahl; Interesse allein ersetzt diesen Vergleich nicht.',
'Chemistry occupations differ in tasks, application areas and requirements. Their relationship to chemical applications and social developments informs a justified choice; interest alone does not replace the comparison.',
'Die lernende Person vergleicht quellengebundene Profile mehrerer chemischer Berufsfelder nach konkreten Aufgaben und Anforderungen, erklärt ihren Anwendungs-/Gesellschaftsbezug und zeigt, welche Informationen die eigene begründete Berufsorientierung beeinflussen.',
'The learner compares source-based profiles of several chemistry occupations by concrete tasks and requirements, explains their application/social context and identifies the information influencing their own justified career orientation.',
'Ein frisches Berufsprofil verlagert die Tätigkeit von praktischer Laborarbeit zu datenbezogener Qualitätssicherung. Die lernende Person überprüft ihre bisherigen Auswahlgründe an den veränderten Aufgaben und Anforderungen und begründet eine fortbestehende oder angepasste Orientierung.',
'A fresh occupation profile shifts work from practical laboratory activity to data-based quality assurance. The learner re-examines previous selection reasons against the changed tasks and requirements and justifies retaining or adapting their orientation.',
'Der DE/EN-Text ist eine assessierbare Vergleichs-/Entscheidungskompetenz: Aufgaben, Anforderungen, Anwendungen und begründete Wahl sind konkret genannt. Das Wort Berufsorientierung erklärt diesen Inhalt und macht den Goal nicht zu einer unbewerteten Motivationseinleitung. Der externe Vorgänger7f14 liefert den chemischen Anwendungsbezug; keine Berufsberatung mit erfundenen aktuellen Zugangsvoraussetzungen wird erzeugt. Seite5 zeigt den vollständigen Text und Berufsfelder als Unterstützung. Eine spätere Berufswahl ist kein jetzt behauptetes reales Lernendenereignis.'
],
[
'Soziale, kulturelle, technologische, historische, ökologische und ökonomische Rahmenbedingungen können die Entwicklung chemischen Wissens beeinflussen. Forschungswahl, Möglichkeiten und Bewertung ihrer Einflüsse sind von der empirischen Gültigkeit eines konkreten Befunds zu unterscheiden.',
'Social, cultural, technological, historical, environmental and economic conditions can influence the development of chemical knowledge. Research choices, possibilities and evaluation of those influences differ from the empirical validity of a particular finding.',
'Die lernende Person erklärt anhand chemischer Beispiele konkrete Einflussmechanismen dieser Perspektiven auf die Wissensentwicklung, bewertet sie mit nachvollziehbaren Gründen und zeigt ausdrücklich, weshalb Zustimmung oder wirtschaftliches Interesse einen Befund nicht empirisch gültig macht.',
'The learner explains concrete mechanisms through which these perspectives influence knowledge development using chemistry examples, assesses them with reasons and explicitly shows why approval or economic interest does not make a finding empirically valid.',
'In einem frischen hypothetischen Forschungsfall verbessern neue Analysemöglichkeiten die beobachtbare Datenlage, während veränderte ökologische Prioritäten die Fragenauswahl beeinflussen. Die lernende Person trennt diese beiden Wirkungen und begründet, welche empirische Prüfung weiterhin erforderlich ist.',
'In a fresh hypothetical research case new analytical capabilities improve observable data while changed environmental priorities affect question selection. The learner separates these effects and explains which empirical testing remains necessary.',
'DE und EN halten alle sechs Einflussdimensionen und die wichtige Grenze Gültigkeit versus Zustimmung unverändert. Die Beschreibung benennt eine begründete Einflussanalyse und enthält keine klinische Wirkung oder historische Tatsachenbehauptung. Voraussetzung a880 plus externe Quellenkritik3666 bilden den angegebenen Kontext, der obere Nachhaltigkeitsnachbar wird nicht eingemischt. Seite6 zeigt diesen vollständigen lesbaren Text. UnspecifiedCourse sowie Source-/Kurs-/Atlas-/protectedContext-HOLDs bleiben separate offene Bindungen; dieses KEEP bestätigt ausschließlich die Beschreibung auf dem vorliegenden D-Frame.'
],
[
'Chemische Modelle besitzen zweckgebundene Regeln, Vorhersagen und Grenzen. Auswahl und tatsächliche analoge oder digitale Nutzung für eine chemische Hypothese müssen mit Beobachtungen und anderen Modellvorstellungen verglichen werden; Modell und Wirklichkeit sind nicht identisch.',
'Chemical models have purpose-dependent rules, predictions and limits. Selection and actual analogue or digital use for a chemical hypothesis require comparison with observations and other models; a model is not identical to reality.',
'Die lernende Person wählt geeignete Modelle aus den genannten Materie-/Reaktions-/Bindungs-/Wechselwirkungskontexten, nutzt die gewählte analoge oder digitale Route tatsächlich für die Frage und erklärt anhand ihres Vergleichs, welche Aussagen tragen und weshalb ein Modell kritisch erweitert werden muss.',
'The learner selects suitable models from the stated matter/reaction/bonding/interaction contexts, actually uses the chosen analogue or digital route for the question and explains through comparison which predictions hold and why a model needs critical development.',
'Ein frischer chemischer Fall ändert die relevante Beobachtung so, dass das bisherige Modell sie nicht mehr hinreichend erklärt. Die lernende Person prüft seine Annahmen und entscheidet begründet zwischen einer passenden Erweiterung und einem anderen Modell, statt lediglich einen weiteren Modellnamen zu nennen.',
'A fresh chemical case changes the relevant observation so that the previous model no longer explains it adequately. The learner checks its assumptions and justifies choosing a suitable extension or another model instead of merely naming an additional model.',
'Der DE/EN-Text erhält ausdrücklich analog ODER digital sowie Hypothesenbezug, tatsächliche Modellnutzung, Beobachtungs-/Modellvergleich und begründete Weiterentwicklung. Die chemischen Kontexte werden nicht auf den Wassermolekül-Einstieg der Abbildung reduziert. Die obere theoriegestützte Nachbarkompetenz86d bleibt im externen Kontext, keine universelle selbstimplementierte Softwarepflicht wird in die Beschreibung importiert. Seite7 trägt den ganzen Text lesbar. Eigene P7-Autorenmaterialien sind für dieses D-only Urteil ausgeschlossen; es erteilt ihnen keine unabhängige P-Freigabe.'
],
]
assert len(notes)==len(inp['goals'])==7
records=[]; criteria=[]
for i,(g,n) in enumerate(zip(inp['goals'],notes)):
 assert g['reviewContext']['evidenceProfile'] is None
 rec={k:g[k] for k in ['goalId','goalFingerprint','pageFingerprint','currentTitleDe','currentTitleEn','currentDescriptionDe','currentDescriptionEn']}
 rec.update({'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json','schemaVersion':1,'recordId':runId+'.goal-'+str(i+1),'runId':runId,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'bundleFingerprint':campaign['bundleFingerprint'],'bookDigest':campaign['bookDigest'],'decision':'keep','understandingEvidence':dict(zip(fields,n[:6])),'rationale':n[6],'evidenceProfileContract':'positive-understanding-evidence-v2','evidenceProfileRecommendation':'create','recordStatus':'candidate','reviewAuthority':'ai_candidate'})
 records.append(rec)
 criteria.append({'goalId':g['goalId'],'pageNumber':i+1,'allCriteriaIndependentlyApplied':True,'criteriaNotes':{'exactScopeAndSources':'Exact bilingual goal and supplied direct/containing/external context preserved. sourceRef is null; no full mapping/effective projection proof claimed. e5a unspecifiedCourse/current source HOLD stays separate.','chemicalCorrectness':n[0],'energyAndReactionPath':'No energetic numerical/reaction-path claim added; any later contextual chemistry needs its own valid system/basis.','independentPerformance':n[2],'representations':'Actual page visualization is teaching support. Observed record/interpretation/model/criteria distinctions above are retained; no copied image constitutes understanding.','experimentsAndSafety':'No new experimental execution task or unsupervised action added by this D description; provided data/reconstruction remain within scope. Real performed work is not asserted.','meaningfulTransfer':n[4],'evaluation':'Separate chemical evidence/uncertainty from criteria and value judgment; no unsupported blanket impact/health claim.','atomicityAndLanguage':n[6],'conservativeDecision':'KEEP exact descriptions as candidate only; create recommendation follows actual null profile in this D-only input, without reading or deciding own P7 materials.'},'P7MaterialsRead':False,'peerNative7DOutputsRead':False,'humanApproval':False})
rp=O/'native-seven-description.first.independent-A.records.jsonl'
with rp.open('x') as f:f.write(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in records))
c=write('native-seven-description.first.independent-A.criteria-notes.json',{'schemaVersion':1,'role':'Independent criterion-by-criterion D-only notes on actual7 whole contexts/native pages','reviewedAt':now,'records':criteria,'actualPDFPhysicalGoalPagesViewed':[3,4,5,6,7,8,9],'actualHTMLReadFully':True,'nativeRasterVReapprovalPerformed':False,'sourceCourseWholeApproved':False,'humanApproval':False,'strictGain':0})
v=write('native-seven-description.first.independent-A.verdict.json',{'schemaVersion':1,'role':'Independent blind first native-seven description judgments only; reviewer did not author these goal descriptions','reviewedAt':now,'reviewer':'/root/bio_science14_independent_a; model variant unexposed','neutralInput':bind(A/'round-a/description-review-input.json'),'campaign':bind(A/'round-a/description-review-campaign.json'),'firstRecords':bind(rp),'criteriaNotes':c,'exactBookHTML':bind(A/'bundle/book.html'),'exactBookPDF':bind(A/'bundle/book.pdf'),'records':7,'decisions':{'keep':7,'revise':0,'split_review':0,'block':0},'blindToOtherRuns':True,'ownP7MaterialsReadForDReview':False,'peerNative7DOutputsRead':False,'descriptionAuthorIsThisReviewer':False,'ownP7ApprovalGranted':False,'source19CourseAtlasProtected8ContextsApproved':False,'humanApproval':False,'humanTrial':False,'strictGain':0})
s=write('native-seven-description.first.independent-A.freeze.json',{'schemaVersion':1,'role':'Immutable independent native7 D-only first seal before peer result labels/comparison','sealedAt':now,'verdict':v,'records':bind(rp),'criteria':c,'inputFirst':bind(O/'native-seven-description.actual-input.first.freeze.json'),'script':bind(Path(__file__)),'blindToOtherRuns':True,'humanApproval':False,'strictGain':0})
print(json.dumps({'verdict':v,'seal':s,'records':bind(rp)},indent=2))
