import pathlib,json,uuid,hashlib,copy
R=pathlib.Path('/home/enpasos/projects/skillpilot');O=pathlib.Path(__file__).parent;can=json.loads((R/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_WIRTSCHAFT.de.json').read_text());goal=next(g for g in can['goals'] if g['id']=='424bae9f-8f2e-5093-a17d-ee5eadb6edde');mid=str(uuid.uuid5(uuid.NAMESPACE_URL,'https://skillpilot.com/economics/material/pure-gini-LK-two-independent-whole-transfer-cases-20261010'))
D='''**Zwei vollständig fiktive Verteilungsfälle – 24 Punkte.** Alle Zahlen sind eigens gesetzte Unterrichtsdaten, keine heutigen Länderwerte. Jeder Fall beschreibt vier gleich große Einpersonenhaushalte, alle mit demselben positiven Gesamteinkommen von 100 Geldeinheiten und derselben Definition verfügbaren Jahreseinkommens. Die Tabellen enthalten vollständige Daten dieser Modellpopulationen, keine Stichproben. Bedürfnisse, Preise, Vermögen und politische Gerechtigkeitsmaßstäbe sind nicht angegeben.

**Gemeinsame Rechenhilfe:** Sortiere nach dem aktuellen Einkommen aufsteigend. Die Lorenzkurve zeigt auf der waagerechten Achse den kumulierten Haushaltsanteil und senkrecht den kumulierten Einkommensanteil. Starte bei (0;0); jeder Haushalt erhöht den Haushaltsanteil um 0,25. Verbinde die Punkte geradlinig. Für diese Daten berechne die Fläche A unter der Kurve mit A=Σ((Y_i+Y_(i−1))/2)×0,25 und G=1−2A auf der Skala 0 bis 1. Zeige deine Punkte und Rechnung. Ein gleichwertiger korrekter Rechenweg erhält dieselben Punkte. Das Verfahren ist das hier definierte unnormierte empirische Vier-Haushalts-Maß; bei vier Haushalten mit ausschließlich nichtnegativen Einkommen ist der Maximalwert 0,75, nicht 1. Das verändert die folgende Rangfolge der Fälle nicht.

**Fall A – Transfer ohne Rangwechsel:** Die Einkommen der Haushalte H1–H4 sind (10;20;30;40). Eine vollständig vorgegebene Transferbuchung nimmt H4 acht Einheiten und gibt sie H1; andere Einkommen, Haushalte und Gesamtbetrag ändern sich nicht. Eine Person sagt: „Jetzt haben alle ein gerechtes Einkommen; der kleinere Gini beweist das.“ Eine zweite sagt: „Wenn anschließend jedes Einkommen verdoppelt wird, verdoppelt sich der Gini.“ Preis- und Bedarfsangaben fehlen weiterhin.
A1 (4): Stelle die ursprüngliche Lorenzkurve durch ihre Punkte oder eine passende Skizze dar und bestimme den Gini. Erkläre, was die kumulierten Anteile bedeuten.
A2 (4): Stelle die Verteilung nach der Buchung dar, prüfe die Sortierung und berechne Lorenzpunkte und Gini neu. Erläutere die tatsächliche Veränderung der relativen Verteilung; setze einen kleineren Gini nicht mit gleichen Einkommen gleich.
A3 (4): Prüfe beide Behauptungen mit Rechnung beziehungsweise begründeter Interpretation. Benenne, welche zusätzliche Information für Aussagen über Armut, reale Lebensmöglichkeiten oder Gerechtigkeit fehlt. Es gibt keine Punkte für eine politische Wunschposition ohne Bezug auf die dargestellte Verteilung.

**Fall B – Rangwechsel und gleiche Kennzahl:** Eine andere Modellpopulation J1–J4 hat zunächst (10;10;30;50). J4 überträgt zehn Einheiten ausdrücklich an J1. Die Identität J1 bleibt gleich, aber die Rangposition kann wechseln. Als Vergleich liegt eine dritte, eigenständige Population C mit Einkommen (0;20;40;40) vor; sie hat dieselbe Einkommensdefinition, Haushaltszahl und Gesamtsumme. Eine Person sagt: „Bei gleichem Gini muss jeder Haushaltsanteil denselben Einkommensanteil erhalten; gleiche Kennzahl bedeutet auch gleiches Armuts- und Gerechtigkeitsurteil.“
B1 (4): Berechne die ursprünglichen Lorenzpunkte und den Gini von B. Erläutere den Unterschied zur ursprünglichen Verteilung A bei derselben Summe.
B2 (4): Verarbeite die Transferbuchung in den Haushaltsidentitäten, sortiere danach korrekt neu und berechne Punkte und Gini. Erläutere, warum die ursprüngliche Tabellenreihenfolge jetzt keine Lorenzreihenfolge ist und was sich tatsächlich verändert.
B3 (4): Berechne auch die Lorenzpunkte und den Gini für C, vergleiche C mit B vor dem Transfer und prüfe die Behauptung. Nutze mindestens einen konkreten Kurvenpunkt, um eine tatsächliche Verteilungsdifferenz trotz gleichem Gini zu zeigen, und erkläre die Grenzen der behaupteten Armuts-/Gerechtigkeitsaussage.'''
E='''**Two entirely fictional distribution cases – 24 marks.** All numbers are supplied teaching data, not present country values. Each case describes four equally sized one-person households with the same positive total income of 100 monetary units and the same definition of annual disposable income. The tables cover each entire model population, not a sample. Needs, prices, wealth and political standards of justice are not specified.

**Common calculation aid:** Sort current incomes in ascending order. The Lorenz curve plots cumulative household share horizontally and cumulative income share vertically. Start at (0,0); each household adds 0.25 to population share. Join the points with straight lines. For these data calculate the area A beneath the curve using A=Σ((Y_i+Y_(i−1))/2)×0.25 and G=1−2A on the 0–1 scale. Show points and workings. An equivalent correct calculation method earns equal credit. This is the specified unnormalised empirical four-household measure: for four households with nonnegative incomes its maximum is 0.75 rather than 1. This does not change the ranking of these cases.

**Case A – transfer without rank reversal:** H1–H4 incomes are (10,20,30,40). The stipulated transfer deducts eight units from H4 and gives them to H1; all other incomes, households and total income remain unchanged. One person says, “Everyone now has a just income; the smaller Gini proves it.” Another says, “If every income then doubles, the Gini doubles.” Prices and needs remain unspecified.
A1 (4): Provide original Lorenz points or a suitable sketch and calculate Gini. Explain the cumulative shares.
A2 (4): Give the post-transfer distribution, check ordering and recalculate Lorenz points and Gini. Interpret the change in relative distribution; do not equate a smaller Gini with identical incomes.
A3 (4): Examine both claims with calculation or reasoned interpretation. Explain what additional information is needed for conclusions about poverty, real living opportunities or justice. A political preference without reference to the distribution earns no marks.

**Case B – rank reversal and the same summary measure:** A different model population J1–J4 starts at (10,10,30,50). J4 transfers ten units specifically to J1. Household identity stays unchanged, but ranks can change. A third independent population C has incomes (0,20,40,40), with the same income definition, household count and total. Someone says, “With the same Gini every population share must receive the same income share; the same coefficient also implies identical poverty and justice conclusions.”
B1 (4): Calculate original Lorenz points and Gini for B. Explain how it differs from original A despite the same income total.
B2 (4): Apply the transfer to household identities, re-sort afterwards and calculate points and Gini. Explain why the original identity order is no longer Lorenz rank order and what actually changes.
B3 (4): Calculate Lorenz points and Gini for C, compare with pre-transfer B and examine the claim. Use at least one actual curve point to show a distributional difference despite equal Gini and explain the limits of the asserted poverty/justice conclusion.'''
SD='''A1: Sortierung 10,20,30,40; kumulierte Haushaltsanteile 0;0,25;0,5;0,75;1, Einkommensanteile 0;0,10;0,30;0,60;1. Die untere Hälfte erhält 30% des gesamten Einkommens, nicht 30% eines einzelnen Haushalts. A=0,375 und G=0,25.
A2: 18,20,30,32 bleibt aufsteigend; Einkommensanteile 0;0,18;0,38;0,68;1. A=0,435, G=0,13. Der Gini sinkt um0,12 beziehungsweise12 Punkte auf einer 0–100-Skala; Einkommen bleiben verschieden. Der gegebene Transfer reduziert relative Ungleichheit, ohne alle anderen sozialen Fragen zu lösen.
A3: Verdoppelte Einkommen 36,40,60,64 haben Summe200 und dieselben Anteile/Lorenzpunkte/Gini0,13. Die Kennzahl erfasst relative Verteilung, nicht Einkommenshöhe. Preisentwicklung und Bedürfnisse fehlen für reale Möglichkeiten oder eine Armutsgrenze, ein normativer Maßstab für Gerechtigkeit; auch Vermögen/weitere Lebensbedingungen sind nicht erfasst. Weder kleinerer Gini noch Verdopplung belegt automatisch Armutsfreiheit oder ein einzig richtiges Gerechtigkeitsurteil.
B1: 10,10,30,50; Anteile 0;0,10;0,20;0,50;1. A=0,325, G=0,35. Bei derselben Summe ist die relative Verteilung ungleicher als ursprünglichesA(G0,25), nicht notwendigerweise ein Beweis geringerer Einkommen aller oder größerer Armut.
B2: Identitäten erhalten 20,10,30,40. Neu sortiert 10,20,30,40; Punkte wie ursprünglichesA, A=0,375 und G=0,25. J2 kommt nun vor J1; die Haushaltsidentität und die Rangposition sind verschiedene Informationen. Lorenzsortierung beschreibt die aktuelle Verteilung, nicht dauerhafte Haushaltsrangplätze. Die absolute Summe bleibt100 und G sinkt0,10.
B3: C:0,20,40,40; Anteile0;0;0,20;0,60;1. A=0,325, G=0,35 wieBvorher. Bei25% Haushaltsanteil erhältC0% stattB10%, bei75% erhältC60% stattB50%; die Kurven schneiden sich bzw. wechseln ihre relative Lage. Derselbe Gesamtflächenabstand/Gini bedeutet keine identischen Kurven oder Einzelverteilungen. Armutsurteile benötigen einen ausdrücklich definierten Maßstab, Preise und gegebenenfalls weitere Bedingungen; Gerechtigkeit eine begründete normative Sicht. Der beobachtete Nullbetrag vonC ist keine ausreichende Definition einer allgemeinen Armutsquote.

**Bewertung:** Bewerte die gezeigte fachliche Leistung kriterial, akzeptiere gleichwertige Methoden, Darstellungen und begründete politische Bewertungen. Jede Aufgabe hat4Punkte; unvollkommene richtige Arbeit erhält Teilpunkte und kann bestehen. Eine einzelne Rechenungenauigkeit, eine nur verbal beschriebene korrekte Kurve oder eine fehlende Nebeninformation löst keine pauschale Begrenzung aus. Nur wenn die Konstruktion/korrekte Bedeutungszuordnung von Lorenzanteilen, die Ermittlung/relative Deutung des Gini oder eine fachliche Begrenzung des Indikatorurteils über beide Fälle vollständig fehlt oder durchgehend fachlich falsch ersetzt wird, wird die Gesamtwertung auf14von24begrenzt. Das ist eine Obergrenze nach der kriterialen Bewertung, kein zusätzlicher Punktabzug. Teilleistungen einer Kernleistung zählen: etwa ein begründeter Hinweis auf fehlende Preise oder den normativen Gerechtigkeitsmaßstab ist eine tatsächliche Begrenzung, auch wenn andere Grenzen fehlen.'''
SE='''A1: Sorted10,20,30,40; cumulative household shares0,0.25,0.5,0.75,1 and income shares0,0.10,0.30,0.60,1. The lower half receives30% of total income, not30% of one household’s income. Area0.375 and Gini0.25.
A2:18,20,30,32 remains ascending; income shares0,0.18,0.38,0.68,1. Area0.435, Gini0.13. Gini falls0.12, equivalent to12points on a0–100scale; incomes remain different. The stipulated transfer lowers relative inequality without settling all other social questions.
A3: Doubled36,40,60,64 total200 and retain the same shares/Lorenz points/Gini0.13. The coefficient measures relative distribution, not income level. Prices and needs are missing for real opportunities or a poverty threshold; justice needs a normative standard. Wealth and other living conditions are not covered. Neither a lower Gini nor doubled nominal income guarantees absence of poverty or one uniquely correct justice judgment.
B1:10,10,30,50; shares0,0.10,0.20,0.50,1. Area0.325, Gini0.35. Relative distribution is more unequal than initialA(Gini0.25) despite the same total, not proof that everyone has less income or poverty is greater.
B2: Identities receive20,10,30,40. Re-sort10,20,30,40; points match initialA, area0.375, Gini0.25. J2 now comes before J1; identity differs from income rank. Lorenz ordering describes current distribution rather than permanent household positions. Total stays100 and Gini falls0.10.
B3: C:0,20,40,40; shares0,0,0.20,0.60,1. Area0.325, Gini0.35 like pre-transferB. At25% households C receives0% versusB10%, while at75% C receives60% versusB50%; the curves cross or change relative position. Identical total-area difference/Gini does not imply identical curves or household distributions. Poverty judgments need an explicitly defined threshold, prices and possibly other conditions; justice needs reasoned normative criteria. One observed zero income is not itself a definition of a general poverty rate.

**Scoring:** Apply the criteria to substantive work shown; equivalent methods, representations and justified political evaluations earn equal credit. Each task has4marks; imperfect correct work earns partial credit and may pass. One arithmetic inaccuracy, a correct verbal curve or one missing secondary detail triggers no blanket limit. Only where Lorenz-share construction/meaning, Gini calculation/relative interpretation, or substantive limits to an indicator judgment are entirely absent or consistently replaced by a substantively wrong account across both cases is the total capped at14of24. This is a ceiling after criterion scoring, not an extra deduction. Partial core performances count: a justified observation about missing prices or normative justice criteria is a real limitation even if other limits are omitted.'''
# Product texts receive spaces around inline runs that were initially written compactly in author's solution, without changing numbers or meanings.
import re
for name in ['SD','SE']:
 t=globals()[name];t=re.sub(r'(?<=\w)(?=\d)', ' ', t);t=re.sub(r'(?<=\d)(?=[A-Za-zÄÖÜäöü])',' ',t);globals()[name]=t
steps=[('A: Lorenzpunkte/Anteilsbedeutung2, Fläche/Gini2','A: Lorenz points/share meaning2, area/Gini2'),('A: Transferdaten/Sortierung1, Punkte/Gini2, relative Deutung1','A: transfer/order1, points/Gini2, relative interpretation1'),('A: Skalierung2, begründete Indikatorgrenze2','A: scale invariance2, reasoned indicator limit2'),('B: Lorenz/Gini3, vergleichende Deutung1','B: Lorenz/Gini3, comparative interpretation1'),('B: Identitäten/neue Sortierung1, Lorenz/Gini2, Rangdeutung1','B: identity/re-sorting1, Lorenz/Gini2, rank interpretation1'),('C: Punkte/Gini2, konkrete Verteilungsdifferenz1, begrenztes Urteil1','C: points/Gini2, actual distributional difference1, bounded judgment1')]
m={'id':mid,'title':'Q2 LK: Gini, Lorenzkurve und Grenzen in zwei Verteilungsfällen','titleEn':'Q2 LK: Gini, Lorenz curves and limits in two distribution cases','description':'Die lernende Person kann zwei vollständige neue Verteilungsfälle mit Lorenzkurven und Gini selbstständig auswerten, tatsächliche Transferwirkungen erklären und die Grenzen der Indikatorurteile begründen.','descriptionEn':'The learner can independently analyse two complete new distribution cases using Lorenz curves and Gini, explain actual transfer effects and justify limits to indicator judgments.','weight':1,'tags':['LK','Practice','Assessment'],'contains':[],'requires':[goal['id']],'type':'atomic','phase':'Q2','dimensionTags':{'framework':'canonical-gymnasium-economics','demandLevel':'AB3','phase':'Q2'},'applicability':copy.deepcopy(goal['applicability']),'extendedData':{'applicabilityFromRequires':True},'examData':{'reviewStatus':'draft','coveredGoalIds':[goal['id']],'coveredStrands':['WW_WIRTSCHAFT','WW_GESELLSCHAFT'],'demandLevels':['AB1','AB2','AB3'],'taskContent':D,'taskContentEn':E,'solutionContent':SD,'solutionContentEn':SE,'scoring':{'maxPoints':24,'passingPoints':15,'steps':[{'id':'s'+str(j+1),'points':4,'description':de,'descriptionEn':en} for j,(de,en) in enumerate(steps)]}}}
(O/'whole-one-pure-Gini-LK-two-real-transfer-and-ranking-cases.DRAFT-author-v1.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
# Whole contracts/P cases are bound to the existing unchanged current goal, no new math atom.
Ppath=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-thirty-existing-foreign-KEEP-E7-global-access-bindings-author-v1/actual-schema-field-name-native-author-successor-v2/frozen-current518-inputs/whole-current336-P685.exact.jsonl';P=next(json.loads(x) for x in Ppath.read_text().splitlines() if x.strip() and json.loads(x)['goalId']==goal['id']);(O/'whole-current424-DEEN-contract-and-original-two-P-cases.exact-author-input.json').write_text(json.dumps({'wholeGoal':goal,'wholeOriginalP':P,'nativeSemanticRequiresQualifiedExisting6bf':True,'newOrdinaryGoalCount':0,'MathematicsLandscapeOrPackagesModified':False,'baseActiveCANSHA256':hashlib.sha256((R/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_WIRTSCHAFT.de.json').read_bytes()).hexdigest()},ensure_ascii=False,indent=2)+'\n');print(mid,hashlib.sha256((O/'whole-one-pure-Gini-LK-two-real-transfer-and-ranking-cases.DRAFT-author-v1.json').read_bytes()).hexdigest())
