// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs'
import {resolve,dirname,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import {stableGoalBookJson} from './native-isolated-repository/app/scripts/goalBookModel.ts'
import {validatePreparedGoalDescriptionRolloutBatch,materializeGoalDescriptionRolloutBatchDualSummary,materializeGoalDescriptionRolloutBatchResolutionIndex} from './native-isolated-repository/app/scripts/materializeGoalDescriptionRolloutBatch.ts'
import {extractGoalDescriptionDualRoundResolutionSource,buildGoalDescriptionDualRoundResolution,validateGoalDescriptionDualRoundResolution,fingerprintGoalDescriptionReviewContext} from './native-isolated-repository/app/scripts/validateGoalDescriptionDualRoundResolution.ts'
import {buildGoalDescriptionRolloutSynthesisRoundBinding,fingerprintGoalDescriptionRolloutSynthesisDecisionManifest,validateGoalDescriptionRolloutSynthesisDecisionManifest} from './native-isolated-repository/app/scripts/validateGoalDescriptionRolloutSynthesisDecisionManifest.ts'
import {buildGoalDescriptionRolloutResolutionSynthesis} from './native-isolated-repository/app/scripts/goalDescriptionRolloutResolutionSynthesis.ts'
const own=dirname(fileURLToPath(import.meta.url)),iso=resolve(own,'native-isolated-repository'),out=resolve(iso,'outputs/prepared-three'),config='config/native-three.prepared.config.json'
const sha=(v:Buffer|string)=>'sha256:'+createHash('sha256').update(v).digest('hex'),read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),write=(p:string,v:any)=>{mkdirSync(dirname(p),{recursive:true});writeFileSync(p,JSON.stringify(v,null,2)+'\n',{flag:'wx'})}
await validatePreparedGoalDescriptionRolloutBatch(config)
const dual=await materializeGoalDescriptionRolloutBatchDualSummary(config,true),input=dual.first.input,manifest=read(resolve(out,'batch-manifest.json')),batchId=manifest.batchId
assert.notEqual(dual.first.campaign.campaignId,dual.second.campaign.campaignId);assert.notEqual(dual.first.campaign.independenceGroupId,dual.second.campaign.independenceGroupId)
assert.equal(dual.first.campaign.batchSize,20);assert.equal(dual.second.campaign.batchSize,20)
const canon=resolve(iso,manifest.source.landscapePath),landscape=read(canon)
const sources=input.goals.map((g:any)=>{const a=extractGoalDescriptionDualRoundResolutionSource({artifacts:dual.first,goalId:g.goalId,label:'Actual sealed A'}),b=extractGoalDescriptionDualRoundResolutionSource({artifacts:dual.second,goalId:g.goalId,label:'Actual sealed B'});assert.deepEqual(a.errors,[]);assert.deepEqual(b.errors,[]);assert.equal(a.source!.decision,'keep');assert.equal(b.source!.decision,'keep');return {goal:g,first:a.source!,second:b.source!}})
const synthesizedAt=new Date(Math.max(...[...dual.first.resultPairs,...dual.second.resultPairs].map(({run}:any)=>Date.parse(run.completedAt)))+1000).toISOString()
const batchBinding={batchId,batchManifestDigest:sha(readFileSync(resolve(out,'batch-manifest.json'))),configDigest:manifest.configDigest,bundleFingerprint:manifest.artifacts.bundleFingerprint,bookDigest:input.bookDigest,reviewInputFingerprint:input.reviewInputFingerprint,dualSummaryDigest:sha(dual.bytes),canonicalLandscapeDigest:sha(readFileSync(canon))}
const rounds={first:buildGoalDescriptionRolloutSynthesisRoundBinding(sources[0].first.binding,dual.first.campaign.batches[0].batchInputFingerprint),second:buildGoalDescriptionRolloutSynthesisRoundBinding(sources[0].second.binding,dual.second.campaign.batches[0].batchInputFingerprint)}
const expectedGoals=sources.map(({goal:g,first,second}:any)=>({goalId:g.goalId,effectiveSemanticKind:'curricularAtomic',goalFingerprint:g.goalFingerprint,pageFingerprint:g.pageFingerprint,goalReviewContextFingerprint:fingerprintGoalDescriptionReviewContext(g),finalText:{titleDe:g.currentTitleDe,titleEn:g.currentTitleEn,descriptionDe:g.currentDescriptionDe,descriptionEn:g.currentDescriptionEn},firstSource:first,secondSource:second}))
const decisions=sources.map(({goal:g,first,second}:any)=>({decisionId:batchId+'-decision-'+g.goalId,goalId:g.goalId,effectiveSemanticKind:'curricularAtomic',goalFingerprint:g.goalFingerprint,pageFingerprint:g.pageFingerprint,goalReviewContextFingerprint:fingerprintGoalDescriptionReviewContext(g),finalText:{titleDe:g.currentTitleDe,titleEn:g.currentTitleEn,descriptionDe:g.currentDescriptionDe,descriptionEn:g.currentDescriptionEn},resolutionDecision:'keep_current',evidenceRound:'first',records:{first:{recordId:first.binding.recordId,recordDigest:first.binding.recordDigest},second:{recordId:second.binding.recordId,recordDigest:second.binding.recordDigest}},rationaleDe:'Technische Zusammenführung der echten unabhängig versiegelten A-/B-Erstbewertungen des gleichen vollständigen aktuellen bilingualen Ziels, nativer Seite und Quellen-/Bild-/Kontexteingänge. Alle originalen Records, Run-IDs und Campaign-IDs bleiben exakt. Keine neue fachliche Prüfung oder menschliche Freigabe. A: '+first.record.rationale.slice(0,1500)+' B: '+second.record.rationale.slice(0,1500),rationaleEn:'Technical factual synthesis of genuine sealed independent A/B first-pass judgments over identical whole current bilingual goals, native pages and source/image/context inputs. Original records, runs and campaign identifiers are retained exactly. No new scientific review or human approval. A: '+first.record.understandingEvidence.essentialUnderstandingEn.slice(0,1200)+' B: '+second.record.understandingEvidence.essentialUnderstandingEn.slice(0,1200)}))
const payload={$schema:'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-rollout-synthesis-decision-manifest.schema.json',schemaVersion:1,synthesisContract:'goal-description-rollout-synthesis-decision-v1',manifestId:batchId+'-paired-current-synthesis',authority:'ai_synthesis',synthesizedBy:'Codex technical integration of actual sealed A/B science; model version not exposed',synthesizedAt,batch:batchBinding,rounds,decisions}
const synthesis={...payload,manifestFingerprint:fingerprintGoalDescriptionRolloutSynthesisDecisionManifest(payload as any)};const sv=await validateGoalDescriptionRolloutSynthesisDecisionManifest({manifest:synthesis as any,expected:{batch:batchBinding as any,rounds,synthesizedAt,goals:expectedGoals as any}});assert.deepEqual(sv.errors,[])
const sp=resolve(out,'synthesis-decisions.json');write(sp,synthesis);const sb=readFileSync(sp)
for(const s of sources){const decision=decisions.find(d=>d.goalId===s.goal.goalId)!,summaryGoal=dual.summary.goals.find((g:any)=>g.goalId===s.goal.goalId)!,fact=buildGoalDescriptionRolloutResolutionSynthesis({batchId,manifest:synthesis as any,decision:decision as any,summaryGoal,firstSource:s.first,secondSource:s.second});const resolution=buildGoalDescriptionDualRoundResolution({resolutionId:batchId+'-resolution-'+s.goal.goalId,goalId:s.goal.goalId,effectiveSemanticKind:'curricularAtomic',decision:'keep_current',synthesis:fact,dualSummaryBytes:dual.bytes,currentInput:input,firstSource:s.first,secondSource:s.second,synthesisDecisionManifest:{contract:'goal-description-rollout-synthesis-decision-v1',manifestId:synthesis.manifestId,manifestPath:'synthesis-decisions.json',manifestDigest:sha(sb),manifestFingerprint:synthesis.manifestFingerprint,decisionId:decision.decisionId}});const v=await validateGoalDescriptionDualRoundResolution({resolution,dualSummary:dual.summary,dualSummaryBytes:dual.bytes,currentInput:input,landscape,first:dual.first,second:dual.second,synthesisDecisionManifestArtifact:{manifest:synthesis as any,manifestBytes:sb,manifestPath:'synthesis-decisions.json'}});assert.deepEqual(v.errors,[]);assert.equal(v.strictDescriptionComplete,true);write(resolve(out,'resolutions',s.goal.goalId+'.resolution.json'),resolution)}
const finalized=await materializeGoalDescriptionRolloutBatchResolutionIndex(config,true);assert.equal(finalized.index.resolutions.length,3);assert.ok(finalized.index.resolutions.every(r=>r.strictDescriptionComplete))
write(resolve(own,'native-D3-exact-science-lineage.actual.json'),{documentType:'Actual native standard D3 paired materialization and upper finalize',D3:'PASS',resolvedGoalIds:input.goals.map(g=>g.goalId),originalScientificRecordsRunsCampaignsExact:true,identifierRelabeling:false,independenceGroupIds:[dual.first.campaign.independenceGroupId,dual.second.campaign.independenceGroupId],modelSourcePath:manifest.source.landscapePath,currentCandidateCanonicalGoals:landscape.goals.length,indexPath:relative('/home/enpasos/projects/skillpilot',resolve(out,'resolution-index.json')),activeWrites:false,newScientificJudgments:false,humanApproval:false,humanTrial:false})
console.log(JSON.stringify({D3:'PASS',nativeUpperFinalize:'PASS',genuineOriginalIndependentCampaigns:true,activeWrites:false}))
