import pathlib,json,copy,datetime,hashlib
O=pathlib.Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-dd38-543b-source-course-f08-036ea-followers-AUTHOR-INERT-round-b-v1');(O/'candidates').mkdir(exist_ok=True);H=O/'history';C=O/'candidates'; DD='dd38e0c5-d77b-5893-815c-548ea2a84429';V='776457c2-8bb3-53b9-838b-a028319175fb';P='a5009946-62bb-5e6a-8c92-732d02e8fd70';PO='543bf91f-f6c6-5b1b-ba9e-43de321d8c7f';POL='da73483a-2c18-5d42-b4f3-6ac6bcd6b5b0';S='f1f73ebe-286a-52e8-a2e1-4383ece6e9ec';F='f08e0a97-bcdd-504d-a9d9-7b1d8e6d4f96';Q='036ea7f9-2a33-502f-8729-983fa8054694'
def put(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
f=json.loads((H/(F+'.whole-current-goal.exact.json')).read_text());q=json.loads((H/(Q+'.whole-current-goal.exact.json')).read_text())
f['description']='Die lernende Person kann gegebene Betriebsfälle selbstständig hinsichtlich Arbeitsstunden, Beschäftigtenzahl, Einkommen, geregelter betrieblicher Mitsprache und unterschiedlicher Entlohnungsformen analysieren und bedingte Folgen aus Arbeitnehmer- und Arbeitgebersicht begründet beurteilen.';f['descriptionEn']='The learner can independently analyse supplied business cases through hours worked, headcount, income, regulated employee voice and different remuneration forms, and give reasoned conditional judgements from employee and employer perspectives.'
f['requires']=[DD,V,P];f['applicability']={'jurisdiction':['DE-HE']};f['examData']['coveredGoalIds']=f['requires'].copy();f['examData']['reviewStatus']='needs_review';f['examData']['reviewNote']='INERT E1/G1 ai_candidate; needs_human_review. Own author expansion preserves all original case numbers/performance domains and adds actual whole workplace-rights/job-vs-performance/pay criteria. Native schema/binding checks are technical only. Independent whole source/course/A/M/cards/Practice/D/P/V review, human approval and learner trial remain open. HE-only candidate scope is conditional on actual subject choices; no default target or release claim.'
f['examData']['taskContent']='''**Arbeitszeit, Mitsprache und Entlohnung – 40 Punkte, bestanden ab 25.** Die Betriebs-, Leistungs- und Vergütungsdaten sind fiktive Unterrichtsmodelle. Die bereitgestellte Regelkarte fasst den tatsächlich gelesenen geltenden Normrahmen für die ausdrücklich begrenzten Fallfragen zusammen; keine persönlichen Angaben oder echten Kontakte sind nötig. Bewertet werden die fachlichen Leistungen der ganzen Arbeit; eine zusammenhängende Bearbeitung darf die geforderten Leistungen an geeigneter Stelle verbinden.

**A – Auftragsrückgang und Dienstplan.** 100 Beschäftigte arbeiten je 40 Stunden/Woche für 20 Euro/Stunde. Bei gleicher Produktivität sind vorübergehend 3200 statt 4000 Stunden nötig. K: 32 Stunden für alle, proportional bezahlt. E: 20 Entlassungen, 80 Personen weiterhin je40 Stunden. Beschäftigte äußern Zeitwünsche und beraten mit dem Betrieb Abdeckungsregeln. Das ist organisatorische Mitsprache, keine Kapital-/Gewinnbeteiligung. Im privaten Betrieb besteht ein zuständiger Betriebsrat; das BetrVG ist im gegebenen Fall anwendbar. Streit betrifft nur Beginn/Ende/Pausen und Verteilung des konkreten Dienstplans. Eine diese Frage abschließend regelnde gesetzliche oder tarifliche Vorschrift besteht laut Material nicht. Gesetzliche Schutzgrenzen bleiben zu beachten; der Fall erklärt weder Entlassungen noch dauerhafte Änderung der Vertragswochenstunden allein durch das Dienstplanrecht für zulässig. Die Leitung will kurzfristig planen, Beschäftigte verlässliche Zeiten. Zum Dienstplan gibt es noch keine Einigung.

**Vergütungsdaten desselben Betriebs.** Alle100 Beschäftigten in A haben das Tätigkeitsprofil X. Die fiktive Arbeitsbewertung summiert Qualifikation, Verantwortung und Komplexität: X=3+2+1, Vergleichsprofil Y=4+3+3. Die Modellgrundvergütung ist 8+2×Punktesumme Euro/Stunde. Y ist ein Vergleich anderer Aufgabenanforderungen, keine Behauptung über die Leistung oder einen zusätzlichen Arbeitsplatz in A. Für gleichartige X-Arbeit werden acht Stunden mit20 Euro/Stunde oder alternativ0,50 Euro je abgenommenem Stück angeboten. I fertigt40, J50 abgenommene Stücke jeStunde bei derselben gegebenen Qualität. Ausschuss wird nicht vergütet; Arbeitsintensität und Qualitätskontrolle sind für die Bewertung wichtig. Stück- und Zeitlohn sind Modellalternativen, keine gleichzeitig addierten Zahlungen.

**B – Service, Information und variable Vergütung.** 20 Personen arbeiten je40 Stunden, Gesamtumfang bleibt gleich; Gleitzeit verändert nur die Lage. Täglich10–14 Uhr sind mindestens12 Personen nötig. Der neue, bereits vereinbarte Teamplan deckt14, der alte10; andere Fenster sind nicht vollständig dokumentiert. Der Betriebsrat will die Einhaltung der zugunsten der Beschäftigten geltenden Schutzregeln und die Vereinbarkeit von Familie/Erwerbsarbeit prüfen. Er verlangt dafür rechtzeitig erforderliche anonymisierte Dienstplan- und Belastungsinformationen. Die Leitung verweist auf Planungsaufwand und lehnt alle Angaben ab. In dieser Informationsfrage wird kein allgemeines Recht auf beliebige Unterlagen oder Übernahme der Geschäftsleitung unterstellt; die bereits vereinbarte Lage wird dadurch nicht erneut automatisch freigegeben oder gesperrt.
F: Jede Person erhält sicher1000 Euro/Jahr zusätzlich. G: Freiwillig10% des angegebenen Gesamtgewinns, gleich verteilt auf20. Gewinne können100000,200000 oder0 Euro sein; Wahrscheinlichkeiten fehlen. G enthält keine Stimm-/Entscheidungsrechte. Dritte Modellalternative Q: Qualitätsbonus1000 Euro/Person nur bei mindestens95% korrekt erledigten Servicefällen im Team; sonst0. Es handelt sich um getrennte Vergütungsalternativen; die genannten G-Gewinne sind für die G-Rechnung fest vorgegeben. Drei beobachtete Modellperioden liefern: (i)96%/Gewinn100000, (ii)90%/Gewinn200000, (iii)96%/Gewinn0. Gewinn hängt auch von Nachfrage und Fremdkosten ab. Teamqualität ist keine Bewertung der Anforderungen eines einzelnen Arbeitsplatzes und kein Beweis gleicher individueller Beiträge.

**Begrenzte Regelkarte – BetrVG, gelesen am10.10.2026.** §87(1), insbesondere Nr2, betrifft die Mitbestimmung bei Beginn/Ende/Pausen und Verteilung der täglichen Arbeitszeit unter dem gesetzlichen/tariflichen Regelungsvorbehalt; nach§87(2) entscheidet bei fehlender Einigung die Einigungsstelle. §80(1)Nr1 und2b betreffen Überwachung zugunsten der Arbeitnehmer geltender Regeln und Förderung der Vereinbarkeit von Familie/Erwerbstätigkeit. Nach§80(2) erhält der Betriebsrat rechtzeitig umfassende Unterrichtung und auf Verlangen die für seine gesetzlichen Aufgaben erforderlichen Unterlagen. Allgemeine Aufgaben/Information sind von einem konkreten Mitbestimmungsrecht zu unterscheiden. Quellen: https://www.gesetze-im-internet.de/betrvg/__87.html und https://www.gesetze-im-internet.de/betrvg/__80.html. Diese eigene Zusammenfassung ersetzt keine umfassende Prüfung anderer Arbeitsrechtsfragen.

1(4): Berechne A-Stunden,40-Stunden-Vollzeitäquivalente und Köpfe in K/E; erkläre die Unterscheidung.
2(4): Vergleiche Wocheneinkommen und Lastenverteilung; beurteile die Behauptung kostenloser Arbeitsplatzsicherung.
3(10): Analysiere A-Mitsprache über Information, Koordination, Bindung, eine Bedingung und Nebenwirkung. Wende die Regelkarte auf A-Dienstplan/fehlende Einigung und B-Aufgabe/Informationsverlangen an. Begründe eine tragfähige Lösung aus Beschäftigten- und Betriebssicht und ihre Grenzen.
4(4): Prüfe B-Abdeckung und Stunden. Erkläre mögliche Verbesserungen und Grenzen einer Beschäftigungsbehauptung.
5(4): Berechne G jePerson für alle genannten Gewinnstände, vergleiche F und trenne finanziellen Anteil von organisatorischer Mitsprache.
6(14): Beurteile Anreize, Einkommensrisiko und bedingte Beschäftigungswirkung; begründe eine faire Regel ohne erfundenen Erwartungswert. Nutze Arbeitsbewertung X/Y, individuellen Zeit-/Stücklohn und Q/F/G in den gegebenen Perioden. Trenne Arbeitsplatzanforderung, individuelle Leistung, Teamleistung und Geschäftsergebnis; vergleiche aus beiden Perspektiven.

Nachvollziehbare teilweise richtige Arbeit und begründete alternative Urteile erhalten entsprechende Punkte; keine bestimmte Aufgabenüberschrift oder zusätzliche Fallzahl ist Pflicht. Die ursprünglichen24 Punkte für Stunden/Einkommen/Mitsprache/Service/Gewinn/bedingte Folgen bleiben erhalten;16 zusätzliche Punkte gelten den konkret ergänzten Rechts- und Entlohnungsleistungen. Ein einzelner Rechen-/Detailfehler oder eine unvollständige Begründung begrenzt die Gesamtleistung nicht pauschal. Nur bei vollständig fehlender oder durchgehend sachlich falsch ersetzter Stunden-/Kopfzahlunterscheidung, geregelter Mitsprache oder Unterscheidung von Arbeitsbewertung/Leistung/variablem Ergebnis in der ganzen Arbeit bleibt die Gesamtwertung unter der Bestehensgrenze, höchstens24/40; die Begrenzung ist kein zusätzlicher Punktabzug.'''
f['examData']['taskContentEn']='''**Working time, employee voice and remuneration –40 marks; pass at25.** Business, output and pay data are fictional teaching models. The supplied rule card summarises the actually read current legal framework for expressly bounded case questions. No personal information or real contacts are needed. Substantive performance across the whole submission counts; a coherent response may connect required performances wherever appropriate.

**A – Falling orders and roster.**100 workers each work40 hours/week for EUR20/hour. At unchanged productivity3200 rather than4000 hours are temporarily needed. K:32 hours for everybody with proportional pay. E:20 dismissals,80 still work40 hours. Workers express time preferences and discuss coverage with management: organisational voice, not ownership/profit-sharing. This private business has a competent works council and the BetrVG applies in the stipulated case. The dispute concerns only roster start/end/breaks and distribution of daily hours. No statutory or collective rule conclusively governs that question according to the material. Protective legal limits still apply; roster co-decision alone makes neither dismissals nor a permanent change in contracted weekly hours lawful. Management wants short-notice planning; workers predictable hours. No roster agreement exists yet.

**Pay data from the same business.**All100 A workers have job profile X. Fictional job evaluation sums qualification, responsibility and complexity: X=3+2+1; comparison profileY=4+3+3. Model base pay=8+2×total points EUR/hour. Y compares different job requirements, not individual output or an extra A job. For identical X work, eight hours receive EUR20/hour or alternatively EUR0.50/accepted unit. I produces40, J50 accepted units/hour with the same stated quality. Rejects are unpaid; intensity and quality control matter. Piece/time wages are alternatives, not added payments.

**B – Service, information and variable pay.**20 people each work40 hours; flexitime changes timing alone. At least12 must work daily10:00–14:00. The already agreed new roster provides14 versus10 previously; other windows are incompletely documented. The council seeks to monitor protective rules benefiting staff and promote reconciliation of family/work. It asks for timely necessary anonymised roster/workload information. Management cites administrative workload and refuses everything. This question implies neither unlimited access to any documents nor takeover of management; information duties do not automatically reopen approval/blocking of the agreed roster.
F: fixed EUR1000/person/year supplement. G: voluntary10% of the stated total profit equally divided among20. Profits may be EUR100000,200000 or0, with no probabilities. G grants no voting/decision rights. Third alternativeQ: EUR1000/person quality bonus only with at least95% correctly completed team service cases; otherwise0. These are separate alternatives; G’s supplied profits are fixed inputs for its calculations. Three observed model periods: (i)96%/profit100000, (ii)90%/profit200000, (iii)96%/profit0. Profit also depends on demand/external costs. Team quality neither evaluates one job’s requirements nor proves equal individual contributions.

**Bounded rule card – BetrVG, read10October2026.**§87(1), particularly no2, concerns works-council co-decision on daily start/end/breaks and distribution subject to statutory/collective-rule reservation;§87(2) provides a conciliation committee when agreement fails. §80(1)nos1/2b concern monitoring protective rules and promoting family/work reconciliation. §80(2) provides timely comprehensive information and requested documents necessary for statutory tasks. Distinguish general tasks/information from a particular co-decision right. Primary sources: https://www.gesetze-im-internet.de/betrvg/__87.html and https://www.gesetze-im-internet.de/betrvg/__80.html. This own summary does not examine every other labour-law issue.

1(4): Calculate A hours,40-hour FTE and headcounts K/E; explain the distinction.
2(4): Compare weekly pay and burdens; assess the free-job-protection claim.
3(10): Analyse A voice through information, coordination, retention, a condition and side effect. Apply the card to A’s roster/no agreement and B’s task/information demand. Justify an arrangement from worker/firm perspectives and its limits.
4(4): Check B’s coverage/hours and explain improvements and limits of employment claims.
5(4): Calculate G per person for every stated profit level, compare F and distinguish financial participation from voice.
6(14): Assess incentives, income risk and conditional employment effects; justify a fair rule without invented expected values. Use X/Y job evaluation, individual time/piece pay and Q/F/G across periods. Distinguish job requirements, individual/team performance and business results; compare both perspectives.

Credit coherent partial work and equivalent reasoned judgements. No particular heading or additional number of cases is compulsory. The original24 marks for hours/pay/voice/service/profit/conditional effects remain;16 added marks address actual expanded legal/remuneration performances. Isolated arithmetic/detail errors or incomplete reasons trigger no blanket limit. Only completely absent or consistently wrong hours/headcount, regulated voice, or job-evaluation/performance/variable-result distinctions across the whole work limit the total below passing, at most24/40; this is not an additional deduction.'''
f['examData']['solutionContent']='''1: K100×32=3200h,80VZÄ,100Köpfe; E80×40=3200h,80VZÄ,80Köpfe. VZÄ misst Stunden, nicht Personen (je1P für K-Stunden/E-Stunden/beideVZÄ/Köpfe).
2: vorher800Euro; K640,−20%. EVerbleibende800; Entlassene keinen Betriebslohn, andere Einkommen unbekannt. Kverteilt Kürzung/hält Köpfe unter Nachfrage/Umsetzung, nicht kostenlos (je1P:800/640;−20%;Lasten;Bedingung).
3: Zeitwünsche liefern Information; gemeinsame Abdeckung kann Koordination/Bindung verbessern. Faire verlässliche Regeln und Nachfrage sind Bedingungen; Planung kostet Zeit, Wünsche können kollidieren; keine automatische Kopfzahlwirkung (ursprünglich4P,je1). Ergänzend6P: A§87(1)Nr2 mit Vorbehalt und Fallbegrenzung2P; fehlende Einigung→Einigungsstelle statt einseitigem allgemeinen Managementveto1P; B§80Überwachung/Familie plus notwendige rechtzeitige Aufgabeninformation2P; §80nichtautomatisch dasselbe Mitbestimmungsrecht/unbegrenzte Einsicht1P. Geordnete Einigung schützt Vorhersehbarkeit/Interessen und braucht betriebliche Abdeckung/Planbarkeit; die wirtschaftliche Abwägung hebt geltende Rechte nicht auf. Eine andere rechtlich und materiell tragfähige Lösung zählt.
4:20×40=800h;10<12,14≥12 mit2Puffer. Andere Fenster offen. Passende Lage kann Service/Bindung helfen, erzeugt keine zusätzlichen Stunden oder sichere Jobs (je1P).
5:0,10×100000/20=500, bei200000=1000, bei0=0. F1000sicher im Modell. Gvariabel, nur bei200000gleichhoch; finanzielle Beteiligung schafft keine Stimmrechte, A enthält echte organisatorische Mitsprache (je1P:500;1000/0;fest/variabel;Finanz/Voice).
6: Ursprünglich4P: begründeter Anreiz; Einkommens-/Fremdfaktorrisiko; bedingte Beschäftigungswirkung; transparente faire Regel ohne erfundene Wahrscheinlichkeiten. Zusätzliche10P: X6Punkte→20Euro/h,Y10→28, Arbeitsanforderungen statt Leistung2P;8hZeitlohn160, I8×40×0,50=160,J8×50×0,50=200 bei gleicher gegebenen Qualität2P; einzelne Outputleistung ändert nicht automatisch Arbeitsplatzgrade, Teamleistung und Jobbewertung auseinanderhalten2P; Q/F/Gi=1000/1000/500,ii=0/1000/1000,iii=1000/1000/0, unterschiedliche Bemessungsgrundlagen2P; beide Perspektiven zu Planbarkeit/Leistungsanreiz/Qualität/Intensität/Teameinfluss und Außenrisiko2P. Individueller Stücklohn kann Mengenanreiz/Qualitätsdruck erzeugen; Qreagiert aufTeamqualität, Gaufgegebenen Geschäftserfolg einschließlich Fremdfaktoren, Fverteilt vorhersehbar. Keines garantiert Beschäftigung; kein Erwartungswert ohne Wahrscheinlichkeiten. Teilpunkte je belegtem Element; Gewichtung/Priorität kann abweichen.
Bewertet wird die ganze Arbeit, ohne Zusatzfall-/Überschriftenquote. Alte24P plus tatsächliche neue16P; nur vollständige Kernabwesenheit/durchgehend falscher Ersatz wie in der Aufgabe beschrieben begrenzt auf24/40; kein Einzelirrtum löst dies aus.'''
f['examData']['solutionContentEn']='''1:K100×32=3200h,80FTE,100people;E80×40=3200h,80FTE,80people. FTE measures hours rather than people (1mark each:K hours/E hours/bothFTE/headcounts).
2:Previously800;K640(−20%). Eremaining800; dismissed receive no firm wage, other income unknown. Kshares cuts/retains heads under actual demand/implementation, not freely (1each:800/640;−20%;burdens;condition).
3:Preferences supply information; shared coverage can improve coordination/retention. Fair reliable rules/demand matter; planning uses time and preferences can conflict; no automatic headcount effect (original4marks,1each). Added6: A§87(1)no2 with reservation and bounded question2; failed agreement→conciliation rather than universal unilateral management veto1; B§80monitoring/family-work plus necessary timely task information2; general information≠the same co-decision right/unlimited documents1. Agreement protects predictable voice and needs coverage/planning; economic balancing does not remove rights. Equivalent legally/materially sound arrangements count.
4:20×40=800h;10<12;14≥12 with2buffer. Other windows unknown. Timing may support service/retention without extra hours/guaranteed jobs (1each).
5:0.10×100000/20=500;1000 with200000;0withzero. Ffixed1000. Gvaries/equal only at200000. Financial participation creates no voting right; Ahas actual voice (1each:500;1000/0;fixed/variable;financial/voice).
6:Original4:reasoned incentive; income/external-factor risk; conditional employment effect; transparent fair rule without invented probabilities. Added10: X6points→20/hour,Y10→28; requirements not individual output2;8htime160,I8×40×0.50=160,J8×50×0.50=200 with equal stated quality2; output does not automatically regrade a job; separate individual/team performance/job evaluation2;Q/F/Gperiodi=1000/1000/500,ii=0/1000/1000,iii=1000/1000/0 and different bases2; both perspectives on predictable pay,incentives,quality,intensity,team influence/external risk2. Piece wages can encourage quantity/quality pressure; Qreacts toteamquality,Gto business results including outside factors,Fis predictable. None guarantees jobs; no expected value without probabilities. Award partial credit for shown elements; different reasoned priorities count.
Assess whole work without added case/heading quota. Original24 plusactualnew16marks; only completely missing/consistently wrong core performances as stated limit to24/40; isolated errors do not.'''
f['examData']['scoring']={'maxPoints':40,'passingPoints':25,'steps':[{'id':'s1','points':4,'description':'Stunden/VZÄ/Köpfe: K-Stunden/E-Stunden/beideVZÄ/Köpfe je1.','descriptionEn':'Hours/FTE/heads:K hours/E hours/bothFTE/heads1each.'},{'id':'s2','points':4,'description':'800/640,−20%,Lastenverteilung,Bedingung je1.','descriptionEn':'800/640,−20%,burdens,condition1each.'},{'id':'s3','points':10,'description':'Alte Informations-/Koordinations-/Bedingungs-/Grenzleistungen4; neue§87Recht2/Einigung1,§80Aufgabe+Info2/Grenze1.','descriptionEn':'Originalinformation/coordination/condition/limit4; added§87right2/settlement1,§80task+information2/limit1.'},{'id':'s4','points':4,'description':'800h,Abdeckung,Puffer/andereFenster,LageohneJobgarantie je1.','descriptionEn':'800h,coverage,otherwindows,timingwithoutjobguarantee1each.'},{'id':'s5','points':4,'description':'G500,G1000/0,FfestvsGvariabel,finanziellvsMitsprache je1.','descriptionEn':'G500,G1000/0,fixedFvsvariableG,financialvsvoice1each.'},{'id':'s6','points':14,'description':'AlteAnreiz/Risiko/bedingteJobs/Fairness4; neueArbeitsbewertung/Individualrechnung/Trennungen/QFG/BlickbeiderSeiten je2.','descriptionEn':'Originalincentive/risk/conditionaljobs/fairness4;addedjobevaluation/individualcalculation/distinctions/QFG/bothperspectives2each.'}]}
q['description']='Die lernende Person kann gegebene Entwicklungsfälle selbstständig hinsichtlich sektoraler Struktur und Wachstum, vergleichbarer Armutsindikatoren und finanzierbarer Strategien für materielle Sicherung und tatsächlich nutzbare Teilhabe analysieren und begründet auswerten.';q['descriptionEn']='The learner can independently analyse and reason about supplied development cases through sector structure and growth, comparable poverty indicators and affordable strategies for material security and actually usable participation.';q['requires']=[S,PO,POL];q['applicability']={'jurisdiction':['DE-HE']};q['examData']['coveredGoalIds']=q['requires'].copy();q['examData']['reviewStatus']='needs_review';q['examData']['reviewNote']='INERT E1/G1 ai_candidate; needs_human_review. All old whole structural/measurement/strategy performances and core case numbers retained. Actual added price/distribution/overlap/take-up/capacity/evaluation facts extend the whole543/da734 contracts. Technical checks do not qualify source/course/semantic/material/D/P/V or human/learner gates. HE-only candidate scope requires actualQ4.1 selection and separate reviewed da734GK/LKQ4placement; other historical country roles remain explicitly open.'
q['examData']['taskContent']='''**Strukturwandel, Armutsmessung und nutzbare Entwicklungswege –50 Punkte, bestanden ab30.** Alle Länder und Daten sind fiktiv. Output/Geld sind real in derselben Einheit, außer den ausdrücklich als nominal bezeichneten B-Einkommen. Die Messgruppen und Zeitbezüge sind genannt; reale Staaten werden nicht bewertet. Fachliche Leistungen dürfen in einer zusammenhängenden Analyse verbunden werden; Überschriften oder eine zusätzliche Zahl von Fällen sind keine Leistungsvoraussetzung.

**A – LandU.** Landwirtschaft erzielt20%Wertschöpfung/60%Beschäftigung; Industrie30/15%, Dienstleistungen50/25%. Qualifikation/Transport fehlen; Industrie kann zunächst höchstens50 zusätzliche Personen aufnehmen. R/S haben je100 Einwohner, reale Armutsgrenze100 und jeweils40 Menschen darunter. R:20mit50,20mit90; S:40mit80; übrige Einwohner über100. Armutstiefe ist Summe positiver Lücken zu100 geteilt durch100×gesamteEinwohnerzahl. R:30%ohne sicheren Wasser-,20%ohne verlässlichen Schulzugang; S:20%Wasser-,35%Schulmangel. Überschneidungen der betroffenen Personen sind unbekannt; Einkommen und Zugang sind verschiedene Messgegenstände.
Etat1000 für diese Förderperiode. Direkte gezielte Transfers können vorhandene Einkommenslücken mindern. Bei voller tatsächlicher Erreichbarkeit besteht rechnerisch keine weitere Auszahlungsschranke; derzeit können aber nur60von100Einwohnern die Antragswege nutzen, und welche armen Personen darunter sind, ist unbekannt. Eine Antrags-/Zugangshilfe kostet200; sie soll Zugang verbessern, garantiert jedoch weder100%Teilnahme noch ein bestimmtes Empfängereinkommen. Alternativ kosten50berufliche Lernplätze samt Transport für sechsMonate1000; sie verbessern Voraussetzungen, garantieren keine neuen Einkommen/Arbeitsplätze und brauchen nach Ablauf passende Wege/Finanzierung. Auch vorliegende Industrieaufnahmegrenze bleibt. Die zugänglichen Dienste außerhalb der Projektperiode und längerfristige Nachfrage sind nicht belegt.
A1(10): Analysiere beide sektoralen Anteilsreihen und relative durchschnittliche Wertschöpfung jeBeschäftigten. Vergleiche produktivere Landwirtschaft mit einem Übergang in andere Tätigkeiten unter den Grenzen; keine individuelle Produktivität aus Durchschnitt ableiten.
A2(15): Vergleiche Quote/Tiefe/Lücken R/S und die zusätzlichen Mangelindikatoren, einschließlich möglicher Wasser-/Schulüberschneidung. Beurteile Transfer versus Produktions-/Zugangsförderung anhand unmittelbarer Bedürftigkeit, tatsächlichem Zugang, Etat und längerer Frist. Begründe eine finanzierte Priorität/Kombination und nenne überprüfbare Zielgrößen für ihre Wirkung.

**B – LandV.** Reale Gesamtwertschöpfung100→150, Landwirtschaftsanteil30→24%. Hochqualifizierte Dienstleistungen wachsen, informelle Arbeit bleibt verbreitet; nur20von80Bewerbern erfüllen derzeit die Zugangsvoraussetzungen. JeZeitpunkt werden200Personen durch getrennte Querschnitte untersucht, ohne individuelle Verknüpfung. T0:80Einkommen75,120Einkommen120 zuT0-Preisen; Armutsgrenze100. T1:50nominal108,150nominal180; Preisniveau20%überT0. Die Statistik nutzt weiterhin die gleiche reale Armutsgrenze und meldet monetär40→25%. JeZeitpunkt fehlen30% sicherer Wasser- und20% verlässlicher Schulzugang; Überschneidungen unbekannt.
Transferoption600 kann gegenwärtige Einkommenslücken mindern, bei tatsächlicher Erreichbarkeit. Wasser-/Schulangebot fehlt in abgelegenen Dörfern; Geld allein errichtet es nicht. Öffentliche Grundversorgung kostet600, braucht zweiJahre und gesicherte Wartung/Personal. Ein errichteter Standort allein garantiert noch keine regelmäßige Nutzung: sichere Wege, zugängliche Anmeldung und passende Öffnungszeiten sind nötig. Etat600 für die jetzige Projektperiode; eine spätere Finanzierung ist nicht zugesichert. Eine schrittweise Kombination ist nur mit ausgewiesenen Kosten/Zeiträumen und noch notwendiger Finanzierung vertretbar, ohne den Etat doppelt auszugeben.
B1(10): Berechne absoluten Landwirtschaftsoutput und analysiere Struktur-/Wachstumspfad, Qualifikation, Aufnahmefähigkeit und Verteilung.
B2(15): Prüfe anhand beider Einkommensverteilungen die reale Vergleichsbasis, Quote und Tiefe, Prozentpunkte und relative Änderung. Vergleiche monetäre/nichtmonetäre Messgegenstände und beide Strategien hinsichtlich kurzer/langer Frist und tatsächlicher Nutzung. Begründe eine finanzierbare Wahl und prüfbare Wirkungskriterien. Erkläre Grenzen der gesunkenen Quote für andere Armutsdimensionen und einzelne Haushalte.

Gleichwertige begründete Lösungen und teilweise richtige nachvollziehbare Leistungen zählen. Die ursprünglichen40Punkte bleiben in den vierLeistungsbereichen erhalten;10zusätzlichePunkte betreffen tatsächlich ergänzte Überschneidungs-/Preis-/Zugangsbelege. Ein einzelner Quotienten-/Detailfehler oder unvollständiges Nebenargument begrenzt nicht pauschal. Nur eine im ganzen Werk vollständig fehlende oder durchgehend falsch ersetzte sektorale Strukturanalyse, fallbezogene Messobjekt-/Vergleichsanalyse oder begründete finanzierbare Sicherungs-/Zugangsstrategie bleibt unter der Bestehensgrenze, höchstens29/50; keine zusätzliche Strafpunktabgabe.'''
q['examData']['taskContentEn']='''**Structural change, poverty measurement and usable development paths –50marks; passat30.** Countries/data are fictional. Output/money are real in one common unit except expressly nominal B incomes. Groups/time references are specified; no actual country is judged. Performances may be connected in a coherent analysis; no particular headings or additional case count is required.

**A – U.** Agriculture has20%of value added/60%of employment;industry30/15%;services50/25%. Skills/transport are lacking; industry can initially absorb at most50additional people. R/S each have100residents, common real poverty line100 and40below it. R:20earn50,20earn90;S:40earn80; others exceed100. Depth=positive poverty gaps divided by100×totalpopulation. R:30%lack safe water,20%reliable school access;S:20%water,35%school deprivation. Person overlaps are unknown; income and access measure distinct things.
Budget1000for this support period. Targeted transfers can reduce income gaps. With full actual access no additional payout restriction exists, but currently only60of100people can use application channels; it is unknown which poor people are included. Application/access help costs200; it seeks better access without guaranteeing100%take-up or an income result. Alternatively50vocational places plus transport for sixmonths cost1000; these improve conditions without guaranteed jobs/income and require suitable later routes/funding. Industry’s capacity limit remains. Services beyond the funded period and longer-term demand are unproved.
A1(10):Analyse both share series and relative average value added/worker. Compare agriculture upgrades with transitions under actual constraints; no individual productivity inference from sector means.
A2(15):Compare incidence/depth/gaps and deprivation measures, including possible water/school overlap. Assess transfers versus productive/access support through immediate need, actual access,budget,time. Justify a funded priority/combination and observable outcomes.

**B – V.** Real total value added100→150;agriculture share30→24%. Skilled services grow, informality remains;20of80applicants meet entry qualifications. Separate cross-sections each examine200people without individual links. T0:80earn75 and120earn120 atT0prices;line100. T1:50earn nominal108,150nominal180;prices20%aboveT0. Astatistic retains the same real poverty line and reports40→25%. At each date30%lack safe water and20%reliable school access; overlap unknown.
Transfers costing600can reduce current income gaps with actual reach. Remote villages lack water/schools; cash alone does not build them. Public provision costs600,takes two years and needs maintenance/staff. Built premises alone do not guarantee regular use: safe routes,accessible registration and suitable hours matter. Budget600for the current period; later funding is not promised. A staged combination needs stated costs/time and remaining funding requirements, without double spending.
B1(10):Calculate absolute agricultural output and analyse structure/growth,skills,capacity,distribution.
B2(15):Use income distributions to check real comparison basis,incidence/depth,percentage-point/relative change. Compare monetary/nonmonetary objects and both strategies over time and actual use. Justify affordable choices and observable outcome criteria; explain limits of falling incidence for other dimensions/individuals.

Equivalent reasoned and coherent partial work count. Original40marks remain in four performance areas;10added marks concern actual expanded overlap/price/access evidence. Isolated quotient/detail errors or incomplete secondary reasoning trigger no blanket cap. Only entirely absent or consistently wrong sector analysis,case-specific measurement/comparability or justified affordable security/access strategy across the whole work limits below passing,at most29/50; no additional punishment deduction.'''
q['examData']['solutionContent']='''A1(10):20/60=1/3,30/15=2,50/25=2relativ zum Landesdurchschnitt. Beide Anteilsreihen unterscheiden(4P), Durchschnitt/keine individuelleAbleitung(2P), produktivereLandwirtschaft oder qualifizierter Übergang mit Transport/Nachfrage und höchstens50neuer Industrieaufnahme(4P).
A2(15):BeideQuoten40%;R-Lücke20×50+20×10=1200,Tiefe12%;S-Lücke40×20=800,Tiefe8%(alte5P). Etat1000schließtRnichtganz; Srechnerisch nur mit tatsächlicher Erreichbarkeit. Transfers wirken eher unmittelbar, Förderung bedingt später; Alternativen/Prioritäten anhand Bedürftigkeit,Zugang undFinanzierung(alte5P). Neue5P: NichtmonetäreMessobjekte und Wasser-/Schulmangelvereinigung R30–50%,S35–55%, nichtautomatisch50/55%odervergleichbar zuEinkommensquote(2P). Teilhabediagnose/finanzierte Wahl undprüfbare Wirkungsgrößen(3P):1000Transfer oder1000Lernen/Transport passen; Hilfe200+Transfer800passt und könnteSin theoretischem Vollzug schließen, beweist es bei unbekannter Identität/Takeup nicht. Hilfe200+volle1000Förderung/Transfersüberschreitet1000. Kurs50Plätze≠50Jobs; sechsMonateTransport≠dauerhafterZugang. Prüfen:wer tatsächlich erreicht/beantragt/erhält, reale Einkommenslücken, tatsächliche Kursnutzung/Abschlüsse/passendeJobs und nutzbare Dienste;Ausgaben/Plätze allein genügen nicht. BeiR kann dieselbe Restlücke unterschiedliche Quoten jeZuteilung ergeben; genaue neueQuote ohne Zuteilungs-/Erreichbarkeitsdaten nichtbehaupten.
B1(10):Landwirtschaft30→36,+6/+20%trotz sinkendemAnteil; Gesamt+50%(alte4P). Qualifikation20/80/Nachfrage/Aufnahmegrenzen(3P), informelleArbeit undVerteilungs-/Inklusionsgrenzen statt Wohlstand jedesHaushalts(3P).
B2(15):Monetär40→25%,−15Prozentpunkte; Wasser30%,Schule20% unverändert, andereObjekte und Überschneidung offen(alte4P). Transferkurzfristig,Erschaffung/zugänglicherBetrieb bedingt über2Jahre, Wartung/Personal/tatsächlicher Zugang(alte3P). Etat600nur einmal; finanzierte Priorität oder echte gestaffelteBedarfe, begründeteAlternative akzeptieren. Zielkriterien: tatsächlichgezahlt/realeLücken, sichereWasser-/regelmäßigeSchulnutzung, Erreichbarkeit und Verteilung statt nurBauten/Ausgaben(alte3P). Neue5P:108/1,2=90;180/1,2=150; gleiche realeGrenze100entspricht nominal120,T140/?? ist falsch:50/200=25%,T0=80/200=40%;T0Lücke80×25=2000,Tiefe10%;T1=50×10=500,Tiefe2,5%(3P). Quote−15Prozentpunkte, relativ−37,5%; unveränderte nominal100wäre falscheBasis(1P). GetrennteQuerschnitte belegen keine individuellenAufstiege, jedesEinkommen oder Rückgang jederDimension(1P). Keine automatische neueJob-/Teilhabe-/Finanzierungszusage.
Bewertung der ganzen Arbeit:Original40 plus10neuePunkte, gleiche tragfähigePrioritäten gleichwertig, Teilpunktefür gezeigteElemente. KeineZusatzfall-/Überschriftenquote. Nur vollständige Kernabwesenheit/durchgehend falscherErsatz wieAufgabenbeschreibung begrenzt29/50, keinEinzelirrtum.'''
# Eliminate an editorial scratch expression before any candidate write.
q['examData']['solutionContent']=q['examData']['solutionContent'].replace('T140/?? ist falsch:','')
q['examData']['solutionContentEn']='''A1(10):20/60=1/3,30/15=2,50/25=2relative to national average. Separate both series4;means/not individual output2;agriculture upgrades or trained transitions with transport/demand and max50additional industry capacity4.
A2(15):Both40%;Rgap20×50+20×10=1200,depth12%;S40×20=800,depth8%(original5).1000cannot closeRfully;Sonly arithmetically with actual access. Immediate transfers versus conditional later capacity;need,access,funding,reasoned priority(original5). Added5:nonmonetaryobjects and water/schoolunion R30–50%,S35–55%,not automatically exact50/55%or equivalent to income incidence2. Participation diagnosis,funded choice,observable outcomes3:1000transfer or1000training/transport fits;200help+800transfer fits and could closeSunder theoretical fullreach,not established with unknown take-up/identities.200help+full1000support exceeds budget.50places≠50jobs;six-month transport≠permanent access. Examine actual beneficiaries/applications/payments,real gaps,course use/completions/suitable jobs and usable services; spending/places alone are insufficient. R’s same residual gap could yield different incidence by allocation; no exact post-transfer rate without allocation/reach facts.
B1(10):Agriculture30→36,+6/+20%despite falling share;total+50%(original4).20/80skills/demand/capacity3;informality/distribution/inclusion rather than everyhousehold’s prosperity3.
B2(15):Monetary40→25%,−15percentagepoints;water30%,school20%unchanged,distinct objects/unknown overlap(original4). Immediate transfers versus conditional provision/use aftertwo years,maintenance/staff/actualaccess(original3). Spend600onlyonce;funded priority or genuine staged funding needs;equivalent alternatives count. Outcomes:actualpayments/realgaps,safe-water/regular-schooluse,reach/distribution rather than buildings/spending(original3). Added5:108/1.2=90;180/1.2=150;real100means nominal120;T1=50/200=25%,T0=80/200=40%;T0gap80×25=2000,depth10%;T1gap50×10=500,depth2.5%(3).Rate−15points/−37.5%relative;nominal100is inconsistentbasis1. Unlinkedcross-sections cannot prove individual mobility/everyincome/everydimension1. No guaranteed newjobs/participation/futurefunding.
Assess whole work:original40+new10;equivalent defensible priorities equal,partialshownperformance credited. No added case/heading quota. Only total core absence/consistently wrong replacement as stated limits to29/50;isolatederrors do not.'''
q['examData']['scoring']={'maxPoints':50,'passingPoints':30,'steps':[{'id':'s1','points':10,'description':'A beideAnteilsreihen4/Durchschnitt2/bedingtePfade4 unverändert.','descriptionEn':'Abothshare series4/average2/conditionalpaths4retained.'},{'id':'s2','points':15,'description':'A alteQuote/Tiefe5 und finanzierteStrategie5; neueMessobjekte/Überschneidung2 plusTakeup/Zugang/Ergebniskriterien3.','descriptionEn':'Aoriginalincidence/depth5 andfundedstrategy5;addedobjects/overlap2,takeup/access/outcomes3.'},{'id':'s3','points':10,'description':'B Anteil/Absolutoutput4/Qualifikation3/Verteilung3 unverändert.','descriptionEn':'Bshares/absoluteoutput4/skills3/distribution3retained.'},{'id':'s4','points':15,'description':'B alteDimensionen4,Zugang/Zeit3,Strategie3; neuePreis-/Lückenrechnung3,Vergleich/relativeÄnderung1,Querschnittgrenze1.','descriptionEn':'Boriginaldimensions4,access/time3,strategy3;addedprice/gapcalculation3,comparison/relativechange1,cross-sectionlimit1.'}]}
put(C/'f08.whole-practice.candidate.INERT.json',f);put(C/'036ea.whole-practice.candidate.INERT.json',q);put(C/'two-whole-practices.INERT.json',[f,q]); base=json.loads((H/'canonical.actual-base.exact.json').read_text());dd=json.loads((H/'sealed-dd38-retained-goal.exact.json').read_text());pv=json.loads((H/'sealed-543b-da734-goals.exact.json').read_text());auth=pv['revisedWholeGoals'];route={g['id']:g for g in [dd,*auth,f,q]};base['goals']=[copy.deepcopy(route.get(g['id'],g)) for g in base['goals']];put(C/'landscape.author-only.INERT.json',base)
put(O/'whole-coverage-and-requires-plan.INERT.json',{'status':'ai_candidate_needs_human_review','activationState':'INERT','evidenceLevel':'E1','maximumClaimScope':'G1','wholeHistoricalBreadthAndOldCountryContractsRetained':True,'noNewCanonicalUUIDs':True,'practices':[{'goalId':F,'requiresAndCoveredGoalIds':[DD,V,P],'old24MarkPerformancesPreserved':'All original numbers and six original performanceareas survive; legal6 and remuneration10 are concrete additions within sameA/Bmaterial. Original positiveunderstandingfull776/a500 contracts were read.','realAdditions':['specific§87roster reservation/conciliation and§80duties/necessaryinfo limits','job requirements vs individualacceptedoutput vs teamquality/profit;time/piece/Q/F/Gactualnumbers and two perspectives'],'proposedCountryRole':'OnlyHELKconditional, whole-sourcechoices/independentqualificationopen','wholeContentCannotAutomaticallyQualifyAOrMaterialPracticeM7':True},{'goalId':Q,'requiresAndCoveredGoalIds':[S,PO,POL],'old40MarkPerformancesPreserved':'Both originalsector/data/statistics/budgets and fourperformanceareas survive. Actualoverlap/takeup/capacity/price/evaluationfacts added in sameA/Bmaterial.','realAdditions':['unknown deprivation-overlapbounds','nominal-to-real comparability,depth,%pointvsrelative and unlinkedcrosssections','applicationreach/budget/practicalserviceuse/training-to-jobconstraints/outcomeevaluation'],'proposedCountryRole':'OnlyHEGK/LKconditionalQ4.1with explicitly authoredwholeda734placement;wholequalificationopen','wholeContentCannotAutomaticallyQualifyAOrMaterialPracticeM7':True}],'routingAndComposition':'Currentcontainsparents unchanged in localcandidate; actualsource-qualifiedcountry/courseplacement and routenavigation mustbeindependentlyreviewed beforeactivation. applicabilityFromRequires remains only proposedassessmentvisibility,never sourceproof. Currentda734Q2LKdoesnotimplicitlymakeGKorQ4visible.','openFollowers':['Clinic81f5 remainshours-targeting underdd; nowholevoice/paycoveredclaimfromgenericparticipation wording','f1wholecurrentgoal/P unchanged;anyactualcourse/source correctionmustpreservefullscope','oldothercountryPracticecontractsremainhistory; no silentmastery/scopecarryover'],'openOtherEffects':['Noactivecanonical/config/registry/ledger/card/bookwrites','Source/restoration84rows plus11newboundedsourcecomponents are ownINERTproposals, not reviewedmappingdecisions','Noimagesgenerated. dd/543candidateimagebindingsremainclearedpendingV; reusedwhole776/a500/da734/f1actualimagesretainedonlyatowntrueinputdigests','Nohumanapprovalorlearnertrial','IndependentstablewholeDtwofreshrounds and source/scope/A/M/cards/material/P/V gatesremainopen']})
print('Wrote two wholeDEEN Practice candidates, full solutions/rubrics, own679 author landscape and effects.')
