import json, hashlib
from pathlib import Path
from datetime import datetime, timezone
P=Path(__file__).parent; B=P.parent/'bundle'
def dig(p):return 'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest()
def new(p,x):
    assert not p.exists(),str(p)
    p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
x=json.loads((P/'description-review-input.json').read_text())
c=json.loads((P/'description-review-campaign.json').read_text())
m=json.loads((P/'review-bundle-manifest.json').read_text())
book=json.loads((B/'book-model.json').read_text())
g=x['goals'][0]; batch=c['batches'][0]; bf=P/'batches'/(batch['batchId']+'.input.jsonl')
assert x['goalCount']==1 and g['goalId']=='eee7217a-c2fb-58b6-ba84-2a8d5235edb5'
assert x['bundleFingerprint']==m['bundleFingerprint']==c['bundleFingerprint']=='sha256:49fdebff3db21fa3c337b3cc3b8ff5ea0522a4fb3f489ae8ce361ae24b546321'
assert x['bookDigest']==m['bookModelDigest']==c['bookDigest']=='sha256:0058a2f2c6803a6da29fd69f75e3c28ffefc8cc34553f16a92fe79a5669f9bf9'
assert dig(bf)==batch['batchInputFingerprint']
assert json.loads(bf.read_text())['goal']==g
assert g['reviewContext']['page']==book['pages'][0]
assert g['reviewContext']['evidenceProfile'] is None
assert g['reviewContext']['page']['visualization']['originalDigest']=='sha256:a5ed0ba27eb8270cb98a950d6d61b2d2f041b2ca768e5e7bcd58c505cf4b3413'
for a in m['artifacts']: assert dig(B/a['path'])==a['digest']
run='wirtschaft-q2-labour-eee-one-independent-description-round-b-codex-20261008-v2'
record={'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json','schemaVersion':1,'recordId':run+'.001','runId':run,'campaignId':c['campaignId'],'roundId':c['roundId'],'bundleFingerprint':x['bundleFingerprint'],'bookDigest':x['bookDigest'],**{k:g[k] for k in ['goalId','goalFingerprint','pageFingerprint','currentTitleDe','currentTitleEn','currentDescriptionDe','currentDescriptionEn']},'decision':'keep','understandingEvidence':{
'essentialUnderstandingDe':'Die Analyse einer Arbeitsmarktmaßnahme verbindet das konkrete Beschäftigungsproblem und die betroffene Zielgruppe mit dem Wirkungsmechanismus des Instruments, seinen Voraussetzungen und den begrenzten Schlussfolgerungen aus beobachteten Ergebnissen. Eine höhere Vermittlungszahl allein beweist noch keinen zusätzlichen Beschäftigungseffekt.',
'essentialUnderstandingEn':'Analysing a labour-market measure connects the specific employment problem and affected target group to the instrument mechanism, its conditions and the limited conclusions supported by observed outcomes. A higher placement count alone does not prove an additional employment effect.',
'observablePerformanceDe':'An einer bereitgestellten Fallstudie ordnet die lernende Person Problem, Maßnahme und Zielgruppe zu, erklärt etwa den Zusammenhang zwischen Qualifikationslücke und Weiterbildung und untersucht Umsetzung, Kosten und Beschäftigungsdaten. Sie unterscheidet beobachtete Ergebnisse von einer begründeten Wirkungsaussage und benennt fehlende Vergleichsinformationen.',
'observablePerformanceEn':'Using a supplied case study, the learner identifies the problem, measure and target group, explains for example the connection between a skills gap and training, and examines implementation, cost and employment data. They distinguish observed results from a supported effect claim and identify missing comparison information.',
'transferExpectationDe':'In einer neuen unabhängigen Fallaufgabe werden statt einer Qualifikationslücke saisonale Nachfrageschwankungen, eingeschränkte Mobilität und eine andere Zielgruppe vorgelegt. Die lernende Person analysiert, welche Verbindung zwischen Problem und Instrument nun trägt, welche Bedingungen sich ändern und welche Daten für eine tragfähige Wirkungsaussage fehlen; dieselbe Erfolgsbehauptung wird nicht unverändert übertragen.',
'transferExpectationEn':'A fresh independent case replaces a skills gap with seasonal demand fluctuations, restricted mobility and a different target group. The learner analyses which connection between problem and instrument now holds, which conditions change and which data are missing for a supported effect claim; the same success claim is not carried over unchanged.'},
'rationale':'Die vollständige aktuelle DE/EN-Kompetenz bleibt gleichwertig und auf fallbezogene Analyse begrenzt (AB2). Demografie und Arbeitsmarkt ist die externe Vorbedingung; der folgende Strategievergleich wird nicht in dieses Ziel hineinerweitert. Die ganze neu eingefrorene native PDF-Zielseite wurde tatsächlich angesehen: Problem/Maßnahme/Prüfen, Weiterbildung, Vermittlung und Beschäftigungsprojekt bilden passende Ansatzpunkte; Zielgruppen-, Kosten- und Evidenzfragen garantieren keinen Beschäftigungserfolg. Das Vordergrundheft ist nun textfrei, während der Laptop zur handelnden Person und die Tafel plausibel ausgerichtet bleiben. Der korrigierte Bilddigest und zutreffende Alttext sind tatsächlich gebunden. Das Buch enthält kein P-Profil; create ist daher eine ehrliche separate Empfehlung. Die Bildkorrektur verändert weder den fachlichen Kompetenzumfang noch die sprachliche Parität; dies ist keine erneute A/M- oder P-Abnahme.',
'evidenceProfileContract':'positive-understanding-evidence-v2','evidenceProfileRecommendation':'create','recordStatus':'candidate','reviewAuthority':'ai_candidate'}
out=P/'results';out.mkdir(exist_ok=True);rf=out/(batch['batchId']+'.records.jsonl');assert not rf.exists();rf.write_text(json.dumps(record,ensure_ascii=False,separators=(',',':'))+'\n')
completed=datetime.now(timezone.utc).isoformat(timespec='seconds').replace('+00:00','Z')
par=P/'observed-generation-parameters.actual.json'
new(par,{'provider':'OpenAI','model':'Codex session; exact model identifier not disclosed','agentIdentity':'/root/economics_layer_a','temperature':'not exposed','seed':'not exposed','method':'Actual full one DE/EN goal, own prompt/criteria/contracts/input/campaign, whole new page context and native PDF physical page3 read/viewed. Current whole canonical goal, external prerequisite, successor and three containing nodes actually read from the physical isolate. Goal-specific six bilingual evidence recommendations and rationale manually authored after inspection. No hash-derived substantive verdict.','blindToCurrentRoundA':True,'currentRoundAOutputsRead':False,'rootPositiveVerdictRead':False,'priorRoleDisclosure':'Reviewer authored own original Labour12 D-B and independently reviewed original Labour12 images plus8fbd and eee correction images. The eee original KEEP missed the personal-note perspective defect; immutable correction-V receipt acknowledges and closes it after actual original/corrected native360680 views. Current targeted D-B is a bounded new-page review, not a first-ever exposure to this goal or independence from own prior D/V work. Reviewer did not author this image, translation, P profile or another D round. Root communicated the specific observed image defect; no round-A D outputs were read.','originalOtherElevenReviewTreatment':'Own historical D12 and all original frozen files retained. Technical author root whole-eleven parity receipt is explicitly external technical evidence, not an independent rereading claim. Other eleven substantive goals are not restarted or counted as eleven new reviews.','humanReviewClaimed':False,'learnerPerformanceClaimed':False})
roles=['book_model','book_pdf','book_pdf_render_manifest','review_input_json','review_prompt','review_criteria','finding_schema','run_manifest_schema']
art=[{'role':a['role'],'digest':a['digest']} for a in m['artifacts'] if a['role'] in roles]+[{'role':'description_review_batch_input_jsonl','digest':batch['batchInputFingerprint']}]
runfile=out/(batch['batchId']+'.run.json')
new(runfile,{'$schema':'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json','schemaVersion':1,'runId':run,'campaignId':c['campaignId'],'roundId':c['roundId'],'batchId':batch['batchId'],'batchInputFingerprint':batch['batchInputFingerprint'],'bundleFingerprint':x['bundleFingerprint'],'bookDigest':x['bookDigest'],'provider':'OpenAI','model':'Codex session; exact model identifier not disclosed','role':'sequencing_representation_reviewer','promptFamilyId':'goal-description-understanding-evidence-review-v2','promptFingerprint':c['promptFingerprint'],'criteriaFingerprint':c['criteriaFingerprint'],'generationParametersFingerprint':dig(par),'independenceGroupId':c['independenceGroupId'],'blindToOtherRuns':True,'goalIds':batch['goalIds'],'inputArtifacts':art,'startedAt':'2026-10-08T10:01:15Z','completedAt':completed,'status':'completed','outputDigest':dig(rf),'toolchainVersion':'skillpilot-native-d-v2-input-v3-record-v1-codex-actual-tools'})
new(P/'independent-bounded-one-page-inspection.actual.json',{'schemaVersion':1,'runId':run,'reviewAuthority':'ai_candidate','provider':'OpenAI','model':'Codex session; exact model identifier not disclosed','agentIdentity':'/root/economics_layer_a','startedAt':'2026-10-08T10:01:15Z','completedAt':completed,'bundleFingerprint':x['bundleFingerprint'],'bookDigest':x['bookDigest'],'goalId':g['goalId'],'goalFingerprint':g['goalFingerprint'],'pageFingerprint':g['pageFingerprint'],'recordsDigest':dig(rf),'runDigest':dig(runfile),'actualWholeDeEnAndNativePageContextRead':True,'actualNativePdfPhysicalPageViewed':3,'inspectionPath':'inspection/frozen-native-pdf-page-3.png','inspectionDigest':dig(P/'inspection/frozen-native-pdf-page-3.png'),'actualCorrectedAssetDigest':g['reviewContext']['page']['visualization']['originalDigest'],'actualPageFinding':'Text-free foreground notebook closes the actor-reading defect. The same useful problem/instrument/checking board and user-facing laptop remain; actual new PDF page contains correct current description, image and bounded external prerequisite/successor context. No new description flaw found.','decision':'keep','evidenceProfileActuallyPresent':False,'evidenceProfileRecommendation':'create','unresolvedDescriptionFindings':[],'independenceAndPriorRoles':json.loads(par.read_text()),'externalTechnicalWholeElevenParityReceipt':'../../actual-one-corrected-and-eleven-unchanged-native-pages.receipt.json','externalParityIsNotOwnNewElevenSubstantiveReview':True,'sourceReadingBoundary':'Whole source requirements were actually reviewed in original own D12. No new original curriculum reading or current legal review asserted for this image-only one-page successor. Canonical raw applicability is not full mapping or effective projection proof.','separatePAMVHandling':'This D recommendation creates no P profile, new A/M verdict or human approval. Current V correction receipt is own separate actually viewed work; root must join both D rounds and separate current P/A/M/V and context/source evidence before strict counting.','liveWrites':0,'strictClosuresAdded':0,'restoredBindingsClaimedBeforeRootIntegration':0})
print(json.dumps({'records':1,'keep':1,'recordDigest':dig(rf),'runDigest':dig(runfile),'inspectionDigest':dig(P/'independent-bounded-one-page-inspection.actual.json'),'completedAt':completed}))
