#!/usr/bin/env python3
"""Prepare inert image-author input bindings. No production files are written."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[6]
OUT = Path(__file__).resolve().parent
SOURCE = ROOT / 'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-07/biologie-neuro-twenty-one-current-continuation-author-v3/stage-02-current-twenty-one-native'
RAW = SOURCE / 'final-current21-whole-native-source-context-material-review-inputs.author.raw.json'
CASES = SOURCE / 'forty-two-complete-DEEN-reference-materials.current21.author-candidates.json'
WITNESSES = SOURCE / 'all21-selected-actual-frozen-source-witness-effective-file-bindings.author.json'

def bind(path):
    data = path.read_bytes()
    return {'path': str(path.relative_to(ROOT)), 'sha256': hashlib.sha256(data).hexdigest(), 'bytes': len(data)}

def put(name, obj):
    path = OUT / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + '\n')

DESIGNS = {
    'ce19': ('structure', 'Ein großes modellhaftes Neuron: Dendriten und Zellkörper links, ein langes Axon in der Mitte, verzweigte Endknöpfchen rechts. Eine klare orange Signalroute verläuft im Neuron von den Dendriten durch den Zellkörper entlang des Axons zu den Endknöpfchen. Rechts darf ein kleiner Ausschnitt der nächsten Zelle sichtbar sein, aber mit klar erkennbarem synaptischem Abstand, ohne direkte Zellverschmelzung. Vier große, gut platzierte Bezeichnungen mit kurzen Führungslinien: „Dendriten“, „Zellkörper“, „Axon“, „Endknöpfchen“. Keine weitere Beschriftung. Der Zellkörper ist groß genug, um als Zellkörper erkannt zu werden; die Ausläufer sind echte zusammenhängende Zellfortsätze. Keine Gesichter oder anthropomorphen Zellfiguren.', 'Nicht die Bauform aller Neurontypen, nicht die Entstehung eines Aktionspotenzials oder ein vollständiger Synapsenmechanismus.'),
    'ff1': ('chemical-synapse', 'Nahansicht einer erregenden chemischen Acetylcholin-Synapse: oben ein präsynaptisches Endknöpfchen mit einem spannungsabhängigen Ca²⁺-Kanal. Ca²⁺ tritt aus dem Extrazellulärraum in das Endknöpfchen ein. Ein Vesikel fusioniert mit der präsynaptischen Membran und setzt orange Acetylcholin-Teilchen in den deutlich sichtbaren Spalt frei. Unten bindet Acetylcholin an einen ligandengesteuerten Kationenkanal der postsynaptischen Membran; dieser Kanal ist geöffnet und zeigt den depolarisierenden Einstrom von Na⁺. Alle Membranen und der Spalt sind räumlich sauber getrennt. Große kurze Bezeichnungen „Ca²⁺“, „ACh“, „Na⁺“, „Synaptischer Spalt“; am oberen Kanal „spannungsabhängig“, am unteren „ligandenabhängig“. Keine Aktionspotenzialgarantie oder ACh-Wiederaufnahme.', 'Ein ACh-Beispiel; keine Übertragung aller Transmitter, keine vollständige Prüfung der Kanalrollen oder der Schwellenbedingung.'),
    'a46c': ('network-plasticity', 'Zwei einfache kleine neuronale Netzmodelle nebeneinander, jeweils drei gleiche Knoten mit denselben eingehenden orange Signalmarken. Links sind zwei Verbindungslinien dünn, rechts ist genau eine davon deutlich verstärkt. Ein nachgeschalteter Ausgang zeigt dadurch im gegebenen Modell eine andere Antwort. Große Beschriftungen „Vorher“, „Nachher“, „gleiche Eingabe“. Verbindungslinien bleiben in beiden Netzmodellen an denselben Stellen verbunden. Keine neuen Neuronen erfinden und keine Gleichsetzung mit nachgewiesener Erinnerung.', 'Gegebene Netzänderung als Modell; weder Hebb-Regel noch LTP/LTD-Protokoll oder Nachweis menschlichen Lernens.'),
    '7874': ('sensory-transduction', 'Zwei große deutlich getrennte Modellstreifen. Links eine primäre Sinneszelle, deren eigener Fortsatz Aktionspotenziale weiterleitet. Rechts eine sekundäre Sinneszelle, die einen Transmitter an eine separate afferente Nervenzelle abgibt; deren Axon leitet Aktionspotenziale weiter. In beiden Sinneszellen entsteht zunächst ein lokal abgestuftes Rezeptorpotenzial. Beschriftungen „primäre Sinneszelle“, „sekundäre Sinneszelle“, „Rezeptorpotenzial“, „Aktionspotenziale“; keine klein gedruckten Zusatztexte. Keine direkten Aktionspotenziale im Axon der sekundären Sinneszelle, die hier keinen afferenten Axonfortsatz besitzt.', 'Modellvergleich zweier Signalwege, keine vollständige Anatomie oder universelle Zuordnung aller Sinnesorgane.'),
    '1975': ('endocrine-feedback', 'Ein freundliches vereinfachtes Regelkreismodell mit drei großen Stationen: Nervenzelle links, endokrine Drüse in der Mitte, Zielzelle rechts. Ein neuronales Signal steuert die Drüse, Hormonpunkte reisen im klar erkennbaren Blutgefäß zur Zielzelle. Eine eindeutig gerichtete rückführende Hemmung zeigt negative Rückkopplung. Kurze große Bezeichnungen „Nervensignal“, „Hormon“, „Blut“, „Rückkopplung“. Modellhaft, ohne eine bestimmte Krankheit oder eine universelle Zeitangabe.', 'Ein vorgegebenes Beispiel gemeinsamer neuraler und hormoneller Steuerung, kein allgemeiner Organatlas.'),
    'e111': ('synaptic-integration', 'Zwei große Modellfelder mit klarer Trennung. Links räumliche Summation: zwei grüne erregende und eine violette hemmende Synapse enden auf derselben Nervenzelle, ihre Pfeile führen zum Axonhügel; plus und minus markieren ausschließlich die Wirkung auf das Membranpotenzial. Rechts zeitliche Summation: zwei große einfache Kurven ohne Zahlen zeigen zwei dicht aufeinanderfolgende depolarisierende postsynaptische Potenziale, die sich überlappen, gegenüber zwei weit auseinanderliegenden Potenzialen, die einzeln abklingen. Eine gestrichelte Schwellenlinie und ein roter Punkt markieren im oberen Fall das Überschreiten; die unteren getrennten Antworten bleiben darunter. Gleiche Achsenskala in den beiden rechten Mini-Kurven. Große Bezeichnungen „räumlich“, „zeitlich“, „Schwelle“. Keine neuen Aktionspotenziale aus einem einzelnen unterschwelligen Eingang und kein hemmender Aktionspotenzialpuls.', 'Qualitative Modellkurven für Summation; keine Messdaten, keine universelle lineare Addition realer Leitfähigkeiten.'),
    '3471': ('cellular-learning', 'Ein großer Ausschnitt von zwei benachbarten Nervenzellen vor und nach einer modellhaften plastischen Änderung: dieselbe Kontaktstelle ist rechts stärker ausgeprägt und zeigt bei gleicher Eingabe eine größere postsynaptische Modellantwort. Große kurze Bezeichnungen „Vorher“, „Nachher“, „gleiche Eingabe“. Keine Gleichsetzung einer Verbindung mit einer vollständigen Erinnerung; keine molekulare Spezialkaskade.', 'Allgemeines zelluläres Plastizitätsbeispiel; kein einzelner verpflichtender Mechanismus oder menschlicher Gedächtnisnachweis.'),
    '485e': ('system-limits', 'Zwei große einfache Modellnetze mit denselben Nervenzellen. Links sind mehrere Signalverbindungen intakt. Rechts sind einige Verbindungen deutlich unterbrochen, sodass ein vorgegebenes Signal einen Ausgang schlechter erreicht. Warme, respektvolle Comicdarstellung ohne dramatische Körperbilder oder Personen. Große Beschriftungen „intaktes Modell“, „gestörtes Modell“. Keine Aussage, dass dieses einfache Netz sämtliche Ursachen einer Erkrankung erklärt.', 'Vorgegebenes Störungsmodell, keine Diagnose, Prognose oder vollständige Alzheimer-Erklärung.'),
    'afde': ('imaging-method', 'Freundliche vereinfachte fMRI-Szene: eine liegende Person wird respektvoll im MRT-Gerät gezeigt, daneben ein großes schematisches Hirnbild mit wenigen farbigen Bereichen. Ein deutliches kleines Blutgefäß-Symbol verbindet diese Bereiche mit Änderungen der Blutoxygenierung. Große Beschriftungen „fMRT“, „Blutoxygenierung“. Keine Gedankenblasen oder direkte Gedankenlese-Anzeige; keine Zell-Aktionspotenziale als unmittelbar gemessene Größe.', 'Ein indirektes bildgebendes Prinzip, keine Diagnose oder vollständige Methodenvergleichsleistung.'),
    '2381': ('measurement', 'Ein großes Neuron-Axonmembranmodell mit einer Messelektrode im Zellinneren und einer Bezugselektrode unmittelbar außerhalb in der Lösung. Beide sind sichtbar an dasselbe Differenzmessgerät angeschlossen. Rechts ein großes Diagramm mit ruhiger negativer Baseline und einem einzelnen Aktionspotenzial, mit Achsen „Membranpotenzial“ und „Zeit“, ohne Zahlen oder fein gedruckte Einheiten. Große Beschriftungen „innen“, „außen“. Elektroden nicht beide im Inneren und kein anderes elektrisches Bauteil als Zelle.', 'Schematische Messanordnung, keine tatsächlich durchgeführte Messung oder komplette Versuchsplanung.'),
    'c9a0': ('cellular-learning', 'Zwei große Vergleichsfelder für dieselbe Testeingabe: links LTP mit einer größeren postsynaptischen Antwort nach der Änderung, rechts LTD mit einer kleineren Antwort. Jeweils zwei klar erkennbare einfache Antwortkurven übereinander mit exakt gleicher Testeingabe und gleicher Kurvenskala. Beschriftungen „LTP“, „LTD“, „gleiche Testeingabe“, „vorher“, „nachher“. Keine Frequenzzahlen, keine Universalformel und keine Aussage, dass jeder synaptische Prozess so entsteht.', 'Gegebene Befunde zur langfristigen Wirksamkeitsänderung, kein universelles Induktionsprotokoll oder Lernnachweis.'),
    '4f63': ('network-plasticity', 'Ein einfaches vorgegebenes Hebb-Modell: zwei Nervenzellknoten sind gleichzeitig aktiv und die Verbindung zwischen ihnen wird danach deutlich dicker. Daneben eine Vergleichsverbindung ohne gleichzeitige Aktivität, die unverändert bleibt. Große kurze Beschriftungen „gemeinsam aktiv“, „Verbindung verstärkt“, „Hebb-Modell“. Keine Verminderung der inaktiven Verbindung ohne gegebene Regel und keine Darstellung als universelles biologisches Gesetz.', 'Bedingte gegebene Modellregel; keine amtliche Einzelpflicht, kein LTP/LTD-Protokoll oder universelles Lernprinzip.'),
    '97b2': ('synaptic-integration', 'Ein vorgegebenes sehr übersichtliches Netz aus drei Nervenzellen: ein erregender Eingang wirkt direkt auf die Ausgangszelle und zusätzlich auf eine hemmende Zwischenzelle, deren violetter Kontakt die Ausgangszelle hemmt. Große Plus- und Minuszeichen ausschließlich an den synaptischen Wirkungen. Große Bezeichnungen „erregend“, „hemmend“. Durchgehende eindeutige Pfeile und keine Verbindung, die ohne Synapse unmittelbar zwischen Zellkörpern verschmilzt.', 'Vorgegebene Verschaltung, keine Gewichtänderung, Hebb-Regel oder vollständige Kurvenanalyse.'),
    '9b96': ('chemical-synapse', 'Zwei große synaptische Ausschnitte mit Serotonin-Punkten. Links führt ein Wiederaufnahmetransporter einige Serotonin-Punkte aus dem Spalt zurück in die präsynaptische Zelle. Rechts ist derselbe Transporter durch einen klar erkennbaren Blocker gehemmt und mehr Serotonin bleibt vorübergehend im Spalt. Große Beschriftungen „Serotonin“, „Wiederaufnahme“, „SSRI“. Keine Acetylcholinesterase, kein ACh und kein Versprechen zur Behandlung einer Depression.', 'Ein vorgegebenes Transporter-Beispiel, keine monokausale Depressionserklärung oder Therapieempfehlung.'),
    'f628': ('chemical-synapse', 'Zwei große klar getrennte Ausschnitte derselben neuromuskulären Acetylcholin-Synapse. Oben jeweils ein intaktes Endknöpfchen, darunter synaptischer Spalt, unten deutlich gestreifte Muskelzellmembran. Links bindet ACh an einen geöffneten nikotinischen Kationenkanal und Na⁺ tritt in die Muskelzelle ein. Rechts verhindert ein neutral mit „X“ bezeichneter gegebener Blocker die Aktivierung desselben Kanals; ACh ist weiterhin sichtbar im Spalt, aber der Kanal bleibt geschlossen und zeigt keinen Ionenstrom. Große Beschriftungen „ohne X“, „mit X“, „ACh“, „Muskelzelle“. Keine konkrete Gift- oder Medikamentenmarke, Dosierung oder pauschale Kraftaussage.', 'Vorgegebener Rezeptorblocker als begrenztes Muskelendplattenbeispiel; nicht jeder Stoffmechanismus und keine medizinische Empfehlung.'),
    '8b23': ('sensory-transduction', 'Ein großer mechanosensorischer Modellweg: Druck verformt eine Rezeptormembran und öffnet einen mechanosensitiven Kationenkanal. Danach ein abgestuftes Rezeptorpotenzial und anschließend zwei gleich hohe Aktionspotenzialzüge mit verschiedener Frequenz bei unterschiedlicher Reizstärke. Große Bezeichnungen „Druck“, „Rezeptorpotenzial“, „Aktionspotenziale“. Gleich hohe Aktionspotenziale, stärkere Reize nur durch dichteres Auftreten abgebildet. Keine Verallgemeinerung auf alle Sinnesrezeptoren.', 'Gegebenes mechanosensorisches Beispiel, kein universeller Transduktionsmechanismus.'),
    '1b38': ('membrane-transport', 'Ein großer übersichtlicher Ausschnitt einer Flüssig-Mosaik-Biomembran: zwei Reihen runder hydrophiler Lipidköpfe nach außen zu den wässrigen Räumen, die hydrophoben Schwänze liegen zwischen den Kopf-Reihen nach innen. Zwei gut getrennte große Proteine: ein offener Kanal lässt blaue Teilchen von der Seite mit vielen gleichen Teilchen zur Seite mit wenigen passieren; eine ATP-abhängige Pumpe bewegt orange Teilchen von wenigen zu vielen, entgegen deren eigenem Konzentrationsgefälle. Exakt eindeutig gerichtete Pfeile. Große kurze Bezeichnungen „Kanal“, „Pumpe“, „ATP“, „außen“, „innen“. Keine geladenen Teilchen direkt durch die Lipidschicht; keine starre gemauerte Membran.', 'Zwei modellhafte Transportwege; nicht alle Transportarten oder komplette Kompartimentanalyse.'),
    'e3fb': ('membrane-transport', 'Ein großer Membranausschnitt einer ruhenden Nervenzelle: innen viele K⁺ und wenige Na⁺, außen viele Na⁺ und wenige K⁺. Ein K⁺-Leckkanal zeigt K⁺-Ausstrom nach außen; eine getrennte Na⁺/K⁺-Pumpe zeigt eindeutig drei Na⁺ nach außen und zwei K⁺ nach innen mit ATP. Sehr wenige Plus- und Minuszeichen nur direkt an den beiden Membranflächen zeigen außen relativ positiv und innen relativ negativ; keine ganze negativ geladene Zellfüllung. Große Bezeichnungen „innen“, „außen“, „K⁺“, „Na⁺“, „ATP“. Pumpenpfeile nicht vertauschen, keine Aussage, dass die Pumpe jede schnelle Potenzialänderung erzeugt.', 'Qualitatives Ruhestandsmodell, keine Ableitung eines exakten mV-Wertes allein aus Ionenzahlen oder Energiekostenmessung.'),
    '04d7': ('membrane-transport', 'Oben zwei große aufeinanderfolgende Membranmodellbilder: links ein geöffneter spannungsabhängiger Na⁺-Kanal mit Na⁺-Einstrom ins Axon, rechts ein später geöffneter K⁺-Kanal mit K⁺-Ausstrom. Große Beschriftungen „Na⁺ hinein“, „K⁺ hinaus“. Unten zwei klar getrennte gleich skalierte Aktionspotenzialzüge: „schwacher Reiz“ hat drei Pulse, „stärkerer Reiz“ hat sechs Pulse in derselben dargestellten Zeitspanne. Alle einzelnen Pulse haben exakt gleiche Höhe und Form, stärkere Reize nur höhere Frequenz. Große Bezeichnung „gleiche Höhe“. Keine Pumpe als schneller Repolarisationsmechanismus, keine noch höheren Pulse bei stärkerem Reiz.', 'Qualitatives Beispiel für Ionenbewegung und Frequenzcodierung; keine vollständige Kanalzustands- oder Refraktärzeitanalyse.'),
    '080b': ('conduction', 'Zwei gleich lange vereinfachte Axonmodelle: ein unmyelinisiertes Axon mit fortlaufender lokaler Regeneration und ein myelinisiertes Axon mit deutlich sichtbaren Ranvier-Schnürringen, an denen Aktionspotenziale regeneriert werden. Lokale Ströme verlaufen auch unter der Myelinscheide kontinuierlich, Aktionspotenziale springen nicht als fliegende Teilchen. Große Bezeichnungen „unmyelinisiert“, „myelinisiert“. Keine universelle Zuordnung aller Wirbellosen zur ersten oder aller Wirbeltiere zur zweiten Form.', 'Gegebenes Faservergleichsmodell; Plan vor Generierung erneut an mögliche aktuelle Materialkorrektur binden.'),
    'c05e': ('endocrine-feedback', 'Ein großer vereinfachter Stress-Regelkreis mit drei farbigen Stationen für Hypothalamus, Hypophyse und Nebennierenrinde. Eine klare Vorwärtsroute führt zu Cortisol im Blut und eine eindeutig hemmende Rückkopplung zurück. Rechts ein kleiner Vergleichshinweis mit lang anhaltendem Stressinput, ohne automatische Krankheitsfolge. Große Bezeichnungen „Stress“, „Cortisol“, „Rückkopplung“. Keine Aussage, dass bei jedem Menschen chronischer Stress immer denselben Cortisolspiegel erzeugt.', 'Gegebener hormoneller Regelkreis und begrenzte Stressmodellfolge, keine Diagnose oder monokausale Krankheitsvorhersage.'),
}

COMMON = '''Use case: scientific-educational illustration for German upper-secondary biology.
Create one original landscape PNG, approximately 16:9. A warm, friendly hand-drawn comic learning illustration with clear slightly organic outlines, large welcoming colored forms, a soft ivory background and spacious composition. Friendly does not mean childish or anthropomorphic. Make the scientific mechanism clear using well separated structures and directional arrows. This is a bounded model example, not a task sheet or a full textbook page.
Critical display requirement: all essential labels and symbols must remain easily readable when the actual image width is 360 pixels, and at 680 pixels with maximum display height 448 pixels using object-contain. Use very large short German labels, preferably around 64 pixels high on a 1536-pixel-wide artwork. Never use tiny explanatory sentences, fine-print legends, decorative microtext or dense sterile tables. No header, footer, watermark, logo, goal identifier or branding. The requested German text must be correctly spelled. Favor visual relationships over text. Do not add extra scientific claims or captions.
'''

first = ['ce19', '1b38', 'e3fb', '04d7', 'ff1', 'e111', 'f628']
raw = json.loads(RAW.read_text())
cases = json.loads(CASES.read_text())['cases']
bindings = json.loads(WITNESSES.read_text())['records']
plans = []
for row in raw['wholeCurrent21CandidateNativeRows']:
    gid = row['goalId']
    prefix = next(k for k in DESIGNS if gid.startswith(k))
    family, composition, limit = DESIGNS[prefix]
    prompt = COMMON + '\nComposition and exact model:\n' + composition + '\n\nBoundaries:\n' + limit + '\n'
    prompt_path = OUT / 'prompts' / (gid + '.prompt.txt')
    prompt_path.parent.mkdir(exist_ok=True)
    prompt_path.write_text(prompt)
    item = {'goalId': gid, 'family': family, 'firstSeven': prefix in first,
        'status': 'author_plan_pending_generation', 'wholeStage02CandidateGoal': row['wholeCandidateGoal'],
        'completeReferenceCases': [c for c in cases if c['goalId'] == gid],
        'actualFrozenSourceWitnessEffectiveBindings': [b for b in bindings if b['goalId'] == gid],
        'compositionDe': composition, 'boundedScopeDe': limit, 'prompt': bind(prompt_path),
        'humanApproval': False, 'independentVisualApproval': False, 'strictCompletion': 0}
    if prefix == '080b':
        item['generationHold'] = 'Await possible concrete current P-case correction; outside first seven.'
    assert len(item['completeReferenceCases']) == 2
    plans.append(item)
assert len(plans) == 21 and sum(p['firstSeven'] for p in plans) == 7
put('current21-whole-goals-materials-source-bound-image-plans.author.raw.json', {
    'role': 'image author; not independent V reviewer or integration',
    'authoringMethod': 'ChatGPT/Codex builtin image generation, one call per asset; no API/CLI fallback',
    'licenseForOwnImageCandidates': 'CC-BY-4.0', 'inputs': [bind(RAW), bind(CASES), bind(WITNESSES)],
    'primaryOriginalsActuallyReadForFirstSeven': [bind(ROOT / 'curricula/DE/Gymnasium/input/BY/gymnasium/Biologie.json'), bind(ROOT / 'curricula/DE/Gymnasium/input/HE/upper-secondary/kerncurriculum_gymnasiale_oberstufe-biologie.pdf')],
    'sourceBounds': 'BY B13 basic/advanced and HE Q2.3 page 43 for these bounded models; whole national source closure is not claimed.',
    'families': sorted(set(p['family'] for p in plans)), 'plans': plans,
    'firstSevenOrder': [p['goalId'] for k in first for p in plans if p['goalId'].startswith(k)],
    'actualGoalCardCss': {'path': 'app/src/components/GoalCard.tsx', 'image': 'display:block;height:auto;max-height:448px;width:100%;object-fit:contain'},
    'displayWidths': [360, 680], 'activeWrites': False, 'runtimeWrites': False, 'registryWrites': False,
    'independentVisualApproval': False, 'humanApproval': False, 'newStrictCompletion': 0,
    'allOriginalSourceHoldsPreserved': True})
print(json.dumps({'plans': len(plans), 'firstSeven': 7, 'families': len(set(p['family'] for p in plans)), 'output': str(OUT.relative_to(ROOT))}))
