// SPDX-License-Identifier: Apache-2.0
// Technical authoring only. Standard APIs; no reviewer decisions or active writes.
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync,existsSync,symlinkSync,realpathSync,readdirSync} from 'node:fs'
import {dirname,relative,resolve} from 'node:path'
import {fileURLToPath} from 'node:url'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import {buildGoalBookModel,loadGoalBookBuildInputs,stableGoalBookJson} from '../../../../../../../app/scripts/goalBookModel'
import {emptyGoalVisualizationAiReview} from '../../../../../../../app/scripts/goalVisualizationQaModel'
import {buildGoalDescriptionRolloutSubsetModel} from '../../../../../../../app/scripts/materializeGoalDescriptionRolloutBatch'
import {writeGoalBookHtml,writeGoalBookPdf,writeGoalBookRenderManifest} from '../../../../../../../app/scripts/goalBookRenderer'
import {buildGoalBookReviewBundle} from '../../../../../../../app/scripts/exportGoalBookReviewBundle'
import {createGoalDescriptionReviewCampaignArtifacts} from '../../../../../../../app/scripts/createGoalDescriptionReviewCampaign'
import {fingerprintGoalForPositiveEvidence,fingerprintPositiveGoalEvidenceReviewInput,fingerprintPositiveGoalEvidenceProfile,validatePositiveGoalEvidenceRecordSemantics} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel'
const R=resolve('.'),D=dirname(fileURLToPath(import.meta.url)),P=resolve(D,'../chemie-q3-four-bounded-source-current-author-20261008-v1')
const ids=['d9cce642-4f89-57f8-832a-abeb62586195','3eada74b-25b8-55dc-811a-acb473196f53'], rp=(p:string)=>relative(R,p)
const sh=(b:Buffer|string)=>'sha256:'+createHash('sha256').update(b).digest('hex')
const receipt=(p:string)=>{const b=readFileSync(p);return {path:rp(p),sha256:sh(b),bytes:b.length}}
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8'))
const put=(name:string,v:any)=>{const p=resolve(D,name),b=Buffer.isBuffer(v)?v:Buffer.from(typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');mkdirSync(dirname(p),{recursive:true});if(existsSync(p))assert.ok(readFileSync(p).equals(b),'Prepared existing bytes differ: '+p);else writeFileSync(p,b,{flag:'wx'});return receipt(p)}
const freeze=read(resolve(D,'first-input.freeze.json'))
for(const r of freeze.requiredInputs)assert.deepEqual(receipt(resolve(R,r.path)),r)
const activeGuard=read(resolve(D,'before/active-required-input-guards.actual.json'))
const before=read(resolve(D,'before/canonical.exact.json')),kindsBefore=read(resolve(D,'before/kinds.exact.json')),qaBefore=read(resolve(D,'before/qa.exact.json')),byBefore=new Map<string,any>(before.goals.map((g:any)=>[g.id,g]))
assert.equal(before.goals.length,480);assert.equal(kindsBefore.decisions.filter((r:any)=>r.semanticKind==='curricularAtomic').length,378)
const baselineKinds={...kindsBefore,sourceLandscapePath:rp(resolve(D,'before/canonical.exact.json'))};put('before/semantic-kinds.path-only.json',baselineKinds)
const baselineConfig={schemaVersion:1,bookId:'chemie-two-source-roles-current378-baseline-20261008-v1',title:'Chemie – vollständige aktuelle kanonische Prüfsicht',landscapePath:rp(resolve(D,'before/canonical.exact.json')),semanticKindLedgerPath:rp(resolve(D,'before/semantic-kinds.path-only.json')),goalVisualizationQaPath:rp(resolve(D,'before/qa.exact.json')),publicationMode:'review',atlasBaseUrl:'https://skillpilot.com/lernzielbuch',evidenceReviewPaths:[],outputPath:rp(resolve(D,'native/full378-before.actual-loader.book-model.json')),compositionViewPath:rp(resolve(D,'native/full378-composition-view.exact.json'))}
put('before/full378.actual-loader.config.json',baselineConfig)
const baseline=await loadGoalBookBuildInputs(rp(resolve(D,'before/full378.actual-loader.config.json')),R);assert.equal(baseline.model.pages.length,378);put('native/full378-before.actual-loader.book-model.json',baseline.model)
const canonical=structuredClone(before),by=new Map<string,any>(canonical.goals.map((g:any)=>[g.id,g])),selectedImages:Record<string,any>={}
const caption6='Katalysatorwirkung: geringere Aktivierungsbarriere und schnellere Gleichgewichtseinstellung; Beispiele für homogene und heterogene Katalyse.'
const alt6='Links vergleichen zwei Energieprofile die Reaktion ohne und mit Katalysator: Der katalysierte Weg besitzt eine niedrigere Aktivierungsbarriere bei denselben Energien der Reaktanten und Produkte. Zeitpfeile zeigen eine schnellere Gleichgewichtseinstellung; beide Gleichgewichtsgemische enthalten dieselben Anteile. Rechts steht homogene Katalyse mit Säure in Lösung einer heterogenen Reaktion von Gasen an einer festen Metalloberfläche gegenüber.'
const caption8='Elektrolyse wässriger Natriumchloridlösung und materialabhängige Überspannung bei konkurrierenden Anodenreaktionen.'
const alt8='Links zeigt eine Gleichspannungsquelle die Elektrolyse einer wässrigen Natriumchloridlösung: negative Kathode mit Wasserstoffbildung durch Reduktion und positive Anode mit Chlorbildung durch Oxidation von Chlorid. Rechts wird die benötigte Spannung aus thermodynamischer Zersetzungsspannung und Überspannungen beider Elektroden zusammengesetzt. Für das dargestellte Anodenmaterial ist die benötigte Spannung zur Sauerstoffbildung höher als zur Chlorbildung; deshalb wird Chlorid bevorzugt entladen.'
for(const id of ids){const extension=id===ids[0]?'png':'jpg',selected=resolve(D,'selected-images',id+'.'+extension),bytes=readFileSync(selected);if(extension==='png')assert.ok(bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])));else assert.ok(bytes.subarray(0,2).equals(Buffer.from([255,216])));selectedImages[id]=receipt(selected)
 const link=by.get(id).resourceLinks.find((l:any)=>l.type==='goal-visualization'&&l.role==='primary');assert.equal(link.skillpilotId,id);assert.equal(link.resourceType,'image');link.url='/assets/goal-visualizations/chemie/'+id+'/'+id+'.'+extension;link.license='CC-BY-4.0';link.description=id===ids[0]?caption6:caption8;link.altText=id===ids[0]?alt6:alt8;if(id===ids[0])link.provider='OpenAI / ChatGPT-Codex image generation';else assert.equal(link.provider,byBefore.get(id).resourceLinks.find((l:any)=>l.type==='goal-visualization').provider);assert.equal(link.reviewStatus,'pilot')
 const asset=resolve(D,'assets/goal-visualizations/chemie',id,id+'.'+extension);mkdirSync(dirname(asset),{recursive:true});if(!existsSync(asset))symlinkSync(relative(dirname(asset),selected),asset);assert.ok(realpathSync(asset).startsWith(D+'/'));assert.equal(sh(readFileSync(asset)),selectedImages[id].sha256)
 for(const required of ['type','resourceType','role','skillpilotId','title','url','provider','description','altText','lang','license','reviewStatus'])assert.ok(link[required],required)
}
for(const old of before.goals){const next=by.get(old.id);if(!ids.includes(old.id))assert.deepEqual(next,old);else{const a=structuredClone(old),b=structuredClone(next);delete a.resourceLinks;delete b.resourceLinks;assert.deepEqual(b,a)}}
assert.equal(selectedImages[ids[0]].sha256,'sha256:4b4445b163514281a2acbc1f589d660bf7343156d695f9dc19efc4e2b60031d2');assert.equal(selectedImages[ids[1]].sha256,'sha256:d945e8ed9e46d0def8694599c21b2d71a19504dbce044abea411aad0dc68f76a')
put('candidate/canonical.current480.two-resource-links.inactive.json',canonical)
const kinds={...kindsBefore,sourceLandscapePath:rp(resolve(D,'candidate/canonical.current480.two-resource-links.inactive.json'))};put('candidate/semantic-kinds.current480.path-only.inactive.json',kinds);assert.deepEqual(kinds.decisions,kindsBefore.decisions)
const qa=structuredClone(qaBefore),q6=qa.records.find((r:any)=>r.goalId===ids[0]);Object.assign(q6,{imageUrl:by.get(ids[0]).resourceLinks.find((l:any)=>l.type==='goal-visualization').url,publicAssetPath:selectedImages[ids[0]].path,canonicalAssetPath:selectedImages[ids[0]].path,assetSha256:selectedImages[ids[0]].sha256,visualizationState:'available',missingReason:'',umlautsCorrectChatGpt:'no',contentApprovedChatGpt:'no',chatGptReviewedAt:null,chatGptReviewer:'',chatGptNotes:'Technical native author materialization of actual selected PNGv2. Independent current D/P/V review pending; no approval inferred.',...emptyGoalVisualizationAiReview()})
for(const old of qaBefore.records){const next=qa.records.find((r:any)=>r.goalId===old.goalId);assert.ok(next);if(old.goalId!==ids[0])assert.deepEqual(next,old);for(const key of Object.keys(old).filter(k=>k.startsWith('human')))assert.deepEqual(next[key],old[key])}
put('candidate/visualization-qa.current378.only-six-unapproved.inactive.json',qa)
const candidateConfig={...baselineConfig,bookId:'chemie-two-source-roles-current378-native-20261008-v1',title:'Chemie – vollständige aktuelle Prüfsicht mit zwei gezielten Ressourcenkandidaten',landscapePath:kinds.sourceLandscapePath,semanticKindLedgerPath:rp(resolve(D,'candidate/semantic-kinds.current480.path-only.inactive.json')),goalVisualizationQaPath:rp(resolve(D,'candidate/visualization-qa.current378.only-six-unapproved.inactive.json')),outputPath:rp(resolve(D,'native/full378-candidate.actual-api.book-model.json'))};put('candidate/full378-native.inactive.config.json',candidateConfig)
const digests:Record<string,string>={},assetReceipts=[]
for(const row of qa.records)if(row.visualizationState==='available'){const r=receipt(resolve(R,row.publicAssetPath));assert.equal(r.sha256,row.assetSha256);digests[row.imageUrl]=r.sha256;assetReceipts.push(r)}
assert.equal(assetReceipts.length,qa.records.filter((r:any)=>r.visualizationState==='available').length)
const model=buildGoalBookModel({landscape:canonical,compositionView:read(resolve(R,candidateConfig.compositionViewPath)),semanticKindLedger:kinds,goalVisualizationQa:qa,goalVisualizationAssetDigests:digests,evidenceReviewSources:[],config:candidateConfig}as any);assert.equal(model.pages.length,378);put('native/full378-candidate.actual-api.book-model.json',model)
let same376=0;for(const old of baseline.model.pages)if(!ids.includes(old.goalId)){assert.equal(stableGoalBookJson(model.pages.find(p=>p.goalId===old.goalId)),stableGoalBookJson(old));same376++}assert.equal(same376,376)
const ordered=model.pages.filter(p=>ids.includes(p.goalId)).map(p=>p.goalId);assert.deepEqual(ordered,ids)
const subset=buildGoalDescriptionRolloutSubsetModel({baseModel:model,goalIds:ordered,bookId:'chemie-two-current-native-source-roles-20261008-v1',title:'Chemie: Katalyse und Ionenentladung – zwei aktuelle Prüfseiten'})
const native=resolve(D,'native/two'),modelPath=resolve(native,'book-model.json'),htmlPath=resolve(native,'book.html'),pdfPath=resolve(native,'book.pdf');put('native/two/book-model.json',subset)
const options={publicRoot:D,feedbackBaseUrl:'https://skillpilot.com/feedback',printDerivativeProfile:'bounded-atlas' as const}
const hm=await writeGoalBookHtml(subset,htmlPath,options);await writeGoalBookRenderManifest(hm,htmlPath+'.render-manifest.json');const pm=await writeGoalBookPdf(subset,pdfPath,options);await writeGoalBookRenderManifest(pm,pdfPath+'.render-manifest.json');assert.equal(pm.goalPageCount,2);assert.equal(pm.physicalPageCount,pm.frontMatterPageCount+2)
const bundleDirectory=resolve(native,'bundle'),bundle=await buildGoalBookReviewBundle(subset,{modelPath,pdfPath,pdfRenderManifestPath:pdfPath+'.render-manifest.json',htmlPath,htmlRenderManifestPath:htmlPath+'.render-manifest.json',outputDirectory:bundleDirectory,promptPath:resolve(R,'curricula/DE/Gymnasium/quality/goal-evidence/prompts/goal-description-understanding-evidence-review-v2.md'),criteriaPath:resolve(R,'curricula/DE/Gymnasium/quality/goal-evidence/prompts/chemistry-goal-description-understanding-evidence-review-criteria-v1.md'),goalIds:ordered})
for(const file of bundle.files)put('native/two/bundle/'+file.relativePath,file.content);put('native/two/bundle/review-bundle-manifest.json',bundle.manifest)
const artifact=(role:string)=>bundle.manifest.artifacts.find(a=>a.role===role)??(()=>{throw new Error('Missing '+role)})()
const campaigns=[]
for(const side of ['a','b']){const outputDirectory=resolve(native,'round-'+side);const result=await createGoalDescriptionReviewCampaignArtifacts({bundleBytes:readFileSync(resolve(bundleDirectory,'review-bundle-manifest.json')),bookModelBytes:readFileSync(resolve(bundleDirectory,artifact('book_model').path)),reviewInputBytes:readFileSync(resolve(bundleDirectory,artifact('review_input_json').path)),bundleDirectory,outputDirectory,campaignOptions:{campaignId:'chemie-two-current-source-roles-native-campaign-'+side+'-20261008-v1',roundId:'chemie-two-current-source-roles-native-independent-'+side+'-20261008-v1',reviewerRole:'internal_ai_reviewer',reviewPass:'first_pass',independenceGroupId:'chemie-two-current-source-roles-native-independent-'+side+'-20261008-v1',blindToOtherReviews:true,batchSize:2}});assert.equal(result.campaign.batches.length,1);assert.deepEqual(result.campaign.batches[0].goalIds,ordered);assert.ok(!existsSync(resolve(outputDirectory,'results')));campaigns.push({side,manifest:receipt(resolve(outputDirectory,'description-review-campaign.json')),validationErrors:0,batchSize:2,blindToOtherReviews:true})}
const originalRecords=read(resolve(P,'science/original-four-closed-v2-P-whole-records.exact-retained.json')),priorRecords=readFileSync(resolve(D,'positive/P2-existing-whole-author-records.exact.jsonl'),'utf8').trim().split('\n').map(l=>JSON.parse(l))
const ajv=new Ajv2020({allErrors:true,strict:false});addFormats(ajv);const validate=ajv.compile(read(resolve(R,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json'))),records=[],positiveChecks=[]
for(const id of ids){const prior=priorRecords.find((r:any)=>r.goalId===id),original=originalRecords.find((r:any)=>r.goalId===id);assert.ok(prior&&original);assert.deepEqual(prior.profile,original.profile)
 const goal=by.get(id),resources:Record<string,string>={};for(const link of goal.resourceLinks??[])if(link.type==='goal-visualization')resources[link.url]=digests[link.url];assert.equal(Object.keys(resources).length,1)
 const record={...prior,reviewId:'chemie-two-current-source-roles-native-author-20261008-v1',goalFingerprint:fingerprintGoalForPositiveEvidence(goal,'curricularAtomic'),reviewInputFingerprint:fingerprintPositiveGoalEvidenceReviewInput(goal,prior.reviewCriteriaFingerprint,resources,'curricularAtomic'),profileFingerprint:fingerprintPositiveGoalEvidenceProfile(prior.profile),reviewedAt:new Date().toISOString(),reviewer:'Codex /root/curricula_live_diagnosis technical author; current independent D/P/V reviewers pending',reason:'Exact original whole P2 E1/G1 profiles and four complete DE/EN material/task/model/scoring/fresh-transfer cases retained. Actual PNGv2 for6, original JPEGKEEP for8, current goal bodies and real resource fingerprints. Technical materialization makes no independent science, description, visualization or whole-source verdict.',reviewRunIds:[],dissent:['Author candidate only; needs_human_review and ai_candidate do not establish independent approval.','All49 source roles are explicitly bounded. All16 whole-duty holds from sealed sourceA/sourceB remain; no whole-union release.','Normal CLI resource binding for the new PNG remains pending installation after current independent review. Native positive-profile API and schema are checked here with actual PNG/JPEG bytes.']}
 assert.deepEqual(record.profile,original.profile);assert.equal(record.status,'needs_human_review');assert.equal(record.reviewAuthority,'ai_candidate');assert.equal(record.evidenceLevel,'E1');assert.equal(record.maximumClaimScope,'G1');assert.ok(validate(record),ajv.errorsText(validate.errors));const errors=validatePositiveGoalEvidenceRecordSemantics(record,goal,resources,'curricularAtomic');assert.deepEqual(errors,[]);records.push(record);positiveChecks.push({goalId:id,actualResources:resources,wholeOriginalProfileUnchanged:true,closedV2SchemaErrors:0,nativeSemanticErrors:errors.length})
}
put('positive/P2-current-whole-profiles-real-resource-native-author.jsonl',records.map(r=>JSON.stringify(r)).join('\n')+'\n')
const previousConfig=read(resolve(D,'positive/existing-P-config.exact.json')),positiveConfig={...previousConfig,reviewId:'chemie-two-current-source-roles-native-author-20261008-v1',landscapePath:candidateConfig.landscapePath,semanticKindLedgerPath:candidateConfig.semanticKindLedgerPath,reviewCriteriaPath:rp(resolve(D,'positive/chemistry-existing-review-criteria.exact.md')),reviewPath:rp(resolve(D,'positive/P2-current-whole-profiles-real-resource-native-author.jsonl')),reviewedResourceTypes:['goal-visualization'],requireApproved:false,scope:{label:'Two inactive current native whole science profiles, real PNG/JPEG candidates; independent D/P/V pending and whole-source holds retained',goalIds:ids}}
const validConfig=ajv.compile(read(resolve(R,'contracts/goal-evidence/v2/goal-evidence-review-config.schema.json')));assert.ok(validConfig(positiveConfig),ajv.errorsText(validConfig.errors));put('positive/P2-current-real-resource.inactive.config.json',positiveConfig)
for(const guard of activeGuard.files)assert.deepEqual(receipt(resolve(R,guard.path)),guard)
put('checks/actual-native-render-and-whole-bindings.technical.json',{schemaVersion:1,actualFullCanonicalGoals:480,actualBaselineLoaderGoalPages:378,actualCandidateNormalAPIGoalPages:378,unchangedOtherWholeCanonicalGoals:478,unchangedAllSelectedNonResourceFields:true,unchangedOtherWholeBookPages:same376,unchangedKindDecisions:480,unchangedOtherQARows:377,unchangedAllHumanQARows:378,assetDigestCount:assetReceipts.length,selectedImages,positiveChecks,positiveConfigClosedSchemaErrors:0,campaigns,actualPDF:receipt(pdfPath),actualGoalPageCount:pm.goalPageCount,actualPhysicalPageCount:pm.physicalPageCount,actualFrontMatterPageCount:pm.frontMatterPageCount,pageMap:ordered.map((id,i)=>({goalId:id,logicalPage:i+1,physicalPage:pm.frontMatterPageCount+i+1,actualSelectedImage:selectedImages[id]})),normalNewPNGCLI:'pending_candidate_installation_after_independent_review',sourceWhole49AndAll259Partners:'bound_exact_whole_context',sourceWholeHolds:16,actualActiveGuardsChecked:activeGuard.files.length,nativeD_P_VReviewsCreated:0,newStrictClosures:0,activeWrites:0,humanApproval:false,humanTrial:false})
put('checks/all-available-current-image-digests.technical.json',{files:assetReceipts})
const links=ids.map(id=>({goalId:id,currentLink:by.get(id).resourceLinks.find((l:any)=>l.type==='goal-visualization'&&l.role==='primary'),actualImage:selectedImages[id],fullGuide:receipt(resolve(D,'guide/atomic-goal-visualizations.exact.md')),prompt:receipt(resolve(D,'selected-images',id+(id===ids[0]?'.prompt.md':'.original-prompt.de.md'))),generationProvenance:id===ids[0]?receipt(resolve(D,'selected-images',id+'.provenance.json')):{actualExistingProvider:byBefore.get(id).resourceLinks.find((l:any)=>l.type==='goal-visualization').provider,preciseModelOrGenerationRequestNotPresentInRetainedOriginalInput:true,notInferred:true},firstActualFullRasterViewedForMetadata:true,newIndependentVisualApproval:false}))
put('selected-images/two-current-links-complete-guide-and-actual-provenance.technical.json',{schemaVersion:1,links,actualOriginalGoal8JPEGUnchanged:true,goal6PNGAuthorV2BytesUnchanged:true,newImageGeneration:false,newVisualApproval:false})
console.log(JSON.stringify({full480BaselineAndCandidate378:true,nativeGoalPages:2,physicalPages:pm.physicalPageCount,frontMatterPages:pm.frontMatterPageCount,standardCampaigns:2,campaignErrors:0,P2SchemaAndSemanticErrors:0,all16WholeHoldsRetained:true,activeWrites:0,newStrictClosures:0}))
