"""Own complete bilingual evolution cases. Synthetic models are never pupil evidence."""
CASES=[]
def add(o,n,md,me,td,te,ad,ae):
    CASES.append({'ordinal':o,'id':f'he-evolution18-{o:02d}-case-{n}','material':{'de':md,'en':me},'task':{'de':td,'en':te},'modelAnswer':{'de':ad,'en':ae},'provenance':'Own synthetic didactic material and public model answer; not actual learner performance, experimental execution, or new historical/fossil measurement.'})

add(1,1,
'Eigenes vereinfachtes Museumsmodell: FossilF aus einer älteren Schicht besitzt KnochenA-B-C in derselben relativen Lage wie ein späteres LandwirbeltierL, aber zusätzliche Merkmale einer Wasserlebensweise. Die älter/jünger-Zuordnung ist durch unabhängige Schichtdaten vorgegeben. Mitochondrien besitzen eigene DNA, bakterienähnliche Ribosomen und entstehen aus vorhandenen Mitochondrien; Kern-Gene und Organellfunktionen sind heute eng verflochten. Keine Probe wurde hier untersucht.',
'Own simplified museum model: fossilF from an older layer has bonesA-B-C in the same relative positions as a later land vertebrateL but also traits of an aquatic way of life. Older/younger assignments are supplied by independent stratigraphic data. Mitochondria have their own DNA, bacteria-like ribosomes, and arise from existing mitochondria; nuclear genes and organelle functions are closely integrated today. No specimen was investigated here.',
'Nutze Fossilfolge, Lagehomologie und die genannten Organellbefunde als unterschiedlichartige Evolutionsbelege. Erkläre ihren Zusammenhang und die Grenze der Aussage, F sei dadurch sicher der direkte Vorfahr vonL.',
'Use the fossil sequence, positional homology, and supplied organelle findings as different kinds of evolutionary evidence. Explain how they relate and the limit of claiming thatF is therefore certainly the direct ancestor ofL.',
'Die zeitliche Fossilfolge und das Merkmalsmosaik passen zu Veränderung und Verzweigung von Abstammungslinien. Gleichartige relative Knochenlage unterstützt die Homologiehypothese, wenn weitere strukturelle und entwicklungsbiologische Belege passen. Eigene DNA, bakterienähnliche Ribosomen und Teilung der Mitochondrien stützen die Aufnahme und Integration ehemals freilebender Bakterien nach der Endosymbiontentheorie. Das sind zusammenpassende, verschiedenartige Hinweise. Die zeitlich frühere Form muss kein direkter Vorfahr sein; Fossillücken und Seitenzweige erlauben mehrere Stammbäume. Heutige Mitochondrien sind keine unabhängig lebenden Bakterien.',
'The fossil sequence and mosaic of traits are consistent with changes and branching of lineages. Similar relative bone positions support a homology hypothesis when additional structural and developmental evidence agrees. Their own DNA, bacteria-like ribosomes, and division support uptake and integration of formerly free-living bacteria under endosymbiotic theory. These are mutually compatible but different lines of evidence. An earlier form need not be a direct ancestor; fossil gaps and side branches permit several trees. Present-day mitochondria are not independently living bacteria.')
add(1,2,
'Eigenes Vergleichsmodell: Vogel und Fledermaus fliegen; ihre Vorderextremitäten zeigen denselben Grundbauplan, ihre Flugflächen entstehen aber unterschiedlich. Ein fliegendes Insekt besitzt keine entsprechenden Wirbeltierknochen. Zwei hypothetische Fossilien derselben Epoche tragen verschiedene Merkmalsmosaike. Chloroplasten besitzen eigene DNA, bakterienähnliche Ribosomen und eine Doppelmembran; molekulare Vergleiche ordnen ihre Herkunft einer cyanobakteriellen Linie zu.',
'Own comparison model: a bird and a bat fly; their forelimbs have the same basic anatomical plan, but their flight surfaces develop differently. A flying insect lacks the corresponding vertebrate bones. Two hypothetical fossils from the same period have different trait mosaics. Chloroplasts have their own DNA, bacteria-like ribosomes, and a double membrane; molecular comparisons connect their origin to a cyanobacterial lineage.',
'Prüfe die Aussage, gleiche Funktion beweise gleiche Abstammung und die Fossilien bildeten eine einzige Fortschrittsreihe. Beziehe dabei Homologie, Fossilien und die Endosymbiontentheorie auf die vorliegenden Materialien.',
'Evaluate the claim that the same function proves the same ancestry and that the fossils form a single ladder of progress. Relate homology, fossils, and endosymbiotic theory to the supplied materials.',
'Fliegen ist als Funktion allein kein Homologienachweis. Der Wirbeltier-Vorderextremitätenbauplan kann homolog sein, während Flugflächen und Flugfähigkeit in diesen Linien unabhängig ausgebildet wurden; der Insektenflügel ist hierzu analog. Zeitgleiche Fossilien mit unterschiedlichen Mosaiken passen zu Verzweigungen, nicht zwingend zu einer linearen Rangfolge. Chloroplastenbefunde stützen eine endosymbiotische Herkunft; DNA-Verwandtschaft ergänzt strukturelle Befunde, und die Doppelmembran allein beweist die Theorie nicht. Die drei Belegarten stützen gemeinsame Abstammung und Veränderung mit jeweils eigenen Grenzen, ohne heutige Organismen als höher oder niedriger zu ordnen.',
'Flight as a function alone does not establish homology. The vertebrate forelimb plan can be homologous while flight surfaces and flight evolved independently in these lineages; the insect wing is analogous to them. Contemporaneous fossils with different mosaics fit branching rather than necessarily a linear ranking. Chloroplast findings support an endosymbiotic origin; DNA relationships supplement structural findings, and a double membrane alone does not prove the theory. The three types of evidence support common ancestry and change within their respective limits, without ranking present-day organisms as higher or lower.')

add(2,1,
'Zwei eigene Artbildungsmodelle: A: Eine Flusspopulation wird durch eine dauerhaft entstandene Wasserscheide getrennt. Später unterscheiden sich Balz und Fortpflanzungszeit; im Kontaktgebiet entstehen kaum erfolgreiche Paarungen. B: In einem zusammenhängenden Gebiet wechseln einige Insekten auf eine andere Wirtspflanze; dort paaren sie sich überwiegend, der Genfluss sinkt ohne räumliche Barriere. Anfangs können beide Gruppen miteinander fruchtbare Nachkommen erzeugen. Langzeitdaten sind Modellannahmen.',
'Two own speciation models: A: a river population is separated by a persistent watershed. Later, courtship and reproductive timing differ; few successful matings occur in a contact zone. B: within one connected area, some insects shift to another host plant, where they mainly mate; gene flow decreases without a geographical barrier. Initially both groups can produce fertile offspring together. Long-term findings are model assumptions.',
'Erläutere allopatrische und sympatrische Artbildung anhand vonA/B. Beschreibe die Rolle von Isolation, unterschiedlicher Entwicklung und reproduktiver Isolation und sage, warum Wirtswechsel allein noch keine neue Art beweist.',
'Explain allopatric and sympatric speciation throughA/B. Describe the roles of isolation, divergence, and reproductive isolation and explain why a host shift alone does not establish a new species.',
'A beginnt mit geografischer Isolation: verringerter Genfluss ermöglicht unterschiedliche Entwicklung durch Mutation, Selektion und Drift; später entstandene reproduktive Barrieren können auch nach Kontakt fortbestehen. B beginnt ohne geografische Trennung: ökologische Spezialisierung und assortative Paarung können den Genfluss einschränken und reproduktive Isolation fördern. Die Prozesse sind nicht allein durch unterschiedliche Aussehen oder Wirtspflanzen definiert. Dass anfangs fruchtbare Kreuzungen möglich sind, zeigt einen noch nicht abgeschlossenen Trennungsprozess; für die neue Art wären beständige Fortpflanzungsbarrieren und eine passende Artdefinition zu prüfen.',
'A starts with geographical isolation: reduced gene flow permits divergence through mutation, selection, and drift; subsequently evolved reproductive barriers can persist after renewed contact. B starts without geographical separation: ecological specialization and assortative mating can restrict gene flow and promote reproductive isolation. The processes are not defined merely by different appearances or host plants. Initial fertile crosses indicate an incomplete separation process; a new-species claim would require persistent reproductive barriers and an appropriate species concept.')
add(2,2,
'Eigenes Pflanzenmodell: In einer diploiden Population mit2n=14 entsteht durch einen Fehler der Chromosomenverteilung eine tetraploide Pflanze mit4n=28. Zwei tetraploide Pflanzen bilden gemeinsam fruchtbare Nachkommen. Kreuzungen mit Diploiden erzeugen überwiegend triploide Nachkommen mit gestörter Meiose. Die Pflanzen wachsen am selben Ort. Vergleichsfall: Zwei diploide Bestände werden auf Inseln getrennt, bleiben beim erneuten Kontakt aber vollständig kreuzbar.',
'Own plant model: in a diploid population with2n=14, a chromosome-segregation error produces a tetraploid plant with4n=28. Two tetraploid plants produce fertile offspring together. Crosses with diploids mostly produce triploid offspring with disturbed meiosis. The plants grow in the same location. Comparison: two diploid populations become separated on islands but remain fully interfertile on renewed contact.',
'Erkläre, wie Polyploidisierung im ersten Modell sympatrische Artbildung ermöglichen kann. Vergleiche den Inselprozess als allopatrischen Ausgangspunkt und grenze räumliche Trennung von abgeschlossener Artbildung ab.',
'Explain how polyploidization can enable sympatric speciation in the first model. Compare the island process as an allopatric starting point and distinguish spatial separation from completed speciation.',
'Die unterschiedliche Chromosomenzahl kann ohne Ortswechsel eine reproduktive Barriere schaffen: Triploide haben im Modell Schwierigkeiten bei der regelmäßigen Chromosomenpaarung. Eine sich fortpflanzende tetraploide Gruppe kann deshalb eine getrennte Linie bilden, sofern Etablierung und dauerhafter Genflussverlust gelingen. Ein einzelner Tetraploider begründet nicht automatisch eine stabile Art. Die Inseltrennung ist geografische Isolation und damit ein allopatrischer Ausgangspunkt; vollständige Kreuzbarkeit beim Kontakt belegt hier keine abgeschlossene reproduktive Trennung. Beide Modelle erfordern Aussagen über Genfluss und Fortpflanzung, nicht nur den Ort.',
'Different chromosome numbers can create a reproductive barrier without relocation: triploids have difficulty with regular chromosome pairing in this model. A reproducing tetraploid group can therefore establish a separate lineage if establishment and persistent restriction of gene flow succeed. A single tetraploid does not automatically establish a stable species. Island separation is geographical isolation and an allopatric starting point; full interfertility on contact does not establish completed reproductive separation here. Both models require statements about gene flow and reproduction, not location alone.')

add(3,1,
'Eigenes Fossil- und Kartenmodell, keine neuen historischen Datierungen: FundA in Afrika ist etwa2Mio.Jahre alt und besitzt MerkmaleP/Q; FundB in Afrika ist1Mio.Jahre alt und besitztP/R; FundC außerhalb Afrikas ist0,6Mio.Jahre alt und besitztP/R. Vereinfachte Datierungskarte ergänzt frühe Homo-sapiens-Funde in Afrika vor ungefähr300000Jahren und wesentlich spätere Funde in weiteren Weltregionen. Das Modell lässt Fundlücken und mehrere Ausbreitungsereignisse ausdrücklich offen.',
'Own fossil and map model, not new historical dating: findA in Africa is about2million years old with traitsP/Q; findB in Africa is1million years old withP/R; findC outside Africa is0.6million years old withP/R. A simplified dating map adds early Homo-sapiens finds in Africa around300000years ago and substantially later finds in other world regions. The model explicitly permits gaps and multiple dispersal events.',
'Beschreibe Fossilgeschichte, einen mit den Merkmalen verträglichen hypothetischen Stammbaum und die grobe Ausbreitung moderner Menschen. Erkläre, warum Alter und Fundort allein weder direkte Vorfahren noch eine lückenlose Wanderroute bestimmen.',
'Describe the fossil record, a hypothetical phylogenetic tree compatible with the traits, and the broad dispersal of modern humans. Explain why age and location alone establish neither direct ancestors nor an uninterrupted migration route.',
'Die älteren afrikanischen Funde und späteren außerafrikanischen Funde sind mit afrikanischem Ursprung wichtiger Menschenlinien und späteren Ausbreitungen vereinbar. GemeinsamkeitenP/R können B/C als verwandte Zweige stützen; A kann ein früherer Seitenzweig sein statt zwingend direkter Vorfahr. Die Homo-sapiens-Karte unterstützt afrikanischen Ursprung und spätere geografische Verbreitung, nicht die Behauptung einer einzigen bekannten Route. Erhaltungs- und Fundlücken sowie mögliche zeitliche Überlappung machen den Stammbaum hypothetisch. Heutige Menschen stammen nicht von heute lebenden Menschenaffen ab; beide besitzen gemeinsame frühere Vorfahren.',
'Older African and later non-African finds are consistent with African origins of important human lineages and subsequent dispersals. SharedP/R traits may support B/C as related branches; A may be an earlier side branch rather than necessarily a direct ancestor. The Homo-sapiens map supports African origins and later geographical spread, not a single fully known route. Preservation and discovery gaps and possible temporal overlap make the tree hypothetical. Present-day humans do not descend from present-day apes; both have earlier common ancestors.')
add(3,2,
'Eigenes Lehrmodell: Ein vereinfachter Stammbaum verzweigt vor der Aufteilung von Neandertaler-Linie und Homo-sapiens-Linie; beide Zweige existieren zeitweilig nebeneinander. Fossile Merkmalskombinationen unterscheiden sich, und bereitgestellte genetische Befunde weisen auf begrenzten Genfluss zwischen den Linien hin. Die Karte zeigt Homo-sapiens-Ursprung in Afrika und spätere Fundorte in Eurasien sowie weiteren Regionen. Die Grafik enthält weder einen sicheren direkten Vorfahr noch eine vollständige Individuengenealogie.',
'Own teaching model: a simplified tree branches before the separation of Neanderthal and Homo-sapiens lineages; both branches coexist for a period. Fossil trait combinations differ, and supplied genetic evidence indicates limited gene flow between the lineages. The map shows Homo-sapiens origins in Africa and later find locations in Eurasia and other regions. The diagram identifies neither a certain direct ancestor nor a complete individual genealogy.',
'Beschreibe die im Modell belegte Fossilgeschichte, Verzweigung und Ausbreitung. Korrigiere die Bildunterschrift Neandertaler wurden vollständig zu modernen Menschen und ordne die Genflussdaten ein.',
'Describe the fossil record, branching, and dispersal represented in the model. Correct the caption Neanderthals all turned into modern humans and interpret the gene-flow findings.',
'Die Bildunterschrift macht aus nebeneinander bestehenden Zweigen fälschlich eine lineare Umwandlung. Der Stammbaum stellt Abstammungshypothesen zwischen Populationen und Linien dar. Homo sapiens entstand in Afrika und breitete sich später aus; ein begrenzter genetischer Beitrag aus einer anderen Linie passt zu Kontakten und Kreuzungen, ohne diese Linie zum einzigen direkten Ursprung aller modernen Menschen zu machen. Fossilformen und Datierungen sowie DNA-Befunde ergänzen einander, bleiben aber lückenhaft. Aus dem Modell folgt keine Rangfolge heutiger Menschengruppen.',
'The caption incorrectly converts coexisting branches into a linear transformation. The tree represents ancestry hypotheses among populations and lineages. Homo sapiens originated in Africa and dispersed later; a limited genetic contribution from another lineage fits contact and interbreeding without making that lineage the sole direct origin of all modern humans. Fossil forms and dates complement DNA evidence but remain incomplete. The model does not imply a hierarchy among present-day human groups.')

add(4,1,
'Eigenes Weitergabemodell: Eine Gruppe lernt einen dreistufigen Werkzeugbau entweder nur durch Anschauen oder zusätzlich durch sprachliche Erklärungen. In fünf aufeinanderfolgenden Lernweitergaben bleibt im Sprachmodell die komplexe Abfolge häufiger erhalten; beide Gruppen besitzen dasselbe vorhandene biologische Lernvermögen. Funde bearbeiteter Steine belegen Werkzeugproduktion, erhalten aber keine gesprochenen Sätze. Die Zahlen sind synthetisch und beweisen keinen historischen Beginn der Sprache.',
'Own transmission model: a group learns a three-step toolmaking sequence either by observation alone or additionally through verbal explanation. Across five successive learning transmissions, the complex sequence is retained more often in the language model; both groups have the same existing biological capacity to learn. Worked-stone finds indicate tool production but preserve no spoken sentences. The figures are synthetic and do not establish the historical origin of language.',
'Stelle die Bedeutung von Werkzeuggebrauch und Sprachentwicklung für kulturelle Evolution dar. Trenne Weitergabe erlernter Techniken von genetischer Vererbung und die Modellbeobachtung von einer historischen Schlussfolgerung.',
'Explain the significance of tool use and language development for cultural evolution. Distinguish transmission of learned techniques from genetic inheritance and the model observation from a historical conclusion.',
'Werkzeuge verändern die Möglichkeiten, Ressourcen zu nutzen und Tätigkeiten zu organisieren. Sprache kann Anleitungen, Kooperation und die präzise Weitergabe komplexer Techniken erleichtern; dadurch können kulturelle Neuerungen kumulieren. Das vorhandene Lernvermögen hat biologische Voraussetzungen, die konkrete Baufolge wird hier aber sozial erlernt und nicht als erworbene Anleitung genetisch vererbt. Das Modell zeigt einen möglichen Mechanismus, nicht die tatsächliche Reihenfolge von Werkzeug- und Sprachentstehung. Steinfunde allein datieren keine vollständige Sprache.',
'Tools change the possibilities for using resources and organizing activities. Language can facilitate instruction, cooperation, and accurate transmission of complex techniques, allowing cultural innovations to accumulate. Existing learning capacity has biological prerequisites, but the particular sequence is learned socially here rather than inherited genetically as an acquired instruction. The model demonstrates a possible mechanism, not the actual chronological order in which tools and language originated. Stone finds alone do not date a complete language.')
add(4,2,
'Eigenes Vergleichsmodell: Eine Werkzeugtechnik verbreitet sich innerhalb weniger Jahre auch zwischen nicht verwandten Gruppen, begleitet von erklärenden Begriffen und gemeinsamer Planung. Eine andere Gruppe verwendet denselben einfachen Werkzeugtyp, aber ohne Nachweis gemeinsamer Begriffe. Generationen lange genetische Änderungen wurden in keinem Fall untersucht. Zwei Hypothesen lauten: Jede Werkzeugverbesserung setzt sofort ein neues Sprachgen voraus; Sprache und Werkzeuggebrauch können sich durch Lernen und Rückkopplungen gegenseitig unterstützen.',
'Own comparison model: a tool technique spreads within a few years among unrelated groups, accompanied by explanatory terms and joint planning. Another group uses the same simple tool type without evidence of shared terminology. No multigenerational genetic changes were studied in either case. Two hypotheses claim respectively that every tool improvement immediately requires a new language gene, or that language and tool use can support one another through learning and feedback.',
'Begründe mit dem Material die Bedeutung beider kultureller Leistungen und vergleiche die Hypothesen. Gib an, welche Aussagen über frühe Sprachentwicklung offenbleiben.',
'Use the material to explain the significance of both cultural achievements and compare the hypotheses. State which claims about early language development remain open.',
'Die schnelle Weitergabe auch zwischen Nichtverwandten spricht für kulturelles Lernen. Werkzeuge erschließen Handlungsoptionen; sprachliche Begriffe und Planung können Wissen koordinieren und seine Weitergabe erleichtern. Dafür muss nicht bei jeder Neuerung ein neues Gen entstehen. Biologische Fähigkeiten und kulturelle Prozesse können langfristig wechselwirken, aber diese Modellbeobachtung beweist keine bestimmte genetische Veränderung. Gleiche Werkzeuge allein belegen weder gleiche Sprachfähigkeit noch den Ursprung oder den genauen Zeitpunkt von Sprache. Die Rückkopplungshypothese ist mit dem Material vereinbar, ohne als vollständig bewiesene historische Geschichte zu gelten.',
'Rapid transmission among unrelated individuals supports cultural learning. Tools enable actions; verbal terms and planning can coordinate knowledge and facilitate its transmission. Each innovation does not require a new gene. Biological capacities and cultural processes can interact over longer times, but the model observation establishes no particular genetic change. Similar tools alone establish neither identical language abilities nor the origin or exact timing of language. The feedback hypothesis is compatible with the material without constituting a fully established historical account.')

add(5,1,
'Eigenes nichtinvasives Beobachtungsmodell an Primaten: Bei derselben Gruppe treten in einer Saison mit räumlich konzentriertem Futter häufiger Verdrängungen am Futterplatz auf als bei verstreutem Futter. Paarungsverhalten häuft sich in der Fortpflanzungsphase. Bereits vorhandene Beobachtungsprotokolle dokumentieren bekannte Individuen, Alter, Gruppenzusammensetzung und reproduktiven Zustand; keine Tiere wurden manipuliert. Futterverteilung und Jahreszeit ändern sich teilweise gemeinsam.',
'Own noninvasive primate-observation model: the same group shows more displacement at feeding sites during a season with concentrated food than when food is dispersed. Mating behavior is more frequent during the reproductive phase. Existing observation protocols record known individuals, age, group composition, and reproductive state; no animals were manipulated. Food distribution and season partly change together.',
'Erläutere exogene und endogene Ursachen der beschriebenen sozialen Verhaltensweisen. Unterscheide geeignete Beobachtungsbelege von einer sicheren Ursachenzuordnung und nenne eine gezielte Auswertung ohne Eingriff an den Tieren.',
'Explain exogenous and endogenous causes of the described social behavior. Distinguish suitable observational evidence from a certain causal attribution and propose a focused analysis without intervening in the animals.',
'Futterverteilung und die Anwesenheit anderer Tiere sind exogene Einflussgrößen; hormoneller/reproduktiver Zustand und innere Motivation sind mögliche endogene Einflüsse. Konkurrenz bei konzentriertem Futter und Paarungsverhalten in der Fortpflanzungsphase sind damit vereinbar. Das gemeinsame Ändern mehrerer Größen verhindert jedoch eine eindeutige Ursache allein aus der Häufigkeit. Eine Auswertung kann dieselben Individuen bei vergleichbarem reproduktivem Zustand und unterschiedlicher Futterverteilung vergleichen und Gruppengröße kontrollieren. Proximate Ursachen beantworten das unmittelbare Wie/Warum, nicht bereits den evolutiven Fitnessnutzen.',
'Food distribution and the presence of other animals are exogenous factors; hormonal/reproductive state and internal motivation are possible endogenous influences. Competition around concentrated food and mating during the reproductive phase are compatible with these factors. Concurrent changes in several variables prevent a unique causal attribution from frequency alone. An analysis could compare the same individuals at comparable reproductive states under different food distributions while accounting for group size. Proximate causes address immediate mechanisms rather than already establishing an evolutionary fitness benefit.')
add(5,2,
'Eigenes Datensatzmodell: Bereits dokumentierte Gruppenwechsel sind zeitweise mit weniger Fellpflege und mehr Distanzverhalten verbunden. Bei denselben Tieren liegen unabhängig gewonnene, nichtinvasive Hinweise auf veränderten Stresszustand vor. Verwandtschaft, Rang und vorherige soziale Bindungen unterscheiden sich zwischen Tieren. Eine Zusammenfassung behauptet, sämtliche soziale Handlungen seien entweder nur durch Umwelt oder nur durch Hormone bestimmt. Es gibt keine experimentelle Manipulation und keine Diagnosedaten von Menschen.',
'Own dataset model: documented group changes are temporarily associated with less grooming and more distancing. The same animals have independently obtained noninvasive indications of altered stress state. Kinship, rank, and prior social bonds differ among individuals. A summary claims that every social action is determined either only by the environment or only by hormones. There is no experimental manipulation or human diagnostic information.',
'Prüfe die Entweder-oder-Erklärung anhand exogener und endogener Ursachen. Erkläre, welche Informationen eine begründete Verhaltensanalyse braucht und welche Ursache aus dem Material nicht bewiesen ist.',
'Evaluate the either-or explanation using exogenous and endogenous causes. Explain which information a justified behavioral analysis needs and which cause the material does not establish.',
'Der Gruppenwechsel verändert exogene soziale Reize und Beziehungen; der innere Stresszustand kann die Reaktion beeinflussen. Beide Ebenen wirken zusammen und lassen sich nicht durch eine Entweder-oder-Zuordnung ersetzen. Individuenvergleiche müssen Rang, Verwandtschaft, frühere Bindungen und Beobachtungszeit berücksichtigen. Die Zusammenhänge begründen Hypothesen über Stress und Sozialverhalten, zeigen aber nicht allein, ob Stress das Distanzverhalten verursacht, aus ihm folgt oder beide auf den Gruppenwechsel reagieren. Primatenbefunde erlauben keine einfache biologische Festlegung menschlicher sozialer Rollen.',
'Group changes alter exogenous social stimuli and relationships; internal stress state can influence the response. Both levels interact and cannot be replaced by an either-or classification. Individual comparisons must account for rank, kinship, previous bonds, and observation period. The associations support hypotheses about stress and social behavior but alone do not show whether stress causes distancing, follows it, or whether both respond to the group change. Primate findings do not justify simple biological prescriptions of human social roles.')

add(6,1,
'Eigenes didaktisches Material, kein wörtliches historisches Zitat: Eine kommentierte Karte beschreibt, dass NS-Eugenik vermeintlich erblichen Eigenschaften einen unterschiedlichen Menschenwert zuschrieb und damit Zwangssterilisation und Verfolgung rechtfertigte. Zweite Karte erläutert biologische Fitness als kontextabhängigen Fortpflanzungsbeitrag, nicht als Würde, Gesundheit oder moralischen Wert. Historischer Hintergrund wurde gegen die USHMM-Darstellung Eugenics geprüft; Opfer werden nicht als biologisch minderwertig beschrieben.',
'Own didactic material, not a verbatim historical quotation: an annotated card describes how Nazi eugenics assigned unequal human worth to supposedly inherited traits and used this to justify forced sterilization and persecution. A second card explains biological fitness as context-dependent reproductive contribution, not dignity, health, or moral value. Historical background was checked against the USHMM account Eugenics; victims are not described as biologically inferior.',
'Ordne die Karte als historischen Missbrauch biologischer/evolutionärer Vorstellungen ein. Erkläre den naturalistischen Fehlschluss und die Verwechslung von Fitness und Menschenwert und begründe eine sachliche Gegendarstellung.',
'Classify the card as a historical misuse of biological/evolutionary ideas. Explain the naturalistic fallacy and confusion of fitness with human worth and justify a factual counterstatement.',
'NS-Eugenik verband selektive beziehungsweise fehlerhafte Vererbungsannahmen mit rassistischer Wertung und staatlichem Zwang. Aus biologischen Unterschieden oder unterschiedlichem Fortpflanzungserfolg folgt keine moralische Erlaubnis zur Entrechtung: der Übergang von einer Beschreibung zu einer normativen Forderung ist hier unbegründet. Fitness ist relativ zur Umwelt und bezeichnet keinen Rang menschlicher Würde. Evolutionstheorie erklärt Veränderungsprozesse; sie schreibt keine politische Gewalt oder Ausschließung vor. Die Gegendarstellung unterscheidet empirische Prüfung von ethischen Grundsätzen und benennt Verfolgung und Zwang als Unrecht, ohne die Täterkategorien als gültige Biologie zu übernehmen.',
'Nazi eugenics combined selective or erroneous heredity assumptions with racist judgments and state coercion. Biological differences or differences in reproductive success do not entail moral permission to deny rights: the move from description to normative demand is unjustified here. Fitness is environment-relative and does not rank human dignity. Evolutionary theory explains processes of change; it does not prescribe political violence or exclusion. The counterstatement separates empirical testing from ethical principles and identifies persecution and coercion as wrong without adopting the perpetrators’ categories as valid biology.')
add(6,2,
'Eigenes Quellenprüfungsmodell: Ein heutiger Kommentar behauptet, staatliche Unterstützung sei gegen die Evolution, und verweist als Vorbild auf NS-Rassenhygiene. Eine historische Übersicht benennt deren Zwangssterilisationspolitik und rassistische Verfolgung. Ein Biologiehinweis beschreibt neben Konkurrenz auch Kooperation, Umweltabhängigkeit und genetische Variabilität innerhalb menschlicher Populationen. Die Aussagen des Kommentars sind zur Kritik paraphrasiert, nicht als Tatsachen oder Originalzitat wiedergegeben.',
'Own source-evaluation model: a present-day commentary claims that state support is against evolution and presents Nazi racial hygiene as a model. A historical overview identifies its compulsory sterilization policies and racist persecution. A biology note describes cooperation alongside competition, environmental dependence, and genetic variation within human populations. The commentary’s claims are paraphrased for critique, not presented as facts or original quotations.',
'Analysiere die argumentative Verwendung der Evolutionstheorie und ordne das NS-Beispiel kritisch ein. Zeige, warum eine politische Sollensregel nicht aus dem Evolutionsbegriff folgt, auch wenn einzelne biologische Beobachtungen stimmen.',
'Analyze the argumentative use of evolutionary theory and critically assess the Nazi example. Show why a political prescription does not follow from evolution even when some biological observations are correct.',
'Der Kommentar reduziert Evolution auf eine politisch gewünschte Konkurrenzgeschichte und stellt NS-Rassenhygiene fälschlich als biologische Anleitung dar. Historisch wurden pseudowissenschaftliche Hierarchien für Zwang und Verfolgung eingesetzt. Kooperation und kontextabhängige Fitness widerlegen bereits die biologische Verengung, aber selbst eine korrekte biologische Beschreibung würde die politische Norm nicht begründen. Ethische und rechtliche Regeln benötigen eigene Begründungen. Die Kritik darf weder die Evolutionstheorie pauschal mit NS-Ideologie gleichsetzen noch Menschenwert aus Abstammung oder vermeintlichen genetischen Gruppenrängen ableiten.',
'The commentary reduces evolution to a politically preferred story of competition and incorrectly presents Nazi racial hygiene as biological instruction. Historically, pseudoscientific hierarchies were used to support coercion and persecution. Cooperation and context-dependent fitness already refute the biological simplification, but even a correct biological description would not justify the political norm. Ethical and legal rules require their own justification. The critique must neither equate evolutionary theory wholesale with Nazi ideology nor infer human worth from ancestry or supposed genetic group rankings.')
