// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict'
import {readFileSync,writeFileSync,readdirSync} from 'node:fs'
import {relative,resolve,dirname} from 'node:path'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
import {compileCompositionView,normalizeCompositionView,collectCompositionProjectionRoleGoalIds} from '../../../../../../../app/src/utils/authoring/compositionViewAuthoring.ts'
import {normalizeCanonicalLandscape} from '../../../../../../../app/src/utils/authoring/canonicalAuthoring.ts'
import {fingerprintGoalForPositiveEvidence,fingerprintPositiveGoalEvidenceReviewInput,fingerprintPositiveGoalEvidenceProfile,validatePositiveGoalEvidenceRecordSemantics} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel.ts'
const R=resolve('.'),D=dirname(fileURLToPath(import.meta.url)),P=relative(R,D),ID='82acfbde-9ce8-5658-892e-4dcfb1c3a1f1',read=(p:string)=>JSON.parse(readFileSync(resolve(R,p),'utf8')),sha=(x:any)=>'sha256:'+createHash('sha256').update(x).digest('hex'),bind=(p:string)=>({path:p,sha256:sha(readFileSync(resolve(R,p))),bytes:readFileSync(resolve(R,p)).length})
const canonical=read(`${P}/inputs/full479-only16.canonical.exact.json`),goal=canonical.goals.find((g:any)=>g.id===ID),profile=read(`${P}/inputs/whole82ac-preserved-original-profile-plus-method-appendices.exact.json`),cfg=read(`${P}/../biologie-source7-four-protected-method-owner-material-author-v1/P5-method-material.author-candidate.v2.config.json`),criteria=sha(readFileSync(resolve(R,cfg.reviewCriteriaPath))),url=goal.resourceLinks.find((r:any)=>r.type==='goal-visualization').url,resources={[url]:sha(readFileSync(resolve(R,`app/public${url}`)))}
assert.equal(profile.goalFingerprint,fingerprintGoalForPositiveEvidence(goal,'curricularAtomic'));assert.equal(profile.reviewInputFingerprint,fingerprintPositiveGoalEvidenceReviewInput(goal,criteria,resources,'curricularAtomic'));assert.equal(profile.profileFingerprint,fingerprintPositiveGoalEvidenceProfile(profile.profile));assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(profile,goal,resources,'curricularAtomic'),[])
const directory='curricula/DE/Gymnasium/composition-views/biologie',views=[],normal=normalizeCanonicalLandscape(canonical),gm=new Map<string,any>(canonical.goals.map((g:any)=>[g.id,g]))
for(const f of readdirSync(resolve(R,directory)))if(f.endsWith('.view.json')){const path=directory+'/'+f,raw=read(path);if(raw.scope?.stage!=='SekII')continue;const view=normalizeCompositionView(raw),findings=compileCompositionView(view,normal).findings,projection=collectCompositionProjectionRoleGoalIds(view.rootNodes,gm);assert.deepEqual(findings.filter((x:any)=>x.severity==='error'),[]);views.push({actualUnchangedInput:bind(path),scope:raw.scope,viewId:raw.viewId,targetGoalIds:[...projection.targetGoalIds],prerequisiteOnlyGoalIds:[...projection.prerequisiteOnlyGoalIds],contains82acTarget:projection.targetGoalIds.has(ID),normalFindings:findings,noViewOrCanonicalChange:true})}
writeFileSync(resolve(D,'checks/unchanged-whole-P82-and-all-current-upper-view-inputs.actual.json'),JSON.stringify({schemaVersion:1,actualUnchangedP82:{wholeRecord:bind(`${P}/inputs/whole82ac-preserved-original-profile-plus-method-appendices.exact.json`),goalFingerprint:profile.goalFingerprint,reviewInputFingerprint:profile.reviewInputFingerprint,profileFingerprint:profile.profileFingerprint,wholeApplicationCaseCount:profile.profile.applicationCaseBriefs.length,normalSemanticErrors:[],criteria:bind(cfg.reviewCriteriaPath),actualResourceFingerprints:resources,sourceRouteOnlyChangeDoesNotAlterTheseInputs:true,status:profile.status,reviewAuthority:profile.reviewAuthority,evidenceLevel:profile.evidenceLevel,maximumClaimScope:profile.maximumClaimScope,newPApproval:false},allActualCurrentUpperLearnerViews:views,currentUpperViewChanges:0,activeWrites:0,strictGain:0,humanApproval:false},null,2)+'\n')
console.log(JSON.stringify({actualP82GoalInputProfileFingerprintsUnchanged:true,actualWholeP82Cases:profile.profile.applicationCaseBriefs.length,allCurrentUpperViewsCompiled:views.length,unchangedUpper82acTargetViews:views.filter(x=>x.contains82acTarget).length,newApproval:false}))
