# SPDX-License-Identifier: Apache-2.0
"""Final portable bounded author freeze; no independent or global stage approval."""
from pathlib import Path
import json,hashlib,datetime,subprocess,importlib.util
import jsonschema
R=Path.cwd();D=Path(__file__).resolve().parent;P=D.relative_to(R).as_posix();ID='82acfbde-9ce8-5658-892e-4dcfb1c3a1f1'
def read(n):return json.loads((D/n).read_text())
def bind(f):
 if isinstance(f,str):f=D/f
 b=f.read_bytes();return {'path':f.relative_to(R).as_posix(),'sha256':'sha256:'+hashlib.sha256(b).hexdigest(),'bytes':len(b)}
def put(n,x):
 f=D/n;assert not f.exists(),f;f.parent.mkdir(parents=True,exist_ok=True);f.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');return f
for n in ['checks/normal-compiler-whole394-stage-route.terminal.actual.json','checks/normal-one-native82ac.terminal.actual.json']:assert read(n)['actualExitCode']==0
assert read('native/whole394-actual-source-scope-and-native-page.diff.json')['actualChangedPageIds']==[ID]
parse=[];schemas=[]
for f in sorted(D.rglob('*')):
 if f.is_file() and f.suffix=='.json':json.loads(f.read_text());parse.append(bind(f))
 if f.is_file() and f.suffix=='.jsonl':
  for l in f.read_text().splitlines():
   if l.strip():json.loads(l)
  parse.append(bind(f))
for n,s in [('inputs/full479-only16.canonical.exact.json','docs/landscape-runtime.schema.json'),('inputs/full394-only16.semantic-kinds.exact.json','contracts/curriculum-package/v1/curriculum-ontology-profile.schema.json'),('inputs/whole82ac-preserved-original-profile-plus-method-appendices.exact.json','contracts/goal-evidence/v2/goal-evidence-profile.schema.json')]:
 jsonschema.validate(read(n),json.loads((R/s).read_text()));schemas.append({'input':bind(n),'existingContract':bind(R/s)})
spec=importlib.util.spec_from_file_location('ordinaryguard',R/'scripts/validate_schemas.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);symlinks=m.curriculum_symlink_errors(R);assert not symlinks,symlinks
ignored=[]
for f in D.rglob('*'):
 if f.is_file() and subprocess.run(['git','check-ignore','--quiet',str(f)],cwd=R).returncode==0:ignored.append(f.relative_to(R).as_posix())
assert not ignored,ignored
index=[]
for n in ['primary/SN-official-whole-current.original.pdf','primary/ST-official-whole-current.original.pdf','native/actual82ac/book.html','native/actual82ac/book.pdf']:
 f=D/n;b=subprocess.run(['git','show',':'+f.relative_to(R).as_posix()],capture_output=True,check=True).stdout;assert b==f.read_bytes();index.append(bind(f))
put('checks/whole-targeted-json-schema-index-and-portability.actual.json',{'schemaVersion':1,'allActualParsedJSONJSONL':parse,'existingClosedContractsPassed':schemas,'ordinaryCurriculumSymlinkErrors':symlinks,'ignoredUncommittableOwnedInputs':ignored,'exactIndexedOriginals':index,'sourceViewsValidatedByNormalCompilerAndSourceAtlas':True,'independentApproval':False,'humanApproval':False})
normal=read('checks/completed-normal-full394-source-atlas-and-stage-route.actual.json');aft=normal['ordinaryAtlasRuns'][1];views=read('checks/four-actual-ordinary-learner-compiler-projections.actual.json')['views'];capture='native/actual82ac/qa-captures/82ac-whole-actual-pdf-physical003.png'
limits={'schemaVersion':1,'scope':'Inactive SN/ST only; no global82ac stage approval','originalActiveRepositoryViewsAndMappingsStillUnchanged':True,'candidateSNST82acSekITargetRemoved':True,'wholeOriginalDutiesAndMethod5MaterialsPreserved':True,'new26aaSTSJ10MappingEdgeAdded':False,'unchangedOtherSekI82acCatalogWitnesses':[{'key':s['key'],'whole82acWitnesses':s['whole82acWitnesses']} for s in aft['scopeRoles'] if '/SekI/' in s['key'] and s['contains82ac']],'stillExistingHigherStageDependentTargetsInSNSTOutside82acFix':[{'state':v['state'],'variant':'proposed-current-view' if v['variant']=='active' else 'proposed-source7-successor-view','wholeTargets':v['stillExistingHigherStageDependentTargetsOutside82acFix']} for v in views],'remaining32xPrerequisiteOnlyRoleInvented':False,'nextWork':'Separate larger primary-operator review of nine other lower-stage source routes and328fd SN/ST; tags alone establish no source conclusion. No changes to these regions in this narrow package.','source7WholeProgrammeClosed':False,'whole82acApplicabilityScientificallyClosed':False,'humanApproval':False}
put('candidate/actual-unmodified-boundaries-and-remaining-stage-source-witnesses.json',limits)
put('native/actual82ac/qa-captures/actual-capture-and-author-visual-inspection.receipt.json',{'schemaVersion':1,'actualSourcePDF':bind('native/actual82ac/book.pdf'),'physicalPage':3,'capture':bind(capture),'actualCaptureCommand':['pdftoppm','-f','3','-l','3','-r','120','-singlefile','-png',P+'/native/actual82ac/book.pdf',P+'/native/actual82ac/qa-captures/82ac-whole-actual-pdf-physical003'],'actualAuthorViewedCapture':True,'authorObservation':'Whole original image and entire unchanged goal description visible. Native applicability changes concern the SN/ST lower-stage catalog witnesses. Other unchanged lower-stage labels remain visible and are separately open; no global stage clearance claimed.','nativeIndependentApproval':False,'humanApproval':False})
neutral=['inputs/full479-only16.canonical.exact.json','inputs/full394-only16.semantic-kinds.exact.json','inputs/full394-only16.visualization-qa.exact.json','inputs/full394-only16.normal-book.config.exact.json','inputs/full394-only16.normal-source-atlas.config.exact.json','inputs/full394-only16.normal-model.exact.json','inputs/whole35-duty30-partner-frame.exact.json','inputs/current-whole82ac-and26aa-goals.exact.json','inputs/SN-whole-lower-source7.mapping.exact.json','inputs/ST-whole-lower-source7.mapping.exact.json','inputs/SN-whole-lower-source7.extraction.exact.json','inputs/ST-whole-lower-source7.extraction.exact.json','candidate/mappings/SN-whole-lower-source7.without82ac-SekI-target.review.json','candidate/mappings/ST-whole-lower-source7.without82ac-SekI-target.review.json','candidate/exact-SN-ST-mapping-and-four-learner-view.scope-diffs.json','candidate/full394-source-atlas.without82ac-SN-ST-SekI-target.inputs.json','candidate/full394-book.without82ac-SN-ST-SekI-target.config.json','inputs/whole82ac-preserved-original-profile-plus-method-appendices.exact.json','inputs/five-whole-method-material-cases.exact-retained.json','native/full394-before.normal-model.actual.json','native/full394-after82ac-route.normal-model.actual.json','native/whole394-actual-source-scope-and-native-page.diff.json','native/actual82ac/book-model.json','native/actual82ac/book.html','native/actual82ac/book.pdf',capture,'native/actual82ac/bundle/review-bundle-manifest.json','native/actual82ac/round-a/description-review-input.json','native/actual82ac/round-a/description-review-campaign.json','native/actual82ac/round-b/description-review-input.json','native/actual82ac/round-b/description-review-campaign.json','candidate/actual-unmodified-boundaries-and-remaining-stage-source-witnesses.json']
neutral += [f.relative_to(D).as_posix() for f in sorted((D/'primary').rglob('*')) if f.is_file()]
neutral += [f.relative_to(D).as_posix() for f in sorted((D/'inputs/views').glob('*.json'))]
neutral += [f.relative_to(D).as_posix() for f in sorted((D/'candidate/views').glob('*.json'))]
# Bind whole normal source inputs at actual portable archives; planned book-local names belong only to the generating capsule.
sourceviews=[]
for stage in ['before','after']:
 prefix=f'source-atlas/{stage}-normal-exact-output-archive/app/scripts/config/goal-books/inactive/biologie-evolution-native17-current394-v1/'
 for state in ['SN','ST']:
  n=prefix+f'source-views/de-gym-biologie-bundesweit-source-de-{state.lower()}-seki.view.json';neutral.append(n);sourceviews.append({'state':state,'variant':'whole-normal-baseline-book-source' if stage=='before' else 'proposed-normal-book-source','wholeView':bind(n)})
 neutral.append(prefix+'atlas.sources.json')
entry={'schemaVersion':1,'createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'role':'Neutral additive inactive82ac SN/ST lower-stage source/learner/native successor for targeted independent review','FIRSTRule':'Read whole original/candidate mappings, actual original primary clauses, four inactive learner-view successors, two proposed normal book-source views and exact whole native82ac page before own science-FIRST. Original B own finding may be known. No author technical check or peer findings become a scientific verdict. Then inspect actual normal rendered HTML/PDF and normal campaign/P-binding terminals. No blind-to-own-history claim.','neutralWholeInputs':[bind(n) for n in dict.fromkeys(neutral)],'actualSourceBookViews':sourceviews,'learnerVariants':{'activeNamedInputCopiesAreOnlyBaselines':True,'SN-ST-activeNamedCandidateVariants':'proposed-current-view successors, not actual active writes','SN-ST-source7NamedCandidateVariants':'proposed-source7-successor views, not existing frozen historical source7 edits'},'actualChangedWholeNativePageIds':[ID],'whole394BeforeAfterPages':394,'whole479GoalBodiesAnd394KindsUnchanged':True,'allOther393NativePagesIncluding2ae2Exact':True,'normalSourceScopeDelta':{'removedTargetsOnly':{'DE-SN/SekI/':[ID],'DE-ST/SekI/':[ID]},'addedTargets':[],'SekIITargetChanges':0},'actualNativeBundle':bind('native/actual82ac/bundle/review-bundle-manifest.json'),'actualNativeRenderedOriginalHTML':bind('native/actual82ac/book.html'),'actualNativeRenderedOriginalPDF':bind('native/actual82ac/book.pdf'),'actualPageMap':[{'goalId':ID,'goalPage':1,'physicalPDFPage':3}],'afterOwnFIRSTOnly':[bind(n) for n in ['author.input-FIRST.actual-source-reading-and-route-finding.json','checks/completed-normal-full394-source-atlas-and-stage-route.actual.json','checks/four-actual-ordinary-learner-compiler-projections.actual.json','checks/unchanged-whole-P82-and-all-current-upper-view-inputs.actual.json','checks/normal-compiler-whole394-stage-route.terminal.actual.json','checks/normal-one-native82ac.terminal.actual.json','checks/whole-targeted-json-schema-index-and-portability.actual.json','native/actual82ac/normal-render-bundle-and-two-independent-campaigns.actual.json']],'openLimits':limits,'unchangedP82Status':'Existing whole five-case profile/current goal-image/criteria fingerprints exact; ai_candidate needs_human_review E1/G1. No new P scientific approval.','proposedCurrentIsNotActiveState':True,'humanApproval':False,'humanTrial':False,'wholeSourceApproval':False,'whole82acStageApproval':False,'independentResults':0,'currentStrict299ActiveUntouched':True,'newScientificClosures':0,'restoredBindings':0,'strictGain':0,'activeWrites':0,'finalSealPath':P+'/author.final.freeze.json'}
e=put('neutral-whole82ac-SN-ST-SekI-source-view-native.author-successor.independent-review.entry.json',entry)
files=[f for f in sorted(D.rglob('*')) if f.is_file()]
s=put('author.final.freeze.json',{'schemaVersion':1,'sealedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'role':'Final exact narrow inactive author package; independent source/native checks pending','neutralEntry':bind(e),'allWholeOperativeAndDiagnosticBindings':[bind(f) for f in files],'historicalArtifactMutations':0,'activeWrites':0,'strictGain':0,'humanApproval':False})
print(json.dumps({'entry':bind(e),'seal':bind(s),'allExactFiles':len(files),'actualChangedPages':[ID],'remainingOtherLowerScopes':len(limits['unchangedOtherSekI82acCatalogWitnesses']),'independentApproval':False}))
