import json,hashlib,datetime
from pathlib import Path
BASE=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-05/chemie-b014-five-prospective-book-current-v1')
OUT=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-05/chemie-b014-five-current-independent-d-b-v1')
ROUND=BASE/'native-finalbook/round-b'
CAM=json.loads((ROUND/'description-review-campaign.json').read_text())
BUNDLE=json.loads((BASE/'native-finalbook/bundle/manifest.json').read_text())
BATCH=CAM['batches'][0]
ROWS=[json.loads(l) for l in (ROUND/'batches'/f"{BATCH['batchId']}.input.jsonl").read_text().splitlines()]
RUN='chemie-b014-five-current-independent-d-b-20261005-v1'
SPECS=[
{
 'decision':'keep',
 'ue':[
 'Bei einer Redoxreaktion gibt ein Elektronendonator Elektronen ab und wird oxidiert; der Elektronenakzeptor nimmt sie auf und wird reduziert. Das Reduktionsmittel ist daher selbst der oxidierte Partner, das Oxidationsmittel der reduzierte Partner. Beide Vorgänge gehören zu derselben Elektronenübertragung; Sauerstoff ist dafür nicht erforderlich.',
 'In a redox reaction an electron donor loses electrons and is oxidized, while the electron acceptor gains electrons and is reduced. The reducing agent is therefore the partner that is oxidized, and the oxidizing agent the partner that is reduced. Both processes belong to the same electron transfer; oxygen is not required.',
 'Die lernende Person erklärt an unabhängig bereitgestellten Stoff- oder Teilchenangaben, welcher Partner Elektronen abgibt beziehungsweise aufnimmt, ordnet Oxidation, Reduktion und beide Mittel begründet zu und verbindet diese Zuordnungen zu einem Donator-Akzeptor-Zusammenhang. Sie erklärt dabei die oft verwechselte Beziehung zwischen dem Namen eines Mittels und seiner eigenen Veränderung.',
 'Using independently supplied substance or particle information, the learner explains which partner loses or gains electrons, justifies the oxidation, reduction and agent assignments, and connects them through the donor-acceptor relationship. They explain the frequently confused relationship between an agent name and the change that the agent itself undergoes.',
 'In einer neuen, nicht aus dem Zink-Kupfer-Bild kopierten Metall-Metallionen-Reaktion, etwa Eisen mit Silberionen bei angegebenen Produkten, bestimmt die lernende Person die Rollen erneut aus der Elektronenabgabe und -aufnahme. Sie erklärt, weshalb das Fehlen von Sauerstoff die Redoxdeutung nicht verhindert; eine selbstständige Gesamtgleichungs-Bilanzierung gehört nicht zusätzlich zu diesem Begriffslernziel.',
 'In a fresh metal-metal-ion reaction that is not copied from the zinc-copper image, such as iron with silver ions with products supplied, the learner determines the roles from electron loss and gain. They explain why the absence of oxygen does not prevent a redox interpretation; independent balancing of an overall equation is not an additional requirement of this terminology goal.'
 ],
 'rationale':'KEEP: DE und EN benennen dieselbe zusammenhängende Elektronenübertragungs-Kompetenz; Definitionen und Mittelzuordnung sind deren Beziehungen, keine unabhängigen Routinen. Die erhaltene amtliche HE-KC2024-Fassung S.35 und die selbst abgerufene Live-Fassung S.33 führen in E.1 den erweiterten Redoxbegriff und die vier Begriffe; die selbst geprüfte BY9.6-Stelle trägt das Donator-Akzeptor-Konzept. Orientierung als Vorbedingung sowie die nachfolgende Redoxreihe erweitern dieses Ziel nicht zur Spannungsrechnung oder Gleichungsbilanzierung. PDF-Seite3 und HTML enthalten denselben vollständigen Text; das Bild unterstützt die Rollen, beweist keine unabhängige Leistung. Die allgemeine Bild-alt-Zeile ersetzt keine Bildprüfung. Ein eigener V2-Profilvorschlag ist im Batch nicht enthalten. Dies ist ein AI-Kandidat, keine menschliche Freigabe oder vollständige Prüfung aller Bundesland-Mappings.'
},
{
 'decision':'keep',
 'ue':[
 'Metallabscheidungen aus Metallsalzlösungen zeigen, welches Metall unter den untersuchten Bedingungen leichter Elektronen abgibt als ein anderes; Messungen einfacher galvanischer Zellen ergänzen diese relative Ordnung. Ein Redoxpaar besteht aus einem Metall und seinem zugehörigen Ion; Donator- und Akzeptorrollen in einer konkreten Reaktion sind aus der Elektronenübertragung zu begründen.',
 'Metal deposition from metal-salt solutions shows which metal loses electrons more readily than another under the investigated conditions; measurements of simple galvanic cells supplement this relative ordering. A redox pair consists of a metal and its corresponding ion; donor and acceptor roles in an individual reaction must follow from the electron transfer.',
 'Aus unabhängigen Abscheidungsbeobachtungen und bereitgestellten Messdaten einfacher Zellen unter vergleichbaren Bedingungen erstellt die lernende Person eine konsistente verkürzte Metallreihe, erläutert mindestens eine Ordnungsbeziehung und kennzeichnet die zugehörigen Metall-Ion-Paare und reagierenden Donator-/Akzeptorrollen. Sie unterscheidet dabei Beobachtung und Teilchendeutung; das Konstruieren eines kompletten galvanischen Aufbaus und Standardpotenzial-Berechnungen sind keine zusätzliche Anforderung.',
 'From independent deposition observations and supplied measurement data for simple cells under comparable conditions, the learner constructs a consistent shortened metal series, explains at least one ordering relation and identifies the associated metal-ion pairs and reacting donor/acceptor roles. They distinguish observation from particle interpretation; constructing a complete galvanic apparatus and calculating standard potentials are not additional requirements.',
 'In einem frischen Datensatz wird ein weiteres Metall durch neue Abscheidungs- und Polaritätsbefunde eingeordnet. Die lernende Person begründet seine Position oder eine durch fehlende Daten offenbleibende Teilordnung und sagt eine zusätzliche mögliche Metallabscheidung aus der hergeleiteten Ordnung voraus. Damit ändert sich die chemische Vergleichsstruktur, nicht lediglich ein Zahlenwert.',
 'In a fresh data set an additional metal must be placed using new deposition and polarity findings. The learner justifies its position or a partial order left unresolved by missing data, and predicts another possible deposition from the derived order. This changes the chemical comparison structure rather than merely a numerical value.'
 ],
 'rationale':'KEEP: Die Beschreibung fordert eine empirisch begründete kurze Reihe und die dazugehörigen Paare, eine einheitliche Ordnungs-Kompetenz. HE E.1 trägt Metallabscheidungen und Donator-/Akzeptor-Paare; BY9.6 trägt Reaktionsverhalten von Metallen in Metallsalzlösungen mit Teilchendeutung. Die ergänzenden einfachen Zellmessungen bleiben auf gegebene vergleichbare Daten beschränkt und werden nicht zur Nernst-Gleichung oder zum vorgängigen vollständigen Zellaufbau ausgeweitet. Die direkte Vorbedingung04fa liefert genau die benötigten Elektronenrollen; die eigenen Nachfolger f093 und8be behalten ihre weitergehenden Kompetenzen. PDF-Seite4 und HTML zeigen Metall/Ion-Unterscheidung, Zn>Cu>Ag und die korrekte Elektronenrichtung. Allein dieses vorgegebene Ergebnis ist kein Leistungsnachweis; unbekannte Daten und ein neu einzuordnendes Metall machen die Leistung unabhängig. Eigene Versuche verlangen beaufsichtigte sichere Bedingungen. Kein aktuelles V2-Profil ist supplied. AI-Kandidat; keine menschliche oder globale Quellenfreigabe.'
},
{
 'decision':'keep',
 'ue':[
 'Elektrolyse erzwingt durch elektrische Energie einen Redoxvorgang: Elektronen werden an der Kathode aufgenommen und an der Anode abgegeben; Ionen übernehmen den Ladungstransport im Elektrolyten. Elektrodenreaktionen bestimmen atom- und ladungserhaltend die Stoffmengenverhältnisse. Ob eine Schmelze oder eine wässrige Lösung vorliegt und welche Elektroden eingesetzt werden, gehört zu den Bedingungen der Produktdeutung.',
 'Electrolysis uses electrical energy to force a redox process: electrons are accepted at the cathode and released at the anode, while ions carry charge in the electrolyte. Electrode reactions determine product amount ratios while conserving atoms and charge. Whether the electrolyte is molten or aqueous and which electrodes are used are conditions of the product interpretation.',
 'Die lernende Person erklärt an unabhängig bereitgestellten Beobachtungen eines geeigneten Elektrolysebeispiels einschließlich wässriger Kupfer(II)-chloridlösung mit angegebenen Elektroden und Bedingungen Ionenwanderung und die beiden Elektrodenreaktionen. Für die unter diesen Bedingungen nachgewiesenen Produkte begründet sie das Stoffmengenverhältnis aus dem gemeinsamen Elektronenumsatz und vergleicht äußere Energiezufuhr und Reaktionsantrieb mit einem galvanischen Element. Beobachtung, Modell und Gleichung bleiben getrennt; Chlorversuche erfolgen nur als beaufsichtigte Demonstration oder mit bereitgestellten Daten.',
 'Using independently supplied observations of a suitable electrolysis example, including aqueous copper(II) chloride with specified electrodes and conditions, the learner explains ion migration and both electrode reactions. For the products established under those conditions, they justify the amount ratio from the common electron transfer and compare external energy input and reaction drive with a galvanic cell. Observation, model and equation remain distinct; chlorine experiments use supervised demonstrations or provided data.',
 'Nach einem Schmelzbeispiel wird als frische Aufgabe eine wässrige Kupfer(II)-chloridlösung mit geeigneten inerten Elektroden und beobachteten Produkten angeboten. Die lernende Person entwickelt die neue Elektroden- und Stoffmengenbeschreibung und erklärt, weshalb die Natriumchlorid-Schmelzgleichung nicht auf die wässrige Lösung übertragen werden darf. Quantitative Strom-Zeit-Ausbeuten, Überspannung und Gleichgewichtsrechnung werden nicht zusätzlich verlangt.',
 'After a molten-salt example, a fresh task provides aqueous copper(II) chloride with suitable inert electrodes and observed products. The learner develops the new electrode and amount description and explains why the molten sodium chloride equation cannot be transferred to the aqueous solution. Quantitative current-time yields, overpotential and equilibrium calculations are not added requirements.'
 ],
 'rationale':'KEEP: DE und EN verbinden die Elektrolyseerklärung mit ihrem Ladungs-/Stoffzusammenhang und dem notwendigen Vergleich zum bereits vorausgesetzten galvanischen Element. Das ist ein erklärbares zusammenhängendes Ziel; die eigenen Nachfolger bearbeiten Akkuvergleich und Anwendungen gesondert. HE E.1 nennt Elektrolyse an einem Beispiel, Q3.3 GK/LK nennt ausdrücklich Kupfer(II)-chloridlösung (erhaltene S.47, live S.45). PDF-Seite5 zeigt korrekt ausdrücklich eine NaCl-Schmelze mit Na(l)/Cl2(g), keine wässrige Natriumabscheidung; die alternative wässrige Kupferlösung bleibt im Text explizit. Die Bild-Alternative erfüllt allein die ganze Kompetenz nicht, wird aber nicht zum falschen Beleg für die wässrige Lösung erklärt. Geeignete Bedingungen und beobachtete Produkte vermeiden eine universelle Anodenproduktbehauptung. Native Voraussetzungen70b undf093 begrenzen angenommene Vorkenntnisse. Kein supplied V2-Profil; AI-Kandidat, keine neue Human Approval oder pauschale HB-Live-Verifikation.'
},
{
 'decision':'keep',
 'ue':[
 'Eine geeignete wiederaufladbare elektrochemische Zelle gibt beim freiwilligen Entladen elektrische Energie ab; äußere elektrische Energie treibt beim Laden die dazugehörige chemische Rückreaktion an. Diese technisch nutzbare Umkehrbarkeit gilt für geeignete Zellen und Bedingungen, nicht für jede Batterie. Leer bezeichnet fehlende aktuelle Nutzbarkeit, nicht verschwundene Materie; geladen bezeichnet einen Zustand verfügbarer chemischer Energie.',
 'A suitable rechargeable electrochemical cell supplies electrical energy during spontaneous discharge; external electrical energy drives the associated chemical reverse reaction during charging. This technically useful reversibility applies to suitable cells and conditions, not to every battery. Empty describes a lack of current usability, not vanished matter; charged describes a state with available chemical energy.',
 'Die lernende Person vergleicht an einer unabhängig beschriebenen geeigneten wiederaufladbaren Zelle Entladen und Laden, erläutert die entgegengesetzte Richtung der chemischen Veränderung und der Energieübertragung und beurteilt Aussagen zu leeren Batterien und geladenen Akkus anhand dieses Zusammenhangs. Sie erklärt, weshalb ein Ladegerät erforderlich ist und weshalb aus dem Schema keine allgemeine Aufladbarkeit oder chemisches Gleichgewicht folgt.',
 'For an independently described suitable rechargeable cell, the learner compares discharge and charge, explains the opposite directions of chemical change and energy transfer, and assesses statements about empty batteries and charged rechargeable cells through this relationship. They explain why a charger is required and why the diagram does not establish universal rechargeability or chemical equilibrium.',
 'Eine frische Aufgabe stellt einen beschriebenen geeigneten Akku und eine ausdrücklich nicht zum Laden vorgesehene Primärzelle gegenüber oder bietet eine neue fehlerhafte Alltagsaussage zu leer/geladen an. Die lernende Person überträgt das Entlade-/Lademodell unter Beachtung der Eignungsgrenze und korrigiert die Aussage begründet, ohne Primärzellen praktisch aufladen zu wollen oder eine vollständige konkrete Akkumulatorchemie zusätzlich vorführen zu müssen.',
 'A fresh task contrasts a described suitable rechargeable cell with a primary cell explicitly not intended for charging, or supplies a new misleading everyday statement about empty/charged. The learner transfers the discharge/charge model while respecting its suitability limit and corrects the statement with reasons, without attempting to charge primary cells or additionally having to demonstrate a complete specific accumulator chemistry.'
 ],
 'rationale':'KEEP: Die explizite Einschränkung auf eine geeignete reversibel arbeitende Zelle löst die fachliche Allgemeinheitsfrage. Laden/Entladen und die Alltagsformulierungen sind dieselbe Energie-/Reaktionskompetenz, keine allgemeine Quellen- oder Nachhaltigkeitsbewertung des Nachfolgers16b. Die selbst abgerufene amtliche BY9/ch-Seite, Lernbereich6, enthält genau freiwillig/erzwungen, Reversibilität und leer/geladen; einfache qualitative Deutung ist daher der passende jüngste belegte Anspruch. PDF-Seite6 und HTML zeigen zwei Zustände, Energiepfeile und korrekt angeschlossene Ladeleitungen mit den ausdrücklich sichtbaren Begrenzungen. Ein Zustandsschema ohne konkrete Zellchemie ist keine behauptete Gleichgewichtsabbildung. Die direkten Grundlagenfd797/f093 bleiben erhalten. Eine eigenständige Erklärung und ein neuer Primärzellenvergleich machen die Leistung beobachtbar. Kein supplied V2-Profil; AI-Kandidat und kein Human-/Release-Siegel.'
},
{
 'decision':'keep',
 'ue':[
 'Eine bekannte Maßlösung bestimmt über den verbrauchten Volumenunterschied und die Reaktionsstöchiometrie die Stoffmenge des Analyten in einem bekannten Probenvolumen. Der Indikatorendpunkt ist ein beobachteter Farbumschlag, der zum stöchiometrischen Äquivalenzbereich passen muss; beide sind begrifflich verschieden. Fachgerechte Planung, sichere Durchführung und dokumentierte Anfangs-/Endablesungen bilden eine zusammenhängende quantitative Bestimmung.',
 'A standard solution of known concentration determines the analyte amount in a known sample volume through the delivered volume difference and reaction stoichiometry. The indicator endpoint is an observed colour change that must suit the stoichiometric equivalence region; the two concepts are distinct. Correct planning, safe execution and documented initial/final readings form one coherent quantitative determination.',
 'Für eine einfache geeignete Säure-Base-Probe, insbesondere HCl(aq)/NaOH(aq), begründet die lernende Person Maßlösung und Indikator, plant Probenvolumen und sichere Arbeitsschritte, führt die Titration im beaufsichtigten geeigneten Labor fachgerecht durch und dokumentiert die Ablesungen. Aus verbrauchtem Maßlösungsvolumen, bekannter Konzentration, Probenvolumen und Reaktionsverhältnis leitet sie die Probenkonzentration her und erläutert die Bedeutung des Farbumschlags. Ein reiner Datensatz kann Rechnung und Planung, allein aber keine tatsächlich beobachtete Durchführung belegen.',
 'For a simple suitable acid-base sample, particularly HCl(aq)/NaOH(aq), the learner justifies the standard solution and indicator, plans sample volume and safe steps, carries out the titration correctly in a suitable supervised laboratory, and records the readings. They derive the sample concentration from delivered titrant volume, known concentration, sample volume and reaction ratio, and explain the colour change. A data-only task can evidence calculation and planning, but cannot by itself establish observed practical execution.',
 'Bei einer frischen einfachen Titration wird die saure Probe durch eine basische Probe ersetzt oder es werden eine vorher verdünnte Probe und vollständige Messdaten gegeben. Die lernende Person passt Maßlösung, Farbumschlag-Richtung und gegebenenfalls Verdünnungsbezug begründet an und berechnet die Konzentration aus dem neuen Versuchsplan. Komplexe Titrationskurven, Halbäquivalenzpunkte oder die Behauptung eines universellen Äquivalenz-pH7 werden nicht hinzugefügt.',
 'In a fresh simple titration the acidic sample is replaced by a basic one, or a previously diluted sample and complete measurement data are supplied. The learner justifies the adjusted standard solution, direction of colour change and, where applicable, dilution reference, and calculates concentration from the new experimental plan. Complex titration curves, half-equivalence points and a universal equivalence-pH7 claim are not added.'
 ],
 'rationale':'KEEP: Planen, tatsächliches Durchführen, Dokumentieren und stöchiometrische Konzentrationsbestimmung gehören hier zum selben analytischen Versuchsziel. HE E.2 nennt HCl/NaOH, Umschlagspunkt und Konzentration (erhaltene S.35, live S.33); BY13 GA/EA Lernbereich3 nennt Planen/Durchführen/Dokumentieren starker Säuren/Basen, während BY10 bereits einfache Titrationen trägt. Die Beschreibung bleibt dafür auf eine geeignete einfache Bestimmung ausgerichtet und verlangt keine komplette Kurvenanalyse. Die selbst betrachtete PDF-Seite7 und HTML zeigen den passend beschrifteten Aufbau und einen zarten Endpunkt, nicht eine universelle pH7-Regel. f1ed bleibt die direkte Rechen-/pH-Grundlage. Die Fachgerechtigkeit verlangt proportionales Laborsicherheitswissen; bereitgestellte Messdaten ersetzen die ausdrücklich claimed Durchführung nicht. HB-Live-URL404 bleibt eine Quellenverifikationsgrenze und wird nicht als vollständiger HB-Quellennachweis ausgegeben. Kein supplied V2-Profil; AI-Kandidat ohne menschliche Freigabe.'
},
{
 'decision':'keep',
 'ue':[
 'Die unveränderte Sek-I-Beschreibung betrifft die fachliche Deutung einfacher Oxidations- und Reduktionsvorgänge bei Metallen und Nichtmetallen. Ein direkter Nachfolger im Buch ist Kontext, keine zusätzliche Teilkompetenz; das Entfernen seiner Rückreferenz verändert weder diese eigene Kompetenz noch ihre Vorbedingung oder das eigene Bild.',
 'The unchanged lower-secondary description concerns interpreting simple oxidation and reduction processes involving metals and non-metals. A direct successor in the book is context, not an additional subcompetence; removing its reverse reference changes neither this goal competence nor its prerequisite or its own image.',
 'Für die hier ausschließlich geprüfte Seitenbindung bleiben die eigenständige Deutung einer einfachen Metall-/Nichtmetallreaktion und die Unterscheidung des Vorgangs auf Stoff- und Teilchenebene unverändert. Der Leser findet weiterhin das vorausgesetzte Unterscheiden chemischer und physikalischer Vorgänge und den verbleibenden Nachfolger22133; eine Rückreferenz auf16da ist nach dessen geändertem direktem requires-Feld sachlich nicht mehr angezeigt.',
 'For the page binding reviewed exclusively here, independent interpretation of a simple metal/non-metal reaction and distinction between substance and particle descriptions remain unchanged. The reader still finds the prerequisite distinguishing chemical from physical processes and the remaining successor22133; a reverse reference to16da is no longer appropriate after that goal direct requires field changes.',
 'Die bereits bestehende Übertragung auf eine andere einfache Metall-/Nichtmetallreaktion bleibt inhaltlich bestehen; diese gezielte Prüfung fügt keine neue Aufgabenquote oder Elektronenbilanzierungsanforderung hinzu. Für den Kontextvergleich lässt sich der verbleibende Nachfolger22133 weiter nachvollziehen, während16da aus seinen eigenen Redoxbegriffs-Vorkenntnissen04fa erreichbar bleibt.',
 'The existing transfer to another simple metal/non-metal reaction remains substantively unchanged; this targeted check adds no new task quota or electron-balancing demand. In the context comparison the remaining successor22133 can still be followed, while16da remains reachable through its own redox-terminology prerequisite04fa.'
 ],
 'rationale':'TARGETED KEEP ausschließlich für die neue Seitenbindung: Die bereitgestellten tatsächlichen Vorher-/Nachher-Objekte wurden selbst strukturell verglichen: ganzes Zielobjekt, canonicalContext, Bild/alt/Digest, eigene requires und Provenienz sind gleich. Im ursprünglichen Buchumfang ändern sich nur externalReverseRequires und pageFingerprint: die alte zusätzliche Referenz16da entfällt;22133 bleibt unverändert. Die neue sechsseitige Ausgabe ändert zusätzlich die lokale Seitenposition auf6, hält aber sämtliche fachlichen Seitenfelder außer der entfernten Rückreferenz identisch. Im exakten Zukunftsgraph fordert16da nun04fa, das die benötigten Elektronendonator-/akzeptor-Begriffe trägt; dieses Feld liefert die direkte Berechtigung der neuen Rückreferenzanzeige. PDF-Seite8 und HTML stellen das aktuelle Umfeld korrekt dar. Die sechs Evidence-Felder sind ein begrenzter Kontextbefund und keine erneute historische fachliche Freigabe, kein Ersatz der unveränderten strikten Autorität und keine neue P-Behauptung. Das supplied Batchprofil ist null, daher formale create-Empfehlung ohne autorisierte Profiländerung. AI-Kandidat; keine Human Approval.'
}
]
KEYS=['essentialUnderstandingDe','essentialUnderstandingEn','observablePerformanceDe','observablePerformanceEn','transferExpectationDe','transferExpectationEn']
records=[]
for r,s in zip(ROWS,SPECS):
 g=r['goal'];item={
 '$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json','schemaVersion':1,'recordId':RUN+'-'+g['goalId'],'runId':RUN,'campaignId':CAM['campaignId'],'roundId':CAM['roundId'],'bundleFingerprint':r['bundleFingerprint'],'bookDigest':r['bookDigest']}
 for k in ['goalId','goalFingerprint','pageFingerprint','currentTitleDe','currentTitleEn','currentDescriptionDe','currentDescriptionEn']:item[k]=g[k]
 item.update({'decision':s['decision'],'understandingEvidence':dict(zip(KEYS,s['ue'])),'rationale':s['rationale'],'evidenceProfileContract':'positive-understanding-evidence-v2','evidenceProfileRecommendation':'create','recordStatus':'candidate','reviewAuthority':'ai_candidate'})
 records.append(item)
res=ROUND/'results';res.mkdir(exist_ok=True)
recordPath=res/f"{BATCH['batchId']}.records.jsonl"
recordPath.write_text(''.join(json.dumps(r,ensure_ascii=False,separators=(',',':'))+'\n' for r in records))
sha=lambda p:'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest()
params={'provider':'OpenAI','model':'GPT-6','agent':'/root/chem_five_final_d_b','mode':'independent blind review of frozen native inputs','samplingSettings':'not exposed','humanApproval':False}
(OUT/'actual-generation-parameters.json').write_text(json.dumps(params,ensure_ascii=False,indent=2)+'\n')
artroles={'book_model','book_pdf','book_pdf_render_manifest','book_html','book_html_render_manifest','review_input_jsonl','review_prompt','review_criteria','run_manifest_schema'}
run={'$schema':'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json','schemaVersion':1,'runId':RUN,'campaignId':CAM['campaignId'],'roundId':CAM['roundId'],'batchId':BATCH['batchId'],'batchInputFingerprint':BATCH['batchInputFingerprint'],'bundleFingerprint':CAM['bundleFingerprint'],'bookDigest':CAM['bookDigest'],'provider':'OpenAI','model':'GPT-6','role':'subject_reviewer','promptFamilyId':'skillpilot-goal-description-understanding-evidence-review-v2','promptFingerprint':CAM['promptFingerprint'],'criteriaFingerprint':CAM['criteriaFingerprint'],'generationParametersFingerprint':sha(OUT/'actual-generation-parameters.json'),'independenceGroupId':CAM['independenceGroupId'],'blindToOtherRuns':True,'goalIds':BATCH['goalIds'],'inputArtifacts':[{'role':a['role'],'digest':a['digest']} for a in BUNDLE['artifacts'] if a['role'] in artroles]+[{'role':'description_review_batch_input_jsonl','digest':BATCH['batchInputFingerprint']}],'startedAt':datetime.datetime.fromtimestamp((OUT/'freeze-before.receipt.json').stat().st_mtime,datetime.timezone.utc).isoformat(),'completedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'completed','outputDigest':sha(recordPath),'toolchainVersion':'native-goal-description-review-campaign-v2'}
runPath=res/f"{BATCH['batchId']}.run.json";runPath.write_text(json.dumps(run,ensure_ascii=False,indent=2)+'\n')
(OUT/'description-records.jsonl').write_bytes(recordPath.read_bytes());(OUT/'description-run.json').write_bytes(runPath.read_bytes())
verdict={'status':'INDEPENDENT_D_B_CANDIDATES_WRITTEN_PENDING_NATIVE_VALIDATION','authority':'ai_candidate','needsHumanReview':True,'humanApproval':False,'scienceClaimsScope':'five new description judgments plus one existing goal targeted page binding only','blindToOtherDAndPReviews':True,'decisions':[{'goalId':r['goalId'],'decision':r['decision'],'scope':'targeted_page_binding_only' if i==5 else 'current_description'} for i,r in enumerate(records)],'bookDigest':CAM['bookDigest'],'bundleFingerprint':CAM['bundleFingerprint'],'recordsSHA256':sha(recordPath),'runSHA256':sha(runPath),'sources':{'heRetainedSHA256':sha(Path('curricula/DE/Gymnasium/input/HE/upper-secondary/kerncurriculum_gymnasiale_oberstufe-chemie.pdf')),'heLiveSHA256':sha(OUT/'sources/he-live.pdf'),'heVersionTruth':'different retained/live bytes and pagination; E.1/E.2 relevant claims agree, Q3.3 electrolysis claim agrees; no byte identity asserted','hbRetainedSHA256':sha(Path('curricula/DE/Gymnasium/input/HB/GyO_Chemie_2022.pdf')),'hbLiveStatus':404,'hbLimitation':'retained official E and Q pages inspected; current live availability and all HB mapped clause coverage not certified','by9LiveURL':'https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/9/chemie/ch','by13LiveURLs':['https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/13/chemie/grundlegend','https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/13/chemie/erhoeht']},'actualRasterizer':'pdftoppm -f 3 -l 8 -r 110 -png','viewedPhysicalPDFPages':[3,4,5,6,7,8],'HTMLTextAltAndContextInspected':True,'scientificClosuresActual':0,'newStrictAuthorityClaims':0,'activeCanonQARuntimeRegistryLedgerWrites':0,'PInputsReadBeforeDCompletion':False}
(OUT/'independent-description-verdict.json').write_text(json.dumps(verdict,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'recordsPath':str(recordPath),'recordsSHA256':sha(recordPath),'runSHA256':sha(runPath),'decisions':[r['decision'] for r in records]},indent=2))
