import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validatePositiveGoalEvidenceRecordSemantics } from '/home/enpasos/projects/skillpilot/app/scripts/positiveGoalEvidenceProfileModel.ts';
const root = '/home/enpasos/projects/skillpilot';
const own = dirname(fileURLToPath(import.meta.url));
const bind = (p: string) => { const bytes = readFileSync(p); return { path: p.slice(root.length + 1), sha256: 'sha256:' + createHash('sha256').update(bytes).digest('hex'), bytes: bytes.length }; };
const cp = resolve(own, 'four-targeted-positive.independent-b.candidate-only.config.json');
const config = JSON.parse(readFileSync(cp, 'utf8'));
const lp = resolve(root, config.landscapePath);
const kp = resolve(root, config.semanticKindLedgerPath);
const rp = resolve(root, config.reviewPath);
const landscape = JSON.parse(readFileSync(lp, 'utf8'));
const kinds = JSON.parse(readFileSync(kp, 'utf8'));
const records = readFileSync(rp, 'utf8').trim().split('\n').map(l => JSON.parse(l));
const errors = records.flatMap(record => validatePositiveGoalEvidenceRecordSemantics(record, landscape.goals.find((g: any) => g.id === record.goalId), {}, kinds.decisions.find((d: any) => d.goalId === record.goalId)?.semanticKind));
const receipt = { schemaVersion: 1, role: 'Actual existing ordinary P semantic helper, candidate-only finite-material scope', helper: bind(resolve(root, 'app/scripts/positiveGoalEvidenceProfileModel.ts')), config: bind(cp), landscape: bind(lp), kinds: bind(kp), records: bind(rp), checkedGoalIds: records.map(r => r.goalId), errors, resourceDigestScope: {}, reviewedResourceTypes: config.reviewedResourceTypes, resourceGateReviewed: false, ordinaryNativeGateReviewed: false, humanApproval: false, strictGain: 0 };
writeFileSync(resolve(own, 'actual-existing-ordinary-P4-semantics.candidate-only.receipt.json'), JSON.stringify(receipt, null, 2) + '\n', {flag:'wx'});
console.log(JSON.stringify({checkedRecords:records.length, errors, scope:'candidate-only finite materials; no native/resource gate'}, null, 2));
if(errors.length) process.exitCode = 1;
