#!/usr/bin/env python3
"""Actual one-candidate routing; no operative installation or independent V."""
from pathlib import Path
import datetime,hashlib,json,subprocess
from PIL import Image
OUT=Path(__file__).resolve().parent;ROOT=OUT.parents[5]
prepared_path=OUT/'one-whole-goal-original-targeted-finding-native-prepared.author.raw.json';raw=json.loads(prepared_path.read_text())
def bind(p):
    d=p.read_bytes();return {'path':str(p.relative_to(ROOT)),'sha256':hashlib.sha256(d).hexdigest(),'bytes':len(d)}
canonical=ROOT/raw['frozenStage02Canonical']['path'];before=bind(canonical);asset=OUT/'original-generated-targeted-axon-leader-attempt-02.png';prompt=OUT/'ce19-targeted-axon-leader.attempt-02.actual.prompt.txt';gid=raw['wholeUnchangedStage02Goal']['id'];alt=raw['boundedImageAltTextDe']
args=['npm','--prefix','app','run','visualization:import','--',gid,str(asset),'--landscape='+raw['frozenStage02Canonical']['path'],'--subject=biologie','--lang=de','--provider=OpenAI / ChatGPT-Codex image generation','--review-status=pilot','--license=CC-BY-4.0','--prompt='+str(prompt),'--alt-text='+alt,'--description=Modellhafte Illustration: '+raw['wholeUnchangedStage02Goal']['title']+'.','--dry-run'];start=datetime.datetime.now(datetime.timezone.utc).isoformat();r=subprocess.run(args,cwd=ROOT,capture_output=True,text=True);finish=datetime.datetime.now(datetime.timezone.utc).isoformat();folder=OUT/'native-import-dry-run';folder.mkdir(exist_ok=True);stdout=folder/'actual.stdout.txt';stderr=folder/'actual.stderr.txt';stdout.write_text(r.stdout);stderr.write_text(r.stderr);assert r.returncode==0 and 'No files were written.' in r.stdout
routing={}
for line in r.stdout.splitlines():
    if ': ' in line and line.split(': ',1)[0] in ['Canonical image','Public image','Backend image','Canonical prompt','Canonical reconstruction prompt','JSON link URL']:
        key,value=line.split(': ',1);routing[key]=value
assert len(routing)==6 and bind(canonical)==before
historical=json.loads((ROOT/raw['historicalSevenFreeze']['path']).read_text())
for item in historical['ownFiles']:
    assert bind(ROOT/item['path'])==item
record={'goalId':gid,'role':'image author targeted current raster candidate; no independent V','wholeUnchangedStage02Goal':raw['wholeUnchangedStage02Goal'],'completeUnchangedDEENReferenceCases':raw['completeUnchangedDEENReferenceCases'],'actualFrozenSourceWitnessEffectiveBindings':raw['actualFrozenSourceWitnessEffectiveBindings'],'priorOriginal':raw['unchangedPriorOriginal'],'selectedUnchangedOriginalAsset':bind(asset),'actualPixelDimensions':list(Image.open(asset).size),'actualFinalGeneratorMetadata':bind(OUT/'builtin-targeted-second-edit.actual.metadata.json'),'actualFinalGenerationPrompt':bind(prompt),'actualProvider':'OpenAI / ChatGPT-Codex image generation','actualTool':'ChatGPT/Codex builtin image generation','actualModelVersion':None,'modelVersionDisclosure':'not exposed; unknown','license':'CC-BY-4.0','boundedImageAltTextDe':alt,'receivedTargetedFinding':raw['receivedTargetedFinding'],'ownAuthorActualSightNoteDe':'Der erste Edit blieb an der letzten Hüllgrenze mehrdeutig und wird nicht ausgewählt. Der zweite Leader endet deutlich links der ersten Myelinhülle am oberen violetten freiliegenden Axonhals. Original sowie tatsächliche 360/680-Bildbreiten gesehen; vier große Strukturbezeichnungen und übrige begrenzte Motive erhalten. Keine Behauptung pixelidentischer anderer Regionen bei generativem Edit.','ownAuthorSightFullSizeAndBothActualWidths':True,'actualDisplayWidths':[360,680],'actualDisplays':[bind(OUT/'author-displays'/('ce19.'+str(w)+'.png')) for w in [360,680]],'actualDisplayReceipt':bind(OUT/'author-displays/actual-360-680-display.receipt.json'),'actualGenerationHistory':[bind(OUT/'builtin-one-targeted-edit.actual.metadata.json'),bind(OUT/'builtin-targeted-second-edit.actual.metadata.json')],'firstAmbiguousAttemptPreserved':bind(OUT/'original-generated-targeted-axon-leader.png'),'nativePrepareBeforeBothEdits':True,'nativePrepareInputs':[bind(OUT/'native-prepare-before-edit/metadata.json'),bind(OUT/'native-prepare-before-second-edit/actual-prepare.receipt.json')],'nativeImportDryRun':{'argv':args,'startedAt':start,'finishedAt':finish,'exitCode':r.returncode,'stdout':bind(stdout),'stderr':bind(stderr),'routingProducedByUnmodifiedNativeImport':routing},'authorDisposition':'targeted_candidate_ready_for_two_independent_visual_reviews','independentVisualApproval':False,'humanApproval':False,'newStrictCompletion':0}
obj={'role':'one targeted label-anchor correction author input, no independent review or operative installation','nativePreparedWholeRaw':bind(prepared_path),'historicalSevenFreeze':raw['historicalSevenFreeze'],'historicalSevenOwnFilesActualExactCount':len(historical['ownFiles']),'sixOtherHistoricalImagesUnmodified':True,'frozenStage02Canonical':before,'actualBuiltinCalls':2,'nativePrepareExit0':2,'nativeImportDryRunExit0':1,'wholeGoalAndMaterialsUnmodified':True,'allSourceHoldsPreserved':True,'records':[record],'activeWrites':False,'runtimeWrites':False,'operativeInstallCopiesWritten':0,'nativeResourceLinksWereNotHandBuilt':True,'independentVisualApproval':False,'humanApproval':False,'newStrictCompletion':0}
(OUT/'one-whole-goal-source-material-current-raster-native-routing.author.raw.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'selectedCandidate':1,'nativePrepareExit0':2,'nativeImportDryRunExit0':1,'historicalSevenOwnFilesExact':len(historical['ownFiles']),'canonicalUnchanged':True,'strictCompletion':0}))
