"""Bounded, read-only Source-B input/delta reproduction; no science verdict inferred."""
import hashlib,json,pathlib,datetime
from bs4 import BeautifulSoup
REPO=pathlib.Path.cwd()
BASE=REPO/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-06'
AUTHOR=BASE/'biologie-neuro-eight-missing-primary-scope-remediation-author-v1'
OWN=BASE/'biologie-neuro-eight-primary-scope-independent-b-v1'
HIST=BASE/'biologie-neuro-th-hh-forty-reviewed-components-native-overlay-preparation-v1'
V3=BASE/'biologie-neuro-he-original-spelling-nw-two-source-components-author-v3'
def read(p): return json.loads(pathlib.Path(p).read_text())
def sha(p): return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def write(name,obj): (OWN/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def rel(p): return str(pathlib.Path(p).relative_to(REPO))
freeze=AUTHOR/'eight-missing-primary-scope-remediation-author-v1.final.freeze.json'
assert sha(freeze)=='cf1dfb10cb94e25620c501713f0de6b285e4c80a390bc8c3a94685a1262938e2'
frozen=[]
for row in read(freeze)['files']:
 p=AUTHOR/row['path'];actual=sha(p);assert actual==row['sha256'].removeprefix('sha256:');assert p.stat().st_size==row['bytes']
 frozen.append({'path':rel(p),'sha256':actual,'bytes':p.stat().st_size,'exactAtIndependentRead':True})
inputs=[]
for row in read(AUTHOR/'current-inputs-and-routing.initial.actual.receipt.json')['actualInputBindings']:
 p=REPO/row['path'];actual=sha(p);inputs.append({'path':row['path'],'authorInitialSha256':row['sha256'],'actualSha256':'sha256:'+actual,'sameAsAuthorInitial':actual==row['sha256'].removeprefix('sha256:')})
canonPath=REPO/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_BIOLOGIE.de.json'
current=read(canonPath);snapshot=read(AUTHOR/'current472-whole-canonical.actual.snapshot.json');candidate=read(AUTHOR/'current472-eight-only.canonical.author-v1.candidate.json')
assert current==snapshot
c={x['id']:x for x in current['goals']};n={x['id']:x for x in candidate['goals']};assert set(c)==set(n);assert len(c)==472
records=read(AUTHOR/'eight-current-goals.actual-primary-scope-and-DEEN-candidates.author-v1.json')['records'];ids={x['goalId'] for x in records};assert len(ids)==8
changed={k for k in c if c[k]!=n[k]};assert changed==ids
assert all(c[k].get('requires',[])==n[k].get('requires',[]) and c[k].get('contains',[])==n[k].get('contains',[]) for k in c)
assert {k:v for k,v in current.items() if k!='goals'}=={k:v for k,v in candidate.items() if k!='goals'}
for r in records: assert r['wholeCurrentGoalDEEN']==c[r['goalId']] and r['wholeCanonicalCandidateDEEN']==n[r['goalId']]
kinds=read(REPO/'curricula/DE/Gymnasium/quality/goal-book-publication/biologie.semantic-kinds.json')['decisions'];atomic={x['goalId'] for x in kinds if x['semanticKind']=='curricularAtomic'};assert len(atomic)==390 and ids<=atomic
central=read(REPO/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-06/chemie-current-fifteen-reviewed-active-integration-v1/current-central-five-gate.actual.report.json');bio=next(x for x in central['subjects'] if x['subject']=='biologie');protected=set(bio['strictCompleteGoalIds']);assert len(protected)==74 and not ids&protected;assert all(c[k]==n[k] for k in protected)
neighbor=read(AUTHOR/'preserved-source-obligations-overlap-and-review-worklist.json')['currentCanonicalNeighborsDEEN'];assert all(x==c[x['id']] for x in neighbor)
components=read(AUTHOR/'eight-bounded-components-and-declared-specialisations.source-candidates.author-v1.json')['sourceGoals'];assert len({x['id'] for x in components})==8 and {x['canonicalGoalId'] for x in components}==ids
mapping=read(AUTHOR/'eight-inactive-source-component-mapping-proposals.author-v1.json');assert mapping['mappings']==[] and len(mapping['decisions'])==8;assert all(x['decision']=='needs_canonical_goal' and not x['mappedTargetGoalIds'] and x['matchType']=='partial' for x in mapping['decisions'])
by=read(REPO/'curricula/DE/Gymnasium/input/BY/gymnasium/source-extraction/DE_BY_BIOLOGIE_GYMNASIUM_LEHRPLANPLUS.source-extraction.json');byids={x['id']:x for x in by['sourceGoals']};byChecks=[]
for r in read(AUTHOR/'BY13-EA-GA.exact-current-merged-source-IDs-and-original-occurrences.addendum.json')['records']:
 g=byids[r['existingExtractionSourceGoalId']];assert g['rawSourceText']==r['originalText'];assert g['sourceOccurrences']==r['existingExtractionOriginalOccurrences'];assert r['originalLevelMatchingOccurrence']
 byChecks.append({'recordId':r['recordId'],'mergedCurrentSourceGoalId':g['id'],'originalLevelLabel':r['originalLevelLabel'],'actualMatchingOccurrence':r['originalLevelMatchingOccurrence'],'actualSourceTextExact':True,'HTMLNumericSelectorRevisionRequired':True})
heActive=read(REPO/'curricula/DE/Gymnasium/input/HE/upper-secondary/source-extraction/DE_HE_BIOLOGIE_SEKII_KC2024.m7-ephase-seven-current365-20261005-v2.source-extraction.json');ha={x['id']:x for x in heActive['sourceGoals']};heCandidatePath=V3/'HE.LK7.exact-original-and-declared-normalization.author-v3.candidate.json';hc={x['id']:x for x in read(heCandidatePath)['sourceGoals']};heChecks=[]
xml=BeautifulSoup((OWN/'primary/HE-physical-043.actual-bbox.html').read_text(),'html.parser');lines=[' '.join(line.get_text(' ',strip=True).split()) for line in xml.find_all('line')]
for r in read(AUTHOR/'HE43.actual-original-components-bbox-and-stage-course.json')['records']:
 # Whitespace normalization is only for PDF line extraction; original soft-hyphen text retained.
 for line in r['actualBboxLines']:assert ' '.join(line['rawText'].split()) in lines
 sid=r['sourceGoalId'];a=hc.get(sid) if sid else None
 if sid:assert a and a['sourceText']==r['originalText']
 heChecks.append({'recordId':r['recordId'],'sourceGoalId':sid,'originalText':r['originalText'],'actualBBoxLinesFound':True,'physicalPage':43,'printedPage':43,'originalLevelLabel':r['originalLevelLabel'],'compulsoryThemeField':r['compulsoryThemeField'],'existsInActiveHEExtraction':sid in ha if sid else False,'existsInPreviouslyFrozenProspectiveHEExtraction':sid in hc if sid else False,'prospectiveDefinitionPath':rel(heCandidatePath) if sid else None,'noActiveSourceRestorationClaim':True})
# Two narrow NW source components and direct positive-witness loss.
nwrecords=read(AUTHOR/'NW-two-protected-losses.actual-primary-and-direct-mapping-diagnosis.json')['records'];atlas=read(REPO/'app/scripts/config/goal-books/de-gym-biology-national-atlas.inputs.json');policy=read(REPO/'curricula/DE/Gymnasium/provenance/gymnasium-duration-model-policy.json')['decisions'];nwSourcePath=V3/'NW.two-bacterial-source-components.author-v3.candidate.json';nwMapPath=V3/'NW.two-bacterial-component-mappings.author-v3.candidate.json';ns=read(nwSourcePath);nm=read(nwMapPath);nsids={x['id']:x for x in ns['sourceGoals']};nmm={x['canonicalGoalId']:x for x in nm['mappings']};assert len(nsids)==len(nmm)==2
orig=next(x for x in read(HIST/'effective-original-neuro21-source-overrides.json') if '/DE-NW/' in x['originalPath']);activeMapping=read(REPO/orig['originalPath']);holdMapping=read(REPO/orig['effectiveCandidatePath']);broad='nw-biology-seki-klp-2019-if7-10-hormonelle-regulation-immunbiologie-und-neurobiologie-erklaren';ad=next(x for x in activeMapping['decisions'] if x['sourceGoalId']==broad);hd=next(x for x in holdMapping['decisions'] if x['sourceGoalId']==broad);assert ad['decision']=='mapped' and hd['decision']=='needs_canonical_goal'
baseModelPath=HIST/'baseline-current390-source-atlas.actual.book-model.json';holdModelPath=HIST/'neuro21-hold-plus-reviewed40-source-atlas.actual.book-model.json';bm={x['goalId']:x for x in read(baseModelPath)['pages']};hm={x['goalId']:x for x in read(holdModelPath)['pages']};assert len(bm)==390 and len(hm)==382 and set(bm)-set(hm)==ids
nwChecks=[]
for r in nwrecords:
 gid=r['goalId'];assert gid in protected and c[gid]==r['fullCurrentGoalDEEN'];sg=r['existingSeparateSourceComponent'];assert nsids[sg['id']]==sg and nmm[gid]==r['existingSeparateMapping'];assert sg['rawSourceText']==sg['rawParentBulletText']=='den Bau und die Vermehrung von Bakterien und Viren beschreiben (UF1),';assert sg['printedPage']==sg['physicalPage']==35 and sg['stage']=='SekI' and sg['isOfficialBullet'] is False and sg['wholeOriginalBulletCoverage'] is False;assert gid in ad['canonicalGoalIds'] and gid in hd['originalCanonicalGoalIdsRetainedAsDebt']
 direct=[x for x in activeMapping['mappings'] if x['legacyGoalId']==broad and x['canonicalGoalId']==gid];assert len(direct)==1
 oldNW=[x for x in bm[gid]['applicability'] if x['jurisdiction']=='DE-NW'];newNW=[x for x in hm[gid]['applicability'] if x['jurisdiction']=='DE-NW'];assert oldNW==[{'jurisdiction':'DE-NW','scopes':[{'stage':'SekI','durationModel':'G9','courseProfile':None}]}] and newNW==[]
 activeOriginalPolicy=[x for x in policy if x.get('sourceExtractionPath')=='curricula/DE/Gymnasium/input/NW/lower-secondary/source-extraction/DE_NW_BIOLOGIE_SEKI_KLP2019.source-extraction.json'];candidatePolicy=[x for x in policy if x.get('sourceExtractionPath')==r['declaredActiveComponentExtractionPath']];assert len(activeOriginalPolicy)==1 and activeOriginalPolicy[0]['durationModels']==['G9'];assert not candidatePolicy
 nwChecks.append({'goalId':gid,'wholeProtectedCanonicalGoalExact':True,'sourceComponentId':sg['id'],'sourceComponentWholePayloadExact':True,'mappingWholePayloadExact':True,'directBroadIF7Mapping':direct[0],'activeDecision':'mapped','frozenOverlayDecision':'needs_canonical_goal','originalScope':oldNW,'frozenOverlayScope':newNW,'falseClusterInheritance':False,'canonicalCourseTagsDoNotOverrideNativeScope':True,'currentPrimaryG9DurationPolicy':activeOriginalPolicy[0],'candidateExtractionExists':(REPO/r['declaredActiveComponentExtractionPath']).exists(),'candidateMappingAlreadyInActiveAtlas':r['existingSeparateMappingDossierPath'] in atlas['mappingPaths'],'candidateSeparateDurationDecision':candidatePolicy,'nativeSourceAndDurationAdoptionPending':True,'activeBindingRestored':False,'fullIF7AndViralObligationsRemainHOLD':True})
assert all(x['candidateExtractionExists'] is False and x['candidateMappingAlreadyInActiveAtlas'] is False for x in nwChecks)
extra=[canonPath,heCandidatePath,nwSourcePath,nwMapPath,REPO/orig['originalPath'],REPO/orig['effectiveCandidatePath'],baseModelPath,holdModelPath,HIST/'effective-original-neuro21-source-overrides.json',HIST/'all22-ordered-target-lists-and-actual-overlay-deltas.json',HIST/'protected-current74-full-page-and-context-checks.json',REPO/'AGENTS.md',REPO/'docs/concept/skill-graph/atomic-goal-visualizations.md']
write('author47-and-current77.actual-binding-verification.independent-b.json',{'schemaVersion':1,'authorFreezePath':rel(freeze),'authorFreezeSha256':sha(freeze),'authorDossierRelativePathsCorrectlyResolved':True,'frozenOwnFiles':frozen,'actualInputBindings':inputs,'authorInitialInputDrifts':[x for x in inputs if not x['sameAsAuthorInitial']],'additionalActualReadOnlyBindings':[{'path':rel(p),'sha256':sha(p),'bytes':p.stat().st_size} for p in extra],'noPeerSourceARead':True,'noNewPeerVRead':True})
write('current390-eight-only-delta-and-protected74.actual.independent-b.json',{'schemaVersion':1,'currentWholeCanonicalExactToAuthorSnapshot':True,'canonicalNodes':len(c),'currentCurricularAtomicGoalCount':len(atomic),'candidateCanonicalNodes':len(n),'candidateCurricularAtomicIdsUnchanged':True,'actualChangedGoalIds':sorted(changed),'all464OtherWholeGoalsExact':True,'all472RequiresContainsExact':True,'all74StrictProtectedWholeGoalsExact':True,'selectedEightProtectedIntersection':[],'allFiveActualNeighborWholeGoalsExact':True,'mappingDecisionCount':8,'activeMappedDecisions':0,'mappingRows':0,'full390DenominatorPreserved':True,'historicalFrozenAtlasCounts':{'baseline':390,'heldProspective':382,'omittedEightIds':sorted(set(bm)-set(hm))},'held382ModelIsDiagnosticNotAllowedCompletionDenominator':True,'strictCountsFromBoundedExistingReportNotNewGlobalRun':{x['subject']:{'strictComplete':x['strictComplete'],'denominator':x['denominator']} for x in central['subjects']},'newStrictCompletions':0,'bindingRestorations':0,'strictNetGain':0,'wholeSourceClearance':False,'nativeD_P_A_M_VApproval':False,'humanApproval':False,'humanTrial':False,'activeWrites':False,'gitMutation':False,'globalBuilds':0,'centralRuns':0})
write('HE-BY-current-and-prospective-source-ID-scope-binding.independent-b.json',{'schemaVersion':1,'actualBYMergedSourceIdentityChecks':byChecks,'actualHEPrimaryAndProspectiveIdentityChecks':heChecks,'HEQ23RequiredHEQ24Optional':True,'HEHormoneLK3NotEvidenceForDopamineSerotonin':True,'BYEAandGAOriginalLevelLabelsNotOfficialGK_LKNames':True,'BYHTMLNoInventedPhysicalOrPrintedPages':True,'modelNamesHebbLTP_LTDNotLiteralOfficialObligations':True,'nativePlacementPending':True,'noWholeSourceApproval':True})
write('NW-two-protected-direct-witness-loss-and-bounded-v3.actual.independent-b.json',{'schemaVersion':1,'actualOriginalPDFPhysicalAndPrintedPage':35,'actualOriginalUF1BulletReadAndRasterViewed':True,'records':nwChecks,'sourceComponentCount':2,'sourceComponentScienceKEEP':2,'sourceComponentsRemainPartial':True,'actualAdoptionStatus':'not integrated; source mapping duration-policy and current native-context bindings pending','sourceSupersetWholeCoverage':False,'newNativeProbeRun':False,'old382AtlasNeverCurrentDenominator':True,'noActiveWrites':True})
print(json.dumps({'authorPayloadFilesVerified':len(frozen),'authorInitialInputsChecked':len(inputs),'initialInputDrifts':len([x for x in inputs if not x['sameAsAuthorInitial']]),'currentNodes':len(c),'currentAtomic':len(atomic),'exactProtected':len(protected),'currentCandidateDelta':len(changed),'BYSourceIDs':len(byChecks),'HEPrimaryRecords':len(heChecks),'NWProtectedActualLosses':len(nwChecks)}))
