import {loadGoalBookBuildInputs} from '../../../../../../../app/scripts/goalBookModel'
import {buildGoalDescriptionRolloutSubsetModel} from '../../../../../../../app/scripts/materializeGoalDescriptionRolloutBatch'
import {buildGoalDescriptionCanonicalContext} from '../../../../../../../app/scripts/validateGoalDescriptionReviewCampaign'
import {readFileSync,writeFileSync} from 'node:fs'
import {resolve} from 'node:path'
const root=process.cwd(),own='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-05/chemie-b014-five-prospective-book-current-v1',iso=resolve(root,'tmp/chemie-b014-five-native-isolated-20261005-v1'),id='bcf8b24b-3eed-4a36-8fb3-d6bffc1e193a'
const read=(base:string,path:string):any=>JSON.parse(readFileSync(resolve(base,path),'utf8'))
const baseConfig='curricula/DE/Gymnasium/quality/goal-description-review/chemie/review-book-full.config.json',oldPackage='curricula/DE/Gymnasium/quality/goal-description-review/chemie/rollout-v1/2026-10-05/batch-009-open-redox-one-current-v2'
const stored=read(root,oldPackage+'/bundle/book-model.json'),[oldBase,newBase]=await Promise.all([loadGoalBookBuildInputs(baseConfig,root),loadGoalBookBuildInputs(baseConfig,iso)])
const opts={goalIds:stored.pages.map((p:any)=>p.goalId),bookId:stored.book.id,title:stored.book.title}
const oldPage=buildGoalDescriptionRolloutSubsetModel({baseModel:oldBase.model,...opts}).pages.find(p=>p.goalId===id)!,newPage=buildGoalDescriptionRolloutSubsetModel({baseModel:newBase.model,...opts}).pages.find(p=>p.goalId===id)!,storedPage=stored.pages.find((p:any)=>p.goalId===id)
if(storedPage.goalFingerprint!==oldPage.goalFingerprint||storedPage.pageFingerprint!==oldPage.pageFingerprint)throw new Error('Old strict registered page not current at task baseline')
const canonicalRel='curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_CHEMIE.de.json',oldGoal=read(root,canonicalRel).goals.find((g:any)=>g.id===id),newGoal=read(iso,canonicalRel).goals.find((g:any)=>g.id===id)
if(JSON.stringify(oldGoal)!==JSON.stringify(newGoal)||oldPage.goalFingerprint!==newPage.goalFingerprint)throw new Error('A scientific bcf change was not authorized')
const changedKeys=Object.keys(oldPage).filter(k=>JSON.stringify((oldPage as any)[k])!==JSON.stringify((newPage as any)[k]))
if(changedKeys.some(k=>!['pageFingerprint','externalReverseRequires','reverseRequires'].includes(k)))throw new Error('Unexpected existing scientific or image/source page change '+changedKeys)
const result={status:'EXACT_existing_current_strict_page_binding_delta_for_targeted_independent_review',goalId:id,existingRegisteredIndexPath:oldPackage+'/resolution-index.json',existingRegisteredResolutionPath:oldPackage+'/resolutions/'+id+'.resolution.json',registeredPageStillCurrentBeforeCandidate:true,registeredPageFingerprint:storedPage.pageFingerprint,oldModelDigest:stored.digest,registeredScientificAuthorityUnmodified:true,oldGoalObject:oldGoal,newGoalObject:newGoal,wholeGoalObjectUnchanged:true,oldCanonicalContext:buildGoalDescriptionCanonicalContext(oldGoal),newCanonicalContext:buildGoalDescriptionCanonicalContext(newGoal),canonicalContextUnchanged:true,oldCurrentPageUsingExistingReviewBookScope:oldPage,newCurrentPageUsingExistingReviewBookScope:newPage,pageFieldsChanged:changedKeys,sourceBindingsAndImageUnchanged:true,scientificBasisForRemovedReference:'Only the direct requirement 16da->bcf is removed. The current independent source/A/prerequisite candidate shows metal depositions and given measurements require actual electron-transfer donor/acceptor roles from04fa; the old oxygen-redox foundation is not an additional universal prerequisite. bcf itself retains its old own content, requirements, source/provenance and accepted image.',scientificSourcePrerequisiteDecisionPath:'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-05/chemie-b014-eleven-source-remediation-independent-a-v1/bounded-prerequisite-edge-cases.json',needsTwoTargetedIndependentPageReviews:true,needsCurrentPBindingCheckBySeparateOwner:true,newScientificClosures:0,restoredBindingsActual:0,restoredBindingPotentialAfterAllRequiredCurrentChecks:1,activeWrites:0,humanApproval:false}
writeFileSync(resolve(root,own,'bcf-current-authoritative-page-targeted-binding.case.json'),JSON.stringify(result,null,2)+'\n')
console.log(JSON.stringify({status:result.status,wholeGoalUnchanged:true,goalFingerprintUnchanged:true,pageFieldsChanged:changedKeys,oldPageFingerprint:oldPage.pageFingerprint,newPageFingerprint:newPage.pageFingerprint,activeWrites:0}))
