"""Apache-2.0. Actual author inputs and individual inert A/M/taxonomy boundaries."""
from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
ROOT=Path(__file__).resolve().parents[7];OWN=Path(__file__).resolve().parent
read=lambda p:json.loads(p.read_text());sha=lambda p:'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):
 with p.open('x')as f:json.dump(v,f,ensure_ascii=False,indent=2);f.write('\n')
ids=read(OWN/'goal-ids.json');goals=read(OWN/'whole-goals.candidate.json')
reg=read(ROOT/'curricula/DE/Gymnasium/quality/deep-understanding-rollout/de-gymnasium-math-physics.config.json');econ=next(s for s in reg['subjects']if s['subject']=='wirtschaftswissenschaften');old={};inputs=[]
for kind,key in [('atomicity','semanticAtomicityConfigPath'),('memory','memoryReviewConfigPath')]:
 cfg=read(ROOT/econ[key]);path=ROOT/cfg['reviewPath'];rows={r['goalId']:r for r in[json.loads(l)for l in path.read_text().splitlines()]};old[kind]=[rows[g]for g in ids];inputs.append({'kind':kind,'configPath':econ[key],'configSha256':sha(ROOT/econ[key]),'reviewPath':cfg['reviewPath'],'reviewSha256':sha(path)})
deck=ROOT/'app/public/data/de_gymnasium_economics_flashcards_business_law.de.json';cards=[c for c in read(deck)['cards']if set(c['originGoalIds'])&set(ids)];assert len(cards)==8
write(OWN/'actual-prior-forty-AM-and-eight-whole-cards.author-inputs.json',{'role':'author_actual_input_preservation','recordedAt':datetime.now(timezone.utc).isoformat(),'scope':'All20 complete prior A and20 complete prior M records and all8 complete physical cards were actually printed and read during author work. This is input reading, not independent review.','configInputs':inputs,'actualWholePriorAtomicityRecords':old['atomicity'],'actualWholePriorMemoryRecords':old['memory'],'actualDeckPath':str(deck.relative_to(ROOT)),'actualDeckSha256':sha(deck),'actualWholeCards':cards,'nativeVisibilityClaim':False,'independentApprovalClaim':False,'activeWrites':0,'newStrictClosures':0})
boundaries=[
 ('Die Notwendigkeit einer konkreten Rechtsregel aus verbundenen Schutz-, Ordnungs-, Verlässlichkeits- und Ausgleichsfunktionen beurteilen.','Keine Behauptung jede Regel sei nötig/gerecht oder zusätzliche Gesamtkompetenz zu jedem Rechtsgebiet.','Die bestehende enge Funktionskarte unterstützt den begrifflichen Abruf; begründete Regelnotwendigkeit und Alternativen müssen am neuen Fall gezeigt werden.'),
 ('In echten datierten Fällen vereinfachte zivile und strafrechtliche Normen fallbezogen analysieren und anwenden.','Keine Strafzumessung, Verurteilung aus einer Verdachtsmeldung oder vollständige Rechtsberatung; beide Rechtsbahnen gehören zur begrenzten vergleichenden Fallprüfung.','Normtexte und authentische Fallmaterialien werden bereitgestellt; Tatbestand, Alter, Schuld und Beweisgrenzen brauchen verständige Anwendung statt weitere Gesetzeslisten als Karten.'),
 ('Mögliche Folgen widerrechtlichen Handelns in konkreten Alltagssituationen unter Voraussetzungen abschätzen.','Keine sichere Straf-/Haftungsprognose oder automatische Elternhaftung; umfassende juristische Technik und Regelungsurteil bleiben Nachbarziele.','Fallbedingungen und bereitgestellte Normen tragen die bedingte Folgeeinschätzung, ohne zusätzliche Sanktionshöhe zu memorieren.'),
 ('Onlinehandlungen anhand der jeweils einschlägigen jugendrelevanten Normen rechtssicher gestalten.','Keine vollständige Datenschutz-/IT-Sicherheitskompetenz, Plattformfreigabe oder tatsächliche private Lernendendaten; konkrete Erlaubnis und Vertragsbedingungen entscheiden.','Die einschlägigen Normen und Bedingungen werden als Material geprüft; keine weitere wechselnde Plattform- oder Rechtsliste ist notwendig.'),
 ('Geistiges Eigentum und Rechte erkennbarer Personen in privatem/schulischem Alltag reflektieren und wesentliche Urheberregeln beachten.','Keine universale Medienrechtsberatung oder Eigentum an Dateien als öffentliche Lizenz; die beiden Schutzbereiche müssen im selben Nutzungskontext abgegrenzt werden.','Die bestehende enge Schutzbereichskarte ist ein begrifflicher Anker; tatsächliche Nutzungszwecke, Schranken und Einwilligungen bleiben Fallprüfung.'),
 ('Vertragszustandekommen und eigene rechtliche Handlungsfolgen über Erklärungen, Pflichten und getrennte Verfügung erklären/analysebezogen verbinden.','Nicht jedes Angebot im Alltag als wirksamer Vertrag oder Vertrag und Eigentum als identisch behandeln; keine Volllehre aller Rechtsgeschäfte.','Die bestehende Angebot-/Annahme-Karte bildet einen engen notwendigen Abrufkern, nicht die konkrete Wirksamkeits- oder Eigentumsprüfung.'),
 ('Rechtliche Kaufmöglichkeiten als beschränkt Geschäftsfähiger erkennen und durch zulässige Handlungen/Kommunikation wahrnehmen.','Keine künstliche universale Taschengeld-Preisgrenze oder volle Vertragsfreiheit trotz zukünftiger Pflichten; bestehende Zustimmung/Ausnahmen werden fallbezogen geprüft.','Die bestehende beschränkte-Geschäftsfähigkeit-Karte wird beibehalten; Zustimmung, Genehmigung und vollständig bewirkte Leistung müssen mit neuen Fällen verbunden werden.'),
 ('Passende Verbraucherrechte in Kaufproblemen bestimmen und sie sachlich an den Verkäufer kommunizieren.','Keine pauschale Laden-Rückgabe, freiwillige Garantie als einziges Recht oder beliebige automatische Erstattung; Rechtewahl und Mitteilung bilden die eine begrenzte Handlung.','Rechte/Fristen stehen im Fallmaterial; verständige Auswahl und konkret begründete Forderung brauchen keine zusätzliche Nachrichten-Schablonenkarte.'),
 ('Tatbestandsmerkmale und Rechtsfolge einer einschlägigen Norm strukturiert mit konkreten Fakten verknüpfen.','Kein bloßes Zitieren einer Norm oder sichere Gerichtsprognose; vollständige Anspruchsdurchsetzung bleibt Nachbarziel.','Die bereits beim Technikziel vorhandene Subsumtionskarte wird nicht doppelt benötigt; hier müssen Merkmale und ergebnisändernde Tatsachen angewandt werden.'),
 ('Konkrete rechtliche Rahmenbedingungen über mehrere verbundene Rechtsfunktionen analysieren.','Nicht bereits die umfassende Notwendigkeit/Gerechtigkeit einer Regelung beurteilen oder nur Funktionsnamen aufzählen; Mechanismen sind gefordert.','Der bestehende Funktionsanker beim Urteilsziel genügt; der aktuelle materialgebundene Analysefall benötigt keine zusätzliche doppelte Karte.'),
 ('Mögliche staatliche Rechtsfolgen jugendlichen Handelns in ausgewählten öffentlich-rechtlichen Situationen analysieren.','Keine administrative Geldbuße mit strafrechtlicher Geldstrafe oder Privatanspruch gleichsetzen; juristische Vollberatung und konkrete Strafhöhe bleiben außen vor.','Datierte Normtexte tragen die Abgrenzung Ordnungswidrigkeit/Straftat und Alters-/Reifeprüfung, ohne weitere pauschale Sanktionskarte.'),
 ('Zweck und Ausgestaltung einer öffentlichen Regel im Zusammenhang von Rechtsfunktionen, Gerechtigkeit und Wandel beurteilen.','Keine freie Reformbehauptung ersetzt gültige Normen oder Wirksamkeitsnachweise; alle drei Urteilsperspektiven gehören zusammen.','Fallregeln und Wandelmaterial sind bereitgestellt; konkrete begründete Abwägung benötigt keine zusätzliche starre Meinung oder Instrumentenliste.'),
 ('Jugendkriminalitätsfälle durch strukturierte Tatbestands-/Rechtswidrigkeits-/Schuld- und Alters-/Reifeprüfung bearbeiten.','Keine Strafhöhe aus dem Etikett Jugendstraftat ableiten oder ungeklärte Schuld behaupten; Rechtsfolgenurteil ist separat.','Die bestehende enge Karte zum Erziehungsgedanken ist der konservative vorhandene Jugendstrafrechtsanker; sie ersetzt weder Elemente noch Subsumtion und wird nicht vermehrt.'),
 ('Rechtsfolgenalternativen für jugendliche Straftäter nach Erziehungsbedarf, Prävention und Zumutbarkeit beurteilen.','Keine automatische Haft aus Wiederholung, reale Sanktionsentscheidung oder garantierte Wirkung; die konkreten erzieherischen Bedingungen bleiben entscheidend.','Der vorhandene Jugendanker beim Tatbestandsziel und aktuelle JGG-Materialien reichen; zusätzliche Strafmaß- oder Wirkungslisten sind nicht nötig.'),
 ('Grundlegende juristische Techniken und BGB-Systematik an Kauf-/Rechtsfragen anwenden.','Nicht bloß Paragrafenzahlen oder Vertrags-/Eigentumsebenen vermischen; Ausformulierung gesetzlicher Forderungen bleibt eigenes Ziel.','Die enge bestehende Subsumtionskarte trägt den Methodenabruf; Normkette, BGB-Ebenen und konkrete Tatsachenanwendung müssen neu gezeigt werden.'),
 ('Gesetzlich entstandene Ansprüche rechtstechnisch begründen und sachliche Durchsetzungstexte verfassen.','Nicht auf vertragliche Kaufansprüche verengen; Eigentums-/Besitzeinwendung und Deliktsschaden müssen getrennt begründet werden, keine tatsächliche rechtliche Vertretung.','Die Methodenkarte beim Vorgängerziel reicht, weil Normen und konkrete Anspruchsfakten bereitstehen; zusätzliche Forderungsbriefschablonen sind kein notwendiger Memorykern.'),
 ('Mehrere gesetzlich begrenzte Möglichkeiten gerechten Interessenausgleichs in praktischen Rechtsfällen diskutieren.','Keine moralische Sympathie als gesetzlicher Anspruch oder beliebiger Ausgleich entgegen Eigentums-/Nacherfüllungsregeln; Urteil muss normgebunden bleiben.','Die verständige Perspektivabwägung mit bereitgestellten Regelgrenzen benötigt keine weitere abstrakte Fairness-Liste als Karte.'),
 ('Die Grundsystematik von Leistungsstörungen/Rechtsbehelfen anhand konkreter Fälle und gesetzgeberischer Ausgleichsintention nachvollziehen.','Nicht jeden Mangel sofort erstatten, Rücktritt automatisch als Ersatzanspruch oder alle Folgen ohne Zusatzvoraussetzungen behandeln.','Die vorhandene enge Leistungsstörungs-Karte unterstützt die grobe Orientierung; Normverweise, Zusatzbedingungen und Ausgleich müssen fallbezogen erklärt werden.'),
 ('Mangelhafte Leistung anhand subjektiver, objektiver und einschlägiger Montageanforderungen bei Gefahrübergang identifizieren.','Nicht jede Enttäuschung oder spätere Käuferbeschädigung als anfänglichen Mangel behandeln; Rechtekommunikation ist Nachbarziel.','Die aktuelle§434-Systematik wird als Material bereitgestellt; genaue Abweichung und Ursachen-/Zeitpunktprüfung brauchen keine zusätzliche fixe Mängelliste.'),
 ('Vertragstypen anhand geschuldeter Leistung identifizieren, beiderseitige Pflichten erklären und vom Kauf abgrenzen.','Nicht Maßanfertigung automatisch als Werkvertrag oder Tätigkeitsversprechen als Erfolgsgarantie behandeln; keine Volllehre aller Sonderverträge.','Die enge bestehende Typen-/Pflichten-Karte ist begrenzter Abrufanker; Kauf, Dienst, Werk und einschlägige Herstellungs-Liefergrenze müssen neu angewandt werden.')]
assert len(boundaries)==20
proposals=[]
for i,g in enumerate(goals):
 scope,limit,mreason=boundaries[i];mr=old['memory'][i];ar=old['atomicity'][i]
 proposals.append({'goalId':g['id'],'wholeCurrentCandidate':g,'authorSemanticDecision':'atomic','boundedPerformanceDe':scope,'boundaryDe':limit,'semanticReasonDe':'Eine begrenzte zusammenhängende juristische Leistung mit den im ganzen Ziel genannten verknüpften Aspekten: '+scope,'requiresRetained':g['requires'],'priorAtomicityStatus':ar['status'],'authorMemoryDecision':mr['status'],'memoryReasonDe':mreason,'existingCardIds':[c['id']for c in cards if g['id']in c['originGoalIds']],'newCardsProposed':0,'nativeVisibilityPending':True,'independentApprovalClaimed':False})
assert sum(g['authorMemoryDecision']=='memory_required'for g in proposals)==8
write(OWN/'semantic-atomicity-memory.proposals.author.actual.json',{'role':'author_individual_boundaries_and_memory_proposals','goals':proposals,'cardContentChanges':0,'independentReviewRequired':True,'activeWrites':0,'newStrictClosures':0})
units=['WR8 3','WR8 3','WR8 3','WR8 3','WR8 3','WR9 1','WR9 1','WR9 1','WR9 1','WR10 WWG2','WR10 WWG2','WR10 WWG2','WR10 WWG2','WR10 WWG2','WR12 grundlegend3.1','WR12 grundlegend3.2','WR12 grundlegend3.2','WR13 erhoeht1.1','WR13 erhoeht1.2','WR13 erhoeht1.1']
levels=['AB3','AB2','AB2','AB2','AB2','AB2','AB2','AB2','AB2','AB2','AB2','AB3','AB2','AB3','AB2','AB2','AB3','AB2','AB2','AB2']
reasons=[
 'Notwendigkeit und begrenzte Gestaltung einer Regel nach mehreren Funktionen mit Gegenoption abwägen: eigenständiges begründetes Urteil.',
 'Authentische neue Sachverhalte mit vereinfachten zivil-/strafrechtlichen Normen und Voraussetzungen analysieren/subsumieren: strukturierte Anwendung.',
 'Bedingte rechtliche Folgen über Alter, Verschulden und Schaden erklären; begrenzte Folgeanalyse statt freier normativer Sanktionsbewertung.',
 'Einschlägige Regeln bei neuen Onlinehandlungen anwenden und zulässige konkrete Handlungsalternative erkennen: begrenzter Transfer.',
 'Beide Schutzbereiche und urheberrechtliche Zweckgrenzen in neuen privaten/schulischen Fällen reflektiert beachten: verknüpfte materialgebundene Anwendung.',
 'Erklärungen, Vertragspflichten und Verfügung an neuen Handlungsabläufen analysieren: bekannte Rechtsstruktur übertragen.',
 'Minderjährigenregeln auf konkrete neue Kaufoptionen übertragen und situationsgerecht wahrnehmen: Handlungsanwendung.',
 'Aus neuen Kaufproblemen passende gesetzliche Rechte ableiten und eine begründete sachliche Forderung kommunizieren: Anwendung und Übersetzung.',
 'Normmerkmale strukturiert mit neuen Fakten verknüpfen und ergebnisändernde Varianten erkennen: Subsumtion.',
 'Konkrete Regelmechanismen auf mehrere Rechtsfunktionen beziehen und Spannungen analysieren, ohne umfassendes Regelungsurteil zu verlangen.',
 'Normketten und Alters-/Reifevoraussetzungen auf neue öffentlich-rechtliche Situationen anwenden, Geldbuße/Straftat/Privatanspruch abgrenzen.',
 'Zweck und Ausgestaltung nach Rechtsfunktionen, Gerechtigkeit und Wandel abwägen: eigenständiges mehrperspektivisches Urteil.',
 'Tatbestandsmerkmale, Rechtfertigung und jugendliche Schuldvoraussetzungen an neuen Fällen geordnet prüfen: juristische Anwendung.',
 'Rechtsfolgenalternativen mit Erziehungsbedarf, Zumutbarkeit und Prävention gewichten: eigenständiges bedingtes Urteil.',
 'BGB-Systematik, Verweisnormen und Subsumtion auf neue Rechtsfragen anwenden und Verpflichtung/Verfügung trennen.',
 'Gesetzliche Anspruchsvoraussetzungen subsumieren und daraus sachliche juristische Forderungstexte formulieren: begrenzte Anwendung, keine freie Normsetzung.',
 'Mehrere normgebundene Ausgleichsoptionen mit Schutz/Belastung/Umsetzbarkeit gewichten und eine begründete Position diskutieren.',
 'Bekannte Rechtsbehelfssystematik, Zusatzvoraussetzungen und gesetzgeberischen Ausgleich in neuen Fällen rekonstruieren: strukturierte Analyse.',
 'Neue Abweichungen der subjektiven/objektiven/Montageanforderungen und Zeitpunktgrenzen klassifizieren: begrenzte Fallanalyse.',
 'Verschiedene konkrete Vertragsleistungen und typische Pflichten rechtlich einordnen und vom Kauf abgrenzen: begrenzter Vergleich/Transfer.']
write(OWN/'bounded-twenty-whole-goal-demand-level.proposals.author.json',{'role':'inert_author_skillpilot_taxonomy_proposals','scope':'Native SkillPilot demand levels based on whole goals, original operators and individual case performance; no claim of official per-goal AB assignment.','wholeGoalProposals':[{'goalId':g['id'],'wholeUnmodifiedDeEnCandidate':g,'candidateDemandLevel':levels[i],'reasonDe':reasons[i],'originalCurriculumUnit':units[i],'originalDemandLevel':g['dimensionTags']['demandLevel'],'independentTaxonomyAcceptanceClaim':False}for i,g in enumerate(goals)],'candidateV1DemandLevelFieldsChanged':0,'activeWrites':0,'newStrictClosures':0,'sourceCourseBoundary':'WR13 contract-types original source is the increased-level course1.1, not an asserted official GK requirement. Active applicability/tags remain unchanged and require separate mapping/projection consideration if affected.'})
write(OWN/'actual-primary-source-author-reading.receipt.json',{'role':'author_actual_targeted_primary_source_reading','recordedAt':datetime.now(timezone.utc).isoformat(),'whole20CanonicalOriginalsAndCandidatesActuallyRead':True,'curriculumTargetedActualRead':[{'url':'https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/'+u,'units':units}for u,units in [('8/wirtschaft-und-recht',['3 entire expectations and content']),('9/wirtschaft-und-recht',['1 entire expectations and content']),('10/wirtschaft-und-recht/wwg',['2 entire expectations and content']),('12/wirtschaft-und-recht/grundlegend',['3.1 and3.2 entire expectations and content']),('13/wirtschaft-und-recht/erhoeht',['1.1 and1.2 entire expectations and content'])]],'actualNormSnapshotDirectory':str((OWN/'actual-primary-norm-inputs').relative_to(ROOT)),'actualNormHttpResultsPath':str((OWN/'actual-primary-norm-inputs/actual-fetch-results.json').relative_to(ROOT)),'normReadingScope':'The substantive paragraph text returned by the actual fetch was read. Nested enumerations for434/437/475d/312g/JGG10/13/UrhG60a/KUG23/StVO23 were subsequently extracted from full retained HTML and actually read. Full source bytes retained do not themselves imply that every irrelevant provision has been reviewed. OWiG first incorrect slug404 and BGH referral403 attempts are honestly preserved and unused as substantive sources.','additionalNormsActuallyRead':['BGB106/107/110/828 andJGG3 via actual web primary opens','BGB104/105/929/312j,UrhG53,StVO49,StVG24 andOWiG1968-12 through actual full local primary fetch/read'],'authenticCasesActuallyRead':[{'url':'https://www.polizei.bayern.de/aktuelles/pressemitteilungen/104234/index.html','publicationDate':'2026-06-15','caseStatus':'Actual public primary police suspicion report; no conviction or proven individual liability asserted.'},{'url':'https://www.polizei.bayern.de/aktuelles/pressemitteilungen/082377/index.html','publicationDate':'2025-03-25','caseStatus':'Actual public primary report with unquantified damage; no invented amount or adjudication.'}],'caseMaterialsStatus':'All other tasks are explicitly fictional didactic cases with prescribed dated primary norm extracts; none is observed learner work or personalised legal advice.','notClaimed':['No complete new source mapping/country projection approval.','No independent substantive review.','No image approval, human release or learner performance evidence.'],'activeWrites':0,'newStrictClosures':0})
print('Actual40oldAM+8cards retained;20individual atomic/memory and bounded taxonomy proposals; precise primary source author record; no independent approval.')
