from pathlib import Path
import json,shutil,hashlib,subprocess
from datetime import datetime,timezone
R=Path.cwd();A=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/biologie-q1-eight-current-v3-raster-native-technical-author-candidate-v1';O=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/biologie-q1-eight-current-native-independent-b-20261010-v1';X=R/'tmp/biologie-eight-native-independent-b-20261010-v1/ordinary-P-capsule';X.mkdir(parents=True,exist_ok=True)
config_path=str((A/'positive/eight-current-P.author.config.json').relative_to(R));c=json.loads((R/config_path).read_text());e=json.loads((A/'neutral-eight-current-v3-raster-native.independent-review.entry.json').read_text());bindings=[]
def cp(path):
 s=R/path;t=X/path;t.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(s,t);assert s.read_bytes()==t.read_bytes();bindings.append({'path':path,'sha256':'sha256:'+hashlib.sha256(s.read_bytes()).hexdigest(),'executionCopyByteExact':True})
for p in ['app/package.json','app/scripts/positiveGoalEvidenceReview.ts','app/scripts/positiveGoalEvidenceProfileModel.ts','app/scripts/goalEvidenceProfileModel.ts','contracts/goal-evidence/v2/goal-evidence-profile.schema.json','contracts/goal-evidence/v2/goal-evidence-review-config.schema.json','contracts/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json',config_path]:cp(p)
for k in ['landscapePath','semanticKindLedgerPath','reviewCriteriaPath','reviewPath']:cp(c[k])
for item in e['neutralWholeFirstInputs']['originalActualEightPNGs']:
 s=R/item['path'];id=s.stem;p=f'app/public/assets/goal-visualizations/biologie/{id}/{id}.png';t=X/p;t.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(s,t);actual='sha256:'+hashlib.sha256(t.read_bytes()).hexdigest();assert actual==item['sha256'];bindings.append({'sourcePath':item['path'],'publicPath':p,'sha256':actual,'executionCopyByteExact':True})
n=X/'app/node_modules'
if not n.exists():n.symlink_to(R/'app/node_modules',target_is_directory=True)
cmd=[str(R/'app/node_modules/.bin/tsx'),'app/scripts/positiveGoalEvidenceReview.ts','--mode=check','--config='+config_path];start=datetime.now(timezone.utc).isoformat();result=subprocess.run(cmd,cwd=X,capture_output=True,text=True);(O/'checks/normal-inactive-current-P.stdout.actual.txt').write_text(result.stdout);(O/'checks/normal-inactive-current-P.stderr.actual.txt').write_text(result.stderr);(O/'checks/normal-inactive-current-P.terminal.actual.json').write_text(json.dumps({'schemaVersion':1,'command':['app/node_modules/.bin/tsx']+cmd[1:],'startedAt':start,'completedAt':datetime.now(timezone.utc).isoformat(),'actualExitCode':result.returncode,'ordinaryProductionCheckerBytesUnmodified':True,'exactFrozenCandidateAndPNGCopies':bindings,'executionCapsule':'tmp/biologie-eight-native-independent-b-20261010-v1/ordinary-P-capsule','activeRuntimeAssetsWereNotWritten':True,'scope':'Normal current eight inactive candidate P input/resource verification; no active closure or human approval'},ensure_ascii=False,indent=2)+'\n');print(result.stdout,result.stderr);raise SystemExit(result.returncode)
