import fs from 'node:fs/promises'
import path from 'node:path'
import {normalizeCanonicalLandscape} from '../../../../../../../app/src/utils/authoring/canonicalAuthoring.ts'
import {compileCompositionView,normalizeCompositionView} from '../../../../../../../app/src/utils/authoring/compositionViewAuthoring.ts'
const repo=process.cwd(), own=path.relative(repo,path.dirname(new URL(import.meta.url).pathname))
const read=async(p:string)=>JSON.parse(await fs.readFile(path.join(repo,p),'utf8'))
const snap=await read(own+'/author-input-snapshot-manifest.actual.json'), paths=new Map(snap.inputs.map((x:any)=>[x.path,x.snapshotPath]))
const before=await read(paths.get('curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_BIOLOGIE.de.json') as string),after=await read(own+'/candidate/canonical.476-split-author.json')
const beforeKinds=await read(paths.get('curricula/DE/Gymnasium/quality/goal-book-publication/biologie.semantic-kinds.json') as string),afterKinds=await read(own+'/candidate/semantic-kinds.open-author-proposal.json')
const old='3ee4b55c-81c3-5826-9d26-1a8c22cbd0b8',children=['9d3f71d7-5273-5e50-b1ba-4e291edbf114','dd923eeb-eef0-5796-b372-a5d4f5be21f7']
const nav='app/scripts/config/goal-books/navigation/de-gym-biology-national-atlas.view.json'
const compile=async(l:any,p:string)=>compileCompositionView(normalizeCompositionView(await read(p)),normalizeCanonicalLandscape(l))
const bc=await compile(before,paths.get(nav) as string),ac=await compile(after,own+'/candidate/views/'+nav)
const assert=(v:any,m:string)=>{if(!v)throw new Error(m)}
assert([...bc.findings,...ac.findings].every((x:any)=>x.severity!=='error'),'native navigation compiler')
const flatten=(nodes:any[],kinds:any)=>{const atomic=new Set(kinds.decisions.filter((d:any)=>d.semanticKind==='curricularAtomic').map((d:any)=>d.goalId)),rows:any[]=[];const visit=(n:any,labels:string[],ids:string[])=>{if(n.sourceGoalId&&atomic.has(n.sourceGoalId))rows.push({goalId:n.sourceGoalId,title:n.label,breadcrumbs:labels,parentSourceGoalIds:ids,nativeRuntimeId:n.runtimeId,compiledAtomicOrder:rows.length});n.children.forEach((child:any)=>visit(child,[...labels,n.label],[...ids,...(n.sourceGoalId?[n.sourceGoalId]:[])]))};nodes.forEach(n=>visit(n,[],[]));return rows}
const b=flatten(bc.compiledRootNodes,beforeKinds),a=flatten(ac.compiledRootNodes,afterKinds), bm=new Map(b.map(x=>[x.goalId,x])),am=new Map(a.map(x=>[x.goalId,x]))
assert(b.length===391&&a.length===392,'compiled navigation denomination')
const pure=await read(own+'/technical-preview/full391.before.pure.book-model.json')
const beforeCompiledOrderEqualsActualNativePageOrder=JSON.stringify(b.map(x=>x.goalId))===JSON.stringify(pure.pages.map((x:any)=>x.goalId))
const equal=(x:any,y:any)=>JSON.stringify(x)===JSON.stringify(y)
const common=b.filter(x=>x.goalId!==old).map(x=>{const y=am.get(x.goalId);assert(y,'lost compiled atomic');return {goalId:x.goalId,beforeCompiledAtomicOrder:x.compiledAtomicOrder,afterCompiledAtomicOrder:y.compiledAtomicOrder,positionChanged:x.compiledAtomicOrder!==y.compiledAtomicOrder,wholeBreadcrumbAndParentContextExact:equal({title:x.title,breadcrumbs:x.breadcrumbs,parentSourceGoalIds:x.parentSourceGoalIds},{title:y.title,breadcrumbs:y.breadcrumbs,parentSourceGoalIds:y.parentSourceGoalIds}),nativeRuntimeIdBefore:x.nativeRuntimeId,nativeRuntimeIdAfter:y.nativeRuntimeId}})
assert(common.every(x=>x.wholeBreadcrumbAndParentContextExact),'unrelated compiled context change')
const preceding='249f4c5d-fd23-57c7-ac62-773d62c33b49',consumer='4b7fdc2c-9dbe-5439-8d84-295abc240eec'
const reverse=(land:any,id:string)=>land.goals.filter((g:any)=>(g.requires||[]).includes(id)).map((g:any)=>({goalId:g.id,title:g.title,type:g.type,contains:g.contains||[]}))
const contextImpacts=[{goalId:preceding,reason:'Two new children retain the original hormonal-control prerequisite, adding two actual direct reverse-requires edges; the old requiring node also changes from atom to aggregate.',beforeDirectReverseRequires:reverse(before,preceding),afterDirectReverseRequires:reverse(after,preceding)},{goalId:consumer,reason:'Its unchanged direct prerequisite still references the stable original ID; that node now denotes the two-child aggregate. Actual native-page display and external prerequisite treatment need recheck after classification review.',beforeWholeRequires:before.goals.find((g:any)=>g.id===consumer).requires,afterWholeRequires:after.goals.find((g:any)=>g.id===consumer).requires,beforePrerequisiteNode:before.goals.find((g:any)=>g.id===old),afterPrerequisiteNode:after.goals.find((g:any)=>g.id===old)}]
const protectedBase=await read(own+'/protected-current154-and-other-subject-baseline.actual.json'),protectedIds=protectedBase.protectedBiology154GoalIds
assert(!contextImpacts.some(x=>protectedIds.includes(x.goalId)),'protected154 substantive relation/context impact')
const trueContextIds=new Set(contextImpacts.map(x=>x.goalId))
const out={inactiveAuthorCandidate:true,nativeCompiledAtomicCounts:[391,392],beforeCompiledOrderEqualsActualNativePageOrder,native392FullPageCompiler:'BLOCKED: open candidate semantic classifications; no 392 page fingerprints or retained D rebindings made',retainedAtomicCount:common.length,retainedCompiledBreadcrumbContextsExact:common.length,compiledPositionChangedCount:common.filter(x=>x.positionChanged).length,positionOnlyCompiledNodeCount:common.filter(x=>x.positionChanged&&!trueContextIds.has(x.goalId)).length,substantiveRelationContextCount:contextImpacts.length,substantiveRelationContextImpacts:contextImpacts,commonAtomicNodes:common,removedOldAtomicCompiledNode:bm.get(old),newChildCompiledNodes:children.map(id=>am.get(id)),protected154:{substantiveRelationContextImpactCount:0,compiledPositionsChanged:common.filter(x=>protectedIds.includes(x.goalId)&&x.positionChanged).length,wholeGoalBodiesAndBreadcrumbContextsRetained:true},limits:'Compiled positions and real graph relations are actual native comparison results. Exact future native page fingerprints, D/P resource/context bindings and strict intersection must be recalculated after genuine whole split reviews and mandatory rebase onto the stable HE18 active baseline. Position changes alone are not independent science review.'}
await fs.writeFile(path.join(repo,own,'technical-preview/native-compiled-position-and-true-context-impact.actual.json'),JSON.stringify(out,null,2)+'\n',{flag:'wx'})
console.log(JSON.stringify({compiledCounts:[b.length,a.length],current391PageOrderMatches:beforeCompiledOrderEqualsActualNativePageOrder,retainedBreadcrumbContextsExact:common.length,positionChanged:out.compiledPositionChangedCount,positionOnly:out.positionOnlyCompiledNodeCount,substantiveRelationContext:contextImpacts.map(x=>x.goalId),protected154Context:0,native392Pages:'BLOCKED'}))
