"""New targeted author candidates only; prior packages and judgments stay immutable."""
import copy,csv,hashlib,io,json
from datetime import datetime,timezone
from pathlib import Path

ROOT=Path('/home/enpasos/projects/skillpilot')
OWN=Path(__file__).parent
OLD=OWN.parent
NOW=datetime.now(timezone.utc).isoformat()
def bind(path):
    path=Path(path).resolve();raw=path.read_bytes()
    return {'path':str(path.relative_to(ROOT)),'sha256':'sha256:'+hashlib.sha256(raw).hexdigest(),'bytes':len(raw)}
def h(v):return 'sha256:'+hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def write(name,value):
    p=OWN/name;assert not p.exists(),name
    p.write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n')
def textwrite(name,value):
    p=OWN/name;assert not p.exists(),name;p.write_text(value)
inputs=['neutral-remaining-seven-whole-source-and-P.author.entry.json','remaining-seven-whole-source-and-P-author.first.freeze.json','remaining-seven.whole-goal-profile-fourteen-cases.exact-input.json','remaining-seven.normal-positive-profile-bodies.author-candidate.json','remaining-seven.fourteen-whole-cases-with-worked-transfer.author-candidate.json','seven-bounded-BY8-11-source-roles.author-candidate.json','remaining-seven.normal-partial-mapping-delta.author-candidate.json','finite-seven-materials.author.index.json','finite-materials/calibration.synthetic.csv','finite-materials/analogue-model-cards.printable.tsv','finite-materials/digital-model-rule.blank.csv']
write('targeted-remediation-v2.actual-input.first.freeze.json',{'schemaVersion':1,'role':'Exact author followup inputs before targeted changes; no review decision','capturedAt':NOW,'inputs':[bind(OLD/p) for p in inputs],'targetGoalIds':['9fc800d1-92d1-5ef6-81c1-33960ae034dd','6c7ce93c-7675-51da-bc0c-7d0257f7ff7d'],'activeWrites':[],'humanApproval':False})
old_profiles=json.loads((OLD/'remaining-seven.normal-positive-profile-bodies.author-candidate.json').read_text())
profiles=copy.deepcopy(old_profiles['entries'])
cases=json.loads((OLD/'remaining-seven.fourteen-whole-cases-with-worked-transfer.author-candidate.json').read_text())['cases']
doc_de='BY C8: Dokumentation nach Anleitung. BY C9 Nicht-NTG (HG, SG, MuG, WWG, SWG): Dokumentation, Auswertung und Veranschaulichung strukturiert nach Anleitung. BY C9 NTG: bei bekannten Sachverhalten selbständig, bei unbekannten mit Hilfestellung. BY C10: selbstständige Dokumentation gemäß der jeweiligen vollständigen Quelle. Eine angeleitete Quellenteilkompetenz ist kein Nachweis der ganzen selbstständigen kanonischen Kompetenz. Digitale Erfassung und Tabellen sind schon in Sek I möglich; tatsächliche eigene Durchführung, digitale Messwerterfassung und die ursprünglichen Partnerpflichten bleiben bei ihrer jeweiligen Quelle offen, wenn nur vorgegebene Daten dokumentiert werden.'
doc_en='BY C8: documentation with guidance. BY C9 non-NTG (HG, SG, MuG, WWG, SWG): structured documentation, evaluation and illustration with guidance. BY C9 NTG: independently for familiar subject matter, with assistance for unfamiliar subject matter. BY C10: independent documentation according to the respective whole source. A guided source component does not demonstrate the entire independent canonical competence. Digital acquisition and spreadsheets may already occur in lower secondary; actual own execution, digital measurement acquisition and the original partner obligations remain open for their respective source when only supplied data are documented.'
model_de='Für den gemeinsamen kanonischen Kern wird ein geeignetes analoges ODER digitales Modell tatsächlich hypothesengeleitet gewählt, genutzt, mit Beobachtungen und einem anderen Modell verglichen und begrenzt. Keine universelle Pflicht zur selbst implementierten Tabellenkalkulation folgt aus diesem ODER. Im ausdrücklich gewählten digitalen Originalfall bleiben eigene Implementierung der Ladungsregel, alle sechs Prüffälle und das tatsächliche digitale Arbeitsprodukt verbindlich. Die analoge Alternative verwendet eigene Kartenanordnung und manuell protokollierte Regelprüfungen; sie ist keine digitale Leistung. Spezielle source-spezifische Software-/Simulation-/Messwerterfassungs- und praktische Partnerpflichten bleiben unverändert; die analoge Route darf diese nicht schließen. Alle Materie-/Reaktions-/Bindungs-/Wechselwirkungsbeiträge und begründete Modellgrenzen bleiben erhalten; spezielle Inhaltsmodelle behalten ihre eigenen Ziele und source-/Stufen-/target-Grenzen.'
model_en='For the common canonical core, a suitable analogue OR digital model is actually selected and used with a hypothesis, compared with observations and another model, and its limits justified. This OR creates no universal requirement to implement a spreadsheet. In the explicitly selected original digital case, own implementation of the charge rule, all six checks and the actual digital artifact remain mandatory. The analogue alternative uses an own card arrangement and manually documented rule checks; it is not digital performance. Specific source-level software/simulation/measurement-acquisition and practical partner obligations remain unchanged and cannot be completed through the analogue route. All matter/reaction/bonding/interaction contributions and justified model limits remain; specific subject models retain their own goals and source/stage/target boundaries.'
for axis in profiles[0]['profile']['variationAxes']:
    if axis['id']=='source-and-limit':axis.update(textDe=doc_de,textEn=doc_en)
model=profiles[6]['profile']
for exp in model['expectations']:
    if exp['id']=='digital-rule-and-comparison':
        exp.update(id='selected-model-rule-and-comparison',essentialUnderstandingDe='Die gewählte analoge ODER digitale Modellregel unterscheidet Anziehung, Abstoßung und neutral-unbestimmt; ihre Aussagen werden mit einem anderen Modell und Beobachtungen verglichen. Partialladungen sind keine ganzen Ionenladungen.',essentialUnderstandingEn='The selected analogue OR digital model rule distinguishes attraction, repulsion and neutral-undetermined; its statements are compared with another model and observations. Partial charges are not full ionic charges.',observablePerformanceDe='Tatsächlich die gewählte analoge Kartenregel mit eigener Anordnung/Prüfprotokoll ODER die gewählte digitale Regel als eigene Implementation/Datei anwenden und begründet vergleichen. Im digitalen Originalfall alle sechs Prüffälle, eigene Formel und Ergebnisse belegen; in der analogen Alternative eigene manuelle Regelprüfungen zeigen, ohne digitale Leistung zu behaupten.',observablePerformanceEn='Actually apply the selected analogue card rule with an own arrangement/check record OR the selected digital rule with own implementation/file, and justify the comparison. In the original digital case evidence all six tests, own formula and results; in the analogue alternative show own manual rule checks without claiming digital performance.')
model['coverageExpectations']['requiredExpectationIds']=['selected-model-rule-and-comparison' if v=='digital-rule-and-comparison' else v for v in model['coverageExpectations']['requiredExpectationIds']]
for axis in model['variationAxes']:
    if axis['id']=='source-and-limit':
        axis['textDe']=model_de+' '+axis['textDe']
        axis['textEn']=model_en+' Concrete model knowledge is supplied or linked to a suitable content goal; Dalton knowledge is not a universal prerequisite. Successful work must remain hypothesis-guided, earlier-stage contributions remain partial pending stage/target decisions, and the goal asks for justified model criticism rather than claiming already completed model development.'
brief=model['applicationCaseBriefs'][1]
brief['taskDemandDe']='Wähle für die vorgegebene Hypothese die analoge ODER die digitale Route. Analog: ordne selbst die unveränderten gedruckten Wasser-/Na⁺-/Cl⁻-/U-Karten an, prüfe die sechs vorgegebenen Ladungspaarungen manuell und vergleiche mit dem einfacheren M1/M2-Modell und der Lösungsbeobachtung. Digital: führe den ursprünglichen digitalen Fall vollständig aus; implementiere die Regel selbst in einer Tabelle und prüfe alle sechs Fälle mit eigener Formel und Datei. Begründe jeweils Aussagen und Grenzen. Neue Variation: Warum widerlegt ein schlecht lösliches Salz nicht automatisch die Ladungsregel? Benenne fehlende Modellanteile.'
brief['taskDemandEn']='Select the analogue OR digital route for the supplied hypothesis. Analogue: arrange the unchanged printed water/Na⁺/Cl⁻/U cards yourself, manually test the six supplied charge pairs and compare with the simpler M1/M2 model and dissolution observation. Digital: perform the whole original digital case, implement the rule yourself in a table and test all six cases with own formula and file. Justify statements and limits in either route. Fresh variation: Why does a poorly soluble salt not automatically refute the charge rule? Identify missing model components.'
brief['expectedPerformanceDe']='O-Ende zu Na⁺, H-Enden zu Cl⁻; Prüffälle 1/4 Anziehung, 2/3 Abstoßung, 5/6 unbestimmt. Analog liegen eigene Kartenanordnung und manuelles Prüf-/Vergleichsprotokoll vor; digital liegen zusätzlich eigene Implementation, Formel und digitale Ergebnisse aller sechs Fälle vor. Keine Route wird durch eine gelesene Musterlösung belegt. Partialladungs-/Beweglichkeitsmodelle erklären qualitative Wechselwirkungen, aber keine ganze Löslichkeits-/Energiebilanz oder exakte Geometrie. Transfer: '+cases[13]['authoredWorkedFreshTransferResponse']['de']
brief['expectedPerformanceEn']='O end towards Na⁺, H ends towards Cl⁻; checks1/4 attraction,2/3 repulsion,5/6 undetermined. Analogue evidence is an own card arrangement and manual check/comparison record; digital evidence additionally includes own implementation, formula and digital results for all six cases. Reading the worked answer demonstrates neither route. Partial-charge/mobility models explain qualitative interactions, not a complete solubility/energy balance or exact geometry. Transfer: '+cases[13]['authoredWorkedFreshTransferResponse']['en']

overrides=[]
for index in [0,1,12,13]:
    c=cases[index]
    replacement={'sourceOperatorScopeContractDe':doc_de if index<2 else c['originalWholeCase']['sourceOperatorScopeContractDe']+'\n'+model_de,'sourceOperatorScopeContractEn':doc_en if index<2 else model_en+' Concrete model knowledge is supplied or linked to a suitable content goal; Dalton knowledge is not a universal prerequisite. Successful work must remain hypothesis-guided, earlier-stage contributions remain partial pending stage/target decisions, and the goal asks for justified model criticism rather than claiming already completed model development.'}
    if index==13:
        replacement['analogueAlternativeLearnerTask']={'de':brief['taskDemandDe'],'en':brief['taskDemandEn']}
        replacement['analogueOrDigitalExpectedPerformance']={'de':brief['expectedPerformanceDe'],'en':brief['expectedPerformanceEn']}
        replacement['requiredAssessmentCriteriaOverride']=copy.deepcopy(c['originalWholeCase']['requiredAssessmentCriteria'])
        replacement['requiredAssessmentCriteriaOverride'][1]['meaning']={'de':'In der gewählten analogen Alternative: eigene Kartenanordnung und manuelle Regelprüfung. Im gewählten digitalen Originalfall: eigene analoge Anordnung UND eigene digitale Implementation mit allen sechs Checks. Die ursprünglichen Hypothesen-/Bindungs- und Grenzkriterien bleiben verbindlich.','en':'In the selected analogue alternative: own card arrangement and manual rule checks. In the selected original digital case: own analogue arrangement AND own digital implementation with all six checks. Original hypothesis/bonding and limitation criteria remain mandatory.'}
    overrides.append({'goalId':c['operativeGoalId'],'caseKey':c['caseKey'],'originalArchiveBinding':c['originalWholeCasePointer'],'originalWholeCasePreservedExactly':True,'applyToOperativeViewOnly':True,'replacesOriginalScopeContract':True,'selectedOriginalDigitalTaskAndRubricUnchangedWhenDigitalRouteChosen':index==13,'replacementFields':replacement})
write('four-targeted-operative-case-scope-overrides.author-candidate.json',{'schemaVersion':1,'role':'Explicit operative successor overrides; original14 archived whole cases unchanged','entries':overrides,'noOriginalCaseBodyChanged':True,'noPartnerSourceDutyWaived':True,'status':'ai_candidate','reviewStatus':'needs_human_review','humanApproval':False,'humanTrial':False,'actualLearnerPerformance':False,'strictGain':0})

raw_cal=(OLD/'finite-materials/calibration.synthetic.csv').read_text()
new_cal=raw_cal.replace(',P2,',',P-2,')
assert new_cal.count(',P-2,')==6 and ',P2,' not in new_cal
textwrite('calibration.device-P-2.synthetic.v2.csv',new_cal)
textwrite('analogue-rule-comparison.blank.v2.tsv','test_id\tion_label\tion_charge\tfacing_end\tfacing_partial_charge\tlearner_card_arrangement\tlearner_manual_rule_result\tcomparison_with_other_model_and_observation\tmodel_limit\n'+'\n'.join([f'{i+1}\t{ion}\t{charge}\t{end}\t{partial}\t\t\t\t' for i,(ion,charge,end,partial) in enumerate([('Na+',1,'O-end',-1),('Na+',1,'H-end',1),('Cl-',-1,'O-end',-1),('Cl-',-1,'H-end',1),('U',0,'O-end',-1),('U',0,'H-end',1)])])+'\n')
write('device-identifier-literal-correction.author.json',{'schemaVersion':1,'oldMaterial':bind(OLD/'finite-materials/calibration.synthetic.csv'),'newMaterial':bind(OWN/'calibration.device-P-2.synthetic.v2.csv'),'originalWholeD2Case':cases[1]['originalWholeCasePointer'],'oldDeviceToken':'P2','newDeviceToken':'P-2','changedRows':6,'allOtherCsvCellsByteExact':raw_cal.replace(',P2,',',P-2,')==new_cal,'unprovenAliasClaimed':False,'reason':'The original bilingual D2 case explicitly supplies P-2; the new operative material uses that exact ID. The old P2 file remains immutable history.','humanApproval':False})
old_index=json.loads((OLD/'finite-seven-materials.author.index.json').read_text())
new_files=[bind(OWN/'calibration.device-P-2.synthetic.v2.csv') if v['path'].endswith('/calibration.synthetic.csv') else v for v in old_index['files']]
new_files.append(bind(OWN/'analogue-rule-comparison.blank.v2.tsv'))
write('finite-seven-materials.operative-v2.author.index.json',{'schemaVersion':1,'role':'Exact operative successor material index; 9 original files unchanged,1 literal device-ID successor and1 analogue-choice blank supplement','originalIndex':bind(OLD/'finite-seven-materials.author.index.json'),'files':new_files,'originalCalibrationPreserved':bind(OLD/'finite-materials/calibration.synthetic.csv'),'originalDigitalWorksheetUnchanged':bind(OLD/'finite-materials/digital-model-rule.blank.csv'),'originalAnalogueCardsUnchanged':bind(OLD/'finite-materials/analogue-model-cards.printable.tsv'),'softwareOrPracticalPartnerDutiesNotWaived':True,'noRealMeasurementOrPerformanceClaim':True,'humanApproval':False,'strictGain':0})
for p in profiles:
    p['finiteMaterialsBinding']=bind(OWN/'finite-seven-materials.operative-v2.author.index.json')
    if p['goal']['id'] in ['9fc800d1-92d1-5ef6-81c1-33960ae034dd','6c7ce93c-7675-51da-bc0c-7d0257f7ff7d']:
        p['operativeCaseScopeOverrides']=bind(OWN/'four-targeted-operative-case-scope-overrides.author-candidate.json')
write('remaining-seven.normal-positive-profile-bodies.v2.author-candidate.json',{'schemaVersion':1,'role':'New operative P7 author successor; exactly2 profile bodies corrected,5 profile bodies unchanged; no actual-current/native binding','originalProfiles':bind(OLD/'remaining-seven.normal-positive-profile-bodies.author-candidate.json'),'entries':profiles,'changedGoalIds':[profiles[i]['goal']['id'] for i in [0,6]],'wholeOriginal7GoalsUnchanged':True,'original14CasesUnchanged':True,'allOriginal13PartialSourceRelationsAnd8PartnersPreserved':True,'status':'ai_candidate','reviewStatus':'needs_human_review','evidenceLevel':'E1','maximumClaimScope':'G1','humanApproval':False,'humanTrial':False,'actualLearnerPerformance':False,'wholeSource19Status':'HOLD','strictGain':0})
specs=[{'goalId':p['goal']['id'],'reason':'Author successor: retain all original whole goal/source/partner/operator duties; only exact targeted C9 assistance, analogue OR digital essential-performance contract and literal D2 device identifier are remediated. No independent/native review or learner performance claimed.','evidenceLevel':'E1','maximumClaimScope':'G1','dissent':['Whole Source19, current source/course/target and actual native D/P/A/M/V remain pending independent validation.'],'profile':p['profile']} for p in profiles]
write('remaining-seven.normal-positive-candidate-set.v2.author-candidate.json',{'schemaVersion':1,'authoringContract':'positive-understanding-evidence-candidates-v1','reviewId':'chemie-b008-source19-remaining-seven-targeted-remediation-author-v2','reviewedAt':NOW,'reviewer':'OpenAI Codex author /root/bio_science14_independent_a; precise model variant unexposed; no independent review claimed','goals':specs})
textwrite('author-candidates.v2.jsonl','\n'.join(json.dumps(s,ensure_ascii=False) for s in specs)+'\n')
write('targeted-author-v2.exact-delta-and-boundaries.json',{'schemaVersion':1,'role':'Author correction specification, not a reviewer verdict','changes':[{'goalId':profiles[0]['goal']['id'],'findingCommunicated':'ROOT7-001','fieldsChanged':['profile.variationAxes/source-and-limit DE/EN','both operative documentation case scope-contract DE/EN'],'wholeSourceBoundaries':['C8 guided','C9 non-NTG guided','C9NTG familiar independently/unfamiliar assisted','C10 independent per whole source'],'otherProfileFieldsUnchanged':True},{'goalId':profiles[6]['goal']['id'],'findingCommunicated':'ROOT7-002','fieldsChanged':['essential expectation ID/observablePerformance','requiredExpectationIds','source-and-limit DE/EN','second operative case-brief route choice','both operative model scope-contract DE/EN'],'selectedDigitalCaseOwnImplementationAndSixChecksStillRequired':True,'analogueAlternativeMustUseOwnCardsAndChecks':True,'allSpecialSourceSoftwareAndPracticalDutiesPreserved':True},{'goalId':profiles[0]['goal']['id'],'findingCommunicated':'Independent B7 exact D2 device-ID mismatch communicated by Root','fieldsChanged':['one new CSV device column literal in6 rows P2 toP-2'],'allNumericDataAndOtherCellsUnchanged':True,'aliasInvented':False}],'unchangedFiveProfileBodies':[{'goalId':profiles[i]['goal']['id'],'valueSha256':h(profiles[i]['profile'])} for i in range(1,6)],'original14WholeCaseBodiesByteAndValuePreserved':True,'originalGoalBodiesUnchanged':True,'originalSourceRolesAndPartnerBodiesUnchanged':True,'noNewImagesOrImageReapproval':True,'strictGain':0,'humanApproval':False})
print(json.dumps({'changedProfiles':2,'unchangedProfiles':5,'operativeCaseOverrides':4,'literalDeviceRows':6,'normalCandidateSet':bind(OWN/'remaining-seven.normal-positive-candidate-set.v2.author-candidate.json')}))
