import pathlib,json,hashlib,shutil
R=pathlib.Path('/home/enpasos/projects/skillpilot');Q='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/'
O=R/(Q+'wirtschaft-M4-twelve-labour-whole-science-independent-merge-audit-v1');D=R/(Q+'wirtschaft-M4-twelve-labour-society-one-contract-local-whole-material-author-b-v1')
def bind(p):
 p=pathlib.Path(p);p=p if p.is_absolute() else R/p;raw=p.read_bytes();return {'path':str(p.relative_to(R)),'sha256':hashlib.sha256(raw).hexdigest(),'bytes':len(raw)}
def write(n,j):
 p=O/n;assert not p.exists();p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n');return bind(p)
guard=json.loads((O/'actual-labour-current-binding-and-author-history-external-before-guards.independent.json').read_text());assert all(bind(r['path'])==r for r in guard['files'])
canp=R/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_WIRTSCHAFT.de.json';can=json.loads(canp.read_text());assert len(can['goals'])==597 and bind(canp)['sha256']=='6118557f37604ddd3fa5c5b8a418ee9d0061c570dfeea14a12d29ee7cb4addf3'
base=json.loads((O/'actual-whole-twelve-labour-original-DEEN-goals-P24-and-bodies.independent-intake.json').read_text());cur={g['id']:g for g in can['goals']};pbind=base['inputBindings'][-1];P=json.loads('['+','.join((R/pbind['path']).read_text().splitlines())+']');pb={r['goalId']:r for r in P};assert len(P)==336 and sum(len(x['profile']['applicationCaseBriefs']) for x in P)==685
for r in base['wholeGoalsPAndBodies']:assert cur[r['wholeCurrentGoal']['id']]==r['wholeCurrentGoal'] and pb[r['wholeOriginalP']['goalId']]==r['wholeOriginalP']
hpath=D/'one-real-income-and-education-distribution-separated-essential-author-successor-v3/actual-final-one-real-income-and-education-separate-whole-boundary.author-handoff-v3.json';h=json.loads(hpath.read_text());assert bind(h['wholeFinal12']['path'])==h['wholeFinal12']
schemas=json.loads((O/'actual-final609-production-runtime-schema-and-genuine-missing-task-negative.independent.json').read_text());assert schemas['schemaValid'] and schemas['actualMissingRequiredTaskRejected']
oldcan=json.loads((O/'whole-current609-final-twelve-labour-V3-DRAFT-only-independent-schema-input.inert.json').read_text());assert oldcan['goals'][:597]==can['goals']
works=json.loads((O/'actual-thirtysix-whole-labour-independent-two-case-submissions432-criterion-decisions.json').read_text());remedy=json.loads((O/'actual-one-real-labour-two-field-remedy-three-whole-new-works-and-original20-regrade.independent.json').read_text());calc=json.loads((O/'actual-independent-Fraction-calculations-twelve-rubric-sums-and-rule-classifications.json').read_text());science=json.loads((O/'actual-final-twelve-labour-current-contract-P24-and-whole-material-individual-scientific-decisions.independent.json').read_text())
assert science['actualWholeKEEPCount']==12 and all(x['draftStatusRetained'] for x in science['decisions'])
assert remedy['old20CounterworkActuallyRegraded']['actualFinalV3Points']==14 and len(remedy['actualChangedFields'])==2
end=write('actual-current597-P336685-twelve-contracts-and126-history-byte-endguards.independent.json',{'role':'INDEPENDENT actual endguards; no new historical scientific qualification','actualActiveCAN':bind(canp),'all597OriginalWholeGoalsExact':True,'all336WholeOriginalProfilesAnd685CasesExact':True,'all12CurrentWholeDEENGoalsAnd24OriginalCasesExact':True,'actual126ExternalByteGuardsExact':guard['files'],'actualNew609InertInputRetains597WholeGoalsExact':True,'noActiveCANSEMSourceRegistryOrViewWrites':True,'noCardsImagesOtherSubjectOrRuntimeChanges':True})
helpers=O/'actual-executed-own-review-helpers';helpers.mkdir(exist_ok=True)
for n in ['economics-labour12-read-whole-inputs.py','economics-labour12-independent-intake-calcs-and-sources.py','economics-labour12-independent-whole-works.py','economics-labour12-independent-science-and-remedy.py','economics-labour12-independent-runtime-schema-and-negative.mjs','economics-labour12-independent-final-seal.py']:
 p=pathlib.Path('/tmp')/n;target=helpers/n;assert not target.exists();shutil.copyfile(p,target)
commands=write('actual-independent-review-command-exits-and-honest-score-assertion-history.json',{'role':'ACTUAL executed command receipts; not forecast outputs','commands':[{'argv':['python','/tmp/economics-labour12-independent-intake-calcs-and-sources.py'],'exit':0,'actualWholeGoals':12,'actualCases':24,'actualOwnFractionChecks':89},{'argv':['python','/tmp/economics-labour12-independent-whole-works.py'],'exit':0,'actualWrittenWholeWorks':36,'actualManualMarks':432},{'argv':['python','/tmp/economics-labour12-independent-science-and-remedy.py'],'initialExit':1,'initialReason':'Expected18sum was incorrectly typed as17; exact before-correction script retained, no successor/final artifacts created by failed run.','correctedExit':0,'actualChangedFields':2,'actualFinalKEEP':12},{'argv':['node','/tmp/economics-labour12-independent-runtime-schema-and-negative.mjs'],'exit':0,'schemaValid':True,'genuineRequiredDETaskNegativeRejected':True},{'argv':['python','/tmp/economics-labour12-independent-final-seal.py'],'actualChecksReachedBeforeSeal':True,'allEndguardsPassed':True}],'incidentalReadOnlyLookupBoundary':'One preliminary guessed registry filename was absent; it was never a science input or write target. Actual provenance files were subsequently resolved and126externalguards checked.'})
files=[bind(p) for p in sorted(O.rglob('*')) if p.is_file()]
manifest=write('actual-final-twelve-labour-independent-portable-evidence.manifest.json',{'role':'INDEPENDENT portable whole evidence manifest','files':files,'externalUnchangedInputs':guard['files'],'noFreshScopeOrSourceCoverageVerdict':True})
final=write('actual-final-twelve-labour-whole-DEEN-science-one-real-remedy-independent-KEEP.handoff.receipt.json',{'role':'INDEPENDENT whole scientific KEEP twelve; original elevenKEEP/oneREVISE preserved; no author tests adopted as independent','subject':'Wirtschaftswissenschaften','wholeForeignFinalAuthorHandoff':bind(hpath),'wholeFinalTwelveDRAFT':h['wholeFinal12'],'wholeScientificDecisions':bind(O/'actual-final-twelve-labour-current-contract-P24-and-whole-material-individual-scientific-decisions.independent.json'),'wholeOriginalElevenKEEPoneREVISEHistory':bind(O/'actual-original-twelve-labour-eleven-whole-KEEP-one-entire-education-absence-REVISE.independent.json'),'wholeOriginal20PASSCounterwork':bind(O/'actual-whole-inequality20point-income-correct-entire-education-distribution-absent.independent-REVISE.json'),'actualBoundedTwoDEENTaskFieldFollowup':bind(O/'actual-one-real-labour-two-field-remedy-three-whole-new-works-and-original20-regrade.independent.json'),'actualWholeDEENTasksSolutionsRubricsCurrentGoalsRead':12,'actualOriginalPCaseCount':24,'actualDistinctOwnCompleteTwoCaseSubmissions':39,'actualWrittenAnswers':234,'actualManualIndividualCriterionMarks':468,'actualFullAndFairSubmissionsPASS':26,'actualCoreCounterworksFAILAfterRemedy':13,'actualOriginalEducationalDistributionAbsence20Now14FAIL':True,'actualSeparateIncomeAbsence20Now14FAIL':True,'actualTwoNewImperfectFairWorksPASS':[18,18],'actualOriginalOtherElevenWholeMaterialBodiesExact':True,'actualOnlyTwoTaskDEENFirstGradingParagraphsChanged':True,'allSolutionsRubricsPointsRequiresCoveredTagsAndDraftStatusExact':True,'actualIndependentFractionChecks':calc['actualFractionCheckCount'],'actualFractionErrors':0,'actualOwnRuleClassifications':6,'actualIndependentRubricSumChecks':12,'actualOwnFreshReadOfficialPrimaryLocators':13,'ownPrimarySelectedReadingBoundaries':bind(O/'actual-thirteen-own-fresh-primary-locators-selected-readings-and-classification-boundaries.independent.json'),'unreadLinkedFullPDFsNotClaimed':True,'actualCurrentRuntimeSchema609PASS':bind(O/'actual-final609-production-runtime-schema-and-genuine-missing-task-negative.independent.json'),'actualGenuineRequiredDETaskNegativeRejected':True,'metadataClosedSchemaOrWholeScopeCompilerPASSClaim':False,'actualCurrentWholeEndguards':end,'actualCommandExits':commands,'actualPortableManifest':manifest,'actualOwnSimulatedCareerRecordWritten':True,'actualObservedRealPlacementOrLearnerPerformance':False,'meaningfulPartialPerformanceAnywhereCounts':True,'noTaskQuotaPerfectWorkOrFixedJudgmentRequirement':True,'allTwelveStatusRemains':'draft','statusNavScopeSEMSourceOrHumanApproval':False,'newOrdinaryGoalsProfilesOrCases':0,'newCardsImagesRuntimeOrOtherSubjectChanges':0,'activeWrites':0,'strictNetGain':0,'M4M6M7OrPublicationClaim':False})
print(json.dumps({'finalHandoff':final,'actualFilesInPortableManifest':len(files),'externalGuards':126,'wholeScientificKEEP':12,'finalWholeBody':h['wholeFinal12'],'activeWrites':0}))
