// SPDX-License-Identifier: Apache-2.0
// Materialize genuine sealed A/B judgments only; this integrator performs no new scientific review.
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs'
import {resolve,dirname,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import {normalizeGoalVisualizationAiReview,isGoalVisualizationAiApproved} from '../../../../../../../app/scripts/goalVisualizationQaModel.ts'
import {fingerprintGoalForPositiveEvidence,fingerprintPositiveGoalEvidenceReviewInput,fingerprintPositiveGoalEvidenceProfile,validatePositiveGoalEvidenceRecordSemantics} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel.ts'
import {buildGoalBookModel,loadGoalBookBuildInputs,stableGoalBookJson} from '../../../../../../../app/scripts/goalBookModel.ts'
const R=resolve('.'),D=dirname(fileURLToPath(import.meta.url)),base=resolve(D,'..'),author=resolve(base,'chemie-q3-two-native-source-roles-resume-technical-20261008-v1'),af=resolve(base,'chemie-q3-two-current-native-independent-a-root-20261008-v1'),bf=resolve(base,'chemie-q3-two-native-source-roles-independent-b-20261008-v1')
const ids=['d9cce642-4f89-57f8-832a-abeb62586195','3eada74b-25b8-55dc-811a-acb473196f53'],REQ=new Map<string,any>()
const sh=(b:Buffer|string)=>'sha256:'+createHash('sha256').update(b).digest('hex'),rp=(p:string)=>relative(R,p),bind=(p:string)=>{const b=readFileSync(p),v={path:rp(p),sha256:sh(b),bytes:b.length};REQ.set(v.path,v);return v},read=(p:string)=>{bind(p);return JSON.parse(readFileSync(p,'utf8'))}
const put=(name:string,v:any)=>{const p=resolve(D,name),b=Buffer.isBuffer(v)?v:Buffer.from(typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');if(existsSync(p))assert.ok(readFileSync(p).equals(b),p);else{mkdirSync(dirname(p),{recursive:true});writeFileSync(p,b,{flag:'wx'})}return bind(p)}
const rows=(p:string)=>{bind(p);return readFileSync(p,'utf8').trim().split('\n').map(l=>JSON.parse(l))}
const guard=read(resolve(D,'current-two-protected-baseline-and-original-pair.technical.guard.json')),can=read(resolve(R,guard.candidateCanonical.path)),by=new Map<string,any>(can.goals.map((g:any)=>[g.id,g])),kinds=read(resolve(R,guard.candidateKinds.path)),oldQA=read(resolve(D,'before/qa.exact.json')),candidateQA=read(resolve(author,'candidate/visualization-qa.current378.only-six-unapproved.inactive.json'))
for(const pair of Object.values(guard.originalGenuinePair)as any[])for(const b of[pair.seal,...pair.verifiedOriginalFiles]){const current=bind(resolve(R,b.path));assert.equal(current.sha256,'sha256:'+b.sha256.replace('sha256:',''));assert.equal(current.bytes,b.bytes)}
const aAtomicPath=resolve(af,'A2.actual-scientific-atomicity.independent-a.addendum.json'),bSciencePath=resolve(bf,'whole-science-P2-and-semantic-atomicity.independent-b.first-verdict.json'),aAtomic=read(aAtomicPath),bScience=read(bSciencePath),aVPath=resolve(af,'actual-two-current-raster.independent-a.first-verdict.json'),bVPath=resolve(bf,'V2-actual-raster-and-native-PDF.independent-b.first-verdict.json'),aV=read(aVPath),bV=read(bVPath)
assert.equal(aAtomic.blindToIndependentB,true);assert.equal(bScience.blindToNewNativeA,true);assert.equal(aV.blindToIndependentBNativeAndVisual,true);assert.equal(bV.blindToNewNativeA,true)
const observedAt=[guard.originalGenuinePair.a.sealedAt,guard.originalGenuinePair.b.sealedAt].sort().at(-1)!
// Exact ordinary semantic-atomicity-v1 payload. The standard CLI validates the materialized records.
const norm=(v:any)=>String(v??'').normalize('NFKC').replace(/\s+/g,' ').trim(),stable=(v:any):string=>Array.isArray(v)?`[${v.map(stable).join(',')}]`:v&&typeof v==='object'?`{${Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>JSON.stringify(k)+':'+stable(x)).join(',')}}`:JSON.stringify(v)
const atomFP=(g:any)=>sh(stable({ruleVersion:'semantic-atomicity-v1',goalId:g.id,shortKey:g.shortKey??'',title:norm(g.title),titleEn:norm(g.titleEn),description:norm(g.description),descriptionEn:norm(g.descriptionEn),phase:norm(g.dimensionTags?.phase),area:norm(g.dimensionTags?.area),topicCode:norm(g.dimensionTags?.topicCode),nodeKind:norm(g.nodeKind)}))
const aid='chemie-q3-two-source-roles-genuine-reviewed-atomicity-adoption-20261008-v1'
const A=ids.map(i=>{const ar=aAtomic.records.find((r:any)=>r.goalId===i),br=bScience.goals.find((r:any)=>r.goalId===i);assert.ok(ar&&br);assert.equal(ar.status,'atomic');assert.equal(ar.semanticAtomic,true);assert.ok(br.semanticAtomicityDecision.startsWith('PASS_SEMANTIC_ATOMIC:'));assert.equal(br.wholeScienceAndNativePVerdict,'PASS_BOUNDED_AUTHORED_E1_G1');assert.deepEqual(ar.wholeCurrentGoal,by.get(i));assert.deepEqual(br.wholeCurrentGoal,by.get(i));return{schemaVersion:1,reviewId:aid,ruleVersion:'semantic-atomicity-v1',landscapeId:can.landscapeId,goalId:i,fingerprint:atomFP(by.get(i)),status:'atomic',semanticAtomic:true,reviewedAt:observedAt,reviewer:'Technical materializer of actual independent Root-A addendum and separate blind B whole-science atomicity judgments; not a new scientific reviewer',reason:'Die echten getrennten aktuellen Urteile begründen die Atomarität dieses unveränderten ganzen DE/EN-Ziels. A: '+ar.reason+' B: '+br.semanticAtomicityDecision+' Diese technische Materialisierung erzeugt keine neue fachliche Prüfung; Erstseals bleiben exakt. Alle49 begrenzten Quellenrollen und16 Gesamtpflicht-HOLDs bleiben erhalten.'}})
put('atomicity/current-two.genuine-reviewed.records.jsonl',A.map(r=>JSON.stringify(r)).join('\n')+'\n')
const Acfg={schemaVersion:1,reviewId:aid,ruleVersion:'semantic-atomicity-v1',landscapeId:can.landscapeId,landscapePath:guard.candidateCanonical.path,reviewPath:rp(resolve(D,'atomicity/current-two.genuine-reviewed.records.jsonl')),scope:{label:'Two current genuinely independent atomicity judgments; technical record materialization only',leafGoalIds:ids}}
put('atomicity/current-two.inactive.config.json',Acfg);put('atomicity/current-two.future-active.config.json',{...Acfg,landscapePath:guard.before.canonical.active.path})
const qa=structuredClone(oldQA),resourceDigests:Record<string,string>={},qaChecks=[]
assert.equal(qa.records.length,379)
for(const i of ids){const ar=aV.records.find((r:any)=>r.goalId===i),br=bV.goals.find((r:any)=>r.goalId===i),r=qa.records.find((q:any)=>q.goalId===i),prior=oldQA.records.find((q:any)=>q.goalId===i),source=candidateQA.records.find((q:any)=>q.goalId===i);assert.ok(ar&&br&&r&&source);assert.ok(ar.decision.startsWith('KEEP_ACTUAL_'));assert.ok(br.decision.startsWith('accepted_pilot'));assert.equal(br.grossScientificBlockerFound,false)
 const human=Object.fromEntries(Object.entries(prior).filter(([k])=>k.startsWith('human')));if(i===ids[0])Object.assign(r,source)
 const link=by.get(i).resourceLinks.find((l:any)=>l.type==='goal-visualization'&&l.role==='primary'),ext=i===ids[0]?'png':'jpg',image=resolve(D,'selected-images',i+'.'+ext),digest=bind(image).sha256;assert.equal(r.assetSha256,digest);assert.equal(ar.assetSha256.replace('sha256:',''),digest.replace('sha256:',''));assert.equal(br.actualAsset.sha256.replace('sha256:',''),digest.replace('sha256:',''));r.imageUrl=link.url;r.publicAssetPath='app/public'+link.url;r.canonicalAssetPath=link.url.replace('/assets/goal-visualizations/','curricula/DE/Gymnasium/visualizations/');r.visualizationState='available';r.missingReason=''
 Object.assign(r,human,normalizeGoalVisualizationAiReview({aiApproved:'yes',aiApprovedAssetSha256:digest,aiReviewedAt:observedAt,aiReviewer:'Actual independent Root-A and separate blind B native-page/full-raster reviewers; technical materialization only',aiNotes:i===ids[0]?'Both genuine independent actual raster and native-page judgments KEEP the corrected catalyst PNGv2, including full image and360/680 displays. Historical original JPEG remains retained. Actual generator provenance and generation attempts remain separate; generation is not approval. No human approval or trial.':'Both genuine independent actual full original JPEG and360/680/native-page judgments KEEP the image. Exact original raster and provider retained independently of its format/generator. Current image-specific caption/alt text were reviewed in the native input. No human approval or trial.'},digest));assert.ok(isGoalVisualizationAiApproved(r));resourceDigests[link.url]=digest
 assert.deepEqual(Object.fromEntries(Object.entries(r).filter(([k])=>k.startsWith('human'))),human);put('assets/goal-visualizations/chemie/'+i+'/'+i+'.'+ext,readFileSync(image));qaChecks.push({goalId:i,actualAsset:bind(image),independentA:bind(aVPath),independentB:bind(bVPath),exactDigestIndependentApproval:true,humanFieldsExact:true})
}
for(const r of qa.records){const prior=oldQA.records.find((q:any)=>q.goalId===r.goalId);assert.ok(prior);if(!ids.includes(r.goalId))assert.deepEqual(r,prior);assert.deepEqual(Object.fromEntries(Object.entries(r).filter(([k])=>k.startsWith('human'))),Object.fromEntries(Object.entries(prior).filter(([k])=>k.startsWith('human'))))}
const qaPath=put('candidate/visualization-qa.current378.paired-two.future-active.json',qa)
const aPPath=resolve(af,'P2-current-full-profile.independent-a.review.jsonl'),bPPath=resolve(bf,'P2-actual-independent-b-candidate.records.jsonl'),aP=rows(aPPath),bP=rows(bPPath),originals=rows(resolve(author,'positive/P2-current-whole-profiles-real-resource-native-author.jsonl')),ajv=new Ajv2020({allErrors:true,strict:true});addFormats(ajv);const validP=ajv.compile(read(resolve(R,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json'))),pChecks=[]
for(const r of aP){const br=bP.find((q:any)=>q.goalId===r.goalId),original=originals.find((q:any)=>q.goalId===r.goalId),goal=by.get(r.goalId),digests=Object.fromEntries(goal.resourceLinks.filter((l:any)=>l.type==='goal-visualization').map((l:any)=>[l.url,resourceDigests[l.url]]));assert.ok(br&&original);assert.deepEqual(r.profile,br.profile);assert.deepEqual(r.profile,original.profile);assert.equal(r.status,'needs_human_review');assert.equal(r.reviewAuthority,'ai_candidate');assert.equal(r.evidenceLevel,'E1');assert.equal(r.maximumClaimScope,'G1');assert.deepEqual(r.reviewRunIds,[]);assert.equal(r.goalFingerprint,fingerprintGoalForPositiveEvidence(goal,'curricularAtomic'));assert.equal(r.reviewInputFingerprint,fingerprintPositiveGoalEvidenceReviewInput(goal,r.reviewCriteriaFingerprint,digests,'curricularAtomic'));assert.equal(r.profileFingerprint,fingerprintPositiveGoalEvidenceProfile(r.profile));assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(r,goal,digests,'curricularAtomic'),[]);assert.ok(validP(r),ajv.errorsText(validP.errors));pChecks.push({goalId:r.goalId,exactIndependentARowReused:true,bothActualIndependentWholeProfilesMatch:true,allProfileAndCaseBodiesExact:true,goalFingerprint:r.goalFingerprint,reviewInputFingerprint:r.reviewInputFingerprint,profileFingerprint:r.profileFingerprint,nativeSchemaAndSemanticErrors:0,reviewRunIds:[],independentBRunIdNotImportedAsPManifest:true})}
assert.deepEqual(aP.map(r=>r.goalId),ids)
const pPath=put('positive/current-two.exact-independent-a-reviewed.jsonl',readFileSync(aPPath)),baseP=read(resolve(author,'positive/P2-current-real-resource.inactive.config.json')),criteriaPath=put('positive/current-review-criteria.exact.md',readFileSync(resolve(R,baseP.reviewCriteriaPath)))
const pConfig={...baseP,reviewId:aP[0].reviewId,landscapePath:guard.before.canonical.active.path,semanticKindLedgerPath:guard.before.kinds.active.path,reviewCriteriaPath:criteriaPath.path,reviewPath:pPath.path,reviewRunManifestPaths:[],reviewedResourceTypes:['goal-visualization'],requireApproved:false,scope:{label:'Two actual independent A whole E1/G1 reviews also independently verified by B; whole16 source holds retained; no human approval',goalIds:ids}}
put('positive/current-two.future-active.config.json',pConfig)
const inactiveKinds={...kinds,sourceLandscapePath:guard.candidateCanonical.path};assert.deepEqual(inactiveKinds.decisions,kinds.decisions);const inactiveKindsPath=put('candidate/semantic-kinds.current480.path-only.inactive.json',inactiveKinds);put('positive/current-two.inactive.config.json',{...pConfig,landscapePath:guard.candidateCanonical.path,semanticKindLedgerPath:inactiveKindsPath.path})
const validCfg=ajv.compile(read(resolve(R,'contracts/goal-evidence/v2/goal-evidence-review-config.schema.json')));assert.ok(validCfg(pConfig),ajv.errorsText(validCfg.errors))
// The unchanged normal model compiler verifies all378 whole pages against the actual A/B-reviewed native frame.
const beforeInput=await loadGoalBookBuildInputs(rp(resolve(author,'before/full378.actual-loader.config.json')),R);assert.equal(beforeInput.model.pages.length,378)
const digests:Record<string,string>={};for(const q of qa.records)if(q.visualizationState==='available'){const image=ids.includes(q.goalId)?resolve(D,'selected-images',q.goalId+(q.goalId===ids[0]?'.png':'.jpg')):resolve(R,q.publicAssetPath);const digest=bind(image).sha256;assert.equal(digest,q.assetSha256);digests[q.imageUrl]=digest}
const config={...beforeInput.config,landscapePath:guard.candidateCanonical.path,semanticKindLedgerPath:inactiveKindsPath.path,goalVisualizationQaPath:qaPath.path,outputPath:rp(resolve(D,'native/current378.paired-two.actual-model.json'))};put('candidate/current378.paired-two.inactive-book.config.json',config)
const after=buildGoalBookModel({landscape:can,compositionView:read(resolve(R,config.compositionViewPath)),semanticKindLedger:inactiveKinds,goalVisualizationQa:qa,goalVisualizationAssetDigests:digests,evidenceReviewSources:[],config}as any),reviewed=read(resolve(author,'native/full378-candidate.actual-api.book-model.json'));assert.equal(after.pages.length,378)
for(const page of after.pages){const expected=reviewed.pages.find((p:any)=>p.goalId===page.goalId);assert.ok(expected);assert.equal(stableGoalBookJson(page),stableGoalBookJson(expected),'Current whole page differs from actual independently reviewed frame '+page.goalId);if(!ids.includes(page.goalId))assert.equal(stableGoalBookJson(page),stableGoalBookJson(beforeInput.model.pages.find(p=>p.goalId===page.goalId)),'Other376 whole pages changed '+page.goalId)}
put('native/current378.paired-two.actual-model.json',after)
put('checks/genuine-A2-P2-QA2-and-whole-current-native-adoption.actual.json',{actualAtomicityA:bind(aAtomicPath),actualWholeScienceAtomicityB:bind(bSciencePath),actualPositiveA:bind(aPPath),actualPositiveB:bind(bPPath),genuineA2RowsMaterializedFromActualJudgments:2,selectedExistingARecordsActuallyAbsent:true,actualP2ClosedSchemaAndNativeSemanticErrors:0,actualP2ConfigSchemaErrors:0,independentARowsReusedByteExactly:true,allWholeProfileAndFourDEENCaseBodiesExact:true,BRunIdsNotUsedAsPManifests:true,P:pChecks,QA:qaChecks,actualAll378WholePagesExactToA_BReviewedFrame:true,other376BeforeWholePagesExact:true,other478BeforeWholeCanonicalGoalsExact:true,other377WholeRawQARowsExact:true,all379HumanFieldsExact:true,all378MemoryRowsCardsAndSevenScopesExactReuse:true,sourceAll49Duties259PartnerRowsAnd16HoldsExactRetained:true,ordinaryOperativeP2CLI:'Pending guarded Root PNG installation; actual normal native API/schema/semantics0 verified separately',noScientificReviewByTechnicalIntegrator:true,activeWrites:0,strictGainClaimed:0,humanApproval:false,humanTrial:false})
put('checks/genuine-A2-P2-QA2-declared-inputs.actual.json',{files:[...REQ.values()]})
console.log(JSON.stringify({actualA2FromTwoGenuineScientificJudgments:true,P2ExactIndependentARowsClosedSchemaNativeErrors:0,QA2ExactDigestIndependentApproval:true,actualAll378WholePagesExactToReviewed:true,other478WholeCanon376WholePages377RawQA379HumanFieldsExact:true,source49_259_16HoldsRetained:true,actualP2PublicCLI:'pending Root reviewed installation',activeWrites:0,strictGain:0}))
