// SPDX-License-Identifier: Apache-2.0
// Technical integration of actual sealed scientific judgments, no reviewer run.
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync,existsSync,copyFileSync,symlinkSync} from 'node:fs'
import {dirname,resolve,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import {buildGoalBookModel,fingerprintSemanticKindSourceGoal,loadGoalBookBuildInputs,stableGoalBookJson} from '../../../../../../../app/scripts/goalBookModel'
import {buildGoalBookOriginalSources} from '../../../../../../../app/scripts/goalBookOriginalSources'
import {validatePositiveGoalEvidenceRecordSemantics} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel'
const root=resolve('.'),own=dirname(fileURLToPath(import.meta.url)),base=resolve(own,'..'),old=resolve(base,'../2026-10-07')
const author=resolve(base,'biologie-flora-fauna20-amnion14-raster-native-targeted-author-root-v3'),oldAuthor=resolve(old,'biologie-flora-fauna20-final-raster-native-author-root-20261007-v1')
const srcA=resolve(base,'biologie-flora-fauna20-final-raster-native-independent-a-20261008-v1'),srcB=resolve(base,'biologie-flora-fauna20-final-raster-native-independent-b-20261008-v1')
const targetA=resolve(base,'biologie-flora-fauna20-amnion14-targeted-independent-a-20261008-v3'),targetB=resolve(base,'biologie-flora-fauna20-amnion14-targeted-independent-b-20261008-v2'),gid14='321ea315-37fe-5f9e-8fa8-dd631bb447c7'
const sha=(b:Buffer|string)=>'sha256:'+createHash('sha256').update(b).digest('hex'),normalize=(s:string)=>'sha256:'+s.replace(/^sha256:/u,''),declared=new Map<string,any>()
const bind=(p:string)=>{const b=readFileSync(p);return {path:relative(root,p),sha256:sha(b),bytes:b.length}}
const bytes=(p:string)=>{declared.set(p,bind(p));return readFileSync(p)},read=(p:string)=>JSON.parse(bytes(p).toString('utf8'))
const write=(p:string,v:any)=>{mkdirSync(dirname(p),{recursive:true});const b=Buffer.isBuffer(v)||typeof v==='string'?v:JSON.stringify(v,null,2)+'\n';if(existsSync(p)){assert.equal(sha(readFileSync(p)),sha(b),'Existing inactive artifact cannot silently change');return}writeFileSync(p,b,{flag:'wx'})}
const verify=(dir:string,name:string,expected:string)=>{const p=resolve(dir,name);assert.equal(bind(p).sha256,normalize(expected));const seal=read(p),rows=seal.frozenFiles??[...(seal.inputFiles??seal.inputs??[]),...(seal.ownOutputFiles??seal.outputs??[])];for(const e of rows){const q=existsSync(resolve(root,e.path))?resolve(root,e.path):resolve(dir,e.path);assert.equal(bind(q).sha256,normalize(e.sha256));if(e.bytes!==undefined)assert.equal(bind(q).bytes,e.bytes)}return {seal:bind(p),verifiedPayloads:rows.length}}
const imageRoot=resolve(root,'curricula/DE/Gymnasium/quality/goal-visualization-review/biologie-flora-fauna20-image-author-root-20261007-v1')
const seals={Author194:verify(imageRoot,'final-flora-fauna20-raster-native-author-input.freeze.json','a0e466c3ecb503ee73188c39a1545fd4a91e3adc7a321081f040b7a233b1f180'),AuthorV4:verify(author,'targeted-amnion14-whole-native-author-input.freeze.json','8a3e4229e784f1b43bf401096f4d5920c062423e088322f320d52eb014495db2'),AOriginal20:verify(srcA,'completed-native-D20-P20.independent-a.final.freeze.json','9ffe99c7896a78c6d5c5aa595e28ab03845126c2ccfabba85556311dc02e5d31'),BOriginal20:verify(srcB,'independent-b.completed-flora-fauna20.exact-input-output.first.freeze.json','793f049c0a0e3539204e4b67c333afb0f658c31f955e61ffceba48865de308b2'),ATarget14:verify(targetA,'first-final-v4-D-P-V14.independent-a.exact.freeze.json','884182241dd5318455722a3de1fd13bf362a12d0d8ee211a3eaf094862ab6c9a'),BTarget14:verify(targetB,'independent-b.completed-amnion14-v4-targeted.exact-input-output.first.freeze.json','afb57629c4fbbf28b62bc676d90991b2c46908025ca91196d03050c3e30af1f3')}
const plan=read(resolve(own,'candidate/twenty-exact-resource-link-patches.guarded.json'))
for(const key of ['canonical','kinds','qa'])assert.equal(sha(bytes(resolve(root,plan.beforeBindings[key].path))),plan.beforeBindings[key].sha256,'Active '+key+' moved: explicit rebase required')
const canonicalPath=resolve(own,'candidate/canonical.future-active.json'),landscape=read(canonicalPath),before=read(resolve(own,'before/canonical.json')),ids=plan.selectedGoalIds as string[],selected=new Set(ids),goalBy=new Map<string,any>(landscape.goals.map((g:any)=>[g.id,g]))
assert.equal(landscape.goals.length,474);assert.equal(ids.length,20)
for(const g of before.goals)if(!selected.has(g.id))assert.deepEqual(goalBy.get(g.id),g)
const sourceImageManifest=resolve(author,'selected-twenty-one-targeted-image-correction.author.json');assert.equal(bind(sourceImageManifest).sha256,normalize('ed28beaccce6a422b090be481bb6344b996210fd064a8f808f75f7b0a7073b1f'))
const images=read(sourceImageManifest).images,imageBy=new Map<string,any>(images.map((i:any)=>[i.goalId,i])),aV=read(resolve(srcA,'actual-twenty-V-first-independent-a.verdicts.json')),bV=read(resolve(srcB,'V20.actual-image-width-native-page.independent-b.json')),a14=read(resolve(targetA,'actual-amnion14-v4-V-first-independent-a.verdict.json')),b14=read(resolve(targetB,'V14.actual-v4-image-width-native-page.independent-b.first.json'))
const aVby=new Map<string,any>(aV.records.map((r:any)=>[r.goalId,r])),bVby=new Map<string,any>(bV.verdicts.map((r:any)=>[r.goalId,r]));assert.equal(aVby.size,20);assert.equal(bVby.size,20)
assert.equal(bVby.get(gid14).decision,'HOLD');assert.equal(bVby.get(gid14).status,'OPEN_LABEL_ALLOCATION')
assert.equal(a14.decision,'KEEP');assert.equal(a14.scopedMachineVisualVerdict,'PASS');assert.equal(b14.decision,'KEEP');assert.equal(b14.status,'PASS');assert.deepEqual(a14.openFindings,[])
const futureQa=read(resolve(own,'before/qa.json')),qaBy=new Map<string,any>(futureQa.records.map((r:any)=>[r.goalId,r])),assetLineage:any[]=[]
const exact=(e:any)=>{assert.equal(bind(resolve(root,e.path)).sha256,normalize(e.sha256));if(e.bytes!==undefined)assert.equal(bind(resolve(root,e.path)).bytes,e.bytes)}
for(const id of ids){const img=imageBy.get(id),a=aVby.get(id),b=bVby.get(id),g=goalBy.get(id),expected=normalize(img.sha256),is14=id===gid14;exact({path:img.path,sha256:img.sha256})
 let actualA:any,actualB:any,observationsA:string,observationsB:string,reviewedAt:string
 if(is14){exact(a14.actualOriginal);exact(b14.actualFullImage);assert.equal(a14.actualOriginal.path,img.path);assert.equal(b14.actualFullImage.path,img.path);assert.equal(a14.actualFullOriginalInspected,true);assert.equal(a14.actual360And680ChromiumImageCapturesInspected,true);assert.equal(a14.actualWholeNativePage03Inspected,true);assert.equal(b14.actualFourViewsRead,true)
  for(const e of [...a14.actualWidthCaptures.captures,a14.actualNativePdf,a14.actualWholeNativePage03Capture,...b14.actualWidthCaptures,b14.actualNativePdf,b14.actualNativePdfPage])exact(e)
  assert.deepEqual(a14.actualNativePdf,b14.actualNativePdf);assert.deepEqual(a14.actualWholeNativePage03Capture,b14.actualNativePdfPage)
  actualA=a14;actualB=b14;observationsA=a14.substantiveActualObservationsDe+' '+a14.formatAndLegibilityDe+' '+a14.nativeContextDe;observationsB=b14.concreteObservation;reviewedAt=[a14.recordedAt,b14.reviewedAt].sort().at(-1)!
 }else{assert.equal(a.machineCandidateDecision,'KEEP');assert.equal(a.scientificAndVisualVerdict,'PASS');assert.equal(b.decision,'KEEP');assert.equal(b.status,'PASS');assert.equal(a.actualObservedFullRaster.path,img.path);assert.equal(b.actualFullImage.path,img.path);assert.equal(normalize(a.actualObservedFullRaster.sha256),expected);assert.equal(normalize(b.actualFullImage.sha256),expected);assert.equal(b.actualImageViewed,true);assert.equal(b.actualBothWidthsViewed,true);assert.equal(b.actualCompleteNativePageViewed,true)
  assert.deepEqual(a.actualObservedNativePdfPage,b.actualNativePdfPage)
  for(const e of [...a.actualObservedChromiumCaptures,a.actualObservedNativePdfPage.capture,a.actualObservedNativePdfPage.actualPdf,...b.actualWidthCaptures])exact(e)
  actualA=a;actualB=b;observationsA=a.substantiveActualObservationsDe+' '+a.nativePageObservation;observationsB=b.scientificLabelArrowPerspectiveObservation+' '+b.widthReadabilityObservation+' '+b.nativePageObservation;reviewedAt=[aV.recordedAt,bV.reviewedAt].sort().at(-1)!
 }
 const captures=is14?b14.actualWidthCaptures:b.actualWidthCaptures;assert.equal(captures.length,2);for(const e of captures){assert.ok([360,680].includes(e.width));assert.equal(e.measured.renderedWidth,e.width);assert.equal(e.measured.objectFit,'contain')}
 const q=qaBy.get(id);assert.equal(q.visualizationState,'missing');assert.equal(q.humanApproved,'no');assert.equal(q.title,g.title);assert.equal(q.description,g.description)
 const patch=plan.rows.find((r:any)=>r.goalId===id);Object.assign(q,{visualizationState:'available',missingReason:'',imageUrl:patch.imageUrl,publicAssetPath:patch.futureAppPNG,canonicalAssetPath:patch.futureCanonicalPNG,assetSha256:expected,aiApproved:'yes',aiApprovedAssetSha256:expected,aiReviewedAt:reviewedAt,aiReviewer:'Two actual independently sealed A/B machine reviewers; technical synthesis only, no human approval',aiNotes:'A: '+observationsA+' B: '+observationsB+' Exact A/B seals: '+(is14?seals.ATarget14.seal.path:seals.AOriginal20.seal.path)+'; '+(is14?seals.BTarget14.seal.path:seals.BOriginal20.seal.path)+'. Original Ord14 HOLD and preceding rejected variants preserved. Actual Chromium sizing captures are not physical device or whole app acceptance. No human approval or trial.'})
 for(const [k,v]of Object.entries(read(resolve(own,'before/qa.json')).records.find((r:any)=>r.goalId===id)))if(k.startsWith('human'))assert.deepEqual(q[k],v)
 const dst=resolve(own,'selected-images',id+'.png');mkdirSync(dirname(dst),{recursive:true});if(!existsSync(dst))copyFileSync(resolve(root,img.path),dst);assert.equal(bind(dst).sha256,expected)
 const alias=resolve(own,q.imageUrl.replace(/^\//u,''));mkdirSync(dirname(alias),{recursive:true});if(!existsSync(alias))symlinkSync(relative(dirname(alias),dst),alias)
 assetLineage.push({goalId:id,sourceRaster:bind(resolve(root,img.path)),selectedRaster:bind(dst),originalPrompt:bind(resolve(root,img.promptPath)),originalGenerationProvenance:bind(resolve(root,img.toolProvenancePath)),targetPublicPath:q.publicAssetPath,targetCanonicalPath:q.canonicalAssetPath,altDe:img.altDe,altEn:img.altEn,sourceIndependentAAssetRow:actualA,sourceIndependentBAssetRow:actualB,actualBothIndependentViews:['full','360','680','native-PDF-page'],pairedFinalSeals:is14?[seals.ATarget14,seals.BTarget14]:[seals.AOriginal20,seals.BOriginal20],unchangedHistorical19:is14?false:true,machineApprovalOnly:true})
}
for(const r of read(resolve(own,'before/qa.json')).records)if(!selected.has(r.goalId))assert.deepEqual(qaBy.get(r.goalId),r)
write(resolve(own,'candidate/visualization-qa.future-active.json'),futureQa)
const inertQa=structuredClone(futureQa);for(const r of inertQa.records)if(selected.has(r.goalId)){r.publicAssetPath=relative(root,resolve(own,'selected-images',r.goalId+'.png'));r.canonicalAssetPath=r.publicAssetPath}write(resolve(own,'candidate/visualization-qa.inactive-native.json'),inertQa)
write(resolve(own,'candidate/exact-selected-asset-provenance-and-paired-machine-approval.technical.json'),{seals,sourceManifest:bind(sourceImageManifest),rows:assetLineage,unrelatedQaRecordsExact:true,noExistingGoodAssetReplaced:true,oneActualEvidencedAmnionCorrection:true,humanApproval:false,humanTrial:false,activeWrites:0})
const kinds=read(resolve(own,'before/kinds.json')),inertKinds=read(resolve(own,'candidate/semantic-kinds.inactive-native.json'));assert.equal(kinds.counts.curricularAtomic,391);assert.equal(kinds.counts.total,474)
for(const d of kinds.decisions)assert.equal(fingerprintSemanticKindSourceGoal(goalBy.get(d.goalId)),d.sourceFingerprint,'All474 classifications must stay current without row adjustment')
const activeFullCfg=resolve(old,'biologie-human20-reviewed-integration-preparation-technical-20261007-v1/native-full391.future-active.config.json'),actual=await loadGoalBookBuildInputs(activeFullCfg);assert.equal(actual.model.pages.length,391)
const inertCfg={...actual.config,landscapePath:relative(root,canonicalPath),semanticKindLedgerPath:relative(root,resolve(own,'candidate/semantic-kinds.inactive-native.json')),goalVisualizationQaPath:relative(root,resolve(own,'candidate/visualization-qa.inactive-native.json')),evidenceReviewPaths:[],outputPath:relative(root,resolve(own,'native-full391.current474-inactive.book-model.json'))},futureCfg={...actual.config,evidenceReviewPaths:[],outputPath:relative(root,resolve(own,'native-full391.future-active.pure.book-model.json'))}
const manifest=read(resolve(root,inertCfg.compositionViewManifestPath)),digests:Record<string,string>={};for(const r of inertQa.records)if(r.visualizationState==='available')digests[r.imageUrl]=sha(bytes(resolve(root,r.publicAssetPath)))
const common={landscape,compositionViewManifest:manifest,compositionViewSources:manifest.sourcePaths.map((p:string)=>({path:p,view:read(resolve(root,p))})),navigationView:read(resolve(root,manifest.navigationViewPath)),durationModelPolicy:read(resolve(root,manifest.durationModelPolicyPath)),goalVisualizationAssetDigests:digests,evidenceReviewSources:[]}
const model=buildGoalBookModel({...common,semanticKindLedger:inertKinds,goalVisualizationQa:inertQa,config:inertCfg}as any),futureModel=buildGoalBookModel({...common,semanticKindLedger:kinds,goalVisualizationQa:futureQa,config:futureCfg}as any)
assert.equal(model.pages.length,391);assert.equal(futureModel.pages.length,391);const oldPages=new Map(actual.model.pages.map(p=>[p.goalId,p])),futurePages=new Map(futureModel.pages.map(p=>[p.goalId,p])),authorFull=read(resolve(author,'native-raster-candidate/full391.book-model.json')),authorPages=new Map<string,any>(authorFull.pages.map((p:any)=>[p.goalId,p]))
assert.deepEqual(new Set(model.pages.filter(p=>p.pageFingerprint!==oldPages.get(p.goalId)?.pageFingerprint).map(p=>p.goalId)),selected)
const compatibility:any[]=[]
for(const p of model.pages){assert.equal(p.pageFingerprint,futurePages.get(p.goalId)!.pageFingerprint)
 if(!selected.has(p.goalId))assert.equal(p.pageFingerprint,oldPages.get(p.goalId)?.pageFingerprint)
 else{const a=authorPages.get(p.goalId),normalized=structuredClone(p),comparison=structuredClone(a);delete normalized.pageFingerprint;normalized.visualization!.qaStatus=a.visualization.qaStatus;delete comparison.pageFingerprint;assert.equal(stableGoalBookJson(normalized),stableGoalBookJson(comparison),'Whole source/context/science fields must exactly match the genuinely reviewed current v4 frame')
 compatibility.push({goalId:p.goalId,actualAuthorWholeFramePageFingerprint:a.pageFingerprint,futureWholeFramePageFingerprint:p.pageFingerprint,allWholeGoalContextSourceScopeFieldsExact:true,actualAssetDigestExact:a.visualization.originalDigest,actualChangedCurrentWholePageFields:['visualization.qaStatus','derived pageFingerprint'],beforeQaStatus:a.visualization.qaStatus,afterQaStatus:p.visualization!.qaStatus,originalNativeD20OrTargetedD1FrameRetained:true,noBlindHistoricalPageHashSubstitution:true})}}
const mappingPaths=read(resolve(root,'app/scripts/config/goal-books/de-gym-biology-national-atlas.inputs.json')).mappingPaths,oldSource=buildGoalBookOriginalSources(actual.model,root,mappingPaths),newSource=buildGoalBookOriginalSources(futureModel,root,mappingPaths);for(const k of Object.keys(oldSource).filter(k=>k!=='bookDigest'))assert.deepEqual((newSource as any)[k],(oldSource as any)[k])
write(resolve(own,'native-full391.current474-inactive.config.json'),inertCfg);write(resolve(own,'native-full391.current474-inactive.book-model.json'),model);write(resolve(own,'native-full391.future-active.config.json'),futureCfg);write(resolve(own,'native-full391.future-active.pure.book-model.json'),futureModel)
write(resolve(own,'checks/full391-exact-unaffected371-and-twenty-approved-state-only.technical.json'),{currentBaseCanonical:plan.beforeBindings.canonical,preparedFutureCanonical:bind(canonicalPath),sourceCanonicalDigestMustUsePreparedFutureBytes:bind(canonicalPath).sha256,all474ClassificationsExact:true,total391:true,other371PagesExactCurrentActive474:true,allPrimarySourceDocumentsClausesScopesAndTitlesExact:true,targetWholeFrameCompatibility:compatibility,noFull391PDFRendered:true,activeWrites:0})
const readRows=(p:string)=>bytes(p).toString('utf8').trim().split('\n').map(s=>JSON.parse(s)),aBinding=read(resolve(srcA,'P20.exact-final-author-input.binding.json'));assert.equal(bind(resolve(root,aBinding.path)).sha256,normalize(aBinding.sha256));assert.equal(aBinding.newProfileScientificAuthorship,false)
const originalA=new Map(readRows(resolve(root,aBinding.path)).map(r=>[r.goalId,r])),originalB=new Map(readRows(resolve(srcB,'P20.current-raster-independent-b.review.jsonl')).map(r=>[r.goalId,r])),currentRows=readRows(resolve(author,'native-raster-candidate/P20.actual-raster-author.review.jsonl')),sourceOld=new Map(readRows(resolve(oldAuthor,'native-raster-candidate/P20.actual-raster-author.review.jsonl')).map(r=>[r.goalId,r]))
const aP14=read(resolve(targetA,'P1.exact-inactive-native-api.independent-a.actual.json')),bP14=read(resolve(targetB,'P14.current-v4-independent-b.record.json'));assert.equal(aP14.schemaErrors,0);assert.equal(aP14.semanticErrors,0);assert.equal(aP14.actualVisualVerdict,'PASS');assert.equal(aP14.actualRasterBytesRead,true)
assert.equal(currentRows.length,20);const ajv=new Ajv2020({strict:false,allErrors:true});addFormats(ajv);const schema=ajv.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json'))),cfgSchema=ajv.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-review-config.schema.json')))
const reviewId='biologie-flora-fauna20-current391-paired-reviewed-current-binding-technical-20261008-v1',records:any[]=[],Plineage:any[]=[]
for(const source of currentRows){const is14=source.goalId===gid14,a=is14?source:originalA.get(source.goalId),b=is14?bP14:originalB.get(source.goalId),oldP=sourceOld.get(source.goalId),g=goalBy.get(source.goalId),resources=Object.fromEntries(g.resourceLinks.filter((l:any)=>l.type==='goal-visualization').map((l:any)=>[l.url,digests[l.url]]));assert.ok(a);assert.ok(b);assert.ok(oldP)
 for(const k of ['profile','profileFingerprint','goalFingerprint','reviewInputFingerprint','reviewCriteriaFingerprint','evidenceLevel','maximumClaimScope','status','reviewAuthority']){assert.deepEqual(a[k],b[k]);assert.deepEqual(a[k],source[k])}
 assert.deepEqual(source.profile,oldP.profile);assert.equal(source.profileFingerprint,oldP.profileFingerprint);assert.equal(source.goalFingerprint,oldP.goalFingerprint);if(!is14)assert.equal(source.reviewInputFingerprint,oldP.reviewInputFingerprint)
 if(is14){for(const k of ['goalId','goalFingerprint','profileFingerprint','reviewInputFingerprint'])assert.equal(aP14[k],source[k])}
 assert.equal(source.status,'needs_human_review');assert.equal(source.reviewAuthority,'ai_candidate');assert.equal(source.evidenceLevel,'E1');assert.equal(source.maximumClaimScope,'G1');assert.deepEqual(source.dissent,oldP.dissent);assert.deepEqual(b.dissent.slice(0,source.dissent.length),source.dissent)
 const dissent=[...source.dissent,...b.dissent.slice(source.dissent.length),'Die historische Autoren-/Quellen-/Leistungsbegrenzung bleibt erhalten. Aktuelle echte A/B-Prüfungen decken die ganzen unveränderten Profile sowie tatsächliche Raster, native Seiten und Kontexte: originale19 plus gezieltesv4für14. Keine reale Lernendenleistung, E2, menschliche Freigabe oder Erprobung. Öffentliche Bindungen und strenger Zentralabschluss folgen erst nach Integration.']
 const record={...source,reviewId,reviewedAt:new Date().toISOString(),reviewer:'Codex technical integrator of actual sealed independent A/B science and exact current raster/page/context judgments; no new scientific reviewer or run',reason:'Exact whole bilingual positive profile and original forty common bilingual cases plus two conditional fish-choice cases retained. Genuine original A/B judgments for19 and actual independent targeted v4 A/B for14; concrete image error corrected and old holds preserved. No new science, whole-country primary-source closure, real learner performance, human approval or trial. Only current exact resource bindings and integration metadata.',reviewRunIds:[],dissent}
 assert.ok(schema(record),ajv.errorsText(schema.errors));assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(record,g,resources,'curricularAtomic'),[]);records.push(record)
 Plineage.push({goalId:source.goalId,actualAInput:is14?bind(resolve(targetA,'P1.exact-inactive-native-api.independent-a.actual.json')):bind(resolve(srcA,'P20.exact-final-author-input.binding.json')),actualBInput:is14?bind(resolve(targetB,'P14.current-v4-independent-b.record.json')):bind(resolve(srcB,'P20.current-raster-independent-b.review.jsonl')),sourceBReviewId:b.reviewId,sourceBReviewedAt:b.reviewedAt,wholeProfileBodyExactBothAndOriginalScience:true,profileFingerprint:source.profileFingerprint,priorReviewInputFingerprint:oldP.reviewInputFingerprint,currentReviewInputFingerprint:source.reviewInputFingerprint,currentRasterChangedSinceOriginalReview:is14,sourceAndPerformanceDissentPreserved:source.dissent,sourceBFurtherDissentRetained:b.dissent.slice(source.dissent.length),onlyIntegrationMetadataAdded:true,noScientificRunInvented:true,resources})}
write(resolve(own,'positive/current20.records.jsonl'),records.map(r=>JSON.stringify(r)).join('\n')+'\n')
const positiveCfg={...read(resolve(old,'biologie-flora-fauna20-current391-author-v1/P20.current-text-preimage.author.config.json')),reviewId,landscapePath:plan.beforeBindings.canonical.path,semanticKindLedgerPath:plan.beforeBindings.kinds.path,reviewPath:relative(root,resolve(own,'positive/current20.records.jsonl')),reviewRunManifestPaths:[],scope:{label:'Current whole Flora20 positive profiles from genuine paired independent science; original19 plus actual targetedv4for14, E1/G1 machine candidates, no learner/Human evidence',goalIds:ids}};assert.ok(cfgSchema(positiveCfg),ajv.errorsText(cfgSchema.errors));write(resolve(own,'positive/current20.future-active.config.json'),positiveCfg);write(resolve(own,'positive/current20.inactive-native.config.json'),{...positiveCfg,landscapePath:inertCfg.landscapePath,semanticKindLedgerPath:inertCfg.semanticKindLedgerPath})
write(resolve(own,'positive/twenty-paired-original-science-and-current-binding-lineage.technical.json'),{seals,rows:Plineage,nativePerRecordClosedSchemaPASS:true,nativePerRecordSemanticChecksPASS:true,scientificBodiesChanged:0,needsHumanReview:20,E1G1:true,actualPublicPCLIStillPendingRootIntegration:true,activeWrites:0})
write(resolve(own,'checks/ready-native-current20-profile-visual-and-whole391-bindings.technical.json'),{seals,selectedActualAssets:20,nativeP20SchemaAndSemanticsPASS:true,nativePureCurrent391PASS:true,exactOther371Pages:true,noActualAssetBytesChangedSinceFinalPairedIndependentReviews:true,original19AndTargeted14ActualPairedV:'PASS',currentAM20OriginalRowsExact:true,newScientificJudgmentsByTechnicalAgent:false,humanApproval:false,humanTrial:false,newStrictClosureClaim:0,potentialPackageGainAfterRootIntegrationAndCentralCheck:20,activeWrites:0})
write(resolve(own,'checks/binding-preparation-declared-inputs.json'),{files:[...declared.values()]})
console.log(JSON.stringify({futureCanonicalDigest:bind(canonicalPath).sha256,nativeFull391:'PASS',exactUnchangedPages:371,nativeP20SchemaAndSemantics:'PASS',pairedActualV20:'PASS_original19_plus_targeted14',activeWrites:0,strictGainClaimed:0}))
