from pathlib import Path
import json,hashlib,datetime
own=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-07/chemie-b007-b014-four-current-independent-b-20261007-v2')
author=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-07/chemie-b007-b014-four-current479-native-refresh-author-20261007-v2')
tech=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-07/chemie-b007-b014-four-dual-campaign-technical-followup-20261007-v4')
freeze=json.load(open(tech/'technical.final.freeze.json'))
for x in freeze['payloads']:
 b=Path(x['path']).read_bytes();assert len(b)==x['bytes'] and hashlib.sha256(b).hexdigest()==x['sha256'],x['path']
p=tech/'native/four/round-b';campaign=json.load(open(p/'description-review-campaign.json'));input_=json.load(open(p/'description-review-input.json'));bundle=json.load(open(p/'review-bundle-manifest.json'));batch=campaign['batches'][0]
batchpath=p/'batches'/f"{batch['batchId']}.input.jsonl";raw=batchpath.read_bytes();assert 'sha256:'+hashlib.sha256(raw).hexdigest()==batch['batchInputFingerprint'];assert [json.loads(l)['goal']['goalId'] for l in raw.splitlines()]==batch['goalIds']
runid='chemie-b007-b014-four-current-blind-b-native-20261007-v4'
fields=[
['Das Piktogramm bezeichnet eine Gefahrenart; erst der zugehörige Warnhinweis grenzt die konkrete Gefahr für diesen Stoff ein. Eine gezielte Ergänzung aus bereitgestellter Stoffinformation gehört zu derselben Kennzeichnungsdeutung.','A pictogram denotes a hazard type; the associated statement specifies the actual hazard for that substance. Looking up a missing detail in supplied substance information is part of that same interpretation.','Die Person deutet H315, H319 und H335 mithilfe der vollständigen vorgelegten Information, begründet die verschiedenen konkreten Gefahren trotz gemeinsamem Ausrufezeichen und benennt beim unvollständigen Auszug die noch benötigte Angabe.','The learner interprets H315, H319 and H335 using the supplied complete information, explains their different specific hazards despite the shared exclamation mark and identifies the information missing from an incomplete excerpt.','Bei Flammen-Auszügen für Flüssigkeit und Feststoff deutet die Person H225, H226 oder H228 datenbezogen und überträgt weder eine Stoffidentität noch einen H-Code allein aus dem gemeinsamen Symbol.','For flame excerpts concerning liquids and solids, the learner interprets H225, H226 or H228 from the supplied data and does not infer either substance identity or a hazard code from the common pictogram alone.'],
['Eine galvanische Zelle koppelt räumlich getrennte Oxidation und Reduktion durch äußeren Elektronentransport und inneren ionischen Ladungsausgleich. Die qualitative Spannung folgt der Differenz der Elektrodenpotenziale unter den gegebenen Bedingungen.','A galvanic cell couples separated oxidation and reduction through external electron transport and internal ionic charge balance. Its qualitative voltage follows from the difference of electrode potentials under the stated conditions.','Die Person formuliert und bilanziert Teilreaktionen, ordnet Anode, Kathode und Pole aus dem tatsächlichen Reaktionsverlauf zu und erklärt Elektronen- und Brückenionenwege einschließlich des fehlenden dauerhaften Stroms ohne Ionenverbindung.','The learner writes and balances half-reactions, assigns anode, cathode and polarity from the actual reactions and explains electron and bridge-ion paths, including the absence of sustained current without an ionic connection.','In einer neuen Cu/Ag-Zelle und nach Bechertausch begründet die Person chemische Rollen unabhängig von links und rechts; identische Halbzellen unter gleichen Bedingungen liefern keine Potenzialdifferenz. Ohne Potenzialdaten wird keine Zahl und aus einer Anzeige kein dauerhafter Strom behauptet.','For a fresh Cu/Ag cell and swapped beaker locations, the learner explains chemical roles independently of left and right; identical half-cells under identical conditions give no potential difference. No voltage number is invented without potential data and no sustained current is inferred from a reading.'],
['Die Namen und Formeln der ausgewählten fünf Säuren und vier Hydroxide bezeichnen Stoffe; im Arrhenius-Modell erhöht ihre Wirkung in Wasser die Oxonium- beziehungsweise Hydroxidionenkonzentration. Die gesamte Lösung ist ein Teilchengemisch und keine einzelne Stoffformel.','The names and formulas of the selected five acids and four hydroxides identify substances; their aqueous behaviour in the Arrhenius model increases hydronium or hydroxide concentration. The entire solution is a species mixture rather than one substance formula.','Die Person gibt die neun Namen-/Formelzuordnungen und gebräuchlichen Lösungsnamen richtig an, erklärt HCl in Wasser, die Bedeutung von H+(aq) als solvatisierter Kurzschreibweise und den OH−-Beitrag gelöster Hydroxide, ohne schwache Säuren als vollständig dissoziiert zu behandeln.','The learner correctly gives the nine name/formula associations and common solution names, explains aqueous HCl, H+(aq) as solvated-proton shorthand and the hydroxide contribution of dissolved hydroxides without treating weak acids as completely dissociated.','In rückwärts gestellten Namens-/Formelaufgaben und beim mehrwertigen Calciumhydroxid begründet die Person das Ionenverhältnis1:2, unterscheidet klares Kalkwasser vom ungelösten Feststoff und überträgt Stoffformeln nicht auf die ganze Lösung.','In reversed name/formula questions and with divalent calcium hydroxide, the learner explains the1:2 ion ratio, distinguishes clear limewater from undissolved solid and does not assign the solute formula to the entire solution.'],
['Brønsted-Säure und -Base sind die Rollen eines Teilchens beim Abgeben oder Aufnehmen eines Protons. Korrespondierende Paare unterscheiden sich um genau ein Proton; Wasser kann je nach Partner beide Rollen einnehmen und bleibt als Stoff von einer ganzen Lösung zu unterscheiden.','Brønsted acid and base are the roles of a species donating or accepting a proton. Conjugate pairs differ by exactly one proton; water can take either role depending on its partner, and a species remains distinct from the entire solution.','Die Person formuliert HF/Wasser- und NH3/Wasser-Protolysegleichungen, kennzeichnet den Protonenweg sowie beide Paare und begründet die wechselnde Rolle von Wasser, mit Atom- und Ladungserhaltung und klarer Trennung zwischen H3O+-Teilchen und saurer Lösung.','The learner writes HF/water and NH3/water proton-transfer equations, marks the proton path and both conjugate pairs and explains water\'s changing role while conserving atoms and charge and distinguishing an H3O+ species from an acidic solution.','Mit dem neuen geladenen Ampholyten H2PO4− stellt die Person die formalen Protonenabgabe- und Aufnahmegleichungen mit Wasser auf, begründet beide Rollen und behauptet aus ihrer Möglichkeit weder gleich große Umsätze noch Neutralität oder eine quantitative Gleichgewichtslage.','With the fresh charged ampholyte H2PO4−, the learner constructs formal proton-donation and proton-acceptance equations with water, explains both roles and does not infer equal extents, neutrality or a quantitative equilibrium position from their possibility.']
]
reasons=[
'Das aktuelle DE/EN-Wording begrenzt Kennzeichnungsdeutung und erforderliches Nachschlagen auf zusammengehörende bereitgestellte Information. Beide vollständigen Fälle prüfen konkrete Aussage und Informationslücke, ohne praktische Handhabung/Entsorgung oder offene Webrecherche einzuschieben. Die HE-Quelle stützt nur diesen Kennzeichnungsaspekt; weitere Source-Duties bleiben getrennt.',
'DE und EN benennen denselben zusammenhängenden Zellmechanismus einschließlich Teilreaktionen und qualitativer Potenzialdifferenz. Beide vollständigen Fälle prüfen echte neue Stoffpaarung, Ladungsausgleich, Rollen und Gegenfall; Berechnung von Standardpotenzialen und Referenz-Halbzelle bleiben eigene Ziele. Die sprachliche Entscheidung keep behebt keine separat dokumentierten V-Befunde am vorhandenen Bild.',
'Das Wording verbindet die ausdrücklich verlangten kompakten Namen/Formeln mit der zu erklärenden Wirkung in Wasser. Die beiden vollständigen Fälle umfassen fünf Säuren, vier Hydroxide, Lösungsnamen sowie Teilchen- und Dissoziationsgrenzen. Die erforderlichen18 Primärkarten stützen nur den Abrufteil; Salznamen und Salzformeln im breiteren HE-Original bleiben eigener offener Companion.',
'Die einzelnen Verben operationalisieren ein einziges Protonenübertragungsmodell mit verschiedenen Darstellungen; DE/EN sind fachlich gleichwertig. HF/NH3 und der formal vorgegebene Phosphat-Ampholyt zeigen wechselnde Teilchenrollen ohne pH-/Gleichgewichtsquantifizierung. Wortlaut und positive Fallantworten sind richtig; separat dokumentierte Bildbefunde bleiben als V-HOLD offen.'
]
keys=['essentialUnderstandingDe','essentialUnderstandingEn','observablePerformanceDe','observablePerformanceEn','transferExpectationDe','transferExpectationEn']
records=[]
for i,g in enumerate(input_['goals']):
 records.append({'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json','schemaVersion':1,'recordId':runid+'.goal-'+str(i+1),'runId':runid,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'bundleFingerprint':bundle['bundleFingerprint'],'bookDigest':bundle['bookModelDigest'],**{k:g[k] for k in ['goalId','goalFingerprint','pageFingerprint','currentTitleDe','currentTitleEn','currentDescriptionDe','currentDescriptionEn']},'decision':'keep','understandingEvidence':dict(zip(keys,fields[i])),'rationale':reasons[i],'evidenceProfileContract':'positive-understanding-evidence-v2','evidenceProfileRecommendation':'none','recordStatus':'candidate','reviewAuthority':'ai_candidate'})
results=own/'native-results'/batch['batchId'];results.mkdir(parents=True,exist_ok=True); rb=('\n'.join(json.dumps(x,ensure_ascii=False,separators=(',',':')) for x in records)+'\n').encode();(results/'description-records.jsonl').write_bytes(rb);(results/'batch.input.jsonl').write_bytes(raw)
params={'execution':'Independent Codex B agent, blind first substantive pass','modelFamily':'GPT-6 as declared by session instructions','exactModelVersion':'not exposed','temperature':'not exposed','seed':'not exposed','inputReading':'full frozen public D/P/source text, original rasters, physical PDF page PNGs, actual browser360/680 display captures','humanApproval':False}
pb=(json.dumps(params,ensure_ascii=False,sort_keys=True,separators=(',',':'))+'\n').encode();(own/'actual-generation-parameters.json').write_bytes(pb)
started=json.load(open(own/'first-scientific-observations.actual.json'))['recordedAtUTC'];completed=datetime.datetime.now(datetime.timezone.utc).isoformat()
run={'$schema':'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json','schemaVersion':1,'runId':runid,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'batchId':batch['batchId'],'batchInputFingerprint':batch['batchInputFingerprint'],'bundleFingerprint':bundle['bundleFingerprint'],'bookDigest':bundle['bookModelDigest'],'provider':'OpenAI','model':'GPT-6 (Codex session; exact model version not exposed)','role':'subject_reviewer','promptFamilyId':'goal-description-understanding-evidence-v2','promptFingerprint':campaign['promptFingerprint'],'criteriaFingerprint':campaign['criteriaFingerprint'],'generationParametersFingerprint':'sha256:'+hashlib.sha256(pb).hexdigest(),'independenceGroupId':campaign['independenceGroupId'],'blindToOtherRuns':True,'goalIds':batch['goalIds'],'inputArtifacts':[{'role':a['role'],'digest':a['digest']} for a in bundle['artifacts']]+[{'role':'description_review_batch_input_jsonl','digest':batch['batchInputFingerprint']}],'startedAt':started,'completedAt':completed,'status':'completed','outputDigest':'sha256:'+hashlib.sha256(rb).hexdigest(),'toolchainVersion':'codex-native-independent-review-v1'}
(results/'run-manifest.json').write_text(json.dumps(run,ensure_ascii=False,indent=2)+'\n')
(own/'native-contract-bindings.actual.json').write_text(json.dumps({'bundle':str(p/'review-bundle-manifest.json'),'input':str(p/'description-review-input.json'),'campaign':str(p/'description-review-campaign.json'),'batchInput':str(batchpath),'records':str(results/'description-records.jsonl'),'run':str(results/'run-manifest.json'),'technicalFreezeSha256':hashlib.sha256((tech/'technical.final.freeze.json').read_bytes()).hexdigest(),'scientificV2Unchanged':True,'humanApproval':False},indent=2)+'\n')
print(str(results))
