#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
from pathlib import Path
from datetime import datetime, timezone
import hashlib, importlib.util, json, shutil, subprocess
from PIL import Image
R=Path('/home/enpasos/projects/skillpilot');D=Path(__file__).resolve().parent
def bind(p):
 p=Path(p);raw=p.read_bytes();return {'path':str(p.relative_to(R)),'sha256':hashlib.sha256(raw).hexdigest(),'bytes':len(raw)}
def put(n,j):
 p=D/n;p.parent.mkdir(parents=True,exist_ok=True);raw=json.dumps(j,ensure_ascii=False,indent=2)+'\n';assert not p.exists();p.write_text(raw);return bind(p)
def textfile(n,t):
 p=D/n;p.parent.mkdir(parents=True,exist_ok=True);assert not p.exists();p.write_text(t+'\n');return str(p.relative_to(R))
firstSeal=json.loads((D/'first-nine.actual-images.author.first-binding.freeze.json').read_text())
for x in firstSeal['files']:
 a=bind(R/x['path']);assert a['sha256']==x['sha256'] and a['bytes']==x['bytes']
wholeInputs=json.loads((D/'all26-whole-goals-and-unchanged26P52cases.readonly-inputs.snapshot.json').read_text());whole={x['wholeGoal']['id']:x for x in wholeInputs['routineBodies']}
selected={
 'f79f15c0-e848-5e17-9eb5-26753d35c93b':{'key':'upper-hypothesis-investigation','originalName':'exec-d465bf7a-9ef4-4a18-a6a8-2928e2be180d.png','correctedName':'exec-4e3d4966-7d23-4e1b-a1c5-f0659c476cc2.png','firstDefectDe':'Blauer Büretteninhalt wurde am einzelnen austretenden Tropfen unbegründet rosa; inkonsistente Farbe derselben Flüssigkeit.','actualCorrectionDe':'Einzelner Tropfen jetzt wie der Büretteninhalt sehr hellblau; rosa Kolbenansatz und Gesamtkomposition behalten.','descriptionDe':'Ein schematischer Plan mit Proben und Kontrollen führt zu einer standfesten volumetrischen Analyse und einem noch leeren Rohdatenblatt. Bedingungen und Kontrollen sind zu beachten. Farben dienen der Illustration, nicht einer bestimmten Stoffidentität oder Konzentration. Das Bild behauptet weder eine konkrete Sicherheitsfreigabe noch bereits ausgeführte eigene Messungen.','altTextDe':'Plan, geklemmte Bürette mit kontrollierter Analyse und leeres Rohdatenblatt für Proben A und B.','reconstructionDe':'Freundlicher klarer Schulbuchcomic, quer16:9, pastellblau/gold/grün. Drei große Stationen: Plan mit A/B-Kolben und Kontrollproben; Analyse mit geschützter Laborperson an standfest geklemmter senkrechter Bürette, hellblauem Inhalt und gleich hellblauem einzelnen Tropfen über rosa Kolben, Kontrollprobe und leerer Bedingungsanzeige; Rohdaten mit nachdenklicher Person, leerem Blatt A/B und Stift. Große Pfeile und unten Kontrollen beachten. Keine echten Werte, keine Erfolgshäkchen, keine praktische Stoffanleitung.'},
 '31781d00-8f20-5041-bd7f-e261b27af162':{'key':'chemical-representation-transformation','originalName':'exec-72305941-f0d2-4f43-8b46-9aae09e3c968.png','correctedName':'exec-8da9803f-5eda-49c0-b852-7a9a349acc78.png','firstDefectDe':'Festes Feld enthielt4Na⁺/4Cl⁻, gelöstes Feld nur3Na⁺/3Cl⁻; ungedeckter Teilchenverlust im dargestellten Prozess.','actualCorrectionDe':'Jetzt tatsächlich4blauePlus und4grüneMinus in beiden Feldern gezählt; gelöste Ionen getrennt beweglich und Ladungsbilanz/Sorte erhalten.','descriptionDe':'Ein Fachtext wird in ein vereinfachtes digitales Teilchenschema überführt. Im festen Gitterausschnitt und in der Lösung erscheinen jeweils vier Na⁺- und vier Cl⁻-Ionen; Sorten und Gesamtladung bleiben erhalten, in Wasser werden die Ionen beweglich. Kreise, Farben und Bewegungslinien sind Modellcodes; Hydrathüllen, Größen, Energie und reale Bewegung werden vereinfacht. Das Bild ist ein Beispiel, kein Nachweis eines eigenen erstellten Produkts.','altTextDe':'Fachtext zu Salz in Wasser wird als Schema mit4Na⁺/4Cl⁻ im festen Gitter und denselben4Na⁺/4Cl⁻ in Lösung dargestellt.','reconstructionDe':'Freundlicher abstrakter Schulbuchcomic16:9. Links Papier Fachtext/Salz in Wasser und nachdenkliche Figur; großer goldener Pfeil zum Tablet Darstellung. Im Tablet links Feld fest, exakt2×4abwechselndeIonen4blauePlus und4grüneMinus. Wassertropfen und blauer Pfeil zum rechten Wasserfeld gelöst, dort exakt4blauePlus und4grüneMinus locker getrennt mit Bewegungsstrichen. Unten Legende blauPlus Na⁺, grünMinus Cl⁻ und Modell. Keine Teilchen verschwinden, keine neuen Stoffsorten oder gebundenen NaCl-Moleküle.'},
 '38e30bb9-6145-5da0-80b8-36e3c45e15d0':{'key':'chemical-presentation','originalName':'exec-7878b264-5b3d-4b05-aedd-c875af94c2a2.png','correctedName':'exec-d4e4b943-ce43-4072-8b69-5590ef41cbc4.png','firstDefectDe':'Vor Trennung stand Frischlösemittel, obwohl die dargestellte Rückgewinnung den gebrauchten Stoffstrom benötigt; Rücklauf ohne erneuten Einsatz missverständlich.','actualCorrectionDe':'Linkes Feedlabel jetzt Gebrauchtes Lösemittel; grüner Rücklauf ausdrücklich Erneut nutzen. Energiebedarf, analoges/digitales Medium, eigene Auswertung und Publikumfragen behalten.','descriptionDe':'Eine Person erklärt Stoffrückgewinnung mit analogem Handout, digitaler Prozessdarstellung und eigener Auswertung vor einem fragenden Publikum. Gebrauchtes Lösemittel wird schematisch getrennt, der rückgewonnene Stoff erneut genutzt; die Trennung benötigt Energie und kann Frischbedarf senken. Der Rücklauf fasst den erneuten Einsatz und anschließenden Gebrauch abstrakt zusammen. Es wird weder vollständige verlustfreie Rückgewinnung noch eine Gesamtumweltbilanz oder ein tatsächlich absolvierter Vortrag behauptet.','altTextDe':'Präsentation mit Handout, digitalem Modell der Lösemittelrückgewinnung, eigener Auswertung und offenen Zuhörerfragen.','reconstructionDe':'Freundlicher Klassenraumcomic16:9. Links präsentierendePerson mit Handout, rechts digitale Fläche Stoffrückgewinnung. Prozess: blauesGefäß Gebrauchtes Lösemittel → abstraktesTrenngefäß Trennung mit Energieblitz → blauesGefäß Rückgewonnenes Lösemittel. Großer grüner Rücklauf Erneut nutzen; Hinweis weniger Frischlösemittel möglich. Tischschild Eigene Auswertung mit getrennten Stoff/Energie-Symbolen; zweiZuhörer, eine Frageblase. Unten Erklären und nachfragen. Keine klinischen/echtenMesswerte, keine verlustfreieKreisprozessgarantie oder bestandeneVortragsleistung.'}
}
images=[];attempts=[]
for id,v in selected.items():
 assert whole[id]['candidateKey']==v['key'];out=D/'images'/id;out.mkdir(parents=True,exist_ok=True);src=D/(id+'.corrected-v2.png');asset=out/(id+'.png');shutil.copyfile(src,asset);assert asset.read_bytes()==src.read_bytes();im=Image.open(asset);assert im.size==(1672,941)
 for w in [360,680]:shutil.copyfile(D/(id+f'.corrected-v2.actual-{w}.png'),out/f'actual-{w}.png')
 shutil.copyfile(D/(id+'.correction-v2.prompt.de.md'),out/'prompt.de.md');shutil.copyfile(D/(id+'.prompt.de.md'),out/'original-v1.prompt.de.md')
 reconstruction=textfile('images/'+id+'/image-reconstruction-prompt.de.md',v['reconstructionDe'])
 original=bind(D/(id+'.png'));attempt={'goalId':id,'originalAttempt':original,'originalPrompt':bind(D/(id+'.prompt.de.md')),'originalOutputPath':'/home/enpasos/.codex/generated_images/01a11a60-3a68-72a2-8957-0790a0202f5b/'+v['originalName'],'firstActualDefectDe':v['firstDefectDe'],'firstAttemptAuthorDecision':'HOLD','correctedAttempt':bind(src),'actualCorrectionPrompt':bind(D/(id+'.correction-v2.prompt.de.md')),'actualReferencedImage':original,'correctedOriginalOutputPath':'/home/enpasos/.codex/generated_images/01a11a60-3a68-72a2-8957-0790a0202f5b/'+v['correctedName'],'actualCorrectionObservedDe':v['actualCorrectionDe'],'originalAndCorrected360680ActuallyViewedByAuthor':True,'actualProvider':'OpenAI / ChatGPT-Codex','actualTool':'image_gen.imagegen','modelNotExposed':True,'actualCalls':2,'generationFailures':0,'independentReview':'pending'};attempts.append(attempt)
 images.append({'goalId':id,'candidateKey':v['key'],'path':str(asset.relative_to(R)),'assetPath':str(asset.relative_to(R)),**{k:x for k,x in bind(asset).items() if k!='path'},'dimensions':[1672,941],'format':'PNG','provider':'OpenAI / ChatGPT-Codex integrated image_gen tool','providerModel':'not exposed by tool','promptPath':str((out/'prompt.de.md').relative_to(R)),'originalGenerationPromptPath':str((out/'original-v1.prompt.de.md').relative_to(R)),'reconstructionPromptPath':reconstruction,'descriptionDe':v['descriptionDe'],'altTextDe':v['altTextDe'],'authorDecision':'actual corrected raster candidate, independent reviews pending','actualOriginal360680ViewedByAuthor':True,'sourceAndPositiveApprovalInferred':False,'wholeGoal':whole[id]['wholeGoal'],'exactWholeScientificInputSnapshot':bind(D/'all26-whole-goals-and-unchanged26P52cases.readonly-inputs.snapshot.json'),'wholeTwoCaseKeys':[c['caseKey'] for c in whole[id]['wholeTwoCases']],'independentVA':'pending','independentVB':'pending','machineApproval':False,'humanApproval':False,'humanTrial':False})
attemptBinding=put('three-new-attempts-and-minimal-raster-corrections.actual-provenance.json',{'schemaVersion':1,'role':'Actual author generation/defect/correction chronology; no V/source/P approval','attempts':attempts,'actualOriginalCalls':3,'actualEditCalls':3,'allOriginalAttemptsPreserved':True,'allCorrectedOriginal360680ActuallyViewed':True,'independentApprovals':0,'activeWrites':0})
entry=put('neutral-three-corrected.actual-images.author.entry.json',{'schemaVersion':1,'role':'Neutral bounded actual corrected PNG candidates for independent review','images':images,'actualGenerationAndCorrectionProvenance':attemptBinding,'firstNineEntry':bind(D/'neutral-first-nine.actual-images.author.entry.json'),'firstNineSeal':bind(D/'first-nine.actual-images.author.first-binding.freeze.json'),'firstNineArtifactsByteExact':True,'whole26GoalProfilesAnd52CasesUnchanged':True,'totalActualRoutineImageCandidatesNow':12,'remaining14RoutinesImageRoles':'not started further due to user commit-checkpoint steering','actualCurrentStrictChemistry':177,'strictGain':0,'restoredActiveBindings':0,'activeWrites':0,'allIndependentV':'pending','humanApproval':False,'humanTrial':False})
textfile('README.commit-checkpoint.md','# B008 image author checkpoint\n\nThis is inactive author work. The first-nine entry and seal remain byte exact. A separate three-image entry preserves three original HOLD attempts and their minimal actual raster corrections. Twelve routine image candidates are now available: eight existing assets retained, one new theory PNG, and three corrected new PNGs. Fourteen further image roles remain unprepared. All current26 goal/P bodies and52 scientific cases remain unchanged; independent V, native current binding and integration remain pending. No active Canon/QA/Registry/runtime write and no strict increase, source/P/human approval are claimed.\n\nUse `neutral-first-nine.actual-images.author.entry.json` plus `neutral-three-corrected.actual-images.author.entry.json`. Every selected image has portable bytes, actual provider metadata, original/edit prompts, standalone reconstruction and actual author full/360/680 views. Preserved originals and failed first content attempts are not silently replaced. The user requested a commit-capable checkpoint, so no further image role began after the three already-started corrections.')
prior=set(x['path'] for x in firstSeal['files'])|{str((D/'first-nine.actual-images.author.first-binding.freeze.json').relative_to(R))};newfiles=sorted(p for p in D.rglob('*') if p.is_file() and str(p.relative_to(R)) not in prior)
res=subprocess.run(['git','check-ignore','--stdin'],input='\n'.join(str(p.relative_to(R)) for p in newfiles)+'\n',text=True,capture_output=True,cwd=R);assert res.returncode in [0,1] and not res.stdout,res.stdout
spec=importlib.util.spec_from_file_location('ordinarySchemas',R/'scripts/validate_schemas.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);schema=json.loads((R/'docs/landscape-runtime.schema.json').read_text());jf=list(D.rglob('*.json'));assert all(m.validate_file(str(p),schema) for p in jf)
checks=put('three-corrected.normal-targeted-schema-portability.actual.json',{'schemaVersion':1,'role':'Actual targeted normal schema/versionability/input byte checks, no science approval','normalJSONFilesChecked':len(jf),'normalSchemaErrors':0,'gitCheckIgnoreOrdinaryCurrentIndex':True,'newFilesIgnored':0,'newPortableFiles':[bind(p) for p in newfiles],'firstNine77ArtifactsByteExact':True,'providerOutputsRetainedOutsideAndCopiedInsideRepository':True,'allNewSelected3PNG1672x941':True,'actualOriginal360680AuthorViews':True,'activeWrites':0,'independentVAandVB':'pending'})
seal=put('three-corrected.actual-images.author.first-binding.freeze.json',{'schemaVersion':1,'role':'Immutable first selected corrected three-image author input set; no independent approval','sealedAt':datetime.now(timezone.utc).isoformat(),'neutralEntry':entry,'firstNinePreviousSeal':bind(D/'first-nine.actual-images.author.first-binding.freeze.json'),'targetedChecks':checks,'newFiles':[bind(p) for p in newfiles],'originalAttemptHoldsRetained':3,'correctedCandidateImages':3,'currentStrictGain':0,'activeWrites':0,'humanApproval':False,'humanTrial':False})
print(json.dumps({'entry':entry,'seal':seal,'newFiles':len(newfiles)+2,'normalJSONChecked':len(jf),'whole12Candidates':12,'remainingUnprepared':14,'firstNineBytesExact':True}))
