// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict'
import {readFileSync,writeFileSync} from 'node:fs'
import {resolve,dirname,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
import {hasCompletedDeepUnderstandingVisualizationReview,intersectStrictGoalGates,buildResolutionSupersessionChains} from '/home/enpasos/projects/skillpilot/app/scripts/reportDeepUnderstandingRollout.ts'
const root='/home/enpasos/projects/skillpilot',own=dirname(fileURLToPath(import.meta.url)),read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),sha=(v:Buffer)=>'sha256:'+createHash('sha256').update(v).digest('hex'),qaPath='curricula/DE/Gymnasium/quality/goal-visualization-qa/biologie.qa.json',original=read(resolve(root,qaPath)),current=read(resolve(own,'candidate/visualization-qa.metadata-only.json')),landscape=read(resolve(own,'candidate/canonical.json')),protectedIds=read(resolve(own,'checks/protected-current100.actual.json')).protectedStrictGoalIds,ledger=read(resolve(own,'candidate/semantic-kinds.json')),bio=read(resolve(own,'candidate/biologie.registry-subject.json'))
const changed=current.records.filter((r:any)=>JSON.stringify(r)!==JSON.stringify(original.records.find((o:any)=>o.goalId===r.goalId)));assert.equal(changed.length,1);assert.equal(changed[0].goalId,'9f73b963-5fac-5a90-a993-d7b7c0cc8526');const oldEvolution=original.records.find((r:any)=>r.goalId===changed[0].goalId);for(const k of Object.keys(oldEvolution).filter(k=>k!=='description'))assert.deepEqual(changed[0][k],oldEvolution[k]);assert.equal(changed[0].visualizationState,'missing');assert.equal(changed[0].assetSha256,'');assert.equal(changed[0].contentApprovedChatGpt,'no');assert.equal(changed[0].humanApproved,'no')
const Vids=new Set<string>(),bindings:any[]=[]
for(const id of protectedIds){const row=current.records.find((r:any)=>r.goalId===id),goal=landscape.goals.find((g:any)=>g.id===id);assert(hasCompletedDeepUnderstandingVisualizationReview(row));assert.equal(row.title,goal.title);assert.equal(row.description,goal.description);assert.equal(row.landscapePath,bio.landscapePath);const links=goal.resourceLinks.filter((l:any)=>l.type==='goal-visualization'&&l.role==='primary');assert.equal(links.length,1);assert.equal(row.imageUrl,links[0].url);const assets=[row.canonicalAssetPath,row.publicAssetPath];for(const p of assets)assert.equal(sha(readFileSync(resolve(root,p))),row.assetSha256);Vids.add(id);if(id.startsWith('e70')||id.startsWith('ffef')){assets.push('backend/src/main/resources/static'+row.imageUrl);for(const p of assets)assert.equal(sha(readFileSync(resolve(root,p))),row.assetSha256);assert.deepEqual(row,original.records.find((r:any)=>r.goalId===id));bindings.push({goalId:id,qaRecordWholeExact:true,actualAssets:assets.map(p=>({path:p,sha256:sha(readFileSync(resolve(root,p)))})),sourceScopeBinding:'Changed only applicability / bounded source route; actual original PNG and its existing QA status unchanged. Both fresh sealed A/B whole-goal/image judgments remain separate from historical authority.'})}}
const atoms=new Set<string>(ledger.decisions.filter((d:any)=>d.semanticKind==='curricularAtomic').map((d:any)=>d.goalId));assert.equal(atoms.size,391)
const lower=read(resolve(own,'checks/all-current-lower-native-D102-P100.actual.json')),Dids=new Set<string>(lower.retainedD.map((r:any)=>r.goalId)),Pids=new Set<string>(protectedIds),intersection=intersectStrictGoalGates(atoms,[Dids,Pids,atoms,atoms,Vids]);assert.deepEqual([...intersection].sort(),[...protectedIds].sort())
const chains=buildResolutionSupersessionChains(bio.resolutionSupersessions,bio.resolutionIndexPaths,atoms);assert.deepEqual(chains.issues,[]);assert.equal(chains.invalidGoalIds.size,0)
writeFileSync(resolve(own,'checks/V100-unchanged-assets-scope-and-open-V-metadata.actual.json'),JSON.stringify({nativeHelper:'hasCompletedDeepUnderstandingVisualizationReview',nativeProtectedVCount:Vids.size,affectedTwoActualBindings:bindings,changedQaRecordFields:[{goalId:changed[0].goalId,fields:['description'],missingReasonExact:'no_primary_link',allApprovalAndAssetFieldsExact:true}],other390QaRecordsExact:true,missingPAndVRemainOpen:['05358518-f66c-5c1b-ad3f-d16211d0fc1c','9f73b963-5fac-5a90-a993-d7b7c0cc8526'],nativeSupersessionChainsPASS:true,lowerCandidateIntersectionExactProtected100:true,centralFullReportRun:false,newScientificReviewsOrAssetEdits:false,newM7Completions:0,humanApproval:false,humanTrial:false,activeWrites:false},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({nativeCurrentV100:'PASS',rawQa390Continuity:'PASS',nativeSupersessionChains:'PASS',lowerCandidateProtectedIntersection100:'PASS',centralReportRun:false}))
