from pathlib import Path
import json,hashlib,datetime
p=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-07/biologie-three-source-485-ENG-EKG-and-e70-BW-author-20261007-v2')
q=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-07/biologie-three-current-fresh-blind-a-20261007-v2')
r=json.loads((p/'reviewer-entry/whole-three-current-native-goals-context-P-source.author.raw.json').read_text())
judgments=[
{'goalId':r['records'][0]['goalId'],'D':'KEEP','P':'KEEP','A':{'status':'atomic','semanticAtomic':True},'M':{'status':'no_memory_needed','memoryUseful':False,'memoryGoalIds':[],'deckIds':[]},'V':{'decision':'accepted_pilot','aiMachineReviewOnly':True},'rationale':{
'D':'The bilingual descriptions ask for one causal explanation from a supplied neuronal disease model, not classification or diagnosis of all diseases. HE physical43 supports the model principle with Alzheimer/Parkinson examples. BY EA explicitly names MS/Parkinson, so BY support remains partial and does not turn Alzheimer into a BY obligation.',
'P':'Both complete bilingual cases fit that bounded explanation. The first relates lost connections to impaired network processing and rejects a diagnosis from one memory complaint. The second changes the alteration level from degenerative structural loss to temporary transmitter action and requires distinguishing similar impairment from common disease or mechanism. Independent explanation is demanded by the observable-performance and understanding-focus fields; echoing the prompt is not an independent demonstration. No disease-specific causes or symptoms beyond the supplied model are required.',
'A':'Explaining a supplied neuronal alteration through its effect on system function is one model competence. Naming alternative disease examples does not create independently required disease competencies.',
'M':'The assessed work is a material-supported causal explanation and inference boundary. No independent retrieval of a compact disease list, mechanism catalogue or diagnostic threshold is required by this bounded goal; no new memory deck/card is justified.',
'V':'Actually inspected full PNG, actual360/680 rasters and PDF physical3. The intact chain carries arrows through each illustrated connection. The disrupted chain stops after the green neuron at the red X; no downstream arrow or transmitter dots imply continued propagation across the broken connection. Modell explicitly labels the abstraction. The title labels and network contrast remain legible at360; the image makes no disease-specific or diagnostic claim.'}},
{'goalId':r['records'][1]['goalId'],'D':'KEEP','P':'KEEP','A':{'status':'atomic','semanticAtomic':True},'M':{'status':'no_memory_needed','memoryUseful':False,'memoryGoalIds':[],'deckIds':[]},'V':{'decision':'accepted_pilot','aiMachineReviewOnly':True},'rationale':{
'D':'DE/EN identify surface electrical potential differences as an aggregate recording, bounded use of a supplied comparison, and limits concerning single cells, brain images and diagnosis. English disambiguates German ENG as nerve conduction studies. Original BY EA competence9 and the adjacent explicit ENG/EKG content support this bounded method model. Neither GA nor HE support is asserted. Cardiac tissue is distinguished from peripheral nerves rather than described as neurons.',
'P':'All two-case DE/EN scientific bodies and answers were read. The sensory ENG case supplies extracellular weighted contributions, equal recording site and timing/temperature controls. Independent calculation gives50m/s and25m/s; the difference supports slower modelled peripheral conduction, not MS. Fresh ECG changes tissue, timed event and reference polarity: +0.7mV becomes−0.7mV after lead swap; regular intervals give60/min and75/min. The learner must explain common differential recording while distinguishing tissue-specific interpretation and both diagnostic overclaims. These are substantive changed representations and signal sources, not a number-only repetition. No exact cell count follows from amplitude.',
'A':'One competence explains aggregate surface electrical recording and bounded interpretation. ENG and ECG serve as contrasting applications of the same recording principle. The supplied speed/rate formulas are supports for interpreting the given model, not separately required calculation routines or clinical-method training.',
'M':'The complete cases supply signal source, electrode relation, timing rules, controls and legends. Assessed understanding is comparison and causal interpretation. Memorizing abbreviations, fixed waveform labels, clinical thresholds or formulas is not needed to meet this model competence; no memory goal/deck/card is required.',
'V':'Actually inspected full PNG, own actual360/680 rasters and PDF physical4. Separate Nerv and Herz panels keep peripheral fibres distinct from cardiac tissue. Two labelled measurement inputs lead to each device; qualitative waveforms have no numerical diagnostic scale. Plus/minus are measurement-input polarity, as stated by the specific alt text, not permanent cellular charges. Arm and chest overlays are schematic anatomy, not an electrode-placement training guide. Both signal panels and all essential labels remain legible at360. No technical IDs, provider artifacts, brain-image or diagnostic claim is visible.'}},
{'goalId':r['records'][2]['goalId'],'D':'KEEP','P':'KEEP','A':{'status':'atomic','semanticAtomic':True},'M':{'status':'no_memory_needed','memoryUseful':False,'memoryGoalIds':[],'deckIds':[]},'V':{'decision':'accepted_pilot','aiMachineReviewOnly':True},'rationale':{
'D':'The bilingual goal explains replication significance through the same simple semiconservative copying model. The prerequisite DNA-Aufbau supplies structural context. BW physical24/printed22 clause3.3.2(3) explicitly asks for simple-model duplication capability; the added BW support is a partial operationalisation, not complete coverage of the whole structure/information-storage bullet or a requirement for advanced enzyme mechanisms.',
'P':'The two complete bilingual cases keep pairing/direction legends supplied. Independently checking AGTCCA gives complementary TCAGGT; X andY separate into different daughters with newly made complements. The second round explicitly labels only original starting material: two of four molecules retain one original labelled strand, two have only unlabelled strands, while copied sequence information is preserved in all four. The altered tracking frame is meaningful transfer and prevents conflating material provenance with genetic information. The profile requires the learner to construct and justify, not repeat the image.',
'A':'Significance and strand tracing explain one DNA copying relation. The fresh round extends that same model; it does not import enzyme kinetics, a separate inheritance routine or mitosis assessment.',
'M':'The goal/profile assess a supplied-model construction and information/material distinction; base-pairing and strand-direction legends are supplied. No separate rote recall item is necessary for this goal as authored.',
'V':'Actually inspected full PNG, own actual360/680 rasters and PDF physical5. Two blue original strands become separate daughters, each paired with one orange new strand, with the same arrangement of schematic information pieces. The old/new legend matches the strand colours and remains readable at360. Coloured internal puzzle pieces are unlabeled schematic information tokens, not a claim about additional named DNA bases or replication intermediates. The preserved strands and information pattern match the specific alt text.'}}
]
bindings=[]
paths=[p/'README.md',p/'author.final.freeze.json',p/'reviewer-entry/whole-three-current-native-goals-context-P-source.author.raw.json',p/'reviewer-entry/native-first-pass-contracts.author.json',p/'candidate/three-complete-P-profiles-six-cases.DE-EN.author.json',p/'native-three/book.pdf',p/'native-three/book.pdf.render-manifest.json',p/'native-three/book-model.json']
paths += list((p/'primary').iterdir())
paths += list((p/'selected-existing-images').iterdir())
paths += [p/'native-three/fresh-blind-round-a'/f for f in ['description-review-campaign.json','description-review-input.json','review-bundle-manifest.json','prompt.md','criteria.md']]
paths += list((p/'native-three/fresh-blind-round-a/batches').iterdir())
paths += list(q.glob('actual-pdf-*.png')) + list(q.glob('*-actual-*.png'))
paths += [q/'actual-responsive-bindings.json',q/'independent-case-answers.json',q/'medlineplus-nerve-conduction.primary.html',q/'nhlbi-heart-tests.primary.html',q/'external-primary-retrieval.actual.json']
paths += [Path('AGENTS.md'),Path('docs/concept/skill-graph/atomic-goal-visualizations.md')]
for f in paths:
 if f.is_file():
  b=f.read_bytes();bindings.append({'path':str(f),'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)})
for j,d in zip(judgments,r['records']):
 j.update({'goalFingerprint':d['currentNativeDInput']['goalFingerprint'],'pageFingerprint':d['currentNativeDInput']['pageFingerprint'],'actualPDFPhysicalPage':d['actualPDFPhysicalPage'],'assetSha256':d['currentNativeDInput']['reviewContext']['page']['visualization']['originalDigest'].removeprefix('sha256:'),'currentWholeGoal':next(g for g in r['currentWholeGoals'] if g['id']==j['goalId'])})
seal={'schemaVersion':1,'role':'Independent scientific first-pass seal before native output and before peer exposure','reviewer':'A, OpenAI GPT-6 Codex; version not exposed','sealedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sourcePacket':str(p),'blindToPeerAndRootScientificJudgments':True,'peerScientificOutputsRead':False,'earlierOwnIncompleteV1InputRecord':'../biologie-two-current-fresh-blind-a-20261007-v1/v1.partial-pass-paused-for-v2.json','actualReviewedPDFPhysicalPages':[3,4,5],'actualReviewedPNGCount':3,'actualReviewedResponsiveRasterCount':6,'completeBilingualPCaseCount':6,'originalOfficialRawSourcesInspected':True,'judgments':judgments,'findingCount':0,'findings':[],'scopeHolds':['Full GA/EA depression symptoms, multifactorial causation, therapy and social duties remain beyond these bounded model routes.','BY named MS/Parkinson symptom duties and full clinical method competence are not established by generic neuronal or recording models.','BW whole DNA structure/information-storage/duplication bullet is not solely covered by the replication goal. Existing other-jurisdiction applicability is preserved but is not independently re-audited here.'],'maximumClaimScope':'G1 for each exact bound goal and supplied artifacts; no human performance or field generalisation','evidenceLevel':'E1 artifact review, independently checked model answers','humanApproval':False,'humanTrial':False,'clinicalAcceptance':False,'activeCanonicalOrQAWrites':False,'inputAndActualVisualBindings':bindings}
f=q/'scientific-first-pass.sealed.json';f.write_text(json.dumps(seal,ensure_ascii=False,indent=2)+'\n');b=f.read_bytes();(q/'scientific-first-pass.sealed.sha256').write_text(hashlib.sha256(b).hexdigest()+'  scientific-first-pass.sealed.json\n');print('Scientific first pass sealed:',hashlib.sha256(b).hexdigest(),'KEEP3; findings0; native outputs not yet created.')
