// SPDX-License-Identifier: Apache-2.0
// Combine already completed independent A/B records using the ordinary validators.
// The technical integrator authored two prior corrections and is not an independent reviewer.
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { existsSync, lstatSync, mkdirSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { stableGoalBookJson } from '../../../../../../../app/scripts/goalBookModel.ts'
import { loadGoalDescriptionReviewCampaignResultDirectories } from '../../../../../../../app/scripts/validateGoalDescriptionReviewCampaignResults.ts'
import { validateGoalDescriptionReviewDualRound } from '../../../../../../../app/scripts/validateGoalDescriptionReviewDualRound.ts'
import { buildGoalDescriptionDualRoundResolution, extractGoalDescriptionDualRoundResolutionSource, validateGoalDescriptionDualRoundResolution } from '../../../../../../../app/scripts/validateGoalDescriptionDualRoundResolution.ts'
import { validateStandaloneResolutionIndexSchema, validateStandaloneResolutionIndexStructure } from '../../../../../../../app/scripts/reportDeepUnderstandingRollout.ts'
const root=resolve(process.argv[2]??'.')
const P='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/biologie-stoffwechsel-eight-current335-inactive-integration-technical-20261010-v1'
const V='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/biologie-stoffwechsel-eight-two-findings-current-raster-native-technical-successor-20261010-v3'
const A='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/biologie-stoffwechsel-two-findings-current-followup-independent-a-20261010-v1'
const B='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/biologie-stoffwechsel-eight-current-v3-independent-b-v1'
const own=resolve(root,P),out=resolve(own,'native-current-eight-dual-resolution')
const sha=(b:Buffer|string)=>`sha256:${createHash('sha256').update(b).digest('hex')}`
const ref=(p:string)=>{assert.ok(lstatSync(p).isFile()&&!lstatSync(p).isSymbolicLink());const b=readFileSync(p);return {path:relative(root,p),sha256:sha(b),bytes:b.length}}
const read=(p:string):any=>JSON.parse(readFileSync(resolve(root,p),'utf8'))
const verify=(x:any)=>{assert.equal(x.path.startsWith('/'),false);assert.equal(x.path.split('/').includes('..'),false);const a=ref(resolve(root,x.path));assert.equal(a.sha256,`sha256:${x.sha256.replace(/^sha256:/,'')}`,x.path);if(x.bytes!==undefined)assert.equal(a.bytes,x.bytes,x.path)}
const write=(p:string,x:any)=>{assert.ok(p.startsWith(own+'/'));const bytes=Buffer.isBuffer(x)?x:Buffer.from(typeof x==='string'?x:`${JSON.stringify(x,null,2)}\n`);if(existsSync(p)){assert.ok(readFileSync(p).equals(bytes),p);return};mkdirSync(dirname(p),{recursive:true});writeFileSync(p,bytes,{flag:'wx'})}
assert.equal(ref(resolve(root,B,'independent-b.completed.entry.json')).sha256,'sha256:11b41e60765cedecf28b5de273a36e20b96a2cbe264e56d248d9b2ea22185445')
assert.equal(ref(resolve(root,B,'FINAL.independent-b.portable.freeze.json')).sha256,'sha256:915f4392a6c5486d0486c1a0b6f76984dbf7ff981093ee1b2622adbad5f8eea4')
const be=read(B+'/independent-b.completed.entry.json'),bf=read(B+'/FINAL.independent-b.portable.freeze.json');bf.boundRegularFiles.forEach(verify)
const bc=read(be.portableInputClosure.path);bc.bindingsVerified.forEach(verify)
assert.equal(be.result.descriptionKEEP,8);assert.equal(be.result.positiveCandidateScientificallyAcceptable,8);assert.equal(be.result.visualKEEP,8);assert.equal(be.result.unresolvedBlockingFindings,0);assert.equal(be.result.peerJudgmentsRead,false)
const af=read(A+'/FINAL.current-native-eight-independent-A.freeze.json');af.ownRegularFiles.forEach(verify)
const vf=read(V+'/FINAL.two-findings-current-raster-P8-native8.technical.freeze.json');[...vf.ownFiles,...vf.requiredCurrentPortableFiles].forEach(verify)
const guards=read(P+'/inputs/current-active-write-guards.exact.json').files;guards.forEach(verify)
const normalSources=['goalBookModel.ts','validateGoalDescriptionReviewCampaignResults.ts','validateGoalDescriptionReviewDualRound.ts','validateGoalDescriptionDualRoundResolution.ts','reportDeepUnderstandingRollout.ts']
const executionRepoRoot=resolve(dirname(fileURLToPath(import.meta.url)),'../../../../../../..')
const sourceProof=normalSources.map(n=>{const a=readFileSync(resolve(root,'app/scripts',n)),b=readFileSync(resolve(executionRepoRoot,'app/scripts',n));assert.ok(a.equals(b),n);return {path:'app/scripts/'+n,sha256:sha(a),bytes:a.length,executionSourceByteExact:true}})
for(const x of [be.normalResults,be.normalRun]){verify(x);const to=resolve(out,'round-b/results',x.path.split('/').at(-1)!);write(to,readFileSync(resolve(root,x.path)))}
// Preserve the exact original current8 contexts/campaigns and actual independent result bytes.
const load=async(label:string)=>{const d=resolve(out,'round-'+label),bundle=JSON.parse(readFileSync(resolve(d,'review-bundle-manifest.json'),'utf8')),input=JSON.parse(readFileSync(resolve(d,'description-review-input.json'),'utf8')),campaign=JSON.parse(readFileSync(resolve(d,'description-review-campaign.json'),'utf8'));assert.equal(campaign.blindToOtherReviews,true);const r=await loadGoalDescriptionReviewCampaignResultDirectories({campaign,batchesDirectory:resolve(d,'batches'),resultsDirectory:resolve(d,'results')});assert.deepEqual(r.errors,[]);return {bundle,input,campaign,resultPairs:r.resultPairs}}
const [first,second]=await Promise.all([load('a'),load('b')]);assert.equal(stableGoalBookJson(first.input),stableGoalBookJson(second.input))
const ids=first.input.goals.map((g:any)=>g.goalId);assert.equal(ids.length,8);assert.deepEqual([...ids].sort(),[...be.goalIds].sort())
const dual=await validateGoalDescriptionReviewDualRound({first,second});assert.deepEqual(dual.errors,[]);assert.ok(dual.summary)
for(const g of dual.summary.goals){assert.equal(g.firstDecision,'keep',g.goalId);assert.equal(g.secondDecision,'keep',g.goalId)}
const dualBytes=Buffer.from(`${JSON.stringify(dual.summary,null,2)}\n`);write(resolve(out,'dual-summary.json'),dualBytes)
const candidate=read(P+'/candidate/whole479.only-eight-resourceLinks.inactive.exact.json'),whole=read(V+'/native/current394-after.actual-normal-model.json')
const groupId='biologie-stoffwechsel-eight-current-native-genuine-independent-dual-20261010-v1';const entries:any[]=[],actual:any[]=[]
for(const goalId of ids){
 const a=extractGoalDescriptionDualRoundResolutionSource({artifacts:first,goalId,label:'Actual completed independent A'}),b=extractGoalDescriptionDualRoundResolutionSource({artifacts:second,goalId,label:'Actual completed fresh independent blind B'});assert.deepEqual(a.errors,[]);assert.deepEqual(b.errors,[]);assert.ok(a.source?.record&&b.source?.record);assert.equal(a.source.decision,'keep');assert.equal(b.source.decision,'keep');assert.equal(a.source.record.evidenceProfileRecommendation,'none');assert.equal(b.source.record.evidenceProfileRecommendation,'none')
 const comparison=dual.summary.goals.find((g:any)=>g.goalId===goalId)!
 const synthesis={synthesisId:`${groupId}-selection-${goalId}`,authority:'ai_synthesis' as const,synthesizedBy:'Technical combination of completed independent A and fresh blind B. Integrator authored2prior corrections and supplies no third scientific judgment.',synthesizedAt:new Date().toISOString(),rationaleDe:'Beide echten abgeschlossenen unabhängigen aktuellen Records entscheiden KEEP ohne Korrekturempfehlung. Der technische Integrator übernimmt die unveränderte erste Verständnisevidenz; beide ganzen Begründungen, Evidenzen und ihre Grenzen bleiben exakt erhalten. Dies ist die normale technische Auflösung ihrer aktuellen Records, keine weitere unabhängige Fachprüfung und keine menschliche Freigabe. Die zwei früheren Korrekturen wurden vom Integrator authored; ihre unabhängigen Bewertungen stammen ausschließlich aus A und dem frischen blinden B.',rationaleEn:'Both actual completed independent current records decide KEEP without a correction recommendation. The technical integrator selects unchanged first understanding evidence; both complete rationales, evidence and their limits remain exact. This is ordinary technical resolution of their current records, no additional independent scientific review or human approval. The integrator authored two prior corrections; their independent judgments originate exclusively from A and fresh blind B.',understandingEvidence:structuredClone(a.source.record.understandingEvidence),dissent:comparison.disagreementFields.length?[{dissentId:`${groupId}-wording-${goalId}`,source:'both' as const,textDe:'Der normale Vergleich meldet unterschiedliche Formulierungen in '+comparison.disagreementFields.join(', ')+'. Beide Quellen entscheiden KEEP. Die unveränderte erste Verständnisevidenz wird ausgewählt; beide Originalrecords bleiben erhalten.',textEn:'The ordinary comparison reports differing formulations in '+comparison.disagreementFields.join(', ')+'. Both sources decide KEEP. Unchanged first understanding evidence is selected; both original records remain preserved.',disposition:'accepted_first' as const}]:[],humanAttestation:null}
 const resolution=buildGoalDescriptionDualRoundResolution({resolutionId:`${groupId}-resolution-${goalId}`,goalId,effectiveSemanticKind:'curricularAtomic',decision:'keep_current',synthesis,dualSummaryBytes:dualBytes,currentInput:first.input,firstSource:a.source,secondSource:b.source});const validation=await validateGoalDescriptionDualRoundResolution({resolution,dualSummary:dual.summary,dualSummaryBytes:dualBytes,currentInput:first.input,landscape:candidate,first,second});assert.deepEqual(validation.errors,[]);assert.equal(validation.strictDescriptionComplete,true)
 const p=resolve(out,'resolutions',goalId+'.resolution.json');write(p,resolution);entries.push({goalId,titleDe:resolution.goal.finalText.titleDe,groupId,decision:'keep_current',resolutionPath:'resolutions/'+goalId+'.resolution.json',resolutionDigest:ref(p).sha256,resolutionFingerprint:resolution.resolutionFingerprint,strictDescriptionComplete:true});actual.push({goalId,firstBinding:a.source.binding,secondBinding:b.source.binding,firstWholeRationale:a.source.record.rationale,secondWholeRationale:b.source.record.rationale,firstWholeUnderstandingEvidence:a.source.record.understandingEvidence,secondWholeUnderstandingEvidence:b.source.record.understandingEvidence,differingFields:comparison.disagreementFields,normalCurrentValidation:validation,newScientificReviewClaimed:false})
}
const index={$schema:'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-standalone-batch-resolution-index.schema.json',schemaVersion:2,indexContract:'goal-description-standalone-batch-resolution-index-v1',artifactSetId:groupId+'-inactive-resolutions',subject:'Biologie',semanticKind:'curricularAtomic',batchGoalIds:ids,groups:[{groupId,artifactDirectory:'.',dualSummaryPath:'dual-summary.json',dualSummaryDigest:sha(dualBytes),campaignGoalCount:8,resolvedGoalCount:8}],resolutions:entries};assert.deepEqual(validateStandaloneResolutionIndexSchema(index),[]);assert.deepEqual(validateStandaloneResolutionIndexStructure(index,new Set(whole.pages.map((p:any)=>p.goalId))),[]);write(resolve(out,'resolution-index.json'),index)
guards.forEach(verify);write(resolve(own,'checks/actual-normal-current-D8-dual-and-resolution.validation.json'),{schemaVersion:1,checkedAt:new Date().toISOString(),normalSourceEquality:sourceProof,completedActualIndependentA:ref(resolve(root,A,'final-current-native-eight-independent.A.json')),completedActualIndependentB:ref(resolve(root,B,'independent-b.completed.entry.json')),freshBNumericNarrativeCorrection:be.firstRecordNumericCorrection,normalDualSummary:dual.summary,normalIndividualResolutions:actual,normalStandaloneIndexSchemaAndStructure:'PASS',all8StrictDescriptionComplete:true,activeWriteGuardsUnchanged:true,newIndependentScientificReviews:0,humanApproval:false,strictActiveGain:0,activeWrites:[]})
console.log(JSON.stringify({normalDualGoals:8,normalKEEPResolutions:8,normalStrictDescriptionComplete:8,originalAAndBResultBytesPreserved:true,activeWrites:0,humanApproval:false,strictActiveGain:0}))
