import pathlib,json,hashlib,datetime,sys
P=pathlib.Path
load=lambda p:json.loads(P(p).read_text())
sha=lambda p:'sha256:'+hashlib.sha256(P(p).read_bytes()).hexdigest()
bind=lambda p:{'path':str(p),'sha256':sha(p),'bytes':P(p).stat().st_size}
q=P('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10')
basep=P('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-final702-current346-M6-source-scope-and-foreign-floor-independent-c-READONLY-v1/preserved-original-foreign20-and807-input-before-baseline.EXACT.json');base=load(basep)
reportp=P(sys.argv[1] if len(sys.argv)>1 else 'docs/qa-ci/status/curriculum-quality-status.json');report=load(reportp)
corep=P('curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_WIRTSCHAFT.de.json');regp=P('curricula/DE/Gymnasium/quality/deep-understanding-rollout/de-gymnasium-math-physics.config.json');bookp=P('app/scripts/config/goal-books/de-gym-economics-current-canonical.json')
sp=q/'wirtschaft-final702-native-SEM-346-exact-and48-pointer-followers-AUTHOR-INERT-c-v1';seal=sp/'SEALED-native702-346-whole-decisions-and48-pointer-only-author-successors.INERT.json';semrec=sp/'actual-native-SEM702-five-bounded-existing-and-nine-qualified-practices-48-pointer-only-followers.AUTHOR-INERT.receipt.json';sr=load(semrec)
pp=q/'wirtschaft-final702-nine-local-whole-practices-and-qualified-scope-route-COMPOSITION-INERT-v1';planseal=pp/'SEALED-final702-346-source2135-and-whole-route-author-handoff.INERT.json';planidx=pp/'ROOT-ready-final702-exact-Core-and-35Views-qualified-warning-lane.GUARDED.handoff.json';ix=load(planidx)
sourcep=q/'wirtschaft-current-source32-six-explicit-qualified-successors-endguard-independent-c-READONLY-v1/actual-current32-source-pairs-26-exact-six-explicit-qualified-followers.independent-READONLY.receipt.json';sources=load(sourcep)
reg=load(regp);ecid='605bdaf6-32d5-56fd-8d92-5a80c2fd2901';current={c['landscapeId']:c for c in report['curricula']};ec=current[ecid];checks={}
def ck(k,v):
 checks[k]=bool(v)
 if not v:raise AssertionError(k)
def matchbytes(active,candidate,label):
 ck(label+':candidateManifestSha',sha(candidate['path'])=='sha256:'+candidate['sha256'].replace('sha256:',''))
 ck(label+':activeWholeByteExact',P(active).read_bytes()==P(candidate['path']).read_bytes())
ck('statusGeneratedLaterThanPreservedForeignBaseline',report['generatedAt']>base['statusGeneratedAt']);ck('actualCurrentEconomicsM6OrBetter',ec['maturity'] in ['M6','M7']);ck('rulesVersionAndCatalogNotLoweredOrMutated',report['rulesVersion']==base['rulesVersion'] and report['ruleCatalog']==base['ruleCatalog'])
rules={r['id']:r for r in ec['rules']}
for rid in ['CQR-000','CQR-001','CQR-002','CQR-003','CQR-004','CQR-301','CQR-302','CQR-401','CQR-501']:ck('economics:'+rid+':PASS',rules[rid]['status']=='pass')
for rid,ks in {'CQR-000':['sourceUnregisteredGoals','sourceUnregisteredAtomicGoals','originalSourceUrlIssues'],'CQR-003':['unsupportedAssignedAtomicGoals','unmappedSourceAtomicGoals','sourcePartiallyCoveredOriginalGoals','sourceUncoveredOriginalGoals','warningedJurisdictions','errorJurisdictions'],'CQR-004':['mismatches','missingSourceGoals','missingTargetGoals','unmappedCourseLevelSourceGoals']}.items():
 for k in ks:ck('actualSource:'+rid+':'+k+':zero',rules[rid]['metrics'][k]==0)
for k in ['sourceOriginalGoals','sourceFullyCoveredOriginalGoals','sourceAtomicGoals','sourceMappedToViewAtomicGoals']:ck('actualSource2135:'+k,rules['CQR-003']['metrics'][k]==2135)
ck('all16JurisdictionsSourceFullyCovered',rules['CQR-003']['metrics']['sourceCompleteJurisdictions']==rules['CQR-003']['metrics']['fullCoverageJurisdictions']==16)
ck('currentScopesPresent',len(ec['scopes'])>0)
for s in ec['scopes']:
 rs={r['id']:r for r in s['rules']}
 for rid in ['CQR-101','CQR-102','CQR-103','CQR-201','CQR-202','CQR-203']:ck('actualScope:'+s['scopeId']+':'+rid,rs[rid]['status']=='pass')
 if 'CQR-104'in rs:ck('actualScope:'+s['scopeId']+':CQR-104',rs['CQR-104']['status']=='pass')
pipe=ec['mappingPipeline'];ck('nativeCurrentPipelineCountsCompleteSeparateFromHistoricalBE3RawPending',pipe['completeSources']==pipe['totalSources'] and pipe['incompleteSources']==pipe['blockedSources']==0)
bb=next(s for s in pipe['sources'] if s['sourceLandscapeId']=='936fa4b0-f550-5b6a-895a-d086a3401c6e');ck('currentBB100Rows31Exact69PartialNativeCounters',bb['sourceGoals']==bb['mappedSourceGoals']==100 and bb['unmappedSourceGoals']==0 and bb['exactMappings']==31 and bb['partialMappings']==69 and bb['completedSteps']==bb['totalSteps'])
ck('C702AuthorSealImmutable',sha(seal)=='sha256:76c74d5d5e12940e30fa26f8c62afb456bee095565c524a4e54433fb9d3c6b0d');ck('C702ReceiptImmutable',sha(semrec)=='sha256:788a86bafcef538c7481c81983e6a47c993a647d98b228778d99787dc8c20e66');ck('PlanFinal702AuthorSealImmutable',sha(planseal)=='sha256:d6c8b2855769b6425298a8e8777377efc06d60f6b2385fbca52743f73f0e4d50')
matchbytes(corep,ix['currentCore'],'explicitQualified702WholeCore');matchbytes(regp,sr['centralRegistryFollower'],'explicitQualified702SEM47RegistryPointers');bc=next(c for c in sr['pointerFollowers48'] if c['role']=='goalBook');matchbytes(bookp,bc['after'],'explicitQualifiedBookPointerOnlyFollower')
ecr=next(s for s in reg['subjects'] if s['subject']=='wirtschaftswissenschaften');matchbytes(ecr['semanticKindLedgerPath'],sr['currentSemanticLedger'],'explicitQualified702SEMLedger')
for c in sr['pointerFollowers48']:
 matchbytes(c['after']['path'],c['after'],'48PointerArtifactExact:'+c['role']+':'+str(c.get('index','')))
 before=load(c['before']['path']);after=load(c['after']['path']);after['semanticKindLedgerPath']=before['semanticKindLedgerPath'];ck('48PointerOtherFieldsWholeExact:'+c['role']+':'+str(c.get('index','')),before==after)
for row in ix['all35WholeViewBindings']:matchbytes(row['activePath'],row['candidate'],'all35ActualWholeView:'+row['activePath'])
for row in ix['pairs']:matchbytes(row['activePath'],row['candidate'],'all33ActualCoreViewWarningPair:'+row['activePath'])
for row in sources['actualByteChecks']:matchbytes(row['active']['path'],row['expectedQualifiedCandidate'],'source32_26Exact6ExplicitQualifiedSuccessors:'+row['active']['path'])
be_row=next(row for row in sources['actualByteChecks'] if '/BE/' in row['active']['path'] and '/source-extraction/' in row['active']['path']);be_source=load(be_row['active']['path']);be_candidate=load(be_row['expectedQualifiedCandidate']['path']);be3=next(st for st in be_source['pipelineStatus']['steps'] if st['id']=='MAPPING-3');be3old=next(st for st in be_candidate['pipelineStatus']['steps'] if st['id']=='MAPPING-3');ck('BE125OriginalRawMAPPING3WholePendingObjectPreserved',be3==be3old and be3['status']=='incomplete' and any(not c['passed'] for c in be3['checks']));ck('BE125MAPPING12OnlyCompleteNoNew125Science',all(st['status']=='complete' for st in be_source['pipelineStatus']['steps'] if st['id'] in ['MAPPING-1','MAPPING-2']) and len(be_source['sourceGoals'])==125 and len(be_source['passages'])==57 and be_source['currentMachineSourceQualification']['officialGKFourVsThreeAreasAmbiguityResolved']==False)
core=load(corep);oldcore=load(q/'wirtschaft-b144-canonical-practice-phase-Q2-bounded-successor-root-v1/canonical693.practice-phase-Q2.AUTHOR-INERT.json');oldby={g['id']:g for g in oldcore['goals']};by={g['id']:g for g in core['goals']};sem=load(ecr['semanticKindLedgerPath']);oldsem=load(q/'wirtschaft-b144-canonical-practice-phase-Q2-bounded-successor-root-v1/semantic693.practice-phase-Q2.AUTHOR-INERT.json');oldsd={d['goalId']:d for d in oldsem['decisions']};sd={d['goalId']:d for d in sem['decisions']};ordinary={id for id,d in sd.items() if d['semanticKind']=='curricularAtomic'}
ck('current702CanonicalUniqueIDs',len(by)==len(core['goals'])==702);ck('current346OrdinaryIDsExactToQualifiedPredecessor',ordinary=={id for id,d in oldsd.items() if d['semanticKind']=='curricularAtomic'});ck('all346OrdinaryWholeGoalsAndSemanticDecisionsExact',all(by[id]==oldby[id] and sd[id]==oldsd[id] for id in ordinary));ck('all9CurrentQualifiedNewPracticeKinds',len(set(by)-set(oldby))==9 and all(sd[id]['semanticKind']=='practiceAssessment' for id in set(by)-set(oldby)));ck('actualAandMCurrent346',rules['CQR-301']['metrics']['leafGoals']==346 and rules['CQR-302']['metrics']['reviewedGoals']==346);ck('strictM7CurrentDenominator346',rules['CQR-303']['metrics']['expectedGoals']==346)
for proof in sr['qualifiedRootWholePracticeProofs']:
 for key in ['seal','science','ready']:ck('Root9WholePracticeScienceProofImmutable:'+proof[key]['path'],bind(proof[key]['path'])==proof[key])
foreign=[]
for old in base['foreignCurriculaBaseline']:
 now=current[old['landscapeId']];ck('all20ForeignMaturityFloor:'+old['landscapeId'],int(now['maturity'][1:])>=int(old['maturity'][1:]));ns={r['id']:r['status'] for r in now['rules']};ck('allForeignPreviouslyPassedRulesRetained:'+old['landscapeId'],all(ns.get(r['id'])=='pass' for r in old['rules'] if r['status']=='pass'));foreign.append({'landscapeId':old['landscapeId'],'subject':old['subject'],'beforeMaturity':old['maturity'],'currentMaturity':now['maturity']})
for s in base['foreignRegistryEntries']:ck('all4ForeignRegistryWholeExact:'+s['subject'],next(z for z in reg['subjects'] if z['subject']==s['subject'])==s)
aq=q/'wirtschaft-assessed-target-terminal-filter-independent-a-READONLY-v1';aseal=aq/'SEALED-bounded-Economics-assessedTarget-route-filter-independent-KEEP.READONLY.json';arec=aq/'actual-independent-Economics-assessedTarget-only-expectation-whole-native-negative-cases-KEEP.receipt.json';anative=aq/'actual-native-thirteen-meaningful-route-predicate-negative-fixtures.READONLY.json';ar=load(arec);an=load(anative);ck('ExplicitIndependentAssessedTargetFilterASealImmutable',sha(aseal)=='sha256:b5104b347e16645f8b1ec6a156cee01c690ac3ca94ebf540bfad210787c62b01');ck('ExplicitIndependentAssessedTargetFilterAReceiptImmutable',sha(arec)=='sha256:f663dc94f7e37d6ca666aa7d21aae11cef933992506793234e1ce2591d3367e2');ck('Native13NegativeFixtures15ChecksWithMathPhysicsParityPreserved',len(an['cases'])==13 and len(an['checks'])==15 and all(ch['passed'] for ch in an['checks']) and sha(anative)=='sha256:0c2fc502bbd30a4556be9886127dfc5fa52e864a82de961c358aead3f7aebaa9');ck('NoStrictGateOrPAMOrWholeCoverageLowering',ar['strictCompletionThresholdOrGateLogicModified']==False and ar['PAMFullCoverageRequiredUnchanged'] and ar['allExistingCountryCourseAuthorityRequiresVisibleAndWholeClosureChecksUnchanged'])
for b in base['foreignDirectInputs']+base['allForeignCanonicalWholeBodies']+base['qualityImplementationBodies']:
 if b['path']=='app/scripts/generateCurriculumQualityStatus.ts':
  currentbytes=P(b['path']).read_bytes();bounded=ar['actualBoundedFilter'].encode();ck('Explicit14LineAssessedTargetQualitySuccessorCurrentExactlyQualifiedBytes',sha(b['path'])=='sha256:'+ar['actualCode']['sha256'] and currentbytes.count(bounded)==1);ck('RemoveExactlyBoundedFilterRestoresOriginalWholeProtectedQualityBytes',hashlib.sha256(currentbytes.replace(bounded,b'',1)).hexdigest()==b['sha256'].replace('sha256:',''))
 else:ck('all806ForeignAndOtherQualityBodiesExact:'+b['path'],bind(b['path'])=={k:b[k] for k in ['path','sha256','bytes']})
for sub,n in [('mathematik',807),('physik',478)]:
 c=next(x for x in report['curricula'] if x['subject'].lower()==sub);r=next(r for r in c['rules'] if r['id']=='CQR-303');ck('protectedM7:'+sub+':actualCurrentIDsAndAllFiveGates',c['maturity']=='M7' and r['status']=='pass' and r['metrics']['expectedGoals']==r['metrics']['strictComplete']==n)
out=P('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-final702-current346-M6-source-scope-and-foreign-floor-independent-c-READONLY-v1/reexecuted-stable702-current346-independent-endguard.READONLY.json')
out.write_text(json.dumps({'reviewer':'economics_common_source_course_independent_c','checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'allChecksPassed':True,'checks':checks,'report':bind(reportp),'baseline':bind(basep),'core':bind(corep),'currentSemanticLedger':bind(ecr['semanticKindLedgerPath']),'currentEconomicMaturity':ec['maturity'],'current346OrdinaryWholeGoalAndDecisionParity':True,'currentSourceRules':[rules[x] for x in ['CQR-000','CQR-003','CQR-004']],'currentBB100Pipeline':bb,'BE125HistoricalRawMAPPING3StillIncompleteWholeExact':be3,'BE125FreshScientificReviewClaim':False,'all35QualifiedViewCandidatesByteExact':True,'Source32_26HistoricalExact6ExplicitRootQualifiedSuccessors':True,'strictM7CurrentReportSeparate':rules['CQR-303'],'all20ForeignFloors':foreign,'all806ForeignAndOtherQualityBodiesExact':True,'explicitOneQualified14LineEconomicsAssessedTargetCodeSuccessor':{'Aseal':bind(aseal),'AindependentReview':bind(arec),'native13NegativeCasesAnd15Checks':bind(anative),'entireRestoredPredecessorSha':'sha256:'+hashlib.sha256(currentbytes.replace(bounded,b'',1)).hexdigest(),'freshNativeExecutionClaim':False},'all4ForeignRegistryWholeExact':True,'freshNativeGeneratorOrBuildRun':False,'activeMutation':False,'humanApproval':False,'CIClaim':'Read-only current metadata/endguard; Root actual Layer-A/build command exits and GitHub CI remain separate required evidence.'},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'output':str(out),'checks':len(checks),'maturity':ec['maturity'],'actualOrdinary':346,'wholeNodes':702,'foreignFloors':len(foreign)}))
