"""Whole bilingual, constructed molecular cases. No performed experiments."""
CASES = {}

def case(i, key, de, en):
    assert len(de) == len(en) == 5
    CASES.setdefault(i, []).append({
        'caseId': key, 'dataOrigin': 'Explicitly constructed educational model/data; no performed experiment, patient or learner data',
        'materialDe': de[0], 'materialEn': en[0], 'taskDe': de[1], 'taskEn': en[1],
        'workedResponseDe': de[2], 'workedResponseEn': en[2],
        'freshTransferTaskDe': de[3], 'freshTransferTaskEn': en[3],
        'workedFreshTransferDe': de[4], 'workedFreshTransferEn': en[4],
    })

case(0, 'meiosis-one-homolog-missegregation', [
    'Papiermodell eines menschlichen Chromosomenpaars 21: Nach der Replikation sind beide homologen Chromosomen zweichromatidig. In Meiose I wandern ausnahmsweise beide homologen Chromosomen in dieselbe Tochterzelle. Meiose II trennt danach die Schwesterchromatiden regelgerecht. Die übrigen Chromosomen werden normal verteilt. Eine normale zweite Keimzelle trägt 23 Chromosomen.',
    'Zeichne die vier resultierenden Keimzellen nur für Paar 21, ergänze ihre gesamten Chromosomenzahlen und erkläre die möglichen Zygoten nach Befruchtung mit der normalen Keimzelle. Unterscheide Meiosefehler und Genmutation.',
    'Die fehlende Trennung homologer Chromosomen heißt Non-Disjunction in Meiose I. Zwei Gameten erhalten zwei Chromosomen 21 und insgesamt 24 Chromosomen; zwei erhalten keines und insgesamt 22. Mit einer normalen Keimzelle entstehen modellhaft Zygoten mit 47 bzw. 45 Chromosomen: Trisomie bzw. Monosomie 21. Es wird die Anzahl eines ganzen Chromosoms verändert, nicht eine einzelne Basenfolge. Das Papiermodell erklärt den Entstehungsweg; es belegt weder Lebensfähigkeit jeder Zygote noch Symptome einer bestimmten Person.',
    'Im neuen Modell verläuft Meiose I normal, aber die Schwesterchromatiden von Chromosom 21 trennen sich in nur einer der zwei Meiose-II-Zellen nicht. Bestimme die vier Gameten und die Zygotenzahlen.',
    'Aus der unauffälligen Meiose-II-Zelle entstehen zwei normale Gameten mit 23. Die betroffene Zelle liefert einen mit 24 und einen mit 22. Nach normaler Befruchtung folgen zweimal 46, einmal 47 und einmal 45. Dieser Unterschied zu vier aneuploiden Gameten bei einem Meiose-I-Fehler begründet die zeitliche Zuordnung.'
], [
    'Paper model of human chromosome pair 21: both replicated homologues have two chromatids. Exceptionally both homologues move into one daughter cell at meiosis I. Meiosis II then separates sister chromatids normally. All other chromosomes segregate normally. A second normal gamete carries 23 chromosomes.',
    'Draw the four gametes for pair 21, add their total chromosome numbers and explain possible zygotes after fertilisation by the normal gamete. Distinguish this meiotic error from a gene mutation.',
    'Failure of homologous separation is nondisjunction at meiosis I. Two gametes receive two chromosome-21 copies and 24 chromosomes in total; two receive none and total 22. Normal fertilisation gives model zygotes with 47 or 45 chromosomes, trisomy or monosomy 21. Whole-chromosome number changes, rather than an individual base sequence. The model explains an origin; it establishes neither viability of every zygote nor a particular person’s symptoms.',
    'Fresh model: meiosis I is normal, but chromosome-21 sister chromatids fail to separate in just one meiosis-II cell. Determine four gamete and zygote totals.',
    'The unaffected division makes two normal 23-chromosome gametes. The affected division makes one 24 and one 22. Normal fertilisation gives two 46, one 47 and one 45. This differs from four aneuploid gametes following meiosis-I nondisjunction and locates the error in time.'
])
case(0, 'gamete-count-evidence-and-limits', [
    'Ein konstruierter Satz von vier Keimzellkarten zeigt 22+X, 22+X, 22+Y und 22+Y Chromosomen im normalen Vergleich. Ein zweiter Satz zeigt 22+XY, 22+XY, 22+0 und 22+0. Dabei sind die 22 Autosomen normal; X und Y bezeichnen unterschiedliche homologe Geschlechtschromosomen im vereinfachten Modell.',
    'Leite den plausiblen Meiosefehler des zweiten Satzes her. Bestimme die möglichen Zygoten nach Verbindung mit einer normalen 22+X-Keimzelle; erkläre, weshalb die Zahl von X-Chromosomen keine sichere klinische Vorhersage erlaubt.',
    'Im zweiten Satz sind X und Y in Meiose I gemeinsam weitergegeben worden, statt getrennt zu werden. Zwei Gameten tragen 24 Chromosomen (XY), zwei 22 (kein Gonosom). Mit der normalen X-Keimzelle entstehen 47,XXY oder 45,X. Beide sind Änderungen des Chromosomenbestands. Ein Karyotyp kann Entwicklung und Genexpression beeinflussen; individuelle Gesundheit, Ausprägung und Kontext werden hier nicht gemessen. Die Karten zeigen einen möglichen Mechanismus und keine Diagnose einer realen Person.',
    'Neue Karten zeigen X, X, YY und 0 als Gonosomenbestand der vier Gameten. Welcher Fehler ist mit diesem Muster vereinbar?',
    'Die erste Teilung kann X und Y normal getrennt haben; in der Y-tragenden Zelle wurden danach Schwesterchromatiden nicht getrennt. Dadurch bleiben zwei X-Gameten normal, während YY und 0 entstehen. Ein Meiose-II-Fehler ist somit möglich. Das Muster allein schließt weitere biologische Ursachen oder nachträgliche Fehler nicht sicher aus.'
], [
    'Constructed normal gamete cards show 22+X, 22+X, 22+Y and 22+Y. Another set shows 22+XY, 22+XY, 22+0 and 22+0. The 22 autosomes are normal; X and Y represent the different homologous sex chromosomes in this simplified model.',
    'Infer a plausible meiotic error in the second set. Determine zygotes after fertilisation with normal 22+X and explain why X-copy number does not provide a certain clinical prediction.',
    'X and Y passed together at meiosis I rather than separating. Two gametes total 24 chromosomes (XY) and two total 22 (no sex chromosome). With normal X fertilisation these give 47,XXY or 45,X. Both change chromosome complement. Development and expression may be affected, but individual health, phenotype and context are not measured here. The cards demonstrate a possible mechanism, not a real-person diagnosis.',
    'Fresh cards have X, X, YY and 0 as their sex-chromosome complements. What error is compatible with this pattern?',
    'Meiosis I may have separated X and Y normally, followed by failed sister-chromatid separation in the Y-containing cell. Two normal X gametes remain, with YY and 0 from the affected division. A meiosis-II error is possible; the pattern alone cannot exclude other biological or later errors.'
])

case(1, 'phenotype-health-separate-evidence', [
    'Fiktive Bildungsfallkarten, keine Patientendaten: A hat Karyotyp 47,XXY, ein abweichendes Körpermerkmal und keine berichtete Funktionsbeeinträchtigung. B hat denselben Karyotyp und eine ärztlich festgestellte behandlungsbedürftige hormonelle Funktionsstörung. C hat 46,XX und eine nicht genetisch bedingte Infektion. Weitere Merkmale sind unbekannt.',
    'Unterscheide pro Karte Chromosomenbestandsänderung, sichtbaren Phänotyp und Krankheit. Widerlege sowohl „jede Genommutation ist jede Krankheit“ als auch „ohne sichtbaren Unterschied gibt es nie Folgen“. Begründe die Grenzen der Angaben.',
    'A und B haben dieselbe numerische Genomänderung. Das beschriebene abweichende Merkmal von A ist ein Phänotypbefund, aus dem allein keine Krankheit folgt. Bei B ist zusätzlich eine Funktionsstörung belegt; diese zusätzliche Information begründet den Krankheitsbefund. C zeigt, dass Krankheit ohne Genommutation auftreten kann. Unbekannte oder nicht sichtbare Funktionen bleiben offen. Chromosomenbefunde ermöglichen keine Bewertung des Wertes einer Person und keine vollständige Prognose.',
    'Neue Fallkarte D: 45,X; der einzige gegebene Befund ist ein Chromosomenbild. Was darf eine sorgfältige Zusammenfassung behaupten?',
    'Sie darf eine numerische Gonosomenabweichung beschreiben. Ohne zusätzliche Entwicklungs-, Funktions- oder Gesundheitsbefunde dürfen weder ein bestimmter sichtbarer Phänotyp noch das Vorliegen oder die Schwere einer konkreten Krankheit als festgestellt bezeichnet werden. Mögliche Auswirkungen und tatsächlich belegte Auswirkungen bleiben getrennt.'
], [
    'Fictional education cards, no patient data: A has karyotype 47,XXY, a different bodily trait and no reported functional impairment. B has the same karyotype and a medically established hormone-function disorder requiring care. C has 46,XX and a non-genetic infection. Other traits are unknown.',
    'Separate chromosome-complement change, observable phenotype and disease for each card. Refute both “every genome mutation is every disease” and “no visible difference means no effects”. State the evidence limits.',
    'A and B share a numerical genome change. A’s different trait is phenotypic evidence, insufficient alone to establish disease. B has additional established functional impairment; that information supports a disease finding. C demonstrates disease without a genome mutation. Unknown or invisible functions remain unresolved. Chromosome findings neither rank a person’s worth nor provide a complete prognosis.',
    'Fresh card D has 45,X, with only a chromosome image supplied. What can a careful summary claim?',
    'It can describe a numerical sex-chromosome difference. Without developmental, functional or health evidence, no particular visible phenotype or presence/severity of a specific disease is established. Possible effects must remain separate from observed effects.'
])
case(1, 'plant-polyploid-phenotype-function', [
    'Konstruierter Vergleich zweier Pflanzenlinien derselben Art: P hat 2n=14, Q hat 4n=28. Q besitzt größere Zellen und größere Blätter. Beide Linien wachsen und bilden Samen unter den angegebenen Bedingungen. Eine dritte Linie R hat eine nachgewiesene Pilzinfektion. Der Vergleich dient als Gegenbeispiel, nicht als menschliches Krankheitsmodell.',
    'Ordne Polyploidie, Phänotyp und Krankheitsbefund. Erkläre mit Bezug auf den Menschen, weshalb eine Chromosomenbestandsänderung keine bloße Definition von Krankheit ist, aber auch nicht immer folgenlos bleibt.',
    'Q besitzt zusätzliche vollständige Chromosomensätze: eine Genommutation als Polyploidie. Größere Zellen und Blätter sind beobachtete Phänotypänderungen. In den gegebenen Funktionen ist keine Krankheit von Q belegt; R hat dagegen einen gesondert belegten Infektionsbefund. Daraus folgt nicht, dass Polyploidie beim Menschen dieselben Folgen hätte. Bei Menschen muss Gesundheit mit konkreten Entwicklungs- und Funktionsdaten beurteilt werden, statt aus Andersartigkeit allein eine Krankheit oder aus Pflanzenvitalität allgemeine Harmlosigkeit abzuleiten.',
    'Eine andere konstruierte polyploide Pflanzenlinie bildet keine Samen. Ist damit schon eine menschliche Krankheit bewiesen? Welche konkrete Folge ist belegt?',
    'Belegt ist fehlende Samenbildung dieser Linie unter den geprüften Modellbedingungen. Das ist eine reproduktive Funktionsänderung. Ihre Ursache und Bewertung brauchen zusätzlichen Kontext; daraus folgt weder eine menschliche Diagnose noch, dass jede polyploide Pflanze dieselbe Einschränkung zeigt.'
], [
    'Constructed plant-line comparison within one species: P has 2n=14, Q 4n=28. Q has larger cells and leaves. Both grow and make seeds under the supplied conditions. R has an established fungal infection. This counterexample is not a human-disease model.',
    'Classify polyploidy, phenotype and disease evidence. Relate the distinction to humans: why is changed chromosome complement not a definition of disease, yet not necessarily without effects?',
    'Q has extra complete chromosome sets, a genome mutation called polyploidy. Larger cells and leaves are observed phenotype differences. Disease of Q is not established by the supplied functions; R has separate infection evidence. Polyploidy need not have identical effects in humans. Human health requires developmental and functional evidence, rather than inferring disease from difference or universal harmlessness from plant viability.',
    'Another constructed polyploid plant line makes no seeds. Has a human disease thereby been demonstrated? What effect is established?',
    'Only failure of that line to produce seeds under the model conditions is established: a reproductive-function change. Cause and evaluation need further context. This supplies neither a human diagnosis nor a universal limitation in every polyploid plant.'
])

case(2, 'dna-rna-model-symbol-comparison', [
    'Bausteinkarten zeigen Phosphat, Zucker D (Desoxyribose) bzw. R (Ribose) und Basen. DNA-Modell: 5′-A G T C-3′ / 3′-T C A G-5′. RNA-Modell: 5′-A G U C-3′, zunächst ungepaart. Bindungslegende: durchgehende Kanten = kovalentes Zucker-Phosphat-Rückgrat; gestrichelte Verbindungen = Wasserstoffbrücken zwischen Basen.',
    'Beschreibe die Nukleotide und antiparallele Doppelstrangstruktur der DNA, vergleiche Zucker/Basen/Strangform mit RNA und erkläre, welche Modellteile Information und Paarung darstellen. Prüfe „RNA besitzt nie Basenpaarung“.',
    'Ein Nukleotid enthält Zucker, Phosphat und Base. Das DNA-Rückgrat verbindet Nukleotide eines Strangs kovalent; A–T und G–C paaren zwischen antiparallelen Strängen. Die Basenfolge trägt die Sequenzinformation. RNA verwendet Ribose und Uracil anstelle von Desoxyribose und Thymin. Das gegebene RNA-Modell ist einzelsträngig, kann aber durch komplementäre Bereiche intramolekular falten. „Nie Paarung“ ist daher falsch. Die Karten zeigen keine vollständige räumliche Chemie oder tatsächlichen Größenverhältnisse.',
    'Neue RNA 5′-G C A A A G C-3′ bildet einen Haarnadelansatz. Welche Randbasen können paaren und warum wird sie dadurch nicht DNA?',
    'Die äußeren G/C- und C/G-Positionen können antiparallel paaren; A A A bleibt im vereinfachten Modell die Schleife. Paarung ändert weder Ribose in Desoxyribose noch die chemische Identität der RNA. Ein gefalteter RNA-Einzelstrang ist kein DNA-Doppelstrang.'
], [
    'Cards represent phosphate, sugar D (deoxyribose) or R (ribose) and bases. DNA: 5′-A G T C-3′ / 3′-T C A G-5′. RNA: 5′-A G U C-3′, initially unpaired. Solid links indicate the covalent sugar-phosphate backbone; dashed links indicate hydrogen bonds between bases.',
    'Describe nucleotides and antiparallel DNA duplex structure; compare sugar, bases and strands with RNA. Explain information and pairing in the models and evaluate “RNA never base-pairs”.',
    'A nucleotide contains sugar, phosphate and base. DNA’s backbone covalently joins nucleotides within each strand; A–T and G–C pair across antiparallel strands. Base order carries sequence information. RNA uses ribose/uracil instead of deoxyribose/thymine. The supplied RNA is single-stranded but complementary regions may fold and pair within it. “Never pairs” is false. Cards do not reproduce complete three-dimensional chemistry or actual scale.',
    'Fresh RNA 5′-G C A A A G C-3′ begins a hairpin. Which end bases can pair, and why does this not make it DNA?',
    'Outer G/C and C/G positions can pair antiparallel, leaving A A A as the model loop. Pairing changes neither ribose into deoxyribose nor the molecule’s RNA identity. A folded single RNA strand is not a DNA duplex.'
])
case(2, 'model-error-repair-and-structure-limits', [
    'Ein fehlerhaftes Poster nennt eine DNA-Leiter mit parallel gerichteten 5′→3′-Strängen, A–C-/G–T-Paaren und einer durchgehenden Linie zwischen gegenüberliegenden Phosphaten. Das danebenstehende „RNA“-Band enthält Desoxyribose und T. Die dargestellte Helix ist ein Schulmodell, kein Atommodell.',
    'Korrigiere jede chemisch-strukturelle Aussage und erstelle ein vergleichbares richtiges DNA-/RNA-Modell. Erkläre, warum Formähnlichkeit allein die Molekülart nicht belegt und weshalb das Modell die Bindungsarten unterscheiden muss.',
    'DNA-Stränge laufen antiparallel; typische komplementäre Paare sind A–T und G–C. Kovalente Bindungen bilden je ein Zucker-Phosphat-Rückgrat; Wasserstoffbrücken zwischen Basen sind davon getrennt. Das RNA-Band braucht Ribose und im Standardmodell U statt T. Eine gezogene Leiter oder Spirale ohne diese Legende identifiziert keine chemische Struktur. DNA kann Information aus der Basenfolge speichern, während Paarung ein komplementäres Gegenstück ermöglicht. Eine korrekte Modelllegende darf nicht vortäuschen, alle Atome oder Helixwindungen maßstäblich zu zeigen.',
    'Ein neues Bild zeigt doppelsträngige RNA eines Modellvirus. Woran unterscheidest du sie trotz Doppelstrangform von DNA?',
    'Entscheidend sind die dargestellten Nukleotide: Ribose und RNA-Basen einschließlich U, nicht bloß die Zahl der Stränge. Komplementäre RNA-Stränge können eine Doppelstruktur bilden. „DNA immer doppelt, RNA immer einfach“ eignet sich als typische Einführung, nicht als ausnahmslose chemische Definition.'
], [
    'An incorrect poster shows a DNA ladder with parallel 5′→3′ strands, A–C/G–T pairs and continuous links between opposite phosphates. The adjacent “RNA” has deoxyribose and T. Its helix is a school model, not an atomic structure.',
    'Correct each structural/chemical claim and provide comparable DNA/RNA models. Explain why shape alone cannot identify a molecule and why bond types need distinction.',
    'DNA strands are antiparallel; standard complementary pairs are A–T and G–C. Covalent bonds form each sugar-phosphate backbone, separately from inter-base hydrogen bonds. RNA needs ribose and U rather than T in the standard model. An unlabelled ladder or spiral does not identify chemical structure. DNA sequence stores information and complementary pairing supplies a matching strand. A correct legend must not imply that all atoms or helical turns are drawn to scale.',
    'A fresh image shows double-stranded RNA from a model virus. How can you distinguish it from DNA despite its duplex shape?',
    'Its nucleotide chemistry, ribose and RNA bases including U, is decisive rather than strand count. Complementary RNA strands can form a duplex. “DNA always double, RNA always single” describes common introductory examples, not an exception-free chemical definition.'
])

case(5, 'exon-choice-functional-isoforms', [
    'Fiktives eukaryotisches Gen besitzt Exons E1/E2/E3/E4, jeweils mit vollständigen Codons und kompatiblem Leseraster. E1 enthält Start, E4 Stopp. In Zelltyp A wird E1–E2–E4, in B E1–E3–E4 in die reife mRNA übernommen. E2 codiert im Modell eine Bindedomäne für Partner X, E3 für Y. Beide mRNAs sind hier stabil und werden translatiert.',
    'Erkläre vom gleichen Gen über alternatives Spleißen zur Proteinvielfalt. Leite unterschiedliche Bindefunktionen ab und ordne den Beitrag zur Evolution ein, ohne somatische Isoformwahl mit einer neuen vererbbaren DNA-Mutation gleichzusetzen.',
    'Die gemeinsame Prä-mRNA wird unterschiedlich prozessiert: Introns werden entfernt, E2 oder E3 alternativ übernommen. Die erhaltenen Leseraster liefern zwei Proteinisoformen mit gleichem Anfang/Ende und unterschiedlichen Bindedomänen. Das erhöht Vielfalt ohne zusätzliche Gene. Proteinvariation kann unterschiedliche Funktionen ermöglichen. Für Selektion muss relevante Variation jedoch vererbbar sein und den Fortpflanzungserfolg beeinflussen, etwa durch erblich verschiedene Spleißregulation; die bloße Zelltypwahl beweist dies nicht. Spleißen ist ein möglicher Beitrag, keine universelle notwendige Bedingung sämtlicher Selektion.',
    'Neue Variante: Auslassen eines 4-Nukleotid-Exons verschiebt das Leseraster und erzeugt früh Stopp. Liefert jede alternative mRNA ein zusätzliches funktionales Protein?',
    'Nein. Vier Nukleotide sind kein Vielfaches von drei; Auslassen kann das nachfolgende Leseraster verändern. Ein früher Stopp kann eine verkürzte oder instabile RNA/Proteinvariante verursachen. Ob ein funktionsfähiges Produkt entsteht, braucht Sequenz-, Stabilitäts- und Funktionsbefunde. Mehr Transkriptvarianten sind nicht automatisch mehr funktionale Proteine.'
], [
    'A fictional eukaryotic gene has E1/E2/E3/E4 exons with complete codons and compatible frames. E1 contains start and E4 stop. Cell A retains E1–E2–E4; B retains E1–E3–E4. E2 encodes a model X-binding domain, E3 a Y-binding domain. Both mature RNAs are stable and translated here.',
    'Explain alternative splicing from one gene to protein diversity. Infer binding differences and place the contribution in evolution without equating somatic isoform choice with a new inherited DNA mutation.',
    'The shared pre-mRNA is processed differently: introns are removed and E2 or E3 is retained. Compatible frames yield two isoforms with common ends and different binding domains, increasing diversity without extra genes. Protein variation can enable different functions. Selection additionally needs relevant inherited variation and differential reproductive success, perhaps through inherited splicing regulation; cell-type choice alone demonstrates neither. Splicing is a possible contributor, not a universal prerequisite of all selection.',
    'Fresh variant: omission of a four-nucleotide exon shifts the frame and produces early stop. Does every alternative mRNA provide another functional protein?',
    'No. Four is not a multiple of three, so omission may change the downstream frame. Early termination may produce shortened or unstable RNA/protein. Functional output needs sequence, stability and function evidence. More transcript variants do not automatically mean more functional proteins.'
])
case(5, 'splice-regulation-inherited-versus-plastic', [
    'Konstruierte Population: Genallele R und r beeinflussen die Spleißregulation eines Rezeptorgens. R erzeugt im Modell häufiger Isoform A, r häufiger B. Nachkommen erben R/r nach den gegebenen Regeln. Bei Trockenheit beträgt der mittlere Fortpflanzungserfolg von R-Trägern 4, von r/r 2. Unabhängig davon verändert Temperatur in allen Tieren vorübergehend das A/B-Verhältnis; ihre DNA wird dabei nicht geändert.',
    'Trenne beide Variationsquellen. Erkläre Proteinvielfalt und weshalb im ersten Teil ein Selektionsprozess möglich ist, im zweiten allein noch nicht. Benenne die Grenzen der vereinfachten Erfolgsdaten.',
    'Alternative Exonwahl erzeugt A/B-Proteinisoformen. Die erblich unterschiedliche Regulation R/r verbindet diese Vielfalt im ersten Teil mit vererbbarer Variation und unterschiedlichem Fortpflanzungserfolg; unter den Modellbedingungen kann R häufiger werden. Die vorübergehende Temperaturreaktion beschreibt dagegen Plastizität innerhalb gleicher Genotypen. Allein daraus folgt keine vererbbare Häufigkeitsänderung. Fitnesswerte gelten nur für die genannten Bedingungen; Drift, weitere Gene und andere Umwelten fehlen. Die Umwelt erzeugt keine zielgerichtete „passende“ Mutation.',
    'Im neuen feuchten Lebensraum haben beide Genotypen denselben Fortpflanzungserfolg. Was folgt aus fortbestehender Proteinvielfalt für Selektion?',
    'Vielfalt bleibt vorhanden, aber ein selektiver Unterschied ist durch diese Daten nicht gezeigt. Allelfrequenzen können dennoch etwa durch Drift schwanken. Proteinvielfalt ermöglicht Unterschiede; ohne differenziellen Erfolg folgt keine gerichtete Selektion zugunsten der dargestellten Isoform.'
], [
    'Constructed population: R/r alleles influence splicing regulation of a receptor gene. R favours isoform A, r favours B. Offspring inherit R/r under supplied rules. In drought, mean reproductive success is 4 for R carriers and 2 for r/r. Separately, temperature temporarily changes A/B proportions in all animals without changing their DNA.',
    'Distinguish the two variation sources. Explain protein diversity and why selection is possible in the first part but not established by the second alone. Bound the simplified success data.',
    'Alternative exon choice produces A/B isoforms. Inherited R/r regulation links protein diversity to inherited variation and differential reproduction; R may increase under the model conditions. Temporary temperature response is plasticity within genotypes, insufficient alone to establish inherited frequency change. Fitness values apply only to stated conditions; drift, other genes and environments are absent. Environment does not purposefully produce a “needed” mutation.',
    'In a fresh wet habitat both genotypes have equal reproductive success. What does remaining protein diversity establish about selection?',
    'Diversity remains, but these data show no selective difference. Frequencies can still fluctuate through drift. Protein diversity permits differences; without differential success it does not establish directional selection for the shown isoform.'
])

case(6, 'hiv-cycle-host-translation-stage-targets', [
    'Vereinfachtes HI-Virus-Modell: Anheften/Eindringen; virale reverse Transkriptase schreibt RNA in DNA um; Integrase fügt DNA in Wirts-DNA ein; Wirtsenzyme transkribieren virale mRNA; Wirtsribosomen bilden virale Proteine; Zusammenbau, Knospung und Reifung mithilfe viraler Protease. Modellmessung neuer Produkte: Kontrolle virale DNA 100, neue virale Proteine 100; spezifischer RT-Blocker vor Infektion DNA 2, Proteine 3. Zahlen sind fiktive relative Einheiten.',
    'Erkläre den ganzen Zyklus und den Eingriff in Wirts-Proteinbiosynthese. Deute die Produktzahlen, mögliche Wirtsfolgen und zwei prinzipielle Angriffspunkte. Leite keine tatsächliche Behandlungsempfehlung oder Heilungsquote ab.',
    'Das Virus nutzt Wirtszellen, ihre Transkription und insbesondere Ribosomen zur Herstellung viraler Bestandteile; es besitzt keine eigene vollständige Proteinbiosynthese. Reverse Transkription und Integration gehen viraler Expression voraus. Weniger neue DNA und Proteine beim früh eingesetzten RT-Blocker sind mit einer Hemmung dieses frühen Schritts vereinbar. Prinzipielle Eingriffe betreffen RT, Integrase oder Reifungsprotease; unspezifische Hemmung aller Wirtsribosomen würde auch notwendige Wirtsproteine beeinträchtigen. Infizierte Immunzellen können geschädigt werden. Die Konstruktion liefert weder klinische Wirksamkeit noch vollständige Entfernung integrierter Virus-DNA.',
    'Neuer Modellversuch: Protease wird erst nach Proteinsynthese blockiert. Neue virale Proteine bleiben 100, infektiöse neue Partikel fallen auf 4. Erkläre, weshalb dies kein Widerspruch ist.',
    'Die Protease wirkt bei der Reifung, nach dem Übersetzen viraler mRNA. Vorhandene neue Proteine können daher normal gezählt werden, während ihre Verarbeitung zu funktionsfähigen Partikeln stockt. Proteinmenge und infektiöse Partikel messen verschiedene Zyklusschritte. Ein RT-Blocker kann vorhandene integrierte DNA nicht rückwirkend entfernen.'
], [
    'Simplified HIV model: attachment/entry; viral reverse transcriptase copies RNA into DNA; integrase inserts DNA into host DNA; host enzymes transcribe viral mRNA; host ribosomes make viral proteins; assembly, budding and maturation using viral protease. Constructed new-product measurements: control viral DNA 100/new proteins 100; specific RT inhibitor before infection DNA 2/proteins 3, fictional relative units.',
    'Explain the whole cycle and use of host protein synthesis. Interpret products, possible host effects and two conceptual intervention points. Infer no real treatment advice or cure rate.',
    'The virus uses host cells, transcription and especially ribosomes to make components; it has no complete protein-synthesis apparatus of its own. Reverse transcription/integration precede expression. Reduced new DNA/protein with early RT inhibition is consistent with blocking that early step. Conceptual targets include RT, integrase and maturation protease; nonselectively blocking all host ribosomes would impair essential host proteins too. Infected immune cells can be damaged. The construction proves neither clinical efficacy nor elimination of integrated viral DNA.',
    'Fresh model: protease is inhibited after synthesis. New proteins remain 100, infectious new particles fall to 4. Why is this consistent?',
    'Protease acts during maturation after mRNA translation. New proteins can remain abundant while processing into functional particles fails. Protein amount and infectious particles report different stages. RT inhibition cannot retroactively remove already integrated DNA.'
])
case(6, 'virus-own-polymerase-host-ribosome-limit', [
    'Zwei ausdrücklich vereinfachte Virusmodelle: V1 bringt eine RNA-Polymerase für die Vermehrung seines RNA-Genoms mit. V2 lässt sein DNA-Genom im Zellkern von Wirtsenzymen ablesen. Beide benötigen Wirtsribosomen und tRNAs für neue Virusproteine. Ein Modellstoff blockiert nur Bindung eines viralen Eintrittsproteins an den passenden Wirtsrezeptor; zweite Messreihe startet erst nach bereits erfolgtem Eintritt.',
    'Vergleiche die Zyklen vom Eintritt bis zur Freisetzung und widerlege „alle Viren benötigen genau dieselben Wirtsenzyme“. Erkläre einen selektiven Eintrittsansatz, seine zeitliche Grenze und mögliche Wirtsfolgen.',
    'Beide brauchen Eintritt, Genomexpression/-vermehrung, Synthese viraler Proteine, Zusammenbau und Freisetzung. V1 liefert die gegebene RNA-Polymerase, V2 nutzt hier Kernenzyme; trotzdem translatiert der Wirt in beiden Modellen. Der spezifische Rezeptorbindungsblock kann neue Eintritte verhindern, beseitigt aber keinen schon begonnenen intrazellulären Zyklus. Proteinproduktion/Ressourcenverbrauch und Zellschädigung können Wirtsfunktionen beeinträchtigen. Die genaue Freisetzung durch Lyse oder Knospung hängt vom Virus ab und ist nicht durch eine universelle Zeichnung bestimmt.',
    'Neue Behauptung: „Antibiotika gegen bakterielle 70S-Ribosomen stoppen automatisch jedes Virus.“ Bewerte sie anhand der Modelle.',
    'Das folgt nicht. Diese Viren verwenden eukaryotische Wirtsribosomen, keine eigenen bakteriellen 70S-Ribosomen. Ein bakterieller Translationsangriff liefert daher keinen allgemeinen antiviralen Mechanismus. Ein Eingriff in Wirtsfunktionen hätte zudem eigene Selektivitäts- und Sicherheitsfragen; das Modell ersetzt keine therapeutische Prüfung.'
], [
    'Two explicitly simplified virus models: V1 supplies an RNA polymerase for copying its RNA genome. V2 has host nuclear enzymes read its DNA genome. Both need host ribosomes/tRNAs for new viral proteins. A model compound blocks only viral entry-protein binding to the matching host receptor; a second measurement begins after entry already occurred.',
    'Compare entry-to-release cycles and refute “every virus needs exactly the same host enzymes”. Explain a selective entry concept, its timing limit and possible host effects.',
    'Both require entry, genome expression/copying, viral protein synthesis, assembly and release. V1 supplies the specified RNA polymerase; V2 uses nuclear enzymes here, but both use host translation. Specific receptor blockade can prevent fresh entry without erasing an existing intracellular cycle. Protein production/resource use and cell damage may impair host functions. Lysis versus budding depends on the virus and is not settled by one universal diagram.',
    'Fresh claim: “Antibiotics against bacterial 70S ribosomes automatically stop every virus.” Evaluate it using the models.',
    'No. These viruses use eukaryotic host ribosomes rather than their own bacterial 70S ribosomes. A bacterial translation target supplies no universal antiviral mechanism. Host-function interference raises separate selectivity/safety questions; the model replaces no therapeutic testing.'
])

case(7, 'antisense-complementarity-target-control', [
    'Fiktives mRNA-Zielstück 5′-AUG GCU-3′ liegt im angegebenen Translationsstartbereich. Modellregel: Eine passend antiparallel gebundene Antisense-RNA versperrt hier den Ribosomenzugang. A = 3′-UAC CGA-5′; B = 3′-UAC UGA-5′. Außer der Sequenz ist alles gleich. Das Gen bleibt unverändert; RNA-Abbau ist für dieses Modell nicht vorausgesetzt.',
    'Begründe die Paarung und leite Proteinfolgen für A gegenüber der Fehlpaarungskontrolle B ab. Erkläre eine mögliche medizinische Anwendung als Prinzip und die Grenze zwischen Knock-down und DNA-Knock-out.',
    'A ist komplementär und antiparallel: A–U, U–A, G–C usw. Es kann nach der Modellregel den Startbereich maskieren und die Neubildung des Zielproteins vermindern. B besitzt eine Fehlpaarung; ein gleich starker Effekt ist nicht aus der Regel ableitbar und müsste geprüft werden. Ein denkbares Prinzip wäre die gezielte Verringerung eines schädlichen Genprodukts. Dies verändert zunächst RNA-Nutzung, nicht die DNA-Sequenz, und ist ein Knock-down statt Genentfernung. Zustellung, Stabilität, Nebenbindungen und tatsächlicher Nutzen sind damit nicht belegt.',
    'Neues Zielstück 5′-AUG AAU-3′: Konstruiere eine passende Antisense-RNA in 5′→3′-Schreibweise und sage voraus, ob das alte A zwingend noch gleich wirksam ist.',
    'Antiparallel entspricht 3′-UAC UUA-5′, in 5′→3′ also 5′-AUU CAU-3′. Das alte A passt nicht mehr vollständig; gleiche Wirksamkeit darf nicht behauptet werden. Sequenzabhängigkeit und weitere Bedingungen sind zu prüfen. Das Rückwärtsschreiben ändert nicht die tatsächliche Paarungsrichtung.'
], [
    'Fictional mRNA target 5′-AUG GCU-3′ is in the specified translation-start region. Model rule: an antiparallel complementary antisense RNA masks ribosome access here. A = 3′-UAC CGA-5′; B = 3′-UAC UGA-5′. Only sequence differs. DNA remains unchanged; RNA degradation is not assumed in this model.',
    'Justify pairing and infer protein effects for A versus mismatch control B. Explain a possible medical application concept and distinguish knock-down from DNA knock-out.',
    'A pairs complementarily and antiparallel, A–U/U–A/G–C etc. Under the rule it masks initiation and reduces newly produced target protein. B mismatches; an equally strong effect is not established and needs testing. A possible application concept is selectively reducing a harmful gene product. This changes RNA utilisation, not DNA sequence, and is knock-down rather than gene removal. Delivery, stability, off-target pairing and actual benefit remain unproven.',
    'Fresh target 5′-AUG AAU-3′: build matching antisense in 5′→3′ notation. Must old A retain the same effect?',
    'Antiparallel complement is 3′-UAC UUA-5′, or 5′-AUU CAU-3′. Old A no longer fully matches; identical efficacy cannot be claimed. Sequence dependence and other conditions need investigation. Reversing written orientation does not reverse physical pairing rules.'
])
case(7, 'antisense-expression-versus-cell-loss', [
    'Konstruierte Zellkultur-Daten, keine Patienten: ohne RNA-Hilfe Ziel-mRNA 100, Zielprotein 100, Zellzahl 100; passende künstliche Antisense-RNA mRNA 98, Protein 25, Zellzahl 99; Kontroll-RNA mRNA 101, Protein 96, Zellzahl 100. Ein natürliches regulatorisches Antisense-Transkript kann nach der gegebenen Modellregel ebenfalls den Translationsstart maskieren.',
    'Deute die Daten mechanistisch und prüfe, ob RNA-Abbau oder bloßer Zellverlust nötig sind. Übertrage das natürliche Prinzip auf eine künstliche Anwendung, ohne alle Antisense-Mechanismen gleichzusetzen.',
    'Die fast gleiche mRNA-/Zellmenge bei stark verringertem Protein passt zu verringerter Translation des Zieltranskripts. Weniger Zellen erklärt die Größenordnung nicht; starker RNA-Abbau ist hier nicht belegt. Natürliches und künstliches komplementäres RNA-Binden können in diesem Modell denselben Startblock erzeugen. Andere Systeme können zusätzliche Abbauwege besitzen, aber diese Daten beweisen keinen bestimmten Enzymweg. Eine mögliche zielgerichtete Proteinabsenkung ist ein Forschungsprinzip, keine belegte klinische Heilung.',
    'Neue Daten: Protein 20, aber auch Zellzahl 20 bei Kontroll- und Antisense-RNA. Was fehlt für den spezifischen Antisense-Schluss?',
    'Die Proteinabnahme kann durch Zellverlust erklärt werden. Es fehlen Normalisierung pro lebensfähiger Zelle, spezifische Sequenzkontrollen und Ziel-/Nichtzielvergleiche. Eine allgemeine Schädigung ist nicht gleich selektiver Hemmung der Zieltranslation.'
], [
    'Constructed cell-culture data, no patients: without RNA aid target mRNA 100/protein 100/cell count 100; matching artificial antisense mRNA 98/protein 25/cells 99; control RNA mRNA 101/protein 96/cells 100. A natural regulatory antisense transcript can also mask initiation under the supplied rule.',
    'Interpret mechanism and test whether RNA degradation or cell loss is needed. Transfer the natural principle to an artificial application without treating every antisense mechanism as identical.',
    'Nearly unchanged mRNA/cell abundance with strongly reduced protein is consistent with reduced translation. Cell loss cannot explain its magnitude; strong RNA degradation is not established. Natural/artificial complementary binding can both block initiation in this model. Other systems can add degradation pathways, but these data identify no particular enzyme route. Selective protein reduction is a research concept, not evidence of clinical cure.',
    'Fresh data: protein 20 and cell count 20 with both control and antisense RNA. What is missing for a specific antisense conclusion?',
    'Protein loss can be explained by cell loss. Normalisation per viable cell, sequence-specific controls and target/nontarget comparisons are missing. General toxicity is not equivalent to selective inhibition of target translation.'
])

case(8, 'ribosome-selective-binding-targets', [
    'Modellbakterium besitzt cytoplasmatische 70S-Ribosomen aus 30S/50S-Untereinheiten; die kernhaltige Vergleichszelle besitzt im Cytoplasma 80S aus 40S/60S. Molekül X bindet laut Material ausschließlich an eine definierte bakterielle 30S-Stelle und stört tRNA-Codon-Erkennung. Molekül Y bindet ausschließlich eine bakterielle 50S-Stelle und stört Peptidverknüpfung. S-Werte sind Sedimentationskoeffizienten, keine addierbaren Massen.',
    'Leite beide Angriffsorte aus den Unterschieden ab und erkläre die Folgen für bakterielle Proteinbildung. Begründe mögliche Selektivität und weshalb „für Menschen immer völlig nebenwirkungsfrei“ daraus nicht folgt.',
    'X greift in korrekte Decodierung/Aminosäurezuordnung, Y in Bildung der Peptidkette ein; dadurch kann bakterielle Synthese funktionsfähiger Proteine abnehmen. Die anders aufgebauten cytoplasmatischen Wirtsribosomen bieten einen Ansatz für selektive Bindung. Daraus folgt keine universelle Sicherheit: Zustellung, Konzentration, andere Bindungsstellen und mitochondriale Ribosomen sind nicht geprüft. 30S+50S ergeben wegen sedimentationsabhängiger Form/Reibung nicht arithmetisch 80S. Die Konstruktion begründet mögliche Targets, keine Arzneimittelwahl.',
    'Neue bakterielle Mutation verändert nur die X-Bindestelle, lässt normale Translation bestehen. Was ist für X und Y zu erwarten?',
    'X kann schwächer binden und seine Wirkung verlieren; das ist ein möglicher Resistenzmechanismus. Y besitzt im Modell eine andere Bindestelle und muss nicht betroffen sein. Die Behauptung „jede Resistenz wirkt gegen alle Antibiotika“ folgt nicht; tatsächliche Bindung und Wachstumsfolgen müssten gemessen werden.'
], [
    'Model bacteria have cytoplasmic 70S ribosomes with 30S/50S subunits; nucleated comparison cells have cytoplasmic 80S with 40S/60S. X binds only a specified bacterial 30S site and disrupts tRNA-codon recognition. Y binds only a specified bacterial 50S site and disrupts peptide joining. S values are sedimentation coefficients, not additive masses.',
    'Derive both targets and protein-synthesis effects. Justify possible selectivity and explain why this does not imply “always entirely side-effect free in humans”.',
    'X interferes with decoding/amino-acid assignment; Y with peptide-chain formation, potentially reducing functional bacterial proteins. Differently structured host cytoplasmic ribosomes permit a selective-binding concept. Universal safety does not follow: delivery, concentration, other targets and mitochondrial ribosomes are not tested. Sedimentation depends on shape/friction, so 30S+50S is not an arithmetic 80S. These are possible targets, not a drug-choice recommendation.',
    'A fresh bacterial mutation changes only X’s binding site while preserving translation. Predict effects for X and Y.',
    'X may bind less and lose effect, a possible resistance mechanism. Y uses another site in the model and need not be affected. “Every resistance affects every antibiotic” does not follow; actual binding/growth consequences require measurement.'
])
case(8, 'translation-coupling-versus-nuclear-boundary', [
    'Gegeben sind typische Bakterienzelle P ohne Kern und Eukaryotenzelle E mit Kern. In P kann Translation an entstehender mRNA beginnen; in E liegt zwischen Kerntranskription und cytoplasmatischer Translation Reifung/Export. Modellinhibitor Z bindet spezifisch bakterielle Initiationsfaktoren; eine zweite Karte behauptet als Ziel „Kernmembran aller Bakterien“.',
    'Vergleiche die räumlich-zeitlichen Prozesse und begründe einen möglichen bakterienspezifischen Translationsangriff. Verwirf das falsche Target und trenne die Mechanismusableitung vom Nachweis eines wirksamen Antibiotikums.',
    'P ermöglicht gekoppelte Transkription/Translation ohne Kernexport; E trennt typische Kernprozesse und cytoplasmatische Synthese. Unterschiedliche bakterielle Initiationsfaktoren könnten mit der vorgegebenen spezifischen Bindung ein Angriffspunkt sein, der Start neuer Peptide beeinträchtigt. Eine Kernmembran ist in P nicht vorhanden und daher kein entsprechendes bakterielles Target. Unterschiede allein beweisen noch kein brauchbares Mittel: Aufnahme, spezifische Bindung, Wirtsverträglichkeit und Resistenz gehören zu offenen Prüfungen. Nicht alle Organellen folgen dem cytoplasmatischen E-Modell.',
    'Ein neues Modellmolekül blockiert jede tRNA in P und E gleichermaßen. Ist dies aus dem Vergleich ein selektives Antibiotikakonzept?',
    'Nein. Beide Systeme brauchen passende beladene tRNA. Eine unterschiedslose Hemmung beeinträchtigt auch Wirts-Proteinbildung. Ein möglicher selektiver Angriff müsste an einem tatsächlich unterschiedlichen, spezifisch erreichbaren Merkmal ansetzen; der gemeinsame Prozess allein begründet keine Selektivität.'
], [
    'Typical bacterium P has no nucleus; eukaryotic E has one. P can begin translation on emerging mRNA; E processes/exports RNA between nuclear transcription and cytoplasmic translation. Model Z specifically binds bacterial initiation factors. Another card proposes targeting “the nuclear membrane of every bacterium”.',
    'Compare spatial/timing organisation and derive a possible bacterial translation target. Reject the false target and distinguish mechanism reasoning from demonstration of a usable antibiotic.',
    'P permits coupled transcription/translation without nuclear export; E separates typical nuclear processes and cytoplasmic synthesis. Distinct bacterial initiation factors could provide a target under the specified binding rule, impairing initiation of new peptides. P has no nuclear membrane to target. Differences alone prove no usable agent: uptake, specificity, host compatibility and resistance remain open. Not every organelle follows the cytoplasmic E model.',
    'A fresh molecule blocks every tRNA equally in P and E. Is this a selective antibiotic concept derived from the comparison?',
    'No. Both need matching charged tRNA; nonselective blockade also impairs host proteins. Selectivity requires a genuinely different, specifically accessible feature. A shared essential process alone does not establish it.'
])

case(9, 'two-enzyme-chain-knockout-rescue', [
    'Fiktive Pigmentkette: farbloser Stoff S wird durch Enzym E1 (Gen A) in farbloses I, dann durch E2 (Gen B) in blaues P umgewandelt. Funktionsfähige Allele A/B wirken dominant, aa/bb liefern hier kein funktionsfähiges jeweiliges Enzym. Zusatz von I umgeht nur den ersten Schritt. E1/E2 sind Genprodukte; die DNA selbst katalysiert die Stoffumwandlung nicht.',
    'Erkläre die Genwirkkette und Phänotypen für A_B_, aaB_ und A_bb. Sage die Wirkung von I-Zusatz vorher und leite daraus die Reihenfolge der Unterbrechungen ab. Nenne einen nicht enzymatischen Proteintyp.',
    'A_B_ bildet beide Enzyme und blaues P. aaB_ unterbricht S→I und bleibt ohne Zusatz farblos; I-Zusatz ermöglicht mit E2 P-Bildung. A_bb bildet I, aber kein P; I-Zusatz behebt fehlendes E2 nicht. Das verknüpft Genexpression, Proteinfunktion und Merkmal über eine geordnete Wirkfolge. DNA codiert Enzyme; Enzyme katalysieren. Strukturproteine wie Keratin erfüllen andere Aufgaben als Enzyme. Die Dominanz- und Funktionsregeln sind Modellannahmen, keine universelle Regel für alle Allele.',
    'Eine neue Kette S→I→J→P hat E3 für J→P. Bei einem E3-Knock-out helfen I und J nicht, P-Zugabe färbt aber das Modell. Begründe die Grenze einer scheinbaren „Reparatur“.',
    'Die Unterbrechung liegt im letzten enzymatischen Schritt. Vorgelagerte Stoffe bleiben ohne funktionsfähiges E3 unzureichend. P-Zugabe ersetzt das Produkt, nicht Gen oder Enzym; der sichtbare Phänotyp kann sich ändern, während die genetische Unterbrechung bestehen bleibt.'
], [
    'Fictional pigment pathway: colourless S becomes colourless I via E1 (gene A), then blue P via E2 (gene B). Functional A/B alleles are dominant here; aa/bb provide no respective functional enzyme. Added I bypasses only step one. E1/E2 are gene products; DNA does not itself catalyse conversion.',
    'Explain pathway/phenotypes for A_B_, aaB_ and A_bb. Predict I addition and locate interruptions. Name a non-enzymatic protein function.',
    'A_B_ makes both enzymes and blue P. aaB_ blocks S→I and stays colourless unless supplied I allows E2 to make P. A_bb makes I but not P; adding I cannot replace E2. This links expression, protein function and phenotype through ordered steps. DNA encodes enzymes; enzymes catalyse. Structural proteins such as keratin have different roles. Dominance/function assumptions are model rules, not universal allele properties.',
    'Fresh S→I→J→P pathway uses E3 for J→P. E3 knock-out is not rescued by I/J but added P colours the model. Explain the limit of this apparent “repair”.',
    'The last catalytic step is interrupted. Upstream substances cannot replace E3. Adding P supplies product rather than repairing gene or enzyme; phenotype may change while the genetic interruption remains.'
])
case(9, 'transport-and-enzyme-joint-gene-effect', [
    'Fiktive Zellkarte: Transportprotein T (Gen t) importiert S; Enzym C (Gen c) wandelt intrazelluläres S in signalgebendes P um; Strukturprotein K (Gen k) stabilisiert die Zellform. Knock-out t: außen S vorhanden, innen S/P fehlen. Knock-out c: innen S vorhanden, P fehlt. K bleibt in beiden Fällen normal.',
    'Verknüpfe die drei unterschiedlichen Proteinaufgaben mit Merkmalen und erkläre die Wirkung der beiden Genwirkkettenunterbrechungen. Prüfe die Behauptung „jeder Genwirkkettenschritt muss ein Enzym sein“.',
    'T transportiert, C katalysiert, K stabilisiert. T und C wirken geordnet zusammen, damit P ein Signalmerkmal ermöglicht. t-Knock-out blockiert die Bereitstellung des Substrats, c-Knock-out seine Umwandlung; beide verlieren P auf verschiedenen Wegen. Eine Genwirkkette kann funktional auch einen Transportprozess einschließen; nicht jedes Genprodukt ist ein Enzym. Normales K erklärt, warum nicht automatisch jede Zellfunktion ausfällt. Das Modell beschreibt gegebene Rollen, nicht alle Wechselwirkungen einer realen Zelle.',
    'Eine neue Karte liefert S direkt ins Zellinnere. Welchen Knock-out kann das unter den Modellannahmen umgehen, welchen nicht?',
    'Direkte Lieferung umgeht T und kann beim t-Knock-out zusammen mit vorhandenem C P entstehen lassen. Fehlendes C wird nicht ersetzt; c-Knock-out bleibt blockiert. Ein Produkt- oder Substrat-Rescue ist kein Nachweis einer reparierten DNA.'
], [
    'Fictional cell: transporter T (gene t) imports S; enzyme C (gene c) converts intracellular S into signalling P; structural K (gene k) stabilises shape. t knock-out has external S but no intracellular S/P. c knock-out has intracellular S but no P. K remains normal in both.',
    'Link the different protein functions to traits and explain both pathway interruptions. Evaluate “every gene-pathway step must be an enzyme”.',
    'T transports, C catalyses and K stabilises. T/C cooperate in sequence to make signalling P. t knock-out prevents substrate supply; c knock-out prevents conversion. Both lose P through different steps. A functional gene pathway can include transport, so not every product is an enzyme. Normal K explains why not every cell function fails. These supplied roles do not enumerate all real-cell interactions.',
    'Fresh material delivers S directly inside. Which knock-out can this bypass under the assumptions?',
    'It bypasses T, allowing existing C to make P in t knock-out. It does not replace C, so c knock-out remains blocked. Substrate/product rescue does not demonstrate repaired DNA.'
])

case(10, 'same-genome-differentiated-expression', [
    'Konstruierte kernhaltige Zelltypen M und N besitzen dieselbe DNA-Sequenz. In M aktiviert Transkriptionsfaktor F einen Enhancer des Modellgens E: E-mRNA/Protein hoch. In N fehlt F und die entsprechende Chromatinregion ist weniger zugänglich: E-mRNA/Protein niedrig. Gen K für ein gemeinsames Strukturprotein ist in beiden aktiv. Diese Zellen sind keine reifen Erythrozyten.',
    'Erkläre Mechanismen der Regulation und unterschiedlicher Zelleigenschaften trotz gleicher DNA. Verknüpfe die Beobachtung mit Entwicklung/Spezialisierung und grenze Genexpression von Mutation ab.',
    'DNA enthält in beiden Zellen dieselben Möglichkeiten, doch F-Bindung und Chromatinzugänglichkeit verändern, wie häufig E transkribiert wird. Unterschiedliche Proteinmengen können unterschiedliche Zellfunktionen ermöglichen, während gemeinsame K-Expression gemeinsame Eigenschaften erhält. Entwicklung und Spezialisierung können so regulierte Ausdrucksmuster stabilisieren. Die gegebenen Befunde ändern nicht die Basenfolge. Sie beweisen weder, dass jede Körperzelle ausnahmslos identische DNA besitzt, noch dass nur ein Faktor sämtliche Zelltypen erklärt.',
    'Neue Zellkarte: F wird hinzugefügt, aber E bleibt trotz kontrollierter F-Bindung schwach; der Promotor ist blockiert. Was folgt für eine einfache „F allein genügt“-Regel?',
    'Die Regel reicht nicht. Zugänglichkeit und zusätzliche regulatorische Bedingungen können notwendig sein; gebundener F erzwingt nicht automatisch Transkription. Eine plausible Erweiterung umfasst Promotor-/Chromatinzustand, ohne aus unveränderter DNA eine neue Mutation zu erfinden.'
], [
    'Constructed nucleated cell types M/N share DNA sequence. In M, factor F activates an enhancer of model gene E, with high E mRNA/protein. N lacks F and has less accessible chromatin there, with low E mRNA/protein. Common structural gene K is active in both. These are not mature red blood cells.',
    'Explain regulation and different properties despite shared DNA. Connect development/specialisation and distinguish expression from mutation.',
    'Both DNA sequences offer the same possibilities, but F binding/chromatin access change E transcription frequency. Different protein amounts can enable different functions, while shared K expression maintains common properties. Development/specialisation may stabilise regulated patterns. The supplied findings do not change base sequence, establish identical DNA in every body cell without exception, or show one factor explains all cell types.',
    'Fresh cell receives F but E stays low despite controlled F binding; its promoter is blocked. What happens to “F alone suffices”?',
    'That rule is insufficient. Accessibility/additional regulation may be necessary; factor binding does not automatically force transcription. Promoter/chromatin state is a plausible extension without inventing a mutation in unchanged DNA.'
])
case(10, 'reversible-environmental-expression-response', [
    'Fiktive Pflanzenzellen gleicher Linie: vor Trockenreiz Schutzgen P-mRNA 1, Protein 1; nach Trockenreiz mRNA 8, Protein 6; nach Wasserzufuhr später mRNA 1,5, Protein 2. Sequenzkontrolle zeigt gleiche DNA. Modellkette: Reiz→Signal→Transkriptionsfaktor→P-Transkription. Ein Silencer an Gen Q hält dessen Transkription unter diesen Bedingungen niedrig.',
    'Erkläre flexible Anpassung mit mindestens zwei Regulationsmechanismen und unterscheide sie von Zelldifferenzierung und evolutionärer Anpassung. Deute, warum Protein und mRNA nicht sofort gleich zurückgehen.',
    'Der Reiz aktiviert Signale/Faktoren und erhöht P-Transkription, sodass mehr Schutzprotein entsteht. Ein Silencer kann dagegen ein anderes Gen hemmen; Regulation bedeutet nicht bloß überall mehr Expression. Unterschiedliche Abbauzeiten und Translation erklären zeitversetzte Mengen. Die reversible Antwort gleicher Zellen ist physiologische Anpassung; stabile Spezialisierung betrifft Zellfunktionen während Entwicklung. Evolutionäre Anpassung betrifft erblich veränderte Populationszusammensetzung über Generationen, die diese Kurzzeitdaten nicht zeigen.',
    'Neue Daten zeigen nach Reiz Protein 7, mRNA weiterhin 1. Welche Regulation ist alternativ möglich, ohne den ursprünglichen Mechanismus als erwiesen auszugeben?',
    'Veränderte Translation oder geringerer Proteinabbau kann Protein erhöhen, obwohl mRNA gleich bleibt. Zusätzliche Messungen sind nötig. Ein Proteinanstieg allein beweist weder erhöhte Transkription noch Mutation; mehrere Regulationsstufen sind möglich.'
], [
    'Fictional same-line plant cells: before drought P mRNA/protein 1/1; after stimulus 8/6; later rewatering 1.5/2. Sequence control shows unchanged DNA. Model chain: stimulus→signal→transcription factor→P transcription. A silencer keeps gene Q low under these conditions.',
    'Explain flexible response with at least two regulatory mechanisms; distinguish differentiation and evolutionary adaptation. Explain delayed protein/mRNA recovery.',
    'Stimulus activates signals/factors and increases P transcription/protection protein. A silencer can inhibit another gene; regulation is not universally increased expression. Different degradation times/translation produce delays. Reversible response within the same cells is physiological adjustment; differentiation concerns stable developmental specialisation. Evolutionary adaptation concerns inherited population change across generations, absent from these short-term data.',
    'Fresh data show protein 7 while mRNA remains 1. What alternative regulation is possible without claiming the old mechanism established?',
    'Increased translation or reduced protein breakdown can raise protein despite stable mRNA. Further measurements are required. Protein increase alone proves neither increased transcription nor mutation; several regulatory levels are possible.'
])

case(11, 'replication-pcr-technical-and-repair', [
    'Modellkarten: Zelle trennt DNA-Stränge durch Helicase und startet Synthese mit Primase-RNA-Primern; Polymerase verlängert nur 5′→3′. PCR verwendet Hitze zur Trennung, zwei synthetische DNA-Primer und thermostabile DNA-Polymerase. Zellkarte zusätzlich: falsch eingebaute Base kann durch geeignete Polymerase-Korrektur oder nachgeschaltete Reparatur entfernt/ersetzt werden; beschädigte Base durch Basenexzisionsreparatur. Das sind nicht identische Mechanismen.',
    'Vergleiche Vorlage, Start, Richtung und Wiederholung. Erkläre das technische Problem eines hitzeempfindlichen Enzyms und die Lösung. Beschreibe ausdrücklich den Wert natürlicher Fehlerkorrektur und Basenreparatur; prüfe „PCR repariert automatisch jedes Gen“.',
    'Beide kopieren komplementär an DNA-Vorlagen und brauchen ein Primerende; Synthese erfolgt 5′→3′. Zelluläre Replikation vervielfältigt hier das Genom vor Teilung, PCR einen begrenzten Primerabschnitt in Temperaturzyklen. Hitze ersetzt Helicase, würde aber ein ungeeignetes Enzym zerstören; thermostabile Polymerase übersteht die Zyklen. Korrektur/Reparatur verringern Fehler und erhalten Information, sind aber nicht vollkommen. Basenexzision entfernt gezielt beschädigte Basen und ergänzt/repariert den Strang. PCR-Amplifikation ist kein allgemeines Reparaturverfahren; manche PCR-Enzyme korrigieren Fehlpaarungen, andere nicht.',
    'Neue PCR enthält einen falsch gewählten Primer und trotzdem eine korrekturlesende Polymerase. Garantiert dies das richtige Zielprodukt? Begründe.',
    'Nein. Korrekturlesen betrifft geeignete Synthesefehler, nicht automatisch die Auswahl eines biologisch richtigen Zielabschnitts. Falsche oder unspezifische Primer können unpassende Produkte erzeugen; Zielkontrollen und Primerspezifität bleiben nötig. Fehlerarme Vervielfältigung und richtige Zielwahl sind verschiedene Anforderungen.'
], [
    'Model cards: cells separate DNA with helicase and initiate using primase-made RNA primers; polymerase extends only 5′→3′. PCR uses heat, two synthetic DNA primers and thermostable polymerase. Cell repair cards distinguish polymerase proofreading/downstream mismatch repair from damaged-base removal by base-excision repair.',
    'Compare template, initiation, direction and repetition. Explain heat-sensitive enzyme difficulty/solution. Explicitly describe natural error correction and base repair, and evaluate “PCR automatically repairs every gene”.',
    'Both copy complementary DNA templates and need a primer end, extending 5′→3′. Cellular replication copies the genome before division here; PCR copies a primer-bounded region through temperature cycles. Heat replaces helicase but destroys unsuitable enzymes; thermostability solves that repeated-heating problem. Correction/repair reduce errors and preserve information without being perfect. Base excision removes damaged bases and restores DNA. Amplification is not general gene repair; some PCR enzymes proofread whereas others do not.',
    'Fresh PCR has an incorrectly selected primer despite a proofreading polymerase. Does this guarantee the right target product?',
    'No. Proofreading addresses eligible synthesis errors, not automatically biological target choice. Wrong/nonspecific primers can generate wrong products; target controls and specificity remain needed. Accurate copying and correct target choice are separate requirements.'
])
case(11, 'repair-perturbation-and-amplification-evidence', [
    'Fiktive DNA-Läsion im Zellmodell: eine beschädigte Base ist durch das Reparatursystem erkennbar. Regelrechte Basenexzision: Glycosylase entfernt Base, weitere Enzyme bearbeiten Stelle, Polymerase ergänzt nach Gegenstrang, Ligase schließt. Kontrollpopulation zeigt 2 verbleibende Läsionen je 1000 Stellen, blockierte Reparatur 30. Separat idealisierte PCR startet mit 3 doppelsträngigen Zielmolekülen und verdoppelt nach jedem vollständigen Zyklus.',
    'Erkläre die Reparaturschritte und deren biologische Bedeutung. Berechne nach vier PCR-Zyklen die ideale Zielzahl, vergleiche Amplifikation mit Reparatur und benenne beide Modellgrenzen.',
    'Die Abfolge entfernt die beschädigte Base und stellt anhand des unbeschädigten Gegenstrangs einen korrekten Abschnitt her; Ligase verbindet das Rückgrat. Weniger verbleibende Läsionen bei funktionierendem System passen zu Informationserhaltung, nicht zu Fehlerfreiheit. PCR ergibt ideal 3×2⁴=48 Zielmoleküle. Sie vervielfältigt DNA zwischen Primern und erkennt damit nicht notwendig die dargestellte Zellläsion. Reale Ausbeute kann durch Effizienz/Materialgrenzen abweichen; Reparaturdaten sind konstruiert und erlauben keine klinische Prognose.',
    'Neue natürliche Fehlpaarung besitzt noch keinen beschädigten Basenrest. Darf das Basenexzisionsschema ohne Begründung als einziger Reparaturweg eingesetzt werden?',
    'Nein. Fehlpaarungsreparatur, korrekturlesende Polymerase und Basenexzision haben unterschiedliche Erkennungsaufgaben. Für den konkreten Fehler ist der passende Mechanismus zu begründen. Alle Systeme erhalten Information, aber die gemeinsame Funktion macht sie nicht zu einem identischen Verfahren.'
], [
    'Fictional cellular lesion is recognisable by repair: glycosylase removes a damaged base, other enzymes process the site, polymerase restores from the opposite strand and ligase seals. Control has 2 residual lesions/1000 sites, blocked repair 30. Separate ideal PCR starts with three double-stranded target molecules and doubles after every complete cycle.',
    'Explain repair steps/significance. Calculate ideal target count after four PCR cycles; compare amplification with repair and state model limits.',
    'The sequence removes damage, restores DNA from the intact opposing template and seals the backbone. Fewer residual lesions is consistent with preserving information, not perfection. Ideal PCR gives 3×2⁴=48 targets. It amplifies a primer-bounded region without necessarily recognising that cellular lesion. Real yield can differ through efficiency/resources; constructed repair data provide no clinical prognosis.',
    'A fresh natural mismatch has no damaged base residue. May base excision simply be asserted as the only repair route?',
    'No. Mismatch repair, polymerase proofreading and base excision have different recognition tasks. The appropriate mechanism must be justified for the error. Their shared information-preserving function does not make them one identical procedure.'
])
