import json,hashlib,datetime
from pathlib import Path
root=Path('/home/enpasos/projects/skillpilot')
out=root/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-05/chemie-b008-inquiry-targeted-continuation-candidate-v1'
inv=json.loads((out/'current-nine-inventory.json').read_text())
def text(de,en):return {'descriptionDe':de,'descriptionEn':en}
plans=[
('split_review','Fragestellung/Hypothese und Untersuchungsplanung/-durchführung sind getrennt prüfbare Teilkompetenzen. Die Sek-I-Anforderungen an einfache, angeleitete Untersuchungen werden mit selbstständigen Oberstufenanforderungen und Modellprüfungen vermischt.',[
('question-hypothesis','Sek I',text('Die lernende Person kann aus einem Alltagsphänomen eine chemisch untersuchbare Frage ableiten und eine begründete, durch Beobachtungen überprüfbare Hypothese formulieren.','The learner can derive an investigable chemical question from an everyday phenomenon and formulate a justified hypothesis that can be tested through observations.')),
('investigation','Sek I',text('Die lernende Person kann zur Prüfung einer chemischen Hypothese eine einfache Untersuchung planen, unter Anleitung sicher durchführen und ihre Beobachtungen nachvollziehbar protokollieren.','The learner can plan a simple investigation to test a chemical hypothesis, carry it out safely under guidance, and document observations clearly.'))],
'Selbstständige qualitative/quantitative Untersuchungen sowie theorie- und modellgeleitete Prüfungen aus C10/C11/C12 benötigen einen ausdrücklich gebundenen Oberstufenanspruch; bestehende Zuordnungen nicht auf die beiden Sek-I-Vorschläge umetikettieren.'),
('split_review','Dokumentation, quantitative Auswertung und Prüfung der Aussagekraft sind eigenständig prüfbar. Tabellenkalkulation und digitale Messwerterfassung sind bereits im C8-Inhaltsbereich belegt; das Problem ist der Umfang und Grad der Selbstständigkeit, nicht die Existenz dieser Werkzeuge.',[
('data-documentation','Sek I',text('Die lernende Person kann einfache chemische Mess- und Beobachtungsdaten mit Größen, Einheiten und Versuchsbedingungen übersichtlich dokumentieren.','The learner can clearly document simple chemical measurements and observations with quantities, units, and experimental conditions.')),
('data-interpretation','Sek I',text('Die lernende Person kann einfache chemische Daten mit einer geeigneten Darstellung auswerten, erkennbare Muster und mögliche Messfehler berücksichtigen und die Ergebnisse mit einer Ausgangshypothese vergleichen.','The learner can evaluate simple chemical data using a suitable representation, consider visible patterns and possible measurement errors, and compare the results with an initial hypothesis.'))],
'Gültigkeitsprüfung, eigenständige mathematische/digitale Auswertungsmethoden und komplexe Darstellungswechsel aus C11/C12 bleiben gesonderte Quellendeckungspflichten. Vorgeschlagene Größen/Einheiten dienen nachvollziehbarer Dokumentation; sie sind keine neue unabhängige Spezialkompetenz.'),
('split_review','Die Sek-I-Frage nach naturwissenschaftlich beantwortbaren Fragen ist von der Oberstufenreflexion des eigenen Erkenntnisprozesses und dem formalen Gültigkeitskriterienkatalog zu trennen.',[
('inquiry-limits','Sek I',text('Die lernende Person kann an einer chemischen Untersuchung erklären, welche Frage durch die Beobachtungen beantwortet wird und welche Fragen oder Unsicherheiten offenbleiben.','The learner can explain which question is answered by the observations in a chemical investigation and which questions or uncertainties remain open.')),
('validity-criteria','Sek II',text('Die lernende Person kann die Aussagekraft chemischer Untersuchungsergebnisse anhand von Reproduzierbarkeit, Falsifizierbarkeit, Intersubjektivität, logischer Konsistenz und Vorläufigkeit begründet beurteilen.','The learner can assess the validity of chemical investigation results using reproducibility, falsifiability, intersubjectivity, logical consistency, and provisionality.'))],
'C12-GA.1.14/.15 und weitere Teilbindungen nicht als verbindlichen C8-Katalog behandeln. Eine getrennte Oberstufenreflexion des eigenen Erkenntnisprozesses ist noch mit der konkreten Teilbindung und atomaren Abgrenzung zu entscheiden.'),
('split_review','Quellenprüfung, Informationsaufbereitung/Präsentation und Bewertung von Argumenten sind unabhängige prüfbare Routinen. Pharmazeutische Fachquellen und komplexe Darstellungsformen sind tatsächlich in höheren Jahrgangsstufen belegt, aber keine allgemeine Sek-I-Pflicht.',[
('source-appraisal','Sek I',text('Die lernende Person kann vorgegebene chemische Informationsquellen auf fachliche Eignung und Vertrauenswürdigkeit prüfen und ihre Auswahl begründen.','The learner can assess given chemistry information sources for relevance and trustworthiness and justify their selection.')),
('information-presentation','Sek I',text('Die lernende Person kann chemische Informationen aus geeigneten Quellen sachgerecht strukturieren, verständlich darstellen und die verwendeten Quellen angeben.','The learner can structure chemical information from suitable sources, present it clearly, and identify the sources used.')),
('argument-appraisal','Sek I',text('Die lernende Person kann zu einer alltagsnahen chemischen Frage Pro- und Kontra-Argumente anhand vorgegebener Bewertungskriterien abwägen.','The learner can weigh arguments for and against an everyday chemistry-related question using given evaluation criteria.'))],
'Die bereits existierende Zielkompetenz Untersuchungsergebnisse adressaten- und sachgerecht darstellen ist vor Anlage eines Präsentationskindes auf Überschneidung zu prüfen. Selbstständige komplexe Quellenrecherche, Zitatkennzeichnung und pharmazeutische Kontexte werden in oberstufenspezifischen Bindungen erhalten, nicht pauschal gestrichen.'),
('open_keep_split_dissent','Die C9-Quelle verbindet Aufgaben, Anwendungsbereiche, gesellschaftliche Bedeutung und Berufswahl ausdrücklich. Ein kohärenter Anwendungsfall kann dies integriert prüfen. Rund A KEEP gegen Rund B SPLIT bleibt dennoch offen; kein automatisches Überstimmen.',[],
'KEEP-Option: bestehende DE/EN-Texte unverändert in einem konkreten chemischen Berufsfeld prüfen. Die partiellen C12-Bindungen sind keine Garantie, dass dieser begrenzte C9-Anspruch alle Oberstufen-Bewertungskompetenzen deckt. Alternative Trennung benötigt eine bewusste Atomaritätsentscheidung.'),
('revise_candidate','Die kriteriengeleitete Entscheidung ist eine integrierte Bewertungsroutine. Der aktuelle Text reiht Auswahlkontexte und Teilhandlungen auf. Kürzung soll alle Kriterienfamilien, Chancen/Risiken, Grenzen und Überprüfung einer begründeten Entscheidung erhalten.',[
('decision-evaluation','Sek I / Sek II mit getrennten Anforderungsgraden',text('Die lernende Person kann bei einer alltagsnahen chemischen Entscheidung ethische, ökologische, ökonomische und sicherheitsbezogene Kriterien begründen, Chancen und Risiken abwägen und ihre Entscheidung unter Berücksichtigung der Grenzen chemischer Aussagen überprüfen.','The learner can justify ethical, environmental, economic, and safety criteria for an everyday chemistry-related decision, weigh benefits and risks, and review their decision while considering the limits of chemical evidence.'))],
'C10 benötigt eine überschaubare, gegebene Fallbasis; C11/C12 verlangen anspruchsvollere selbstständige Kriterien- und Strategieanwendung. Der Profilkontext darf keine individuelle Arzneimittelberatung und kein neues spezielles Entscheidungsverfahren als eigenständige Kompetenz einführen. Nach neuer Formulierung D/A/M/Profilbindung gezielt erneuern.'),
('split_review_and_stage_repair','Einflüsse auf die Entwicklung wissenschaftlichen Wissens und die Bewertung gesellschaftlicher Auswirkungen von Produkten/Verfahren sind zwei Gegenstände. Das Oberstufenziel liegt im tatsächlichen gebundenen Buch unter einem Sek-I-Kapitel.',[
('knowledge-influences','Sek II',text('Die lernende Person kann an einem chemischen Beispiel erklären und beurteilen, wie soziale, kulturelle, technologische, historische, ökologische und ökonomische Bedingungen die Entwicklung naturwissenschaftlichen Wissens beeinflussen.','The learner can explain and assess, using a chemistry example, how social, cultural, technological, historical, environmental, and economic conditions influence the development of scientific knowledge.')),
('societal-impacts','Sek II',text('Die lernende Person kann gesellschaftliche und ökologische Auswirkungen eines chemischen Produkts oder Verfahrens anhand fachlicher Kriterien im Sinne nachhaltiger Entwicklung bewerten.','The learner can assess the societal and environmental impacts of a chemical product or process using scientific criteria in relation to sustainable development.'))],
'C11.1.11 und C12-GA.1.31/.33 getrennt abdecken. Das neue Buchkapitel und Oberstufen-Voraussetzungen müssen tatsächlich gebunden werden; Umbenennen allein behebt das nicht.'),
('conditional_keep_after_stage_repair','Die zwei tatsächlichen direkten C12-GA-Quellenbindungen .1.21 und .1.24 stützen fachliches Erklären/Argumentieren UND konstruktiven Austausch/Standpunktreflexion. Eine Streichung der zweiten Hälfte wäre sachlich unbegründet. Der aktuelle Oberstufenanspruch wird aber im Sek-I-Buchkapitel gezeigt.',[],
'Bestehende DE/EN-Texte KEEP als kohärente fachliche Diskussion; das ist eine neue begründete Kandidatenposition, keine Aufhebung des historischen BLOCK. Erst passende Oberstufen-Buchseite, direkter Quellennachweis, Voraussetzungen und gezielte unabhängige D-Klärung erlauben Abschluss.'),
('stage_bounded_revision_candidate','Der allgemeine Modellvergleich passt zu Sek I. Verbindliche komplexe organische, biochemische und pharmazeutische Modelle greifen dagegen belegte C11/C12-Anforderungen auf und überschreiten das C8-Niveau.',[
('model-comparison','Sek I',text('Die lernende Person kann einfache analoge oder digitale Modelle und Simulationen zum Aufbau der Materie und zu chemischen Reaktionen nutzen, ihre Aussagekraft vergleichen und ihre Grenzen an einem konkreten Beispiel erklären.','The learner can use simple analogue or digital models and simulations of matter and chemical reactions, compare their explanatory power, and explain their limits using a concrete example.')),
('advanced-model-comparison','Sek II',text('Die lernende Person kann Modelle und Simulationen komplexer organischer Moleküle und molekularer Wechselwirkungen in biochemischen oder pharmazeutischen Zusammenhängen vergleichen und ihre Aussagekraft und Grenzen begründen.','The learner can compare models and simulations of complex organic molecules and molecular interactions in biochemical or pharmaceutical contexts and justify their explanatory power and limits.'))],
'Bestehende C11/C12-Mappings und Weiterentwicklungsanspruch nicht stillschweigend verlieren. Überschneidung mit bestehenden Struktur-/Modellzielen und tatsächliche prerequisites des Oberstufenziels vor finalem Split klären. Für das Wasser-Modell sind Bindungs-/Polaritätskenntnisse je Kontext bereitzustellen oder als passende Voraussetzung zu binden.')]
find=[]
for idx,(g,p) in enumerate(zip(inv['goals'],plans),1):
 status,reason,proposals,debt=p
 change=[{'proposalKey':key,'stage':stage,**words} for key,stage,words in proposals]
 image={'decision':'retain_current_binding_pending_semantic_decision','reason':'Die tatsächlichen aktuellen V-Bytes stimmen mit QA und Buch überein. Bestehende unveränderte Bildprüfung wird nicht neu gestartet. Bei angenommenem Split ist Motivpassung gezielt zu prüfen.'}
 if idx==5:image={'decision':'targeted_image_correction_required','reason':'Tatsächlich angesehenes aktuelles Bild enthält pauschale Nutzen-aufwärts/Risiko-abwärts-Aussagen in Medizin/Energie. Ohne Fallbedingungen unzulässige allgemeine Nutzen-Risiko-Wertung; diese Texte korrigieren, sinnvolle Berufs-/Anwendungsstruktur erhalten.'}
 if idx==3:image={'decision':'targeted_image_content_clarification_required','reason':'Tatsächlich angesehenes aktuelles Bild nennt formal Wenn nicht C, dann widerlegt! ohne Versuchsbedingungen. Eine erfolglose Durchführung bzw. ein Messfehler widerlegt nicht automatisch eine Hypothese. Bedingungen und zuverlässige Beobachtung ergänzen; das formale Kriterienbild nur einem dafür passenden Oberstufenziel zuordnen.'}
 if idx==9:image={'decision':'retain_for_bounded_model_candidate','reason':'Tatsächlich angesehenes Wasser-Modellbild kontrastiert Kugel-Stab, Kalotten und Ladungs-/Simulationsmodell. Kein konkreter fachlicher Bildfehler gesehen. Fortführung am begrenzten Modellvergleich ist sinnvoll, sofern Wassergeometrie/Polarität kontextgerecht erklärt bzw. vorausgesetzt werden.'}
 find.append({'ordinal':idx,'goalId':g['goalId'],'currentGoalFingerprint':g['book']['goalFingerprint'],'currentPageFingerprint':g['book']['pageFingerprint'],'before':g['before'],'existingDDecisions':{'roundA':g['existingD']['a']['decision'],'roundB':g['existingD']['b']['decision']},'candidateDecision':status,'findingDe':reason,'afterProposals':change,'keepOption':g['before'] if idx in (5,8) else None,'remainingSourceCoverageObligation':debt,'sourceBindings': [{'sourceGoalId':x['source']['id'],'sourceSpan':x['source']['sourceSpan'],'matchType':x['mapping']['matchType']} for x in g['sourceBindings']],'atomicityDecision':'existing_A_current_but_D2_dissent_open' if status not in ('conditional_keep_after_stage_repair','revise_candidate') else 'integrated_competence_candidate_pending_targeted_D_resolution','memoryDecision':{'status':'no_memory_needed','reason':'Diese Kompetenz verlangt nachvollziehbares Beobachten, Auswerten, Beurteilen, Darstellen oder Argumentieren im Fall. Reines Abfragen eines Kriterienkatalogs ersetzt das nicht; keine neuen SRS-Karten erforderlich. Bei Textänderung ist die aktuelle M-Bindung gezielt neu zu prüfen.'},'imageDecision':image,'prerequisiteDecision':{'current':g['canonicalContext']['requires'],'requiredCheck':'Keine routinemäßigen fachlichen prerequisites ergänzen. Bei Split innerhalb der Kompetenzfamilie nur tatsächlich notwendige Frage-/Datengrundlagen binden. Bei Oberstufenkontext passende Fachkenntnisse statt einer alleinigen strukturellen Oberstufen-Wurzel nachweisen.'},'readyForStrictM7':False})
time=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z')
obj={'schemaVersion':1,'artifactKind':'independent_targeted_continuation_D_findings','status':'ai_candidate','frozenAt':time,'reviewer':'Codex independent continuation C; exact deployed model version not exposed','notAReplacementD2Run':True,'existingPNotReadBeforeFreeze':True,'existingDArtifactsUnchanged':True,'bindingSummary':{'nineGoalAndPageBindingsCurrent':True,'fullCanonicalBookDigestCurrent':False,'fullCanonicalDigestDifferenceDoesNotInvalidateUnchangedSelectedGoalBindings':True,'nineAtomicityFingerprintsCurrent':True,'nineMemoryFingerprintsCurrent':True,'nineVisualAssetQaAndBookBindingsCurrent':True,'knownCurrentVisualContentFindings':[3,5],'bookStageMismatches':[7,8]},'liveNormativeSources':[{'url':'https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium%20/8/chemie','sections':['C8.1 Kompetenzerwartungen','C8.1 Inhalte'],'observation':'Einfache angeleitete Untersuchung und Modell-/Quellenarbeit; digitale Messwerterfassung und Tabellenkalkulation im Inhalt genannt.'},{'url':'https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/11/chemie','sections':['C11.1'],'observation':'Tatsächlich komplexe organische, biochemische/pharmazeutische Modell- und Quellenkontexte sowie Wissenseinflüsse.'},{'url':'https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/12/chemie/grundlegend','sections':['C12.1.2','C12.1.3','C12.1.4'],'observation':'Formal gültigkeitsbezogene Kriterien, fachliche Argumentation und konstruktiver Austausch sind explizit belegt; nicht nur alte C8-Provenance.'},{'url':'https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/9/chemie/ch','sections':['C9.1'],'observation':'Anwendungen, gesellschaftliche Bedeutung und Berufsfelder ausdrücklich verbunden.'}],'inputInventoryByteDigest':'sha256:'+hashlib.sha256((out/'current-nine-inventory.json').read_bytes()).hexdigest(),'goals':find,'limitations':['Keine neuen fachlichen Review-Freigaben oder menschlichen Freigaben.','Keine aktuelle PDF-Neubindung und keine neuen realen chemischen Untersuchungen; vorhandene unveränderte D2-Artefakte bleiben historisch und fachlich offen.','Nur drei aktuelle B008-Bilder inhaltlich angesehen; für sechs unveränderte Bilder wird die vorhandene gültige V-Bindung erhalten.','Split-Kinder haben Vorschlagsnamen, noch keine neuen kanonischen IDs. Oberstufen-Quellendeckung ist ausdrücklich offen.']}
p=out/'D-findings.frozen.json';p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
sha='sha256:'+hashlib.sha256(p.read_bytes()).hexdigest();(out/'D-freeze.sha256').write_text(sha+'  D-findings.frozen.json\n')
print(time,sha)
