import {createHash} from 'node:crypto'
export const packageId='physics100-four-goal-consolidation-v1'
export const base='curricula/DE/Gymnasium/'
export const landscapeId='7f6fc60c-9fcc-4cc2-b07e-f897a1d0338a'
export const ids={
optical:'ea17b0af-3d53-5a10-acda-7fd9348537ce',nuclear:'49872cc0-401f-5464-9235-4763df4db5cf',stars:'7df923a0-6470-595e-8cea-53126fad9506',transistor:'d36727cc-ce42-51a3-9425-41afb0b9acdd',
modulation:'122e83ac-c9cf-50c1-8a73-a1e3db347f21',spectrum:'4a7cbe83-b694-57d3-85ce-1eeca418daaf',reflection:'58fc7852-722c-5a67-be6a-bfd1be0b527e',
comparison:'50877233-7abf-54df-b347-6d3224678fc9',energy:'7d78da7f-6af5-440a-9d6b-6cab4bee8dd2',risk:'bb5c5eab-2fc1-5336-b8cf-14d147695487',evaluation:'7e719cc2-0866-5267-a252-e7e7ac0d03f1',binding:'cde9b548-2cf4-59ad-b5d4-a71872afbe56',qvalue:'5492f0e0-cbae-574e-a853-182616205ed3',
lifecycle:'6f896466-e0ec-5f8d-82ad-2890433c82ba',hr:'206fe51d-cc78-5422-b139-32cc97eb1c37',hrCluster:'9b47a758-1b5d-5906-84c9-8621050d5aa5',hrQuantitative:'f67550ac-df22-5a3e-8172-f04642efca64',
amplifier:'af50bb9a-fd7b-50f5-9698-48c4efe99032',diode:'7f0798cb-5966-5dcb-beb3-84f637ab6139',solidParent:'620d4320-6b93-500b-8a62-86d02b1ed1f0',
nuclearAssessment:'a77e53d5-246d-52df-86a2-d14f7a08fb77',switchAssessment:'88f27aab-8724-5a4d-8543-e49ebcb54b8e',alphaTunnel:'76bcbdcb-3003-5e6a-952e-aa36eb8f97ee'}
const keys={audio:'canonical_physics_audio_light_transmission_apparatus',multiplex:'canonical_physics_optical_multiplex_channel_model',switch:'canonical_physics_bipolar_transistor_switch_function',flipflop:'canonical_physics_bistable_transistor_flipflop_interpret',elements:'canonical_physics_stellar_heavy_element_argument_evaluate',endstage:'canonical_physics_stellar_end_state_mass_loss_predict'}
function id(s){const h=createHash('sha1').update('DE-GYM-CANONICAL-PHYSICS:'+s).digest('hex');return h.slice(0,8)+'-'+h.slice(8,12)+'-5'+h.slice(13,16)+'-'+((parseInt(h[16],16)&3)|8).toString(16)+h.slice(17,20)+'-'+h.slice(20,32)}
for(const [k,v] of Object.entries(keys))ids[k]=id(v)
export const paths={canonical:base+'canonical/DE_DEU_S_GYM_CANONICAL_PHYSIK.de.json',atomicity:base+'quality/semantic-atomicity/canonical-physics-full.review.jsonl',memory:base+'quality/memory-card-review/canonical-physics-full.review.jsonl',cards:base+'quality/memory-card-review/canonical-physics-full.cards.review.jsonl',kinds:base+'quality/release-model/physik.semantic-kinds.json',
he:base+'mapping/DE-HE/upper-secondary/hessen_physics_upper_secondary_source_extraction_to_canonical_physics.review.json',
by:base+'mapping/DE-BY/gymnasium/bavaria_physics_source_extraction_to_canonical_physics.review.json',
hh:base+'mapping/DE-HH/upper-secondary/hh_physics_upper_secondary_source_extraction_to_canonical_physics.review.json',
rp:base+'mapping/DE-RP/upper-secondary/rp_physics_upper_secondary_source_extraction_to_canonical_physics.review.json',
bw:base+'mapping/DE-BW/upper-secondary/bw_physics_upper_secondary_source_extraction_to_canonical_physics.review.json',
bwLower:base+'mapping/DE-BW/lower-secondary/bw_physics_lower_secondary_source_extraction_to_canonical_physics.review.json',
heGenerator:'app/scripts/generateHePhysicsSourceExtraction.ts',byGenerator:'app/scripts/generateByPhysicsSourceExtraction.ts',hhGenerator:'app/scripts/generateHhPhysicsSourceExtraction.ts',rpGenerator:'app/scripts/generateRpPhysicsSourceExtraction.ts',bwGenerator:'app/scripts/generateBwPhysicsSourceExtraction.ts'}
export const originalSources=[
{path:base+'input/BY/gymnasium/Physik.json',locator:'Ph13 EA5.2; GA-ASTRO4.3/4.4; Ph10.4.3,5.1,5.2; Ph13 GA4.1,4.8 and EA4.1,4.10; GA-ASTRO3.2. Each original JSON clause read individually.'},
{path:base+'input/HE/upper-secondary/kernkurriculum_gymnasiale_oberstufe-physik.pdf',locator:'Printed/PDF pp.46-47: Q4.3 nuclear reaction/energy clauses separate; Q4.5 GK/LK pnp OR npn, switch/flipflop; LK amplifier demonstration and/or student experiment. Q4.6 LK stellar life cycles.'},
{path:base+'input/HH/physik-gyo-2022-data.pdf',locator:'Printed/PDF p.33 4.2: evolution/end stages of Sun and massive stars, not heavy-element argument or initial-mass/mass-loss forecast. Two extraction records repeat this narrow source aspect.'},
{path:base+'input/RP/Physik_Sekundarstufe_II_MSS.pdf',locator:'Printed/PDF pp.38,68 optional electronics includes transistor switching only; pp.40,64 nuclear processes, binding energy and technical energy applications. No amplifier obligation in these clauses.'},
{path:base+'input/BW/BP2016BW_ALLG_GYM_PH_V2.pdf',locator:'Printed pp.23,38 (PDF25,40): 3.3.4(4) reaction description separate from risk evaluation(5); 3.5.6(6) solar fusion energy/binding, 3.5.7(5-7) qualitative formation/main sequence/post-main sequence.'}]
export const officialByExperimentSelection={url:'https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/13/physik/erhoeht',checkedDate:'2026-09-07',section:'Ph13 EA5, introduction and EA5.2',finding:'Five of seven listed experiments are selected as student experiments; remaining experiments are compulsory demonstrations with competency aspects included. Do not claim all seven require an individual student build.'}
function goal(k,title,titleEn,description,descriptionEn,requires,scope,area,process,level='AB2'){return {id:ids[k],shortKey:keys[k],title,titleEn,description,descriptionEn,weight:1,tags:[...(k==='audio'||k==='multiplex'?['LK']:k==='elements'||k==='endstage'?['GK']:['GK','LK']),'canonical'],contains:[],requires,type:'atomic',dimensionTags:{framework:'canonical-gymnasium-physics',demandLevel:level,processCompetencies:process,guidingIdeas:[area==='Astrophysik'?'LI_KOSMOS':area==='Elektromagnetische Wellen'?'LI_WELLEN':'LI_TECHNIK'],phase:'GLOBAL',area,topicCode:keys[k].toUpperCase()},competencyRefs:process.map(x=>'PROCESS.'+x),applicability:{jurisdiction:scope},extendedData:{applicabilityMappingInheritance:'boundary',applicabilityOverrides:{jurisdiction:scope}}}}
export const newGoals=[
goal('audio','Einen Audio-Licht-Übertragungsversuch funktional umsetzen','Implement an Audio-over-Light Experiment',
'Die lernende Person kann einen vorgegebenen Versuch zur Übertragung eines Audiosignals mit Licht funktional erläutern, indem sie Signalumwandlung in Sender und Empfänger sowie den Übertragungsweg erklärt, und ihn bei Auswahl als Schülerexperiment funktionsfähig aufbauen.',
'The learner can explain the operation of a specified audio-over-light experiment by accounting for signal conversion in the transmitter and receiver and the transmission path, and can build a working setup when it is selected as a student experiment.',
[ids.spectrum,ids.reflection],['DE-BY'],'Elektromagnetische Wellen',['PK1_EXPERIMENTIEREN','PK2_MODELLIEREN']),
goal('multiplex','Ein Modell optischen Multiplexings entwickeln','Develop an Optical Multiplexing Model',
'Die lernende Person kann mithilfe vorgegebener Quellen ein Modell zur gemeinsamen optischen Übertragung mehrerer unterscheidbarer Signalkanäle entwickeln und daran erklären, wie die Kanäle zusammengeführt und am Empfänger wieder getrennt werden.',
'The learner can use supplied sources to develop a model for transmitting several distinguishable signal channels together optically and explain how the channels are combined and separated again at the receiver.',
[ids.spectrum],['DE-BY'],'Elektromagnetische Wellen',['PK2_MODELLIEREN','PK4_KOMMUNIZIEREN']),
goal('switch','Die Schaltfunktion eines bipolaren Transistors erklären','Explain the Switching Function of a Bipolar Transistor',
'Die lernende Person kann an einem vorgegebenen npn- oder pnp-Transistoraufbau die Funktion von Basis, Kollektor und Emitter qualitativ erklären und daraus das Ein- und Ausschalten eines Laststromkreises durch die Ansteuerung der Basis begründen.',
'The learner can qualitatively explain the roles of base, collector and emitter in a supplied npn or pnp transistor setup and use them to justify how driving the base switches a load circuit on and off.',
[ids.diode],['DE-BY','DE-HE','DE-RP'],'Festkörperphysik',['PK2_MODELLIEREN']),
goal('flipflop','Eine bistabile Transistor-Flipflop-Schaltung deuten','Interpret a Bistable Transistor Flip-Flop',
'Die lernende Person kann an einer vorgegebenen bistabilen Transistorschaltung erklären, wie gegenseitige Rückkopplung zwei stabile Zustände ermöglicht, und anhand der Schaltung vorhersagen, wie ein geeigneter Schaltimpuls den gespeicherten Zustand ändert.',
'The learner can use a supplied bistable transistor circuit to explain how mutual feedback permits two stable states and predict from the circuit how an appropriate switching pulse changes the stored state.',
[ids.switch],['DE-HE'],'Festkörperphysik',['PK2_MODELLIEREN']),
goal('elements','Argumentationen zur Entstehung schwerer Elemente beurteilen','Evaluate Arguments about the Formation of Heavy Elements',
'Die lernende Person kann anhand vorgegebener Sachtexte und Diagramme zum kosmischen Materiekreislauf beurteilen, ob eine Argumentation zur Entstehung schwerer Elemente durch die dargestellten Kernprozesse und die Weitergabe angereicherter Materie begründet ist.',
'The learner can use supplied texts and diagrams of the cosmic matter cycle to judge whether an argument about the formation of heavy elements is supported by the nuclear processes shown and the transfer of enriched matter.',
[ids.lifecycle],['DE-BY'],'Astrophysik',['PK4_KOMMUNIZIEREN','PK5_BEWERTEN'],'AB3'),
goal('endstage','Stern-Endstadien aus Anfangsmasse und Massenverlust prognostizieren','Predict Stellar End States from Initial Mass and Mass Loss',
'Die lernende Person kann mithilfe vorgegebener Entwicklungsmodelle aus Anfangsmasse und Massenverlust eines Sterns ein mögliches Endstadium begründet prognostizieren und dabei zwischen Anfangsmasse, verbleibender Kernmasse und den Grenzen der Modellvorhersage unterscheiden.',
'The learner can use supplied evolution models to make a reasoned prediction of a possible stellar end state from initial mass and mass loss, distinguishing initial mass, remaining core mass and the limits of the model prediction.',
[ids.lifecycle],['DE-BY'],'Astrophysik',['PK2_MODELLIEREN'],'AB3')]
export const clusters=[
{id:ids.optical,title:'Optische Audioübertragung und Multiplexing',titleEn:'Optical Audio Transmission and Multiplexing',description:'Dieser fachliche Cluster bündelt das funktionale Umsetzen eines Audio-Licht-Übertragungsversuchs und das Entwickeln eines Modells optischen Multiplexings.',descriptionEn:'This subject cluster groups implementing an audio-over-light experiment and developing an optical multiplexing model.',contains:[ids.audio,ids.multiplex]},
{id:ids.nuclear,title:'Kernreaktionen: Prozesse, Energie und Sicherheit',titleEn:'Nuclear Reactions: Processes, Energy and Safety',description:'Dieser fachliche Cluster bündelt den qualitativen Vergleich von Kernspaltung und Kernfusion, die Erklärung der Energiefreisetzung aus Ruhemassendifferenzen sowie die Beurteilung von Strahlungsrisiken und die begründete Bewertung von Kernenergieoptionen.',descriptionEn:'This subject cluster groups qualitative comparison of nuclear fission and fusion, explanation of energy release from rest-mass differences, assessment of radiation risks and reasoned evaluation of nuclear-energy options.',contains:[ids.comparison,ids.energy,ids.risk,ids.evaluation]},
{id:ids.stars,title:'Materiekreislauf, Elemententstehung und Stern-Endstadien',titleEn:'Matter Cycle, Element Formation and Stellar End States',description:'Dieser fachliche Cluster bündelt die materialgestützte Beurteilung von Argumentationen zur Entstehung schwerer Elemente im kosmischen Materiekreislauf und die Prognose von Stern-Endstadien anhand von Anfangsmasse und Massenverlust.',descriptionEn:'This subject cluster groups evidence-based evaluation of arguments about heavy-element formation in the cosmic matter cycle and prediction of stellar end states using initial mass and mass loss.',contains:[ids.elements,ids.endstage]},
{id:ids.transistor,title:'Bipolartransistor: Schalter, Verstärker und Flipflop',titleEn:'Bipolar Transistor: Switch, Amplifier and Flip-Flop',description:'Dieser fachliche Cluster bündelt die qualitative Grund- und Schaltfunktion eines bipolaren Transistors, die Analyse von Verstärkerschaltungen und die Deutung einer bistabilen Flipflop-Schaltung.',descriptionEn:'This subject cluster groups the qualitative basic and switching functions of a bipolar transistor, analysis of amplifier circuits and interpretation of a bistable flip-flop circuit.',contains:[ids.switch,ids.amplifier,ids.flipflop]}]
export const amplifierAfter={description:'Die lernende Person kann an einer vorgegebenen oder selbst aufgebauten bipolaren Verstärkerschaltung mithilfe von Kennlinien und Arbeitspunkt erklären, wie ein kleines Eingangssignal ein größeres Ausgangssignal steuert und welche Grenzen für eine unverzerrte Verstärkung gelten.',descriptionEn:'The learner can use characteristic curves and the operating point of a supplied or self-built bipolar amplifier circuit to explain how a small input signal controls a larger output signal and the limits of undistorted amplification.',requires:[ids.switch]}
export const mappingChanges=[]
const mc=(file,source,old,next,reason)=>mappingChanges.push({file,source,old,next,reason})
mc('by','6a715839-21e8-5af3-8c56-015f1b09423a',ids.optical,[ids.audio,ids.multiplex],'Ph13 EA5.2 has two independent products: the specified audio-light experiment and a source-assisted multiplex model. Partial component mappings; five selected student experiments, others demonstration, not seven universal build obligations.')
for(const s of ['a4461a25-8e68-5f80-ab23-0c3f61af59db','70a98347-c765-5555-bf07-4272c78e7a22'])mc('by',s,ids.transistor,[ids.switch],'Ph10.5 transistor properties and specified application circuits support the basic switching interpretation only. No blanket amplifier or bistable flipflop coverage.')
mc('he','he-phys-sekii-q4-5-b04-a01-d50394f8',ids.transistor,[ids.switch],'Q4.5 basic-course heading diode/transistor supports the qualitative transistor component, not all advanced circuit products.')
mc('he','he-phys-sekii-q4-5-b07-a01-9e9d4c4b',ids.transistor,[ids.switch],'Q4.5 GK/LK bipolar transistor: pnp OR npn, animation. Partial foundational component of switching interpretation, not both device types mandatory.')
mc('he','he-phys-sekii-q4-5-b08-a01-13ce719e',ids.transistor,[ids.switch,ids.flipflop],'Q4.5 GK/LK transistor switch with flipflop explicitly supports the two circuit functions; amplifier belongs to the separate LK clause.')
mc('rp','rp-phys-sek2-q-electronics-basic-circuits',ids.transistor,[ids.switch],'RP optional electronics basic circuits support the switching component. Optional topic selection remains; no mandatory full transistor cluster.')
mc('rp','rp-phys-sek2-q-electronics-transistor-switch',ids.transistor,[ids.switch],'RP optional electronics explicitly names transistor as switching element, not amplification or bistable feedback.')
mc('rp','rp-phys-sek2-q-electronics-transistor-switch',ids.amplifier,[],'Remove unsupported amplifier component: the actual RP original names the transistor as a switching element only.')
mc('by','f2d7d811-d8d0-5f7c-ab0f-91734ec337a6',ids.stars,[ids.elements,ids.endstage],'Ph13 GA-ASTRO4.4 separately asks for evaluation of heavy-element arguments using supplied material and end-state prediction using initial mass and mass loss. Neither is reduced to recalling a life cycle.')
mc('by','f2d7d811-d8d0-5f7c-ab0f-91734ec337a6',ids.nuclear,[],'The stellar source clause is not evidence for a full terrestrial nuclear-energy/safety cluster. Nuclear background is supplied or didactic, not a normative mapping fanout.')
for(const s of ['hh-physics-sekii-bp2022-4-2-143-462b367f','hh-physics-sekii-bp2022-4-2-144-6098f1da'])mc('hh',s,ids.stars,[ids.lifecycle],'HH original p.33 describes evolution and end stages of Sun and massive stars. Reuse qualitative life-cycle competence; this is not evidence for heavy-element argumentation or mass-loss forecasting. Partial mapping; the two extraction rows reflect the same narrow source aspect.')
mc('he','he-phys-sekii-q4-3-b10-a01-d1df2489',ids.nuclear,[ids.comparison],'Q4.3 reaction/fission/fusion presentation supports existing qualitative comparison. Energy calculation and risk evaluation have separate source clauses and goals.')
mc('bwLower','bw-phys-seki-3-3-4-b04-a01-74604a85',ids.nuclear,[],'BW3.3.4(4) reaction description is already mapped to 50877233. Delete redundant mixed-cluster mapping; safety evaluation is a separate clause(5).')
mc('bw','bw-phys-sekii-3-5-6-b06-a01-6bb41069',ids.nuclear,[],'BW3.5.6(6) is stellar fusion energy, already mapped to pp-chain and binding energy. Do not inherit unrelated reactor safety or energy-option evaluation.')
mc('rp','rp-phys-sek2-q-nuclear-reactions-lk',ids.nuclear,[ids.comparison],'RP reaction clause names decay, fission and fusion. Existing comparison covers fission/fusion; separate retained decay goal handles radioactivity. No blanket safety-judgment claim.')
mc('rp','rp-phys-sek2-q-technical-nuclear-energy-lk',ids.nuclear,[ids.energy],'RP technical nuclear-energy applications support the existing qualitative energy-release component, not a new duplicate or the full historic safety cluster.')
mc('rp','rp-phys-sek2-q-technical-nuclear-energy-lk',ids.evaluation,[],'The original technical-energy clause does not demand a criteria-based societal evaluation. Remove that unsupported exact-clause component; this does not deny other RP evaluation curriculum clauses.')
mc('by','1294d659-60f1-5ef4-b19a-3726cd2e09e4',ids.nuclear,[],'Ph10.4.3 energy explanation already maps to 7d78. The reactor-function aspect remains only partly covered; do not mislabel the fission/fusion comparison or safety cluster as full reactor-schematic competence.')
mc('by','1294d659-60f1-5ef4-b19a-3726cd2e09e4',ids.evaluation,[],'Ph10.4.3 does not itself ask for evaluation of energy options. Keep quantitative/qualitative energy semantics separate from later societal judgment.')
for(const s of ['410b1355-c593-5aab-bc4e-8fdcb512ef9c','7d5bed45-f84c-5230-bab2-aefd8875bacc'])mc('by',s,ids.nuclear,[],'The quantitative energy/binding clause is already represented by cde9 and Q-value goal5492. No redundant qualitative/safety cluster coverage.')
for(const s of ['d5355d5d-1db0-5a96-b769-c855fa127daf','096063c6-8853-5a36-9e20-ba7a81cd845c'])mc('by',s,ids.nuclear,[],'Ph13 nuclear-energy judgment remains at existing7e719 with source-handling goals. Reactor function is only partly represented; the historic cluster must not inflate source coverage.')
mc('by','99401ce9-6c74-56c0-acbe-dd6d92a254d9',ids.nuclear,[],'Solar-energy hypotheses/pp-chain are covered by existing4c5c7cb1. No claim for terrestrial nuclear risks or energy-option comparison.')
export const mappingAdditions=[{file:'by',source:'38126b26-5efd-5b0e-8c41-ad77111483a6',id:ids.lifecycle,reason:'Ph13 GA-ASTRO4.3 explicitly includes temporal stellar evolution using the HR diagram. Reuse the existing qualitative life-cycle atom as one partial component; quantitative HR tasks remain at f675.'}, {file:'he',source:'he-phys-sekii-q4-3-b09-a01-7fd810e7',id:ids.energy,reason:'Q4.3 mass defect and mass-energy equivalence explicitly support the qualitative energy-release explanation as a partial component. The retained binding-energy goals carry the quantitative requirements.'}]
export const originalClauseConstraints=[
{goalIds:[ids.audio,ids.multiplex],jurisdiction:'DE-BY',courseProfile:'LK',sourceProfile:'Ph13 EA5.2',delivery:'Audio setup build only when selected among five student experiments; otherwise mandatory demonstration with functional competency aspects. Multiplex model remains source-assisted.',notClaimed:['All seven listed experiments individually built','Modulation equals multiplexing','BY GK target']},
{goalIds:[ids.elements,ids.endstage],jurisdiction:'DE-BY',courseProfile:'GK',sourceProfile:'Ph13 GA-ASTRO4.4',delivery:'The selected GA astrophysics course branch, not a universal requirement of every Bavarian basic-course variant.',notClaimed:['HH p33 heavy-element argument','HH p33 mass-loss forecast','BY EA mandatory astronomy branch']},
{goalIds:[ids.switch],jurisdiction:'DE-BY',courseProfile:'both',sourceProfile:'Ph10.5.1/5.2',delivery:'SekI semiconductor application, no amplifier/flipflop fanout.'},
{goalIds:[ids.switch,ids.flipflop],jurisdiction:'DE-HE',courseProfile:'both',sourceProfile:'Q4.5 GK/LK',delivery:'pnp OR npn; interpret the specific supplied bistable circuit, no universal all-flipflop treatment.'},
{goalIds:[ids.amplifier],jurisdiction:'DE-HE',courseProfile:'LK',sourceProfile:'Q4.5 LK',delivery:'Demonstration and/or student experiment. Not a GK prerequisite or individually compulsory build.'},
{goalIds:[ids.switch],jurisdiction:'DE-RP',courseProfile:'both',sourceProfile:'Optional electronics pp38/68',delivery:'Only within chosen optional topic. No amplifier or flipflop target inherited.'},
{goalIds:[ids.lifecycle],jurisdiction:'DE-HH',courseProfile:'both',sourceProfile:'4.2 Astrophysics p33',delivery:'Describe evolution and end states; no upgrade to BY argument/forecast products.'}]
export const reviewReasons={
[ids.audio]:{atomicity:'Ein funktionales experimentelles Produkt: Signalweg und Komponenten begründen und denselben vorgegebenen Aufbau im ausgewählten Schülerexperiment realisieren. Multiplexentwurf ist ausgelagert; Auswahl-/Demonstrationsklausel bewahrt den tatsächlichen BY-Scope.',memory:'Kein zusätzlicher harter Abruf: der konkrete Schalt-/Signalplan wird vorgegeben, Komponenten werden funktional begründet und erprobt. Eine auswendig gelernte Bauteilliste ersetzt diesen Nachweis nicht.'},
[ids.multiplex]:{atomicity:'Ein Modellierungsprodukt: gemeinsame Übertragung bei erhaltener Kanalunterscheidbarkeit einschließlich Zusammenführung und Rückgewinnung. Kein Aufbau des Audiosenders und keine zusätzliche Modulationsroutine.',memory:'Quellengestützter Modellentwurf und Funktionsprüfung an zwei unabhängigen Kanälen; keine neue notwendige Formel oder isolierte Merkliste.'},
[ids.switch]:{atomicity:'Eine qualitative Funktionsdeutung am Schalterbetrieb verbindet die drei Anschlüsse mit dem gesteuerten Laststrom. Die Rolle von Basis/Kollektor/Emitter ist Teil derselben Erklärung, nicht zusätzliches Verstärker- oder Speicherziel.',memory:'An einem vorgegebenen beschrifteten Transistoraufbau werden Eingriffe und Strompfade begründet. Das ist Modellanwendung, kein neues notwendiges BCE-Abrufkärtchen.'},
[ids.flipflop]:{atomicity:'Eine bistabile Speicherfunktion: Rückkopplung begründet Zustandsstabilität und den Zustandswechsel durch einen geeigneten Impuls. Keine Verstärkerkennlinie und keine komplette Familie digitaler Bausteine.',memory:'Zustandswechsel werden aus der konkret vorgegebenen Rückkopplungsschaltung begründet; keine unverbundene Wahrheitstabellen- oder Flipflop-Typenliste memorieren.'},
[ids.elements]:{atomicity:'Ein argumentatives Urteil an bereitgestelltem Material: Die tragenden Kernprozess- und Materietransportprämissen einer Entstehungsbehauptung werden bewertet. Endstadienprognose ist ein eigener unabhängiger Nachweis.',memory:'Die Aufgabe liefert Sachtexte und Diagramme. Quellenbezug, korrekte Schlussfolgerung und Synthese-versus-Transport-Unterscheidung benötigen keine neue Auswendiglernliste aller Nukleosynthesewege.'},
[ids.endstage]:{atomicity:'Eine bedingte Modellprognose: Anfangsmasse und Massenverlust werden im vorgegebenen Entwicklungsmodell zu einem möglichen Endstadium verknüpft. Gegenüber6f ist das mehr als einen vorbekannten Lebenslauf beschreiben.',memory:'Modellabhängige Massengrenzen werden bereitgestellt und dürfen nicht als universelle Zahlenkarte memoriert werden. Die Leistung ist begründetes Zuordnen mit Unsicherheitsprüfung.'},
[ids.amplifier]:{atomicity:'Eine Verstärkeranalyse am bipolaren Transistor: Kennlinie und Arbeitspunkt erklären Signalsteuerung und Verzerrungsgrenzen. Der optionale eigene Aufbau gehört zum selben untersuchten Verstärker und wird nicht als universelle HE-Schülerexperimentpflicht ausgegeben.',memory:'Schaltung und Kennlinien sind vorgegeben; die lernende Person begründet Arbeitsbereich, Signalform und Grenzen. Eine zusätzliche Merkkarte für eine beliebige Standardschaltung ist nicht notwendig.'}}
