import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const dir=path.dirname(fileURLToPath(import.meta.url));
const sha=v=>`sha256:${createHash('sha256').update(v).digest('hex')}`;
const startedAt='2026-09-07T00:05:30.000Z';
const parameters={interface:'Codex delegated agent',agent:'mp_b039r_blind_a',exactModelIdentifier:'unknown',modelVersion:'unknown',temperature:'unknown',seed:'unknown',reviewMode:'independent blind first pass',humanReviewClaim:false,modelDiversityClaim:false};
const U=(essentialUnderstandingDe,essentialUnderstandingEn,observablePerformanceDe,observablePerformanceEn,transferExpectationDe,transferExpectationEn)=>({essentialUnderstandingDe,essentialUnderstandingEn,observablePerformanceDe,observablePerformanceEn,transferExpectationDe,transferExpectationEn});
const authored=[
{goalId:'911f3200-1dbc-59a6-90df-c883c77de39c',decision:'block',understandingEvidence:U(
'Eine geometrische Reihe modelliert die Summe gleichartig interpretierter Beiträge mit konstantem Verhältnis. Startindex, Anzahl der Beiträge und die Entscheidung zwischen endlicher Summe und Grenzwert müssen aus der Situation folgen; ein konvergierendes Zahlenmuster allein legitimiert keinen Sachkontext.',
'A geometric series models the sum of consistently interpreted contributions with a constant ratio. Starting index, number of terms and the choice between finite sum and limit must follow from context; a convergent numerical pattern alone does not validate a model.',
'In einer neuen Situation wiederholt halbierter Wegstücke von anfangs 6 m bildet die Person 6+3+1,5+... und deutet 12 m als idealisierten Grenzwert, nicht als Länge eines Einzelstücks. Im zweiten Fall summiert sie nur die ersten vier Beiträge einer anderen Situation, begründet die endliche Grenze und erklärt, weshalb der unendliche Summenwert dort nicht die tatsächlich bereits erreichte Gesamtgröße ist.',
'For newly presented repeatedly halved path segments starting at 6 m, the learner constructs 6+3+1.5+... and interprets 12 m as an idealized limiting total, not one segment’s length. In a second case they sum only the first four contributions of another context, justify the finite endpoint and explain why the infinite-series value is not the total already attained.',
'Wird der konstante Faktor durch wechselnde Faktoren ersetzt, prüft die Person die Modellpassung und verwendet die geometrische Summenformel nicht automatisch. Bei Faktor eins trennt sie eine endliche Summe von einem nicht endlichen Grenzwert.',
'When the constant ratio is replaced by varying ratios, the learner checks model suitability and does not automatically use the geometric-sum formula. With ratio one, they distinguish a finite sum from a non-finite limiting total.'),rationale:'DE: BLOCK der gebundenen Visualisierung, während der Textkern modellieren/auswerten tragfähig ist: Im tatsächlich angesehenen JPG werden zeitlich aufeinanderfolgende „Echo-Intensitäten“ 80,40,20,... ohne Einheiten oder Zeitgewichtung zu einer „Gesamtintensität“ 160 summiert. Intensität einzelner Echos ist keine über die Zeit additiv angesammelte Größe; dafür müssten etwa Energien bei klaren Dauerannahmen modelliert werden. Die Zahlenreihe ist korrekt, die behauptete Sachdeutung ungeklärt. Die bloße sourceRef-Zeile beweist keine gesonderte Quellenprüfung. EN: BLOCK of the bound visualization while the modelling/evaluation text is viable: the viewed JPG adds successive “echo intensities” 80,40,20,... into “total intensity” 160 without units or time weighting. Individual echo intensity is not an accumulated quantity over time; energy contributions would require defined duration assumptions. The numerical series is correct but the claimed contextual interpretation unresolved. A sourceRef line is not evidence of a separate source audit.'},
{goalId:'3773bd34-3631-5fd2-b9b7-dfa01adf5abd',decision:'keep',understandingEvidence:U(
'Ein Taylorpolynom an 0 stimmt mit einer hinreichend differenzierbaren Funktion dort im Funktionswert und in den Ableitungen bis zur gewählten Ordnung überein. Die Fakultäten kompensieren wiederholtes Ableiten; lokale Annäherung ist weder allgemeine Funktionsgleichheit noch automatisch globale Genauigkeit.',
'A Taylor polynomial at zero matches a sufficiently differentiable function there in value and derivatives through the chosen order. Factorials compensate for repeated differentiation; local approximation is neither general equality of functions nor automatic global accuracy.',
'Aus vorgegebenen Werten f(0)=2, f′(0)=3 und f″(0)=4 erklärt die Person, warum das quadratische Polynom 2+3x+2x² lautet, und überprüft die drei Übereinstimmungen. In einem zweiten Beispiel vergleicht sie zwei Polynome mit gleichem Wert, aber unterschiedlicher Steigung bei 0 und begründet, warum nur eines eine Taylorannäherung erster Ordnung sein kann.',
'Given f(0)=2, f′(0)=3 and f″(0)=4, the learner explains why the quadratic polynomial is 2+3x+2x² and checks all three matches. In a second example they compare two polynomials with equal value but different slopes at zero and explain why only one can be a first-order Taylor approximation.',
'Bei zusätzlicher Information über die dritte Ableitung erklärt die Person den zusätzlichen kubischen Term und die neue lokale Übereinstimmung. Sie behauptet daraus keine garantierte gute Näherung weit von 0; eine andere Entwicklungsstelle wird nicht als neue Pflichtkompetenz eingeführt.',
'When third-derivative information is added, the learner explains the additional cubic term and new local match. They do not infer guaranteed accuracy far from zero; expansion at a different centre is not introduced as a new compulsory competence.'),rationale:'DE: KEEP: Grundidee, Entwicklungsstelle 0 und fachliche Erklärung begrenzen ein klares Begriffslernziel; konkrete Exponentialnäherung ist ein eigener Nachfolger. JPG tatsächlich angesehen: korrekte kubische Koeffizienten, Ableitungsübereinstimmung und lokale Näherung. DE/EN verlangen denselben Inhalt; die Beispiele prüfen Bedeutung statt Formelabschrift. EN: KEEP: the basic idea, centre zero and explanation define a clear conceptual goal; exponential approximation is a separate successor. Viewed JPG correctly shows cubic coefficients, derivative matching and local approximation. Both languages claim the same content; demonstrations test meaning rather than copying the formula.'},
{goalId:'1b664036-3c29-5d94-9f42-97069aaa2c53',decision:'block',understandingEvidence:U(
'Für e^x sind alle Ableitungswerte an 0 gleich eins, daher T_n(x)=Summe von k=0 bis n über x^k/k!. Ein endliches Taylorpolynom ist eine Annäherung, deren Güte von Auswertungsstelle und Grad abhängt; für n größer gleich eins stimmt auch die Tangente bei 0 überein.',
'For e^x every derivative at zero equals one, so T_n(x) is the sum of x^k/k! from k=0 to n. A finite Taylor polynomial is an approximation whose quality depends on evaluation point and degree; for n at least one its tangent at zero also matches.',
'Die Person gewinnt T2=1+x+x²/2 aus den Ableitungswerten, berechnet T2(0,2)=1,22 und interpretiert eine bereitgestellte genauere Vergleichszahl als Fehlerinformation. In einem zweiten Fall berechnet sie T2(1)=2,5 und T3(1)=8/3, erklärt deren Annäherung an e und zeigt durch Ableiten, dass T1,T2,T3 bei 0 dieselbe Steigung besitzen.',
'The learner obtains T2=1+x+x²/2 from derivative values, calculates T2(0.2)=1.22 and interprets a supplied more accurate comparison value as error information. In a second case they calculate T2(1)=2.5 and T3(1)=8/3, explain the approximation to e and show by differentiation that T1,T2,T3 have the same slope at zero.',
'Für einen negativen kleinen x-Wert überprüft die Person die Vorzeichen der Terme und vergleicht erneut Polynome verschiedener Grade. Sie kann einen Graphenvorschlag zurückweisen, wenn er die lokale Tangentenübereinstimmung verletzt.',
'For a small negative x value, the learner checks term signs and again compares different polynomial degrees. They can reject a proposed graph if it violates local tangent matching.'),rationale:'DE: BLOCK: Die Textkompetenz ist präzise und atomar, aber im tatsächlich angesehenen JPG schneiden sich T1,T2,T3 und e^x bei 0 mit sichtbar verschiedenen Tangenten. Links nahe 0 liegt T3 zudem unter T1, obwohl T3−T1=x²(3+x)/6 dort positiv ist. Die korrekten Formeln und Werte bei 1 kompensieren diese falsche Kerndarstellung der Approximation nicht; Bildreparatur ist erforderlich. EN: BLOCK: the text competence is precise and atomic, but the viewed JPG makes T1,T2,T3 and e^x intersect at zero with visibly different tangents. Just left of zero T3 also lies below T1, although T3−T1=x²(3+x)/6 is positive there. Correct formulas and values at one do not repair this misleading core approximation diagram; the image needs correction.'},
{goalId:'315093d4-515a-542c-b776-d72a12763d1a',decision:'keep',understandingEvidence:U(
'Die Darstellung e=Summe 1/k! ab k=0 entsteht durch Auswerten der Taylorreihe von e^x an x=1. Die endlichen Partialsummen sind T_n(1), nicht e selbst; Entwicklungsstelle 0 und Auswertungsstelle 1 haben verschiedene Rollen.',
'The representation e=sum of 1/k! starting at k=0 comes from evaluating the Taylor series of e^x at x=1. Finite partial sums are T_n(1), not e itself; expansion centre zero and evaluation point one play different roles.',
'Die Person schreibt die Reihe einschließlich der beiden ersten Einsen auf und erklärt 0!=1 sowie den Indexbeginn. In einem zweiten Nachweis bildet sie T3(1)=1+1+1/2+1/6, unterscheidet diesen Wert von e und erklärt die Verbindung zwischen zusätzlichen Taylorpolynomtermen und verbesserten Partialsummen.',
'The learner writes the series including its first two ones and explains 0!=1 and the starting index. In a second demonstration they form T3(1)=1+1+1/2+1/6, distinguish that value from e and explain the connection between additional Taylor terms and improved partial sums.',
'Bei anders beginnender Summenschreibweise erkennt die Person einen fehlenden k=0-Term und korrigiert ihn begründet. Sie erläutert auch, warum Einsetzen von x=0 in dieselbe Taylorreihe eins und nicht e liefert.',
'For a sum written with a different starting index, the learner identifies and justifies restoring a missing k=0 term. They also explain why evaluating the same Taylor series at x=0 yields one rather than e.'),rationale:'DE: KEEP: „angeben“ ist bereits mit der fachlichen Taylor-Einordnung verbunden, daher kein reines Memorierungsziel. Die Reihe ist als konkreter Spezialwert eng abgegrenzt. JPG tatsächlich angesehen: richtige Fakultätsreihe, Partialsummen bis k=4 und klare Unterscheidung Entwicklungsstelle 0/Auswertung 1. EN: KEEP: stating the series is already coupled to its Taylor interpretation, so this is not mere memorization. The specific value provides a narrow scope. Viewed JPG has the correct factorial series, partial sums through k=4 and the centre-zero/evaluation-one distinction.'},
{goalId:'1eb7b2ce-f9b1-52dc-aa66-5543c946454b',decision:'keep',understandingEvidence:U(
'Digitale Funktionsanalyse übersetzt einen Term in Darstellung und numerische Befunde, die anhand mathematischer Eigenschaften geprüft werden müssen. Eine Nullstelle hat Funktionswert null; eine Extremstelle ist eine Stelle lokalen Größer- oder Kleinerwerdens im Vergleich zur Umgebung, nicht irgendein markierter Bildpunkt.',
'Digital function analysis translates an expression into a graph and numerical findings that must be checked against mathematical properties. A root has function value zero; an extremum location is locally higher or lower relative to neighbouring values, not merely a highlighted point.',
'Die Person gibt eine neue Funktion wie x³−3x in einem frei gewählten geeigneten Werkzeug ein, wählt ein sinnvolles Fenster und ermittelt Nullstellen sowie Extremstellen mit Angabe der Näherungsgenauigkeit. Im zweiten Beispiel überprüft sie einen numerisch gemeldeten Kandidaten durch Einsetzen und Nachbarwerte und begründet, weshalb eine im engen Fenster nicht sichtbare weitere Nullstelle trotzdem vorhanden sein kann.',
'The learner enters a new function such as x³−3x in a suitable tool of their choice, selects a useful window and determines roots and extremum locations with stated numerical precision. In a second example they check a reported candidate by substitution and neighbouring values and explain why another root can exist outside a narrow visible window.',
'Bei veränderten Achsenskalen oder verschobenem Suchintervall kontrolliert die Person mathematisch dieselben Befunde, statt Sichtbarkeit mit Existenz gleichzusetzen. Die Aufgabe bleibt digitale Analyse mit Kontrolle, nicht eine Pflicht zur vollständigen analytischen Kurvendiskussion.',
'With changed axis scales or search interval, the learner verifies the same mathematical findings rather than equating visibility with existence. The task remains digital analysis with checking, not a compulsory complete analytic curve investigation.'),rationale:'DE: KEEP: Graph, numerische Merkmale und kritische Prüfung bilden hier einen zusammenhängenden Werkzeug-Analyseprozess, nicht eine neue Bündelung sämtlicher zugehöriger Rechenverfahren. Die Funktionswert-Voraussetzungen erlauben elementare Prüfungen ohne ungeforderte Differentialrechnung. JPG angesehen: kubischer Graph mit passenden Näherungsnullstellen und richtigen Extrempunkten, danach Plausibilitätsvergleich. EN: KEEP: graphing, numerical features and critical checking form one tool-analysis workflow rather than a bundle of all underlying calculation methods. Function-value prerequisites permit elementary checks without importing calculus. Viewed JPG shows a cubic with suitable approximate roots and correct extrema, followed by plausibility comparison.'},
{goalId:'89ca5089-7122-5a82-b21f-17d0bd46a3bd',decision:'keep',understandingEvidence:U(
'Interaktive Parameteränderung untersucht eine Funktionsfamilie, während x die unabhängige Variable bleibt. Aussagekräftige Beobachtungen benötigen kontrollierte Änderungen und dokumentierte Parameterwerte, damit die Wirkung dem Parameter statt einem zufälligen Fensterwechsel zugeordnet wird.',
'Interactive parameter variation investigates a family of functions while x remains the independent variable. Meaningful observations require controlled changes and recorded parameter values so that effects can be attributed to the parameter rather than an accidental window change.',
'Die Person erzeugt in einem geeigneten digitalen Werkzeug f_a(x)=a x² und dokumentiert für a=1/2,1,2 den gleichen Scheitel und veränderte Funktionswerte bei festem x. In einem zweiten Fall verändert sie bei g_b(x)=x²+b nur b, zeichnet die Graphen in vergleichbaren Fenstern und hält die Verschiebung mit konkreten Parametern und Bezugspunkten fest.',
'The learner creates f_a(x)=a x² in a suitable digital tool and records for a=1/2,1,2 the unchanged vertex and changed values at fixed x. In a second case they vary only b in g_b(x)=x²+b, graph in comparable windows and document the shift with concrete parameter values and reference points.',
'Bei negativem a beziehungsweise a=0 dokumentiert die Person Spiegelung beziehungsweise den entarteten konstanten Fall und unterscheidet sie vom bloßen Herauszoomen. Sie kann die Untersuchung in einem anders gestalteten Werkzeug nachvollziehbar wiederholen.',
'For negative a and for a=0, the learner records reflection and the degenerate constant case respectively and distinguishes these from simply zooming out. They can repeat the investigation transparently in a differently designed tool.'),rationale:'DE: KEEP: Trotz „bedienen“ ist die Bedienung zielgerichtet an Parameteruntersuchung und dokumentierte Beobachtungen gebunden. Das AB1-Ziel fordert keine allgemeine Parameterbeweisroutine und bleibt werkzeugneutral. JPG tatsächlich angesehen: y=a x², Schieberegler, Breitenvergleich und Ergebnistabelle; ein reales eigenes Untersuchungsprotokoll muss die vorgeführte Tabelle ersetzen. EN: KEEP: despite “operate”, operation is purposefully tied to parameter investigation and documented observations. This introductory goal does not demand a general parameter proof and remains tool-neutral. Viewed JPG shows y=a x², a slider, width comparison and a results table; independent evidence must replace that displayed table with the learner’s own investigation.'},
{goalId:'df5eeadd-414e-50ae-84ec-7e5dbf7449d6',decision:'block',understandingEvidence:U(
'Numerische Ergebnisse sind näherungsweise Antworten auf präzise mathematische Fragen. Suchbereich, Genauigkeit und gewählte Größe bestimmen ihre Aussage; analytische Beziehungen ermöglichen unabhängige Kontrolle, ohne jedes numerische Problem geschlossen lösen zu müssen.',
'Numerical results are approximate answers to precise mathematical questions. Search domain, precision and the quantity selected determine their meaning; analytic relationships enable independent checks without requiring closed-form solutions to every numerical problem.',
'Die Person bestimmt digital die Nullstellen einer neuen quadratischen Funktion und kontrolliert durch exakte Rechnung und Einsetzen, ob beide Lösungen im gewählten Bereich erfasst wurden. In einer zweiten Aufgabe berechnet sie numerisch ein bestimmtes Integral einer einfachen Funktion und vergleicht mit einer begründeten geometrischen oder analytischen Bestimmung, einschließlich Vorzeichen und Genauigkeit; alternative Aufgaben können dieselbe Kontrollkompetenz an Extremstellen prüfen.',
'The learner digitally determines roots of a new quadratic and checks by exact calculation and substitution whether both solutions in the selected domain were found. In a second task they numerically evaluate a definite integral of a simple function and compare with a justified geometric or analytic result, including sign and precision; alternative tasks can test the same checking competence through extrema.',
'Wird das Suchintervall eingeschränkt oder die Genauigkeit grober eingestellt, erklärt die Person geänderte oder fehlende Ausgaben anhand dieser Bedingungen. Bei einer gerundeten Nullstelle erwartet sie nur einen entsprechend kleinen Residualwert, nicht exakte symbolische Gleichheit.',
'If the search interval is restricted or accuracy reduced, the learner explains changed or missing output through those conditions. For a rounded root they expect a correspondingly small residual, not exact symbolic equality.'),rationale:'DE: BLOCK des aktiven JPG: Im Nullstellenpaneel steht f(x)=3x²−7, aber die Parabel hat ihren Scheitel rechts der y-Achse und beide sichtbaren Achsenschnitte rechts davon; das widerspricht Achsensymmetrie und den angegebenen Lösungen ±sqrt(7/3). Im Integralbild zu x+1 liegt der Punkt bei x=2 nahe y=2 statt y=3. Die Zahlenkontrollen sind weitgehend richtig, doch ein Ziel kritischer Werkzeugprüfung darf diese Graphwidersprüche nicht verdecken. Der Text selbst beschreibt eine gemeinsame Kontrollkompetenz mit alternativen Fällen, keinen automatischen Split. EN: BLOCK of the active JPG: the root panel states f(x)=3x²−7 but places the vertex right of the y-axis and both visible roots to its right, contradicting symmetry and the stated ±sqrt(7/3) solutions. The x+1 integral plot is near y=2 at x=2 rather than y=3. Numerical checks are largely correct, but a critical-tool-checking goal cannot conceal these graph contradictions. The text describes one checking competence across alternative cases, not an automatic split.'},
{goalId:'94d63ad9-ae1c-5ff2-b05e-188a0f5ebec6',decision:'keep',understandingEvidence:U(
'Eine Flächennäherung addiert Teilbeiträge aus Breite mal repräsentativer Höhe. Ober- und Untersummen begrenzen bei nichtnegativer Randfunktion den Flächeninhalt; ihre Differenz liefert eine überprüfbare Genauigkeitsaussage. Linker Rand bedeutet nur bei passenden Monotonieverhältnissen Untersumme.',
'Area approximation adds contributions formed from width times representative height. For a nonnegative boundary function, upper and lower sums bound area; their difference supplies a checkable accuracy statement. A left endpoint gives a lower sum only under suitable monotonicity.',
'Für einen neuen steigenden nichtnegativen Graphen auf einem vorgegebenen Intervall bildet die Person obere und untere Rechtecksummen, schreibt die Faktoren und Summen auf und gibt eine Einschließung an. In einem zweiten Fall verfeinert sie die Zerlegung und vergleicht mit einer Trapeznäherung, erklärt die neue Bandbreite und behauptet nicht ohne Begründung, jede Näherungsart liege automatisch über oder unter dem echten Wert.',
'For a new increasing nonnegative graph on a specified interval, the learner constructs upper and lower rectangle sums, writes factors and sums and states a bound. In a second case they refine the partition and compare with a trapezoidal approximation, explain the new uncertainty interval and do not assert without justification that every method lies above or below the true value.',
'Bei einem fallenden Graphen vertauscht die Person die Rolle linker und rechter Randwerte; bei nicht gleich breiten Teilintervallen verwendet sie jeweils die tatsächliche Breite. Genauigkeit wird durch sachliche Einschließung statt bloße zusätzliche Dezimalstellen begründet.',
'For a decreasing graph, the learner reverses the roles of left and right endpoints; with unequal subinterval widths they use each actual width. Accuracy is supported by meaningful bounds rather than simply adding decimal places.'),rationale:'DE: KEEP: Näherung, Summenschreibweise und Genauigkeit sind Bestandteile derselben Flächenapproximationskompetenz; Grenzwertdefinition und Hauptsatz bleiben Nachfolger. JPG angesehen: f=x+1, korrekte vier Rechtecke je Summe, 10≤A≤14 und exakter Wert 12. Die Randwertregel ist auf das gezeigte steigende Beispiel beschränkt. EN: KEEP: approximation, sum notation and accuracy belong to one area-approximation competence; limits and the fundamental theorem remain successors. Viewed JPG correctly shows f=x+1, four rectangles in each sum, 10≤A≤14 and exact value 12. Endpoint rules are understood within the increasing example shown.'},
{goalId:'3862890e-9ea9-4c62-bcf2-e354c9d8f306',decision:'revise',proposedDescriptionDe:'Die lernende Person kann das bestimmte Integral als gemeinsamen Grenzwert von Ober- und Untersummen deuten und bei einer Änderungsrate als Bestandsänderung beschreiben, aus der zusammen mit dem Anfangsbestand der Endbestand entsteht.',proposedDescriptionEn:'The learner can interpret the definite integral as the common limit of upper and lower sums and, for a rate of change, describe it as the change in a quantity, which combines with the initial value to give the final value.',understandingEvidence:U(
'Der gemeinsame Grenzwert geeigneter Ober- und Untersummen definiert den Integralwert. Ist der Integrand eine Änderungsrate, beschreibt der Integralwert die Nettoänderung; der absolute Endbestand benötigt zusätzlich den Anfangsbestand.',
'The common limit of suitable upper and lower sums defines the integral value. If the integrand is a rate, that value describes net change; the absolute final quantity additionally requires the initial value.',
'Die Person erläutert an einer neu vorgelegten Verfeinerungstabelle, wie obere und untere Summen denselben Wert einschließen, und unterscheidet endliche Näherungen vom Grenzwert. Im zweiten Beispiel deutet sie ein Integral von +6 Litern über eine Nettozuflussrate und berechnet bei Anfangsbestand 9 Litern den Endbestand 15 Liter; sie nennt die Multiplikation der Einheiten Liter/Minute mit Minute.',
'Using a new refinement table, the learner explains how upper and lower sums enclose the same value and distinguishes finite approximations from the limit. In a second example they interpret an integral of +6 litres of net inflow and obtain a final amount of 15 litres from an initial 9 litres, explaining litre/minute multiplied by minute.',
'Bei einem negativen Integral und verändertem Anfangsbestand erklärt die Person dieselbe Nettoabnahme, aber einen anderen Endbestand. Die Grenzwertidee bleibt dieselbe; ein negativer orientierter Beitrag wird nicht in einen positiven Flächenbetrag umgedeutet.',
'For a negative integral and changed initial value, the learner explains the same net decrease but a different final quantity. The limit concept remains unchanged; a negative signed contribution is not replaced by a positive area magnitude.'),rationale:'DE: REVISE: „Integral ... als rekonstruierten Bestand“ verschleiert die notwendige Anfangsbedingung und lässt Integralwert und Endbestand zusammenfallen. Die lokale Präzisierung erhält beide Deutungen eines Integralbegriffs und führt keine neue Rechenmethode ein. JPG tatsächlich angesehen: Grenzwert 12, Anfang 7, Endbestand 19 und ausdrücklich „Integral=Zuwachs“; die neue Formulierung beseitigt den Konflikt mit dieser korrekten Aussage. EN: REVISE: interpreting the integral itself as a reconstructed quantity obscures the initial condition and conflates integral value with final quantity. The local clarification retains two interpretations of one integral concept without adding a method. Viewed JPG shows limit 12, initial 7, final 19 and explicitly “integral=increment”; the replacement resolves the conflict with that correct statement.'},
{goalId:'ece68088-71a8-466b-874c-09e6baac19fc',decision:'block',understandingEvidence:U(
'Bestandsrekonstruktion verknüpft B(t)=B(t0)+Integral der Änderungsrate. Änderungsrate, deren akkumulierte Änderung und Bestandswert sind verschiedene Größen mit verschiedenen Einheiten; eine Fläche unter dem Bestandsgraphen ist nicht diese Bestandsänderung.',
'Quantity reconstruction uses B(t)=B(t0)+the integral of its rate. Rate, accumulated change and quantity value are distinct quantities with different units; area under the quantity graph is not its change.',
'Für eine neu vorgegebene Nettozuflussrate r(t)=2t Liter/Minute und B(0)=4 Liter bestimmt die Person B(3)=13 Liter, zeichnet die passende Fläche unter r und erklärt Anfang plus Änderung. In einem zweiten innermathematischen Beispiel rekonstruiert sie aus F′(x)=2x und F(1)=5 die Funktion F(x)=x²+4 und kontrolliert sowohl Ableitung als auch Anfangswert.',
'For a newly supplied net inflow r(t)=2t litres/minute and B(0)=4 litres, the learner obtains B(3)=13 litres, marks the appropriate area under r and explains initial amount plus change. In a second mathematical example they reconstruct F(x)=x²+4 from F′(x)=2x and F(1)=5, checking both derivative and initial value.',
'Bei einer Rate, die zeitweise negativ wird, lässt die Person den Bestand entsprechend fallen und prüft Kontextgrenzen wie einen leeren Behälter. Eine verschobene Anfangszeit führt zur passend geänderten unteren Integralgrenze.',
'For a rate that becomes temporarily negative, the learner lets the quantity decrease accordingly and checks contextual constraints such as an empty container. A shifted initial time leads to the corresponding new lower integration bound.'),rationale:'DE: BLOCK trotz korrektem Text und korrekter Rechnung im JPG: Die tatsächlich angesehene rechte Grafik zeichnet B(t)=5+t³ gegen Zeit, schattiert die Fläche zwischen B und 5 und nennt sie „Integralfläche=Zuwachs=8 Liter“. Diese Fläche hat die Einheit Liter·Minute und beträgt von 0 bis 2 nur 4 Liter·Minute; 8 Liter ist die vertikale Bestandsdifferenz bzw. Fläche unter r. Texttausch kann den zentralen Darstellungsfehler nicht beheben. EN: BLOCK despite correct text and arithmetic in the JPG: the viewed right-hand plot graphs B(t)=5+t³ against time, shades between B and 5 and calls it “integral area=increment=8 litres”. That area has units litre-minutes and equals 4 litre-minutes from 0 to 2; 8 litres is the vertical quantity difference or area under r. A wording change cannot fix this central representation error.'},
{goalId:'90662398-a0fd-45bf-9ce9-2abbc20428ed',decision:'keep',understandingEvidence:U(
'Der Hauptsatz verbindet lokale Steigung und akkumulierten orientierten Flächenzuwachs. Bei stetigem f hat A(x)=Integral von a bis x über f die Ableitung f; für eine Stammfunktion F gilt A(x)=F(x)−F(a), nicht allgemein A=F ohne Konstante.',
'The fundamental theorem connects local slope and accumulated signed area. For continuous f, A(x)=the integral of f from a to x has derivative f; for an antiderivative F, A(x)=F(x)−F(a), not generally A=F without a constant.',
'Die Person erläutert mit einem selbst gezeichneten schmalen Flächenstreifen, warum Delta A ungefähr f(x) Delta x und damit die momentane Steigung A′(x)=f(x) ist. In einem zweiten Beispiel ordnet sie F=x³/3+C, f=x² und f′=2x den Rollen Stammfunktion, Funktion und Ableitungsfunktion zu und verbindet die passende geometrische Flächendifferenz mit F(b)−F(a).',
'With their own narrow-strip sketch, the learner explains why Delta A is approximately f(x) Delta x, yielding instantaneous slope A′(x)=f(x). In a second example they assign F=x³/3+C, f=x² and f′=2x to antiderivative, function and derivative and connect the corresponding geometric area difference to F(b)−F(a).',
'Wird die untere Grenze von 0 auf 1 verschoben, erklärt die Person eine vertikale Verschiebung der Integralfunktion bei unveränderter Ableitung. Sie kann dieselbe inverse Beziehung bei negativen Funktionswerten mit orientiertem Flächenzuwachs beschreiben.',
'When the lower bound moves from zero to one, the learner explains a vertical shift of the integral function with unchanged derivative. They describe the same inverse relationship for negative function values using signed area increments.'),rationale:'DE: KEEP: Geometrische Hauptsatzbegründung und die Rollen von F,f,f′ sind ein zusammenhängendes Umkehrungsverständnis; wechselseitige Graphenarbeit und Methodenauswahl sind getrennte Nachfolger. JPG tatsächlich angesehen: x²→2x→Integral von 0, Wert 9 und A′=f. Die dortige Gleichheit A=F gilt im gewählten Beispiel mit F(0)=0; der unabhängige Nachweis muss die Konstante sichtbar machen. EN: KEEP: geometric justification and the roles F,f,f′ form one inverse-operation understanding; graph inference and method selection are separate successors. Viewed JPG shows x² to 2x to integration from zero, value 9 and A′=f. Its A=F equality holds for the selected F(0)=0 example; independent evidence must expose the constant.'},
{goalId:'24f21c0c-b506-56ec-ad17-39b209af4585',decision:'keep',understandingEvidence:U(
'Eine Integralfunktion F_a(x)=Integral von a bis x über f(t) ordnet jeder veränderlichen oberen Grenze einen akkumulierten orientierten Flächenwert zu. a bleibt fest, t ist Integrationsvariable, x Funktionsargument und F_a(a)=0; dies unterscheidet die Funktion von einem einzelnen bestimmten Integral.',
'An integral function F_a(x)=the integral of f(t) from a to x assigns accumulated signed area to each variable upper bound. The lower bound a is fixed, t is the integration variable, x the function argument and F_a(a)=0; this distinguishes the function from one definite integral.',
'Die Person definiert für einen neu vorgelegten Graphen eine Integralfunktion mit vorgegebener Startstelle, markiert die zu F_a(x1) gehörende orientierte Fläche und erklärt alle Variablen. Im zweiten Beispiel f(t)=2 und a=1 gewinnt sie aus Rechtecksflächen F_1(x)=2(x−1), prüft F_1(1)=0 und erläutert auch Werte links von 1.',
'For a newly supplied graph, the learner defines an integral function with a specified starting point, marks the signed area corresponding to F_a(x1) and explains every variable. For a second example f(t)=2 and a=1, rectangle areas give F_1(x)=2(x−1); they verify F_1(1)=0 and explain values left of one.',
'Bei gleicher Randfunktion, aber anderer unterer Grenze, erklärt die Person die veränderten Funktionswerte als konstanten Flächenversatz. Bei einem Vorzeichenwechsel des Integranden beschreibt sie Zu- und Abnahme der akkumulierten Größe, nicht bloß immer größere geometrische Fläche.',
'For the same integrand with a different lower bound, the learner explains changed function values as a constant accumulated-area offset. When the integrand changes sign, they describe increase and decrease of the accumulated quantity rather than ever-growing unsigned area.'),rationale:'DE: KEEP: Definition und geometrische Bedeutung desselben Objekts sind klar verknüpft; der Nachfolger übernimmt die weitergehende wechselseitige Graphendeutung. JPG tatsächlich angesehen: feste Untergrenze a, variable Obergrenze x, Beispiel f=2t und F0=x² mit passenden Punkten. Die Flächenworte sind im gezeigten positiven Bereich richtig; außerhalb wird orientiert gedeutet. EN: KEEP: definition and geometric meaning of the same object are explicitly connected; more extensive mutual graph inference belongs to the successor. Viewed JPG shows fixed a, variable x, f=2t and F0=x² with matching points. Area wording is correct in the positive range shown and is interpreted as signed accumulation outside it.'},
{goalId:'5042fd2b-bab2-50be-8144-c9ccf5618615',decision:'block',understandingEvidence:U(
'Wechselseitige Graphendeutung beruht auf F′=f: Vorzeichen von f bestimmen Monotonie von F, Werte von f dessen Steigung, und Änderungen von f die Krümmung. Für die Lage von F ist zusätzlich ein Start- oder Flächenwert nötig; eine Nullstelle von f muss kein Extremum von F sein.',
'Mutual graph interpretation rests on F′=f: signs of f determine monotonicity of F, values of f give its slopes, and changes in f give curvature. Locating F additionally requires a starting or area value; a zero of f need not be an extremum of F.',
'Aus einem neu vorgelegten stetigen f-Graphen mit positivem und negativem Abschnitt skizziert die Person F für vorgegebenes F(a)=0 und begründet Steigung, Extremstellen und mindestens einen Flächenwert. In einem zweiten Fall rekonstruiert sie aus dem Graphen von F qualitativ f durch Tangentensteigungen und unterscheidet waagerechte Tangente mit und ohne Vorzeichenwechsel.',
'From a new continuous graph f with positive and negative sections, the learner sketches F for specified F(a)=0 and explains slope, extrema and at least one area value. In a second case they qualitatively reconstruct f from the graph of F through tangent slopes and distinguish horizontal tangents with and without a sign change.',
'Bei vertikaler Verschiebung von F bleibt der rekonstruierte Integrand gleich. Bei einer positiven, aber fallenden f-Passage zeichnet die Person F steigend und zugleich mit abnehmender Steigung statt fallend.',
'A vertical shift of F leaves the reconstructed integrand unchanged. Where f is positive but decreasing, the learner draws F increasing with decreasing slope rather than decreasing.'),rationale:'DE: BLOCK: Das tatsächlich angesehene JPG ist im Kern F′=f nicht konsistent. Ganz rechts wird der rote Integrand nach seinem zweiten Achsenschnitt positiv, während die blaue Integralfunktion weiter fällt; links steigt f zunächst, aber die blaue Kurve verliert schon Steigung statt zunächst steiler zu werden. Die Beschriftungsregeln sind richtig, die dazugehörigen Kurven widersprechen ihnen. Ein Textwechsel behebt keine widersprüchliche wechselseitige Graphendarstellung. EN: BLOCK: the viewed JPG is inconsistent with its core F′=f relationship. At the far right the red integrand becomes positive after its second zero while the blue integral function continues decreasing; on the left f initially increases while the blue curve already loses slope. The written rules are correct but the curves contradict them. Wording alone cannot repair a contradictory mutual graph representation.'},
{goalId:'269675a9-13cd-4a3a-ab75-63794f5c9710',decision:'block',understandingEvidence:U(
'Produktsummen addieren Teilwirkungen aus Rate mal Zeitdauer beziehungsweise Dichte mal Ausdehnung. Orientierte Beiträge haben ein sachlich bedeutendes Vorzeichen; ihre Summe beschreibt die Nettowirkung, nicht die Summe aller positiven Beträge.',
'Product sums add partial effects such as rate times duration or density times extent. Signed contributions have a contextually meaningful sign; their sum gives net effect rather than the sum of absolute amounts.',
'Zu einem neuen Nettozuflussdiagramm erklärt die Person, warum 2 Minuten mit +4 L/min und 3 Minuten mit −1 L/min insgesamt +5 Liter ergeben, und markiert die zugehörigen orientierten Rechtecke. In einem zweiten Fall deutet sie gleich große positive und negative Geschwindigkeitsbeiträge als null Ortsänderung, obwohl Bewegung und zurückgelegte Weglänge nicht null sind.',
'For a new net-inflow graph, the learner explains why 2 minutes at +4 L/min and 3 minutes at −1 L/min give +5 litres overall, marking the corresponding signed rectangles. In a second case they interpret equal positive and negative velocity contributions as zero displacement despite nonzero motion and distance travelled.',
'Wird nur die Dauer eines negativen Abschnitts verlängert, sagt die Person die geänderte Nettowirkung samt Einheit voraus und unterscheidet sie vom Endbestand, solange ein Anfangsbestand fehlt. Eine neue Vorzeichenkonvention wird konsistent auf alle Beiträge angewandt.',
'If only a negative interval’s duration increases, the learner predicts the changed net effect with units and distinguishes it from final quantity when no initial value is given. A new sign convention is applied consistently to every contribution.'),rationale:'DE: BLOCK des JPG: Der negative Abschnitt ist tatsächlich bis zur Achsenmarke −2 gezeichnet, aber mit Höhe −1 L/min, Teilwirkung −3 Liter und Summe +5 Liter beschriftet. Von t=2 bis 5 würde der gezeichnete Wert −2 eine Wirkung −6 Liter und damit Gesamtwirkung +2 Liter ergeben. Gerade die geforderte Verbindung von Höhe, Breite und Gesamtwirkung wird widersprüchlich vermittelt. Textkern und DE/EN sind sonst klar; reine Wordingkorrektur reicht nicht. EN: BLOCK of the JPG: its negative interval is drawn down to the −2 tick but labelled height −1 L/min, contribution −3 litres and total +5 litres. From t=2 to 5 the plotted −2 would contribute −6 litres and yield total +2 litres. This contradicts the very height-width-total relationship being taught. The text and bilingual parity are otherwise clear; wording alone is insufficient.'},
{goalId:'9441bb35-2a2f-4edc-9d8a-bc58c257054d',decision:'revise',proposedDescriptionDe:'Die lernende Person kann zu einer gegebenen Randfunktion und einer festen unteren Grenze den Graphen der zugehörigen orientierten Flächeninhaltsfunktion qualitativ skizzieren und dessen Verlauf aus den Flächenbeiträgen begründen.',proposedDescriptionEn:'The learner can qualitatively sketch the signed area-accumulation function for a given boundary function and fixed lower bound and justify its shape from the accumulated area contributions.',understandingEvidence:U(
'Die orientierte Flächeninhaltsfunktion sammelt mit f gewichtete Beiträge ab einer festen Startstelle. Sie beginnt dort bei null und steigt oder fällt entsprechend dem Vorzeichen der Randfunktion; die geometrische Gesamtfläche ohne Vorzeichen wäre bei negativen Abschnitten eine andere Funktion.',
'The signed area-accumulation function sums contributions weighted by f from a fixed starting point. It starts at zero there and increases or decreases according to f’s sign; total unsigned geometric area would be a different function on negative sections.',
'Zu einer neu gegebenen stückweise konstanten Randfunktion mit positiven und negativen Abschnitten skizziert die Person die stetige, stückweise lineare Flächenfunktion und beschriftet mindestens zwei aus Rechtecken berechnete Werte. In einem zweiten Beispiel einer positiven steigenden Randfunktion erklärt sie qualitativ, warum die Flächenfunktion steigt und dabei steiler wird, ohne eine Stammfunktion als einzigen Lösungsweg zu benötigen.',
'For a newly supplied piecewise constant boundary function with positive and negative sections, the learner sketches the continuous piecewise linear accumulation function and labels at least two values calculated from rectangles. For a second example with positive increasing boundary function, they explain why accumulation increases and becomes steeper without requiring an antiderivative as the sole solution method.',
'Bei veränderter Startstelle legt die Person den neuen Nullwert fest und beschreibt den konstanten Versatz. Wird ein positiver Abschnitt durch einen gleich großen negativen ersetzt, begründet sie den nun fallenden Verlauf statt die Fläche weiterhin positiv aufzusummieren.',
'With a changed starting point, the learner sets the new zero and explains the constant offset. If a positive section is replaced by an equal negative one, they explain the now-decreasing curve instead of continuing to add unsigned area.'),rationale:'DE: REVISE: Ohne feste Startgrenze und ohne Orientierung ist „zugehörige Flächeninhaltsfunktion“ bei negativen Randwerten mehrdeutig. Das tatsächlich angesehene JPG bindet A(x)=Integral von 0 bis x und zeigt korrektes Fallen bei negativer Randfunktion mit Werten 4,2,3. Die lokale Klärung übernimmt diese vorhandene Konvention, nicht die andere Kompetenz einer beliebigen wechselseitigen Graphenrekonstruktion. EN: REVISE: without a fixed starting bound and sign convention, “associated area function” is ambiguous for negative boundary values. The viewed JPG explicitly defines accumulation from zero and correctly decreases over the negative interval, with values 4,2,3. The local clarification preserves this supplied convention without importing arbitrary two-way graph reconstruction.'},
{goalId:'b559e2ea-60ef-4b3f-a37c-669b867ace29',decision:'keep',understandingEvidence:U(
'Der Integralübergang behält die Bedeutung der Produktsumme bei und verfeinert die Zerlegung so, dass sich im geeigneten Fall ein bestimmter Grenzwert ergibt. Das Integral ist weder eine einzelne sehr feine Summe noch das Einsetzen der Breite null in jeden Summanden.',
'The transition to an integral preserves the product sum’s meaning while refining the partition so that a definite limit emerges in appropriate cases. An integral is neither one very fine sum nor the result of substituting zero width into every term.',
'Die Person bildet für einen neuen einfachen positiven Graphen zwei Produktsummen bei unterschiedlicher Teilbreite, erklärt die approximierten Beiträge und schreibt den zugehörigen Integralansatz mit Grenzen. In einem zweiten Fall erläutert sie an einer Folge zunehmend engerer Einschließungen, warum die Gesamtwirkung einen Grenzwert besitzen kann, obwohl jeder einzelne Teilbeitrag kleiner wird.',
'For a new simple positive graph, the learner constructs two product sums with different interval widths, explains the approximate contributions and writes the corresponding integral with bounds. In a second case they use a sequence of increasingly tight bounds to explain why a total effect can approach a limit while each individual contribution becomes smaller.',
'Bei einer Zerlegung mit anderen Stützstellen vergleicht die Person die endlichen Werte und erläutert am geeigneten stetigen Beispiel denselben Grenzwert. Sie kann einen negativen Abschnitt als orientierten Beitrag weiterführen, ohne einen formalen Epsilon-Delta-Beweis zu verlangen.',
'With different sample points, the learner compares finite sums and explains the same limiting value for a suitable continuous example. They retain a negative section as a signed contribution without requiring a formal epsilon-delta proof.'),rationale:'DE: KEEP: Erläutern und Nachvollziehen benennen dieselbe propädeutische Grenzwertkonstruktion; die vorhandenen Produktsummen-/Näherungs-Vorgänger stützen sie. JPG tatsächlich angesehen: Teilbreiten 2,1,0,5 mit Summen 8,10,11 und Grenzwert 12 für t+1. Es zeigt ein geeignetes Beispiel, keine universelle Konvergenzbehauptung für jede Funktion. EN: KEEP: explaining and tracing name the same introductory limit construction supported by product-sum and approximation prerequisites. Viewed JPG has widths 2,1,0.5, sums 8,10,11 and limit 12 for t+1. It illustrates a suitable case rather than universal convergence for every function.'},
{goalId:'a9ed219d-d497-55e5-a4e0-4d45d2554f6b',decision:'block',understandingEvidence:U(
'Stammfunktionen kehren bekannte Ableitungsbeziehungen um und sind auf einem Intervall bis auf eine Konstante bestimmt. Potenz-, Faktor- und Summenregel beschreiben die lineare Kombination solcher Grundbausteine; n=−1 ist von der angegebenen Potenzregel ausgeschlossen.',
'Antiderivatives reverse known derivative relationships and are determined up to a constant on an interval. Power, factor and sum rules combine these basic building blocks linearly; n=−1 is excluded from the stated power rule.',
'Die Person bestimmt für 3x²−2x+4 eine Stammfunktion x³−x²+4x+C und erklärt die Linearkombination durch Ableitungskontrolle. In einer zweiten Aufgabe integriert sie e^x+sin(x)−2cos(x) zu e^x−cos(x)−2sin(x)+C, kontrolliert die Vorzeichen und erklärt, weshalb verschiedene C dieselbe Ableitung liefern.',
'The learner obtains x³−x²+4x+C as an antiderivative of 3x²−2x+4 and explains the linear combination by differentiating. In a second task they integrate e^x+sin(x)−2cos(x) to e^x−cos(x)−2sin(x)+C, check signs and explain why different C values give the same derivative.',
'Für x hoch minus zwei beachtet die Person ein Intervall ohne null und findet −1/x+C; für x hoch minus eins erkennt sie die Ausnahme, ohne die nicht beanspruchte Logarithmusintegration als Pflicht hinzuzufügen. Sie unterscheidet eine Stammfunktion von einem bestimmten Integralwert.',
'For x to the power minus two, the learner uses an interval avoiding zero and obtains −1/x+C; for exponent minus one they recognize the exception without importing logarithmic integration as a requirement. They distinguish an antiderivative from a definite integral value.'),rationale:'DE: BLOCK des aktiven Bildes: Die tatsächlich angesehene Tabelle enthält richtige einzelne Stammfunktionen und die obere bestimmte Rechnung ergibt korrekt 12. Die zweite Rechenzeile schreibt jedoch das Integral ohne Grenzen und setzt es mit der Zahl 12 gleich. Damit wird ein unbestimmtes Integral mit einem bestimmten Integralwert verwechselt, genau an der begrifflichen Grenze dieses Ziels. Die Funktionsfamilien selbst sind Instanzen derselben rückwärtigen linearen Ableitungsroutine, kein notwendiger Split. EN: BLOCK of the active image: the viewed table contains correct particular antiderivatives and the upper definite integral correctly equals 12. But its second calculation line writes an integral without bounds and equates it to 12, conflating an indefinite integral with a definite value at this goal’s conceptual boundary. The function families themselves instantiate the same reverse linear differentiation routine, so no split is inherently needed.'},
{goalId:'23589682-2028-54cb-9034-b468b42688f1',decision:'keep',understandingEvidence:U(
'Eine lineare innere Funktion besitzt eine konstante Ableitung; beim rückwärtigen Anwenden der Kettenregel muss der dadurch entstehende Faktor kompensiert werden. Für nichtverschwindenden inneren Faktor wird deshalb durch ihn dividiert; Verschiebungen verändern ihn nicht.',
'A linear inner function has a constant derivative; reverse use of the chain rule must compensate for the factor it produces. Thus one divides by a nonzero inner slope, while shifts do not change that factor.',
'Die Person bestimmt zu e^(3x−2) eine Stammfunktion e^(3x−2)/3+C und begründet den Faktor durch Rückableiten. In einer zweiten Aufgabe integriert sie sin(2(x−1)) und cos(−4(x+2)), erklärt jeweils inneren Faktor und Vorzeichen und überprüft die erhaltenen Ausdrücke mit der Kettenregel.',
'The learner finds e^(3x−2)/3+C as an antiderivative of e^(3x−2), explaining the factor by differentiation. In a second task they integrate sin(2(x−1)) and cos(−4(x+2)), explain each inner slope and sign, and check the resulting expressions with the chain rule.',
'Wird der innere Faktor negativ oder null, behandelt die Person das Vorzeichen beziehungsweise die dann konstante Funktion korrekt, statt durch null zu dividieren. Eine quadratische innere Funktion wird nicht unberechtigt mit derselben konstanten Faktorregel behandelt.',
'For a negative or zero inner slope, the learner correctly handles the sign or the resulting constant function rather than dividing by zero. They do not wrongly apply the same constant-factor rule to a quadratic inner function.'),rationale:'DE: KEEP: Drei Grundfunktionen sind Variationen einer einzigen klar benannten rückwärtigen Kettenregel; die passenden Ableitungs- und Grundintegral-Vorgänger sind gebunden. Der Nullfaktor lässt sich als Randfall im Nachweis behandeln, ohne die Beschreibung mit Formelfällen zu überladen. JPG tatsächlich angesehen: drei korrekte Stammfunktionen samt C und expliziten Rückableitungen. EN: KEEP: the three base functions are variations of one explicitly named reverse chain rule, with fitting derivative and basic-integration prerequisites. The zero-slope case can be tested without burdening the description with formula cases. Viewed JPG shows three correct antiderivatives with C and explicit differentiation checks.'},
{goalId:'8675a3d8-9aaa-4f35-b4ed-383d1c93ea24',decision:'keep',understandingEvidence:U(
'Der Hauptsatz besagt für stetige Integranden, dass die Änderung einer akkumulierten orientierten Fläche durch den Randfunktionswert bestimmt ist. So verbindet er die Integralfunktion mit einer Stammfunktion und erlaubt die Auswertung als F(b)−F(a).',
'For continuous integrands, the fundamental theorem says that change in accumulated signed area is governed by the boundary function value. It connects the integral function with an antiderivative and permits evaluation as F(b)−F(a).',
'Die Person erklärt an einem eigenen schmalen Flächenstreifen einer neuen stetigen Funktion, warum die Steigung der Integralfunktion dem Integranden entspricht. In einem zweiten einfachen Integralbeispiel f(t)=2t+1 von 1 bis 3 nutzt sie eine Stammfunktion und erhält 10, deutet die Differenz geometrisch und überprüft sie als Trapezfläche.',
'For a new continuous function, the learner uses their own narrow area-strip sketch to explain why the integral function’s slope equals the integrand. In a second simple example f(t)=2t+1 from 1 to 3, they use an antiderivative to obtain 10, interpret the difference geometrically and check it as a trapezoid area.',
'Bei vertauschten Integrationsgrenzen begründet die Person das Vorzeichen; bei einer anderen Stammfunktion F+C zeigt sie denselben Integralwert. Erklärung und Anwendung müssen verbunden bleiben, nicht als bloßer Merksatz und Taschenrechnerzahl nebeneinanderstehen.',
'When bounds are reversed, the learner explains the sign; for another antiderivative F+C they show the same integral value. Explanation and application must stay connected rather than being an isolated memorized statement and calculator number.'),rationale:'DE: KEEP: Der geometrisch-anschauliche Hauptsatz und seine einfache Anwendung sind ein kohärentes Verständnisziel auf AB2; die explizit stetigkeitsbezogene LK-Begründung bleibt getrennt. JPG tatsächlich angesehen: f=t+1, A=x²/2+x, korrekte Werte A(2)=4, A(4)=12 und A′(2)=3. Das ist eine Illustration, nicht der vom Lernenden zu liefernde geometrische Grund. EN: KEEP: intuitive geometric explanation and simple application form one coherent AB2 goal; the explicitly continuity-based advanced justification remains distinct. Viewed JPG has f=t+1, A=x²/2+x, correct values A(2)=4, A(4)=12 and A′(2)=3. It illustrates the relationship rather than supplying the learner’s own geometric reasoning.'},
{goalId:'ced4f794-9b42-4be4-bde5-7d44f134a140',decision:'keep',understandingEvidence:U(
'Stetigkeit sorgt dafür, dass die Werte des Integranden auf einem schrumpfenden Intervall nahe bei f(x) liegen. Deshalb nähert sich der mittlere Flächenzuwachs pro Intervallbreite f(x), und die Integralfunktion hat dort die Ableitung f(x); hier liegt die Begründung, nicht in einer bloßen Formel.',
'Continuity ensures that integrand values on a shrinking interval lie close to f(x). Hence average area increase per interval width approaches f(x), giving the integral function derivative f(x) there; this is the justification rather than merely a formula.',
'Die Person begrenzt an einem eigenen lokalen Graphenausschnitt den schmalen Flächenzuwachs durch Rechtecke mit kleinster und größter Höhe und erklärt anschaulich, warum beide Höhen für kleineres h gegen f(x) gehen. In einem zweiten Beispiel wertet sie ein einfaches bestimmtes Integral mittels Stammfunktion aus und begründet, warum deren additive Konstante verschwindet und der Ansatz zur betrachteten stetigen Funktion passt.',
'Using their own local graph section, the learner bounds a narrow area increment by rectangles with minimum and maximum heights and intuitively explains why both heights approach f(x) as h shrinks. In a second example they evaluate a simple definite integral using an antiderivative and explain why its additive constant cancels and why the method fits the continuous function considered.',
'An einer vorgegebenen Sprungfunktion vergleicht die Person die einseitigen mittleren Flächenzuwächse und erklärt, weshalb die Stetigkeitsbegründung an der Sprungstelle nicht gilt. Sie behauptet nicht, dass deswegen das ganze Integral undefiniert sei; ein formaler Epsilon-Delta-Beweis bleibt außerhalb.',
'For a supplied step function, the learner compares one-sided average area increments and explains why the continuity argument fails at the jump. They do not claim that the entire integral is therefore undefined; a formal epsilon-delta proof remains outside scope.'),rationale:'DE: KEEP: Die Beschreibung nennt ausdrücklich das anspruchsvollere Begründungsmittel Stetigkeit und verbindet es mit derselben Hauptsatzanwendung. Das ist eine kohärente lokale Begründung, kein Sammelziel; effektive Sek-II-Seiten werden nicht allein nach dem LK-Tag umgedeutet. JPG tatsächlich angesehen: schmaler Streifen, Rechtecklupe, Delta A/h und Grenzübergang zu A′=f, dazu korrektes Beispiel A′(2)=3. EN: KEEP: the description explicitly names continuity as the stronger justification and links it to application of the same theorem. This is one coherent local argument, not a bundle; effective upper-secondary pages are not reinterpreted solely from the LK tag. Viewed JPG shows a narrow strip, rectangle magnification, Delta A/h and the limit yielding A′=f, plus correct example A′(2)=3.'}
];
const campaign=JSON.parse(fs.readFileSync(path.join(dir,'description-review-campaign.json')));
const bundle=JSON.parse(fs.readFileSync(path.join(dir,'review-bundle-manifest.json')));
const batch=campaign.batches[0];
const batchBytes=fs.readFileSync(path.join(dir,'batches',batch.batchId+'.input.jsonl'));
if(sha(batchBytes)!==batch.batchInputFingerprint)throw new Error('batch drift');
const rows=batchBytes.toString('utf8').trim().split('\n').map(JSON.parse);
const runId=campaign.campaignId+'-run';
const records=rows.map(({goal},i)=>{
 const a=authored[i];if(!a||a.goalId!==goal.goalId||goal.reviewContext.evidenceProfile!==null)throw new Error('goal/profile mismatch');
 const v=goal.reviewContext.page.visualization;
 if(!v||sha(fs.readFileSync(path.resolve('app/public','.'+v.url)))!==v.originalDigest)throw new Error('image drift');
 return {$schema:'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json',schemaVersion:1,recordId:campaign.campaignId+'-'+String(i+1).padStart(3,'0'),runId,campaignId:campaign.campaignId,roundId:campaign.roundId,bundleFingerprint:campaign.bundleFingerprint,bookDigest:campaign.bookDigest,goalId:goal.goalId,goalFingerprint:goal.goalFingerprint,pageFingerprint:goal.pageFingerprint,currentTitleDe:goal.currentTitleDe,currentTitleEn:goal.currentTitleEn,currentDescriptionDe:goal.currentDescriptionDe,currentDescriptionEn:goal.currentDescriptionEn,...a,evidenceProfileContract:'positive-understanding-evidence-v2',evidenceProfileRecommendation:'create',recordStatus:'candidate',reviewAuthority:'ai_candidate'};
});
if(records.length!==20||authored.length!==20)throw new Error('count mismatch');
const recordsText=records.map(JSON.stringify).join('\n')+'\n';
const run={$schema:'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json',schemaVersion:1,runId,campaignId:campaign.campaignId,roundId:campaign.roundId,batchId:batch.batchId,batchInputFingerprint:batch.batchInputFingerprint,bundleFingerprint:campaign.bundleFingerprint,bookDigest:campaign.bookDigest,provider:'OpenAI',model:'unknown',modelVersion:'unknown',role:'subject_reviewer',promptFamilyId:'goal-description-understanding-evidence-review-v2',promptFingerprint:campaign.promptFingerprint,criteriaFingerprint:campaign.criteriaFingerprint,generationParametersFingerprint:sha(JSON.stringify(parameters)),independenceGroupId:campaign.independenceGroupId,blindToOtherRuns:true,goalIds:batch.goalIds,inputArtifacts:[{role:'description_review_batch_input_jsonl',digest:batch.batchInputFingerprint},{role:'review_prompt',digest:campaign.promptFingerprint},{role:'review_criteria',digest:campaign.criteriaFingerprint}],startedAt,completedAt:new Date().toISOString(),status:'completed',outputDigest:sha(recordsText),toolchainVersion:'codex-native-description-review-round-a-v1'};
const files=[[batch.batchId+'.records.jsonl',recordsText],[batch.batchId+'.run.json',JSON.stringify(run,null,2)+'\n']];
const patch='*** Begin Patch\n'+files.map(([name,body])=>{const target=path.join(dir,'results',name);if(fs.existsSync(target))throw new Error('refusing overwrite '+target);return `*** Add File: ${target}\n${body.trimEnd().split('\n').map(x=>'+'+x).join('\n')}\n`;}).join('')+'*** End Patch';
console.log(JSON.stringify({patch,summary:{runId,startedAt,completedAt:run.completedAt,outputDigest:run.outputDigest,decisions:records.reduce((a,r)=>(a[r.decision]=(a[r.decision]||0)+1,a),{})}}));
