# SPDX-License-Identifier: Apache-2.0
import pathlib,json,hashlib,datetime,shutil,subprocess,importlib.util,jsonschema,re
from html.parser import HTMLParser
from referencing import Registry,Resource
R=pathlib.Path('/home/enpasos/projects/skillpilot');BASE=pathlib.Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10');P=BASE/'chemie-b008-C11-NTG-bounded-layer-a-proposal-author-20261010-v1';H=BASE/'chemie-b008-C11-NTG-course-placement-research-neutral-20261010-v1'
E=P/'neutral-C11-NTG-bounded-author-current-constraints.entry.json';F=P/'FINAL.C11-NTG-bounded-author-current-constraints.freeze.json'
assert not (R/E).exists() and not (R/F).exists()
def read(p):return json.loads((R/p).read_text())
def ref(p):p=pathlib.Path(p);b=(R/p).read_bytes();return {'path':str(p),'sha256':'sha256:'+hashlib.sha256(b).hexdigest(),'bytes':len(b)}
def put(p,x):f=R/P/p;f.parent.mkdir(parents=True,exist_ok=True);assert not f.exists();f.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');return ref(P/p)
class Text(HTMLParser):
 def __init__(self):super().__init__();self.out=[];self.skip=0
 def handle_starttag(self,t,a):
  if t in ['script','style']:self.skip+=1
 def handle_endtag(self,t):
  if t in ['script','style']:self.skip=max(0,self.skip-1)
 def handle_data(self,d):
  if not self.skip and d.strip():self.out.append(d.strip())
parser=Text();parser.feed((R/P/'primary/C11-NTG.current-official.html.snapshot.txt').read_text());text='\n'.join(parser.out);normalized=re.sub(r'\s+',' ',text)
frame=read(P/'inputs/prior-confirmed-C11-whole-source-frame.exact.json');source=frame['wholeSourceOperatorAndAllOccurrences'];operator=source['rawSourceText'];assert operator in normalized;assert 'Fachlehrplan Chemie 11 (NTG)' in normalized
begin=normalized.index('C11 Lernbereich 1');end=normalized.index('C11 Lernbereich 2',begin);area=normalized[begin:end].strip()+'\n';plain=P/'primary/C11-NTG.whole-learning-area1.normalized-extract.actual.txt';(R/plain).write_text(area)
witness=put('primary/C11.1.11-NTG11.literal-primary-and-programme.author-witness.json',{'schemaVersion':1,'role':'AUTHOR primary witness, not independent course approval','officialURL':'https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/11/chemie','currentOfficialFullPage':ref(P/'primary/C11-NTG.current-official.html.snapshot.txt'),'wholeCurrentLearningArea1':ref(plain),'actualFetchReceipt':ref(P/'primary/actual-current-official-fetch.receipt.json'),'actualHeading':'Fachlehrplan Chemie 11 (NTG)','officialSpan':'C11.1.11','sourceGoalId':source['id'],'sourcePassageId':source['passageId'],'literalSourceOperator':operator,'officialCourseLevelRetained':'unspecified','regularProgramme':'NTG','programmeYear':11,'programmePhase':'Einführungsphase','regularProgrammeTablePrimary':ref(P/'primary/GSO-Anlage1.current-official.html.snapshot.txt'),'priorWholeRegularProgrammeTableObservations':ref(P/'inputs/prior-confirmed-regular-programme-table-observations.exact.json'),'regularNTG11EvidenceIsNotAllLaterGKOrLKProgrammeEvidence':True,'sourceExtractionEdited':False,'runtimeOrUXChanges':[],'PSelected':False,'coursePlacementApproval':False})
normal=read(P/'checks/actual-normal-C11-NTG-scope-and-placement-boundary.json');positive=read(P/'terminal/normal-existing-G1-profile-diagnostic.terminal.actual.json');assert positive['actualExitCode']==0
assert read(P/'terminal/normal-C11-scope-and-placement-actual-parent-guard.terminal.actual.json')['actualExitCode']==0
prow=json.loads((R/P/'positive/historical-e5a5-one-row.DIAGNOSTIC-NOT-SELECTED.exact.jsonl').read_text());assert prow['maximumClaimScope']=='G1' and prow['evidenceLevel']=='E1' and prow['status']=='needs_human_review' and prow['reviewAuthority']=='ai_candidate'
put('checks/actual-two-driver-assertions-corrected-without-rule-change.json',{'schemaVersion':1,'failedActualTerminals':[ref(P/'terminal/normal-C11-scope-and-placement.terminal.actual.json'),ref(P/'terminal/normal-C11-scope-and-placement-corrected.terminal.actual.json')],'firstActualSource':ref(P/'technical-first-scope-envelope-assertion.actual.mts'),'firstActualError':'The driver passed the runtime envelope, including landscapeId, as a constrained scope. The normal scope matcher correctly rejects that extra dimension. Corrected driver separates landscapeId from the scope map.','secondActualSource':ref(P/'technical-second-canonical-parent-assertion.actual.mts'),'secondActualError':'The driver assumed the proposed placement would attach both goals. The actual normal placement retains explicit non-root authored parents, so neither goal is attached. The final report records this real additional limitation.','successfulActualTerminal':ref(P/'terminal/normal-C11-scope-and-placement-actual-parent-guard.terminal.actual.json'),'normalCodeOrCheckerEdited':False,'unsealedRejectedPlacementFilenameClarified':True,'scienceOrApprovalChanged':False})
scope_schema=read('contracts/curriculum-package/v1/composition-view.schema.json');bad=read(P/'rejected-projection-experiments/explicit-track-year.NOT-VALID-composition-view.json');errors=list(jsonschema.Draft202012Validator(scope_schema).iter_errors(bad));assert errors
schema_negative=put('checks/actual-closed-composition-schema-track-year-rejection.json',{'schemaVersion':1,'purpose':'Explicitly rejected AUTHOR data specimen, never a valid adoption input','schema':ref('contracts/curriculum-package/v1/composition-view.schema.json'),'specimen':ref(P/'rejected-projection-experiments/explicit-track-year.NOT-VALID-composition-view.json'),'actualErrors':[{'path':list(e.path),'message':e.message} for e in errors],'closedScopeDimensions':['schoolForm','jurisdiction','stage','courseProfile','durationModel'],'trainingDirectionAndProgrammeYearSupported':False,'checkerException':False})
constraints=put('AUTHOR.current-C11-NTG-placement-and-G1-competence.findings.json',{'schemaVersion':1,'role':'Bounded data AUTHOR proposal and actual normal diagnostic; no independent approval','assessmentGoalId':'eed5eda3-2daf-5d48-b935-23dadd622d9b','competenceGoalId':'e5a5dcd8-053c-55fd-b5c7-bba93779da53','literalPrimaryWitness':witness,'currentCoursePlacementDecision':'HOLD_NO_SUPPORTED_NORMAL_NTG11_SCOPE','currentSourceCourseLevel':'unspecified','currentPSelected':False,'actualNormalG1Diagnostic':{'result':'PASS','approved':0,'needsHumanReview':1,'blockers':0,'evidenceLevel':'E1','maximumClaimScope':'G1','status':'needs_human_review','reviewAuthority':'ai_candidate','literalHistoricalReviewId':prow['reviewId'],'literalProfileFingerprint':prow['profileFingerprint'],'actualTerminal':ref(P/'terminal/normal-existing-G1-profile-diagnostic.terminal.actual.json'),'newProfileOrJudgmentAuthored':False},'normalPDoesNotRequireGKOrLKAtlasScope':True,'G1Definition':'One identified learning goal and its bound artifacts. It is not curricular programme/course clearance.','actualPRequiredGates':'Current curricularAtomic; exact criteria/goal/profile/reviewInput/resource fingerprints; valid status and authority; genuine run references when claimed; coverage, fresh variation and independent transfer. No source-atlas/course-profile lookup is present in the normal P validator or central P loader.','sourceAndProjectionRequirement':'Chemistry review criteria still require preserving actual source and learner-facing projection, avoiding nationwide scope inferred from applicability and recording unresolved source concerns. Therefore a separate bounded subject-competence AUTHOR candidate can be reviewed while NTG11 placement remains explicitly HOLD. This diagnostic does not select it or invent its acceptance.','normalSourceAtlasRequiredGate':'C11 source metadata yields stage=[SekII], courseProfile=[] and scoped=false. Only four BB/BE fallback paths are authorized; no BY fallback or training-direction/year output dimension exists. This blocks normal scoped source-atlas inclusion, not the independent G1 profile schema.','actualScopeAndPlacementConstraints':normal,'closedScopeRejection':schema_negative,'authoredDataRecommendation':'Adopt none of the rejected diagnostic projections/placements. Keep source course unspecified, P unselected and current C11 course HOLD. A future supported NTG11 programme selector and reviewed placement would be a separate authorized task; no runtime/UX changes are proposed here.','otherScopedSourceWorkRetained':'The existing bounded378 source-supported union and23 source-scoped B008 children remain untouched; no C12/13 proxy is substituted for C11.1.11 and the whole398 curricularAtomic denominator is not reduced.','newIndependentApproval':False,'humanApproval':False,'strictGain':0,'operativeWrites':[]})
shutil.copyfile(pathlib.Path(__file__),R/P/'technical-finalize-and-seal-bounded-author.py')
checks=read(P/'checks/selective-own-diagnostic-positive-execution-inputs.json');ext=normal['normalSourceFiles']+checks['sourceCodeByteExact']+[checks['actualCurrentRaster'],checks['historicalP7Source'],ref(H/'research.final.entry.json'),ref(H/'research.final.freeze.json'),ref('contracts/curriculum-package/v1/composition-view.schema.json'),ref('contracts/goal-evidence/v2/goal-evidence-profile.schema.json'),ref('contracts/goal-evidence/v2/goal-evidence-review-config.schema.json'),ref('docs/landscape-runtime.schema.json'),ref('scripts/validate_schemas.py'),ref('docs/concept/skill-graph/learning-goal-book-and-evidence-review-pipeline.md'),ref('curricula/DE/Gymnasium/quality/goal-evidence/prompts/chemistry-positive-understanding-evidence-profile-criteria-v1.md')]
ext+=read(H/'research.final.freeze.json')['ownWholeFiles'];ext={x['path']:{k:x[k] for k in ['path','sha256','bytes']} for x in ext}
for x in ext.values():assert ref(x['path'])==x
put('inputs/required-current-portable-external-bindings.exact.json',{'schemaVersion':1,'bindings':[ext[k] for k in sorted(ext)],'observedOtherAuthorMutableCandidatePaths':'Diagnostic only; own whole517/kinds517 snapshots are immutable review inputs. No dependency on continuing other-agent writes or its capsule.','requiredIgnoredPaths':[]})
entry={'schemaVersion':1,'createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'entryKind':'bounded_C11_NTG_Layer_A_AUTHOR_constraints_and_G1_subject_competence_diagnostic','role':'Data proposal AUTHOR; no new independent judgment','currentDecision':'HOLD_NO_SUPPORTED_NORMAL_NTG11_SCOPE','currentPSelected':False,'sourceOfficialCourse':'unspecified','literalCurrentPrimaryWitness':witness,'completeAuthorConstraints':constraints,'actualNormalScopeAndPlacement':ref(P/'checks/actual-normal-C11-NTG-scope-and-placement-boundary.json'),'normalExistingG1CompetenceProfileDiagnostic':ref(P/'terminal/normal-existing-G1-profile-diagnostic.terminal.actual.json'),'historicalPRowExact':ref(P/'positive/historical-e5a5-one-row.DIAGNOSTIC-NOT-SELECTED.exact.jsonl'),'G1ResultIsNotCourseClearanceOrNewIndependentApproval':True,'existingWhole517Snapshot':ref(P/'inputs/whole517.observed-exact.json'),'existingKinds517Snapshot':ref(P/'inputs/kinds517.observed-exact.json'),'wholeGoalBodiesAndAssessmentRubricsEdited':False,'rejectedScopeAndPlacementSpecimens':'Own diagnostic failures only, no operative integration copy plan','actualTechnicalAssertionCorrections':ref(P/'checks/actual-two-driver-assertions-corrected-without-rule-change.json'),'requiredPortableInputs':ref(P/'inputs/required-current-portable-external-bindings.exact.json'),'priorResearchEntry':ref(H/'research.final.entry.json'),'priorResearchFreeze':ref(H/'research.final.freeze.json'),'priorPrimaryAndResearchSealsUnchanged':True,'other23ScopedSourcesAndBounded378UnionUnchanged':True,'398CurricularAtomicDenominatorUnreduced':True,'normalActualTerminals':[ref(f.relative_to(R)) for f in sorted((R/P/'terminal').glob('*.terminal.actual.json'))],'nextIndependentWork':'A separate current e5a5 G1 competence author candidate can be reviewed by two independent reviewers without granting course/source-atlas publication scope. ROOT retains authority over selection.','humanApproval':False,'runtimeOrUXChanges':[],'sourceExtractionWrites':[],'otherAgentCapsuleWrites':[],'operativeWrites':[],'GitOrGitHubWrites':[],'strictGain':0}
put(E.name,entry)
(R/P/'README.de.md').write_text('# C11 NTG11: begrenzter Layer-A-Autorbefund\n\nErgebnis: HOLD für die aktuelle NTG11-Platzierung. Der LehrplanPLUS-Fachlehrplan belegt C11.1.11 ausdrücklich in Chemie11(NTG); amtlicher Kurs bleibt unspecified. Die geschlossene Composition-Scope-Schnittstelle kennt keine Ausbildungsrichtung/Jahrgang-Dimension. NTG als freier courseProfile-Wert kompiliert, ist aber aus dem normalen committed Lernplanscope nicht ableitbar. Eine nur als NTG11 beschriftete BY/SekII-View passt dagegen auch zu allgemeinen GK/LK-Anfragen. Generische goalPlacement-Kontextfelder begrenzen bekannte Filter nicht; die beiden vorhandenen Nicht-Root-Eltern verhindern zusätzlich die vorgeschlagene Platzierung. Alle untersuchten Varianten bleiben ausdrücklich verworfene Diagnostik.\n\nDie normale G1-Prüfung der exakten vorhandenen e5a5-P-Zeile besteht: approved0, needs_human_review1, blocker0. G1 bedeutet ein identifiziertes Ziel mit gebundenen Artefakten und verlangt keine GK/LK-Atlasfreigabe. Kompetenzprofil und veröffentlichter Kurs-/Programmscope sind separate Behauptungen. Die normalen Chemie-Kriterien verlangen dennoch tatsächliche Quellen-/Projektionsgrenzen und offenen Dissens. SourceAtlas kann C11 mit SekII/unspecified nicht scoped einbinden; dessen Autor-Fallback ist auf vier BB/BE-Views beschränkt. Kein BY-Fallback oder Runtime-/UX-Eingriff wird eingeführt.\n\nAktuelle Primärseite und ganzer Lernbereich1 sind exakt gebunden; vorherige Research-Seals bleiben erhalten. Whole517/Kinds517 wurden als eigene exakte Beobachtungssnapshots kopiert; der andere Autor darf seine eigenen unversiegelten Dateien weiter bearbeiten. Keine Ziel-/Rubrikänderung, keine operative P-Auswahl, keine unabhängige Freigabe, kein strenger Zuwachs. Separater aktueller G1-Autorkandidat wird von ROOT und zwei unabhängigen Reviewern behandelt. Technischer Code Apache-2.0; eigener Befund CC-BY-4.0; Primärquellenrechte bleiben getrennt.\n')
spec=importlib.util.spec_from_file_location('normal_validate',R/'scripts/validate_schemas.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);runtime=read('docs/landscape-runtime.schema.json');reg=Registry();schemas={}
for base in ['contracts','docs']:
 for f in (R/base).rglob('*.schema.json'):
  x=json.loads(f.read_text());sid=x.get('$id')
  if sid:reg=reg.with_resource(sid,Resource.from_contents(x));schemas[sid]=x
negative=P/'rejected-projection-experiments/explicit-track-year.NOT-VALID-composition-view.json';count=closed=jsonl=0
for f in sorted((R/P).rglob('*')):
 if not f.is_file():continue
 assert not f.is_symlink()
 if f.suffix=='.json':
  x=json.loads(f.read_text());count+=1
  if f.relative_to(R)==negative:continue
  assert m.validate_file(str(f),runtime),f
  if x.get('$schema') in schemas:s=schemas[x['$schema']];jsonschema.validators.validator_for(s)(s,registry=reg).validate(x);closed+=1
 if f.suffix=='.jsonl':
  for l in f.read_text().splitlines():
   if l.strip():x=json.loads(l);s=schemas[x['$schema']];jsonschema.validators.validator_for(s)(s,registry=reg).validate(x);jsonl+=1
guards=read(P/'inputs/current-observed-author-state-and-write-boundaries.json')['activeUnchangedGuards']
for x in guards:assert ref(x['path'])==x
paths=[str(f.relative_to(R)) for f in (R/P).rglob('*') if f.is_file()]+list(ext)
ignored=subprocess.run(['git','check-ignore','--stdin'],cwd=R,input='\n'.join(paths)+'\n',capture_output=True,text=True);assert ignored.returncode==1,ignored.stdout
err=m.curriculum_symlink_errors(R);assert not err,err
put('checks/final-normal-targeted-schema-portability-and-current-guards.actual.json',{'schemaVersion':1,'actualExitCode':0,'normalJSONParsed':count,'closedValidSchemasValidated':closed,'normalPositiveJSONLValidated':jsonl,'intentionallyRejectedClosedCompositionSpecimen':ref(negative),'expectedNegativeSchemaErrors':len(errors),'ignoredRequiredPaths':[],'currentActiveChemAndOriginalSourceGuardsUnchanged':True,'normalCurriculumSymlinkErrors':err,'runtimeOrValidatorChanges':False,'independentApproval':False,'operativeWrites':[]})
entry=read(E);entry['finalTargetedNormalCheck']=ref(P/'checks/final-normal-targeted-schema-portability-and-current-guards.actual.json');(R/E).write_text(json.dumps(entry,ensure_ascii=False,indent=2)+'\n')
own=[ref(f.relative_to(R)) for f in sorted((R/P).rglob('*')) if f.is_file()]
freeze={'schemaVersion':1,'sealedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'role':'Bounded data AUTHOR constraints; current C11 NTG11 placement HOLD and normal existing G1 subject-competence diagnostic','entry':ref(E),'ownRegularFiles':own,'requiredCurrentPortableFiles':[ext[k] for k in sorted(ext)],'requiredIgnoredPaths':[],'deliberatelyRejectedSpecimen':ref(negative),'currentCourse':'unspecified','PSelected':False,'genuineNewIndependentApproval':False,'humanApproval':False,'runtimeOrUXChanges':[],'operativeWrites':[],'strictGain':0}
(R/F).write_text(json.dumps(freeze,ensure_ascii=False,indent=2)+'\n')
for x in own+list(ext.values()):assert ref(x['path'])==x
print(json.dumps({'entry':ref(E),'freeze':ref(F),'literalPrimaryWitness':witness,'ownRegularFiles':len(own),'requiredCurrentPortableFiles':len(ext),'normalExistingG1PositiveDiagnostic':'EXIT0 approved0/needsHuman1/blockers0','normalScopeAndParentGuardDiagnostic':'EXIT0','currentCoursePlacement':'HOLD','currentPSelected':False,'operativeWrites':[]}))
