# SPDX-License-Identifier: Apache-2.0
import pathlib,json,hashlib,datetime,shutil,urllib.request,copy
R=pathlib.Path('/home/enpasos/projects/skillpilot');BASE=pathlib.Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10');P=BASE/'chemie-b008-C11-NTG-bounded-layer-a-proposal-author-20261010-v1';H=BASE/'chemie-b008-C11-NTG-course-placement-research-neutral-20261010-v1';CURRENT=BASE/'chemie-b008-current517-machine-content-native-readiness-author-20261010-v1'
C=R/'tmp/m7-resumption-20261010/chem-c11-bounded-layer-a-author-only';assert not C.exists();assert not (R/P).exists();(R/P).mkdir();C.mkdir()
def read(p):return json.loads((R/p).read_text())
def ref(p):p=pathlib.Path(p);b=(R/p).read_bytes();return {'path':str(p),'sha256':'sha256:'+hashlib.sha256(b).hexdigest(),'bytes':len(b)}
def put(p,x):f=R/P/p;f.parent.mkdir(parents=True,exist_ok=True);f.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');return ref(P/p)
def exact(p,target):f=R/P/target;f.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(R/p,f);return ref(P/target)
hf=read(H/'research.final.freeze.json')
for x in hf['ownWholeFiles']:assert ref(x['path'])=={k:x[k] for k in ['path','sha256','bytes']}
wholepath=CURRENT/'candidate/whole517.inactive.machine-content-final-author.json';kindpath=CURRENT/'candidate/current517-semantic-kinds.inactive.json'
whole=exact(wholepath,'inputs/whole517.observed-exact.json');kinds=exact(kindpath,'inputs/kinds517.observed-exact.json');w=read(P/'inputs/whole517.observed-exact.json');ids=['e5a5dcd8-053c-55fd-b5c7-bba93779da53','eed5eda3-2daf-5d48-b935-23dadd622d9b'];byid={g['id']:g for g in w['goals']};assert all(x in byid for x in ids)
assert byid[ids[1]]['extendedData']['courseScopeHold']['PSelected']==False
snapshot=put('inputs/current-observed-author-state-and-write-boundaries.json',{'schemaVersion':1,'sourceCandidateDiagnosticAtObservation':ref(wholepath),'sourceKindsDiagnosticAtObservation':ref(kindpath),'sourceStillBeingAuthoredByOtherAgent':True,'requiredStableInputs':[whole,kinds],'activeUnchangedGuards':[ref(p) for p in ['curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_CHEMIE.de.json','curricula/DE/Gymnasium/quality/goal-book-publication/chemie.semantic-kinds.json','curricula/DE/Gymnasium/quality/goal-visualization-qa/chemie.qa.json','curricula/DE/Gymnasium/input/BY/gymnasium/source-extraction/DE_BY_CHEMIE_GYMNASIUM_LEHRPLANPLUS.source-extraction.json','curricula/DE/Gymnasium/input/BY/gymnasium/Chemie.json']],'otherAgentCapsuleWrites':[]})
observations=[]
for key,url in [('C11-NTG','https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/11/chemie'),('GSO-Anlage1','https://www.gesetze-bayern.de/Content/Document/BayGSO-ANL_1')]:
 t=datetime.datetime.now(datetime.timezone.utc).isoformat();req=urllib.request.Request(url,headers={'User-Agent':'SkillPilot curriculum author evidence/1.0'})
 with urllib.request.urlopen(req,timeout=40) as res:b=res.read();status=res.status;final=res.url
 f=P/'primary'/f'{key}.current-official.html.snapshot.txt';(R/f).parent.mkdir(parents=True,exist_ok=True);(R/f).write_bytes(b);observations.append({'key':key,'requestedURL':url,'actualResponseURL':final,'actualHttpStatus':status,'retrievedAt':t,'actualOriginalBytes':ref(f),'role':'Official primary source snapshot, no provider-layout/logo license asserted'})
put('primary/actual-current-official-fetch.receipt.json',{'schemaVersion':1,'observations':observations,'sourceExtractionWrites':[],'independentApproval':False})
exact(H/'inputs/current-C11-whole-operator-occurrences-and-programme.research-frame.json','inputs/prior-confirmed-C11-whole-source-frame.exact.json');exact(H/'sources/actual-official-live-programme-and-course-observations.json','inputs/prior-confirmed-regular-programme-table-observations.exact.json')
original=pathlib.Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-09/chemie-b008-current-twenty-six-native-preparation-author-v1/seven-operative-native-preparation-v2/P7.actual-current-raster.ordinary-author-candidate.review.jsonl')
line=next(l for l in (R/original).read_text().splitlines(keepends=True) if json.loads(l)['goalId']==ids[0]);f=R/P/'positive/historical-e5a5-one-row.DIAGNOSTIC-NOT-SELECTED.exact.jsonl';f.parent.mkdir(parents=True,exist_ok=True);f.write_text(line)
criteria=pathlib.Path('curricula/DE/Gymnasium/quality/goal-evidence/prompts/chemistry-positive-understanding-evidence-profile-criteria-v1.md');exact(criteria,'positive/chemistry-positive-criteria.exact.md')
cfg={'$schema':'https://skillpilot.com/schemas/goal-evidence/v2/goal-evidence-review-config.schema.json','schemaVersion':2,'reviewId':json.loads(line)['reviewId'],'goalFingerprintRuleVersion':'goal-evidence-v1','profileRuleVersion':'positive-understanding-evidence-v2','landscapeId':w['landscapeId'],'landscapePath':str(P/'inputs/whole517.observed-exact.json'),'semanticKindLedgerPath':str(P/'inputs/kinds517.observed-exact.json'),'reviewCriteriaPath':str(P/'positive/chemistry-positive-criteria.exact.md'),'reviewPath':str(P/'positive/historical-e5a5-one-row.DIAGNOSTIC-NOT-SELECTED.exact.jsonl'),'reviewRunManifestPaths':[],'reviewedResourceTypes':['goal-visualization'],'requireApproved':False,'scope':{'label':'Diagnostic existing G1 subject-competence profile only; current NTG11 placement remains HOLD and operative P remains unselected','goalIds':[ids[0]]}}
put('positive/one-existing-G1-profile.DIAGNOSTIC-NOT-OPERATIVE.config.json',cfg)
png=BASE/'chemie-b008-current-whole-P26-native-continuation-author-20261010-v1/assets/chemie'/ids[0]/f'{ids[0]}.png';pngref=ref(png)
codepaths=['app/scripts/positiveGoalEvidenceReview.ts','app/scripts/positiveGoalEvidenceProfileModel.ts','app/scripts/goalEvidenceProfileModel.ts','app/src/landscapeTypes.ts','contracts/goal-evidence/v2/goal-evidence-profile.schema.json','contracts/goal-evidence/v2/goal-evidence-review-config.schema.json','contracts/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json']
for p in codepaths:
 target=C/p;target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(R/p,target)
(C/'app/node_modules').symlink_to(R/'app/node_modules',target_is_directory=True)
for p in [P/'inputs/whole517.observed-exact.json',P/'inputs/kinds517.observed-exact.json',P/'positive/chemistry-positive-criteria.exact.md',P/'positive/historical-e5a5-one-row.DIAGNOSTIC-NOT-SELECTED.exact.jsonl',P/'positive/one-existing-G1-profile.DIAGNOSTIC-NOT-OPERATIVE.config.json']:
 target=C/p;target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(R/p,target)
target=C/'app/public'/byid[ids[0]]['resourceLinks'][0]['url'].lstrip('/');target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(R/png,target)
put('checks/selective-own-diagnostic-positive-execution-inputs.json',{'schemaVersion':1,'sourceCodeByteExact':[ref(p) for p in codepaths],'actualCurrentRaster':pngref,'historicalP7Source':ref(original),'newOwnCapsuleDiagnosticOnly':str(C),'nodeModulesDependencyDiagnosticOnly':str(R/'app/node_modules'),'filesCopied':len(codepaths)+6,'fullRepositoryCopy':False,'otherWriterCapsuleTouched':False,'newScienceOrApproval':False})
closure=set()
def prereq(gid):
 for x in byid[gid].get('requires',[]):
  if x in closure or x in ids:continue
  assert x in byid;closure.add(x);prereq(x)
for gid in ids:prereq(gid)
scope={'schoolForm':'Gymnasium','jurisdiction':'DE-BY','stage':'SekII','courseProfile':'NTG'}
view={'$schema':'https://skillpilot.com/schemas/curriculum-package/v1/composition-view.schema.json','viewFormatVersion':'1.0','viewId':'chemie-by-ntg11-C11-inactive-diagnostic-hold','landscapeId':w['landscapeId'],'language':'de-DE','title':'AUTHOR diagnostic: NTG11 knowledge development; not selectable in current committed scope','scope':scope,'rootNodes':[{'kind':'structure','id':'ntg11-root','label':'Chemie Jahrgangsstufe 11 (NTG)','children':[{'kind':'structure','id':'ntg11-process','label':'Wie Chemiker denken und arbeiten','children':[{'kind':'goalEntry','goalId':ids[0]}]},{'kind':'structure','id':'ntg11-exams','label':'Prüfungen Jahrgangsstufe 11 (NTG)','children':[{'kind':'goalEntry','goalId':ids[1]}]},{'kind':'structure','id':'ntg11-prerequisites','label':'Voraussetzungen','children':[{'kind':'goalEntry','goalId':gid,'projectionRole':'prerequisiteOnly'} for gid in sorted(closure)]}]}]}
put('rejected-projection-experiments/ntg-courseProfile.compilable-but-unselectable.view.json',view)
track=copy.deepcopy(view);track['viewId']='chemie-by-ntg11-explicit-track-year-schema-rejection';track['scope'].pop('courseProfile');track['scope'].update({'trainingDirection':'NTG','programmeYear':'11'});put('rejected-projection-experiments/explicit-track-year.NOT-VALID-composition-view.json',track)
generic=copy.deepcopy(view);generic['viewId']='chemie-by-general-sekii-labelled-ntg11-NOT-A-SAFE-BOUNDARY';generic['scope'].pop('courseProfile');put('rejected-projection-experiments/general-SekII-labelled-NTG11.NOT-A-SAFE-BOUNDARY.view.json',generic)
placed=copy.deepcopy(w);placed['programUnits']=[{'id':'by-ntg-inactive-author-track','kind':'track','label':'Naturwissenschaftlich-technologisches Gymnasium (NTG)'},{'id':'by-ntg-j11-inactive-author-year','kind':'year','label':'Jahrgangsstufe 11 (NTG)','shortLabel':'J11','parentUnitId':'by-ntg-inactive-author-track'}];placed['goalPlacements']=[{'goalId':gid,'unitId':'by-ntg-j11-inactive-author-year','relation':'primary','context':{'schoolForm':'Gymnasium','jurisdiction':'DE-BY','stage':'SekII','trainingDirection':'NTG','programmeYear':'11'}} for gid in ids];assert placed['goals']==w['goals'];put('rejected-projection-experiments/whole517.generic-context-placement.LEAKS-UNDER-BY.inactive.json',placed)
put('inputs/authored-proposal-experiment-boundaries.json',{'schemaVersion':1,'targetIds':ids,'prerequisiteOnlyGoalIds':sorted(closure),'existingCourseScopeHold':byid[ids[1]]['extendedData']['courseScopeHold'],'sourceOfficialCourse':'unspecified','currentOperativePSelected':False,'authorRecommendation':'Do not adopt any rejected experiment. No current normal scope can select NTG and year11 without replacing existing semantics. Preserve current HOLD.','changedWholeGoalBodies':[],'runtimeOrUXChanges':[],'independentApproval':False})
shutil.copyfile(pathlib.Path(__file__),R/P/'technical-prepare-author-proposal.py')
print(json.dumps({'namespace':str(P),'snapshotWhole':whole,'snapshotKinds':kinds,'ownDiagnosticCapsule':str(C),'currentRaster':pngref,'priorResearchOwnFilesVerified':len(hf['ownWholeFiles']),'newAuthoredGoalBodies':0,'operativeWrites':[]}))
