// SPDX-License-Identifier: Apache-2.0
// Factual inactive integration of genuine sealed independent reviews. No new science run.
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync,existsSync,copyFileSync,symlinkSync} from 'node:fs'
import {dirname,resolve,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import {buildGoalBookModel,fingerprintSemanticKindSourceGoal,loadGoalBookBuildInputs,stableGoalBookJson} from '../../../../../../../app/scripts/goalBookModel'
import {buildGoalBookOriginalSources} from '../../../../../../../app/scripts/goalBookOriginalSources'
import {validatePositiveGoalEvidenceRecordSemantics} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel'
const root=resolve('.'),own=dirname(fileURLToPath(import.meta.url)),base=resolve(own,'..'),author=resolve(base,'biologie-human20-current391-author-v1'),srcA=resolve(base,'biologie-human20-final-raster-native-independent-a-20261007-v1'),srcB=resolve(base,'biologie-human20-final-raster-native-independent-b-20261007-v1')
const sha=(b:Buffer|string)=>'sha256:'+createHash('sha256').update(b).digest('hex'),declared=new Map<string,any>()
const bind=(p:string)=>{const b=readFileSync(p);return {path:relative(root,p),sha256:sha(b),bytes:b.length}}
const bytes=(p:string)=>{declared.set(p,bind(p));return readFileSync(p)},read=(p:string)=>JSON.parse(bytes(p).toString('utf8'))
const write=(p:string,v:any)=>{mkdirSync(dirname(p),{recursive:true});const b=Buffer.isBuffer(v)||typeof v==='string'?v:JSON.stringify(v,null,2)+'\n';if(existsSync(p)){assert.equal(sha(readFileSync(p)),sha(b),'Existing prepared artifact cannot silently change');return}writeFileSync(p,b,{flag:'wx'})}
const verify=(dir:string,name:string,expected:string)=>{const p=resolve(dir,name);assert.equal(bind(p).sha256,'sha256:'+expected);const seal=read(p);for(const e of seal.frozenFiles){const q=existsSync(resolve(root,e.path))?resolve(root,e.path):resolve(dir,e.path);assert.equal(bind(q).sha256.replace('sha256:',''),e.sha256.replace('sha256:',''));if(e.bytes!==undefined)assert.equal(bind(q).bytes,e.bytes)}return {seal:bind(p),verifiedPayloads:seal.frozenFiles.length}}
const imageRoot=resolve(root,'curricula/DE/Gymnasium/quality/goal-visualization-review/biologie-human20-image-author-continuation-root-20261007-v2')
const seals={author:verify(imageRoot,'final-human20-raster-native-author-input.freeze.json','3116f324fa096c8f8061553bb7bedb2a16187a8a96f5b98586a2a3aad12b894d'),A:verify(srcA,'completed-native-D20-P20.independent-a.final.freeze.json','46629d1ce691432d09b71f438f2c07e95308393f969e2a3e1d0b0d24ea2cfa5d'),AFirst:verify(srcA,'first-final-D-P-V20.independent-a.freeze.json','c2f43201c67b01d03c30425b028011d5679b2476512f4cc7e0806a76d402fcc4'),B:verify(srcB,'independent-b.completed-human20.exact-input-output.first.freeze.json','e64ccb537d7b9a99b5370bdab59ba0328003fe32d5a96c70856852083549bf9c')}
const scientificA=read(resolve(srcA,'actual-current-D-P-context-source-retention.independent-a.receipt.json'))
for(const b of scientificA.retainedGenuinePriorScientificSeals){const p=resolve(root,b.path);assert.equal(bind(p).sha256,'sha256:'+b.sha256.replace('sha256:',''));const f=read(p);for(const e of f.frozenFiles??[]){const q=resolve(root,e.path);assert.equal(bind(q).sha256,'sha256:'+e.sha256.replace('sha256:',''))}}

const plan=read(resolve(own,'candidate/twenty-exact-resource-link-patches.guarded.json'))
for(const key of ['canonical','kinds','qa'])assert.equal(sha(bytes(resolve(root,plan.beforeBindings[key].path))),plan.beforeBindings[key].sha256,'Active '+key+' moved: explicit rebase required')
const canonicalPath=resolve(own,'candidate/canonical.future-active.json'),landscape=read(canonicalPath),before=read(resolve(own,'before/canonical.json')),ids=plan.selectedGoalIds as string[],selected=new Set(ids),goalBy=new Map<string,any>(landscape.goals.map((g:any)=>[g.id,g]))
assert.equal(landscape.goals.length,474);assert.equal(ids.length,20)
const sourceImageManifest=resolve(imageRoot,'selected-twenty-author-images.exact.json');assert.equal(bind(sourceImageManifest).sha256,'sha256:4cb47b854123f1e3b9d1bc55ab737c9ab1e0235b7d01d0d50839ef0365ef614b')
const images=read(sourceImageManifest).images,imageBy=new Map<string,any>(images.map((i:any)=>[i.goalId,i])),aV=read(resolve(srcA,'actual-twenty-V-first-independent-a.verdicts.json')),bV=read(resolve(srcB,'V20.actual-image-width-native-page.independent-b.json'))
assert.deepEqual(aV.openFindings??aV.findings,[]);assert.equal(aV.candidateV20Pass,20);assert.equal(bV.all20Passed,true);assert.equal(bV.unresolvedFindings,0)
const aVby=new Map<string,any>(aV.records.map((r:any)=>[r.goalId,r])),bVby=new Map<string,any>(bV.verdicts.map((r:any)=>[r.goalId,r]));assert.equal(aVby.size,20);assert.equal(bVby.size,20)
const futureQa=read(resolve(own,'before/qa.json')),qaBy=new Map<string,any>(futureQa.records.map((r:any)=>[r.goalId,r])),assetLineage:any[]=[]
for(const id of ids){const img=imageBy.get(id),a=aVby.get(id),b=bVby.get(id),g=goalBy.get(id),expected='sha256:'+img.sha256.replace('sha256:','');assert.equal(bind(resolve(root,img.path)).sha256,expected)
 assert.equal(a.scientificAndVisualVerdict,'PASS');assert.equal(a.machineCandidateDecision,'KEEP');assert.equal(a.actualObservedFullRaster.path,img.path);assert.equal('sha256:'+a.actualObservedFullRaster.sha256.replace('sha256:',''),expected);assert.equal(a.humanApproval,false)
 assert.equal(b.machineVisualizationDecision,'PASS');assert.equal(b.decision,'KEEP');assert.equal(b.selectedOriginalPNG.path,img.path);assert.equal('sha256:'+b.selectedOriginalPNG.sha256.replace('sha256:',''),expected);assert.equal(b.humanApproval,false);assert.equal(b.actualSourceRasterViewed,true);assert.equal(b.actualWholePageViewed,true);assert.deepEqual(b.openFindings,[])
 assert.deepEqual(a.actualObservedNativePdfPage,b.actualNativePDFGoalPage)
 for(const e of [...a.actualObservedChromiumCaptures,a.actualObservedNativePdfPage.capture,a.actualObservedNativePdfPage.actualPdf])assert.equal(bind(resolve(root,e.path)).sha256,'sha256:'+e.sha256.replace('sha256:',''))
 assert.equal(a.actualObservedChromiumCaptures.length,2);assert.equal(b.actualWidthCaptures.length,2)
 for(const e of b.actualWidthCaptures){assert.ok([360,680].includes(e.width));assert.equal(bind(resolve(root,e.path)).sha256,'sha256:'+e.sha256.replace('sha256:',''));assert.equal(e.measured.renderedWidth,e.width);assert.equal(e.measured.objectFit,'contain')}
 const q=qaBy.get(id);assert.equal(q.visualizationState,'missing');assert.equal(q.humanApproved,'no');assert.equal(q.humanIssueIdentified,'no');assert.equal(q.title,g.title);assert.equal(q.description,g.description)
 const patch=plan.rows.find((r:any)=>r.goalId===id);Object.assign(q,{visualizationState:'available',missingReason:'',imageUrl:patch.imageUrl,publicAssetPath:patch.futureAppPNG,canonicalAssetPath:patch.futureCanonicalPNG,assetSha256:expected,aiApproved:'yes',aiApprovedAssetSha256:expected,aiReviewedAt:[aV.recordedAt,bV.reviewedAt].sort().at(-1),aiReviewer:'Two genuine independent machine reviewers A and B, technically synthesized from exact sealed asset/page judgments; no human approval',aiNotes:'A: '+a.substantiveActualObservationsDe+' '+a.nativePageObservation+' B: '+b.substantiveScientificObservation+' '+b.mobile360+' '+b.desktop680+' '+b.nativePageObservation+' Exact seals A: '+seals.A.seal.path+'; B: '+seals.B.seal.path+'; original Carbonyl HOLD and exact unchanged-pixel resolution retained. No human approval or trial; Chromium captures are not physical-device acceptance.'})
 for(const [k,v]of Object.entries(read(resolve(own,'before/qa.json')).records.find((r:any)=>r.goalId===id)))if(k.startsWith('human'))assert.deepEqual(q[k],v)
 const dst=resolve(own,'selected-images',id+'.png');mkdirSync(dirname(dst),{recursive:true});if(!existsSync(dst))copyFileSync(resolve(root,img.path),dst);assert.equal(bind(dst).sha256,expected)
 const alias=resolve(own,q.imageUrl.replace(/^\//u,''));mkdirSync(dirname(alias),{recursive:true});if(!existsSync(alias))symlinkSync(relative(dirname(alias),dst),alias)
 assetLineage.push({goalId:id,sourceRaster:bind(resolve(root,img.path)),selectedRaster:bind(dst),originalPrompt:bind(resolve(root,img.promptPath)),originalGenerationProvenance:bind(resolve(root,img.toolProvenancePath)),targetPublicPath:q.publicAssetPath,targetCanonicalPath:q.canonicalAssetPath,altDe:img.altDe,altEn:g.resourceLinks.find((r:any)=>r.type==='goal-visualization').altEn??null,sourceIndependentAAssetRow:a,sourceIndependentBAssetRow:b,actualBothIndependentViews:['full','360','680','native-PDF-page'],machineApprovalOnly:true})}

for(const r of read(resolve(own,'before/qa.json')).records)if(!selected.has(r.goalId))assert.deepEqual(qaBy.get(r.goalId),r)
write(resolve(own,'candidate/visualization-qa.future-active.json'),futureQa)
const inertQa=structuredClone(futureQa);for(const r of inertQa.records)if(selected.has(r.goalId)){r.publicAssetPath=relative(root,resolve(own,'selected-images',r.goalId+'.png'));r.canonicalAssetPath=r.publicAssetPath}write(resolve(own,'candidate/visualization-qa.inactive-native.json'),inertQa)
write(resolve(own,'candidate/exact-selected-asset-provenance-and-paired-machine-approval.technical.json'),{seals,sourceManifest:bind(sourceImageManifest),rows:assetLineage,unrelatedQaRecordsExact:true,noExistingAssetReplaced:true,humanApproval:false,humanTrial:false,activeWrites:0})
const kinds=read(resolve(own,'before/kinds.json')),inertKinds=read(resolve(own,'candidate/semantic-kinds.inactive-native.json'));assert.equal(kinds.counts.curricularAtomic,391);assert.equal(kinds.counts.total,474)
for(const d of kinds.decisions)assert.equal(fingerprintSemanticKindSourceGoal(goalBy.get(d.goalId)),d.sourceFingerprint,'All classifications must stay current without adjusting any row')
const activeFullCfg=resolve(base,'biologie-ecology20-current391-reviewed-integration-preparation-technical-v1/native-full391.future-active.config.json'),actual=await loadGoalBookBuildInputs(activeFullCfg);assert.equal(actual.model.pages.length,391)
const inertCfg={...actual.config,landscapePath:relative(root,canonicalPath),semanticKindLedgerPath:relative(root,resolve(own,'candidate/semantic-kinds.inactive-native.json')),goalVisualizationQaPath:relative(root,resolve(own,'candidate/visualization-qa.inactive-native.json')),evidenceReviewPaths:[],outputPath:relative(root,resolve(own,'native-full391.current474-inactive.book-model.json'))},futureCfg={...actual.config,evidenceReviewPaths:[],outputPath:relative(root,resolve(own,'native-full391.future-active.pure.book-model.json'))}
const manifest=read(resolve(root,inertCfg.compositionViewManifestPath)),digests:Record<string,string>={};for(const r of inertQa.records)if(r.visualizationState==='available')digests[r.imageUrl]=sha(bytes(resolve(root,r.publicAssetPath)))
const common={landscape,compositionViewManifest:manifest,compositionViewSources:manifest.sourcePaths.map((p:string)=>({path:p,view:read(resolve(root,p))})),navigationView:read(resolve(root,manifest.navigationViewPath)),durationModelPolicy:read(resolve(root,manifest.durationModelPolicyPath)),goalVisualizationAssetDigests:digests,evidenceReviewSources:[]}
const model=buildGoalBookModel({...common,semanticKindLedger:inertKinds,goalVisualizationQa:inertQa,config:inertCfg}as any),futureModel=buildGoalBookModel({...common,semanticKindLedger:kinds,goalVisualizationQa:futureQa,config:futureCfg}as any)
assert.equal(model.pages.length,391);assert.equal(futureModel.pages.length,391);const oldPages=new Map(actual.model.pages.map(p=>[p.goalId,p])),futurePages=new Map(futureModel.pages.map(p=>[p.goalId,p])),authorFull=read(resolve(author,'native-raster-candidate/full391.book-model.json')),authorPages=new Map<string,any>(authorFull.pages.map((p:any)=>[p.goalId,p]))
const changed=model.pages.filter(p=>p.pageFingerprint!==oldPages.get(p.goalId)?.pageFingerprint);assert.deepEqual(new Set(changed.map(p=>p.goalId)),selected)
const compatibility:any[]=[]
for(const p of model.pages){assert.equal(p.pageFingerprint,futurePages.get(p.goalId)!.pageFingerprint)
 if(!selected.has(p.goalId))assert.equal(p.pageFingerprint,oldPages.get(p.goalId)?.pageFingerprint)
 else{const old=authorPages.get(p.goalId),normalized=structuredClone(p);delete normalized.pageFingerprint;normalized.visualization!.qaStatus=old.visualization.qaStatus;const comparison=structuredClone(old);delete comparison.pageFingerprint;assert.equal(stableGoalBookJson(normalized),stableGoalBookJson(comparison),'Every current full391 target field except exact approved QA-state metadata must match the author whole frame')
 compatibility.push({goalId:p.goalId,authorWholeFramePageFingerprint:old.pageFingerprint,futureWholeFramePageFingerprint:p.pageFingerprint,allScientificGoalContextSourceScopeFieldsExact:true,actualAssetDigestExact:old.visualization.originalDigest,actualChangedCurrentWholePageFields:old.visualization.qaStatus===p.visualization!.qaStatus?[]:['visualization.qaStatus','derived pageFingerprint'],beforeQaStatus:old.visualization.qaStatus,afterQaStatus:p.visualization!.qaStatus,noBlindHistoricalPageHashSubstitution:true,originalNativeSubset20ReviewFrameRetained:true})}}
const mappingPaths=read(resolve(root,'app/scripts/config/goal-books/de-gym-biology-national-atlas.inputs.json')).mappingPaths,oldSource=buildGoalBookOriginalSources(actual.model,root,mappingPaths),newSource=buildGoalBookOriginalSources(futureModel,root,mappingPaths);for(const k of Object.keys(oldSource).filter(k=>k!=='bookDigest'))assert.deepEqual((newSource as any)[k],(oldSource as any)[k])
write(resolve(own,'native-full391.current474-inactive.config.json'),inertCfg);write(resolve(own,'native-full391.current474-inactive.book-model.json'),model);write(resolve(own,'native-full391.future-active.config.json'),futureCfg);write(resolve(own,'native-full391.future-active.pure.book-model.json'),futureModel)
write(resolve(own,'checks/full391-exact-unaffected371-and-twenty-approved-state-only.technical.json'),{currentBaseCanonical:plan.beforeBindings.canonical,preparedFutureCanonical:bind(canonicalPath),sourceCanonicalDigestMustUsePreparedFutureBytes:bind(canonicalPath).sha256,all474ClassificationsExact:true,total391:true,other371PagesExactCurrentActive474:true,new11675TerminalPageRetainedExact:true,allPrimarySourceDocumentsClausesScopesAndTitlesExact:true,targetWholeFrameCompatibility:compatibility,noFull391PDFRendered:true,activeWrites:0})
const readRows=(p:string)=>bytes(p).toString('utf8').trim().split('\n').map(s=>JSON.parse(s)),aBinding=read(resolve(srcA,'P20.exact-final-author-input.binding.json'))
assert.equal(bind(resolve(root,aBinding.path)).sha256,'sha256:'+aBinding.sha256.replace('sha256:',''));assert.equal(aBinding.newProfileScientificAuthorship,false)
const pa=readRows(resolve(root,aBinding.path)),pbBy=new Map(readRows(resolve(srcB,'P20.current-raster-independent-b.review.jsonl')).map(r=>[r.goalId,r])),authorPBy=new Map(readRows(resolve(author,'native-raster-candidate/P20.actual-raster-author.review.jsonl')).map(r=>[r.goalId,r])),sciencePBy=new Map(readRows(resolve(author,'science-correction-v2/P20.current-text-preimage.author-targeted-v2.review.jsonl')).map(r=>[r.goalId,r]))
assert.equal(pa.length,20);assert.equal(pbBy.size,20);const ajv=new Ajv2020({strict:false,allErrors:true});addFormats(ajv);const schema=ajv.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json'))),cfgSchema=ajv.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-review-config.schema.json')))
const reviewId='biologie-human20-current391-paired-reviewed-current-binding-technical-20261007-v1',records:any[]=[],Plineage:any[]=[]
for(const a of pa){const b=pbBy.get(a.goalId),source=authorPBy.get(a.goalId),science= sciencePBy.get(a.goalId),g=goalBy.get(a.goalId),resources=Object.fromEntries(g.resourceLinks.filter((l:any)=>l.type==='goal-visualization').map((l:any)=>[l.url,digests[l.url]]));assert.ok(b);assert.ok(source);assert.ok(science)
 for(const k of ['profile','profileFingerprint','goalFingerprint','reviewInputFingerprint','reviewCriteriaFingerprint','evidenceLevel','maximumClaimScope','status','reviewAuthority']){assert.deepEqual(a[k],b[k]);assert.deepEqual(a[k],source[k])}
 assert.deepEqual(a.profile,science.profile);assert.equal(a.profileFingerprint,science.profileFingerprint)
 assert.equal(a.status,'needs_human_review');assert.equal(a.reviewAuthority,'ai_candidate');assert.equal(a.evidenceLevel,'E1');assert.equal(a.maximumClaimScope,'G1')
 assert.deepEqual(a.dissent,source.dissent);assert.deepEqual(a.dissent,science.dissent);assert.deepEqual(b.dissent.slice(0,a.dissent.length),a.dissent)
 const dissent=[...source.dissent,...b.dissent.slice(source.dissent.length),'Die aktuelle tatsächlich versiegelte A/B-Maschinenprüfung von D/P/V ist abgeschlossen; oben behaltene Autoren-Zeitaussagen sind historisch. E1/G1 und alle Quellen-/Leistungsgrenzen bleiben erhalten. Keine reale Lernendenleistung, E2, menschliche Freigabe oder Erprobung; öffentliche Dateibindungen und zentraler strenger Abschluss werden nach Integration geprüft.']
 const record={...source,reviewId,reviewedAt:new Date(Math.max(Date.parse(b.reviewedAt),Date.parse(read(resolve(srcA,'first-final-D-P-V20.independent-a.freeze.json')).recordedAt))+1000).toISOString(),reviewer:'Codex technical integrator of genuine sealed independent A/B science and current exact raster/page/context judgments; no new scientific reviewer or run',reason:'Exact independently reviewed whole bilingual profile body and all forty bilingual model cases retained from operative science-correction-v2. Current image, native page and full source/context fields have actual independent A/B sealed judgments. No new scientific review, whole-primary-source approval, learner performance, human approval or trial. A retained original science: '+seals.AFirst.seal.path+'; B actual current science/binding: '+seals.B.seal.path+'. Only integration metadata and current resources are bound.',reviewRunIds:[],dissent}
 assert.ok(schema(record),ajv.errorsText(schema.errors));assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(record,g,resources,'curricularAtomic'),[]);records.push(record)
 Plineage.push({goalId:a.goalId,sourceAInputBinding:bind(resolve(srcA,'P20.exact-final-author-input.binding.json')),sourceAReviewedAt:read(resolve(srcA,'first-final-D-P-V20.independent-a.freeze.json')).recordedAt,sourceBReviewId:b.reviewId,sourceBReviewedAt:b.reviewedAt,profileBodyExactBothAndAuthorV2:true,profileFingerprint:a.profileFingerprint,reviewInputFingerprint:a.reviewInputFingerprint,wholeSourceAndPerformanceDissentLimitsExact:a.dissent,sourceBFurtherDissentRetained:b.dissent.slice(a.dissent.length),onlyIntegrationMetadataAdded:true,noScientificRunInvented:true,resources})}

write(resolve(own,'positive/current20.records.jsonl'),records.map(r=>JSON.stringify(r)).join('\n')+'\n')
const positiveCfg={...read(resolve(author,'P20.current-text-preimage.author.config.json')),reviewId,landscapePath:plan.beforeBindings.canonical.path,semanticKindLedgerPath:plan.beforeBindings.kinds.path,reviewPath:relative(root,resolve(own,'positive/current20.records.jsonl')),reviewRunManifestPaths:[],scope:{label:'Current exact whole Human20 positive profiles from genuine paired independent science, E1/G1 machine candidates, no learner/Human evidence',goalIds:ids}};assert.ok(cfgSchema(positiveCfg),ajv.errorsText(cfgSchema.errors));write(resolve(own,'positive/current20.future-active.config.json'),positiveCfg)
write(resolve(own,'positive/current20.inactive-native.config.json'),{...positiveCfg,landscapePath:inertCfg.landscapePath,semanticKindLedgerPath:inertCfg.semanticKindLedgerPath})
write(resolve(own,'positive/twenty-paired-original-science-and-current-binding-lineage.technical.json'),{seals,rows:Plineage,nativePerRecordClosedSchemaPASS:true,nativePerRecordSemanticChecksPASS:true,scientificBodiesChanged:0,needsHumanReview:20,E1G1:true,actualPublicPCLIStillPendingRootIntegration:true,activeWrites:0})
write(resolve(own,'checks/ready-native-current20-profile-visual-and-whole391-bindings.technical.json'),{seals,selectedActualAssets:20,nativeP20SchemaAndSemanticsPASS:true,nativePureCurrent391PASS:true,exactOther371Pages:true,noActualAssetBytesChangedSincePairedIndependentReviews:true,currentAM20ExactOriginalRowsAndNativeChecks:'PASS',newScientificJudgmentsByTechnicalAgent:false,humanApproval:false,humanTrial:false,newStrictClosureClaim:0,potentialPackageGainAfterRootIntegrationAndCentralCheck:20,activeWrites:0})
write(resolve(own,'checks/binding-preparation-declared-inputs.json'),{files:[...declared.values()]})
console.log(JSON.stringify({futureCanonicalDigest:bind(canonicalPath).sha256,nativeFull391:'PASS',exactUnchangedPages:371,retained11675:'PASS',nativeP20SchemaAndSemantics:'PASS',pairedActualV20:'PASS',activeWrites:0,strictGainClaimed:0}))
