// SPDX-License-Identifier: Apache-2.0
// Technical adoption of actual two independent judgments; this author is no independent reviewer.
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync,existsSync,renameSync,symlinkSync,readlinkSync,realpathSync} from 'node:fs'
import {resolve,dirname,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import {normalizeGoalVisualizationAiReview,isGoalVisualizationAiApproved} from '../../../../../../../app/scripts/goalVisualizationQaModel.ts'
import {fingerprintGoalForPositiveEvidence,fingerprintPositiveGoalEvidenceReviewInput,fingerprintPositiveGoalEvidenceProfile,validatePositiveGoalEvidenceRecordSemantics} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel.ts'
import {buildGoalBookModel,loadGoalBookBuildInputs,stableGoalBookJson} from '../../../../../../../app/scripts/goalBookModel.ts'
const R=resolve('.'),D=dirname(fileURLToPath(import.meta.url)),base=resolve(D,'..'),author=resolve(base,'chemie-q3-whole-twenty-raster-native-remediation-technical-20261008-v2'),ids=['9f0d6d4c-f918-5a44-a9a2-7732c4e338f3','c95f6059-d7c2-5bcd-b61e-95e3577efdb2'],REQ=new Map<string,any>()
const sh=(b:Buffer|string)=>'sha256:'+createHash('sha256').update(b).digest('hex'),rp=(p:string)=>relative(R,p),bind=(p:string)=>{const b=readFileSync(p),v={path:rp(p),sha256:sh(b),bytes:b.length};REQ.set(v.path,v);return v},read=(p:string)=>{bind(p);return JSON.parse(readFileSync(p,'utf8'))}
const put=(name:string,v:any)=>{const p=resolve(D,name),b=Buffer.isBuffer(v)?v:Buffer.from(typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');if(existsSync(p))assert.ok(readFileSync(p).equals(b),p);else{mkdirSync(dirname(p),{recursive:true});const t=p+'.'+process.pid+'.tmp';writeFileSync(t,b,{flag:'wx'});renameSync(t,p)}return bind(p)}
const guard=read(resolve(D,'current-two-protected-baseline-and-original-pair.technical.guard.json')),can=read(resolve(R,guard.candidateCanonical.path)),by=new Map<string,any>(can.goals.map((g:any)=>[g.id,g])),kinds=read(resolve(R,guard.candidateKinds.path)),oldQA=read(resolve(D,'before/qa.exact.json')),sourceQA=read(resolve(author,'candidate/visualization-qa.current378.only-one-candidate-unapproved.inactive.json'))
const aFolder=resolve(base,'chemie-q3-two-corrosion-final-raster-native-independent-a-20261008-v2'),bFolder=resolve(base,'chemie-q3-two-corrosion-final-raster-native-independent-b-20261008-v2'),aPath=resolve(aFolder,'two-genuine-current-D-P-V.independent-a.first.verdicts.json'),bPath=resolve(bFolder,'two-current-whole-science-P-D-retained-and-targeted16-resolved.independent-b.first.verdict.json'),a=read(aPath),b=read(bPath),observedAt=[guard.originalGenuinePair.a.sealedAt,guard.originalGenuinePair.b.sealedAt].sort().at(-1)!
const wholeSourceA=read(resolve(aFolder,'eight-current-source-duties-all-partners.retained-independent-a.v3.actual.json')),wholeSourceB=read(resolve(bFolder,'two-whole-source-five-three-all-partners.independent-b.first.verdicts.json'))
for(const i of ids){const ar=a.records.find((r:any)=>r.goalId===i),br=b.verdicts.find((r:any)=>r.goalId===i);assert.ok(ar&&br);assert.equal(ar.semanticAtomicity,'atomic');assert.equal(ar.D,'KEEP');assert.equal(ar.V,'KEEP actual raster');assert.equal(ar.blockingFindings.length,0);assert.ok(br.semanticAtomicity.startsWith('retained genuine PASS'));assert.equal(ar.currentPeerFinalBFilesRead,0);assert.equal(br.status,'needs_human_review');assert.equal(br.evidenceLevel,'E1');assert.equal(br.maximumClaimScope,'G1')}
// Materialize the unchanged ordinary semantic-atomicity-v1 fingerprint contract.
const normalize=(v:any)=>String(v??'').normalize('NFKC').replace(/\s+/g,' ').trim()
const stable=(v:any):string=>Array.isArray(v)?`[${v.map(stable).join(',')}]`:v&&typeof v==='object'?`{${Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>JSON.stringify(k)+':'+stable(x)).join(',')}}`:JSON.stringify(v)
const atomFP=(g:any)=>sh(stable({ruleVersion:'semantic-atomicity-v1',goalId:g.id,shortKey:g.shortKey??'',title:normalize(g.title),titleEn:normalize(g.titleEn),description:normalize(g.description),descriptionEn:normalize(g.descriptionEn),phase:normalize(g.dimensionTags?.phase),area:normalize(g.dimensionTags?.area),topicCode:normalize(g.dimensionTags?.topicCode),nodeKind:normalize(g.nodeKind)}))
const aid='chemie-q3-two-corrosion-genuine-reviewed-atomicity-adoption-20261008-v1',A=ids.map(i=>{const ar=a.records.find((r:any)=>r.goalId===i),br=b.verdicts.find((r:any)=>r.goalId===i);return {schemaVersion:1,reviewId:aid,ruleVersion:'semantic-atomicity-v1',landscapeId:can.landscapeId,goalId:i,fingerprint:atomFP(by.get(i)),status:'atomic',semanticAtomic:true,reviewedAt:observedAt,reviewer:'Technical adoption of actual independent A/B whole chemistry atomicity judgments; integrator is not a new scientific reviewer',reason:'Beide tatsächlichen unabhängigen finalen Whole-Science-Urteile erklären dieses unveränderte ganze DE/EN-Ziel ausdrücklich als atomar. A: '+ar.scienceReasonDe+' B: '+br.reasonDe+' Keine neue fachliche Entscheidung durch diese technische Materialisierung; die vollständigen unabhängigen Zeilen und Erst-/Finalseals bleiben unverändert erhalten.'}})
put('atomicity/current-two.genuine-reviewed.records.jsonl',A.map(r=>JSON.stringify(r)).join('\n')+'\n');const Acfg={schemaVersion:1,reviewId:aid,ruleVersion:'semantic-atomicity-v1',landscapeId:can.landscapeId,landscapePath:guard.candidateCanonical.path,reviewPath:rp(resolve(D,'atomicity/current-two.genuine-reviewed.records.jsonl')),scope:{label:'Only two genuinely independent whole-science reviewed corrosion goals; technical record adoption',leafGoalIds:ids}};put('atomicity/current-two.inactive.config.json',Acfg);put('atomicity/current-two.future-active.config.json',{...Acfg,landscapePath:guard.before.canonical.active.path})
const qa=structuredClone(oldQA),selectedAssets:Record<string,string>={},qaChecks=[]
for(const i of ids){const r=qa.records.find((q:any)=>q.goalId===i),prior=oldQA.records.find((q:any)=>q.goalId===i),candidate=sourceQA.records.find((q:any)=>q.goalId===i);assert.ok(r&&prior&&candidate);const human=Object.fromEntries(Object.entries(prior).filter(([k])=>k.startsWith('human')))
 if(i===ids[1])Object.assign(r,candidate)
 const link=by.get(i).resourceLinks.find((l:any)=>l.type==='goal-visualization'&&l.role==='primary'),ext=i===ids[0]?'jpg':'png',image=resolve(D,'selected-images',i+'.'+ext),digest=bind(image).sha256;assert.equal(r.assetSha256,digest);r.imageUrl=link.url;r.publicAssetPath='app/public'+link.url;r.canonicalAssetPath=link.url.replace('/assets/goal-visualizations/','curricula/DE/Gymnasium/visualizations/');r.visualizationState='available';r.missingReason='';Object.assign(r,human,normalizeGoalVisualizationAiReview({aiApproved:'yes',aiApprovedAssetSha256:digest,aiReviewedAt:observedAt,aiReviewer:'Actual independent A and B final two-corrosion raster/native-page reviewers; technical adoption only',aiNotes:i===ids[0]?'Both genuine final A/B actual full JPEG, 360/680 widths and whole native page KEEP. Good original image retained byte exactly independent of its generator. Separate machine QA only; no human approval.':'Both genuine final A/B full corrected PNG, actual 360/680 widths and whole native page KEEP. Minimal real Humid Luft → Feuchte Luft correction independently verified. Science and visual author generation are not approval; these existing actual independent judgments are technically adopted. No human approval.'},digest));assert.ok(isGoalVisualizationAiApproved(r));selectedAssets[link.url]=digest;assert.deepEqual(Object.fromEntries(Object.entries(r).filter(([k])=>k.startsWith('human'))),human);qaChecks.push({goalId:i,actualAsset:bind(image),actualAiReviewedAt:observedAt,genuineFinalA_BV:true,humanFieldsExact:true})
 const alias=resolve(D,'assets/goal-visualizations/chemie',i,i+'.'+ext),target=relative(dirname(alias),image);mkdirSync(dirname(alias),{recursive:true});if(existsSync(alias))assert.equal(readlinkSync(alias),target);else symlinkSync(target,alias);assert.ok(realpathSync(alias).startsWith(D+'/'));bind(alias)
}
assert.equal(qa.records.length,379);for(const r of qa.records){const old=oldQA.records.find((q:any)=>q.goalId===r.goalId);if(!ids.includes(r.goalId))assert.deepEqual(r,old);assert.deepEqual(Object.fromEntries(Object.entries(r).filter(([k])=>k.startsWith('human'))),Object.fromEntries(Object.entries(old).filter(([k])=>k.startsWith('human'))))}
const qaPath=put('candidate/visualization-qa.current378.paired-two.future-active.json',qa)
const originalsPath=resolve(author,'positive/P2.actual-current-JPEG-KEEP-and-corrected-PNG.native-author.jsonl');bind(originalsPath);const originals=readFileSync(originalsPath,'utf8').trim().split('\n').map(l=>JSON.parse(l)),pid='chemie-q3-two-corrosion-paired-machine-current378-20261008-v1',ajv=new Ajv2020({allErrors:true,strict:true});addFormats(ajv);const validP=ajv.compile(read(resolve(R,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json'))),pChecks=[]
const P=originals.map(prior=>{const goal=by.get(prior.goalId),resourceDigests=Object.fromEntries(goal.resourceLinks.filter((l:any)=>l.type==='goal-visualization').map((l:any)=>[l.url,selectedAssets[l.url]])),ar=a.records.find((r:any)=>r.goalId===prior.goalId);assert.deepEqual(prior.profile,ar.wholePRecord.profile);assert.equal(prior.goalFingerprint,fingerprintGoalForPositiveEvidence(goal,'curricularAtomic'));assert.equal(prior.reviewInputFingerprint,fingerprintPositiveGoalEvidenceReviewInput(goal,prior.reviewCriteriaFingerprint,resourceDigests,'curricularAtomic'));assert.equal(prior.profileFingerprint,fingerprintPositiveGoalEvidenceProfile(prior.profile));const next={...prior,reviewId:pid,reviewedAt:observedAt,reviewer:'Technical adopter of genuine independent A/B whole current chemistry P2/science/source/raster judgments; not a new scientific reviewer',reason:'Actual independent A/B final whole science and P judgments both PASS for the entire retained bilingual profile and both complete application cases. Goal15 original JPEG and entire scientific profile remain exact. Goal16 actual previously held German standard-potential fresh/scoring statement is genuinely remedied and independently checked; only the minimal corrected caption PNG replaces its previous raster. All current five/three source obligations and every partner remain bounded. These are E1/G1 synthetic author models, not actual learner performance or experiment execution. Separate genuine D runs are not P run manifests; reviewRunIds remains empty. This is technical adoption of those actual judgments, not a new scientific review, human approval or trial.',reviewRunIds:[],dissent:['E1/G1 synthetic author model only; needs human review, no actual learner or experimental performance.','Independent whole source evidence is bounded to five/three duties with all partners; other18 original source/science/atomicity HOLDs remain outside this integration.','Ordinary operative corrected-PNG P2 CLI remains pending the Root guarded asset installation. Native current raster API/schema/semantic checks are separate truthful evidence.']};assert.deepEqual(next.profile,prior.profile);assert.equal(next.status,'needs_human_review');assert.equal(next.reviewAuthority,'ai_candidate');assert.equal(next.evidenceLevel,'E1');assert.equal(next.maximumClaimScope,'G1');assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(next,goal,resourceDigests,'curricularAtomic'),[]);assert.ok(validP(next),ajv.errorsText(validP.errors));pChecks.push({goalId:prior.goalId,wholeProfileAndCasesExact:true,goalFingerprint:next.goalFingerprint,reviewInputFingerprint:next.reviewInputFingerprint,profileFingerprint:next.profileFingerprint,actualRasterResources:resourceDigests,closedSchemaErrors:0,nativeSemanticErrors:0,reviewRunIds:[]});return next})
const pPath=put('positive/current-two.paired-machine-native.jsonl',P.map(r=>JSON.stringify(r)).join('\n')+'\n'),baseP=read(resolve(author,'positive/P2.actual-current-raster.future-active.config.json'));assert.equal(baseP.reportPath,undefined);const pConfig={...baseP,reviewId:pid,reviewPath:pPath.path,reviewRunManifestPaths:[],reviewedResourceTypes:['goal-visualization'],requireApproved:false,scope:{label:'Only two genuine independently reviewed current whole corrosion profiles and actual raster bindings; E1/G1 needs human review',goalIds:ids}};put('positive/current-two.future-active.config.json',pConfig);put('positive/current-two.inactive.config.json',{...pConfig,landscapePath:guard.candidateCanonical.path,semanticKindLedgerPath:guard.candidateKinds.path});const validCfg=ajv.compile(read(resolve(R,'contracts/goal-evidence/v2/goal-evidence-review-config.schema.json')));assert.ok(validCfg(pConfig),ajv.errorsText(validCfg.errors))
// Verify actual whole-page effects through the existing real loader and native compiler.
const cfgPath=resolve(author,'before/full378.current-before.real-loader.config.json'),beforeInput=await loadGoalBookBuildInputs(rp(cfgPath),R);assert.equal(beforeInput.model.pages.length,378);const digests:Record<string,string>={};for(const q of qa.records)if(q.visualizationState==='available'){const image=ids.includes(q.goalId)?resolve(D,'selected-images',q.goalId+(q.goalId===ids[0]?'.jpg':'.png')):resolve(R,q.publicAssetPath);const digest=bind(image).sha256;assert.equal(digest,q.assetSha256);digests[q.imageUrl]=digest}
const inactiveKinds={...kinds,sourceLandscapePath:guard.candidateCanonical.path};assert.deepEqual(inactiveKinds.decisions,kinds.decisions);const inactiveKindsPath=put('candidate/semantic-kinds.current480.path-only.inactive.json',inactiveKinds);const config={...beforeInput.config,landscapePath:guard.candidateCanonical.path,semanticKindLedgerPath:inactiveKindsPath.path,goalVisualizationQaPath:qaPath.path,outputPath:rp(resolve(D,'native/current378.paired-two.actual-model.json'))};put('candidate/current378.paired-two.path-bound.inactive-book.config.json',config);const afterModel=buildGoalBookModel({landscape:can,compositionView:read(resolve(R,config.compositionViewPath)),semanticKindLedger:inactiveKinds,goalVisualizationQa:qa,goalVisualizationAssetDigests:digests,evidenceReviewSources:[],config}as any);assert.equal(afterModel.pages.length,378);const reviewedFull=read(resolve(author,'native/full378.final-current-raster-api.book-model.json'));for(const page of afterModel.pages){const original=beforeInput.model.pages.find(p=>p.goalId===page.goalId)!;if(page.goalId!==ids[1])assert.equal(stableGoalBookJson(page),stableGoalBookJson(original),'Other377 page changed '+page.goalId);const reviewed=reviewedFull.pages.find((p:any)=>p.goalId===page.goalId);assert.equal(stableGoalBookJson(page),stableGoalBookJson(reviewed),'Actual paired native page must remain exact '+page.goalId)}
put('native/current378.paired-two.actual-model.json',afterModel);put('checks/genuine-A2-P2-QA2-and-whole-current-native-adoption.actual.json',{actualIndependentA:bind(aPath),actualIndependentB:bind(bPath),actualOriginalSourceA:bind(resolve(aFolder,'eight-current-source-duties-all-partners.retained-independent-a.v3.actual.json')),actualOriginalSourceB:bind(resolve(bFolder,'two-whole-source-five-three-all-partners.independent-b.first.verdicts.json')),genuineWholeAtomicityA2Rows:2,existing201ARecordsNotTouched:true,all480KindDecisionsExactWithInactivePathOnlyBinder:true,actualP2ClosedSchemaNativeSemanticErrors:0,actualFutureP2ConfigClosedSchemaErrors:0,originalProfilesAndAllFourCasesExact:true,reviewRunIdsEmptyAndDRunNotPManifest:true,P:pChecks,QA:qaChecks,actualAll378CompiledPageObjectsExactToReviewedFrame:true,other377BeforeCurrentWholePageObjectsExact:true,other479BeforeWholeCanonicalGoalsExact:true,other377WholeRawQARecordsExact:true,other376CurrentAtomicQARecordsExact:true,retainedExtraNonCurricularQARowExact:true,all379RawHumanFieldsExact:true,all378CurrentAtomicHumanFieldsExact:true,all378MemoryRecordsCardsAndSevenActualViewsExact:true,sourceAll1602_929_5459AndSelectedFiveThreePartnersExact:true,ordinaryOperativeP2CLI:'Pending actual guarded Root installation; current actual-raster API/schema/semantic checks pass',allOther18HoldsRetained:true,sourceScienceNewReviewByTechnicalIntegrator:false,activeWrites:0,strictGainClaimed:0,humanApproval:false,humanTrial:false});put('checks/genuine-A2-P2-QA2-declared-inputs.actual.json',{files:[...REQ.values()]});console.log(JSON.stringify({genuineA2AdoptionReady:true,P2CurrentRasterClosedSchemaSemanticsErrors:0,QA2NormalizedGenuineActualIndependentV:true,other377WholePagesAnd377RawQAAnd379RawHumanFieldsExact:true,whole378NativePageObjectsExactReviewed:true,ordinaryOperativeP2CLI:'pending Root installation',activeWrites:0,strictGain:0}))
