// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict'
import {readFileSync,writeFileSync} from 'node:fs'
import {resolve,dirname} from 'node:path'
import {fileURLToPath} from 'node:url'
import {buildGoalBookSourceAtlasInputs} from '/home/enpasos/projects/skillpilot/app/scripts/goalBookSourceAtlasInputs.ts'
const root='/home/enpasos/projects/skillpilot',own=dirname(fileURLToPath(import.meta.url)),read=(p:string)=>JSON.parse(readFileSync(p,'utf8'))
const oldConfig=read(resolve(root,'app/scripts/config/goal-books/de-gym-biology-national-atlas.inputs.json')),newConfig=read(resolve(own,'source/current390.future-active-atlas.inputs.json'))
const baseline=buildGoalBookSourceAtlasInputs(oldConfig,root),candidate=buildGoalBookSourceAtlasInputs(newConfig,resolve(own,'source/inert-input-root')),protectedIDs=read(resolve(own,'protected/current95-and-unrelated-state.technical.json')).protected95WholeGoals.map((r:any)=>r.goalId)
const routes=(outputs:Record<string,string|Buffer>,goalId:string)=>{const rows:any[]=[];for(const [path,bytes]of Object.entries(outputs)){if(!path.endsWith('.view.json'))continue;const v=JSON.parse(bytes.toString());const visit=(nodes:any[],parents:any[])=>{for(const n of nodes){if(n.kind==='goalEntry'&&n.goalId===goalId)rows.push({viewId:v.viewId,scope:v.scope,route:parents.map(x=>({id:x.id,label:x.label})),entry:n});if(n.children)visit(n.children,[...parents,n])}};visit(v.rootNodes,[])}return rows.sort((a,b)=>a.viewId.localeCompare(b.viewId))}
const protectedRows=protectedIDs.map((goalId:string)=>{const before=routes(baseline.outputs,goalId),after=routes(candidate.outputs,goalId);assert.deepEqual(after,before,'Protected95 source view route changed: '+goalId);return {goalId,sourceViews:before.map(x=>x.viewId),allWholeEntriesAndParentRoutesExact:true}})
const receipt={role:'Actual unchanged native source atlas builder on live current source bindings and guarded inert four-goal/source field candidate; computes only, no active outputs',baselineCounts:baseline.receipt.counts,candidateCounts:candidate.receipt.counts,protected95ExactSourceViewEntriesAndParentRoutes:protectedRows,expected390ContractPASS:true,wholeHistoricalSourceClearance:false,legacySourceHoldsRemain:true,activeWrites:false,newScientificJudgments:false,humanApproval:false,strictGain:0};writeFileSync(resolve(own,'source/native-current-field-merge-source-atlas-and95-routing.actual.json'),JSON.stringify(receipt,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({nativeSourceAtlas:'PASS',counts:candidate.receipt.counts,protected95SourceRoutes:'PASS',activeWrites:false,strictGain:0}))
