import {readFileSync,writeFileSync} from 'node:fs'
import {dirname,resolve,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
import assert from 'node:assert/strict'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import {validatePositiveGoalEvidenceRecordSemantics,fingerprintGoalForPositiveEvidence} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel'
import {buildGoalDescriptionCanonicalContext} from '../../../../../../../app/scripts/validateGoalDescriptionReviewCampaign'
import {buildGoalBookModel} from '../../../../../../../app/scripts/goalBookModel'
const root=resolve('.'),own=dirname(fileURLToPath(import.meta.url)),base=dirname(own),author=resolve(base,'biologie-he-evolution-eighteen-reviewed-integration-preparation-root-20261008-v1'),tech=resolve(base,'biologie-he-evolution-one-cat-raster-native-followup-technical-20261008-v2'),original=resolve(base,'biologie-he-evolution-eighteen-raster-native-author-technical-20261008-v1'),gid='7008979d-7890-5f7b-ad07-27b8bb597cbe'
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),hash=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex'),bind=(p:string)=>({path:relative(root,p),sha256:hash(p),bytes:readFileSync(p).length})
const seal=resolve(author,'required-link-metadata-P18.technical-first.freeze.json');assert.equal(hash(seal),'68de6451f5b2957dc365a55e618e70c5b2df81015c4422e17add1931afc5540c');for(const f of read(seal).files){assert.equal(hash(resolve(root,f.path)),f.sha256);assert.equal(readFileSync(resolve(root,f.path)).length,f.bytes)}
const entry=read(resolve(author,'neutral-required-link-metadata-and-P18.technical.entry.json'));for(const k of ['originalCanonical','candidateCanonical','oldCurrentRasterP18','currentP18','actualSelectedRasterQA']){const x=entry[k];assert.equal(hash(resolve(root,x.path)),x.sha256.replace('sha256:',''));assert.equal(readFileSync(resolve(root,x.path)).length,x.bytes)}
const old=read(resolve(root,entry.originalCanonical.path)),now=read(resolve(root,entry.candidateCanonical.path)),byOld=new Map(old.goals.map((g:any)=>[g.id,g])),byNew=new Map(now.goals.map((g:any)=>[g.id,g])),ids=entry.actualRequiredLinkMetadataDeltas.map((x:any)=>x.goalId),selected=new Set(ids);assert.equal(selected.size,18);assert.equal(old.goals.length,476);assert.equal(now.goals.length,476)
const oldp=readFileSync(resolve(root,entry.oldCurrentRasterP18.path),'utf8').trim().split('\n').map(x=>JSON.parse(x)),newp=readFileSync(resolve(root,entry.currentP18.path),'utf8').trim().split('\n').map(x=>JSON.parse(x));assert.equal(newp.length,18)
const ajv=new Ajv2020({allErrors:true,strict:true});addFormats(ajv);const val=ajv.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json'))),mapping=read(resolve(original,'checks/eighteen-native-whole-page-and-36-width-image-map.actual.json')).captures,receipts:any[]=[]
for(const g of now.goals){const before:any=byOld.get(g.id);if(!selected.has(g.id)){assert.deepEqual(g,before);continue}assert.deepEqual(Object.fromEntries(Object.entries(g).filter(([k])=>k!=='resourceLinks')),Object.fromEntries(Object.entries(before).filter(([k])=>k!=='resourceLinks')));assert.equal(g.resourceLinks.length,1);const l=g.resourceLinks[0],ol=before.resourceLinks[0];assert.deepEqual(Object.fromEntries(Object.entries(l).filter(([k])=>!['skillpilotId','provider','lang','license','reviewStatus'].includes(k))),ol);assert.equal(l.skillpilotId,g.id);assert.equal(l.provider,'ChatGPT/Codex builtin image_gen');assert.equal(l.lang,'de');assert.equal(l.license,'CC-BY-4.0');assert.equal(l.reviewStatus,'pilot');assert.equal(fingerprintGoalForPositiveEvidence(g,'curricularAtomic'),fingerprintGoalForPositiveEvidence(before,'curricularAtomic'));assert.deepEqual(buildGoalDescriptionCanonicalContext(g),buildGoalDescriptionCanonicalContext(before))}
for(const row of newp){const oldrow=oldp.find((x:any)=>x.goalId===row.goalId),g:any=byNew.get(row.goalId);assert.deepEqual(row.profile,oldrow.profile);assert.equal(row.goalFingerprint,oldrow.goalFingerprint);assert.equal(row.profileFingerprint,oldrow.profileFingerprint);assert.notEqual(row.reviewInputFingerprint,oldrow.reviewInputFingerprint);assert.equal(row.status,'needs_human_review');assert.equal(row.reviewAuthority,'ai_candidate');assert.equal(row.evidenceLevel,'E1');assert.equal(row.maximumClaimScope,'G1');const selectedPath=resolve(tech,'selected-images',row.goalId+'.png'),dig='sha256:'+hash(selectedPath),digests={[g.resourceLinks[0].url]:dig};assert.ok(val(row),ajv.errorsText(val.errors));assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(row,g,digests,'curricularAtomic'),[])
 const img= row.goalId===gid ? resolve(root,'curricula/DE/Gymnasium/quality/goal-visualization-review/biologie-he-evolution-one-cat-anatomy-correction-author-root-20261008-v2',gid,'candidate-v2.png') : resolve(root,mapping.find((x:any)=>x.goalId===row.goalId).originalPNG.path);assert.equal(hash(img),hash(selectedPath));const prov=img.replace(/\.png$/,'.provenance.json'),pj=read(prov);assert.ok(JSON.stringify(pj).includes('ChatGPT/Codex'));receipts.push({goalId:row.goalId,exactRequired5Metadata:true,wholeGoalDEENAndDCanonicalContextExact:true,wholePProfileAndBothCasesExact:true,actualCurrentPNG:bind(img),actualCurrentProvenance:bind(prov),actualResourceDigests:digests,newReviewInputFingerprint:row.reviewInputFingerprint,schemaErrors:0,semanticErrors:0,status:row.status,reviewAuthority:row.reviewAuthority})}
const cfg=read(resolve(tech,'candidate/book.current392.one-cat-correction.inactive.config.json')),qa=read(resolve(root,entry.actualSelectedRasterQA.path)),manifest=read(resolve(root,cfg.compositionViewManifestPath)),kinds=read(resolve(root,cfg.semanticKindLedgerPath)),digests=Object.fromEntries(qa.records.filter((r:any)=>r.visualizationState==='available').map((r:any)=>[r.imageUrl,r.assetSha256]));for(const r of receipts)assert.equal(digests[Object.keys(r.actualResourceDigests)[0]],Object.values(r.actualResourceDigests)[0]);
const input={compositionViewManifest:manifest,compositionViewSources:manifest.sourcePaths.map((p:string)=>({path:p,view:read(resolve(root,p))})),navigationView:read(resolve(root,manifest.navigationViewPath)),durationModelPolicy:read(resolve(root,manifest.durationModelPolicyPath)),semanticKindLedger:kinds,goalVisualizationQa:qa,goalVisualizationAssetDigests:digests,evidenceReviewSources:[],config:cfg};const oldModel=buildGoalBookModel({...input,landscape:old}as any),newModel=buildGoalBookModel({...input,landscape:now}as any);assert.equal(newModel.pages.length,392);assert.deepEqual(newModel.pages,oldModel.pages)
writeFileSync(resolve(own,'required-link-metadata-P18-targeted-technical.independent-b.receipt.json'),JSON.stringify({schemaVersion:1,checkedAt:new Date().toISOString(),authorFirstSeal:bind(seal),exactCurrent18MetadataAndPBindings:receipts,other458WholeGoalsExact:true,whole392NativePageObjectsAndFingerprintsExactByActualStandardCompiler:true,nativeCompilerApi:'buildGoalBookModel',whole18ScienceAndActualVJudgmentsRetainedNotRestarted:true,whole18DCanonicalContextsExact:true,newScientificApprovals:0,newVisualApprovals:0,bindingRestorationOnly:true,ordinaryPCLI:'pending actual install',activeWrites:0,strictGain:0,humanApproval:false,humanTrial:false},null,2)+'\n',{flag:'wx'});console.log('Actual targeted metadata/P18 check:18 exact5fields,18 closed/currentactualPNG semantics0,458goals exact,392standard-native-page objects exact; no new science or V approval.')
