// SPDX-License-Identifier: Apache-2.0
// Author engineering only: no reviewer records/runs, approval or integration.
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {existsSync,mkdirSync,readFileSync,writeFileSync,renameSync} from 'node:fs'
import {dirname,relative,resolve} from 'node:path'
import {fileURLToPath} from 'node:url'
import {fingerprintSemanticKindSourceGoal} from '../../../../../../../app/scripts/goalBookModel'
const root=resolve('.'),own=dirname(fileURLToPath(import.meta.url)),rp=(p:string)=>relative(root,p),declared:Record<string,any>={}
const sha=(b:Buffer|string)=>'sha256:'+createHash('sha256').update(b).digest('hex')
const bind=(p:string)=>{const b=readFileSync(p),r={path:rp(p),sha256:sha(b),bytes:b.length};declared[r.path]=r;return r}
const read=(p:string)=>{bind(p);return JSON.parse(readFileSync(p,'utf8'))}
const write=(p:string,v:any)=>{const b=Buffer.from(typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');if(existsSync(p)){assert.ok(readFileSync(p).equals(b));return bind(p)}mkdirSync(dirname(p),{recursive:true});const tmp=p+'.'+process.pid+'.tmp';writeFileSync(tmp,b,{flag:'wx'});renameSync(tmp,p);return bind(p)}
const g=read(resolve(own,'current204-whole-eighteen-author-guards.technical.json')),ids:string[]=g.selectedGoalIds,landscape=read(resolve(own,'candidate/canonical.current476.actual-raster.inactive.json')),sourceOnly=read(resolve(own,'candidate/canonical.current476.source-only.inactive.json')),by=new Map<string,any>(landscape.goals.map((r:any)=>[r.id,r])),oldKinds=read(resolve(own,'before/kinds.json')),kinds=structuredClone(oldKinds)
const wordIds=[...new Set<string>(g.whole3Fields2GoalWordPatches.map((p:any)=>p.goalId))],changedKinds=[]
for(const row of kinds.decisions){const fp=fingerprintSemanticKindSourceGoal(by.get(row.goalId));if(fp!==row.sourceFingerprint){assert.ok(wordIds.includes(row.goalId));changedKinds.push({goalId:row.goalId,before:row.sourceFingerprint,after:fp});row.sourceFingerprint=fp}}
assert.deepEqual(changedKinds.map(r=>r.goalId).sort(),wordIds.sort());assert.equal(kinds.counts.curricularAtomic,392);assert.equal(kinds.counts.total,476)
write(resolve(own,'candidate/semantic-kinds.current476.two-reviewed-word-patches.future-active.json'),kinds)
write(resolve(own,'candidate/semantic-kinds.current476.actual-raster.inactive.json'),{...kinds,sourceLandscapePath:rp(resolve(own,'candidate/canonical.current476.actual-raster.inactive.json'))})
write(resolve(own,'candidate/semantic-kinds.current476.source-only.inactive.json'),{...kinds,sourceLandscapePath:rp(resolve(own,'candidate/canonical.current476.source-only.inactive.json'))})
const oldQA=read(resolve(own,'before/qa.json')),qa=structuredClone(oldQA),images=read(resolve(own,'selected-eighteen-images.current-whole-exact.json'))
let unchanged=0
for(const q of qa.records){if(!ids.includes(q.goalId)){unchanged++;continue};assert.equal(q.visualizationState,'missing');assert.equal(q.humanApproved,'no');const im=images.images.find((im:any)=>im.goalId===q.goalId),goal=by.get(q.goalId),primary=goal.resourceLinks.find((l:any)=>l.type==='goal-visualization');assert.equal(bind(resolve(root,im.selectedPath)).sha256,'sha256:'+im.sha256)
 Object.assign(q,{title:goal.title,description:goal.description,visualizationState:'available',missingReason:'',imageUrl:primary.url,publicAssetPath:im.selectedPath,canonicalAssetPath:im.selectedPath,assetSha256:'sha256:'+im.sha256,chatGptNotes:'Actual current PNG AUTHOR candidate; generation is not approval. Two true blind final current D/P/V reviews pending.'});for(const k of ['aiApproved','aiApprovedAssetSha256','aiReviewedAt','aiReviewer','aiNotes'])delete q[k]
}
assert.equal(qa.records.length,392);assert.equal(unchanged,374);qa.records.sort((l:any,r:any)=>l.title.localeCompare(r.title,'de-DE',{numeric:true,sensitivity:'base'})||l.goalId.localeCompare(r.goalId))
write(resolve(own,'candidate/visualization-qa.current392.actual-raster-author.inactive.json'),qa)
const sq=structuredClone(oldQA);for(const q of sq.records)if(wordIds.includes(q.goalId)){q.title=by.get(q.goalId).title;q.description=by.get(q.goalId).description}
write(resolve(own,'candidate/visualization-qa.current392.source-only-loader.inactive.json'),sq)
const originalAtlas=read(resolve(own,'before/atlasInputs.json')),authorMapping=read(resolve(root,g.sourceV3MappingCandidate)),currentMatches=[]
const mappingPaths=originalAtlas.mappingPaths.map((path:string)=>{const m=read(resolve(root,path));if(m.sourceLandscapeId===authorMapping.sourceLandscapeId){currentMatches.push(path);return g.sourceV3MappingCandidate};return path})
assert.equal(currentMatches.length,1)
const inertRoot='app/scripts/config/goal-books/inactive/biologie-he-evolution-eighteen-raster-native-20261008-v1'
const atlasConfig={...originalAtlas,landscapePath:rp(resolve(own,'candidate/canonical.current476.actual-raster.inactive.json')),semanticKindLedgerPath:rp(resolve(own,'candidate/semantic-kinds.current476.actual-raster.inactive.json')),mappingPaths,outputDirectory:inertRoot+'/source-views',manifestPath:inertRoot+'/atlas.sources.json',navigationViewPath:inertRoot+'/navigation.view.json',expectedCurricularAtomicGoalCount:392}
write(resolve(root,inertRoot,'atlas.inputs.json'),atlasConfig)
const sourceCandidate=read(resolve(own,'whole-science/P18.thirty-six-whole-DEEN-cases.author.candidates.json')),reviewId='biologie-he-evolution-eighteen-current392-source-only-author-v1',reviewedAt=new Date().toISOString()
const sourceSpec={...sourceCandidate,reviewId,reviewedAt,reviewer:'Codex /root/he12_native_four_engineering technical author; not independent reviewer of current raster/native variant',goals:sourceCandidate.goals.map((r:any)=>({...r,reason:'Whole original bilingual science/case/profile bodies kept byte-semantically exact after genuine prior A/B whole science and Source-v3 pair. Two reviewed wording repairs retained. This is a source-only current technical author binding; actual new PNG/current native D/P/V pair still pending, E1/G1 ai_candidate needs_human_review, no learner/human/practical evidence.',dissent:['Technical author of this current raster/native variant, not its independent final reviewer.','Prior genuine whole case/profile science retained; optional/bounded source18 is not full144 source release or all-route original-operator approval.','Source-only record has no PNG digest; separate actual-raster APIs are required and ordinary raster CLI awaits installation after independent review.','E1/G1 AI candidate, needs_human_review; no actual learner performance, human approval or trial.']}))}
write(resolve(own,'positive/P18.whole-kept.source-only-author.candidates.json'),sourceSpec)
const criteria='curricula/DE/Gymnasium/quality/goal-evidence/prompts/biology-positive-understanding-evidence-profile-criteria-v1.md'
const cfg={$schema:'https://skillpilot.com/schemas/goal-evidence/v2/goal-evidence-review-config.schema.json',schemaVersion:2,reviewId,goalFingerprintRuleVersion:'goal-evidence-v1',profileRuleVersion:'positive-understanding-evidence-v2',landscapeId:landscape.landscapeId,landscapePath:rp(resolve(own,'candidate/canonical.current476.source-only.inactive.json')),semanticKindLedgerPath:rp(resolve(own,'candidate/semantic-kinds.current476.source-only.inactive.json')),reviewCriteriaPath:criteria,reviewPath:rp(resolve(own,'positive/P18.whole-kept.source-only-author.review.jsonl')),reviewRunManifestPaths:[],reviewedResourceTypes:[],requireApproved:false,scope:{label:'Explicit source-only technical P18 candidate; actual raster binding is separately native-API checked and normal raster CLI pending installation',goalIds:ids}}
write(resolve(own,'positive/P18.whole-kept.source-only-author.config.json'),cfg)
const whole=read(resolve(own,'whole-science/eighteen-whole-goals-thirty-six-complete-DEEN-cases.author.json'));assert.equal(whole.wholeCases.length,36);assert.equal(whole.wholeGoalBodies.length,18)
write(resolve(own,'current-eighteen-whole-DEEN-goals.actual.json'),{role:'Actual whole current476 candidate eighteen bodies including reviewed two wording repairs and new raster links; author only',goals:ids.map(id=>by.get(id)),activeWrites:0,strictGainClaimed:0})
let md='# Eighteen complete bilingual source-science case pairs\n\nUnchanged whole materials, tasks and model answers. Actual learner/practical performance and human approval are not claimed.\n'
for(const id of ids){const goal=by.get(id);md+='\n## '+goal.title+'\n\n'+id+'\n\n'+goal.description+'\n\n'+goal.descriptionEn+'\n';const cases=whole.wholeCases.filter((c:any)=>c.goalId===id);assert.equal(cases.length,2);for(const c of cases){const profile=sourceSpec.goals.find((p:any)=>p.goalId===id).profile,brief=profile.applicationCaseBriefs.find((b:any)=>b.id===c.id);assert.ok(brief);for(const [lang,suffix]of [['de','De'],['en','En']]){assert.equal(brief['taskDemand'+suffix],c.material[lang]+' '+c.task[lang]);assert.equal(brief['expectedPerformance'+suffix],c.modelAnswer[lang]);md+='\n### '+c.id+' ('+lang+')\n\n**Material**\n\n'+c.material[lang]+'\n\n**Task**\n\n'+c.task[lang]+'\n\n**Model answer**\n\n'+c.modelAnswer[lang]+'\n'}}}
write(resolve(own,'whole-science/eighteen-whole-goals-thirty-six-complete-DEEN-cases.current-binding.md'),md)
write(resolve(own,'checks/native-configs-two-word-kind-binding-and-whole36-retention.author.technical.json'),{role:'Technical author preparation, not new science review',wholeGoalCount476:true,atomic392:true,onlyTwoClassSourceFingerprintsRebound:changedKinds,allOther474ClassRowsKeptExact:true,newAuthorImages18Unapproved:true,other374QARowsExact:true,whole36CaseBodiesExact:true,whole18ProfileBodiesExact:true,currentSourceMappingReplacedOnlyInactive:currentMatches,sourceV3Mapping:g.sourceV3MappingCandidate,ordinarySourceOnlyP18Config:rp(resolve(own,'positive/P18.whole-kept.source-only-author.config.json')),ordinaryRasterP18CLIBlockedOnlyByNotYetInstalledCandidateAssets:true,noEmptyFilterClaimedAsRasterCheck:true,activeWrites:0,strictGainClaimed:0})
write(resolve(own,'checks/native-configs-declared-inputs.author.technical.json'),{files:Object.values(declared)})
console.log(JSON.stringify({whole476:true,atomic392:true,sourceAtlasInertConfig:true,wholeProfiles18Cases36Exact:true,newRaster18:'author unapproved',wordClassifierRebindings2:true,other474KindRowsExact:true,activeWrites:0,strictGainClaimed:0}))
