#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Materialize independently observed current E7 description candidates only."""
from pathlib import Path
import json, hashlib, datetime

OWN = Path(__file__).resolve().parent
PREP = OWN.parent / 'biologie-ephase-seven-current-native-candidate-v1'
ROUND = PREP / 'native-finalbook/round-a'
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p, v): p.write_text(json.dumps(v, ensure_ascii=False, indent=2) + '\n')
freeze = PREP / 'author-native-candidate.final.freeze.json'
assert sha(freeze) == '36a3cd9763d06419dba9a1464a2b36ea62f4e88a539fcdcf7ff3cfacf0dcc790'
frozen = json.loads(freeze.read_text())
assert len(frozen['files']) == 195
for f in frozen['files']:
    assert 'sha256:' + sha(Path(f['path'])) == f['sha256'], f['path']
c = json.loads((ROUND / 'description-review-campaign.json').read_text())
b = c['batches'][0]
inp = [json.loads(v)['goal'] for v in (ROUND / 'batches' / (b['batchId'] + '.input.jsonl')).read_text().splitlines()]
assert len(inp) == 7 and not (OWN / 'results').exists()
assert c['bookDigest'] == 'sha256:50ef9c8068c84a2da5301d8961622a7390cec096ebd789a5bfc373037918e92a'
assert c['bundleFingerprint'] == 'sha256:1e1ab0094971d73c89f78b142911847af93462216f1b667e5f9818914d842f52'
runid = 'biologie-ephase-seven-current-independent-d-a-20261005-v1'
e = [
[
'Tierische Entwicklung verbindet die Vermehrung von Zellen, ihre unterschiedliche Spezialisierung und die räumliche Ausbildung von Geweben und Körperformen. Eine veränderte Form allein zeigt noch nicht, welche Zellen sich geteilt oder differenziert haben.',
'Animal development connects an increase in cell number, different cell specializations, and spatial formation of tissues and body structures. A changed shape alone does not reveal which cells divided or differentiated.',
'Die lernende Person beschreibt an einem geeigneten tierischen Entwicklungsbeispiel das Zusammenspiel von Zellteilung, Differenzierung und Morphogenese und ordnet passende Befunde diesen miteinander verbundenen Vorgängen zu.',
'Using a suitable example of animal development, the learner describes the interplay of cell division, differentiation, and morphogenesis and relates appropriate observations to these connected processes.',
'Bei einer veränderten Entwicklungsfolge oder einem anderen tierischen Gewebe beschreibt die lernende Person erneut das Zusammenspiel und begründet, warum mehr Zellen allein noch keine neue Gewebeform oder Zellfunktion erklären. Eine schematische Farbe wird nicht als nachgewiesene Zellabstammung verwendet.',
'For a changed developmental sequence or another animal tissue, the learner again describes the interplay and explains why more cells alone do not account for a new tissue shape or cell function. A schematic colour is not treated as evidence of cell lineage.'
],
[
'Pflanzliche Entwicklung verbindet Zellteilung, Differenzierung und räumliche Formbildung; die Entstehung eines Blattes oder einer Frucht ist mehr als eine bloße Zunahme gleichartiger Zellen. Eine Sprossknospe veranschaulicht einen begrenzten Entwicklungsfall.',
'Plant development connects cell division, differentiation, and spatial formation of structures; formation of a leaf or fruit involves more than an increase in identical cells. A shoot bud illustrates a limited developmental case.',
'Die lernende Person erläutert an einem Pflanzenbeispiel, wie neue Zellen, unterschiedliche Zellfunktionen und die Ausbildung eines Organs zusammenwirken, und trennt sichtbare Entwicklungsmerkmale von ergänzenden Modellinformationen.',
'Using a plant example, the learner explains how new cells, different cell functions, and formation of an organ interact and distinguishes visible developmental features from supplementary model information.',
'Für ein anders dargestelltes pflanzliches Organ oder eine veränderte Entwicklungsfolge erläutert die lernende Person das Zusammenspiel erneut und vermeidet, alle Veränderungen allein als Zellvermehrung zu bezeichnen. Die einfache Beschreibung der Individualentwicklung aus Sek I wird nicht als Beleg für die gesamte zellbiologische Erklärung verwendet.',
'For a differently represented plant organ or a changed developmental sequence, the learner again explains the interplay and avoids calling every change merely cell multiplication. A lower-secondary description of individual development is not treated as evidence of the complete cell-biological explanation.'
],
[
'Meristeme stellen teilungsfähige Zellbereiche für die weitere Pflanzenentwicklung bereit. Signale zwischen Zellen können ihre Teilung und Entwicklung abstimmen; der räumliche Signalweg und die Zellreaktion sind Modellbeziehungen, keine aus einer Zeichnung nachgewiesene Molekülidentität.',
'Meristems provide regions of division-capable cells for further plant development. Signals between cells can coordinate their division and development; the spatial signal route and cell response are model relationships, not molecular identities established by a drawing.',
'Die lernende Person erklärt an einem Meristembeispiel die Funktion des teilungsfähigen Bereichs und an einem passenden vereinfachten Signalbeispiel, wie eine Information zwischen Zellen eine Entwicklungsreaktion beeinflussen kann.',
'Using a meristem example, the learner explains the function of the division-capable region and uses a suitable simplified signalling example to explain how information exchanged between cells can affect a developmental response.',
'Bei einem anderen Meristem oder einem veränderten Signalweg erklärt die lernende Person die Folgen für den beschriebenen Wachstumsvorgang und unterscheidet Signalübertragung von bloßer Stoffversorgung. Eine bestimmte Hormonsorte oder ein vollständiger molekularer Signalweg wird nicht zusätzlich vorausgesetzt.',
'For another meristem or a changed signalling route, the learner explains the consequences for the described growth process and distinguishes signal transmission from mere nutrient supply. A particular hormone or a complete molecular signalling pathway is not added as a prerequisite.'
],
[
'Diffusion verteilt Teilchen; Osmose ist der Nettotransport von Wasser durch eine selektiv durchlässige Membran. In einer Pflanzenzelle kann Wasserabgabe zur Ablösung des Protoplasten von der Zellwand führen. Beobachtungen und die Erklärung durch Teilchen- beziehungsweise Membranmodelle sind zu unterscheiden.',
'Diffusion redistributes particles; osmosis is net movement of water through a selectively permeable membrane. In a plant cell, water loss can cause the protoplast to pull away from the cell wall. Observations must be distinguished from explanations using particle and membrane models.',
'Die lernende Person führt geeignete Versuche zu Diffusion, Osmose und Plasmolyse mit zulässiger Anleitung durch, dokumentiert Vergleichsbedingungen und eigene Beobachtungen beziehungsweise Messungen und deutet die Ergebnisse mit passenden Transportvorstellungen. Ein gegebenes Protokoll allein ersetzt die Durchführung nicht.',
'The learner carries out suitable investigations of diffusion, osmosis, and plasmolysis with permitted guidance, documents comparison conditions and their own observations or measurements, and interprets the results using suitable transport concepts. A supplied laboratory record alone does not replace carrying out the investigation.',
'Bei verändertem Konzentrationsunterschied oder einem anderen geeigneten Präparat führt die lernende Person den angepassten Vergleich durch, dokumentiert den Befund und erklärt die Transportrichtung beziehungsweise die Veränderung des Protoplasten. Vermutete Teilchenbewegung und tatsächlicher mikroskopischer Befund werden getrennt.',
'With a changed concentration difference or another suitable specimen, the learner carries out the adapted comparison, documents the result, and explains the direction of transport or the change in the protoplast. Inferred particle movement is distinguished from actual microscope observations.'
],
[
'Membranmodelle unterscheiden sich in ihren Annahmen zur Anordnung von Lipiden und Proteinen. Ihre Aussagekraft hängt davon ab, welche Struktur- und Funktionsbefunde sie erklären; die größere Zahl gezeichneter Einzelheiten macht ein Modell nicht automatisch zutreffender.',
'Membrane models differ in their assumptions about the arrangement of lipids and proteins. Their explanatory value depends on the structural and functional observations they account for; drawing more details does not automatically make a model more accurate.',
'Die lernende Person stellt unterschiedliche Membranmodelle mit ihren wesentlichen Annahmen dar, vergleicht diese an passenden Struktur- oder Funktionsbefunden und begründet eine Stärke und eine Grenze der jeweiligen Darstellung.',
'The learner depicts different membrane models with their main assumptions, compares them using suitable structural or functional observations, and explains a strength and a limitation of each representation.',
'Bei einem zusätzlichen Befund, etwa zur Lage oder Beweglichkeit eines Membranproteins, beurteilt die lernende Person erneut, welches Modell den Befund besser berücksichtigt und wo selbst das passendere Modell vereinfacht. Das Bild wird nicht als eigener experimenteller Befund ausgegeben.',
'Given an additional observation, such as the location or movement of a membrane protein, the learner reassesses which model accounts for it better and where even the more suitable model simplifies the system. The illustration is not presented as their own experimental observation.'
],
[
'Die RGT-Regel beschreibt im geeigneten begrenzten Temperaturbereich die ungefähre Änderung einer Reaktionsgeschwindigkeit bei einer Temperaturänderung um zehn Grad. Der konkrete Faktor gehört zum betrachteten Fall; bei einem sich inaktivierenden oder denaturierenden Enzym darf diese Zunahme nicht weiter extrapoliert werden.',
'Within a suitable limited temperature range, the RGT rule describes the approximate change in reaction rate for a temperature change of ten degrees. The specific factor belongs to the case considered; this increase must not be extrapolated when the enzyme is becoming inactivated or denatured.',
'Die lernende Person quantifiziert für einen angegebenen geeigneten Temperaturbereich mit einem passenden gegebenen beziehungsweise fallbezogen begründeten RGT-Faktor die Änderung einer Enzymaktivität und erläutert die Bedeutung von Faktor, Temperaturdifferenz und unveränderten Vergleichsbedingungen.',
'For a stated suitable temperature range, the learner quantifies the change in enzyme activity using an appropriate supplied or case-justified RGT factor and explains the meaning of the factor, temperature difference, and unchanged comparison conditions.',
'Für einen veränderten Ausgangswert oder eine andere Temperaturdifferenz berechnet die lernende Person erneut die näherungsweise Änderung und entscheidet bei einem Fall außerhalb des geeigneten Bereichs, warum keine weitere RGT-Hochrechnung zulässig ist. Ein eigener zweiter Denaturierungsnachweis wird daraus nicht gemacht.',
'For a changed initial value or another temperature difference, the learner again calculates the approximate change and explains why further RGT extrapolation is invalid for a case outside the suitable range. This does not add a second independent denaturation investigation.'
],
[
'Allosterische Hemmung beschreibt die Beeinflussung einer Enzymwirkung durch Bindung an einer anderen Stelle als dem aktiven Zentrum. Nichtkompetitive Hemmung bezeichnet ein bestimmtes Hemmungsverhalten im jeweiligen Modell; ein gezeichneter anderer Bindungsort beweist keine allgemeine Identität mit rein nichtkompetitiver Kinetik.',
'Allosteric inhibition describes an effect on enzyme action caused by binding at a site other than the active site. Noncompetitive inhibition describes a particular inhibition behaviour in the relevant model; a differently located binding site in a drawing does not establish a universal identity with pure noncompetitive kinetics.',
'Die lernende Person erklärt an geeigneten Beispielen, wie ein allosterischer Hemmstoff die Enzymwirkung verändert und wie das beschriebene nichtkompetitive Hemmungsverhalten vom bloßen Wettbewerb um das aktive Zentrum abzugrenzen ist, und ordnet einen passenden Arznei- oder Giftstoffkontext zu.',
'Using suitable examples, the learner explains how an allosteric inhibitor changes enzyme action and distinguishes the described noncompetitive inhibition behaviour from mere competition for the active site, relating it to a suitable medication or toxic-substance context.',
'In einem veränderten Alltagsbeispiel mit angegebenem Bindungs- und Wirkungsmodell erklärt die lernende Person die Hemmwirkung erneut und begründet, welche Aussage zum Hemmungsverhalten durch die Angaben getragen wird. Aus einem anderen Bindungsort allein wird weder eine universelle Nichtkompetitivität noch ein unverändertes Km abgeleitet.',
'In a changed everyday example with a stated binding and effect model, the learner again explains the inhibition and justifies which claim about its behaviour is supported by the information. A different binding site alone is not used to infer universal noncompetitiveness or an unchanged Km.'
]
]
r = [
'KEEP: Die vollständigen aktuellen DE/EN-Texte beschreiben dieselbe integrierte tierische Entwicklungsbeziehung. Teilung, Differenzierung und Formbildung sind hier gemeinsam an einem Entwicklungsfall zu beschreiben, keine drei unabhängigen Stofflisten. HE physisch/gedruckt S.36, E.4 Bullet1, trägt diesen Zusammenhang; Modellorganismen bleiben Bullet2 und die sichtbare externe Voraussetzung. E.4 ist gemäß Original S.35 kein verbindliches Themenfeld E.1-E.3. Das tatsächliche PNG und die volle PDF S.3 sowie geladene HTML-Seite zeigen schematische Gewebeformung; Alt-Text begrenzt Tierart, Stadienfolge und Farbbedeutung zutreffend. Kein neuer universeller Zellabstammungsnachweis oder externe BY-Vollfreigabe aus roher Geltungsliste.',
'KEEP: DE/EN erläutern dasselbe Zusammenspiel bei Pflanzen; der kurze beschreibende Titel schränkt die ausdrücklich erläuternde Beschreibung nicht auf das Benennen von Stadien ein. HE S.37 E.5 Bullet1 ist der aktuelle gesamte zellbiologische Bezug, E.5 ist nicht verbindliches E.1-E.3-Thema. Native PDF S.4 und actual HTML stellen Sprossknospe und Meristem-Nachfolger korrekt dar; die Farben sind ausdrücklich kein Zellliniennachweis. Original NI S.87 trägt die einfache Beschreibung der Individualentwicklung von Blütenpflanzen am Ende Jg.6, SL S.25-26 enthält lokal Fruchtformen/Verbreitung/ungeschlechtliche Vermehrung. Beide bestehenden partial mappings werden nur als Teilkontexte erhalten und tragen weder HE-vollen Erklärungsanspruch noch den Abschluss der anderen lokalen Pflanzenziele. Kein alter SL-Seitenverweis wird durch einen neuen behaupteten Originalbullet ersetzt.',
'KEEP: Eine funktionale Erklärung der Regulation weiterer Pflanzenentwicklung integriert den teilungsfähigen Meristembereich und den Signalaustausch; der bereits vorausgesetzte Pflanzenentwicklungsfall liefert den Zusammenhang. Aktuelle DE/EN verlangen keine bestimmte Hormonsorte oder vollständige Signalkaskade. HE S.37 enthält die getrennten offiziellen Bullet2 und3, beide sind in der aktuellen Quelle erhalten; kein gesamter E.5-Abschluss wird beansprucht. Tatsächliches PNG, volle PDF S.5 und geladene HTML zeigen Meristemlokalisation und gerichtete schematische Signale; Alt-Text trennt Modellpunkte von Molekülidentität. Keine identische Funktion jeder dargestellten Zellform unterstellt.',
'KEEP: Die experimentelle Untersuchung der verbundenen passiven Transportphänomene einschließlich plasmolytischer Zellreaktion ist eine begrenzte Untersuchungsleistung mit tatsächlicher Durchführung, Dokumentation und begründeter Deutung. HE S.36 E.1 Bullet5 verlangt ausdrücklich experimentell; die DE/EN-Texte bewahren das. Original BW physisch26/gedruckt24 nennt durchgeführte mikroskopische Untersuchung von Plasmolyse/Deplasmolyse und Osmose-Erklärung; das bestehende partial mapping bleibt begrenzt. Native PDF S.6 und actual HTML zeigen Farbstoffverteilung, Nettowasserbewegung zur gelösten-Stoff-Seite und zurückgezogenen Protoplasten, nicht einen eigenen schon erbrachten Versuchsbeleg. Keine zusätzliche Selbstständigkeit ohne Anleitung verlangt; bloße Interpretation eines gegebenen Protokolls wäre unzureichend. Die drei zusammengehörigen Fälle werden als vergleichende Transportuntersuchung bewertet, nicht allein aufgrund eines gemeinsamen Quellbullets atomar genannt.',
'KEEP: Die aktuelle Darstellung und kritische Prüfung unterschiedlicher Modelle ist ein kriteriengebundener Modellvergleich. Deutsche Aussagekraft und englische validity sind im konkreten Modellkontext gleichwertig; keine absolute Wahrheit aller Modellteile wird verlangt. HE S.36 E.1 Bullet6 nennt Biomembran-Schema und Modelle-Übersicht; die Quelle deckt diesen Modellaspekt, während sämtliche Lipid- und Transportkomponenten getrennt bleiben. Tatsächliches PNG/PDF S.7/HTML zeigt den Kontrast äußerer Proteinlagen zu eingelagerten Proteinen; Alt-Text passt. Ein Kanal im Bild begründet weder dessen gesamte Transportkompetenz noch ein eigenes Experiment. Gute vorhandene Rasterdarstellung bleibt unverändert.',
'KEEP: Quantifizieren mittels einer fallgebundenen Näherungsregel ist ein anderes beobachtbares Können als die bereits als externe Voraussetzung sichtbare qualitative Temperatur-/Denaturierungsdeutung. Aktuelle DE/EN bezeichnen dieselbe RGT-Anwendung. HE S.36 E.2 Bullet4 enthält auch pH und Substratkonzentration; das aktuelle partial mapping erhält hier allein die RGT-Temperaturkomponente, keine gesamte Sammelbullet-Freigabe. Actual PNG/PDF S.8/HTML zeigt gleiche Zeit, 10/20Grad und im Modell doppelte Produkte mit separater Überhitzungsgrenze, nicht universell Faktor2. Die neue Evidenz begrenzt Temperaturbereich und Faktor; die aktuelle memory_required-Karten-/Sichtbarkeitsentscheidung ist ein getrennt zu erhaltendes M-Gate und wird durch D nicht abgeschaltet.',
'KEEP: Aktuelle DE/EN nennen allosterische und nichtkompetitive Hemmung, behaupten keine automatische Gleichheit beider Begriffe. Prinzip und funktionaler Alltagsbezug bilden eine begrenzte Mechanismus-/Wirkungs-Erklärung mit dem grundlegenden Enzymhemmungsziel als Voraussetzung; dessen teilweise Allosterieabdeckung wird nicht als vollständige Nichtkompetitivitätsprüfung ausgegeben. HE S.36 E.2 Bullet5 enthält zusätzlich kompetitive Hemmung; aktuelles partial mapping hält diesen breiten Quellenpunkt offen. Das tatsächlich gesehene PNG/PDF S.9/HTML zeigt nur einen allosterischen Formänderungsfall; passender Alt-Text behauptet keine Km-/Vmax-Messung oder reine Nichtkompetitivität. IUBMB actual Section6.4 bestätigt die kinetische Bedeutung und deren Bindungsmechanismus-unabhängige Definition. Ein eigener kinetischer Vollkurs wird nicht zur Voraussetzung erhoben, die fachliche Nichtgleichsetzung bleibt aber erforderlich.'
]
keys = ['essentialUnderstandingDe','essentialUnderstandingEn','observablePerformanceDe','observablePerformanceEn','transferExpectationDe','transferExpectationEn']
records = []
for i, (g, ev, rat) in enumerate(zip(inp, e, r), 1):
    assert g['reviewContext']['evidenceProfile'] is None
    rec = {'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json','schemaVersion':1,'recordId':f'{runid}.record-{i:03}','runId':runid,'campaignId':c['campaignId'],'roundId':c['roundId'],'bundleFingerprint':c['bundleFingerprint'],'bookDigest':c['bookDigest']}
    for k in ['goalId','goalFingerprint','pageFingerprint','currentTitleDe','currentTitleEn','currentDescriptionDe','currentDescriptionEn']: rec[k] = g[k]
    rec.update(decision='keep', understandingEvidence=dict(zip(keys, ev)), rationale=rat, evidenceProfileContract='positive-understanding-evidence-v2', evidenceProfileRecommendation='create', recordStatus='candidate', reviewAuthority='ai_candidate')
    records.append(rec)
out = OWN / 'results'; out.mkdir()
recfile = out / (b['batchId'] + '.records.jsonl')
recfile.write_text(''.join(json.dumps(v,ensure_ascii=False,separators=(',',':'))+'\n' for v in records))
params = {'reviewer':'independent OpenAI Codex subagent D-A','modelSamplingParameters':'Not separately exposed by orchestration','E7DescriptionsOrProfilesAuthored':False,'otherE7DReviewsRead':False,'actualPDFPhysicalPagesViewed':list(range(1,10)),'actualLoadedHTMLSectionsViewed':7,'actualOriginalPrimaryPagesViewed':{'HE':[35,36,37],'NI':[87],'SL':[25,26],'BWPhysical':[26]},'boundEvidenceProfilesRead':0,'standaloneVApprovalClaim':False,'humanApproval':False,'humanTrial':False,'activeWrites':0}
dump(OWN/'generation-parameters.json', params)
bundle = json.loads((ROUND/'review-bundle-manifest.json').read_text())
run = {'$schema':'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json','schemaVersion':1,'runId':runid,'campaignId':c['campaignId'],'roundId':c['roundId'],'batchId':b['batchId'],'batchInputFingerprint':b['batchInputFingerprint'],'bundleFingerprint':c['bundleFingerprint'],'bookDigest':c['bookDigest'],'provider':'OpenAI Codex','model':'Codex reviewer; exact model identifier not exposed','role':'subject_reviewer','promptFamilyId':'goal-description-understanding-evidence-v2','promptFingerprint':c['promptFingerprint'],'criteriaFingerprint':c['criteriaFingerprint'],'generationParametersFingerprint':'sha256:'+sha(OWN/'generation-parameters.json'),'independenceGroupId':c['independenceGroupId'],'blindToOtherRuns':True,'goalIds':b['goalIds'],'inputArtifacts':[{'role':v['role'],'digest':v['digest']} for v in bundle['artifacts']]+[{'role':'description_review_batch_input_jsonl','digest':b['batchInputFingerprint']}],'startedAt':json.loads((OWN/'preparation-start.actual.json').read_text())['startedAt'],'completedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'completed','outputDigest':'sha256:'+sha(recfile),'toolchainVersion':'goal-description-review-v1'}
dump(out/(b['batchId']+'.run.json'), run)
dump(OWN/'independent-current-findings.json', {'bookDigest':c['bookDigest'],'bundleFingerprint':c['bundleFingerprint'],'keep':7,'openCurrentDFindings':[],'independentDScienceCandidates':7,'unchangedCanonicalDescriptions':7,'newSourceAndPageBindingChecks':7,'activeStrictNetIncrease':0,'boundProfilesActuallyRead':0,'profileRecommendationCreate':7,'HEE4E5CompulsoryClaim':False,'NIandSLFullHETargetCoverageClaim':False,'wholeSourceUmbrellaCompetenciesClaimedClosed':False,'allostericEqualsPureNoncompetitiveClaim':False,'givenLabRecordReplacesActualExperimentClaim':False,'RGTMemoryRequiredOverridden':False,'standaloneVApprovalClaim':False,'humanApproval':False,'humanTrial':False,'activeWrites':0})
print('Independent D-A7: seven KEEP; seven create evidence recommendations; candidates only')
