from pathlib import Path
import json,hashlib
R=Path('/home/enpasos/projects/skillpilot');O=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-thirteen-local-social-state-distribution-Europe-one-contract-author-a-v1';I=next(O.glob('*intake.json'));D=json.loads(I.read_text());B=O/'whole-thirteen-social-Europe-one-contract-two-case-DEEN24-15.DRAFT-author-candidates-v1.json'
def rec(p):z=p.read_bytes();return {'path':str(p.relative_to(R)) if p.is_relative_to(R) else str(p),'sha256':hashlib.sha256(z).hexdigest(),'bytes':len(z)}
def put(n,v):p=O/n;assert not p.exists();p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');return rec(p)
sources=[
 {'url':'https://www.gesetze-im-internet.de/bgb/__439.html','publisher':'Bundesministerium der Justiz / Bundesamt für Justiz','actualAccess':'Browser direct official returned26lines; whole section actually read','actualScope':'Subsections1–6, especially1/2/4 for stipulated claim/repair choice/costs and disproportionate-remedy limit','usedIn':'c7b institutional rule case A','ownBoundedReadingDecision':'Use a stipulated existing claim, not a manufactured statement of all statutory prerequisites. No automatic refund, no risk-free transactions.','fullTextCopiedIntoRepository':False},
 {'url':'https://citizens-initiative.europa.eu/how-it-works_en','publisher':'European Commission','actualAccess':'Browser official whole194line procedure page returned and read','actualScope':'Seven organisers/seven states; million valid statements/national minima; verification, hearing, reasoned response; no automatic proposal or adoption','usedIn':'ab556 citizens initiative','ownBoundedReadingDecision':'Participation milestones are separate from binding law; use fictive900000/1.1million variants. No individual advice or campaign contact.','fullTextCopiedIntoRepository':False},
 {'url':'https://europarl.europa.eu/factsheets/en/sheet/7/the-principle-of-subsidiarity','publisher':'European Parliament','actualAccess':'Actual primary indexed search paragraphs read; direct page output only robot/JavaScript3lines, no full direct text reading claimed','actualScope':'Article5(3) EU Treaty non-exclusive-competence test, inadequate national achievement and scale/effects European added value','usedIn':'79ed subsidiarity','ownBoundedReadingDecision':'This chooses an action level inside conferred power, never manufactures a new power. Proportionality is a separate extent test.','fullTextCopiedIntoRepository':False},
 {'url':'https://commission.europa.eu/about/role/law/areas-eu-action_en','publisher':'European Commission','actualAccess':'Actual primary indexed response paragraphs read, including conferral/proportionality/subsidiarity and competence categories','actualScope':'Conferred powers; proportionality; shared/exclusive domains','usedIn':'79ed norm aid','ownBoundedReadingDecision':'Fictional dossiers explicitly supply the legal basis and practical cross-border conditions. No claim that an actual municipality has the invented powers.','fullTextCopiedIntoRepository':False},
 {'url':'https://european-union.europa.eu/institutions-law-budget/institutions-and-bodies/types-institutions-and-bodies_en','publisher':'European Union','actualAccess':'Actual browser output through229 of236lines; key75–91 read, not claim all unseen footerlines','actualScope':'Commission initiatives/implementation, directly elected Parliament, ministerial Council, European Council political direction; updated21April2026 displayed','usedIn':'8c4d/ab556 authority distinctions','ownBoundedReadingDecision':'European Council is not the ordinary co-legislator. Do not generalise procedural equality to every legal basis.','fullTextCopiedIntoRepository':False},
 {'url':'https://www.consilium.europa.eu/en/council-eu/decision-making/special-legislative-procedures/','publisher':'Council of the European Union','actualAccess':'Actual browser full123line page read','actualScope':'Consultation opinion required but substantively non-binding; indirect-tax harmonisation example; reviewed9April2026','usedIn':'8c4d case B','ownBoundedReadingDecision':'The fictional indirect-tax legal basis selects consultation. Parliament rights cannot be removed at will; general consent procedure not substituted.','fullTextCopiedIntoRepository':False},
 {'url':'https://european-union.europa.eu/principles-countries-history/history-eu/1945-59_en','publisher':'European Union','actualAccess':'Actual browser99line page read','actualScope':'1951Coal/Steel Treaty/1952start;1957Rome/1958EEC; Assembly then not elected directly','usedIn':'8c4d historic case','ownBoundedReadingDecision':'Distinguish signature and commencement, sectoral from broader integration. No identical EU institutions claim since1957.','fullTextCopiedIntoRepository':False},
 {'url':'https://european-union.europa.eu/principles-countries-history/history-eu/1970-79_en','publisher':'European Union','actualAccess':'Actual browser93line page read','actualScope':'1979first direct Parliament elections; previous national parliamentary delegation','usedIn':'8c4d historic case','ownBoundedReadingDecision':'Changing representation does not imply identical lawmaking rights across all fields.','fullTextCopiedIntoRepository':False},
 {'url':'https://european-union.europa.eu/principles-countries-history/history-eu/1990-99_en','publisher':'European Union','actualAccess':'Actual browser output through61 of102lines; scoped40–52 read, no full102line reading claimed','actualScope':'1January1993single market/four freedoms; Maastricht signed1992/entered1993','usedIn':'9ea and8c4d','ownBoundedReadingDecision':'Legal opening is not measured equal benefits or abolition of safety requirements.','fullTextCopiedIntoRepository':False},
 {'url':'https://www.europarl.europa.eu/olp/en/in-the-past/key-milestones','publisher':'European Parliament','actualAccess':'Actual primary indexed paragraphs read; directbrowser3line JavaScript response only','actualScope':'1993Maastricht limited co-decision;2009Lisbon extension/renaming to ordinary legislative procedure including agriculture','usedIn':'8c4d historic requirement','ownBoundedReadingDecision':'Explain actual changes rather than a date-list quota. The direct2000–09history page did not show Lisbon paragraph, and is not cited as read.','fullTextCopiedIntoRepository':False},
 {'url':'https://eur-lex.europa.eu/eli/treaty/tfeu_2016/art_3/oj/eng','publisher':'Official Journal of the European Union / EUR-Lex','actualAccess':'Actual complete Article3 returned as primary indexed search text','actualScope':'Exclusive common commercial policy; no full treaty reading claimed','usedIn':'96c2 distinct trade competence','ownBoundedReadingDecision':'Exclusive EU competence is not Commission-only legislative authority.','fullTextCopiedIntoRepository':False},
 {'url':'https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=OJ%3AC%3A2016%3A202%3AFULL','publisher':'Official Journal of the European Union / EUR-Lex','actualAccess':'Actual primary indexed treaty passages Articles3/4 read; not entirefullOJ PDF reading','actualScope':'Shared agriculture/environment, exclusive common commercial policy','usedIn':'96c2 three-field comparison','ownBoundedReadingDecision':'Use the exact supplied case legal basis. Do not generalise OLP to all possible environmental/trade measures.','fullTextCopiedIntoRepository':False},
 {'url':'https://eur-lex.europa.eu/eli/treaty/tfeu_2016/2024-09-01','publisher':'Official Journal of the European Union / EUR-Lex','actualAccess':'Actual primary indexed treaty Articles288/289 text read; not entireconsolidatedtreaty reading','actualScope':'Regulation directapplicability, directive boundresult/nationalformmethods; ordinaryjointEP/CoEUadoption','usedIn':'8c4d legal acts/procedures','ownBoundedReadingDecision':'Formal adoption and entry into force are distinct. Allconditions of directeffect or litigation are outside the task.','fullTextCopiedIntoRepository':False},
 {'url':'https://www.consilium.europa.eu/en/press/press-releases/2025/12/18/council-signs-off-simplification-of-common-agricultural-policy/','publisher':'Council of the European Union','actualAccess':'Actual English primary indexedpressrelease paragraphs read; independently returneddatedofficialGerman/French counterparts also read','actualScope':'18December2025finalCouncil approval for changes toCAPbasicregulations, CommissionMayproposal andtwo-colegislatoragreement','usedIn':'96c2 actual dated CAP case','ownBoundedReadingDecision':'FinalCouncilapproval follows co-legislativework. Savings estimates do not become measured farm outcomes. No minister quote copied.','fullTextCopiedIntoRepository':False},
 {'url':'https://agriculture.ec.europa.eu/media/news/commission-delivers-further-cap-simplification-eur215-million-farmers-and-national-administrations-2026-01-23_en','publisher':'European Commission DG AGRI','actualAccess':'Actual whole132line browserpage read','actualScope':'Nine23January2026secondaryacts, prior14May2025proposal and31December2025publication; GSApesticideduplication removed/generalrecordkeepingretained; remotelymonitorablequalityconditions','usedIn':'96c2actual2026sourcefollowedbyfictionalS/T','ownBoundedReadingDecision':'Secondary rules remain within powers. Do not erase generalrecords/allconditions or promise actual savings/individualsubsidies. Fictive twelve×two hours is owned teaching data.','fullTextCopiedIntoRepository':False}
]
source=put('actual-fifteen-bounded-current-primary-source-readings-and-honest-access-limits.AUTHOR.json',{'role':'AUTHOR actual scoped primary reading and bounded own paraphrase decisions; foreign verification pending','readAt':'2026-10-10','wholeBody':rec(B),'sources':sources,'actualSourceLocators':len(sources),'browserWholePageVsScopedIndexExplicit':True,'noThirdPartyFullTextArchivedInRepository':True,'failedEPDirectFetch':{'url':'https://www.europarl.europa.eu/news/en/press-room/20251211IPR32163/parliament-endorses-simpler-rules-and-more-support-for-farmers','HTTP':202,'bytes':0,'sha256':'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855','usedAsReadFullSource':False,'sixteenthDecemberDateNotManufacturedInBody':True},'legalScope':'Owned supplied cases; no real claimant/country competence or blanket current-law completeness claim. No full course/GK source approval.','ownScienceKEEP':False})
reuse=[]
for row in D['rows']:
 for s in row['actualProjectionGapAndOriginalWholeClosureMatrix']:
  for m in s['existingWholeMaterialCandidates']:
   if m['actualCompiledCountryEligible'] and m['actualCourseEligible'] and not m['missingWholePrerequisiteIdsInActualProjection']:
    reuse.append({'goalId':row['goalId'],'materialId':m['materialId'],'viewPath':s['actualViewPath'],'jurisdiction':s['actualJurisdiction'],'courseFilters':s['actualCourseFilters'],'wholeNativeClosure':m['actualWholeNativePrerequisiteClosure'],'action':'Propose exact existing qualified material access only; body unchanged and not re-reviewed. Actual append, foreignscope and currentboundScience reuse remain separate.'})
read=put('actual-thirteen-whole-DEEN-contracts-original-P28-read-and-KEEP-first-access-boundaries.AUTHOR.json',{'role':'AUTHOR actual complete13Goal/P28reading and evidence-directed packagechoice, not description review','wholeIntake':rec(I),'wholeBody':rec(B),'actualWholeGoalsRead':13,'actualOriginalPCasesRead':sum(len(r['wholeOriginalPositiveProfileRecord']['profile']['applicationCaseBriefs'])for r in D['rows']),'actualNewMaterials':13,'actualNewCases':26,'actualOriginalMissingLocalOccurrences':D['actualSelectedRouteGapOccurrences'],'earlierMessage188Correction':'A summation error in an interim message was corrected to168; the actual frozen original intake was already168. No historical numbers silently changed.','actualExistingAccessOnlyCandidates':reuse,'actualExistingAccessOnlyScopeOccurrences':len(reuse),'remainingTransferWholeContractLocalGapNeedsNewSmallerMaterial':True,'actualCurrentSourceOrGKCourseClaimsAdded':0,'allExistingQualifiedWholeBodiesKeptExact':True,'sourceReviewRestart':False,'ownScientificOrScopeApproval':False,'strictNewClosures':0,'restoredBindings':0,'humanApprovalReleaseTrial':False})
print(json.dumps({'sources':source,'readReceipt':read},indent=2))
