"""Prepare whole E1/G1 v2 author profiles; source HOLD is explicit dissent."""
from pathlib import Path
from datetime import datetime, timezone
import json

D=Path(__file__).resolve().parent
ROOT=D.parents[6]
materials=json.loads((D/'materials-revision-v2/twenty-whole-goals-forty-complete-DEEN-cases.author-v2.json').read_text())
plans=json.loads((D/'neutral-twenty-current-whole-imageplans.author.json').read_text())['goals']
def p(de,en):return (de,en)
S=[
 ('representation',p('Nahrungsnetze verbinden mehrere Nahrungspfade; Energie wird gerichtet übertragen und als Wärme entwertet. Destruenten nutzen Reste, während biotische Rückkopplung Populationen beeinflusst.','Food webs connect several feeding paths; energy is transferred directionally and dissipated as heat. Decomposers use remains, while biotic feedback affects populations.'),p('Netzfolgen sind bedingte Hypothesen; Energieübergänge sind nicht universal und werden nicht mit Stoffkreisläufen gleichgesetzt.','Web consequences are conditional hypotheses; energy transfers are not universal and must not be equated with matter cycles.'),p('Wiese/Teich; verzweigte direkte Pfade/indirekte Kaskade; unterschiedliche Energieübergänge.','Meadow/pond; branching direct paths/indirect cascade; different energy transfers.')),
 ('concept',p('Pflanzenbau beeinflusst Aufnahme, Wasserverlust und Gastransport im jeweiligen Umweltkontext; Struktur und Funktion werden begründet verknüpft.','Plant structure influences uptake, water loss and gas transport within environmental contexts; structure and function require justified linkage.'),p('Angepasstheit bringt Zielkonflikte; derselbe Bau ist nicht bei jeder Licht-, Wasser- oder Sauerstoffbedingung optimal.','Adaptation involves trade-offs; the same structure is not optimal under every light, water or oxygen condition.'),p('Trocken-/Lichtbedingungen der Blätter gegenüber kurzfristiger Wasseraufnahme und Überschwemmung der Wurzeln.','Dry/light conditions of leaves versus brief water uptake and root flooding.')),
 ('concept',p('Morphologische Bauform und physiologische Regulation sind verschiedene Anpassungsebenen, die Wärme- oder Wasserbilanz im Habitat beeinflussen.','Morphological structure and physiological regulation are distinct levels of adaptation affecting habitat heat or water balance.'),p('Regulation und Bau wirken unter Bedingungen; endotherme Wärmeproduktion und Osmoregulation sind keine allgemeine Höherentwicklung.','Regulation and structure act under conditions; endothermic heat production and osmoregulation imply no general advancement.'),p('Kälte/Wärme und Oberflächenwärmeübertrag gegenüber Trockenheit/Süßwasser und osmotischer Wasserbilanz.','Cold/heat and surface heat transfer versus drought/freshwater and osmotic water balance.')),
 ('representation',p('Dynamische ökologische Modelle verknüpfen Bestände mit Änderungsraten und erklärten Rückkopplungen unter ausdrücklichen Annahmen.','Dynamic ecological models relate abundance to rates of change and explicit feedback under stated assumptions.'),p('Modellkapazität und Gleichgewicht sind bedingt; unterschiedliche Dynamikmodelle lassen Ressourcen, Zufall oder alternative Nahrung unterschiedlich außer Betracht.','Model capacity and equilibrium are conditional; different dynamic models omit resources, chance or alternative food differently.'),p('Generische gemeinsame Kapazitätsmodelle und Umweltänderung; Lotka-Volterra nur explizite quellenspezifische Erweiterung.','Generic shared capacity models and environmental change; Lotka-Volterra only an explicit source-specific extension.')),
 ('modeling',p('Gemeinschaftsschutz setzt an Lebensraum-/Ressourcenfunktionen und Wirkmechanismen an; Schutz, Nutzung und konkrete Risiken brauchen Abwägung.','Community protection addresses habitat/resource functions and mechanisms; protection, use and actual risks require deliberation.'),p('Eine plausible Maßnahme beweist noch keine Stabilisierung; standardisierte vergleichende Kontrolle und Ziel-/Maßstabsgrenzen sind erforderlich.','A plausible measure does not establish stabilization; standardized comparative monitoring and objective/scale limitations are required.'),p('Uferzugang/Laichraum gegenüber Waldnutzung/Habitatkontinuität; Sicherheit und Nutzung variieren.','Bank access/spawning habitat versus woodland use/habitat continuity; safety and use vary.')),
 ('concept',p('Torpor ist regulierte zeitweilige Stoffwechsel-/Temperaturabsenkung; täglicher Torpor und saisonaler Winterschlaf unterscheiden sich in zeitlicher Organisation.','Torpor is regulated temporary metabolic/temperature depression; daily torpor and seasonal hibernation differ in temporal organization.'),p('Absenkung spart laufende Energie, Erwärmung kostet Energie; Dauer, Nahrung und wiederholte Aufwachphasen beeinflussen den Nettoeffekt.','Depression saves continuing energy while rewarming costs energy; duration, food and repeated arousals affect the net result.'),p('Physiologische Zeitreihe mit täglicher/saisonaler Absenkung gegenüber Aktivbleiben und veränderter Aufwachhäufigkeit.','Daily/seasonal physiological depression time series versus remaining active and changing arousal frequency.')),
 ('modeling',p('Der ökologische Fußabdruck bilanziert Flächenäquivalente von Ressourcen-/Aufnahmeanforderungen relativ zur Biokapazität unter Modellannahmen.','The ecological footprint accounts for equivalent areas of resource/absorption demands relative to biocapacity under model assumptions.'),p('Pro-Kopf- und Gesamtbedarf können gegenläufig sein; ein Indikator deckt Biodiversität, Gerechtigkeit und alle Nachhaltigkeitsdimensionen nicht vollständig.','Per-capita and aggregate demand can move differently; one indicator does not fully capture biodiversity, justice and all sustainability dimensions.'),p('Individuelle Maßnahmenbilanz gegenüber wachsender Gemeinde; Zahlenentlastung gegenüber zusätzlichem Habitatschutz.','Individual intervention accounting versus a growing municipality; numerical relief versus additional habitat protection.')),
 ('experiment',p('Eine feldbiologische Ökosystemuntersuchung erfordert tatsächliche eigene Beobachtung/Messung mit passenden Methoden, Rohdaten und eigenständiger Auswertung.','A field ecosystem investigation requires actual personal observation/measurement with suitable methods, raw data and independent analysis.'),p('Stichprobe und Suchaufwand begrenzen Gemeinschaftsaussagen; Beobachtung, begründete Hypothese und Kausalnachweis sind getrennt. Ein Modelltext ersetzt die Durchführung nicht.','Sampling and search effort limit community conclusions; observations, justified hypotheses and causal evidence are distinct. Model text cannot replace performance.'),p('Reale Wiesenquadrate gegenüber zwei sicheren Uferabschnitten; Pflanzen-/Tiernachweise, abiotische Verfahren und Suchaufwand.','Actual meadow quadrats versus two safe banks; plant/animal records, abiotic methods and search effort.')),
 ('concept',p('Bioakkumulation ist zeitliche Anreicherung im Individuum, Biomagnifikation Konzentrationssteigerung über Nahrungsebenen bei geeigneten Stoff-/Bilanzbedingungen.','Bioaccumulation is temporal accumulation within an individual; biomagnification is rising concentration across trophic levels under suitable chemical/accounting conditions.'),p('Konzentration ist keine unmittelbar belegte Schädigung; Ausscheidung/Abbau können Biomagnifikation verhindern, Wirkung braucht eigene Daten.','Concentration does not directly establish injury; elimination/degradation can prevent biomagnification, while effects require separate data.'),p('Persistenter Stoff mit ansteigender Trophiekonzentration gegenüber zeitlich akkumulierender Muschel und fallenden Trophiekonzentrationen.','Persistent chemical with rising trophic concentrations versus a temporally accumulating mussel and declining trophic concentrations.')),
 ('representation',p('Stochastische Modelle verwenden ausdrückliche Übergangswahrscheinlichkeiten und erzeugen verschiedene mögliche Populations-/Belegungsverläufe.','Stochastic models use explicit transition probabilities and produce multiple possible abundance/occupancy trajectories.'),p('Erwartungswert und einzelne Realisation sind getrennt; Unabhängigkeit, Parameter und Vernetzung sind überprüfbare Modellannahmen statt sichere Prognosen.','Expectation and individual realization are distinct; independence, parameters and connectivity are testable assumptions rather than certain forecasts.'),p('Einzelne dokumentierte Zufallsfolge gegenüber Erwartungsvergleich mit/ohne Habitatkorridor und korrelierten Wetterrisiken.','One documented random sequence versus expected outcomes with/without a corridor and correlated weather risks.')),
 ('modeling',p('r-/K-Strategien sind idealisierte Lebenszyklus-Merkmalskombinationen, deren Nutzen von Störung, freien Ressourcen und Konkurrenz abhängt.','r/K strategies are idealized combinations of life-cycle traits whose benefits depend on disturbance, free resources and competition.'),p('Nachkommenzahl, Einzelinvestition und Überleben bilden Zielkonflikte; Keimrate allein und binäre Kategorien bestimmen keine allgemeine Gesamtfitness.','Offspring number, individual investment and survival trade off; germination alone and binary categories do not determine universal total fitness.'),p('Gepflegte/wenig gepflegte Nachkommen bei gestörtem/stabilem Habitat gegenüber Samen-/Überlebensstrategien in offenen/dichten Beständen.','High/low offspring care under disturbed/stable habitat versus seed/survival strategies in open/crowded vegetation.')),
 ('representation',p('Fitnesskurven ordnen einem Merkmal bedingten reproduktiven Erfolg zu; relative Fitness und definierter Selektionskoeffizient quantifizieren Benachteiligung.','Fitness curves assign conditional reproductive success to a trait; relative fitness and a defined selection coefficient quantify disadvantage.'),p('Kurve ist keine Häufigkeitsverteilung; geändertes Umfeld verändert den Selektionsdruck, sichere Artbildung oder Individuenumbildung folgt daraus nicht.','A curve is not a frequency distribution; changed environment alters selection pressure but does not imply certain speciation or individual transformation.'),p('Mittleres Optimum gegenüber zwei Extremen und anschließend gerichteter Kurve; verschiedene relative Koeffizienten.','Central optimum versus two extremes and then a directional curve; different relative coefficients.')),
 ('concept',p('Balz, Territorialität und Kooperation können durch kontextspezifischen Überlebens-/Fortpflanzungsnutzen bei Energie-/Risikokosten erklärt werden.','Courtship, territoriality and cooperation may be explained through context-specific survival/reproductive benefits and energy/risk costs.'),p('Funktionale Fitnessdeutung setzt keine bewusste Evolutionsabsicht oder ungeprüfte Verwandtenselektion voraus; knappe Ressourcen ändern Nutzen/Kosten.','Functional fitness interpretation assumes neither deliberate evolutionary purpose nor untested kin selection; scarce resources alter benefits/costs.'),p('Vogelrufe/Wachsamkeit gegenüber Fischfarben, Territorien und gemeinsamer Jagd bei Knappheit.','Bird calls/vigilance versus fish colours, territories and joint hunting under scarcity.')),
 ('modeling',p('Klima beeinflusst geeignete Habitate, Ausbreitung und zeitliche Interaktionen; Artenreaktionen wirken über Beziehungen auf Ökosysteme.','Climate affects suitable habitats, dispersal and temporal interactions; species responses affect ecosystems through relationships.'),p('Ein Szenario begründet bedingte Risiken und Maßnahmen, keinen empirischen Einzelursachennachweis oder unvermeidlichen Verlust jeder Art.','A scenario supports conditional risks and measures, not empirical single-cause evidence or inevitable loss of every species.'),p('Gebirgshabitat mit begrenztem Gipfelraum gegenüber verschobenen Blüten-/Bestäuberzeitfenstern und Wasserknappheit.','Mountain habitat with limited summit space versus shifted flower/pollinator timing and water scarcity.')),
 ('modeling',p('Renaturierung behebt Habitatursachen; Wiederansiedlung ist ein zusätzlicher begründeter Schritt mit geeigneter Herkunft, Zuständigkeit und Risiken.','Restoration addresses habitat causes; reintroduction is an additional justified step requiring suitable origin, authority and risk assessment.'),p('Ausgesetzte Individuen beweisen keine funktionsfähige Gemeinschaft; Habitatkontinuität, natürliche Besiedlung und längerfristige Reproduktion brauchen Kontrolle.','Released individuals do not establish a functional community; habitat continuity, natural colonization and long-term reproduction require monitoring.'),p('Teich-/Straßenbarriere und Laichhabitat gegenüber Altbaum-/Totholzkontinuität und verzögerter Waldentwicklung.','Pond/road barrier and spawning habitat versus old-tree/dead-wood continuity and delayed woodland development.')),
 ('modeling',p('Ökosystemleistungen umfassen unterschiedliche Nutzenkategorien; monetäre Bilanzgrenzen und ökologische Funktionen müssen explizit erfasst werden.','Ecosystem services include different benefit categories; monetary accounting boundaries and ecological functions require explicit assessment.'),p('Doppelzählung, unbekannte Geldwerte und nicht ersetzbare Artenwerte begrenzen ökonomische Vergleiche; ökologische Bewertung bleibt erforderlich.','Double counting, unknown monetary values and irreplaceable species values limit economic comparisons; ecological assessment remains necessary.'),p('Feuchtgebiet mit Wasser-/Hochwasser-/Erholungsleistungen gegenüber Bestäubung/Ernte und Habitatverbindung.','Wetland purification/flood/recreation services versus pollination/crops and habitat links.')),
 ('representation',p('Quellen haben positive, Senken negative lokale demografische Bilanz; Migration und Kolonisation verbinden geeignete Habitatteilpopulationen.','Sources have positive and sinks negative local demographic balance; migration and colonization connect suitable habitat populations.'),p('Belegung und Einwanderungszunahme allein definieren keine Quelle; homogenisierte Anteilmodelle lassen lokale Qualitätsunterschiede außer Betracht.','Occupancy and immigration-driven increase alone do not define a source; homogeneous fraction models omit local quality differences.'),p('Lokale Geburts-/Sterbe-/Migrationsbilanz gegenüber homogenisiertem Kolonisations-Aussterbe-Anteilmodell mit Barriere.','Local birth/death/migration accounting versus homogeneous colonization/extinction fraction model with a barrier.')),
 ('representation',p('Nichtlineare Rückkopplung kann abrupte Ökosystem-Zustandswechsel und unterschiedliche Hin-/Rückschwellen erzeugen.','Nonlinear feedback can create abrupt ecosystem state changes and different forward/return thresholds.'),p('Ein Sprung oder Foto allein beweist keinen Kipppunkt; Mechanismus, Verlauf und alternative Ursachen bestimmen Diagnose und vorsorgliches Management.','A jump or photograph alone establishes no tipping point; mechanism, trajectory and alternative causes inform diagnosis and precautionary management.'),p('Synthetische See-Hysterese durch Nährstofflast gegenüber Trockenheit/Feuer im Wald und stetigem Vergleichsverlauf.','Synthetic lake hysteresis from nutrient loading versus woodland drought/fire and a gradual comparison trajectory.')),
 ('modeling',p('Szenarien sind bedingte Annahmen; Managementvergleich benötigt vergleichbare Kriterien, Budget, Prioritäten und Unsicherheitsbehandlung.','Scenarios are conditional assumptions; management comparison requires comparable criteria, budget, priorities and treatment of uncertainty.'),p('Robuste und billigste Optionen können auseinanderfallen; adaptive Entscheidungen brauchen überprüfbare Auslöser und tatsächlich verfügbare Mittel.','Robust and cheapest options may differ; adaptive decisions require testable triggers and actually available resources.'),p('Zwei Klimaumfelder mit Minimax-/Kostenabwägung gegenüber Landnutzung, Budgetgrenze und stufenweiser Nachsteuerung.','Two climate settings with minimax/cost deliberation versus land use, budget limit and staged adjustment.')),
 ('concept',p('Resilienzbewertung benötigt definierte Funktion, Störung und Zeithorizont; unmittelbarer Widerstand und spätere Wiedererholung sind getrennte Aspekte.','Resilience assessment needs defined function, disturbance and time horizon; immediate resistance and subsequent recovery are distinct aspects.'),p('Hohe Ausgangsfunktion garantiert keine Erholung zwischen Störungen; Regenerationsbedingungen und Belastungsreduktion bestimmen Management.','High baseline function does not guarantee recovery between disturbances; regeneration conditions and reduced pressure inform management.'),p('Einmalige gleich starke Störung mit Resistenz-/Erholungsunterschied gegenüber wiederholter Trockenheit und Funktionsverlust.','One equal disturbance with resistance/recovery differences versus recurring drought and functional loss.')),
]
assert len(S)==20
HOLD={9,10,12,15,17,18,19,20}
review_id='biologie-ecology20b-current391-positive-author-v1'
candidates={'schemaVersion':1,'authoringContract':'positive-understanding-evidence-candidates-v1','reviewId':review_id,'reviewedAt':datetime.now(timezone.utc).isoformat().replace('+00:00','Z'),'reviewer':'Codex ecology20b material author; model family GPT-6, exact serving revision unavailable','goals':[]}
for n,(item,s,plan) in enumerate(zip(materials['goals'],S,plans),1):
    archetype,core,transfer,variation=s
    ex=[]
    for suffix,u,c in [('core',core,item['cases'][0]),('transfer',transfer,item['cases'][1])]:
        ex.append({'id':f'ecology20b-{n:02d}-{suffix}','essentialUnderstandingDe':u[0],'essentialUnderstandingEn':u[1],'observablePerformanceDe':c['task']['de'],'observablePerformanceEn':c['task']['en']})
    briefs=[]
    for c in item['cases']:
        briefs.append({'id':c['id'],'taskDemandDe':c['material']['de']+' '+c['task']['de'],'taskDemandEn':c['material']['en']+' '+c['task']['en'],'expectedPerformanceDe':c['modelAnswer']['de'],'expectedPerformanceEn':c['modelAnswer']['en'],'understandingFocusDe':core[0]+' '+transfer[0],'understandingFocusEn':core[1]+' '+transfer[1]})
    if n==4:
        c=item['courseBoundConditionalExtension']['wholeConditionalCase']
        briefs.append({'id':'ecology20b-04-by-ea-lotka-volterra-extension','taskDemandDe':'Nur im tatsächlich belegten BY13-EA-Quellenteil4.1, keine gemeinsame GK-Pflicht: '+c['material']['de']+' '+c['task']['de'],'taskDemandEn':'Only under the actually supported BY13 EA source passage4.1, no common basic-course obligation: '+c['material']['en']+' '+c['task']['en'],'expectedPerformanceDe':c['modelAnswer']['de'],'expectedPerformanceEn':c['modelAnswer']['en'],'understandingFocusDe':'Kursbedingte Lotka-Volterra-Erweiterung: vier Terme, positives Gleichgewicht, phasenverschobene Räuber/Beute und idealisierte Modellgrenzen. Die beiden gemeinsamen Modellfälle bleiben separat vollständig.','understandingFocusEn':'Course-bound Lotka-Volterra extension: four terms, positive equilibrium, phase-lagged predators/prey and idealized limitations. Both shared model cases remain separately complete.'})
    dissent=['E1/G1-Autorkandidat mit eigenen Modellmaterialien; keine reale Lernendenleistung, E2, menschliche Prüfung, Freigabe oder Erprobung. Tatsächliche finale Rasterbindungen und zwei unabhängige aktuelle D/P/V-Prüfungen stehen aus.',plan['sourceBoundary']]
    if n in HOLD:
        dissent.append('SOURCE-HOLD: Die ganze aktuelle Zielpflicht ist durch die tatsächlich gelesenen amtlichen HE/BY-Komponenten und gezielt gesuchten NI/NW/BB/BE/TH/SN-Primärteile nicht gültig belegt. Kein strenger D/P/M7-Abschluss bis Auflösung; wissenschaftlich sinnvolle eigene Modelle sind keine Curriculum-Pflichtquelle.')
    if n==8:
        dissent.append('Tatsächliche eigene Felduntersuchung mit Rohbefunden und eigener Auswertung bleibt verpflichtend; Planung, Modellwerte und Mustertext ersetzen sie nicht. Qualitativ gemeinsame Aufgaben, quantitative Pflicht nur in zutreffenden LK/EA-Quellenteilen.')
    if n==4:
        dissent.append('Gemeinsame zwei Modellfälle prüfen generische Dynamik, Kapazität und Grenzen. Lotka-Volterra ist eine separat bedingte BY-EA-Erweiterung; keine unvermerkte HE-GK-Pflicht oder universelle Q4.2-Pflicht.')
    profile={'archetype':archetype,'expectations':ex,'coverageExpectations':{'requiredExpectationIds':[e['id'] for e in ex],'alternativeExpectationGroups':[],'minimumIndependentDemonstrations':2,'freshVariationRequired':True,'independentTransferRequired':True},'variationAxes':[{'id':f'ecology20b-{n:02d}-context-and-mechanism','textDe':variation[0],'textEn':variation[1]}],'applicationCaseBriefs':briefs}
    candidates['goals'].append({'goalId':item['goalId'],'reason':'Ganze unveränderte aktuelle DE/EN-Zielbeschreibung mit zwei vollständigen unterschiedlichen Material-/Musterfällen operationalisiert. Kandidat für gezielte unabhängige wissenschaftliche Prüfung, keine Freigabe; konkrete offene Quellenfacetten werden ausdrücklich nicht als Abschluss gezählt.','evidenceLevel':'E1','maximumClaimScope':'G1','dissent':dissent,'profile':profile})
p=D/'P20.current-text-preimage.author.candidates.json';assert not p.exists();p.write_text(json.dumps(candidates,ensure_ascii=False,indent=2)+'\n')
cfg={'$schema':'https://skillpilot.com/schemas/goal-evidence/v2/goal-evidence-review-config.schema.json','schemaVersion':2,'reviewId':review_id,'goalFingerprintRuleVersion':'goal-evidence-v1','profileRuleVersion':'positive-understanding-evidence-v2','landscapeId':'08a43a1b-d97e-522c-9dfa-c950a493364e','landscapePath':'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_BIOLOGIE.de.json','semanticKindLedgerPath':'curricula/DE/Gymnasium/quality/goal-book-publication/biologie.semantic-kinds.json','reviewCriteriaPath':'curricula/DE/Gymnasium/quality/goal-evidence/prompts/biology-positive-understanding-evidence-profile-criteria-v1.md','reviewPath':str(D.relative_to(ROOT)/'P20.current-text-preimage.author.review.jsonl'),'reviewRunManifestPaths':[],'reviewedResourceTypes':['goal-visualization'],'requireApproved':False,'scope':{'label':'20 exact current whole ecological author profiles; 8 explicit source HOLDs, no strict completion claim','goalIds':[i['goalId'] for i in materials['goals']]}}
p=D/'P20.current-text-preimage.author.config.json';assert not p.exists();p.write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'wholeProfiles':20,'bilingualCases':40,'sourceHoldOrdinals':sorted(HOLD),'eligibleToSeekIndependentApprovalOnly':12,'newStrictClosure':0,'activeWrites':0}))
