"""Own current-ID author candidates. No active writes or scientific approval."""
from pathlib import Path
import hashlib, json

D = Path(__file__).resolve().parent
ROOT = D.parents[6]
def read(p): return json.loads((ROOT / p).read_text())
def bind(p):
    b = (ROOT / p).read_bytes()
    return {"path": str(p), "sha256": hashlib.sha256(b).hexdigest(), "bytes": len(b)}
def write(name, data):
    p = D / name
    assert not p.exists(), p
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")

CP = 'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_BIOLOGIE.de.json'
RP = 'curricula/DE/Gymnasium/quality/deep-understanding-rollout/de-gymnasium-math-physics.config.json'
KP = 'curricula/DE/Gymnasium/quality/goal-book-publication/biologie.semantic-kinds.json'
REPORT = 'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-07/biologie-ecology20-reviewed-active-integration-root-v1/active-after-ecology20-central.actual.json'
canon = read(CP)
report = next(x for x in read(REPORT)['subjects'] if x['subject'] == 'biologie')
subject = next(x for x in read(RP)['subjects'] if x['subject'] == 'biologie')
kinds = {x['goalId']: x for x in read(KP)['decisions']}
prefixes = 'ea5d75af 5ef8ffbf 5bfb8ede 52d195f7 914fb22b 4c037a86 68bb29c8 ac4a650d de1c19a2 691b0711 e6120e08 eccf935c 258218b2 ca6d4912 7749de90 25eaa5cf 4ef85d98 f36a52b8 64a31f9a b7b84b6a'.split()
goals = [next(g for g in canon['goals'] if g['id'].startswith(p)) for p in prefixes]
ids = [g['id'] for g in goals]
all_indexed = {r['goalId'] for p in subject['resolutionIndexPaths'] for r in read(p)['resolutions']}
all_p = {g for p in subject['positiveEvidenceConfigPaths'] for g in read(p)['scope']['goalIds']}
assert len(goals) == 20 and len(canon['goals']) == 474 and report['denominator'] == 391 and report['strictComplete'] == 120
assert not (set(ids) & set(report['strictCompleteGoalIds']))
assert not (set(ids) & all_indexed), 'Never restart valid or already indexed historical D reviews'
assert not (set(ids) & all_p), 'Never restart indexed P profiles'
assert not (set(ids) & {'05358518-f66c-5c1b-ad3f-d16211d0fc1c','9f73b963-5fac-5a90-a993-d7b7c0cc8526'})
for g in goals:
    assert kinds[g['id']]['semanticKind'] == 'curricularAtomic'
    assert not any(r.get('type') == 'goal-visualization' for r in g.get('resourceLinks', []))

write('current20-whole-DEEN-goals.actual.json', {'schemaVersion':1, 'artifactKind':'current-whole-author-input', 'baselineCanonical':bind(CP),'currentReport':bind(REPORT),'goals':goals})
write('current20-selection-and-no-restart.actual.json', {'schemaVersion':1,'artifactKind':'current-ID-gap-selection','baselineCanonical':bind(CP),'registry':bind(RP),'currentReport':bind(REPORT),'currentWholeGoalCount':474,'currentCurricularAtomic':391,'strictCurrentComplete':120,'selectedGoalIds':ids,'selectedStrictIncomplete':20,'selectedNeverInActiveDescriptionIndex':20,'selectedNeverInActivePConfig':20,'selectedWithoutExistingGoalImage':20,'retainedValidStrictGoals':120,'P2AndEcology20Excluded':True,'activeWrites':0,'newStrictClosuresClaimed':0,'humanApproval':False})

# Exact goal fields precede neutral imagery. Diagram details are bounded models,
# never purported official observations, learner performance or release approval.
visuals = [
 ('Verzweigtes freundlich-comicartiges Wiesennahrungsnetz: Gras→Heuschrecke→Frosch→Storch und Gras→Maus→Storch. Wenige klare Pfeile von Nahrung zu Verbraucher. Sonne speist Gras; seitliche Wärmeabgabe an jeder Ebene, niemals Energie-Rückkreislauf. Kleine zeitlich versetzte Miniwellen für Räuber/Beute als Modell, ohne behauptete echte Bestandszahlen.', 'Nahrungsnetz, gerichteter Energiefluss und bedingte Populationswechselwirkungen; keine universelle zehnprozentige Effizienz.', 'HE Q3.1 GK/LK und BY13 GA/EA 4.1: Netz/Energie; Populationsphasen BY13 GA/EA, idealisierte HE Populationsmodelle nur LK.'),
 ('Zwei große Querschnitte comicartiger Pflanzenblätter: trockenes Umfeld mit schmalem/gerolltem Blatt, dicker Cuticula und geschützter Blattunterseite; feuchtes Umfeld mit größerer dünnerer Blattfläche. Sichtbare Wurzeln, Sonnen- und Wassersymbole. Struktur mit Funktion verbinden; keine spontane willentliche Umbildung, keine Universalbehauptung, keine unmöglichen Blattgewebe.', 'Strukturelle Angepasstheiten beeinflussen Wasserverlust und Aufnahme; Bedingungen und Zielkonflikte.', 'HE Q3.2 mesophyter Blattaufbau und Q3.3 Wasserhaushalt als begrenzte Komponenten; alle möglichen Anpassungsformen werden nicht als wortgetreu vorgeschriebener Quellenumfang behauptet.'),
 ('Zwei freundliche schematische Säugetiere als vergleichendes Modell: kompakter Körper mit kleiner exponierter Ohrfläche im kalten Umfeld; größere dünne Ohren mit sichtbarer Oberflächendurchblutung im warmen Umfeld. Haupttier zusätzlich kleine symbolische Stoffwechsel-Wärmequelle innen. Morphologische Form und physiologische Regulation klar getrennt; keine starre Bergmann/Allen-Ausnahmefreiheit.', 'Körperform und physiologische Thermoregulation sind verschiedene Arten von Angepasstheit.', 'HE Q3.3 Ektothermie/Endothermie GK/LK; Strukturbeispiele sind eigene begrenzte didaktische Anwendungen.'),
 ('Große gut lesbare schematische Räuber-Beute-Zeitkurven im freundlichen Landschaftsrahmen: Beutekurve steigt zuerst, Räuberkurve erreicht Gipfel später; abfallende Phase folgt. Zwei eindeutig verschiedenfarbige Linien mit direkt sichtbaren Tier-Symbolen, Achsen Zeit und Bestand groß. Seitlich sehr kleine symbolische Grenze: Einwirkung von Wetter/Nahrungsänderung. Kein behauptetes exaktes reales Gleichgewicht oder synchroner Gipfel.', 'Lotka-Volterra ist ein idealisiertes dynamisches Modell mit phasenverschobenen Populationen und Grenzen.', 'BY13 EA 4.1 nennt Lotka-Volterra, GA nicht; HE Q4.2 nennt Sukzession, kein wörtliches universelles Lotka-Volterra-Pflichtmodell. Kurs-/Quellenteilgrenzen erhalten.'),
 ('Ein comicartiges Flussufer mit zwei übersichtlich verglichenen Managementwegen: durchgehende Betonwand versus schmaler sicherer Zugang plus breiter naturnaher Uferstreifen. Fische, Insekten und Uferpflanzen bekommen zusammenhängende Rückzugsbereiche. Großes Beobachtungs-/Kontrollsymbol am geschützten Weg, keine garantierte Erfolgsstempel. Keine naive Forderung Menschen ganz auszusperren.', 'Gemeinschaftsschutz beruht auf Wirkmechanismen, Abwägung und Erfolgskontrolle.', 'HE Q4.1 GK/LK, BY13 GA/EA 4.2; eigenständige Szenarien statt vorgespiegelter Maßnahmenwirksamkeit.'),
 ('Freundliche abstrakte Kleinsäuger-Darstellung: links kurze tägliche Torporphase in schützendem Schlafplatz mit kleiner Stoffwechsel-/Temperaturabsenkung, rechts Winterschlaf über längere kalte Jahreszeit mit unterbrochenem Zeitband für Aufwachphasen. Ein deutlicher Schwerpunkt auf energiesparender regulierter Absenkung. Nicht einfach Schlafen, nicht Körpertemperatur dauerhaft exakt Außentemperatur, keine tote Tierpose.', 'Torpor und Winterschlaf sind regulierte zeitlich verschieden organisierte Energiesparzustände.', 'HE Q3.3 LK explizit; keine pauschale GK- oder BY-Pflichtbehauptung.'),
 ('Ein sehr großer freundlicher Fußabdruck aus drei groben Teilflächen für Ernährung, Mobilität und Wohnen steht einer grünen regenerierenden Flächensymbolik gegenüber. Daneben zwei Handlungssymbole Fahrrad und pflanzenreicher Einkauf. Kein CO2-Fußabdruck als alleinige identische Messgröße, kein Fantasiewert mit echter Datenbehauptung, keine exakte Geldgleichsetzung.', 'Ökologischer Fußabdruck vergleicht Ressourcen-/Aufnahmeanforderungen mit Biokapazität und hat begrenzte Aussagekraft.', 'HE Q4.1 LK und BY13 EA 4.2 nennen Fußabdruck; BY13 GA Nachhaltigkeitsbezug nur Komponente.'),
 ('Freundliche Person untersucht auf einem sicheren erlaubten Wiesentransekt drei kleine markierte Quadrate. Lupe, Thermometer und Heft sichtbar; Heft orientiert zum Schreibenden, korrekt gehalten. Arten nur beobachten, keine Pflanzen ausreißen, keine Tiere freisetzen. Vergleichbare Messpunkte und anschließende einfache eigene Tabelle ohne erfundene Zahlen. Bild zeigt Arbeitsweise, nicht angeblich bereits absolvierte Leistung.', 'Feldbiologische Durchführung, eigene Rohdaten und Auswertung sind zwingend; eine Modellgrafik ersetzt die Untersuchung nicht.', 'HE Q3.1 qualitative Erfassung GK/LK, quantitative LK; BY13 GA qualitativ, EA quantitativ. Pflicht zur echten Durchführung bleibt in Aufgabe/Profil.'),
 ('Ein klarer zweigeteilter comicartiger See: links ein einzelner Fisch sammelt über die Zeit persistente farbige Schadstoffpunkte aus Nahrung; rechts eine Nahrungskette kleine Wasserorganismen→kleiner Fisch→Raubfisch mit zunehmender Punktdichte pro vergleichbarer Gewebefläche. Beschriftungen nur Bioakkumulation/Biomagnifikation groß. Nicht jeder beliebige Stoff oder jede Kette zeigt dies; keine fantastische Gefahrenpose.', 'Zeitliche Anreicherung im Individuum und Konzentrationssteigerung über Trophieebenen sind getrennt.', 'BY13 EA 4.3 anthropogene Stoffe als Komponente; HE Q4.1 LK hormonartige Substanzen als Komponente. Allgemeine Biomagnifikation wird nicht fälschlich als wortgetreue Gesamtabdeckung freigegeben.'),
 ('Vier freundliche räumlich getrennte Lebensraumpatches mit je bewohntem/unbewohntem Zustand. Kleine Würfelsymbole neben klaren verschiedenen möglichen nächsten Zuständen, Pfeile für Kolonisation und lokales Aussterben. Zwei mögliche Zukunftspfade, kein einziges vorherbestimmtes Ergebnis und keine Quelle/Senke fälschlich aus Belegung allein. Einfaches stochastisches Modell bleibt als schematisch erkennbar.', 'Wahrscheinlichkeitsmodelle bilden mehrere mögliche Populationsverläufe ab, kein deterministisches Zukunftsversprechen.', 'Allgemeine Quellen Populationsdynamik/Management sind nur Komponenten; Metapopulationsstochastik nicht als ausdrücklich vorgeschriebener Vollumfang von HE/BY erfunden.'),
 ('Zwei freundliche Modellorganismen mit kontrastierenden Lebenszyklen: viele kleine Nachkommen/geringe Einzelinvestition und wenige größere Nachkommen/mehr Pflege. Unvorhersehbar gestörte offene Fläche versus stabilere dicht besiedelte Fläche im Hintergrund. Nicht als starre gute/schlechte oder unveränderliche binäre Artenklassen; kein Tier mit unrealistischen Schwangerschaftsdetails.', 'r/K sind idealisierte Kontinua; Lebenszyklusmerkmale und Umweltbedingungen müssen gemeinsam gewichtet werden.', 'HE Q3.1 LK und BY13 EA 4.1 Fortpflanzungsstrategien; GA ausdrücklich nicht pauschal mit LK-Anforderungen verbinden.'),
 ('Freundliche Käfer vor einer großen klaren Fitnesskurve: x=Merkmal, y=relative Fitness, drei sichtbare Größenklassen und ein deutlich höchstes Optimum in gegebenem Modellumfeld. Zweite kleinere farbig klar verschiedene Umweltkurve als Vergleich. Fitness ist Fortpflanzungserfolg, keine Körperkraft- oder Bestandszahlkurve; keine extrem winzige Formelschrift.', 'Fitnesskurven beziehen phänotypabhängigen Fortpflanzungserfolg auf ein definiertes Umfeld; Selektionsdruck wird relativ zum Maximum gemessen.', 'BY12 GA Evolution/Fitness trägt begrenzten Grundbegriff; exakte Kurven-/Quantifizierungspflicht ist im tatsächlichen HE/BY-Auszug nicht belegt und bleibt Quellenkomponenten-HOLD.'),
 ('Drei klar getrennte freundliche Vogelszenen in einem ruhigen Gesamtbild: Balz mit Empfängerentscheidung, Territorialität mit Abstand statt gefährlichem Kampf, gemeinschaftliche Wachsamkeit/Jungenpflege. Pfeile auf Nachkommen-/Überlebenssymbole, daneben kleines Energieaufwand-Symbol. Verhalten nicht als bewusste Evolution oder moralisch altruistische Absicht.', 'Balz, Territorialität und Kooperation werden über Nutzen, Kosten und reproduktive Fitness gedeutet.', 'BY12 GA Verhaltensökologie 4.2 tatsächliche Kooperation/Aggression/Fortpflanzung; keine vollständige neue Methodenpflicht als schon erfüllte Leistung behaupten.'),
 ('Comicartiges Gebirge mit drei breiten Höhenzonen: geeigneter Temperaturraum verlagert sich aufwärts, zusammenhängender Wald wird oben kleiner und endet am Gipfel; eine Art hat begrenzten Fluchtraum. Zweiter deutlicher Phenologiehinweis mit Blüte und Insekt bei versetzten Zeitfenstern. Kein pauschaler sicherer Verlust jeder Art, keine Ursache aus einem Einzelbild als empirisch bewiesen.', 'Klimaveränderung beeinflusst Habitate, zeitliche Beziehungen und Biodiversität mit artspezifischen Grenzen.', 'HE Q4.1 und BY13 GA/EA 4.2 anthropogener Treibhauseffekt/Management; regionale Szenarien sind eigene Modelle.'),
 ('Freundlicher Fluss mit wiederhergestellter Ufervegetation und durchgängiger sicherer Verbindung zu einem Nebenarm; rechts getrennte kleine Wiederansiedlungs-Szene nur nach geeignetem Habitat, fachlicher Genehmigung und Prüfung. Priorität Ursache beheben→Habitat prüfen→Monitoring; keine Tiere einfach aus Eimer aussetzen. Keine garantierte Populationserholung.', 'Renaturierung schafft Bedingungen; Wiederansiedlung braucht Eignung, Herkunft, Zuständigkeit und Kontrolle.', 'HE Q4.1/BY13 4.2 Renaturierungskomponente; konkrete Wiederansiedlungsplanung ist eigenes bounded Modell und keine behauptete tatsächliche Durchführung.'),
 ('Ein freundliches Feuchtgebiet mit vier großen klaren Symbolen: Wasserreinigung, Hochwasserrückhalt, nachhaltiger Rohstoffbezug und Erholung. Doppelte Waage mit Geldsymbol auf einer Seite und Biodiversitäts-/Eigenwertsymbol auf der anderen; kein Alles-hat-einen-Preis oder doppelte monetäre Addition identischer Leistungen. Platz und Hauptmotiv vor Beschriftungen.', 'Ökosystemleistungen werden erfasst und monetäre Ansätze neben ökologischen Kriterien begrenzt bewertet.', 'BY13 GA/EA 4.2 Ökosystemleistungen und Monetarisierungsgrenzen, HE Q4.1 Managementkomponente.'),
 ('Drei räumliche Habitatinseln: gute grüne Quelle mit sichtbarem lokalem Nachwuchsüberschuss sendet Individuen über eine Verbindung zur roten Senke, deren lokale Verluste größer als Nachwuchs sind; dritte leere geeignete Insel wird kolonisiert. Eindeutige Pfeilrichtungen, keine Quellen/Senken nur nach Farbe oder Belegung definieren, kein geschlossener geographischer Kreislauf.', 'Lokale Reproduktion minus Verluste trennt Quelle/Senke; Migration erhält Senke und ermöglicht Kolonisation.', 'Allgemeine Populationsdynamik/Management als Quellenkomponenten; exakte Metapopulations-/Quelle-Senke-Pflicht im gelesenen HE/BY-Ausschnitt nicht behauptet.'),
 ('Zwei große Seezustände klar versus trüb in freundlichem comicartigem Vergleich. Rechts trüber Zustand mit weniger Unterwasserpflanzen; Rückpfeil mit stärker verringerter äußerer Nährstofflast symbolisiert schwierigen Rückweg. Eine klare Grenze/Knickmarkierung und positive Rückkopplung schematisch, keine einzelne Messung beweist Kipppunkt; keine universell echte Schwellenzahl.', 'Kipppunkte und Rückkopplung können Zustandswechsel/Hysterese erzeugen; Management setzt früh an und überprüft Daten.', 'HE/BY Ökosystemmanagement nur Komponentenbezug; kein wörtlich amtliches Kipppunkt-Gesamtpflichtziel belegt.'),
 ('Zwei große verständliche Zukunftsrahmen derselben Landschaft: warm/trocken versus weniger trocken, darin jeweilige Schutzoptionen breiter Uferpuffer und Habitatverbindung. Kleine einfache Kriterienwaage mit Kosten, Artenvielfalt und Wirksamkeit; kein eindeutiger Sieg ohne Daten, keine Wettervorhersage als Tatsache. Sichtbare gleiche Ausgangslandschaft ermöglicht echten Vergleich.', 'Szenarien sind bedingte Annahmen und zeigen robuste versus empfindliche Managemententscheidungen.', 'HE Q4.1/BY13 4.2 Management/Abwägung tragen Komponenten; quantitative Szenariomethode eigenständiges Material, keine Ganzquellen-Freigabe.'),
 ('Zwei freundliche schematische Ökosystemverläufe nach gleichem Sturm: diverse bewachsene Fläche erholt Funktionen schneller, vereinfachte Fläche langsamer. Gleicher Vorzustand und gleiche Störung klar, Zeitband und Funktionssymbol statt Artenzahlgleichsetzung. Unterschied zwischen Widerstand während Störung und Wiedererholung danach; keine pauschale Garantie durch Vielfalt.', 'Resistenz und Erholung nach Störung unterscheiden sich; Resilienz umfasst Funktionserhalt/Wiederaufbau unter klaren Kriterien.', 'Allgemeine ökologische Management-/Biodiversitätsquellen tragen Komponenten; der formale Resilienzvollumfang bleibt source-HOLD, nicht falsch freigegeben.')
]
assert len(visuals) == 20
plans = []
for i, (g, (scene, meaning, scope)) in enumerate(zip(goals, visuals), 1):
    plans.append({'ordinal':i,'goalId':g['id'],'wholeGoal':g,'status':'author_neutral_candidate_no_approval','existingImageDecision':'No current goal image exists; create necessary raster candidate, no KEEP asset replaced.','conceptAndOperator':meaning,'sourceBoundary':scope,'scenePlanDe':scene,'format':{'fileFormat':'PNG','aspectRatio':'approximately 16:9','preferredNativePixels':[1672,941],'verifyActualWidths':[360,680],'style':'friendly abstract clear comic illustration; match existing biology images','labels':'few short large correct German labels only; no reading-dependent small text'},'perspective':'Notebook/measurement interfaces must face the acting person, not a reversed observer-only readable arrangement.','generationIsNotApproval':True,'humanApproval':False,'realLearnerPerformanceClaimed':False,'scientificWholeGoalTextChanged':False,'requiredCopyTargetsAfterPairedApproval':['curricula/DE/Gymnasium/visualizations/biologie/'+g['id']+'/'+g['id']+'.png','app/public/assets/goal-visualizations/biologie/'+g['id']+'/'+g['id']+'.png','backend/src/main/resources/static/assets/goal-visualizations/biologie/'+g['id']+'/'+g['id']+'.png']})
write('neutral-twenty-current-whole-imageplans.author.json',{'schemaVersion':1,'artifactKind':'neutral-author-image-plan','currentBaseline':bind(CP),'strictReport':bind(REPORT),'goals':plans,'activeWrites':0,'newStrictClosuresClaimed':0,'scientificTextChanges':0,'humanApproval':False})
write('native20.neutral.batch.config.json',{'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-rollout-batch-config.schema.json','schemaVersion':1,'batchId':D.name+'-20261007','subject':'biologie','subjectLabel':'Biologie','bookId':D.name,'title':'Biologie – zwanzig aktuelle weitere Ökologieziele','outputDirectory':str(D.relative_to(ROOT)/'native20'),'baseGoalBookConfigPath':'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-07/biologie-ecology20-current391-reviewed-integration-preparation-technical-v1/native-full391.future-active.config.json','goalIds':ids,'feedbackBaseUrl':'https://skillpilot.com/feedback','promptPath':'curricula/DE/Gymnasium/quality/goal-description-review/prompts/biology-goal-description-understanding-evidence-review-prompt-v2.md','criteriaPath':'curricula/DE/Gymnasium/quality/goal-description-review/prompts/biology-goal-description-understanding-evidence-review-criteria-v2.md','publicRoot':'app/public'})
print(json.dumps({'selected':20,'wholeCount':474,'strictBase':120,'neverIndexedD':20,'neverIndexedP':20,'imagesNeeded':20,'activeWrites':0,'goalIds':ids}))
