import json,pathlib,hashlib,datetime
B=pathlib.Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-09');O=B/'biologie-upper-science-fourteen-independent-b-v1';A=B/'biologie-upper-science-fourteen-whole-author-v1';N=A/'native-targeted-two-v2'
def read(p):return json.load(open(p))
def bind(p):
 p=pathlib.Path(p);b=p.read_bytes();return {'path':str(p),'sha256':'sha256:'+hashlib.sha256(b).hexdigest(),'bytes':len(b)}
def write(p,d):
 assert not p.exists(),p;p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');return bind(p)
e=read(N/'neutral-targeted-two-native-independent-review.entry.json');old=read(A/'native-preparation-v1/neutral-fourteen-native-independent-review.entry.json')
x=read(e['actualFullReviewedBeforeModelPath']);y=read(e['actualFullCandidateModelPath']);changes=[p['goalId'] for i,p in enumerate(x['pages']) if p!=y['pages'][i]];assert changes==[e['goalIds'][0]];assert len(x['pages'])==394
assert read(old['candidateCanonicalPath'])['goals']==read(e['candidateCanonicalPath'])['goals']
assert read(old['wholeSourceDutiesPath'])==read(e['wholeSourceDutiesPath'])
c0={c['goalId']:c for c in read(old['wholeCaseMaterialsPath'])['entries']};c1={c['goalId']:c for c in read(e['wholeCaseMaterialsPath'])['entries']};assert all(c0[k]==c1[k] for k in c0 if k!=e['goalIds'][1])
p0={p['goalId']:p for p in map(json.loads,open(old['positiveRecordPath']))};p1={p['goalId']:p for p in map(json.loads,open(e['positiveRecordPath']))};assert p0[e['goalIds'][0]]['profile']==p1[e['goalIds'][0]]['profile']
remedy=read(A/'remediation-v3-p11/P11-own-results-whole-profile.author-candidates.json')['goals'][0]['profile'];assert remedy==p1[e['goalIds'][1]]['profile']
# Exact binding verification, no author/peer verdict used.
errors=[]
for b in e['inputBindings']:
 got=bind(b['path'])
 if got['sha256']!=b['sha256'] or got['bytes']!=b['bytes']:errors.append(b['path'])
assert not errors
campaign=next(c for c in e['campaigns'] if c['side']=='b');i=read(campaign['inputPath'])
rows=[]
for j,g in enumerate(i['goals']):
 rows.append({'goalId':g['goalId'],'goalFingerprint':g['goalFingerprint'],'targetedSubsetPageFingerprint':g['pageFingerprint'],'wholeCurrentDEENDescriptionRead':True,'wholeCanonicalAndNativeContextRead':True,'actualPhysicalPDFPageViewed':j+3,'actualPDFInspectionBinding':bind(O/f'targeted-native-two-inspection/physical-page-{j+3:03d}.inspection-only.png'),'wholeProfileExactBindingFields':{k:p1[g['goalId']][k] for k in ['profileFingerprint','reviewInputFingerprint','reviewCriteriaFingerprint']},'wholeCasesReadBeforeAndExactCurrentBindingConfirmed':True,'descriptionDecision':'keep','positiveUnderstandingDecision':'ACCEPT_CANDIDATE_CONTENT','actualNativeVisualDecision':'ACCEPT_CANDIDATE_CONTENT','machineCandidateDApproval':True,'machineCandidatePApproval':True,'machineCandidateVApproval':True,'scientificReason':('The actual printed diagram explicitly labels Brutto-Sauerstoffrate and Gleiche Bedingungen. It represents a gross production rate, with zero at no light and a conditional saturation limit; neither concentration nor dark net balance is asserted. Whole enzyme and population cases retain quantification, mechanism, bounded conclusion and independent fresh variation. Full whole394 context has only this image delta.' if j==0 else 'The complete unchanged DE and corrected EN require own results and own inquiry. The exact new P-v3 sensor and leaf tasks require own generated correction/model tables and decision records, reflection of those specific choices and results, and own revised results on independent variation. Sensor mean7/range0.2 and fresh22/3; leaf40/residual-10 and fresh2N+5/35 are scientifically coherent with explicit calibration/test and physical-data limits. The complete unchanged native description, image and required/direct/reverse context are legible without clipping.'),'reviewAuthority':'ai_candidate','status':'needs_human_review','evidenceLevel':'E1','maximumClaimScope':'G1','humanApproval':False,'humanTrial':False})
v={'schemaVersion':1,'role':'Independent B first actual targeted-native2 verdict, following immutable scientific and visual first judgments','createdAtUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'neutralEntry':bind(N/'neutral-targeted-two-native-independent-review.entry.json'),'actualNativePDF':e['actualNativePDF'],'actualNativeHTML':e['actualNativeHTML'],'campaign':bind(campaign['campaignPath']),'input':bind(campaign['inputPath']),'whole394CurrentModel':bind(e['actualFullCandidateModelPath']),'allInputBindingsVerified':len(e['inputBindings']),'bindingErrors':errors,'exactUnchangedWhole394Pages':393,'onlyChangedWholePageGoalId':changes[0],'all479CanonicalGoalObjectsExact':True,'otherTwelveWholePagesProfilesCasesAndRastersRetained':True,'source69AndPartner68WholeFrameExact':True,'sourceFrame':bind(e['wholeSourceDutiesPath']),'cases29':bind(e['wholeCaseMaterialsPath']),'P2ProfileSource':bind(e['positiveRecordPath']),'rows':rows,'firstVerdictsRemainImmutable':[bind(O/'first-semantic-P-source-verdict.immutable.json'),bind(O/'first-whole14-actual-V-verdict.immutable.json'),bind(O/'targeted-P11-own-results-v3.first-verdict.immutable.json'),bind(O/'targeted-v4-ten-visible-rate.first-verdict.immutable.json')],'actualOriginal360680InspectionAlreadyCompleted':True,'wholeSourceDutyLimits':'All69 original source decisions and68 partners remain preserved. Finite authored-model actions and planned organ preparation are not real learner/physical-experiment evidence or closure of broader whole-source duties. No whole-source closure is issued.','biologyPeerJudgmentsRead':False,'humanApproval':False,'humanTrial':False,'actualLearnerResults':False,'actualPhysicalExperimentPerformed':False,'strictGain':0,'newScientificClosures':0,'restoredBindings':0,'activeWrites':[]}
out=write(O/'targeted-native2.first-verdict.immutable.json',v);write(O/'targeted-native2.first-verdict.freeze.json',{'schemaVersion':1,'createdAtUTC':v['createdAtUTC'],'immutableOutputs':[out],'independentApprovalScope':'Only actual targeted2 candidate D/P/V scientific content and exact native bindings; no human/learner/physical/whole-source acceptance','humanApproval':False,'strictGain':0});print(json.dumps({'firstVerdict':out,'rows':len(rows),'allInputBindings':len(e['inputBindings']),'unchangedPages':393}))
