from pathlib import Path
import json,hashlib,datetime,subprocess,re
ROOT=Path.cwd(); OWN=Path(__file__).resolve().parent;AUTHOR=OWN.parent/'biologie-he-evolution-eighteen-raster-native-author-technical-20261008-v1';OLD=OWN.parent/'biologie-he-q4-evolution-eighteen-whole-science-independent-b-20261008-v1';SOURCE=OWN.parent/'biologie-he-evolution-eighteen-decision-locators-independent-b-20261008-v3'
def read(p):return json.loads(p.read_text())
def rows(p):return [json.loads(s) for s in p.read_text().splitlines() if s.strip()]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return str(p.relative_to(ROOT))
def bind(p):return {'path':rel(p),'sha256':sha(p),'bytes':p.stat().st_size}
def write(n,x):
 p=OWN/n;p.parent.mkdir(parents=True,exist_ok=True)
 with p.open('x') as f:f.write(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
 return p
def verify(f):
 p=ROOT/f['path'];assert p.is_file() and sha(p)==f['sha256'].removeprefix('sha256:') and p.stat().st_size==f['bytes'],str(p)
started=datetime.datetime.now(datetime.timezone.utc).isoformat();entrypath=AUTHOR/'neutral-eighteen-current-raster-native-author-review.entry.json';assert sha(entrypath)=='67e77e97ce0521f874c7fbd8b5df89ca56f44fbf7afbfd233d4c16973f688496';e=read(entrypath)
seal=AUTHOR/'eighteen-current204-raster-native-author.first-input.freeze.json';assert sha(seal)=='9cc7c31975a3ede287fb4ec0350c7f2f4a75bf44b9445df31a264b5195d59680';s=read(seal)
for f in s['ownFiles']+s['authorizedInactiveAtlasFiles']+[s['requiredPortableInputs'],s['neutralEntry']]:verify(f)
required=read(ROOT/s['requiredPortableInputs']['path'])
for f in required['requiredFiles']:verify(f)
for x in required['actualContainedRelativeAliases']:
 p=ROOT/x['path'];assert p.is_symlink() and p.exists();assert p.readlink()==Path(x['containedRelativeTarget']);assert p.resolve().is_relative_to(AUTHOR.resolve());verify(x['target'])
assert len(required['actualContainedRelativeAliases'])==18 and not required['ignoredRequiredFiles'] and not required['brokenRequiredSymlinks']
oldseal=OLD/'eighteen-whole-source-science-independent-b.final-portable.freeze.json';assert sha(oldseal)=='5cde2a758454a25efb6f5c38c6d3b17d70a4e9a06811ae995081aa6b538fcd61'
sources=SOURCE/'eighteen-source-v3-independent-b.final-portable.freeze.json';assert sha(sources)=='b78017bdcda64e4670d38595d10a89c88cdcf4f8bef5599897b0f26b57855bc1'
# The actual previous whole-science and source judgments are our own, not a peer's.
oldps={p['goalId']:p for p in rows(OLD/'P18.whole-original-independent-b.review.jsonl')};ps=rows(ROOT/e['wholeP18CurrentRasterAIProfiles']);pmap={p['goalId']:p for p in ps}
whole=read(ROOT/e['wholeGoals'])['goals'];c=read(AUTHOR/'candidate/canonical.current476.actual-raster.inactive.json');idx={g['id']:g for g in c['goals']};guard=read(AUTHOR/'current204-whole-eighteen-author-guards.technical.json');live=ROOT/guard['beforeBindings']['canonical']['path'];assert sha(live)==guard['beforeBindings']['canonical']['sha256'];before={g['id']:g for g in read(live)['goals']}
assert len(c['goals'])==476 and len(whole)==18 and set(idx)==set(before)
selected=set(e['goalIds']);changes=[]
for gid,g in idx.items():
 if gid not in selected:assert g==before[gid]
 else:
  for k in set(g)|set(before[gid]):
   if g.get(k)!=before[gid].get(k):changes.append({'goalId':gid,'field':k})
  allowed=['resourceLinks']+[p['field'] for p in guard['whole3Fields2GoalWordPatches'] if p['goalId']==gid]
  assert all(x['field'] in allowed for x in changes if x['goalId']==gid)
assert len(guard['baselineStrictGoalIds204'])==204
wholecases=read(ROOT/e['whole36OriginalExactCaseJSON']);original=read(OWN.parent/'biologie-he-q4-evolution-eighteen-whole-science-author-20261008-v1/eighteen-whole-goals-thirty-six-complete-DEEN-cases.author.json');assert wholecases==original and len(wholecases['wholeCases'])==36
for p in ps:
 assert p['profile']==oldps[p['goalId']]['profile'];assert p['status']=='needs_human_review' and p['reviewAuthority']=='ai_candidate' and p['evidenceLevel']=='E1' and p['maximumClaimScope']=='G1'
q=ROOT/e['roundB'];inp=read(q/'description-review-input.json');campaign=read(q/'description-review-campaign.json');bundle=read(q/'review-bundle-manifest.json');assert campaign['batchSize']==campaign['goalCount']==inp['goalCount']==18
mapping=read(ROOT/e['actualPhysicalPagesAnd36Widths']);im={x['goalId']:x for x in mapping['captures']};pages={x['goalId']:x for x in mapping['actualPhysicalPages']};assert len(im)==len(pages)==18
pdf=ROOT/e['nativeWholePDF'];argv=['pdftotext','-layout',str(pdf),'-'];run=subprocess.run(argv,capture_output=True,text=True);assert run.returncode==0;pdftext=run.stdout.split('\f');assert len(pdftext)-1==20
with (OWN/'actual-whole-twenty-physical-page-native-PDF.independent-b.txt').open('x') as f:f.write(run.stdout)
norm=lambda t:re.sub(r'[\s\u00ad]+','',t)
# These reasons are our own judgments from all 18 full PNGs,36 actual-width captures,and18 full PDF pages.
visuals=[
 'HOLD: Im Homologie-Inset besitzt die vollständig als katzenartige Vorderpfote gezeichnete mittlere Extremität nur drei komplette Finger-/Krallenstrahlen. Mensch und Wal besitzen jeweils fünf. Eine nicht bezeichnete Teilansicht darf hier den homologen fünfstrahligen Grundbauplan nicht auf drei reduzieren. Der Befund ist am Original,360,680 und physischer Seite6 sichtbar. Minimal die katzenartige Pfote mit vier Hauptzehen und seitlichem ersten Finger anatomisch richtig zeichnen; Farben, Fossil und Komposition behalten.',
 'KEEP: Oben trennt eine räumliche Barriere eine Ausgangspopulation und verschiedenfarbige Folgegruppen; unten entsteht Nischen-/Partnertrennung im selben Gebiet. Die durchgehenden Zeitpfeile erlauben den Vergleich. Farbe ist ein didaktisches Gruppenmerkmal, kein alleiniger Nachweis reproduktiver Isolation; die unveränderten ganzen P-Fälle klären diese Grenze. Beide Wege sind ohne Kleinschrift bei360 und680 sichtbar.',
 'KEEP: Fossilschädel, verzweigende hypothetische Abstammung und schematische Ausbreitung aus Afrika sind klar getrennt. Die heutigen vielfältigen Menschen stehen zusammen am heutigen Zweig; keine Wert- oder Rassenleiter. Das unbeschriftete basale hominine Symbol wird nicht als heutiger Schimpanse oder sicherer direkter Fossilvorfahr bezeichnet. Atlas/P-Fälle begrenzen die vereinfachten Hypothesen und Migration; Hauptmotive bleiben bei360 sichtbar.',
 'KEEP: Werkzeugherstellung, beobachtetes Lernen und symbolische Sprache/Ideen verknüpfen kulturelle Weitergabe. Gegenwartswerkstatt ist ein Lehrbeispiel und kein archäologisch datierter Befund. Werkzeughandhabung ist plausibel; kein lesepflichtiger spiegelverkehrter Eintrag. Handlung und Weitergabepfeil bleiben bei360/680 erkennbar.',
 'KEEP: Grooming zeigt soziales Verhalten; Nahrungsumgebung und Gehirn-/Körpermotiv unterscheiden äußere Bedingungen und innere Mechanismen schematisch. Die Symbole behaupten kein Hormonnachweisexperiment und keine vollständige Kausaldiagnose. Das Notizheft liegt zur beobachtenden Person, Strichliste ohne falsche Leserperspektive. Die drei Primaten sind bei360 klar.',
 'KEEP: Historische1933–1945-Seite, ausdrücklich durchgestrichene Menschenhierarchie und gleichberechtigte Vielfalt unter Waage machen Kritik statt Befürwortung deutlich. Das historische Buch ist korrekt für die beiden Lesenden ausgerichtet. Keine Täterpropaganda und keine angeblich biologisch begründete Wertordnung. Bei360 bleiben Durchstreichung und gleiche Würde deutlich; Jahreszahlen sind bei680 und Original lesbar.',
 'KEEP: Zwei farblich getrennte Pflanzen und Pollenwege zur mittleren Form illustrieren Hybridisierung als Fragestellung; geteilte Stammbaumlinien sind schematische Verwandtschaftshinweise. Keine Behauptung, jede Kreuzung erzeuge eine fertile neue Art; ganze P-Fälle prüfen allopatrisch/sympatrisch, Fertilität und Genfluss. Die Blüten/Pollen/Fragezeichen bleiben bei360 klar.',
 'KEEP: Beide heutigen Linien zeigen Veränderungen nach gemeinsamer Aufspaltung; Fossilkalibrierung und fragende Uhr begrenzen Zeitabschätzung. Keine exakte Zahlenableitung aus den dekorativen Farbfeldern und keine neue amtliche Pflicht. Bei360 bleiben beide Zweige, Sequenzfelder, Zeitachse und unsichere Uhr deutlich; kleine Zusatztexte sind unterstützend, bei680 lesbar.',
 'KEEP: Zwei verschiedene verzweigte Stammbäume mit gleichen drei nummerierten Schädeln stehen als offene Alternativen nebeneinander; Fossilien, Werkzeuge und Gespräch tragen die differenzierte Hypothesendiskussion. Die Tafel verhindert eine lineare Fortschrittsleiter; keine exakten Artnamen oder Datierungen werden erfunden. Beide Topologien sind bei360/680 erkennbar.',
 'KEEP: Gleiche blaue Ausgangsverteilungen und rote spätere Verteilungen zeigen schmalere Mitte, Verschiebung zu einer Seite und zwei Maxima. Häufigkeits-/Schnabelgrößenachsen, Farb-/Linienlegende sind fachlich konsistent. Die drei großen Titel und Kurven bleiben bei360 klar; die Legende und Achsen sind bei680 gut lesbar. Kein Gleichsetzen der Kurven mit individueller zielgerichteter Veränderung.',
 'KEEP: Netzwerkhöhe stellt Fitness dar; blauer nur aufsteigender Nachbarschaftspfad endet an niedrigerem lokalem Gipfel, höherer Gipfel ist nur über das Tal erreichbar. Fragezeichen markiert Pfad-/Umweltgrenzen. Kein Teleologie- oder globaler Garantieanspruch; eigenes nichtamtlich verpflichtendes Modell bleibt so gebunden. Große Knoten und beide Maxima bleiben bei360/680 sichtbar.',
 'KEEP: Lange Blütenröhre und passender Saugrüssel, je zwei Varianten sowie entgegengesetzte Wechselwirkungspfeile zeigen reziproken Selektionskontext. Fragezeichen bewahrt die Prüffrage, nicht jeder heutige Passungsbefund beweist gemeinsame Evolution. Einzelner dekorativer Falter ist keine Gesamtgliedmaßenzählung. Hauptpaarung und zwei Pfeilrichtungen sind bei360 klar.',
 'KEEP: Vier diploide Individuen AA,AA,Aa,aa ergeben acht Kopien mit fünfA und drei a; gene pool fractions5/8 and3/8 passen exakt. Farbe und Groß-/Kleinschreibung halten Allele auseinander; keine Verwechslung mit vier Individuenfrequenzen. Die acht großen Symbole und Brüche sind bei360/680 lesbar, der lange Bildtitel ist Zusatz.',
 'KEEP: Unter ausdrücklich bestimmten Modellbedingungen p=q0,5 ergibt das Kreuzungsschema AA,Aa,Aa,aa und1:2:1. Beobachtungsbalken werden als mögliche Beobachtung/Frage dargestellt, nicht als universelles Gesetz. Annahmen und verschiedene Abweichungsursachen stehen im ganzen P. Große Genotypen, p/q und Verhältnis bleiben bei360 klar, Zusatztexte bei680 lesbar.',
 'KEEP: Zufallswürfel, enges Probengefäß und getrennte Gründergruppe mit neuer Insel zeigen zwei Mechanismen zufälliger kleiner Stichproben. Die Illustration ist keine zählgenaue Allelstatistik; die vorgegebenen exakten Zahlen befinden sich in den unveränderten P-Fällen. Weiterbestehende Variation und mögliche Häufigkeitsänderungen sind richtig bezeichnet. Bei360 sind beide großen Mechanismen und Stichprobenwege klar; Kleincaptions sind Zusatz, bei680 lesbar.',
 'KEEP: Pfauenornament, Partnerwahl, Nachwuchs sowie Waage mit Energie/Flucht/Nahrung zeigen Fortpflanzungsvorteile und Überlebenskosten. Das ist ein Tierbeispiel, keine universelle Geschlechterrolle oder Wertordnung; keine vollständige männliche Brutpflege wird behauptet. Große Ornament-/Wahlsymbole und Kostenseite bleiben bei360/680 klar.',
 'KEEP: Morphologische Merkmalsmatrix und drei ausgerichtete Farbsequenzen führen mit Fragezeichen zu einer Hypothese1+2gegen3. Morphologische gemeinsame Merkmale und geringere Sequenzdistanz1/2 sind konsistent. Nummerierung und Felder bleiben bei360/680 lesbar; keine erwiesene endgültige Topologie und kein family-tree-Missverständnis im korrigierten ganzen Text.',
 'KEEP: Tatsächlich homolog ausgerichtete fünf Basen A=ATGCC,B=ATGCT,C=AAGTT ergeben DistanzenAB1,AC3,BC2; engere A/B-Hypothese ist nachvollziehbar. Beide gleichen Baumtopologien sind ausdrücklich Hypothese/Frage. Große Basen und A/B/C sind bei360 klar; keine exakte molekulare Uhr, absolute Abstammungssicherheit oder zusätzliche amtliche Modellpflicht.'
]
sciences=[
 'Fossilienlage, Strukturhomologie und Organellbefunde liefern unterschiedlichartige vereinbare Belege, nicht den sicheren direkten Vorfahren.',
 'Räumliche Trennung und Fortpflanzungsbarrieren im gleichen Raum werden verglichen; äußerliche Verschiedenheit allein definiert keine Art.',
 'Die Fossilfolge, mehrere Stammbäume und heutige Verbreitung bleiben evidenzgebundene Hypothesen; korrigiertes phylogenetic trees ist fachlich passend.',
 'Werkzeuge und Sprache erlauben soziale Informationsweitergabe ohne zielgerichteten genetischen Entwicklungszwang.',
 'Äußere soziale/ökologische Bedingungen und innere hormonale/neuronale Bereitschaft wirken zusammen; Korrelation beweist keine einzelne Ursache.',
 'Naturbeschreibung rechtfertigt keine Ungleichwertigkeit oder Gewalt; historische Ideologie wird als Missbrauch mit optionalem Q2.2-LK-Bezug kritisiert.',
 'Geographie, reproduktive Isolation und Hybridfertilität/Genfluss werden als unterschiedliche Artbildungsbedingungen verglichen.',
 'Kalibrierte Distanz und Veränderungen beider Linien begrenzen Zeitschätzung; dieses eigene Modell bleibt nicht amtlich verpflichtend.',
 'Fossilien/Datierung, alternative Topologien und kulturelle Belege erlauben differenzierte Hypothesen ohne Fortschrittsleiter.',
 'Selektionsvorteile können mittlere, einseitige oder extreme Merkmale begünstigen; unterschiedliche Verteilungen belegen den jeweiligen Modus.',
 'Genotypnachbarschaft und Umweltbedingung begrenzen adaptive Aufwärtspfade und lokale Maxima; eigene Erweiterung bleibt nicht amtlich verpflichtend.',
 'Wechselseitige evolutionäre Änderungen müssen im beidseitigen Selektionskontext erklärt werden, nicht nur momentane Passung.',
 'Allelkopien werden über diploide Individuen gezählt; Genpool und Häufigkeiten unterscheiden sich von Individuen- und Genotypzahlen.',
 'p+q1 und p²,2pq,q² gelten unter Modellannahmen; Abweichungen erlauben mehrere Ursachen und keinen eindeutigen Selektionsschluss.',
 'Zufällige kleine Proben ändern Allelfrequenzen bei Flaschenhals/Gründung; Erwartung ist keine garantierte individuelle Veränderung.',
 'Fortpflanzungserfolg und Überlebenskosten bestimmen bedingte Fitnessfolgen der sexuellen Selektion.',
 'Abgeleitete gemeinsame Merkmale und homolog ausgerichtete Sequenzen liefern eine prüfbare Verwandtschaftshypothese; korrigierter Stammbaumtext bleibt gültig.',
 'Sequenzdistanz und homologe Stellen begründen eingeschränkte Topologien; Ähnlichkeit ist keine absolute Datierung oder Sicherheit.'
]
gord={g['id']:n for n,g in enumerate(whole)};v=[];d=[];per=[]
for item in inp['goals']:
 gid=item['goalId'];n=gord[gid];g=idx[gid];p=pmap[gid];page=item['reviewContext']['page'];img=im[gid];pg=pages[gid];assert g==whole[n]
 for k,suffix in [('title','Title'),('description','Description')]:assert item['current'+suffix+'De']==g[k] and item['current'+suffix+'En']==g[k+'En']
 assert item['goalFingerprint']==p['goalFingerprint']==page['goalFingerprint'];assert item['pageFingerprint']==page['pageFingerprint'];assert page['visualization']['originalDigest']=='sha256:'+img['sourceSha256'];assert sha(ROOT/img['sourcePath'])==img['sourceSha256'];verify(img['originalPNG']);verify(pg['actualPhysicalPNG'])
 for cap in img['captures']:assert sha(ROOT/cap['path'])==cap['sha256']
 assert sorted(x['goalId'] for x in page['requires']+page['externalPrerequisites'])==sorted(g['requires'])
 assert sorted(x['goalId'] for x in page['reverseRequires']+page['externalReverseRequires'])==sorted(x['id'] for x in c['goals'] if gid in x.get('requires',[]))
 for ref in page['requires']+page['externalPrerequisites']+page['reverseRequires']+page['externalReverseRequires']:assert ref['title']==idx[ref['goalId']]['title']
 tx=pdftext[pg['physicalPage']-1];assert norm(g['title']) in norm(tx) and norm(g['description']) in norm(tx) and ('Lernziel-ID '+gid) in tx
 visual=visuals[n]+' Tatsächliche ganze native Seite'+str(pg['physicalPage'])+' hat vollständige UUID, ganze Beschreibung, korrekte direkte/äußere Voraussetzungen und Nachfolger, Geltungsblock und Seitenfingerprint ohne Beschnitt.'
 v.append({'ordinal':n+1,'goalId':gid,'decision':'HOLD' if n==0 else 'KEEP','fachlich':'HOLD' if n==0 else 'PASS','visual':'HOLD' if n==0 else 'PASS','actualReasonDe':visual,'goalFingerprint':item['goalFingerprint'],'pageFingerprint':item['pageFingerprint'],'bookDigest':inp['bookDigest'],'actualOriginalPNG':img['originalPNG'],'exactSelectedPNG':bind(ROOT/img['sourcePath']),'actualWidths':[bind(ROOT/cap['path']) for cap in img['captures']],'actualPDF':bind(pdf),'actualNativePage':pg['actualPhysicalPNG'],'physicalPage':pg['physicalPage'],'fullPNGActuallyViewed':True,'actual360680AndWholeNativePageActuallyViewed':True,'formatDecision':'Existing friendly clear1672x941~16:9 raster style retained; motifs checked at actual360/680. Decorative small text is not compulsory phone reading.','generationOrHashMatchingIsApproval':False,'fullAppOrRealDeviceAcceptanceClaim':False,'reviewAuthority':'ai_candidate','status':'needs_human_review','humanApproval':False})
 ex=p['profile']['expectations'];briefs=p['profile']['applicationCaseBriefs'];ue={'essentialUnderstandingDe':' '.join(x['essentialUnderstandingDe'] for x in ex),'essentialUnderstandingEn':' '.join(x['essentialUnderstandingEn'] for x in ex),'observablePerformanceDe':briefs[0]['taskDemandDe'],'observablePerformanceEn':briefs[0]['taskDemandEn'],'transferExpectationDe':briefs[1]['taskDemandDe'],'transferExpectationEn':briefs[1]['taskDemandEn']};assert all(0<len(t)<=4000 for t in ue.values())
 reason=sciences[n]+' Eigener tatsächlich versiegelter vorheriger ganzer Science-/Quellenreview B bleibt gültig: 36 ganze DE/EN-Fälle und18 Profile exakt erhalten;15 begrenzte Konkretisierungen und3 nichtamtlich verpflichtende Modelle, bestehender NeuroGK2-Quellen-HOLD nicht aufgehoben. '+visual+' Keine aktuellen Peer-A-Finalurteile gelesen. Text KEEP ist keine Visualfreigabe des gehaltenen Anatomiedetails und keine menschliche Prüfung oder ausgeführte Lernendenleistung.'
 assert len(reason)<=4000
 d.append({'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json','schemaVersion':1,'recordId':OWN.name+'.'+gid,'runId':OWN.name,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'bundleFingerprint':inp['bundleFingerprint'],'bookDigest':inp['bookDigest'],**{k:item[k] for k in ['goalId','goalFingerprint','pageFingerprint','currentTitleDe','currentTitleEn','currentDescriptionDe','currentDescriptionEn']},'decision':'keep','understandingEvidence':ue,'rationale':reason,'evidenceProfileContract':'positive-understanding-evidence-v2','evidenceProfileRecommendation':'none','recordStatus':'candidate','reviewAuthority':'ai_candidate'})
 per.append({'goalId':gid,'ordinal':n+1,'retainedWholeScience':'KEEP','retainedWholePProfileExact':True,'newNativePageContextBindingsActuallyChecked':True,'currentVisual':'HOLD' if n==0 else 'KEEP','clinicalOrExperimentPerformanceClaim':False,'sourceRole':'own-not-mandatory-model' if n+1 in [8,11,14] else 'bounded-own-operationalization','noWhole144SourceApproval':True})
batch=campaign['batches'][0];results=OWN/'round-b/results';results.mkdir(parents=True,exist_ok=True);records=results/(batch['batchId']+'.records.jsonl')
with records.open('x') as f:
 for x in d:f.write(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n')
write('round-b/results/'+batch['batchId']+'.run.json',{'$schema':'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json','schemaVersion':1,'runId':OWN.name,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'batchId':batch['batchId'],'batchInputFingerprint':batch['batchInputFingerprint'],'bundleFingerprint':inp['bundleFingerprint'],'bookDigest':inp['bookDigest'],'provider':'OpenAI','model':'Codex actual independent B; exact serving revision not exposed','role':'subject_reviewer','promptFamilyId':'goal-description-understanding-evidence-v2','promptFingerprint':campaign['promptFingerprint'],'criteriaFingerprint':campaign['criteriaFingerprint'],'generationParametersFingerprint':'sha256:'+hashlib.sha256(b'Actual independent EvolutionB18; genuine unchanged Science36/sourcev3; actual18original PNG36width18PDF; serving sampling unavailable').hexdigest(),'independenceGroupId':campaign['independenceGroupId'],'blindToOtherRuns':True,'goalIds':batch['goalIds'],'inputArtifacts':[{'role':x['role'],'digest':x['digest']} for x in bundle['artifacts'] if x['role'] in ['book_model','book_pdf','book_pdf_render_manifest','review_input_json','review_prompt','review_criteria']]+[{'role':'description_review_batch_input_jsonl','digest':batch['batchInputFingerprint']}],'startedAt':started,'completedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'outputDigest':'sha256:'+sha(records),'status':'completed','toolchainVersion':'skillpilot-goal-description-review-v1'})
write('eighteen-actual-PNG-width-native-pages-V.independent-b.first.verdicts.json',{'schemaVersion':1,'role':'Own independent B genuine actual original/360/680/native V first verdict before peer-A final reading','records':v,'KEEP':17,'HOLD':1,'findings':[{'findingId':'EVOLUTION-HOMOLOGY-CAT-DIGITS','goalId':whole[0]['id'],'severity':'blocking','actualWholeImage':im[whole[0]['id']]['originalPNG'],'requiredMinimalCorrection':'Four main feline forepaw digits plus lateral first digit in bone homology inset; preserve other good components/style.'}],'currentPeerAFinalRead':False,'activeWrites':0,'newStrictGain':0,'humanApproval':False})
write('eighteen-current-whole-D-P-source-context.independent-b.first.verdict.json',{'schemaVersion':1,'D18':'KEEP whole current descriptions,source/context/scientific wording','P18Science':'KEEP genuine previous whole36 science; exact profiles retained','V18':{'KEEP':17,'HOLD':1},'ownGenuineWholeScienceFinalSeal':bind(oldseal),'ownGenuineSourceV3FinalSeal':bind(sources),'sourceRoles':'15 bounded own operationalizations plus3 nonmandatory own models; NeuroGK2 full144 remains HOLD','goalBindings':per,'currentPeerAFinalRead':False,'nativeTechnicalChecks':'pending actual subsequent API/CLI validation; not invented','status':'needs_human_review','reviewAuthority':'ai_candidate','evidenceLevel':'E1','maximumClaimScope':'G1','humanApproval':False,'humanTrial':False,'performedExperiments':False,'newStrictGain':0,'activeWrites':0})
write('exact-current204-authored-input-science-source18-preservation.independent-b.actual.json',{'authorFirstSeal':bind(seal),'ownAuthorFilesActuallyVerified':len(s['ownFiles']),'authorizedInactiveAtlasFilesActuallyVerified':len(s['authorizedInactiveAtlasFiles']),'requiredPortableFileBindingsActuallyVerified':len(required['requiredFiles']),'containedRelativeAliasesActuallyVerified':18,'currentCanonical':bind(live),'wholeOther458GoalsExact':True,'whole36DEENCasesExact':True,'whole18PProfileBodiesExact':True,'protectedStrict204':True,'changedSelectedFields':changes,'actualVisualFilesSeen':{'originals':18,'width360':18,'width680':18,'wholeNativePDFPages':18},'pdfExtraction':{'argv':argv,'exitCode':run.returncode,'stderr':run.stderr,'physicalPages':20},'hashIdentityIsScience':False,'currentPeerAFinalRead':False,'activeWrites':0})
files=[x for x in OWN.rglob('*') if x.is_file()];first=write('eighteen-current-D-P-V.independent-b.first.freeze.json',{'schemaVersion':1,'sealedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'stage':'Own first actual18D/P/V judgment before any current peer-A final reading','files':[bind(x) for x in sorted(files)],'authorInputSeal':bind(seal),'scienceOwnFinal':bind(oldseal),'sourceOwnV3Final':bind(sources),'D18KEEP':18,'P18ScienceKEEP':18,'V17KEEP1HOLD':True,'nativeApiAndCliChecks':'pending actual next step','noActiveWrites':True,'humanApproval':False,'humanTrial':False,'strictGain':0})
print(json.dumps({'firstSeal':rel(first),'sha256':sha(first),'files':len(files),'DKEEP':18,'PScienceKEEP':18,'VKEEP':17,'VHOLD':1}))
