import json, hashlib
from pathlib import Path
from datetime import datetime, timezone
from PIL import Image

ROOT = Path('/home/enpasos/projects/skillpilot')
AUTHOR = ROOT / 'curricula/DE/Gymnasium/quality/goal-visualization-review/wirtschaft-q4-twenty-seven-image-author-20261008-v1'
OWN = Path(__file__).parent
GOALS = ROOT / 'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-08/wirtschaft-q4-development-ethics-twenty-seven-bilingual-positive-author-v1/whole-goals.candidate.json'
BEFORE = ROOT / 'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-08/wirtschaft-q4-development-ethics-twenty-seven-bilingual-positive-author-v1/native-image-preparation/native-twenty-seven-preparation.actual.json'

# Goal-specific judgments manually authored AFTER actual native/360/680 viewing.
# This script serializes those judgments; it does not infer verdicts from hashes,
# generation prompts, templates, or another reviewer's output.
READ = [
('KEEP', 'Agriculture, manufacturing and services remain distinct, with two possible growth paths rather than an inevitable sector ladder. No fabricated data or universal welfare ranking.', 'The oblique handheld pictorial map has no reader-dependent words. Large sector icons and alternative paths remain clear at360 and680.', 'Drei große Sektorsymbole für Landwirtschaft, verarbeitendes Gewerbe und Dienstleistungen sind verbunden. Eine Person betrachtet zwei mögliche Entwicklungspfade mit unterschiedlichen Produktions- und Dienstleistungsstrukturen.', None),
('KEEP', 'The goods arrow goes to the buyer and the money arrow returns to producers. Both regions have open income, work and dependency questions. This is one fictional trade example, not an immutable ethnic hierarchy or guaranteed winner.', 'Phone backs face the viewer while their readers face the screens. Main commodity/payment relations remain recognizable at360; no small numerical dataset is needed.', 'Zwei Regionen handeln mit Rohprodukten. Der Warenpfeil führt zu den Käufern, der Geldpfeil zurück zu den Verkäufern. Beide Seiten fragen nach Einkommen, Arbeit und Abhängigkeiten.', None),
('KEEP', 'Consequences, rights and justice are separate ethical lenses on the same affected people. Rights are not automatically priced away and no lens is declared universally correct.', 'Floating conceptual lenses are not physical papers falsely oriented to their readers. The central phone back faces the viewer; the main three lenses survive360.', 'Drei große Denkfelder zu Folgen, Rechten und Gerechtigkeit umgeben eine Gruppe von Menschen, die eine Globalisierungsentscheidung betrachtet.', None),
('KEEP', 'Health, education and material living standards illustrate the HDI lens; unequal income illustrates a different Gini lens. The decorative balance and coin heights are not a defined dataset or computation, and a higher Gini is not labelled better.', 'Held cards are outward presentations, not personal reading pages. Abstract book lines are not required text. Both indicator lenses remain recognizable at360.', 'Gesundheit, Bildung und Lebensstandard stehen einem eigenen Feld zur Einkommensverteilung gegenüber. Menschen vergleichen diese unterschiedlichen Sichtweisen auf Entwicklung.', None),
('KEEP', 'Resources and access are distinct poverty perspectives, followed by possible support paths and open outcome questions. No strategy is promised to end poverty automatically.', 'Large resources, access icons and paths remain visible at360. Small subordinate strategy phrases are optional details; no personal reading surface faces the wrong reader.', 'Ein Bildfeld zeigt materielle Lebensbedingungen, ein anderes den Zugang zu Gesundheit, Bildung, Wasser und Verkehr. Mehrere mögliche Unterstützungswege bleiben als offene Fragen dargestellt.', None),
('KEEP', 'Rules, funds and participation accompany a diverse international discussion, with implementation and accountability open. No official organization logo or automatic agreement-to-success chain is used.', 'Shared table plan and outward group labels are common discussion surfaces, not a personal upside-down notebook. Three large governance headings remain distinguishable at360.', 'Eine internationale Gruppe diskutiert am gemeinsamen Tisch. Große Felder zu Regeln, Mitteln und Mitsprache sowie offene Umsetzungsfragen rahmen die Szene.', None),
('REJECT', 'Claim, action and evidence are useful CSR lenses, and costs and effects remain questions. The surrounding scene is substantively suitable and should be retained.', 'The personal foreground sheet titled Standortentscheidung and its directional arrows face the external viewer while all acting readers sit behind it. They would have to read it upside down. This actual perspective error persists at native,360 and680.', 'Menschen vergleichen Unternehmensanspruch, tatsächliches Handeln und Nachweise bei einer Standortentscheidung. Die großen Felder fragen nach Kosten, Verantwortung und Wirkungen.', ('q4-csr-personal-sheet-reading-perspective', 'Neutralize ONLY the personal foreground sheet text and reader-dependent arrows, or orient that surface correctly to the actors. Preserve claim/action/evidence panels and the warm scene.')),
('REJECT', 'The stated comparison concerns one limited resource distributed among the same five people, but the drawn equality cylinders differ in quantity and the other panels introduce additional stacks and inconsistent total resources. Correct labels cannot repair an incorrect allocation drawing.', 'Native,360 and680 show unequal equality volumes and non-conserved totals. Equal marker sizes and conserved quantity are essential instructional details, not optional decoration.', 'Drei alternative Verteilungen derselben begrenzten Ressourcen werden anhand von Gleichheit, Bedarf und Beitrag verglichen.', ('q4-justice-equal-units-and-conserved-total', 'Use the SAME five person positions and ten equal-sized resource markers in EACH alternative: equality2/2/2/2/2, need1/1/4/3/1, contribution3/2/1/3/1. Leave the normative judgment open. Recount actual generated markers; a requested count is not approval.')),
('KEEP', 'Domestic production and export shipping are distinct routes, considered through workforce, inputs, finance and conditional risks. No fixed economic winner is shown.', 'Large factory and shipping motifs and common conditional questions remain recognizable at360. The front conditions card is an outward annotation rather than a falsely oriented personal note.', 'Binnenproduktion und Export stehen als zwei mögliche Entwicklungsstrategien nebeneinander. Menschen vergleichen gemeinsame Bedingungen und offene Risiken.', None),
('KEEP', 'Producer/buyer conditions are separate from customs, agreements and standards, with outcome questions. This does not use an actual Fairtrade certification mark or claim that ticks prove development effects.', 'The held board is intentionally presented outward. The gate officer clipboard back faces the viewer and its reading side faces the actor. Both major scenes remain clear at360.', 'Produzenten und Käufer betrachten Handelsbedingungen. Daneben zeigt ein Handelszugang Regeln und Standards; offene Fragen betreffen die tatsächlichen Entwicklungswirkungen.', None),
('KEEP', 'Workers, rights, protective measures, complaints and remedy are connected to an evidence question. A checklist is not presented as sufficient proof of compliance.', 'Reports are displayed to a group rather than read by a person from the back. Large worker, protection and remedy motifs remain recognizable at360 without reading all subordinate words.', 'Eine Lieferkette verbindet Menschen an verschiedenen Arbeitsorten. Rechte, Schutz, Beschwerden und Abhilfe werden mit einer offenen Nachweisfrage verbunden.', None),
('REJECT', 'The shared project discussion usefully connects access, environment, durability and a limited budget. These motifs should remain unchanged.', 'The acting woman points to the personal/shared project card with Neue Perspektiven printed toward the outside viewer; the whole acting group behind the table would read the wording upside down. Native,360 and680 confirm the specific surface.', 'Eine Gruppe plant ein inklusives und nachhaltiges Projekt und betrachtet Zugang, Umwelt, dauerhafte Wirkung und den verfügbaren Rahmen.', ('q4-inclusive-project-card-reading-perspective', 'Remove ONLY the reader-dependent Neue Perspektiven text on that project card, or properly orient it. Keep the group, project motif and valid outward discussion panels.')),
('REJECT', 'Local people actively contribute alongside NGO and public-authority support, with finance and access questions. The actors are not portrayed as passive recipients and the main governance scene is suitable.', 'The detached bottom-left SkillPilot slogan block is an actual visible watermark, independent of whether the brand belongs to this project. The visualization hardgate rejects visible watermarks. Outward held diagrams are valid presentations.', 'Menschen vor Ort, eine NGO und öffentliche Akteure diskutieren Zugang, Unterstützung, Finanzierung und Verantwortung.', ('q4-ngo-detached-watermark', 'Remove ONLY the detached bottom-left SkillPilot / WIR VERSTEHEN / WIR GESTALTEN / WIR WACHSEN watermark block. Preserve the active community and governance scene.')),
('REJECT', 'Values, rules and accountability are useful lenses on global governance; the main cooperation scene is suitable.', 'The small foreground blue flag copies the recognizable UN azimuthal-map-and-laurel emblem. The no-copied-third-party-logo hardgate applies. This is a visual identity finding, not a claim of a completed legal-rights assessment.', 'Menschen verbinden ethische Maßstäbe mit Regeln, Beteiligung und Kontrolle in einer internationalen Kooperationsszene.', ('q4-governance-copied-un-emblem', 'Replace ONLY the concrete UN emblem on the small flag with a neutral abstract cooperation symbol. Preserve the flag, people, values, rules and accountability motifs.')),
('KEEP', 'The same four identities appear in origin, movement and destination. Skills-gap and destination effects remain questions, with a possible knowledge-return channel rather than an automatic migration gain or loss.', 'Devices face their users; no readable personal surface is reversed. Origin, movement and destination remain visible at360.', 'Dieselben Menschen erscheinen in Herkunftsregion, Wanderung und Zielregion. Die Szene fragt nach Fachkräfteverlust, möglichen Vorteilen und Rückflüssen von Wissen.', None),
('KEEP', 'Primary goods travel toward processing and processed goods return; neither flow is falsely labelled money. Concentration, partners and alternative routes are open dependency questions, not a real-country dataset or fixed ethnic economic role.', 'The acting person writes abstract lines without reader-dependent wording. Two major trade directions and alternative routes are recognizable at360.', 'Eine Region liefert Rohprodukte und erhält verarbeitete Güter zurück. Menschen prüfen Partner, Konzentration und mögliche alternative Handelswege.', None),
('KEEP', 'Corporate due care, public rules and controls, and civil-society voice/oversight are distinct responsibilities linked to protection and remedy. No tick absolves actors of all obligations.', 'The company clipboard back faces the viewer. Three large roles survive360; smaller subordinate lists are optional details rather than obligatory fine print.', 'Unternehmen, Staat und Zivilgesellschaft übernehmen unterschiedliche Aufgaben für Schutz, Kontrolle, Mitsprache und Abhilfe in Lieferketten.', None),
('KEEP', 'A concrete unsafe/low-pay conflict has negotiation and enforcement/remedy options, with conditions, cost, responsibility, time and limits. Improvement is a conditional possibility, not proof that every conflict is resolved.', 'The Verhandeln paper faces a participant sitting on the near side of the shared table. It therefore differs from the all-readers-behind personal-sheet errors; an outward standards board is also a valid presentation. Main alternatives remain clear at360.', 'Eine problematische Arbeitssituation wird mit Verhandlungen, Regeln und möglichen Abhilfen verbunden. Kosten, Zuständigkeit, Dauer und Grenzen bleiben offene Prüfungsfragen.', None),
('KEEP', 'Extraction and resource revenue coexist with price-risk and diversification questions. Resource wealth is not automatically a curse, and the decorative zigzag is not a measured price or GDP series.', 'The shared paper has pictorial connections without compulsory reader-dependent wording. Quarry, risks and alternative production/education/energy routes remain clear at360.', 'Rohstoffgewinnung und Einnahmen stehen möglichen Risiken gegenüber. Daneben werden Produktion, Bildung, Energie und andere Diversifizierungswege als offene Optionen betrachtet.', None),
('KEEP', 'Credit disbursement runs from lender to borrower and repayment with interest runs back. Access and debt risks remain open; the same borrower appears in alternatives. Credit is not confused with donation or guaranteed escape from poverty.', 'Large opposing financial flows and interest symbol remain identifiable at360. No personal screen or paper is falsely oriented, and no specific product return is promised.', 'Ein Mikrokredit fließt zum selben möglichen Kreditnehmer, Rückzahlung mit Zinsen zurück zum Kreditgeber. Zugang, Schuldenrisiken und mögliche Wirkungen werden als Fragen dargestellt.', None),
('REJECT', 'The with-program branch contains a happy woman and an unqualified positive leaf, while the without-program branch contains a different doubting man and a questioned leaf. This hypothetical contrast changes person identity and builds a favourable outcome into the program branch without comparable conditions or evidence.', 'Native,360 and680 confirm both identity and outcome asymmetries. Real study groups can contain different people when comparability is established; the actual drawing does not establish that. The useful effort/output/evidence stages should remain.', 'Aufwand, Leistungen und beobachtete Wirkungen eines Entwicklungsprogramms werden anhand einer offenen Vergleichsfrage untersucht.', ('q4-programme-counterfactual-comparability-and-outcome', 'For this fictional hypothetical comparison, use the same person identity in both branches and neutral/open outcome questions on BOTH sides. Do not prescribe that actual empirical control groups must contain identical individuals. Preserve effort, output and evidence lenses.')),
('REJECT', 'Distinct WTO, IMF, World Bank and UN role cards are useful. The UN limit is falsely absolute: keine Durchsetzungsgewalt omits Security Council enforcement measures, including sanctions under CharterArticle41. The IMF phrasing keine dauerhafte Lösung also needs an honest conditional limit, not a universal denial of durable effects.', 'Organization headings and major icons survive360, but the false limit is visible in the native and680 versions. The outward front caption is not an actor personal-note orientation error.', 'Vier große Karten vergleichen Rollen und Grenzen von WTO, IWF, Weltbank und UN. Menschen diskutieren Handel, Stabilität, Entwicklung und Zusammenarbeit.', ('q4-institutions-false-absolute-limits', 'Keep the four-role layout; replace the UN absolute by Umsetzung hängt oft von der Mitwirkung der Staaten ab or equivalent accurate conditional wording. Replace the IMF absolute by keine automatische Dauerlösung; Kreditauflagen möglich. No current membership or program-success numerical claims.')),
('REJECT', 'Paris climate goals and sustainability goals are distinguished through goals, funds and an open implementation/evidence question. The SDG card copies the official-style multicolour wheel and pictogram branding, while presenting an incomplete/altered grid; this cannot serve as a faithful official set.', 'The recognizable wheel/grid is visible at native,360 and680. Main economic sequence remains large and useful. Group discussion does not require every decorative card to face all actors simultaneously.', 'Paris-Klimaabkommen und Nachhaltigkeitsziele rahmen eine Diskussion von Zielen, Finanzierung, Umsetzung und Evidenz.', ('q4-sustainability-copied-sdg-branding', 'Replace ONLY the recognizable official-style SDG wheel and grid with neutral abstract sustainability goal motifs. Keep the SDG heading, Paris card and large Ziele/Mittel/Umsetzung sequence; do not invent a labelled official17-goal inventory.')),
('REJECT', 'Market-access restrictions and investment screening are distinct routes with competition, security, resilience and effects to weigh. Permit/conditions/reject are possible decisions, not automatic universal rankings.', 'The detached upper-left SkillPilot / Wirtschaft besser verstehen brand block is a visible watermark, which the hardgate rejects. The main balance, barriers and investment loupe remain readable at360. Abstract map and lined paper do not require reversed personal reading.', 'Menschen wägen wirtschaftliche Chancen und Sicherheitsfragen ab. Marktregeln und die Prüfung von Investitionen stehen als verschiedene Instrumente mit mehreren möglichen Entscheidungen gegenüber.', ('q4-geoeconomics-detached-watermark', 'Remove ONLY the detached upper-left SkillPilot watermark block. Preserve the market-access/screening distinction, people and open balance.')),
('KEEP', 'Voluntary corporate engagement beyond law is distinguished from mandatory risk analysis, prevention/remedy and checking measures. Applicability and actual effects remain explicit questions. The chain is a responsibility motif, not a guarantee of complete legal coverage or success.', 'The physical explanatory display faces the audience; no personal notebook is reversed. Claim, duty and open effects remain recognizable at360 even though subordinate wording is optional. No current statutory thresholds are depicted.', 'Freiwilliges Engagement, Sorgfaltspflichten und offene Wirkungsfragen stehen nebeneinander. Eine Lieferkette verbindet Arbeitsorte, Transport und Verkauf; Menschen fragen nach Anwendungsbereich und tatsächlichen Folgen.', None),
('KEEP', 'Environmental, social and governance criteria are distinct from intended impact and actual evidence. The explicit statement rejects automatic ethical quality from a high ESG score and causal proof from an impact claim. The decorative chart has no measured data values.', 'The foreground cards are outward analytical panels, while the actor has only abstract note lines. Three large headings and icons remain clear at360; small question lists are optional. The arrows structure analysis rather than guarantee impact.', 'Drei große Felder unterscheiden ESG-Kriterien, beabsichtigte Wirkung und Nachweise. Eine Person fragt nach Messung, Grenzen und möglichen anderen Ursachen beobachteter Veränderungen.', None),
('REJECT', 'The main data/control, fairness and accountability lenses are useful and outcomes remain questions. The fictional friendly AI is a conceptual character, not a claim that systems are sentient or automatically neutral. No private data are shown.', 'The background health building carries a recognizable red cross on a white sign, reproducing the distinctive protected/identification emblem rather than a neutral generic health symbol. ICRC source actually read confirms that specific form and function. This logo/emblem defect is bounded; main motifs survive360.', 'Eine fiktive KI-Anwendung verbindet verschiedene Datenarten mit betroffenen Menschen. Drei große Felder fragen nach Datenkontrolle, Fairness, Transparenz und Verantwortung.', ('q4-ai-background-red-cross-emblem', 'Replace ONLY the tiny red-cross-on-white building sign with a neutral heart or clearly different abstract healthcare pictogram. Preserve all good data, fairness, responsibility and affected-person motifs.')),
]

def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p): return str(p.relative_to(ROOT))
def write_new(p,data):
    assert not p.exists(), f'Immutable receipt already exists: {p}'
    p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')

goals=json.loads(GOALS.read_text()); jobs=json.loads((AUTHOR/'jobs.author.json').read_text())
assert len(goals)==len(jobs)==len(READ)==27
assert sha(GOALS)=='b75840950161879e50ce2faa73d53330d4d48ad413b8d6d06d36f910d0d50acf'
assert [g['id'] for g in goals]==[j['goalId'] for j in jobs]
now=datetime.now(timezone.utc).isoformat(); rows=[]
for g,j,(decision,subject,perspective,alt,finding) in zip(goals,jobs,READ):
    gid=g['id']; asset=ROOT/j['candidatePath']; gen=AUTHOR/gid/'generation.actual.json'
    provenance=json.loads(gen.read_text())
    assert provenance['assetSha256'].removeprefix('sha256:')==sha(asset)
    with Image.open(asset) as im: size=im.size; fmt=im.format
    assert fmt=='PNG'
    inspections=[]
    for kind,p in [('native-original',asset),('uncropped-inspection-360',OWN/gid/'inspection-360.png'),('uncropped-inspection-680',OWN/gid/'inspection-680.png')]:
        with Image.open(p) as im: w,h=im.size
        inspections.append({'kind':kind,'path':rel(p),'width':w,'height':h,'sha256':sha(p),'actualViewImage':True,'transformation':'Native unchanged PNG' if kind=='native-original' else 'Proportional LANCZOS inspection derivative only; no production asset edit'})
    openfind=[] if not finding else [{'findingId':finding[0],'status':'open_original_REJECT','actualFinding':subject+' '+perspective,'minimalCorrectionRequest':finding[1]}]
    sources=[]
    if gid=='fed15db6-e700-514d-a65e-6c2a34f1c81a': sources=[{'url':'https://hdr.undp.org/data-center/human-development-index','actualRead':'Main explanation actually read: health, education, living-standard dimensions; no computation or fabricated dataset claim.'}]
    if gid=='e7542590-40e7-5d06-99f3-f295be1f9e12': sources=[{'url':'https://legal.un.org/repertory/art41.shtml','actualRead':'Whole rendered Article41 text actually read2026-10-08; Security Council may order non-force enforcement measures. No current sanctions inventory claim.'},{'url':'https://main.un.org/securitycouncil/en/sanctions/information','actualRead':'Main sanctions explanation actually read2026-10-08; sanctions enforce Council decisions. Published site numerical inventory not relied on.'},{'url':'https://www.imf.org/en/About/Factsheets/IMF-at-a-Glance','actualRead':'Main factsheet actually read;2024/April2025 dated institutional-role concepts only, no current member/finance figures.'},{'url':'https://www.worldbank.org/ext/en/what-we-do','actualRead':'Main roles explanation actually read; project finance, technical assistance and policy support. No claimed current program result.'},{'url':'https://www.wto.org/ENGLISH/thewto_e/thewto_e.htm','actualRead':'Primary search returned role explanation only; direct whatis/what-we-do fetches returned402. No whole fetched WTO page or current rule inventory claimed.'}]
    if gid=='13705b9f-9623-500b-80ba-4574b753a29c': sources=[{'url':'https://sdgs.un.org/goals','actualRead':'Main17 goal titles and implementation explanation actually read; no linked progress reports or current progress numerical claims.'},{'url':'https://unfccc.int/process-and-meetings/the-paris-agreement','actualRead':'Main explanation actually read; distinct treaty/climate-goal/implementation concepts, no numerical current-party or climate-success claim.'}]
    if gid=='36ebee6c-ec32-53e2-a5da-f50185e61a55': sources=[{'url':'https://www.gesetze-im-internet.de/lksg/__3.html','actualRead':'Whole current section3 allthreeparagraphs actually read; appropriate diligence, no guaranteed prevention or unqualified universal applicability. Actual teaching must bind legal cases to supplied dated material.'}]
    if gid=='7a55332e-7c1d-531a-8679-e18592e74ea2': sources=[{'url':'https://www.icrc.org/en/our-emblems','actualRead':'Main emblem form/functions explanation actually read2026-10-08; red cross on white distinctive protective/identification emblem. No complete legal-rights or national-law review claimed.'}]
    receipt={'schemaVersion':1,'reviewId':'wirtschaft-q4-independent-original-image-review-20261008-v1.'+gid,'reviewedAt':now,'reviewer':{'provider':'OpenAI','model':'Codex session; exact model identifier not disclosed','agentIdentity':'/root/economics_layer_a','independentOfImageAuthor':True,'imageAuthor':'/root','authority':'ai_candidate'},'goalId':gid,'currentTitleDe':g['title'],'currentTitleEn':g['titleEn'],'currentDescriptionDe':g['description'],'currentDescriptionEn':g['descriptionEn'],'wholeGoalCandidatePath':rel(GOALS),'wholeGoalCandidateSha256':sha(GOALS),'actualWholeDeEnGoalRead':True,'candidatePath':rel(asset),'assetSha256':sha(asset),'generationReceiptPath':rel(gen),'generationReceiptSha256':sha(gen),'actualGenerator':provenance['provider'],'generatorModelVersion':provenance['modelVersion'],'generationIsNotApproval':True,'nativeBeforeGenerationPreparationReceipt':rel(BEFORE),'nativeBeforeGenerationPreparationReceiptSha256':sha(BEFORE),'actualBeforeGenerationReadingScope':'Shared receipt overview and matching whole goal/context semantics actually read; all27 machine metadata/copy guards checked. No claim of manual reading every long command/import-log object.','inspections':inspections,'formatDecision':{'format':fmt,'nativeDimensions':list(size),'defaultNear16By9':True,'actualDidacticDecision':'Existing wide friendly comic layout retained; three actual uncropped scales seen. New aspect ratio or style overhaul not required.'},'actualSubjectReview':subject,'actualActorPerspectiveAndReadabilityReview':perspective,'actualSourceReferences':sources,'curriculumSourceReading':{'path':'curricula/DE/Gymnasium/input/HE/upper-secondary/kerncurriculum_gymnasiale_oberstufe-wirtschaftswissenschaften.pdf','actualWholeUnitsRead':'Printed/PDF48and49 Q4 introduction and Q4.1–Q4.3 whole units actually read; themes selected by decree, not all universally compulsory. No full multi-jurisdiction mapping coverage or authored-scope projection review claimed.'},'decision':decision,'machineQaStatus':'ai_approved' if decision=='KEEP' else 'rejected_open','aiApproved':'yes' if decision=='KEEP' else 'no','aiApprovedAssetSha256':sha(asset) if decision=='KEEP' else None,'altTextCandidateFromActualMotif':alt,'openFindings':openfind,'humanApprovalClaimed':False,'learnerPerformanceClaimed':False,'liveWrites':0,'newStrictGoalClosures':0,'independentPositiveAtomicityMemoryReviewClaimed':False}
    dest=OWN/gid/'independent-original-image-review.receipt.json';write_new(dest,receipt)
    rows.append({'goalId':gid,'decision':decision,'candidatePath':rel(asset),'assetSha256':sha(asset),'independentReceiptPath':rel(dest),'independentReceiptSha256':sha(dest),'openFindingIds':[x['findingId'] for x in openfind],'minimalCorrectionRequest':finding[1] if finding else None})
summary={'schemaVersion':1,'reviewId':'wirtschaft-q4-independent-original-twenty-seven-image-review-20261008-v1','reviewedAt':now,'reviewerAgent':'/root/economics_layer_a','provider':'OpenAI','model':'Codex session; exact model identifier not disclosed','authority':'ai_candidate','scope':'ALL27originalPNGs, actual81native/360/680views, all27wholeDE/ENgoals; no sampling','counts':{'actuallySeen':27,'actualViews':81,'KEEP':17,'REJECT':10,'openImageFindings':10,'generationByReviewer':0,'liveWrites':0,'strictGoalClosures':0},'finalAll27Approval':False,'historicalOriginalsPreserved':True,'correctionSuccessorsNotYetApproved':True,'rootAgreementAfterIndependentFindingsNotUsedAsReviewEvidence':True,'rows':rows,'humanApprovalClaimed':False,'learnerPerformanceClaimed':False}
assert sum(x['decision']=='KEEP' for x in rows)==17
write_new(OWN/'actual-original-twenty-seven-selection-17KEEP-10REJECT.receipt.json',summary)
write_new(OWN/'actual-original-twenty-seven-alttexts.candidate.json',[{'goalId':g['id'],'altTextCandidateFromActualMotif':v[3],'approvalStatus':v[0]} for g,v in zip(goals,READ)])
print(json.dumps({'records':27,'KEEP':17,'REJECT':10,'summaryPath':rel(OWN/'actual-original-twenty-seven-selection-17KEEP-10REJECT.receipt.json'),'summarySha256':sha(OWN/'actual-original-twenty-seven-selection-17KEEP-10REJECT.receipt.json')},ensure_ascii=False))
