#!/usr/bin/env python3
"""Apache-2.0 serializer; manually authored curricular review text CC-BY-4.0.
Actual blind Q2-19 D-B on frozen Root68. No other D or P verdict consulted.
"""
import hashlib,json
from pathlib import Path
from datetime import datetime,timezone
P=Path(__file__).resolve().parent
B=P.parent/'bundle'
def digest(p):return 'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest()
def new(p,x):
 if p.exists():raise RuntimeError('Preserve existing '+str(p))
 p.parent.mkdir(parents=True,exist_ok=True)
 p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')

# Each seven-field tuple is a manually written judgement after actual whole-page
# reading. No algorithm chooses KEEP, topic, rationale or evidence expectations.
TEXT=[
(
'Konjunkturindikatoren messen unterschiedliche Größen und reagieren zu unterschiedlichen Zeiten. Produktionsniveau und Wachstumsrate, nominale und reale Entwicklung sowie vorlaufende und nachlaufende Signale sind zu unterscheiden. Ein einzelner Wert beweist keine eindeutige Phase des Zyklus.',
'Business-cycle indicators measure different quantities and respond at different times. Production levels and growth rates, nominal and real developments, and leading and lagging signals must be distinguished. A single observation does not establish an unambiguous phase of the cycle.',
'Die lernende Person interpretiert eine bereitgestellte Zeitreihe aus realer Produktion, Beschäftigung, Preisen und Aufträgen. Sie erklärt Einheiten, Zeitraum und zeitliche Beziehungen und begründet eine konjunkturelle Einordnung einschließlich widersprüchlicher Signale, statt bloß steigende Preise mit einem Aufschwung gleichzusetzen.',
'The learner interprets supplied time series for real production, employment, prices and orders. They explain units, period and timing relationships and justify a business-cycle assessment including conflicting signals rather than equating rising prices with an expansion.',
'Eine neue unabhängige Aufgabe liefert nominale Umsätze mit einem Preisindex sowie später reagierende Beschäftigung und rückläufige Aufträge. Die lernende Person erschließt die reale Entwicklung und begründet die neue Einordnung anhand der unterschiedlichen Signalzeiten statt die erste Phasenzuordnung zu übernehmen.',
'A fresh independent task supplies nominal sales with a price index, lagging employment and falling orders. The learner determines the real development and justifies a new assessment using the different signal timings rather than copying the earlier phase classification.',
'KEEP: Indikatorinterpretation und Einordnung im Zyklus sind DE/EN gleichwertig. Die tatsächlich gesehene Seite verbindet Produktion, Beschäftigung und Preise mit einer schematischen Welle, ohne Messwerte oder einen zwingenden Gleichlauf zu behaupten. Modell-, Fiskal- und Phillips-Nachfolger bleiben separate Kompetenzen.'
),
(
'Ein einfaches Konjunkturmodell erklärt eine Wirkungskette unter ausdrücklich angegebenen Annahmen über Nachfrage, Einkommen, Rückkopplung und Anpassung. Modellanwendung unterscheidet exogene Änderungen von endogenen Reaktionen; eine geschlossene Kette ist keine empirische Erfolgsgarantie.',
'A simple business-cycle model explains a causal chain under explicitly stated assumptions about demand, income, feedback and adjustment. Applying a model distinguishes exogenous changes from endogenous responses; a closed chain does not guarantee empirical success.',
'An einem vorgegebenen einfachen Nachfragemodell mit freien Kapazitäten erklärt die lernende Person, wie ein autonomer Rückgang der Ausgaben Produktion und Einkommen verändert und weitere Ausgabenreaktionen auslöst. Sie nutzt die gegebenen Beziehungen und nennt die Bedingungen, von denen die abgeleitete Entwicklung abhängt.',
'Using a supplied simple demand model with spare capacity, the learner explains how an autonomous fall in expenditure changes production and income and produces further expenditure responses. They apply the given relationships and identify the conditions on which the derived development depends.',
'Eine neue unabhängige Aufgabe gibt statt des Nachfrageimpulses eine veränderte Kreditbedingung und andere Kapazitätsannahmen vor. Die lernende Person wendet das dazu bereitgestellte einfache Modell an, rekonstruiert die neue Wirkungskette und begründet, welche Aussagen des ersten Modells nicht unverändert übertragbar sind.',
'A fresh independent task replaces the demand impulse with changed credit conditions and different capacity assumptions. The learner applies the corresponding supplied simple model, reconstructs the new causal chain and explains which statements from the first model cannot be transferred unchanged.',
'KEEP: Einfache Modelle zur Konjunkturanalyse sind gleichbedeutend übersetzt. Haushalt-Unternehmen-Rückkopplung und offene staatliche Rolle sind tatsächlich sichtbar; das Bild schreibt kein universelles Modell vor. Der LK-Kontext und die Erwartungsbildungs-Nachfolge werden respektiert; keine zusätzliche ganze Modelltheorie wird eingeführt.'
),
(
'Fiskalpolitische Instrumente verändern öffentliche Ausgaben, Steuern oder Transfers und damit Nachfrage und öffentliche Finanzen. Ihre Bewertung im Konjunkturverlauf verbindet Wirkungsketten, automatische und diskretionäre Reaktionen, zeitliche Verzögerung und mögliche Nebenfolgen unter den jeweiligen Kapazitätsbedingungen.',
'Fiscal instruments change public expenditure, taxes or transfers and thereby demand and public finances. Evaluating them over the business cycle connects causal chains, automatic and discretionary responses, delays and possible side effects under the relevant capacity conditions.',
'Für einen bereitgestellten Abschwung mit freien Kapazitäten bewertet die lernende Person ein öffentliches Reparaturprogramm gegenüber einer befristeten Steuerentlastung. Sie begründet die Nachfragekanäle, zeitliche Umsetzung und Verteilungs- oder Finanzierungsfolgen anhand der Fallangaben und unterscheidet erwartete von gesicherten Wirkungen.',
'For a supplied downturn with spare capacity, the learner evaluates a public repair programme against temporary tax relief. They explain demand channels, implementation timing and distributional or funding consequences using the case information and distinguish expected from established effects.',
'Eine neue unabhängige Aufgabe stellt eine hoch ausgelastete Wirtschaft mit Preisdruck und bereits verzögert anlaufenden Ausgaben gegenüber. Die lernende Person bewertet die vorgegebenen Fiskalinstrumente neu und begründet, weshalb ein zuvor plausibler expansiver Impuls unter diesen Bedingungen andere Vorteile und Risiken besitzt.',
'A fresh independent task presents a highly utilised economy with price pressure and expenditure already starting after a delay. The learner reassesses the stipulated fiscal instruments and explains why a previously plausible expansionary impulse has different benefits and risks under these conditions.',
'KEEP: DE/EN erhalten die Bewertung fiskalpolitischer Instrumente im Zyklus. Ruhige und beschäftigte Werkstätten, öffentliche Reparatur und Zeit-/Verschuldungsmotive sind passend dargestellt; die offene Abwägung behauptet keinen sicheren Ertrag. Multiplikatormodellierung bleibt beim spezifischen LK-Nachfolger.'
),
(
'Konjunkturprognosen beruhen auf Daten, Ansätzen und Annahmen mit begrenzter Aussagekraft. Bedingte Szenarien sind von einem statistischen Unsicherheitsintervall zu unterscheiden. Datenrevision, Schocks und ein veränderter Prognosehorizont können die Einschätzung beeinflussen.',
'Business-cycle forecasts rest on data, approaches and assumptions with limited predictive power. Conditional scenarios differ from statistical uncertainty intervals. Data revisions, shocks and a changed forecast horizon can affect an assessment.',
'Die lernende Person bewertet zwei bereitgestellte Prognosen desselben realen Indikators, deren Datenstände, Ansätze, Horizonte und Annahmen dokumentiert sind. Sie erklärt unterschiedliche Ergebnisse und Unsicherheiten und prüft, ob die angegebenen Bänder statistische Intervalle oder alternative bedingte Szenarien darstellen.',
'The learner evaluates two supplied forecasts of the same real indicator with documented data vintages, approaches, horizons and assumptions. They explain differing results and uncertainties and check whether the stated bands are statistical intervals or alternative conditional scenarios.',
'Eine neue unabhängige Aufgabe liefert eine Prognoserevision nach einem unerwarteten Handelsschock und geänderte Daten. Die lernende Person beurteilt den neuen Ansatz und die Unsicherheit und begründet, welche Annahmeänderung die Revision erklärt und weshalb der frühere Punktwert keine sichere Zusage war.',
'A fresh independent task supplies a forecast revision after an unexpected trade shock and changed data. The learner assesses the new approach and uncertainty, explains which changed assumptions account for the revision and why the earlier point estimate was not a certainty.',
'KEEP: Prognoseansätze UND Unsicherheiten bleiben bilingual vollständig. Die tatsächlich betrachtete Seite trennt Vergangenheit und drei gestrichelte Szenarien; diese werden nicht als berechnetes Konfidenzintervall ausgegeben. Fiskalpolitischer Vorgänger und Stabilitätsziele-Nachfolger verändern die Prognosekompetenz nicht.'
),
(
'Die vier Ziele des Stabilitäts- und Wachstumsgesetzes betreffen Preisniveaustabilität, hohen Beschäftigungsstand, außenwirtschaftliches Gleichgewicht sowie stetiges und angemessenes Wachstum. Anwendung prüft alle vier gemeinsam am Fall und unterscheidet Zielkonflikte von Zielharmonien; maximaler Überschuss oder Boom ist keine automatische Zielerreichung.',
'The four objectives of the German Stability and Growth Act concern price stability, high employment, external economic balance and steady, appropriate growth. Application considers all four together in a case and distinguishes conflicts from mutually supportive objectives; a maximum surplus or boom does not automatically meet them.',
'Die lernende Person wendet die vier Ziele auf einen bereitgestellten Datensatz mit schwachem realem Wachstum, steigender Arbeitslosigkeit, höherer Inflation und außenwirtschaftlicher Ungleichgewichtigkeit an. Sie ordnet die Befunde begründet den Zielen zu und erläutert mögliche Zielbeziehungen bei einer vorgeschlagenen Maßnahme.',
'The learner applies the four objectives to supplied data showing weak real growth, rising unemployment, higher inflation and external imbalance. They explain how the findings relate to the objectives and discuss possible relationships among objectives for a proposed measure.',
'Eine neue unabhängige Aufgabe beschreibt starkes Wachstum mit Kapazitätsengpässen, niedrigem Beschäftigungszuwachs und hohem Außenüberschuss. Die lernende Person prüft erneut alle vier Ziele und begründet, weshalb positive Einzelwerte das gesamtwirtschaftliche Gleichgewicht weder beweisen noch alle Zielkonflikte aufheben.',
'A fresh independent task describes strong growth with capacity constraints, little employment growth and a large external surplus. The learner rechecks all four objectives and explains why positive individual observations neither establish overall equilibrium nor remove every conflict.',
'KEEP: Der gesetzliche Zielbezug und die Fallanwendung sind DE/EN korrekt. Die tatsächlich gesehene Seite umfasst vier gleichrangige Zielmotive mit offenen Beziehungen. StabG§1 wurde aktuell vollständig gelesen; Rechtsanwendung wird nicht mit dem EU-Stabilitäts- und Wachstumspakt verwechselt.'
),
(
'Nationale und EU-Fiskalregeln besitzen unterschiedliche Zuständigkeiten, Bezugsgrößen, Kontrollverfahren und Ausnahmen. Die Schuldenbremse ist anhand datierter aktueller Materialien zu beurteilen; weder pauschale Länder-Nullverschuldung noch eine automatische Sanktion beim Überschreiten eines EU-Referenzwerts ist als allgemeine Regel vorauszusetzen.',
'National and EU fiscal rules have different responsibilities, reference measures, monitoring procedures and exceptions. The debt brake must be assessed using dated current material; neither blanket zero borrowing by states nor automatic sanctions for exceeding an EU reference value can be assumed as a general rule.',
'Mit bereitgestellten datierten Auszügen aus Grundgesetz und EU-Fiskalrahmen diskutiert die lernende Person ein fiktives Budget mit konjunktureller Abschwächung und geplanten Investitionen. Sie trennt nationale Berechnung und Spielräume von EU-Ausgabenpfad und Verfahren und begründet Chancen und Grenzen unter den tatsächlich genannten Bedingungen.',
'Using supplied dated extracts from the Basic Law and EU fiscal framework, the learner discusses a fictional budget during an economic slowdown with planned investment. They distinguish national calculations and scope from the EU expenditure path and procedure and explain opportunities and limits under the conditions actually stated.',
'Eine neue unabhängige Aufgabe betrifft ein anderes Haushaltsniveau und eine ausdrücklich im neuen Material beschriebene außergewöhnliche Situation mit Verfahrens- und Rückführungsbedingungen. Die lernende Person diskutiert deren Bedeutung getrennt für nationale und EU-Regeln; Ausnahmen oder Sanktionen werden nicht aus dem ersten Fall übernommen.',
'A fresh independent task concerns a different level of government and an exceptional situation expressly described in new material with procedural and repayment conditions. The learner discusses its significance separately for national and EU rules without importing exceptions or sanctions from the first case.',
'KEEP: Nationale UND EU-Regeln werden in beiden Sprachen genannt; der Titel bindet die Schuldenbremse. Die tatsächliche Seite enthält Prüfung und Spielräume ohne veraltete Zahlenbehauptung. Aktuelle Art109/115 und die amtliche EU-Übersicht wurden nachgelesen; genaue Fallnormen bleiben datiert und bereitgestellt, kein persönliches Rechtsurteil.'
),
(
'Ein Instrumentenmix verbindet Geld-, Fiskal- und Ordnungspolitik mit unterschiedlichen Übertragungswegen, Zuständigkeiten und Zeithorizonten. Gemeinsame Beurteilung prüft ergänzende, widersprüchliche und überlappende Wirkungen unter den angegebenen Bedingungen; gleiche Wirkungen werden nicht doppelt gezählt.',
'An instrument mix connects monetary, fiscal and economic-framework policy with different transmission channels, responsibilities and time horizons. Joint evaluation considers complementary, conflicting and overlapping effects under the stated conditions without counting the same effect twice.',
'Für eine bereitgestellte schwache Konjunktur beurteilt die lernende Person gemeinsam eine Zinsmaßnahme, einen öffentlichen Investitionsimpuls und eine Änderung von Marktzugangsregeln. Sie erklärt für alle drei Instrumente Kanäle, Verzögerungen und Grenzen sowie ihr Zusammenwirken, statt drei isolierte Erfolgserwartungen zu addieren.',
'For a supplied weak economy, the learner jointly evaluates an interest-rate measure, public investment and a change in market-entry rules. For all three instruments they explain channels, delays and limits and their interaction rather than adding three isolated expectations of success.',
'Eine neue unabhängige Aufgabe gibt einen Angebotsschock, Preisdruck und eingeschränkte Fiskalspielräume vor. Die lernende Person beurteilt einen neuen Mix aus allen drei Politikarten unter diesen Bedingungen und begründet veränderte Zielkonflikte und Wechselwirkungen gegenüber dem nachfragearmen Ausgangsfall.',
'A fresh independent task stipulates a supply shock, price pressure and limited fiscal scope. The learner evaluates a new mix containing all three policy types under those conditions and explains changed trade-offs and interactions compared with the initial low-demand case.',
'KEEP: Alle drei ausdrücklich behaupteten Politikarten sind DE/EN erhalten; economic-framework policy übersetzt Ordnungspolitik passend. Die tatsächlich gesehene Seite zeigt drei getrennte Stationen mit offenen Wirkungspfeilen. Die LK-Bindung und das externe Q2-Assessment belegen keine real getestete Politik oder effektive Scope-Projektion.'
),
(
'Eine kurzfristige Phillips-Kurve beschreibt unter Modellbedingungen eine Beziehung zwischen Inflation und Arbeitslosigkeit. Nachfragebedingte Bewegungen auf einer Kurve sind von Verschiebungen durch Erwartungen oder Angebotsbedingungen zu trennen. Der kurzfristige Zielkonflikt ist keine zeitlose, sicher wählbare Austauschrelation.',
'A short-run Phillips curve describes a relationship between inflation and unemployment under model conditions. Demand-related movements along a curve differ from shifts due to expectations or supply conditions. The short-term trade-off is not a timeless exchange that policymakers can choose with certainty.',
'Für eine vorgegebene kurzfristige Phillips-Kurve mit festgehaltenen Erwartungen analysiert die lernende Person eine Nachfrageausweitung und den verbundenen Zielkonflikt. Sie erläutert Richtung und Modellbedingungen der Bewegung und begründet die Grenzen einer aus der Grafik abgeleiteten stabilisierungspolitischen Empfehlung.',
'For a supplied short-run Phillips curve with fixed expectations, the learner analyses an expansion of demand and the related policy trade-off. They explain the direction and conditions of movement and the limits of a stabilisation recommendation derived from the graph.',
'Eine neue unabhängige Aufgabe beschreibt einen Kosten-/Angebotsschock mit verändertem Inflationsdruck und liefert eine verschobene Kurve. Die lernende Person analysiert den neuen Zielkonflikt und erklärt, weshalb dieser Fall nicht als dieselbe Bewegung auf der ursprünglichen Kurve behandelt werden darf.',
'A fresh independent task describes a cost or supply shock with changed inflation pressure and supplies a shifted curve. The learner analyses the new trade-off and explains why this case cannot be treated as the same movement along the original curve.',
'KEEP: Der ausdrückliche kurzfristige Bezug vermeidet eine unbedingte Dauerrelation; DE/EN sind äquivalent. Die tatsächliche Waagenillustration zeigt Preise/Beschäftigung und offene Angebots-/Kosten-/Erwartungsbedingungen. Sie ersetzt keine Phillips-Grafik oder Leistungsevidenz; der NAIRU-Nachfolger bleibt eine weitere Kompetenz.'
),
(
'NAIRU bezeichnet eine modellabhängig geschätzte Arbeitslosenquote, die unter entsprechenden Bedingungen mit nicht beschleunigter Inflation vereinbar ist. Sie ist weder direkt sicher beobachtet noch ein moralisch erwünschter Arbeitslosigkeitswert. Ihre Bedeutung für Geld- und Fiskalentscheidungen hängt auch von Schätzunsicherheit und anderen Inflationsursachen ab.',
'NAIRU is a model-dependent estimate of an unemployment rate consistent, under the relevant conditions, with non-accelerating inflation. It is neither directly observed with certainty nor a morally desirable unemployment level. Its significance for monetary and fiscal decisions depends on estimation uncertainty and other causes of inflation.',
'An einem bereitgestellten Fall mit Arbeitslosenquote, NAIRU-Schätzbereich, Inflation und Nachfragedaten begründet die lernende Person die Bedeutung der Schätzung für eine geldpolitische und eine fiskalpolitische Entscheidung. Sie erläutert modellbedingten Preisdruck, alternative Erklärungen und das Risiko einer fehlerhaften Einschätzung.',
'For a supplied case with unemployment, an estimated NAIRU range, inflation and demand data, the learner explains the estimate’s significance for a monetary and a fiscal decision. They discuss model-based price pressure, alternative explanations and the risk of an incorrect assessment.',
'Eine neue unabhängige Aufgabe verändert Matchingbedingungen und liefert neue, unsichere Schätzungen sowie einen externen Kostenimpuls. Die lernende Person begründet die Bedeutung für beide Politikarten erneut und erklärt, weshalb die alte Schätzung oder beobachtete Inflation allein keine eindeutige Handlung vorgibt.',
'A fresh independent task changes matching conditions and supplies new uncertain estimates and an external cost impulse. The learner reassesses the implications for both policy types and explains why the old estimate or observed inflation alone does not dictate one action.',
'KEEP: Geld- UND fiskalpolitische Bedeutung ist bilingual vollständig. Die tatsächliche Seite zeigt Schätzung und Unsicherheitsband statt einer garantierten Schwelle. Der tatsächlich gelesene historische amtliche Forschungsabstract bestätigt die Schätzproblematik; keine aktuellen NAIRU-Werte oder normative Optimalquote werden behauptet.'
),
(
'Fiskalische Multiplikatoren folgen aus Rückkopplungen eines vorgegebenen Modells und ändern sich durch Spar-, Steuer- oder Importabflüsse. Crowding-Out kann den autonomen privaten Impuls vermindern und ist vor der Rückkopplung korrekt zu berücksichtigen. Modellwerte sind von beobachteten universellen Effekten zu trennen.',
'Fiscal multipliers follow from feedback in a specified model and change with saving, tax or import leakages. Crowding out can reduce the autonomous private impulse and must be incorporated correctly before feedback. Model values differ from universally observed effects.',
'Für das ausdrücklich vereinfachte Modell Y=C+I+G mit C=20+0,8Y modelliert die lernende Person eine Erhöhung von G um 10 und eine vorgegebene autonome Senkung von I um 2. Sie leitet den Multiplikator 5 und die Nettoänderung von Y um 40 aus dem Gesamtimpuls 8 ab und bewertet Annahmen und Grenzen.',
'For the explicitly simplified model Y=C+I+G with C=20+0.8Y, the learner models a rise in G of 10 and a stipulated autonomous fall in I of 2. They derive a multiplier of 5 and a net change in Y of 40 from the overall impulse of 8 and evaluate assumptions and limits.',
'Eine neue unabhängige Aufgabe gibt C=20+0,8(1−0,25)Y, M=0,1Y und Y=C+I+G−M mit gleichem staatlichem und privatem autonomen Impuls vor. Die lernende Person leitet den Multiplikator 2 und die Nettoänderung 16 neu ab und erklärt den Einfluss der Steuer-/Importabflüsse statt eine einmalige Verdrängung erst nach der Multiplikation abzuziehen.',
'A fresh independent task supplies C=20+0.8(1−0.25)Y, M=0.1Y and Y=C+I+G−M with the same government and private autonomous impulses. The learner derives a multiplier of 2 and net change of 16 and explains the tax and import leakages rather than subtracting displacement only after multiplication.',
'KEEP: Modellieren UND Bewerten beider Effekte ist in DE/EN erhalten. Die tatsächliche Seite zeigt Ausgabenfolgen und mögliche Verdrängung mit Fragezeichen, keinen garantierten festen Multiplikator. Die hier neu formulierten Rechnungen wurden vollständig nachgerechnet; sie sind keine behaupteten oder geprüften P19-Fälle.'
),
(
'Adaptive Erwartungsbildung orientiert sich an vergangenen Erfahrungen; rationale Erwartungen nutzen im Modell verfügbare Informationen und die erwarteten Zusammenhänge. Rationale Erwartungen bedeuten keine fehlerfreie Voraussicht. Politikglaubwürdigkeit beeinflusst, wie Ankündigungen Erwartungen und Entscheidungen verändern können.',
'Adaptive expectation formation draws on past experience; rational expectations use available information and anticipated relationships within the model. Rational expectations do not mean perfect foresight. Policy credibility affects how announcements may change expectations and decisions.',
'Die lernende Person unterscheidet in einem bereitgestellten Inflationsfall vergangenheitsorientierte Anpassung von einer Erwartungsbildung, die neue Informationen über eine angekündigte Politik berücksichtigt. Sie erklärt Auswirkungen unterschiedlicher Glaubwürdigkeit auf Preise, Löhne oder Nachfrage unter den genannten Annahmen und benennt verbleibende Unsicherheit.',
'In a supplied inflation case, the learner distinguishes backward-looking adjustment from expectation formation incorporating new information about announced policy. They explain effects of differing credibility on prices, wages or demand under the stated assumptions and identify remaining uncertainty.',
'Eine neue unabhängige Aufgabe enthält gleichartige Ankündigungen, aber einen geänderten institutionellen Rahmen und frühere Nichteinhaltung. Die lernende Person erklärt die neuen Erwartungsreaktionen und stabilisierungspolitischen Folgen, ohne Information mit Glaubwürdigkeit oder rationale Erwartungen mit sicherem Politikversagen gleichzusetzen.',
'A fresh independent task contains similar announcements but a changed institutional framework and previous non-compliance. The learner explains new expectation responses and stabilisation implications without equating information with credibility or rational expectations with certain policy failure.',
'KEEP: Die Unterscheidung UND ihre Rolle für Stabilisierungspolitik bleiben bilingual. Die tatsächlich gesehene Seite ergänzt vergangene Erfahrungen durch weitere Informationen und lässt beide Zukunftsausgänge offen; damit wird rationale Erwartung nicht als Hellseherei abgebildet. Der Modell-Vorgänger liefert einen passenden LK-Kontext.'
),
(
'Wettbewerbsordnung stellt Instrumente bereit, um Wettbewerbsbeschränkung oder missbräuchliche Marktmacht zu begrenzen und Marktzugang zu sichern. Begründung verbindet ein konkretes Wettbewerbsproblem mit dem passenden Wirkungsmechanismus; Unternehmensgröße allein beweist keinen Missbrauch und jede Intervention besitzt Bedingungen und Grenzen.',
'A competition framework provides instruments to limit restrictions of competition or abuse of market power and preserve entry. Justification connects a concrete competition problem with the appropriate mechanism; firm size alone does not establish abuse, and every intervention has conditions and limits.',
'In einem fiktiven Markt mit bereitgestellten Angaben über Zugangsschranken und Ausschlusspraktiken begründet die lernende Person geeignete wettbewerbliche Instrumente anhand aktueller datierter Materialien. Sie erklärt, welches Problem eine Maßnahme adressiert, welche Alternativen bestehen und welche Zusatzinformationen für die Prüfung nötig sind.',
'In a fictional market with supplied information about barriers to entry and exclusionary practices, the learner justifies appropriate competition instruments using current dated material. They explain the problem addressed, available alternatives and further information needed for assessment.',
'Eine neue unabhängige Aufgabe beschreibt ein großes Unternehmen mit niedrigen Zugangsschranken und nachvollziehbaren Effizienzvorteilen. Die lernende Person prüft neu, welche Instrumente sachlich begründbar sind und weshalb dieselbe Größe ohne die ursprünglichen Einschränkungen kein identisches Eingreifen rechtfertigt.',
'A fresh independent task describes a large firm with low entry barriers and substantiated efficiency benefits. The learner reassesses which instruments are justified and why similar size without the original restrictions does not justify identical intervention.',
'KEEP: Instrumente gegen Marktmacht begründen ist DE/EN gleichwertig und als grundlegende Kompetenz von den spezifischen LK-Prüfungen abgegrenzt. Die tatsächlich gesehene Seite stellt Größe, Kooperation, Fusion und Zugang unter offene Prüfzeichen; Größe wird nicht mit einem nachgewiesenen Rechtsverstoß gleichgesetzt.'
),
(
'Ordnungspolitische Denkschulen unterscheiden sich in Annahmen zu Marktkoordination, staatlichen Aufgaben und angemessenen Regeln oder Maßnahmen. Kritischer Vergleich erklärt die jeweilige Begründung, prüft Bedingungen und Gegenargumente und trennt empirische Wirkungsbehauptungen von normativen Prioritäten.',
'Schools of thought on the economic framework differ in assumptions about market coordination, state responsibilities and appropriate rules or measures. Critical comparison explains each rationale, tests conditions and counterarguments and separates empirical effect claims from normative priorities.',
'Für einen bereitgestellten Fall mit schwacher Investition und Marktzugangshürden diskutiert die lernende Person zwei ausdrücklich beschriebene Denkschulen und deren Maßnahmen. Sie rekonstruiert die verschiedenen Mechanismen und staatlichen Rollen und begründet eine Bewertung mit offengelegten Annahmen und möglichen Gegenargumenten.',
'For a supplied case with weak investment and entry barriers, the learner discusses two expressly described schools and their measures. They reconstruct the different mechanisms and state roles and justify an assessment with explicit assumptions and possible counterarguments.',
'Eine neue unabhängige Aufgabe ändert das Problem zu knappem Angebot und monopolisiertem Zugang und liefert andere Maßnahmen derselben Schulen. Die lernende Person vergleicht ihre Eignung unter den neuen Bedingungen und begründet, weshalb ein allgemeines Schuletikett allein keine fallunabhängige Lösung ergibt.',
'A fresh independent task changes the problem to constrained supply and monopolised access and supplies other measures from the same schools. The learner compares their suitability under the new conditions and explains why a school’s label alone does not yield a case-independent solution.',
'KEEP: Kritische Diskussion von Schulen UND Maßnahmen bleibt vollständig äquivalent. Markt-, Nachfrage- und Ordnungsmotive auf der tatsächlichen Seite dienen als offene Vergleichsimpulse, keine pauschale Zuordnung jeder Schule zu nur einem Instrument. Nachhaltigkeit, Intervention und Industriepolitik bleiben gezielte Nachfolger.'
),
(
'Nachhaltigkeitsziele verbinden ökologische, soziale und wirtschaftliche Anforderungen mit dem institutionellen Ordnungsrahmen. Integration benennt prüfbare Zielgrößen und Regeln sowie Zielkonflikte und Verteilung. Sinkende Belastung je Produktionseinheit beweist bei wachsender Menge keine sinkende absolute Umweltbelastung.',
'Sustainability objectives connect environmental, social and economic requirements with the institutional framework. Integration identifies assessable objectives and rules, trade-offs and distribution. A lower burden per unit does not establish lower absolute environmental pressure when output increases.',
'Die lernende Person integriert vorgegebene Umwelt-, Teilhabe- und wirtschaftliche Ziele in einen fiktiven ordnungspolitischen Ansatz. Sie begründet geeignete Regeln, nachvollziehbare Indikatoren und Kontrollbedingungen und prüft anhand bereitgestellter Produktions- und Belastungsdaten sowohl Intensität als auch absolute Wirkung.',
'The learner integrates supplied environmental, participation and economic objectives into a fictional economic-framework approach. They justify suitable rules, transparent indicators and monitoring conditions and use supplied output and burden data to assess both intensity and absolute effects.',
'Eine neue unabhängige Aufgabe verbindet effizientere Produktion mit höherer Nachfrage und ungleichen Anpassungskosten. Die lernende Person integriert die Ziele unter diesen neuen Bedingungen erneut und erklärt, welche Regeln und Erfolgsindikatoren erforderlich sind, damit eine Intensitätsverbesserung nicht als vollständiger Nachhaltigkeitsnachweis ausgegeben wird.',
'A fresh independent task combines more efficient production with higher demand and unequal adjustment costs. The learner reintegrates the objectives under those conditions and explains which rules and success indicators are needed so an intensity improvement is not presented as complete evidence of sustainability.',
'KEEP: Nachhaltigkeitsziele in ordnungspolitische Konzepte integrieren ist bilingual vollständig. Die tatsächliche Seite verbindet ökologische, soziale und wirtschaftliche Motive mit einer offenen Prüfung; keine automatische Harmonie wird behauptet. Folgenabschätzung des Instrumentenmixes bleibt die spezifische Nachfolgekompetenz.'
),
(
'Kartellrechtliche Prüfung von Vereinbarungen und Kontrolle geplanter Zusammenschlüsse betreffen unterschiedliche Gegenstände und Verfahren. Bewertung nutzt den angegebenen Markt, Wettbewerbswirkungen, Belege und rechtliche Kriterien. Gleichpreise, Kooperation oder Größe allein beweisen keinen Verstoß; eine Fusion kann freigegeben, mit Bedingungen freigegeben oder untersagt werden.',
'Antitrust assessment of agreements and control of proposed mergers concern different objects and procedures. Evaluation uses the specified market, competitive effects, evidence and legal criteria. Equal prices, cooperation or size alone do not establish infringement; a merger may be cleared, conditionally cleared or prohibited.',
'An zwei bereitgestellten Teilfällen bewertet die lernende Person eine dokumentierte wettbewerbsbeschränkende Absprache und einen geplanten Zusammenschluss anhand datierter aktueller Materialien. Sie trennt Prüfgegenstände und Verfahren, begründet die Bedeutung von Marktdefinition, Zugang, Effizienzen und möglichen Auflagen und nennt verbleibenden Ermittlungsbedarf.',
'For two supplied subcases, the learner evaluates a documented restrictive agreement and a proposed merger using dated current material. They distinguish objects and procedures, explain the relevance of market definition, entry, efficiencies and possible remedies and identify further investigation needed.',
'Eine neue unabhängige Aufgabe gibt parallele Preise ohne nachgewiesene Absprache sowie eine andere Fusion mit veränderten Zugangshürden und prüfbaren Zusagen vor. Die lernende Person bewertet beide Vorgänge neu und begründet, weshalb identische Preise beziehungsweise Größe die frühere rechtliche Schlussfolgerung nicht automatisch tragen.',
'A fresh independent task supplies parallel prices without proven agreement and another merger with changed entry barriers and verifiable commitments. The learner reassesses both matters and explains why identical prices or size do not automatically support the earlier legal conclusion.',
'KEEP: DE/EN erhalten beide ausdrücklich benannten Prüfformen; antitrust assessments erweitert kartellrechtlich nicht. Die tatsächlich gesehene finale Seite trennt Handschlagprüfung von Fusionskontrolle; deren drei Ausgänge sind echte Alternativen, und bei Untersagung bleiben zwei Läden getrennt. Keine konkrete Fusion wird allein aus dem Bild freigegeben.'
),
(
'Staatliche Eingriffe können auf konkrete Marktprobleme reagieren, schaffen aber ebenfalls Informations-, Anreiz-, Kontroll- und Verteilungsprobleme. Abwägung vergleicht Wirkungsmechanismen, realistische Alternativen und Nebenfolgen; weder Markt noch Staat ist unabhängig von Fallbedingungen pauschal überlegen.',
'State intervention can respond to particular market problems while also creating information, incentive, monitoring and distributional problems. Evaluation compares mechanisms, realistic alternatives and side effects; neither markets nor the state are unconditionally superior.',
'Für einen bereitgestellten Markt mit externen Umweltkosten wägt die lernende Person eine Abgabe und eine Regelung gegenüber dem bestehenden Zustand ab. Sie erklärt Ziele, Anreize, Durchsetzung, Verteilung und mögliche Fehlwirkungen anhand der Fallangaben und begründet ein Urteil mit zulässigen Gegenpositionen.',
'For a supplied market with external environmental costs, the learner weighs a levy and a rule against the existing situation. They explain objectives, incentives, enforcement, distribution and possible adverse effects using the case information and justify a judgement allowing counterpositions.',
'Eine neue unabhängige Aufgabe verändert das Problem zu fehlendem Infrastrukturzugang und gibt eingeschränkte öffentliche Kontrollmöglichkeiten vor. Die lernende Person wägt Chancen und Grenzen passender Eingriffe neu gegen realistische marktliche Alternativen ab und begründet, welche vorherigen Argumente hier nicht ausreichen.',
'A fresh independent task changes the problem to inadequate infrastructure access and stipulates limited public monitoring capacity. The learner weighs suitable interventions against realistic market alternatives and explains which earlier arguments are insufficient in this setting.',
'KEEP: Chancen UND Grenzen staatlicher Eingriffe bleiben DE/EN vollständig. Die tatsächlich betrachtete Seite zeigt Infrastruktur, Ordnungsrahmen und Förderung unter Ziel-/Wirkungs-/Nebenfolgenfragen; die Waage verordnet keine generelle richtige Seite. Der Vergleichsvorgänger liefert Maßstäbe statt einer zwingenden politischen Präferenz.'
),
(
'Digitale Plattformmärkte können mehrere Nutzergruppen, Netzwerkeffekte, Datenvorteile und Wechsel- oder Zugangskosten verbinden. Bewertung kartellrechtlicher Optionen erklärt konkrete Wettbewerbswirkungen und den einschlägigen Regelrahmen. Ein kostenloser Dienst beweist weder fehlenden Markt noch automatisch Missbrauch; sektorale Pflichten sind von einer konkreten Missbrauchsfeststellung zu unterscheiden.',
'Digital platform markets can connect several user groups, network effects, data advantages and switching or entry costs. Evaluating antitrust options explains specific competitive effects and the applicable framework. A free service establishes neither absence of a market nor automatic abuse; sectoral obligations differ from a finding of particular abusive conduct.',
'In einem bereitgestellten fiktiven Plattformfall erklärt die lernende Person die Verknüpfung von Anbietern und Nutzern sowie Daten-, Netzwerk- und Wechselmechanismen. Anhand aktueller datierter Materialien bewertet sie begründete kartellrechtliche Optionen, mögliche Zugangswirkungen und Grenzen und benennt fehlende Nachweise für einen konkreten Verstoß.',
'In a supplied fictional platform case, the learner explains connections between businesses and users and the data, network and switching mechanisms. Using current dated material, they evaluate justified antitrust options, possible effects on access and limits and identify missing evidence of a specific infringement.',
'Eine neue unabhängige Aufgabe bietet geringe Wechselkosten und Mehrfachnutzung, aber eine andere Ausschlusspraxis bei einem monetär kostenlosen Dienst. Die lernende Person bewertet die veränderten Wettbewerbsbedingungen und Optionen neu und trennt behauptete Vorteile, belastbare Beschränkungen und rechtlichen Prüfbedarf.',
'A fresh independent task presents low switching costs and multi-homing but a different exclusionary practice in a service with no monetary price. The learner reassesses competition conditions and options, distinguishing claimed advantages, supported restrictions and the need for legal investigation.',
'KEEP: Plattformbesonderheiten UND kartellrechtliche Optionen bleiben bilingual. Die tatsächliche Seite zeigt mehrere Zugänge, Nutzer, Daten und Wechsel als offene Prüfung. Aktuelle amtliche DMA-Erläuterung wurde gelesen; die illustrative Wechselmöglichkeit wird nicht als universell leichte reale Portabilität oder als bewiesene Rechtsverletzung ausgegeben.'
),
(
'Industriepolitische Subventionen und Standortmaßnahmen verändern selektiv oder allgemein Produktions- und Investitionsbedingungen. Ordnungspolitische Einordnung erklärt Eingriffsform, Anreiz, Wettbewerbs- und Verteilungsbezug sowie Prüfbedingungen; ein Förderzweck beweist weder zusätzliche Wirkung noch rechtliche Zulässigkeit.',
'Industrial subsidies and location measures alter production and investment conditions selectively or generally. Classification within the economic framework explains the form of intervention, incentives, competition, distribution and assessment conditions; a policy objective proves neither additional effects nor legal permissibility.',
'Für einen bereitgestellten Fall ordnet die lernende Person allgemeine Infrastruktur- und Qualifikationsmaßnahmen sowie einen selektiven Unternehmenszuschuss ordnungspolitisch ein. Sie erklärt Unterschiede in Zugang, Anreizen, Kosten und Wettbewerbswirkungen und prüft die behauptete zusätzliche Investition anhand des vorgegebenen Vergleichsszenarios.',
'For a supplied case, the learner classifies general infrastructure and training measures and a selective firm subsidy within the economic framework. They explain differences in access, incentives, costs and competition and assess claimed additional investment against the supplied counterfactual.',
'Eine neue unabhängige Aufgabe beschreibt eine bereits ohnehin geplante Investition mit anderer Standortentscheidung und veränderten Kontrollbedingungen. Die lernende Person ordnet die Eingriffe erneut ein, begründet zusätzliche oder bloße Mitnahmeeffekte und trennt das ordnungspolitische Urteil von einer nur anhand aktueller Fallnormen möglichen Beihilfeprüfung.',
'A fresh independent task describes an investment already planned without support, a different location decision and changed monitoring conditions. The learner reclassifies the interventions, explains additional or windfall effects and separates the economic-framework judgement from an aid assessment requiring current case provisions.',
'KEEP: Subventionen UND Standortpolitik sind in DE/EN erhalten; Einordnen wird nicht still zu einer ganzen Rechtsfreigabe erweitert. Die tatsächliche Seite zeigt Standortbedingungen, Förderung und offene Nutzen-/Kosten-/Umweltabwägung. Ein Prüfbogen im Bild behauptet keine bereits nachgewiesene Zusatzinvestition oder Zulässigkeit.'
),
(
'Ein Regulierungsmix kombiniert Instrumente mit unterschiedlichen Anreizen, Informationen, Pflichten und Kontrollbedingungen. Folgenabschätzung verbindet diese Mechanismen mit Zielerreichung, Kosten, Verteilung und unbeabsichtigten Wirkungen. Ergänzungen und Überschneidungen sind zu prüfen; dieselbe Wirkung darf nicht zweimal als Nutzen gerechnet werden.',
'A regulatory mix combines instruments with different incentives, information, obligations and monitoring conditions. Impact assessment connects those mechanisms with objectives, costs, distribution and unintended effects. Complementarities and overlap must be assessed without counting the same effect twice as a benefit.',
'Für ein bereitgestelltes Umweltziel kombiniert die lernende Person eine Informationsmaßnahme, einen finanziellen Anreiz und eine Regel. Sie erklärt die jeweiligen und gemeinsamen Wirkungsketten, prüft Überschneidungen anhand der Daten und schätzt ökonomische Folgen einschließlich Verteilung und Durchsetzung unter den angegebenen Annahmen ab.',
'For a supplied environmental objective, the learner combines information, a financial incentive and a rule. They explain individual and joint causal chains, assess overlaps using the data and estimate economic effects including distribution and enforcement under the stated assumptions.',
'Eine neue unabhängige Aufgabe verändert die Zielgruppe, Ausweichmöglichkeiten und Kontrollkapazität und gibt mögliche Verlagerungseffekte vor. Die lernende Person gestaltet den Mix neu und begründet die geänderten Folgen, statt die Einzelwirkungen unverändert zu summieren oder das ursprüngliche Maßnahmenpaket als sichere Lösung zu übernehmen.',
'A fresh independent task changes the target group, switching options and monitoring capacity and stipulates possible displacement effects. The learner redesigns the mix and explains changed impacts instead of adding unchanged individual effects or copying the original package as a certain solution.',
'KEEP: Kombinieren UND ökonomische Folgenabschätzung sind bilingual vollständig. Die tatsächlich gesehene Seite trennt Ziel, Instrumentenmix und mehrere offene Folgen; Pluszeichen kombinieren Instrumente, sie beweisen keine additive sichere Erfolgsrechnung. Nachhaltigkeitsvorgänger und externer Q2-Fall erweitern den Umfang nicht automatisch.'
)
]

PAGE_FINDINGS=[
'Produktion, Beschäftigung und Preise sind klar als unterschiedliche Motive zu einer schematischen Zykluswelle verbunden; keine empirischen Werte oder identischen Verzögerungen behauptet.',
'Nachfrage läuft Haushalt→Unternehmen und Einkommen in Gegenrichtung; staatliche Rolle bleibt offen. Notebook/Monitor sind zur handelnden Person orientiert.',
'Öffentliche Reparatur neben ruhiger und stark beschäftigter Werkstatt; Verzögerung und Finanzierung mit offenen Wirkung/Grenzen-Urteilen sichtbar.',
'Vergangenheit endet an Heute; gestrichelte Zukunftsszenarien bleiben Alternativen, kein statistisches Intervall mit erfundener Wahrscheinlichkeit. Wandtafel ist aus Sicht der Person plausibel lesbar.',
'Vier gleichrangige Motive umfassen alle gesetzlichen Ziele; offene Beziehungen und Außenwirtschaftsmotiv behaupten weder Maximalüberschuss noch automatisches Gleichgewicht.',
'Nationale und EU-Institutionen, Haushalts- und Regelmotive zeigen Prüfbedarf und Spielräume ohne veraltete Grenzwerte oder automatische Nullverschuldung.',
'Geldpolitik, Fiskalpolitik und Ordnungsrahmen sind getrennt dargestellt; offene Wirkungspfeile zu wirtschaftlicher Aktivität versprechen keine Summe sicherer Effekte.',
'Preis- und Beschäftigungsmotive auf offener Waage, Angebots-/Kosten-/Erwartungsbedingungen darunter; keine unbedingte langfristige Phillips-Relation.',
'Schätzband und Unsicherheit verbinden Beschäftigung mit Geld- und Fiskalentscheidungen sowie Matching/Qualifikation/Institutionen; kein sicher ablesbarer moralischer Sollwert.',
'Öffentlicher Auftrag führt zu möglichen Nachfragefolgen; staatliche Kreditaufnahme/Zins/private Investition rechts tragen ein Verdrängungsfragezeichen statt universeller Wirkung.',
'Erfahrungsreihe gegenüber Reihe plus zusätzlichen Informationen; beide Zukunftsräume besitzen Fragezeichen, keine perfekte rationale Voraussicht.',
'Großes Geschäft und Krone sind mit Fragezeichen gerahmt; Kooperation/Fusion/Zugang werden geprüft, Größe ist nicht schon nachgewiesener Missbrauch. Die gehaltene Tafel wird präsentiert, nicht aus falscher Personenperspektive gelesen.',
'Markt-, Nachfrage- und Ordnungsmotive unterstützen offenen Denkschulvergleich; keine allein richtige Schule oder Zuordnung jeder Schule zu einem einzigen Instrument.',
'Ökologisch, sozial und ökonomisch sind gleichrangig sichtbar; Integration in Prüfbogen bleibt offen, kleine Markierungen sind nicht zur Hauptmotiverkennung erforderlich.',
'Kartellprüfung links offen; Fusionskontrolle rechts führt alternativ zu Freigabe, Bedingungen oder Untersagung. Bei rotem X bleiben zwei Geschäfte getrennt, keine unter X dargestellte erfolgte Fusion.',
'Infrastruktur, Regeln und Förderung mit Ziel/Wirkung/Nebenfolgen; offene Markt/Staat-Waage fordert Abwägung. Notizblock wird plausibel gehalten und enthält keine rückwärts zu lesenden fachlichen Daten.',
'Mehrere Plattformzugänge, verschiedene Nutzer, Datenkoffer und Wechselpfeile unterstützen spezifischen Wettbewerbskontext; Zugang/Regeln bleiben Fragen statt Erfolgs- oder Missbrauchsbehauptung.',
'Standortbedingungen und selektive Förderung neben offener Nutzen/Kosten/Umweltwaage; keine behauptete zusätzliche Investition oder rechtliche Freigabe.',
'Ziel→Mix→ökonomische/ökologische/unbeabsichtigte offene Folgen; Informations-, Anreiz- und Regelmotive klar. Pluszeichen verbinden Instrumente, keine numerische doppelte Nutzenrechnung.'
]

x=json.loads((P/'description-review-input.json').read_text())
c=json.loads((P/'description-review-campaign.json').read_text())
m=json.loads((P/'review-bundle-manifest.json').read_text())
book=json.loads((B/'book-model.json').read_text())
batch=c['batches'][0]
batchfile=P/'batches'/(batch['batchId']+'.input.jsonl')
assert digest(batchfile)==batch['batchInputFingerprint']
assert [json.loads(s)['goal'] for s in batchfile.read_text().splitlines()]==x['goals']
assert len(TEXT)==len(PAGE_FINDINGS)==len(x['goals'])==19
assert all(g['reviewContext']['page']==p for g,p in zip(x['goals'],book['pages']))
assert all(g['reviewContext']['evidenceProfile'] is None and g['reviewContext']['page']['evidenceReview'] is None for g in x['goals'])
for a in m['artifacts']:assert digest(B/a['path'])==a['digest'],a
run='wirtschaft-q2-nineteen-independent-description-round-b-codex-20261008-v1'
fields=['essentialUnderstandingDe','essentialUnderstandingEn','observablePerformanceDe','observablePerformanceEn','transferExpectationDe','transferExpectationEn']
records=[]
for i,(g,t) in enumerate(zip(x['goals'],TEXT),1):
 records.append({'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json','schemaVersion':1,'recordId':run+'.'+str(i).zfill(3),'runId':run,'campaignId':c['campaignId'],'roundId':c['roundId'],'bundleFingerprint':x['bundleFingerprint'],'bookDigest':x['bookDigest'],**{k:g[k] for k in ['goalId','goalFingerprint','pageFingerprint','currentTitleDe','currentTitleEn','currentDescriptionDe','currentDescriptionEn']},'decision':'keep','understandingEvidence':dict(zip(fields,t[:6])),'rationale':t[6],'evidenceProfileContract':'positive-understanding-evidence-v2','evidenceProfileRecommendation':'create','recordStatus':'candidate','reviewAuthority':'ai_candidate'})
out=P/'results';out.mkdir(exist_ok=True)
record=out/(batch['batchId']+'.records.jsonl')
if record.exists():raise RuntimeError('Preserve existing records')
record.write_text(''.join(json.dumps(r,ensure_ascii=False,separators=(',',':'))+'\n' for r in records))
completed=datetime.now(timezone.utc).isoformat(timespec='seconds').replace('+00:00','Z')
par=P/'observed-generation-parameters.actual.json'
new(par,{'provider':'OpenAI','model':'Codex session; exact model identifier not disclosed','agentIdentity':'/root/economics_layer_a','temperature':'not exposed','seed':'not exposed','method':'Actually read all19 whole DE/EN frozen goals and all canonical/page contexts; own prompt/criteria/contracts/campaign and bundle metadata. Actually viewed all19 rendered native PDF goal pages3-21. Bilingual goal-specific understanding/performance/fresh-transfer expectations and KEEP rationales authored individually. Serializer verifies frozen technical bindings, not fachliche decisions.','blindToCurrentRoundA':True,'otherDescriptionOutputsRead':False,'rootPositiveFinalVerdictRead':False,'authorPreferredDVerdictRead':False,'priorRelatedWorkDisclosure':'Reviewer did not author these19 English translations, P19 profiles or PNGs, and did not perform the Q2-19 V review. It independently reviewed other E1/E2 and Q1 D/P/V packages and authored earlier phase-assessment drafts later independently reviewed by root. Those linked-assessment/topic connections are disclosed; no Q2 D-A, author/root P19 verdict or preferred outcome was consulted.','timingNote':'startedAt uses first preserved clock anchor08:35:09UTC after initial unclocked reading of own contracts/campaign; it does not fabricate the earlier start minute.','humanReviewClaimed':False,'learnerPerformanceClaimed':False})
roles=['book_model','book_pdf','book_pdf_render_manifest','review_input_json','review_prompt','review_criteria','finding_schema','run_manifest_schema']
art=[{'role':a['role'],'digest':a['digest']} for a in m['artifacts'] if a['role'] in roles]
art.append({'role':'description_review_batch_input_jsonl','digest':batch['batchInputFingerprint']})
runfile=out/(batch['batchId']+'.run.json')
new(runfile,{'$schema':'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json','schemaVersion':1,'runId':run,'campaignId':c['campaignId'],'roundId':c['roundId'],'batchId':batch['batchId'],'batchInputFingerprint':batch['batchInputFingerprint'],'bundleFingerprint':x['bundleFingerprint'],'bookDigest':x['bookDigest'],'provider':'OpenAI','model':'Codex session; exact model identifier not disclosed','role':'sequencing_representation_reviewer','promptFamilyId':'goal-description-understanding-evidence-review-v2','promptFingerprint':c['promptFingerprint'],'criteriaFingerprint':c['criteriaFingerprint'],'generationParametersFingerprint':digest(par),'independenceGroupId':c['independenceGroupId'],'blindToOtherRuns':True,'goalIds':batch['goalIds'],'inputArtifacts':art,'startedAt':'2026-10-08T08:35:09Z','completedAt':completed,'status':'completed','outputDigest':digest(record),'toolchainVersion':'skillpilot-native-d-v2-input-v3-record-v1-codex-actual-tools'})
ins=[]
for i,(g,f) in enumerate(zip(x['goals'],PAGE_FINDINGS),3):
 d=P/'inspection'/('frozen-native-pdf-page-'+str(i).zfill(2)+'.png')
 ins.append({'goalId':g['goalId'],'goalFingerprint':g['goalFingerprint'],'pageFingerprint':g['pageFingerprint'],'actualWholeDeEnGoalRead':True,'actualWholeCanonicalAndPageContextRead':True,'actualNativePdfGoalPageViewed':True,'pdfPhysicalPage':i,'inspectionDerivative':str(d.relative_to(P)),'inspectionDerivativeDigest':digest(d),'actualPageFinding':f,'decision':'keep','evidenceProfileActuallyPresent':False,'profileRecommendation':'create','unresolvedDescriptionFindings':[]})
new(P/'independent-description-page-inspection.actual.json',{'schemaVersion':1,'reviewId':run,'agentIdentity':'/root/economics_layer_a','provider':'OpenAI','model':'Codex session; exact model identifier not disclosed','reviewAuthority':'ai_candidate','completedAt':completed,'bundleFingerprint':x['bundleFingerprint'],'bookDigest':x['bookDigest'],'recordsDigest':digest(record),'runDigest':digest(runfile),'bookPdfDigest':digest(B/'book.pdf'),'inspections':ins,'frozenArtifactBindingsActuallyChecked':[{'role':a['role'],'path':a['path'],'expectedDigest':a['digest'],'actualDigest':digest(B/a['path'])} for a in m['artifacts']],
 'actualSourcesRead':[
 {'path':'curricula/DE/Gymnasium/input/HE/upper-secondary/kerncurriculum_gymnasiale_oberstufe-wirtschaftswissenschaften.pdf','reading':'Fresh actual whole printed42/PDF42 and printed43/PDF43 read: Q2 introduction, exact Q2.1/Q2.2 source clauses and GK/LK distinction. Confirms conditional controversy/model and growth/competition context. Does not assert complete mapping or that raw goal tags alone prove effective curriculum scope.'},
 {'url':'https://www.gesetze-im-internet.de/stabg/__1.html','path':'inspection/actual-stabg-section1.html','actualDigest':digest(P/'inspection/actual-stabg-section1.html'),'reading':'Actual complete official current§1 HTML read; four objectives and simultaneous overall balance. Web requests failed, urllib HTTP200 succeeded. Initial UTF8 decoding failed; actual declared iso-8859-1 encoding then used and whole text genuinely read. No failed retrieval or encoding attempt is called substantive reading.'},
 {'url':'https://www.gesetze-im-internet.de/gg/art_109.html','path':'inspection/actual-gg-article109.html','actualDigest':digest(P/'inspection/actual-gg-article109.html'),'reading':'Actual complete official current Art109 read via HTTP200 and declared iso-8859-1 after initial UTF8 error. Contains currently changed federal/state scope and exceptions, not the old blanket zero-debt statement for states. Used to ensure dated provided-source case conditions, not a personal fiscal ruling.'},
 {'url':'https://www.gesetze-im-internet.de/gg/art_115.html','reading':'Actual whole current article text read via web: federal constitutional credit rule, cyclic adjustment, specified expenditure adjustment and emergency decision/repayment conditions. No current individual budget approval inferred.'},
 {'url':'https://www.consilium.europa.eu/en/policies/economic-governance-framework/','reading':'Actual complete main official page read, page last-review10Oct2025 with2026timeline. Differentiated multiannual net-expenditure paths, national plans, preventive/corrective procedures and conditional escape clauses checked. Reference threshold does not itself prove an automatic sanction. D cases require separately supplied dated norms and material.'},
 {'url':'https://ec.europa.eu/economy_finance/publications/pages/publication_summary11126_en.htm','reading':'Actual whole publication abstract and publication metadata read. Official historical EconomicPaper145/September2000, archived2017; conceptual use only for non-directly-observed/model-dependent NAIRU estimate. No full59page paper or current NAIRU number claimed.'},
 {'url':'https://digital-markets-act.ec.europa.eu/businesses-portal/interoperability_en','reading':'Actual whole official main page read. Network/scale/lock-in/interoperability conditions and difference between specification and noncompliance decisions support conditional platform case expectations. Illustrative D task does not adjudicate a real platform or pretend DMA is identical to a proved cartel infringement.'},
 {'url':'https://www.bundeskartellamt.de/DE/Aufgaben/Fusionen/Verfahren_Fusionskontrolle/Verfahren_node.html','reading':'Actual official search-result excerpt read about substantial impediment, market-access/switching conditions and clearance, conditional clearance and prohibition. Full direct request403; no complete page/current numeric thresholds claimed. Used only for conditional procedural distinctions, with dated actual norms required in proposed educational cases.'},
 {'url':'https://www.bundeskartellamt.de/DE/Aufgaben/Kartelle/Kartellverfolgung/Kartellverfolgung.html','reading':'Actual official search-result content read on restrictive agreement and possible legally bounded exemptions. Direct request403; no complete-page reading claimed. No failed old English URL treated as evidence.'},
 {'url':'https://www.bundeskartellamt.de/DE/Aufgaben/Missbrauchsaufsicht/missbrauchsaufsicht_node.html','reading':'Actual official search excerpt read distinguishing market power from its abusive use. Direct request403; full page not claimed. Specific infringement and legal availability are left to supplied current primary case materials.'}
 ],
 'independence':json.loads(par.read_text()),'descriptionDecisions':{'keep':19,'revise':0,'split_review':0,'block':0},'unresolvedDescriptionFindings':[],
 'independentNewIllustrativeArithmeticActuallyChecked':{'goalId':'b0bdd6e9-3b74-51dc-b85e-d35346a5e04c','case1':'Y=C+I+G,C=20+0.8Y gives denominator0.2,multiplier5; autonomous net change10−2=8 yields40.','freshCase':'C=20+0.8(1−0.25)Y=20+0.6Y,M=0.1Y,Y=C+I+G−M gives denominator1−0.6+0.1=0.5,multiplier2; same net impulse8 yields16.','limits':'These two manually authored D illustrations were independently recomputed; they are not the absent P19 profiles or claimed reviewed38 bilingual P cases.'},
 'positiveProfileHandling':'All19 frozen evidenceProfile and evidenceReview values are null; all19 native D records honestly recommend create. The bound criteria request19wholeP/38cases; those inputs are absent from this D book. That substantive acceptance belongs to a separately performed P lane and is not claimed here. D understanding/performance/fresh-transfer chains are recommendations only, not fabricated current profiles. Synthesis must preserve and transparently resolve this separation.',
 'scopeAndOtherGateLimits':'This frozen canonical CrossStage review view is not a proved learner GK/LK projection. Raw sourceRef=null and evidenceReviewSources=[] do not certify complete mappings/source binding; only actually read official subject references are listed. No new whole A/M verdict, card visibility review, V approval, effective readiness approval, human release or observed learner-performance evidence is inferred. Both independent D rounds, separately current P/V/A/M and native synthesis/current integration remain necessary for strict completion.',
 'strictCompletionAddedByThisRound':0,'liveFilesMutated':0})
print(json.dumps({'recordDigest':digest(record),'runDigest':digest(runfile),'inspectionDigest':digest(P/'independent-description-page-inspection.actual.json'),'goalCount':19,'keep':19,'profileCreate':19,'completedAt':completed},indent=2))
