import json,datetime,hashlib,subprocess
from pathlib import Path
import jsonschema
B=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-05/chemie-b014-eleven-current-source-description-candidate-v1');now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def read(p):return json.loads(Path(p).read_text())
def h(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def w(n,x):(B/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
r=read(B/'input-receipt.json'); ids=r['goalIds']; witnesses=read(B/'current-source-witnesses.json'); contexts=witnesses['contexts']; retained=read('curricula/DE/Gymnasium/input/HE/upper-secondary/source-extraction/DE_HE_CHEMIE_SEKII_KC2024.source-extraction.json'); by=read('curricula/DE/Gymnasium/input/BY/gymnasium/source-extraction/DE_BY_CHEMIE_GYMNASIUM_LEHRPLANPLUS.source-extraction.json'); sourceById={g['id']:g for g in retained['sourceGoals']+by['sourceGoals']};
main=[
 ['he-chem-sekii-e-1-b01-a01-76c838e1','he-chem-sekii-e-1-b01-a02-37836467','he-chem-sekii-e-1-b01-a03-6e3160f2','he-chem-sekii-e-1-b01-a04-94393d48','he-chem-sekii-e-1-b01-a05-94ebccd7','9ac37e41-7308-593c-b99a-d47df850ebef','36b785ad-043b-59b6-8c23-05d5021c4fd7'],
 ['a64c4974-d9ba-5580-a109-c17a19556047','9a9b3e03-be49-526d-8886-733f61c70582','he-chem-sekii-e-1-b08-a01-0bba4a7b','he-chem-sekii-q1-1-b05-a01-5b6f7c6a','he-chem-sekii-q3-3-b01-a01-1e5794fd'],
 ['he-chem-sekii-e-1-b05-a01-f455805a','he-chem-sekii-e-1-b06-a01-5428c244','6817ce94-d1b4-51b2-a596-65c11d8c62bd'],
 ['he-chem-sekii-e-1-b07-a01-e3d57612','he-chem-sekii-e-1-b06-a01-5428c244','he-chem-sekii-q3-3-b02-a01-f4d24c56'],
 ['he-chem-sekii-e-1-b09-a01-45b22583','he-chem-sekii-q3-3-b04-a01-a7519947'],
 ['069deab0-9b1b-565c-b796-cd77e792de4a'],
 ['he-chem-sekii-e-2-b01-a01-4b89f4d7'],
 ['he-chem-sekii-e-2-b02-a01-c32ee65f','he-chem-sekii-e-2-b03-a01-b6eb2233','d6ad6ab1-1c9a-5101-9b26-d2ed456d3089','he-chem-seki-10-3-b04-a01-19eb255b'],
 ['he-chem-sekii-e-2-b04-a01-803d5801','679791db-9f6f-5f25-96ee-d001ea4aa052','731a7a29-d7d2-58bd-b58c-2bd11f021f50','aef2890a-b4ca-5f85-9797-8a7d60d9ff45','he-chem-seki-10-3-b04-a02-57993467'],
 ['he-chem-sekii-e-2-b05-a01-0713a913','he-chem-sekii-e-2-b06-a01-a508fe05','4c524f0f-8801-5ad7-8bd8-28f855720e1d','bdf423a8-c033-555e-ac10-c9af3baae26a','he-chem-seki-10-3-b03-a01-494031f0','he-chem-seki-10-3-b03-a02-f8366f86','he-chem-seki-10-3-b03-a03-8db502ef'],
 ['he-chem-seki-10-3-b03-a01-494031f0','he-chem-seki-10-3-b03-a02-f8366f86','he-chem-seki-10-3-b03-a03-8db502ef']]
for c in contexts: sourceById[c['sourceGoalId']]=c['sourceGoal']
limits=[
 'PASS substantive electron-transfer terminology; HOLD obsolete provenance and misassigned E.1 B08. BY9 ion formation is partial/joint with ion-formation goal; no independent approval of other jurisdictions.',
 'HOLD split and EN repair. BY10.5.1 specifically includes inorganic AND organic species and identifying redox. BY10.5.2/HE E.1 B08 balancing routes to existing221; HE Q1 combustion clause is joint, not whole coverage by oxidation numbers alone.',
 'PASS one inferred series. HE E.1 B05 supports deposition; B06 requires measurement/reference/numeric-voltage route in addition. BY9.6.4 supports deposition and equations, not automatically the complete voltage measurement operator. HOLD visual Ag label and parent/prereq rebind after496 split.',
 'PASS qualitative cell mechanism. HOLD treating E.1 B06 as fully carried: standard hydrogen half-cell and numeric voltage must remain with independently checked existing reference/voltage goals. Q3.3 B02 is an additional current source candidate, not already mapped to this goal in the extracted eleven-context routing.',
 'PASS electrolysis example and stoichiometric ratios. HE Q3 explicitly aqueous CuCl2; current molten NaCl image is valid example but not all required examples. Faraday law/overvoltage are separate LK scope, not smuggled into this E atom.',
 'PASS BY current provenance/sourceID and scientifically conditional revision. BY9 unspecified profile corresponds listed non-NTG and merged NTG content; existing E galvanic/electrolysis prerequisites need an actual grade-appropriate reviewed route, not deletion to hide a floor mismatch.',
 'HOLD names/formula recall trace and obsolete source binding. HE E.2 B01 explicitly names sulfuric, nitric, carbonic, phosphoric, hydrochloric acids and their salts; NaOH,KOH,Ca(OH)2,Ba(OH)2 and corresponding aqueous solutions. The nine acid/base facts remain in the candidate; salt coverage needs separate existing-salt/formula goals, not whole approval of28+d2.',
 'HOLD split, missing EN preparation and scale depiction. BY10.4.8 own preparation operator retained. HE G9 10.3 B04a01 only amount/concentration, not the complete strong-acid pH logarithmic model; optional pH investigations do not automatically license the entire current atom as mandatory grade10.',
 'PASS one titration workflow after precise revision. HE E.2 B04 exact analytical target is026, not concentration-only f1/680. BY10 simple titration and BY13GA own plan/conduct/document operators are preserved at their actual stages. No universal endpoint pH7 assertion. HOLD missing visual and obsolete provenance.',
 'PASS one proton-transfer model. HE E.2 B06 ionic protolysis equations route to1c, not concentration/pH-only f1. HE G9 and BY10 support concept level; current F1 whole prerequisite may impose unrelated preparation/strong-pH content and needs bounded per-edge review.',
 'HOLD three independent performances and source/stage breadth. HE G9 clauses only roles/pairs/water-ampholyte: direction/detection/reflection not full coverage. HB original printed23 verifies strength/equilibrium/MWG; extracted pK wording is an author operationalization, not a literal quote. Generic reflection exact normative operator remains unestablished; existing detection and pK targets are reuse candidates, not fresh approvals.' ]
rows=[]
for i,g in enumerate(r['goals']):
 prov=g.get('extendedData',{}).get('provenance',{}); inCurrent=prov.get('sourceGoalId') in sourceById
 routes=[]
 for sid in main[i]:
  sg=sourceById[sid]; routes.append({'sourceGoalId':sid,'sourceRef':sg.get('sourceRef'),'sourceSpan':sg.get('sourceSpan'),'courseLevel':sg.get('courseLevel'),'tags':sg.get('tags',[]),'fullCurrentClause':sg.get('rawSourceText',sg.get('sourceText')),'operatorQualifier':'HE nominal content-list clause; candidate assessable operator is an author operationalization' if sid.startswith('he-chem-sekii') else 'Source operator preserved in exact current clause','sourceLandscapeId':retained['sourceLandscapeId'] if sid.startswith('he-chem-sekii') else (by['sourceLandscapeId'] if not sid.startswith('he-') else 'bea90c22-b9c5-4c0c-9b10-89d875f50772')})
 rows.append({'goalId':g['id'],'currentProvenance':prov,'currentProvenanceSourceIdExists':inCurrent,'substantiveCurrentSourceCandidateRoutes':routes,'currentMappingRows':[{'sourceGoalId':c['sourceGoalId'],'sourceLandscapeId':c['sourceLandscapeId'],'rows':[m for m in c['mappings'] if m.get('canonicalGoalId')==g['id']]} for c in contexts if any(m.get('canonicalGoalId')==g['id'] for m in c['mappings'])],'scientificSourceVerdict':'PASS_content_basis_with_HOLD_bindings_and_scope' if i in [0,2,3,4,5,8,9] else 'HOLD_targeted_revision_split_memory_or_extent','reason':limits[i],'sourceHumanApproved':False,'allJurisdictionsApproved':False})
critical=[]
for sid,after,why in [
 ('he-chem-sekii-e-1-b08-a01-0bba4a7b',[{'canonicalGoalId':'22133f29-ef02-4408-8f8d-2bbea3275d91','matchType':'exact_candidate_after_scoped_reuse_review'}],'04 terms cannot carry balancing; preserve balancing coverage with existing221, not duplicated new atom.'),
 ('he-chem-sekii-e-2-b04-a01-803d5801',[{'canonicalGoalId':ids[8],'matchType':'exact_candidate_after_description_revision'}],'Actual titration clause requires measurement/endpoint/stoichiometric inference, missing in f1 and acid/base classification680.'),
 ('he-chem-sekii-e-2-b06-a01-a508fe05',[{'canonicalGoalId':ids[9],'matchType':'exact_candidate'}],'Actual protolysis ionic-equation clause is carried by Brønsted1c, not concentration/pH f1.')]:
  c=next(c for c in contexts if c['sourceGoalId']==sid);critical.append({'sourceGoalId':sid,'sourceLandscapeId':c['sourceLandscapeId'],'before':c['mappings'],'candidateAfter':after,'reason':why,'activeMutation':False,'historicalClaimsPreserved':True})
for sid in main[10]:
 c=next(c for c in contexts if c['sourceGoalId']==sid);critical.append({'sourceGoalId':sid,'sourceLandscapeId':c['sourceLandscapeId'],'before':c['mappings'],'candidateAfter':[{'canonicalGoalId':ids[9],'matchType':'exact_candidate_for_roles_pairs_or_water_ampholyte_after_current_source_review'}],'reason':'No source support for entire b477 direction/detection/reflection in these G9 clauses; 1c relational proton model is the narrower actual carrier. Preserve remaining mappings/history pending group review.','activeMutation':False,'historicalClaimsPreserved':True})
primary=[
 {'name':'HE current KCGO Chemie April2026','url':'https://kultus.hessen.de/sites/kultus.hessen.de/files/2026-07/kcgo_chemie_21.04.2026.pdf','localPath':str(B/'primary-he-current-2026.pdf'),'sha256':h(B/'primary-he-current-2026.pdf'),'actualPhysicalAndPrintedPagesViewed':[35,38,47],'scope':'Only E.1/E.2, targeted organic oxidation Q1.1 and electrolysis/redox Q3.3 clauses; no full2026-source migration approval.'},
 {'name':'HE retained KC2024 extraction-bound PDF','path':'curricula/DE/Gymnasium/input/HE/upper-secondary/kerncurriculum_gymnasiale_oberstufe-chemie.pdf','sha256':h('curricula/DE/Gymnasium/input/HE/upper-secondary/kerncurriculum_gymnasiale_oberstufe-chemie.pdf'),'actualPhysicalAndPrintedPagesViewed':[35],'comparison':'E.1/E.2 substantive clauses visually agree with current2026 page35; obsolete legacy goalIDs do not become current extraction IDs merely because wording agrees.'},
 {'name':'HE G9 Chemie','url':'https://kultus.hessen.de/sites/kultus.hessen.de/files/2021-06/g9-chemie.pdf','actualPhysicalPagesViewed':[18,19,25],'actualPrintedPagesViewed':[17,18,24],'scope':'Only9.1,9.2,10.3 target clauses. Optional and mandatory columns differentiated.'},
 {'name':'BY current LehrplanPLUS HTML','urls':['https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/9/chemie/ch','https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/10/chemie/ch','https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/10/chemie/ch-ntg','https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/13/chemie/grundlegend'],'actualSectionsRead':['C9.6','C10.4','C10.5','C10-NTG.2/.3','C13-GA.3'],'scope':'Actual grade/profile/operators, no generic GK label equated with BY course names.'},
 {'name':'HB Q Protolysegleichgewichte','url':'https://www.lis.bremen.de/sixcms/media.php/13/GyO_Chemie_2022.pdf','localPath':'curricula/DE/Gymnasium/input/HB/GyO_Chemie_2022.pdf','sha256':h('curricula/DE/Gymnasium/input/HB/GyO_Chemie_2022.pdf'),'actualPhysicalAndPrintedPagesViewed':[23],'scope':'Only targeted b477 strength/equilibrium route; no full HB review. Original page calls explain reversible protolysis, apply MWG, justify strength; extraction pK formulation is derived.'}]
w('eleven-current-source-clause-routes-and-holds.json',{'recordStatus':'candidate','reviewAuthority':'ai_candidate','observedAt':now,'canonicalLandscapeId':r['canonical']['landscapeId'],'goalCount':11,'originalPrimarySourcesActuallyRead':primary,'rows':rows,'preciseMappingDeltaCandidates':critical,'metadataOnlyOtherJurisdictions':'48 atlas routing scopes / 16 curricula are book publication/routing context, not16 independent source approvals. b477 other-source contexts are preserved as routing evidence; only the targeted HB original page was additionally reviewed.','scopeBookViewFullDoesNotMean16SourceApproval':True,'legacyHeProvenanceCountAbsent':sum(not row['currentProvenanceSourceIdExists'] for row in rows),'sourceHumanApproval':False,'PRead':False,'activeWrites':0})
# Schemas used by native D helper and direct JSON-schema check.
errors=[]; checks=[]
for name,sp,multi in [('source-description-author.records.jsonl','contracts/goal-description-review/v1/goal-description-review-record.schema.json',True),('source-description-author.run.json','contracts/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json',False)]:
 schema=read(sp); validator=jsonschema.Draft202012Validator(schema,format_checker=jsonschema.FormatChecker());objs=[json.loads(l) for l in (B/name).read_text().splitlines()] if multi else [read(B/name)]
 for i,o in enumerate(objs):
  for e in validator.iter_errors(o):errors.append({'file':name,'row':i+1,'path':list(e.path),'error':e.message})
 checks.append({'file':name,'schemaPath':sp,'schemaSha256':h(sp),'recordCount':len(objs)})
w('schema-validation.receipt.json',{'observedAt':now,'result':'PASS' if not errors else 'FAIL','checks':checks,'errors':errors,'recordStatus':'candidate','reviewAuthority':'ai_candidate'})
probes=[]
for tag,script in [('a','semanticAtomicityReview'),('m','memoryCardReview')]:
 cmd=['app/node_modules/.bin/tsx',f'app/scripts/{script}.ts',f'--config={B}/historical-current-eleven.{tag}.config.json','--mode=check'];p=subprocess.run(cmd,text=True,capture_output=True);(B/f'historical-current-eleven.{tag}.terminal.txt').write_text(p.stdout+p.stderr);probes.append({'tag':tag,'command':cmd,'exitCode':p.returncode,'terminalPath':str(B/f'historical-current-eleven.{tag}.terminal.txt')})
w('native-isolated-a-m.receipt.json',{'observedAt':now,'status':'candidate','authority':'ai_candidate','checks':probes,'qualifier':'Historical current schema/fingerprint status only, no write-fingerprints and no active report write. Native technically current11atomic/no_memory decisions do not resolve author three non-atomic cases or28compact-recall HOLD.'})
print(json.dumps({'schemaErrors':errors,'nativeHistoricalAM':[{k:x[k] for k in ['tag','exitCode']} for x in probes],'sourceRows':len(rows),'obsoleteHeProvenanceIDs':sum(not row['currentProvenanceSourceIdExists'] for row in rows),'criticalMappingDeltas':len(critical)}))
