from pathlib import Path
import json,hashlib,copy
R=Path('/home/enpasos/projects/skillpilot');O=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-seven-policy-whole-science-independent-root-v1'
p=O/'actual-twentyone-own-policy-whole-two-case-works-and252-halfcriterion-decisions.independent-root.json';x=json.loads(p.read_text());y=copy.deepcopy(x);changes=[]
def replace(i,answers,marks,bound,why):
 w=next(z for z in y['works']if z['materialId']==x['works'][i*3]['materialId']and'absence'in z['kind']);old=copy.deepcopy(w)
 for j,(t,v)in enumerate(zip(answers,marks)):
  a=w['wholeTwoCasesAndSixTaskAnswers'][j];a['wholeOwnAnswer']=t;a['individualHalfCriterionPoints']=v;a['actualPoints']=sum(v);a['actualReviewerReason']='Eigene korrigierte konkrete ganze Gegenarbeit; beide Rasterhälften am gebundenen Originalraster einzeln0/1/2gegradet. '+why
 w['rawPoints']=sum(z['actualPoints']for z in w['wholeTwoCasesAndSixTaskAnswers']);w['finalPoints']=min(w['rawPoints'],14);w['result']='FAIL';w['wholeCoreDecision']=bound;changes.append({'materialId':w['materialId'],'wholePriorWorkNotEligibleForAbsenceClaim':old,'wholeCorrectedOwnWork':w,'actualOwnProofLimitationCorrected':why})
w=next(z for z in y['works']if z['materialId']==x['works'][3]['materialId']and'absence'in z['kind']);a=[z['wholeOwnAnswer']for z in w['wholeTwoCasesAndSixTaskAnswers']]
a[0]='R ändert Kartell- undZugangsregeln durch Aufsicht. Svergibt die genannten10ausdemBudget,aberichbehauptefälschlich,dassAufträgehiernurRegelnändernundkeineaktuellewirtschaftlicheAktivitätoderNachfragebeeinflussen. DurationsunterschiedalleinentscheidetdenOrdnungsrahmennicht.'
a[1]='OstütztWettbewerbsdurchsetzung,LverlässlicheoffeneallgemeineRegeln.K lehntnachmeinerfalschenDeutungjedeBeeinflussungderNachfrageselbstbeifreienRessourcenab;diegegenteiligeKarteberücksichtig eichnicht.'
a[2]='RundöffentlicheVergabeinderKombinationkönntenBegünstigungbegrenzen;10fehlenanderemBudgetundZusätzlichkeitistzuprüfen.Ichbehaupteweiter,SändernurausschließlichMarktregeln,niemalslaufendeAufträge/NachfrageoderProduktion.'
a[3]='B imJahr1habeangeblichüberhauptkeinenBau-/Nachfrage-/Auslastungskanal.AbJahr3könnenZugangundTransportkostenmittechnischerFertigstellungundNutzungverbessertwerden;diese langfristige Funktionbeschreibeich.'
a[4]='L/O begründenallgemeineZugangsbedingungenstattDauervorteilefürStammkunden.KkannnachmeinerfalschenDeutungkeinenkurzfristigenImpulsbegründen,unddiesesProjektbesitzefälschlichnur eine dauerhafteInstitutionenfunktion.'
a[5]='20gehenzulastenandererBudgets,NutzungundFertigstellungbleibenunsicherundEtappensindzulässig.Ichbehauptefälschlich,dassfreiegegenüberausgelastetenBaukapazitätenkeinenUnterschiedfür aktuelleNachfrage-/Mengen-/Beschäftigungswirkungenmachen.'
replace(1,a,[[1,1],[2,0],[1,2],[0,2],[1,0],[0,2]],'Prozess-/NachfragemechanismusundkonkreteK-Anwendungsinddurchgehendfalsch;die langfristige L/O-Funktionalleinersetztsie nicht.','V1 enthielt richtige eigene kurzzeitige Nachfragemechanismen außerhalb falscherK-Labels; diese können alsTeilleistungzählen. V1 wird daher nicht als Beleg einer vollständig fehlendenK-Leistung verwendet. V2 macht die substantielle Prozessmechanik tatsächlich falsch, statt Labelabweichung alsHardfailzuverwenden.')
w=next(z for z in y['works']if z['materialId']==x['works'][6]['materialId']and'absence'in z['kind']);a=[z['wholeOwnAnswer']for z in w['wholeTwoCasesAndSixTaskAnswers']]
a[2]='KostenP500undQ340sowiedigitaleWartezeit/Folgeschädenwägeichwirtschaftlichab.Für Qwürdeicheine statistischeFehlerstichprobeundvergleichbareFallmischungenmitausgewiesenenKostenprüfen,für PfehltZeit-/Nutzenvergleich.DiegegebenenVertragsanforderungenprüfeichwederhiernochanderswo.'
a[5]='HäufigeKäuferkönnenmit80statt100nach2Gebühr18sparen,gelegentlicheNichtkäuferverlieren2. Anbieter100kauftAufmerksamkeit;ichwürdeIbeigleichenLeistungenfürregelmäßigeKäuferprüfen,VollständigkeitundLieferkonditionenfehlen.EconomicbenefitbeweistkeinesichereKausalitätoderumfassenderealeZulässigkeit;keineKennzeichnungsregeloderkonkreteRegelbefundwirdangewandt.'
replace(2,a,[[2,2],[0,0],[2,2],[2,2],[0,0],[2,2]],'KeinerleikonkreteAnwendungdergegebenenVertrags-/Kennzeichnungsanforderungen;Kosten-/SuchanalyseundallgemeineRechtsgrenzenreichennicht.','V1wünschtesichtbareKennzeichnungundmenschlicheBeschwerdeninanderenAntworten;dieskannechtekorrekteNormanwendungalsTeilleistungsein.DeshalbkeineV1-Ganzabsenzbehauptung. V2entferntdieseKonkretioneninderkomplettenArbeit,währendwirtschaftlicheAnalyseundDatenbegrenzungbleiben.')
w=next(z for z in y['works']if z['materialId']==x['works'][12]['materialId']and'absence'in z['kind']);a=[z['wholeOwnAnswer']for z in w['wholeTwoCasesAndSixTaskAnswers']]
a[0]='Kurs30−45=−15ppundspäter70−60=+10pp,Teilnehmer+30pp,Vergleich+20pp.KurszeitkannLock-inverursachen.Aberichbehauptefälschlich,dassgleicheAlters-/BerufsanteilesowienichtzufälligeTeilnahmeMotivationsselektionvollständigausschließenunddamit+10ppalsbewiesenenKausaleffektausweisen.'
a[1]='100Teilnahme,90Abschluss,80Nachweis,60Zielberufunterscheid eich;300.000/60=5.000beschreibend.Darüberhinausbehaupteichfälschlich30.000jeerwiesenemZusatzjob,weilbeobachteteAlters-/BerufsgleichheitalleunbeobachtetenUnterschiedeausschließe.'
a[2]='Passung,Zugang,Qualität,KostenundKurszeitsindzuprüfen.MehrZeitpunkteundähnlichebeobachtetePersonensindnützlich;ichbehauptejedochweiterfalsch,dassMotivationundunterschiedlicheVorverläufebeidernichtzufälligenAuswahlunmöglichseienundkeinekausaleGrenzebegründen.'
a[4]='Die10ohnehin geplantenZieljobssindMitnahme,5könnenandereBewerberverdrängenundunklarüberlappen,daher25keineerwieseneB-Zusatzjobzahl.MitBetreuung250.000/40=6.250gegen200.000/40=5.000beschreibend.TrotzdembehaupteichfürAweiterfalsch,gleichenbeobachtetenGruppenentsprächenautomatischidentischeunbeobachteteEntwicklungund+10ppbewieseneKausalwirkung.'
a[5]='IchwürdezugänglicheBetreuung/Digitalhilfeunter250.000undpassendeNachfrage/Qualitätnach12/24Monatenprüfen.DafürfehltanderesBudget.EineA-Selektionsgrenzelehneichweiterfälschlichab;gleicheAlters-/BerufsanteilebeweisenangeblichRandomisierungunddenkausalenErfolg.'
replace(4,a,[[2,2],[2,0],[2,1],[2,2],[2,2],[2,1]],'DiegegebeneA-ZuweisungistnichtzufälligundunbeobachteteMotivationsselektionoffen;dieganzeArbeitweistdieseGrenzedurchgehendfalschalsunmöglichzurück. B-Mitnahme-/VerdrängungskenntnisbleibtkorrekteTeilleistung,heiltaberdie explizit falscheKausalbeurteilungdesanderengegebenenFallesnicht.','V1nanntebereits10ohnehin geplanteJobsundderenMitnahmeeffektimNichtbehandlungsatz;dasisteinmöglichererkannterTeilbefundundkeinvaliderGanzabsenzbeleg.V2nutztstattdessen tatsächlich durchgehend falscheKausalselektionsbewertung, undwertet die richtige B-Mitnahme/Verdrängungvoll.')
y['role']='ACTUAL_ROOT_INDEPENDENT21_WHOLE_WORKS_WITH_THREE_REAL_PROOF_LIMITATION_CORRECTIONS';y['originalV1HistoryPreserved']=True;y['actualThreeProofLimitationsCorrected']=changes;y['originalBadThreeClaimsEligible']=False
y['newHumanOrHostAcceptanceClaim']=False
q=O/'actual-final-twentyone-whole-policy-works-three-own-proof-limits-corrected.independent-v2.json';assert not q.exists();q.write_text(json.dumps(y,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'path':str(q.relative_to(R)),'sha256':hashlib.sha256(q.read_bytes()).hexdigest(),'bytes':q.stat().st_size,'wholeOwnFinalWorks':21,'actualHalfMarks':252,'correctedOwnProofs':3,'actualBadRaw':[z['rawPoints']for z in y['works']if'absence'in z['kind']],'actualBadFinal':[z['finalPoints']for z in y['works']if'absence'in z['kind']]}))
