// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync,readdirSync,existsSync} from 'node:fs'
import {resolve,dirname,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import {buildGoalBookModel,fingerprintSemanticKindSourceGoal,stableGoalBookJson} from '../../../../../../../app/scripts/goalBookModel'
import {buildGoalBookOriginalSources} from '../../../../../../../app/scripts/goalBookOriginalSources'
import {validatePreparedGoalDescriptionRolloutBatch,materializeGoalDescriptionRolloutBatchDualSummary} from '../../../../../../../app/scripts/materializeGoalDescriptionRolloutBatch'
import {extractGoalDescriptionDualRoundResolutionSource,buildGoalDescriptionDualRoundResolution,validateGoalDescriptionDualRoundResolution,fingerprintGoalDescriptionReviewContext,fingerprintGoalDescriptionReviewCampaign} from '../../../../../../../app/scripts/validateGoalDescriptionDualRoundResolution'
import {buildGoalDescriptionRolloutSynthesisRoundBinding,fingerprintGoalDescriptionRolloutSynthesisDecisionManifest,validateGoalDescriptionRolloutSynthesisDecisionManifest} from '../../../../../../../app/scripts/validateGoalDescriptionRolloutSynthesisDecisionManifest'
import {buildGoalDescriptionRolloutResolutionSynthesis} from '../../../../../../../app/scripts/goalDescriptionRolloutResolutionSynthesis'
import {evaluateRouteProfile,routeProfiles} from '../biologie-11675-terminal-route-author-20261007-v1/native-quality-private-function-probe'
import {buildApplicabilityCompilation} from './native-reviewed-candidate-applicability.technical'

const root=resolve('.'),own=dirname(fileURLToPath(import.meta.url)),base=resolve(own,'..'),author=resolve(base,'biologie-11675-terminal-route-author-20261007-v1')
const srcA=resolve(base,'biologie-11675-terminal-route-independent-a-root-20261007-v1'),srcB=resolve(base,'biologie-11675-terminal-route-independent-b-20261007-v1'),followB=resolve(srcB,'current-context-followup')
const target='11675f1a-5de2-5926-be78-1e8275f19f5b',terminal='e8caebd4-57bc-5c2f-881d-0b1693777c64',parent='28788f27-f079-5d78-936f-b7684760ff31'
const activeCanon='curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_BIOLOGIE.de.json',activeKinds='curricula/DE/Gymnasium/quality/goal-book-publication/biologie.semantic-kinds.json',activeRegistry='curricula/DE/Gymnasium/quality/deep-understanding-rollout/de-gymnasium-math-physics.config.json'
const declared=new Map<string,any>(),sha=(b:Buffer|string)=>'sha256:'+createHash('sha256').update(b).digest('hex')
const bind=(p:string)=>{const b=readFileSync(p);return {path:relative(root,p),sha256:sha(b),bytes:b.length}}
const bytes=(p:string)=>{declared.set(p,bind(p));return readFileSync(p)}
const read=(p:string)=>JSON.parse(bytes(p).toString('utf8'))
const write=(p:string,v:any)=>{mkdirSync(dirname(p),{recursive:true});const b=Buffer.isBuffer(v)||typeof v==='string'?v:JSON.stringify(v,null,2)+'\n';if(existsSync(p)){assert.equal(sha(readFileSync(p)),sha(b),'Existing technical payload must remain exact');return}writeFileSync(p,b,{flag:'wx'})}
const copy=(a:string,b:string)=>write(b,bytes(a))
const verify=(dir:string,name:string,expected:string)=>{const path=resolve(dir,name);assert.equal(bind(path).sha256,'sha256:'+expected);const seal=read(path);for(const e of seal.files??seal.payloads??seal.ownFiles){const p=e.path.startsWith('curricula/')||e.path.startsWith('app/')?resolve(root,e.path):resolve(dir,e.path);assert.equal(bind(p).sha256.replace('sha256:',''),e.sha256.replace('sha256:',''));if(e.bytes!==undefined)assert.equal(bind(p).bytes,e.bytes)}return {seal:bind(path),verifiedFiles:(seal.files??seal.payloads??seal.ownFiles).length}}
const seals={author:verify(author,'author-terminal-and-one-context.inputs.freeze.json','ff4237cb0020129b3a45872ade989072b4a8f4e10b12c140d47046e886d04c46'),A:verify(srcA,'independent-a.final.freeze.json','46043a12b6e69d922a1f420495f3fa9dbc3b0d8b2014e385ff4b4d85bada64ed'),B:verify(srcB,'final-terminal-review.independent-b.seal.json','3e1a61a09ca9069fe5742481079e57717cf9a9fca90f65a5c65952399108c91b'),currentB:verify(followB,'current-context.independent-b.final.seal.json','a262aa3a3030e894bae1c566f9b7941b53f6c2d1976e5cf4b2f19706c17b91cf')}
const sourceCanon=resolve(own,'candidate/canonical.future-active.json'),future=read(sourceCanon),before=read(resolve(own,'before/canonical.json')),baseline=read(resolve(own,'before/baseline-bindings.json'))
assert.equal(sha(bytes(resolve(root,activeCanon))),baseline.canonical.sha256,'Root must rebase explicitly if active canonical moved')
assert.equal(sha(bytes(resolve(root,activeKinds))),baseline.kinds.sha256)
assert.equal(before.goals.length,473);assert.equal(future.goals.length,474)
const beforeBy=new Map<string,any>(before.goals.map((g:any)=>[g.id,g])),futureBy=new Map<string,any>(future.goals.map((g:any)=>[g.id,g]))
for(const g of before.goals){const expected=g.id===parent?{...g,contains:[...g.contains,terminal]}:g;assert.deepEqual(futureBy.get(g.id),expected)}
const newGoal=futureBy.get(terminal),originalGoal=read(resolve(author,'bounded-bylk-terminal.whole-goal.candidate.json'))
assert.deepEqual({...newGoal,examData:{...newGoal.examData,reviewStatus:'needs_review'},extendedData:{...newGoal.extendedData,assessmentBasis:originalGoal.extendedData.assessmentBasis}},originalGoal)
assert.equal(newGoal.examData.reviewStatus,'released');assert.equal(newGoal.extendedData.assessmentBasis.humanApproval,false);assert.equal(newGoal.extendedData.assessmentBasis.humanTrial,false)
assert.deepEqual(newGoal.requires,[target]);assert.deepEqual(newGoal.examData.coveredGoalIds,[target])
const kinds=read(resolve(own,'before/kinds.json')),beforeKinds=structuredClone(kinds),kindChanges:any[]=[]
for(const d of kinds.decisions){const current=fingerprintSemanticKindSourceGoal(futureBy.get(d.goalId));if(d.sourceFingerprint!==current){kindChanges.push({goalId:d.goalId,before:d.sourceFingerprint,after:current,classificationUnchanged:true});d.sourceFingerprint=current}}
assert.deepEqual(kindChanges.map(r=>r.goalId),[parent])
kinds.decisions.push({goalId:terminal,sourceFingerprint:fingerprintSemanticKindSourceGoal(newGoal),semanticKind:'practiceAssessment',decisionStatus:'authoritative',decisionBasis:'reviewed-current-pilot-practice-assessment'});kinds.decisions.sort((a:any,b:any)=>a.goalId.localeCompare(b.goalId));kinds.counts.total++;kinds.counts.practiceAssessment++
assert.equal(kinds.counts.curricularAtomic,391);assert.equal(kinds.counts.total,474)
write(resolve(own,'candidate/semantic-kinds.future-active.json'),kinds)
const inertKinds={...kinds,sourceLandscapePath:relative(root,sourceCanon)},inertKindPath=resolve(own,'candidate/semantic-kinds.inactive-native.json');write(inertKindPath,inertKinds)
const ajv=new Ajv2020({strict:false,allErrors:true});addFormats(ajv);const schemaCheck=ajv.compile(read(resolve(root,'docs/landscape-runtime.schema.json')));assert.ok(schemaCheck(future),ajv.errorsText(schemaCheck.errors))
const originalFull=read(resolve(author,'native-full391.after-terminal.book-model.json')),originalCfg=read(resolve(author,'native-full391.after-terminal.book.config.json'))
const fullConfig={...originalCfg,landscapePath:relative(root,sourceCanon),semanticKindLedgerPath:relative(root,inertKindPath),outputPath:relative(root,resolve(own,'native-full391.reviewed-terminal.inactive.book-model.json'))}
const manifest=read(resolve(root,fullConfig.compositionViewManifestPath)),qa=read(resolve(root,fullConfig.goalVisualizationQaPath)),digests:Record<string,string>={}
for(const row of qa.records)if(row.visualizationState==='available')digests[row.imageUrl]=sha(bytes(resolve(root,row.publicAssetPath)))
const modelFull=buildGoalBookModel({landscape:future,semanticKindLedger:inertKinds,compositionViewManifest:manifest,compositionViewSources:manifest.sourcePaths.map((p:string)=>({path:p,view:read(resolve(root,p))})),navigationView:read(resolve(root,manifest.navigationViewPath)),durationModelPolicy:read(resolve(root,manifest.durationModelPolicyPath)),goalVisualizationQa:qa,goalVisualizationAssetDigests:digests,evidenceReviewSources:[],config:fullConfig} as any)
assert.equal(modelFull.pages.length,391)
const oldPageBy=new Map(originalFull.pages.map((p:any)=>[p.goalId,p]));for(const p of modelFull.pages)assert.equal(p.pageFingerprint,(oldPageBy.get(p.goalId)as any).pageFingerprint,'Release metadata/source alias must not alter actually reviewed page')
const mappingPaths=read(resolve(root,'app/scripts/config/goal-books/de-gym-biology-national-atlas.inputs.json')).mappingPaths
const oldSources=buildGoalBookOriginalSources(originalFull,root,mappingPaths),newSources=buildGoalBookOriginalSources(modelFull,root,mappingPaths)
for(const k of Object.keys(oldSources).filter(k=>k!=='bookDigest'))assert.deepEqual((newSources as any)[k],(oldSources as any)[k])
write(resolve(own,'native-full391.reviewed-terminal.inactive.book-model.json'),modelFull);write(resolve(own,'native-full391.reviewed-terminal.inactive.config.json'),fullConfig)
const futureActiveCfg={...fullConfig,landscapePath:activeCanon,semanticKindLedgerPath:activeKinds};write(resolve(own,'native-full391.future-active.config.json'),futureActiveCfg)
const applicability=buildApplicabilityCompilation(),bioAP=applicability.reports.find(r=>r.landscapeId===future.landscapeId)!,newEndpointAP=bioAP.goals.find(g=>g.goalId===terminal)!
assert.deepEqual(newEndpointAP.compiledApplicability,{jurisdiction:['DE-BY']})
const route=evaluateRouteProfile(future,routeProfiles.find(p=>p.profileId==='canonical-biology-sek2')!,applicability)
for(const id of ['CQR-101','CQR-102','CQR-202','CQR-203'])assert.equal(route.rules.find(r=>r.id===id)?.status,'pass',id)
write(resolve(own,'checks/native-current391-and-reviewed-terminal.technical.json'),{seals,canonical:bind(sourceCanon),schemaPASS:true,wholeGoals:474,curricularAtomic:391,all391PagesExactAuthorReviewedBeforeRelease:true,other390OriginalPageBindingsUnchanged:true,allOriginalSourcesAndScopeExact:true,kindChanges,newEndpointKind:kinds.decisions.find((d:any)=>d.goalId===terminal),nativeRoute:route,newEndpointApplicability:newEndpointAP,nativeCQR104:'not_configured: Biology native route profile has no compositionViewStage',activeWrites:0,strictGain:0,humanApproval:false,humanTrial:false})
const out=resolve(own,'native-d-one'),sourceBundle=resolve(author,'native-d-one/bundle')
for(const n of readdirSync(sourceBundle,{recursive:true}) as string[]){const p=resolve(sourceBundle,n);try{readFileSync(p)}catch{continue}copy(p,resolve(out,'bundle',n))}
copy(resolve(sourceBundle,'review-bundle-manifest.json'),resolve(out,'bundle/manifest.json'))
const bundle=read(resolve(out,'bundle/manifest.json')),model=read(resolve(out,'bundle/book-model.json'))
const input=read(resolve(srcA,'native-d-one/description-review-input.json')),inputB=read(resolve(followB,'description-review-input.json'));assert.equal(stableGoalBookJson(input),stableGoalBookJson(inputB));assert.equal(stableGoalBookJson(input),stableGoalBookJson(read(resolve(author,'native-d-one/round-a/description-review-input.json'))))
const originalFirstCampaign=read(resolve(srcA,'native-d-one/description-review-campaign.json')),originalSecondCampaign=read(resolve(followB,'description-review-campaign.json'))
assert.equal(originalFirstCampaign.batchSize,1);assert.equal(originalSecondCampaign.batchSize,1)
const firstCampaign={...originalFirstCampaign,batchSize:20},secondCampaign={...originalSecondCampaign,batchSize:20}
write(resolve(out,'campaign-lineage/original-a.campaign.exact.json'),originalFirstCampaign);write(resolve(out,'campaign-lineage/original-b.campaign.exact.json'),originalSecondCampaign)
write(resolve(out,'campaign-lineage/container-capacity-only-normalization.technical.json'),{originalA:bind(resolve(srcA,'native-d-one/description-review-campaign.json')),originalB:bind(resolve(followB,'description-review-campaign.json')),changedField:'batchSize',before:1,after:20,actualGoalCountUnchanged:1,actualInputJsonlUnchanged:true,actualRecordBytesUnchanged:true,actualRunManifestBytesUnchanged:true,reviewIdentityAndTimestampsUnchanged:true,newScientificReview:false,newRun:false,reason:'Existing native RolloutBatch loader requires container capacity20 for any batch. This is technical packaging of actual completed one-goal original reviews, never a claimed additional review.'})
for(const k of ['campaignId','roundId','independenceGroupId'])assert.notEqual(firstCampaign[k],secondCampaign[k]);assert.equal(firstCampaign.blindToOtherReviews,true);assert.equal(secondCampaign.blindToOtherReviews,true)
const batchId='biologie-11675-reviewed-terminal-context-paired-20261007-v1',configPath=resolve(own,'native-d-one.batch.config.json'),cfg={$schema:'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-rollout-batch-config.schema.json',schemaVersion:1,batchId,subject:'biologie',subjectLabel:'Biologie',bookId:model.book.id,title:model.book.title,outputDirectory:relative(root,out),baseGoalBookConfigPath:relative(root,resolve(own,'native-full391.future-active.config.json')),goalIds:[target],feedbackBaseUrl:'https://skillpilot.com/feedback',promptPath:relative(root,resolve(author,'native-d-one/round-a/prompt.md')),criteriaPath:relative(root,resolve(author,'native-d-one/round-a/criteria.md')),publicRoot:'app/public'};write(configPath,cfg)
const roundBinding=(directory:string,c:any)=>({directory,campaignId:c.campaignId,campaignDigest:fingerprintGoalDescriptionReviewCampaign(c),roundId:c.roundId,independenceGroupId:c.independenceGroupId,batchId:c.batches[0].batchId,batchInputFingerprint:c.batches[0].batchInputFingerprint})
const batchManifest={$schema:'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-rollout-batch-manifest.schema.json',schemaVersion:1,validationContract:'goal-description-rollout-batch-v1',batchId,subject:'biologie',subjectLabel:'Biologie',configPath:relative(root,configPath),configDigest:sha(readFileSync(configPath)),goalIds:[target],curriculumAtomicDenominatorAtPreparation:391,source:{baseGoalBookConfigPath:cfg.baseGoalBookConfigPath,landscapePath:model.source.landscapePath,landscapeId:model.book.landscapeId,baseBookDigest:modelFull.digest},artifacts:{bundleDirectory:'bundle',bookModelPath:'bundle/book-model.json',bookModelDigest:model.digest,bundleManifestPath:'bundle/manifest.json',bundleFingerprint:bundle.bundleFingerprint,reviewInputFingerprint:input.reviewInputFingerprint,rounds:{first:roundBinding('round-a',firstCampaign),second:roundBinding('round-b',secondCampaign)}},reviewPolicy:{oneBatchPerRound:true,blindIndependentFirstPass:true,aiRecordsAreCandidatesOnly:true,automaticAcceptance:false}};write(resolve(out,'batch-manifest.json'),batchManifest)
for(const [side,campaign,sourceResults] of [['a',firstCampaign,resolve(srcA,'native-d-one/results')],['b',secondCampaign,resolve(followB,'native-results')]] as any[]){const campaignSource=resolve(author,'native-d-one/round-'+side),dest=resolve(out,'round-'+side);for(const n of ['description-review-input.json','review-bundle-manifest.json','prompt.md','criteria.md','contracts/goal-description-review-record.schema.json'])copy(resolve(campaignSource,n),resolve(dest,n));write(resolve(dest,'description-review-campaign.json'),campaign);const bid=campaign.batches[0].batchId;copy(resolve(campaignSource,'batches',bid+'.input.jsonl'),resolve(dest,'batches',bid+'.input.jsonl'));for(const s of ['records.jsonl','run.json'])copy(resolve(sourceResults,bid+'.'+s),resolve(dest,'results',bid+'.'+s));const run=read(resolve(dest,'results',bid+'.run.json'));assert.equal(run.blindToOtherRuns,true);assert.equal(run.independenceGroupId,campaign.independenceGroupId)}
await validatePreparedGoalDescriptionRolloutBatch(relative(root,configPath));const dual=await materializeGoalDescriptionRolloutBatchDualSummary(relative(root,configPath),true)
const goal=input.goals[0],firstExtract=extractGoalDescriptionDualRoundResolutionSource({artifacts:dual.first,goalId:target,label:'actual sealed A'}),secondExtract=extractGoalDescriptionDualRoundResolutionSource({artifacts:dual.second,goalId:target,label:'actual sealed B'});assert.deepEqual(firstExtract.errors,[]);assert.deepEqual(secondExtract.errors,[]);const first=firstExtract.source!,second=secondExtract.source!;assert.equal(first.decision,'keep');assert.equal(second.decision,'keep')
const synthesizedAt=new Date(Math.max(...[...dual.first.resultPairs,...dual.second.resultPairs].map(({run}:any)=>Date.parse(run.completedAt)))+1000).toISOString(),batchBinding={batchId,batchManifestDigest:sha(readFileSync(resolve(out,'batch-manifest.json'))),configDigest:batchManifest.configDigest,bundleFingerprint:bundle.bundleFingerprint,bookDigest:input.bookDigest,reviewInputFingerprint:input.reviewInputFingerprint,dualSummaryDigest:sha(dual.bytes),canonicalLandscapeDigest:sha(bytes(sourceCanon))}
const rounds={first:buildGoalDescriptionRolloutSynthesisRoundBinding(first.binding,firstCampaign.batches[0].batchInputFingerprint),second:buildGoalDescriptionRolloutSynthesisRoundBinding(second.binding,secondCampaign.batches[0].batchInputFingerprint)},finalText={titleDe:goal.currentTitleDe,titleEn:goal.currentTitleEn,descriptionDe:goal.currentDescriptionDe,descriptionEn:goal.currentDescriptionEn}
const decision={decisionId:batchId+'-decision-'+target,goalId:target,effectiveSemanticKind:'curricularAtomic',goalFingerprint:goal.goalFingerprint,pageFingerprint:goal.pageFingerprint,goalReviewContextFingerprint:fingerprintGoalDescriptionReviewContext(goal),finalText,resolutionDecision:'keep_current',evidenceRound:'first',records:{first:{recordId:first.binding.recordId,recordDigest:first.binding.recordDigest},second:{recordId:second.binding.recordId,recordDigest:second.binding.recordDigest}},rationaleDe:'Technische Zusammenführung der tatsächlichen versiegelten unabhängigen A-/B-KEEP-Prüfungen der vollständigen aktuellen ENG/EKG-Seite und neuen begrenzten BY-LK-Terminalbindung. Unveränderte eigene Beschreibungen, P-Bodies und PNGs; ausschließlich eine geprüfte Rückwärts-Kontextbindung wiederhergestellt. A: '+first.record.rationale.slice(0,1500)+' B: '+second.record.rationale.slice(0,1500),rationaleEn:'Technical synthesis of actual sealed independent A/B KEEP reviews of the whole current ENG/ECG native page and bounded new BY-LK terminal context. Own goal text, positive profiles and PNG remain unchanged. This restores one current description binding; it adds no curricular target or scientific completion. Machine QA only; no human approval or trial. A: '+first.record.understandingEvidence.essentialUnderstandingEn.slice(0,1500)+' B: '+second.record.understandingEvidence.essentialUnderstandingEn.slice(0,1500)}
const payload={$schema:'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-rollout-synthesis-decision-manifest.schema.json',schemaVersion:1,synthesisContract:'goal-description-rollout-synthesis-decision-v1',manifestId:batchId+'-synthesis',authority:'ai_synthesis',synthesizedBy:'Codex technical integrator: exact actual sealed A/B KEEP synthesis; no new review or human approval',synthesizedAt,batch:batchBinding,rounds,decisions:[decision]};const synthesis={...payload,manifestFingerprint:fingerprintGoalDescriptionRolloutSynthesisDecisionManifest(payload as any)}
const sv=await validateGoalDescriptionRolloutSynthesisDecisionManifest({manifest:synthesis as any,expected:{batch:batchBinding as any,rounds,synthesizedAt,goals:[{goalId:target,effectiveSemanticKind:'curricularAtomic',goalFingerprint:goal.goalFingerprint,pageFingerprint:goal.pageFingerprint,goalReviewContextFingerprint:fingerprintGoalDescriptionReviewContext(goal),finalText,firstSource:first,secondSource:second}] as any}});assert.deepEqual(sv.errors,[])
write(resolve(out,'synthesis-decisions.json'),synthesis);const synthesisBytes=readFileSync(resolve(out,'synthesis-decisions.json')),fact=buildGoalDescriptionRolloutResolutionSynthesis({batchId,manifest:synthesis as any,decision:decision as any,summaryGoal:dual.summary.goals[0],firstSource:first,secondSource:second})
const resolution=buildGoalDescriptionDualRoundResolution({resolutionId:batchId+'-resolution-'+target,goalId:target,effectiveSemanticKind:'curricularAtomic',decision:'keep_current',synthesis:fact,dualSummaryBytes:dual.bytes,currentInput:input,firstSource:first,secondSource:second,synthesisDecisionManifest:{contract:'goal-description-rollout-synthesis-decision-v1',manifestId:synthesis.manifestId,manifestPath:'synthesis-decisions.json',manifestDigest:sha(synthesisBytes),manifestFingerprint:synthesis.manifestFingerprint,decisionId:decision.decisionId}})
const validation=await validateGoalDescriptionDualRoundResolution({resolution,dualSummary:dual.summary,dualSummaryBytes:dual.bytes,currentInput:input,landscape:future,first:dual.first,second:dual.second,synthesisDecisionManifestArtifact:{manifest:synthesis as any,manifestBytes:synthesisBytes,manifestPath:'synthesis-decisions.json'}});assert.deepEqual(validation.errors,[]);assert.equal(validation.strictDescriptionComplete,true)
const resolutionPath=resolve(out,'resolutions',target+'.resolution.json');write(resolutionPath,resolution)
const index={$schema:'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-standalone-batch-resolution-index.schema.json',schemaVersion:2,indexContract:'goal-description-standalone-batch-resolution-index-v1',artifactSetId:batchId+'-strict-resolutions',subject:'Biologie',semanticKind:'curricularAtomic',batchGoalIds:[target],groups:[{groupId:batchId,artifactDirectory:'.',dualSummaryPath:'dual-summary.json',dualSummaryDigest:sha(dual.bytes),campaignGoalCount:1,resolvedGoalCount:1}],resolutions:[{goalId:target,titleDe:goal.currentTitleDe,groupId:batchId,decision:'keep_current',resolutionPath:'resolutions/'+target+'.resolution.json',resolutionDigest:sha(readFileSync(resolutionPath)),resolutionFingerprint:resolution.resolutionFingerprint,strictDescriptionComplete:true}]}
const indexValidator=ajv.compile(read(resolve(root,'contracts/goal-description-review/v1/goal-description-standalone-batch-resolution-index.schema.json')));assert.ok(indexValidator(index),ajv.errorsText(indexValidator.errors));const indexPath=resolve(out,'resolution-index.json');write(indexPath,index)
const registry=read(resolve(root,activeRegistry)),bio=registry.subjects.find((s:any)=>s.subject==='biologie');assert.deepEqual(bio,baseline.registryBiology)
const owners=bio.resolutionIndexPaths.filter((p:string)=>read(resolve(root,p)).resolutions?.some((e:any)=>e.goalId===target));assert.equal(owners.length,1);const newBio=structuredClone(bio);newBio.resolutionIndexPaths.push(relative(root,indexPath));newBio.resolutionSupersessions??=[];newBio.resolutionSupersessions.push({goalId:target,supersededIndexPath:owners[0],replacementIndexPath:relative(root,indexPath)})
write(resolve(own,'candidate/registry-biologie.future-entry.json'),newBio)
write(resolve(own,'checks/targeted-registry-patch.technical.json'),{subject:'biologie',before:bio,after:newBio,appendIndexPath:relative(root,indexPath),singleSupersession:newBio.resolutionSupersessions.at(-1),otherRegistryFieldsExact:true,otherSubjectsMustRemainExact:true,newScientificClosures:0,restoredBindings:1,activeWrites:0})
write(resolve(own,'checks/D1-native-resolution-and-current-canonical.technical.json'),{seals,nativePreparedBatch:'PASS',nativeDualSummary:'PASS',nativeSynthesis:'PASS',nativeResolution:'PASS',strictDescriptionComplete:true,index:bind(indexPath),canonicalLandscapeDigestInSynthesis:batchBinding.canonicalLandscapeDigest,exactPreparedFutureCanonicalDigest:bind(sourceCanon).sha256,currentReviewInput:bind(resolve(srcA,'native-d-one/description-review-input.json')),genuineRecordsCopiedUnchanged:true,distinctBlindCampaigns:true,newScientificReviewerInvented:false,humanApproval:false,humanTrial:false,newScientificClosures:0,restoredCurrentDescriptionBindings:1,activeWrites:0})
write(resolve(own,'checks/technical-declared-inputs.json'),{files:[...declared.values()]})
console.log(JSON.stringify({nativeD1:'PASS',nativeFull391:'PASS',nativeCQR101:'PASS',nativeCQR102:'PASS',nativeCQR202:'PASS',nativeCQR203:'PASS',CQR104:'not_configured',canonicalFutureDigest:bind(sourceCanon).sha256,wholeCount:474,curricularAtomic:391,newScienceClosures:0,restoredD1Binding:1,activeWrites:0}))
