import {readFileSync,writeFileSync} from 'node:fs'
import {dirname,resolve} from 'node:path'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
import assert from 'node:assert/strict'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import {validatePositiveGoalEvidenceRecordSemantics} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel'
import {validateGoalDescriptionReviewCampaignResultDirectories} from '../../../../../../../app/scripts/validateGoalDescriptionReviewCampaignResults'
import {fingerprintSemanticKindSourceGoal} from '../../../../../../../app/scripts/goalBookModel'
const root=resolve('.'),own=dirname(fileURLToPath(import.meta.url)),base=dirname(own),author=resolve(base,'biologie-he-evolution-one-current-subset-first-pass-neutral-root-20261008-v3'),tech=resolve(base,'biologie-he-evolution-one-cat-raster-native-followup-technical-20261008-v2'),original=resolve(base,'biologie-he-evolution-eighteen-raster-native-author-technical-20261008-v1'),gid='7008979d-7890-5f7b-ad07-27b8bb597cbe'
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));const hash=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex')
const first=resolve(own,'one-current-native-D-P-V.independent-b.first.freeze.json');assert.equal(hash(first),'c43da1bbcf9c5e7a65d3a291c7227a9536e47eb5512feca5b6c60f296996cf49')
for(const x of read(first).files){assert.equal(hash(resolve(root,x.path)),x.sha256);assert.equal(readFileSync(resolve(root,x.path)).length,x.bytes)}
const q=resolve(author,'round-b'),result=await validateGoalDescriptionReviewCampaignResultDirectories({bundle:read(resolve(q,'review-bundle-manifest.json')),input:read(resolve(q,'description-review-input.json')),campaign:read(resolve(q,'description-review-campaign.json')),batchesDirectory:resolve(q,'batches'),resultsDirectory:resolve(own,'current-one-first-pass-b/results')});assert.deepEqual(result.errors,[]);assert.equal(result.records.length,1);assert.equal(result.records[0].goalId,gid);assert.equal(result.records[0].decision,'keep')
writeFileSync(resolve(own,'D1.actual-current-own-native-campaign.independent-b.receipt.json'),JSON.stringify({schemaVersion:1,reviewedAt:new Date().toISOString(),nativeApi:'validateGoalDescriptionReviewCampaignResultDirectories',actualOwnCurrentD1Records:1,batchSize:1,goalCount:1,reviewPass:'first_pass corrected current subset',pageFingerprint:result.records[0].pageFingerprint,currentSubsetContext:'sha256:b30963b3cf5d230b89a777ae4ab884fa1a1c97273ba772b855d92f73aef61dcb',noHelperTo18Adoption:true,other17OriginalSealedRunRecordsUnchanged:true,errors:result.errors,ownFirstSealSha256:hash(first),currentPeerRead:false,activeWrites:0,humanApproval:false},null,2)+'\n',{flag:'wx'})
console.log('Actual own D1 full current subset native campaign API:1 KEEP candidate,0 errors; old17 preserved.')
const landscape=read(resolve(original,'candidate/canonical.current476.actual-raster.inactive.json')),kind=read(resolve(original,'candidate/semantic-kinds.current476.actual-raster.inactive.json')).decisions.find((x:any)=>x.goalId===gid),goal=landscape.goals.find((x:any)=>x.id===gid),row=readFileSync(resolve(tech,'positive/P18.only-one-current-PNG-rebound.seventeen-lines-exact.jsonl'),'utf8').trim().split('\n').map(x=>JSON.parse(x)).find(x=>x.goalId===gid)
assert.equal(kind.semanticKind,'curricularAtomic');assert.equal(kind.sourceFingerprint,fingerprintSemanticKindSourceGoal(goal))
const links=goal.resourceLinks.filter((x:any)=>x.type==='goal-visualization');assert.equal(links.length,1)
const actualPNG=resolve(tech,'selected-images',gid+'.png'),digest='sha256:'+hash(actualPNG);assert.equal(digest,'sha256:cae551e813945967b2dc9d889ab04517da989fcfa131d5b1911e431d27033758');const urlDigests:Record<string,string>={[links[0].url]:digest}
const ajv=new Ajv2020({allErrors:true,strict:true});addFormats(ajv);const validate=ajv.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json')));assert.ok(validate(row),ajv.errorsText(validate.errors));assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(row,goal,urlDigests,'curricularAtomic'),[])
assert.equal(row.status,'needs_human_review');assert.equal(row.reviewAuthority,'ai_candidate');assert.equal(row.evidenceLevel,'E1');assert.equal(row.maximumClaimScope,'G1');assert.equal(row.reviewCriteriaFingerprint,'sha256:'+hash(resolve(root,'curricula/DE/Gymnasium/quality/goal-evidence/prompts/biology-positive-understanding-evidence-profile-criteria-v1.md')))
writeFileSync(resolve(own,'P1.actual-current-PNG-closed-schema-semantics.independent-b.receipt.json'),JSON.stringify({schemaVersion:1,reviewedAt:new Date().toISOString(),nativeApi:'validatePositiveGoalEvidenceRecordSemantics',goalId:gid,actualPNG,actualDigest:digest,resourceDigests:urlDigests,semanticKind:kind.semanticKind,goalFingerprint:row.goalFingerprint,profileFingerprint:row.profileFingerprint,reviewInputFingerprint:row.reviewInputFingerprint,schemaErrors:0,semanticErrors:0,status:row.status,reviewAuthority:row.reviewAuthority,evidenceLevel:row.evidenceLevel,maximumClaimScope:row.maximumClaimScope,wholeTwoCasesAndWholeProfileGenuineScienceRetained:true,targetedActualImageContextReviewed:true,noFingerprintOnlyScienceClaim:true,ordinaryCurrentRasterPCLI:'pending actual installation; native API uses actual candidate PNG bytes',currentPeerRead:false,activeWrites:0,humanApproval:false,humanTrial:false},null,2)+'\n',{flag:'wx'})
console.log('Actual own P1 closed-v2 schema/current correct PNG native API:0 errors; E1/G1 ai_candidate needs_human_review, no practical/human approval.')
