from pathlib import Path
import json,copy,hashlib,tempfile,shutil,os
from jsonschema import Draft202012Validator
R=Path('/home/enpasos/projects/skillpilot');D=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-seven-market-money-current532-status-nav-fullclosure-access-author-a-v1/physical-whole-reader-input-successor-v3';O=D/'thirteen-induced-existing9f-qualified-body-access-author-successor-v4';O.mkdir(exist_ok=False);ID='9f234592-2e3f-58c0-aa1a-e5971818c447'
def b(p):return {'path':str(p.relative_to(R)) if p.is_relative_to(R) else str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}
def put(n,v):
 p=O/n;assert not p.exists();p.parent.mkdir(parents=True,exist_ok=True);assert p.resolve().is_relative_to(O.resolve());p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');json.loads(p.read_text());return b(p)
idxp=D/'actual-final539-seven-market-money156-access13support-two-nav-whole-input.AUTHOR-index-v2.json';idx=json.loads(idxp.read_text());npp=D/'actual-final-five-native-current539-market156-support13-fullclosure-source64sets-and-two-genuine-drops.AUTHOR.json';np=json.loads(npp.read_text());can=json.loads((R/idx['wholeCurrent539Candidate']['path']).read_text());by={g['id']:g for g in can['goals']};m=by[ID];sp=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-seven-local-E-whole-science-independent-b-v1/one-real-responsibility-whole-performance-independent-followup-v2/actual-final-E7-seven-whole-science-independent-b-KEEP.handoff.receipt.json';sc=json.loads(sp.read_text());dec=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-seven-local-E-whole-science-independent-b-v1/actual-seven-individual-whole-DEEN-material-scientific-six-KEEP-one-REVISE.independent-b.json';ds=json.loads(dec.read_text());dr=next(r for r in ds['individualMaterials'] if r['materialId']==ID);assert dr['decision']=='KEEP';u=copy.deepcopy(m);u['examData']['reviewStatus']=dr['wholeActualCandidate']['examData']['reviewStatus'];u['examData'].pop('reviewNote',None);assert u==dr['wholeActualCandidate'];whole=put('whole-current539-existing9f-DEEN-body-and-both-whole-covered-goal-originalP4.exact-binding.json',{'role':'Whole current body science reuse binding; no fresh own 9f scientific approval','wholeExisting9fMaterial':m,'wholeOriginalIndependentKEEPDecision':dr,'wholeForeignScientificReceipt':b(sp),'wholeForeignOriginalScientificDecision':b(dec),'exactCurrentBodyMatchesForeignKEEPExceptReleasedStatus':True,'wholeBothCurrentCoveredContractsP4':[r for r in json.loads((R/idx['wholeBounded13PriceFoundationAuthorContext']['path']).read_text())['wholeThreeActuallyReadCurrentGoalsAndOriginalP6'] if r['wholeGoal']['id'] in m['examData']['coveredGoalIds']],'current539Input':idx['wholeCurrent539Candidate'],'historicalWholeScienceRestarts':0,'activeWrites':0,'ownIndependentScienceKEEP':False,'humanApproval':False})
rows=[];vsc=Draft202012Validator(json.loads((R/'contracts/curriculum-package/v1/composition-view.schema.json').read_text()));total=0
for vr in idx['whole35FinalViews']:
 v=json.loads((R/vr['wholeCandidateAfter156']['path']).read_text());aft=copy.deepcopy(v);eligible=bool(vr['actual13PrerequisiteOnlyBindings']);refs=[]
 if eligible:
  ref={'kind':'goalEntry','goalId':ID,'displayLabel':m['title'],'projectionRole':'target'};assert not any(c.get('goalId')==ID for c in aft['rootNodes'][0]['children']);aft['rootNodes'][0]['children'].append(ref);aft['viewId']='de-gym-econ-market9f-a-20261010-'+v['scope']['jurisdiction'].lower()+'-gk';refs.append(ref);total+=1
 errs=[{'path':list(e.path),'message':e.message} for e in vsc.iter_errors(aft)];assert not errs or not eligible
 c=put('whole35-final169targets13supports/'+Path(vr['activePath']).name,aft);undo=copy.deepcopy(aft)
 if refs:undo['rootNodes'][0]['children'].pop();undo['viewId']=v['viewId']
 assert undo==v
 rows.append({'activePath':vr['activePath'],'wholeScope':vr['wholeScope'],'wholeBefore156':vr['wholeCandidateAfter156'],'wholeAfter169Targets13Supports':c,'actualAdditional9fTargetReferences':refs,'wholeQualifiedScienceReuseBinding':whole if refs else None,'closedSchemaErrors':errs})
assert total==13;nr=next(r for r in rows if r['wholeScope'].get('jurisdiction')=='DE-HB' and r['wholeScope'].get('courseProfile')=='GK');neg=json.loads((R/nr['wholeAfter169Targets13Supports']['path']).read_text());where=[i for i,r in enumerate(neg['rootNodes'][0]['children']) if r.get('goalId')==ID];assert len(where)==1;neg['rootNodes'][0]['children'].pop(where[0]);negref=put('genuine-HBGK-existing9f-new-target-access-dropped.INERT-negative.json',neg)
caps={'before156':idx['capsules']['after156']};guards=[]
for mode in ['after169Targets13Supports','negative9fAccess']:
 cap=Path(tempfile.mkdtemp(prefix='skillpilot-economics-market-existing9f-thirteen-author-a-'+mode+'-'))/'capsule';shutil.copytree(Path(caps['before156']),cap,symlinks=True,copy_function=os.link)
 for r in rows:
  if not r['actualAdditional9fTargetReferences']:continue
  p=cap/r['activePath'];assert p.exists() and not p.is_symlink() and p.resolve().is_relative_to(cap.resolve());active=R/r['activePath'];same=os.path.samefile(p,active);p.unlink();p.write_bytes((R/r['wholeAfter169Targets13Supports']['path']).read_bytes());assert not os.path.samefile(p,active);guards.append({'path':str(p),'resolvedInsidePrivate':True,'sameFileActiveBeforeMutation':same,'detachedBeforeMutation':True,'notSameFileActiveAfterMutation':True})
 if mode=='negative9fAccess':
  p=cap/nr['activePath'];assert p.resolve().is_relative_to(cap.resolve());p.unlink();p.write_bytes((R/negref['path']).read_bytes());assert not os.path.samefile(p,R/nr['activePath']);guards.append({'path':str(p),'resolvedInsidePrivate':True,'detachedBeforeMutation':True,'notSameFileActiveAfterMutation':True})
 caps[mode]=str(cap)
for r in idx['basis532']['wholeInputs']:assert b(R/r['path'])['sha256']==r['sha256']
final=put('actual-thirteen-existing9f-target-accesses-only-on-frozen-market156-plus13support.AUTHOR-index-v4.json',{'role':'AUTHOR thirteen append-only existing foreign wholeKEEP material accesses on exact Market156+13POnly frame; foreign scope review pending','wholeMarketInputIndex':b(idxp),'wholeMarketFiveNativeFrames':b(npp),'wholeQualifiedExisting9fScienceAndCurrentContractsBinding':whole,'wholeForeignScienceReceipt':b(sp),'wholeExisting9fID':ID,'wholeUnmodifiedCAN539':idx['wholeCurrent539Candidate'],'wholeUnmodifiedSEM539':np['wholeConditional539SEM'],'whole35BeforeAfterViews':rows,'actualAdditionalExisting9fCountryRefs':13,'actualTotalSevenNewMaterialCountryRefs':156,'actualTotalMaterialTargetCountryRefs':169,'actualTotalFoundationSupportCountryRefs':13,'actualTotalReferences':182,'nationalEdits':0,'inducedDebtCounts':{'beforeEndpointScopes':12,'afterMarket156EndpointScopes':20,'additionalAffectedEndpointScopes':8,'actualAdditionalExpectedExisting9fGKViewPairs':13,'eightScopesIsNotThirteenReferences':True},'wholeGenuineNegative9fAccess':negref,'negativeActivePath':nr['activePath'],'capsules':caps,'privateWriteGuards':guards,'productionExactExportHelperPath':idx['productionExactExportHelperPath'],'noCANSEMBodyNavSourceOrdinaryPCardMutation':True,'activeWrites':0,'ownIndependentScopeKEEP':False})
print(json.dumps(final))
