from pathlib import Path
import json,hashlib
from datetime import datetime,timezone
ROOT=Path.cwd()
AUTHOR=ROOT/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/chemie-q3-three-BW-current-raster-native-preparation-author-20261010-v1'
OUT=ROOT/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/chemie-q3-three-BW-current-native-independent-a-20261010-v1'
def read(p):return json.loads(p.read_text())
def digest(b):return 'sha256:'+hashlib.sha256(b).hexdigest()
campaign=read(AUTHOR/'native/three-current-P/round-a/description-review-campaign.json');input=read(AUTHOR/'native/three-current-P/round-a/description-review-input.json');bundle=read(AUTHOR/'native/three-current-P/round-a/review-bundle-manifest.json')
runid='chemie-three-BW-current-native-independent-a-20261010-v1'
judgments=[
 {
  'essentialUnderstandingDe':'Eine kontrollierte Konzentrationsänderung kann die Lage eines homogenen Gleichgewichts verändern. Referenz, gleiche Zugabevolumina und passende Blindwerte trennen den Konzentrationseffekt von Verdünnung und Eigenfarbe; bei gleicher Temperatur bleibt die Gleichgewichtskonstante unverändert. Beobachtung und begrenzte Le-Chatelier-Deutung sind verschiedene Schritte derselben Untersuchung.',
  'essentialUnderstandingEn':'A controlled concentration change can alter the position of a homogeneous equilibrium. A reference, matched addition volumes, and appropriate blanks distinguish concentration effects from dilution and inherent colour; at fixed temperature the equilibrium constant is unchanged. Observation and a bounded Le Chatelier interpretation are distinct steps of the same investigation.',
  'observablePerformanceDe':'Die lernende Person dosiert und mischt die vorgeschriebene Einzelvariation unter den angegebenen Schutzbedingungen, protokolliert Ausgangszustand, Referenz und Kontrolle mit gleichen Messbedingungen und erklärt den relativen Farbbefund mit Le Chatelier. Sie benennt Modellgrenzen und unterscheidet die erforderliche beobachtete Durchführung von der vorliegenden synthetischen Ausarbeitung.',
  'observablePerformanceEn':'The learner doses and mixes the specified single variation under the stated protection conditions, records the initial state, reference, and control under matched measurement conditions, and explains the relative colour observation using Le Chatelier. They state model limitations and distinguish the required observed execution from the supplied synthetic worked material.',
  'transferExpectationDe':'In einem unabhängig vorgelegten neuen Ansatz erkennt die lernende Person, dass eine schwächere Farbe nach bloßer Verdünnung noch keinen isolierten Nachweis einer chemischen Verschiebung liefert, und schlägt einen passenden Vergleich vor. Bei zusätzlicher Temperaturänderung begrenzt sie die Konzentrationskausalität, statt aus zwei veränderten Faktoren eine eindeutige Ursache abzuleiten.',
  'transferExpectationEn':'For an independently supplied fresh mixture, the learner recognizes that weaker colour after dilution alone does not isolate a chemical equilibrium shift and proposes an appropriate comparison. When temperature also changes, they limit the concentration-causality claim rather than infer a unique cause from two changed factors.',
  'rationale':'KEEP nach tatsächlicher Prüfung der vollständigen DE/EN-Beschreibung, Native-PDF-Seite 3 und unverändertem HTML, Whole381-Ziel-/Vorbedingungskontext, aktuellem P3 und der Original-/360-/680-PNG. Die Beschreibung fordert eine zusammenhängende experimentelle Untersuchung mit kontrollierter Variation, Beobachtung, Protokoll und begrenzter Erklärung; sie ersetzt die Durchführung nicht durch Datenlesen. Primärquelle BW, physische PDF-Seite 27 / gedruckte S. 25, 3.3.2(7), bestätigt den experimentellen Operator für Basisfach und Leistungsfach. Dieses auf homogene Konzentrationsvariation begrenzte Ziel bleibt ein partial-Beitrag zu SOURCE002; Temperatur-, Druck- und übrige ganze Quellenpflichten werden nicht freigegeben. Beide synthetischen P-Fälle enthalten Volumen-/Blindkontrolle, sichere vorgegebene Reagenzien und frischen Transfer. Keine Quellen-, Atomaritäts-, Sprach- oder Bildkorrektur ist für diesen geprüften Native3-Kontext erforderlich.'
 },
 {
  'essentialUnderstandingDe':'Im vorgegebenen geschlossenen reversiblen Austauschmodell entsteht ein stationärer Zustand, wenn die beiden weiterhin stattfindenden Übertragungen je Runde annähernd gleich sind; die gespeicherten Mengen müssen dabei nicht gleich sein. Die Bestimmung beider Transfers aus demselben Rundenanfang und die Erhaltung der Gesamtmenge legen die Modellregel fest. Wasserübertragung ist eine Analogie und keine chemische Stoffumwandlung.',
  'essentialUnderstandingEn':'In the specified closed reversible-exchange model, a stationary state arises when both continuing transfers per round are approximately equal; the stored amounts need not be equal. Computing both transfers from the same round-start values and conserving the total define the model rule. Water exchange is an analogy, not chemical conversion.',
  'observablePerformanceDe':'Die lernende Person führt beide Entnahmen und kreuzweisen Zugaben regelgetreu aus, protokolliert Mengen und beide Transfermengen über die Zeit und prüft die Gesamtmenge sowie die Ableseauflösung. Sie wertet das Plateau anhand weiterhin positiver, annähernd gleicher Transfers aus und erklärt an ihrem Protokoll, weshalb unterschiedliche Mengen, dynamischer Austausch und begrenzte Modellanalogie zusammenpassen.',
  'observablePerformanceEn':'The learner carries out both withdrawals and crosswise additions according to the rules, records both stored and transferred amounts over time, and checks the total and reading resolution. They interpret the plateau through continuing positive, approximately equal transfers and explain from their record how unequal amounts, dynamic exchange, and a bounded model analogy fit together.',
  'transferExpectationDe':'Bei einer unabhängig vorgelegten neuen Gruppe mit nachträglich aus der bereits veränderten Rückmenge berechnetem Transfer erkennt die lernende Person die veränderte Modellregel und begründet einen anderen Verlauf. Bei einem Verlust von Wasser prüft sie die Erhaltungsbedingung und erkennt, dass ein späteres Plateau das ursprüngliche geschlossene Modell nicht bestätigt.',
  'transferExpectationEn':'For an independently presented fresh group calculating reverse transfer from the already changed amount, the learner identifies the altered model rule and explains why the trajectory changes. When water is lost, they check conservation and recognize that a later plateau does not establish the original closed model.',
  'rationale':'KEEP nach tatsächlicher Prüfung von DE/EN-Ziel, Native-PDF-Seite 4 und unverändertem HTML, Whole381-Kontext und aktuellem P3 mit beiden vollständigen Austauschprotokollen. Die Beschreibung grenzt eine integrierte praktische Modellkompetenz ab: regelgetreue Durchführung, Protokoll und Auswertung derselben Gleichgewichtseinstellung. Physische Primär-PDF-Seite 33 / gedruckte S. 31, BW 3.4.2(6), fordert Durchführung und Auswertung im Leistungsfach; eine Basisfach-Durchführung wird nicht behauptet. Beide Transferreihen wurden unabhängig aus den gleichen Rundenanfangswerten nachgerechnet und erhalten 90 mL. Original-/360-/680-PNG mit 30/60 mL und zwei gleichen 10-mL-Pfeilen passt zum modellhaften stationären Beispiel. Aktueller Alttext bezeichnet die gezeichneten Geräte zutreffend als Messspritzen. Gleichheit der Raten wird weder als gleiche Mengen noch als Stillstand oder reale Stoffumwandlung ausgegeben. Der ganze P-Vertrag deckt frische Regel-/Verlustfälle und die Durchführungsvoraussetzung ab; keine lokale Textänderung nötig.'
 },
 {
  'essentialUnderstandingDe':'Eine galvanische Zelle benötigt geeignete Halbzellen, elektronische Messleitungen und eine kompatible ionische Verbindung. Das Vorzeichen der Anzeige hängt von der Anschlussrichtung ab; ein hochohmiges Voltmeter nähert Leerlauf an, ohne exakt stromlos zu messen. Ein Vergleichswert gilt nur für die angegebenen Bedingungen und darf nicht ungeprüft mit Standard- oder Lastspannung gleichgesetzt werden.',
  'essentialUnderstandingEn':'A galvanic cell requires suitable half-cells, electronic measurement leads, and a compatible ionic connection. The reading sign depends on the lead arrangement; a high-impedance voltmeter approximates open circuit without exactly zero current. A reference applies only to its stated conditions and must not be equated without justification with standard or loaded voltage.',
  'observablePerformanceDe':'Die lernende Person baut die vorgegebene Zelle sicher mit zugehörigen Metall-/Elektrolytpaaren und kompatibler Salzbrücke auf, verbindet und bedient das hochohmige Gleichspannungsmessgerät und protokolliert Polung, Bedingungen und stabilisierte Anzeigen. Sie ermittelt einen begründeten näherungsweisen Leerlaufwert mit Streuung und beurteilt dessen Vereinbarkeit mit dem bedingungsspezifischen Vergleich, statt den synthetischen Wert als ausgeführten Versuch zu behandeln.',
  'observablePerformanceEn':'The learner safely assembles the specified cell with corresponding metal/electrolyte pairs and a compatible salt bridge, connects and operates the high-impedance DC meter, and records polarity, conditions, and stabilized readings. They determine a justified approximate open-circuit value with spread and evaluate compatibility with the condition-specific reference rather than treat the synthetic value as an executed experiment.',
  'transferExpectationDe':'An einer unabhängig vorgelegten neuen Messung mit vertauschten Leitungen unterscheidet die lernende Person das geänderte Anzeigevorzeichen von unveränderter galvanischer Polung. Bei einer Silberhalbzelle mit chloridhaltiger Brücke erkennt sie die chemische Änderung durch mögliche AgCl-Fällung und begründet, weshalb der ursprüngliche Vergleichswert und ein bloßes Kabeltauschargument den neuen Befund nicht freigeben.',
  'transferExpectationEn':'For an independently presented fresh measurement with swapped leads, the learner distinguishes the reversed display sign from unchanged galvanic electrode polarity. For a silver half-cell with a chloride-containing bridge, they recognize the chemical change from possible AgCl precipitation and explain why the original reference and a mere lead-swap argument do not validate the new observation.',
  'rationale':'KEEP nach tatsächlicher Prüfung des vollständigen DE/EN-Ziels, Native-PDF-Seite 5 und unverändertem HTML, Whole381-/P3-Kontext, Original-/360-/680-PNG und Primär-PDF-Seite 41 / gedruckte S. 39, BW 3.4.7(6) im Leistungsfach. Sicherer Aufbau, Protokoll, Ermittlung und begründeter Vergleich sind zusammengehörige Teile einer experimentellen Zellspannungsbestimmung. Die Beschreibung benennt mit hochohmig und näherungsweise die endliche Messbelastung korrekt und fordert ausdrücklich einen bedingungsspezifischen Vergleich. Die beiden synthetischen Fälle ergeben unabhängig 1,084333… V bzw. 0,423333… V bei jeweils 0,004 V Spannweite; sie belegen keine Ausführung und behaupten keine universellen Standardspannungen. Das tatsächliche Daniell-PNG zeigt richtige Zn-minus-/Cu-plus-Zuordnung, zusammenhängende eingetauchte Salzbrücke, 10-MΩ-Messgerät ohne Zahlenwert und keinen äußeren Last-/Stromquellenzweig. Vorzeichen- und Chloridtransfer sind chemisch sinnvolle neue Fälle. Keine Änderung des geprüften Text-/P-/Bildkontexts nötig.'
 }
]
records=[]
for g,j in zip(input['goals'],judgments,strict=True):
 r={'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json','schemaVersion':1,'recordId':runid+'.'+g['goalId'],'runId':runid,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'bundleFingerprint':input['bundleFingerprint'],'bookDigest':input['bookDigest']}
 for k in ['goalId','goalFingerprint','pageFingerprint','currentTitleDe','currentTitleEn','currentDescriptionDe','currentDescriptionEn']:r[k]=g[k]
 r.update(decision='keep',understandingEvidence={k:v for k,v in j.items() if k!='rationale'},rationale=j['rationale'],evidenceProfileContract='positive-understanding-evidence-v2',evidenceProfileRecommendation='none',recordStatus='candidate',reviewAuthority='ai_candidate')
 records.append(r)
batch=campaign['batches'][0];body=('\n'.join(json.dumps(r,ensure_ascii=False) for r in records)+'\n').encode();records_path=OUT/'results'/f"{batch['batchId']}.records.jsonl";records_path.write_bytes(body)
parameters={'execution':'independent Codex reviewer A in a separate agent; model version and sampling parameters are not exposed','role':'subject reviewer; no authorship or current other D-results','inputBoundary':'frozen normal Native3 on whole381 with current P and existing exact rasters; separately bound whole BW126 source and before185/after189 contexts','inspected':'actual native HTML/PDF and original/360/680 PNG pixels; complete six bilingual protocol cases','history':'only permitted prior independent P profile bodies and A/M/V binding references retained; earlier D records not read','outputAuthority':'candidate/ai_candidate; no active registry integration or human release'}
paramsbytes=(json.dumps(parameters,ensure_ascii=False,indent=2)+'\n').encode();(OUT/'generation-parameters.actual.json').write_bytes(paramsbytes)
completed=datetime.now(timezone.utc).isoformat();started=datetime.fromtimestamp((OUT/'inputs.entry.exact.json').stat().st_mtime,timezone.utc).isoformat()
run={'$schema':'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json','schemaVersion':1,'runId':runid,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'batchId':batch['batchId'],'batchInputFingerprint':batch['batchInputFingerprint'],'bundleFingerprint':input['bundleFingerprint'],'bookDigest':input['bookDigest'],'provider':'OpenAI','model':'Codex active model; exact version not exposed','role':'subject_reviewer','promptFamilyId':'goal-description-understanding-evidence-review-v2','promptFingerprint':campaign['promptFingerprint'],'criteriaFingerprint':campaign['criteriaFingerprint'],'generationParametersFingerprint':digest(paramsbytes),'independenceGroupId':campaign['independenceGroupId'],'blindToOtherRuns':True,'goalIds':batch['goalIds'],'inputArtifacts':[{'role':a['role'],'digest':a['digest']} for a in bundle['artifacts']]+[{'role':'description_review_batch_input_jsonl','digest':batch['batchInputFingerprint']}],'startedAt':started,'completedAt':completed,'status':'completed','outputDigest':digest(body),'toolchainVersion':'skillpilot-normal-native-review-v1'}
(OUT/'results'/f"{batch['batchId']}.run.json").write_text(json.dumps(run,ensure_ascii=False,indent=2)+'\n')
assert len(records)==3 and [r['goalId'] for r in records]==batch['goalIds'];assert len([json.loads(l) for l in body.decode().splitlines()])==3
print('Wrote exactly 3 independent ordinary KEEP candidate records and their truthful AI run manifest.')
