import{readFileSync,writeFileSync,copyFileSync}from'node:fs';import{join}from'node:path';import assert from'node:assert/strict';import Ajv2020 from'ajv/dist/2020.js';import{run,ids,canPath,CAP,OUT,ROOT}from'./actualNativeCurrent555Social13Common.mts';
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),save=(n:string,d:any)=>writeFileSync(join(OUT,n),JSON.stringify(d,null,2)+'\n');const ix=read(join(OUT,'actual-country-national209-practice-only-target-reference-appends.author-index.json'));const before=read(join(OUT,'intake-before-current555.actual-native.json'));const positive=()=>{copyFileSync(join(OUT,'whole-current568-thirteen-foreign-KEEP-three-Nav-one-derived-Q1-jurisdiction.INERT-final-author.json'),canPath);for(const v of ix.views)copyFileSync(v.afterPath,join(CAP,v.activePath));};
const val=new Ajv2020({strict:true,allErrors:true}).addKeyword({keyword:'x-skillpilot-listSemantics',schemaType:'string',valid:true,metaSchema:{enum:['ordered']}}).compile(read(join(ROOT,'contracts/curriculum-package/v1/composition-view.schema.json')));const schemas=ix.views.filter((v:any)=>v.actualNewReferenceCount).map((v:any)=>{assert.equal(val(read(v.afterPath)),true,JSON.stringify({view:v.activePath,errors:val.errors}));return{view:v.activePath,errors:0};});assert.equal(schemas.length,34);save('actual34-changed-crossstage-closed-schema-errors0.author.json',{changedWholeViews:schemas,oneHistoricalSekIUnchangedNotNewlySchemaApproved:true});
positive();const after=run('final-after-current568-social13-209-whole-accesses');
for(let i=0;i<before.all64NativeScopeSets.length;i++){const b=structuredClone(before.all64NativeScopeSets[i]),a=structuredClone(after.all64NativeScopeSets[i]);for(const key of ['allTargetAtomicIds','allSupportAtomicIds'])a[key]=a[key].filter((id:string)=>!ids.includes(id));assert.deepEqual(a,b);}
const pg=read(join(OUT,'whole-current555-thirteen-original-contracts-actualP28-and336P685-exact-author-endguards.json'));for(const p of pg.allCurrentOriginalWholeP)assert.deepEqual(after.wholeCompiler.goals.find((g:any)=>g.goalId===p.goalId),before.wholeCompiler.goals.find((g:any)=>g.goalId===p.goalId));assert.equal(pg.allCurrentOriginalWholeP.length,336);
const source=(d:any)=>{const z=structuredClone(d);delete z.rawAtomicGoals;for(const j of z.jurisdictions){delete j.visibleGoals;delete j.visibleClusterGoals;}return z;};assert.deepEqual(source(before.wholeSource),source(after.wholeSource));assert.equal(after.wholeSource.rawAtomicGoals-before.wholeSource.rawAtomicGoals,13);assert.equal(after.wholeCompiler.summary.goals,568);assert.equal(after.wholeCompiler.summary.errors,0);assert.equal(after.wholeCompiler.summary.warnings,0);
const metrics=(d:any)=>d.wholeRoute.rules.find((q:any)=>q.id==='CQR-104').metrics;for(const r of [before,after]){const q=metrics(r);assert.equal(q.visibleProjectedRouteTargetGoalOccurrences,6974);assert.equal(q.visibleProjectedRouteTargetGoalOccurrencesExcludedByProfileSelector,0);assert.equal(q.projectionScopesWithInvalidStageStructure,0);assert.equal(q.wholeMaterialCoveredGoalOccurrencesWithoutVisiblePrerequisitePath,0);assert.equal(q.wholeMaterialPrerequisiteOccurrencesMissingFromProjection,0);}
const bindings=after.actualMaterials.flatMap((m:any)=>m.actual64Scopes.map((s:any)=>{const eligible=s.countryCompatible&&s.courseCompatible&&!s.missingPrerequisites.length;assert.equal(s.materialCurrentlyVisible,eligible,JSON.stringify({id:m.id,eligible,...s}));return{materialId:m.id,wholeClosure:m.wholeClosure,...s,eligible};}));assert.equal(bindings.filter((s:any)=>s.eligible).length,376);assert.equal(bindings.filter((s:any)=>s.eligible&&!s.wholeCoveredTargetsPresent).length,18);assert.equal(bindings.filter((s:any)=>s.countryCompatible&&s.courseCompatible&&s.missingPrerequisites.length).length,28);
const drop=(v:any,id:string,role:string)=>{let n=0;const f=(o:any)=>{if(!o||typeof o!=='object')return;for(const k of Object.keys(o)){if(Array.isArray(o[k])){o[k]=o[k].filter((q:any)=>{if(q?.kind==='goalEntry'&&q.goalId===id&&q.projectionRole===role){n++;return false;}return true;});for(const z of o[k])f(z);}else f(o[k]);}};f(v);assert.equal(n,1);return v;};let negRef:any,negSupport:any;
try{const be=ix.views.find((v:any)=>v.activePath.endsWith('de-be-gym-economics-gk.view.json')),bep=join(CAP,be.activePath);writeFileSync(bep,JSON.stringify(drop(read(bep),'64fac140-ab4a-5994-97fe-cb3fef3f78bd','target'),null,2)+'\n');negRef=run('negative-one-real-BE-GK-whole-EU-institution-practice-reference-drop');assert.ok(metrics(negRef).visibleSelectedGoalOccurrencesMissingDirectTerminalRoute>metrics(after).visibleSelectedGoalOccurrencesMissingDirectTerminalRoute);assert.deepEqual(after.wholeSource,negRef.wholeSource);copyFileSync(be.afterPath,bep);
writeFileSync(bep,JSON.stringify(drop(read(bep),'79edbe3a-7557-5b3b-a0f2-c31f45b6dad7','prerequisiteOnly'),null,2)+'\n');negSupport=run('negative-one-real-BE-GK-existing-EU-competence-POnly-support-drop-whole-practices-remain-visible');assert.ok(metrics(negSupport).wholeMaterialCoveredGoalOccurrencesWithoutVisiblePrerequisitePath>0);assert.ok(metrics(negSupport).wholeMaterialPrerequisiteOccurrencesMissingFromProjection>0);assert.deepEqual(after.wholeSource,negSupport.wholeSource);
}finally{positive();}
const oldCompiled=after.wholeCompiler.goals.filter((g:any)=>!ids.includes(g.goalId)&&JSON.stringify(g)!==JSON.stringify(before.wholeCompiler.goals.find((b:any)=>b.goalId===g.goalId))).map((g:any)=>({goalId:g.goalId,wholeBefore:before.wholeCompiler.goals.find((b:any)=>b.goalId===g.goalId),wholeAfter:g}));save('actual-final-social13-209-accesses376-whole-bindings18-existing-POnly28-held-source64-role-and-genuine-negatives.author-guards.json',{role:'AUTHOR_NATIVE_CANDIDATE_CHECKS_NOT_FOREIGN_SCOPE_KEEP',beforeCompiler:before.wholeCompiler.summary,afterCompiler:after.wholeCompiler.summary,whole64OldAtomicSetsExactExceptOnly13NewPracticeTargets:true,all64OrdinaryTargetSupportPOnlyMemoryOrientationExactlyUnchanged:true,current336CompiledOrdinaryWholeExact:true,source16_2134WholeAtomicIncludingPartialDiagnosticsExact:true,only13NewPracticeRawCountDelta:13,actualOldDerivedCompilerRowChanges:oldCompiled,actual376CompatibleWholeBindings:bindings.filter((s:any)=>s.eligible),actual18WholeAssessmentTargetsAboveExistingPOnly:bindings.filter((s:any)=>s.eligible&&!s.wholeCoveredTargetsPresent),actual28HeldCountryCourseClosureIncompatibleBindings:bindings.filter((s:any)=>s.countryCompatible&&s.courseCompatible&&s.missingPrerequisites.length),metrics:[before,after,negRef,negSupport].map(metrics),actual209ReferencesIn34WholeChangedViews:true,onlyOldApplicabilityMetadataChangeActualQ1Childunion:true,activeWrites:0,strictNewClosures:0,strictRestoredBindings:0,strictNet:0,humanApproval:false,privatePositiveActuallyRestored:true});console.log(JSON.stringify({role:'AUTHOR_ONLY',compiler:after.wholeCompiler.summary,actualRefs:209,wholeBindings:376,POnlyBindings:18,held:28,local:[before,after,negRef,negSupport].map(r=>metrics(r).visibleSelectedGoalOccurrencesMissingDirectTerminalRoute),unique:[before,after,negRef,negSupport].map(r=>metrics(r).uniqueVisibleSelectedGoalsMissingDirectTerminalRoute),supportNegative:metrics(negSupport).wholeMaterialPrerequisiteOccurrencesMissingFromProjection}));
