# SPDX-License-Identifier: Apache-2.0
import pathlib,json,hashlib,shutil,datetime,subprocess,importlib.util,jsonschema,re
from referencing import Registry,Resource
R=pathlib.Path('/home/enpasos/projects/skillpilot');B=pathlib.Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10');P=B/'chemie-b008-current-P25-protected12-source24-inactive-integration-technical-20261010-v1';T=B/'chemie-b008-manganometry-current-EN-SN-targeted-memory-review-20261010-v1';W=R/'tmp/m7-resumption-20261010/chemistry-current-P25-protected12-source24-inactive-integration';CA=B/'chemie-b008-current-whole-P26-native-continuation-author-20261010-v1';CD=B/'chemie-b008-current-P26-plus-protected12-dual-resolution-technical-20261010-v1';DS=B/'chemie-b008-source24-dual-bounded-scope-technical-20261010-v1'
def read(p):return json.loads((R/p).read_text())
def ref(p):b=(R/p).read_bytes();return {'path':str(p),'sha256':'sha256:'+hashlib.sha256(b).hexdigest(),'bytes':len(b)}
def put(p,x):
 f=R/p;f.parent.mkdir(parents=True,exist_ok=True);s=f.with_name(f.name+'.writing-tmp');s.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');s.replace(f)
def text(p,t):
 f=R/p;f.parent.mkdir(parents=True,exist_ok=True);s=f.with_name(f.name+'.writing-tmp');s.write_text(t);s.replace(f)
# Preserve whole actual original FIRST; this is a concrete didactic scope addendum.
put(T/'actual-protocol-stoichiometry-and-open-SN-scope.followup.json',{'schemaVersion':1,'role':'Own bounded Memory meaning application, not D/P/native or primary-source approval','actualWholeCurrentGoal':ref(T/'input/whole-current511-after.goal.json'),'unchangedActualFIRST':ref(T/'Memory-FIRST.actual.bounded-decision.json'),'givenProtocolReasoning':'With the acidic Fe(II) protocol and the balanced redox equation supplied, n(Fe2+)=5*n(MnO4-). A 10.00mL consumption of 0.0200mol/L permanganate gives 0.00100mol Fe(II); a 20.00mL aliquot gives 0.0500mol/L. A persistent faint permanganate colour is an endpoint interpretation under the supplied protocol, not memorized proof of correct experiment. Blank correction, dilution and the specified reaction must be justified from the given conditions.','actualCalculatedExample':{'molesPermanganate':0.0200*0.01000,'molesFeII':5*0.0200*0.01000,'concentrationFeII':5*0.0200*0.01000/0.02000},'givenMaterialNotNewPProfile':True,'existingRedoxPrerequisitesUnchanged':read(T/'input/whole-current511-after.goal.json')['requires'],'whyNoAdditionalRecallGoal':'Stoichiometric use of the given protocol, endpoint and measurement interpretation are situated reasoning and practical evidence. Existing prerequisite Memory/card decisions remain intact; a dedicated recalled manganometry recipe would not replace the required execution and analysis.','actualNormalSNVisibility':ref(T/'SN-current-source-supported-scope.after-complete-inputs.actual-normal-composition.json'),'SNPublishedViewsContainingGoal':0,'scopeAdoptionStillOpen':True,'humanApproval':False,'strictGain':0,'activeWrites':[]})
put(T/'neutral-current-2fdd-bounded-Memory-review.entry.json',{'schemaVersion':1,'role':'Completed current bounded Memory follow-up to a stale historical row; no entire goal or scope approval','goalIds':['2fdd759f-8349-5f7e-b29a-6ac7fb0299f9'],'wholeNeutralBeforeAfterInput':ref(T/'neutral-2fdd-current-EN-SN-and-open-gates.input.json'),'actualOwnFIRST':ref(T/'Memory-FIRST.actual.bounded-decision.json'),'preRecordsFIRSTFreeze':ref(T/'Memory-FIRST.pre-records.freeze.json'),'concreteMeaningAndProtocolFollowup':ref(T/'actual-protocol-stoichiometry-and-open-SN-scope.followup.json'),'ordinaryCurrentReview':ref(T/'current-one.normal.review.jsonl'),'ordinaryScopedConfig':ref(T/'current-one.normal.config.json'),'oldRowImmutableHistory':ref(T/'input/old-stale-Memory-row.exact.jsonl'),'actualNormalExportAndCheck':[ref(P/'checks/normal-2fdd-actual-Memory-fingerprint-export.terminal.actual.json'),ref(P/'checks/normal-2fdd-actual-current-Memory-check.terminal.actual.json'),ref(P/'checks/normal-whole398-Memory-with-actual-2fdd-successor-check.terminal.actual.json')],'humanApproval':False,'actualLearnerPerformance':False,'currentD_P_A_native_scopeStillOpen':True,'activeWrites':[],'strictGain':0})
text(T/'README.md','# Actual current manganometry Memory follow-up\n\nWhole DE/EN, actual SN physical page49, all eight whole existing decks and seven required Memory views were read. Own bounded FIRST was sealed before ordinary current fingerprint export. The no-memory decision is based on experiment/stoichiometric/endpoint reasoning with given conditions and existing prerequisite Memory, not a mechanical hash update.\n\nThe English sentence restores the already complete German operators. The explicit SN jurisdiction is not currently published in any SN source-supported view. D/P/A/native/source-scope follow-up remains open; no strict or human approval is claimed. The stale May17 row and FIRST bytes remain historical.\n')
# Technical actual contexts preserve all scientific page fields; the old scoped
# author model did not contain111 already-existing active P profiles.
model=read(P/'checks/actual398-whole-P-normal-page-context-after-formal-P25-V-adoption.json');rows=model['changedPages'];added=[x['goalId'] for x in rows if x['oldEvidenceReview'] is None and x['currentEvidenceReview'] is not None];removed=[x['goalId'] for x in rows if x['oldEvidenceReview'] is not None and x['currentEvidenceReview'] is None];assert len(added)==111 and removed==['e5a5dcd8-053c-55fd-b5c7-bba93779da53'];assert all(x['changedTopLevelFields']==['evidenceReview','pageFingerprint'] for x in rows)
exact=read(P/'checks/actual205-inactive-exact-protected180-and-new25-ID-sets.json');new25=set(exact['newCandidateStrictIds']);p12={x['goalId'] for x in read(CD/'protected-12/resolution-index.json')['resolutions']};assert not (new25|p12)&set(x['goalId'] for x in rows)
put(P/'checks/actual-current37-reviewed-pages-retained-and-e5a5-P-hold.json',{'schemaVersion':1,'actualNormalModel':ref(P/'native/current398-whole-all205-P-normal-model.actual.json'),'whole398GoalFingerprintsExact':True,'wholeCurrent25CandidateAnd12ProtectedPageContextsExact':sorted(new25|p12),'addedExistingOldPMetadataGoalIds':added,'addedExistingOldPMetadataBodiesOrFingerprintsRevised':False,'reasonAddedMetadata':'The previous scoped author model loaded95 P profiles; the actual current whole205 model loads the111 previously reviewed additional old profiles and excludes only the held e5a5. These are existing original operative records, not new scientific approvals.','onlyOmittedPMetadataGoalIds':removed,'e5a5ActualCurrentDescriptionKEEPUnchanged':True,'e5a5NotStrictAndSourceCourseUnspecified':True,'actualCurrent111ExistingProfileMetadataAdditionIsNotScienceChange':True,'activeWrites':[],'newScientificReviewClaims':0})
routes=read(P/'checks/actual-normal-current511-scoped-route-rules-and-graph.json');rule=routes['reports'][0]['rules'][0];assert rule['id']=='CQR-101' and rule['status']=='fail';ids=[]
for item in rule['details']:
 m=re.search(r'\[([0-9a-f-]{36})\]',item)
 if m:ids.append({'goalId':m.group(1),'reason':item})
put(P/'checks/exact-current-route-integration-HOLD-and-required-followup.json',{'schemaVersion':1,'role':'Concrete genuine ordinary route coverage integration blocker; central candidates not activated','actualNormalReport':ref(P/'checks/actual-normal-current511-scoped-route-rules-and-graph.json'),'actualCQR101':'fail','metrics':rule['metrics'],'wholeCurrentGoalBodiesForAllAffectedIDs':[{'finding':x,'wholeGoal':next(g for g in read(P/'candidate/whole511-398.inactive.json')['goals'] if g['id']==x['goalId'])} for x in ids],'CQR202':'pass','CQR203':'pass','graph':'pass','typeConsistency':'pass','fullMaturityM6FloorClaim':False,'requiredBeforeActiveAdoption':'Actual bounded motivation/practice route preparation and independent current task/context checks where needed, then ordinary full status and nine protected floors. No blanket fake requires or checker/quality weakening.','activeWrites':[],'strictGain':0})
# Keep all failed technical attempts and incomplete-input models as history.
put(P/'checks/actual-error-and-model-selection-history.json',{'schemaVersion':1,'historicalFailedOrIncompleteResults':[ref(P/'checks/normal-whole-current-chemie-QA-generation.terminal.actual.json'),ref(P/'checks/normal-chemie-inactive-central-five-gate.terminal.actual.json'),ref(P/'checks/normal-chemie-inactive-central-five-gate-complete-inputs-attempt2.terminal.actual.json'),ref(P/'checks/normal-chemie-inactive-central-five-gate-actual-Memory-successor-attempt3.terminal.actual.json')],'firstScopedModel':ref(P/'native/current398-P25-protected12-normal-model.actual.json'),'operativeWholeModel':ref(P/'native/current398-whole-all205-P-normal-model.actual.json'),'firstScopedModelIsHistoricalNotCurrentWholeAuthority':True,'actualInitialRouteAttemptError':'Missing unchanged Bio M394 config required by normal all-subject Memory discovery; copied exactly two small unchanged config/record files (267604bytes); no foreign subject images or new scientific reviews.','actualInitialLedgerPreparationMistake':'Technical predicate expected decision keep; real ordinary enum is keep_current. Current unchanged normal D26 records are all keep_current. No decision altered.','actualInitialProtectedSetLookupMistake':'Summary authority had counts/gains but no whole strict set; actual linked hashed terminal central JSON was read and its complete180 strict set used.','normalRulesChanged':False,'activeWrites':[]})
for f in W.iterdir():
 if f.suffix in ['.py','.mts']:shutil.copyfile(f,R/P/'technical'/f.name)
selected=[P/'candidate/whole511-398.inactive.json',P/'candidate/current511-semantic-kinds.future-active.json',P/'candidate/current-QA.after-normal-generation.future-active.json',P/'registry/chemie-subject.future-active.inactive.json',P/'registry/in-flight-ledger.with-current-B008-resolution.inactive.json',P/'memory/current398-with-actual-2fdd-Memory-successor.future-active.config.json',P/'memory/current398-with-actual-2fdd-Memory-successor.review.jsonl',P/'positive/current-P19-exact.future-active.config.json',P/'positive/current-P6-from-original-P7.future-active.config.json',P/'source-atlas/bounded378-normal-isolated.inputs.json',P/'source-atlas/generated-actual/source-manifest.json',P/'native/current398-whole-all205-P-normal-model.config.json',P/'native/current398-whole-all205-P-normal-model.actual.json',P/'checks/actual205-inactive-exact-protected180-and-new25-ID-sets.json',P/'checks/current-V-exact-before-after-normal-predicate-and-complete-files.actual.json',P/'checks/actual-current37-reviewed-pages-retained-and-e5a5-P-hold.json',P/'checks/exact-current-route-integration-HOLD-and-required-followup.json',CA/'neutral-whole26-current-material-P-and-native20-plus6.independent-review.entry.json',CA/'author.final.freeze.json',CD/'completed-current-P26-plus-protected12-dual-technical.entry.json',CD/'FINAL.technical.freeze.json',DS/'completed-source24-paired-bounded-technical.entry.json',DS/'FINAL.paired-bounded-source24.technical.freeze.json',DS/'candidate/BY-whole-retained-with-current-paired-partial-source-review.inactive.review.json',DS/'candidate/ST-whole-retained-with-current-paired-partial-source-review.inactive.review.json',T/'neutral-current-2fdd-bounded-Memory-review.entry.json']
put(P/'neutral-current-P25-protected12-source24-inactive-integration.entry.json',{'schemaVersion':1,'role':'Concrete inactive normal integration candidate with actual205/398 central intersection, explicit genuine route HOLD','createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'operativeExactInputs':[ref(x) for x in selected],'current398CurricularDenominatorUnreduced':True,'actualInactiveStrictIntersection':205,'actualInactiveStrictProtected180Lost':0,'actualInactiveCandidateGain':25,'actualActiveGain':0,'actualGates':exact['actualGates'],'sourceSupportedUnion':378,'sourceUnionFormula':'362 previous source-supported atoms minus7 retained family areas plus23 scoped new children; whole398 retains19 previous omissions plus held e5a5/C11','remainingSourceScopeDecisions':496,'allWholeSourceDutiesPartnerRowsPartialRightsBoundariesPreserved':True,'e5a5':{'descriptionActualKEEP':True,'originalP7HistoryExact':True,'newOrdinaryP6SubsetExcludesOnlyHeldE5a5':True,'currentCourse':'unspecified','strict':False},'unchangedCurrentReviewObjects':{'genuineD26Pair':'Exact current original20+6 KEEP; no fabricated D deferral','protected12':'Exact genuine targeted current dual resolutions and current P12','AM26':'Exact genuine25 current plus one prior unchanged literal row','V26':'Technical adoption of actual existing independent current raster KEEP only, imagebytes unchanged'},'registryAdoptionContract':'Merge only prepared subject=chemie into latest live central registry. Four other subject objects/beforeRegistry are historical preflight copies, not future overwrite authority; preserve newer Bio335 if integrated.','inFlight':'Remove exactly old B008 nine-goal active config; retain all other six exact configs/history; seven family areas and two genuine current KEEP replaced by real current D26. No held course-P goal relabeled as D defer.','remainingIntegrationHOLD':'CQR-101 actual fail:13 missing motivation paths and9 missing terminal paths. No active adoption, protected M6 floor or publication readiness until actual bounded route follow-up/appropriate independent reviews and full normal status/floors.','normalNationalPDFRendered':False,'wholeCurrent398NormalReviewModelBuilt':True,'actualAll37ReviewedRelevantWholePagesExact':True,'actual111OldProfileMetadataLoadedFromExistingOperativeRows':True,'actualSN2fddSourceSupportedViews':0,'humanApproval':False,'humanTrial':False,'actualLearnerPerformance':False,'activeWrites':[],'newIndependentScientificReviewsClaimed':0})
text(P/'README.md','# Inactive Chemie P25 / protected12 / Source24 integration candidate\n\nThe actual normal isolated central check passes with205/398, all180 current strict IDs preserved, D206/P205/A225/M398/V379 and zero blocking issues. These are inactive candidate results; no active progress is claimed. Whole511/398, all original duties/partners, original D26 KEEP and source378/398 with19 old omissions + held e5a5/C11 +496 unresolved rows remain explicit. P6 is a literal ordinary selection from originalP7, not a fabricated defer or reviewId change.\n\nA genuine normal route evaluation still fails CQR-101 (13 missing motivation and9 missing terminal paths). The package is not ready for active adoption/M6 claims. CQR202/203, graph and types pass. Future bounded real route work is required.\n\nMerge only the Chemie subject into the latest central registry after all actual integration gates. Other subject/preflight registry copies must never overwrite newer Bio progress. Existing historical reviews/seals and failed technical attempt receipts remain intact. All runtime/active paths were bound solely inside the ignored selective normal capsule.\n')
# Standard validators and closed schemas; no per-file validator exception.
spec=importlib.util.spec_from_file_location('normal_validate',R/'scripts/validate_schemas.py');normal=importlib.util.module_from_spec(spec);spec.loader.exec_module(normal);runtime=read('docs/landscape-runtime.schema.json');registry=Registry();schemas={}
for folder in ['contracts','docs']:
 for f in (R/folder).rglob('*.schema.json'):
  s=json.loads(f.read_text());sid=s.get('$id')
  if sid:schemas[sid]=s;registry=registry.with_resource(sid,Resource.from_contents(s))
external={}
def collect(x):
 if isinstance(x,dict):
  if {'path','sha256','bytes'}<=x.keys():
   p=pathlib.Path(x['path']);assert not p.is_absolute() and '..' not in p.parts and not str(p).startswith('tmp/'),p
   a=ref(p);assert a['sha256'].removeprefix('sha256:')==x['sha256'].removeprefix('sha256:') and a['bytes']==x['bytes'],p
   if not str(p).startswith(str(P)+'/') and not str(p).startswith(str(T)+'/'):external[str(p)]=a
  for v in x.values():collect(v)
 elif isinstance(x,list):
  for v in x:collect(v)
counts={}
for pkg in [T,P]:
 count={'normalJSON':0,'JSONLRows':0,'closedSchemaObjects':0};own=[f for f in (R/pkg).rglob('*') if f.is_file()]
 for f in own:
  if f.suffix=='.json':
   assert normal.validate_file(str(f),runtime),f;x=json.loads(f.read_text());count['normalJSON']+=1;collect(x);sid=x.get('$schema') if isinstance(x,dict) else None
   if sid in schemas:jsonschema.validators.validator_for(schemas[sid])(schemas[sid],registry=registry).validate(x);count['closedSchemaObjects']+=1
  elif f.suffix=='.jsonl':
   for line in f.read_text().splitlines():
    if not line.strip():continue
    x=json.loads(line);count['JSONLRows']+=1;sid=x.get('$schema');collect(x)
    if sid in schemas:jsonschema.validators.validator_for(schemas[sid])(schemas[sid],registry=registry).validate(x);count['closedSchemaObjects']+=1
 assert not any(f.is_symlink() for f in own)
 ignored=subprocess.run(['git','check-ignore','--stdin'],cwd=R,input='\n'.join(str(f.relative_to(R)) for f in own)+'\n',capture_output=True,text=True);assert ignored.returncode==1,ignored.stdout
 counts[str(pkg)]=count
jsonschema.validate(read(P/'candidate/whole511-398.inactive.json'),runtime);ms=read('contracts/goal-book/v1/goal-book-model-1.1.schema.json');jsonschema.validators.validator_for(ms)(ms,registry=registry).validate(read(P/'native/current398-whole-all205-P-normal-model.actual.json'))
symlinks=normal.curriculum_symlink_errors(R);assert not symlinks,symlinks
put(P/'checks/actual-normal-scoped-schemas-and-portable-input-bindings.json',{'schemaVersion':1,'checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'packages':counts,'explicitFullRuntimeLandscapeCount':1,'explicitWhole398NormalBookModelCount':1,'normalCurriculumSymlinkErrors':symlinks,'ownSymlinks':0,'ignoredOwnInputs':[],'requiredExternalBytesVerified':len(external),'incompleteJSONFiles':0,'rulesChanged':False,'activeWrites':[]})
for pkg,name,role in [(T,'FINAL.current-targeted-Memory.freeze.json','Actual bounded ordinary current Memory follow-up; whole D/P/source still open'),(P,'FINAL.inactive-normal-P25-protected12-source24-route-HOLD.technical.freeze.json','Inactive actual checked candidate with explicit genuine CQR101 integration HOLD')]:
 put(pkg/name,{'schemaVersion':1,'role':role,'sealedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'ownFiles':[ref(f.relative_to(R)) for f in sorted((R/pkg).rglob('*')) if f.is_file()],'requiredExternalFiles':list(external.values()),'humanApproval':False,'strictGain':0,'activeWrites':[]})
 for x in read(pkg/name)['ownFiles']+read(pkg/name)['requiredExternalFiles']:assert ref(x['path'])==x,x['path']
 print(json.dumps({'package':str(pkg),'freeze':ref(pkg/name),'files':len(read(pkg/name)['ownFiles']),'counts':counts[str(pkg)]}),flush=True)
