// SPDX-License-Identifier: Apache-2.0
import fs from 'node:fs'; import path from 'node:path'; import assert from 'node:assert/strict';
import {loadGoalBookBuildInputs,stableGoalBookJson} from '../chemistry-b008-P26-native-author/isolated-normal-capsule/app/scripts/goalBookModel.ts';
import {loadGoalDescriptionRolloutInFlightLedger} from '../chemistry-b008-P26-native-author/isolated-normal-capsule/app/scripts/materializeGoalDescriptionRolloutBatch.ts';
const R='/home/enpasos/projects/skillpilot',P='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/chemie-b008-current-P25-protected12-source24-inactive-integration-technical-20261010-v1',C=path.join(R,'tmp/m7-resumption-20261010/chemistry-b008-P26-native-author/isolated-normal-capsule');const read=(p:string)=>JSON.parse(fs.readFileSync(path.join(R,p),'utf8'));const put=(p:string,x:any)=>{const f=path.join(R,P,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f+'.writing-tmp',JSON.stringify(x,null,2)+'\n');fs.renameSync(f+'.writing-tmp',f)};
const loaded=await loadGoalDescriptionRolloutInFlightLedger(P+'/registry/in-flight-ledger.with-current-B008-resolution.inactive.json');assert.equal(loaded.activeBatches.length,6);put('checks/normal-in-flight-six-unchanged-active-batches.actual.json',{schemaVersion:1,normalAPI:'loadGoalDescriptionRolloutInFlightLedger',valid:true,activeConfigPaths:loaded.ledger.activeBatchConfigPaths,activeWholeGoalIds:loaded.activeBatches.map(x=>({path:path.relative(C,x.configPath),wholeGoalIds:x.config.goalIds})),activeWrites:[]});
const f=await loadGoalBookBuildInputs(P+'/native/current398-whole-all205-P-normal-model.config.json',C);assert.equal(f.model.pages.length,398);put('native/current398-whole-all205-P-normal-model.actual.json',f.model);
const old=read('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/chemie-b008-protected-twelve-current-native-technical-author-20261010-v1/native/after-whole-with-current-protected-P-model.actual.json');const om=new Map(old.pages.map((p:any)=>[p.goalId,p]));const changes=f.model.pages.map((p:any)=>{const o:any=om.get(p.goalId);assert.ok(o);assert.equal(p.goalFingerprint,o.goalFingerprint);const fields=Object.keys({...o,...p}).filter(k=>stableGoalBookJson(o[k])!==stableGoalBookJson(p[k]));return{goalId:p.goalId,changedTopLevelFields:fields,oldPageFingerprint:o.pageFingerprint,currentPageFingerprint:p.pageFingerprint,oldVisualization:o.visualization,currentVisualization:p.visualization,oldEvidenceReview:o.evidenceReview,currentEvidenceReview:p.evidenceReview}}).filter(x=>x.changedTopLevelFields.length>0);
put('checks/actual398-whole-P-normal-page-context-after-formal-P25-V-adoption.json',{schemaVersion:1,normalAPI:'loadGoalBookBuildInputs',all398WholeGoalFingerprintsExact:true,oldModelDigest:old.digest,currentModelDigest:f.model.digest,exactUnchangedPageCount:398-changes.length,changedPages:changes,role:'Actual formal QA/P selection metadata comparison; neither technical hash reconciliation nor new science review',activeWrites:[]});console.log(JSON.stringify({normalSixInFlightBatches:6,actualWholePages398:f.model.pages.length,unchanged398WholeGoalFingerprints:true,changedPages:changes.map(x=>({id:x.goalId,fields:x.changedTopLevelFields}))}));
