# SPDX-License-Identifier: Apache-2.0
from pathlib import Path
import json,copy,hashlib
Q=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10');N=Q/'chemie-b008-current517-seven-BY-source-two-direct-routes-author-20261010-v1';I=Q/'chemie-b008-current517-dual38-P38-reviewed-inactive-integration-technical-20261010-v1';S=Q/'chemie-b008-source24-dual-bounded-scope-technical-20261010-v1';old=json.load(open(S/'candidate/BY-whole-retained-with-current-paired-partial-source-review.inactive.review.json'));new=copy.deepcopy(old);culprits=json.load(open(I/'checks/concrete-seven-source-view-culprits-and-twenty-uncertain-source-scopes.actual.json'))['candidate']['missing'];lower='6c7ce93c-7675-51da-bc0c-7d0257f7ff7d';upper='86d34f1f-692d-5522-a9a4-a71c65b24de7';raw=json.load(open('curricula/DE/Gymnasium/input/BY/gymnasium/Chemie.json'));rg={g['id']:g for g in raw['goals']};whole=json.load(open(N/'candidate/whole517.two-direct-orientation-routes.author-candidate.json'));gm={g['id']:g for g in whole['goals']}
notes={
'C8.1.6':('Modelleigenschaften beschreiben; Materie-Teilchen/Reaktionen modellgestützt veranschaulichen und erklären','Der Sek-I-Leaf verlangt geeignete Modelle zu Materie und Reaktionen auszuwählen und tatsächlich zu nutzen. Vergleich mit Beobachtungen und Grenzenprüfung operationalisieren Modelleigenschaften. Eine Quelle mit allgemeiner Modellnutzung verlangt keine analoge UND digitale Doppelpflicht.'),
'C8.1.7':('Eignung vergleichen; Eigenschaften, Aussagekraft, Grenzen erkennen; Hinterfragen/Weiterentwicklung begründen','Modellaussagen untereinander und mit Beobachtungen vergleichen, Grenzen benennen und Hinterfragen oder Weiterentwicklung begründen erhält sämtliche Operatoren. Bloße Dalton-Nennung oder eine schlichte Bildbetrachtung wäre unzureichend.'),
'C9-HG_SG_MUG_WWG_SWG.1.7':('Aussagekraft von Materiemodellen anhand stofflicher Wirklichkeit beurteilen','Beobachtungsvergleich und begründete Grenzenprüfung stehen ausdrücklich im Sek-I-Leaf. Die stoffliche Wirklichkeit bleibt empirischer Maßstab; Illustration und experimenteller Befund werden nicht gleichgesetzt.'),
'C9-NTG.1.6':('Modelleigenschaften beschreiben; Materie, Reaktionen, Bindungen, Wechselwirkungen modellgestützt erklären; Aussagekraft/Grenzen/Weiterentwicklung prüfen','Alle vier Gegenstandsgruppen sowie tatsächliche Modellnutzung, Modellaussagen, Grenzen und Weiterentwicklungsgrund sind im Sek-I-Leaf enthalten. Die NTG-Pflicht zu Bindungen und Wechselwirkungen wird nicht durch ein ausschließliches Wasserbild oder einen oberen Rezeptor-Fall ersetzt.'),
'C9-NTG.2.4':('Alternative Modelldarstellungen zum Feinbau der Atome vergleichen/bewerten; Modellgrenzen beschreiben','Modellvergleich und begründetes Grenzenurteil liegen im Sek-I-Modell-Leaf. Der fachliche Feinbau-Kontext bleibt aus C9-NTG.2 vollständig erhalten und wird zusammen mit den vorhandenen Atomstrukturzielen 72236f2c (Kern-Hülle/experimenteller Befund) und f5efab9d (Energiestufen/Ionisierungsenergie) betrachtet. Inhaltsziele allein ersetzen den Vergleichs-/Grenzenoperator nicht. Der Prozessleaf ist kein neues Abhaken sämtlicher Atommodelldetails.'),
'C10-HG_SG_MUG_WWG_SWG.1.6':('Modelleigenschaften beschreiben; Stoffeigenschaften und Reaktionsverhalten von Teilchen modellgestützt erklären','Sek-I-Modellnutzung zu Materie, Reaktionen, Bindungen und Wechselwirkungen wird mit empirischem Vergleich verbunden. C10.1 nennt in seinem Originalkontext materielle/ideelle Modelle, Ladungsdarstellungen und Molekülmodellierungssoftware; passende analoge ODER digitale Wahl bleibt möglich, ohne beide Verfahren zusätzlich zu fordern.'),
'C12-GA.1.13':('Möglichkeiten und Grenzen von Modellen diskutieren; allgemeiner Sek-II-Erkenntnisgewinnungsoperator E9','Der Sek-II-Leaf verlangt begründete Aussagekraft, Grenzen und Weiterentwicklungen anhand von Beobachtungen oder Vergleichen. Das erhält das Diskutieren statt bloßer Modellbenennung. Die vier identischen GA/EA-Fundstellen sind ausdrücklich SekII/GK_LK beziehungsweise LK belegt. Diese Quelle erschöpft nicht sämtliche komplexen Kontextfamilien des ganzen Leafs; C11 erhält daraus keinerlei Kurszuordnung.')}
rows=[];added=0;promoted=0
for c in culprits:
 sid=c['sourceGoalId'];g=c['sourceRecord'];target=upper if g['sourceSpan']=='C12-GA.1.13'else lower;matches=[m for m in new['mappings']if m['legacyGoalId']==sid and m['canonicalGoalId']==target];assert len(matches)<=1;before=copy.deepcopy(matches[0])if matches else None
 if matches:assert matches[0]['matchType']=='partial';m=matches[0];promoted+=1
 else:m={'legacyGoalId':sid,'canonicalGoalId':target,'reviewDecisionId':sid};new['mappings'].append(m);added+=1
 m['matchType']='exact';m['authorCoverageProposal']='seven-source-obligation-to-current-leaf';op,reason=notes[g['sourceSpan']];d=next(d for d in new['decisions']if d['sourceGoalId']==sid);prior=copy.deepcopy(d)
 if target not in d['canonicalGoalIds']:d['canonicalGoalIds'].append(target)
 d['rationale']+=' Neuer gezielter SOURCE-AUTHOR-Vorschlag nach der aktuellen 277a3c20-Aufteilung: '+reason+' Vollständige Sourcepflicht im ursprünglichen Stufen-/Inhaltskontext repräsentiert; eine einzelne Quelle erschöpft nicht alle Pflichten des breiteren kanonischen Leafs. Neue unabhängige SOURCE-Doppelprüfung dieser Vollabdeckungsentscheidung bleibt erforderlich.'
 d['authorCandidateBoundary']={'role':'SOURCE_route_AUTHOR_only','createdAt':'2026-10-10','originalWholeSourceDecisionRetained':True,'originalPartnerIdsRetained':True,'newLeafSourceObligationCoverageIndependentReviewPending':True,'wholeCurrentLeafSourceApproval':False,'nationalSourceApproval':False,'wholeCourseApproval':False,'humanApproval':False}
 rows.append({'sourceGoalId':sid,'sourceRecord':g,'wholePrimarySourceGoal':rg.get(sid),'allPrimaryOccurrences':[rg.get(x['sourceGoalId'])for x in g['sourceOccurrences']],'operatorsToPreserve':op,'proposedTargetWholeGoal':gm[target],'beforeMapping':before,'afterMapping':copy.deepcopy(m),'originalDecision':prior,'authorScientificRationaleDe':reason,'coverageMeaning':'Complete source obligation represented by current leaf in retained original stage/content context; not a claim that one source exhausts all mandatory contexts of that broader canonical leaf.','contextPartners':[gm[id]for id in ['72236f2c-771e-4ab6-933a-e549ee49d15b','f5efab9d-2c61-44ea-b36a-87f873b51fd8']]if sid.startswith('3ca0')else[],'independentCurrentSourceReviewPending':True})
assert len(rows)==7 and promoted==4 and added==3
new['reviewId']='chemie-current517-seven-BY-leaf-source-obligation-author-candidate-v1';new['currentSevenSourceLeafAuthorProposal']={'role':'SOURCE/route AUTHOR candidate only','basis':str(N/'rationale/seven-source-operators-and-current-targets.author.json'),'wholeOriginalMappingPartnersRetained':True,'fourPreviouslyPartialNewFullSourceObligationProposals':4,'threeNewTargetedLeafSourceObligationProposals':3,'newIndependentReviewPending':True,'sourceExtractionChanged':False,'historicalBoundedPartialReviewsNotRecastAsFullSourceApproval':True,'nationalCoverageApproval':False,'C11CourseSourceHoldUnchanged':True,'humanApproval':False}
for p,obj in [(N/'candidate/BY-whole-original-partners-plus-seven-current-leaf-source-obligation.author-candidate.review.json',new),(N/'rationale/seven-source-operators-and-current-targets.author.json',{'schemaVersion':1,'role':'SOURCE AUTHOR substantive proposal, current independent review pending','rows':rows,'sourceExtractionChanged':False,'originalFullMappedSourceDutiesRetained':True,'originalSourcePartnersAllRetained':True,'partialToFullProposals':4,'newLeafProposals':3,'noC11ScopeDecision':True,'noTwentyAtlasHoldClearance':True,'humanApproval':False,'activeWrites':[]})]:p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
print('Individual7 source obligations: four partial→full proposals, three new leaf proposals; original partners/source bodies retained')
