// SPDX-License-Identifier: Apache-2.0
import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const R=process.cwd(),N='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/chemie-b008-current517-seven-BY-source-two-direct-routes-author-20261010-v1',I=N.replace('chemie-b008-current517-seven-BY-source-two-direct-routes-author-20261010-v1','chemie-b008-current517-dual38-P38-reviewed-inactive-integration-technical-20261010-v1'),C=path.join(R,'tmp/m7-resumption-20261010/chemistry-b008-P26-native-author/isolated-normal-capsule');
const read=(p:string)=>JSON.parse(fs.readFileSync(path.join(R,p),'utf8')),imp=async(n:string)=>import(pathToFileURL(path.join(C,'app/scripts',n)).href),put=(p:string,x:any)=>fs.writeFileSync(path.join(R,N,p),JSON.stringify(x,null,2)+'\n');
const m=await imp('generateCurriculumQualityStatus.current517-author-technical-exports.ts'),a=await imp('applicabilityCompiler.ts'),whole=read(N+'/candidate/whole517.two-direct-orientation-routes.author-candidate.json'),current=read('docs/qa-ci/status/curriculum-quality-status.json').curricula.find((x:any)=>x.subject==='Chemie'),comp=a.buildApplicabilityCompilation(),coverage=m.readJurisdictionCoverageByLandscapeId(comp).get(whole.landscapeId),source=m.evaluateJurisdictionCoverage(coverage),routes=m.routeProfiles.filter((p:any)=>p.landscapeId===whole.landscapeId).map((p:any)=>m.evaluateRouteProfile(whole,p,comp));
const old=read(I+'/checks/protected-M6-baseline-versus-current398-actual-source-route-BLOCKERS.json'),rules=current.rules.map((r:any)=>r.id==='CQR-003'?source:r),isolated=m.deriveCurriculumMaturity(rules,routes),report={schemaVersion:1,role:'SOURCE/route AUTHOR candidate machine evidence; independent science review pending',criteriaChanged:false,normalOriginalFunctions:true,baseline:old.baseline,priorSealedCandidate:old.candidate,currentAuthorCandidate:{wholeGoals:whole.goals.length,sourceRule003:source,jurisdictionCoverage:coverage,routes,derivedMaturityUsingSameProtectedOtherRules:isolated,otherProtectedRulesLiteralCurrentActive:rules.filter((r:any)=>r.id!=='CQR-003'),applicabilityReport:comp.reports.find((x:any)=>x.landscapeId===whole.landscapeId)},M6Meaning:'Same protected current-active other rules held literal solely to isolate the genuine source/route regression. This is not full independently approved current candidate readiness.',currentSourceIndependentReviewPending:true,currentRouteContextIndependentReviewPending:true,twentyAtlasHoldsCleared:false,C11CourseApproved:false,humanApproval:false,activeWrites:[]};
put('checks/CQR003-CQR102-protected-floor.original-normal.actual.json',report);
const allIds=new Set(whole.goals.map((g:any)=>g.id)),graph=m.evaluateGraphIntegrity(whole,allIds),type=m.evaluateTypeConsistency(whole);put('checks/normal-graph-and-type.actual.json',{graph,type,activeWrites:[]});
assert.equal(source.status,'pass');for(const r of routes){assert.equal(r.rules.find((x:any)=>x.id==='CQR-102').status,'pass');for(const id of ['CQR-101','CQR-202','CQR-203'])assert.equal(r.rules.find((x:any)=>x.id===id).status,'pass')}assert.equal(isolated,'M6');assert.equal(graph.status,'pass');assert.equal(type.status,'pass');
console.log(JSON.stringify({CQR003:source,CQR102:routes.map((x:any)=>x.rules.find((r:any)=>r.id==='CQR-102')),protectedOtherRulesIsolatedMaturity:isolated,graph:graph.status,type:type.status,currentScienceIndependentReviewPending:true}));
