# Apache-2.0. Verifiable inactive candidate records and freezes, never active QA.
from pathlib import Path
import datetime, hashlib, json, platform, subprocess
P=Path(__file__).resolve().parent;ROOT=P.parents[6]
read=lambda n:json.loads((P/n).read_text())
sha=lambda p:'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest()
rel=lambda p:str(p.relative_to(ROOT))
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(n,d):
 (P/n).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def candidate(n,d):
 write(n,{'status':'candidate','reviewAuthority':'ai_candidate','createdAt':now,'humanApproval':False,'activeWrites':0,**d})
source,mapping=read('ni.current-source.candidate.json'),read('ni.current-mapping.candidate.json')
sg={g['id']:g for g in source['sourceGoals']};dec={d['sourceGoalId']:d for d in mapping['decisions']}
canon={g['id']:g for g in read('canonical.biologie.candidate.json')['goals']}
assert len(sg)==len(source['sourceGoals'])==len(dec)==123
passages={p['id'] for p in source['passages']}
assert all(g['passageId'] in passages and g['sourceSpan']['passageId'] in passages for g in sg.values())
assert all(g.get('headingTitle') and g.get('sourceText') and g.get('sourceRef') and g.get('sourceSpanText') for g in sg.values())
assert {g['passageId'] for g in sg.values()}==passages
assert set(dec)==set(sg) and all(d['decision']=='mapped' for d in dec.values())
rows=mapping['mappings'];assert len(rows)==336
assert len({(r['legacyGoalId'],r['canonicalGoalId']) for r in rows})==336
for r in rows:
 assert r['legacyGoalId'] in dec and r['canonicalGoalId'] in canon
 assert r['canonicalGoalId'] in dec[r['legacyGoalId']]['canonicalGoalIds']
 assert r['reviewDecisionId']==r['legacyGoalId']
for i,d in dec.items():assert set(d['canonicalGoalIds'])=={r['canonicalGoalId'] for r in rows if r['legacyGoalId']==i}
F='ni-biology-seki-kc2015-fw6-008-d14910ea';new=read('before-after-deltas.candidate.json')['newGoalIds']
assert len(dec[F]['canonicalGoalIds'])==4 and all(r['matchType']=='partial' for r in rows if r['legacyGoalId']==F)
checks2=[('source-goals-created','123 actual structured source goals, with FW6-003 synthetic retirement preserved'),('passage-to-source-goal-coverage','18 actual passages all referenced by current source goals'),('source-goal-ids-unique','123 unique actual source IDs'),('source-goals-reference-passages','All source passage/span IDs resolve'),('source-goal-trace-complete','All123 have heading, sourceText, sourceRef and sourceSpanText'),('source-goal-count-peer-baseline-local-audit','123 actual table competencies, not124 synthetic-expanded predecessor; prior frozen actualPDF87-89 evidence preserved'),('current-selected-source-adoption-review','Five NI3 source cells and FW6-008 revised primary cell bound to actual source references; three advisory caches versioned,115 complete historical records retained')]
checks3=[('mapping-2-complete','Current source structural/selected-cell candidate checks above pass; active M2 still root-owned'),('m3-review-file-present','Exactly one prospective current NI mapping file materialized'),('m3-review-decisions-reference-source-goals','123 unique decisions reference exactly123 current source IDs'),('m3-review-targets-exist','All336 actual row targets exist in446-record candidate canonical'),('m3-all-source-goals-reviewed','123 decided groups,117 historical decisions unchanged; selected changed groups bound in candidate delta'),('m3-all-source-goals-covered-by-canonical','Scoped content candidate: preserved117 decisions plus selectedNI3 mappings and two FW6-008 partial companions jointly support chosen chromosomal principles. Neither companion alone nor123mapped count is a whole-clause proof.'),('current-selected-source-adoption-review','Five new ordinary atoms and two contains-only parents reviewed as prospective candidate units; operative adoption and actual supplied-model/Book/D2 bindings remain pending')]
candidate('source-mapping-fourteen-checks.candidate.json',{'canonicalLandscapeId':'08a43a1b-d97e-522c-9dfa-c950a493364e','sourceLandscapeId':source['sourceLandscapeId'],'checks':[{'phase':p,'id':i,'candidateVerdict':'HOLD' if p=='MAPPING-3' and i in ['m3-all-source-goals-covered-by-canonical','current-selected-source-adoption-review'] else 'PASS','finding':f+(' Five current retained NI target paths require molecular DNA competence reserved to SekII; prerequisiteOnly is not a fachliche repair. Three optional narrow deltas are separate, mutation/evolution scope remains HOLD.' if p=='MAPPING-3' and i in ['m3-all-source-goals-covered-by-canonical','current-selected-source-adoption-review'] else ''),'activeCompletionClaim':False} for p,ls in [('MAPPING-2',checks2),('MAPPING-3',checks3)] for i,f in ls],'selectedConceptCoverageVerdict':'PASS new-five author-informed source/template candidate, with actual final model bindings conditional; complete current NI source/frontier scope remains HOLD','adoptionVerdict':'HOLD until root adopts and resolves actual current model/Book binding and retained NI prerequisite scope question','sourceHumanApproval':False,'structuralCountsAloneUsedAsNormativeCoverage':False})
# Predecessor FULL A/M line bytes and cards are immutable prefix/copy evidence.
for lane in ['semantic-atomicity','memory-card-review']:
 b=(P/(lane+'.base.review.jsonl')).read_bytes();a=(P/(lane+'.candidate.review.jsonl')).read_bytes();assert a.startswith(b)
 assert len(b.decode().strip().splitlines())==363 and len(a.decode().strip().splitlines())==368
oldM=ROOT/'curricula/DE/Gymnasium/quality/memory-card-review/biologie-q1-tests-therapy-current-20261004-v1/canonical-biology-full.cards.review.jsonl'
assert oldM.read_bytes()==(P/'memory.cards.unchanged.review.jsonl').read_bytes()
candidate('native-am.terminal.receipt.json',{'toolchain':{'provider':'OpenAI tool-mediated local agent','deployedModelId':'not exposed','Python':platform.python_version(),'Node':subprocess.check_output(['node','--version'],text=True).strip(),'runner':'repository app/node_modules/.bin/tsx'},'runs':[{'lane':'A FULL candidate','exitCode':0,'log':'native-A.terminal.txt','digest':sha(P/'native-A.terminal.txt')},{'lane':'M FULL candidate unchanged registered visibility scope','exitCode':0,'log':'native-M.terminal.txt','digest':sha(P/'native-M.terminal.txt')},{'lane':'additional pure-source-book-view probe','exitCode':1,'log':'native-M-NI-probe.terminal.txt','digest':sha(P/'native-M-NI-probe.terminal.txt'),'qualification':'Same five pre-existing missing memory nodes; pure curricularAtomic book derivative is not runtime registered and is not an added learner M gate'},{'lane':'actual registered runtime GK+SekI before','exitCode':0,'log':'native-M-runtime-before.terminal.txt','digest':sha(P/'native-M-runtime-before.terminal.txt')},{'lane':'actual registered runtime GK+SekI after','exitCode':0,'log':'native-M-runtime-after.terminal.txt','digest':sha(P/'native-M-runtime-after.terminal.txt')}],'all363OldARecordBytesPreservedAsPrefix':True,'all363OldMRecordBytesPreservedAsPrefix':True,'allOldCardBytesUnchanged':True,'cardDigest':sha(oldM),'oldCardRecords':len(oldM.read_text().strip().splitlines()),'newFiveScientificIndividualReasons':'five-targeted-kind-am.rationales.candidate.json','nativeCandidateResultsAreOperativeGates':False})
impact=read('strict37-context-impact.candidate.json');assert impact['strictInputCount']==37
assert all(r['goalEvidenceFingerprintBefore']==r['goalEvidenceFingerprintAfter'] for r in impact['records'])
assert all(not r['flags']['canonicalBodyChanged'] and not r['flags']['requiresChanged'] for r in impact['records'])
removed=read('ni-four-sourceview-removals.evidence.candidate.json');assert not set(removed['removedDirectGoalIds']) & set(r['goalId'] for r in impact['records'])
candidate('strict37-floor-preservation.candidate.json',{'baselineReport':read('strict37.ids.metadata-only.json'),'retainedCanonicalIDs':37,'all37BodyAndNativeGoalEvidenceFingerprintsUnchanged':True,'all37DirectRequiresUnchanged':True,'removedNIViewGoalIntersectionWithStrict37':[],'currentSemanticFloorCandidateVerdict':'PASS structural preservation; fresh integrated BookModel/dossier/central validation remains root-owned','actualContextAffectedCount':len(impact['actualAffectedGoalIds']),'actualContextAffectedGoalIds':impact['actualAffectedGoalIds'],'unaffectedCount':len(impact['unaffectedGoalIds']),'actualStrictCurrentAfterIntegrationCountClaim':None,'allFiveNewGoalsStillCandidateNotCountedAsActiveM7':True})
delta=read('before-after-deltas.candidate.json');delta['viewPolicy']='Navigation exactly5 additions; NI source view5 additions and exactly4 native-witness-supported removals. Canonical bodies and other jurisdictions retained.';delta['NISourceViewRemovedIDs']=removed['removedDirectGoalIds'];write('before-after-deltas.candidate.json',delta)
candidate('root-integration-follow-up.exact.json',{'AConfigPathAfterAdoption':'curricula/DE/Gymnasium/quality/semantic-atomicity/biologie-ni-five-current-20261005-v1/canonical-biology-full.config.json','MConfigPathAfterAdoption':'curricula/DE/Gymnasium/quality/memory-card-review/biologie-ni-five-current-20261005-v1/canonical-biology-full.config.json','rootOwnedCentralConfigChanges':[{'subject':'biologie','field':'semanticAtomicityConfigPath','after':'curricula/DE/Gymnasium/quality/semantic-atomicity/biologie-ni-five-current-20261005-v1/canonical-biology-full.config.json'},{'subject':'biologie','field':'memoryReviewConfigPath','after':'curricula/DE/Gymnasium/quality/memory-card-review/biologie-ni-five-current-20261005-v1/canonical-biology-full.config.json'}],'rootOwnedNextSteps':['Resolve retained five old NI prerequisite paths to DNA against stage limits; prerequisiteOnly model is candidate, not source-target coverage.','Bind and actually review real new supplied-model PNGs and final goal resources; no placeholder V approval.','Adopt bounded data with byte archives outside both active scanners, verify NI one extraction + one mapping file.','Regenerate and verify source atlas/manifest/projection outputs with final current canonical and Kind inputs.','Build current review BookModel/HTML/PDF, perform required targeted D2 for new five and materially affected old five contexts; preserved bodies are not automatically failed.','Run status/central gates on integrated current artifacts. Never set source M3 merely from123 mapped decisions.'],'noPContentsReadOrNewProfileAuthored':True,'currentM6And37FloorMustBeLiveVerifiedByRoot':True})
# Bind known peer receipts and the exact adopted-UUID text snapshots before P.
freezeNames=['canonical.biologie.candidate.json','ni.current-source.candidate.json','ni.current-mapping.candidate.json','native-seven-fingerprints.receipt.json','five-targeted-kind-am.rationales.candidate.json','source-mapping-fourteen-checks.candidate.json','strict37-context-impact.candidate.json','dna-native-effective-require-paths.candidate.json','dna-five-paths.full-source-texts-and-options.candidate.json','optional-dna-prerequisite-deltas.native-check.receipt.json','native-scoped-checks.receipt.json','native-am.terminal.receipt.json']
candidate('source-description-adoption.freeze.receipt.json',{'freezeKind':'author-informed current prospective Source/D units; not independent new review','nativeBookD2Passed':False,'VPassed':False,'PContentsRead':False,'newGoalIds':new,'sourceConceptDecision':'PASS scoped current template operationalization; two FW6-008 partial components joint-cover the chosen chromosomal principles','descriptionTemplateDecision':'KEEP exact reviewed DE/EN templates, unchanged NI3 competencies','remainingHold':'Actual supplied-model/Book binding and stage treatment of preserved old NI DNA prerequisite paths','artifacts':[{'path':rel(P/n),'digest':sha(P/n)} for n in freezeNames]})
write('materialization-terminal.receipt.json',{'finishedAt':now,'status':'completed_inactive_candidate_with_named_holds','sourceDFreezeDigest':sha(P/'source-description-adoption.freeze.receipt.json'),'records':446,'curricularAtomic':368,'sourceGroups':123,'mappingEdges':336,'sourceRecordsUnchanged':115,'historicalDecisionsUnchanged':117,'runtimeMemoryVisibilityBeforeAfter':'PASS','scopedNativeKindSchemaDagViewsAM':'PASS candidate only','actualStrict37ContextAffectedCount':len(impact['actualAffectedGoalIds']),'adoptionDryRunExitCode':0,'adoptionApplyExecuted':False,'activeWrites':0,'humanApproval':False,'PContentsRead':False})
files=sorted(p for p in P.rglob('*') if p.is_file() and p.name!='frozen-receipt.json')
write('frozen-receipt.json',{'receiptId':'biologie-ni-five-current-adoption-candidate-v3-frozen','frozenAt':now,'status':'candidate','reviewAuthority':'ai_candidate','authorshipMode':'author-informed materialization after known A/B v2; no independent new review','sourceLandscapeId':source['sourceLandscapeId'],'canonicalLandscapeId':'08a43a1b-d97e-522c-9dfa-c950a493364e','activeWrites':0,'humanApproval':False,'PContentsRead':False,'artifacts':[{'path':rel(p),'digest':sha(p),'bytes':p.stat().st_size} for p in files]})
print(sha(P/'frozen-receipt.json'))
