"""Own whole bilingual candidate cases, not evidence from real learners."""
CASES=[]
def add(o,n,md,me,td,te,ad,ae):
    CASES.append({'ordinal':o,'id':f'he-evolution18-{o:02d}-case-{n}','material':{'de':md,'en':me},'task':{'de':td,'en':te},'modelAnswer':{'de':ad,'en':ae},'provenance':'Own synthetic didactic material and public model answer; not actual learner performance, experimental execution, or new historical/fossil measurement.'})

add(7,1,
'Eigenes Drei-Wege-Modell: A: Fischpopulationen werden durch eine geografische Barriere getrennt und bilden später beständige Paarungsbarrieren. B: Eine nicht getrennte Pflanzenpopulation bildet durch Chromosomenverdopplung eine fruchtbare tetraploide Gruppe mit vermindertem Genfluss zu Diploiden. C: Zwei Pflanzenarten hybridisieren; die zunächst schlecht fertile Hybride wird nach Chromosomenverdopplung fruchtbar und ist reproduktiv von beiden Elternlinien getrennt. Alle drei stabilen Linien sind Modellannahmen, keine tatsächlich durchgeführten Kreuzungen.',
'Own three-route model: A: fish populations are separated by a geographical barrier and later develop persistent mating barriers. B: an unseparated plant population produces a fertile tetraploid group through chromosome doubling, with reduced gene flow to diploids. C: two plant species hybridize; the initially poorly fertile hybrid becomes fertile after chromosome doubling and is reproductively separated from both parental lineages. All three stable lineages are model assumptions, not crosses actually performed.',
'Vergleiche allopatrische, sympatrische und hybridisierungsbezogene Mechanismen anhand vonA/B/C. Erkläre Ausgangstrennung, Genfluss und Fortpflanzungsbarriere und prüfe, ob Hybridisierung allein stets Artbildung bedeutet.',
'Compare allopatric, sympatric, and hybridization-related mechanisms throughA/B/C. Explain initial separation, gene flow, and reproductive barriers and evaluate whether hybridization alone always means speciation.',
'A beginnt geografisch getrennt und bildet anschließend reproduktive Isolation. B schafft ohne geografische Trennung eine Chromosomenbarriere und kann sympatrisch eine neue Linie etablieren. C verbindet zuvor getrennte Genome; die Verdopplung ermöglicht im Modell wieder regelmäßige Paarung homologer Chromosomen und fertile Nachkommen, zugleich aber Isolation gegenüber den Eltern. Hybridisierung kann auch bloß zeitweilige Hybriden oder Introgression erzeugen, ohne neue stabile Art. Unterschiedliche Ausgangswege werden daher nach Genfluss und dauerhaftem reproduktivem Zusammenhang verglichen, nicht allein nach Auftreten einer Hybride.',
'A starts with geographical separation and subsequently develops reproductive isolation. B creates a chromosome barrier without geographical separation and can establish a new lineage sympatrically. C combines previously distinct genomes; doubling permits regular pairing of homologous chromosomes and fertile offspring in this model while also separating the hybrid lineage from its parents. Hybridization can also yield only temporary hybrids or introgression without a stable new species. The routes must therefore be compared by gene flow and persistent reproductive cohesion, not merely the presence of a hybrid.')
add(7,2,
'Eigenes Kontaktzonenmodell: Nach allopatrischer Trennung kommen zwei Linien wieder in Kontakt; seltene fertile Hybriden übertragen einzelne Allele, beide Linien bleiben überwiegend getrennt. Vergleichsmodell ohne geografische Barriere: Paarung innerhalb zweier ökologischer Gruppen beträgt95%, zwischen ihnen5%; deren Nachkommen sind noch vollständig fruchtbar. Ein drittes Hybridmodell zeigt eine sich selbst erhaltende, gegenüber beiden Eltern reproduktiv isolierte Gruppe. Zeitangaben und Prozentwerte sind synthetisch.',
'Own contact-zone model: after allopatric separation, two lineages meet again; rare fertile hybrids transfer individual alleles, while the lineages remain mainly separate. Comparison without a geographical barrier: mating is95% within two ecological groups and5% between them; their offspring remain fully fertile. A third hybrid model shows a self-sustaining group reproductively isolated from both parents. Times and percentages are synthetic.',
'Vergleiche die Bedeutung der Hybridisierung im ersten und dritten Modell mit dem sympatrischen Trennungsprozess des zweiten. Beurteile, welche Artbildungsbehauptungen durch die Daten gestützt und welche noch offen sind.',
'Compare the significance of hybridization in the first and third models with the sympatric separation process in the second. Assess which speciation claims the data support and which remain open.',
'Im ersten Fall beschreibt der Ortswechsel eine allopatrische Vorgeschichte; seltene Hybriden ermöglichen begrenzten Genfluss, ohne die Trennung zwangsläufig vollständig aufzuheben. Im dritten kann Hybridisierung eine neue eigenständige Linie hervorbringen, sofern Dauerhaftigkeit und Isolation belegt sind. Das zweite Modell zeigt assortative Paarung und damit einen möglichen sympatrischen Prozess, aber die verbleibende vollständige Fertilität erlaubt noch keine sichere Behauptung abgeschlossener Artbildung. Prozentwerte allein entscheiden keine Artgrenze; Genfluss, Barrieren und verwendetes Artkonzept sind gemeinsam zu beurteilen.',
'The first model has an allopatric history; rare hybrids permit limited gene flow without necessarily removing separation entirely. In the third, hybridization can produce a distinct lineage if persistence and isolation are established. The second shows assortative mating and a possible sympatric process, but remaining full fertility does not establish completed speciation. Percentages alone do not decide species boundaries; gene flow, barriers, and the species concept must be assessed together.')

add(8,1,
'Eigenes Uhrenmodell für eine kurze homologe, neutral angenommene Sequenz: Die korrigierte Distanzd zwischen zwei Linien beträgt0,024Substitutionen jePosition. Aus einer unabhängigen Fossilkalibrierung wird die Rate je einzelner Linie mitr=0,0015Substitutionen jePosition undMio.Jahre angesetzt. Beide Linien folgen im vereinfachten Modell derselben konstanten Rate; die Distanz umfasst Änderungen auf beiden Ästen. Fossilkalibrierung, Neutralität und konstante Rate sind explizite Modellannahmen.',
'Own clock model for a short homologous sequence assumed neutral: corrected distance d between two lineages is0.024substitutions per site. Independent fossil calibration gives a rate per individual lineage r=0.0015substitutions per site per million years. Both lineages follow the same constant rate in the simplified model; the distance includes changes on both branches. Fossil calibration, neutrality, and rate constancy are explicit model assumptions.',
'Schätze die Abspaltungszeit und erkläre den Faktor2. Ordne die Aussagekraft ein und benenne zwei Gründe, warum das Ergebnis keine exakte historische Datierung ist.',
'Estimate the divergence time and explain the factor2. Assess the estimate and give two reasons why it is not an exact historical date.',
'Bei gleichen Einzelast-Raten gilt d=2rt, also t=0,024/(2·0,0015)=8Mio.Jahre. Der Faktor2 zählt die seit der Aufspaltung getrennt akkumulierten Änderungen beider Linien; d/r=16Mio.Jahre wäre hier eine Verwechslung der Paar- und Einzelast-Rate. Die Zahl ist eine kalibrierte Modellschätzung. Unsicherheit der Fossilzuordnung und Kalibrierzeit sowie mögliche Rateunterschiede, Selektion oder mehrfach veränderte Positionen begrenzen die Genauigkeit. Das Modell datiert keine individuelle Geburt und beweist keine bestimmte Fossilform als direkten Vorfahren.',
'With equal single-branch rates d=2rt, so t=0.024/(2×0.0015)=8million years. The factor2 counts changes accumulated separately in both lineages since divergence; d/r=16million years would confuse pairwise and single-branch rates here. The value is a calibrated model estimate. Uncertain fossil assignment and calibration dates, possible rate differences, selection, or multiple changes at a site limit accuracy. The model dates neither an individual birth nor establishes a particular fossil as a direct ancestor.')
add(8,2,
'Eigenes Vergleichsmodell: Eine fossilkalibrierte Paar-Distanz nimmt in DatensatzA mit0,004jePosition undMio.Jahre zu; die neue Paar-Distanz beträgt0,020. Für eine zweite SequenzB ist die geschätzte Einzelast-Rate0,001jePosition undMio.Jahre; deren Paar-Distanz beträgt ebenfalls0,020. Eine Überprüfung zeigt, dass SequenzB in einer Linie auffällig schnell evolviert. Die Kalibrierintervalle überlappen nur teilweise; Materialien sind synthetisch.',
'Own comparison model: a fossil-calibrated pairwise distance increases in datasetA by0.004per site per million years; the new pairwise distance is0.020. A second sequenceB has an estimated single-branch rate of0.001per site per million years and the same pairwise distance0.020. A check shows unusually rapid evolution ofB in one lineage. The calibration intervals overlap only partly; materials are synthetic.',
'Berechne die beiden bedingten Zeitschätzungen und unterscheide Paar- von Einzelast-Rate. Beurteile, wie der Ratebefund fürB die Verwendung als strikte molekulare Uhr verändert.',
'Calculate the two conditional time estimates and distinguish pairwise from single-branch rates. Assess how the rate finding forB affects its use as a strict molecular clock.',
'A verwendet bereits die Paar-Rate: t=0,020/0,004=5Mio.Jahre, ohne weiteren Faktor2. B ergibt unter gleichen Einzelast-Raten t=0,020/(2·0,001)=10Mio.Jahre. Der Befund ungleicher Raten verletzt die strikte B-Modellannahme; die10Mio.Jahre sind deshalb keine belastbare exakte Datierung. Man braucht zusätzliche Kalibrierung und ein Modell, das Rateunterschiede berücksichtigt, oder geeignete andere Sequenzen. Gleiche beobachtete Distanz bedeutet bei verschiedenen Raten nicht gleiche Abspaltungszeit. Die Werte werden nicht einfach gemittelt, um scheinbare Genauigkeit herzustellen.',
'A already uses a pairwise rate: t=0.020/0.004=5million years, without another factor2. ForB, equal single-branch rates would give t=0.020/(2×0.001)=10million years. Unequal rates violate the strictB assumption;10million years is therefore not a defensible exact date. Additional calibration and a model allowing rate differences, or suitable other sequences, are needed. Equal observed distances do not imply equal divergence times under different rates. The estimates must not simply be averaged to manufacture apparent accuracy.')

add(9,1,
'Eigenes Hominiden-Hypothesenmodell: FossilgruppeF zeigt Hinweise auf Zweibeinigkeit, aber noch relativ kleinen Hirnschädel. In späteren und teilweise überlappenden FundgruppenG/H sind andere Merkmalsmosaike dokumentiert. Werkzeugfunde liegen an einigen, nicht allen Fundorten vor; Zuordnung zu einer bestimmten Fossilgruppe ist teilweise unsicher. Hypothese1 behauptet eine einzige zwangsläufige Reihe Zweibeinigkeit→großes Gehirn→Sprache. Hypothese2 erlaubt verzweigte Entwicklung, zeitversetzte Merkmale und kulturell-biologische Rückkopplungen.',
'Own hominin-hypothesis model: fossil groupF shows evidence of bipedality but still a relatively small braincase. Later and partly overlapping groupsG/H have other trait mosaics. Tools occur at some but not all sites; assignment to a particular fossil group is partly uncertain. Hypothesis1 proposes a single inevitable sequence bipedality→large brain→language. Hypothesis2 allows branching, traits emerging at different times, and cultural-biological feedback.',
'Diskutiere beide Hypothesen differenziert anhand Fossil- und Kulturbelegen. Erkläre, welche Schlussfolgerungen begründet sind und welche zusätzliche Evidenz die unsichere Werkzeugzuordnung oder Sprachbehauptung bräuchte.',
'Discuss both hypotheses carefully using fossil and cultural evidence. Explain which conclusions are justified and what additional evidence the uncertain tool attribution or language claim would require.',
'Das Merkmalsmosaik und die Überlappung passen besser zu verzweigten, zeitversetzten Veränderungen als zu einer notwendigen linearen Reihenfolge. Zweibeinigkeit allein beweist kein großes Gehirn und keine Sprache. Werkzeugfunde belegen bearbeitete Gegenstände, aber ohne sichere Fundzusammenhänge nicht ihren Hersteller; sie erhalten auch keine gesprochenen Aussagen. Hypothese2 ist mit den Befunden vereinbar und kann Rückkopplungen zwischen Lernen, Werkzeuggebrauch und biologischen Voraussetzungen berücksichtigen, ist jedoch nicht in jedem Detail bewiesen. Verlässliche Datierungen, Fundzusammenhänge und zusätzliche anatomische/genetische oder archäologische Hinweise können konkurrierende Hypothesen gezielt eingrenzen.',
'Trait mosaics and temporal overlap better fit branching and changes at different times than an inevitable linear sequence. Bipedality alone establishes neither a large brain nor language. Tools establish worked objects but not their makers without secure archaeological associations, and they preserve no spoken statements. Hypothesis2 is compatible with the findings and can incorporate feedback among learning, tools, and biological capacities, but its details are not all established. Reliable dates, archaeological associations, and additional anatomical/genetic or archaeological evidence can constrain competing hypotheses.')
add(9,2,
'Eigenes Forschungsvergleichsmodell: ModellA deutet eine regionale Fossilähnlichkeit als alleinige lokale Abstammung aller dort heute lebenden Menschen. ModellB kombiniert afrikanische Homo-sapiens-Ursprünge, mehrere spätere Ausbreitungen und begrenzte Vermischungen. Bereitgestellte genetische Vergleiche stützen für das Modell überwiegend gemeinsame jüngere Abstammung und einzelne ältere genetische Beiträge; verbreitete Werkzeugtechniken können zusätzlich durch Lernen zwischen Gruppen weitergegeben worden sein. Daten sind didaktisch vereinfacht und bewerten keine Menschengruppe.',
'Own research-comparison model: modelA treats regional fossil similarity as proof that every present-day local person descends only from a local lineage. ModelB combines African Homo-sapiens origins, several later dispersals, and limited interbreeding. Supplied genetic comparisons mainly support shared more-recent ancestry plus some older genetic contributions; widely distributed tool techniques may additionally have spread through learning among groups. Data are simplified for teaching and do not rank human groups.',
'Diskutiere die Aussagekraft der Fossil-, genetischen und kulturellen Belege für beide Hypothesen. Erläutere Unsicherheiten und warum technische Traditionen keine direkte Karte genetischer Abstammung ergeben.',
'Discuss the evidential value of fossil, genetic, and cultural findings for both hypotheses. Explain uncertainties and why technological traditions do not directly map genetic ancestry.',
'Eine regionale Fossilähnlichkeit reicht nicht für ausschließliche lokale Kontinuität aller heutigen Menschen. Die bereitgestellten genetischen Befunde sind mit dem verzweigten B-Modell und begrenzten Kontakten vereinbar; alternative Zuordnungen bleiben nach Datierung und Stichprobe zu prüfen. Werkzeuge können mit wandernden Gruppen verbreitet oder ohne entsprechende Genwanderung sozial übernommen werden. Kulturbelege und genetische Abstammung sind daher verschiedenartige Informationen. Fossillücken, vereinfachte Modelle und begrenzte Sequenzstichproben erfordern vorläufige Schlüsse; daraus folgen keine scharfen biologischen Rangklassen heutiger Menschen.',
'Regional fossil similarity is insufficient to establish exclusive local continuity for all present-day people. The supplied genetic findings fit branching modelB and limited contacts; alternatives still require evaluation of dating and sampling. Tools may spread with migrating groups or be adopted socially without equivalent gene flow. Cultural findings and genetic ancestry therefore convey different kinds of information. Fossil gaps, simplified models, and limited sequence samples require tentative conclusions; they do not imply sharp biological hierarchies among present-day humans.')

add(10,1,
'Eigenes Selektionsmodell: Drei vererbbare Schnabelklassen klein/mittel/groß beginnen je mit100Individuen. Erfolgreiche Nachkommen pro Ausgangsindividuum betragen bei UmweltA 0,5/1,0/0,5, beiB 0,3/0,6/1,2, beiC 1,0/0,3/1,0. Gemeint ist reproduktiver Beitrag unter der jeweiligen Umwelt, nicht bloß Körperstärke. Das Modell kontrolliert gleiche Ausgangsbedingungen, schließt aber Drift und Migration für diese vereinfachte Rechnung aus.',
'Own selection model: three heritable beak classes small/medium/large each start with100individuals. Successful offspring per initial individual are0.5/1.0/0.5 in environmentA,0.3/0.6/1.2 inB, and1.0/0.3/1.0 inC. This denotes reproductive contribution in the relevant environment, not bodily strength alone. Starting conditions are controlled; drift and migration are excluded from this simplified calculation.',
'Erkläre stabilisierende, gerichtete und disruptive Selektion anhand der Tabelle. Begründe die erwarteten Änderungen der Merkmalsverteilung und grenze disruptive Selektion von automatisch abgeschlossener Artbildung ab.',
'Explain stabilizing, directional, and disruptive selection using the table. Justify expected changes in trait distributions and distinguish disruptive selection from automatically completed speciation.',
'A begünstigt die mittlere Klasse gegenüber beiden Extremen: stabilisierende Selektion kann die Streuung verringern. B begünstigt größere Schnäbel: gerichtete Selektion verschiebt die Verteilung in diese Richtung. C begünstigt beide Extreme gegenüber der Mitte: disruptive Selektion kann eine zweigipflige Verteilung fördern. Entscheidend sind vererbbare Variation und ungleicher reproduktiver Beitrag, nicht eine bewusste Anpassungsabsicht. Für Artbildung müssten zusätzlich Genfluss und reproduktive Barrieren geprüft werden; zwei begünstigte Merkmalsklassen sind noch keine zwei Arten.',
'A favors the middle class over both extremes: stabilizing selection may reduce variation. B favors larger beaks: directional selection shifts the distribution in that direction. C favors both extremes over the middle: disruptive selection may promote a bimodal distribution. Heritable variation and unequal reproductive contribution are crucial, not a deliberate intention to adapt. Speciation additionally requires examination of gene flow and reproductive barriers; two favored trait classes are not yet two species.')
add(10,2,
'Eigenes Gegenbeispielmodell: Für vererbbare Körpergrößen kurz/mittel/lang sind bei UmweltD die Überlebensraten0,8/0,8/0,8, die erfolgreichen Nachkommen je überlebendem Tier aber1/2/1. In UmweltE sind die Gesamtbeiträge je Ausgangstier0,9/0,6/0,3 und inF 0,9/0,2/0,9. Ein zufälliger Sturm trifft dagegen alle Größen mit gleicher Wahrscheinlichkeit; in einer kleinen Restgruppe fehlen zufällig lange Tiere.',
'Own counterexample model: for heritable body sizes short/medium/long, survival in environmentD is0.8/0.8/0.8, but successful offspring per survivor are1/2/1. Overall contributions per initial animal are0.9/0.6/0.3 inE and0.9/0.2/0.9 inF. A random storm instead affects all sizes with the same probability; by chance, a small remnant group lacks long individuals.',
'Vergleiche die drei Selektionsmodi mit dem Sturmereignis und nutze fürD den gesamten Fortpflanzungsbeitrag. Prüfe die Behauptung, jede Verschiebung einer Größenverteilung sei gerichtete Selektion.',
'Compare the three modes of selection with the storm event and use total reproductive contribution forD. Evaluate the claim that every change in a size distribution is directional selection.',
'D hat Gesamtbeiträge0,8/1,6/0,8 und begünstigt die Mitte: stabilisierende Selektion trotz gleicher Überlebensrate. E begünstigt kurze Körper und ist gerichtet, F begünstigt Extreme und ist disruptiv. Das zufällige Sturmereignis kann über Stichprobenzufall genetische Drift bewirken; fehlende lange Tiere beweisen keinen erblichen Fitnessnachteil langer Tiere. Eine Verteilungsänderung allein kennzeichnet deshalb keinen Selektionsmodus. Man braucht vererbbare Unterschiede und deren systematische Verbindung zum reproduktiven Beitrag.',
'D has total contributions0.8/1.6/0.8 and favors the middle: stabilizing selection despite identical survival. E favors short bodies and is directional; F favors extremes and is disruptive. The random storm can cause genetic drift through sampling; absent long individuals do not establish a heritable fitness disadvantage. A distributional change alone therefore identifies no selection mode. Heritable differences and their systematic relationship with reproductive contribution are needed.')

add(11,1,
'Eigenes diskretes Fitnesslandschaftsmodell: Genotypen unterscheiden sich in zwei binären Positionen. Relative Fitness unter derselben Umwelt:00=1,0;10=1,2;01=0,8;11=1,6. Nachbarn unterscheiden sich in genau einer Position. Das vereinfachte Modell betrachtet zunächst nur schrittweise Änderungen mit positiver Fitnesswirkung, ohne Rekombination, Drift oder Umweltwechsel. Fitness ist relativer Fortpflanzungsbeitrag, keine gezeichnete tatsächliche Landschaft.',
'Own discrete fitness-landscape model: genotypes differ at two binary positions. Relative fitness in one environment is00=1.0;10=1.2;01=0.8;11=1.6. Neighbors differ at exactly one position. The simplified model initially permits only successive changes with positive fitness effects, excluding recombination, drift, and environmental change. Fitness denotes relative reproductive contribution, not a physical landscape.',
'Interpretiere einen adaptiven Pfad ab00 und prüfe lokale Optima anhand der Nachbarschaft. Erkläre, warum die Zeichnung keine zielgerichtete Planung eines Organismus darstellt.',
'Interpret an adaptive path from00 and identify local optima from the neighborhood. Explain why the diagram does not represent an organism’s goal-directed planning.',
'00→10→11 steigt in zwei Einzelschritten von1,0 über1,2 auf1,6. 00→01 ist unter der gesetzten Regel nicht zugelassen, weil die Fitness zunächst sinkt.11 ist ein lokales Optimum: beide Einzelschrittnachbarn10 und01 liegen niedriger; in diesem kleinen Modell ist es auch das globale Maximum. Mutationen entstehen nicht, weil ein Organismus den Gipfel kennt; Selektion kann Varianten mit höherem reproduktivem Beitrag häufiger werden lassen. Der mögliche Pfad ist eine Modellbeschreibung, keine garantierte tatsächliche Reihenfolge. Umwelt- und Genotypkontext sowie ausgelassene Prozesse begrenzen das Bild.',
'00→10→11 rises in two single steps from1.0 through1.2 to1.6.00→01 is excluded by the stated rule because fitness initially decreases.11 is a local optimum: both single-step neighbors10 and01 have lower values; in this small model it is also the global maximum. Mutations do not arise because an organism knows the peak; selection may increase variants with greater reproductive contributions. The permitted path describes a model, not a guaranteed actual sequence. Environmental and genotype context and omitted processes limit the representation.')
add(11,2,
'Eigenes Fitnesslandschaftsmodell mit drei binären Positionen:000=1,0;100=1,3;010=0,9;001=0,8;110=1,1;101=1,0;011=1,2;111=1,8. Nur Unterschiede an einer Position sind Nachbarschaft. Ein Pfad startet bei000. Zusätzlich steht als Hypothese ein Umweltwechsel, der110 auf1,5 anhebt; die übrigen Werte bleiben im Vergleich unverändert. Alle Werte sind eigene Modellzahlen.',
'Own fitness-landscape model with three binary positions:000=1.0;100=1.3;010=0.9;001=0.8;110=1.1;101=1.0;011=1.2;111=1.8. Only one-position differences define neighbors. A path starts at000. An additional hypothetical environmental change raises110 to1.5 while other values remain unchanged in the comparison. All values are own model figures.',
'Diskutiere, ob ein ausschließlich fitnesssteigernder Pfad von000 das globale Maximum111 erreicht. Bestimme das lokale Optimum und erläutere die Wirkung des Umweltwechsels sowie eine mögliche Grenze der strikten Pfadregel.',
'Discuss whether a path from000 allowing only fitness increases reaches the global maximum111. Identify the local optimum and explain the environmental change and one possible limit of the strict path rule.',
'Zunächst ist000→100 der einzige steigende Anfangsschritt.100 ist ein lokales Optimum, weil000,110 und101 niedrigere Fitness haben;111 bleibt global höher, ist aber unter der strikten Regel von dort nicht erreichbar. Nach dem Umweltwechsel erlaubt100→110→111 weitere Steigerung: das lokale Optimum hängt vom Kontext ab. Drift in kleinen Populationen, Rekombination oder mehrere Änderungen können unter passenden Bedingungen die strikte Einzelschrittregel überschreiten; das bedeutet weder einen sicheren Sprung noch zielgerichteten Fortschritt. Lokales Maximum und global bestes Modellresultat sind zu unterscheiden.',
'Initially000→100 is the only increasing first step.100 is a local optimum because000,110, and101 have lower fitness;111 is globally higher but cannot be reached from100 under the strict rule. After environmental change,100→110→111 permits further increases: local optima depend on context. Drift in small populations, recombination, or multiple changes may under suitable conditions exceed the strict single-step rule; this implies neither a certain jump nor goal-directed progress. A local maximum differs from the globally highest modeled outcome.')

add(12,1,
'Eigenes Bestäubungsmodell: Pflanzentypen haben vererbbare kurze oder lange Blütenröhren; Bestäubertypen vererbbare kurze oder lange Mundwerkzeuge. Lange Röhren werden durch lange Mundwerkzeuge häufiger wirksam bestäubt; bei langen Röhren erreichen lange Mundwerkzeuge mehr Nahrung. In kontrollierten Vergleichsreihen ändern sich Fortpflanzungsbeiträge beider Partner mit dem Häufigkeitsverhältnis des jeweils anderen. Ein bloßes gemeinsames Auftreten zweier Arten wurde als schwächeres Vergleichsmaterial beigelegt.',
'Own pollination model: plants have heritable short or long flower tubes; pollinators have heritable short or long mouthparts. Long tubes are more effectively pollinated by long mouthparts, which also reach more food in long tubes. Controlled comparisons show reproductive contributions in both partners varying with the frequency of the other partner’s types. Mere coexistence of two species is included as weaker comparison material.',
'Untersuche, welche Daten eine koevolutionäre Beziehung stützen. Begründe die wechselseitigen Selektionswirkungen und grenze Übereinstimmung von Merkmalen oder Zusammenleben allein als Beleg ab.',
'Examine which data support a coevolutionary relationship. Explain reciprocal selection and distinguish matching traits or coexistence alone from sufficient evidence.',
'Die vererbbaren Merkmale beeinflussen die Fortpflanzungsbeiträge des jeweils anderen Partners: Bestäuber verändern Pflanzenbestäubung, Blütenformen den Nahrungszugang und damit im Modell den Fortpflanzungsbeitrag der Bestäuber. Nachgewiesene Änderungen beider Partner über Generationen könnten die wechselseitige evolutionäre Antwort ergänzen. Die Vergleichsreihen stützen den Selektionsmechanismus, nicht allein einen lückenlosen historischen Verlauf. Gemeinsames Auftreten oder passende Formen können auch ohne nachgewiesene gegenseitige Evolution entstehen. Koevolution benötigt gerichtete Evidenz wechselseitiger Selektionswirkungen und evolutionärer Antworten; sie bedeutet keine bewusste Zusammenarbeit.',
'Heritable traits affect the other partner’s reproductive contribution: pollinators alter plant pollination, while flower forms alter food access and modeled pollinator reproduction. Demonstrated generational changes in both partners could additionally establish reciprocal evolutionary responses. The comparisons support a selection mechanism, not by themselves a complete historical sequence. Coexistence or matching shapes can occur without demonstrated reciprocal evolution. Coevolution requires targeted evidence of reciprocal selection and evolutionary responses; it does not mean deliberate cooperation.')
add(12,2,
'Eigenes Wirt-Parasit-Zeitvergleichsmodell: Wirtlinien Wfrüh/Wspät und Parasitlinien Pfrüh/Pspät werden in standardisierten bereits vorgegebenen Kreuztests verglichen. Infektionsanteile: Wfrüh/Pfrüh60%;Wfrüh/Pspät80%;Wspät/Pfrüh20%;Wspät/Pspät55%. Beide Merkmalsunterschiede sind im Modell erblich; erfolgreiche Infektion beeinflusst Parasitenreproduktion, Resistenz Wirtsreproduktion. Historische Feldgrößen oder echte Infektionsexperimente mit Lernenden sind nicht Teil des Falles.',
'Own host-parasite time-comparison model: early/late host lines and early/late parasite lines are compared in supplied standardized cross-tests. Infection proportions are earlyHost/earlyParasite60%,earlyHost/lateParasite80%,lateHost/earlyParasite20%,lateHost/lateParasite55%. Both trait differences are heritable in the model; successful infection affects parasite reproduction and resistance affects host reproduction. Historical field sizes and actual infection experiments performed by learners are not part of this case.',
'Interpretiere die Matrix als möglichen koevolutionären Verlauf. Erläutere getrennt Wirt- und Parasitenänderung und prüfe die Aussage, Koevolution müsse immer zu dauerhafter Perfektion beider Partner führen.',
'Interpret the matrix as a possible coevolutionary sequence. Explain changes in host and parasite separately and assess the claim that coevolution always produces permanent perfection in both partners.',
'Der späte Wirt ist gegenüber dem frühen Parasiten resistenter:20%statt60%. Der späte Parasit infiziert beide Wirte häufiger als der frühe:80%statt60% beziehungsweise55%statt20%. Das ist mit wechselseitiger Anpassung von Resistenz und Infektionsfähigkeit vereinbar, wenn Unterschiede erblich und Selektionszusammenhänge belegt sind. Die Matrix allein beweist nicht alle historischen Ursachen; unabhängige Umweltänderungen sind zu kontrollieren. Relativer Vorteil kann sich mit dem Partner verändern; Koevolution kann dynamisch und antagonistisch sein statt einen dauerhaften perfekten Endzustand zu erzeugen.',
'The late host is more resistant to the early parasite:20%instead of60%. The late parasite infects both hosts more frequently than the early parasite:80%instead of60%and55%instead of20%. This fits reciprocal adaptation of resistance and infection ability if heritability and selection relationships are established. The matrix alone establishes no complete historical causation; independent environmental changes require control. Relative advantage can change with the partner; coevolution can be dynamic and antagonistic rather than producing a permanently perfect endpoint.')
