#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Source-faithful executable operation designs; no performed-human claims."""
from pathlib import Path
import json, subprocess, hashlib
BASE=Path(__file__).resolve().parent;ROOT=BASE.parents[6];REL=BASE.relative_to(ROOT).as_posix()
def put(name,v):
 p=BASE/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');return p.relative_to(ROOT).as_posix()
def binding(p):
 p=ROOT/p;b=p.read_bytes();return {'path':p.relative_to(ROOT).as_posix(),'sha256':'sha256:'+hashlib.sha256(b).hexdigest(),'bytes':len(b)}
companion=json.loads((BASE/'candidate/one-bounded-behaviour-companion.goal.json').read_text())
owners={'microscopy':'91df35c7-e384-50d6-bb3a-37e74a6086f1','observation':'0f1549f6-8341-53b0-8161-5eaeb2b37809','models':'713e062d-2bb9-5fbc-8040-129387c7d3ca','investigation':'82acfbde-9ce8-5658-892e-4dcfb1c3a1f1'}
methods=[
 {'methodId':'SN-moss-fern-seed-axis-crosssections','sourceDuty':'source-duty-0311','primaryPhysicalPages':[43],'primaryPrintedPages':[31],'owners':[owners['microscopy'],owners['observation']],
  'purposeDe':'Mikroskopische Querschnitte von Moosstämmchen, Farnachse und Samenpflanzenachse tatsächlich mikroskopieren und anhand erkennbarer Leit-/Festigungsstrukturen vergleichen. Ein erzählter Querschnitt ersetzt das Mikroskopieren nicht.',
  'purposeEn':'Actually examine microscopic cross-sections of a moss stem, fern axis and seed-plant axis and compare visible conducting/supporting structures. A narrated section is not microscopy.',
  'materialsDe':['Schulmikroskop','drei korrekt bestimmte und beschriftete tatsächliche Präparate; geeignetes Moos, Farn und krautige Samenpflanze','von Lehrkraft vorab geschnittenes Material zum eigenen Wasserpräparat','Objektträger, Deckglas, Wasser, Pipette, Pinzette','leere Beobachtungstabelle'],
  'materialsEn':['school microscope','three correctly identified and labelled actual specimens: suitable moss, fern and herbaceous seed plant','teacher-precut material for the learner to mount in water','slides, coverslip, water, pipette, tweezers','blank observation table'],
  'procedureDe':['Ein einfaches Wasserpräparat aus vorbereitetem dünnem Material herstellen; Deckglas schräg absenken und Blasen prüfen. Die Lehrkraft übernimmt nötige Schneidarbeiten.','Am kleinsten Objektiv beginnen; Licht/Blende und Fokus sachgerecht einstellen, erst danach stärker vergrößern.','Alle drei wirklichen Querschnitte bei vergleichbarem Maßstab betrachten; Pflanzenbezeichnung, Vergrößerung und sichtbare Merkmale mit beschrifteter Skizze protokollieren.','Leit-/Festigungsstrukturen nur benennen, wenn im konkreten Präparat erkennbar; Moos nicht pauschal als ohne jegliche Leitung erklären.','Gemeinsamkeiten und Unterschiede aus tatsächlichen Beobachtungen ableiten; keine heutige Art als direkten Vorfahren der anderen ausgeben.'],
  'procedureEn':['Prepare a simple water mount using precut thin material; lower the coverslip at an angle and check bubbles. The teacher performs any necessary cutting.','Start with the lowest-power objective; adjust illumination/aperture and focus correctly before increasing magnification.','Inspect all three real sections at comparable scale; record plant identification, magnification and observed traits with labelled sketches.','Name conducting/supporting structures only when identifiable in the particular specimen; do not claim all mosses lack any conducting cells.','Infer similarities/differences from actual observations; no living species is described as the direct ancestor of another.'],
  'requiredActualEvidenceDe':['eigenes tatsächlich hergestelltes Präparat','Bedienbeobachtung oder nachvollziehbares Gerä­te-/Fokusprotokoll','drei tatsächliche beschriftete Querschnittsbeobachtungen','begründeter Vergleich mit Unsicherheiten'],
  'requiredActualEvidenceEn':['an actual learner-made mount','observed operation or a traceable instrument/focusing record','three actual labelled cross-section observations','a justified comparison with uncertainty'],
  'evaluationDe':'Vollständige Durchführung, passende Fokussierung, echte beobachtete Strukturmerkmale und Vergleich prüfen. Ein Musterbild oder synthetische Tabelle belegt weder Präparieren noch Mikroskopieren.','evaluationEn':'Check completed operation, suitable focusing, real observed structural traits and comparison. A sample image or synthetic table proves neither specimen preparation nor microscopy.'},
 {'methodId':'ST-natural-variation-observe','sourceDuty':'source-duty-0321','primaryPhysicalPages':[44],'primaryPrintedPages':[44],'owners':[owners['observation']],
  'purposeDe':'Variabilität an natürlichen Objekten beobachten, dokumentieren und auswerten.','purposeEn':'Observe, document and evaluate variation in natural objects.',
  'materialsDe':['20 Blätter derselben sicher bestimmten, häufigen Pflanzenart aus zwei festgelegten Stellen','Lineal','leere Tabelle: Ort, Blattnummer, Länge, Breite, Fraßspuren, Unsicherheit'],
  'materialsEn':['20 leaves of the same confidently identified common plant species from two specified places','ruler','blank table: site, leaf number, length, width, feeding traces, uncertainty'],
  'procedureDe':['Vor dem Sammeln/Messen Kriterien und Maßeinheiten festlegen; Tiere/Pflanzen am Ort zusätzlich beobachten und Fundorte protokollieren.','Je zehn Blätter zufällig nach vorab festgelegter Regel wählen; beschädigte Blätter nicht heimlich ausschließen.','Länge/Breite messen und sichtbare Fraßspuren nach angegebenem Kriterium zählen; Unklarheiten markieren.','Rohdaten übersichtlich darstellen, Spannweite und Lage beschreiben; Variation zwischen Individuen nicht mit Artenvielfalt verwechseln.','Vergleich mit der zweiten Stelle durchführen; genetische Ursache, Umwelteinfluss und Auslese nicht aus bloßen Blattmaßen als bewiesen ausgeben.'],
  'procedureEn':['Set criteria and units before collecting/measuring; also observe organisms at the site and record the locations.','Choose ten leaves per site randomly using a predefined rule; do not silently discard damaged leaves.','Measure length/width and count visible feeding traces using the stated criterion; flag uncertainty.','Display raw data, spread and location; do not confuse within-species variation with species diversity.','Compare the second site; leaf measurements alone do not prove a genetic cause, environmental effect or selection.'],
  'requiredActualEvidenceDe':['natürliche Fundorte und tatsächliche Objekte','eigene Rohmessdaten einschließlich Unsicherheiten','Darstellung und begrenzte Auswertung'],
  'requiredActualEvidenceEn':['natural sites and actual objects','own raw measurements including uncertainty','display and bounded evaluation'],
  'evaluationDe':'Prüfen, dass natürlich beobachtet/gemessen wurde; Ergebnis nicht anhand eines verlangten Musterwerts bewerten.','evaluationEn':'Verify natural observations/measurements actually occurred; do not grade by demanding a predetermined result.'},
 {'methodId':'ST-construct-fossil-model','sourceDuty':'source-duty-0321','primaryPhysicalPages':[44,45],'primaryPrintedPages':[44,45],'owners':[owners['models'],owners['investigation']],
  'purposeDe':'Fossilbildung durch eine tatsächlich hergestellte Abformung modellieren; Entstehungsprinzip und Grenzen erklären.','purposeEn':'Model fossil formation by actually producing a mould/cast; explain the principle and model limits.',
  'materialsDe':['leere Muschelschale oder formstabiles Modell','lufttrocknende Modelliermasse als Sedimentmodell','andersfarbige weiche Modelliermasse als spätere Füllung','leeres Foto-/Skizzen- und Zeitprotokoll'],
  'materialsEn':['empty shell or rigid model','air-drying modelling clay representing sediment','soft clay in a different colour representing later infill','blank photo/sketch and timing record'],
  'procedureDe':['Schalenoberfläche im noch weichen Sedimentmodell abformen, dann Schale entfernen und den entstandenen Abdruck tatsächlich sichern.','Abformung trocknen lassen; mit andersfarbiger Masse füllen und den Abguss herauslösen. Jeden realen Arbeitsschritt protokollieren.','Abdruck und Abguss mit dem Original vergleichen; Oberflächenform versus erhaltenes ursprüngliches Material unterscheiden.','Als Kontrast eine Spur im Sedimentmodell erzeugen und erklären, warum eine Spur nicht der erhaltene Körper ist.','Grenzen benennen: Tonabformung bildet keine geologische Zeit, Kompaktion, echte Mineralersetzung oder alle Fossilisationswege nach; Ergebnis ist ein Modell, kein Fossil.'],
  'procedureEn':['Press the shell into soft sediment-model clay, remove it and actually retain the mould.','Let the mould dry; fill it with contrasting clay and remove the cast. Record every actual operation.','Compare the mould and cast with the original; distinguish surface shape from preserved original material.','Produce a trace in the sediment model as a contrast and explain why a trace is not the preserved body.','State limits: clay casting does not reproduce geological time, compaction, real mineral replacement or every fossilization pathway; the result is a model, not a fossil.'],
  'requiredActualEvidenceDe':['tatsächlich hergestellte Abformung und Abguss','eigene Schritt-/Zeitdokumentation','erklärter Zusammenhang und Kontrast','Modellgrenzen'],
  'requiredActualEvidenceEn':['an actually produced mould and cast','own procedure/time record','explained relation and contrast','model limits'],
  'evaluationDe':'Gebautes Modell plus Erklärung prüfen; Lesen eines fertigen Datensatzes erfüllt den Bauoperator nicht.','evaluationEn':'Check the constructed model plus explanation; reading a finished dataset does not fulfil the construction operator.'},
 {'methodId':'ST-conduct-selection-model-experiment','sourceDuty':'source-duty-0321','primaryPhysicalPages':[45],'primaryPrintedPages':[45],'owners':[owners['models'],owners['investigation']],
  'purposeDe':'Einen kontrollierten Selektionsmodellversuch durchführen und auswerten.','purposeEn':'Conduct and evaluate a controlled selection model experiment.',
  'materialsDe':['je 40 gleich große helle und braune Papiertokens mit identischer Form','helle und braune Unterlage','Stoppuhr','leeres Rohdaten-/Variablenprotokoll'],
  'materialsEn':['40 light and 40 brown paper tokens of equal size and identical shape','light and brown backgrounds','timer','blank raw-data/variable record'],
  'procedureDe':['Hypothese formulieren: schlechter sichtbare Farbe bleibt nach zeitbegrenztem Aufsammeln häufiger zurück. Tokenzahl, Größe, Suchzeit und Suchregel konstant halten; Unterlagenfarbe variieren.','Tokens nach derselben randomisierten Verteilregel auslegen; eine suchende Person sammelt sichtbare Tokens für20Sekunden auf, ohne Farbquota. Tatsächliche Überlebendenzahlen protokollieren.','Auf heller und brauner Unterlage mit gleichen Startzahlen je mindestens drei Durchgänge durchführen; Reihenfolge wechseln, Ermüdung/Übung protokollieren.','Relative Häufigkeiten berechnen, Streuung und Richtungswechsel auswerten. Falls Daten Hypothese nicht stützen, das Ergebnis ehrlich behalten.','Tokens fressen, mutieren und pflanzen sich nicht fort. Der Versuch modelliert unterschiedliche Überlebenschancen; eine Veränderung über Generationen verlangt zusätzlich vererbbare Merkmale und Fortpflanzung.'],
  'procedureEn':['Formulate the hypothesis: the less visible colour remains more often after timed collection. Keep token number, size, search time and search rule constant; vary background colour.','Place tokens using the same randomized rule; a searcher collects visible tokens for20seconds without a colour quota. Record actual survivor counts.','Run at least three trials per background with equal starting counts; alternate the order and record fatigue/practice.','Calculate relative frequencies, variation and direction reversal. Retain results honestly when the hypothesis is not supported.','Tokens do not feed, mutate or reproduce. This experiment models different survival probabilities; change over generations additionally requires inherited traits and reproduction.'],
  'requiredActualEvidenceDe':['ausgeführte Durchgänge mit Rohzahlen','Variablen-/Kontrollplan','begründete Auswertung und Streuung','Unterschied Versuch/lebende Population'],
  'requiredActualEvidenceEn':['executed trials with raw counts','variable/control plan','justified evaluation and variation','distinction between experiment and living population'],
  'evaluationDe':'Tatsächliche Durchführung und Auswertung erforderlich; Autor-Simulationsergebnisse zählen nicht als Lernerdurchführung.','evaluationEn':'Actual operation and evaluation required; author simulation output does not count as learner execution.'},
 {'methodId':'ST-computer-simulation-variation-selection','sourceDuty':'source-duty-0321','primaryPhysicalPages':[44],'primaryPrintedPages':[44],'owners':[owners['models'],owners['investigation']],
  'purposeDe':'Variation und Selektion softwaregestützt simulieren und als Grundlage gezielter Auslesezüchtung deuten.','purposeEn':'Simulate variation and selection with software and interpret their use for selective breeding.',
  'materialsDe':[REL+'/selection_simulation.py','Python3','leeres Parameters-/Ergebnis-/Grenzenprotokoll'],
  'materialsEn':[REL+'/selection_simulation.py','Python3','blank parameter/result/limits record'],
  'procedureDe':['Software tatsächlich mit neutraler Kontrolle und entgegengesetzter Selektion ausführen; Populationsgröße, Generationszahl und Vererbung konstant halten, Überlebensgewichte variieren.','Ergebnisse der40 Wiederholungen auslesen; Mittelwerte und einzelne Verläufe vergleichen, zufällige Drift von gerichteter Selektion unterscheiden.','Eigenen zweiten Lauf mit halbierter Populationsgröße und neuem Seed durchführen; Wirkung auf Schwankungen prüfen, nicht aus einem Lauf ein Gesetz behaupten.','Für Auslesezüchtung erklären: unterschiedliche Fortpflanzungsbeiträge geeigneter vererbbarer Merkmale können deren Häufigkeit verändern; gewünschte Eigenschaften entstehen nicht bedarfsgeleitet durch Auswahl.','Modellgrenzen: zwei vererbte Phänotypen in asexueller Population, gewichtetes Fortpflanzungs-Sampling, keine diploiden Genotypen, Mutation/Rekombination, Lebewesen oder ethische Zuchtentscheidung.'],
  'procedureEn':['Actually run software with a neutral control and reversed selection; keep population size, generations and inheritance fixed and vary survival weights.','Read the40 replicates; compare means and individual trajectories, distinguish random drift from directional selection.','Execute a second run with half the population size and a new seed; inspect fluctuations without treating one run as a law.','Explain selective breeding: different reproductive contributions of suitable inherited traits can change their frequency; choosing does not cause a needed trait to appear.','Limits: two inherited phenotypes in an asexual population, weighted reproductive sampling, no diploid genotypes, mutation/recombination, real organisms or ethical breeding decision.'],
  'requiredActualEvidenceDe':['eigene tatsächliche Software-Aufrufe und Parameter','Kontrolle/Selektion/Umkehr mit Ergebnisdaten','Vergleich, Auslese-Deutung und Grenzen'],
  'requiredActualEvidenceEn':['own actual software invocations and parameters','control/selection/reversal output','comparison, selective-breeding interpretation and limits'],
  'evaluationDe':'Aufruf-/Ergebnisdateien prüfen. Die unten gebundene Autoren-Ausführung beweist nur lauffähige Software, keine eigene Lernerleistung.','evaluationEn':'Inspect invocation/output files. The bound author execution below proves runnable software only, not learner performance.'}
]
for m in methods:
 m.update({'candidateStatus':'ai_candidate','reviewStatus':'needs_human_review','independentMethodApproval':False,'humanApproval':False,'humanTrial':False,'actualLearnerPerformance':False,'actualHumanExperimentPerformed':False,'blankPerformanceRecord':{'performer':None,'performedAt':None,'rawObservations':None,'actualMediaBindings':[],'result':None},'successfulUnderstandingFromTextAlone':False,'methodOwnerContextApproval':'pending','license':'CC-BY-4.0'})
put('material/five-source-faithful-executable-method-protocols.author-candidate.json',{'schemaVersion':1,'role':'actual-operation-assessment-design-not-performed-operation','methodProtocols':methods,'originalSelected18TaskQuotaChanged':False,'whole35DutyFramePreserved':True,'methodOwnersReusedWithoutGoalTextChanges':True,'independentApproval':False,'strictGain':0})

cases=[
 {'caseId':'RP-human-stress-immediate-danger-ancestral-function','taskDe':'Gegeben: Bei plötzlichem lautem Knall in der Nähe spannt eine Person Muskeln an, Herzfrequenz und Atmung steigen, sie weicht zurück. In der Informationskarte wird beschrieben: schnelle Energiebereitstellung und rasche Bewegung können bei einer unmittelbaren körperlichen Gefahr die Flucht erleichtern; Menschen stammen von früheren Populationen ab und teilen grundlegende Reaktionsmechanismen mit anderen Säugetieren. Verknüpfe unmittelbaren Auslöser, Funktion und Abstammung. Erkläre auch, welche Aussage diese Informationen nicht beweisen.',
  'taskEn':'Given: after a sudden nearby bang, a person tenses their muscles, heart rate and breathing increase, and they move back. An information card describes how rapid energy availability and movement can aid escape from immediate physical danger; humans descend from earlier populations and share basic response mechanisms with other mammals. Connect the immediate trigger, function and ancestry. Also explain what these data do not prove.',
  'expectedDe':'Der Knall ist unmittelbarer Auslöser; koordinierte schnelle Aktivierung erleichtert unter passenden Bedingungen Bewegung/Flucht. Abstammung und gemeinsame Säugetiermechanismen erlauben eine evolutionäre Funktionserklärung als überprüfbare Hypothese. Das Individuum aktiviert die Reaktion nicht, um erst einen erblichen Vorteil zu erzeugen. Ein möglicher Vorteil beweist weder die genaue historische Selektionsgeschichte noch, dass jede einzelne Reaktion heute hilfreich ist.',
  'expectedEn':'The bang is the immediate trigger; coordinated rapid activation can facilitate movement/escape in suitable conditions. Ancestry and shared mammalian mechanisms support an evolutionary functional account as a testable hypothesis. The individual does not trigger the response to create an inherited advantage. A possible benefit proves neither its precise historical selection history nor that each present-day response is helpful.',
  'materialKind':'own bounded hypothetical informational case; no actual patient/learner data','actualHumanEvidence':False},
 {'caseId':'RP-human-stress-exam-mismatch-limit','taskDe':'Gegeben: Vor einem schriftlichen Test erlebt eine Person dieselbe schnelle körperliche Aktivierung, obwohl Weglaufen keine Lösung für die Aufgaben bietet. Die Informationskarte aus dem ersten Fall bleibt gültig. Erkläre mithilfe der Abstammung, warum ein grundsätzlich bei körperlicher Gefahr plausibler Mechanismus auch hier auftreten kann. Trenne die Funktionshypothese von der aktuellen Nützlichkeit und nenne eine Untersuchung, die für die Hypothese zusätzliche Belege liefern könnte.',
  'taskEn':'Given: before a written test, a person experiences the same rapid physical activation even though running away does not solve the questions. The first case information card remains valid. Use ancestry to explain why a mechanism with a plausible role during physical danger may also be triggered here. Separate the functional hypothesis from present usefulness and name an investigation that could provide additional evidence.',
  'expectedDe':'Ein über Abstammung erhaltener Reaktionsmechanismus kann durch wahrgenommene Bedrohung ausgelöst werden, ohne dass die aktuelle Aufgabe körperliche Flucht verlangt. Plausible ursprüngliche Funktion und heutige Wirkung sind verschieden; kein zielgerichtetes Bedürfnis erzeugt im Test neue Erbanlagen. Eine vergleichende Untersuchung von Auslösern/Reaktionsmechanismen bei Säugetieren oder Daten zu Fitnesswirkungen unter tatsächlich körperlichen Gefahren können die Hypothese weiter prüfen, beweisen aber nicht automatisch jede historische Einzelursache.',
  'expectedEn':'A response mechanism retained through ancestry can be triggered by perceived threat even when the present task does not require physical escape. A plausible original function and current effect differ; an immediate need during a test does not produce new inherited variants. Comparative work on mammalian triggers/mechanisms or evidence about fitness effects under actual physical dangers can test the hypothesis further, but does not automatically prove every historical cause.',
  'materialKind':'own bounded hypothetical informational transfer case; not medical advice','actualHumanEvidence':False}
]
put('material/RP-ancestry-behaviour-two-full-bilingual-material-cases.author-candidate.json',{'schemaVersion':1,'role':'one-new-assessable-companion-whole-material-not-independent-approval','goalId':companion['id'],'wholeGoal':companion,'cases':cases,'wholeDemandDe':'Für beide Kontextfälle einen unmittelbaren Auslöser mit einer durch Abstammung begründeten evolutionären Funktionshypothese verknüpfen, aktuelle Wirkung und historischen Nutzen unterscheiden und Nachweisgrenzen erklären.','wholeDemandEn':'For both contexts, connect the immediate trigger with an evolutionary functional hypothesis grounded in ancestry, distinguish current effect from historical benefit, and explain evidential limits.','memoryAuthorCandidate':{'decision':'no_additional_deck','rationaleDe':'Beurteilt wird die materialgestützte Erklärung samt Grenzen; zentrale begriffliche Kenntnisse liegen bereits in bestehenden Basiszielen. Kein eigenständiges Fakten-Kartendeck erforderlich.','rationaleEn':'Assessment concerns material-based explanation and its limits; key terms are already addressed in basis goals. No separate factual card deck is required.','independentReview':'pending','actualCardAndVisibilityCheck':'not performed; no new cards or active memory decision authored'},'positiveUnderstandingEvidenceV2Status':'not yet materialized; needs independent semantic-kind/atomicity and whole profile authoring','candidateStatus':'ai_candidate','reviewStatus':'needs_human_review','humanApproval':False,'humanTrial':False,'sourceApproval':False,'imageGenerated':False,'strictGain':0,'license':'CC-BY-4.0'})

argv=['python3',REL+'/selection_simulation.py','--n','200','--generations','5','--replicates','40','--seed','7300']
r=subprocess.run(argv,cwd=ROOT,text=True,capture_output=True)
(BASE/'checks').mkdir(exist_ok=True)
(BASE/'checks/selection-simulation.actual.stdout.txt').write_text(r.stdout)
(BASE/'checks/selection-simulation.actual.stderr.txt').write_text(r.stderr)
assert r.returncode==0,r.stderr
d=json.loads(r.stdout)
put('checks/executable-software-operation.actual.receipt.json',{'schemaVersion':1,'argv':argv,'cwd':'.','exitCode':r.returncode,'softwareBinding':binding(REL+'/selection_simulation.py'),'stdout':binding(REL+'/checks/selection-simulation.actual.stdout.txt'),'stderr':binding(REL+'/checks/selection-simulation.actual.stderr.txt'),'completedSyntheticAuthorRuns':d['replicates']*len(d['conditions']),'controlAndReversalAssertionsPassed':True,'terminalMeanBrownFrequencies':{c['name']:c['meanBrownFrequencyByGeneration'][-1] for c in d['conditions']},'provesSoftwareExecutable':True,'provesLearnerPerformedRequiredSoftwareOperation':False,'actualHumanExperiment':False,'actualLearnerPerformance':False,'independentApproval':False})
print(json.dumps({'methodProtocols':len(methods),'actualAuthorSimulationRuns':120,'actualHumanOperationEvidence':False,'RPCompanionCases':len(cases),'newGoalImages':0,'strictGain':0}))
