import json,pathlib,hashlib,copy,shutil,gzip
R=pathlib.Path('/home/enpasos/projects/skillpilot');O=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-current577-twentytwo-qualified470-independent-combined-scope-review-v1';D=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-current577-twentytwo-qualified-and-nine-existing-access-fieldwise-root-candidate-v1';H=D/'three-actually-qualified-foreign-scope-seals-final-author-followup-v2/actual-final-twentytwo-qualified-nine-existing470-current577-fieldwise-author-handoff-with-three-real-foreign-scope-seals.json';h=json.load(open(H));freeze=json.load(open(D/'actual-v14-SEM577-P336685-book577-technical-only-freeze.json'))
def sh(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def info(p):return {'path':str(p.relative_to(R)),'sha256':sh(p),'bytes':p.stat().st_size}
def wr(n,x):p=O/n;assert not p.exists();p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');return info(p)
def snap(p):q=O/'additional-technical-inputs'/p.relative_to(R);q.parent.mkdir(parents=True,exist_ok=True);assert not q.exists();shutil.copyfile(p,q);return info(q)
b=json.load(open(R/h['canonicalBefore']['path']));a=json.load(open(R/h['canonicalCandidate']['path']));bg={g['id']:g for g in b['goals']};ag={g['id']:g for g in a['goals']};s0=json.load(open(R/freeze['oldKindLedger']['path']));s1=json.load(open(R/freeze['newSEM']['path']));sg0={r['goalId']:r for r in s0['decisions']};sg1={r['goalId']:r for r in s1['decisions']};ordinary={r['goalId']for r in s0['decisions']if r['semanticKind']=='curricularAtomic'};mem={r['goalId']for r in s0['decisions']if r['semanticKind']=='memory'};orient={r['goalId']for r in s0['decisions']if r['semanticKind']=='orientation'};assert len(ordinary)==336 and len(mem)==10 and len(orient)==1;nav={n['wholeBefore']['id']for n in h['actualFourWholeNavDeltas']}
for gid in sg0:
 x=copy.deepcopy(sg0[gid]);y=sg1[gid]
 if gid in nav:x['sourceFingerprint']=y['sourceFingerprint']
 assert x==y,gid
assert all(sg1[g]['semanticKind']=='practiceAssessment'for g in h['newQualifiedPracticeGoalIds'])
reports={n:json.load(open(O/('actual-'+n+'-full-native-source-role-route-report.json')))for n in ['before555','after577','refdrop577','supportdrop577']};before=reports['before555'];after=reports['after577'];rd=reports['refdrop577'];sd=reports['supportdrop577'];key=lambda r:r['viewPath']+'|'+r['jurisdiction']+'|'+json.dumps(r['scopeFilters']);rows0={key(r):r for r in before['allScopeRows']};rows1={key(r):r for r in after['allScopeRows']};assert set(rows0)==set(rows1)and len(rows0)==64
role=[]
for k,x in rows0.items():
 y=rows1[k];assert set(x['ordinaryTargetIds'])==set(y['ordinaryTargetIds']);sets={}
 for label,allowed in [('ordinarySupport',ordinary),('memory',mem),('orientation',orient)]:
  for fld in ['visibleAllAtomicIds','visibleTargetAtomicIds']:
   old=set(x[fld])&allowed;new=set(y[fld])&allowed;assert old==new,(k,label,fld);sets[label+'_'+fld]=sorted(old)
 role.append({'scopeKey':k,'jurisdiction':x['jurisdiction'],'courseFilters':x['scopeFilters'],'wholeOrdinaryTargetIDs':sorted(x['ordinaryTargetIds']),'ordinarySupportMemoryOrientationRolesExact':sets,'actualMissingRoutesBefore':x['missingEffectiveTerminalTargetIds'],'actualMissingRoutesAfter':y['missingEffectiveTerminalTargetIds'],'newExpectedPracticeIDs':sorted(set(y['expectedTerminalIds'])-set(x['expectedTerminalIds'])),'newVisiblePracticeIDs':sorted(set(y['actualTerminalIds'])-set(x['actualTerminalIds']))})
assert sum(len(x['ordinaryTargetIds'])for x in before['allScopeRows'])==6974
bc={r['goalId']:r for r in before['compilerGoals']};ac={r['goalId']:r for r in after['compilerGoals']};assert all(bc[g]==ac[g]for g in ordinary|mem|orient)
assert before['sourceRule']==after['sourceRule']==rd['sourceRule']==sd['sourceRule'];assert after['sourceRule']['status']=='pass';assert after['compilerSummary']=={'goals':577,'errors':0,'warnings':0,'diagnostics':1457}
met=lambda z:next(r['metrics']for r in z['nativeRules']if r['id']=='CQR-104');m0=met(before);m1=met(after);mr=met(rd);ms=met(sd)
assert m0['visibleSelectedGoalOccurrencesMissingEffectiveTerminalRoute']==1246 and m1['visibleSelectedGoalOccurrencesMissingEffectiveTerminalRoute']==752
assert m0['uniqueVisibleSelectedGoalsMissingEffectiveTerminalRoute']==129 and m1['uniqueVisibleSelectedGoalsMissingEffectiveTerminalRoute']==102
assert m0['projectionScopesMissingTerminalAutonomyGoals']==6 and m1['projectionScopesMissingTerminalAutonomyGoals']==0
for fld in ['projectionScopesWithIncompleteWholeMaterialCoverageBindings','projectionScopesWithIncompleteWholeMaterialPrerequisiteClosure','projectionScopesWithInvalidStageStructure','visibleProjectedRouteTargetGoalOccurrencesExcludedFromRouteChecks','visibleProjectedRouteTargetGoalOccurrencesExcludedByProfileSelector']:
 assert m1[fld]==0
assert mr['projectionScopesMissingTerminalAutonomyGoals']==1 and mr['visibleSelectedGoalOccurrencesMissingEffectiveTerminalRoute']==754
assert ms['wholeMaterialCoveredGoalOccurrencesWithoutVisiblePrerequisitePath']==2 and ms['wholeMaterialPrerequisiteOccurrencesMissingFromProjection']==4
pold=R/'curricula/DE/Gymnasium/quality/deep-understanding-rollout/wirtschaft-current555-twentythree-qualified477-20261010-v13/whole-current336-original-positive-profiles685cases-no-profile-or-input-change.jsonl';pnew=R/freeze['newWholeP336']['path'];assert pold.read_bytes()==pnew.read_bytes();pRows=[json.loads(s)for s in pold.read_text().splitlines()if s];pm={p['goalId']:p for p in pRows};assert set(pm)==ordinary
# Exact 43 native config and review-line reuse; no CLI rerun or scientific decision implied.
configs=[];techsnaps=[]
for row in freeze['all43ConfigChanges']:
 old=R/row['old']['path'];new=R/row['new']['path'];review=R/row['reviewWholeBytesUnchanged']['path'];assert sh(old)==row['old']['sha256']and sh(new)==row['new']['sha256']and sh(review)==row['reviewWholeBytesUnchanged']['sha256'];x=json.load(open(old));y=json.load(open(new));x['semanticKindLedgerPath']=y['semanticKindLedgerPath'];assert x==y;configs.append({'wholeBefore':row['old'],'wholeAfter':row['new'],'oneField':'semanticKindLedgerPath','wholeReviewLinesExact':row['reviewWholeBytesUnchanged']});techsnaps+=[snap(new),snap(review)]
techsnaps+=[snap(pnew),snap(R/freeze['newSEM']['path'])]
# Whole 25 material x64 current native scope decisions. Reuse separately qualified science; whole closure and actual course/tag/jurisdiction are inspected here.
ids=h['newQualifiedPracticeGoalIds']+[x['goalId']for x in h['existing3WholeScientificReuseBindings']];materialrows={r['id']:r for r in after['materials']};matcontexts=[];materialinputs=[]
for gid in ids:
 g=ag[gid];r=materialrows[gid];assert not r['unresolvedReferences'];cover=g['examData']['coveredGoalIds'];assert all(c in ordinary for c in cover);closure=set(r['wholeMaterialPrerequisites']);materialinputs.append({'goalId':gid,'wholeMaterial':g,'mandatoryNativeAtomicClosure':sorted(closure),'wholeCoveredCurrentGoalPContexts':[{'wholeGoal':ag[c],'wholeOriginalCurrentP':pm[c]}for c in cover],'qualifiedWholeScienceReused':True,'newWholeScienceJudgment':False})
 for k,x in rows1.items():
  support=set(x['visibleAllAtomicIds']);visible=gid in x['actualTerminalIds'];expected=gid in x['expectedTerminalIds'];direct=set(g['requires']);missing=sorted(closure-support);missingcovered=sorted(set(cover)-support);tageligible=not set(g.get('tags',[])).intersection({'GK','LK'})or bool(set(g.get('tags',[])).intersection(x['scopeFilters']));compiledeligible=x['jurisdiction']in ac[gid]['compiledApplicability'].get('jurisdiction',[])
  if visible:assert not missing and not missingcovered and tageligible and compiledeligible,(k,gid,missing,missingcovered)
  assert not expected or visible,(k,gid,'expected endpoint missing')
  target=set(x['ordinaryTargetIds']);po=set(cover)&support-target
  matcontexts.append({'scopeKey':k,'goalId':gid,'actuallyVisibleWholeMaterial':visible,'actuallyExpectedNativeWholeMaterial':expected,'tagCourseEligible':tageligible,'actualCompiledJurisdictionEligible':compiledeligible,'directRequiresAvailable':direct<=support,'entireMandatoryClosureAvailable':not missing,'missingMandatoryNativeAtoms':missing,'missingCoveredNativeAtoms':missingcovered,'coveredOrdinaryTargetIDs':sorted(set(cover)&target),'coveredExistingPrerequisiteOnlyIDs':sorted(po),'decision':'KEEP_whole_bound_access'if visible else 'not_visible_no_new_access_approval'})
mat=wr('actual-1600-individual-whole-material-course-jurisdiction-closure-and-target-support-decisions.independent.json',{'wholeMaterialCount':25,'wholeScopeCount':64,'contexts':matcontexts,'wholeMaterialGoalPScienceReuseInputs':materialinputs,'actualVisibleBindings':sum(x['actuallyVisibleWholeMaterial']for x in matcontexts),'actualPracticeTargetsOverExistingPOnly':sum(bool(x['coveredExistingPrerequisiteOnlyIDs'])and x['actuallyVisibleWholeMaterial']for x in matcontexts),'noWholeSourceOrBodyScienceReapproval':True})
comparison=wr('actual-four-fresh-native-frames-combined470-roles-source-and-real-negative-decisions.independent.json',{'wholeScopeRoleRows':role,'all336CompiledOrdinaryRowsExact':True,'all10MemoryAndOneOrientationCompiledRowsExact':True,'wholeSourceRuleBeforeAfterAndBothNegativesExact':before['sourceRule'],'actualNativeMetrics':{'before':m0,'after':m1,'refdrop':mr,'supportdrop':ms},'actualNetRouteOccurrenceGain':494,'actualNetDistinctLocalRouteGoalGain':27,'actualTotalAppendedPracticeTargetRefs':470,'noSummingPackageRouteForecasts':True,'actualNegativeRefdrop':{'materialId':'ceec91b6-1ef7-5145-ade5-47f8db65cc86','jurisdiction':'DE-BE','course':'GK','expectedMissingScopes':[0,1],'routeOccurrences':[752,754]},'actualNegativeSupportdrop':{'ordinaryTargetChanged':False,'coverageOccurrences':[0,2],'mandatoryClosureOccurrences':[0,4]},'newSourceCurricularTargetClaims':0,'wholeM4Passed':False,'remainingLocalRouteOccurrences':752,'remainingDistinctLocalGoals':102,'strictNetGain':0})
tech=wr('actual-336-original-profile685-case-and43-config-SEM577-whole-preservation-technical-binding-review.json',{'P336WholeBytesExactlyUnchanged':{'before':info(pold),'after':info(pnew)},'currentWholeOriginalRecordIDs336':sorted(pm),'config43WholeDeltas':configs,'all551OldSEMDecisionRowsExact':True,'fourOldNavSEMSourceFPOnly':sorted(nav),'twentytwoNewForeignQualifiedPracticeKindsOnly':h['newQualifiedPracticeGoalIds'],'currentSemanticCounts':s1['counts'],'additionalImmutableTechnicalInputs':techsnaps,'newScientificClosures':0,'newHumanReviewApprovals':0})
# Verify all declared original inputs and snapshots; preserve failures honestly.
guards=json.load(open(O/'actual-before-input-guards-and-immutable-whole-snapshots.json'));assert all(sh(R/x['path'])==x['sha256']for x in guards['inputs']);assert all(sh(R/x['immutableOwnSnapshot']['path'])==x['immutableOwnSnapshot']['sha256']for x in guards['wholeSnapshots']);assert sh(R/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_WIRTSCHAFT.de.json')=='21d75911886b1a47620f311455b8577b09e07a87bb58b3cf33eac7f2a535a286';assert all((R/r['activePath']).read_bytes()==(R/r['before']['path']).read_bytes()for r in h['views'])
end=wr('actual-whole183-input-snapshots-active555-views-source-P-and-code-endguards.independent.json',{'original183WholeInputGuardsExact':True,'own183ImmutableSnapshotsExact':True,'additional88TechnicalInputsExact':True,'all35Active555ViewsExactBefore':True,'activeCanonical555ExactBefore':True,'activeWrites':0,'ownCandidateInputNoSymlinks':True})
# Store command bindings with factual successful exits checked by parent tools and raw readable reports.
commands=[]
for n in reports:
 raw=O/('actual-'+n+'-full-native-source-role-route-report.json');err=O/('actual-'+n+'-native.stderr.txt');assert err.read_bytes()==b'';commands.append({'name':n,'argv':['app/node_modules/.bin/tsx','native-combined-scope.ts',str(raw)],'cwd':'/tmp/skillpilot-economics-combined548-independent-xri79b2w','actualExit':0,'wholeRawReport':info(raw),'wholeStdout':info(O/('actual-'+n+'-native.stdout.txt')),'wholeStderr':info(err)})
cmd=wr('actual-four-fresh-native-command-exit-and-input-bindings.json',{'executedFreshNativeFrames':commands,'schemaAnd577SourceFPSuccess':info(O/'actual-current577-68-whole-view-schemas-canonical-schema-and577-native-sourceFPs.independent.json'),'privateMutationOnly':True})
shutil.copyfile(__file__,O/'actual-executed-independent-final-delta-matrix-and-seal-helper.raw.py')
manifest=wr('actual-final-independent-whole-input-and-fresh-native-evidence.manifest.json',{'artifacts':[info(p)for p in sorted(O.rglob('*'))if p.is_file()],'foreignAuthorFinalHandoff':info(H),'activeWrites':0,'sourcePrimaryFulltextsCopied':False})
final=wr('actual-final-current577-twentytwo-qualified470-combined-scope-nav-independent-KEEP.handoff.receipt.json',{'decision':'KEEP_BOUNDED_COMBINED_SCOPE_NAV_FUSION_OF_THREE_ACTUALLY_FOREIGN_QUALIFIED_PACKAGES','reviewer':'/root/economics_merge_audit','independentFromCombinedScopeAuthor':'/root','wholeForeignAuthorFinalHandoff':info(H),'wholeCurrent555':h['canonicalBefore'],'wholeInert577':h['canonicalCandidate'],'foreignWholeScienceReceiptsExactlyReused':h['foreignWholeScienceReceipts'],'foreignIndividualScopeReceiptsExactlyReused':h['foreignScopeReceipts'],'ownActualFourFreshNativeFrames':cmd,'ownWhole64RoleSourceAndNegativeDecisions':comparison,'own1600IndividualWholeCourseClosureDecisions':mat,'ownWhole336P43SEMTechnicalGuards':tech,'ownWholeActiveEndguards':end,'ownPortableManifest':manifest,'wholeNewPracticeBodies':22,'actualNewExplicitPracticeTargetRefs':470,'wholeViews':35,'newCrossStageViewSchemasValidated':68,'wholeChangedNavigationNodes':4,'all551OtherOldWholeGoalObjectsExact':True,'all336WholeOrdinaryGoalContractsAndP685Exact':True,'all64OrdinarySupportMemoryOrientation6974Exact':True,'wholeSource16_2134AtomicAnd208PartialInputsUnchanged':True,'all577NativeSemanticSourceFPsExact':True,'actualCompiler577Errors':0,'actualCompiler577Warnings':0,'actualMissingExpectedMaterialScopes':[6,0],'actualMissingLocalRouteOccurrences':[1246,752],'actualMissingDistinctLocalGoals':[129,102],'actualNetRouteOccurrenceGain':494,'actualNetDistinctLocalGoalGain':27,'actualNewCountrySourceClaims':0,'newOrdinaryTargetsOrPrerequisiteOnlyFoundationRefs':0,'strictNetGain':0,'newWholeScienceReviewOrHumanApproval':False,'wholeM4':False,'remaining':{'localRouteOccurrences':752,'distinctLocalGoalIDs':102},'historicalFailedSupportDropPreflight':'Direct-root assumption failed before mutation/run; actual nested support entry used for successful genuine native negative.','historicalHelperCopyCwdError':'Initial helper copy targeted nonexistent private artifact directory; production/native run succeeded and helper copied separately to own review folder.','activeWrites':0,'privateCAPCurrently577':'Only independent candidate inputs; shared active repository remains555.'})
print(json.dumps({'final':final,'route':[1246,752],'distinct':[129,102],'newRefs':470,'visibleMaterialBindings':sum(x['actuallyVisibleWholeMaterial']for x in matcontexts),'POnlyBindings':sum(bool(x['coveredExistingPrerequisiteOnlyIDs'])and x['actuallyVisibleWholeMaterial']for x in matcontexts),'source':'exact','activeWrites':0},indent=2))
