import {readFileSync,writeFileSync} from 'node:fs'
import {dirname,resolve,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
import assert from 'node:assert/strict'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import {validatePositiveGoalEvidenceRecordSemantics} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel'
import {validateGoalDescriptionReviewCampaignResultDirectories} from '../../../../../../../app/scripts/validateGoalDescriptionReviewCampaignResults'
import {fingerprintSemanticKindSourceGoal} from '../../../../../../../app/scripts/goalBookModel'
const root=resolve('.'),own=dirname(fileURLToPath(import.meta.url)),author=resolve(dirname(own),'chemie-q3-whole-twenty-raster-native-remediation-technical-20261008-v2'),read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),hash=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex'),bind=(p:string)=>({path:relative(root,p),sha256:hash(p),bytes:readFileSync(p).length})
const first=resolve(own,'two-current-whole-D-P-V-source.independent-b.first.freeze.json');assert.equal(hash(first),'b66f52b1b39543b8fe99f80f6debdc1a44c9a823b0c8524b4e234cec7bf66d78');for(const x of read(first).files){assert.equal(hash(resolve(root,x.path)),x.sha256);assert.equal(readFileSync(resolve(root,x.path)).length,x.bytes)}
const entry=read(resolve(author,'neutral-final-two-corrosion-current480-378-raster-native-author.entry.json')),q=resolve(root,entry.roundB),result=await validateGoalDescriptionReviewCampaignResultDirectories({bundle:read(resolve(q,'review-bundle-manifest.json')),input:read(resolve(q,'description-review-input.json')),campaign:read(resolve(q,'description-review-campaign.json')),batchesDirectory:resolve(q,'batches'),resultsDirectory:resolve(own,'round-b/results')});assert.deepEqual(result.errors,[]);assert.equal(result.records.length,2);assert.deepEqual(result.records.map((r:any)=>r.goalId),entry.finalNativeGoalIds);assert.ok(result.records.every((r:any)=>r.decision==='keep'&&r.recordStatus==='candidate'&&r.reviewAuthority==='ai_candidate'))
writeFileSync(resolve(own,'D2.actual-current-own-native-campaign.independent-b.receipt.json'),JSON.stringify({schemaVersion:1,checkedAt:new Date().toISOString(),nativeApi:'validateGoalDescriptionReviewCampaignResultDirectories',actualNativeBatchSize:2,actualNativeGoalCount:2,ownCompletedRuns:1,ownActualRecords:2,KEEP:2,errors:result.errors,authorCurrentTwoSubsetContexts:result.records.map((r:any)=>({goalId:r.goalId,goalFingerprint:r.goalFingerprint,pageFingerprint:r.pageFingerprint})),noFalseTwentyConvenienceWrapper:true,ownFirstSeal:bind(first),currentPeerFinalRead:false,activeWrites:0,humanApproval:false,humanTrial:false},null,2)+'\n',{flag:'wx'})
console.log('Actual own native D2 campaign API:2 KEEP ai_candidate records,real native batch2,0 errors; no fake20 wrapper.')
const cfg=read(resolve(author,'positive/P2.actual-current-raster.inactive.config.json')),canon=read(resolve(root,cfg.landscapePath)),kinds=read(resolve(root,cfg.semanticKindLedgerPath)).decisions,rows=readFileSync(resolve(root,cfg.reviewPath),'utf8').trim().split('\n').map(x=>JSON.parse(x)),mapping=read(resolve(root,entry.actualTwoNativePagesAndFourWidths)).captures,ajv=new Ajv2020({allErrors:true,strict:true});addFormats(ajv);const validate=ajv.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json'))),checked:any[]=[];assert.equal(rows.length,2)
for(const row of rows){const goal=canon.goals.find((g:any)=>g.id===row.goalId),kind=kinds.find((k:any)=>k.goalId===row.goalId),img=mapping.find((x:any)=>x.goalId===row.goalId);assert.equal(kind.semanticKind,'curricularAtomic');assert.equal(kind.sourceFingerprint,fingerprintSemanticKindSourceGoal(goal));const link=goal.resourceLinks.filter((l:any)=>l.type==='goal-visualization');assert.equal(link.length,1);const actual='sha256:'+hash(resolve(root,img.sourcePath));assert.equal(actual,'sha256:'+img.sourceSha256);assert.equal(hash(resolve(root,img.actualOriginalRaster)),img.sourceSha256);const digests={[link[0].url]:actual};assert.equal(row.reviewCriteriaFingerprint,'sha256:'+hash(resolve(root,cfg.reviewCriteriaPath)));assert.ok(validate(row),ajv.errorsText(validate.errors));assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(row,goal,digests,'curricularAtomic'),[]);assert.equal(row.status,'needs_human_review');assert.equal(row.reviewAuthority,'ai_candidate');assert.equal(row.evidenceLevel,'E1');assert.equal(row.maximumClaimScope,'G1');checked.push({goalId:row.goalId,semanticKind:kind.semanticKind,goalFingerprint:row.goalFingerprint,profileFingerprint:row.profileFingerprint,reviewInputFingerprint:row.reviewInputFingerprint,actualSelectedRaster:bind(resolve(root,img.sourcePath)),actualOriginalRaster:bind(resolve(root,img.actualOriginalRaster)),actualResourceDigests:digests,schemaErrors:0,semanticErrors:0,status:row.status,reviewAuthority:row.reviewAuthority,evidenceLevel:row.evidenceLevel,maximumClaimScope:row.maximumClaimScope})}
writeFileSync(resolve(own,'P2.actual-current-originalJPEG-correctedPNG-closed-schema-semantics.independent-b.receipt.json'),JSON.stringify({schemaVersion:1,checkedAt:new Date().toISOString(),nativeApi:'validatePositiveGoalEvidenceRecordSemantics',configuredGoals:2,checked,schemaErrors:0,semanticErrors:0,ownWholeScienceFirstAndTargetedP16CorrectionGenuine:true,actualPNGJPEGAnd360680AndWholePagesReviewed:true,ordinaryCorrectedPNGCLI:'pending actual installation; actual candidate asset digest map used in unmodified native semanticsAPI',currentPeerFinalRead:false,activeWrites:0,humanApproval:false,humanTrial:false},null,2)+'\n',{flag:'wx'})
console.log('Actual own closed-v2 P2 schema/semantics API:originalJPEG15 + correctedPNG16,0errors,E1/G1 AIcandidate needs_human_review. Standard correctedPNG CLI pending install.')
