import json,pathlib,hashlib
from PIL import Image
BASE=pathlib.Path(__file__).resolve().parent.relative_to(pathlib.Path.cwd().resolve())
M=json.loads((BASE/'23-goal-derived-original-prompts.author-input.json').read_text())['entries']
def binding(path):
 p=pathlib.Path(path); b=p.read_bytes();return {'path':str(p),'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)}
def register(n,description,alt,reconstruction,observations,version=1):
 e=M[n-1];d=BASE/(str(n).zfill(2)+'-'+e['goalId']); asset=d/('candidate-v'+str(version)+'.png')
 reconstructionPath=d/('reconstruction-v'+str(version)+'.actual-view.de.md')
 reconstructionPath.write_text('# Rekonstruktion aus dem tatsächlich betrachteten PNG\n\n'+reconstruction+'\n\nDieser Prompt wurde aus der tatsächlichen Originalansicht und den Ansichten mit 360 und 680 Pixeln Breite abgeleitet. Er ist kein ursprünglicher Erzeugungsprompt und wurde nicht zur Erzeugung dieses PNG verwendet.\n')
 provenancePath=d/('actual-generated-file.local-provenance'+('.v'+str(version) if version>1 else '')+'.json')
 if provenancePath.exists():provenance=json.loads(provenancePath.read_text())
 else:provenance=json.loads((d/'generation-and-actual-view.author.receipt.json').read_text())['generation']
 resource={'type':'goal-visualization','resourceType':'image','role':'primary','skillpilotId':e['goalId'],'title':'Visualisierung: '+e['goalTitle'],'url':'/assets/goal-visualizations/biologie/'+e['goalId']+'/'+e['goalId']+'.png','provider':'built-in ChatGPT/Codex image_gen','description':description,'altText':alt,'lang':'de','license':'CC-BY-4.0','reviewStatus':'pilot'}
 entry={'ordinal':n,'goalId':e['goalId'],'wholeCurrentGoal':e['wholeGoal'],'path':str(asset),'assetPath':str(asset),'assetBinding':binding(asset),'sha256':binding(asset)['sha256'],'bytes':asset.stat().st_size,'dimensions':list(Image.open(asset).size),'provider':'built-in ChatGPT/Codex image_gen','tool':'image_gen__imagegen','model':None,'modelDisclosure':'Integrated tool does not expose model identifier.','originalPromptPath':e['originalPromptPath'],'originalPromptBinding':binding(e['originalPromptPath']),'actualGenerationProvenance':provenance,'reconstructionPromptPath':str(reconstructionPath),'reconstructionPromptBinding':binding(reconstructionPath),'reconstructionRole':'actual-view-derived; not original generator prompt','descriptionDe':description,'altTextDe':alt,'resourceLinkCandidate':resource,'actualAuthorInspection':{'originalSeen':True,'width360Seen':True,'width680Seen':True,'observations':observations,'previews':[binding(d/('candidate-v'+str(version)+'.preview-'+str(w)+'.png')) for w in (360,680)],'authority':'author inspection only; independent visualization reviews pending'},'status':'ai_candidate','humanApproval':False,'independentReviews':[],'activeIntegration':False}
 if version>1:
  entry['selectedEditPromptBinding']=binding(d/('generation-v'+str(version)+'.targeted-edit.prompt.en.md'))
  entry['referenceOriginalImageBinding']=binding(d/'candidate-v1.png')
  entry['originalAttemptPreserved']=True
 (d/'neutral-selected-candidate.actual-author-binding.entry.json').write_text(json.dumps(entry,ensure_ascii=False,indent=2)+'\n')
 return entry
if __name__=='__main__':
 register(1,'Schematische Fehlverteilung des Chromosomenpaares 21 in der Meiose I. Nach der Meiose II entstehen für dieses Paar zwei Keimzellen mit zwei Kopien und zwei ohne Kopie; andere Chromosomen sind nicht dargestellt.','Eine Zelle mit einem roten und einem blauen replizierten Chromosom 21 teilt sich fehlerhaft. Beide X gelangen in eine Zelle. Zwei Endzellen enthalten je zwei Einzelchromosomen, zwei kein dargestelltes Chromosom 21.','Freundliche klare Comicgrafik im Querformat. Links eine Zelle mit genau zwei homologen replizierten X-Chromosomen, blau und rot, unter Chromosom 21. Eine Verzweigung Meiose I führt zu einer oberen Zelle mit beiden X und einer unteren ohne Chromosom 21. Oben steht Fehlverteilung. Unter Meiose II entstehen rechts genau vier Zellen: zwei oben mit jeweils einem roten und einem blauen Einzelchromosom, zwei unten ohne Chromosom 21. Große blaue Konturen, helle Flächen und wenige große Labels. Schematisch nur dieses Chromosomenpaar, keine vollständige 46-Chromosomen-Zelle, keine Krankheitsdiagnose.','Actual1672x940; meiosis-I nondisjunction and four endpoint counts coherent. Correct Meiose I/II labels; large cell motifs and labels visible at360/680. No concrete author defect identified.')
 register(2,'Chromosomenbefund, beobachtetes Merkmal und zusätzliche Gesundheitsbefunde werden getrennt betrachtet. Die gezeichneten Chromosomen sind schematisch und bilden kein Karyogramm; ein Merkmal allein begründet keine Krankheitsdiagnose.','Drei getrennte Felder zeigen schematische Chromosomen, zwei Personen mit beobachtbaren Merkmalen sowie Körperfunktionen und Zusatzbefunde. Ein gestrichelter Weg mit Fragezeichen verbindet die Ebenen und markiert den Bedarf weiterer Belege.','Querformat-Comic mit drei großen Feldern: blau Chromosomen mit einer Lupe und wenigen abstrakten X-Symbolen, gelb Merkmal mit zwei verschiedenen Jugendlichen und einer Beobachtungssprechblase, grün Gesundheit mit Herz, Körperfunktionen und Klemmbrett Zusatzbefunde. Ein gestrichelter blauer Weg mit großem Fragezeichen stellt nur eine Prüfbeziehung dar. Unten gut gesetzter eigener Satz: Chromosomenbefund, beobachtetes Merkmal und zusätzliche Gesundheitsbefunde sind getrennt zu betrachten. Nicht aus dem Gesicht eines Menschen eine Krankheit oder Chromosomenzahl ableiten. Die X-Sammlung ist ausdrücklich kein vollständiges Karyogramm.','Actual1672x941; three levels clearly separated, no deterministic disease arrow. Main headings and motifs readable360; bottom explanatory sentence requires closer reading but is not needed for the basic distinction. No concrete scientific error identified; generic chromosome icons treated as schematic.')
 register(3,'Schematische Strukturmodelle vergleichen doppelsträngige, antiparallele DNA und einzelsträngige RNA. D steht für Desoxyribose und R für Ribose; die Formen sind Symbole, keine vollständigen chemischen Strukturformeln.','Links zwei DNA-Rückgrate mit gegenläufigen Pfeilen und den Paaren A–T, G–C, T–A und C–G. Rechts ein einzelnes RNA-Rückgrat mit A, G, U und C. Zuckerbausteine tragen D beziehungsweise R.','Zwei große Vergleichsfelder DNA links und RNA rechts. Die DNA ist ein flaches Leitermodell mit zwei durchgehenden alternierenden Zucker-Phosphat-Strängen: Zucker als Pentagonsymbole D, Phosphat als Kreise, daran Basensymbole. Vier korrekte komplementäre Paare A–T, G–C, T–A, C–G mit zwei beziehungsweise drei gestrichelten Verbindungen. Außen entgegengesetzte Richtungspfeile. RNA als einzelner durchgehender Zucker-Phosphat-Strang mit R-Pentagonsymbolen und den Basen A, G, U, C. Alle Buchstaben groß. Keine chemisch vollständigen Ringformeln behaupten, keine Parallelstränge oder falschen Basenpaare.','Actual1672x941; all four complementary DNA pairs correct, A–T two/G–C three dashed links, opposing arrows and continuous backbones. RNA hasU and noT. D/R symbolic sugar distinction; abstract base shapes are not claimed as chemical structures. Visible at360/680.')
 register(4,'Zwei mögliche codierende DNA-Sequenzfragmente ergeben über die mRNA dieselbe kurze Aminosäurefolge Met–Glu. Die Rückrichtung liefert mehrere Möglichkeiten; die schematischen Symbole zeigen keinen vollständigen funktionellen Proteinbau.','ATG GAA und ATG GAG führen zu AUG GAA beziehungsweise AUG GAG. Beide mRNA-Fragmente ergeben Met–Glu. Gelbe Pfeile führen von diesem Fragment zu beiden möglichen DNA-Sequenzen zurück.','Klare Comicgrafik mit zwei Zeilen: DNA-Karten ATG GAA und ATG GAG links, mRNA-Karten AUG GAA und AUG GAG in der Mitte. Blaue Pfeile verbinden jeweils korrekt die DNA mit der passenden mRNA. Beide mRNA-Karten führen mit grünen Pfeilen zu einer einzigen Karte Met–Glu rechts, mit zwei abstrakten Aminosäurekugeln. Zwei gelbe Rückpfeile führen zu beiden DNA-Karten. Großes Label Mehrere Möglichkeiten. Eine lernende Person denkt über die Sequenzen nach; das offene Notizbuch liegt ihr zugewandt auf dem Tisch. DNA/RNA-Wellen nur schematisch, keine vollständige Moleküldetailzeichnung oder vollständiges Enzym behaupten.','Actual1672x941; all four sequence fragments andMet–Glu correct; both GAA/GAG representGlu and reverse arrows branch toward two DNA possibilities. Peptide only short fragment, no functional enzyme claim. Actor notebook faces actor. Strings visible360/680.')
 print('Registered4 actually viewed candidates; no independent approvals.')
