// SPDX-License-Identifier: Apache-2.0
// Factual inactive integration of genuine sealed independent reviews. No new science run.
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync,existsSync,copyFileSync,symlinkSync} from 'node:fs'
import {dirname,resolve,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import {buildGoalBookModel,fingerprintSemanticKindSourceGoal,loadGoalBookBuildInputs,stableGoalBookJson} from '../../../../../../../app/scripts/goalBookModel'
import {buildGoalBookOriginalSources} from '../../../../../../../app/scripts/goalBookOriginalSources'
import {validatePositiveGoalEvidenceRecordSemantics} from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel'
const root=resolve('.'),own=dirname(fileURLToPath(import.meta.url)),base=resolve(own,'..'),author=resolve(base,'biologie-ecology20b-current391-author-v1'),srcA=resolve(base,'biologie-ecology20b-twelve-current391-independent-a-20261007-v1'),srcB=resolve(base,'biologie-ecology20b-current391-independent-b-20261007-v1')
const sha=(b:Buffer|string)=>'sha256:'+createHash('sha256').update(b).digest('hex'),declared=new Map<string,any>()
const bind=(p:string)=>{const b=readFileSync(p);return {path:relative(root,p),sha256:sha(b),bytes:b.length}}
const bytes=(p:string)=>{declared.set(p,bind(p));return readFileSync(p)},read=(p:string)=>JSON.parse(bytes(p).toString('utf8'))
const write=(p:string,v:any)=>{mkdirSync(dirname(p),{recursive:true});const b=Buffer.isBuffer(v)||typeof v==='string'?v:JSON.stringify(v,null,2)+'\n';if(existsSync(p)){assert.equal(sha(readFileSync(p)),sha(b),'Existing prepared artifact cannot silently change');return}writeFileSync(p,b,{flag:'wx'})}
const verify=(dir:string,name:string,expected:string)=>{const p=resolve(dir,name);assert.equal(bind(p).sha256,'sha256:'+expected);const seal=read(p);for(const e of seal.frozenFiles){const q=e.path.startsWith('curricula/')||e.path.startsWith('app/')?resolve(root,e.path):resolve(dir,e.path);assert.equal(bind(q).sha256.replace('sha256:',''),e.sha256.replace('sha256:',''));if(e.bytes!==undefined)assert.equal(bind(q).bytes,e.bytes)}return {seal:bind(p),verifiedPayloads:seal.frozenFiles.length}}
const seals={author:verify(author,'author.final-twelve-current391-native-inputs.freeze.json','d9f4ed46c31d2551d891267c7702640131e5a73c008df238507808f96880f71f'),A:verify(srcA,'independent-a.final.freeze.json','acb4bba78644325903feb890f867ff5a85e679e56c2090ce240e8fce3b4c1f7a'),B:verify(srcB,'independent-b.final-current-twelve-native-D-P-V.freeze.json','42db65c35415255148ce2f4c3234ade6a93657d408c459f6b8a9a7444d980d0c')}
const plan=read(resolve(own,'candidate/twelve-exact-resource-link-patches.guarded.json'))
for(const key of ['canonical','kinds','qa'])assert.equal(sha(bytes(resolve(root,plan.beforeBindings[key].path))),plan.beforeBindings[key].sha256,'Active '+key+' moved: explicit rebase required')
const canonicalPath=resolve(own,'candidate/canonical.future-active.json'),landscape=read(canonicalPath),before=read(resolve(own,'before/canonical.json')),ids=plan.selectedGoalIds as string[],selected=new Set(ids),goalBy=new Map<string,any>(landscape.goals.map((g:any)=>[g.id,g]))
assert.equal(landscape.goals.length,474);assert.equal(ids.length,12)
const sourceImageManifest=resolve(root,'curricula/DE/Gymnasium/quality/goal-visualization-review/biologie-ecology20b-current391-image-author-root-20261007-v1/selected-twelve-raster-inputs.author-handoff.frozen.json');assert.equal(bind(sourceImageManifest).sha256,'sha256:e7bbca6881b7340def7141ed3e2d0ae3e6673a264a179d3f08ccf720cab6537f')
const images=read(sourceImageManifest).images,imageBy=new Map<string,any>(images.map((i:any)=>[i.goalId,i])),aV=read(resolve(srcA,'V12.actual-raster-widths-pages-independent-a.final.json')),bV=read(resolve(srcB,'native-final-followup/V12.actual-raster-independent-b.approvals.json'))
assert.equal(aV.blockingVisualFindings,0);const aVby=new Map<string,any>(aV.records.map((r:any)=>[r.goalId,r])),bVby=new Map<string,any>(bV.records.map((r:any)=>[r.goalId,r]));assert.equal(aVby.size,12);assert.equal(bVby.size,12)
const futureQa=read(resolve(own,'before/qa.json')),qaBy=new Map<string,any>(futureQa.records.map((r:any)=>[r.goalId,r])),assetLineage:any[]=[]
for(const id of ids){const img=imageBy.get(id),a=aVby.get(id),b=bVby.get(id),g=goalBy.get(id),expected='sha256:'+img.sha256.replace('sha256:','');assert.equal(bind(resolve(root,img.path)).sha256,expected)
 assert.equal(a.scientificVisualVerdict,'PASS');assert.equal(a.aiApproved,'yes');assert.equal(a.aiApprovedAssetSha256,expected);assert.equal(a.assetSha256,expected);assert.equal(a.humanApproved,false)
 assert.equal(b.aiApproved,'yes');assert.equal(b.aiApprovedAssetSha256,expected);assert.equal(b.assetSha256,expected);assert.equal(b.humanApproved,'no');assert.equal(b.description,g.description);assert.equal(b.title,g.title)
 const q=qaBy.get(id);assert.equal(q.visualizationState,'missing');assert.equal(q.humanApproved,'no');assert.equal(q.humanIssueIdentified,'no')
 const row={...q,...b,aiReviewedAt:[a.aiReviewedAt,b.aiReviewedAt].sort().at(-1),aiReviewer:'Two genuine independent machine reviewers A and B, technically synthesized from exact sealed asset/page judgments; no human approval',aiNotes:'A: '+a.aiNotes+' B: '+b.aiNotes+' Exact science seals A: '+seals.A.seal.path+'; B: '+seals.B.seal.path+'; no human approval or trial.'};Object.assign(q,row)
 const dst=resolve(own,'selected-images',id+'.png');mkdirSync(dirname(dst),{recursive:true});if(!existsSync(dst))copyFileSync(resolve(root,img.path),dst);assert.equal(bind(dst).sha256,expected)
 const alias=resolve(own,b.imageUrl.replace(/^\//u,''));mkdirSync(dirname(alias),{recursive:true});if(!existsSync(alias))symlinkSync(relative(dirname(alias),dst),alias)
 assetLineage.push({goalId:id,sourceRaster:bind(resolve(root,img.path)),selectedRaster:bind(dst),originalPrompt:bind(resolve(root,img.promptPath)),originalGenerationProvenance:bind(resolve(root,img.provenancePath)),targetPublicPath:b.publicAssetPath,targetCanonicalPath:b.canonicalAssetPath,altDe:img.altDe,altEn:img.altEn,sourceIndependentAAssetRow:a,sourceIndependentBAssetRow:b,actualBothIndependentViews:['full','360','680','native-PDF-page'],machineApprovalOnly:true})}
for(const r of read(resolve(own,'before/qa.json')).records)if(!selected.has(r.goalId))assert.deepEqual(qaBy.get(r.goalId),r)
write(resolve(own,'candidate/visualization-qa.future-active.json'),futureQa)
const inertQa=structuredClone(futureQa);for(const r of inertQa.records)if(selected.has(r.goalId)){r.publicAssetPath=relative(root,resolve(own,'selected-images',r.goalId+'.png'));r.canonicalAssetPath=r.publicAssetPath}write(resolve(own,'candidate/visualization-qa.inactive-native.json'),inertQa)
write(resolve(own,'candidate/exact-selected-asset-provenance-and-paired-machine-approval.technical.json'),{seals,sourceManifest:bind(sourceImageManifest),rows:assetLineage,unrelatedQaRecordsExact:true,noExistingAssetReplaced:true,humanApproval:false,humanTrial:false,activeWrites:0})
const kinds=read(resolve(own,'before/kinds.json')),inertKinds=read(resolve(own,'candidate/semantic-kinds.inactive-native.json'));assert.equal(kinds.counts.curricularAtomic,391);assert.equal(kinds.counts.total,474)
for(const d of kinds.decisions)assert.equal(fingerprintSemanticKindSourceGoal(goalBy.get(d.goalId)),d.sourceFingerprint,'All classifications must stay current without adjusting any row')
const activeFullCfg=resolve(base,'biologie-ecology20-current391-reviewed-integration-preparation-technical-v1/native-full391.future-active.config.json'),actual=await loadGoalBookBuildInputs(activeFullCfg);assert.equal(actual.model.pages.length,391)
const inertCfg={...actual.config,landscapePath:relative(root,canonicalPath),semanticKindLedgerPath:relative(root,resolve(own,'candidate/semantic-kinds.inactive-native.json')),goalVisualizationQaPath:relative(root,resolve(own,'candidate/visualization-qa.inactive-native.json')),evidenceReviewPaths:[],outputPath:relative(root,resolve(own,'native-full391.current474-inactive.book-model.json'))},futureCfg={...actual.config,evidenceReviewPaths:[],outputPath:relative(root,resolve(own,'native-full391.future-active.pure.book-model.json'))}
const manifest=read(resolve(root,inertCfg.compositionViewManifestPath)),digests:Record<string,string>={};for(const r of inertQa.records)if(r.visualizationState==='available')digests[r.imageUrl]=sha(bytes(resolve(root,r.publicAssetPath)))
const common={landscape,compositionViewManifest:manifest,compositionViewSources:manifest.sourcePaths.map((p:string)=>({path:p,view:read(resolve(root,p))})),navigationView:read(resolve(root,manifest.navigationViewPath)),durationModelPolicy:read(resolve(root,manifest.durationModelPolicyPath)),goalVisualizationAssetDigests:digests,evidenceReviewSources:[]}
const model=buildGoalBookModel({...common,semanticKindLedger:inertKinds,goalVisualizationQa:inertQa,config:inertCfg}as any),futureModel=buildGoalBookModel({...common,semanticKindLedger:kinds,goalVisualizationQa:futureQa,config:futureCfg}as any)
assert.equal(model.pages.length,391);assert.equal(futureModel.pages.length,391);const oldPages=new Map(actual.model.pages.map(p=>[p.goalId,p])),futurePages=new Map(futureModel.pages.map(p=>[p.goalId,p])),authorFull=read(resolve(author,'native-raster-candidate/full391.book-model.json')),authorPages=new Map<string,any>(authorFull.pages.map((p:any)=>[p.goalId,p]))
const changed=model.pages.filter(p=>p.pageFingerprint!==oldPages.get(p.goalId)?.pageFingerprint);assert.deepEqual(new Set(changed.map(p=>p.goalId)),selected)
const compatibility:any[]=[]
for(const p of model.pages){assert.equal(p.pageFingerprint,futurePages.get(p.goalId)!.pageFingerprint)
 if(!selected.has(p.goalId))assert.equal(p.pageFingerprint,oldPages.get(p.goalId)?.pageFingerprint)
 else{const old=authorPages.get(p.goalId),normalized=structuredClone(p);delete normalized.pageFingerprint;normalized.visualization!.qaStatus=old.visualization.qaStatus;const comparison=structuredClone(old);delete comparison.pageFingerprint;assert.equal(stableGoalBookJson(normalized),stableGoalBookJson(comparison),'Every current full391 target field except exact approved QA-state metadata must match the author whole frame')
 compatibility.push({goalId:p.goalId,authorWholeFramePageFingerprint:old.pageFingerprint,futureWholeFramePageFingerprint:p.pageFingerprint,allScientificGoalContextSourceScopeFieldsExact:true,actualAssetDigestExact:old.visualization.originalDigest,actualChangedCurrentWholePageFields:old.visualization.qaStatus===p.visualization!.qaStatus?[]:['visualization.qaStatus','derived pageFingerprint'],beforeQaStatus:old.visualization.qaStatus,afterQaStatus:p.visualization!.qaStatus,noBlindHistoricalPageHashSubstitution:true,originalNativeSubset12ReviewFrameRetained:true})}}
const mappingPaths=read(resolve(root,'app/scripts/config/goal-books/de-gym-biology-national-atlas.inputs.json')).mappingPaths,oldSource=buildGoalBookOriginalSources(actual.model,root,mappingPaths),newSource=buildGoalBookOriginalSources(futureModel,root,mappingPaths);for(const k of Object.keys(oldSource).filter(k=>k!=='bookDigest'))assert.deepEqual((newSource as any)[k],(oldSource as any)[k])
write(resolve(own,'native-full391.current474-inactive.config.json'),inertCfg);write(resolve(own,'native-full391.current474-inactive.book-model.json'),model);write(resolve(own,'native-full391.future-active.config.json'),futureCfg);write(resolve(own,'native-full391.future-active.pure.book-model.json'),futureModel)
write(resolve(own,'checks/full391-exact-unaffected379-and-twenty-approved-state-only.technical.json'),{currentBaseCanonical:plan.beforeBindings.canonical,preparedFutureCanonical:bind(canonicalPath),sourceCanonicalDigestMustUsePreparedFutureBytes:bind(canonicalPath).sha256,all474ClassificationsExact:true,total391:true,other379PagesExactCurrentActive474:true,new11675TerminalPageRetainedExact:true,allPrimarySourceDocumentsClausesScopesAndTitlesExact:true,targetWholeFrameCompatibility:compatibility,noFull391PDFRendered:true,activeWrites:0})
const readRows=(p:string)=>bytes(p).toString('utf8').trim().split('\n').map(s=>JSON.parse(s)),pa=readRows(resolve(srcA,'P12.actual-raster-independent-a.review.jsonl')),pbBy=new Map(readRows(resolve(srcB,'native-final-followup/P12.current-actual-raster.independent-b.review.jsonl')).map(r=>[r.goalId,r])),authorPBy=new Map(readRows(resolve(author,'source-locator-precision-v3/P12.actual-raster-source-roles-author-v3.review.jsonl')).map(r=>[r.goalId,r]))
assert.equal(pa.length,12);assert.equal(pbBy.size,12);const ajv=new Ajv2020({strict:false,allErrors:true});addFormats(ajv);const schema=ajv.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json'))),cfgSchema=ajv.compile(read(resolve(root,'contracts/goal-evidence/v2/goal-evidence-review-config.schema.json')))
const reviewId='biologie-ecology20b-twelve-current391-paired-reviewed-current-binding-technical-20261007-v1',records:any[]=[],Plineage:any[]=[]
for(const a of pa){const b=pbBy.get(a.goalId),source=authorPBy.get(a.goalId),g=goalBy.get(a.goalId),resources=Object.fromEntries(g.resourceLinks.filter((l:any)=>l.type==='goal-visualization').map((l:any)=>[l.url,digests[l.url]]));assert.ok(b);assert.ok(source)
 for(const k of ['profile','profileFingerprint','goalFingerprint','reviewInputFingerprint','reviewCriteriaFingerprint','evidenceLevel','maximumClaimScope','status','reviewAuthority']){assert.deepEqual(a[k],b[k]);assert.deepEqual(a[k],source[k])}
 assert.equal(a.status,'needs_human_review');assert.equal(a.reviewAuthority,'ai_candidate');assert.equal(a.evidenceLevel,'E1');assert.equal(a.maximumClaimScope,'G1')
 assert.deepEqual(a.dissent.slice(1),b.dissent.slice(1));assert.deepEqual(a.dissent.slice(1),source.dissent.slice(1));const dissent=['Die tatsächlichen zwei unabhängigen aktuellen D/P/V-Maschinenprüfungen sind versiegelt. E1/G1-Autorkandidat; keine reale Lernendenleistung, kein E2, keine menschliche Freigabe oder Erprobung. Öffentliche Dateibindungen und zentraler strenger Abschluss werden nach Integration getrennt geprüft.',...source.dissent.slice(1)]
 const record={...source,reviewId,reviewedAt:new Date(Math.max(Date.parse(a.reviewedAt),Date.parse(b.reviewedAt))+1000).toISOString(),reviewer:'Codex technical integrator of actual sealed independent A/B whole twelve profiles and exact actual approved raster resources; no new reviewer or run',reason:'Exact independently reviewed whole bilingual profile body and two complete bilingual model cases retained. Eight SOURCEHOLD targets are excluded and remain open. Technical current-resource binding on active474 prospective goal bytes; source A: '+seals.A.seal.path+'; source B: '+seals.B.seal.path+'. Only obsolete metadata stating current reviews are pending was updated. E1/G1 AI candidate, no real learner performance, human approval, trial, or whole-primary-source closure.',reviewRunIds:[],dissent}
 assert.ok(schema(record),ajv.errorsText(schema.errors));assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(record,g,resources,'curricularAtomic'),[]);records.push(record)
 Plineage.push({goalId:a.goalId,sourceAReviewId:a.reviewId,sourceAReviewedAt:a.reviewedAt,sourceBReviewId:b.reviewId,sourceBReviewedAt:b.reviewedAt,profileBodyExactBothAndAuthor:true,profileFingerprint:a.profileFingerprint,reviewInputFingerprint:a.reviewInputFingerprint,sourceAndPerformanceDissentLimitsExact:a.dissent.slice(1),onlyMetadataStatusSentenceChanged:true,noScientificRunInvented:true,resources})}
write(resolve(own,'positive/current12.records.jsonl'),records.map(r=>JSON.stringify(r)).join('\n')+'\n')
const positiveCfg={...read(resolve(author,'P20.current-text-preimage.author.config.json')),reviewId,landscapePath:plan.beforeBindings.canonical.path,semanticKindLedgerPath:plan.beforeBindings.kinds.path,reviewPath:relative(root,resolve(own,'positive/current12.records.jsonl')),reviewRunManifestPaths:[],scope:{label:'Current exact whole Ecology20b twelve positive profiles from genuine paired independent science, E1/G1 machine candidates, no learner/Human evidence',goalIds:ids}};assert.ok(cfgSchema(positiveCfg),ajv.errorsText(cfgSchema.errors));write(resolve(own,'positive/current12.future-active.config.json'),positiveCfg)
write(resolve(own,'positive/current12.inactive-native.config.json'),{...positiveCfg,landscapePath:inertCfg.landscapePath,semanticKindLedgerPath:inertCfg.semanticKindLedgerPath})
write(resolve(own,'positive/twenty-paired-original-science-and-current-binding-lineage.technical.json'),{seals,rows:Plineage,nativePerRecordClosedSchemaPASS:true,nativePerRecordSemanticChecksPASS:true,scientificBodiesChanged:0,needsHumanReview:12,E1G1:true,actualPublicPCLIStillPendingRootIntegration:true,activeWrites:0})
write(resolve(own,'checks/ready-native-current12-profile-visual-and-whole391-bindings.technical.json'),{seals,selectedActualAssets:12,nativeP12SchemaAndSemanticsPASS:true,nativePureCurrent391PASS:true,exactOther379Pages:true,noActualAssetBytesChangedSincePairedIndependentReviews:true,currentAM12ExactOriginalRowsAndNativeChecks:'PASS',newScientificJudgmentsByTechnicalAgent:false,humanApproval:false,humanTrial:false,newStrictClosureClaim:0,potentialPackageGainAfterRootIntegrationAndCentralCheck:12,activeWrites:0})
write(resolve(own,'checks/binding-preparation-declared-inputs.json'),{files:[...declared.values()]})
console.log(JSON.stringify({futureCanonicalDigest:bind(canonicalPath).sha256,nativeFull391:'PASS',exactUnchangedPages:379,retained11675:'PASS',nativeP12SchemaAndSemantics:'PASS',pairedActualV12:'PASS',activeWrites:0,strictGainClaimed:0}))
