import pathlib,json,hashlib,datetime,collections,subprocess
q=pathlib.Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-08');a=q/'biologie-stoffwechsel-first-three-regional-source-remediation-author-20261008-v1';o=q/'biologie-stoffwechsel-first-three-source-roles-independent-b-20261008-v1';seal=o/'three-source-roles-b.first-verdict.seal.json';assert not seal.exists()
load=lambda p:json.loads(pathlib.Path(p).read_text());rec=lambda p:{'path':str(p),'sha256':'sha256:'+hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest(),'bytes':pathlib.Path(p).stat().st_size}
e=load(a/'neutral-three-regional-source-role-remediation.author.corrected-count.entry.json');roles=load(e['sourceRoles']['path']);checks=load(o/'three-source-b.actual-primary-whole-duty-retention-and-portability.check.json');assert checks['allPassed']
# Manually authored original-based explanations; no current A source judgment has been read.
reasons={
1:'The complete BB3.2 table names significance of photosynthesis, ecological matter/energy interactions, trophic energy flow and cycles. It does not locate light-reaction chemistry, Calvin stages or ATP/NADPH coupling. Accept only the declared basic/significance contribution, retaining all seven whole partner rows.',
2:'BB3.3 explicitly states the principle of cellular energy conversion within whole human nutrition, transport and respiration. The normalized row adds aerobic/anaerobic wording; the actual page does not mandate the three molecular stages or that comparison. Accept only principle context, retaining all three partners and the complete human duties.',
3:'The BE original is byte-identical to BB, and its3.2 whole page has the same ecological basic/significance scope. Native lower-secondary scope is preserved; advanced1 is not independently mandated by this page. All original partners remain.',
4:'The BE3.3 original principle-of-energy-conversion wording is identical to BB. A normalized extended title/description cannot create a glycolysis/cycle/chain quota. Accept the bounded principle contribution without approving the full three-partner union.',
5:'Both actual BY GA and EA3.1 have an explicit three-part operator chain: explain factors, explain rate change, judge consequences for wild and crop plants. Current1 and its unchanged P1 demonstrate the first causal contribution; they do not provide the original plant-consequence judgment. Retain the genuine whole-source HOLD.',
6:'Both actual BY GA and EA3.1 require separation of pigments in leaf extract by chromatography. Current3 describes an antenna and its other original partner demonstrates light dependence; neither names this separation procedure. Accept thematic pigment context only. EA explicitly names LHC in the separate anatomical/functional content; this does not convert the chromatography duty into theoretical antenna competence or mandate LHC in GA.',
7:'Both BY courses3.3 require overview of aerobic carbon breakdown/carrier regeneration and comparison with photosynthetic buildup to derive common metabolic principles. Current2 and unchanged P2 cover route coupling, carbon flow and terminal oxygen, while the original comparison/derivation remains a separate observable duty. Retain the whole-source comparison HOLD.',
8:'Complete HE45 places abiotically limited rate, primary-reaction schema, Calvin fixation/reduction/regeneration and reaction coupling under grundlegendes Niveau GK+LK. These explicitly support the whole current explanatory1 as a bounded authored operationalization. The normalized Q3.2.1 index is not an official literal bullet and other original practical/chromatography/leaf duties are not discharged.',
9:'HE45 GK+LK explicitly names material/energy balance of glycolysis, oxidative decarboxylation, tricarboxylic cycle and respiratory chain. The schematic whole current2 has this explicit bounded upper-stage basis; its title does not erase oxidative decarboxylation, compartments or carrier coupling. Whole source balances/comparisons/practical operations are not approved from a sketch alone.',
10:'HE46 places Lichtsammelkomplex (Prinzip) under actual Leistungskurs. Whole current3 antenna structure/function and retained P3 fit that theoretical principle. No GK mandate, chromatography performance or whole photosynthesis approval follows.',
11:'Actual MV class8 pages separately name autotrophic/heterotrophic assimilation, fermentation and cellular respiration, then lung/circulation/gas-exchange duties. Accept basic anabolic and respiratory-energy contributions only. Do not import stronger later-class molecular wording or silently discharge organ-system and comparison operations.',
12:'NW IF1 whole original22 explicitly demands photosynthesis word reaction schema and significance for plants/animals; surrounding plant/germination/practical duties remain. This is a bounded substrate/product/significance basis, not named molecular light reaction or Calvin coupling.',
13:'NW IF4 whole30/31 explicitly juxtaposes basic photosynthesis and basic respiration as energy provision and separately demands historical-experiment analysis and ecological matter/energy flows. Current2 contributes basic respiration context only; its advanced molecular three-stage scope is not a named Sek-I quota here.',
14:'SH27 table separates Sek.I SE1–4 bodily systems from SE5 photosynthesis/respiration energy conversion and SE6 biosphere matter/energy, with separate SE7–8 sustainability duties. Accept two basic energy/coupling contributions. No molecular cycle/chain or advanced Sek-II content is imported into this actual lower-stage table.',
15:'SN class9 original37–39 names light-dependent/light-independent interaction, gross equations, energy conversion and conditions, as well as respiration and distinct CO2/heat measurements. The photosynthesis contribution is more than a word equation and retains this explicit coupling; it is conservatively partial to the authored Calvin scope. Respiration remains basic here, with practical measurements and full plant-anatomy duties separate.',
16:'ST7/8 original28–31 is a combined cellular structure and microorganism/fermentation duty. It supplies organelle/nutrition prerequisite context but does not name glycolysis/cycle/chain competence. Original30 requires planning, performing and protocol;31 makes temperature influence on yeast fermentation a compulsory student experiment. Accept only prerequisite context and retain the real procedural union HOLD.',
17:'ST34–35 explicitly names respiration as energy provision for muscle and word/gross equation within a complete human-system duty. This supports bounded basic respiration context only. Compulsory nutrient and physiological experiments, immunity and reproductive system duties remain unapproved by current2.',
18:'ST36–37 explicitly names photosynthesis under environmental factors in simple schemes, word/gross equation, assimilation/dissimilation and plant systems. Accept the actual factor/basic anabolic and dissimilatory relationship contributions. Molecular reaction grouping/cycle stages are not named. Water experiments, microscopic work, crop data and agricultural judgments remain separate.',
19:'TH7/8 physical22–24, printed16–18, explicitly names respiration word/sum equation, oxygen significance, nutrition-respiration coupling and complete human systems/practical work. Current2 contributes basic energy/respiration context. The broad normalized row is not a molecular-stage or complete human-system competence proof.',
20:'TH9/10 physical26–27, printed20–21, explicitly names chloroplast energy/matter conversion, rate-factor result interpretation, mitochondrial glucose-to-ATP/heat and equations, plus crop yield, storage, fungi and practical product-detection duties. Accept two actual basic/factor contributions, retaining all original application/practical operators and all20 partners. No named molecular three-stage or light/Calvin quota is inferred.'}
verdicts=[];locator_checks=[]
for r in roles['rows']:
 for loc in r['originalPrimaryLocators']:
  if 'wholeOfficialPage'in loc:
   p=pathlib.Path(loc['wholeOfficialPage']['path']);excerpt='\n'.join(p.read_text().splitlines()[loc['lineStart']-1:loc['lineEnd']]);ok=excerpt==loc['actualOriginalText'];assert ok,(r['sourceOrdinal'],str(p));locator_checks.append({'sourceOrdinal':r['sourceOrdinal'],'path':str(p),'lineStart':loc['lineStart'],'lineEnd':loc['lineEnd'],'exactOriginalComponentSha256':'sha256:'+hashlib.sha256(excerpt.encode()).hexdigest(),'wholeOriginalLocatorExact':True})
 verdicts.append({'sourceOrdinal':r['sourceOrdinal'],'sourceKey':r['sourceKey'],'ownDecision':'ACCEPT_EXACT_BOUNDED_ROLE_INTERPRETATION_ONLY','ownOriginalBasedReason':reasons[r['sourceOrdinal']],'actualWholeOriginalLocators':r['originalPrimaryLocators'],'acceptedCurrentTargetContributions':[{'goalId':x['goalId'],'acceptedRole':x['role'],'fullCurrentTargetSupportedByThisSourceAlone':x['fullCurrentTargetSupportedByThisSourceAlone'],'wholeCurrentGoalUnchanged':True,'officialLiteralWholeGoalClaim':False}for x in r['selectedTargetRoles']],'wholeSourceUnionNewlyApproved':False,'allOriginalPartnerRowsRetained':True,'allOriginalNonselectedOperatorsRetained':True,'sciencePAMNewlyReviewed':False})
residuals=load(e['stillOpenOriginalOperatorDuties']['path']);preserved_holds=[]
for r in residuals['residuals']:
 preserved_holds.append({'sourceOrdinal':r['sourceOrdinal'],'sourceGoalId':r['sourceGoalId'],'goalId':r['selectedGoalId'],'findingIdsRetained':r['findingIds'],'ownDecision':'HOLD_RETAINED_ORIGINAL_OPERATOR_DUTY','status':r['status'],'wholeOriginalRequiredPerformance':r['exactOriginalDutyDe'],'missingObservablePerformance':r['missingObservablePerformanceDe'],'currentTargetExpanded':False,'wholeSourceUnionApproved':False,'actualExecutionOrHumanTrialClaimed':False})
now=datetime.datetime.now(datetime.timezone.utc).isoformat();obs=o/'ordinary-projection-not-remediated-by-role-only-package.independent-b.observation.json'
verdict={'schemaVersion':1,'reviewedAtUtc':now,'reviewer':'OpenAI Codex independent B; current A123 outputs unread','role':'Genuine independent current source-role interpretation first verdict; does not mutate or approve unchanged ordinary source projections','candidateEntry':rec(a/'neutral-three-regional-source-role-remediation.author.corrected-count.entry.json'),'candidateOriginalFirstFreeze':rec(a/'three-regional-source-role-remediation.author.first-input.freeze.json'),'candidateCorrectedCountFreeze':rec(a/'three-regional-source-role-remediation.author.corrected-count.freeze.json'),'sourceRoleDecision':'ACCEPT_BOUNDED_INTERPRETATION_ONLY','acceptedSourceRows':20,'acceptedConcreteRoles':25,'roleCategories':checks['sourceRoleCategories'],'wholeCurrentTargetsWithExplicitBoundedHEBasis':e['goalIds'],'HECourseScopeByWholeGoal':{'32f47903-0788-5c27-ac88-7464f481f2f7':'GK_LK','135447a0-5d55-564a-afc3-3e3fbed77819':'GK_LK','ec782ce3-475e-5628-b3fe-947d72e74a74':'LK'},'wholeSourceUnionsNewlyApproved':0,'wholeRegionalCoverageApproved':False,'wholeNamedOfficialGoalNumberingApproved':False,'verdicts':verdicts,'preservedFourRealOriginalOperatorHolds':preserved_holds,'newRoleInterpretationBlockingFindings':[],'ordinaryProjectionRemediationDecision':'NOT_PRESENT_IN_ROLE_ONLY_PACKAGE','ordinaryProjectionScopeHold':rec(obs),'unchangedValidWhole3ProfilesAnd6WholeDEENCases':'KEEP_EXISTING_SCIENTIFIC_BODIES; exact objects checked, not newly scientific re-reviewed','retainedExactExistingSciencePAMCarriers':e['exactOriginalThreeSciencePAMJudgmentsKEEP'],'retainedProfiles':e['unchangedThreeProfiles'],'retainedCases':e['unchangedSixWholeCases'],'actualWholePrimaryPagesRead':28,'currentBYCourseOriginalsRead':2,'all268PartnerRowsRetained':True,'wholeUniqueCurrentPartnerTextsRead':104,'retentionAndPrimaryChecks':rec(o/'three-source-b.actual-primary-whole-duty-retention-and-portability.check.json'),'literalPageComponentChecks':locator_checks,'caseEvidenceLevel':'E1','caseMaximumClaimScope':'G1','reviewAuthority':'ai_candidate','status':'needs_human_review','newCurrentPeerA123SourceVerdictsRead':False,'newScienceReviews':0,'newAtomicityReviews':0,'newMemoryReviews':0,'nativeDOrVApproved':False,'activeWrites':0,'newStrictClosures':0,'bindingRestorationsClaimed':0,'humanApproval':False,'humanTrial':False,'performedExperiments':False}
vpath=o/'three-whole-targets25-source-roles.actual-independent-b.first-verdict.json';vpath.write_text(json.dumps(verdict,ensure_ascii=False,indent=2)+'\n')
handoff={'schemaVersion':1,'createdAtUtc':now,'role':'Neutral Source3 independent B handoff; bounded interpretation only and real original duties retained','sourceReviewPath':str(vpath),'firstSealPath':str(seal),'resultsDirectory':str(o),'peerSourceAReadBeforeFirstSeal':False,'sourceRoleDecision':'ACCEPT_BOUNDED_INTERPRETATION_ONLY','wholeCurrentGoalIds':e['goalIds'],'wholeSourceCount':20,'currentRoleCount':25,'originalPartnerRows':268,'wholeCurrentUniquePartners':104,'acceptedBoundedHEWholeTargetSupport':3,'newRoleInterpretationBlockingFindings':[],'retainedOriginalOperatorHolds':4,'ordinaryProjectionRemediationPresent':False,'ordinaryProjectionScopeObservationPath':str(obs),'retainedProfilesPath':e['unchangedThreeProfiles']['path'],'retainedCasesPath':e['unchangedSixWholeCases']['path'],'newPositiveReviewRecords':0,'reviewRunIds':[],'nextNativeDPV':'Separate actual raster/page reviews required; no pre-approval','sourceScopeGuard':'HE theory basis is not BY/NI whole-coverage or complete original-operator approval. Actual ordinary mappings/views are unchanged and still expose advanced targets in basic source scopes; this package reviews accurate bounded-role descriptions only. Any later operative projection correction requires actual bound review.','activeWrites':0,'newStrictClosures':0,'humanApproval':False,'humanTrial':False}
(o/'neutral-three-source-role-remediation.independent-b.handoff.entry.json').write_text(json.dumps(handoff,ensure_ascii=False,indent=2)+'\n')
(o/'README.md').write_text('''# Independent Biologie1/2/3 source-role B first verdict

ACCEPT25 concrete bounded role interpretations over20 retained whole source duties. The three current theoretical whole goals have explicit bounded HE support (1/2 GK+LK;3 LK). BB/BE/NW and other actual lower-stage rows supply only the named basic contributions. BY chromatography supplies context for antenna theory, with no chromatographic operator coverage. All28 whole original PDF pages were directly checked; both current BY EA/GA full texts match the completely read originals. All268 retained partner rows and104 unique whole DE/EN goal texts were considered. Three whole valid profiles and six whole DE/EN cases are exact retained scientific bodies, not new scientific/P/A/M reviews.

The four real original duties remain HOLD: judging consequences for wild/crop plants, comparing respiratory breakdown with photosynthetic buildup, chromatographic pigment separation, and yeast-fermentation practical temperature work. No whole source union or regional complete coverage is approved.

The candidate changes no ordinary source extraction or mapping. Actual ordinary views still project whole advanced1/2 into BB/BE/NW SekI and whole LHC3 into BY-GK through chromatography. The correct bounded-role descriptions are accepted within the source-only package; they do not themselves remediate those operative target edges. Exact view/reader snapshots document this remaining operational scope constraint. Later operative correction is separate work and is not pre-approved by this seal.

No new current Source-A output was read before this first seal. Candidate/human/practical/strict limits remain: ai_candidate, needs_human_review, E1/G1 witness limits, active writes0, strict gain0, no experiment or human approval/trial. Ordinary ignore behavior respects index membership; all candidate/reviewer/portable original text/HTML inputs are eligible. Raw original PDFs may remain local caches with durable URLs and complete portable reviewed pages. Historical seals are unchanged.
''')
# One immutable first seal, with all actual reviewer outputs including independent operational snapshots.
inputs=load(o/'corrected-author-all-input-receipts.first.freeze.json');fail=[]
for r in inputs['checks']:
 p=pathlib.Path(r['path'])
 if not p.is_file()or rec(p)['sha256']!=r['expected'] if r['expected'].startswith('sha256:') else not p.is_file()or rec(p)['sha256'].removeprefix('sha256:')!=r['expected']:fail.append(r['path'])
assert not fail,fail
paths=[p for p in sorted(o.rglob('*'))if p.is_file()and p!=seal]
r=subprocess.run(['git','check-ignore','-z','--stdin'],input=b'\0'.join(str(p).encode()for p in paths)+b'\0',stdout=subprocess.PIPE,check=False);assert not r.stdout,r.stdout
outputs=[rec(p)for p in paths]
d={'schemaVersion':1,'sealedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'role':'Immutable independently authored Source3 B first verdict before peer current A123 comparison','peerSourceAReadBeforeFirstSeal':False,'ownFirstVerdictBeforeAnyCurrentPeerComparison':True,'outputCount':len(outputs),'outputs':outputs,'sourceRoleDecision':'ACCEPT_BOUNDED_INTERPRETATION_ONLY','wholeSourceRows':20,'acceptedConcreteCurrentRoles':25,'wholePartnerRowsRetained':268,'wholeCurrentUniquePartnerTextsRead':104,'originalOperatorHoldsRetained':4,'ordinaryProjectionRemediationClaimed':False,'finalFrozenAuthorReceiptChecks':len(inputs['checks']),'finalFrozenAuthorHashFailures':fail,'whole3ProfileAnd6CaseBodiesExactKEEP':True,'actualWholeOriginalPDFPagesRead':28,'actualBYEAAndGAOriginalsRead':2,'sourceRoleReviewInputs':[rec(o/'neutral-corrected-three-source-author-entry.first-input.freeze.json'),rec(o/'corrected-author-all-input-receipts.first.freeze.json'),rec(o/'original-holds-and-primary-inputs.first.freeze.json'),rec(o/'primary-pages-and-operative-regional-baselines.supplemental-input.freeze.json'),rec(o/'ordinary-source-projection.first-read.freeze.json')],'activeWrites':0,'newStrictClosures':0,'humanApproval':False,'humanTrial':False,'newScienceReviews':0,'newAtomicityReviews':0,'newMemoryReviews':0}
with seal.open('x')as f:f.write(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
assert all(rec(r['path'])==r for r in load(seal)['outputs'])
print(json.dumps({'firstSealPath':str(seal),'firstSealSHA256':rec(seal)['sha256'],'outputs':len(outputs),'inputHashFailures':fail,'sourceRoleDecision':d['sourceRoleDecision'],'acceptedRoles':25,'originalOperatorHolds':4,'neutralHandoff':str(o/'neutral-three-source-role-remediation.independent-b.handoff.entry.json'),'ordinaryProjectionRemediationPresent':False},ensure_ascii=False))
