from pathlib import Path
import json,hashlib,importlib.util,shutil,jsonschema
R=Path('/home/enpasos/projects/skillpilot');P=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-two-global-ten-current518-accesses-independent-merge-audit-v1';O=P/'private-config-isolation-and-current520-native-successor-v2';A=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-M4-thirteen-globalisation-development-whole-material-author-a-v1/two-only-additional-country-contexts-ten-whole-accesses-author-successor-v8';read=lambda p:json.loads(p.read_text())
def fp(p):return {'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}
def wr(n,x):p=O/n;assert not p.exists();p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');return p
x=read(O/'actual-ten-accesses-fieldwise-current518-to520-whole-input-review.json');ix=read(A/'actual-two-only-additional-contexts10-whole-target-accesses-current518.AUTHOR-index-v8.json');b=read(O/'independent-before-current518.actual-native.json');a=read(O/'independent-after-two-global-current520-ten-accesses.actual-native.json');n=read(O/'independent-negative-BBGK-company-process-access-drop.actual-native.json');can=read(O/'whole-reviewed-current520.exact.json');goals={g['id']:g for g in can['goals']};newids=set(x['newPracticeIds']);access=[];rest=[]
assert len(b['allScopeRows'])==len(a['allScopeRows'])==64
for u,v in zip(b['allScopeRows'],a['allScopeRows']):
 assert all(u[k]==v[k]for k in ['viewPath','jurisdiction','scopeFilters','ordinaryTargetIds'])
 for f in ['visibleAllAtomicIds','visibleTargetAtomicIds']:assert set(u[f])==set(v[f])-newids
 assert not v['wholeMaterialCoverageBindingIssues'] and not v['wholeMaterialPrerequisiteClosureIssues']
 for k in set(v['actualTerminalIds'])&newids:
  g=goals[k];m=next(z for z in a['materials']if z['id']==k);assert not m['unresolvedReferences'];assert set(m['wholeMaterialPrerequisites'])<=set(v['visibleAllAtomicIds']);assert set(g['examData']['coveredGoalIds'])<=set(v['visibleAllAtomicIds']);assert all(c in g['tags']for c in v['scopeFilters']if c in ['GK','LK']);assert v['jurisdiction']in m['actualCompiled']['compiledApplicability']['jurisdiction']
  access.append({'viewPath':v['viewPath'],'jurisdiction':v['jurisdiction'],'scopeFilters':v['scopeFilters'],'materialId':k,'wholeCoveredGoalIds':g['examData']['coveredGoalIds'],'wholeMandatoryPrerequisiteClosure':m['wholeMaterialPrerequisites'],'decision':'KEEP_WHOLE_SCIENCE_REUSE_AND_SCOPE_ACCESS_ONLY','reason':'The entire unchanged foreign-qualified material fits the actual course and compiled jurisdiction; all examined goals plus every actual inherited/transitive prerequisite are locally visible as target or explicitly authored support. No ordinary target, source mapping or mastery standard is changed.'})
 for k in (set(v['expectedTerminalIds'])-set(v['actualTerminalIds']))&newids:
  g=goals[k];m=next(z for z in a['materials']if z['id']==k);missing=sorted(set(m['wholeMaterialPrerequisites'])-set(v['visibleAllAtomicIds']));assert not missing
  rest.append({'viewPath':v['viewPath'],'jurisdiction':v['jurisdiction'],'scopeFilters':v['scopeFilters'],'materialId':k,'wholeCoveredGoalIds':g['examData']['coveredGoalIds'],'wholeMandatoryPrerequisiteClosure':m['wholeMaterialPrerequisites'],'missingClosure':missing,'finding':'REAL_EXPECTED_ACCESS_OMISSION_AUTHOR_ADDITIONAL_REFERENCE_NO_POLICY_CHANGE','coveredTargetsAlreadyHaveOtherEndpoints':True})
assert len(access)==20 and len(rest)==46 and len({(z['viewPath'],z['materialId'])for z in rest})==46
for k in x['navFieldIds']:
 r=next(z for z in a['compilerGoals']if z['goalId']==k);assert goals[k]['applicability']==r['compiledApplicability'];assert all(e['kind']=='child-union'for e in r['evidence'])
checks=[]
for p,s in [(O/'whole-reviewed-current520.exact.json',R/'docs/landscape-runtime.schema.json')]+[(R/z['after']['path'],R/'contracts/curriculum-package/v1/composition-view.schema.json')for z in x['wholeViewPairs']if z['addedReferences']]:
 errors=list(jsonschema.Draft202012Validator(read(s)).iter_errors(read(p)));assert not errors,[str(e)for e in errors];checks.append({'input':fp(p),'schema':fp(s),'closedErrors':0})
r=lambda d:next(q for q in d['nativeRules']if q['id']=='CQR-104');metrics=lambda d:r(d)['metrics'];assert b['sourceRule']==a['sourceRule']==n['sourceRule'];assert metrics(b)['visibleSelectedAtomicGoalOccurrences']==metrics(a)['visibleSelectedAtomicGoalOccurrences']==6974
for d in [b,a,n]:assert d['compilerSummary']['errors']==d['compilerSummary']['warnings']==0
assert metrics(b)['visibleSelectedGoalOccurrencesMissingEffectiveTerminalRoute']==2044 and metrics(a)['visibleSelectedGoalOccurrencesMissingEffectiveTerminalRoute']==1998 and metrics(n)['visibleSelectedGoalOccurrencesMissingEffectiveTerminalRoute']==2004
assert metrics(b)['uniqueVisibleSelectedGoalsMissingEffectiveTerminalRoute']==175 and metrics(a)['uniqueVisibleSelectedGoalsMissingEffectiveTerminalRoute']==171
assert metrics(b)['projectionScopesMissingTerminalAutonomyGoals']==16 and metrics(a)['projectionScopesMissingTerminalAutonomyGoals']==32
for k in ['projectionScopesWithInvalidStageStructure','projectionScopesWithIncompleteWholeMaterialCoverageBindings','projectionScopesWithIncompleteWholeMaterialPrerequisiteClosure']:assert metrics(a)[k]==0
rootBook=R/'app/scripts/config/goal-books/de-gym-economics-current-canonical.json';assert fp(rootBook)['sha256']=='a48a7a9998902e988ff7c420bd305a2bc89860d9244bea4181da0cbb92c4be27';assert fp(R/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_WIRTSCHAFT.de.json')['sha256']==ix['basis518']['wholeActiveCAN518']['sha256']
proof=wr('actual-independent20-visible-material-contexts-and46-whole-closure-access-debts.json',{'wholeTwentyNewVisibleContextJudgments':access,'wholeFortysixExpectedAccessOmissions':rest,'all64WholeOrdinaryTargetSupportPOnlyMemorySetsExact':True,'wholeCurrentFourGoalsP8AndAll516OtherOldGoalsExact':True,'tenViewReferenceAppendsTwoNavFieldsOnly':True,'closedSchemas':checks,'before':r(b),'after':r(a),'genuineOwnBBGKDropNegative':r(n),'newScienceOrHumanApprovals':0,'noCheckerPolicyChanges':True})
incident=wr('actual-private-capsule-book-config-isolation-failure-and-byte-exact-current518-restoration.json',{'failedSetupHistory':fp(P/'first-private-capsule-config-symlink-setup-failure.raw.txt'),'cause':'Capsule app/scripts/config was a preexisting symbolic link to the shared repo; unlink+copy mistakenly removed the source Book config and failed before copying. No native execution had occurred.','currentBookExactRestoration':fp(rootBook),'restoredFrom':fp(R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-current518-E7-Glob7-qualified-fieldwise-root-candidate-v1/whole-economics-book-config-current518-v9-SEM-P336.INERT.json'),'privateFullConfigCopyNow':True,'destinationParentResolvedOutsideRepoBeforeEveryWrite':True,'CANSEMViewsAndScientificBodiesUnmodified':True,'activeNetChangesAfterRestoration':0})
for p in [Path('/tmp/economics-Glob2-ten-independent-native-review.py'),Path('/tmp/economics-Glob2-ten-independent-native-review-v2.py'),Path('/tmp/economics-Glob2-ten-independent-seal.py')]:shutil.copyfile(p,O/'technical-reproduction'/p.name)
s=importlib.util.spec_from_file_location('validator',R/'scripts/validate_schemas.py');mod=importlib.util.module_from_spec(s);s.loader.exec_module(mod);assert not mod.curriculum_symlink_errors(str(R));files=[]
for p in sorted(O.rglob('*')):
 if p.is_file():
  assert not p.is_symlink()
  if p.suffix=='.json':assert p.read_bytes().endswith(b'\n');json.loads(p.read_text())
  files.append(fp(p))
manifest=wr('actual-independent-Glob2-ten-current518-inputs-native64-and-closed11-schema.manifest.json',{'files':files,'JSONWholeParseLF':True,'curriculumSymlinkErrors':0,'inadvertentTemporaryBookWriteRestoredExactly':fp(incident),'activeNetChanges':0})
receipt=wr('actual-final-independent-two-global-status-nav-ten-accesses-KEEP-and46-real-expected-access-debts.handoff.receipt.json',{'reviewer':'/root/economics_merge_audit independent of /root/economics_m2_source_independent_a authorship','decision':'BOUNDED_TWO_WHOLE_QUALIFIED_BODY_BINDINGS_TWO_NAV_FIELDS_TEN_VIEW_REFERENCES_KEEP','authorHandoffV8':fp(A/'actual-final-two-additional-global-contexts-ten-current518-target-accesses.author-handoff-v8.json'),'manifest':fp(manifest),'wholeIndividualScopeProof':fp(proof),'actualNative':'Current5182044/175 -> current5201998/171; genuine own BB-GK company-process access drop2004. Compiler0/0, Source16/2134 unsupported0/reverse0 wholeexact, all64 ordinary6974/support/Memory sets exact, 11 closed schemas0. Twenty visible new material contexts have complete actual whole prerequisite closure and current course compatibility.','openExpectedAccesses46':fp(proof),'expectedMaterialScopeDebt16to32ExplicitlyNotPass':True,'additionalAuthorReferenceFollowerRequested':True,'wholeScience5affOnlyReused':ix['basis518']['wholeForeignScience'],'noNewWholeScientificOrHumanStatusApproval':True,'strictNetGain':0,'wholeM4CompletionClaim':False,'activeNetChangesAfterByteExactBookRestoration':0,'executionIsolationIncident':fp(incident)})
print(json.dumps({'receipt':fp(receipt),'manifest':fp(manifest),'proof':fp(proof)},ensure_ascii=False))
