"""Own whole bilingual teaching cases; no observed learner work or animal experiment."""
from pathlib import Path
import json
D=Path(__file__).resolve().parent
goals=json.loads((D/'current20-whole-DEEN-goals.actual.json').read_text())['goals']
cases=[]
def add(mde,men,tde,ten,ade,aen):
    cases.append({'material':{'de':mde,'en':men},'task':{'de':tde,'en':ten},'modelAnswer':{'de':ade,'en':aen}})

#1 Species versus individuals, discovery versus extinction in both whole cases.
add('Eigenes Modellinventar einer Wiese: fünf Gänseblümchen, drei Rotkehlchen und zwei Weinbergschnecken. Ein Fossil zeigt eine heute ausgestorbene Tiergruppe. Eine Meldung nennt einen erstmals wissenschaftlich beschriebenen Pilz; ein Schüler entdeckt erstmals eine ihm unbekannte Schnecke im Garten.',
 'Own meadow model inventory: five daisies, three robins and two Roman snails. A fossil shows an extinct animal group. A report describes a fungus newly described by science; a pupil first finds an unfamiliar snail in the garden.',
 'Benenne Beispiele der Vielfalt, trenne Arten- und Individuenzahl und erläutere Entdeckung und Aussterben einschließlich der Grenze dieser lokalen Liste.',
 'Name examples of diversity, distinguish species and individual counts, and explain discovery/extinction including limits of this local list.',
 'Die Liste enthält drei bezeichnete Arten und zehn Individuen aus verschiedenen Gruppen. Der Fossilbefund verweist auf vergangene Vielfalt; globales Aussterben bedeutet, dass keine lebenden Individuen einer Art mehr existieren. Ein neu wissenschaftlich beschriebener Pilz erweitert das bekannte Arteninventar, während eine persönliche Erstbeobachtung keine neue Art beweist. Die kurze lokale Liste zählt weder alle Arten der Wiese noch der Erde und zeigt keinen aktuellen Aussterbevorgang.',
 'The list identifies three species and ten individuals from different groups. The fossil indicates past diversity; global extinction means no living individuals of a species remain. A newly scientifically described fungus expands the known inventory, whereas a personal first sighting establishes no new species. This short local list counts neither all meadow nor global species and demonstrates no current extinction process.')
add('Synthetische Teichliste: sechs Wasserfrösche, vier Libellen derselben benannten Art und drei Wasserpflanzen derselben Art. Eine Art aus dem Gebiet wird anderswo weiterhin gefunden. Ein Forschungsteam erkennt anhand mehrerer Merkmale, dass zwei bisher zusammengefasste Populationen verschiedene Arten sind.',
 'Synthetic pond list: six water frogs, four dragonflies of one named species and three water plants of one species. A species absent locally is still found elsewhere. A research team uses several traits to recognize two formerly grouped populations as distinct species.',
 'Benenne die Vielfalt und ordne Individuen, Arten, wissenschaftliche Neubeschreibung sowie lokales Verschwinden versus globales Aussterben.',
 'Name the diversity and classify individuals, species, scientific new description, and local disappearance versus global extinction.',
 'Frösche, Libellen und Pflanzen zeigen verschiedene Lebensformen; die Modellliste umfasst dreizehn Individuen und drei benannte Arten. Eine Neubeschreibung kann bisher übersehene Vielfalt sichtbar machen, ohne dass die Organismen gerade erst entstanden sein müssen. Die andernorts noch vorhandene Art ist lokal verschwunden, nicht weltweit ausgestorben. Die Liste erlaubt keine vollständige Artenzahl oder Häufigkeitsaussage für andere Gebiete.',
 'Frogs, dragonflies and plants represent different living forms; the model list contains thirteen individuals and three named species. A new description can reveal overlooked diversity without the organisms having just originated. A species still present elsewhere has disappeared locally rather than become globally extinct. The list establishes no complete species count or abundance elsewhere.')

#2 Structure and function of organs of a mammal.
add('Schematischer Hund: Gelenke verbinden Knochen, Muskeln ziehen über Sehnen; die Lunge hat viele dünne Austauschflächen; das Herz besitzt kräftige Muskelwände; Fell liegt auf der Haut. Keine tatsächliche Präparation ist vorgenommen.',
 'Schematic dog: joints connect bones and muscles pull through tendons; lungs contain many thin exchange surfaces; the heart has strong muscular walls; fur covers skin. No actual dissection has been performed.',
 'Ordne den Organen ihre Funktionen zu und erkläre jeweils einen passenden Bau-Funktions-Zusammenhang.',
 'Assign functions to the organs and explain one matching structure–function relationship for each.',
 'Knochen stützen, Gelenke erlauben Bewegung und Muskelzug bewegt Knochen über Sehnen. Große dünne Lungenflächen unterstützen Gasaustausch; der muskuläre Herzbau erzeugt Bluttransport. Haut grenzt den Körper ab, Fell kann Wärmeverlust durch eingeschlossene Luft mindern. Organe wirken zusammen: Herztransport versorgt auch bewegte Muskeln, die Lunge erzeugt selbst keinen Blutkreislauf.',
 'Bones support, joints permit motion and muscle pull moves bones through tendons. Large thin lung surfaces support gas exchange; muscular heart walls pump blood. Skin provides a boundary and fur can reduce heat loss by trapping air. Organs cooperate: blood transport supplies active muscles, while lungs do not themselves produce circulation.')
add('Modell eines Maulwurfs: kräftige Vordergliedmaßen mit breiten Grabflächen, ein gegliedertes Skelett, Lunge und Herz sowie empfindliche Haut und Tasthaare. Ein fehlerhafter Plan nennt Knochen einen Motor und Herz ein Organ zur Zerkleinerung von Nahrung.',
 'Mole model: powerful forelimbs with broad digging surfaces, an articulated skeleton, lungs and heart, plus sensitive skin and tactile hairs. A faulty plan calls bones a motor and the heart an organ for crushing food.',
 'Korrigiere die Zuordnung und verbinde Gestalt beziehungsweise Organbau mit Bewegung, Versorgung und Wahrnehmung.',
 'Correct the assignments and connect body shape/organ structure to movement, supply and sensing.',
 'Muskeln liefern Zugkraft; Knochen und Gelenke übertragen und führen Bewegung, breite Vordergliedmaßen eignen sich zum Graben. Herzmuskel pumpt Blut, Lungenflächen ermöglichen Gasaustausch; diese Versorgung unterstützt Muskelarbeit. Sensible Haut und Tasthaare vermitteln mechanische Reize. Weder Knochen allein erzeugen Muskelkraft noch zerkleinert das Herz Nahrung; diese Funktionen gehören anderen Strukturen.',
 'Muscles generate pulling force; bones and joints transmit/direct movement, and broad forelimbs assist digging. Heart muscle pumps blood and lung surfaces support gas exchange; this supply enables muscle work. Sensitive skin and tactile hairs convey mechanical stimuli. Bones alone do not generate muscle force and the heart does not crush food; those functions belong to other structures.')

#3 Genuine functional adaptations, no purposeful acquisition.
add('Schematischer Fischotter: dichtes Fell hält bei intaktem Zustand Luft zwischen Haaren, Schwimmhäute vergrößern die antreibende Fußfläche; der Lebensraum ist kühles Wasser mit Nahrungssuche im Wasser. Eine Behauptung lautet, Wasser zwinge ein einzelnes Tier sofort zur Bildung von Schwimmhäuten.',
 'Schematic otter: intact dense fur traps air and webbing increases the propulsive foot area; its habitat includes cool water and aquatic feeding. A claim says water forces an individual immediately to develop webbed feet.',
 'Deute beide Merkmale als Angepasstheit an den Lebensraum und begrenze die behauptete Entstehungserklärung.',
 'Interpret both traits as habitat adaptations and bound the proposed origin explanation.',
 'Eingeschlossene Luft kann isolieren und Wärmeverlust mindern; größere wirksame Fußfläche unterstützt Schwimmen. Diese Funktionen passen zur Nahrungssuche in kühlem Wasser, ohne perfekte Anpassung an jede Situation zu garantieren. Die funktionelle Passung beweist keine absichtliche oder sofortige Neubildung durch Wasser. Vererbbare Variation und langfristige Selektion betreffen Populationen über Generationen.',
 'Trapped air can insulate and reduce heat loss; greater effective foot area supports swimming. These functions suit feeding in cool water without guaranteeing perfect adaptation in every situation. Functional fit establishes no intentional or immediate production by water. Heritable variation and long-term selection affect populations over generations.')
add('Vergleichendes Robbenmodell: stromlinienförmiger Körper, flossenartige Gliedmaßen und eine isolierende Fettschicht. Ein Landsäugetier mit langen Laufgliedmaßen ist bei schneller Bodenbewegung vorteilhaft. Gleiche Körpermasse und Gesundheit werden im Modell angenommen.',
 'Comparative seal model: streamlined body, flipper-like limbs and insulating fat. A land mammal with long running limbs benefits during fast ground movement. Equal body mass and health are assumed in this model.',
 'Deute die Robbenmerkmale mit Wasserwiderstand, Fortbewegung und Wärmehaushalt und erläutere Grenzen der Vergleichsaussage.',
 'Interpret seal traits through water resistance, movement and thermal balance, and explain limits of the comparison.',
 'Stromlinienform mindert Strömungswiderstand, Flossen übertragen Kraft im Wasser und Fett verringert Wärmeverlust. Laufgliedmaßen erfüllen auf Land andere günstige Funktionen. Der Lebensraum setzt Bedingungen, in denen Merkmale unterschiedlich nützlich sind; er erzeugt sie nicht zielgerichtet. Der Vergleich erlaubt keine allgemeine Rangfolge höherer oder besserer Tiere und keine universelle Aussage über jedes Robbenmerkmal.',
 'Streamlining reduces flow resistance, flippers transfer force in water and fat reduces heat loss. Running limbs provide other advantages on land. Habitat supplies conditions in which traits differ in usefulness rather than purposefully creating them. The comparison establishes no general ranking of superior animals or universal explanation of every seal trait.')

#4 Ethograms must retain actual observation/recording duties.
add('Eigene hypothetische Hundesequenz in6gleichlangen Zeitfenstern: sitzt und Blick zur Tür; läuft drei Schritte; schnuppert am Boden; schnuppert; legt sich; liegt. Die Begriffe „will hinaus“ und „ist beleidigt“ stehen daneben als fremde Deutungen. Dies ist keine echte Videoaufnahme oder Beobachtung.',
 'Own hypothetical dog sequence in six equal time windows: sits looking at door; walks three steps; sniffs floor; sniffs; lies down; remains lying. “Wants to leave” and “is offended” are added interpretations. This is no genuine video or observation.',
 'Erstelle ein beobachtungsnahes Ethogramm mit definierten Kategorien, halte Zeiten fest und deute vorsichtig. Beobachte für die tatsächliche Leistung später ein reales Tier oder geeignetes reales Video ohne Störung und erstelle ein eigenes Protokoll.',
 'Create an observation-based ethogram with defined categories, record times and interpret cautiously. For actual performance later observe a real animal or suitable genuine video without disturbing it and create your own record.',
 'Definierte Kategorien sind Sitzen, Gehen, Schnuppern und Liegen; das Ablegen ist ein Übergang. Die sechs Intervalle werden diesen sichtbaren Vorgängen zugeordnet, etwa Schnuppern in2/6Intervallen. Schnuppern kann Informationsaufnahme dienen; Türblick allein beweist weder Wunsch noch Gefühl. Kategorien müssen durch andere Beobachtende nachvollziehbar und zeitlich eindeutig sein. Ein echtes eigenes Beobachtungsprotokoll mit Rahmenbedingungen, Reihenfolge und vorsichtiger Deutung bleibt für Performanz erforderlich; diese Modellantwort ersetzt es nicht.',
 'Defined categories include sitting, walking, sniffing and lying; lying down is a transition. The six intervals map to these visible actions, with sniffing in2/6intervals. Sniffing may gather information; looking at a door proves neither desire nor emotion. Other observers must be able to apply categories consistently and assign times clearly. Genuine personal observation with conditions, sequence and cautious interpretation remains required for performance; this model answer does not replace it.')
add('Synthetische Katzensequenz: Kopf folgt bewegtem Spielzeug; geducktes Schleichen; kurzes Stillhalten; Sprung; Pfote berührt Spielzeug; Körperpflege. Der Beobachtungsbogen mischt „jagt“, „böse“, „läuft“ und „verhält sich normal“. Keine echte Jagd oder Tierversuchsleistung ist dokumentiert.',
 'Synthetic cat sequence: head tracks moving toy; crouched stalking; brief pause; jump; paw contacts toy; grooming. The sheet mixes “hunts”, “angry”, “walks” and “behaves normally”. No genuine hunt or animal experiment is documented.',
 'Verbessere Kategorien und Protokoll, trenne Beobachtung und Deutung und plane eine eigene echte schonende Beobachtung oder Auswertung eines realen Videos.',
 'Improve categories/recording, separate observation from interpretation, and plan genuine nonintrusive observation or analysis of a real video.',
 'Kopfverfolgung, geducktes Fortbewegen, Stillhalten, Springen, Pfotenkontakt und Körperpflege sind überprüfbare Beschreibungen mit vereinbarten Start-/Endkriterien. Zeiten und Beobachtungskontext gehören in das Ethogramm; „böse/normal“ sind unklare wertende Etiketten. Die Abfolge ähnelt Jagdkomponenten, belegt aber keinen vollständigen Beutefang und keine sichere innere Absicht. Für die tatsächliche Leistung wird die echte Sequenz ohne Reizsteigerung oder Stress beobachtet, separat protokolliert und mit Unsicherheit interpretiert.',
 'Head tracking, crouched movement, pausing, jumping, paw contact and grooming are observable descriptions with agreed start/end criteria. Times and context belong in the ethogram; “angry/normal” are unclear evaluative labels. The sequence resembles hunting components without proving complete prey capture or certain internal intention. Actual performance observes a genuine sequence without intensified stimulation or stress, records it separately and interprets uncertainty.')

#5 Ancestry and domestication.
add('Modell einer Vorfahrenpopulation von Wölfen: vererbbare Unterschiede in Körpergröße und Reaktionsverhalten. Über viele Generationen werden im Kontakt mit Menschen bestimmte Tiere häufiger zur Fortpflanzung ausgewählt. Spätere Hundepopulationen unterscheiden sich in Gestalt und Verhalten.',
 'Model ancestral wolf population: heritable differences in size and responses. Over many generations certain animals are more often selected for reproduction around humans. Later dog populations differ in form and behaviour.',
 'Beschreibe Abstammung und Domestikation, erkläre Zuchtziele/-merkmale und korrigiere die Aussage, ein heutiger Wolf verwandle sich durch Erziehung in einen Hund.',
 'Describe ancestry/domestication and breeding aims/traits; correct the claim that training turns a modern wolf into a dog.',
 'Hunde haben eine Abstammungsgeschichte innerhalb der Wolfslinie; heutige Hunde entstehen nicht aus der Erziehung eines einzelnen heutigen Wolfs. Vererbbare Variation und unterschiedliche Fortpflanzung über Generationen können Merkmalsanteile verändern. Menschen fördern bei Zucht bestimmte Gestalt- oder Verhaltensmerkmale; Lernen eines Individuums ist davon verschieden. Domestikation und weitere Rassezucht sind historische Populationsprozesse, keine zielgerichtete Selbstveränderung.',
 'Dogs have ancestry within the wolf lineage; training one modern wolf does not make it a dog. Heritable variation and differential reproduction over generations can change trait frequencies. Breeding favours selected body or behavioural traits, distinct from individual learning. Domestication and subsequent breed selection are historical population processes rather than purposeful self-transformation.')
add('Schematischer Vergleich zweier Hundelinien aus gemeinsamen domestizierten Vorfahren: LinieA wurde auf ausgeprägten Geruchssinn und Suchverhalten, LinieB auf andere Körper-/Verhaltensmerkmale ausgewählt. Innerhalb jeder Linie bleibt Variation. Eine Darstellung ordnet große Hunde als evolutionär höher als kleine ein.',
 'Schematic dog lines from shared domesticated ancestors: lineA was selected for scent-related searching and lineB for other body/behavioural traits. Variation remains within each line. A display ranks large dogs as evolutionarily higher than small dogs.',
 'Beschreibe den Entwicklungs-/Domestikationszusammenhang, ordne Zuchtmerkmale ein und beurteile die Rangfolge.',
 'Describe developmental/domestication relationships, identify breeding traits and assess the ranking.',
 'Beide Linien teilen Abstammung und frühere Domestikation; spätere menschliche Auswahl verändert populationsbezogen Häufigkeiten vererbbarer Merkmale. Trainingswirkung und Umweltbedingungen wirken zusätzlich auf beobachtetes Verhalten. Rassen sind keine verschiedenen Entwicklungsstufen und Körpergröße bildet keine höhere Evolution. Zuchtziele sind menschliche Auswahlkriterien, deren Auswirkungen auf Funktion und Gesundheit gesondert beurteilt werden müssen.',
 'Both lines share ancestry and earlier domestication; later human selection changes population frequencies of heritable traits. Training and environment also affect observed behaviour. Breeds are not successive developmental stages and size measures no higher evolution. Breeding aims are human selection criteria whose functional/health consequences require separate assessment.')

#6 Germination and monitoring growth.
add('Synthetischer Bohnenvergleich bei gleicher geeigneter Temperatur und Luftzufuhr: feuchtes Papier8/10Keimlinge, trockenes0/10. Beispielreihe eines Keimlings: Samenschale öffnet; Keimwurzel tritt aus; Spross richtet sich auf; erste grüne Blätter entfalten sich. Kein tatsächlich ausgeführter Versuch ist belegt.',
 'Synthetic bean comparison at equal suitable temperature/air: moist paper8/10seedlings, dry paper0/10. Example sequence: seed coat opens, radicle emerges, shoot rises and first green leaves unfold. No actual experiment is evidenced.',
 'Beschreibe Keimungsbedingungen und verfolge die Wachstumsschritte. Führe für eigene Performanz später eine angeleitete Beobachtungsreihe mit echten Samen durch und dokumentiere Zeitpunkte und Merkmale.',
 'Describe germination conditions and track growth stages. For personal performance later make guided observations of real seeds and record times/features.',
 'Im Modell fehlt der trockenen Gruppe Wasser; geeignete Temperatur und Sauerstoff sind weitere Bedingungen. Keimwurzel und Spross entwickeln sich aus dem Embryo, danach entfalten sich Blätter; Reservestoffe unterstützen frühe Entwicklung. Später benötigt grünes Wachstum auch Licht, CO2, Wasser und Mineralsalze. Die Modellreihe erlaubt keinen vollständigen Nachweis aller Keimungsfaktoren oder eine allgemeine Lichtkeimregel. Die echte spätere Reihe protokolliert gleiche Ausgangsbedingungen, Zeit und beobachtetes Wachstum; die synthetische Reihe ersetzt sie nicht.',
 'Water is absent in the dry model group; suitable temperature and oxygen are further conditions. Radicle and shoot develop from the embryo before leaves unfold; reserves support early growth. Later green growth also needs light, CO2, water and minerals. The model proves neither every germination factor nor a universal light-germination rule. The genuine later series records matched starting conditions, time and observed growth; synthetic data do not replace it.')
add('Eigenes Datenmodell bei gleicher Feuchte: warme geeignete Gruppe keimt früher als eine kühlere Gruppe. Später misst die synthetische Reihe Sprosslängen2,4und7cm an aufeinanderfolgenden Zeitpunkten und zeigt neue Blätter. Ein falsches Protokoll nennt diese Werte echte Messungen der lernenden Person.',
 'Own model at equal moisture: a suitably warm group germinates earlier than a cooler group. Later synthetic shoot lengths are2,4and7cm at successive times with new leaves. A faulty record calls them the learner own actual measurements.',
 'Erläutere Bedingungen und Wachstumsschritte, korrigiere den Datenstatus und plane eine echte dokumentierte Wachstumsbeobachtung ohne erfundene Messungen.',
 'Explain conditions/stages, correct data status and plan real recorded growth observation without invented measurements.',
 'Temperatur beeinflusst in diesem Bereich den zeitlichen Verlauf, zusammen mit Wasser und Sauerstoff. Die Folge zeigt Wachstum nach Keimung mit Sprossverlängerung und Blattbildung; geeignete Bedingungen sind artspezifisch. Zahlen müssen als synthetisch gekennzeichnet bleiben. Für tatsächliche Performanz werden echte Samen wiederholt mit derselben Messdefinition beobachtet, Datum und Merkmale festgehalten und Abweichungen berichtet. Modellwerte sind keine eigenen Messungen und fehlende Beobachtungen werden nicht ergänzt.',
 'Temperature affects timing in this range alongside water/oxygen. The sequence shows post-germination shoot extension and leaf formation; suitable conditions depend on species. Numbers must remain labelled synthetic. Actual performance repeatedly observes real seeds with consistent measurement definitions, records dates/features and reports deviations. Model values are no personal measurements and missing observations are not invented.')

#7 Root, shoot, leaf, upward water and source-to-sink assimilates.
add('Schematische Bohnenpflanze: Wurzeln mit feinen Aufnahmebereichen im Boden; Spross mit Leitgewebe; flächige grüne Blätter mit Spaltöffnungen. Boden liefert Wasser/Mineralsalze, Luft liefert CO2 und Sonne Licht. Junge Wurzelspitzen und Früchte verbrauchen beziehungsweise speichern gebildete Stoffe.',
 'Schematic bean: roots with fine uptake regions in soil, stem with conducting tissues, broad green leaves with stomata. Soil supplies water/minerals, air CO2 and sunlight energy. Young root tips/fruits use or store produced substances.',
 'Erkläre Bau und Funktion aller drei Organe und verbinde Stoffaufnahme, Transport, Transpiration und Fotosynthese.',
 'Explain structure/function of all three organs and connect uptake, transport, transpiration and photosynthesis.',
 'Wurzeln verankern und nehmen Wasser/Mineralsalze auf; ihre feinen Bereiche vergrößern Kontakt. Der Spross trägt Blätter/Blüten und verbindet Organe durch Leitgewebe. Blätter bieten Lichtaufnahmefläche und Gasaustausch; Fotosynthese bildet aus CO2 und Wasser mithilfe von Licht energiereiche Stoffe und O2. Wassertransport führt von Wurzeln zu Blättern, Wasserverlust über Spaltöffnungen trägt dazu bei. Assimilate gelangen von bildenden Blättern zu Verbrauchs-/Speicherorganen; die Pflanze nimmt nicht fertige Nahrung aus dem Boden auf.',
 'Roots anchor and absorb water/minerals; fine regions enlarge contact. The stem supports leaves/flowers and connects organs through conducting tissues. Leaves provide light capture and gas exchange; photosynthesis uses CO2, water and light to form energy-rich substances and O2. Water moves roots-to-leaves, aided by loss through stomata. Assimilates move from producing leaves to consuming/storing organs; plants do not take ready-made food from soil.')
add('Modell einer Rübe: grüne Blätter werden beleuchtet, die verdickte Wurzel speichert organische Stoffe. Ein Fehlerschema zeichnet Zucker ausschließlich vom Boden nach oben und zeigt den Spross ohne Transportfunktion.',
 'Turnip model: green leaves are illuminated and the enlarged root stores organic substances. A faulty diagram sends sugar only upward from soil and assigns no transport role to the stem.',
 'Korrigiere das Schema und erläutere den zusammenhängenden Bau-Funktions-Bezug von Wurzel, Spross und Blatt.',
 'Correct the diagram and explain connected root–stem–leaf structure/function.',
 'Die Wurzel nimmt Wasser/Mineralsalze auf und kann Speicherorgan sein; gespeicherte organische Stoffe stammen wesentlich aus Fotosynthese, nicht aus fertigem Bodenzucker. Der Spross stützt und leitet Wasser sowie Assimilate. Blattfläche, grünes Gewebe und Spaltöffnungen ermöglichen Lichtaufnahme, CO2-Austausch und Transpiration. Wasser fließt im Leitweg zu Blättern; Assimilate können von Blättern abwärts zur Speicherwurzel gelangen. Unterschiedliche Transporte haben unterschiedliche Ausgangs- und Zielorgane.',
 'Roots absorb water/minerals and may store substances; stored organics chiefly originate in photosynthesis rather than ready-made soil sugar. Stems support and conduct water/assimilates. Leaf area, green tissue and stomata enable light capture, CO2 exchange and transpiration. Water travels toward leaves, while assimilates may travel downward to the storage root. Different transport processes have distinct source/destination organs.')

#8 Complete flower parts and reproduction.
add('Eigenes Kirschblütenmodell: Kelchblätter schützen die Knospe, auffällige Kronblätter umgeben Staubblätter mit Staubbeuteln; in der Mitte Narbe, Griffel und Fruchtknoten mit Samenanlagen. Eine Biene überträgt Pollen auf die Narbe.',
 'Own cherry-flower model: sepals protect the bud, conspicuous petals surround stamens with anthers, and stigma/style/ovary with ovules occupy the centre. A bee transfers pollen to the stigma.',
 'Benenne Bestandteile und erläutere ihre Funktionen von Bestäubung über Befruchtung bis Samen-/Fruchtbildung.',
 'Name parts and explain functions from pollination through fertilization to seed/fruit formation.',
 'Kelchblätter schützen, Kronblätter können Bestäuber anlocken; Staubbeutel erzeugen Pollen. Die Narbe nimmt geeigneten Pollen auf, durch den Griffel wächst ein Pollenschlauch zur Samenanlage. Eine männliche Keimzelle erreicht die Eizelle; diese Verschmelzung ist Befruchtung, nicht die bloße Pollenablage. Die Samenanlage entwickelt sich zum Samen mit Embryo, der Fruchtknoten zur Frucht. Die Biene ermöglicht Transport, bildet aber weder Embryo noch Samen selbst.',
 'Sepals protect and petals can attract pollinators; anthers produce pollen. The stigma receives suitable pollen and a pollen tube grows through the style toward an ovule. A male gamete reaches/fuses with the egg: this is fertilization, distinct from pollen deposition. The ovule becomes a seed with embryo and the ovary becomes fruit. The bee enables transfer rather than making embryos or seeds.')
add('Schematische Blüte einer windbestäubten Pflanze: unauffällige Blütenhülle, frei exponierte Staubbeutel, vergrößerte Narbenflächen sowie Fruchtknoten und Samenanlagen. Ein Fehlermodell behauptet: Jede Blüte braucht bunte Kronblätter und aus einem Pollenkorn wird unmittelbar eine ganze Frucht.',
 'Schematic wind-pollinated flower: inconspicuous covering, exposed anthers, enlarged stigmas, ovary and ovules. A faulty model says every flower needs colourful petals and a pollen grain immediately becomes a whole fruit.',
 'Ordne Blütenbestandteile funktionell und korrigiere die Aussagen zu Bestäubung, Befruchtung, Samen und Frucht.',
 'Assign flower parts by function and correct pollination, fertilization, seed and fruit claims.',
 'Staubbeutel liefern Pollen, exponierte Narben können ihn aufnehmen; die Hülle muss nicht auffällig sein, wenn Wind den Transport übernimmt. Griffel beziehungsweise entsprechender Leitweg verbinden Narbe mit Samenanlagen im Fruchtknoten. Pollenschlauch und männliche Keimzelle ermöglichen Befruchtung einer Eizelle. Samen stammen aus Samenanlagen und enthalten den Embryo; die Frucht entsteht aus dem Fruchtknoten. Pollen ist weder eine fertige Frucht noch gleichbedeutend mit erfolgter Befruchtung.',
 'Anthers provide pollen and exposed stigmas can receive it; coverings need not be conspicuous when wind transfers pollen. The style or corresponding route connects stigma to ovules in the ovary. Pollen tubes and male gametes enable fertilization of an egg. Seeds derive from ovules and contain embryos; fruit develops from the ovary. Pollen is neither ready-made fruit nor evidence that fertilization has occurred.')

#9 Wild/use distinctions and an actually usable bounded key.
add('Eigener kurzer Bestimmungsschlüssel für drei vorgegebene Pflanzen: A hat weiße Zungenblüten um eine gelbe Mitte und niedrige Rosettenblätter; B hat dreiteilige Blätter und runde Blütenköpfe; C besitzt windende Sprosse, dreiteilige Blätter und Hülsen. Vorgabe: A=Gänseblümchen, B=Klee, C=Gartenbohne. A/B wachsen spontan, C wird für Ernte angebaut.',
 'Own short key for three supplied plants: A has white ray florets around a yellow centre and low rosette leaves; B has three-part leaves and round flower heads; C has twining shoots, three-part leaves and pods. Given identities: A=daisy,B=clover,C=garden bean. A/B grow spontaneously and C is cultivated for harvest.',
 'Nutze die Merkmale zur begrenzten Bestimmung und unterscheide Wild- und Nutzpflanzen mit einer Grenze dieser Einteilung.',
 'Use traits for bounded identification and distinguish wild/crop plants with a limit of this classification.',
 'Der Schlüssel unterscheidet in diesem vorgegebenen Dreiersatz A über Blütenstand/Rosette, B über Blütenkopf/Blätter und C zusätzlich über Spross/Hülse. Spontan wachsende Beispiele sind hier Wildpflanzen, die angebaute Bohne Nutzpflanze. Nutzen ist ein menschlicher Kontext: Klee kann auch als Futter kultiviert werden. Der vereinfachte Schlüssel identifiziert nicht alle ähnlich aussehenden Arten und begründet keine Essbarkeit.',
 'Within this supplied set A is distinguished by flower head/rosette, B by heads/leaves and C additionally by stems/pods. Spontaneously growing examples are wild plants here; cultivated beans are crops. Use is a human context: clover can also be grown for fodder. The simplified key does not identify every lookalike or establish edibility.')
add('Vorgegebene Blätter: X hat einen ungeteilten gelappten Umriss, Y ein herzförmiges Blatt, Z viele schmale Fiederblättchen. Eine begrenzte Bildtabelle ordnet X=Eiche,Y=Linde,Z=Esche zu. Eine Linde wächst wild am Waldrand, eine andere wird im Garten gezielt für einen Nutzungszweck gepflanzt.',
 'Supplied leaves: X is a single lobed blade,Y heart-shaped,Z has many narrow leaflets. A bounded picture table maps X=oak,Y=linden,Z=ash. One linden grows wild at woodland edge and another is intentionally planted in a garden for a use.',
 'Nutze die Tabellenmerkmale, unterscheide Vorkommen und Nutzung und erläutere Grenzen einer Bestimmung anhand eines einzigen Merkmals.',
 'Use the table traits, distinguish occurrence/use and explain limits of identifying from a single trait.',
 'Im begrenzten Satz passen X zur gelappten Eichenform,Y zur Linde und Z zum zusammengesetzten Eschenblatt. Dieselbe Pflanzenart kann wild vorkommen und genutzt werden; die Nutzungsrolle ist keine eigene Abstammungsgruppe. Weitere Merkmale wie Blattstellung, Blüte oder Frucht und passende Bestimmungshilfen stärken eine Zuordnung. Eine einzelne Form ist kein universeller Schlüssel oder Nachweis sicherer Verwendbarkeit.',
 'Within this bounded set X matches lobed oak leaves,Y linden and Z compound ash leaves. The same species can occur wild and be used; a human use role is no separate lineage. Additional traits such as arrangement, flowers/fruits and suitable guides strengthen identification. One shape is neither a universal key nor proof of safe use.')

#10 Bird/fish choice, feature function habitat in both examples.
add('Vorgegebener Vogelfall: Flügel mit Federn, leichter stabiler Skelettbau und kräftige Flugmuskulatur. Lebensraum verlangt Bewegung durch Luft und Landung auf Ästen. Eine vergleichende Fischskizze zeigt Stromlinienform und Kiemen; sie ist hier nur kursorischer Vergleich.',
 'Supplied bird case: feathered wings, light stable skeleton and strong flight muscles. Habitat demands movement through air and landing on branches. A fish sketch shows streamlining/gills and serves only brief comparison here.',
 'Deute Vogelbau und Funktionen als Angepasstheit an Lebensraum und erläutere einen Unterschied zum Fisch ohne beide Themen als verpflichtende Vertiefung auszugeben.',
 'Interpret bird structures/functions as habitat adaptations and give a fish contrast without asserting mandatory depth in both topics.',
 'Federflächen und Flügelbewegung ermöglichen aerodynamische Kräfte, geringere Masse bei Stabilität mindert Anforderungen an Flugleistung und Muskulatur liefert Bewegung. Füße und Gelenke unterstützen Landung/Halt. Der Fisch bewegt sich durch Wasser und nutzt Kiemen für dortigen Austausch; Unterschiede entsprechen anderen Medien. Nicht jeder Vogel fliegt und Anpassung ist keine zielgerichtete Umweltanweisung. HE6.2 sieht Vogel oder Fisch als Vertiefung vor.',
 'Feather surfaces and wing motion enable aerodynamic forces; reduced mass with stability lowers flight demands and muscles power movement. Feet/joints assist landing/grip. Fish move through water and use gills for exchange there; different media favour different traits. Not every bird flies and adaptation is no purposeful environmental command. HE6.2 specifies bird or fish as the in-depth choice.')
add('Vorgegebener Fischfall: stromlinienförmiger Körper, Flossen und dünne Kiemenflächen. Wasser ist das Bewegungs- und Atemmedium. Eine Vogelskizze mit Flügel und Feder dient nur dem kurzen Gegenvergleich; der gewählte Schwerpunkt ist Fisch.',
 'Supplied fish case: streamlined body,fins and thin gill surfaces. Water is the movement/respiratory medium. A bird wing/feather sketch gives only brief contrast; fish is the selected focus.',
 'Erkläre Bau-Funktions-Merkmale als Angepasstheit und begrenze die Aussage gegenüber einem anderen Lebensraum.',
 'Explain structure/function traits as adaptations and bound conclusions for another habitat.',
 'Stromlinienform mindert Wasserwiderstand, Flossen dienen Vortrieb und Steuerung; dünne große Kiemenflächen ermöglichen Austausch mit vorbeiströmendem Wasser. Außerhalb des Wassers fehlen passende Austauschbedingungen; eine Vogelfeder löst dagegen andere Luft-/Wärmefunktionen. Verschiedene Lebensräume begünstigen verschiedene Merkmale, ohne dass einzelne Tiere nach Bedarf die Form ändern. Fischvertiefung und knapper Vogelvergleich entsprechen der Quellenwahl.',
 'Streamlining reduces water resistance,fins propel/steer and large thin gill surfaces exchange gases with flowing water. Appropriate exchange conditions are absent out of water; feathers serve other aerial/thermal functions. Different habitats favour different traits rather than individuals changing form on demand. Fish depth with brief bird comparison respects the source choice.')

#11 Reproductive strategies: differences include conditions and all basic components.
add('Hypothetische Vogelarten: A verteidigt ein Revier, besitzt auffällige Balz und legt wenige Eier in betreutes Nest. B hat gemeinschaftliche Balzplätze, später anderes Revierverhalten und mehr Eier mit geringerem Aufwand je Nachkomme. Keine tatsächlichen Erfolgsdaten liegen vor.',
 'Hypothetical birds: A defends a territory,has conspicuous courtship and few eggs in a tended nest. B has communal courtship sites,later different territorial behaviour and more eggs with less effort per offspring. No actual success data are supplied.',
 'Vergleiche Revierbildung, Balz, Paarung und Brutpflege/Nachkommenzahl und erläutere die bedingte Strategieaussage.',
 'Compare territories,courtship,mating and care/offspring counts,and explain conditional strategy conclusions.',
 'Revierverhalten kann Zugang zu Nahrung oder Partnern beeinflussen; Balz vermittelt Partnerwahl und Paarung ermöglicht Befruchtung. Wenige Nachkommen mit höherem Pflegeaufwand können unter passenden Bedingungen höhere individuelle Überlebenschancen haben; höhere Eizahl verteilt Investition anders. Gemeinschaftliche Balz ersetzt nicht jede spätere Revierfunktion. Ohne Umwelt-/Erfolgsdaten ist keine Strategie allgemein überlegen und Paarungs-/Pflegeformen variieren zwischen Vogelarten.',
 'Territories can affect food/partner access; courtship supports mate choice and mating enables fertilization. Fewer offspring with more care may gain survival advantages under suitable conditions; more eggs distribute investment differently. Communal courtship does not remove every later territorial role. Without environmental/success data no strategy is universally superior,and mating/care vary among birds.')
add('Synthetische Fischstrategien: C bildet zur Fortpflanzung ein kleines Revier, zeigt Balz und bewacht ein Nest mit Eiern. D laicht mit vielen Partnern in offenem Wasser und produziert sehr viele Eier ohne weitere Bewachung. Alle Zahlen sind bewusst nicht als reale Artmessung angegeben.',
 'Synthetic fish strategies: C establishes a small breeding territory, courts and guards an egg nest. D spawns with many partners in open water,producing many eggs without later guarding. No figures are presented as real species measurements.',
 'Vergleiche Fortpflanzungsstrategien einschließlich Revier, Balz/Paarung und Pflege und korrigiere „Fische betreiben nie Brutpflege“.',
 'Compare strategies including territory,courtship/mating and care; correct “fish never care for offspring”.',
 'C investiert in Ressourcen-/Partnerzugang und Nestschutz; D investiert stärker in Eizahl und Verteilung. Laichen beschreibt Ei-/Samenzellabgabe, nicht automatisch dieselbe Paarungssituation wie bei Vögeln. Pflege kann Eiverluste mindern, kostet aber Zeit/Energie; viele unbewachte Eier haben unter manchen Bedingungen Erfolg durch ihre Zahl. Die Beispiele widerlegen die Pauschalbehauptung, ohne eine universell beste Strategie oder identische Befruchtungsweise aller Fische zu beweisen.',
 'C invests in resource/partner access and nest defence; D invests more in egg number/dispersal. Spawning means releasing eggs/sperm and need not match bird mating circumstances. Care may reduce egg losses but costs time/energy; many unguarded eggs may succeed through number under some conditions. The examples refute the blanket claim without establishing a universally best strategy or identical fertilization in every fish.')

#12 Lightweight stable body and feather functions.
add('Modell eines fliegenden Vogels: einige Knochen sind luftgefüllt und durch Verstrebungen stabilisiert; weitere Knochen sind verbunden. Eine Feder besitzt Schaft, Äste und feine verzahnte Strukturen, die eine zusammenhängende Fahne bilden.',
 'Flying-bird model: some bones are air-filled and braced,and others are fused. A feather has shaft,branches and fine interlocking structures forming a coherent vane.',
 'Erkläre Leichtbauweise und Federfunktion für Flug und Wärmehaushalt und korrigiere „alle Knochen sind leere schwache Röhren“.',
 'Explain lightweight construction/feathers for flight and thermal balance; correct “all bones are empty weak tubes”.',
 'Leichtbau verbindet Masseverminderung mit Tragfähigkeit; Verstrebung und verbundene Teile erhöhen Stabilität. Die Fahne schafft geeignete Flächen für Flugkräfte, Schaft/Äste tragen diese Struktur. Gefieder kann Luft einschließen und isolieren; verschiedene Federtypen erfüllen unterschiedliche Aufgaben. Nicht alle Knochen sind hohl und leichter Bau bedeutet nicht fehlende Festigkeit. Federform allein erklärt nicht den gesamten Flug.',
 'Light construction combines reduced mass with strength; braces/fused parts improve stability. Vanes provide surfaces for aerodynamic forces and shafts/branches support them. Plumage can trap insulating air; different feather types serve different roles. Not all bones are hollow and lightness does not mean absence of strength. Feather shape alone does not explain the whole of flight.')
add('Schematischer Gegenvergleich: Ein fliegender Vogel hat große geordnete Schwungfedern und tragfähigen leichten Knochenbau. Ein nichtfliegender Vogel besitzt ebenfalls Federn, deren Funktion hier vorwiegend Isolation und Schutz ist. Eine beschädigte Fahne hat Lücken zwischen Ästen.',
 'Schematic contrast: a flying bird has large organized flight feathers and a strong light skeleton. A flightless bird also has feathers,chiefly providing insulation/protection here. A damaged vane has gaps between branches.',
 'Verbinde Leichtbau und Federbau mit Funktionen und beurteile „Federn bedeuten immer Flugfähigkeit“.',
 'Connect lightweight body/feather structure to functions and assess “feathers always mean flight”.',
 'Geringe Masse bei hinreichender Festigkeit und stabile Federflächen unterstützen Flug, zusammen mit Flügelgestalt und Muskelarbeit. Lücken können die zusammenhängende Fläche beeinträchtigen. Federn besitzen auch Wärme-/Schutzfunktionen, weshalb ihre Anwesenheit keine Flugfähigkeit beweist. Federtypen unterscheiden sich im Bau; der Gegenvergleich ist keine Behauptung identischen Knochenbaus oder identischer Flugleistung aller Vögel.',
 'Low mass with sufficient strength and coherent feather surfaces support flight together with wing form/muscles. Gaps can impair surface continuity. Feathers also provide thermal/protective functions,so their presence does not prove flight. Types differ structurally; this contrast asserts neither identical skeletons nor flight performance in all birds.')

#13 Streamlining, gills, buoyancy are distinct mechanisms.
add('Typisches Knochenfischmodell: spindelförmiger Körper, Flossen, Wasser strömt durch Mund über Kiemen und verlässt den Kiemendeckel; daneben liegt eine gasgefüllte Schwimmblase. Ein Diagramm verwechselt Schwimmblase mit Hauptatemorgan.',
 'Typical bony-fish model: tapered body,fins,water entering mouth across gills and leaving under operculum,and a gas-filled swim bladder. A diagram mistakes the bladder for the main respiratory organ.',
 'Beschreibe Stromlinienform, Kiemen und Schwimmblase jeweils mit Funktion und korrigiere die Verwechslung.',
 'Describe streamlining,gills and swim bladder by function and correct the confusion.',
 'Stromlinienform begrenzt Wasserwiderstand; Flossen erzeugen oder lenken Bewegung. Kiemen bieten große dünne durchblutete Flächen für Austausch von gelöstem O2 und CO2 mit Wasser. Die gasgefüllte Schwimmblase beeinflusst Auftrieb und Haltung in der Wassersäule; sie ist in diesem typischen Modell nicht der Hauptort des Gasaustauschs. Die drei Funktionen sind verschieden, und nicht alle Fischarten besitzen eine Schwimmblase.',
 'Streamlining limits water resistance; fins generate/direct movement. Gills have large thin perfused surfaces exchanging dissolved O2/CO2 with water. A gas-filled bladder affects buoyancy and position in the water column rather than being the main gas-exchange site in this typical model. The three mechanisms differ,and not every fish has a swim bladder.')
add('Schematischer Fisch bei gleicher Masse: geringeres Gasvolumen in seiner vorhandenen Schwimmblase vermindert den Auftrieb. Kiemen werden weiter von Wasser durchströmt; eine stumpfe statt stromlinienförmige Modellform muss bei gleicher Bewegung mehr Wasser verdrängen.',
 'Schematic fish at equal mass: smaller gas volume in its bladder reduces buoyancy. Water still flows across gills; a blunt rather than streamlined model shape must move more water at matching motion.',
 'Ordne die drei Bau-Funktions-Bezüge und erkläre, warum Auftriebsänderung nicht gleichbedeutend mit Gasaustausch ist.',
 'Assign the three structure/function relationships and explain why changing buoyancy is distinct from gas exchange.',
 'Die Modellform beeinflusst Widerstand, die Kiemen ermöglichen O2-Aufnahme/CO2-Abgabe über dünne Flächen und das Gasvolumen beeinflusst verdrängtes Wasser beziehungsweise Auftrieb. Auftrieb erlaubt Höhenhaltung, erzeugt aber keinen Sauerstoff für Gewebe. Geeignete Ventilation/Blutversorgung bleiben für Kiemen nötig. Der Fall beschreibt einen Fisch mit Schwimmblase und keine universelle Regel für alle Fische oder einen exakten Tauchmechanismus.',
 'Body form affects drag,gills exchange O2/CO2 across thin surfaces,and gas volume affects displaced water/buoyancy. Buoyancy permits depth control rather than generating tissue oxygen. Gill ventilation/perfusion remain necessary. This case concerns a fish with a bladder rather than a universal fish rule or exact diving mechanism.')

#14 Reptile and bird embryonic development.
add('Eigene Vergleichsbilder: Eidechsen- und Hühnerei enthalten Embryo, Dotter und schützende Eihüllen. Beide Embryonen entwickeln sich im Ei zu einem Jungtier mit grundlegender Körperform; das Hühnerei wird bebrütet, die gezeigte Eidechse legt Eier an einen geeigneten Ort.',
 'Own comparison: lizard/chicken eggs contain embryo,yolk and protective envelopes. Both embryos develop into young with the basic adult form; chicken eggs are incubated and the illustrated lizard places eggs at a suitable site.',
 'Beschreibe Reptilienentwicklung und vergleiche sie mit Vogelentwicklung anhand gemeinsamer Strukturen und unterschiedlicher Versorgung.',
 'Describe reptile development and compare bird development through shared structures and differing conditions/care.',
 'Befruchtung geht Embryonalentwicklung voraus; Dotter versorgt den Embryo, Hüllen schützen und ermöglichen geeignetes Milieu. Junge Eidechse und Küken entstehen ohne freilebende Kaulquappenphase. Beide besitzen den amniotischen Grundbauplan, während Brutpflege und Temperaturversorgung im Beispiel differieren. Nicht alle Reptilien legen Eier und nicht jede Art hat dieselbe Hüllenhärte; der Vergleich bleibt auf die vorgegebenen Beispiele begrenzt.',
 'Fertilization precedes embryonic development;yolk supplies the embryo and envelopes protect/maintain conditions. Young lizards/chicks form without free-living tadpole stages. Both share the amniotic plan,while care/thermal conditions differ here. Not every reptile lays eggs or has equally hard shells; comparisons remain bounded to the supplied examples.')
add('Fehlerschema: Aus einem Reptilienei schlüpft angeblich eine fischartige Larve mit Kiemen, aus dem Vogelei ein fertiger erwachsener Vogel. Korrekte Vergleichshinweise nennen innere Befruchtung, Embryonalentwicklung mit Dotterversorgung und Wachstum nach dem Schlupf.',
 'Faulty scheme: a reptile egg supposedly hatches a fish-like gilled larva,and a bird egg a fully adult bird. Correct cues name internal fertilization,yolk-supported embryos and growth after hatching.',
 'Korrigiere die Entwicklungsschritte und vergleiche Reptilien- und Vogelentwicklung, ohne aus einer Zeichnung alle Arten zu verallgemeinern.',
 'Correct stages and compare reptile/bird development without generalizing all species from one picture.',
 'Bei den eierlegenden Beispielen entwickelt sich der Embryo nach innerer Befruchtung innerhalb schützender Hüllen mit Dotterversorgung. Geschlüpfte Jungtiere besitzen eine Grundkörperform, wachsen aber weiter und sind nicht sofort erwachsen. Eine typische freilebende Kiemenlarve gehört hier nicht zum Reptilienablauf. Pflege-/Temperaturbedingungen unterscheiden sich zwischen Beispielen; Ausnahmen wie lebendgebärende Reptilien verhindern eine universelle Eierregel.',
 'In these egg-laying examples embryos develop after internal fertilization inside protective envelopes with yolk supply. Hatchlings have the basic body form but continue growing rather than being immediately adult. A typical free-living gilled larva is not part of this reptile sequence. Care/thermal conditions differ; exceptions such as live-bearing reptiles prevent a universal egg-laying rule.')

#15 Behavioural temperature regulation, explicit limits.
add('Synthetisches Eidechsenmodell: morgens ist Luft kühl, sonnenbeschienener Stein wärmer; später wird der Stein sehr heiß, ein Schattenplatz bleibt kühler. Das Tier kann zwischen Orten wechseln. „Wechselwarm bedeutet immer kalt“ steht als Fehleraussage dabei.',
 'Synthetic lizard model: cool morning air with a warmer sunlit rock;later the rock becomes very hot and shade cooler. The animal can move between sites. “Ectothermic always means cold” is a faulty claim.',
 'Beschreibe Verhaltensstrategien zur Körpertemperaturregulation und deren Grenzen.',
 'Describe behavioural strategies for temperature regulation and their limits.',
 'Sonnenbaden kann äußere Wärmeaufnahme und geeignete Aktivität fördern; später kann Schatten Wärmebelastung mindern. Körperhaltung und Ortswechsel beeinflussen Austausch. Wechselwarme Tiere sind nicht ständig kalt; ihre Temperatur hängt stärker von Außenbedingungen ab. Ohne geeignete Plätze oder bei extremen Bedingungen sind Regulationsmöglichkeiten begrenzt. Das Tier besitzt keinen beliebig einstellbaren inneren Heizregler wie das Fehlermodell behaupten könnte.',
 'Basking can increase external heat gain and suitable activity;later shade reduces thermal load. Posture/site choices affect exchange. Ectotherms are not always cold;their temperature depends more strongly on external conditions. Without suitable sites or under extremes,their options are limited. The animal does not possess an arbitrarily adjustable internal heater.')
add('Vorgegebener Landschaftsplan: offener heller Stein, kühler Fels-Spalt, Vegetationsschatten und Wasserfläche. Bei kaltem bedecktem Wetter bleiben alle nutzbaren Plätze kühl. Eine Werbeaussage verspricht, ein Reptil könne durch Willenskraft immer dieselbe Körpertemperatur halten.',
 'Supplied habitat plan: open bright rock,cool crevice,vegetation shade and water. During cold overcast weather all accessible sites remain cool. An advertisement says reptiles can always maintain one temperature by willpower.',
 'Wähle bedingte Verhaltensoptionen und erkläre Aktivitäts- und Umweltgrenzen der Regulation.',
 'Select conditional behavioural options and explain environmental/activity limits.',
 'Bei Sonne kann offener Stein Wärmeaufnahme unterstützen; bei Überwärmung bieten Schatten oder Spalt geringere Wärmebelastung. Die Wahl richtet sich nach tatsächlicher Umgebung und artspezifischen Bedingungen, nicht nach einem universellen Wert. Wenn alle Orte kühl sind, kann Ortswechsel fehlende Wärme nicht erzeugen und Aktivität begrenzt sein. Wasseraufenthalt ist nicht für jede Reptilienart geeignete Kühlung. Wille erklärt weder äußere Wärmebilanz noch unbegrenzte Regulation.',
 'Sunlit rock may help heat gain and shade/crevices reduce excessive heat. Choices depend on actual conditions/species rather than one universal value. When every site is cold,moving cannot create absent heat and activity may be constrained. Entering water is not suitable cooling for every reptile. Willpower explains neither external heat balance nor unlimited control.')

#16 Thermal pit and eye cooperation.
add('Modell eines Klapperschlangenkopfes: Grubenorgan zwischen Nasenöffnung und Auge, thermisch empfindliche Membran; ein warmes kleines Tier liegt vor kühlerem Hintergrund. Auge liefert sichtbare Form-/Bewegungshinweise; Grubenorgan reagiert auf Strahlungsunterschiede.',
 'Rattlesnake-head model: pit between nostril/eye with thermally sensitive membrane;a warm small animal lies against cooler background. Eye supplies visible form/motion cues and pit responds to radiation differences.',
 'Erläutere Leistung des Wärmesinnesorgans und Zusammenarbeit mit dem Auge einschließlich einer Grenze.',
 'Explain thermal-pit function and cooperation with the eye,including a limit.',
 'Infrarotstrahlung kann die Membran unterschiedlich erwärmen und sensorische Signale auslösen. Unterschiede über das Grubenorgan unterstützen räumliche Hinweise auf warme Objekte; das Auge liefert ergänzende sichtbare Informationen. Zusammen können Hinweise die Orientierung unterstützen, besonders bei schwacher Beleuchtung. Das Organ sieht weder Blut im Körper noch Gedanken und ist nicht mit dem Auge identisch. Geringe thermische Unterschiede oder ungünstige Bedingungen begrenzen den Kontrast.',
 'Infrared radiation can warm the membrane differentially and trigger sensory signals. Pit signals support spatial cues to warm objects while eyes provide complementary visible information. Together they support orientation,particularly in weak light. The organ detects neither blood inside bodies nor thoughts and is distinct from the eye. Small thermal differences or adverse conditions limit contrast.')
add('Synthetischer Vergleich zweier Situationen:1 schwaches sichtbares Licht, warmer Körper vor kühlem Hintergrund;2 ausreichend Licht, Körper und Hintergrund ähnlich warm. Ein Fehlervorschlag nennt das Auge überflüssig und schreibt jeder Schlange dieses Organ zu.',
 'Synthetic comparison:1 weak visible light with a warm body against cool background;2 adequate light with body/background similarly warm. A faulty claim says eyes are unnecessary and all snakes share this organ.',
 'Vergleiche Beiträge von Auge und Wärmesinnesorgan und korrigiere die Verallgemeinerungen.',
 'Compare visual/thermal contributions and correct generalizations.',
 'In1 kann thermischer Kontrast nützliche Hinweise liefern, obwohl die sichtbare Darstellung schwach ist; in2 liefert das Auge Form/Bewegung, während Wärmekontrast geringer sein kann. Beide Signalarten ergänzen sich, keine ersetzt jede Leistung der anderen. Grubenorgane gehören bestimmten Schlangengruppen, nicht jeder Schlange. Unterschiedliche Beiträge belegen keinen universellen Kontrastwert oder eine perfekte dreidimensionale Bildkamera im Grubenorgan.',
 'In1 thermal contrast can help despite weak visible information;in2 eyes supply shape/motion while thermal contrast may be lower. Both modalities complement one another rather than replacing every function. Pit organs occur in particular snake groups rather than all snakes. Differing contributions establish neither a universal contrast value nor a perfect three-dimensional camera in the pit.')

#17 Adult frog skin and lung gas exchange.
add('Schematischer erwachsener Frosch: dünne feuchte durchblutete Haut und einfache Lungen. Am Teichrand kann Luft über Mundraumbewegungen in die Lungen gelangen; im Wasser steht Haut weiterhin im Austausch mit Umgebung.',
 'Adult-frog model: thin moist perfused skin and simple lungs. At pond edge,mouth-floor movements can move air to lungs;in water skin continues exchange with the surroundings.',
 'Erkläre Sauerstoffversorgung über Haut und Lunge und verbinde Bau, Stoffgefälle und Regulationsmöglichkeiten.',
 'Explain oxygen supply through skin/lungs and connect structure,gradients and regulatory possibilities.',
 'O2 kann entlang geeigneter Gefälle über dünne feuchte Haut beziehungsweise Lungenflächen ins Blut gelangen, CO2 in Gegenrichtung. Hautdurchblutung und Lungendurchlüftung beeinflussen Beiträge; die Frosch-Mundbodenpumpe erneuert Luft. Feuchte Haut unterstützt Diffusion, Austrocknung beeinträchtigt sie. Beitrag und Bedarf hängen von Temperatur/Aktivität ab; keine Oberfläche liefert unter allen Bedingungen unbegrenzt O2. Erwachsene Frösche sind nicht allein durch äußere Kiemen versorgt.',
 'O2 can move down suitable gradients across thin moist skin/lung surfaces into blood,with CO2 outward. Skin perfusion and lung ventilation affect contributions;the mouth-floor pump renews air. Moisture aids diffusion and drying impairs it. Contributions/demand depend on temperature/activity;neither surface supplies unlimited O2 in every condition. Adult frogs are not sustained solely by external gills.')
add('Hypothetisches Modell: A sitzt feucht am Ufer mit belüfteten Lungen,B ist unter Wasser bei niedrigem Stoffwechselbedarf,C hat austrocknende Haut. Kein reales Tier wurde diesen Bedingungen ausgesetzt.',
 'Hypothetical model:A remains moist at shore with ventilated lungs,B is underwater with low metabolic demand,C has drying skin. No real animal was exposed to these conditions.',
 'Vergleiche Haut-/Lungenbeiträge und Grenzen, ohne das Modell als eigenen Tierversuch auszugeben.',
 'Compare skin/lung contributions and limits without presenting this as an animal experiment.',
 'A kann beide Austauschwege nutzen;B erhält keinen unbegrenzten erneuerten Luftstrom zur Lunge und ist auf vorhandene beziehungsweise Hautaustauschmöglichkeiten unter passenden Gefällen angewiesen. Bei niedrigem Bedarf können Hautbeiträge wichtiger sein, ohne universelle Tauchdauer abzuleiten. C verliert günstige Hautdiffusionsbedingungen. Durchblutung, Ventilation und Umweltkonzentration beeinflussen O2-Versorgung/CO2-Abgabe. Die Daten bleiben hypothetisch und rechtfertigen keinen belastenden Schulversuch.',
 'A can use both pathways;B lacks unrestricted renewed air ventilation and relies on available/skin exchange under suitable gradients. Skin contributions may matter more at low demand without establishing universal dive duration. C loses favourable skin diffusion conditions. Perfusion,ventilation and environmental concentrations affect O2 supply/CO2 removal. The model remains hypothetical and justifies no stressful school experiment.')

#18 Interpret supplied endocrine results, no live experiment instruction.
add('Vorgegebene synthetische historische Versuchslogik: gleichalte Kaulquappen entwickeln ohne zusätzlichen Eingriff den üblichen Zeitverlauf; eine Gruppe mit verminderter Schilddrüsenhormonwirkung entwickelt spätere Metamorphose; Wiederherstellung der Wirkung nähert den Verlauf dem Kontrollmodell an. Keine reale Durchführung ist behauptet.',
 'Supplied synthetic historical experiment logic: same-age tadpoles follow an ordinary developmental course;reduced thyroid-hormone action delays metamorphosis;restoring action moves timing toward the control model. No actual performance is claimed.',
 'Beschreibe Metamorphose und deute die Ergebnisse als hormonelle Steuerung einschließlich der Grenzen des Modells.',
 'Describe metamorphosis and interpret results as endocrine control,including model limits.',
 'Bei Metamorphose ändern sich etwa Gliedmaßen, Schwanz und Atem-/Lebensweise koordiniert. Der Vergleich stützt eine steuernde Rolle der Schilddrüsenhormonwirkung, weil Verminderung und Wiederherstellung unterschiedliche Verläufe zeigen. Gleiche Ausgangsbedingungen/Kontrolle begrenzen alternative Erklärungen, beweisen aber keine vollständige alleinige Steuerung jedes Details. Material ist synthetisch; keine Hormonbehandlung lebender Tiere wird angeleitet oder als durchgeführt behauptet.',
 'Metamorphosis coordinates changes in limbs,tail and respiratory/life patterns. Reduced/restored action producing different courses supports a controlling role of thyroid hormones. Matched starting conditions/controls limit alternatives without proving exclusive control of every detail. Material is synthetic;no live-animal hormone treatment is instructed or claimed performed.')
add('Eigenes Ergebnismodell: Gruppe1 zeigt Hinterbeinbildung vor Schwanzrückbildung; Gruppe2 mit früher verstärktem Hormonsignal erreicht entsprechende Stadien früher. Temperatur und Futter sind modellhaft gleich; einzelne Tiere reagieren unterschiedlich. Eine Behauptung nennt Hormone Nahrung, die direkt zu Beinen wird.',
 'Own result model:group1 forms hindlimbs before tail regression;group2 with earlier stronger hormone signalling reaches corresponding stages sooner. Model temperature/food are equal and individuals vary. A claim calls hormones food directly becoming legs.',
 'Deute Stadien und Versuchsvergleich, erkläre Signalwirkung und begrenze die Kausalaussage.',
 'Interpret stages/comparison,explain signalling and bound causality.',
 'Metamorphose umfasst geordnete Umbauten vom Larven- zum Jungfrosch; frühere Stadien in2 passen zu verändertem zeitlichem Steuersignal. Hormone vermitteln Information an geeignete Zellen und sind nicht das Baumaterial der Beine. Gleichhaltung/Kontrolle unterstützen die Deutung, individuelle Unterschiede und Modellannahmen begrenzen exakte Prognosen. Der Vergleich beweist nicht, dass stärkere Signale beliebig bessere Entwicklung erzeugen oder jeder andere Faktor unwichtig ist.',
 'Metamorphosis reorganizes the larva into a juvenile frog;earlier stages in2 fit altered timing signals. Hormones carry information to responsive cells rather than being leg building material. Matching/controls support interpretation,but individual differences/model assumptions limit exact predictions. This proves neither stronger signals always improve development nor every other factor is irrelevant.')

#19 Egg counts and care forms are conditional comparisons.
add('Hypothetische Amphibienstrategien:A legt viele Eier frei ins Wasser und bewacht sie nicht;B trägt eine kleinere Anzahl befruchteter Eier und hält sie in geeigneter Umgebung. Umwelt-/Überlebensdaten sind nicht gegeben.',
 'Hypothetical amphibian strategies:A releases many eggs into water without guarding;B carries fewer fertilized eggs and maintains suitable surroundings. No environmental/survival data are supplied.',
 'Vergleiche Eizahl, Brutpflegeform und Investition und erläutere Grenzen einer Erfolgsbewertung.',
 'Compare egg number,care form/investment and limits of assessing success.',
 'A verteilt Investition auf viele Eier, die jeweiligen Umweltgefahren ausgesetzt sind;B investiert stärker in Transport/Schutz je Ei. Pflege kann geeignete Bedingungen erhalten und Verlust vermindern,kostet aber Zeit/Energie und schützt nicht gegen alles. Aus Eizahl allein folgt weder höherer Gesamterfolg noch sichere individuelle Überlebenschance. Beide sind Amphibienbeispiele;nicht alle Arten zeigen dieselbe Form oder einen universellen Zahl-Pflege-Zusammenhang.',
 'A spreads investment over many eggs exposed to environmental hazards;B invests more transport/protection per egg. Care can sustain suitable conditions and reduce loss but costs time/energy and cannot protect against everything. Egg number alone predicts neither greater total success nor certain individual survival. These amphibian examples establish no universal care form or count–care relationship.')
add('Eigenes Modell:ArtC bewacht ein kleines Gelege an feuchtem Ort;ArtD hat viele Wasser-Eier mit wenig weiterer Pflege. Für einen gedachten gemeinsamen Vergleich seien ÜberlebensanteileC0.5undD0.05 gegeben, EizahlenC20undD400. Dies sind ausdrücklich keine realen Artwerte.',
 'Own model:speciesC guards a small clutch at a moist site;D has many aquatic eggs with little later care. Hypothetical survival fractions areC0.5,D0.05,with C20eggs,D400. These are no actual species figures.',
 'Vergleiche Formen und Eizahlen, deute die bedingten Zahlen und korrigiere „mehr Pflege erzeugt immer mehr überlebende Nachkommen“.',
 'Compare forms/counts,interpret conditional figures and correct “more care always yields more surviving offspring”.',
 'Im gegebenen Modell ergeben sich erwartete Zahlen10fürC und20fürD;höherer Anteil je Ei bedeutet nicht automatisch größere Gesamtzahl. C betreibt Bewachung/D wenig Pflege mit anderer Investitionsverteilung. Die Zahlen sind bedingte Erwartungen und keine Messung oder sichere Einzelgelege-Prognose. Habitat,Gefahren und Pflegekosten können Ergebnisse ändern;keine Strategie ist überall überlegen.',
 'Under the supplied model expected survivors are10forC and20forD;higher per-egg fraction does not automatically mean greater total number. C guards while D provides little care with different investment. Figures are conditional expectations rather than measurements or certain predictions for an individual clutch. Habitat,hazards and care costs can alter outcomes;neither strategy is best everywhere.')

#20 Apply husbandry requirements to real-case decisions, not animal toy needs.
add('Fiktiver Kaninchen-Haltungsplan:P bietet kleinen leeren Einzelkäfig und nur gelegentlich Futter;Q bietet ausreichend großen sicheren Bewegungsraum,artgemäße Sozialmöglichkeiten,Heu,Wasser,Rückzug und regelmäßige Pflege. Dies sind schematische Fälle,keine zertifizierte Größen-/Tierarztempfehlung.',
 'Fictional rabbit-care plans:P offers a tiny empty solitary cage with occasional food;Q offers sufficient secure movement space,species-appropriate social opportunities,hay,water,refuge and regular care. These are schematic cases rather than certified sizing/veterinary advice.',
 'Wende Kenntnisse zu Physiologie/Verhalten an,vergleiche die Pläne und leite konkrete verantwortliche Verbesserungen ab.',
 'Apply physiology/behaviour,compare plans and derive concrete responsible improvements.',
 'Ernährung/Wasser,mögliche Bewegung,Sozialverhalten,Ruhe/Rückzug und Hygiene müssen zur Art passen. Q berücksichtigt mehr dieser Bedürfnisse;Pmuss Raum,Futter/Wasser,Sozialmöglichkeiten und Schutz zuverlässig verbessern. Vor Anschaffung werden fachgerechte artspezifische Informationen,Zeit/Kosten und Betreuung geklärt. Allgemeine Kriterien ersetzen keine individuelle Tiergesundheitsprüfung;ein Tier ist kein jederzeit austauschbares Spielzeug.',
 'Food/water,movement,social behaviour,rest/refuge and hygiene must suit the species. Q addresses more needs;P must reliably improve space,food/water,social opportunities and protection. Before acquiring an animal,appropriate species-specific information,time/costs and care arrangements must be established. General criteria do not replace individual animal-health assessment;animals are not disposable toys.')
add('Fiktiver Vergleich:Eine Person möchte die Kaninchenempfehlungen unverändert auf einen Hamster übertragen und tagsüber wiederholt zum Spielen wecken. Ein zweiter Plan recherchiert artspezifische Aktivitätszeit,Raumgestaltung,Rückzug,Ernährung und Sozialverträglichkeit und organisiert Betreuung während Abwesenheit.',
 'Fictional contrast:one person transfers rabbit advice unchanged to a hamster and repeatedly wakes it for daytime play. Another researches species-specific activity,enrichment,refuge,diet/social compatibility and arranges care during absence.',
 'Prüfe die Haltung anhand von Physiologie und Verhalten und wende Anforderungen verantwortungsvoll statt pauschal an.',
 'Assess husbandry using physiology/behaviour and apply requirements responsibly rather than uniformly.',
 'Bedürfnisse verschiedener Arten unterscheiden sich;Sozialhaltung und Aktivitätszeit werden fachgerecht für die konkrete Art geprüft. Häufiges Wecken stört Ruhe und darf nicht mit menschlichem Spielwunsch begründet werden. Geeigneter Raum,Rückzug,Beschäftigung,Futter/Wasser,Hygiene und zuverlässige Vertretung müssen konkret geplant werden. Artspezifische Recherche und gegebenenfalls fachkundige Beratung gehen einer Anschaffung voraus;die Kaninchenliste ist kein universeller Haltungsplan.',
 'Species differ;social housing and activity need appropriate assessment for the animal concerned. Repeated waking disturbs rest and is not justified by human play preferences. Suitable space,refuge,enrichment,food/water,hygiene and dependable substitute care need concrete planning. Species-specific research and professional guidance where needed precede acquisition;the rabbit list is no universal husbandry plan.')

if __name__=='__main__':
    assert len(cases)==40
    out=[]
    for n,g in enumerate(goals,1):
        pair=cases[2*(n-1):2*n]
        for i,c in enumerate(pair,1):
            c['id']=f'flora-fauna20-{n:02d}-case-{i}'
            c['dataStatus']='Own explicitly schematic/synthetic model; no actual measurement,learner work or animal experiment.'
        out.append({'goalId':g['id'],'wholeGoal':g,'cases':pair})
    payload={'schemaVersion':1,'contract':'whole-current-goal-bilingual-material-and-model-answer-author-v1','authorRole':'author,no independent reviewer','goals':out,'activeWrites':0,'humanApproval':False,'realLearnerEvidence':False}
    p=D/'materials/twenty-whole-goals-forty-complete-DEEN-cases.author.json';p.parent.mkdir(exist_ok=True)
    with p.open('x')as f:f.write(json.dumps(payload,ensure_ascii=False,indent=2)+'\n')
    md=['# Zwanzig aktuelle Flora-/Faunaziele: vierzig vollständige zweisprachige Modellfälle','','E1/G1-Autorkandidaten;keine Lernendenleistung oder menschliche Freigabe.','']
    for n,row in enumerate(out,1):
        g=row['wholeGoal'];md.extend([f"## {n}. {g['title']} ({g['id']})",'',g['description'],'',g['descriptionEn'],''])
        for c in row['cases']:
            md.extend([f"### {c['id']}",''])
            for lang in ['de','en']:md.extend([f'**{lang.upper()} Material**','',c['material'][lang],'','**Auftrag / Task**','',c['task'][lang],'','**Modellantwort / Model answer**','',c['modelAnswer'][lang],''])
    with p.with_suffix('.md').open('x')as f:f.write('\n'.join(md))
    print(json.dumps({'wholeCurrentGoals':20,'wholeBilingualCases':40,'activeWrites':0,'strictClosuresClaimed':0}))
