from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,subprocess,shutil
ROOT=Path.cwd().resolve();REL=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-05/chemie-q1-acids-soaps-preservatives-twenty-current-candidate-v1');OWN=ROOT/REL;ISO=ROOT/'tmp/chemie-q1-acids-soaps-preservatives-twenty-native-isolated-20261005-v1'
def read(p):return json.loads(Path(p).read_text())
def sha(p):return 'sha256:'+hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v):
 p=Path(p);p.parent.mkdir(parents=True,exist_ok=True);assert not p.is_symlink();p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
ids=read(OWN/'fourteen-current-source-provenance-and-complete-group-deltas.candidate.json')['goalIds'];bd36='bd36dc58-c93e-5247-9e82-da2f9e4e2bed';assert len(ids)==14 and bd36 not in ids
assert not (ISO/REL/'native-finalbook').exists() and not (OWN/'native-finalbook').exists()
v=read(OWN/'eight-current-visual-inputs-v2.freeze.json')
for r in v['files']:assert sha(ROOT/r.get('frozenCopyPath',r.get('path')))==r['sha256']
book={'schemaVersion':1,'bookId':'de-gym-chemie-m7-full-canonical-review-v1','title':'Lernziel-Review Chemie – kanonischer Gesamtumfang','landscapePath':'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_CHEMIE.de.json','compositionViewPath':'curricula/DE/Gymnasium/quality/goal-description-review/chemie/review-views/chemie-m7-full-canonical.view.json','semanticKindLedgerPath':'curricula/DE/Gymnasium/quality/goal-book-publication/chemie.semantic-kinds.json','goalVisualizationQaPath':'curricula/DE/Gymnasium/quality/goal-visualization-qa/chemie.qa.json','publicationMode':'review','atlasBaseUrl':'https://skillpilot.com/lernzielbuch','evidenceReviewPaths':[],'outputPath':str(REL/'prospective-full-base.book-model.json')}
batch={'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-rollout-batch-config.schema.json','schemaVersion':1,'batchId':'chemie-q1-fourteen-prospective-current-20261005-v1','subject':'chemie','subjectLabel':'Chemie','bookId':'de-gym-chemie-q1-fourteen-prospective-current-20261005-v1','title':'Chemie Q1 – vierzehn aktuelle Ziele und eine gezielte bestehende Seitenbindung','baseGoalBookConfigPath':str(REL/'book.config.json'),'goalIds':ids+[bd36],'outputDirectory':str(REL/'native-finalbook'),'feedbackBaseUrl':'https://skillpilot.com/lernziel-feedback','promptPath':'curricula/DE/Gymnasium/quality/goal-evidence/prompts/goal-description-understanding-evidence-review-v2.md','criteriaPath':'curricula/DE/Gymnasium/quality/goal-evidence/prompts/chemistry-goal-description-understanding-evidence-review-criteria-v1.md','printDerivativeProfile':'bounded-atlas'}
for base in [ROOT,ISO]:write(base/REL/'book.config.json',book);write(base/REL/'batch.config.json',batch)
canonical=read(ISO/book['landscapePath'])
for goal_id in ids+[bd36]:
 g=next(g for g in canonical['goals'] if g['id']==goal_id);link=next(l for l in g['resourceLinks'] if l.get('type')=='goal-visualization' and l.get('role')=='primary');p=ISO/'app/public'/link['url'].lstrip('/')
 if p.is_symlink():content=p.read_bytes();p.unlink();p.write_bytes(content)
 assert not p.is_symlink()
commands=[('final-visual-source-bind',['app/node_modules/.bin/tsx',str(REL/'bind-final-visual-and-source-inputs.mts')],ROOT),('final-source-atlas-generate',['app/node_modules/.bin/tsx','app/scripts/buildGoalBookSourceAtlasInputs.ts','--config','app/scripts/config/goal-books/de-gym-chemistry-national-atlas.inputs.json'],ISO),('final-source-atlas-check',['app/node_modules/.bin/tsx','app/scripts/buildGoalBookSourceAtlasInputs.ts','--config','app/scripts/config/goal-books/de-gym-chemistry-national-atlas.inputs.json','--check'],ISO),('final-fifteen-book-prepare',['app/node_modules/.bin/tsx','app/scripts/materializeGoalDescriptionRolloutBatch.ts','prepare','--config',str(REL/'batch.config.json')],ISO),('final-fifteen-book-check',['app/node_modules/.bin/tsx','app/scripts/materializeGoalDescriptionRolloutBatch.ts','check','--config',str(REL/'batch.config.json')],ISO)]
terminal=[]
for name,args,cwd in commands:
 started=datetime.now(timezone.utc).isoformat();r=subprocess.run(args,cwd=cwd,text=True,capture_output=True);ended=datetime.now(timezone.utc).isoformat();(OWN/(name+'.stdout.txt')).write_text(r.stdout);(OWN/(name+'.stderr.txt')).write_text(r.stderr)
 terminal.append({'name':name,'args':args,'cwd':str(cwd),'startedAtUTC':started,'endedAtUTC':ended,'actualExitCode':r.returncode,'stdoutPath':str(REL/(name+'.stdout.txt')),'stdoutSHA256':sha(OWN/(name+'.stdout.txt')),'stderrPath':str(REL/(name+'.stderr.txt')),'stderrSHA256':sha(OWN/(name+'.stderr.txt'))})
 write(OWN/'final-native-preparation.terminal.receipt.json',{'status':'running' if r.returncode==0 else 'failed_closed','commands':terminal,'strictNetDelta':0,'humanApproval':False,'activeWritesThisStage':0});print(json.dumps({'command':name,'actualExitCode':r.returncode,'stdout':r.stdout[:220]}),flush=True);assert r.returncode==0,r.stderr
bundle=ISO/REL/'native-finalbook';shutil.copytree(bundle,OWN/'native-finalbook');model=read(bundle/'bundle/book-model.json');manifest=read(bundle/'batch-manifest.json');render=read(bundle/'bundle/book.pdf.render-manifest.json')
assert [p['goalId'] for p in model['pages']]==ids+[bd36] and manifest['curriculumAtomicDenominatorAtPreparation']==376
assert render['goalPageCount']==15 and render['physicalPageCount']==17 and render['frontMatterPageCount']==2
assert all(p['evidenceReview'] is None and p['visualization']['approvedForPublication'] is False for p in model['pages'])
assert not list((bundle/'round-a/results').iterdir()) and not list((bundle/'round-b/results').iterdir())
write(OWN/'final-native-preparation.terminal.receipt.json',{'status':'PASS_native_exact_future_current_fifteen_page_preparation','commands':terminal,'newScientificCandidateGoalIds':ids,'existingTargetedBindingGoalIds':[bd36],'curriculumAtomicDenominatorAtPreparation':376,'nativeBaseModelDigest':manifest['source']['baseBookDigest'],'nativeModelDigest':model['digest'],'nativeBundleFingerprint':manifest['artifacts']['bundleFingerprint'],'nativeReviewInputFingerprint':manifest['artifacts']['reviewInputFingerprint'],'exactFutureCanonicalPath':model['source']['landscapePath'],'goalPages':[{k:p[k] for k in ['goalId','title','goalFingerprint','pageFingerprint']} for p in model['pages']],'PDFGoalPages':15,'PDFPhysicalPages':17,'reviewModeAIOnly':True,'independentTwoBlindCampaignsPrepared':True,'reviewResultDirectoriesEmpty':True,'PContentsAbsent':True,'DReviewsCompletedByThisPreparation':0,'independentVRequiredForEightCurrentBindings':True,'newScientificClosuresActual':0,'restoredBindingsActual':0,'strictNetDeltaActual':0,'humanApproval':False,'activeWritesThisStage':0,'priorSameByteCardWriteEventDisclosedSeparately':str(REL/'card-ledger-same-byte-write-isolation.erratum.receipt.json')})
print(json.dumps({'prepared':15,'newScientificCandidates':14,'existingTargetedBinding':1,'base':376,'nativeModelDigest':model['digest'],'activeWrites':0}),flush=True)
