import datetime
import hashlib
import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[3]
IDENTITY = 'codex-economics-final46-independent-round-b-20261009-v1'
STARTED = '2026-10-09T09:01:10Z'

# These are the reviewer's own changed-case expectations and actual observations.
# For the 35 unchanged competence/profile bodies, the complete supplied positive
# understanding contract is retained rather than reopened or silently rewritten.
OLD = {
 '047ce369': ('Ein neues kurzfristiges Zahlungsziel statt eines langfristigen Sparziels verändert die Gewichtung von Liquidität und erwarteter Rendite; die reale Kaufkraft bleibt getrennt zu prüfen.', 'A new short-term payment objective instead of a long-term saving goal changes the weighting of liquidity and expected return; real purchasing power remains a separate consideration.', 'Der Portfolio-Nachfolger benötigt Anlagekriterien, die neue E-Anlageprüfung benötigt Kaufkraft und Liquidität; beide erweitern den alten Atomvertrag nicht.', 'Die drei Gläser Risiko, Verfügbarkeit und Kaufkraft stehen als getrennte Kriterien; die Zukunftsblase zeigt ein Fragezeichen, keine sichere Rendite.'),
 '52e6731e': ('Bei einer zweiten Plattform mit geänderten Wechselhürden und Vermittlungsgebühren erklärt die Person, weshalb Reichweite und Abhängigkeit für die beiden Marktseiten anders ausfallen.', 'For a second platform with different switching barriers and intermediary fees, the learner explains why reach and dependence change for the two market sides.', 'Ausschließlich das Seitenziel des bestehenden Konsumentscheidungs-Nachfolgers wandert von 208 auf 207; Marktmodell und beide Folgekompetenzen bleiben identisch.', 'Zugang und Abhängigkeit sind sichtbar als zwei mögliche Folgen; das Schloss-/Gebührenmotiv gibt keine zwangsläufige Gesamtwertung vor.'),
 '1da809f7': ('Ein frischer institutioneller Fall verändert Wettbewerbsregeln oder sozialen Ausgleich; die Person ordnet ihn anhand der tatsächlichen Regeln ein und vermeidet eine Zuordnung allein nach dem Namen.', 'A fresh institutional case changes competition rules or social support; the learner classifies it from the actual rules rather than its name.', 'Der neue direkte GWÖ-Vergleich braucht die Soziale Marktwirtschaft als Vergleichsgrundlage; der zusätzliche Nachfolger macht das Ausgangsziel nicht selbst zur alternativen Ordnung.', 'Wettbewerb, Regeln und Absicherung bleiben gut lesbare verschiedene Säulen; das Bild behauptet weder staatlich festgelegte Einzelpreise noch einen regellosen Markt.'),
 '6f1f4654': ('Neue Konjunkturdaten fördern ein gesetzliches Ziel und belasten ein anderes; die Person begründet die veränderte Gewichtung ohne Umwelt- oder Verteilungsziele in den gesetzlichen Viererkanon einzusetzen.', 'New business-cycle data support one statutory objective while burdening another; the learner justifies the changed weighting without adding environmental or distribution objectives to the statutory four.', 'Der neue lokale Konjunktur-/Fiskalabschluss verwendet die vier gesetzlichen Ziele; die bestehende Konjunkturprognose-Vorleistung bleibt unverändert.', 'Preise, Beschäftigung, Wachstum und Außenwirtschaft sind vier getrennte Felder mit offenen Pfeilfragen; keine falsche Zielzahl oder sichere Harmonie.'),
 '2d8cc4f2': ('Ein neuer Entwicklungsfall verändert Finanzierung und lokale Mitsprache; die Person erklärt daraus veränderte NGO-Funktionen und Rechenschaftsgrenzen.', 'A new development case changes funding and local participation; the learner explains the resulting differences in NGO functions and accountability limits.', 'Die neue Q4-Prüfung verbindet NGO-Beteiligung mit Handelsabhängigkeit als eigene Aufgaben; sie schreibt dem Atom keine automatische Vertretungsmacht aller Betroffenen zu.', 'Stimmen, Zusammenarbeit und Rechenschaft bleiben verschieden; die Frage nach Projektfinanzierung ist ein Prüfhinweis statt eines gesicherten Erfolgs.'),
 'ac76810e': ('Bei einem neuen Handelspartnernetz mit mehr Ersatzlieferanten stellt die Person dieselben Waren- und Zahlungsrichtungen dar, erklärt aber eine geänderte asymmetrische Abhängigkeit.', 'With a new trading-partner network offering more alternative suppliers, the learner represents the same goods and payment directions but explains a changed asymmetric dependence.', 'Die neue Q4-Handels-/NGO-Prüfung ergänzt den vorhandenen Rohstoff-/Governance-Abschluss; beide benötigen richtungsrichtige Handelsbeziehungen.', 'Die Warenpfeile laufen in beide Richtungen; Partner, Produkte und Abhängigkeit werden getrennt und mit Fragezeichen betrachtet.'),
 '2aee114f': ('Eine neue Alltagskonfliktregel verfolgt denselben Schutzzweck mit anderer Belastung; die Person begründet ihren Bedarf und prüft eine weniger belastende Alternative.', 'A new everyday conflict rule serves the same protective purpose with a different burden; the learner explains its need and considers a less burdensome alternative.', 'Nur das Seitenziel der bestehenden Vertragsvorleistung wird angepasst; Rechtsschutz, Internet- und Vertragskompetenzen bleiben gleich.', 'Schutz, Ordnung und Ausgleich sind lesbar getrennt; Konflikt und geregeltes Zusammenleben illustrieren eine Begründungsfrage statt pauschaler Regelbefürwortung.'),
 '7159ae22': ('Bei verändertem Alter oder Vorsatz im neuen Schadensfall begründet die Person mögliche Ersatz- und Strafrechtsfolgen getrennt und begrenzt das Ergebnis auf die Fallangaben.', 'When age or intent changes in a fresh damage case, the learner explains possible civil remedies and criminal consequences separately and limits the result to the facts.', 'Der sachfremde direkte Weg zur nun konkreten Minderjährigenbeschäftigung entfällt; der neue Schadensfallabschluss verwendet tatsächliche zivil- und strafrechtliche Folgen.', 'Handlung, Folgen und Prüfung bleiben drei offene Schritte; der Fahrradschaden wird nicht als automatische Verurteilung gezeigt.'),
 '3a6568d2': ('Ein frischer Onlinefall verändert Nutzungskreis oder Einwilligung; die Person trifft eine neue rechtlich begründete Veröffentlichungsentscheidung statt technische Verfügbarkeit für Erlaubnis zu halten.', 'A fresh online case changes the audience or consent; the learner makes a new legally reasoned publication decision rather than equating technical availability with permission.', 'Der nicht universelle Weg zur Beschäftigung Minderjähriger entfällt; die passende Vertiefung zu geistigem Eigentum und Persönlichkeitsrechten bleibt.', 'Einwilligung, Rechte und Entscheidung sind klar getrennt; die beiden Wegpfeile setzen keine unbedingte Veröffentlichungserlaubnis.'),
 'f6a445cb': ('Beim Wechsel vom geschlossenen Unterricht zur öffentlichen Schulwebsite prüft die Person Urheber- und Bildnisinteressen neu und begründet einen passenden engeren Nutzungsweg.', 'When a closed classroom use becomes publication on a school website, the learner reassesses copyright and image rights and explains a suitable narrower use.', 'Die Beschäftigungs-Vertiefung entfällt als unpassender Nachfolger; der neue Onlineveröffentlichungsabschluss passt zu den beiden Schutzbereichen.', 'Urheberrecht, Nutzung und Persönlichkeit stehen nebeneinander; das sichtbare Fragezeichen hält die Nutzung offen.'),
 '78eeb8fe': ('Bei einer veränderten Annahmeerklärung im neuen Kaufablauf unterscheidet die Person Vertragsschluss, Pflichten und gesonderten Eigentumsübergang und begründet das andere Ergebnis.', 'With a changed acceptance in a new purchase sequence, the learner distinguishes formation, obligations and separate transfer of ownership and explains the changed outcome.', 'Die eigene Seite wandert 205→204 und die zwei unveränderten Nachfolger erhalten korrekte Zielseiten 205/208; keine neue Kante oder Vertragsweite.', 'Angebot und Annahme nennen dieselben 300 Euro; Pflichten bleiben eine getrennte Folge statt eines automatischen Eigentumsübergangs.'),
 '1f5c3e82': ('Ein neuer Kauf ersetzt vollständig gezahlte überlassene Mittel durch spätere Raten; die Person begründet, weshalb Zustimmung und Wirksamkeit nun anders geprüft werden.', 'A new purchase replaces full payment from entrusted funds with future instalments; the learner explains why consent and validity must now be assessed differently.', 'Nur eigene und verlinkte Seitenzahlen werden verschoben; die Vertragsvorleistung und Verbraucherrechtsfolge bleiben unverändert.', 'Alter, Mittel und Zustimmung sind drei eigenständige Prüfhinweise, jeweils mit Fragezeichen; keine pauschale Freigabe eines Kaufs.'),
 'c4faf50c': ('Ein neues Kaufproblem betrifft statt eines Mangels einen Fernabsatzwiderruf; die Person wählt das passende Recht und ändert Forderung und Belege der Nachricht.', 'A new purchase problem concerns distance-sale withdrawal instead of a defect; the learner chooses the relevant right and changes the request and supporting facts.', 'Die verschobenen Zielseiten der Minderjährigenvorleistung und Onlinekauf-Folge sind korrekt; Anspruch und Kommunikationsoperator bleiben gleich.', 'Mangel, Gespräch und Nacherfüllung sind in sinnvoller Reihenfolge; der Geldpfeil ist ausdrücklich nur die nachgelagerte bedingte Möglichkeit.'),
 'd3c11bfa': ('Ein zweites Onlineangebot verändert Lieferkosten, Verkäufer und Zahlungsrisiko; die Person prüft neu, ob der scheinbar niedrigere Preis zum gegebenen Bedarf passt.', 'A second online offer changes shipping costs, seller and payment risk; the learner reassesses whether its apparently lower price suits the stated need.', 'Nur die eigene Seite und die Zielseite der Verbraucherrechtsvorleistung verschieben sich; die beiden wirklichen direkten Voraussetzungen bleiben gleich.', 'Gesamtkosten, Zuverlässigkeit und Vergleich stehen als offene Fragen; das Fachgeschäft bleibt eine Möglichkeit statt eines pauschalen Onlineverbots.'),
 'dae93971': ('Eine frische Normanwendung verändert eine entscheidende Falltatsache; die Person ordnet die einzelnen Merkmale neu zu und erklärt die veränderte oder offenbleibende Rechtsfolge.', 'A fresh application changes one decisive fact; the learner reassesses individual statutory elements and explains the changed or unresolved legal consequence.', 'Die neuen Beschäftigungs-/Gerichtszweig-Nachfolger und der präzisierte Verfahrensvergleich verwenden dieselbe Norm-Tatsachen-Methode; Vertragszielseite 204 ist korrekt.', 'Norm, Tatbestand und Rechtsfolge bleiben gerichtete Schritte; die Rechtsfolgenblase enthält ein Fragezeichen und keine sichere Sanktion.'),
 'b44892ea': ('Ein neuer Jugendfall verändert Zueignungsabsicht oder Schadensvorsatz; die Person prüft die betreffenden Tatbestandsmerkmale erneut statt aus Missbilligung Strafbarkeit abzuleiten.', 'A fresh youth case changes intent to appropriate or damage; the learner reassesses the relevant statutory elements rather than inferring criminal liability from disapproval.', 'Die geänderte Zielseite der Normvorleistung ist korrekt; der Verfahrensvergleich entfällt als nicht universeller Tatbestandsnachfolger, echte Rechtsfolgen-/Deliktsaufbauziele bleiben.', 'Merkmale und Belege werden vor der offenen Prüfung getrennt; das Bild behauptet keine konkrete Schuld oder Strafhöhe.'),
 '682facbf': ('Eine zweite bereitgestellte öffentlich- oder privatrechtliche Regel verändert Eingriffsgewicht und Rechtsschutz; die Person begründet ein neues rechtsstaatliches Interessenurteil.', 'A second supplied public- or private-law rule changes the burden and legal protection; the learner gives a new reasoned rule-of-law assessment.', 'Der nun auf Gerichtszweigzuordnung begrenzte Nachfolger benötigt kein umfassendes Rechtsstaatsurteil und entfällt; Eigentum und Regelungsabwägung bleiben passende Folgen.', 'Regeln, Rechtsstaat und Interessen sind eigene Perspektiven; öffentliche und private Falltafeln behaupten keine automatische Gleichwertigkeit aller Regeln.'),
 '099086bb': ('Bei einem neuen Eigentumsfall unterscheidet die Person eine allgemeine Nutzungsgrenze von einer konkreten Enteignung und begründet jeweils Schutz, Sozialbindung und Wertkonflikt.', 'In a new property case, the learner distinguishes a general use restriction from a specific expropriation and explains protection, social obligation and value conflicts.', 'Die nun konkrete Gerichtszweigzuordnung entfällt als unpassende Folge; der neue Eigentums-/Interessenausgleichsabschluss verwendet das wirkliche institutionelle Eigentumsverständnis.', 'Eigentum, Grenzen und Werte sind sichtbar getrennt; die gestrichelte Grenze und Frageblase behaupten kein schrankenloses Eigentum.'),
 'bd413a7c': ('Eine frische Kaufrechtsfrage verändert Anspruchsgrundlage oder Eigentumsfrage; die Person folgt relevanten BGB-Verweisen und trennt Verpflichtung und Verfügung erneut.', 'A fresh sales-law question changes the legal basis or ownership issue; the learner follows relevant Civil Code cross-references and again separates obligations and disposition.', 'Nur die Seitenziele der beiden unveränderten Vorleistungen ändern sich; der neue Vertragstypen-P2-Vertrag erweitert die Kaufrechtsmethodik selbst nicht.', 'BGB, Systematik und Fall sind klar miteinander verbunden; Einkaufswagen und beschädigte Ware sind Anlässe für Prüfung statt fertige Anspruchslösungen.'),
 'aa9db8f6': ('Bei einem zweiten Geschäftsmodell wird dieselbe Tätigkeit von Unterstützung zur verkauften Kernleistung; die Person begründet die Änderung aus dem Kundennutzen.', 'Under a second business model, the same activity becomes the sold core service rather than support; the learner explains the change from customer value.', 'Der präzisierte Baustellen-/Inselfertigungsnachfolger baut auf Prozessanalyse auf, während die übrigen Nachfolger identisch bleiben.', 'Die Bäckerei-Leistungskette steht über den getrennten unterstützenden Personal-, Finanz- und IT-Prozessen; Pfeile geben Unterstützung statt Gleichsetzung an.'),
 '95f2b860': ('Eine andere Zielgruppe oder ein neuer Vertriebskanal verändert mehrere Maßnahmen des Konzepts; die Person stimmt diese erneut auf Budget und Produktziel ab.', 'A different target group or sales channel changes several measures in the concept; the learner coordinates them again with the budget and product aim.', 'Baustellen-/Inselfertigung benötigt kein vollständiges Marketingkonzept und entfällt als direkter Nachfolger; die Geschäftsmodellfolge bleibt.', 'Zielgruppe, Maßnahmen, Abstimmung und Begründung sind unterscheidbar; kein einzelnes Werbesymbol wird als ganzes Konzept ausgegeben.'),
 '53829f76': ('Ein frischer Projektfall verändert Erlösweg oder Kernprozess; die Person passt Ressourcen, Kostenlogik und Grundentscheidungen konsistent an und benennt Annahmen.', 'A fresh project changes the revenue route or core process; the learner consistently adapts resources, cost logic and basic decisions and states assumptions.', 'Der direkte Innovationspfad entfällt als redundante Kante bei erhaltenem Weg über Stakeholder; Projektmanagement und Rahmenbedingungen bleiben.', 'Bedarf, Leistung und Entscheidungen bilden eine nachvollziehbare Kette; die Fragezeichen versprechen keinen Unternehmenserfolg.'),
 'e90586d8': ('Eine neue Unternehmensentscheidung verlagert Kosten zwischen Beschäftigten, Kundschaft und Eigentümern; die Person begründet ein neues Urteil aus den konkreten Interessen.', 'A new business decision redistributes costs among workers, customers and owners; the learner justifies a new assessment from the specific interests.', 'Der Innovationsnachfolger ist nun auf Wirkungswege und Bedingungen beschränkt und benötigt Stakeholderperspektiven; die weitere Zielsetzungsfolge bleibt.', 'Mehrere Akteursblasen und die offene Verantwortungsskala unterstützen Abwägung statt eines automatischen Gewinnurteils.'),
 '8e8a672e': ('Geänderte Zahlungszeitpunkte oder ein anderer ausdrücklich vorgegebener Kalkulationszins führen zu einem neuen statisch-dynamischen Vergleich mit begründetem Risikovorbehalt.', 'Changed payment timing or a different expressly supplied discount rate leads to a new static-dynamic comparison with a reasoned risk qualification.', 'Der zusätzliche lokale Investitions-/Kennzahlenabschluss verwendet die bestehenden Verfahren; der alte LK-Abschluss bleibt unverändert und wird nicht neu materialfreigegeben.', 'Statisch, Dynamisch und Risiko sind als verschiedene Betrachtungen lesbar; ein Plusdiagramm behauptet keine sichere spätere Auszahlung.'),
 '9219c58c': ('Eine neue Unternehmensperiode hat höheren Gewinn bei schwächerer Liquidität; die Person stellt beides anhand geeigneter Bezugsgrößen getrennt dar und begrenzt den Vergleich.', 'A new company period combines higher profit with weaker liquidity; the learner represents both using suitable reference quantities and limits the comparison.', 'Die neue lokale Kennzahlenprüfung verwendet beide Lageperspektiven; der vorhandene LK-Abschluss und die Bilanz-/GuV-Vorleistung bleiben.', 'Vermögen/Kapital, Ertrag/Aufwand und Finanzen/Ergebnis sind unterschiedliche Tafelfelder; die Tabelle ist eine Rechenhilfe und kein Leistungsnachweis.'),
 '3bcb976d': ('Bei einem neuen Markt mit verändertem Knappheits- oder Informationsproblem erklärt die Person die dezentrale Preisreaktion und begrenzt deren Vorzüge gegenüber zentraler Planung.', 'In a new market with changed scarcity or information problems, the learner explains the decentralised price response and limits its advantages over central planning.', 'Der nun materialgebundene GWÖ-Vergleich entfällt als nicht universelle direkte Folge; Gleichgewichts- und Kreislaufmodelle bleiben unverändert.', 'Information, Anreiz und Koordination stehen als drei Preisfunktionen über der konkreten Marktszene; keine automatische soziale Gerechtigkeit.'),
 'bd9ec397': ('Ein neuer Text und eine andere Karikatur gewichten soziale und ökologische Folgen anders; die Person prüft Belege und Intention und begründet eine neue offene Bewertung.', 'A new text and another cartoon weigh social and environmental effects differently; the learner assesses evidence and intention and gives a new open-ended evaluation.', 'Der auf Wirtschaftsordnungsregeln beschränkte GWÖ-Vergleich braucht keine universelle Medienanalyse und entfällt; vier wirkliche Medien-/Beteiligungsfolgen bleiben.', 'Aussage, Intention und Einordnung sind lesbar getrennt; die symbolische Karikatur ist Lernhilfe und keine tatsächliche journalistische Belegquelle.'),
 '99541aa7': ('Ein neuer Exportfall ändert die Rechnungswährung oder den Importanteil; die Person rechnet mit klarer Quotierung und erklärt die andere Wirkung derselben Wechselkursänderung.', 'A new export case changes invoicing currency or imported inputs; the learner uses an explicit quotation and explains the different effect of the same exchange-rate change.', 'Die nun eigenständige Faktorproportionentheorie entfällt als fachlich unabhängige Folge; der neue Haushalt-/Import-/Exportabschluss verwendet die Wechselkurseffekte.', 'Haushalt und Unternehmen sind eigene Wirkungsperspektiven; die Euro-/Dollar-Pfeile enthalten keinen falschen Zahlenkurs.'),
 '7d399b4d': ('Eine zweite datierte Digitalisierungsentwicklung verändert Kostenmechanismus oder Rechtslage; die Person trennt neue Befunde, geltende Regeln und ihre kriterielle Wertung.', 'A second dated digitalisation development changes the cost mechanism or legal position; the learner distinguishes new evidence, applicable rules and criteria-based evaluation.', 'Der nun berechenbare Rohstoffquotient benötigt kein universelles aktuelles Rechts-/Wirtschaftsurteil und entfällt; der Szenariennachfolger bleibt.', 'Wandel, Recht und Bewertung erscheinen als verschiedene Schritte; ein steigender Pfeil ist kein allgemeines Nutzenversprechen.'),
 '7727b988': ('Neue Nachfrage- oder Ressourcenbedingungen verändern zwei Zukunftsbilder; die Person prüft, welche Gestaltungsoption robust bleibt und welches Signal eine Anpassung verlangt.', 'New demand or resource conditions alter two future scenarios; the learner assesses which option remains robust and which signal requires adaptation.', 'Die konkrete statische Reichweite entfällt als eigenständig materialgebundene Folge; das aktive Gestaltungsziel bleibt.', 'Drei Szenarien tragen jeweils Annahmen; die Optionen darunter werden nicht als gesicherte Vorhersagen ausgegeben.'),
 '7f1d5e9f': ('Ein zweiter Handelsbericht und eine anders perspektivierte Karikatur verändern Länder- und Datenauswahl; die Person begrenzt die Aussage und ordnet das politische Interesse neu ein.', 'A second trade report and a cartoon from another perspective change country and data selection; the learner limits the claim and reinterprets the political interest.', 'Die sachfremde Faktorproportionentheorie entfällt; der neue echte Bericht-/Karikaturabschluss prüft die tatsächlich behaupteten Ausdrucksformen.', 'Aussage, Intention und Politik sind getrennt; die vorhandene generische Bildkarikatur ist kein Ersatz für das separate aktuelle Prüfungsmaterial.'),
 '6f75cdff': ('Ein neuer Finanzierungsvorgang ersetzt eine Emission durch Sekundärhandel; die Person erklärt die geänderten Empfänger von Geld und Risiko statt jeden Handel als neue Unternehmensfinanzierung zu behandeln.', 'A new transaction replaces an issuance with secondary trading; the learner explains changed recipients of funds and risk rather than treating all trading as new company finance.', 'Die Portfoliorendite braucht keine universelle Akteursanalyse und entfällt als direkte Folge; der neue Finanzmarktakteursabschluss nutzt Bankkredit, Emission und Sekundärhandel.', 'Geldmarkt und Kapitalmarkt sind über Uhr-/Kalendersymbole getrennt; Akteure und Zahlungswege werden ohne automatische Finanzierungswirkung jedes Handels gezeigt.'),
 'c7b03538': ('Eine neue Regel verändert Informationskosten oder Sanktionen; die Person erklärt andere Anreize und Nebenwirkungen anhand derselben institutionenökonomischen Perspektive.', 'A new rule changes information costs or sanctions; the learner explains different incentives and side effects through the same institutional-economics perspective.', 'Die direkte Experimentfolge entfällt als redundante Kante; der erhaltene Spielgrundmodellpfad liefert die tatsächlich benötigte Zwischenkompetenz.', 'Regeln, Anreize und Folgen bleiben getrennt mit Fragezeichen; das Bild setzt Institutionen nicht bloß mit den gezeichneten Organisationen gleich.'),
 'becf0989': ('Eine frische Auszahlungsmatrix wechselt von Gefangenendilemma zu Koordination; die Person prüft beste Antworten erneut und erklärt andere bedingte Strategien.', 'A fresh payoff matrix changes from a prisoner’s dilemma to coordination; the learner reassesses best responses and explains different conditional strategies.', 'Der präzisierte Modell-/Versuchsdatenvergleich nutzt das vorhandene Spielverständnis, der Strategie-Nachfolger bleibt separat.', 'Entscheidung und Gegenüber markieren die Interdependenz; die symbolische Matrix enthält keine irreführenden numerischen Auszahlungen.'),
 '8a453b6b': ('Bei gleichem Leistungsbilanzdefizit ändern sich Kreditlaufzeit und Importverwendung; die Person erklärt unterschiedliche Risiken mit gegebener financial-account-Konvention statt den Saldo allein zu bewerten.', 'With the same current-account deficit but different loan maturity and import use, the learner explains different risks using the supplied financial-account convention rather than judging the balance alone.', 'Der neue komplette Leistungs-/Finanzkontenabschluss ist ausdrücklich LK-only; die alte Atomsemantik und GK/LK-Zielmengen werden dadurch nicht erweitert, BY-grundlegend deckt nur den Leistungsbilanzteil.', 'Leistungsbilanz und Finanzflüsse stehen getrennt mit einer offenen Zusammenhangsfrage; Pfeile beweisen weder Kausalität noch eine bestimmte Vorzeichenkonvention.'),
}

NEW = {
 '71319337': {
  'e': ['Alter und Vollzeitschulpflicht bestimmen zusammen den maßgeblichen Schutzrahmen. Erfüllte Arbeitszeitgrenzen ersetzen andere Schutzbedingungen nicht; Zulässigkeit bleibt auf bereitgestellte datierte Regeln und geprüfte Kriterien begrenzt.', 'Age and full-time compulsory schooling jointly determine the relevant safeguards. Meeting working-time limits does not replace other protections; permissibility is limited to the dated supplied rules and assessed criteria.', 'Die Person ordnet den Schulstatus ein, verbindet Normbedingungen mit Falltatsachen und begründet erlaubte oder ausgeschlossene Varianten einschließlich nicht geprüfter Bedingungen.', 'The learner classifies school status, connects statutory conditions with case facts and explains permitted or excluded variants, including conditions not assessed.', 'Eine frische Ferienbeschäftigung bei gleichem Alter verändert Schulstatus und Jahresdauer; die Person begründet, weshalb vier und fünf Wochen unter den angegebenen Bedingungen verschieden zu beurteilen sind.', 'Fresh holiday employment at the same age changes school status and annual duration; the learner explains why four and five weeks receive different assessments under the supplied conditions.'],
  'scope':'WR8 4.3 nennt Minderjährigenbeschäftigung als wählbaren Profilinhalt; die Beschreibung beansprucht begrenzte aktuelle Normanwendung, keinen vollständig freigegebenen realen Arbeitsplatz.',
  'atomic':'Alter, Schulpflicht, Zeit und Schutz sind zusammengehörige Bedingungen einer einzigen Zulässigkeitsprüfung, keine vier unabhängigen Kompetenzen.',
  'parity':'EN nennt ausdrücklich age, compulsory schooling, working time, protective conditions und within those criteria; die DE-Begrenzung bleibt vollständig erhalten.',
  'proof':'Beide P2-Fälle liefern Normen und übrige Bedingungen. Der erste schließt jetzt auch §14(5)-Ausnahmen aus; der zweite prüft die Schulpflicht-/Ferienregel bei gleichem Alter.',
  'context':'Normsubsumtion ist die sachliche Vorleistung; Internet-/Urheberrechtskenntnisse entfallen. Die neue eigene Beschäftigungsprüfung verwendet genau diese Kriterien.',
  'image':'Geburtstags-, Schulrucksack-, Uhr- und Schutzsymbole bleiben als zu prüfende Gesichtspunkte sichtbar, ohne eine erlaubte Uhrzeit oder automatische Jobfreigabe zu behaupten.',
 },
 '51203e8f': {
  'e':['Zivilverfahren dienen privaten Ansprüchen, Strafverfahren einem staatlichen Strafvorwurf. Zwecke, Rollen und gewöhnliche Schritte können beim selben Ereignis parallel auftreten; ein Vorwurf ist kein feststehendes Ergebnis.', 'Civil proceedings concern private claims and criminal proceedings a state criminal allegation. Purposes, roles and ordinary steps can coexist for one event; an allegation is not an established outcome.', 'Die Person unterscheidet Kläger/Beklagten, Gericht, Staatsanwaltschaft und beschuldigte Person, erklärt den bereitgestellten normalen Verfahrensweg und begrenzt mögliche Ergebnisse.', 'The learner distinguishes claimant/defendant, court, prosecution and suspect, explains the supplied ordinary procedural sequence and limits possible outcomes.', 'Ein neuer privater Lohnanspruch vor dem Arbeitsgericht neben einem getrennten Diebstahlsverdacht verändert Gericht und Akteure, aber nicht die Unterscheidung von Anspruch und Strafvorwurf.', 'A fresh private wage claim in a labour court alongside a separate theft suspicion changes court and actors while preserving the distinction between an entitlement and a criminal allegation.'],
  'scope':'WR10 5.2 nennt Zivilprozess und Strafverfahren als wählbaren Profilinhalt; die Beschreibung begrenzt sich auf Zwecke, Rollen und grundlegende Schritte, nicht auf alle Rechtsmittel.',
  'atomic':'Der vergleichende Verfahrensoperator verbindet die genannten Dimensionen zu einer einzigen unterscheidenden Kompetenz.',
  'parity':'Civil and criminal proceedings, purpose, participants, basic procedural steps und outcomes versus allegations entsprechen sämtlichen DE-Aspekten.',
  'proof':'Der ganze erste P2-Fall umfasst nun Gerichtseröffnung, grundsätzlich Hauptverhandlung und Urteil sowie Staatsanwaltschaft, Beschuldigte/Angeklagte und Verteidigung; der Lohn-/Verdachtsfall ist ein neuer Strukturkontext.',
  'context':'Norm-Tatsachen-Anwendung passt als Vorleistung. BLOCK: 57984b50 fordert diese Verfahrenskompetenz weiterhin direkt, seine ganzen vier Aufgaben betreffen aber Indikatoren, Konsumentscheidung, Förderung und Nacherfüllungsreklamation; kein Zivil-/Strafverfahrensvergleich wird benötigt. Die Kante ist nach Konkretisierung zu korrigieren; eine Beschreibungserweiterung würde den Atomvertrag verfälschen.',
  'image':'Die getrennten Zivil-/Strafszenen zeigen Kläger-/Beklagtenkommunikation und Gericht/Staatsanwaltschaft/Verteidigung; das Fragezeichen stellt den Strafausgang nicht als Verurteilung dar.',
  'block':'57984b50',
 },
 '772b6d9f': {
  'e':['Für einen Gerichtszweig entscheidet der Streitgegenstand anhand gesetzlicher Zuständigkeitsregeln und Sonderzuweisungen. Staat, Geld oder Steuer als Schlagwort ersetzen diese Prüfung nicht.', 'A court branch follows the dispute’s subject under statutory jurisdiction rules and special allocations. Government, money or tax as keywords do not replace that assessment.', 'Die Person ordnet vorgegebene private, arbeits-, verwaltungs-, sozial- und steuerrechtliche Streitfälle begründet zu und trennt einen Steuerstrafvorwurf von einem Steuerbescheid.', 'The learner justifies assignments of supplied private, labour, administrative, social and fiscal disputes and separates a tax offence allegation from a tax assessment.', 'Ein frischer Steuerstrafverdacht statt eines angefochtenen Steuerbescheids verändert trotz desselben Steuerworts die Zuständigkeit; die Person begründet dies aus der Sonderregel.', 'A fresh tax offence suspicion instead of a challenged tax assessment changes jurisdiction despite the same tax keyword; the learner explains this from the specific rule.'],
  'scope':'WR11 7.2 nennt Aufbau der Gerichtsbarkeit als wählbaren Profilinhalt; die bereitgestellten Zuständigkeitsregeln begrenzen die fünf Grundzuordnungen.',
  'atomic':'Alle Gerichtszweige werden durch denselben Zuordnungsoperator anhand des Streitgegenstands unterschieden; keine vollständige Verfahrens- oder Rechtsmittellehre.',
  'parity':'Ordinary, labour, administrative, social and fiscal courts sowie provided jurisdiction rules/justify übertragen die fünf deutschen Zweige und die Materialbindung genau.',
  'proof':'Die zwei P2-Fälle umfassen die fünf Zweige und einen echten Steuerstraf-Gegenfall; sie prüfen Gegenstand und Sonderzuweisung statt Akteurs- oder Geldetiketten.',
  'context':'Normsubsumtion ist ausreichend, das pauschale Rechtsstaats-/Eigentumsurteil entfällt. BLOCK: Der vorhandene 9a88ee21-Aufgabenbody braucht keine Gerichtszweigzuordnung; die direkte requires-Kante ist nach Konkretisierung nicht universal fachlich begründet.',
  'image':'Fünf verschiedenfarbige Ordner führen auf lesbare Gerichtszweige; das Steuerbescheidmotiv passt zur Finanzgerichtsbarkeit, ohne eine Steuerstrafsache abzubilden.',
  'block':'9a88ee21',
 },
 '479fb87a': {
  'e':['Das konkret versprochene Ergebnis, die Tätigkeit oder die neue zu liefernde Sache bestimmen den Vertragstyp und die wechselseitigen Hauptpflichten. Werklieferung neuer beweglicher Sachen unterliegt grundsätzlich Kaufrecht, trotz ergänzender Werkregeln.', 'The specifically promised result, service or newly supplied goods determine contract type and mutual main obligations. Manufacture and delivery of new movable goods generally follow sales law despite supplementary work-contract rules.', 'Die Person klassifiziert Reparatur, Unterricht, fertigen Kauf und neue Werklieferung anhand der gelieferten Normen, erklärt die Pflichten beider Parteien und begründet die Abgrenzung zum Kauf.', 'The learner classifies repair, instruction, a sale of ready goods and manufacture/delivery using supplied rules, explains both parties’ obligations and justifies their relation to a sale.', 'Eine frische Instrumentreparatur und Übungsbegleitung desselben Fachberufs sowie hergestellte Taschen zeigen, dass Berufsbezeichnung und Zweck die Vertragsart nicht bestimmen.', 'A fresh instrument repair and guided practice offered by the same specialist, alongside manufactured bags, show that occupation and purpose do not determine contract type.'],
  'scope':'Der erhaltene BY-J13-Vertragstypenauftrag wird als Fallvergleich mit gegenseitigen Hauptpflichten operationalisiert; keine zusätzliche Leistungsstörungs- oder Strafrechtskompetenz.',
  'atomic':'Typzuordnung und beiderseitige Hauptpflichten sind eine zusammenhängende Analyse des konkreten Leistungsversprechens; keine voneinander losgelösten Rechtskapitel.',
  'parity':'EN contracting parties und contracts of sale halten die beiderseitigen Pflichten und Kaufabgrenzung; weder Ergebnisgarantie für Unterricht noch pauschales Werkrecht wird eingeführt.',
  'proof':'Die zwei ganzen Fälle trennen Erfolg, Dienste, Warenlieferung und §650(1)-Grundregel mit ausdrücklich erhaltenen ergänzenden Werkregeln; der Beruf-/Zweck-Gegenfall trägt Transfer.',
  'context':'Kaufrechtliche Arbeitstechnik ist passende Vorleistung; der erhaltene Maschinenkauf-Abschluss benötigt Käufer-/Verkäuferpflichten. Der bestehende eng begrenzte Rechtsbegriffs-Memory-Vertrag bleibt zusätzlich bestehen, während Fallklassifikation führend bleibt.',
  'image':'Werk zeigt Reparaturerfolg, Dienst Unterrichtszeit, Kauf fertigen Helm und Werklieferung neuen Hocker; die vier lesbaren Felder enthalten keine falsche Unterrichtserfolgsgarantie.',
 },
 '8964ef4b': {
  'e':['Bei Baustellenfertigung bleibt das Produkt ortsfest und Ressourcen kommen zu ihm; eine Fertigungsinsel bündelt mehrere Operationen für bewegliche Produktfamilien. Eignung hängt von Produkt und Ablauf statt einer universellen Kostenrangfolge ab.', 'In fixed-position production the product stays in place and resources move to it; a production cell groups operations for movable product families. Suitability depends on product and process rather than a universal cost ranking.', 'Die Person beschreibt die tatsächlichen Personal- und Materialwege, klassifiziert die Produktionsform und begründet ihre Eignung samt Koordinationsbedarf aus den vorgegebenen Bedingungen.', 'The learner describes actual movements of workers and materials, classifies production organisation and explains suitability and coordination needs from the supplied conditions.', 'Ein frischer Möbelbetrieb nutzt sowohl Teaminseln für Module als auch ortsfeste Endmontage beim Kunden; die Person unterscheidet beide Verfahren innerhalb derselben Branche.', 'A fresh furniture firm uses team cells for modules and fixed-position final assembly at a customer’s site; the learner distinguishes both methods within one industry.'],
  'scope':'WR8 4.2 nennt Baustellen- und Inselfertigung als ausgewählte wählbare Beispiele; kein Anspruch auf alle Fertigungsverfahren oder vollständigen Profilbereich.',
  'atomic':'Arbeitsorganisation, Materialfluss und Eignung bilden einen einzigen Vergleich der beiden Verfahren, keine separate Kostenrechnung.',
  'parity':'Fixed-position und cellular production übersetzen die fachliche Unterscheidung; work organisation, material flow und suitability bilden alle DE-Aspekte ab.',
  'proof':'Windrad/Fahrradinsel und Möbelmodule/kundenseitige Endmontage variieren Produktbewegung und Koordination; keine Kosten-/Geschwindigkeitsgarantie aus dem Namen.',
  'context':'Kernprozessanalyse bleibt die passende direkte Vorleistung; Marketingvollkompetenz entfällt. Der neue Baustellen-/Inselabschluss benötigt die tatsächlichen Organisationsmerkmale.',
  'image':'Das große Boot bleibt links ortsfest, der Materialwagen fährt zum Boot; rechts bilden Arbeitsschritte eine kompakte Teaminsel. Die Perspektive verfälscht keine Materialrichtung oder numerische Relation.',
 },
 'f90e4741': {
  'e':['Eine Innovation kann betriebliche Prozesse oder Leistungen verändern; gesamtwirtschaftliche und gesellschaftliche Folgen entstehen über bedingte Wirkungswege. Direkter Betriebsbefund, mögliche Nachfrage-/Beschäftigungsfolge und Zielkonflikt sind verschieden.', 'Innovation can change a firm’s processes or services; aggregate and social effects emerge through conditional pathways. A direct firm observation, possible demand or employment effects and trade-offs are distinct.', 'Die Person verbindet belegte Betriebsänderungen mit möglichen Folgen für Betroffene und Gesamtwirtschaft, erklärt Bedingungen und benennt Daten, die ein stärkeres Urteil erst erlauben würden.', 'The learner connects evidenced changes at a firm with possible effects on affected groups and the economy, explains conditions and identifies data needed for stronger conclusions.', 'Eine frische Werkzeug-Leihdienstinnovation verlagert Nachfrage zwischen Herstellung und Reparatur; die Person prüft Netto-Beschäftigung und Umweltbedingungen statt dieselbe Effizienzerzählung zu wiederholen.', 'A fresh tool-sharing service shifts demand between manufacturing and repair; the learner assesses net employment and environmental conditions rather than repeating the same efficiency story.'],
  'scope':'WR10 5.1 nennt Innovationswirkungen als wählbaren Profilinhalt; der Rückzug unbelegter Länderclaims schafft keine allgemeine Kursfreigabe.',
  'atomic':'Betriebs- und Gesellschaftswirkung sind Glieder derselben Kausalanalyse; die Beschreibung verlangt keine eigenständige allgemeine Innovationsprognose.',
  'parity':'EN pathways, supplied cases, conditions and possible trade-offs übertragen Mechanismus, Materialbindung und Ergebnisoffenheit.',
  'proof':'100→70 Ausfallstunden ist 30% Rückgang ohne bewiesenen Absatz-/Jobeffekt. Der Leihdienstfall verändert Nachfrage und Reparaturbedarf; offene Transporte verhindern Umweltgarantie.',
  'context':'Stakeholderbewertung trägt die Betroffenenperspektiven; der direkte Geschäftsmodellpfeil entfällt redundant. Im Reparaturförderungsfall dienen reparierbare Gestaltung, Reparaturjobs und Zielkonflikte als passender Anwendungskontext.',
  'image':'Neue/weitergenutzte Teile, eingesparte Entsorgung und offene Ertragsfrage illustrieren bedingte Innovationswirkung; Schulung/Planung wird als weiterer Weg gezeigt, keine sichere Wohlstandsfolge.',
 },
 'f7c051f4': {
  'e':['Eine Gemeinwohlökonomie-Konzeption muss über ihre beschriebenen Regeln verglichen werden. Ziele, Eigentum und Koordination sind eigene Dimensionen; freiwilliger Unternehmensbericht ist keine vollständige nationale Wirtschaftsordnung.', 'An Economy for the Common Good proposal must be compared through its described rules. Objectives, property and coordination are distinct dimensions; a voluntary company report is not a complete national economic order.', 'Die Person vergleicht die bereitgestellten Regeln in allen drei Dimensionen, trennt Hypothese und geltenden Rahmen und begrenzt Schlussfolgerungen aus einem betrieblichen Instrument.', 'The learner compares supplied rules across all three dimensions, distinguishes a hypothesis from an applicable framework and limits conclusions drawn from a company-level tool.', 'Ein frischer freiwilliger Gemeinwohlbericht verändert Zielgewichtung eines Unternehmens bei unverändertem Eigentums- und Wettbewerbssystem; die Person weist den behaupteten nationalen Systemwechsel begründet zurück.', 'A fresh voluntary common-good report changes one firm’s emphasis while property and competition rules remain unchanged; the learner explains why it does not establish a national system change.'],
  'scope':'WR11 7.1 nennt alternative Ordnungen, etwa GWÖ, als wählbaren Inhalt; die Beschreibung ist an eine bereitgestellte Variante gebunden und beansprucht nicht alle GWÖ-Konzeptionen.',
  'atomic':'Drei Ordnungsdimensionen bilden einen zusammenhängenden kriteriellen Vergleich statt drei unabhängiger Routineziele.',
  'parity':'Supplied proposal, objectives, property, coordination und tie conclusions to described rules erhalten die vollständige deutsche Material- und Aussagebegrenzung.',
  'proof':'Die hypothetische Beschaffungsanreizvariante erhält Märkte und Privateigentum; der freiwillige Bericht ist ein echter Ebenen-Gegenfall. Kein gesetzlicher Systemwechsel oder Zentralplanungsautomatismus.',
  'context':'Soziale Marktwirtschaft ist die richtige Vergleichsvorleistung; Preisfunktionen/Medienanalyse entfallen als universelle Zusatzvoraussetzungen. BLOCK: 9a88ee21 verlangt den GWÖ-Vergleich, verwendet in den Aufgaben aber nur Denkschulen, EU-Verfahren, Interessenvertretung und Steuergerechtigkeit; keine GWÖ-Regel oder Drei-Dimensionen-Zuordnung.',
  'image':'GWÖ-Fall und Soziale Marktwirtschaft werden anhand der Ziel-/Eigentums-/Koordinationssymbole betrachtet; das Bild behauptet keine Abschaffung privaten Eigentums.',
  'block':'9a88ee21',
 },
 '575c08d4': {
  'e':['Relative Faktorausstattung ist das Kapital-Arbeit-Verhältnis statt absoluter Ländergröße. Unter vorgegebenen gemeinsamen Modellbedingungen verbindet sie sich mit Güterintensität zu einem bedingten Handelsmuster.', 'Relative factor abundance is the capital–labour ratio rather than absolute country size. Under supplied common model conditions it combines with goods’ factor intensity to produce a conditional trade pattern.', 'Die Person vergleicht die Verhältnisse, verbindet relativ reichlichen Faktor und intensive Güterproduktion und erklärt, weshalb eine verletzte Technologieannahme die einfache Ableitung begrenzt.', 'The learner compares the ratios, connects the relatively abundant factor with factor-intensive production and explains why a violated technology assumption limits the simple inference.', 'Ein frischer Fall macht das Land mit weniger absolutem Kapital relativ kapitalreich; anschließend verhindern nicht beschriebene unterschiedliche Technologien dieselbe sichere Ableitung.', 'A fresh case makes the country with less absolute capital relatively capital-abundant; unspecified different technologies then prevent the same definite inference.'],
  'scope':'WR11 7.3 nennt Faktorproportionentheorie als ausgewählten wählbaren Inhalt; keine vollständige Handelstheorien- oder reale Länderprognose.',
  'atomic':'Verhältnis, Intensität und Annahmen begründen dieselbe bedingte Modellvorhersage; berechnen und erklären sind hier verbunden.',
  'parity':'Relative factor endowments, goods’ intensities und model assumptions bilden relative Ausstattung, Güterintensität und Modellbindung vollständig ab.',
  'proof':'Die P2-Verhältnisse 2/0,5 und 0,5/2 sind korrekt; der Gegenfall mit mehr absolutem Kapital und neue Technologiegrenze verändern echte Begründung.',
  'context':'Die unbenotete Orientierung vermittelt keine Fachmastery; alle Modellbegriffe und Bedingungen sind im Fall geliefert, Wechselkurs-/Medienwissen ist nicht versteckt. BLOCK: Der historische fe55b4b3-Lieferkettenfall vergleicht Beschaffungspreis, Lieferzeiten, Unterbrechung und fehlende Wahrscheinlichkeiten; er verwendet weder relative Ausstattung noch Güterintensität oder Faktorproportionentheorie. Die direkte requires-Kante benötigt Korrektur.',
  'image':'A zeigt relativ mehr Arbeit, B relativ mehr Kapital; die Warenpfeile stimmen mit der symbolisch gezeigten Intensität überein. Fragezeichen und fehlende Zahlen verhindern ein falsches konkretes Modellresultat.',
  'block':'fe55b4b3',
 },
 '7a2435f2': {
  'e':['Die Portfoliorendite gewichtet Einzelrenditen mit den Anfangsanteilen. Gegensätzliche gemeinsame Bewegungen können Ergebnisse glätten, gleichgerichtete Verluste bleiben trotz mehrerer Anlagen möglich.', 'Portfolio return weights individual returns by initial holdings. Offsetting joint movements can smooth outcomes, while losses moving together remain possible despite multiple investments.', 'Die Person berechnet die vorgegebenen Portfoliorenditen und erklärt aus gemeinsamen Kursbewegungen einen Diversifikationseffekt sowie seine Grenze ohne vollständige Wahrscheinlichkeitsdaten.', 'The learner calculates supplied portfolio returns and explains a diversification effect and its limit from joint price movements without assuming a full probability distribution.', 'Ein frisches Szenariopaar wechselt von gegensätzlichen Bewegungen zu gemeinsamen Verlusten; die Person begründet, weshalb dieselbe Anlagezahl keine Verlustgarantie ergibt.', 'A fresh scenario pair switches from offsetting movements to losses moving together; the learner explains why the same number of assets guarantees no protection from loss.'],
  'scope':'WR11 7.4 nennt Portfoliotheorie/Diversifikation als wählbaren Inhalt; die Beschreibung bleibt bei gegebenen Portfolios und Kursverläufen, keine reale Anlageberatung.',
  'atomic':'Gewichtete Rechnung und Risikogrenze sind eine Portfolioanalyse desselben Gegenstands; keine unabhängige Marktakteurskompetenz.',
  'parity':'Weighted returns, supplied portfolios and differing joint movements bewahren Rechnung und genau die gemeinsame Kursstruktur des deutschen Vertrags.',
  'proof':'Die beiden P2-Szenarien ergeben +5%/+5% und +15%/−15%. Der zweite Fall widerlegt Verlustgarantie strukturell, nicht durch bloßen Zahlentausch.',
  'context':'Anlagekriterien sind passend; die volle Geldmarktakteursanalyse ist keine universelle Vorleistung. BLOCK: 9a88ee21 verwendet weder Portfoliogewichte noch Anlagenrenditen oder gemeinsame Kursverluste; der Abgabenvergleich kann diese Voraussetzung nicht begründen. Der Rückzug unbelegter Länderclaims löst diese Kante nicht.',
  'image':'A stellt unterschiedliche, B gemeinsame Kursbewegungen ohne Zahlenmaßstab gegenüber; verschiedene Korbanteile sind keine konkrete sicher gewinnbringende Portfolioempfehlung.',
  'block':'9a88ee21',
 },
 '5a72a72a': {
  'e':['Spielvorhersagen folgen Auszahlungen und ausdrücklich gegebenen Verhaltens-, Informations- und Wiederholungsbedingungen. Eine empirische Abweichung zeigt weder eindeutig ein Motiv noch allein die Ursache einer veränderten Entscheidung.', 'Game predictions follow payoffs and expressly supplied behavioural, information and repetition conditions. An empirical deviation identifies neither a unique motive nor the sole cause of changed choices.', 'Die Person leitet beste Antworten und die bedingte Modellvorhersage ab, berechnet Beobachtungsanteile und begrenzt Interpretationen anhand von Modell- und Versuchsbedingungen.', 'The learner derives best responses and the conditional prediction, calculates observed proportions and limits interpretations using model and experimental conditions.', 'Eine frische wiederholte Interaktion mit festen Partnern verändert strategische Bedingungen; die Person unterscheidet 20 Prozentpunkte Unterschied von einem bewiesenen kausalen Wiederholungseffekt.', 'A fresh repeated interaction with fixed partners changes strategic conditions; the learner distinguishes a 20-percentage-point difference from a proven causal effect of repetition.'],
  'scope':'WR11 7.5 nennt spieltheoretische Experimente als wählbaren Inhalt; bereitgestelltes Modell und Daten begrenzen Vorhersage und Interpretation.',
  'atomic':'Ableiten, Vergleichen und Einordnen bilden die gemeinsame Modell-/Datenprüfung; kein zusätzliches allgemeines Psychologiemodell.',
  'parity':'Conditional predictions, experimental data und model/experimental conditions erhalten sämtliche DE-Bindungen, keine eindeutige Motivzuschreibung.',
  'proof':'In der angegebenen Matrix ist D strikt dominant und DD Nash; 8/20=40%, 60−40=20 Prozentpunkte. Fehlende Zufallszuweisung verhindert den behaupteten alleinigen Kausalnachweis.',
  'context':'Spielgrundmodelle sind passend, die institutionenökonomische Grundlage bleibt transitiv. BLOCK: Der ganze 9a88ee21-Aufgabenbody enthält keine Versuchsdaten, Modellvorhersage oder wiederholte Interaktion; dieser präzisierte Atomvertrag ist keine universelle direkte Voraussetzung der EU-/Steuerprüfung.',
  'image':'Modell und Daten sind lesbare getrennte Felder mit symbolischen Entscheidungen und Fragezeichen; keine falsche 40%- oder Gleichgewichtsbehauptung im Bild.',
  'block':'9a88ee21',
 },
 '055ef95c': {
  'e':['Statische Reichweite ist ein Bestands-/Flussquotient bei rechnerisch konstanten Reserven und jährlicher Förderung. Reserveklassifikation und Förderung können sich ändern, daher ist der Quotient kein gesichertes Erschöpfungsdatum.', 'Static lifetime is a stock-to-flow ratio with reserves and annual production treated as constant. Reserve classification and production can change, so the ratio is not a guaranteed exhaustion date.', 'Die Person berechnet mit passenden Einheiten die statische Reichweite, unterscheidet definierte Reserven von weiteren Ressourcen und erklärt Änderungen aus Reklassifizierung und Förderrate.', 'The learner calculates static lifetime with appropriate units, distinguishes defined reserves from broader resources and explains changes from reclassification and production rates.', 'Ein frischer Fall erhöht Reserven durch Technik, steigert Förderung stärker und nennt zusätzliche ungeklärte Ressourcen; die Person begründet die kürzere Reichweite ohne daraus gesunkenen Gesamtbestand abzuleiten.', 'A fresh case raises reserves through technology, increases production even more and lists other unclassified resources; the learner explains shorter lifetime without inferring lower total geological stock.'],
  'scope':'WR11 7.6 nennt ausgewählte Ressourcenknappheit als wählbaren Inhalt; kein Vollvertrag sämtlicher Zukunftstrends oder echter heutiger Rohstoffbestände.',
  'atomic':'Quotientenrechnung und Bedingungserklärung sind dieselbe Interpretation einer Modellkennzahl; Formelersatz allein genügt nicht.',
  'parity':'Static reserve-to-production lifetime und not a fixed prediction of exhaustion übertragen Modell und Nichtprognose; annual production erhält den Flussbezug.',
  'proof':'120/4=30 Jahre, (112+48)/8=20 Jahre; die weiteren 88 Mio. t sind ausdrücklich keine wirtschaftlich gewinnbaren Reserven. Der kürzere Quotient trotz größerer Reserve ist ein echter Deutungsgegenfall.',
  'context':'Die unbenotete Orientierung trägt keine verborgene Fachleistung; Formel, Kategorie und Zahlen sind bereitgestellt. BLOCK: 9a88ee21 erwähnt Ressourcenverbrauch als politischen Zweck, verlangt aber keinen Reserven-/Förderquotienten, keine Kategoriengrenze oder Reichweitendeutung. Dieser Atomvertrag ist keine universelle Voraussetzung dieser Aufgaben.',
  'image':'Reserveglas, Förderung pro Jahr und R/P bleiben richtig gerichtete Stock-/Flusssymbole; das Kalenderfragezeichen verspricht kein festes Erschöpfungsdatum.',
  'block':'9a88ee21',
 },
}

def sha(data):
    return 'sha256:' + hashlib.sha256(data).hexdigest()

def main():
    impact = json.loads((BASE / 'actual-full-P300-to-P311-all311-whole-ownerpage-impact.native.json').read_text())
    scope = {r['goalId']: r for r in impact['affectedOwnerpages']}
    completed = datetime.datetime.now(datetime.timezone.utc).isoformat()
    keys = ['essentialUnderstandingDe', 'essentialUnderstandingEn', 'observablePerformanceDe', 'observablePerformanceEn', 'transferExpectationDe', 'transferExpectationEn']
    all_records = []
    for n in (1, 2, 3):
        rd = BASE / f'native-d-final46-ordered-pack{n}-scope46-v2/round-b'
        inp = json.loads((rd / 'description-review-input.json').read_text())
        campaign = json.loads((rd / 'description-review-campaign.json').read_text())
        bundle = json.loads((rd / 'review-bundle-manifest.json').read_text())
        batch = campaign['batches'][0]
        run_id = f'{IDENTITY}-pack{n}'
        records = []
        for index, goal in enumerate(inp['goals'], 1):
            gid = goal['goalId']; prefix = gid[:8]
            if scope[gid]['wasCurrentStrict300']:
                td, te, cn, vi = OLD[prefix]
                expectations = goal['reviewContext']['evidenceProfile']['profile']['expectations']
                eu_de = ' '.join(x['essentialUnderstandingDe'] for x in expectations)
                eu_en = ' '.join(x['essentialUnderstandingEn'] for x in expectations)
                op_de = ' '.join(x['observablePerformanceDe'] for x in expectations)
                op_en = ' '.join(x['observablePerformanceEn'] for x in expectations)
                evidence = dict(zip(keys, [eu_de, eu_en, op_de, op_en, td, te]))
                decision = 'keep'
                rationale = ('1. Scope: Gezielte echte Kontextprüfung des erhaltenen Ziels „' + goal['currentTitleDe'] + '“; die vorher gültige Beschreibung und der vollständige P2-Inhalt werden nicht wiederaufgenommen. '
                    '2. Atomarer Zusammenhang bleibt unverändert: ' + eu_de + ' '
                    '3. Beobachtbarer Operator bleibt unverändert: ' + op_de + ' '
                    '4. Frische strukturelle Übertragung im bestehenden vollständigen P2-Vertrag: ' + td + ' '
                    '5. DE/EN: Beide ganzen Beschreibungen und der bilinguale P2-Vertrag sind im Before/After-Ownerkontext unverändert; „' + goal['currentTitleEn'] + '“ bewahrt die aktuelle Kompetenz und erhält keine scope-erweiternde Ersetzung. '
                    '6. Individueller ganzer Seiten-/Graphkontext: ' + cn + ' Tatsächliche PDF-/Bildbetrachtung: ' + vi + ' Bestehende A/M-/Quellenbindungen bleiben in ihrem bisherigen Umfang; keine neue Vollquellen-, Kurs- oder menschliche Freigabe. E1/G1 und needs_human_review bleiben Kandidatenstatus.')
            else:
                notes = NEW[prefix]
                evidence = dict(zip(keys, notes['e']))
                decision = 'block' if 'block' in notes else 'keep'
                rationale = ('1. Fachlicher Quellen-/Umfangsbezug: ' + notes['scope'] + ' '
                    '2. Semantische Atomarität: ' + notes['atomic'] + ' '
                    '3. Lernendenwortlaut/DE-EN: ' + notes['parity'] + ' '
                    '4. Positive selbstständige Verstehensevidenz: ' + notes['proof'] + ' '
                    '5. Frische Übertragung: ' + notes['e'][4] + ' Der vollständige gelieferte P2-Vertrag trägt diese Kette; keine Profilmutation empfohlen. '
                    '6. Ganzer Prerequisite-/Nachfolger-/A-M-Bildkontext: ' + notes['context'] + ' Tatsächliche PNG- und PDF-Sichtprüfung: ' + notes['image'] + ' Die zehn materialbezogenen Konkretisierungen benötigen keine neue Abrufpflicht; die bestehende Vertragstypen-Memorybindung bleibt getrennt. Selected BY partial bedeutet keine Gesamtprofil-/Länder-/Kursfreigabe. E1/G1, ai_candidate und needs_human_review bleiben unverändert; keine Lernenden- oder Human-Trial-Evidenz.')
            record = {
                '$schema': 'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json',
                'schemaVersion': 1, 'recordId': f'{run_id}.goal-{index:03}',
                'runId': run_id, 'campaignId': campaign['campaignId'], 'roundId': campaign['roundId'],
                'bundleFingerprint': campaign['bundleFingerprint'], 'bookDigest': campaign['bookDigest'],
                **{k: goal[k] for k in ['goalId','goalFingerprint','pageFingerprint','currentTitleDe','currentTitleEn','currentDescriptionDe','currentDescriptionEn']},
                'decision': decision, 'understandingEvidence': evidence, 'rationale': rationale,
                'evidenceProfileContract': 'positive-understanding-evidence-v2', 'evidenceProfileRecommendation': 'none',
                'recordStatus': 'candidate', 'reviewAuthority': 'ai_candidate',
            }
            assert len(record['rationale']) <= 4000, (gid, len(record['rationale']))
            records.append(record); all_records.append(record)
        results = rd / 'results'; results.mkdir(exist_ok=True)
        records_path = results / (batch['batchId'] + '.records.jsonl')
        records_path.write_text(''.join(json.dumps(r,ensure_ascii=False,separators=(',',':'))+'\n' for r in records))
        params = {'reviewIdentity': IDENTITY, 'runtimeSamplingParameters': 'not exposed', 'blindToOtherReviews': True, 'temperatureOrSeedClaimed': False}
        run = {
            '$schema':'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json', 'schemaVersion':1,
            'runId':run_id, 'campaignId':campaign['campaignId'], 'roundId':campaign['roundId'], 'batchId':batch['batchId'],
            'batchInputFingerprint':batch['batchInputFingerprint'], 'bundleFingerprint':campaign['bundleFingerprint'], 'bookDigest':campaign['bookDigest'],
            'provider':'OpenAI', 'model':'Codex; exact runtime model identifier not exposed', 'role':'disconfirming_reviewer',
            'promptFamilyId':'goal-description-understanding-evidence-review-v2', 'promptFingerprint':campaign['promptFingerprint'], 'criteriaFingerprint':campaign['criteriaFingerprint'],
            'generationParametersFingerprint':sha(json.dumps(params,sort_keys=True,separators=(',',':')).encode()),
            'independenceGroupId':campaign['independenceGroupId'], 'blindToOtherRuns':True, 'goalIds':batch['goalIds'],
            'inputArtifacts':[{'role':a['role'],'digest':a['digest']} for a in bundle['artifacts']] + [{'role':'description_review_batch_input_jsonl','digest':batch['batchInputFingerprint']}],
            'startedAt':STARTED,'completedAt':completed,'status':'completed','outputDigest':sha(records_path.read_bytes()),'toolchainVersion':'native-goal-description-v3-input-v1-record-20261009',
        }
        (results / (batch['batchId'] + '.run.json')).write_text(json.dumps(run,ensure_ascii=False,indent=2)+'\n')
        own = rd / 'independent-b';own.mkdir(exist_ok=True)
        (own/'generation-parameters.actual.json').write_text(json.dumps(params,indent=2)+'\n')
        print(n, len(records), {d:sum(r['decision']==d for r in records) for d in ['keep','block']}, sha(records_path.read_bytes()))
    assert len(all_records)==46

if __name__ == '__main__':
    main()
