# SPDX-License-Identifier: Apache-2.0
import pathlib,json,copy,hashlib,datetime,fitz
ROOT=pathlib.Path('/home/enpasos/projects/skillpilot');OWN=pathlib.Path(__file__).resolve().parent;SPARSE=ROOT/'tmp/biologie-q1-four-current390-native-author-20261007-v1-attempt02'
assert not (OWN/'author.final.freeze.json').exists()
def read(p):return json.loads(p.read_text())
def write(p,j):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
def bind(p):b=p.read_bytes();return {'path':str(p.relative_to(ROOT)),'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)}
canonical=read(SPARSE/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_BIOLOGIE.de.json');goals={g['id']:g for g in canonical['goals']}
originalMapPath='curricula/DE/Gymnasium/mapping/DE-ST/lower-secondary/st_biology_lower_secondary_source_extraction_to_canonical_biology.m7-q1-bacterial-structure-fission-20261005-v1.review.json'
existingMapPath='curricula/DE/Gymnasium/mapping/DE-ST/source-components/st_biology_genetics_components.author-v6.review.json';existingMap=read(ROOT/existingMapPath);existingExtraction=read(ROOT/existingMap['sourceExtractionPath'])
originalExtraction=read(ROOT/read(ROOT/originalMapPath)['sourceExtractionPath'])
sourceSummaryId='st-biology-seki-fachlehrplan-2022-sj10-genetik-10-genetik-vererbung-proteinbiosynthese-mutation-humangenetik-und-gentechnik-erklaeren'
primary=ROOT/'curricula/DE/Gymnasium/input/ST/FLP_Biologie_Gym_01082022_swd.pdf';pdf=fitz.open(primary);raw43=pdf[42].get_text();raw42=pdf[41].get_text()
assert 'Schuljahrgang 10 (Einführungsphase)' in raw42
foundation=raw43[raw43.index('– Grundlagen der Vererbung:'):raw43.index('– Ausprägung von Merkmalen:')].rstrip()
flow=raw43[raw43.index('– Ausprägung von Merkmalen:'):raw43.index('– Vererbung des Geschlechts')].rstrip()
assert 'Replikation (Reißverschlussmodell)' in foundation and 'komplementäre Basenpaarung' in foundation and 'Transkription' in flow and 'Translation' in flow
scope=copy.deepcopy(existingExtraction['sourceGoals'][0]['courseProfileDerivation']);scope['independentReview']='Fresh three four-goal bindings pending; unchanged common-entry-phase derivation reused from actual existing independently reviewed ST component input'
items=[('0daa79f6-8f61-5506-98f9-65db83062ba8','dna-structure-information',foundation,'Structure/function, nucleotides and complementary pairing are literal; bounded modeling/information contribution only, no whole heredity bullet clearance.'),('e70d8a85-2dea-5165-919b-200fee9f4db4','replication-simple-model',foundation,'Literal Replikation/Reißverschlussmodell supports a bounded simple DNA-copying model; semiconservative identification is supplied author operationalisation, not a new claim that the original names every detail.'),('475eebb4-4eb0-524f-b1ec-4a672bf856d2','transcription-translation-model',flow,'Literal basics of transcription/translation and supplied protein-synthesis schemes support connected information-flow modeling; broad genotype-to-trait and Mendel obligations remain separate HOLD.')]
rows=[];passages=[];decisions=[];mappings=[];now=datetime.datetime.now(datetime.timezone.utc).isoformat()
for gid,key,raw,reason in items:
 sid='st-bio-ephase10-q1-four-bounded-'+key+'-author-20261007-v1';pid='author-q1-four-ST:'+key
 passages.append({'id':pid,'sourceDocumentKey':existingExtraction['sourceGoals'][0]['sourceDocumentKey'],'stage':'SekII','sourceText':' '.join(raw.split()),'rawSourceText':raw,'physicalPage':43,'printedPage':43})
 rows.append({'id':sid,'passageId':pid,'topicCode':'3.5','title':goals[gid]['title'],'description':goals[gid]['description'],'sourceText':' '.join(raw.split()),'rawSourceText':raw,'parentBulletText':' '.join(raw.split()),'rawParentBulletText':raw,'sourceRef':'Fachlehrplan Biologie Gymnasium Sachsen-Anhalt 2022, Kapitel3.5 Schuljahrgang10 (Einführungsphase), printed/physical42–43; bounded author component, not an official numbered standalone bullet','sourceSpan':'author-component:'+key,'rawSourceSpan':'physical43: actual original knowledge bullet; operator context physical42','sourceDocumentKey':existingExtraction['sourceGoals'][0]['sourceDocumentKey'],'physicalPage':43,'printedPage':43,'stage':'SekII','courseLevel':'unspecified','courseProfile':'GK_LK','rawCourseLevel':'unspecified','courseProfileIsOriginalOfficialTerm':False,'courseProfileDerivation':scope,'granularity':'officialCompetencyAspect','isOfficialBullet':False,'officialNumberingClaim':False,'authorOperationalisation':True,'componentKey':key,'wholeOriginalBulletCoverage':False,'originalSourceSummaryGoalId':sourceSummaryId,'wholeOriginalSummaryPreserved':True,'tags':['jurisdiction:DE-ST','stage:SekII','component-only'],'sourceSectionContext':copy.deepcopy(existingExtraction['sourceGoals'][0]['sourceSectionContext']),'operatorAndClaimBoundary':reason,'independentReviewStatus':'pending_current_targeted_review','thirdPartyOriginalLicense':'CC-BY-SA-3.0 as original PDF footer; no relicensing'})
 decisions.append({'sourceGoalId':sid,'decision':'mapped','canonicalGoalIds':[gid],'matchType':'partial','rationale':'AUTHOR CANDIDATE ONLY: '+reason,'reviewer':'codex-q1-four-current390-author-not-independent-reviewer','reviewedAt':now,'wholeOriginalSourceCoverage':False,'independentReviewStatus':'pending_current_targeted_review'})
 mappings.append({'legacyGoalId':sid,'canonicalGoalId':gid,'matchType':'partial','reviewDecisionId':sid})
x=copy.deepcopy(existingExtraction);x.update({'extractionId':'DE_ST_BIOLOGIE_EPHASE10_Q1_FOUR_BOUNDED_COMPONENTS_AUTHOR_20261007_V1','sourceLandscapeId':'DE_ST_BIOLOGIE_EPHASE10_Q1_FOUR_BOUNDED_COMPONENTS_AUTHOR_20261007_V1','title':'Sachsen-Anhalt E-Phase10: drei vorhandene Q1-Ziele als begrenzte Komponenten – Autorenkandidat','passages':passages,'sourceGoals':rows,'method':{'role':'bounded own source aspects extracted from actual retained original page43, with actual page42 entry-phase heading; not official standalone numbering','independentReviewStatus':'pending_current_targeted_review','wholeOriginalSourceCoverage':False}})
x['expectedTopicCodes']=['3.5']
x['qualityReview']={'status':'author_candidate_pending_independent_review','humanApproval':False,'humanTrial':False,'machineApproval':False,'wholeOriginalSourceCoverage':False}
xp='curricula/DE/Gymnasium/input/ST/source-components/DE_ST_BIOLOGIE_EPHASE10_Q1_FOUR_BOUNDED_COMPONENTS.author-20261007-v1.source-extraction.json'
mp='curricula/DE/Gymnasium/mapping/DE-ST/source-components/st_biology_q1_four_bounded_stage_components.author-20261007-v1.review.json'
m=copy.deepcopy(existingMap);m.update({'sourceLandscapeId':x['sourceLandscapeId'],'sourceExtractionPath':xp,'decisions':decisions,'mappings':mappings,'reviewer':'codex-q1-four-current390-author-not-independent-reviewer','reviewedAt':now,'title':'Author candidate three actual existing Q1/ST stage bindings, not independent source approval'})
m['reviewStatus']='author_candidate_pending_independent_review';m.pop('machineReviewEvidence',None);m['machineApproval']=False
for path,payload in [(xp,x),(mp,m)]:write(SPARSE/path,payload)
write(OWN/'source-overlays-inert/ST-three-stage-source-component.author-envelope.json',{'role':'New source components for existing canonical IDs only, pending independent targeted source/operator/route review','replacesPath':None,'prospectivePath':xp,'candidatePayload':x,'wholeSourceClosure':False,'canonicalNewIDs':[]})
write(OWN/'source-overlays-inert/ST-three-stage-component-mappings.author-envelope.json',{'role':'Candidate-only partial ST routing, pending independent review; inherited closed parser enums do not claim reviewer approval','replacesPath':None,'prospectivePath':mp,'candidatePayload':m,'wholeSourceClosure':False,'canonicalNewIDs':[]})
# Correct only these three wrong legacy stage bindings, preserving every non-four decision target and relation.
lane=OWN/'source-overlays-inert/lane-12.candidate-envelope.json';env=read(lane);old=copy.deepcopy(env['candidatePayload']);candidate=env['candidatePayload'];ids={i[0] for i in items}
candidate['mappings']=[r for r in candidate['mappings'] if not(r['legacyGoalId']==sourceSummaryId and r['canonicalGoalId'] in ids)]
for d in candidate['decisions']:
 if d['sourceGoalId']==sourceSummaryId:d['canonicalGoalIds']=[id for id in d['canonicalGoalIds'] if id not in ids]
env['additionalTargetedStageCorrection']={'existingCanonicalGoalIds':sorted(ids),'oldSourceSummaryStageWas':'SekI inherited from historical extraction default','actualOriginalStage':'SekII / common Einführungsphase','oldRelationsRemoved':3,'newBoundedPartialComponents':3,'wholeOriginalSummaryAndOtherGoalsUnchanged':True,'independentReviewPending':True};write(lane,env);write(SPARSE/originalMapPath,candidate)
plan=read(OWN/'actual-four-source-corrections-and-deferred-partner-routes.author.json');plan['additionalSTThreeStageComponents']={'sourceExtractionEnvelope':str((OWN/'source-overlays-inert/ST-three-stage-source-component.author-envelope.json').relative_to(ROOT)),'mappingEnvelope':str((OWN/'source-overlays-inert/ST-three-stage-component-mappings.author-envelope.json').relative_to(ROOT)),'mappingPath':mp,'sourceExtractionPath':xp,'onlyExistingCanonicalIDs':sorted(ids),'wholeOriginalSummaryHOLD':True,'unrelatedSTLegacyStageDutiesStillHeld':True};write(OWN/'actual-four-source-corrections-and-deferred-partner-routes.author.json',plan)
write(OWN/'ST-three-actual-primary-stage-and-operator-binding.author.json',{'role':'Actual current author targeted ST correction; fresh independent review pending','primary':bind(primary),'retainedExistingScopeDerivationInput':bind(ROOT/existingMap['sourceExtractionPath']),'actualPage42Text':raw42,'actualPage43Text':raw43,'newSourceComponentIDs':[r['id'] for r in rows],'canonicalGoalIDs':[i[0] for i in items],'threeExistingIDsNotNewGoals':True,'existingSevenCurrentSTBindingsExact':True,'protectedOtherSTRelationsExact':True,'wholeSourceClosure':False,'strictGain':0,'humanApproval':False})
print(json.dumps({'actualSTStage':'SekII common entry-phase','threeOldWrongStageRelationsRemoved':3,'threeBoundedExistingIDComponentsPrepared':3,'newCanonicalIDs':0,'wholeSTSummary':'HOLD','strictGain':0}))
