import json, hashlib
from pathlib import Path
from datetime import datetime, timezone
ROOT=Path('/home/enpasos/projects/skillpilot')
OUT=ROOT/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-09/biology-molecular-genetics-first-seven-independent-v-a-v1'
INPUT=OUT/'seven-actual-original-360-680.independent-A.input.first.freeze.json'
data=json.loads(INPUT.read_text())
def bind(p):
 b=p.read_bytes();return {'path':str(p.relative_to(ROOT)),'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)}
def put(name,x):
 p=OUT/name
 with p.open('x') as f:json.dump(x,f,ensure_ascii=False,indent=2);f.write('\n')
 return p
details=[
 {'mechanism':'Two duplicated homologous chromosome21 symbols enter the same MI daughter; the other lacks chromosome21. Normal MII separates their sister chromatids, giving two gametes with two chromosome21 copies and two with none.','geometry':'The blue/red X symbols persist together only after MI; four final cells correctly contain two single-chromatid rods or no chromosome21. The heading Chromosom21 bounds the blank-cell depiction to that chromosome, rather than depicting chromosome-free human gametes.','phone':'At360 all four principal labels and the chromosome symbols/arrows are clear. Large model objects show the error without needing a small legend.','desktop':'At680 and original the centromeres, X/rod distinction, branching arrows and model scope are readily visible.','perspective':'No actor-held directional object; this is a diagram for the outside viewer.','fit':'Friendly rounded cell/chromosome schematic is appropriate for SekI/introductory human meiosis and preserves the orientation function.','limit':'Only chromosome21 is shown; no actual gamete, patient, experiment or diagnosis is inferred.'},
 {'mechanism':'Chromosome findings, a visible trait and additional functional/health findings are separated into three panels. The question mark on the dashed relation prevents automatic disease inference.','geometry':'The magnifying-glass chromosome symbols are a generic schematic, not a numbered or claimed full karyotype. The heart/clipboard icons refer to independent health findings. Neither drawn learner is assigned a specific mutation or disease.','phone':'At360 the three headings, question mark and the two-line separation sentence remain readable. The small Zusatzbefunde/Körperfunktionen lettering is secondary to the readable main distinction.','desktop':'At680 the health icons and Zusatzbefunde label are clear and the footer can be read without zooming.','perspective':'Clipboard is a front-facing explanatory poster object; neither character is shown reading an inverted document. The eye/magnifier is a trait-observation icon.','fit':'Respectful comic learners and distinct blue/yellow/green panels are approachable; appearance is not presented as a diagnosis.','limit':'The characters are illustration, not real patient or learner evidence; the drawing does not establish a genotype for either person.'},
 {'mechanism':'DNA is shown as complementary antiparallel paired chains with A–T and G–C; the RNA example has a single sugar-phosphate chain with U. D/R distinguish the supplied sugar schematics.','geometry':'A–T/T–A show two interbase dashes; G–C/C–G show three. The two DNA arrows point in opposite directions. Backbone connections are solid and interbase links dashed.','phone':'At360 the bases, D/R sugars, double versus single chain and opposed arrows are distinct; the necessary labels DNA/RNA remain large.','desktop':'At680 and original the dashed bond counts and continuous backbones are clear.','perspective':'No actor or directional reading surface; antiparallel chain direction is a viewer-facing diagram relation.','fit':'Large colored molecular tokens meet the need to compare simplified structure models without a sterile atomic diagram.','limit':'This is a typical simplified RNA example, not a claim that all RNA is single-stranded or that D/R constitute a full chemical structural formula.'},
 {'mechanism':'Two coding-sequence examples ATG GAA and ATG GAG lead to AUG GAA/AUG GAG and both Met–Glu. Yellow reconstruction arrows return to two possible DNA examples under the visible Mehrere Möglichkeiten heading.','geometry':'The sequence letters and codon mapping are correct under coding-strand/left-to-right reading. The reverse arrows are a learner reconstruction relation, not a depicted biochemical protein-to-DNA synthesis pathway.','phone':'At360 DNA/mRNA, both codon strings, Met–Glu and Mehrere Möglichkeiten are large enough to read. Color-separated arrows retain forward versus reconstruction directions.','desktop':'At680 the two alternatives and the green converging arrows are clear; the gold reverse arrows terminate at the two DNA panels.','perspective':'The student looks toward the diagram; the open book has decorative lines and no inverted meaningful text. The pen/hand pose is plausible.','fit':'Comic learner plus simple mapping panels support the bidirectional code goal without pretending the raster is a full64-codon lookup instrument.','limit':'Coding strand/orientation assumptions need to remain in the bound teaching text. No stop codon or full protein function is claimed for the two-residue fragment.'},
 {'mechanism':'Bacterial DNA/mRNA/ribosome/tRNA and nuclear transcription/export through a visible pore to cytoplasmic translation are correctly distinguished at overview level. Lower icons illustrate catalytic, structural, transport and defense roles.','geometry':'The eukaryotic mRNA visibly crosses the nuclear boundary at a drawn pore; the ribosome is outside. Charged tRNA arrows approach ribosomes and protein chains leave. This is not a claim of simultaneous bacterial coupling or a full molecular enzyme equation.','phone':'HOLD: at360 the required mechanism labels mRNA/tRNA/Ribosom/Kernpore and the function labels/explanatory lines are reduced to roughly5–7 pixels or less. Headings remain clear, but essential detailed stages/functions cannot be reliably read at the intended phone size.','desktop':'At680 and original the same labels and flow are readable. The failure is the actual phone composition density, not PNG dimensions or an unviewed hash.','perspective':'No actor or instrument using a reversed surface; cell interiors are conceptual cutaways.','fit':'Friendly cells and protein-function icons fit the visual language, but the two-cell plus four-function layout is too dense at360.','limit':'The lower enzyme tokens are schematic rather than a stoichiometric equation; do not use the icon count as quantitative reaction evidence.'},
 {'mechanism':'A pre-mRNA from one gene has E1/E2/E3/E4 and intervening introns. Mature E1–E2–E4 versus E1–E3–E4 produces two color-consistent protein variants under the supplied exon-compatibility model.','geometry':'Shared E1/E4 and mutually selected E2/E3 are retained consistently in mature RNA and corresponding domain-color illustrations; intron connectors disappear. No evolutionary selection arrow or inheritance claim appears in the raster.','phone':'At360 E1–E4, both mature exon combinations, Spleißen and the two protein-variant labels remain readable. Tiny gray Intron annotations are supplementary; the gap/connector contrast is visible.','desktop':'At680 the pre-/mature-RNA labels and removed intervening segments are clear.','perspective':'No actor; all token order and process arrows are coherent for the outside viewer.','fit':'Large rounded exon/protein icons suit the molecular model; this is a bounded isoform illustration.','limit':'Raster PASS does not close the separately sealed whole-goal DE/EN prerequisite-claim finding BIO23-A-001. No inevitable selection, stable inheritance or actual protein-folding prediction is proved.'},
 {'mechanism':'The HIV-labeled sequence shows entry, RNA-to-DNA conversion, integration, transcription, ribosome/viral proteins, assembly and budding/new particles. The red block symbol targets reverse transcription as a possible intervention principle.','geometry':'HOLD: the visibly faceted, roughly hexagonal/polyhedral purple capsids at assembly and in HIV-labeled entering/new particles depict a generic polyhedral core rather than a recognizably tapered mature HIV capsid. A scientific source check confirms the mature HIV core is conical. The image also does not show a genomic-RNA packaging branch despite RNA drawn inside new particles.','phone':'HOLD: at360 Integration in Wirts-DNA, Virale mRNA, Virale Proteine and Ribosom shrink to roughly4–6-pixel text. Numbers1–7 and the large headings survive, but numbered circles alone do not name the essential stages.','desktop':'At680 the stage text is readable and the problematic capsid shapes are visible; original inspection confirms this is actual geometry, not a phone compression artifact.','perspective':'No actor; viewer-facing cutaway. The viral RNA export arrow reaches a cytoplasmic ribosome, and the integration inset lies inside the nucleus.','fit':'Approachable cell and particle drawing is suitable in style, but HIV-specific structure and phone readability need targeted correction.','limit':'The therapy symbol is a conceptual target, not evidence of treatment efficacy/safety. The raster does not prove host damage or actual viral investigation.'}
]
findings=[
 {'findingId':'V7-A-001','ordinal':5,'goalId':data['images'][4]['goalId'],'type':'RESPONSIVE_READABILITY','severity':'HOLD','actualWidth':360,'actualInspection':data['images'][4]['inspectionDerivatives'][0],'visibleAffectedRegions':[{'region':'cell mechanisms','approximatePhoneCoordinates':[65,38,352,117],'labels':['mRNA','tRNA','Ribosom','Kernpore']},{'region':'four protein functions','approximatePhoneCoordinates':[16,157,346,195],'labels':['Enzyme ermöglichen Reaktionen','Struktur gibt Stabilität','Transport bewegt Stoffe','Schutz unterstützt die Abwehr']}],'reason':'Essential mechanism/function text is around5–7px or below at the required360 width. Large headings do not make the tiny essential labels readable.','targetedRemedy':'Reduce layout density or enlarge the essential stages/function names so they are actually readable at360. Preserve correct nuclear export/cytoplasmic translation, protein-role distinctions, current whole goal and historical rasters. Reinspect the genuinely changed raster at all three sizes.'},
 {'findingId':'V7-A-002','ordinal':7,'goalId':data['images'][6]['goalId'],'type':'HIV_SPECIFIC_CAPSID_FORM','severity':'HOLD','actualInspection':data['images'][6]['selectedActualOriginal'],'visibleAffectedRegions':[{'region':'assembly polyhedral capsids','originalApproximateCoordinates':[1380,500,1454,647]},{'region':'entering and new HIV particles','originalApproximateCoordinates':[20,15,219,240]},{'region':'three new particles','originalApproximateCoordinates':[1278,60,1640,323]}],'reason':'The raster explicitly identifies HIV while using generic faceted/polyhedral core icons. Mature HIV is characteristically conical; hexameric building blocks do not make the entire core a regular polyhedron.','primaryVerification':{'url':'https://pubmed.ncbi.nlm.nih.gov/23719463/','doi':'10.1038/nature12162','actualRead':'Primary2013 abstract and figure4 description confirm a mature fullerene-cone model from cryo-ET/native core and atomistic model.'},'supportingPrimaryDataset':'https://www.rcsb.org/structure/3J3Q','targetedRemedy':'Draw recognizably tapered HIV cores for mature entry/new virions and retain a truthful distinction between assembly/budding and maturation. Do not fix a misleading shape only by adding caption text.'},
 {'findingId':'V7-A-003','ordinal':7,'goalId':data['images'][6]['goalId'],'type':'RESPONSIVE_READABILITY','severity':'HOLD','actualWidth':360,'actualInspection':data['images'][6]['inspectionDerivatives'][0],'visibleAffectedRegions':[{'region':'nuclear integration and transcript','approximatePhoneCoordinates':[179,64,231,123],'labels':['Integration in Wirts-DNA','Virale mRNA']},{'region':'host translation and assembly','approximatePhoneCoordinates':[239,144,318,172],'labels':['Ribosom','Virale Proteine']}],'reason':'Essential stage labels are about4–6px at360. Numbers1–7 retain visibility, but no readable stage key makes these numbered objects independently interpretable.','targetedRemedy':'Enlarge the essential stage text and objects or simplify the layout while preserving actual HIV-specific sequence and the distinction between genome and protein production.'}
]
rows=[]
for row,note in zip(data['images'],details):
 fs=[f['findingId'] for f in findings if f['ordinal']==row['ordinal']]
 rows.append({**row,'decision':'HOLD' if fs else 'PASS_KEEP_RASTER_CANDIDATE','actualOriginalViewed':True,'actual360Viewed':True,'actual680Viewed':True,'scientificMechanism':note['mechanism'],'scientificFormAndGeometry':note['geometry'],'phoneReadability':note['phone'],'desktopAndOriginalReadability':note['desktop'],'actorAndOutsideViewerPerspective':note['perspective'],'comicFormatAgeAndGoalFit':note['fit'],'orientationAndEvidenceLimit':note['limit'],'findings':fs,'currentNativeResourceAndPageApproval':False,'humanApproval':False,'humanTrial':False})
viewlog=put('actual-seven-original-360-680.view-log.independent-A.json',{'role':'Actual images returned to and visually inspected by this reviewer','views':[{'ordinal':r['ordinal'],'goalId':r['goalId'],'original':r['selectedActualOriginal'],'phone':r['inspectionDerivatives'][0],'desktop':r['inspectionDerivatives'][1],'allThreeActuallyViewed':True} for r in rows],'totalActualImageViews':21,'cropping':False,'inspectionResizeOnly':True,'generationOrAssetEditing':False})
verdict=put('seven-actual-raster-first.independent-A.verdict.json',{'schemaVersion':1,'role':'Independent actual V7 pixel science/geometry/perspective/readability FIRST before original/reconstruction prompt and candidate caption/alt-text reading','reviewer':'/root/bio_science14_independent_a','firstJudgmentAt':datetime.now(timezone.utc).isoformat(),'inputFirst':bind(INPUT),'ownWholeScienceFirst':data['ownScienceFirst'],'actualViewLog':bind(viewlog),'views':21,'counts':{'rasterCandidatesPassKeep':5,'rasterCandidatesHold':2,'nativeVApprovals':0,'strictGain':0},'findings':findings,'nonblockingScientificDetailToPreserve':{'ordinal':7,'scope':'Complete life-cycle teaching/source duty is not waived by a high-level orientation picture.','actualRasterObservation':'New particles contain RNA, but the only illustrated nuclear viral-RNA route leads to translation and proteins; no genome-RNA packaging branch is displayed.','recommendation':'Make genomic RNA contribution to assembly visible in a correction, or keep this omission explicit in the bound teaching explanation; do not interpret the proteins-only assembly arrow as evidence of genome copying.'},'images':rows,'wholeSciencePAndSourceReuse':'Own23 whole scientific first is exact prior input; selected7 goals/profiles/14 cases have the same actual whole bodies. Four old cases remain exact historical material reuse, not fresh native approval.','freshPeerVisualOrScienceRead':False,'authorVisualInspectionRecordsRead':False,'originalPromptsReadBeforeFirst':False,'reconstructionPromptsReadBeforeFirst':False,'candidateCaptionsAndAltTextReadBeforeFirst':False,'wholeSourceCourseApproval':False,'currentNativeResourceAndPageApproval':False,'humanApproval':False,'humanTrial':False,'actualExperimentPerformed':False,'actualLearnerPerformance':False,'activeWrites':[]})
files=[INPUT,verdict,viewlog,OUT/'materialize-seven-pixel-first.independent.py']+sorted((OUT/'inspection').glob('*.png'))
seal=put('seven-actual-raster-first.independent-A.freeze.json',{'schemaVersion':1,'role':'Immutable own V7 pixel first before peer pairing/provenance-prompt review','frozenAt':datetime.now(timezone.utc).isoformat(),'firstVerdict':bind(verdict),'boundOutputs':[bind(p) for p in files],'freshPeerRead':False,'humanApproval':False,'humanTrial':False,'nativeApproval':False,'strictGain':0})
print(json.dumps({'verdict':bind(verdict),'firstSeal':bind(seal)},ensure_ascii=False))
