import pathlib,json,hashlib,copy,shutil
R=pathlib.Path('/home/enpasos/projects/skillpilot');O=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/wirtschaft-current678-SEM-P43-book-technical-author-b-followers-v1';V=R/'curricula/DE/Gymnasium/quality/deep-understanding-rollout/wirtschaft-current678-international-operations-policy33-20261010-v17';C=pathlib.Path('/tmp/skillpilot-current678-technical-author-B-l9zrm5cl/capsule')
def rd(p):return json.loads(p.read_text())
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def b(p):return dict(path=str(p.relative_to(R)),sha256=h(p),bytes=p.stat().st_size)
i=rd(O/'actual-current678-five-native-Nav-FPs33-foreign-kind-only-author-inputs.json');reg=rd(R/i['oldRegistry']['path']);sub=next(s for s in reg['subjects']if s['subject']=='wirtschaftswissenschaften');sem=V/'wirtschaftswissenschaften.semantic-kinds.json';assert rd(sem)['counts']['total']==678
cfgs=[];newpaths=[];original={}
for n,rel in enumerate(sub['positiveEvidenceConfigPaths'],1):
 p=R/rel;old=rd(p);cp=V/'configs'/f'{n:02d}.positive.config.json';new=rd(cp);assert {k for k in new if new[k]!=old[k]}=={'semanticKindLedgerPath'};assert new['semanticKindLedgerPath']==str(sem.relative_to(R));cfgs.append({'old':b(p),'new':b(cp),'reviewWholeBytesUnchanged':b(R/old['reviewPath']),'onlyFieldChanged':'semanticKindLedgerPath'});newpaths.append(str(cp.relative_to(R)))
 for l in (R/old['reviewPath']).read_text().splitlines():
  if l.strip():r=json.loads(l);assert r['goalId']not in original;original[r['goalId']]=r
agg=V/'whole-current336-original-positive-profiles685cases-no-profile-or-input-change.jsonl';book=R/i['oldBookConfig']['path'];oldagg=R/rd(book)['evidenceReviewPaths'][0];assert agg.read_bytes()==oldagg.read_bytes();assert len(original)==336 and sum(len(q['profile']['applicationCaseBriefs'])for q in original.values())==685
rp=R/i['oldRegistry']['path'];rc=O/'whole-central-registry-only-Economics-v17-SEM-P43-pointers.INERT.json';bc=O/'whole-economics-book-config-current678-v17-SEM-P336.INERT.json';nr=rd(rc);nb=rd(bc);ns=next(s for s in nr['subjects']if s['subject']=='wirtschaftswissenschaften');assert {k for k in ns if ns[k]!=sub[k]}=={'semanticKindLedgerPath','positiveEvidenceConfigPaths'};assert ns['positiveEvidenceConfigPaths']==newpaths
assert {k for k in nb if nb[k]!=rd(book)[k]}=={'semanticKindLedgerPath','evidenceReviewPaths'}
f={'role':'TECHNICAL_AUTHOR_FOLLOWERS_OF_THREE_FOREIGN_WHOLE_SCIENCE; combined678 foreignScope pending','wholeBeforeCAN':i['canonicalBefore'],'wholeAfterCAN':i['canonicalCandidate'],'wholeAuthorIndex':i['wholeFieldwiseAuthorIndex'],'foreignWholeScientificBindings':i['foreignWholeScientificBindings'],'foreignCombined678ScopePending':'Root whole combined678 Scope KEEP pending; technical native checks cannot grant scope approval','oldRegistry':b(rp),'oldBookConfig':b(book),'oldKindLedger':i['oldSEM'],'newSEM':b(sem),'newPconfigs':newpaths,'all43ConfigChanges':cfgs,'all336OriginalWholeRecordsProfiles685CasesStatusesAuthorityAndInputFingerprintsExact':True,'newWholeP336':b(agg),'oldWholeP336Aggregate':b(oldagg),'newWholeP336AggregateByteExact':True,'candidateRegistry':b(rc),'candidateBookConfig':b(bc),'allOtherRegistrySubjectsWholeExact':True,'onlyEconomicRegistrySEMAndP43PointersChanged':True,'onlyEconomicBookSEMAndAggregatePPointersChanged':True,'newCurricularAtomicScientificClosures':0,'strictNetGain':0,'humanApproval':False,'activeWrites':0}
fp=O/'actual-v17-SEM678-P336685-book678-technical-only-freeze.json';assert not fp.exists();fp.write_text(json.dumps(f,ensure_ascii=False,indent=2)+'\n')
for p in [sem,agg]+[R/p for p in newpaths]:
 dst=C/p.relative_to(R);dst.parent.mkdir(parents=True,exist_ok=True);assert not dst.exists();shutil.copyfile(p,dst);assert not dst.samefile(p)
hist=O/'actual-first-pending678-author-index-key-and-dependent-no-file.history';hist.mkdir(exist_ok=True)
for name in ['author_current678_P43_registry_book_fields.py','actual-native43-positive.stdout.txt','actual-native43-positive.stderr.txt','actual-native43-positive.command-exit.json']:
 src=O/name;assert src.exists();shutil.copyfile(src,hist/name)
(hist/'actual-first-pending-key-failure.json').write_text(json.dumps({'firstAuthorExit':1,'missingKey':'authorHandoff','cause':'Final678 Authorhandoff not yet available; prepared bridge binds wholeFieldwiseAuthorIndex. Original metadata script still expected earlier final handoff field.','subsequentFirstNativeExit':1,'subsequentCause':'Dependent native run started before missing freeze file existed. No positive profile checks ran or passed in failed run.','remedy':'Verify all already created43 field-only files, add pending-scope technical freeze and install physical clones, then actual native43 run.','activeWrites':0,'nativeThresholdChanged':False},indent=2)+'\n')
shutil.copyfile('/tmp/complete_678_P43_pending_technical_B.py',O/'complete_pending678_existing_P43_fields.py');print(json.dumps({'pendingFreeze':b(fp),'configs':43,'SEM':678,'profileRecords':336,'cases':685,'foreignScopePending':True}))
