import assert from 'node:assert/strict'
import {readFileSync,writeFileSync} from 'node:fs'
import {resolve} from 'node:path'
import {pathToFileURL} from 'node:url'
import {createHash} from 'node:crypto'
import {createRequire} from 'node:module'
const root=resolve('.'),base='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-06/'
const own=base+'chemie-current-aromatic-delocalization-final-native-author-v6',v3=base+'chemie-current-fifteen-final-native-review-inputs-author-v3'
const read=(p:string)=>JSON.parse(readFileSync(resolve(root,p),'utf8')),sha=(b:string|Buffer)=>'sha256:'+createHash('sha256').update(b).digest('hex'),bind=(p:string)=>({path:p,sha256:sha(readFileSync(resolve(root,p))),bytes:readFileSync(resolve(root,p)).length}),write=(p:string,v:any)=>writeFileSync(resolve(root,own,p),JSON.stringify(v,null,2)+'\n')
const iso=read(own+'/temporary-isolated-root.reuse.author.json'),isolatedRoot=iso.isolatedRootUsed,gid='b8d3b453-d638-5518-aab0-d84ec2e8567c'
const paths=['app/scripts/materializePositiveGoalEvidenceCandidates.ts','app/scripts/positiveGoalEvidenceProfileModel.ts','app/scripts/positiveGoalEvidenceReview.ts'];for(const p of paths)assert.equal(bind(p).sha256,sha(readFileSync(resolve(isolatedRoot,p))))
const {buildPositiveGoalEvidenceCandidateRecords}=await import(pathToFileURL(resolve(isolatedRoot,'app/scripts/materializePositiveGoalEvidenceCandidates.ts')).href),{reviewPositiveGoalEvidenceConfig}=await import(pathToFileURL(resolve(isolatedRoot,'app/scripts/positiveGoalEvidenceReview.ts')).href),{validatePositiveGoalEvidenceRecordSemantics}=await import(pathToFileURL(resolve(isolatedRoot,'app/scripts/positiveGoalEvidenceProfileModel.ts')).href)
const config=read(own+'/positive-evidence.aromatic-one.native-author-candidate.config.json'),spec=read(own+'/positive-one-profile.exact-v2-science.author-candidate.json'),materials=read(own+'/two-complete-aromatic-materials.de-en.exact-v2.json'),goal=read(config.landscapePath).goals.find((g:any)=>g.id===gid)
assert.equal(spec.goals.length,1);assert.equal(materials.materials.length,2);assert.equal(materials.caseCount,2);assert.deepEqual(spec.goals[0],read(v3+'/fifteen-positive-profile-specifications.exact-v2.json').goals.find((s:any)=>s.goalId===gid))
for(const c of materials.materials)assert.deepEqual(c,read(v3+'/thirty-complete-materials.de-en.exact-v2.json').materials.find((m:any)=>m.caseId===c.caseId))
const records=await buildPositiveGoalEvidenceCandidateRecords({config,candidateSet:spec});assert.equal(records.length,1);const record=records[0];assert.equal(record.status,'needs_human_review');assert.equal(record.reviewAuthority,'ai_candidate');assert.equal(record.evidenceLevel,'E1');assert.equal(record.maximumClaimScope,'G1');assert.deepEqual(record.reviewRunIds,[])
const req=createRequire(resolve(root,'app/package.json')),Ajv=req('ajv/dist/2020').default,formats=req('ajv-formats').default,ajv=new Ajv({strict:true,allErrors:true});formats(ajv);const rs=ajv.compile(read('contracts/goal-evidence/v2/goal-evidence-profile.schema.json')),cs=ajv.compile(read('contracts/goal-evidence/v2/goal-evidence-review-config.schema.json'));assert.ok(rs(record),ajv.errorsText(rs.errors));assert.ok(cs(config),ajv.errorsText(cs.errors))
const resources:Record<string,string>={};for(const l of goal.resourceLinks.filter((l:any)=>l.type==='goal-visualization'))resources[l.url]=sha(readFileSync(resolve(isolatedRoot,'app/public'+l.url)));assert.equal(Object.values(resources)[0],iso.expectedB8SHA256);assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(record,goal,resources,'curricularAtomic'),[])
const old=readFileSync(resolve(root,v3,'positive-evidence.fifteen.prospective.native-author-candidates.review.jsonl'),'utf8').trim().split('\n').map(l=>JSON.parse(l)).find(r=>r.goalId===gid);assert.notEqual(record.goalFingerprint,old.goalFingerprint);assert.notEqual(record.reviewInputFingerprint,old.reviewInputFingerprint);assert.equal(record.profileFingerprint,old.profileFingerprint);assert.equal(record.reviewCriteriaFingerprint,old.reviewCriteriaFingerprint);assert.deepEqual(record.profile,old.profile)
for(const c of materials.materials){const b=record.profile.applicationCaseBriefs.find((b:any)=>b.id===c.caseId);assert.ok(b);for(const lang of ['de','en']){const s=lang[0].toUpperCase()+lang.slice(1);assert.equal(b['taskDemand'+s],c.material[lang]+' '+c.taskDemand[lang]);assert.equal(b['expectedPerformance'+s],c.expectedPerformance[lang]);assert.equal(b['understandingFocus'+s],c.specificBoundaryOrCounterexample[lang])}}
writeFileSync(resolve(root,config.reviewPath),JSON.stringify(record)+'\n');const result=reviewPositiveGoalEvidenceConfig(own+'/positive-evidence.aromatic-one.native-author-candidate.config.json');assert.deepEqual(result.errors,[]);assert.deepEqual(result.counts,{approved:0,needsHumanReview:1,rejected:0})
write('native-aromatic-single-positive-current-goal-material-binding-checks.actual.json',{schemaVersion:1,createdAtUTC:new Date().toISOString(),role:'AUTHOR actual isolated current text/resource fingerprints through full unchanged native P materializer/checker, no new science approval',goalId:gid,nativeMaterializer:'PASS1',nativeFullChecker:'PASS1',closedRecordAndConfigSchemas:'PASS',nativePureSemantics:'PASS',errors:result.errors,counts:result.counts,wholeScientificProfileAndTwoCompleteMaterialsExactV3:true,profileFingerprintExactV3:true,criteriaFingerprintExactV3:true,goalAndReviewInputFingerprintsChangedForExactlyTwoDescriptionFields:true,before:{goalFingerprint:old.goalFingerprint,reviewInputFingerprint:old.reviewInputFingerprint},prospective:{goalFingerprint:record.goalFingerprint,reviewInputFingerprint:record.reviewInputFingerprint,profileFingerprint:record.profileFingerprint,reviewCriteriaFingerprint:record.reviewCriteriaFingerprint},currentActualResourceDigests:resources,actualB8PNGUnchanged:true,helperBindings:paths.map(bind),status:record.status,reviewAuthority:record.reviewAuthority,newIndependentPApproval:false,findingResolved:false,nativeActiveBinding:'PENDING_INTEGRATION: frozen image resides only in inactive candidate package and physical temporary staging',humanApproval:false,humanTrial:false,actualLearnerEvidence:false,activeWrites:false,strictNetGain:0,newScientificClosures:0,restoredActiveBindings:0})
console.log(JSON.stringify({nativeMaterializer:'PASS1',nativeFullChecker:'PASS1',scientificProfileAndTwoMaterialsExact:true,goalAndInputFingerprintsCurrent:true,actualB8PNGUnchanged:true,status:record.status,activeWrites:false,strictNetGain:0}))
