#!/usr/bin/env python3
"""Independent whole assessment review with original answers and honest manual scoring."""
import hashlib,json,subprocess
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path('/home/enpasos/projects/skillpilot');OUT=Path(__file__).resolve().parent
def load(n):return json.loads((OUT/n).read_text())
def bind(p):
 p=Path(p);p=p if p.is_absolute() else ROOT/p;b=p.read_bytes();return {'path':str(p.relative_to(ROOT)),'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b),'symlink':p.is_symlink()}
def save(n,o):
 p=OUT/n;assert not p.exists();p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n');return bind(p)
intake=load('actual-three-frozen-whole-DEEN-bodies-eight-current-contracts-and-seven-P16.intake.json');mats={g['id'][:8]:g for g in intake['wholeBodies']};works=[]
def work(stem,label,answers,points,reasons,cap=None):
 g=mats[stem];rubric=g['examData']['scoring'];assert len(answers)==len(points)==len(reasons)==4
 assert all(0<=p<=s['points'] for p,s in zip(points,rubric['steps']))
 raw=sum(points);final=min(raw,cap) if cap is not None else raw
 works.append({'workId':stem+'-'+label,'materialId':g['id'],'origin':'Own independent reviewer synthetic submission; not learner/session/coach-grader evidence','wholeFourPartOwnSubmission':[{'taskId':s['id'],'wholeOwnAnswer':a,'manualPoints':p,'maxPoints':s['points'],'gradingReason':r} for s,a,p,r in zip(rubric['steps'],answers,points,reasons)],'manualRawPoints':raw,'essentialTotalAbsenceCap':cap,'finalPoints':final,'passingPoints':rubric['passingPoints'],'manualVerdict':'PASS' if final>=rubric['passingPoints'] else 'FAIL','authorCounterworkReused':False})

work('a7bd6f96','whole-correct-independent',[
 'Parteimitglieder ab dem gegebenen Erwachsenenalter bilden intern einen Vorschlag und können Vorstand/Fraktionslinie beeinflussen; acht von20 Ratssitzen verleihen der Partei allein keinen Mehrheitsbeschluss des ganzen Rats. Die ab16 zugängliche Petition erreicht mit1.400 die Schwelle1.000 und erzwingt eine Anhörung, keinen Linienbau. Der Ausbildungsverband kann Argumente öffentlich einbringen, hat aber keine Stimme. Einfluss, Zugang und die beim Rat verbleibende Entscheidung sind auseinanderzuhalten.',
 'Der Rat kann repräsentativ Verantwortung übernehmen; öffentliche Abstimmungsgründe ermöglichen nachträgliche Kritik. Verfügbare Kosten/Alternativen helfen informierter Beteiligung. Zugleich sind unter16 Betroffene von Parteimitgliedschaft und Petition ausgeschlossen und späte Schichten erschweren den Zugang. Ein zusätzliches verständliches schriftliches Verfahren und wiederholte Termine könnten diese Perspektiven aufnehmen, müssen aber tatsächlich ausgewertet werden; sie garantieren weder gleiche Beteiligung noch eine bestimmte Ratsentscheidung.',
 '1.200/4.000 ergibt30Prozent Beteiligung;720/1.200 ergibt60Prozent X-Anteil an gültigen Stimmen;720/4.000 wären18Prozent aller Berechtigten. Das1.000-Quorum ist erfüllt, doch eine höhere Zustimmungszahl setzt die vorgegebene Zugangsschutzregel nicht außer Kraft. X muss so angepasst oder erneut behandelt werden, dass der barrierearme Zugang erhalten wird. Die150 regelmäßig Nutzenden dürfen nicht allein wegen ihrer Minderheitenposition übergangen werden. Mehrheitsentscheidung und umfassende Legitimation sind verschiedene Fragen.',
 'Die direkte Abstimmung gibt unmittelbare Mitwirkung und ein klares Ergebnis, hier aber nach einseitiger Information. Der Ratsweg kann Alternativen und betroffene Gruppen begründet abwägen und benennbare Verantwortung schaffen; seine Repräsentation kann dennoch Interessen übergehen. Ich würde vor der endgültigen Entscheidung eine neutrale zugängliche Kosten-/Zugangsanalyse, Anhörung und veröffentlichte Schutzprüfung verlangen. Danach kann auch ein erneuter direkter Entscheid legitim sein, wenn Regeln und Zugang tatsächlich gewahrt sind; ein Ratsbeschluss ist ohne diese Prüfung ebenfalls nicht automatisch überlegen.'
],[6,6,6,6],['All three mechanisms/access/authority correctly separated','Two concrete criteria plus disadvantaged-group remedy and limit','Correct denominators/quorum plus actual safeguard application','Balanced actual comparison, improvement and conditional criteria-based judgment'])
work('a7bd6f96','imperfect-meaningful-PASS',[
 'Die Petition bewirkt hier Anhörung und die Partei wirkt über Fraktion/gewählten Vorstand; der Rat beschließt. Die Verbandsmeinung ist keine Ratsstimme. Die unterschiedlichen Altersgrenzen kann ich nicht vollständig vergleichen.',
 'Öffentliche Gründe machen den Rat kritisierbar und Wahl ermöglicht Repräsentation. Schriftliche Eingaben können Schichtarbeitende erreichen. Ich erkläre keine konkrete Grenze dieser Verbesserung.',
 'Es stimmen30Prozent aller Berechtigten ab; X hat60Prozent der gültigen Stimmen. X muss den geschützten Zugang erhalten, da die Schutzregel auch bei einem Mehrheitsentscheid gilt. Den genauen Zusammenhang des Quorums und der unterschiedlichen Bezugsgrößen führe ich nicht aus.',
 'Direkte Abstimmung ermöglicht selbst zu entscheiden, ist hier aber schlecht informiert; ein Rat kann Fachargumente berücksichtigen, kann Betroffene jedoch übergehen. Eine gemeinsame Anhörung verbessert Information. Ich würde den Ratsweg mit dokumentierter Schutzprüfung bevorzugen, ohne alle weiteren Kriterien zu behandeln.'
],[4,5,4,4],['Mechanisms/authority4; detailed access comparison absent','Two applied criteria4; suitable improvement1; limit missing','Correct percentages2 and safeguard2; denominator/quorum explanation missing','Balanced comparison2 plus conditional/limited improvement2; incomplete detail earns partial credit'])
work('a7bd6f96','influence-counts-equal-authority-FAIL',[
 'Die Mitgliedschaft steht Erwachsenen offen und die Petition Einwohnern ab16; deshalb dürfen Partei und Unterzeichnende jeweils selbst entscheiden.1.400 Unterschriften sind bereits der verbindliche Linienbeschluss, die Anhörung ist unnötig. Der Verband darf ebenfalls verbindlich abstimmen, weil er öffentlich Interessen äußert.',
 'Legitimität bedeutet nur möglichst viele Unterstützende.1.400 sind mehr als20, daher brauchen wir weder Ratsverantwortung noch Information über die Betroffenen.',
 'Turnout30Prozent, X60Prozent gültiger Stimmen, Quorum1.000 erreicht. Weil720 mehr als480 ist, dürfen die150 Wegnutzenden und die Schutzregel vollständig ignoriert werden.',
 'Direkter oder Ratsweg ist gleichgültig, sofern irgendeine Zahl eine Mehrheit enthält. Informationsprobleme, Beteiligungszugang und Verantwortung spielen dann keine Rolle.'
],[2,0,4,0],['Correct age/access facts2; claimed authority and mechanisms wrong','No correct case-specific legitimacy reasoning','Rates/denominators and quorum4; actual safeguard claim wrong','No meaningful requested comparison/improvement/conditional legitimacy judgment'],14)

work('2bc079fa','whole-correct-independent',[
 'Die zwölf Heimarbeitenden sparen12×2×60=1.440Minuten, also24Stunden Pendelzeit insgesamt oder2Stunden je Person/Woche. Das erleichtert Alltag und kann Flexibilität bringen, ist aber kein zusätzlicher betrieblicher Output oder Arbeit je Stunde. Nachrichtenpflicht7–22 und an freien Tagen kann Freizeitgrenzen auflösen. Die acht vorOrt Tätigen gewinnen diesen Wegeffekt nicht; planbare Schichten sind ein anderer Vorteil und nicht nachgewiesen gleich groß.',
 'Vereinbarte Antwortzeiten plus Notfallvertretung halten Zusammenarbeit aufrecht, ohne dauerndes Online-Sein als Leistung zu belohnen. Ich würde gemeinsam feste Übergabezeiten, Ergebnisziele und einen erreichbaren Vertretungsplan definieren und die Standortgruppe an planbaren Schichten beteiligen. Wir brauchen Angaben zu tatsächlichen Spitzen, Ergebnisqualität und Vertretungsbedarf. Die Regeln können Entlastung ermöglichen, garantieren aber weder gleichen Nutzen noch einen gemessenen Gesundheitsgewinn.',
 'Vorher100×10=1.000Minuten menschliche Routineprüfung, nachher20×15=300Minuten;700Minuten weniger betreffen nur diese Aktivität. Automatische Vorprüfung kann Routine freimachen und sorgfältigere komplexe Bearbeitung ermöglichen. Einführungs-/Schulungskosten, neue Fehler und Betreuungszeit fehlen jedoch. Ohne sie und übrige Aufgaben sind weder Netto-Gesamtproduktivität noch eine bestimmte Zahl abgebauter Stellen belegt; im Fall bleibt die Personalzahl zunächst zehn.',
 'Komplexere Aufgaben brauchen geeignete Schulung und einen menschlichen Eskalationsweg. Alternative bezahlte Kurszeiten könnten die vier bisher ausgeschlossenen Personen beteiligen; erreichbare qualifizierte Verantwortliche müssen Fehlerfolgen prüfen. Zweckgebundene nachvollziehbare Qualitätskontrolle ist sinnvoll, dauernde Überwachung wäre damit nicht automatisch begründet. Gesellschaftliche Teilhabe kann sich verbessern, wenn Zugang und Qualifikation verteilt werden, oder verschlechtern, wenn nur die sechs Geschulten profitieren. Der Nutzen bleibt bedingt durch Qualität, Schulungszugang und Aufwand.'
],[6,6,6,6],['Time/unit/mechanism/groups/scope correct','Concrete design mechanisms, fair proposal, needed information and limit','Human-time calculation and appropriate quality/productivity/jobs limits','Task participation, specific responsibility design and connected conditional social judgment'])
work('2bc079fa','imperfect-meaningful-PASS',[
 'Die Gruppe spart1.440Minuten proWoche. Das kann freie Zeit schaffen, die Antwortpflicht bis22Uhr belastet aber. Zu Vergleich und Vorteil der Standortgruppe sage ich nichts.',
 'Ich würde Antworten auf die Vertragsarbeitszeit begrenzen und eine Vertretung vorsehen. Die Standortgruppe sollte über Schichtplanung mitreden. Die erforderliche zusätzliche Information oder konkrete Grenze lasse ich offen.',
 'Die Routinezeit fällt von1.000 auf300Minuten. Es bleibt mehr Zeit für komplexe Fälle und700Minuten sind kein Nachweis für ganze weggefallene Stellen. Einführung, Betreuung und Netto-Gesamtproduktivität erläutere ich nicht weiter.',
 'Vier Personen brauchen andere bezahlte Schulungszeiten und klare erreichbare menschliche Fehlerverantwortung. Sonst werden Chancen ungleich verteilt. Ich befürworte das System nur mit diesen Vorkehrungen; eine genaue Kontrolle ihrer Wirksamkeit habe ich noch nicht entwickelt.'
],[4,4,4,5],['Calculation2 and genuine benefit/risk mechanism2; group comparison/scope missing','Mechanisms and fair concrete proposal4; additional information/limit absent','Calculation2 and benefit/job-scope partial reasoning2; net-quality discussion incomplete','Task access2, specific responsibility/design2 and conditional social judgment1'])
work('2bc079fa','only-calculations-no-work-mechanism-FAIL',[
 '12×2×60=1.440Minuten=24Stunden. Zu Auswirkungen auf die beiden Gruppen und der Nachrichtenregel gebe ich keine Antwort.',
 'Digitale Geräte sind gut, weil sie modern sind. Ich nenne keine Antwortzeitregel, Zusammenarbeit, Gruppe oder benötigte Information.',
 '100×10=1.000 und20×15=300, Differenz700Minuten. Ob das Arbeitsplätze, Qualität oder Gesamtproduktivität betrifft, diskutiere ich nicht.',
 'Technik gewinnt immer. Ausbildung, die vier Ausgeschlossenen und menschliche Verantwortung behandle ich nicht.'
],[2,0,2,0],['Correct calculation only2','No proper case-specific design reasoning','Correct calculation only2','No proper task/participation/responsibility judgment'],14)

work('16955ace','whole-correct-independent-with-conditional-buffer',[
 'Eigene Tabelle A: A1=360,A2=150,A3=100,A4=120,A5=30,A6=A4/12,A7=SUM(A2,A3,A5,A6),A8=A1-A7. Damit Reserve10, verwendete Mittel einschließlich Sparziel290, Rest70. Nur A4 auf180 geändert ergibt automatisch Reserve15, Mittel295 und Rest65. Dies sind reservierte Monatsmittel; nach zwölf unverändert finanzierten Monaten entstehen120/180 für die dann fällige Versicherung. Die Zahlung wird nicht ein zweites Mal als Monatsausgabe gerechnet. Anfangsreserve0 reicht für frühere Zahlung nicht, diese ist hier aber erst nach zwölf Monaten fällig.',
 'Die parallelen Raten samt Gebühren sind24+36+2+2=64 proMonat und768 über12Monate. Vom Rest70 bleiben6, von65 bleibt1. Schon zusätzliche10Ausgaben verursachen−4/−9, deshalb bieten kleine Einzelraten keine ausreichende Sicherheitsreserve. Zusätzlicher Kredit für alte Raten kann Gebühren und künftige Verpflichtungen vergrößern. Ein Kaufaufschub vermindert die gemeinsame Bindung; eine Ausgabenkürzung müsste tatsächlich möglich sein, eine Kürzung der Sparrate würde das erklärte Ziel verändern. Ein knappes Modellbudget beweist keine rechtlich dauerhafte Überschuldung.',
 'Neue Tabelle B: T1=300,T2=120,T3=80,T4=120,T5=20,T6=T4/12,T7=SUM(T2,T3,T5,T6),T8=T1-T7. Sie hat eigene Einnahme-/Ausgabenzellen und ergibt Reserve10, Mittel230, Rest70. Nur T1=220 ändert den Rest automatisch auf−10, Reserve/Sparziel bleiben unverändert. Diese spätere Einnahme ist nur angenommen. Der Plan braucht bei ihrem Eintreten eine erklärte Anpassung oder einen begrenzten Puffer; Zahlungsverpflichtung nach zwölf Monaten ist über die monatliche Rücklage abgedeckt, soweit sie wirklich gebildet wird.',
 'K kostet240 sofort und insgesamt, lässt10 der separaten250 und hat keine Kreditrate. R kostet24×12+24=312, also72 mehr, benötigt24 sofort und lässt226, bindet aber12 monatlich24Monate. R lässt zunächst58 und im angenommenen220-Szenario−22 monatlich. Eine plausible andere Gewichtung kann den frühen Puffer bevorzugen: Nur unter der zusätzlichen Annahme, dass sämtliche sechs Überschüsse58 gespart werden und220 tatsächlich18weitereMonate eingehen, wächst er auf574 und fällt um18×22=396 auf178. K hätte analog250 am Ende; der Unterschied72 entspricht dem Mehrpreis. Das zeigt eine begrenzte Liquiditätsbrücke statt automatisch bewiesener Überschuldung, garantiert aber keine zukünftigen220 oder sonstige Kostenfreiheit. Ich bevorzuge K, wenn10 sofortige Sicherheitsreserve genügen; andernfalls braucht R einen ausdrücklich belegten Zahlungsplan. Die sechs gesicherten Monate allein garantieren keinen der24-Monats-Verläufe.'
],[8,8,8,6],['Own executable formulas, one-cell variation and correct annual reserve timing','Actual joint/term burden, both rests, risk chain and bounded reaction','Independent table/variation plus expectations and timing','All costs/liquidity/month/duration tradeoffs; valid alternative finite-buffer reasoning expressly conditional'])
work('16955ace','no-executable-formulas-FAIL',[
 'Alle Endzahlen habe ich fest eingetippt: Jahres120 ergibt Monatsrücklage10, Einnahmen360, Ausgaben150/100, Sparziel30, Rest70. Danach rechne ich neu vonHand: Jahres180, Reserve15, Rest65. Ich gebe ausdrücklich keine Zellbezüge oder Formeln an; kein Ergebnis ändert sich durch Eingabeänderung. Die Jahreszahlung nach zwölf Monaten wird aus der Rücklage gezahlt und nicht doppelt monatlich abgezogen.',
 'Gemeinsam sind es64monatlich und768insgesamt. Daraus folgen6 beziehungsweise1Rest, bei10Extraausgaben−4/−9. Neue Schulden für alte Raten können Verpflichtungen erhöhen. Aufschieben eines Kaufs kann helfen, falls er nicht sofort nötig ist; eine Sparzielkürzung ist eine erklärte Zieländerung.',
 'Auch B enthält nur fest eingetragene Resultate: Einnahmen300, Ausgaben120/80, Rücklage10, Sparziel20, Rest70. VonHand trage ich für220Einnahmen den Rest−10 neu ein. Formeln und automatische Eingabevariation fehlen auch hier vollständig. Die erste Jahreszahlung folgt nach zwölf Monaten, wenn monatlich gespart wird; das spätere Einkommen ist unsicher.',
 'K kostet240 und lässt10 liquide Mittel. R kostet312, erfordert24sofort, lässt226, bindet12monatlich24Monate und lässt58/−22 unter den beiden Einkommen. Deshalb ist K billiger, R liquiditätsschonender zuBeginn, aber die sechs sicheren Monate garantieren kein24-Monats-Einkommen. Ein Urteil hängt von nötiger Reserve und einem konkreten künftigen Plan ab.'
],[4,8,4,6],['Input/period2 and reserve/due-date2; formulas0 and actual automatic variation0','Correct whole credit reasoning8','Independent inputs/period2 and expectations/reserve2; formulas0 and actual variation0','Correct whole cost/liquidity/duration reasoning6'],17)
work('16955ace','credit-as-isolated-rates-no-budget-or-time-risk-FAIL',[
 'Ich benutze die korrekten tatsächlichen A-Zellformeln A1 bisA8 aus meiner separaten Tabelle: Reserve10, Rest70 und nach alleinigerA4-Änderung Reserve15, Rest65. Zahlung ist erst nach zwölf Ansparmonaten fällig, keine Doppelzählung. Kreditbezogene A9/A10 sind nicht Teil dieser Antwort.',
 '24ist weniger als70 und36ist weniger als70. Deshalb ist jeder Kauf sicher bezahlbar. Die gemeinsame Verpflichtung, Gebühren und geänderte Reserve müssen nicht addiert werden. Schulden zur Zahlung alter Käufe schaffen kein zusätzliches Risiko, weil jede einzelne Rate klein aussieht.',
 'Unabhängige B-Formeln T1 bisT8 ergeben Reserve10 und Rest70 beziehungsweise−10 bei alleiniger Einnahmeänderung auf220. Die Rücklage bleibt zweckgebunden, die Jahreszahlung ist erst nach zwölf Monaten fällig. Der−10-Plan muss ohne neue Finanzierung geändert werden. Kreditbezogene T9/T10 werden hier nicht benutzt.',
 'K kostet insgesamt240 und lässt250−240=10 sofort. R kostet24×12+24=312 und lässt250−24=226 sofort. Die12proMonat sind klein, daher sicher24Monate bezahlbar; die sechs sicheren Einkommensmonate reichen dafür automatisch. Die monatlichen Restmittel und das nur angenommene spätere Einkommen beziehe ich nicht auf die Kreditbindung.'
],[8,0,8,2],['Correct independent formula/variation/reserve performance8','No correct combined commitment/budget-risk response','Correct independent formula/variation/reserve performance8','Correct total/immediate arithmetic2; repayment ability/duration/conditional judgment consistently wrong'],17)
work('16955ace','imperfect-genuine-budget-and-credit-PASS',[
 'A1=360,A2=150,A3=100,A4=120,A5=30,A6=A4/12,A7=SUM(A2,A3,A5,A6),A8=A1-A7 ergeben10Reserve und70Rest. Bei nurA4=180 entstehen15/65 automatisch. Reserve und tatsächliche Fälligkeit/Doppelzählung erläutere ich nicht.',
 'Beide Verpflichtungen gemeinsam kosten64monatlich; daraus bleiben6/1, ein zusätzlicher Aufwand10ergibt−4/−9. Kredit zur Bedienung alter Raten kann weitere Verpflichtungen erzeugen. Ich schiebe einen nicht dringlichen Kauf auf, erläutere dessen konkrete verbleibende Grenze aber nicht. Die zwölfmonatige Gesamtsumme berechne ich nicht.',
 'Ich erstelle B mit eigenen T1=300,T2=120,T3=80,T4=120,T5=20,T6=T4/12,T7=SUM(T2,T3,T5,T6),T8=T1-T7. Reserve10/Rest70, beiT1=220 bleibt−10. Den Anfangsbestand, Fälligkeit und gesicherten Zeitraum diskutiere ich hier nicht weiter.',
 'K benötigt240und lässt10 sofort; R kostet312gesamt,24sofort und lässt226. R lässt58oder−22monatlich, daher kann die unsichere Einnahme neue Probleme erzeugen. Ich vermeide eine Bezahlbarkeitsgarantie, erläutere aber die24-Monats-Bindung und mein konkretes bedingtes Auswahlurteil nicht vollständig.'
],[6,6,6,4],['Inputs/formulas/automatic variation6; separate reserve-time explanation missing','Combined monthly1, rests2, risk mechanism2, response partial1; term total/limit missing','Independent inputs/formulas/variation6; expectation/timing discussion missing','Costs/immediate and monthly arithmetic with partial risk4; duration/judgment incomplete'])

assert len(works)==10
assert sum(len(w['wholeFourPartOwnSubmission']) for w in works)==40
assert [w['manualVerdict'] for w in works]==['PASS','PASS','FAIL','PASS','PASS','FAIL','PASS','FAIL','FAIL','PASS']
counter=save('actual-ten-whole-own-counterworks-and40-manual-rubric-decisions.json',{'reviewer':'/root/economics_m2_views_independent_b','actualWholeOwnSyntheticSubmissions':works,'actualManualStepDecisions':40,'creditNegativeRaw18To17AndFormulaNegative22To17ActuallyExercised':True,'imperfectMeaningfulAnswersPassWithoutTotalAbsenceCap':True,'actualLearnerOrPrivateDataUsed':False,'actualCoachGradeRunClaimed':False,'authorCounterworkOrScoreEvidenceReused':False})
source=save('actual-official-GG20-21-primary-check-and-fictitious-procedure-boundary.json',{'reviewedAt':datetime.now(timezone.utc).isoformat(),'actualOfficialPagesBrowsed':[{'title':'Art20 GG','url':'https://www.gesetze-im-internet.de/gg/art_20.html','boundedParaphrase':'Democratic authority is exercised through elections, votes and state organs and remains constrained by constitutional and legal requirements.'},{'title':'Art21 GG','url':'https://www.gesetze-im-internet.de/gg/art_21.html','boundedParaphrase':'Parties participate in political preference formation and must have a democratic internal organisation.'}],'verbatimWordsQuoted':0,'specificMunicipalRulesAssertedCurrentLaw':False,'fictionalAgesQuorumsSeatsProceduresSafeguardsRemainSuppliedSimulationRules':True,'individualLegalAdviceClaimed':False})
goals={g['id']:g for g in intake['wholeOriginalAuthorContext']['wholeGoals']};primary=set(intake['wholeOriginalAuthorContext']['ordinaryContractsDirectlyExamined']);assert len(primary)==4
decisions=[]
for stem,interpretation in [
 ('a7bd6f96','Both separate public decisions require actual institutional mechanisms and explicit legitimacy criteria. Party internal participation, petition hearing and association input are separated from council authority; a second actual direct/representative comparison applies information, minority access and accountability. Quotas use distinct denominators. Neither majority numbers nor a generic party role substitute for the full76a performance.'),
 ('2bc079fa','Remote work and an independent routine-checking change provide concrete benefits, mechanisms, distribution, training and responsibility. Actual commute/private-time and bounded human-task-time calculations are separated from empirical output, health, net productivity and whole-job claims. Each case supports a conditional design judgment with differently affected groups.'),
 ('16955ace','Two independent constructed budgets contain income, fixed/variable expenditure, annual reserves and savings. Executable alternative cell layouts genuinely propagate separate annual-cost and income input changes. Joint fees/instalments and term cost, timing, one-off liquidity and unsecured later income require actual credit-risk reasoning. The finite-buffer alternative demonstrates that a negative monthly flow is not automatically legal overindebtedness; it remains conditional on surplus retention and future income.')
]:
 g=mats[stem];assert g['requires']==g['examData']['coveredGoalIds'];assert set(g['requires']).issubset(primary)
 decisions.append({'materialId':g['id'],'wholeDecision':'KEEP whole bounded DRAFT task/solution/rubric/required-performance candidate','wholeCoveredContracts':[goals[i] for i in g['examData']['coveredGoalIds']],'scientificMeaning':interpretation,'actualOwnCounterworks':[w['workId'] for w in works if w['materialId']==g['id']],'directFullAssessedContractRequiresFit':True,'transitiveExistingRequiresUniversalityNewlyApproved':False,'wholeDEENTaskSolutionMeaningAndNumbersEquivalent':True,'scoringAndPassThresholdUnchanged':g['examData']['scoring'],'essentialCapOnlyWhollyAbsentOrConsistentlyWrongCore':True,'newPracticeAssessmentSemanticKindScientificallyAppropriate':True,'oldSourceGoalOrWholeCountryCourseScopeApproved':False,'reviewStatusStill':'draft','actualLearnerMasteryHumanApprovalOrTrialClaimed':False})
science=save('actual-three-whole-DEEN-materials-four-current-performances-ten-own-works-scientific-KEEP.independent-b.json',{'reviewer':'/root/economics_m2_views_independent_b','reviewedAt':datetime.now(timezone.utc).isoformat(),'status':'KEEP whole three bounded DRAFT science candidates','exactAuthorWholeBodiesSHA256':'dfb3fe708e8a9f53f0b1c4137240aa99090104a0a4d1571f1e56576da0e87abd','wholeInput':bind(OUT/'actual-three-frozen-whole-DEEN-bodies-eight-current-contracts-and-seven-P16.intake.json'),'individualWholeDecisions':decisions,'actualOriginalOwnCounterworks':counter,'actual49DecimalChecks':bind(OUT/'actual49-own-Decimal-case-calculations-and-alternative-finite-buffer-proof.json'),'actualExecutedTwoCellTablesFourVariations':bind(OUT/'actual-two-independent-executable-budget-celltables-and-single-input-recalculations.json'),'officialBoundedSourceReview':source,'currentExistingPStatusesUntouched':'needs_human_review; ai_candidate','unmodifiedQualifiedPContentReauthored':False,'oldLegacy591b58cca47REVISEClaimsPreserved':True,'author62ViewReferencesCANCandidateSEMKindsOrRouteNumbersIndependentlyApprovedHere':False,'newImages':0,'activeWrites':0,'nativeBuildRuns':0,'strictGain':0,'newActiveFachClosures':0,'restoredActiveBindings':0,'M4WholeM6M7OrHumanReleaseClaimed':False,'next':'Parent/Main can author exact machine-status release followers and independently qualify current whole source/country/course/mandatory closure/View/Nav/SEM/Book/P bindings. Integrate only three approved objects and qualified field deltas onto actual currentCAN; no old wholeCAN overwrite.'})
end=[]
for b in load('actual-three-whole-science-input-bindings.before-verdict.json')['inputs']:
 a=bind(b['path']);end.append({'before':b,'after':a,'wholeExact':b==a})
can=intake['currentCanonical']['path'];active={g['id']:g for g in json.loads((ROOT/can).read_text())['goals']}
assert all(active[g['id']]==g for g in intake['wholeOriginalAuthorContext']['wholeGoals'])
changed=[r['before']['path'] for r in end if not r['wholeExact']]
assert not [p for p in changed if p not in [can,'curricula/DE/Gymnasium/quality/deep-understanding-rollout/de-gymnasium-math-physics.config.json']]
required=[str(p.relative_to(ROOT)) for p in sorted(OUT.iterdir()) if p.is_file()];ignored=subprocess.run(['git','check-ignore','--',*required],cwd=ROOT,text=True,capture_output=True);assert ignored.returncode==1 and not ignored.stdout
assert not [p for p in OUT.rglob('*') if p.is_symlink()]
guard=save('actual-current-contract-profile-authorfreeze-endguards-and-artifact-availability.json',{'inputEndBindings':end,'actualParentGlobalContextChanges':changed,'allEightActualWholeCurrentContractsStillExact':True,'allSevenPInputsWholeExact':True,'authorFinalWholeBodiesAndManifestExact':True,'requiredIgnoredPaths':[],'symlinkErrors':0,'ignoreCommand':{'argv':['git','check-ignore','--',*required],'exitCode':ignored.returncode,'stdout':ignored.stdout,'stderr':ignored.stderr},'activeWrites':0})
manifest=save('actual-three-coherent-local-materials-whole-science-independent-b.manifest.json',{'reviewer':'/root/economics_m2_views_independent_b','sealedAt':datetime.now(timezone.utc).isoformat(),'artifacts':[bind(p) for p in sorted(OUT.iterdir()) if p.is_file()],'wholeScienceCompleted':True,'status':'KEEP whole three bounded DRAFT science candidates','historyOverwrites':0})
receipt=save('actual-final-three-local-whole-materials-scientific-KEEP.independent-b.handoff.receipt.json',{'reviewer':'/root/economics_m2_views_independent_b','status':'KEEP whole three bounded DRAFT science candidates','science':science,'manifest':manifest,'inputGuards':guard,'authorFinalHandoff':intake['authorHandoff'],'exactWholeBodiesSHA256':'dfb3fe708e8a9f53f0b1c4137240aa99090104a0a4d1571f1e56576da0e87abd','wholeMaterials':3,'wholeAssessedContracts':4,'wholeCurrentContractsWithSupport':8,'wholeCurrentProfiles':7,'currentApplicationCases':16,'ownWholeCounterworks':10,'manualStepDecisions':40,'ownDecimalChecks':49,'ownIndependentExecutableBudgetTables':2,'actualTableFramesExecuted':4,'authorScoringWorksReused':False,'profileStatusesUpdatedOrHumanReviewClaimed':False,'actualSourceCourseViewSEMBookPIntegrationApproved':False,'activeWrites':0,'strictGain':0,'newActiveFachClosures':0,'restoredActiveBindings':0,'M4WholeM6M7Claimed':False})
print(json.dumps({'receipt':receipt,'science':science,'manifest':manifest,'materials':3,'ownWorks':10,'manualMarks':40,'decimalChecks':49,'executedCellFrames':4,'changedGlobalInputs':changed}))
