# Technical review tooling: Apache-2.0. Reviewed own didactic media: CC-BY-4.0.
from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
from PIL import Image
root=Path.cwd();own=root/'curricula/DE/Gymnasium/quality/goal-visualization-review/biologie-q1-carrier-hidden-continuity-independent-a-v3';src=root/'curricula/DE/Gymnasium/quality/goal-visualization-review/biologie-q1-carrier-hidden-continuity-and-length-author-20261006-v3'
assert not (own/'independent-v4-a.final.freeze.json').exists()
stamp=datetime.now(timezone.utc).isoformat();id='ac9e824f-003c-50ac-8751-2b8456004c63'
def read(p):return json.loads(p.read_text())
def bind(p):
 raw=p.read_bytes();return {'path':str(p.relative_to(root)),'sha256':'sha256:'+hashlib.sha256(raw).hexdigest(),'bytes':len(raw)}
def write(name,obj):(own/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
cpath=root/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_BIOLOGIE.de.json';qpath=root/'curricula/DE/Gymnasium/quality/goal-visualization-qa/biologie.qa.json'
goal=next(g for g in read(cpath)['goals'] if g['id']==id);old=next(g for g in read(qpath)['records'] if g['goalId']==id)
asset=bind(src/'carrier-v4.candidate.png');assert asset['sha256']=='sha256:ea766edf279fd977118453494e2f837a3ccef57a6d1ceca448cf98010f49a63a'
inputs=[bind(cpath),bind(qpath),bind(root/'AGENTS.md'),bind(root/'docs/concept/skill-graph/atomic-goal-visualizations.md')]
for name in ['carrier-v4.candidate.png','carrier-v4.actual-360.png','carrier-v4.actual-680.png','v4-actual-image-generation-prompt.en.md','v4-candidate-generation.actual.json','before-v2.png']:inputs.append(bind(src/name))
rasters=[{'input':bind(src/name),'actualSize':list(Image.open(src/name).size),'personallyInspected':True} for name in ['carrier-v4.candidate.png','carrier-v4.actual-360.png','carrier-v4.actual-680.png']]
reviewer='Codex independent actual-image reviewer A /root/biology_q1_v7_sources_independent_a_followup; no author role for this image, no new peer image verdict read'
notes=('KEEP after personally viewing actual1672x941,360x203,680x383 PNGs and lossless native-pixel inspection crops. Both lavender backbones form separate smooth opposing curves; tracking each curve through five visible crossing regions near x490/730/970/1210/1450 finds alternating front/back for that SAME strand, tangent-compatible hidden continuations, and no splice, branch or backbone identity exchange. Foreground diagonals descend right consistently, compatible with a right-handed textbook projection; this is a schematic, not molecular stereochemical validation. Base-pair rods connect the two opposing tubes and remain separate from the gold bracket. The bracket covers about1.2 complete360-degree turns (roughly2.4 projected half-turn fields), not the requested two whole turns; this generator deviation is explicitly accepted only as a long strongly shortened gene-region illustration, never as a measured real gene length. The readable note stark verkürzt makes the symbolic scale limitation explicit. The unplanned X shows a replicated two-sister-chromatid chromosome: a local dashed zoom box makes sampling DNA from one chromatid plausible; no statement asserts the whole replicated X contains only one DNA molecule. The generic information-carrier goal does not require an unreplicated rod or a cell-cycle lesson. All four labels stay readable at360 and680. Human flags remain unchanged/no new human approval. Final active V import and exact D/P image/page binding remain separate.')
planned=dict(old);planned.update({'assetSha256':asset['sha256'],'aiApprovedAssetSha256':asset['sha256'],'aiApproved':'yes','aiReviewedAt':stamp,'aiReviewer':reviewer,'aiNotes':notes})
write('single-native-v-record.v4-candidate.json',planned)
findings=[
 {'id':'V4-A-01','verdict':'KEEP','scope':'Actual opposing backbone curves and occlusions','observation':'A: upper crest~610→lower~850→upper~1090→lower~1330→upper~1570; B opposite. At~730/970/1210/1450, each individual strand alternates front/back. Hidden ends resume along the same smooth rising or falling continuation; no same-curve merge, tangent reversal or foreground/backbone-colour identity change. Both are identically lavender, so geometry rather than colour is tracked. First~490 transition is schematic chromatin opening into two backbones; no extra branch in the genetic segment.'},
 {'id':'V4-A-02','verdict':'KEEP','scope':'Handedness and base-pair rods','observation':'The repeated foreground crossing diagonal descends right. Same crossing orientation throughout is compatible with the standard right-handed projection. Paired rods bridge opposing backbones; small occluded portions terminate behind the foreground tube. No atomistic helix pitch, base-count or bond-angle claim is made.'},
 {'id':'V4-A-03','verdict':'KEEP_WITH_EXPLICIT_PROMPT_DEVIATION','scope':'Gene length and shortened symbolic scale','observation':'Brace~x720–1295 covers~575px; same-strand phase repeat is~480px. About1.2 complete rotations, not2; visible half-turn fields must not be called full turns. Long multi-base section plus clearly readable stark verkürzt makes gene-as-section intelligible; no numerical real gene-length claim. Two complete turns was the author prompt, not a binding owner requirement.'},
 {'id':'V4-A-04','verdict':'KEEP_WITH_EXPLICIT_PROMPT_DEVIATION','scope':'X chromosome and local extraction','observation':'Generator substituted an X for the requested rod. It is a plausible replicated chromosome with two sister chromatids, not two different chromosomes. The square dashed local zoom selects a small region near one side of the constricted chromosome and leads to a representative chromatin/DNA strand, so it can sample one chromatid. The image does not claim the whole replicated structure comprises a single DNA molecule; generic current goal only demands organized carrier/material/section relationships. Phase and replication-state details are outside this goal.'},
 {'id':'V4-A-05','verdict':'KEEP','scope':'Actual360/680 accessibility and style','observation':'Chromosom, Gen, DNA and stark verkürzt remain readable. The gold brace stays outside the material geometry, pale halo behind the helix; same friendly abstract comic visual style, wide PNG, ample contrast, no photographic or sterile technical reconstruction.'}
]
write('independent-v4-a.actual-visual-science-verdict.json',{'schemaVersion':1,'createdAtUTC':stamp,'goalId':id,'reviewer':reviewer,'role':'independent actual image QA only','decision':'KEEP_ONE_EXACT_CANDIDATE_WITH_DOCUMENTED_PROMPT_DEVIATIONS','currentWholeGoal':goal,'reviewedCandidate':asset,'reviewedRasterSizes':rasters,'actualCrossingAndTransitionCropPaths':[str(p.relative_to(root)) for p in sorted(own.glob('*.inspection.png'))],'cropMethod':'Lossless rectangular native-pixel excerpts for inspection only; candidate bytes never changed; no drawing or synthetic replacement.','individualFindings':findings,'freshScientificIssues':[],'reviewedPrimarySources':[{'url':'https://medlineplus.gov/genetics/understanding/basics/gene/','reviewedAtUTC':stamp,'supports':'Genes are DNA sections; typical human gene length spans hundreds to millions of base pairs. Thus visible model bars and turns cannot be real-scale gene length.'},{'url':'https://medlineplus.gov/genetics/understanding/basics/chromosome/','reviewedAtUTC':stamp,'supports':'Chromosomes package DNA with proteins; condensation is a division-related representation.'},{'url':'https://www.genome.gov/genetics-glossary/Chromatid','reviewedAtUTC':stamp,'supports':'Replicated chromosomes have two sister chromatids connected at the centromere; local sampling one is compatible with a representative DNA zoom.'}],'historicalV2ReviewUnchangedAndNoCurrentCompletionAuthority':True,'unimportedV3NotReviewedOrApprovedByThisNewRecord':True,'noPeerNewVerdictsRead':True,'nativeDPRevalidation':'HOLD final actual imported image/page/native inputs; no D/P candidate generated in this V-only stage','otherSixGoalsNotReopened':True,'activeWrites':False,'strictNetGain':0,'restoredActiveBindings':0,'humanApproval':False,'humanTrial':False})
write('actual-v4-bound-inputs.for-freeze.json',{'schemaVersion':1,'createdAtUTC':stamp,'inputs':inputs,'currentActivePublicPNG':bind(root/old['publicAssetPath']),'currentActiveCanonicalPNG':bind(root/old['canonicalAssetPath']),'candidateImportedAtReview':bind(root/old['publicAssetPath'])['sha256']==asset['sha256'],'globalNineteenInputEqualityNotClaimed':True,'authorRoleForThisPNG':False})
print(json.dumps({'decision':'KEEP_V4_ONLY','assetSha256':asset['sha256'],'newDOrP':False,'activeWrites':False}))
