# SPDX-License-Identifier: Apache-2.0
"""New author remedy; original Science60 and current active files remain unchanged."""
import copy,hashlib,json,re,runpy
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path.cwd();OWN=Path(__file__).resolve().parent;OLD=OWN.parent
REL=OWN.relative_to(ROOT).as_posix();STAMP=datetime.now(timezone.utc).isoformat()
def load(p):return json.loads(p.read_text())
def write(n,x):
 p=OWN/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def bind(p):
 b=p.read_bytes();return dict(path=p.relative_to(ROOT).as_posix(),sha256='sha256:'+hashlib.sha256(b).hexdigest(),bytes=len(b))
assert not (OWN/'targeted-whole-remediation.first.freeze.json').exists()
ns=runpy.run_path(OLD/'author-cases-01-to-05.py')
for n in ['author-cases-06-to-10.py','author-cases-11-to-14.py']:exec(compile((OLD/n).read_text(),str(OLD/n),'exec'),ns)
specs=ns['SPECS'];case=ns['case'];pair=ns['pair']
def readable(x):
 if isinstance(x,dict):return {k:readable(v) for k,v in x.items()}
 if isinstance(x,list):return [readable(v) for v in x]
 if isinstance(x,tuple):return tuple(readable(v) for v in x)
 if not isinstance(x,str):return x
 x=re.sub(r'(?<=[A-Za-zÄÖÜäöüß])(?=\d)',' ',x)
 x=re.sub(r'(?<=\d)(?=[A-Za-zÄÖÜäöüß])',' ',x)
 return re.sub(r'(?<=[,:;])(?=[A-Za-zÄÖÜäöüß])',' ',x)
specs=readable(specs)
germ=specs[6]['cases'][0]
germ['material']=pair(
 'Das neue eigene Aufgabenmedium media/finite-inquiry-and-preparation.html erlaubt wirklich die Auswahl Wasserzustand trocken/mäßig feucht/bedeckt und Temperatur 22/28 °C. Erst nach Bestätigung gleicher Charge, Licht, Schalenfläche und Zeit kann ein Ansatz gestartet werden. Bei 22 °C zeigt jeder Wasserzustand zwei getrennte Modellschalen à 20 Samen, zunächst Tag 0 mit 0/0; die tatsächlichen Schaltflächen legen Tag 2 und Tag 4 offen: trocken 0/1 und 1/1, mäßig feucht 8/9 und 16/15, bedeckt 2/3 und 5/6. Keimung ist eine sichtbare Wurzel von mindestens 2 mm. Nach Zurücksetzen lässt sich ein neuer unabhängiger Wasserzustand bei gleicher Temperatur starten. Alle Rohwerte und Modellaktionen sind konstruiert; keine echten Samen oder Lernenden wurden untersucht.',
 'The new own medium media/finite-inquiry-and-preparation.html actually permits selecting dry/moderately moist/submerged water conditions and 22/28 °C. A trial starts only after confirmation of matching batch, light, dish area and duration. At 22 °C, each water condition provides two distinct modeled dishes of 20 seeds, initially day 0 with 0/0; actual buttons reveal day 2 and day 4: dry 0/1 then 1/1, moderately moist 8/9 then 16/15, submerged 2/3 then 5/6. Germination is a visible root at least 2 mm long. Resetting permits a new independent water condition at the same temperature. All raw values and model actions are constructed; no real seeds or learners were investigated.')
germ['task']=pair(
 'Plane einen kontrollierten Vergleich, wähle Wasserzustände und konstante Temperatur tatsächlich im Medium, bestätige die Kontrollen, starte und protokolliere je Ansatz Ausgangswert, Tag 2 und Tag 4. Vergleiche alle sechs Modellschalen mit Hypothese und Theorie; trenne Rohdaten, Berechnung und Schluss. Nenne anschließend das erforderliche sichere praktische Vorgehen an echten Schalen und die Grenzen des Mediums.',
 'Plan a controlled comparison, actually select water conditions and matching temperature in the medium, confirm controls, start and record the initial state, day 2 and day 4 for each treatment. Compare all six modeled dishes against hypothesis and theory, separating raw data, calculation and conclusion. Then identify the required safe practical procedure with real dishes and the limits of this medium.')
germ['workedResponse']=pair(
 'Hypothese: Unter gleichen Bedingungen fördert mäßige Feuchtigkeit Keimung gegenüber Trockenheit; vollständige Bedeckung kann Gastransport und damit Stoffwechsel begrenzen. Ich wähle zuerst trocken/22 °C, bestätige Charge, Licht, Schalenfläche und Zeit, starte, notiere Tag 0: 0/0, betätige die zwei Schritte und notiere Tag 2: 0/1, Tag 4: 1/1. Nach Zurücksetzen wiederhole ich die Handlungen für mäßig feucht/22 °C mit 0/0→8/9→16/15 und bedeckt/22 °C mit 0/0→2/3→5/6. Wasserzustand ist die unabhängige Variable; gekeimte Samen je 20 die abhängige. Die zwei Schalen sind getrennte Wiederholungen, nicht zwei Messungen derselben Schale. Tag-4-Anteile über je 40 Samen sind 2/40=5 %, 31/40=77,5 % und 11/40=27,5 %. Die Modellbefunde stützen den begrenzten Vergleich, messen Sauerstoff jedoch nicht und beweisen den vorgeschlagenen Mechanismus nicht. Eine wirkliche Durchführung verlangt geeignete nicht behandelte Samen, beaufsichtigte saubere Schalen, reale gleich gehaltene Bedingungen, gekennzeichnete Ansätze, sichere Beobachtung und dokumentierte tatsächliche Rohwerte; unbekannte oder schimmelige Proben werden nicht geöffnet, Hygiene und Entsorgung folgen der Anleitung. Die Bedienung hier ist nur eine vorbereitende Modellhandlung und ersetzt weder diese praktische Quellenpflicht noch Gerätefertigkeit oder echte Versuchsevidenz.',
 'Hypothesis: under matching conditions, moderate moisture promotes germination compared with dryness; full submersion may limit gas transport and metabolism. I first select dry/22 °C, confirm batch, light, area and duration, start and record day 0: 0/0, then use both step buttons and record day 2: 0/1 and day 4: 1/1. After reset I repeat for moderately moist/22 °C with 0/0→8/9→16/15 and submerged/22 °C with 0/0→2/3→5/6. Water state is the independent variable and germinated count per 20 the dependent variable. The two dishes are independent repeats, not two measurements of one dish. Day-4 fractions across 40 seeds are 2/40=5 %, 31/40=77.5 % and 11/40=27.5 %. The modeled findings support the bounded comparison without measuring oxygen or proving the proposed mechanism. Real performance requires suitable untreated seeds, supervised clean dishes, genuinely matched conditions, labeled treatments, safe observation and recorded actual raw values; unknown or moldy samples are not opened, and hygiene and disposal follow instructions. Operating this medium is preparatory model action and replaces neither the practical source duty nor instrument skill or genuine experimental evidence.')
germ['freshTransfer']=pair(
 'Wähle nach einem neuen Start bedeckt/28 °C. Das Medium zeigt Tag 2: 3/4 und Tag 4: 9/10. Darf der höhere Tag-4-Anteil gegenüber bedeckt/22 °C einen isolierten Wassereffekt belegen? Begründe ein kontrolliertes weiteres Vorgehen.',
 'In a new trial select submerged/28 °C. The medium shows day 2: 3/4 and day 4: 9/10. Can its higher day-4 fraction than submerged/22 °C demonstrate an isolated water effect? Justify a controlled follow-up.')
germ['freshTransferWorkedResponse']=pair(
 'Nein: 19/40=47,5 % gegenüber 11/40=27,5 % stammt aus einer zusätzlich geänderten Temperatur. Für den ursprünglichen Vergleich aller Wasserzustände bei 22 °C gehört dieser neue Ansatz getrennt ins Störungsprotokoll. Ein Temperaturvergleich verlangt dieselbe Wasserbedingung mit kontrolliert gleicher Charge, Zeit und anderen Faktoren, und für Aussagen über Wasser jeweils gleiche Temperaturen. Die konstruierten Modellwerte zeigen die Kontrolle, keine wirklichen Temperatureffekte an Samen.',
 'No: 19/40=47.5 % versus 11/40=27.5 % comes with a changed temperature. For the original comparison of water states at 22 °C this new treatment belongs separately in the disturbance record. A temperature comparison requires the same water condition and matched batch, duration and other factors; claims about water require matching temperatures. Constructed values illustrate control and do not establish real temperature effects on seeds.')
aquatic=specs[6]['cases'][1]
aquatic['material']=pair(
 'Das neue Medium hat wirkliche Auswahl für geringe/mittlere/hohe Beleuchtung, Temperatur 20/28 °C und Anfangssauerstoff 6/7 mg/L. Je Beleuchtung werden drei unabhängige Modellansätze derselben Pflanzenmasse und desselben Wasservolumens gestartet. Bei 20 °C und 6 mg/L zeigen sie vor Beleuchtung die Rohwerte 6/6/6 mg/L; nach 10 min: gering 6,2/6,3/6,1, mittel 6,7/6,8/6,6, hoch 6,8/6,9/6,7 mg/L. Das Medium zeigt getrennt die jeweils berechneten Differenzen; bei hoch/28 °C lautet die separate Reihe 6,4/6,5/6,3 mg/L. Alle Daten sind ausdrücklich konstruierte Aufgabenwerte.',
 'The new medium has real controls for low/medium/high illumination, 20/28 °C and starting oxygen 6/7 mg/L. Each illumination starts three independent modeled setups with matching plant mass and water volume. At 20 °C and 6 mg/L the pre-exposure readings are 6/6/6 mg/L; after 10 min: low 6.2/6.3/6.1, medium 6.7/6.8/6.6, high 6.8/6.9/6.7 mg/L. The medium separately shows calculated differences; high/28 °C supplies a separate 6.4/6.5/6.3 mg/L series. These are explicitly constructed task values.')
aquatic['task']=pair(
 'Plane und bediene einen kontrollierten Vergleich: Wähle drei Lichtstufen nacheinander mit 20 °C und 6 mg/L, bestätige die Konstanten, starte, notiere jeden Anfangswert und rufe nach 10 min alle Endwerte ab. Berechne End-minus-Anfang je Replikat und den mittleren Nettozuwachs. Deute theoriebezogen; dokumentiere hoch/28 °C getrennt. Erkläre, welche Gerätehandlungen und Sicherheitsregeln eine reale Durchführung zusätzlich verlangt.',
 'Plan and operate a controlled comparison: select each of the three illumination levels at 20 °C and 6 mg/L, confirm constants, start, record each initial value and reveal all endpoints after 10 min. Calculate endpoint-minus-start per replicate and the mean net increase. Interpret against theory and record high/28 °C separately. Explain the instrument actions and safety rules additionally required for actual performance.')
aquatic['workedResponse']=pair(
 'Hypothese: Mehr Licht erhöht zunächst den Netto-Sauerstoffzuwachs durch Fotosynthese, bis andere Bedingungen begrenzen. Ich stelle gering/20 °C/6 mg/L ein, bestätige Pflanzenmasse, Volumen, Anfangswert und 10 min, starte und protokolliere für drei unabhängige Ansätze 6/6/6 und dann 6,2/6,3/6,1 mg/L. Nach Zurücksetzen bediene ich mittel und hoch bei identischen Konstanten: 6→6,7/6,8/6,6 und 6→6,8/6,9/6,7 mg/L. Jeweilige End-minus-Anfang-Reihen sind 0,2/0,3/0,1; 0,7/0,8/0,6; 0,8/0,9/0,7 mg/L. Die Mittel betragen 0,2, 0,7 und 0,8 mg/L je 10 min. Licht ist die unabhängige Variable, Netto-Konzentrationsänderung die abhängige; drei eigenständige Ansätze liefern Wiederholungen. Der kleinere zweite Anstieg passt zu Begrenzung, bestimmt den Faktor aber nicht; gelöster Sauerstoff hängt auch von Atmung und Austausch ab. Separat bediene ich hoch/28 °C: 6/6/6→6,4/6,5/6,3, also 0,4/0,5/0,3 und im Mittel 0,4 mg/L. Dieser Temperaturwechsel gehört nicht in den isolierten Lichtvergleich. Echte Geräteanwendung verlangt beaufsichtigte standsichere Gefäße, geprüfte geeignete Sauerstoffsensoren und Kalibrierung, tatsächliche Messzeit und Temperaturen, sichere Trennung von Wasser und Elektrik sowie Schutz der Organismen. Das Medium trainiert Auswahl, Kontrolle und Protokoll mit festen Werten; es ersetzt weder diese physische Durchführung noch deren Quellenpflicht.',
 'Hypothesis: increasing illumination initially raises net oxygen gain through photosynthesis until other conditions limit it. I select low/20 °C/6 mg/L, confirm plant mass, volume, initial value and 10 min, start and record 6/6/6 followed by 6.2/6.3/6.1 mg/L for three independent setups. After reset I operate medium and high with identical constants: 6→6.7/6.8/6.6 and 6→6.8/6.9/6.7 mg/L. Endpoint-minus-start series are 0.2/0.3/0.1; 0.7/0.8/0.6; 0.8/0.9/0.7 mg/L. Means are 0.2, 0.7 and 0.8 mg/L per 10 min. Light is the independent variable and net concentration change the dependent variable; three distinct setups provide repeats. The smaller later rise fits limitation without identifying the factor; dissolved oxygen also depends on respiration and exchange. Separately I operate high/28 °C: 6/6/6→6.4/6.5/6.3, giving 0.4/0.5/0.3 and a 0.4 mg/L mean. This temperature change cannot enter the isolated light comparison. Real instrument use requires supervised stable vessels, suitable checked oxygen sensors and calibration, actual times and temperatures, safe separation of water and electricity and organism protection. The medium trains selection, control and recording with fixed values; it replaces neither physical performance nor its source duty.')
specs[6]['limits'].append('Tatsächlich bedienbare Auswahl und vollständige konstruierte Replikatrohwerte; Modellaktionen sind vorbereitend und ersetzen keine praktische originale Quellenpflicht.')
organ=case('technique-own-organ-preparation','Eigenes Pflanzenorgan sicher präparieren',
 ('Aufgabenmaterial für eine beaufsichtigte praktische Demonstration: eine von der Lehrkraft freigegebene ungiftige, nicht allergieauslösende Blüte aus legalem Lehrmaterial, Schale, stumpfe Pinzette, Lupe, Schutz der Arbeitsfläche und Protokollbogen. Zielorgan ist ein Staubblatt mit Staubfaden und Staubbeutel; die Blüte umfasst mehrere Organe. Es gibt keine unbekannten Pflanzen, Messer, Chemikalien oder zu entnehmenden geschützten Organismen. Im endlichen eigenen Medium bietet Organpräparation vier auswählbar abrufbare Planungsschritte, aber keine wirkliche Probe. Die amtliche NI-Zeile lautet genau präparieren ein Organ; sie verlangt keine zusätzliche verpflichtende Sektion.',
  'Material for a supervised practical demonstration: a teacher-approved non-toxic, non-allergenic flower from legal teaching material, dish, blunt forceps, magnifier, protected work surface and record sheet. The target organ is a stamen with filament and anther; the flower comprises several organs. No unknown plants, knives, chemicals or protected organisms are used. The finite own medium supplies four retrievable organ-preparation planning steps but no actual specimen. The official NI clause says prepare an organ; it does not add compulsory dissection.'),
 ('Plane und erläutere die eigene sichere Präparation eines Staubblatts, bediene die vier vorbereitenden Modellschritte und schreibe die erwartete Schrittfolge, Beobachtung und Sicherheitsentscheidung getrennt auf. Welche tatsächliche Demonstration würde Geräte-/Präparationsfertigkeit belegen? Erkläre den Unterschied zu einem schon fertigen Objektträger und zu einem Säugetierorgan-Zuordnungsziel.',
  'Plan and explain safe preparation of a stamen, operate the four preparatory model steps and separately record expected actions, observations and safety decisions. What actual demonstration would evidence instrument/preparation skill? Distinguish this from a ready-made microscope slide and a mammalian-organ assignment goal.'),
 ('Ich prüfe zuerst Freigabe, Allergiehinweise, stabile Schale und passende stumpfe Pinzette; bei unbekannter oder problematischer Probe beginne ich nicht. Nach Anleitung löse ich äußere Blütenteile vorsichtig, um die Staubblätter zugänglich zu machen, ohne sie blind zu zerquetschen. Unter der Lupe identifiziere ich Staubfaden und Staubbeutel, löse ein ganzes Staubblatt behutsam mit der Pinzette am Ansatz und lege das präparierte Organ geordnet in die Schale. Ich dokumentiere Herkunft/Freigabe, Gerät, Reihenfolge, eine beschriftete Beobachtungsskizze und eventuelle Beschädigung; anschließend reinige ich Geräte und Arbeitsplatz und entsorge nach Anleitung, ohne Pollen zu berühren oder Material zu probieren. Im Medium starte ich das Präparationsszenario und rufe Freigabeprüfung, vorsichtiges Freilegen, Beobachtung der Teile sowie Dokumentation/Reinigung ab; dieses Modellprotokoll ist keine ausgeführte echte Präparation. Prüfbarkeit verlangt eine tatsächlich beobachtete eigene sachgerechte Handhabung an der freigegebenen Probe sowie ein eigenes korrektes Protokoll. Ein fertig präparierter Objektträger zeigt gerade nicht das eigene Präparieren. Staubblattpräparation operationalisiert die generische Organpräparationspflicht; sie behauptet weder Präparation eines Säugetierorgans noch vollständige Abdeckung des unverändert erhaltenen separaten Säugetier-Struktur/Funktionspartners. Das originale partial-Mapping bleibt partial.',
  'I first check approval, allergy information, a stable dish and suitable blunt forceps; I do not start with an unknown or unsuitable sample. Following instructions, I gently loosen outer flower parts to make stamens accessible without blindly crushing them. Under the magnifier I identify filament and anther, gently release one complete stamen at its base with the forceps and place the prepared organ in order in the dish. I record origin/approval, instrument, sequence, a labeled observational sketch and any damage, then clean equipment and surface and dispose as instructed without touching pollen or tasting material. In the medium I start preparation and reveal approval checks, gentle exposure, observation of parts and recording/cleanup; this model record is no actual preparation. Evidence requires genuinely observed competent own handling of the approved specimen and an accurate own record. A ready-made slide does not demonstrate own preparation. Stamen preparation operationalizes the generic organ-preparation duty; it claims neither preparation of a mammalian organ nor complete coverage of the separately retained mammalian structure/function partner. The original partial mapping remains partial.'),
 ('Die Pinzette zerreißt beim ersten Versuch den Staubfaden; eine unbekannte Pflanze wird als Ersatz angeboten. Was dokumentierst du, und wie setzt du sicher und überprüfbar fort?',
  'The forceps tear the filament on the first attempt, and an unknown plant is offered as a replacement. What do you record, and how do you proceed safely and assessably?'),
 ('Ich notiere die Beschädigung als wirklichen Handlungsbefund, zeichne sie nicht als unversehrtes Organ und behaupte keine gelungene Fertigkeit. Die unbekannte Ersatzpflanze verwende ich nicht. Nach Rücksprache nehme ich nur eine erneut freigegebene Probe, korrigiere Griffpunkt und Kraft nach Anleitung und lasse den neuen Versuch beobachtbar ausführen; bis dahin bleibt die praktische Demonstration offen. Die Modellantwort kann die Sicherheitsentscheidung erklären, aber das tatsächliche Gelingen nicht bestätigen.',
  'I record damage as an actual procedural finding rather than drawing an intact organ or claiming competent success. I do not use the unknown replacement. After consultation I use only a newly approved specimen, adjust grip and force as instructed and make the new attempt observable; practical demonstration remains open until then. A model response explains the safety decision without confirming actual success.'),
 [('Eigene konkrete Organpräparation mit passenden Geräten und differenzierter Anatomie.','Concrete own organ preparation with suitable equipment and distinguished anatomy.'),('Freigabe, Hygiene, geordnete Handhabung und ehrliche Beschädigungs-/Schrittdokumentation.','Approval, hygiene, organized handling and honest damage/action recording.'),('Modell-/Praxisgrenze und ursprüngliche partial-Partnerrolle ausdrücklich erhalten.','Explicitly retains the model/practice boundary and original partial partner role.')])
specs[8]['cases'].append(organ)
specs[8]['limits'].append('NI verlangt eigene Organpräparation, keine zwingende Sektion. Das praktische Prüfdesign bleibt wirklich praktisch; die Modellsteuerung und geschriebene Antwort beweisen keine tatsächliche Handhabung.')

# Exact one-field current EN fidelity patch, with unchanged whole source/graph semantics.
canon=load(OLD/'input/current-canonical479.original.snapshot.json');cg={g['id']:g for g in canon['goals']}
ENID='8375310d-1f7e-542d-9969-55ad4bd37f7c';before=copy.deepcopy(cg[ENID])
expected='The learner can reflect on results and inquiry processes by judging data validity, identifying error sources, and discussing possibilities and limits of models.'
assert before['descriptionEn']==expected
cg[ENID]['descriptionEn']='The learner can reflect on their own results and their own inquiry process by judging data validity, identifying error sources, and discussing possibilities and limits of models.'
write('input/canonical479-one-en-fidelity.candidate.json',canon)
write('goal-one-en-fidelity.exact-before-after.candidate.json',dict(schemaVersion=1,goalId=ENID,beforeWholeGoal=before,afterWholeGoal=cg[ENID],changedPointers=['/descriptionEn'],reason='Restores own results/own inquiry already present in unchanged DE and official competence clause; no new competence or narrowing.',newScientificApproval=False,requiredTargetedReviews=['two independent EN fidelity/whole-description checks','semantic-kind decision confirmation','A atomicity current decision confirmation','M memory current decision confirmation'],activeWrites=[]))

# Exactly one operative extraction row; neither historical source nor its partial mapping is rewritten.
frame=load(OLD/'fourteen-current-ordinary-source-partner-frame.neutral-input.json')
SID='ni-biology-seki-kc2015-eg2-9-10-001-aaf1299b'
match=[(m,d) for m in frame['wholeAffectedMappingDecisions'] for d in m['wholeSelectedDecisions'] if d['wholeCurrentDecision']['sourceGoalId']==SID]
assert len(match)==1
m,d=match[0];source=load(ROOT/m['sourceExtractionBinding']['path']);rows=source.get('sourceGoals',source.get('goals'));sg=next(g for g in rows if g['id']==SID);oldsg=copy.deepcopy(sg)
assert sg['sourceText']=='präparieren und sezieren ein Organ.' and sg['metadata']['sourcePage']==77
sg['title']='präparieren ein Organ.';sg['description']='Die lernende Person kann präparieren ein Organ.';sg['sourceText']='präparieren ein Organ.'
sg['sourceRef']=sg['sourceRef'].replace('S. 77.','S. 76.');sg['sourceSpan']['label']='Planen, untersuchen, auswerten: präparieren ein Organ.';sg['metadata']['sourcePage']=76
sourceName='source/NI.one-primary-clause-correction.candidate.source-extraction.json';write(sourceName,source)
mapping=load(ROOT/m['mappingBinding']['path']);oldmapping=copy.deepcopy(mapping);mapping['sourceExtractionPath']=REL+'/'+sourceName
mapName='source/NI.same-partial-partners.candidate.mapping.json';write(mapName,mapping)
primary=ROOT/'curricula/DE/Gymnasium/input/NI/lower-secondary/kc_naturwissenschaften_gymnasium_sek_i_2015.pdf';actualText=OWN/'primary/NI-physical-page-076.actual-original-layout.txt'
assert 'präparieren ein Organ.' in actualText.read_text() and 'präparieren und sezieren ein Organ.' not in actualText.read_text()
write('source/NI.one-source-row.exact-before-after.candidate.json',dict(schemaVersion=1,sourceGoalId=SID,originalSourceBinding=m['sourceExtractionBinding'],candidateSourceBinding=bind(OWN/sourceName),originalMappingBinding=m['mappingBinding'],candidateMappingBinding=bind(OWN/mapName),beforeWholeSourceGoal=oldsg,afterWholeSourceGoal=sg,exactChangedPointers=['/title','/description','/sourceRef','/sourceText','/sourceSpan/label','/metadata/sourcePage'],originalPrimary=bind(primary),actualPageExtraction=bind(actualText),physicalPage=76,printedPage=76,exactOriginalClause='präparieren ein Organ.',wholeOriginalPartialDecision=d['wholeCurrentDecision'],bothWholePartnerGoals=d['wholeCanonicalPartnerGoals'],partialDecisionUnchanged=True,parentPassageHistoricalPage77Unchanged=True,allOtherSourceRowsAndMetadataUnchanged=True,mandatoryDissection=False,additionalOwnOrganPreparationCaseId=organ['caseId'],practicalDutyNotReplacedBySimulation=True,scientificSourceApproval=False,activeWrites=[]))
d['wholeCurrentSourceGoal']=copy.deepcopy(sg);m['mappingBinding']=bind(OWN/mapName);m['sourceExtractionBinding']=bind(OWN/sourceName);m['authorSourceMappingChanges']=['sourceExtractionPath only: same actual partial decision and same two partners, corrected original clause/page']
for m2 in frame['wholeAffectedMappingDecisions']:
 for row in m2['wholeSelectedDecisions']:
  row['wholeCanonicalPartnerGoals']=[copy.deepcopy(cg[g['id']]) for g in row['wholeCanonicalPartnerGoals']]
frame['wholeCurrentPartnerBodies']=[copy.deepcopy(cg[g['id']]) for g in frame['wholeCurrentPartnerBodies']]
frame['artifactRole']='inactive exact69 whole source duties/68 partners with one primary-bound NI extraction correction and one exact EN fidelity candidate; independent source/context approval pending'
frame['activeSourceMappingChanges']=[]
# A concise unambiguous patch pointer; do not imply an old author verdict is independent approval.
frame['candidateSourceMappingChanges']=[dict(originalMappingPath=load(OWN/'source/NI.one-source-row.exact-before-after.candidate.json')['originalMappingBinding']['path'],candidateMappingPath=REL+'/'+mapName,sourceRowId=SID,wholeDecisionAndPartnersRetained=True)]
write('fourteen-whole69-source-duties-68-partners.remediated.neutral-input.json',frame)

whole=load(OLD/'whole-fourteen-current-goals-source-and-context.input.snapshot.json');selected=[copy.deepcopy(cg[e['goalId']]) for e in whole['entries']];ids=[g['id'] for g in selected]
for e in whole['entries']:e['wholeCurrentGoal']=copy.deepcopy(cg[e['goalId']])
whole['role']='Inactive whole14 current source and graph input plus exact EN1 fidelity candidate; A/M/Kind1 current confirmation pending'
whole['candidateCanonicalPath']=REL+'/input/canonical479-one-en-fidelity.candidate.json';whole['intentionalGoalFieldDeltas']=[dict(goalId=ENID,pointer='/descriptionEn')]
write('whole-fourteen-remediated-source-and-context.neutral-input.json',whole)
materials=[];profiles=[];coverage=[]
for ordinal,(g,spec) in enumerate(zip(selected,specs),1):
 assert len(spec['cases'])==(3 if ordinal==9 else 2) and len(spec['expectations'])==3
 exps=[dict(id=f'essential-{i}',essentialUnderstandingDe=e[0]['de'],essentialUnderstandingEn=e[0]['en'],observablePerformanceDe=e[1]['de'],observablePerformanceEn=e[1]['en']) for i,e in enumerate(spec['expectations'],1)]
 briefs=[]
 for c in spec['cases']:
  briefs.append(dict(id=c['caseId'],taskDemandDe=c['material']['de']+'\n\nAuftrag: '+c['task']['de']+'\n\nFrische Variation: '+c['freshTransfer']['de'],taskDemandEn=c['material']['en']+'\n\nTask: '+c['task']['en']+'\n\nFresh variation: '+c['freshTransfer']['en'],expectedPerformanceDe=c['workedResponse']['de']+'\n\nTransferantwort: '+c['freshTransferWorkedResponse']['de'],expectedPerformanceEn=c['workedResponse']['en']+'\n\nTransfer response: '+c['freshTransferWorkedResponse']['en'],understandingFocusDe=' '.join(e['essentialUnderstandingDe'] for e in exps)+' Rubrik: '+'; '.join(r['de'] for r in c['rubric']),understandingFocusEn=' '.join(e['essentialUnderstandingEn'] for e in exps)+' Rubric: '+'; '.join(r['en'] for r in c['rubric'])))
 profile=dict(archetype=spec['archetype'],expectations=exps,coverageExpectations=dict(requiredExpectationIds=[e['id'] for e in exps],alternativeExpectationGroups=[],minimumIndependentDemonstrations=2,freshVariationRequired=True,independentTransferRequired=True),variationAxes=[dict(id='biological-context',textDe='Verschiedene biologische Sachkontexte: '+' / '.join(c['title'] for c in spec['cases'])+'.',textEn='Distinct biological contexts: '+' / '.join(c['title'] for c in spec['cases'])+'.'),dict(id='fresh-counterfinding-or-condition',textDe='Jeder Fall enthält eine konkret beantwortete frische Variation; ihre Bedingungen und Grenzen bleiben erhalten.',textEn='Every case has a worked fresh variation with retained conditions and limits.')],applicationCaseBriefs=briefs)
 profiles.append(dict(goalId=g['id'],reason='Targeted author remedy: actual model controls and replicated start/end data, additional practical own-organ preparation case, faithful EN1 and exact original NI1 correction. Whole cases remain candidate only; physical source duties are not replaced by simulations.',evidenceLevel='E1',maximumClaimScope='G1',dissent=[],profile=profile))
 materials.append(dict(ordinal=ordinal,goalId=g['id'],wholeCurrentGoal=g,expectations=exps,authoredCases=spec['cases'],modelLimits=spec['limits'],reviewStatus='needs_human_review',reviewAuthority='ai_candidate',evidenceLevel='E1',maximumClaimScope='G1',actualLearnerResults=False,actualRealInvestigation=False,independentReviews=[],humanApproval=False))
 coverage.append(dict(goalId=g['id'],wholeGoalDescriptionDe=g['description'],wholeGoalDescriptionEn=g['descriptionEn'],requiredExpectationIds=[e['id'] for e in exps],caseCoverage=[dict(caseId=c['caseId'],expectationIds=[e['id'] for e in exps],evidenceLocations=['workedResponse','freshTransferWorkedResponse','rubric'],role='author-proposed coverage, independently unchecked') for c in spec['cases']],wholeDescriptionUnchanged=ordinal!=11,EN1FidelityCandidate=ordinal==11))
write('fourteen-whole-twenty-nine-bilingual-cases.author-candidate.json',dict(schemaVersion=1,reviewId='biologie-upper-science-fourteen-targeted-remediation-v2',authoredAt=STAMP,license='CC-BY-4.0',entries=materials,scopeGoalIds=ids,actualLearnerResults=False,independentApproval=False,humanApproval=False))
write('fourteen-whole-expectation-coverage.author-matrix.json',dict(schemaVersion=1,role='author proposed whole14/29 coverage only; original physical duties retained',entries=coverage))
write('fourteen-whole-profile-candidates.author-candidates.json',dict(schemaVersion=1,authoringContract='positive-understanding-evidence-candidates-v1',reviewId='biologie-upper-science-fourteen-targeted-remediation-v2',reviewedAt=STAMP,reviewer='Codex actual author; independent targeted science/source/EN and A/M/Kind confirmation pending',goals=profiles))
config=load(OLD/'fourteen-whole-positive-understanding.author-candidate.config.json')
config.update(reviewId='biologie-upper-science-fourteen-targeted-remediation-v2',landscapePath=REL+'/input/canonical479-one-en-fidelity.candidate.json',semanticKindLedgerPath=REL+'/input/kinds394-one-en-fingerprint.technical-candidate.json',reviewPath=REL+'/fourteen-whole-positive-understanding.author-candidate.review.jsonl')
write('fourteen-whole-positive-understanding.author-candidate.config.json',config)
media=[]
for p in sorted((OWN/'media').iterdir()):media.append(dict(**bind(p),license='CC-BY-4.0',mediaRole='actual bounded own task-control model, or preserved raw cards/record template; no actual physical experiment'))
write('procedural-digital-task-media.neutral-manifest.json',dict(schemaVersion=1,entries=media,goalCaseBindings=[dict(goalId=ids[6],caseIds=[c['caseId'] for c in specs[6]['cases']],paths=[REL+'/media/finite-inquiry-and-preparation.html',REL+'/media/finite-inquiry-and-preparation.inputs.json']),dict(goalId=ids[7],caseIds=[c['caseId'] for c in specs[7]['cases']],paths=[REL+'/media/'+p.name for p in (OWN/'media').glob('*.csv')]),dict(goalId=ids[8],caseIds=[organ['caseId']],paths=[REL+'/media/finite-inquiry-and-preparation.html'],role='preparatory plan only; actual competent own physical organ preparation remains required')],actualLearnerPerformance=False,actualExperimentPerformed=False,practicalOriginalDutiesRetained=True,noNetworkOrPersistentDataStorage=True))
md=['# Ganze 14 Wissenschaftsziele: gezielte Kandidatenkorrektur mit 29 bilingualen Fällen','','AI-Kandidaten E1/G1, needs_human_review. Keine unabhängige oder menschliche Freigabe. Alle Daten konstruiert; praktische Quellenpflichten bleiben real praktisch.','']
for m in materials:
 md += [f"## {m['ordinal']}. {m['wholeCurrentGoal']['title']}",'',m['goalId'],'',m['wholeCurrentGoal']['description'],'',m['wholeCurrentGoal']['descriptionEn'],'']
 for c in m['authoredCases']:
  md += ['### '+c['caseId']+': '+c['title'],'']
  for lang in ['de','en']:
   md+=['#### '+lang.upper(),'']
   for fld in ['material','task','workedResponse','freshTransfer','freshTransferWorkedResponse']:md+=['**'+fld+'**: '+c[fld][lang],'']
   md+=['**Rubrik**: '+'; '.join(r[lang] for r in c['rubric']),'']
 md+=['**Modellgrenzen**: '+' '.join(m['modelLimits']),'']
(OWN/'whole-fourteen-twenty-nine-cases.author-review.md').write_text('\n'.join(md)+'\n')
write('remediation-exact-author-change-scope.actual.json',dict(schemaVersion=1,originalScienceEntry=bind(OLD/'neutral-whole-fourteen-science-twenty-eight-cases.author.entry.json'),originalScienceFirstSeal=bind(OLD/'whole-fourteen-science-author.first.freeze.json'),wholeGoals=14,bilingualCases=29,originalCasesRetained=28,addedCaseId=organ['caseId'],meaningfulCaseCorrections=['procedure-germination','procedure-aquatic-light'],ownTextTypographyCorrection='Rebuilt from original raw authored strings; preserved decimal commas without inserting spaces inside decimal values.',intentionalCanonicalChanges=[dict(goalId=ENID,field='descriptionEn')],intentionalSourceRows=[SID],sourceDecisionCount=69,wholeSourcePartnerCount=68,originalMappingDecisionsChanged=0,originalPhysicalDutiesRetained=True,targetedAMKindConfirmationRequired=[ENID],independentScientificApprovals=0,humanApprovals=0,activeWrites=[],newScientificClosures=0,restoredBindings=0,netStrictGain=0))
print(json.dumps({'wholeGoals':14,'bilingualCases':29,'sourceRowsCorrected':1,'sourceDecisionsPreserved':69,'wholePartners':68,'ENfieldsCorrected':1,'AMKindTargetedConfirmation':'PENDING','activeWrites':0}))
