import hashlib
import json
import uuid
from pathlib import Path

BASE = Path(__file__).resolve().parent
OUT = BASE / 'four-new-Generic-global-terminal-author-v5'
OUT.mkdir(exist_ok=True)

def terminal(key, title, en, desc, den, phase, required, task, solution, steps):
    return {
        'id': str(uuid.uuid5(uuid.NAMESPACE_URL, 'skillpilot:economics:bounded-terminal:20261009:'+key)),
        'title': title, 'titleEn': en, 'description': desc, 'descriptionEn': den,
        'weight': 1, 'tags': ['GK', 'LK', 'Practice', 'Assessment'],
        'contains': [], 'requires': [required], 'type': 'atomic', 'phase': phase,
        'dimensionTags': {'framework':'canonical-gymnasium-economics','demandLevel':'AB3','phase':phase},
        'extendedData': {'applicabilityFromRequires': True},
        'examData': {
            'reviewStatus':'draft','coveredGoalIds':[required], 'coveredStrands':['WW_WIRTSCHAFT'],
            'demandLevels':['AB1','AB2','AB3'], 'taskContent':task,'solutionContent':solution,
            'scoring': {'maxPoints':sum(x[0] for x in steps),'passingPoints':18 if sum(x[0] for x in steps)==30 else 15,
                        'steps':[{'id':'s'+str(i+1),'points':x[0],'description':x[1]} for i,x in enumerate(steps)]}
        }
    }

property_case = terminal(
    'property-institution-and-limits', 'Q1: Eigentumsrechte und sozialen Interessenausgleich beurteilen',
    'Q1: assess property rights and a social balance of interests',
    'Die lernende Person kann in einem neuen materialgestützten Eigentumsfall Befugnisse und rechtliche Grenzen unterscheiden, die Wertgrundlagen und wirtschaftliche Funktion privater Eigentumsrechte analysieren und einen bedingten Interessenausgleich begründen.',
    'The learner can distinguish powers and legal limits in a new material-based property case, analyse the underlying values and economic function of private property rights and justify a conditional balance of interests.',
    'Q1', '099086bb-5100-5ce0-8334-0aab8850a48e',
    '''**Fall: Eine private Werkstatt und ein öffentlicher Weg**

Personen und Vorhaben sind erfunden. Beurteilt wird der bereitgestellte rechtliche und wirtschaftliche Rahmen; weitere Vorschriften oder ein tatsächlich bestehender Rechtsanspruch werden nicht unterstellt. Diese Unterrichtsaufgabe ersetzt keine individuelle Rechtsberatung.

**Material 1 – Regeln, sinngemäß:** § 903 BGB erlaubt Eigentümerinnen und Eigentümern einer Sache grundsätzlich, über sie zu verfügen und andere von Einwirkungen auszuschließen, soweit Gesetze oder Rechte Dritter nicht entgegenstehen. Art. 14 Abs. 1 GG schützt Eigentum und Erbrecht; Gesetze bestimmen Inhalt und Grenzen. Nach Abs. 2 verbindet Eigentum sich mit Verantwortung und sein Gebrauch soll zugleich der Allgemeinheit dienen. Eine Enteignung ist nach Abs. 3 nur zum Wohl der Allgemeinheit zulässig, auf gesetzlicher Grundlage, die auch Art und Ausmaß der Entschädigung regelt. Der öffentliche Zweck allein ersetzt die weiteren Voraussetzungen nicht. Quellen: [§ 903 BGB](https://www.gesetze-im-internet.de/bgb/__903.html) und [Art. 14 GG](https://www.gesetze-im-internet.de/gg/art_14.html), tatsächlich gelesen am 9. Oktober 2026. Die abstrakte Sozialbindung ist keine unmittelbare allgemeine Befugnis Dritter zum Betreten oder Nutzen eines beliebigen Grundstücks.

**Material 2 – Eigentümerentscheidung:** Nora besitzt eine kleine Werkstatt und das Grundstück. Sie darf über die Nutzung und einen möglichen Verkauf grundsätzlich selbst entscheiden; ein Dritter hat im Fall kein vertragliches Nutzungsrecht. Eine für diesen Modellfall ausdrücklich verbindliche gesetzliche Lärmregel begrenzt lärmintensive Arbeiten nachts zum Schutz der Nachbarschaft. Nora erklärt: „Weil ich die Eigentümerin bin, brauche ich keine Lärmgrenze zu beachten.“ Für neue Maschinen würde sie erhebliche eigene Mittel einsetzen. Sie benötigt dafür einen verlässlichen Rahmen für künftige Nutzung und Erträge; Erträge werden dadurch weder zugesagt noch garantiert.

**Material 3 – Gemeindevorhaben:** Die Gemeinde möchte einen dauerhaften öffentlichen Fußweg über Noras Grundstück bauen, weil er Wege zur Schule verkürzt. Ein freiwilliger Vertrag könnte Lage, Nutzung und Vergütung regeln. Es ist aber noch kein Vertrag zustande gekommen; eine besondere gesetzliche Grundlage für einen Entzug oder eine verpflichtende Nutzung und eine Entschädigungsregelung werden im Fall nicht nachgewiesen. Der Bürgermeister erklärt: „Der Weg nützt vielen Menschen; Art. 14 Abs. 2 erlaubt uns deshalb sofort den dauerhaften Zugriff.“ Das Material behauptet weder, dass ein öffentliches Vorhaben generell ausgeschlossen ist, noch dass eine zulässige Enteignung bereits feststeht. Andere mögliche Rechtsgrundlagen müssten konkret geprüft werden.

**Aufgaben – 24 BE:**

1. Erläutern Sie am Fall jeweils eine Eigentümerbefugnis, deren gesetzliche Grenze und die Bedeutung der Sozialbindung. Prüfen Sie Noras Aussage zur Lärmregel sowie die Aussage des Bürgermeisters. Unterscheiden Sie allgemeine Sozialbindung und die Voraussetzungen einer Enteignung. **(8 BE)**
2. Analysieren Sie, wie verlässliche private Eigentumsrechte in der Sozialen Marktwirtschaft Planung, eigenverantwortliche Entscheidung und Investitionsanreize unterstützen können. Beziehen Sie die Werte Freiheit, Rechtssicherheit und Verantwortung für andere auf Nora, die Nachbarschaft und den Fußweg; zeigen Sie, warum weder garantierte Erträge noch grenzenlose Nutzung folgen. **(8 BE)**
3. Begründen Sie einen bedingten Interessenausgleich für den Weg und die Werkstatt. Vergleichen Sie eine freiwillige Vereinbarung mit einem staatlich erzwungenen Zugriff. Benennen Sie mindestens zwei noch zu klärende rechtliche oder praktische Informationen und prüfen Sie „Gemeinwohl schlägt Eigentum immer“ sowie „Eigentum schließt öffentliche Belange immer aus“. **(8 BE)**
''',
    '''1. Nora kann die Werkstatt grundsätzlich selbst nutzen, andere ohne Nutzungsrecht ausschließen oder über einen Verkauf entscheiden. Die ausdrücklich verbindliche Lärmregel begrenzt die Nutzung zum Schutz anderer; Eigentum hebt sie nicht auf. Sozialbindung verlangt, Eigentumsgebrauch auch auf öffentliche Belange zu beziehen, gibt Dritten aber keine allgemeine Zugriffserlaubnis. Der Bürgermeister weist keinen Vertrag oder eine konkrete Eingriffsgrundlage nach. Soll Eigentum entzogen werden, reicht ein nützlicher öffentlicher Zweck nicht: Art. 14 Abs. 3 verlangt Allgemeinwohlzweck, gesetzliche Grundlage sowie gesetzlich geregelte Entschädigung. Ob ein anderes rechtmäßiges Instrument besteht, ist offen. **8 BE: fallbezogene Befugnis 1; Lärmregel als konkrete Grenze einschließlich Noras Fehler 2; Sozialbindung und fehlende automatische Zugriffserlaubnis 2; fehlende Grundlage im Wegfall 1; gesetzliche Grundlage und Entschädigungsregelung bei Enteignung 2.**

2. Dispositionsfreiheit ermöglicht Nora eine eigene Nutzungs- oder Verkaufsentscheidung. Ein verlässlicher Schutz gegen beliebigen Entzug unterstützt längerfristige Planung und kann den Anreiz stärken, eigene Mittel in Maschinen einzusetzen. Das Ergebnis hängt weiterhin von Nachfrage, Kosten und anderen Bedingungen ab; Eigentum garantiert keinen Gewinn. Rechtssicherheit betrifft zugleich nachvollziehbare Regeln für Nora und Schutzrechte anderer. Die Lärmregel konkretisiert Verantwortung für die Nachbarschaft. Der Weg zeigt einen legitimen öffentlichen Bedarf, der mit Noras Freiheit und Planung im rechtlichen Rahmen abgewogen werden muss. Private Entscheidungsräume und sozialer Schutz bilden zusammen den institutionellen Rahmen, ohne eine der Seiten pauschal aufzuheben. **8 BE: zwei konkrete wirtschaftliche Mechanismen je 2 (4); Freiheit und Rechtssicherheit am Fall 1; Verantwortung und Schutz der Nachbarschaft 1; legitimer Wegbedarf im rechtlichen Rahmen 1; kein Ertrags- oder grenzenloses Nutzungsversprechen 1.**

3. Zunächst kann eine freiwillige, transparente Vereinbarung über Lage, Sicherheitsfragen, Dauer und Vergütung geprüft werden; sie benötigt Noras Zustimmung und darf ihre Produktionsnutzung nicht ungeprüft ignorieren. Ein erzwungener Zugriff benötigt das tatsächlich passende gesetzliche Instrument und dessen Voraussetzungen; im Material fehlen sie. Offen sind z. B. die genaue Wegführung und Alternativen sowie die geltende Eingriffsgrundlage und gegebenenfalls Entschädigung. Ein bedingtes Urteil kann den Weg bei nachgewiesenem Bedarf, rechtmäßiger Grundlage und tragbarem Ausgleich unterstützen oder eine weniger belastende Alternative bevorzugen. Beide pauschalen Sätze sind falsch: Gemeinwohl beseitigt Eigentum nicht automatisch, Eigentum beseitigt aber auch rechtmäßige gesetzliche Grenzen und öffentliche Interessen nicht. Andere materialgebundene Abwägungen sind gleichwertig. **8 BE: freiwillige Vereinbarung mit Zustimmung und Fallbedingungen 2; rechtlich bedingter staatlicher Zugriff 2; zwei konkrete fehlende Informationen je 1 (2); ausgewogenes bedingtes Urteil und begründete Zurückweisung beider Absolutsätze 2.**
''', [(8,'Befugnisse, konkrete Lärmgrenze, Sozialbindung und Enteignungsbedingungen'),(8,'Werte und zwei wirtschaftliche Funktionen von Eigentumsrechten am Fall'),(8,'Bedingter Interessenausgleich und tatsächliche Informationsgrenzen')])

forex = terminal(
    'household-and-business-exchange-rate-effects', 'Q3: Wechselkurseffekte für Haushalt, Import und Export analysieren',
    'Q3: analyse exchange-rate effects for households, imports and exports',
    'Die lernende Person kann in einem neuen Modellfall aus einer ausdrücklich gegebenen Kursnotierung Zahlungs- und Erlösänderungen für einen Haushalt, ein importierendes und ein exportierendes Unternehmen berechnen und die Folgen an Vertragswährung, Vorleistungen und ungewisse Nachfrage binden.',
    'The learner can calculate changes in payments and receipts for a household, an importing firm and an exporting firm from an explicitly given exchange-rate quotation in a new model case and limit the effects by invoicing currency, intermediate inputs and uncertain demand.',
    'Q3', '99541aa7-c590-5f5d-8e89-fe2e39da7a9c',
    '''**Fall: Eine Euro-Abwertung und drei unterschiedliche Betroffene**

Die Kurse, Personen und Verträge sind fiktive Unterrichtsmodelle, keine aktuellen Marktdaten oder Empfehlung. Alle Zahlungen erfolgen genau zum jeweiligen angegebenen Kurs, ohne Gebühren, Steuern, Absicherung oder zeitliche Verzögerung. Zwei Zeitpunkte werden bei sonst gleichen ausdrücklich gegebenen Bedingungen verglichen.

**Material 1 – Notierung:** Zum Zeitpunkt A gilt 1 EUR = 1,25 USD, zum Zeitpunkt B 1 EUR = 1,00 USD. Ein unveränderter USD-Betrag wird in EUR umgerechnet, indem er durch die jeweils pro EUR erhältlichen USD geteilt wird. Die Kursnotierung ist kein Preisindex und keine Prognose.

**Material 2 – feste USD-Verträge:** Haushalt H muss für eine Reise zu jedem der Vergleichszeitpunkte 1.000 USD bezahlen. Importfirma I kauft dieselbe Warenmenge für 8.000 USD. Exportfirma X erhält für dieselbe Liefermenge 10.000 USD; ihre importierten Vorleistungen für genau diese Lieferung kosten 4.000 USD. In jedem Vergleich werden Zahlung und Eingang zum selben angegebenen Kurs umgerechnet. Inländische Löhne und sonstige EUR-Kosten von X fehlen. Deshalb ist die Differenz zwischen Erlös und diesen importierten Vorleistungen ein begrenzter Deckungsbetrag vor den nicht angegebenen weiteren Kosten, kein vollständiger Nettogewinn. Die Liefermengen und USD-Preise sind in Material 2 vertraglich fest.

**Material 3 – getrennte Preisvariante:** In einem anderen Vertrag berechnet eine Exportfirma ihren ausländischen Kundinnen und Kunden je Stück unverändert 80 EUR. Der ausländische Preis wird zum jeweiligen Kurs in USD umgerechnet. Eine niedrigere USD-Summe könnte Nachfrage fördern, aber Nachfrageänderung, Kapazität und tatsächlich verkaufte Menge sind nicht gegeben. Material 3 ist keine zusätzliche Erlösquelle der Firma X aus Material 2.

Hintergrund zur Begriffsrichtung: [Deutsche Bundesbank, Glossar – Aufwertung](https://www.bundesbank.de/dynamic/action/de/startseite/glossar/723820/glossar). Die Rechenbeispiele und Vertragsvarianten stammen von SkillPilot und behaupten keine empirischen Wirkungsgrößen.

**Aufgaben – 30 BE:**

1. Bestimmen Sie die Auf- oder Abwertung von EUR gegenüber USD anhand der Notierung. Berechnen Sie für H und I die Zahlungen in EUR zu A und B einschließlich absoluter und prozentualer Änderung gegenüber A. Erläutern Sie, warum derselbe USD-Preis für beide in EUR teurer wird, und prüfen Sie „Von 1,25 auf 1,00 sind −20 %, also steigen die EUR-Kosten nur um 20 %“. **(10 BE)**
2. Berechnen Sie für X Erlöse, importierte Vorleistungskosten und deren Differenz jeweils in EUR zu A und B. Deuten Sie die gegenläufigen Teilwirkungen und prüfen Sie „Die höheren EUR-Erlöse beweisen einen höheren Nettogewinn jedes Exportunternehmens“. **(10 BE)**
3. Berechnen und vergleichen Sie in der getrennten Variante den USD-Stückpreis zu A und B. Erläutern Sie, wie eine Nachfragewirkung vom Ergebnis der festen USD-Verträge zu unterscheiden ist. Begründen Sie ein differenziertes Urteil zur Behauptung „Eine Euro-Abwertung nützt allen Unternehmen und allen Haushalten“; nennen Sie zwei konkrete Informationen, die für eine tatsächliche Unternehmensbeurteilung fehlen. **(10 BE)**
''',
    '''1. Für einen EUR erhält man zu B weniger USD: der EUR wertet gegenüber USD ab, der USD gegenüber EUR auf. H: 1.000/1,25 = 800 EUR, 1.000/1 = 1.000 EUR, +200 EUR bzw. +25 % von 800. I: 8.000/1,25 = 6.400 EUR, 8.000/1 = 8.000 EUR, +1.600 EUR bzw. +25 % von 6.400. Der Euro-Gegenwert steigt, weil für die gleiche USD-Schuld mehr EUR nötig sind. Die USD-pro-EUR-Notierung fällt um 20 % ihrer alten Bezugsgröße; der inverse EUR-pro-USD-Preis steigt um 25 %. Die Bezugsgrößen dürfen nicht vertauscht werden. **10 BE: Richtung mit Notierung 2; je richtige Zahlungspaarung H und I je 2 (4); beide absoluten Änderungen zusammen 1; beide 25-%-Änderungen mit alter EUR-Basis 1; Umrechnungsmechanismus und begründete Unterscheidung der inversen Prozentänderung 2.**

2. X-Erlöse: 10.000/1,25 = 8.000 EUR und 10.000/1 = 10.000 EUR. Importierte Vorleistungen: 4.000/1,25 = 3.200 EUR und 4.000/1 = 4.000 EUR. Differenzen: 4.800 EUR und 6.000 EUR, +1.200 EUR. Die Euro-Erlöse steigen um 2.000 EUR, zugleich steigen die Vorleistungskosten um 800 EUR. Für die ausdrücklich festen USD-Mengen und -Preise steigt hier die begrenzte Differenz. Unbekannte Löhne, andere Kosten, Vertragswährungen und Mengen schließen eine Nettogewinnberechnung oder Verallgemeinerung auf jedes Exportunternehmen aus. **10 BE: richtiges Erlöspaar 2; richtiges Vorleistungspaar 2; beide Differenzen und deren Änderung 2; gegenläufige Teilwirkungen mit Zahlen 2; begrenzter Deckungsbetrag statt Nettogewinn und keine universelle Exportaussage 2.**

3. 80 EUR kosten die ausländische Kundschaft zu A 80×1,25 = 100 USD, zu B 80×1 = 80 USD, −20 USD bzw. −20 % der alten USD-Summe. Hier bleibt der EUR-Stückerlös vertraglich 80; in Material 2 bleibt dagegen der USD-Erlös fest und der EUR-Gegenwert verändert sich. Ein günstigerer USD-Preis kann Nachfrage anregen, beweist aber weder die tatsächliche Nachfrage noch höhere gesamte EUR-Erlöse oder Gewinn. H und I tragen im gegebenen Fall höhere EUR-Kosten; X hat bei seinen besonderen Bedingungen eine höhere begrenzte Differenz. Die pauschale Behauptung ist damit widerlegt. Für einen realen Unternehmensfall fehlen z. B. Mengenreaktionen und Kapazität, übrige Kosten und ihre Währungen oder tatsächliche Absicherung/Vertragsbedingungen. Auch in EUR festgelegte Importpreise könnten die unmittelbare Wirkung verändern. **10 BE: USD-Preise und Änderung 2; richtige Unterscheidung der festen Vertragswährung/EUR-Stückerlöse 2; mögliche statt bewiesene Nachfragewirkung 2; differenziertes Urteil mit H/I und X 2; zwei konkrete fehlende Informationen je 1 (2).**
''', [(10,'Kursrichtung, Haushalt und Import mit korrekten inversen Bezugsgrößen'),(10,'Exporterlös und Vorleistungen, begrenzte Differenz statt Nettogewinn'),(10,'Alternative Fakturierung, Nachfragegrenze und differenziertes Urteil')])

finance_actors = terminal(
    'financial-market-actors-and-funding', 'Q1: Finanzmarktakteure und Unternehmensfinanzierung unterscheiden',
    'Q1: distinguish financial-market participants and business financing',
    'Die lernende Person kann in einem neuen Finanzierungsfall Interessen und Funktionen von Haushalten, Unternehmen, Banken, Börse und einer Vermittlungsplattform analysieren, kurzfristige Liquidität von längerfristiger Finanzierung sowie Neuemissionen von Sekundärhandel unterscheiden und wirtschaftliche Nutzen und Risiken bedingt beurteilen.',
    'The learner can analyse the interests and functions of households, businesses, banks, an exchange and an intermediary platform in a new funding case, distinguish short-term liquidity from longer-term funding and new issues from secondary trading and assess economic benefits and risks conditionally.',
    'Q1', '6f75cdff-7d32-533b-8fe9-3d003b7af241',
    '''**Fall: Eine Lieferzahlung, eine Maschine und unterschiedliche Finanzakteure**

Alle Personen, Beträge und Angebote sind Unterrichtsmodelle. Es werden keine realen Produkte empfohlen. Die folgende Abgrenzung und die beschriebenen Vertragsbedingungen gelten ausdrücklich im Modell; daraus folgen keine realen Garantien oder aufsichtsrechtlichen Zusagen.

**Material 1 – zeitlicher Rahmen und Interessen:** Im weiten Begriffsgebrauch betrifft der Geldmarkt kurzfristige Finanzforderungen und Wertpapiere mit Laufzeiten bis zu einem Jahr; der Kapitalmarkt betrifft längerfristige Finanzierungen. Im engeren Interbankengeldmarkt handeln insbesondere Banken kurzfristige Liquidität untereinander. Ein Betrieb ist nicht allein deshalb eine Bank, weil er einen kurzfristigen Kredit benötigt. Hintergrund: [Deutsche Bundesbank, Geldmarktsätze](https://www.bundesbank.de/de/statistiken/geld-und-kapitalmaerkte/zinssaetze-und-renditen/geldmarktsaetze), tatsächlich gelesen am 9. Oktober 2026.

Das Unternehmen Lumen muss Materialrechnungen von 15.000 EUR in zwei Wochen bezahlen; vertraglich sichere Kundeneingänge von 15.000 EUR werden in drei Monaten erwartet. Unabhängig davon möchte es eine Maschine für 100.000 EUR erwerben und acht Jahre nutzen. Die Erträge daraus sind ungewiss. Haushalt H hält eine kurzfristig benötigte Zahlungsreserve; Haushalt J verfügt im Modell über darüber hinausgehende langfristige Mittel, muss aber Risiken und Informationslücken selbst berücksichtigen. Ihr Interesse an Verfügbarkeit und Sicherheit kann vom langfristigen Finanzierungsbedarf des Unternehmens abweichen.

**Material 2 – Bank und Kapitalmarkt:** Eine Bank kann Informationen über Lumen prüfen und einen dreimonatigen Überbrückungskredit vermitteln bzw. vergeben. Für die Maschine prüft sie ein gesondertes längerfristiges Darlehen. Kredite begründen Rückzahlungsverpflichtungen; die Bank muss ihre eigene Liquidität, Finanzierung und Ausfallrisiken steuern. Kreditvergabe ist hier kein bloßes physisches Durchreichen exakt derselben zuvor eingezahlten Banknoten. Kurzfristig fällige Verpflichtungen und längerfristige Kredite können einen Liquiditätskonflikt erzeugen; Risikoprüfung garantiert keinen Ausfall von null.

Als getrennte Kapitalmarktvariante gibt Lumen 1.000 neue Beteiligungsanteile zu jeweils 100 EUR aus. Die gesamten Zahlungen fließen in dieser Modell-Neuemission an Lumen; Gebühren fehlen. Diese Beteiligungen haben kein im Material zugesagtes festes Rückzahlungsdatum oder garantierte Gewinne. In einem späteren, getrennten Börsengeschäft verkauft Anleger A 20 bereits vorhandene Anteile zu je 100 EUR an Anleger B. Die Zahlung fließt von B an A und nicht an Lumen. Organisierter Sekundärhandel kann die Veräußerbarkeit und Preisfindung unterstützen; ein Verkauf zu einem bestimmten Preis oder eine Mindestliquidität wird dadurch nicht garantiert.

**Material 3 – Plattformvariante:** Eine Plattform vermittelt direkte dreijährige Darlehensverträge zwischen vielen Geldgebenden und Lumen. Sie selbst ist in diesem Modell weder Darlehensgeberin noch Bank und garantiert keine Rückzahlung. Eine Vergütung der Plattform und ein Interessenkonflikt bei der Darstellung riskanter Projekte sind möglich. Ob und welche realen Schutzvorschriften anwendbar wären, wird nicht behauptet; es werden keine realen Anbieter bewertet.

**Aufgaben – 24 BE:**

1. Ordnen Sie den dreimonatigen Finanzierungsbedarf und die längerfristigen Varianten zeitlich ein. Vergleichen Sie die Interessen von Lumen und den beiden Haushalten. Erläutern Sie am Bankmodell zwei Vermittlungs- oder Transformationsfunktionen und je ein damit verbundenes Informations- oder Liquiditätsrisiko. Unterscheiden Sie den kurzfristigen Unternehmensbedarf vom engeren Interbankenmarkt. **(8 BE)**
2. Berechnen Sie die Geldzuflüsse in der Neuemission und im späteren Börsengeschäft jeweils mit Empfänger. Analysieren Sie die wirtschaftliche Bedeutung von Neuemission und Sekundärmarkt für Unternehmen und Geldgebende. Prüfen Sie „Jeder Börsenkauf finanziert Lumen unmittelbar“ sowie „Eine Beteiligung garantiert die Rückzahlung wie ein sicherer Kredit“. **(8 BE)**
3. Vergleichen Sie Bankdarlehen, neue Beteiligungsanteile und die Plattformvariante hinsichtlich Akteursrollen, Finanzierung und Risiken. Begründen Sie, wie die Akteure Investitionen und Liquidität in der Wirtschaft unterstützen können, ohne dass Nutzen oder passende Finanzierung garantiert sind. Nennen Sie zwei für ein fallgebundenes Finanzierungsurteil fehlende Informationen. **(8 BE)**
''',
    '''1. Der dreimonatige Bedarf betrifft kurzfristige Überbrückung; achtjährige Maschinennutzung und ausdrücklich längerfristiges Darlehen/Beteiligung betreffen einen längeren Horizont. Kurzfristige Forderungen fallen im weiten Rahmen in den Geldmarktbereich, aber Lumen ist nicht Teil eines Interbankengeschäfts. H braucht kurzfristige Verfügbarkeit, J kann zusätzliche Mittel länger binden, ohne dass daraus Risikolosigkeit folgt. Lumen benötigt passende Finanzierung und muss bei Darlehen später tilgen. Banken können kleinere/verschieden fällige Mittel und längerfristigen Kreditbedarf koordinieren sowie Informationen prüfen und Kreditrisiken bewerten. Kurzfristige eigene Verpflichtungen können trotz langfristigem Kreditvermögen sofortige Liquidität verlangen; unvollständige Information kann zu Fehleinschätzungen führen. **8 BE: kurzfristig/längerfristig korrekt 1; weiter Geldmarkt versus Interbankengeschäft 1; konkrete Interessen Lumen/H/J 2; zwei sachliche Bankfunktionen je 1 (2); zwei zugehörige konkrete Risiken je 1 (2).**

2. Neuemission: 1.000×100 = 100.000 EUR fließen an Lumen zur Finanzierung. Sekundärgeschäft: 20×100 = 2.000 EUR fließen an den bisherigen Anleger A; Lumen erhält hier null. Neuemission beschafft neue Mittel, Sekundärhandel kann Ausstiegsmöglichkeiten und Preise unterstützen und dadurch die Bereitschaft zur Teilnahme am Primärmarkt mittelbar beeinflussen. Das ist keine weitere unmittelbare Mittelzahlung an das Unternehmen. Beteiligungen bedeuten Risikoteilnahme und ohne gegenteilige Vertragsangabe keine garantierte Rückzahlung oder Rendite. Auch ein Kredit ist nicht allein wegen seiner rechtlichen Rückzahlungspflicht wirtschaftlich ausfallsicher. **8 BE: beide Beträge mit richtigen Empfängern je 1 (2); direkte Neuemissionsfinanzierung 1; Sekundärmarkt-Funktion und indirekte Beziehung zur Finanzierung 2; kein unmittelbarer Unternehmenszufluss beim Sekundärgeschäft 1; Beteiligungsrisiko statt Garantie 1; Rückzahlungspflicht nicht mit Ausfallsicherheit verwechselt 1.**

3. Bank: Kreditprüfung und eigener Vertrag/Finanzierungs- und Liquiditätssteuerung, während Lumen Tilgungs- und Zinslasten übernimmt. Beteiligung: viele Geldgebende stellen neue Mittel gegen Risikobeteiligung; im Material kein fester Rückzahlungstermin. Plattform: vermittelt direkte Darlehen zwischen Lumen und Geldgebenden; sie trägt hier nicht automatisch deren Ausfallrisiko und kann trotz Provision ein Eigeninteresse haben. Diese Wege können unterschiedlich benötigte Mittel mobilisieren, Informationen verarbeiten, Liquidität über Zeit verbinden und Investitionen unterstützen. Fehlentscheidung, Ausfälle, Fristkonflikte und Interessenkonflikte begrenzen das. Für ein Urteil fehlen z. B. Kosten und Vertragsbedingungen sowie belastbare Cashflow-/Ausfallinformationen und Verlusttragfähigkeit der Geldgebenden. Ein kurzer Kredit ist nicht allein wegen des heutigen Liquiditätslochs für achtjährige Finanzierung passend. Andere bedingte materialgebundene Bewertungen gelten gleichwertig. **8 BE: drei Varianten mit ihren Akteurs- und Vertragsrollen je 1 (3); wirtschaftlicher Nutzen mit Fallmechanismus 1; zwei konkrete variantengebundene Risiken 2; zwei fehlende fallrelevante Informationen je 1 (2).**
''', [(8,'Zeitliche Abgrenzung, Akteursinteressen und konkrete Bankfunktionen/Risiken'),(8,'Primär-/Sekundärzahlungen, Finanzierung und Beteiligungsrisiko'),(8,'Drei Finanzierungswege und bedingte Bedeutung für die Wirtschaft')])

media = terminal(
    'journalism-and-cartoon-trade-policy', 'Q3: Journalistischen Handelsbericht und Karikatur beurteilen',
    'Q3: assess a journalistic trade report and cartoon',
    'Die lernende Person kann in einem neuen Materialvergleich journalistische Berichterstattung und zugeschriebene politische Aussagen unterscheiden, eine tatsächliche Karikatur über Bildmittel und Intention analysieren und Aussagegrenzen sowie eine bedingte politische Einordnung internationaler Handelsmaßnahmen begründen.',
    'The learner can distinguish journalistic reporting from attributed political claims in a new material comparison, analyse an actual cartoon using visual devices and intention and justify evidential limits and a conditional political assessment of international trade measures.',
    'Q3', '7f1d5e9f-65ef-5d1d-83e5-5e2534772720',
    '''**Fall: Handelskonflikt im Nachrichtenbericht und in einer Karikatur**

**Material 1 – tatsächlicher journalistischer Ausgangstext:** tagesschau.de veröffentlichte am 20. Juni 2025 um 21:55 Uhr einen Nachrichten-/Interviewbericht über Wirtschaftsministerin Katherina Reiches Äußerungen in den tagesthemen zum EU-US-Handelskonflikt. Herausgeber ist ARD-aktuell; in der hier tatsächlich gelesenen Seite wird keine individuelle Autorenzeile angegeben. Der Originalbericht ist unter [tagesschau.de, Bericht zum Reiche-Interview und Zollstreit](https://www.tagesschau.de/wirtschaft/reiche-handelsstreit-usa-zoelle-100.html) erreichbar. Es handelt sich um eine historisch datierte Medienepisode von 2025, nicht um eine Behauptung zum aktuellen Rechts- oder Zollstand im Oktober 2026.

Zwei kurze originale Textstellen; die Auslassungen in eckigen Klammern stammen von SkillPilot:

> „Bundeswirtschaftsministerin Katherina Reiche hat [...] betont, wie wichtig eine schnelle Einigung [...] ist.“
>
> „Der Zollstreit belastet beide Seiten des Atlantiks“, sagte die CDU-Politikerin.

**Eigene kompakte Kontextparaphrase von SkillPilot, kein Originalartikel:** Der Bericht schildert Reiches Reise nach Washington, ihre Gespräche mit US-Verantwortlichen und ihr Werben für rasche Verständigung. Er gibt ihre Zuversicht und ihre wirtschaftlichen Sorgen wieder. Als zeitlichen Hintergrund nennt er eine damals laufende befristete Aussetzung bestimmter Zölle und EU-Gegenmaßnahmen für ein Scheitern der Verhandlungen. Er berichtet außerdem über Unterschiede bei Standards. Die kurzen Originalstellen belegen hier, wie die Ministerin zitiert und Dringlichkeit dargestellt wird; sie enthalten keine quantitative Wirkungsschätzung, keinen Vergleich aller betroffenen Gruppen und keinen Beweis, dass eine bestimmte Einigung schon erreicht war.

**Material 2 – tatsächliche eigene Karikatur:** Die separat eingebundene PNG-Karikatur „Schutzschranke mit Rückwirkung“ ist ein von SkillPilot verfasster didaktischer Kommentar, kein veröffentlichtes Pressebild und keine empirische Datengrafik. Das Bild zeigt zwei fiktive Länderläden, eine errichtete Zollschranke, einen zustimmenden heimischen Hersteller sowie blockierte Vorproduktkisten und eine heimische Verbraucherin mit vielen Münzen und wenigen Waren. Ein Rückwirkungspfeil verbindet die Schutzschranke mit den heimischen Belastungen. Die Aufgabe verlangt das Betrachten des tatsächlichen Bildes; diese Beschreibung ersetzt es nicht. Das Bild materialisiert eine kritische, bewusst vereinfachende Position zu einseitigen Schutzversprechen. Für reale Personen oder Staaten steht es nicht. Der im finalen Materialstand eingebundene PNG-Pfad und sein tatsächlicher SHA müssen vor der Prüfung feststehen.

**Material 3 – offengelegte Urteilskriterien:** Als mögliche Ziele einer zeitlich begrenzten Handelsmaßnahme werden Schutz eines bedrohten Produktionsbereichs und geringere strategische Abhängigkeit diskutiert. Als mögliche Kosten werden höhere Einfuhrpreise, teurere importierte Vorleistungen und Gegenmaßnahmen betrachtet. Das sind allgemeine Unterrichtsperspektiven, keine im Bericht gemessenen Folgen oder quantifizierte Wirksamkeitsnachweise. Für diesen Fall fehlen genaue Zollsätze, Mengenreaktionen, Dauer, Verteilungseffekte und belastbare Wirkungsdaten. Eine Position darf daher begründet bedingt bleiben.

**Aufgaben – 24 BE:**

1. Bestimmen Sie Textsorte, Herausgeber und historischen Anlass von Material 1. Trennen Sie an den Originalstellen die journalistische Zuschreibung von der Aussage der Politikerin. Analysieren Sie zwei tatsächliche sprachliche Mittel und erläutern Sie, was diese kurzen Stellen über Absicht und Aussagekraft belegen und was sie offenlassen. Verwechseln Sie die eigene Kontextparaphrase nicht mit Originalwortlaut. **(8 BE)**
2. Beschreiben Sie mindestens drei tatsächlich sichtbare Elemente der Karikatur. Analysieren Sie die Beziehung zwischen Schutzschranke, heimischem Hersteller, blockierten Vorprodukten und Verbraucherin sowie ein konkretes Bildmittel. Begründen Sie eine plausible Intention und eine Grenze ihrer Aussagekraft anhand des tatsächlichen Bildes. **(8 BE)**
3. Vergleichen Sie die journalistische Vermittlung einer politischen Position mit dem satirischen Kommentar. Ordnen Sie beide in die Diskussion über Freihandel und Protektionismus ein, berücksichtigen Sie mindestens zwei betroffene Gruppen und einen materialgebundenen Einwand gegen Ihre eigene Position. Begründen Sie ein bedingtes Urteil und zwei dafür noch erforderliche Informationen. **(8 BE)**
''',
    '''1. Material 1 ist journalistischer Nachrichten-/Interviewbericht von ARD-aktuell auf tagesschau.de über Reiches Äußerungen und Reise im datierten EU-US-Konflikt von 2025. Das berichtende Verb markiert journalistische Zuschreibung; der zitierte Belastungssatz gehört Reiche, nicht automatisch der Redaktion. Die dargestellte Bedeutung eines raschen Abschlusses markiert in der berichteten Ministerinnenaussage Wertung und Dringlichkeit; die Beschreibung des Konflikts als Belastung formuliert ihre negative Bewertung. Die berichtete Dringlichkeit passt zum politischen Ziel einer raschen Einigung, beweist aber weder manipulative Absicht der gesamten Redaktion noch eine empirisch bezifferte beiderseitige Belastung. Die Stelle belegt die Zuschreibung einer Aussage; sie ist kein unmittelbarer Nachweis ihres wirtschaftlichen Umfangs oder späteren Erfolgs. **8 BE: Textsorte/Herausgeber und historischer Anlass 2; korrekte Trennung von Zuschreibung und Ministerinnenaussage 2; zwei tatsächliche sprachliche Mittel mit Funktion je 1 (2); begrenzte Aussagekraft und keine unbewiesene Redaktions-/Erfolgsbehauptung 2.**

2. Erwartet wird tatsächliche Beobachtung der Figuren, Schranke, Kisten, Verbraucherin/Münzen/Waren und Rückwirkungspfeil, nicht nur eine allgemeine Zollkritik. Die Schranke verspricht dem heimischen Hersteller Schutz, erschwert aber zugleich seine Vorprodukte und kann die inländische Kundschaft belasten. Der Rückwirkungspfeil und die überzeichnete Gegenüberstellung bündeln Kosten, die im einfachen Schutzversprechen fehlen. Eine plausible Intention ist, zum Prüfen heimischer Nebenfolgen anzuregen. Die Karikatur verdichtet eine Position und kann Zollsätze, Größen, Ausnahmen, mögliche Schutzvorteile und längerfristige Effekte nicht beweisen; sie ist kein statistischer Nachweis. **8 BE: drei tatsächlich sichtbare, zutreffend beschriebene Elemente 2; Beziehungen Hersteller/Vorprodukte/Verbraucherin mit Mechanismus 2; konkretes Bildmittel und dessen Funktion 2; bildgebundene Intention und konkrete Evidenzgrenze 2. Punkte für sichtbare Elemente dürfen bei fehlendem oder abweichendem tatsächlichem Bild nicht vergeben werden.**

3. Der Nachrichtenbericht vermittelt und attribuiert eine aktuelle politische Position innerhalb des damaligen Ereignisses; aus kurzen Zitaten folgt keine pauschale redaktionelle Parteinahme. Die eigene Karikatur vertritt erkennbar einen kritischen Kommentar zu einseitigen Schutzversprechen. Freihandel erleichtert grenzüberschreitenden Austausch; Protektionismus kann bestimmte heimische Produktion abschirmen, aber etwa Verbrauchende oder auf importierte Vorprodukte angewiesene Firmen belasten und Gegenreaktionen auslösen. Ein bedingtes Urteil kann Handelshemmnisse wegen dieser Risiken kritisch sehen, dabei den angegebenen Schutz-/Abhängigkeitsgrund als Einwand ernst nehmen und eine nur bei nachgewiesenem Bedarf, begrenzten Kosten und transparenter Dauer tragfähige Ausnahme diskutieren. Auch eine anders gewichtete, materialgebundene Position ist zulässig. Benötigt werden z. B. tatsächliche Preis-/Vorleistungseffekte für benannte Gruppen und geprüfte Wirksamkeit/Alternativen des Schutzes. **8 BE: unterschiedlicher Vermittlungs-/Kommentarstatus 2; Freihandel/Protektionismus mit zwei Gruppenfolgen 2; ernsthaft geprüfter Einwand gegen die eigene Position 1; begründetes bedingtes Urteil 1; zwei konkrete fehlende Informationen je 1 (2).**
''', [(8,'Tatsächliche journalistische Textsorte, Zuschreibung, Sprachmittel und Evidenzgrenzen'),(8,'Tatsächliche Karikaturbeobachtung, Bildmittel, Intention und Aussagegrenze'),(8,'Vergleich, politische Einordnung und materialgebundenes bedingtes Urteil')])

four = [property_case, forex, finance_actors, media]
p = OUT / 'whole-four-new-terminal-DRAFT-assessments.author.candidate.json'
p.write_text(json.dumps(four,ensure_ascii=False,indent=2)+'\n')
receipt = {
    'schemaVersion':1,'kind':'four-material-based-actual-Generic-route-author-candidate',
    'author':'economics_independent_continuation_a','reviewStatus':'draft','humanReviewStatus':'pending',
    'qualityApproval':False,'strictNewClosures':0,'liveWrites':[],
    'wholeCandidate':{'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()},
    'materialImageBindingPendingForMedia':True,
    'rows':[{'goalId':g['id'],'requires':g['requires'],'coveredGoalIds':g['examData']['coveredGoalIds'],
             'maxPoints':g['examData']['scoring']['maxPoints'],'passingPoints':g['examData']['scoring']['passingPoints'],
             'reason':'Exactly one genuine content prerequisite and material-based AB1–3 coverage; no broadened old terminal requires.'} for g in four],
    'sourceScope':'099/995/7f are actual common BY J11 aspects. 6f is explicitly the BY WWG J11 capital-market aspect; national practice inclusion is supplementary practice and does not create or alter national curricularAtomic target claims. Course/source proposals require independent root adoption.',
    'copyright':'The journalism material retains only two compact original excerpts with explicit omissions and an attributed original politician statement; 21 original lexical words in total, plus a short own context paraphrase. Full article and press photography are not reproduced.',
    'remainingBindings':['Actual PNG plus actual viewing and independent visual/material decision for media','Independent whole-material/rubric review of all four candidates','Actual target/support set comparison and native combined graph/routes','Actual final ownerpage impact; dual D, truthful current P2/AM/V/context binding','Human release remains pending']
}
rp = OUT / 'actual-four-whole-material-author-before-independent-review.receipt.json'
rp.write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'candidate':str(p),'sha256':receipt['wholeCandidate']['sha256'],'goals':receipt['rows']},ensure_ascii=False))
