# SPDX-License-Identifier: Apache-2.0
"""Two whole bilingual metal-model cases; source-specific transport is compulsory."""
from datetime import datetime, timezone
from pathlib import Path
import hashlib
import json

ROOT = Path.cwd()
OWN = Path(__file__).resolve().parent
OUT = OWN / 'source-view-remediation-author-v3'
GID = 'fcaf8c9b-bd81-552e-9d91-43649895471e'

def read(p): return json.loads(p.read_text())
def bind(p):
    raw = p.read_bytes()
    return {'path': str(p.relative_to(ROOT)), 'sha256': hashlib.sha256(raw).hexdigest(), 'bytes': len(raw)}
def write(name, value):
    p = OUT / name
    assert not p.exists(), p
    p.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n')
    return bind(p)
def bilingual(de, en): return {'de': de, 'en': en}

canonical_path = OUT / 'canonical504-one-faithful-redox-EN-existing-fields-kept.author-candidate.json'
canonical = read(canonical_path)
goal = next(g for g in canonical['goals'] if g['id'] == GID)
original_path = OWN / 'source-view-author/original35-opaque-entries-whole-source-operator-partner-v2-normal-facets.neutral-input.json'
original = read(original_path)
duty = next(d for d in original['entries'][10]['wholeOriginalSourceDutiesAndPartnerContexts'] if d['wholeSourceGoal']['id'] == 'mv-chem-seki-mv-ch-seki-2021-j8-kabel-005-57941cc6')

case1_task = bilingual(
 'Bereitgestellte qualitative Lehrbeobachtungen, kein eigener Versuch: Ein Kupferdraht leitet in einem geschlossenen Gleichstromkreis. Ohne angeschlossene Spannungsquelle gibt es keinen messbaren gerichteten Strom; bei umgekehrter Polung kehrt sich die Stromrichtung um. Im einfachen Dalton-Modell sind neutrale, unstrukturierte Kugeln zu sehen. Entwickle stattdessen selbst zwei beschriftete Teilchenskizzen (ohne/mit Spannungsquelle) und eine eigene Vergleichstabelle: positive Atomrümpfe/Metall-Ionen an Gitterplätzen mit Schwingungen, bewegliche delokalisierte Elektronen und äußere Spannungsquelle. Zeige den gerichteten Elektronentransport im geschlossenen Kreis und begründe die Grenzen des Dalton-Modells. Sage für eine Umpolung eine überprüfbare Änderung voraus; beurteile ausdrücklich die Behauptung, die positiven Metall-Ionen wanderten durch den Draht zum Minuspol. Kennzeichne Beobachtung, eigene Modellannahme und Grenze getrennt.',
 'Supplied qualitative teaching observations, not your own experiment: a copper wire conducts in a closed direct-current circuit. Without an attached voltage source there is no measurable directed current; reversing polarity reverses current direction. The simple Dalton model shows neutral unstructured spheres. Instead develop your own two labelled particle sketches (without/with the voltage source) and a comparison table: positive metal-ion cores at vibrating lattice sites, mobile delocalised electrons and an external voltage source. Show directed electron transport in the closed circuit and justify limits of Dalton’s model. Predict a testable change under reversed polarity; explicitly judge the claim that positive metal ions migrate along the wire toward the negative terminal. Distinguish observation, your model assumptions and limitations.')
case1_worked = bilingual(
 'Meine Tabelle trennt O1: Leitfähigkeit und O2: Richtungsumkehr von M1: positive Atomrümpfe bilden ein Gitter und M2: delokalisierte negative Elektronen sind beweglich. Neutrale, unstrukturierte Dalton-Kugeln enthalten weder bewegliche Ladungsträger noch eine Erklärung gerichteten Ladungstransports; diese konkrete Beobachtung motiviert eine Erweiterung, verwirft aber nicht Atom-/Stofferhaltung. In Skizze A schwingen positive Atomrümpfe um feste mittlere Gitterplätze; Elektronen bewegen sich ungeordnet, ohne makroskopischen gerichteten Strom. In Skizze B erzeugt die angeschlossene Spannungsquelle ein elektrisches Feld: zusätzlich zur ungeordneten Bewegung entsteht eine kleine mittlere Elektronendrift entgegen der technischen Stromrichtung, vom negativen zum positiven Anschluss durch den Draht. Die Quelle erzeugt keine Elektronen und macht kein Metall zu einer Ionenlösung. Positive Atomrümpfe schwingen weiterhin lokal; kein gerichteter Ionenstrom entlang des Drahtes. Bei Umpolung kehrt sich die Drift um, die Gitterstruktur bleibt. Die Skizze ist kein maßstabgetreues Teilchenfoto, liefert weder genaue Driftgeschwindigkeit noch einen Zahlenwert der Leitfähigkeit; Kontakt-/Grenzflächen und Quanteneffekte fehlen. Eigenes Produkt sind meine beiden Skizzen, Tabelle und begründete Vorhersage; die Messbeobachtungen bleiben bereitgestellt.',
 'My table separates O1: conduction and O2: reversal from M1: positive ion cores form a lattice and M2: delocalised negative electrons are mobile. Neutral unstructured Dalton spheres provide neither mobile charge carriers nor an explanation of directed charge transport; these observations motivate extending the model without rejecting atom or matter conservation. Sketch A shows positive ion cores vibrating around fixed average lattice sites; electrons move irregularly without a macroscopic directed current. In sketch B the connected voltage source establishes an electric field: a small mean electron drift is added to the irregular motion, opposite conventional current direction, from the negative to the positive connection through the wire. The source neither creates electrons nor turns metal into an ionic solution. Positive ion cores keep vibrating locally; there is no directed ion current along the wire. Reversing polarity reverses drift while preserving the lattice. The sketch is not a scale particle photograph and supplies neither exact drift speed nor a conductivity value; contacts and quantum effects are omitted. My own products are the sketches, table and justified prediction; measurements remain supplied.')
case1_transfer = bilingual(
 'Ein unbekannter heller Feststoff leitet nicht. Nach Schmelzen leitet er; im flüssigen Stoff bewegen sich positive UND negative Ionen. Prüfe, ob du ihn deshalb als Metall klassifizieren darfst, und ändere deine Ladungsträger-/Beweglichkeitsskizze begründet. Ein zweiter Kupferdraht hat einen offenen Schalter: Was fehlt gegenüber deinem vorherigen geschlossenen Modell?',
 'An unfamiliar pale solid does not conduct. On melting it conducts, with positive AND negative ions mobile in the liquid. Decide whether that makes it a metal and justify a revised carrier/mobility sketch. A second copper wire has an open switch: what is missing compared with your earlier closed-circuit model?')
case1_transfer_worked = bilingual(
 'Leitfähigkeit allein beweist kein Metall. Bewegliche positive und negative Ionen der Schmelze entsprechen einem anderen Ladungsträgermodell; im metallischen Feststoff waren Elektronen beweglich und positive Atomrümpfe gittergebunden. Ich zeichne in der Schmelze beide Ionensorten beweglich statt das Metallgitter zu übernehmen. Beim offenen Schalter fehlt ein durchgängiger geschlossener Ladungstransportweg; ungeordnete Elektronenbewegung bleibt, ein dauerhafter makroskopischer Kreisstrom fehlt. Eine Spannung über der Unterbrechung kann trotzdem bestehen. Diese Gegenprüfung schränkt das Metallmodell auf seinen tatsächlich begründeten Stoffkontext ein.',
 'Conduction alone does not prove a metal. Mobile positive and negative ions in the melt require another charge-carrier model; in a solid metal electrons were mobile and positive ion cores lattice-bound. I draw both ionic species mobile rather than importing the metal lattice. The open switch removes a continuous closed transport path; irregular electron motion persists but there is no sustained macroscopic circuit current. A voltage can still exist across the gap. The countercheck limits the metal model to its justified material context.')

case2_task = bilingual(
 'Neue bereitgestellte Modellbeobachtungen an demselben Kupferstück, keine reale Lerner-Messung: Es bleibt nach leichtem plastischem Verformen leitfähig. Bei Erwärmung sinkt im gleichen geschlossenen Stromkreis unter gleicher Spannung qualitativ die Stromstärke; beim Abkühlen steigt sie wieder. Geometrieänderungen werden für diesen qualitativen Vergleich vernachlässigt. Entwickle selbst ein Metallmodell und drei beschriftete Zustandsfelder (kalt/warm/verformt). Vergleiche mit einem neutralen Kugelmodell und einem Vorschlag, in dem Metall-Ionen durch den Draht fließen. Erkläre Verformbarkeit und gerichteten Strom mit delokalisierten Elektronen, Spannungsquelle und gittergebundenen schwingenden positiven Atomrümpfen. Begründe eine Modellvorhersage zum Erwärmen und benenne, welche qualitativen oder quantitativen Aussagen aus diesem einfachen Modell nicht folgen. Deine eigene Modellregel und ihre Prüfung müssen sichtbar sein.',
 'New supplied model observations for the same copper piece, not a real learner measurement: it remains conductive after slight plastic deformation. On warming, current qualitatively decreases in the same closed circuit at unchanged voltage; cooling increases it again. Geometry changes are neglected for this qualitative comparison. Develop your own metal model and three labelled states (cold/warm/deformed). Compare it with neutral spheres and a proposal in which metal ions flow down the wire. Explain deformation and directed current using delocalised electrons, a voltage source and vibrating positive ion cores bound to lattice positions. Justify a prediction on warming and state which qualitative or quantitative claims do not follow from this simple model. Your own model rule and its check must be visible.')
case2_worked = bilingual(
 'Mein Modell hat positive Atomrümpfe und gemeinsam verfügbare delokalisierte Elektronen. Die Bindung ist nicht als starre isolierte Zweierkette gezeichnet: bei kleiner plastischer Verschiebung bleibt die metallische Wechselwirkung erhalten, daher kann das Stück verformbar sein und Elektronen bleiben beweglich. Das neutrale unstrukturierte Kugelmodell erklärt nicht, warum gerichteter Ladungstransport erhalten bleibt. Für warmes Kupfer zeichne ich stärkere lokale Gitterschwingungen bei weiterhin geschlossener, gleich gepolter Spannungsquelle. Im einfachen Streumodell behindern Gitterschwingungen die gerichtete Elektronendrift stärker; bei gleicher Spannung erklärt dies qualitativ die geringere Stromstärke. Die positiven Atomrümpfe bleiben gittergebunden und sind keine von Anschluss zu Anschluss wandernden Ladungsträger. Ich prüfe die Vorhersage warm: kleinere Stromstärke gegen die bereitgestellte Beobachtung und halte die qualitative Übereinstimmung fest, ohne einen selbst ausgeführten Versuch zu behaupten. Der aktuelle Modellrahmen liefert keine exakte Strom-/Temperaturfunktion, Festigkeit oder Schmelztemperatur; nicht jedes leitfähige Material folgt dieser Temperaturtendenz. Der verformte Zustand ist ein neues Modellprodukt, kein Beleg beliebig großer reversibler Verformung.',
 'My model has positive ion cores and shared delocalised electrons. Bonding is not drawn as rigid isolated pairs: small plastic displacement can retain metallic interaction, allowing deformation while electrons stay mobile. Neutral unstructured spheres do not explain retained directed charge transport. For warm copper I draw stronger local lattice vibration with the closed, equally polarised voltage source retained. A simple scattering model gives stronger obstruction of directed electron drift and therefore qualitatively less current at the same voltage. Positive ion cores remain lattice-bound rather than travelling between terminals. I check the prediction of less current when warm against the supplied observation and record qualitative agreement without claiming my own experiment. This model supplies no exact current–temperature function, mechanical strength or melting point; not every conducting material follows this trend. The deformed state is an own model product, not proof of arbitrary reversible deformation.')
case2_transfer = bilingual(
 'Frischer Gegenfall: Die Folie wird durch eine durchgehende Lücke in zwei Teile getrennt, während die Spannungsquelle angeschlossen bleibt. Ein Mitschüler behauptet, stärkere Ionenschwingungen überbrückten die Lücke. Revidiere gegebenenfalls dein eigenes Verformungsmodell und erkläre, warum eine lokale Schwingung keine metallische Leitung durch Luft beweist. Welche zusätzliche Information wäre nötig, um eine Hochspannungsentladung zu beurteilen?',
 'Fresh countercase: a continuous gap divides the foil into two pieces while the voltage source stays connected. A peer claims stronger ion vibration bridges the gap. Revise your deformation model if needed and explain why local vibration does not prove metallic conduction through air. What extra information is needed to judge a high-voltage discharge?')
case2_transfer_worked = bilingual(
 'Kleine Verformung und vollständige Trennung sind verschiedene Bedingungen. Die Lücke unterbricht den zusammenhängenden metallischen Elektronentransportweg; lokale Ionenschwingungen verbinden die getrennten Stücke nicht. Ich ergänze die Voraussetzung zusammenhängendes Metall und geschlossener Stromweg. Ein möglicher Luftdurchschlag wäre ein anderes Ionisations-/Entladungsmodell, nicht das einfache Metallmodell; dafür fehlen Spannung, Spaltweite, Medium und geeignete Sicherheitsbedingungen. Ich behaupte keine Entladung und keinen Versuch. So prüfe und begrenze ich meine eigene Modellregel an einem echten Gegenfall.',
 'Small deformation and complete separation are different conditions. The gap interrupts continuous metallic electron transport; local ion vibration does not connect the pieces. I add the conditions of continuous metal and a closed transport path. Possible air breakdown would require another ionisation/discharge model; voltage, gap width, medium and safe conditions are missing. I claim neither discharge nor an experiment. This countercase tests and limits my own model rule.')

briefs = [
 {'id': 'MV-metal-model-copper-polarity', 'taskDemandDe': case1_task['de'], 'taskDemandEn': case1_task['en'],
  'expectedPerformanceDe': case1_worked['de'], 'expectedPerformanceEn': case1_worked['en'],
  'coveredExpectationIds': ['property-to-model', 'voltage-carriers-lattice', 'own-model-countercheck', 'limits-and-context'],
  'freshVariationDe': case1_transfer['de'], 'freshVariationEn': case1_transfer['en']},
 {'id': 'MV-metal-model-deformation-temperature', 'taskDemandDe': case2_task['de'], 'taskDemandEn': case2_task['en'],
  'expectedPerformanceDe': case2_worked['de'], 'expectedPerformanceEn': case2_worked['en'],
  'coveredExpectationIds': ['property-to-model', 'voltage-carriers-lattice', 'own-model-countercheck', 'limits-and-context'],
  'freshVariationDe': case2_transfer['de'], 'freshVariationEn': case2_transfer['en']}]
for index, brief in enumerate(briefs):
    transfer = [case1_transfer, case2_transfer][index]
    answer = [case1_transfer_worked, case2_transfer_worked][index]
    for suffix, language in [('De', 'de'), ('En', 'en')]:
        brief['taskDemand' + suffix] += (' Neue Variation: ' if language == 'de' else ' Fresh variation: ') + transfer[language]
        if index == 0 and language == 'de':
            brief['expectedPerformance' + suffix] = brief['expectedPerformance' + suffix].replace(' Eigenes Produkt sind meine beiden Skizzen, Tabelle und begründete Vorhersage; die Messbeobachtungen bleiben bereitgestellt.', '')
        brief['expectedPerformance' + suffix] += (' Transfer: ' if language == 'de' else ' Transfer: ') + answer[language]
        brief['understandingFocus' + suffix] = (goal['description'] + ' Die vollständige MV-Stromrolle verlangt gemeinsam Spannungsquelle, bewegliche Elektronen und lokal schwingende positive Gitterionen sowie eine eigene begründete Modellvorhersage/Gegenprüfung.' if language == 'de' else goal['descriptionEn'] + ' The whole MV current role jointly requires a voltage source, mobile electrons, locally vibrating positive ion cores and an own justified model prediction/countercheck.')
    del brief['coveredExpectationIds'], brief['freshVariationDe'], brief['freshVariationEn']
    assert all(len(value) <= 2000 for value in brief.values() if isinstance(value, str))
profile = {'archetype': 'modeling', 'expectations': [
 {'id': 'property-to-model', 'essentialUnderstandingDe': 'Metalleigenschaften motivieren eine begründete Erweiterung des neutralen unstrukturierten Dalton-Modells; eine eigene Modellregel verknüpft Beobachtung und Teilchenannahme.',
  'essentialUnderstandingEn': 'Metal properties motivate a justified extension of neutral unstructured Dalton spheres; an own model rule links observation and particle assumptions.',
  'observablePerformanceDe': 'Eigene beschriftete Skizzen/Tabelle aus Leitfähigkeit sowie Verformbarkeit entwickeln, Ladungsträger ergänzen und konkrete Erklärungsgrenzen des Dalton-Modells benennen.',
  'observablePerformanceEn': 'Develop own labelled sketches/table from conductivity and deformation, add charge carriers and identify specific limits of the Dalton model.'},
 {'id': 'voltage-carriers-lattice', 'essentialUnderstandingDe': 'Im geschlossenen metallischen Stromkreis erzeugt die äußere Spannungsquelle gerichtete Elektronendrift; positive Atomrümpfe schwingen um Gitterplätze und wandern nicht als metallischer Strom durch den Draht.',
  'essentialUnderstandingEn': 'In a closed metallic circuit the external voltage source produces directed electron drift; positive ion cores vibrate around lattice sites rather than carrying metallic current down the wire.',
  'observablePerformanceDe': 'Spannungsquelle, bewegliche delokalisierte Elektronen und lokal schwingende Gitterionen explizit in jeder Stromerklärung verknüpfen; ungeordnete Bewegung ohne gerichteten Strom, Umpolung und offene Leitung korrekt deuten.',
  'observablePerformanceEn': 'Explicitly connect voltage source, mobile delocalised electrons and locally vibrating lattice ions in each current explanation; correctly interpret random motion without directed current, reversed polarity and an open path.'},
 {'id': 'own-model-countercheck', 'essentialUnderstandingDe': 'Modellbildung verlangt ein eigenes darstellbares Modellprodukt, eine aus eigener Regel abgeleitete Vorhersage und deren Prüfung an Beobachtung oder Gegenfall.',
  'essentialUnderstandingEn': 'Model development needs an own representable product, a prediction from the learner’s rule and checking it against an observation or countercase.',
  'observablePerformanceDe': 'Eigene Zustandsfelder und Vergleichsbedingungen erstellen, Umpolung/Erwärmung vorausdeuten und am fremden Datensatz/Gegenfall prüfen; das eigene Modell bei vollständiger Trennung gezielt begrenzen.',
  'observablePerformanceEn': 'Produce own states and comparison conditions, predict reversal/warming and check against supplied data/countercases; limit the own model for complete separation.'},
 {'id': 'limits-and-context', 'essentialUnderstandingDe': 'Ein einfaches Metallmodell erklärt qualitative Eigenschaften in einem begrenzten Kontext; Ionenleitung in Schmelze/Lösung, Luftentladung und exakte Materialkennzahlen erfordern andere oder erweiterte Modelle.',
  'essentialUnderstandingEn': 'A simple metal model explains qualitative properties within a bounded context; ionic conduction, gas discharge and exact material constants need other or extended models.',
  'observablePerformanceDe': 'Metallische Elektronenleitung von beweglichen Ionen in Schmelzen unterscheiden, fehlende quantitative/Entladungsangaben benennen und eigene Skizzen von tatsächlichen Messungen/Laborleistungen trennen.',
  'observablePerformanceEn': 'Distinguish metallic electron conduction from mobile ions in melts, identify missing quantitative/discharge data and separate own sketches from actual measurements or lab performance.'}],
 'coverageExpectations': {'requiredExpectationIds': ['property-to-model', 'voltage-carriers-lattice', 'own-model-countercheck', 'limits-and-context'],
  'alternativeExpectationGroups': [], 'minimumIndependentDemonstrations': 2, 'freshVariationRequired': True, 'independentTransferRequired': True},
 'variationAxes': [{'id': 'polarity-and-material', 'textDe': 'Umpolung/offener Kreis und Metall versus ionische Schmelze erfordern begründete Modelländerungen statt auswendig wiederholter Ladungssätze.', 'textEn': 'Reversal/open circuit and metal versus ionic melt require reasoned model changes rather than repeated carrier labels.'},
                   {'id': 'deformation-and-limit', 'textDe': 'Erwärmung, leichte Verformung und vollständige Trennung ändern konkrete Randbedingungen; quantitative Reichweite und alternative Stoffmodelle bleiben begrenzt.', 'textEn': 'Warming, slight deformation and complete separation change boundary conditions; quantitative reach and other material models remain bounded.'},
                   {'id': 'actual-MV-source-role', 'textDe': 'MV Klasse8 verlangt konkret Spannungsquelle, bewegliche Elektronen und schwingende Metall-Ionen. Diese drei Elemente sind verbindliches zusammenhängendes eigenes Modellprodukt; keine Ionenlösung als Ersatz. Die ganze amtliche Kabelpassage und sämtliche bisherigen Partner bleiben erhalten. Ein bereitgestellter Lehrbefund ist kein eigener Versuch.', 'textEn': 'MV year8 specifically requires a voltage source, mobile electrons and vibrating metal ions. These three form one mandatory own model product; ionic solution is not a substitute. The whole official cable passage and all existing partners remain. A supplied teaching observation is not an own experiment.'}],
 'applicationCaseBriefs': briefs}
cases = []
rubric = bilingual(
 'Erforderlich: eigenes Modellprodukt aus Stoffeigenschaften; konkrete begründete Dalton-Grenze; Spannungsquelle im geschlossenen Kreis; bewegliche Elektronen als gerichtete Träger; lokal schwingende positive Gitterionen ohne Translation entlang des Drahts; eigene Vorhersage und Gegenfallprüfung; begrenzte quantitative/stoffliche Reichweite; Daten/Modell/realer Versuch getrennt. Nur Ladungsträgernamen oder bereitgestellte Skizzen nacherzählen reicht nicht. Ionenwandern als metallischer Strom, Elektronenerzeugung durch Batterie oder behaupteter Eigenversuch blockieren. Gezielte Nachfrage prüft fehlende Facette, keine zusätzliche Aufgabenquote.',
 'Required: an own model product derived from properties; a specific justified Dalton limitation; voltage source in a closed circuit; mobile electrons as directed carriers; locally vibrating positive lattice ions without translation down the wire; own prediction and countercheck; bounded quantitative/material reach; data/model/real experiment distinguished. Repeating carrier names or supplied sketches is insufficient. Ion migration as metallic current, electron creation by the battery or invented own experiments block success. A targeted question checks a missing facet, not an extra-task quota.')
for brief, task, worked, transfer, transfer_worked in [(briefs[0], case1_task, case1_worked, case1_transfer, case1_transfer_worked), (briefs[1], case2_task, case2_worked, case2_transfer, case2_transfer_worked)]:
    cases.append({'caseKey': brief['id'], 'goalId': GID, 'wholeUnchangedGoal': goal,
                  'learnerTask': task, 'authoredWorkedTaskResponse': worked, 'freshTransferTask': transfer,
                  'authoredWorkedFreshTransferResponse': transfer_worked, 'requiredAssessmentCriteria': rubric,
                  'sourceOperatorAndWholePartnerFrame': duty, 'suppliedObservationStatus': 'constructed teaching observations, not measured learner data',
                  'actualLearnerPerformance': False, 'actualExperimentPerformed': False, 'humanApproval': False})
materials = write('MV-metal-model-two-whole-bilingual-cases-worked-transfer.author-candidate.json', {
    'schemaVersion': 1, 'role': 'New targeted whole-goal source-bound metal-model author materials, no current P/native verdict',
    'goalId': GID, 'goalDescriptionChanged': False, 'wholeSourceDutyAndAllPartners': duty, 'cases': cases,
    'allSourceSpecificVoltageMobileElectronVibratingIonRequirementsMandatory': True,
    'actualExperimentPerformed': False, 'activeWrites': [], 'netStrictGain': 0, 'humanApproval': False})
candidate = {'schemaVersion': 1, 'authoringContract': 'positive-understanding-evidence-candidates-v1',
 'reviewId': 'chemie-b008-MV-metal-model-whole-source-bound-author-v3-20261009-v1',
 'reviewedAt': datetime.now(timezone.utc).isoformat(), 'reviewer': 'Codex author of targeted whole MV metal-model cases; independent review pending',
 'goals': [{'goalId': GID, 'reason': 'Whole unchanged metal-model goal with two heterogeneous own-model cases; MV voltage/electrons/vibrating ions explicitly compulsory. Author model materials, no real learner/experiment or current source/native approval.',
            'evidenceLevel': 'E1', 'maximumClaimScope': 'G1', 'dissent': ['Independent whole P-material/current native/source/context review remains pending; existing P bodies are preserved and not silently replaced.'], 'profile': profile}]}
binding = write('MV-metal-model.normal-whole-positive-candidate-set.author-v3.json', candidate)
write('MV-metal-model-one-unchanged-goal-two-source-bound-cases.neutral-review.entry.json', {
 'schemaVersion': 1, 'wholeUnchangedGoal': goal, 'sourceDutyWholePassageAndAllPartners': duty,
 'normalWholePositiveAuthorCandidateSet': binding, 'twoWholeBilingualWorkedAndTransferCases': materials,
 'rootCanonicalInput': bind(canonical_path), 'goalDescriptionAndRequiresImagesAllUnchanged': True,
 'actualSourceViewEntryIndex': 10, 'currentPositiveAndNativeReviewStatus': 'PENDING',
 'status': 'ai_candidate', 'evidenceLevel': 'E1', 'maximumClaimScope': 'G1', 'activeWrites': [],
 'netStrictGain': 0, 'humanApproval': False, 'humanTrial': False})
print(json.dumps({'candidateSet': binding, 'wholeCases': materials, 'profileCount': 1, 'cases': 2, 'wholeSourcePerformanceMandatory': True, 'goalTextChanges': 0, 'netStrictGain': 0}))
