# SPDX-License-Identifier: Apache-2.0
import json,hashlib,shutil,datetime,subprocess
from pathlib import Path
B=Path(__file__).resolve().parents[1];R=Path.cwd();rel=lambda p:p.relative_to(R).as_posix() if p.is_absolute() else p.as_posix()
def ref(p):
 p=Path(p);v=p.read_bytes();return {'path':rel(p),'sha256':'sha256:'+hashlib.sha256(v).hexdigest(),'bytes':len(v)}
def put(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
S=json.loads((B/'science/eight-whole-profiles-and-sixteen-cases.author.json').read_text());ids=[x['goalId'] for x in S['records']];now=datetime.datetime.now(datetime.timezone.utc).isoformat()
active=R/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_BIOLOGIE.de.json';assert ref(active)['sha256']=='sha256:e6660bb00510aa381e1aa18e264ee4e4d0073c36b740f3a0314dd4f8914f6453';shutil.copyfile(active,B/'inputs/whole479-current335-before-stoff8.exact.json')
kp=R/'curricula/DE/Gymnasium/quality/goal-book-publication/biologie.semantic-kinds.json';shutil.copyfile(kp,B/'inputs/whole479-current394-kinds.exact.json')
criteria=R/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-10/biologie-sek1-insect-eight-whole-material-author-candidate-v1/inputs/positive-criteria.exact.md';shutil.copyfile(criteria,B/'inputs/positive-criteria.exact.md')
(B/'positive').mkdir(exist_ok=True)
cs={'schemaVersion':1,'authoringContract':'positive-understanding-evidence-candidates-v1','reviewId':'biologie-stoffwechsel-eight-whole-material-author-candidate-v1','reviewedAt':now,'reviewer':'Codex scientific AUTHOR, not an independent reviewer','goals':[{'goalId':x['goalId'],'reason':'Own whole bilingual scientific author candidate with two full materials/tasks/solutions/rubrics and fresh transfer; realistic experimental planning and synthetic data. No actual learner, independent, source, course or Human approval. Current raster/native P rebind and independent reviews remain pending.','evidenceLevel':'E1','maximumClaimScope':'G1','dissent':['All50 current source witnesses reused without new whole-source review;25 legacy passage objects remain honestly null.','Author-created materials and raster inspections do not establish independent D/P/V approval or learner evidence.'],'profile':x['profile']} for x in S['records']]}
put(B/'positive/eight-scientific-P.candidate-set.json',cs)
c={'$schema':'https://skillpilot.com/schemas/goal-evidence/v2/goal-evidence-review-config.schema.json','schemaVersion':2,'reviewId':cs['reviewId'],'goalFingerprintRuleVersion':'goal-evidence-v1','profileRuleVersion':'positive-understanding-evidence-v2','landscapeId':json.loads(active.read_text())['landscapeId'],'landscapePath':rel(B/'inputs/whole479-current335-before-stoff8.exact.json'),'semanticKindLedgerPath':rel(B/'inputs/whole479-current394-kinds.exact.json'),'reviewCriteriaPath':rel(B/'inputs/positive-criteria.exact.md'),'reviewPath':rel(B/'positive/eight-before-raster.author.review.jsonl'),'reviewRunManifestPaths':[],'reviewedResourceTypes':[],'requireApproved':False,'scope':{'label':'Own AUTHOR whole-profile8 candidates on exact current335 before-raster base; no independent approval; native/current-raster rebind pending','goalIds':ids}}
put(B/'positive/eight-before-raster.author.config.json',c)
prov=json.loads((B/'assets/eight-actual-provider-provenance.json').read_text())['records'];v2=json.loads((B/'assets/two-actual-targeted-v2-provider-provenance.json').read_text())['records'];v3=json.loads((B/'assets/one-actual-targeted-v3-provider-provenance.json').read_text())['records'];selected=[]
notes={ids[0]:('Schematic adjacent onion/leaf cells, no onion chloroplasts; microscope objective above slide/illumination below.','Zwiebel/Blatt labels and both tissue patterns remain visible at360/680. Native is actually1672×940, near16:9; exact providerbytes retained.'),ids[1]:('Nahrung/Wasser/O₂ enter; CO₂, water/waste and heat leave. O₂ is not labelled fuel.','All five large labels and arrow directions visible at360/680; pictorial orientation, not quantitative exchange.'),ids[2]:('Finalv3 corrects actual original/v2 grammar; identical tube volumes,10/30/60°C and common timer. No plotted outcome.','Temperatures and experiment purpose legible at360; complete equality note legible at680. Some optional background text is small; no information needed for the orientation relies on it.'),ids[3]:('Finalv2 circle substrates complement round active-site notches; repeatedC copies identical; feedback arrow lands at distinct side regulatory site.','Forward and backward arrows/Enzym/Endprodukt/Rückkopplung readable at360/680; icons schematic, four copies not literal stoichiometry.'),ids[4]:('Yeast gas balloon versus lactic-product/pH illustration; no gas on homolactic side; no ATP misassignment.','Gärung/Hefe/CO₂/Milchsäure/pH core labels remain recognisable at360/680. Food-science orientation, no tasting shown; pH alone not specific lactate proof.'),ids[5]:('O₂ enters mitochondrial aerobic branch; CO₂/H₂O exit. Lactate branch cytosolic without mitochondrion.','Labels and directional comparison legible at360/680. Energy symbols qualitative, not3ATP versus2ATP or a scaled ATP graph; complete cases specify2 versus model30/32.'),ids[6]:('Equal1g portions explicitly17/37kJ; balancedmass beam. Rounded food energy differs from ATP-model values.','Both1g and17/37kJ large enough at360/680. Energy bars qualitative, not a calibrated numerical ratio; labels carry exact values.'),ids[7]:('Cooling/separation/cleaning shown; magnified schematic microbes remain in cool inset, transfer/division modelled. No normal-looking-food safety stamp.','Three large core actions legible at360/680; long optional explanation readable chiefly at680/original. Microbe glyphs are schematic/magnified, not visible pathogens or measured burden.')}
for gid in ids:
 original=next(x for x in prov if x['id']==gid);chosen=next((x for x in v3 if x['goalId']==gid),next((x for x in v2 if x['goalId']==gid and gid==ids[3]),None)) or original
 path=Path(chosen['nativePath']);selected.append({'goalId':gid,'actualCurrentPNG':ref(path),'nativeDimensions':chosen['nativeDimensions'],'actualProportionalViews':[ref(Path(x['path'])) for x in chosen['inspectionDerivatives']],'actualProvider':'image_gen.imagegen','actualProviderProvenance':ref(B/'assets/one-actual-targeted-v3-provider-provenance.json') if gid==ids[2] else ref(B/'assets/two-actual-targeted-v2-provider-provenance.json') if gid==ids[3] else ref(B/'assets/eight-actual-provider-provenance.json'),'actualPrompt':ref(B/'prompts'/f'{gid}.v3.actual-provider-edit-prompt.txt') if gid==ids[2] else ref(B/'prompts'/f'{gid}.v2.actual-provider-edit-prompt.txt') if gid==ids[3] else ref(B/'prompts'/f'{gid}.actual-provider-prompt.txt'),'authorActualOriginal360680Viewed':True,'authorObservation':notes[gid][0],'formatAndSmallViewObservation':notes[gid][1],'independentReviewDecision':None,'authorCandidateReadyForIndependentReview':True,'humanApproval':False})
put(B/'assets/eight-current-selected-raster-author.index.json',{'schemaVersion':1,'role':'Neutral current raster selection, AUTHOR inspection only; independent judgments pending','goalIds':ids,'records':selected,'selectedCurrentViews':24,'totalAuthorActualViewsIncludingHistoricalVariants':33,'originalEightViews':24,'targetedSuccessorViews':9,'currentNativeDimensionsActual':{'1672x941':7,'1672x940':1},'historicalOriginalAndFailedEditFilesPreserved':True,'independentApproval':False,'humanApproval':False})
put(B/'checks/whole-profile-and-raster-author-readiness.actual.json',{'schemaVersion':1,'role':'Author completeness checkpoint, no independent review','wholeProfiles':8,'wholeBilingualCases':16,'allCasesHaveMaterialsTasksWorkedSolutionsRubricsFreshTransferSolutionAndLimits':True,'allDataClearlySynthetic':True,'experimentPlanningEnzymeAndBothFermentationPathsExplicit':True,'allCurrentRastersOriginal360680ActuallyViewed':True,'totalActualAuthorViews':33,'genuineTargetedCorrections':['Enzyme-note grammar finalv3 corrected after actualv2 failure','Regulatory substrate/intermediate/end-product shape consistency finalv2 corrected'],'whole50SourceWitnessesAnd25NullablePassagesExact':True,'humanApproval':False,'strictNet':0,'activeWrites':False,'pending':['WholeNative8HTML/PDF and current-raster P8 technical rebind','Actual independentD/P/V A/B','Any active adoption/QA/M7 increase']})
put(B/'checks/actual-inventory-and-reuse-boundaries.json',{'schemaVersion':1,'role':'Author prior valid work inventory; do not restart existing approved scope','goalIds':ids,'actualInventoryQueries':['Targeted84 existing science/full-profile/full-case JSON files by all8IDs:0 matches','Current49 P-config scope intersections beforeInsect8 adoption:0 matches; no Stoff8 target added by Insect8','Target-ID-containing131 JSONL files parsed for exactgoalId plus fullprofile/cases:0 complete matches','ID-named rasterfiles acrosscurricula/appPublic:0; neutral canonical/public existence8false'],'validWholeProfilesToReuse':0,'validWholeCasesToReuse':0,'validCurrentRastersToReuse':0,'authoredMissingWholeProfiles':8,'authoredMissingWholeCases':16,'existingAM394ReusedUnchanged':True,'all50CurrentSourceWitnessesReusedUnchanged':True,'newWholeSourceCourseApproval':False,'activeWrites':False})
print('Prepared neutral selectedRaster8, actualAuthorViews33, current335snapshot, normal P8 candidate/config')
