# SPDX-License-Identifier: Apache-2.0
from pathlib import Path
import json,hashlib,datetime,copy
out=Path(__file__).resolve().parent; repo=Path.cwd(); au=out.parent/'biologie-ni-ten-source-hold-remediation-candidate-v1'
read=lambda p:json.loads(p.read_text())
def emit(name,data):(out/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
templates=read(au/'nine-missing-performance.DEEN.goal-templates.candidate.json')['goalTemplates']+read(au/'four-prior-templates.referenced.candidate.json')['goalTemplatesCopiedWithoutSemanticChange']
why={
'order_given_criteria':('A single given-rule ordering operation, with groups and sequences as alternative outcomes. The EG1 grade5/6 clause does not require independent criterion invention. Task material supplies traits and criteria, while the actual assignments must be new learner work.','Applying supplied criteria does not require a new fixed recall set.'),
'distinguish_organism_population':('The EG2 grade9/10 table distinguishes exactly two units of reference. Identifying the unit in a new statement is one assessable discrimination, with location/time/species defining the population. Multiple measurements from one organism remain one organism.','The unit distinction is applied to observations; a separate definition card adds no necessary compact recall demand.'),
'sexual_reproduction_variability_advantage':('FW7 grade9/10 asks for an explanation of sexual versus asexual reproduction along one explicit dimension, variability. Existing two recombination atoms provide the chromosomal models. The explanation remains causal and conditional, without claiming guaranteed advantage or no clonal mutations.','The comparison follows from the models and reasoning; a new memorised strategy list is unnecessary.'),
'selected_native_tree_species_knowledge':('FW7 grade5/6 explicitly permits a selected organism group. Four native deciduous species form one bounded recognition repertoire; species name and identifying traits constitute one recognition performance. A new unlabelled specimen must carry the recognition assessment. Local occurrence is not silently claimed.','A finite set of four species names with compact distinguishing traits must be retrievable without a supplied answer list. Four candidate cards are narrow and relevant; the oak prompt needs correction.'),
'breeding_selection_variants':('FW7 grade5/6 requires explaining breeding through suitable variants. Repeated selection of parents with heritable traits is one coherent process. The new example requires an actual choice; selection neither creates need-directed variants nor guarantees identical offspring.','The procedure is explained and applied; no fixed breeding or domestication catalogue is demanded.'),
'individual_adjustment_heritable_adaptation':('FW7 grade9/10 contrasts inherited adaptation with non-inherited adjustment. Heritability, lifetime/generations and organism/population are decision criteria of one contrast. Given evidence supports a new decision without providing it. The epigenetic boundary avoids an invalid universal claim.','The contrast requires reasoned application to new cases, not separate compulsory terminology cards.'),
'family_similarity_kinship_indication':('FW8 grade5/6 asks for interpretation as an indication. Observation plus a limited causal interpretation is one competence, with chance/environment and non-biological family forms handled honestly. Fictional material avoids private family enquiries.','No fixed trait or kinship vocabulary list must be recalled; the observations are supplied.'),
'domestic_wild_common_ancestors':('FW8 grade5/6 requires common ancestry as the explanation of observed similarities. Present relatives are not misrepresented as the literal direct ancestors of every individual. Checked descent material can be supplied without supplying the causal explanation.','No compulsory list of domestication ancestors is proposed; the causal inference is learner work.'),
'five_vertebrate_groups_traits':('The full FW8 grade5/6 clause explicitly names all five groups and common traits. One bounded comparative body-trait scheme is a coherent content goal, assessable in a single comparative task. Separate physiology, phylogenetics and species catalogues are excluded. Traditional school groups are not incorrectly claimed to be five equivalent clades.','The operator nennen requires the compact traits for the entire scheme to be available. Five group-specific cards plus one shared-trait card are justified; real origins and view visibility remain unbound.'),
'morphological_hierarchical_classification':('FW8 grade7/8 requires actual hierarchical placement from morphology/anatomy. The hierarchy convention may be shown; a new placement and its trait justification must be supplied by the learner. This is distinct from an arbitrary flat grouping and from molecular phylogeny.','Levels and trait findings may be supplied; the essential performance is applying the hierarchy, not recalling an added taxon list.'),
'simple_reproductive_species_concept':('FW7 grade9/10 specifies the simple reproductive-community criterion. The candidate applies it to suitable sexual-reproduction examples using actual reproduction/fertility evidence, without claiming to solve all species concepts.','A taught criterion can be applied with source material; an additional definition deck is not necessary for this narrow discrimination.'),
'non_molecular_mutation_recombination_variability':('FW7 grade9/10 explicitly requires mutation without molecular genetics and recombination. Their contrasting effects on within-species differences are one causal comparison. Actual chromosomal gene/product/trait and recombination prerequisites support it; no DNA mechanism is smuggled in.','Mutation versus recombination must be explained from the models; a new molecular glossary would exceed the clause.'),
'non_molecular_evolutionary_interplay':('The two FW7 grade9/10 clauses jointly require causal population adaptation and the interplay of mutation, recombination and selection. A single through-going explanation links existing variability to differential reproduction and changed frequencies. Selection is not a generator of new variants; survival alone is insufficient.','The linked explanation follows a supplied population example; a separate list of evolutionary terms is unnecessary.')}
review=[]
for t in templates:
 key=t['candidateKey']; a,m=why[key]; mem='memory_required' if key in ['selected_native_tree_species_knowledge','five_vertebrate_groups_traits'] else 'no_memory_needed'
 review.append({'candidateKey':key,'stableGoalId':None,'descriptionDE':t['description'],'descriptionEN':t['descriptionEn'],'sourceVerdict':'PASS_candidate_scope','sourceClauseIds':t.get('sourceGoalIds',[]),'sourceGradeBand':t['gradeBand'],'operatorAndAtomicityRationale':a,'atomicityVerdict':'atomic','semanticAtomic':True,'memoryVerdict':mem,'memoryRationale':m,'introducedModelsDoNotSupplyAssessedSolution':True,'authoritativeLedgerDecisionCreated':False,'nativeFinalBookDReviewed':False,'PReviewed':False,'humanApproval':False})
emit('thirteen-ordinary-source-A-M.independent.json',{'role':'independent_source_semantic_atomicity_memory_candidate_review','inputTemplateFiles':[{'path':str(p.relative_to(repo)),'sha256':sha(p)} for p in [au/'nine-missing-performance.DEEN.goal-templates.candidate.json',au/'four-prior-templates.referenced.candidate.json']],'goals':review,'counts':{'ordinary':13,'atomic':13,'memory_required':2,'no_memory_needed':11},'adoptionHolds':['Stable IDs, final placements and actual inherited runtime context','Two native final-book description reviews and resolved findings','Current authoritative A/M fingerprints','Real memory origin/memory IDs, primary-card reviews and same-view visibility','Current P and V and central strict integration']})
# Actual original blocker, with exact proposed corrected inactive text. No author source rewrite.
family=read(au/'existing-440-family-pedigree.full-clause-context.candidate.json')
fixed=copy.deepcopy(family)
fixed['role']='independent_reviewer_correction_candidate';fixed['status']='inactive_corrected_context_pending_author_resolution_and_native_D'
fixed['positiveCompetence'][0]='In einem Familienstammbaum die Folgen von Diploidie erläutern: Im einfachen autosomalen Ein-Merkmal-Modell besitzt eine diploide Zelle zwei Kopien des betrachteten Gens beziehungsweise zwei Allele, eines von jedem Elternteil. Die Allele können gleich oder verschieden sein. Ein rezessives Merkmal kann bei Eltern mit unauffälligem Phänotyp verdeckt vorliegen und bei einem Kind sichtbar werden.'
fixed['positiveCompetenceEn'][0]='Explain the consequences of diploidy within a family pedigree: in the simple autosomal one-trait model a diploid cell has two copies of the gene being considered, or two alleles, one inherited from each parent. The alleles may be identical or different. Parents with an unaffected phenotype may carry a recessive allele that becomes visible in a child.'
fixed['positiveCompetence'][1]='Die Folgen der Neukombination elterlicher Erbinformation erläutern: Bei Keimzellbildung wird für dieses Merkmal eines der beiden Allele weitergegeben; bei Befruchtung können unterschiedliche elterliche Allelkombinationen entstehen. Deshalb können Geschwister im Familienstammbaum unterschiedliche Merkmalsausprägungen haben.'
fixed['positiveCompetenceEn'][1]='Explain the consequences of new combinations of parental genetic information: gamete formation transmits one of the two alleles for this trait; fertilisation can create different combinations of parental alleles. Siblings in the pedigree may therefore express the trait differently.'
emit('existing-440.full-clause-context.corrected.inactive.candidate.json',fixed)
emit('existing-440.source-A-M.independent.json',{'goalId':family['goalId'],'inputPath':str((au/'existing-440-family-pedigree.full-clause-context.candidate.json').relative_to(repo)),'inputSHA256':sha(au/'existing-440-family-pedigree.full-clause-context.candidate.json'),'sourceClause':family['sourceBinding']['sourceGoalId'],'sourceScope':'NI FW6 grade9/10 physical/printed page87; chromosomal simplified model, not DNA/protein mechanism','originalCandidateVerdict':'HOLD','finding':'Two inherited variants implies two distinct variants; diploidy guarantees two homologous copies at an autosomal locus, not heterozygosity. Homozygous AA and aa must remain possible.','correctionFile':'existing-440.full-clause-context.corrected.inactive.candidate.json','correctedProposalScopeVerdict':'PASS_candidate_scope_pending_author_resolution','atomicityVerdict':'atomic','atomicityRationale':'Plausible monohybrid pedigree interpretation, explanatory genotype assignment and limits constitute one evidence-based interpretation. The consequences of two-copy inheritance/new parental combinations justify that interpretation; cytological crossing-over and independent assortment remain separate pre-existing atoms.','memoryVerdict':'no_memory_needed','memoryRationale':'Applying possible genotype combinations to an unfamiliar pedigree does not require a new fixed disease, chromosome-count or term deck.','prerequisiteProposal':'PASS_candidate_scope: DNA prerequisite replaced by actual b8fc simple inheritance; native transitive meiosis/cell context retained. All global monohybrid/autosomal/gonosomal/dominant/recessive scope remains unchanged.','limits':['A monohybrid pedigree does not prove independent assortment of multiple loci or crossing-over.','The corrected copy is reviewer-authored remediation and is not a completed native D review.','Gonosomal alternatives must have correct supplied notation and be assessed within the retained global scope.'],'humanApproval':False})
# Per-card factual and necessity review; exact answer leak corrected only in new copy.
facts={
'beech':('https://www.floraweb.de/php/artenhome.php?suchnr=2357','BfN FloraWeb Fagus sylvatica: oval slightly wavy-edged leaves, smooth pale-grey bark and long pointed buds support the compact identification combination.'),
'oak':('https://www.floraweb.de/php/artenhome.php?suchnr=4685','BfN FloraWeb Quercus robur: deeply lobed leaves with a 2–7 mm stalk and acorns support recognition within the selected four-species group.'),
'birch':('https://www.floraweb.de/php/artenhome.php?name-use-id=829','BfN FloraWeb Betula pendula: triangular/diamond leaves with double serration and white peeling bark becoming dark/fissured with age support the card.'),
'maple':('https://www.wald.rlp.de/wald/baeume-unserer-waelder/bergahorn','Landesforsten Rheinland-Pfalz Acer pseudoplatanus: opposite usually five-lobed coarsely toothed leaves and paired winged fruit support the combination.'),
'shared':('https://openstax.org/books/biology-2e/pages/29-1-chordates','The vertebral column and internal skeleton support the shared-trait claim for the explicitly typical representatives; the card does not generalise to all chordates.'),
'mammals':('https://openstax.org/books/biology-2e/pages/29-6-mammals','Hair and mammary glands/milk distinguish mammals. Monotremes prevent an incorrect universal live-birth rule.'),
'birds':('https://openstax.org/books/biology-2e/pages/29-5-birds','Feathers distinguish the living bird representatives; flight is not an adequate universal criterion.'),
'reptiles':('https://openstax.org/books/biology-2e/pages/29-4-reptiles','Keratinised skin/scales and lung breathing support the traditional school-reptile combination; birds are explicitly excluded only for this school grouping.'),
'amphibians':('https://openstax.org/books/biology-2e/pages/29-3-amphibians','Moist permeable skin and cutaneous gas exchange support the card. Lungless salamanders and larval gills justify the life-stage/species boundary.'),
'fishes':('https://openstax.org/books/biology-2e/pages/29-2-fishes','Typical fishes use gills and fins. The card does not impose scales on every fish; retained cartilage/bone variation is compatible with the shared card.')}
cardReviews=[];fixedDecks=[]
for name in ['native_tree_species','vertebrate_groups']:
 ds=[]
 for lang in ['de','en']:
  d=read(au/f'memory-deck.de_gymnasium_biology_{name}.{lang}.inactive.candidate.json');ds.append(d)
 assert [c['id'] for c in ds[0]['cards']]==[c['id'] for c in ds[1]['cards']]
 for card in ds[0]['cards']:
  suffix=card['id'].rsplit('_',1)[1];url,reason=facts[suffix];isOak=suffix=='oak'
  cardReviews.append({'cardId':card['id'],'deckId':ds[0]['deckId'],'DEENFactualVerdict':'PASS','primaryURL':url,'primaryContentIndependentlyRead':True,'sourceParaphrase':reason,'necessary':True,'necessityRationale':'One compact species identification item in the bounded four-species ordinary goal.' if name=='native_tree_species' else 'One of the explicitly required five-group distinctions or their shared trait; no requested group is omitted.','originalRecallVerdict':'HOLD_answer_leak' if isOak else 'PASS_candidate_card_content','originalDecision':'revise' if isOak else 'kept_candidate_only','originGoalId':None,'memoryGoalId':None,'authoritativeCardLedgerVerdict':'HOLD_missing_current_origin_memory_ids_and_visibility','humanApproval':False})
 for d,lang in zip(ds,['de','en']):
  d['status']='inactive_independently_reviewed_card_content_with_oak_correction_pending_ID_binding'
  if name=='native_tree_species':
   card=next(x for x in d['cards'] if x['id']=='biology_native_tree_species_oak')
   card['front']='Welche Baumart unserer ausgewählten Vierergruppe passt zu diesen Merkmalen? Gelappte Blätter mit sehr kurzem Blattstiel und Eicheln.' if lang=='de' else 'Which tree species in our selected group of four matches these traits? Lobed leaves with a very short leaf stalk and acorns.'
  fn=f'memory-deck.de_gymnasium_biology_{name}.{lang}.corrected.inactive.candidate.json';emit(fn,d);fixedDecks.append(fn)
emit('ten-cards-DEEN-content-and-origin.independent.json',{'role':'independent_candidate_card_reviewer','cards':cardReviews,'contentCounts':{'factualPass':10,'originalPromptPass':9,'originalPromptHold':1,'correctedPromptCandidatePass':10},'correctedInactiveDeckFiles':fixedDecks,'activeCardsApproved':0,'adoptionHolds':['Stable current ordinary origin IDs with memory_required decision and this exact deck','Stable current memoryGoalIds with correct deck tags','Actual cards.review.jsonl bindings for exact kept primary card bytes','Actual compiled same-view visibility in every affected configured scope'],'PContentsRead':False})
# Binding all16 primary table clauses is a source review, never a completed D gate.
routes=[]
for route in read(au/'sixteen-full-clause-routes.candidate.json')['routes']:
 s=route['sourceBinding'];isFamily=bool(route['familyContextReference'])
 routes.append({'sourceGoalId':route['sourceGoalId'],'physicalPage':s['physicalPage'],'printedPage':s['printedPage'],'gradeBand':s['gradeBand'],'stage':s['stage'],'sourceLiteral':s['literalPrimaryClause'],'fullClauseReviewed':True,'originalCandidateVerdict':'HOLD_context_two_copy_wording' if isFamily else 'PASS_candidate_source_route','correctedCandidateScopeVerdict':'PASS_candidate_source_route_pending_adoption','canonicalGoalIds':route['canonicalGoalIdsAfterProposed'],'candidateKeys':route['candidateKeysAfterProposed'],'noExtraMolecularObligationInNISekI':True,'keyMaterialRequired':route.get('keyContextRequirement'),'reviewerCorrectionFile':'existing-440.full-clause-context.corrected.inactive.candidate.json' if isFamily else None,'literalVerifiedAgainstActualRetainedPDF':True,'tableColumnVisuallyChecked':True,'currentSourceMappingApproved':False})
emit('sixteen-source-routes.independent.json',{'role':'independent_source_candidate_reviewer','sourcePDFSHA256':sha(repo/'curricula/DE/Gymnasium/input/NI/lower-secondary/kc_naturwissenschaften_gymnasium_sek_i_2015.pdf'),'routes':routes,'counts':{'clauses':16,'originalCandidateSourcePASS':15,'originalCandidateSourceHOLD':1,'correctedInactiveScopePASS':16},'operatorContext':'Actual NI operator table physical/printed pages103–104: deuten links to an explanatory context; erklären asks a causal/rule relation; erläutern makes a fact understandable with additional information; nennen asks direct naming. Materials must not supply the assessed relation/decision.','currentMappingCoverageApproved':False})
globalFix=read(au/'global-9f.DEEN-scientific-fix-and-source-correction.candidate.json')
emit('global-9f.HE-scientific-source-A-M.independent.json',{'goalId':globalFix['goalId'],'inputSHA256':sha(au/'global-9f.DEEN-scientific-fix-and-source-correction.candidate.json'),'scientificCorrectionVerdict':'PASS_candidate','scientificRationale':'The proposed DEEN body correctly separates mutation creating variants, recombination rearranging existing information, and selection changing heritable-variant frequency through differential reproduction. It removes the false attribution of variant generation to selection.','atomicityVerdict':'atomic','atomicityRationale':'Generation/recombination and frequency change are linked functions within one causal population explanation, rather than three unrelated memorised routines.','memoryVerdict':'no_memory_needed','memoryRationale':'The causal distinction is explained in a new example; no additional fixed molecular term or formula deck is necessary.','HEPrimaryFindings':[{'physicalPage':36,'printedPage':36,'actualHeading':'Q1.1 Speicherung und Realisierung genetischer Information','candidateHeadingIncorrect':'Q1.1 Von der DNA zum Protein','clauseScope':'Rekombination and Mutation; selection is not in this Q1 bullet.','literalSameAsCandidate':True,'matchConsequence':'The Q1 bullet is a partial contribution to the wider corrected canonical goal; it cannot be labelled exact for selection.'},{'physicalPage':40,'printedPage':40,'actualHeading':'Q2.1 Entstehung und Entwicklung des Lebens','candidateHeadingIncorrect':'Q2.1 Evolutionsgedanken','clauseScope':'The larger Q2 bullet includes selection plus nine further concepts; those additional obligations must retain their own valid goal routes.','literalSameAsCandidate':True,'matchConsequence':'Only the selection contribution to9f is justified here; not full coverage of the wider Q2 bullet.'},{'physicalPage':21,'printedPage':21,'actualHeading':'Basiskonzept Entwicklung','clauseScope':'Supporting conceptual context connecting sexual reproduction/recombination/variation with selection and species change; not a replacement literal Q1 selection obligation.'}],'sourceHeadingCorrectionRequired':True,'HEExtractionFalseLiteralMustBeSupersededNotEditedHistorically':True,'nativeGlobalMolecularRequiresMustRemain':True,'NISekIRouteReuseVerdict':'HOLD_unsuitable_global_molecular_prerequisites; retain new nonmolecular atom','allRegionalSourceBindingsApproved':False,'globalAdoptionVerdict':'HOLD_other_current_regional_sources_and_D_A_M_P_context_bindings_unreviewed','currentSourceMappingApproved':False,'humanApproval':False})
emit('independence-and-scoped-inputs.receipt.json',{'createdAtUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'role':'independent_candidate_source_atomicity_memory_reviewer','previouslySeen':['Parent assignment and thread summary mention earlier NI source findings and candidate inventory.','Current candidate README and author data were read as task input.','No other reviewers current substantive output or P profile content was read in this review.'],'blindReview':False,'independence':'Separate current reasoning from original retained primary PDFs, actual native graph and independently fetched factual primary pages. This is not the author agent and is not a second final-book D instance.','memoryGuidanceUsed':'MEMORY.md lines296 and302: preserve good images and strict current machine gates; no stale maturity counts used.','authorFrozenInputFiles':[{'path':str(p.relative_to(repo)),'sha256':sha(p)} for p in sorted(au.rglob('*')) if p.is_file() and p.suffix not in ['.html','.pdf']], 'activeAuthoritativeArtifactsWritten':0,'M7StrictClosureDelta':0,'restoredStrictBindings':0,'humanApproval':False})
print(json.dumps({'ordinaryReviewed':13,'clausesReviewed':16,'cardsReviewedDEEN':10,'originalCandidateConcreteHolds':['440_two_copies_not_two_distinct_variants','oak_card_answer_on_front','HE_real_Q1_Q2_heading_metadata'],'globalRegionalAdoptionHold':True,'strictDelta':0}))
