import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import {
  type GeneratedMarkdownNoticeConfig,
  loadGeneratedMarkdownNoticeConfigs,
  repoRoot,
} from './generatedMarkdownNoticeRegistry'

function checkGeneratedMarkdownNotice(config: GeneratedMarkdownNoticeConfig): string[] {
  const text = readFileSync(resolve(repoRoot, config.path), 'utf8')
  const lines = text.split(/\r?\n/)
  const header = lines.slice(0, 16)
  const failures: string[] = []

  if (!lines[0]?.startsWith('# ')) {
    failures.push(`${config.path}: first line must be a Markdown H1 title`)
  }
  if (lines[1] !== '') {
    failures.push(`${config.path}: generated notice must follow the title after one blank line`)
  }

  const requiredLines = [
    '> Generated artifact. Do not edit manually.',
    '>',
    `> Generated by: \`${config.generatedBy}\``,
    `> Regenerate with: \`${config.regenerateWith}\``,
    ...config.sourceOfTruth.map((source) => `> Source of truth: \`${source}\``),
  ]

  requiredLines.forEach((line) => {
    if (!header.includes(line)) {
      failures.push(`${config.path}: missing generated notice line: ${line}`)
    }
  })

  const generatedLineIndex = lines.findIndex((line) => line.startsWith('Generated: '))
  const noticeLineIndex = lines.indexOf('> Generated artifact. Do not edit manually.')
  if (generatedLineIndex >= 0 && noticeLineIndex >= 0 && generatedLineIndex < noticeLineIndex) {
    failures.push(`${config.path}: generated notice must appear before the Generated timestamp`)
  }

  return failures
}

const generatedMarkdownFiles = loadGeneratedMarkdownNoticeConfigs()

const failures = generatedMarkdownFiles.flatMap(checkGeneratedMarkdownNotice)

if (failures.length > 0) {
  console.error(failures.join('\n'))
  process.exit(1)
}

console.log(`Generated Markdown notice check passed for ${generatedMarkdownFiles.length} files.`)
