import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, dirname, relative, resolve, sep } from 'node:path'
import {
  generatedStatusRegistryReadmeNoticeConfig,
  loadGeneratedMarkdownNoticeConfigs,
  loadGeneratedStatusRegistryRows,
  repoRoot,
} from './generatedMarkdownNoticeRegistry'

const outputPath = resolve(repoRoot, generatedStatusRegistryReadmeNoticeConfig.path)
const statusDir = resolve(repoRoot, 'docs/qa-ci/status')
const docsRoot = resolve(repoRoot, 'docs')
const checkMode = process.argv.includes('--check')

// Artifacts outside `docs/` are not part of the published MkDocs site, so a
// relative link to them 404s there. Link those through GitHub instead.
const repoBlobPrefix = 'https://github.com/enpasos/skillpilot/blob/main/'

function toPosixPath(path: string): string {
  return path.split(sep).join('/')
}

function isInsideDocs(absolutePath: string): boolean {
  const relativePath = relative(docsRoot, absolutePath)
  return relativePath.length > 0 && !relativePath.startsWith('..')
}

function markdownLink(targetPath: string): string {
  const absolute = resolve(repoRoot, targetPath)
  const target = isInsideDocs(absolute)
    ? toPosixPath(relative(dirname(outputPath), absolute))
    : `${repoBlobPrefix}${encodeURI(toPosixPath(relative(repoRoot, absolute)))}`
  return `[${basename(targetPath)}](${target})`
}

function joinHumanReadable(items: string[]): string {
  if (items.length === 0) return ''
  if (items.length === 1) return items[0]
  if (items.length === 2) return `${items[0]} and ${items[1]}`
  return `${items.slice(0, -1).join(', ')}, and ${items[items.length - 1]}`
}

function formatArtifactLinks(artifactPaths: string[]): string {
  return joinHumanReadable(artifactPaths.map(markdownLink))
}

function formatCodeItems(items: string[]): string {
  return items.map((item) => `\`${item}\``).join(', ')
}

function listStatusMarkdownPaths(): string[] {
  return readdirSync(statusDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
    .map((entry) => `docs/qa-ci/status/${entry.name}`)
    .sort((left, right) => left.localeCompare(right, 'en'))
}

function checkRegisteredArtifacts(): string[] {
  const rows = loadGeneratedStatusRegistryRows()
  const registeredArtifacts = [
    generatedStatusRegistryReadmeNoticeConfig.path,
    ...rows.flatMap((row) => row.artifactPaths),
  ]
  const actualMarkdown = new Set(listStatusMarkdownPaths())
  const registeredMarkdown = new Set(
    loadGeneratedMarkdownNoticeConfigs()
      .map((config) => config.path)
      .filter((path) => path.startsWith('docs/qa-ci/status/') && path.endsWith('.md')),
  )
  const failures: string[] = []

  registeredArtifacts.forEach((artifactPath) => {
    if (!existsSync(resolve(repoRoot, artifactPath))) {
      failures.push(`registered generated status artifact does not exist: ${artifactPath}`)
    }
  })

  Array.from(actualMarkdown).forEach((markdownPath) => {
    if (!registeredMarkdown.has(markdownPath)) {
      failures.push(`unregistered Markdown status artifact: ${markdownPath}`)
    }
  })

  Array.from(registeredMarkdown)
    .sort((left, right) => left.localeCompare(right, 'en'))
    .forEach((markdownPath) => {
      if (!actualMarkdown.has(markdownPath)) {
        failures.push(`registered Markdown status artifact does not exist: ${markdownPath}`)
      }
    })

  return failures
}

function renderGeneratedNotice(): string {
  return [
    '> Generated artifact. Do not edit manually.',
    '>',
    `> Generated by: \`${generatedStatusRegistryReadmeNoticeConfig.generatedBy}\``,
    `> Regenerate with: \`${generatedStatusRegistryReadmeNoticeConfig.regenerateWith}\``,
    ...generatedStatusRegistryReadmeNoticeConfig.sourceOfTruth.map((source) => `> Source of truth: \`${source}\``),
  ].join('\n')
}

function renderRegistry(): string {
  const rows = loadGeneratedStatusRegistryRows()
    .map((row) => [
      formatArtifactLinks(row.artifactPaths),
      row.role,
      formatCodeItems(row.sourceOfTruth),
      `\`${row.regenerateWith}\``,
    ])

  const tableRows = rows.map((row) => `| ${row.join(' | ')} |`)

  return `${[
    '# Generated QA Status Artifacts',
    '',
    renderGeneratedNotice(),
    '',
    'This directory contains generated QA reports, queues, and dashboard snapshots. Treat these files as runtime evidence, not as the decision source. If a report looks wrong, update the owning script, config, ledger, mapping, or curriculum data and regenerate it.',
    '',
    '## Rules',
    '',
    '- Do not edit generated Markdown, JSON, or report output manually.',
    '- Each generated Markdown file must start with the generated-artifact notice checked by `cd app && npm run check:generated-doc-notices`.',
    '- JSON companions are machine-readable outputs for tools and dashboards; Markdown companions are human-readable views of the same lane.',
    '- When adding a new generated status file, add it to `app/scripts/generatedMarkdownNoticeRegistry.ts`. For Markdown outputs, the same entry feeds the notice check.',
    '- Every Markdown file directly under this directory must be registered in `app/scripts/generatedMarkdownNoticeRegistry.ts`.',
    '',
    '## Artifact Registry',
    '',
    '| Artifact | Role | Source of truth | Regenerate |',
    '| --- | --- | --- | --- |',
    ...tableRows,
    '',
    '## Validation',
    '',
    'Use these checks after changing generated status docs, their notices, or this registry:',
    '',
    '```bash',
    'cd app',
    'npm run check:generated-doc-notices',
    'npm run check:generated-status-registry',
    'npm run check:docs-links',
    '```',
    '',
    '```bash',
    'git diff --check',
    '```',
    '',
    'For generated reports that also emit JSON, parse the JSON companion before relying on it in another report or dashboard.',
  ].join('\n')}\n`
}

const rendered = renderRegistry()

if (checkMode) {
  const failures = checkRegisteredArtifacts()
  const current = readFileSync(outputPath, 'utf8')
  if (current !== rendered) {
    failures.push(`${generatedStatusRegistryReadmeNoticeConfig.path} is stale. Regenerate it with: ${generatedStatusRegistryReadmeNoticeConfig.regenerateWith}`)
  }
  if (failures.length > 0) {
    console.error(failures.join('\n'))
    process.exit(1)
  }
  console.log(`${generatedStatusRegistryReadmeNoticeConfig.path} is up to date.`)
} else {
  writeFileSync(outputPath, rendered)
  console.log(`Wrote ${generatedStatusRegistryReadmeNoticeConfig.path}`)
}
