// SPDX-License-Identifier: Apache-2.0
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import assert from 'node:assert/strict'
import Ajv2020 from '../../../../../../../app/node_modules/ajv/dist/2020.js'
import addFormats from '../../../../../../../app/node_modules/ajv-formats/dist/index.js'
import { buildGoalBookModel, fingerprintSemanticKindSourceGoal } from '../../../../../../../app/scripts/goalBookModel'
import { buildGoalDescriptionRolloutSubsetModel } from '../../../../../../../app/scripts/materializeGoalDescriptionRolloutBatch'
import { writeGoalBookHtml, writeGoalBookPdf, writeGoalBookRenderManifest } from '../../../../../../../app/scripts/goalBookRenderer'
import { buildGoalBookReviewBundle } from '../../../../../../../app/scripts/exportGoalBookReviewBundle'
import { buildGoalDescriptionReviewInput, buildGoalDescriptionReviewCampaign, serializeGoalDescriptionReviewBatchInput, loadGoalDescriptionReviewRecordSchemaBytes, validateGoalDescriptionReviewCampaign, GOAL_DESCRIPTION_REVIEW_RECORD_SCHEMA_ARTIFACT_PATH } from '../../../../../../../app/scripts/validateGoalDescriptionReviewCampaign'
import { verifyGoalBookReviewBundleArtifactBytes, writeVerifiedGoalDescriptionReviewCampaignGuidanceArtifacts } from '../../../../../../../app/scripts/createGoalDescriptionReviewCampaign'
import { fingerprintGoalForPositiveEvidence, fingerprintPositiveGoalEvidenceProfile, fingerprintPositiveGoalEvidenceReviewInput, validatePositiveGoalEvidenceRecordSemantics, POSITIVE_GOAL_EVIDENCE_SCHEMA_URL } from '../../../../../../../app/scripts/positiveGoalEvidenceProfileModel'

const root=resolve('.'), own=resolve('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-07/chemie-b007-b014-nine-current479-bounded-native-author-20261007-v1')
if(existsSync(resolve(own,'author.final.freeze.json')))throw new Error('Sealed author output')
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),sha=(b:Buffer|string)=>'sha256:'+createHash('sha256').update(b).digest('hex')
const bind=(p:string)=>{const b=readFileSync(p);return{path:relative(root,p),sha256:sha(b),bytes:b.length}}
const write=(p:string,v:any)=>{mkdirSync(dirname(p),{recursive:true});writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n')}
const selection=read(resolve(own,'nine-current-goals-and-four-bounded-candidates.author.raw.json')),ids=selection.reviewReadyGoalIds as string[],canonicalPath=resolve(own,'candidate/canonical.current479-four-bounded-proposals.json'),canonical=read(canonicalPath),by=new Map<string,any>(canonical.goals.map((g:any)=>[g.id,g]))
const kind=read(resolve(own,'candidate/semantic-kinds.original-input.json')),oldKind=structuredClone(kind)
kind.sourceLandscapePath=relative(root,canonicalPath)
const kindChanges=[]
for(const decision of kind.decisions){const goal=by.get(decision.goalId),current=fingerprintSemanticKindSourceGoal(goal);if(decision.sourceFingerprint!==current){assert.ok(ids.includes(goal.id));kindChanges.push({goalId:goal.id,before:decision.sourceFingerprint,after:current,classificationUnchanged:true,authorTechnicalBindingOnly:true});decision.sourceFingerprint=current}}
write(resolve(own,'candidate/semantic-kinds.four-targets.inert-input.json'),kind)
write(resolve(own,'native/kind-four-technical-input-deltas.json'),{role:'Four changed input fingerprints only; existing classification unchanged, no scientific review or active writes',changes:kindChanges,other475RowsExact:oldKind.decisions.filter((d:any)=>!ids.includes(d.goalId)).every((d:any)=>JSON.stringify(d)===JSON.stringify(kind.decisions.find((n:any)=>n.goalId===d.goalId)))})
const qa=read(resolve(own,'candidate/visualization-qa.original-input.json')),view=read(resolve(own,'candidate/review-view.original-input.json'))
const assetDigests:Record<string,string>={},assetBindings=[]
for(const r of qa.records){if(r.visualizationState!=='available')continue;const p=resolve(root,r.publicAssetPath),b=readFileSync(p);assetDigests[r.imageUrl]=sha(b);assetBindings.push(bind(p))}
write(resolve(own,'native/full-model-actual-asset-digests-at-use.json'),{role:'Actual inputs read to build pure native model; no renewed V judgments',assetDigests,assetBindings})
const config={schemaVersion:1,bookId:'chemie-b007-b014-current378-four-bounded-author-20261007-v1',title:'Chemie aktuelle kanonische Basis mit vier begrenzten Autorenkandidaten',landscapePath:relative(root,canonicalPath),compositionViewPath:relative(root,resolve(own,'candidate/review-view.original-input.json')),semanticKindLedgerPath:relative(root,resolve(own,'candidate/semantic-kinds.four-targets.inert-input.json')),goalVisualizationQaPath:relative(root,resolve(own,'candidate/visualization-qa.original-input.json')),publicationMode:'review',atlasBaseUrl:'https://skillpilot.com/lernzielbuch',evidenceReviewPaths:[],outputPath:relative(root,resolve(own,'native/full378.book-model.json'))}
write(resolve(own,'native/full378.book.config.json'),config)
const full=buildGoalBookModel({landscape:canonical,compositionView:view,semanticKindLedger:kind,goalVisualizationQa:qa,goalVisualizationAssetDigests:assetDigests,evidenceReviewSources:[],config} as any)
assert.equal(full.pages.length,378)
write(resolve(own,'native/full378.book-model.json'),full)
const ordered=full.pages.filter((p:any)=>ids.includes(p.goalId)).map((p:any)=>p.goalId)
assert.equal(ordered.length,4)
const model=buildGoalDescriptionRolloutSubsetModel({baseModel:full,goalIds:ordered,bookId:'chemie-b007-b014-four-bounded-native-author-20261007-v1',title:'Chemie: Kennzeichnungen, galvanische Elemente, Arrhenius und Brønsted'})
const modelPath=resolve(own,'native/four/book-model.json'),htmlPath=resolve(own,'native/four/book.html'),pdfPath=resolve(own,'native/four/book.pdf')
write(modelPath,model)
const publicRoot=resolve(own,'native/public')
for(const id of ids){const goal=by.get(id);for(const link of goal.resourceLinks??[]){if(link.type!=='goal-visualization')continue;const p=resolve(publicRoot,link.url.replace(/^\//,''));mkdirSync(dirname(p),{recursive:true});writeFileSync(p,readFileSync(resolve(own,'selected-existing-images',link.url.split('/').at(-1))))}}
const renderOptions={feedbackBaseUrl:'https://skillpilot.com/lernziel-feedback',publicRoot,printDerivativeProfile:'bounded-atlas' as const}
await writeGoalBookRenderManifest(await writeGoalBookHtml(model,htmlPath,renderOptions),htmlPath+'.render-manifest.json')
await writeGoalBookRenderManifest(await writeGoalBookPdf(model,pdfPath,renderOptions),pdfPath+'.render-manifest.json')
const promptPath=resolve(root,'curricula/DE/Gymnasium/quality/goal-evidence/prompts/goal-description-understanding-evidence-review-v2.md'),criteriaPath=resolve(root,'curricula/DE/Gymnasium/quality/goal-evidence/prompts/chemistry-goal-description-understanding-evidence-review-criteria-v1.md'),bundleDirectory=resolve(own,'native/four/bundle')
const bundle=await buildGoalBookReviewBundle(model,{modelPath,pdfPath,pdfRenderManifestPath:pdfPath+'.render-manifest.json',htmlPath,htmlRenderManifestPath:htmlPath+'.render-manifest.json',outputDirectory:bundleDirectory,promptPath,criteriaPath,goalIds:ordered})
for(const f of bundle.files){const p=resolve(bundleDirectory,f.relativePath);mkdirSync(dirname(p),{recursive:true});writeFileSync(p,f.content)}
write(resolve(bundleDirectory,'review-bundle-manifest.json'),bundle.manifest)
const verified=await verifyGoalBookReviewBundleArtifactBytes(bundle.manifest,bundleDirectory),nativeInput=buildGoalDescriptionReviewInput({bundle:bundle.manifest,reviewInput:bundle.input,landscape:canonical}),schemaBytes=await loadGoalDescriptionReviewRecordSchemaBytes(),recordSchemaDigest=sha(schemaBytes),campaignRows=[]
for(const side of ['a','b']){
 const out=resolve(own,'native/four/round-'+side),campaign=buildGoalDescriptionReviewCampaign({bundle:bundle.manifest,input:nativeInput,campaignId:'chemie-b007-b014-four-bounded-native-author-20261007-v1',roundId:'chemie-b007-b014-four-current-independent-'+side+'-20261007-v1',reviewerRole:'internal_ai_reviewer',reviewPass:'first_pass',independenceGroupId:'chemie-b007-b014-four-current-independent-'+side+'-20261007-v1',blindToOtherReviews:true,recordSchemaDigest,batchSize:4})
 const checked=await validateGoalDescriptionReviewCampaign({bundle:bundle.manifest,input:nativeInput,campaign});assert.deepEqual(checked.errors,[])
 write(resolve(out,'description-review-campaign.json'),campaign);write(resolve(out,'description-review-input.json'),nativeInput);write(resolve(out,'review-bundle-manifest.json'),bundle.manifest)
 mkdirSync(dirname(resolve(out,GOAL_DESCRIPTION_REVIEW_RECORD_SCHEMA_ARTIFACT_PATH)),{recursive:true});writeFileSync(resolve(out,GOAL_DESCRIPTION_REVIEW_RECORD_SCHEMA_ARTIFACT_PATH),schemaBytes)
 await writeVerifiedGoalDescriptionReviewCampaignGuidanceArtifacts({bundle:bundle.manifest,campaignDirectory:out,verifiedArtifactBytes:verified})
 for(const b of campaign.batches)write(resolve(out,'batches',b.batchId+'.input.jsonl'),serializeGoalDescriptionReviewBatchInput({bundleFingerprint:bundle.manifest.bundleFingerprint,bookDigest:bundle.manifest.bookModelDigest,reviewInputFingerprint:nativeInput.reviewInputFingerprint,inputSchemaVersion:nativeInput.schemaVersion,recordSchemaDigest:campaign.recordSchemaDigest,batchId:b.batchId,goalIds:b.goalIds,goals:nativeInput.goals}))
 campaignRows.push({side,errors:checked.errors,goalCount:4,independenceGroupId:campaign.independenceGroupId,authorReviewRecords:0,authorRunManifests:0})
}
write(resolve(own,'native/four/native-campaign-and-render.actual.validation.json'),{role:'Actual native candidate rendering/bundle/two blind campaign checks; no author D review records',pureFullModelPages:378,selectedPages:4,physicalPDFGoalPages:[3,4,5,6],campaignRows,errors:[],strictGain:0})

const caseRows=read(resolve(own,'materials/eight-complete-DE-EN-native-P-case-materials.author.json')).cases,prototype=read(resolve(own,'materials/label-prototype-existing-reviewed-whole-understanding.json')),records=[],pErrors:string[]=[]
const expectation=(id:string,de:string,en:string,pde:string,pen:string)=>({id,essentialUnderstandingDe:de,essentialUnderstandingEn:en,observablePerformanceDe:pde,observablePerformanceEn:pen})
const essentials:Record<string,any[]>={
 [ids[0]]:[expectation('label-with-bounded-information',prototype.positiveUnderstandingAuthorCandidate.essentialUnderstandingDe,prototype.positiveUnderstandingAuthorCandidate.essentialUnderstandingEn,prototype.positiveUnderstandingAuthorCandidate.observablePerformanceDe,prototype.positiveUnderstandingAuthorCandidate.observablePerformanceEn)],
 [ids[1]]:[expectation('one-connected-cell-mechanism','Oxidation und Reduktion an getrennten Elektroden treiben äußere Elektronenbewegung; innere Ionenbewegung ermöglicht Ladungsausgleich und dauerhaften Strom. Pole und Richtung folgen der tatsächlichen Reaktion.','Oxidation and reduction at separated electrodes drive external electron flow; internal ion flow balances charge and enables sustained current. Polarity and direction follow the actual reaction.','Die Person formuliert beide Elektrodenreaktionen, bilanziert Elektronen und begründet Anode/Kathode, Pole, Elektronen- und Brückenionenweg einschließlich eines unterbrochenen Ionenwegs.','The learner writes both electrode reactions, balances electrons and justifies electrode roles, signs, electron/bridge-ion paths and an interrupted ionic connection.'),expectation('qualitative-voltage-from-conditions','Zellspannung ist eine Differenz der Elektrodenpotenziale unter den gegebenen Bedingungen; räumliches Vertauschen ändert keine chemische Rolle und gleiche Halbzellen bei gleichen Bedingungen liefern keine Potenzialdifferenz.','Cell voltage is a difference of electrode potentials under the given conditions; exchanging locations does not change chemical roles, and identical half-cells under identical conditions have no potential difference.','Die Person erklärt die Spannung aus ungleichen Potenzialen und Grenzen der gegebenen Daten, ohne Zahlen oder dauerhaften Strom aus einer bloßen Anzeige zu behaupten.','The learner explains voltage from unequal potentials and the limits of given data without inventing a numerical value or inferring sustained current from a reading.')],
 [ids[2]]:[expectation('names-formulas-and-aqueous-species','Namen und Formeln der neun ausgewählten Säuren/Hydroxide unterstützen das Arrhenius-Teilchenmodell: Säuren erhöhen H3O+, gelöste Hydroxide erhöhen OH− in Wasser. Stoffformel und Lösungsname beschreiben nicht dieselbe Ebene oder sämtliche Lösungsteilchen.','Names and formulas of the nine selected acids/hydroxides support the Arrhenius species model: acids increase H3O+ and dissolved hydroxides increase OH− in water. Substance formulas and solution names describe different levels and do not enumerate all solution species.','Die Person ordnet fünf Säure- und vier Hydroxidnamen/Formeln sowie die Lösungsnamen richtig zu und erklärt wässrige Ionenbildung, Stoff/Lösung und die Grenze vollständiger Dissoziationsannahmen.','The learner correctly associates five acid and four hydroxide names/formulas and solution names and explains aqueous ions, substance/solution distinction and limits of complete-dissociation assumptions.')],
 [ids[3]]:[expectation('proton-transfer-species-model','Brønsted-Säure und -Base sind Rollen eines Teilchens als Protonendonator bzw. -akzeptor. Korrespondierende Paare unterscheiden sich um ein Proton; Wasser und geeignete andere Teilchen können je nach Schritt beide Rollen annehmen. Lösungen sind Gemische mehrerer Teilchenarten.','Brønsted acid/base are species roles as proton donor/acceptor. Conjugate pairs differ by one proton; water and suitable other species may take either role depending on the step. Solutions are mixtures of multiple species.','Die Person formuliert neue Protolysegleichungen, markiert den Protonenweg, ordnet beide Paare und Wasser als Ampholyt zu, prüft Ladungs-/Atomerhaltung und trennt Teilchenrollen von der ganzen Lösung.','The learner writes fresh protolysis equations, marks proton transfer, identifies both conjugate pairs and water as an ampholyte, checks atom/charge balance and distinguishes species roles from the entire solution.')]
}
const resourceDigests:Record<string,string>={};for(const id of ids)for(const link of by.get(id).resourceLinks??[])if(link.type==='goal-visualization')resourceDigests[link.url]=sha(readFileSync(resolve(own,'selected-existing-images',link.url.split('/').at(-1))))
const ajv=new Ajv2020({allErrors:true,strict:true});addFormats(ajv);const profileSchemaPath=resolve(root,'contracts/goal-evidence/v2/goal-evidence-profile.schema.json'),validate=ajv.compile(read(profileSchemaPath))
for(const id of ids){const goal=by.get(id),expectations=essentials[id],cases=caseRows.filter((c:any)=>c.goalId===id).map(({goalId,authorStatus,syntheticMaterial,actualLearnerPerformance,humanApproval,...c}:any)=>c),profile={archetype:id===ids[0]?'representation':'concept',expectations,coverageExpectations:{requiredExpectationIds:expectations.map((e:any)=>e.id),alternativeExpectationGroups:[],minimumIndependentDemonstrations:2,freshVariationRequired:true,independentTransferRequired:true},variationAxes:[{id:'fresh-material-and-boundaries',textDe:'Neue konkrete Stoffe, Angaben, Rollen oder unvollständige Informationen variieren; Antworten an die bereitgestellten Daten binden und die abgefragte Verständnisroutine vollständig zeigen.',textEn:'Vary concrete substances, information, roles or incomplete evidence; ground answers in supplied data and demonstrate the complete understanding routine.'}],applicationCaseBriefs:cases}
 const criteriaFingerprint=sha(readFileSync(criteriaPath)),record={$schema:POSITIVE_GOAL_EVIDENCE_SCHEMA_URL,schemaVersion:2,reviewId:'chemie-b007-b014-four-bounded-author-20261007-v1',goalFingerprintRuleVersion:'goal-evidence-v1',profileRuleVersion:'positive-understanding-evidence-v2',reviewCriteriaFingerprint:criteriaFingerprint,landscapeId:canonical.landscapeId,goalId:id,goalFingerprint:fingerprintGoalForPositiveEvidence(goal,'curricularAtomic'),reviewInputFingerprint:fingerprintPositiveGoalEvidenceReviewInput(goal,criteriaFingerprint,resourceDigests,'curricularAtomic'),profileFingerprint:fingerprintPositiveGoalEvidenceProfile(profile as any),status:'needs_human_review',reviewAuthority:'ai_candidate',reviewedAt:new Date().toISOString(),reviewer:'Codex AUTHOR; no independent approval',reason:'Whole bounded goal and two complete DE/EN material cases, exact selected existing raster, and current source/prerequisite context bound. Prior valid source/material science is preserved; final independent current D/P review remains pending.',evidenceLevel:'E1',maximumClaimScope:'G1',reviewRunIds:[],dissent:['Whole-country/source original obligations and companion duties remain open.',...(id===ids[2]?['Arrhenius requires separately adopting and checking its exact already-reviewed memory support; author preparation does not activate it.']:[])],profile}
 pErrors.push(...validatePositiveGoalEvidenceRecordSemantics(record as any,goal,resourceDigests,'curricularAtomic'));if(!validate(record))pErrors.push(...(validate.errors??[]).map((e:any)=>JSON.stringify(e)));records.push(record)
}
assert.deepEqual(pErrors,[])
write(resolve(own,'native/positive-four.current-author-candidate.jsonl'),records.map(r=>JSON.stringify(r)).join('\n')+'\n')
write(resolve(own,'native/positive-four.actual-resource-binding.validation.json'),{role:'Native record schema and actual selected image semantic binding, no own scientific approval',records:4,cases:8,errors:pErrors,resourceDigests,schema:bind(profileSchemaPath),status:'needs_human_review',reviewAuthority:'ai_candidate',evidenceLevel:'E1',maximumClaimScope:'G1',reviewRunIds:[],strictGain:0})
write(resolve(own,'four-current-whole-native-D-and-P-review.author.raw.json'),{role:'Neutral complete author review input; four review-ready bounded current479 proposals, five whole-goal holds retained separately',targetGoalIds:ids,prerequisiteSafeNativeOrder:ordered,wholeGoals:ids.map(id=>({goalId:id,wholeCurrentGoal:selection.currentWholeGoalsDEEN.find((g:any)=>g.id===id),wholeCandidateGoal:by.get(id),nativeWholeDInput:nativeInput.goals.find((g:any)=>g.goalId===id),nativeWholePAuthorCandidate:records.find(r=>r.goalId===id)})),sourceBoundaries:read(resolve(own,'source/four-bounded-existing-source-rows-and-original-partner-duties.author.json')),actualImagesAndAuthorKEEPIntents:read(resolve(own,'visualization/nine-exact-existing-assets-and-four-actual-author-KEEP-intents.raw.json')),actualPDF:'native/four/book.pdf',actualHTML:'native/four/book.html',humanApproval:false,independentApproval:false,strictGain:0})
console.log(JSON.stringify({pureNativePages:378,nativeDReadyGoals:ordered,nativeCampaignErrors:0,authorNativeReviewRecords:0,nativePErrors:0,cases:8,actualSelectedImageBindings:4,strictGain:0}))
