import { createHash } from 'node:crypto'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { Patches,base,canonicalPath,landscapeId,children,exams,localIds,parentH,parentE,successor,existingExam } from './prepare-core.mjs'
async function main(){
const {fingerprintSemanticKindSourceGoal}=await import(pathToFileURL(resolve('app/scripts/goalBookModel.ts')).href)
const p=new Patches(),now=new Date().toISOString(),reviewer='codex-informed-astro-consolidation-20260908'
const c=p.json(canonicalPath),byId=new Map<string,any>(c.goals.map((g:any)=>[g.id,g]))
const reasons=[
  ['Die eine Inferenz bestimmt den Sternradius aus den zwei HRD-Koordinaten mit einem thermischen Strahlungsmodell. Gleich-Leuchtkraft- und Gleich-Temperatur-Vergleiche prüfen dieselbe Flächen-/Temperaturdeutung; weder eine zweite Temperaturbestimmung noch Sternentwicklung wird separat verlangt.','Das Verhältnis von strahlender Fläche, Temperatur und Leistung wird aus bereitgestellten Modellbeziehungen verstanden und begründet. Eine zusätzliche isolierte Abrufkarte ist für genau diese Radiusinferenz nicht notwendig.'],
  ['Die eine kalibrierte Entfernungsinferenz verbindet eine begründete HRD-Klassifikation mit beobachtetem Fluss. Falsche Leuchtkraftklasse und Absorption sind Fehlerfälle desselben Schlusses. Das allgemeine Abstandsgesetz wird als bestehende Kompetenz genutzt, nicht dupliziert.','Die entscheidende Leistung ist die Auswahl der Leuchtkraftklasse und die Identifizierbarkeit unter Absorption; Formelabruf allein würde sie nicht tragen. Keine neue notwendige Memorykarte.'],
  ['Energiebudget, Masse-Leuchtkraft-Beziehung und mittlere Leistung bilden eine zusammenhängende Abschätzung genau einer Hauptreihenzeit. Die Beziehung ist Werkzeug im Lebensdauermodell, kein unabhängiges weiteres Ziel; Massenbereich und Hauptreihenphase begrenzen denselben Schluss.','Ein universeller Exponent wäre fachlich falsch. Die Modellbeziehung und der nutzbare Brennstoffanteil werden explizit bereitgestellt; begründete Skalierung und Grenzprüfung benötigen keine zusätzliche Auswendiglernkarte.'],
  ['Wiederkehrende Sternlicht-Abschwächung wird durch genau ein Transitmodell erklärt. Die Sichtgeometrie entscheidet über die Anwendbarkeit dieses Nachweises und ist keine eigenständige Nachweismethode.','Das Verständnis von Verdeckung, Sternlicht und Beobachtungsrichtung muss an frischen Kurven/Geometrien gezeigt werden. Ein Methodenname als Abrufkarte fügt keine notwendige Beherrschensbedingung hinzu.'],
  ['Die periodische Verschiebung von Sternlinien wird durch die Bewegung desselben Sterns um den gemeinsamen Schwerpunkt erklärt. Richtung und indirekte Aussagegrenze gehören zu einem Kausalmodell; quantitative Dopplergeschwindigkeiten und Planeteneigenschaften sind bewusst nicht Teil des Atoms.','Der Körperbezug und die Kausalkette sind die notwendige Leistung, nicht ein isolierter Formelabruf. Keine zusätzliche Karte zur ohnehin separat existierenden quantitativen Dopplerkompetenz.'],
  ['Die pp-Reaktionsfolge und ihr Energiegewinn beschreiben denselben solaren Umwandlungsprozess. Die präzisierte Ruhemassenbilanz verhindert Energieerzeugung aus dem Nichts und Zerfall als Fehlmodell; sie fügt keine zweite unabhängige Kernreaktionsroutine hinzu.','Gegebene Reaktionsschritte und eine bereitgestellte Massendifferenz reichen für den geforderten Zusammenhang. Das Ziel verlangt keine separate Pflicht zum Auswendiglernen aller pp-Zwischenschritte; bestehende Kernphysik-Karten bleiben unberührt.'],
  ['Entfernung oder Leuchtkraft sind gesuchte Größen derselben modellgestützten Beobachtungsinferenz. Die explizit benötigte Zusatzinformation begrenzt diesen Schluss; keine Pflicht zu mehreren eigenständigen astronomischen Methoden wird ergänzt.','Datenart, Kalibrierung und Modellannahmen müssen erkannt werden. Die begründete Auswahl lässt sich nicht durch eine zusätzliche Standardkarte ersetzen; vorhandene Methoden-/Formelkompetenzen werden nicht dupliziert.'],
  ['Aus der Bahn eines tatsächlich die Sonne umlaufenden Körpers wird mit genau einem Newton-Kepler-Modell die Sonnenmasse abgeschätzt. Die Zentralobjektbindung und große Halbachse konkretisieren denselben Modellgebrauch; keine allgemeine Doppelsternmassenbestimmung wird verlangt.','Die bereits bereitgestellte Newton-Kepler-Beziehung wird an Planet und exzentrischem Sonnenkometen ausgewählt und interpretiert. Neue Pflichtkarten für Fremdzentralkörper oder allgemeine Doppelsternmodelle wären außerhalb des Ziels.'],
  ['Die zwei Sterntypen sind Vergleichsfälle einer einzelnen massenabhängigen Entwicklungsbeschreibung. Typische Wege und mögliche Endzustände werden qualitativ eingeordnet; weder quantitative Hauptreihenzeit noch ein lückenloser Kernreaktionskatalog wird hinzugefügt.','Begründete Lebenswege mit Gegenbeispielen sind wichtiger als eine auswendig gelernte universelle Entwicklungsreihe, die hier gerade falsch wäre. Keine zusätzliche notwendige Memorykarte.']
]
const ids=[...children.map(g=>g.id),...localIds],before:any[]=[]
const stable=(v:any):string=>Array.isArray(v)?`[${v.map(stable).join(',')}]`:v&&typeof v==='object'?`{${Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${stable(x)}`).join(',')}}`:JSON.stringify(v)
const norm=(v:any)=>String(v??'').normalize('NFKC').replace(/\s+/gu,' ').trim()
const fp=(g:any,ruleVersion:string)=>`sha256:${createHash('sha256').update(stable({ruleVersion,goalId:g.id,shortKey:g.shortKey??'',title:norm(g.title),titleEn:norm(g.titleEn),description:norm(g.description),descriptionEn:norm(g.descriptionEn),phase:norm(g.dimensionTags?.phase),area:norm(g.dimensionTags?.area),topicCode:norm(g.dimensionTags?.topicCode),nodeKind:norm(g.nodeKind)})).digest('hex')}`
for(const [lane,rule] of [['semantic-atomicity','semantic-atomicity-v1'],['memory-card-review','memory-card-review-v1']]){
  const path=`curricula/DE/Gymnasium/quality/${lane}/canonical-physics-full.review.jsonl`,records=p.text(path).trim().split('\n').map((v:string)=>JSON.parse(v));
  for(const parent of [parentH,parentE]){const old=records.find((r:any)=>r.goalId===parent);if(old){before.push({lane,record:old,disposition:'retained in this audit; parent is now a cluster outside content-leaf review'});p.replace(path,JSON.stringify(old)+'\n','')}}
  for(const [i,id] of ids.entries()){const g=byId.get(id),old=records.find((r:any)=>r.goalId===id);if(old?.status==='memory_required')throw Error('Do not overwrite necessary memory decision');const next={schemaVersion:1,reviewId:'canonical-physics-full',ruleVersion:rule,landscapeId,goalId:id,fingerprint:fp(g,rule),...(lane==='semantic-atomicity'?{status:'atomic',semanticAtomic:true}:{status:'no_memory_needed',memoryUseful:false}),reviewedAt:now,reviewer,reason:`Informierte individuelle AI-Autorenprüfung E1/G1; keine Blindrunde oder Humanfreigabe. ${reasons[i][lane==='semantic-atomicity'?0:1]}`,...(lane==='semantic-atomicity'?{suggestedSplit:[]}:{})};if(old){before.push({lane,record:old});p.replace(path,JSON.stringify(old),JSON.stringify(next))}else{const last=p.text(path).trimEnd().split('\n').at(-1);p.replace(path,last,last+'\n'+JSON.stringify(next))}}
}
const kpath='curricula/DE/Gymnasium/quality/release-model/physik.semantic-kinds.json',k=p.json(kpath)
const touched=[...ids,parentH,parentE,...exams.map(g=>g.id),successor,existingExam,'85bbad98-2f48-5d64-85c4-ab6cf67f24c2']
for(const id of touched){const g=byId.get(id),kind=g.examData||id==='85bbad98-2f48-5d64-85c4-ab6cf67f24c2'?'practiceAssessment':g.contains?.length?'curricularArea':'curricularAtomic';const old=k.decisions.find((d:any)=>d.goalId===id);const next={...(old||{goalId:id}),semanticKind:kind,sourceFingerprint:fingerprintSemanticKindSourceGoal(g),decisionStatus:'authoritative',decisionBasis:kind==='practiceAssessment'?'reviewed-current-post-split-practice-assessment':kind==='curricularArea'?'reviewed-current-post-split-curricular-area':'reviewed-current-post-split-curricular-atomic'};if(old){before.push({lane:'semantic-kind',record:old});p.object(kpath,old,[next]);Object.assign(old,next)}else{const last=k.decisions.at(-1);p.object(kpath,last,[last,next]);k.decisions.push(next)}}
const counts={...k.counts};for(const key of Object.keys(counts))counts[key]=key==='total'?k.decisions.length:k.decisions.filter((d:any)=>d.semanticKind===key).length;const countsField=(v:any)=>'"counts": '+JSON.stringify(v,null,2).replace(/\n/g,'\n  ');p.replace(kpath,countsField(k.counts),countsField(counts))
const manifest='app/scripts/config/goal-books/de-gym-physics-national-atlas.sources.json',m=p.json(manifest);p.replace(manifest,`"expectedCurricularAtomicGoalCount": ${m.expectedCurricularAtomicGoalCount}`,`"expectedCurricularAtomicGoalCount": ${counts.curricularAtomic}`)
p.add(`${base}/am-k-informed-receipt.json`,JSON.stringify({reviewedAt:now,reviewer,authorship:'informed-ai-E1-G1-not-blind-no-human-approval',technicalSemanticKindStatus:'authoritative is the native ontology enum; it does not claim human approval of descriptions, profiles or images',individualJudgments:ids.map((id,i)=>({goalId:id,atomicity:reasons[i][0],memory:reasons[i][1]})),before,touchedGoalIds:touched,counts},null,2)+'\n')
console.log(JSON.stringify(p.patches))
}
void main()
