import json,hashlib,datetime
from pathlib import Path
BASE=Path('curricula/DE/Gymnasium/quality/goal-evidence/2026-10-09');A=BASE/'chemie-b008-current-twenty-six-native-preparation-author-v1/atomicity-memory-author';O=BASE/'chemie-b008-current-twenty-five-whole-atomicity-memory-independent-b-v1'
def bind(p):p=Path(p);return {'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}
def write(n,v):p=O/n;p.open('x').write(json.dumps(v,ensure_ascii=False,indent=2)+'\n');return bind(p)
def value(v):return hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
# These are independently written reasons from actual whole goal DE/EN reading. Author proposed fields are not read.
reasons={
'75e2eff1':('Eine eigene chemische Frage mit prüfbarer begründeter Hypothese und erwartbarem Für-/Gegenbefund bildet eine zusammengehörige Hypothesenformulierung. Frage, Begründung und Prüflichkeit beurteilen denselben Untersuchungsansatz.','Erfolg zeigt sich durch das Formulieren und Begründen am neuen beobachtbaren Phänomen. Ein auswendig gelernter Hypothesensatz liefert diese Leistung nicht; chemische Begriffe des Beispiels können als Grundlagen getrennt unterstützt werden.'),
'503dedcb':('Die theoriegestützte Ableitung einer eigenen Frage/Hypothese samt Vorhersage und Gegenbefund ist eine epistemisch zusammengehörige Formulierungsroutine. Geeignete Konzepte begründen genau diese Hypothese.','Erforderlich ist die begründete Anwendung geeigneter Theorie auf eine Situation. Die konkrete Theorie ist fachliche Grundlage; eine zusätzliche Prozesskarte ersetzt die eigene Herleitung nicht.'),
'e81a4aed':('Sicheres angeleitetes Durchführen, Befolgen von Einflussgrößen/Arbeitsschritten und ein verständlicher Versuchseintrag mit Hypothesenbezug sind ein überprüfbares angeleitetes Untersuchungshandeln. Dokumentation macht dieses Handeln nachvollziehbar.','Eine vorgegebene Versuchsanleitung wird tatsächlich sicher ausgeführt und die eigenen Beobachtungen werden erklärt. Diese performative Leistung verlangt keine weitere isolierte Memorykarte; Gefahrstoff- und Symbolgrundlagen behalten ihre getrennten bestehenden Karten.'),
'42391b16':('Eigenständige Planung und Durchführung mit Variablen, Vergleich, sicheren Techniken und tatsächlichem Protokoll sind ein eigener Untersuchungszyklus. Qualitativ und quantitativ sind verpflichtende Varianten desselben Hypothesenprüfens und bleiben vollständig erhalten.','Planungsentscheidungen, tatsächliche Durchführung und eigener Versuchseintrag müssen situationsgerecht entstehen. Eine gelernte Schritteliste wäre unzureichend; vorhandene Sicherheits- und Mengenbegriffe bleiben separat unterstützt.'),
'f79f15c0':('Überwiegend selbstständiges Planen, Analysenmethodenwahl, sicheres tatsächliches Durchführen und Protokollieren bilden einen anspruchsvolleren experimentellen Hypothesenprüfzyklus. Alle qualitativen/quantitativen Varianten gehören zur gemeinsamen Untersuchungsleistung.','Die Leistung liegt im begründeten Methodenentscheid und tatsächlich ausgeführten Versuch. Formeln, Gerätesicherheit und Stoffeigenschaften können als jeweilige Grundlagen abrufbar sein; dieser ganze Prozess braucht keine eigene zusätzliche Memorykarte.'),
'9fc800d1':('Struktur, Größen/Einheiten, Herkunft, Bedingungen und Beobachtung/Deutung sind Qualitätsmerkmale eines nachvollziehbaren chemischen Datenprotokolls. Eigene und recherchierte Daten sind unterschiedliche Herkunftsvarianten dieser Dokumentationskompetenz.','Gefordert ist ein korrektes konkretes Datenartefakt mit transparenter Herkunft. Das lässt sich mit Hilfsmitteln erstellen; das Memorieren einer Protokollrubrik belegt keine Dokumentation.'),
'7d9fcc7f':('Tabellen-/Diagrammauswertung, erläuterte Trends und begründeter Hypothesenbezug sind eine zusammengehörige Dateninterpretation. Darstellung und Schlussfolgerung beziehen sich auf denselben Datensatz.','Trends und Hypothesenstützung werden anhand tatsächlicher Daten begründet. Eine zusätzliche Faktenkarte ist dafür nicht erforderlich; Einheiten und relevante chemische Begriffe bleiben Grundlagen.'),
'9e3fae29':('Mathematische/digitale Verfahrenswahl, quantitative Analyse unter Bedingungen und fachübergreifend begründeter Hypothesenbefund bilden eine quantitative Auswertungsroutine. Digitale Anwendung und Schlussfolgerung sind deren überprüfbare Schritte.','Methoden müssen begründet ausgewählt und auf den gegebenen Datensatz angewandt werden. Passende Formeln dürfen aus vorhandener Fachgrundlage/Hilfsmitteln stammen; reine Formelreproduktion wäre kein Nachweis dieser Auswertung.'),
'4aa3a130':('Angemessenheit, Gültigkeit, Tragweite, Fehlerbegründung und zulässige Schlussfolgerungen gehören zu einer Beurteilung der Evidenz desselben chemischen Datensatzes. Es werden verschiedene Beurteilungsdimensionen einer Kompetenz geprüft.','Mess-/Verfahrensfehler und Grenzen sind aus den konkreten Bedingungen abzuleiten. Eine gelernte Fehlerliste wäre keine solche Beurteilung und erfordert hier kein eigenes Deck.'),
'a8800c36':('An einem gegebenen Erkenntnisweg erklärt die Person den Zusammenhang Frage–Methode–Beobachtung–Interpretation und dessen Reichweite. Zusammenwirken und Grenzen beurteilen denselben vorgelegten Erkenntnisprozess.','Die vorgelegte Untersuchungsbeschreibung trägt die Erklärung; die Schritte müssen kausal verbunden werden. Eine zusätzliche Prozesskarte ist nicht notwendig und kein Ersatz für die Erklärung des konkreten Falls.'),
'99d41b0f':('Eigene Ergebnisse, Ausgangsfrage/Hypothese, Methodenbegründung, Unsicherheiten und Verbesserungen sind eine Reflexion genau der eigenen Untersuchung. Die persönliche Herkunft bleibt Voraussetzung dieser Reflexionsleistung.','Die eigene Untersuchung liefert die erforderlichen Tatsachen. Memorykarten können keine eigenen Ergebnisse oder begründete Verbesserung erzeugen; kein zusätzliches Deck ist nötig.'),
'a0080b5f':('Die fünf genannten wissenschaftlichen Gültigkeitskriterien und die Trennung belastbarer Gegenbefunde von Verfahrens-/Messfehlern sind Kriterien einer einzigen begründeten Gültigkeitsreflexion. Die Aufzählung enthält keine fünf unabhängigen Inhaltsziele.','Begriffe wie Falsifizierbarkeit werden an einem tatsächlichen chemischen Erkenntnisprozess angewandt und dürfen erläutert vorliegen. Das reine Aufsagen von fünf Begriffen wäre kein Nachweis; eine eigene verpflichtende Prozesskarte ist nicht notwendig.'),
'5b1bb5d9':('Relevante Information auswählen, strukturieren, adressaten-/situationsgerecht auswerten und Quellen angeben ist eine quellengebundene Erschließungsroutine. Vorgegebene oder eigene Recherche verändert die Herkunft, nicht die zu beurteilende Kompetenz.','Die Information muss aus der tatsächlichen Quelle erschlossen werden. Quellenangaben und Darstellung stehen zur Verfügung; das Ziel verlangt keine unabhängige Faktenreproduktion.'),
'ac8b6c0f':('Eigenständige Recherche in analogen/digitalen Medien mit Auswahl, Strukturierung, Interpretation, Schlussfolgerung und belegtem Zitat ist eine vollständige wissenschaftliche Informationserschließung. Komplexe Darstellungen erhöhen den Anspruch derselben Routine.','Neue Quellen und ihre Aussagen müssen tatsächlich bearbeitet werden. Zitierhilfen und Methoden sind nutzbar; eine zusätzliche Karte über Rechercheabläufe ersetzt diese kompetente Quellenarbeit nicht.'),
'36666b4a':('Aussagen, Relevanz, Vertrauenswürdigkeit, Urheberschaft und Intention sind Dimensionen derselben vergleichenden Quellen-/Darstellungsprüfung für eine konkrete Frage. Das Urteil bezieht alle Merkmale auf gemeinsame Eignung/Gültigkeit.','Quellenmerkmale und Aussagen sind an den tatsächlichen Materialien zu prüfen. Auswendig gelernte Quellenautorität oder Kriterienlisten wären unzureichend; keine eigene Memorykarte ist erforderlich.'),
'431a0f03':('Kriterien, selbst gefundene belegte Pro-/Kontra-Argumente, Vergleich mit bereitgestellten Argumenten und Gewichtung sind eine begründete Argumentabwägung zu demselben Sachverhalt. Die Schritte dienen einem gemeinsamen begründeten Urteil.','Argumente und Belege müssen in ihrer tatsächlichen Situation gefunden und gewichtet werden. Ein memoriertes Argumentpaar liefert die Transferleistung nicht; kein zusätzliches Prozessdeck wird benötigt.'),
'7f140b34':('Beschreibung konkreter chemischer Aufgaben/Anwendungen und fachlich begründete Diskussion ihrer Bedeutung ist eine anwendungsbezogene Bedeutungsbeurteilung. Mensch, Gesellschaft und Umwelt sind zu beachtende Wirkungsdimensionen.','Der konkrete Anwendungsmechanismus und seine Folgen werden erklärt und diskutiert. Die Informationsgrundlage kann bereitstehen; die Leistung ist keine abfragbare Liste von Anwendungen und verlangt kein zusätzliches Deck.'),
'6c9adc36':('Vergleich chemischer Berufsfelder nach Aufgaben/Anforderungen und Einbeziehen ihrer Anwendung-/Entwicklungsbezüge in eine begründete Berufsorientierung oder Wahl ist eine fachlich begründete Berufsentscheidung. Das Ziel ist assessierbarer Inhalt; das Wort Berufsorientierung macht es nicht zu einem motivationalen Orientation-Anker.','Tätigkeiten und Anforderungen dürfen aus aktuellen Materialien entnommen werden und müssen begründet verglichen werden. Berufslisten zu memorieren ist weder erforderlich noch ein fachlicher Entscheidungsnachweis.'),
'1df17884':('Kriterienableitung, Chancen/Risiken, Handlungsoptionen, Entscheidungsstrategie und Überprüfung von Entscheidung/Kriterien/Strategie samt chemischer Reichweite bilden einen zusammengehörigen reflektierten Entscheidungszyklus. Die fünf Kriterienarten sind Urteilsdimensionen; kein Teil wird durch kurze Fälle entfernt.','Die Kriterien und Optionen müssen für eine neue chemisch relevante Entscheidung begründet gewichtet und überprüft werden. Ein auswendig gelernter Kriterienkatalog erzeugt diese Reflexion nicht; keine eigene Memorykarte ist nötig.'),
'e5a5dcd8':('Die soziale, kulturelle, technologische, historische, ökologische und ökonomische Beschreibung/Bewertung betrifft eine gemeinsame Frage nach Einfluss auf die Entwicklung chemischen Wissens. Die Abgrenzung zur empirischen Gültigkeit ist ein notwendiges Qualitätsmerkmal dieses Urteils.','Konkrete historische/aktuelle Belege können verfügbar sein und sind begründet zu verknüpfen. Die Namen der Einflussdimensionen auswendig aufzuzählen wäre unzureichend; keine zusätzliche Karte erforderlich. C11-Kurszuordnung bleibt gesondert offen.'),
'9f892457':('Historische/aktuelle chemische Auswirkungen aus ökologischer, ökonomischer und sozialer Perspektive inklusive eigenem Handeln zu bewerten ist eine Nachhaltigkeitsfolgenbeurteilung. Produkte/Methoden/Verfahren/Erkenntnisse sind vollständige Gegenstandsvarianten derselben Kompetenz.','Folgen und Handlungswirkungen werden an konkreten Daten/Belegen begründet. Memorierte Nachhaltigkeitsbegriffe liefern dieses Urteil nicht; die eigenen Lernkarten der zugrundeliegenden Inhalte bleiben unverändert.'),
'6c7ce93c':('Hypothesengeleitete Modellwahl/-nutzung, Aussagenvergleich mit Beobachtungen/Modellen, Grenzen und Weiterentwicklung bilden eine einzige kritische Modellierungsroutine. Materie, Reaktionen, Bindungen und Wechselwirkungen bleiben Gegenstandsvarianten; analoge oder digitale Wege bleiben erhalten.','Vorgelegte oder selbst benutzte Modelle müssen tatsächlich angewandt und kritisch verglichen werden. Merksätze über Modellgrenzen ersetzen dies nicht. Atombau-/Bindungsgrundlagen haben eigene bestehende Karten, aber dieses Modellhandeln braucht kein zusätzliches Deck.'),
'86d34f1f':('Theoriegestützte Wahl/Nutzung analoger und digitaler Modelle, Hypothesenprüfung und begründete Aussagekraft/Grenzen/Entwicklung sind eine zusammengehörige Modellbeurteilungsroutine. Alle genannten Gegenstände einschließlich Wirkstoff–Rezeptor und Substrat–Enzym bleiben volle Varianten. Zwei Fallbeispiele begrenzen diese Union nicht.','Geeignete Modellrepräsentationen und Theorien müssen in ihrem jeweiligen Kontext angewandt und verglichen werden. Das Ganze fordert keine reine Wiedergabe von Atom-/Geometrie-/Rezeptorbegriffen; bestehende fachliche Karten behalten ihre eigene Funktion, ein zusätzliches Prozessdeck ist nicht erforderlich.'),
'31781d00':('Sach-/adressaten-/situationsgerechte Transformation mit korrekter Fachsprache/Bezugsgrößen und begründeter Wahl sowie erhaltenen/begrenzten Aussagen ist eine qualitätsgesicherte Darstellungsüberführung. Alle Merkmale beurteilen denselben Informationswechsel.','Die tatsächlichen Informationen müssen in eine passende Darstellung überführt werden. Eine gelernte Darstellungsregel ist kein fertiges begründetes Produkt; kein zusätzliches Deck nötig.'),
'38e30bb9':('Eine fach-, adressaten- und situationsgerechte Präsentation chemischer Sachverhalte sowie eigener Ergebnisse mit begründeter Darstellung/Gliederung/analogen und digitalen Medien ist eine Präsentationskompetenz. Die eigenen Ergebnisse müssen wirklich vorliegen.','Die Leistung ist eine eigene konkrete Präsentation und begründete Medienwahl. Ein Kartenabruf der Präsentationsregeln wäre kein solcher Nachweis; kein zusätzliches Memorydeck nötig.')}
d=json.loads((A/'twenty-five-whole-semantic-atomicity.science-author-candidates.json').read_text());rows=[]
for i,r in enumerate(d['decisions']):
 g=r['wholeUnchangedScientificGoal'];ar,mr=reasons[g['id'][:8]];rows.append({'goalId':g['id'],'candidateKey':r['candidateKey'],'wholeDEENActuallyRead':True,'wholeGoalOriginalInput':d['originalWhole26Input'],'wholeGoalValueSHA256':value(g),'semanticKind':{'semanticKind':'curricularAtomic','ownScientificDecision':'KEEP_CONTENT_COMPETENCE','reason':ar,'technicalLeafOrTagAloneUsedAsProof':False},'atomicity':{'status':'atomic','semanticAtomic':True,'suggestedSplit':[],'ownWholeGoalReason':ar,'sourceUnionNarrowedByTwoExamples':False},'memory':{'status':'no_memory_needed','memoryUseful':False,'memoryGoalIds':[],'deckIds':[],'ownWholeGoalReason':mr,'existingOtherGoalCardsRemovedOrNewlyApproved':False},'wholeSourceStageCourseAndProtectedContextApproved':False,'actualLearnerPerformance':False,'humanApproval':False})
frame=BASE/'chemie-b008-current-twenty-six-native-preparation-author-v1/input/current-whole-source-partner-atomicity-memory-frame.neutral.json';f=json.loads(frame.read_text());g=json.loads(Path(f['futureWhole504CanonicalBinding']['path']).read_text());ids={r['goalId'] for r in rows};cards=[]
for goal in g['goals']:
 if any(t.startswith('srs-deck:') for t in goal.get('tags',[])):
  for field in ['vocabularySource','vocabularySourceEn']:
   src=goal.get('extendedData',{}).get(field)
   if src:
    p=Path('app/public')/src.lstrip('/') if src.startswith('/data/') else Path(src);deck=json.loads(p.read_text());cards.append({'memoryGoalId':goal['id'],'sourceBinding':bind(p),'deckId':deck['deckId'],'cardCount':len(deck['cards']),'actualFrontBackRead':True,'scientificKeptRemovalReviewsReusedUnchanged':True,'newCardApproval':False})
v={'schemaVersion':1,'reviewId':'chemie-b008-AM25-independent-b-first-v1','reviewer':'independent-b','reviewedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'role':'independent whole-goal semantic atomicity/memory review, distinct from own authored P19 materials','firstJudgmentImmutable':True,'neutralEntry':bind(A/'neutral-twenty-five-whole-A-M-science-author.entry.json'),'ownInputFirstSeal':bind(O/'twenty-five-whole-A-M.independent-b.input.first.freeze.json'),'all25GoalResults':rows,'actualBeforeFirstReading':{'wholeDEENGoals':25,'ordinaryAtomicityAndMemoryRules':True,'actualExistingPrimaryCardsFrontBackRead':73,'actualExistingENCardFrontBackRead':18,'actualCardOriginsIntersectingSelected25':0,'current504SemanticGoalFieldsExactlySameAsOriginalWhole25':True,'authorProposedStatusesRead':False,'authorProposedReasonsRead':False,'freshAMPeerReviewsRead':False,'own19PReReviewedAsIndependent':False},'actualExistingCardsReading':cards,'literalExisting1fReuseInput':bind(A/'one-existing-current-science-atomicity-memory.exact-reuse.input.json'),'literalExisting1fReReviewed':False,'actualVisibility':{'boundUnchangedSevenCurrentViews':f['actualUnmodifiedCurrentVisibilityScopes'],'requiredNewDecksFor25':0,'wholeCurrentVisibilityOrCardPipelinePassClaimedBeforeActualCLI':False,'ordinaryChecksWillFollowFirstJudgment'},'remainingHolds':['Whole Source354/395 and all source/course/stage placements remain separate','e5a C11 actual course unspecified remains separate','Eight protected177 context changes remain separate','Native D/P/V and actual laboratory/digital receipts remain separate','Current active integration and full source-based visibility validation remain separate'], 'authority':'ai_candidate','status':'needs_human_review','evidenceLevel':'E1','maximumClaimScope':'G1','strictGain':0,'newScientificClosures':0,'restoredBindings':0,'activeWrites':0,'humanApproval':False,'humanTrial':False}
vb=write('twenty-five-whole-A-M.independent-b.first-verdict.immutable.json',v);fb=write('twenty-five-whole-A-M.independent-b.first.freeze.json',{'schemaVersion':1,'role':'immutable own semantic first before author proposal comparison','createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':[vb,bind(O/'twenty-five-whole-A-M.independent-b.input.first.freeze.json'),bind(O/'seal-own-AM25-first.technical.py')],'actualCardReadBindings':cards,'authorProposedStatusesOrReasonsReadBeforeFirstSeal':False,'freshAMPeerReviewsReadBeforeFirstSeal':False,'humanApproval':False,'strictGain':0});print(json.dumps({'firstVerdict':vb,'firstSeal':fb}))
