"""Record the new actual one-page independent D-A review; no old D-record retagging."""
from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
root=Path.cwd();own=root/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-06/biologie-q1-carrier-hidden-continuity-native-d-independent-a-v3';author=root/'curricula/DE/Gymnasium/quality/goal-evidence/2026-10-06/biologie-q1-carrier-hidden-continuity-and-length-targeted-author-v3';id='ac9e824f-003c-50ac-8751-2b8456004c63'
assert not (own/'native-carrier-v5-d-p-independent-a.final.freeze.json').exists()
inputs={}
def raw(p):
 b=p.read_bytes();inputs[str(p.relative_to(root))]={'path':str(p.relative_to(root)),'sha256':'sha256:'+hashlib.sha256(b).hexdigest(),'bytes':len(b)};return b
def read(p):return json.loads(raw(p))
def write(n,v):(own/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def sha(b):return 'sha256:'+hashlib.sha256(b).hexdigest()
campaign=read(author/'round-a/description-review-campaign.json');data=read(author/'round-a/description-review-input.json');bundle=read(author/'bundle/manifest.json');assert read(author/'round-a/review-bundle-manifest.json')==bundle
assert data['bundleFingerprint']==bundle['bundleFingerprint']=='sha256:01ed284cc9512685b4078300739c4f1b5a6bbef1f5049a57a21b4c64c0e44451'
assert data['reviewInputFingerprint']=='sha256:afcb1e653bc78fb488844d36f2dc258906c817e095fb3fb5856b96e81cbacd3c';assert data['goalCount']==1
g=data['goals'][0];assert g['goalId']==id;page=g['reviewContext']['page'];assert page['visualization']['originalDigest']=='sha256:4e543bef5d79f11dc6866bdd7607f915e1343da5014881f0213b6e7bf8210ede'
for artifact in bundle['artifacts']:
 b=raw(author/'bundle'/artifact['path']);assert sha(b)==artifact['digest'] and len(b)==artifact['bytes']
for n in ['round-a/prompt.md','round-a/criteria.md','round-a/contracts/goal-description-review-record.schema.json','render/carrier.book.html','render/carrier.book.pdf']:raw(author/n)
batch=campaign['batches'][0];assert sha(raw(author/'round-a/batches'/(batch['batchId']+'.input.jsonl')))==batch['batchInputFingerprint']
assert [r['jurisdiction'] for r in page['applicability']]==['DE-BB','DE-BE']
for r in page['applicability']:assert r['scopes']==[{'stage':'SekI','durationModel':'G8','courseProfile':None},{'stage':'SekI','durationModel':'G9','courseProfile':None}]
assert len(page['externalReverseRequires'])==6 and not page['requires'];assert g['reviewContext']['evidenceProfile'] is None
html=read(own/'actual-final-carrier-html-browser-check.json');assert html['actualImageLoaded'] if 'actualImageLoaded' in html else html['actual']['imageLoaded'];assert html['titleDescriptionAltAndCurrentPNGExact']
source=read(own/'actual-current-native-source-and-six-view-roles.json');assert len(source['sixActualActiveViewRoleCompilations'])==6
p=read(own/'actual-one-positive-final-v5.verification.json');assert p['nativeActualCurrentOnePChecker']['status']=='PASS'
canonical=read(root/'curricula/DE/Gymnasium/canonical/DE_DEU_S_GYM_CANONICAL_BIOLOGIE.de.json');currentGoal=next(r for r in canonical['goals'] if r['id']==id);assert currentGoal==p['currentWholeGoal']
assets=[]
for path in [root/'app/public'/page['visualization']['url'].lstrip('/'),root/'backend/src/main/resources/static'/page['visualization']['url'].lstrip('/'),root/'curricula/DE/Gymnasium/visualizations/biologie'/id/(id+'.png')]:assert sha(raw(path))==page['visualization']['originalDigest'];assets.append(inputs[str(path.relative_to(root))])
before=read(author/'before.full-390.book-model.json');current=read(author/'current.full-390.book-model.json');assert len(before['pages'])==len(current['pages'])==390
oldPages={p['goalId']:p for p in before['pages']};changed=[p['goalId'] for p in current['pages'] if p!=oldPages[p['goalId']]];assert changed==[id]
fullPage=next(p for p in current['pages'] if p['goalId']==id);oldPage=oldPages[id];delta=[k for k,v in fullPage.items() if v!=oldPage.get(k)];assert sorted(delta)==['pageFingerprint','visualization']
assert {k:v for k,v in fullPage['visualization'].items() if k!='originalDigest'}=={k:v for k,v in oldPage['visualization'].items() if k!='originalDigest'}
parameters={'operation':'one-current-final-v5-native-D-A-targeted-continuation','exactRuntimeModelVersionAvailable':False,'exactSamplingSettingsAvailable':False,'temperature':None,'seed':None,'currentHTMLandPDFActuallyViewed':True,'newPeerDandPResultsRead':False,'activeWrites':False}
write('declared-runtime-parameter-availability.actual.json',parameters)
runid='biologie-carrier-hidden-continuity-v3-independent-a-run-001'
record={'$schema':'https://skillpilot.com/schemas/goal-description-review/v1/goal-description-review-record.schema.json','schemaVersion':1,'recordId':'bio-carrier-hidden-continuity-final-v5-d-a-'+id,'runId':runid,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'bundleFingerprint':data['bundleFingerprint'],'bookDigest':data['bookDigest'],'goalId':id,'goalFingerprint':g['goalFingerprint'],'pageFingerprint':g['pageFingerprint'],'currentTitleDe':g['currentTitleDe'],'currentTitleEn':g['currentTitleEn'],'currentDescriptionDe':g['currentDescriptionDe'],'currentDescriptionEn':g['currentDescriptionEn'],'decision':'keep','understandingEvidence':{
 'essentialUnderstandingDe':'DNA bezeichnet das Material der Erbinformation. Ein Gen ist ein Abschnitt dieses Materials, während das Chromosom dessen organisierte Trägerstruktur bezeichnet; Material, Abschnitt und Trägerstruktur sind miteinander verknüpfte Ebenen eines Modells.',
 'essentialUnderstandingEn':'DNA names the material of genetic information. A gene is a section of that material, while a chromosome is its organised carrier structure; material, section and carrier structure are linked levels of one model.',
 'observablePerformanceDe':'Die lernende Person erläutert am vorgegebenen Modell eigenständig, in welcher Beziehung Chromosom, DNA-Faden und markierter Genabschnitt stehen, und begründet, warum eine Abschnittsmarkierung keinen weiteren Träger hinzufügt und die Chromosomenzahl keine vollständige Genanzahl liefert.',
 'observablePerformanceEn':'Using the supplied model, the learner independently explains how the chromosome, DNA thread and marked gene section relate, justifying why marking a section adds no new carrier and chromosome number does not provide a complete gene count.',
 'transferExpectationDe':'In einem frisch vorgelegten Modell mit zwei vorgegebenen Chromosomen und veränderten Anleitungsvarianten an korrespondierenden DNA-Abschnitten wendet die lernende Person dieselbe Material-Abschnitt-Träger-Beziehung an und begründet, warum der Austausch einer Anleitung allein kein Chromosom hinzufügt. Eine zusätzliche Erbgangs- oder Genproduktkompetenz wird nicht verlangt.',
 'transferExpectationEn':'In a fresh supplied model with two chromosomes and changed instruction variants at corresponding DNA sections, the learner applies the same material-section-carrier relationship and justifies why replacing one instruction alone adds no chromosome. No additional inheritance-pattern or gene-product competence is required.'},
 'rationale':'KEEP nach tatsächlich neuer Sichtprüfung der unveränderten nativen HTML-Lernzielseite in Chromium und der original gerenderten PDF-Lernzielseite, physisch3. Das endgültige importierte v5-PNG zeigt zwei getrennte fortlaufende Rückgratkurven mit passenden verdeckten Tangenten und wechselnder Front/Back-Lage je Strang, verbindende Basenpaare, ein Stabchromosom mit klar innen liegendem Zoom und eine längere Gen-Klammer ohne Veränderung des markierten DNA-Materials. stark verkürzt ist in Bild und Seite lesbar; ungefähr1,6–1,7 vollständige Windungen sind ein symbolischer Ausschnitt, keine tatsächliche Genlänge oder behauptete zwei Windungen. Neuer Bildinhalt, korrekter aktueller Alttext, Beschreibung und Seitenkontext widersprechen einander nicht. Die drei importierten Assetkopien enthalten exakt die gesehenen v5-Bytes. Die gültigen früheren eigenen A-Fachtext-/Atomaritätsbefunde und beide vollständigen fiktiven Materialkarten sind unverändert weiterverwendet; kein Neustart der sechs anderen Ziele. Die tatsächliche390-Seiten-Modelldifferenz betrifft ausschließlich Bilddigest und Seitenfingerprint dieses Carrier-Ziels; andere389 ganze Seiten sind exakt erhalten. Direkte BE/BB-Komponenten einschließlich originaler Quelle3.7/physisch und gedruckt36 sind exakt unverändert und nur partial. Eine volle Zellteilungs-/Karyogramm-/Chemie-Quellenfreigabe wird nicht behauptet. Aktuelle native Quellenkompilation weist den Carrier ausschließlich BE/BB-SekI zu. Die sechs bereits integrierten MV/SN/TH-SekI und ST-SekII-GK/LK-Ansichten sind tatsächlich nativ kompiliert: Carrier nur prerequisiteOnly, nicht target; ST-SekI enthält ihn nicht. Die rohe kanonische Sechs-Länder-Liste ist kein zusätzlicher Quellenbeleg. GUI-Superset-, Lernenden- und Memory-Gates bleiben gesondert. evidenceProfile=null im konkreten D-Bundle begründet create ausschließlich hier; der separate aktuelle P1-Nachweis ist tatsächlich geprüft, ai_candidate/needs_human_review E1/G1. Die menschliche Problemmeldung und daraus qaStatus=rejected/approvedForPublication=false bleiben echte getrennte Releasegrenzen; maschineller KEEP ist keine menschliche Freigabe oder Erprobung. Neuer Record und Run sind aus den frischen Eingängen und der tatsächlichen Seite erstellt, kein bloßes Retagging des alten D-Records.',
 'evidenceProfileContract':'positive-understanding-evidence-v2','evidenceProfileRecommendation':'create','recordStatus':'candidate','reviewAuthority':'ai_candidate'}
recordPath=own/'results'/(batch['batchId']+'.records.jsonl');recordBytes=(json.dumps(record,ensure_ascii=False,separators=(',',':'))+'\n').encode();recordPath.write_bytes(recordBytes)
run={'$schema':'https://skillpilot.com/schemas/goal-evidence/v1/goal-evidence-ai-run-manifest.schema.json','schemaVersion':1,'runId':runid,'campaignId':campaign['campaignId'],'roundId':campaign['roundId'],'batchId':batch['batchId'],'batchInputFingerprint':batch['batchInputFingerprint'],'bundleFingerprint':data['bundleFingerprint'],'bookDigest':data['bookDigest'],'provider':'OpenAI','model':'Codex GPT-6; exact runtime variant not exposed','role':'subject_reviewer','promptFamilyId':'skillpilot-goal-description-understanding-evidence-v2','promptFingerprint':campaign['promptFingerprint'],'criteriaFingerprint':campaign['criteriaFingerprint'],'generationParametersFingerprint':sha((own/'declared-runtime-parameter-availability.actual.json').read_bytes()),'independenceGroupId':campaign['independenceGroupId'],'blindToOtherRuns':True,'goalIds':[id],'inputArtifacts':[{'role':a['role'],'digest':a['digest']} for a in bundle['artifacts']]+[{'role':'description_review_batch_input_jsonl','digest':batch['batchInputFingerprint']}],'startedAt':(own/'native-run-started-at.utc.txt').read_text().strip(),'completedAt':datetime.now(timezone.utc).isoformat(),'status':'completed','outputDigest':sha(recordBytes),'toolchainVersion':'skillpilot-goal-description-review-v2'}
(own/'results'/(batch['batchId']+'.run.json')).write_text(json.dumps(run,ensure_ascii=False,indent=2)+'\n')
write('actual-final-v5-one-page-and-context-independent-a.json',{'schemaVersion':1,'createdAtUTC':datetime.now(timezone.utc).isoformat(),'goalId':id,'decision':'KEEP','actualHTMLandPhysicalPDF3PersonallyRead':True,'freshNativePageFingerprint':g['pageFingerprint'],'full390CurrentCarrierPageFingerprint':fullPage['pageFingerprint'],'subsetAndFullDifferentFingerprintsBecauseExternalSuccessorBindings':True,'bundleFingerprint':data['bundleFingerprint'],'reviewInputFingerprint':data['reviewInputFingerprint'],'changedFullPageFields':delta,'other389WholePagesExactlyPreserved':True,'currentWholeGoalExactlyPreserved':True,'actual3PNGcopies':assets,'oldScienceAndTwoMaterialCaseBodiesExactlyPreserved':True,'directSourceAndActiveSixViewRoleReceipt':'actual-current-native-source-and-six-view-roles.json','fullGUISupersetAcceptance':'SEPARATE_REQUIRED_GATE_NOT_CLAIMED','humanPublicationQaStatus':page['visualization']['qaStatus'],'approvedForPublication':page['visualization']['approvedForPublication'],'fullOriginalSourceClearance':False,'peerNewDorPRead':False,'activeWrites':False,'strictNetGain':0,'newScientificCompletions':0,'restoredActiveBindingsByThisReviewer':0,'humanApproval':False,'humanTrial':False,'learnerEvidence':False})
for helper in ['AGENTS.md','app/scripts/validateGoalDescriptionReviewCampaign.ts','app/scripts/validateGoalDescriptionReviewCampaignResults.ts','app/scripts/validateGoalDescriptionDualRoundResolution.ts','app/scripts/goalBookModel.ts','app/scripts/positiveGoalEvidenceReview.ts']:raw(root/helper)
write('actual-native-d-bound-inputs.for-final-freeze.json',{'schemaVersion':1,'createdAtUTC':datetime.now(timezone.utc).isoformat(),'inputs':list(inputs.values()),'globalHistoricalInputEqualityClaimed':False})
print(json.dumps({'newNativeDA':'KEEP_ONE_ACTUAL_FINAL_PAGE','recordPath':str(recordPath.relative_to(root)),'other389WholePagesExact':True,'strictNetGain':0}))
