import assert from 'node:assert/strict'
import { readFileSync,writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { createHash } from 'node:crypto'
import { createRequire } from 'node:module'
const root=resolve('.'),base='curricula/DE/Gymnasium/quality/goal-evidence/2026-10-06/'
const own=base+'chemie-current-coordinate-final-native-review-inputs-author-v5',v3=base+'chemie-current-fifteen-final-native-review-inputs-author-v3'
const read=(p:string)=>JSON.parse(readFileSync(resolve(root,p),'utf8')),sha=(b:string|Buffer)=>'sha256:'+createHash('sha256').update(b).digest('hex'),bind=(p:string)=>({path:p,sha256:sha(readFileSync(resolve(root,p))),bytes:readFileSync(resolve(root,p)).length}),write=(p:string,v:any)=>writeFileSync(resolve(root,own,p),JSON.stringify(v,null,2)+'\n')
const arg=process.argv.indexOf('--visual-review-bindings');assert.ok(arg>=0,'Require final actual two independent visual freeze bindings');const vbindings=read(process.argv[arg+1])
assert.equal(vbindings.finalActualIndependentVisualFreezes.length,2)
for(const row of vbindings.finalActualIndependentVisualFreezes){assert.equal(bind(row.path).sha256,row.sha256);const f=read(row.path);for(const output of f.files??f.outputs??[]){const h=output.sha256.startsWith('sha256:')?output.sha256:'sha256:'+output.sha256;assert.equal(bind(output.path).sha256,h)}}
for(const n of ['native-d-four-stage-author-v5.final.freeze.json','native-d-one-stage-author-v5.final.freeze.json'])for(const f of read(own+'/'+n).files)assert.equal(bind(f.path).sha256,f.sha256)
const staging=read(own+'/actual-single-visual-resource-staging-and-bounded-delta.author.json'),isolatedRoot=staging.temporaryIsolatedRootUsed,gid=staging.goalId
const helperPaths=['app/scripts/materializePositiveGoalEvidenceCandidates.ts','app/scripts/positiveGoalEvidenceProfileModel.ts','app/scripts/positiveGoalEvidenceReview.ts'];for(const p of helperPaths)assert.equal(bind(p).sha256,sha(readFileSync(resolve(isolatedRoot,p))))
const {buildPositiveGoalEvidenceCandidateRecords}=await import(pathToFileURL(resolve(isolatedRoot,'app/scripts/materializePositiveGoalEvidenceCandidates.ts')).href)
const {reviewPositiveGoalEvidenceConfig}=await import(pathToFileURL(resolve(isolatedRoot,'app/scripts/positiveGoalEvidenceReview.ts')).href)
const {validatePositiveGoalEvidenceRecordSemantics}=await import(pathToFileURL(resolve(isolatedRoot,'app/scripts/positiveGoalEvidenceProfileModel.ts')).href)
const {stableGoalBookJson}=await import(pathToFileURL(resolve(isolatedRoot,'app/scripts/goalBookModel.ts')).href)
const config=read(own+'/positive-evidence.coordinate-one.native-author-candidate.config.json'),spec=read(own+'/positive-one-profile.exact-v2-science.author-candidate.json'),materials=read(own+'/two-complete-coordinate-materials.de-en.exact-v2.json')
assert.equal(spec.goals.length,1);assert.equal(materials.materials.length,2);assert.equal(materials.caseCount,2)
const oldSpecs=read(v3+'/fifteen-positive-profile-specifications.exact-v2.json'),oldMaterials=read(v3+'/thirty-complete-materials.de-en.exact-v2.json').materials
assert.deepEqual(spec.goals[0],oldSpecs.goals.find((s:any)=>s.goalId===gid));for(const c of materials.materials)assert.deepEqual(c,oldMaterials.find((m:any)=>m.caseId===c.caseId))
const record=(await buildPositiveGoalEvidenceCandidateRecords({config,candidateSet:spec}))[0];assert.equal(record.goalId,gid);assert.equal(record.status,'needs_human_review');assert.equal(record.reviewAuthority,'ai_candidate');assert.equal(record.evidenceLevel,'E1');assert.equal(record.maximumClaimScope,'G1');assert.deepEqual(record.reviewRunIds,[])
const req=createRequire(resolve(root,'app/package.json')),Ajv=req('ajv/dist/2020').default,formats=req('ajv-formats').default,ajv=new Ajv({strict:true,allErrors:true});formats(ajv)
const rs=ajv.compile(read('contracts/goal-evidence/v2/goal-evidence-profile.schema.json')),cs=ajv.compile(read('contracts/goal-evidence/v2/goal-evidence-review-config.schema.json'));assert.ok(rs(record),ajv.errorsText(rs.errors));assert.ok(cs(config),ajv.errorsText(cs.errors))
const goal=read(config.landscapePath).goals.find((g:any)=>g.id===gid),resources:Record<string,string>={};for(const l of goal.resourceLinks.filter((l:any)=>l.type==='goal-visualization'))resources[l.url]=sha(readFileSync(resolve(isolatedRoot,'app/public'+l.url)))
assert.equal(Object.values(resources)[0],staging.selectedActualRaster.sha256);assert.deepEqual(validatePositiveGoalEvidenceRecordSemantics(record,goal,resources,'curricularAtomic'),[])
const oldRecord=readFileSync(resolve(root,v3,'positive-evidence.fifteen.prospective.native-author-candidates.review.jsonl'),'utf8').trim().split('\n').map(l=>JSON.parse(l)).find(r=>r.goalId===gid)
assert.equal(record.goalFingerprint,oldRecord.goalFingerprint);assert.equal(record.profileFingerprint,oldRecord.profileFingerprint);assert.equal(record.reviewCriteriaFingerprint,oldRecord.reviewCriteriaFingerprint);assert.notEqual(record.reviewInputFingerprint,oldRecord.reviewInputFingerprint);assert.deepEqual(record.profile,oldRecord.profile)
for(const c of materials.materials){const b=record.profile.applicationCaseBriefs.find((b:any)=>b.id===c.caseId);assert.ok(b);for(const lang of ['de','en']){const s=lang[0].toUpperCase()+lang.slice(1);assert.equal(b['taskDemand'+s],c.material[lang]+' '+c.taskDemand[lang]);assert.equal(b['expectedPerformance'+s],c.expectedPerformance[lang]);assert.equal(b['understandingFocus'+s],c.specificBoundaryOrCounterexample[lang])}}
writeFileSync(resolve(root,config.reviewPath),JSON.stringify(record)+'\n')
const checked=reviewPositiveGoalEvidenceConfig(own+'/positive-evidence.coordinate-one.native-author-candidate.config.json');assert.deepEqual(checked.errors,[]);assert.deepEqual(checked.counts,{approved:0,needsHumanReview:1,rejected:0})
write('native-single-positive-schema-material-visual-binding-checks.actual.json',{schemaVersion:1,createdAtUTC:new Date().toISOString(),role:'AUTHOR actual isolated unchanged native full materializer/checker for one current candidate raster binding, not new independent P approval',goalId:gid,nativeMaterializer:'PASS1',nativeFullChecker:'PASS1',nativeErrors:checked.errors,nativeCounts:checked.counts,closedRecordAndConfigSchemas:'PASS',nativePureSemantics:'PASS',wholeScientificProfileBodyExactV3:true,twoWholeMaterialCasesExactV3:true,goalFingerprintExactV3:true,profileFingerprintExactV3:true,reviewCriteriaFingerprintExactV3:true,onlyReviewInputFingerprintChanged:true,beforeReviewInputFingerprint:oldRecord.reviewInputFingerprint,prospectiveReviewInputFingerprint:record.reviewInputFingerprint,goalFingerprint:record.goalFingerprint,profileFingerprint:record.profileFingerprint,reviewCriteriaFingerprint:record.reviewCriteriaFingerprint,actualResourceDigests:resources,selectedActualRaster:staging.selectedActualRaster,finalActualIndependentVisualFreezes:vbindings.finalActualIndependentVisualFreezes,nativeHelperBindings:helperPaths.map(bind),status:record.status,reviewAuthority:record.reviewAuthority,evidenceLevel:record.evidenceLevel,maximumClaimScope:record.maximumClaimScope,activeNativeResourceBinding:'PENDING_ACTIVE_INTEGRATION: selected PNG exists only in frozen v4 and temporary staged public root',nativeVApprovalIssued:false,nativeDApprovalIssued:false,nativePApprovalIssued:false,humanApproval:false,humanTrial:false,actualLearnerEvidence:false,activeWrites:false,strictNetGain:0,newScientificClosures:0,restoredActiveBindings:0})
console.log(JSON.stringify({nativeMaterializer:'PASS1',nativeFullChecker:'PASS1',closedSchemas:'PASS',profileAndTwoMaterialsExact:true,onlyPReviewInputFingerprintChanged:true,status:record.status,activeWrites:false,strictNetGain:0}))
